### ISSUE TITLE
how to give Virtual box of a list of candidate network interfaces for public bridged network?

### ISSUE THREAD

**Issue by liamz39** [hashicorp/vagrant#10008]
I want to make a Vagrantfile workable through multiple machines, each machine's network interfaces name are different, I looked at the official doc, which provides an example of this syntax:
```
config.vm.network "public_network", bridge: [
  "en1: Wi-Fi (AirPort)",
  "en6: Broadcom NetXtreme Gigabit Ethernet Controller",
]
```
https://www.vagrantup.com/docs/networking/public_network.html#default-network-interface

but when I run vagrant up, I get an error " Specific bridge '["en1: Wi-Fi (AirPort)", "en6: Broadcom NetXtreme Gigabit Ethernet Controller"]' not found", when en1 is actually one of my network interfaces, it looks like it's treating the entire list as a single network interface.

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information in this issue or in a new comment, thank you!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
