### ISSUE TITLE
"rpm -i" install vagrant failed

### ISSUE THREAD

**Issue by chunglam1999** [hashicorp/vagrant#10006]
### Vagrant version
2.1.1

### Host operating system
Centos 7

### Guest operating system
N/A

### Vagrantfile
N/A

# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
N/A

### Debug output
[root@lenovo-2]# rpm -i vagrant-2.1.1-1.el7.noarch.rpm
error: Failed dependencies:
        /usr/local/bin/ruby is needed by vagrant-2.1.1-1.el7.noarch
### Expected behavior
rpm -i should be successful

### Actual behavior
[root@lenovo-2]# rpm -i vagrant-2.1.1-1.el7.noarch.rpm
error: Failed dependencies:
        /usr/local/bin/ruby is needed by vagrant-2.1.1-1.el7.noarch

### Steps to reproduce
1. rpmbuild -ba SPECS/vagrant.spec
2. rpm -i vagrant-2.1.1-1.el7.noarch.rpm

### References
N/A
- ...

**Comment by briancain** [comment]
Hi @chunglam1999 - This repository does not include a `SPECS/vagrant.spec` file. If you wish to install Vagrant, check out the [downloads](https://www.vagrantup.com/downloads.html) page. Thanks.
