### ISSUE TITLE
Using NFS shared folders doesn't work properly when using a VoidLinux host

### ISSUE THREAD

**Issue by Aloz1** [hashicorp/vagrant#10011]
### Vagrant version
vagrant 2.1.2

### Host operating system
Void Linux

### Guest operating system
Alpine (but guest is irrelevant)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.define :pxeserver do |server|
    server.vm.provider :libvirt
    server.vm.box = "generic/alpine38"
    server.vm.synced_folder "server/tftp",
      "/srv/tftp",
      type: "nfs"
  end
end
```
Note, plugins vagrant-libvirt and vagrant-alpine are installed, but are not relevant as this is a host issue.

### Debug output
https://gist.github.com/Aloz1/66ae28001736d255ea895d06a667f63e
Relevant sections are lines 921 to 927

### Expected behavior
vagrant should have detected what the current status of NFS is.

### Actual behavior
vagrant failed because the command used to check the service is not correct. Void uses an init system called runit, additionally the service is under a different name. The correct command should be '/usr/bin/sv status nfs-server'.

### Steps to reproduce
1. Install voidlinux.
2. Install vagrant on top of voidlinux
3. Try running any Vagrantfile with nfs

**Comment by Aloz1** [comment]
PR is done. Could we please tag it as feedback/review?

**Comment by GoingFast** [comment]
hello?

**Comment by briancain** [comment]
Closing this, as the PR has been merged.
