### ISSUE TITLE
Vagrantfile loading is not disabled when running plugin commands

### ISSUE THREAD

**Issue by FlipABit** [hashicorp/vagrant#10013]
### Vagrant version
2.1.2

### Host operating system
macOS 10.12.6

### Guest operating system
Ubuntu 17.10

### Vagrantfile
```ruby
system "vagrant plugin install tty-prompt"

...

require "tty-prompt"
```

OR running the command from the terminal: `vagrant plugin install tty-prompt` from within you vagrant project directory.

### Debug output
Terminal output: https://gist.github.com/FlipABit/f5e335a51ced25c47bfffa0c6598e2b8

### Expected behavior
When running plugin commands other than "list", loading of the Vagrantfile should be disabled.

### Actual behavior
Loading of the Vagrantfile is no longer disabled when running any plugin command. As a result, plugins cannot be installed while working in the directory of the Vagrantfile which requires the plugin. Running the plugin install command will throw an error as a result of the plugin not being installed when the Vagrantfile is loaded.

### Steps to reproduce
1. Require a 3rd party plugin in your Vagrantfile. Make sure that plugin is not already installed on your system.
2. Run `vagrant plugin install <plugin name>` from the Vagrantfile directory.  
3. You should be presented with an error "There was an error loading a Vagrantfile" due to the plugin not being already installed.

### References
This was introduced in v2.1.2. The offending changeset is here: https://github.com/hashicorp/vagrant/commit/1bba1f86bbec387a9297ffd0b705783805b959df. Loading of the vagrant file used to be disabled via `opts[:vagrantfile_name] = ""` (line 41) for `plugin`, `help`, or `box list` command. It is now only disabled for the `box list` command.

Setting the environment variable `VAGRANT_VAGRANTFILE=""` and then running `vagrant plugin install <plugin name>` and then unsetting VAGRANT_VAGRANTFILE temporarily fixes the issue.

**Comment by scottsb** [comment]
As a workaround for now, you can place this at the top of your Vagrantfile:

    # Exit early in 2.1.2 due to bug: https://github.com/hashicorp/vagrant/issues/10013
    if ARGV[0] == "plugin"
      return
    end
