### ISSUE TITLE
vagrant-libvirt plugin build fails on openSUSE Leap 15

### ISSUE THREAD

**Issue by rtamalin** [hashicorp/vagrant#10019]
Similar to the issues reported in https://github.com/hashicorp/vagrant/issues/8986 when attempting to install the vagrant-libvirt plugin on openSUSE Leap 15 I get a failure related to problems with the embedded libreadline.so.7.

The workaround identified in GH-8986, with regard to renaming the offending embedded libreadline.so.X library, also resolves the problem in this case.

### Vagrant version
Vagrant versions 2.1.2 and 2.0.4

### Host operating system
This is the operating system that you run locally.

### Guest operating system
openSUSE Leap 15.0

### Debug output
Gist showing failing vagrant command and mkmf.log output: https://gist.github.com/rtamalin/ba87a0680f24e0d360f65d0d1239ce36

The important error information from the gist is the content of the mkmf.log file:
```
"gcc -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-linux -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I.  -I/opt/vagrant/embedded/include   -I/opt/vagrant/embedded/include -I/vagrant-substrate/cache/ruby-2.4.4/include -O3 -fPIC  conftest.c  -L. -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -Wl,-rpath=XORIGIN/../lib:/opt/vagrant/embedded/lib -fstack-protector -rdynamic -Wl,-export-dynamic -L/opt/vagrant/embedded/lib  -Wl,-rpath,/opt/vagrant/embedded/lib     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby  -lpthread -lrt -lgmp -ldl -lcrypt -lm   -lc "
sh: /opt/vagrant/embedded/lib/libreadline.so.7: no version information available (required by sh)
sh: symbol lookup error: /opt/vagrant/embedded/lib/libreadline.so.7: undefined symbol: PC
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

```

### Expected behavior
The vagrant-libvirt (version 0.0.43) plugin should have been successfully installed.

### Actual behavior
The plugin failed to install successfully

### Steps to reproduce
1. On a clean openSUSE Leap 15 system, install the Vagrant 2.1.2 package, and relevant dependent packages such as patterns-server-kvm_server, patterns-server-kvm_tools, libvirt-devel, pkg-config, gcc-c++ and make
2. Try to install the vagrant-libvirt plugin using `vagrant plugin install vagrant-libvirt`

### References
As previous reported, similar issues have been seen for the openSUSE Leap 42.2 and 42.3 distributions with regard to the embedded libreadline.so.6.
- GH-8986

**Comment by denisok** [comment]
same issue on openSUSE Tumbleweed.

> 
> $readelf -V /opt/vagrant/embedded/lib/libreadline.so.7 | grep READLINE | wc -l 
> 0                                                                               

workaround in https://github.com/hashicorp/vagrant/issues/8986 : 

> 0$sudo mv /opt/vagrant/embedded/lib/libreadline.so.7{,.disabled}

**Comment by chrisroberts** [comment]
Hi there. This was fixed in 2.1.4. If you still encounter errors, please do let us know. 

Cheers!

**Comment by furlongm** [comment]
This is still an issue on 2.2.5 on OpenSuse Leap 15:

```
"gcc -o conftest -I/opt/vagrant/embedded/include/ruby-2.4.0/x86_64-linux -I/opt/vagrant/embedded/include/ruby-2.4.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.4.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include   -I/opt/vagrant/embedded/include -fPIC  conftest.c  -L. -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib64 -Wl,-rpath=XORIGIN/../lib:XORIGIN/../lib64:/opt/vagrant/embedded/lib:/opt/vagrant/embedded/lib64 -fstack-protector -rdynamic -Wl,-export-dynamic -L/opt/vagrant/embedded/lib  -Wl,-rpath,/opt/vagrant/embedded/lib     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby  -lpthread -lrt -lgmp -ldl -lcrypt -lm   -lc "
sh: /opt/vagrant/embedded/lib/libreadline.so.7: no version information available (required by sh)
sh: symbol lookup error: /opt/vagrant/embedded/lib/libreadline.so.7: undefined symbol: UP
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

The workaround still works.

**Comment by guppyfaced** [comment]
Same issue on openSUSE Tumbleweed (20190628)
