### ISSUE TITLE
vagrant ssh fails when running commands in background?

### ISSUE THREAD

**Issue by davidawad** [hashicorp/vagrant#10029]
### Vagrant version
```
david@lithium ~/P/s/M/m/t/test_cluster>master>vagrant -v                                 15:26:06
Vagrant 2.1.2
```

### Host operating system
Mac OSX latest

### Guest operating system
bento/ubuntu-18.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
CLUSTER_OS = "bento/ubuntu-18.04"

BASE_PROVISIONING_SCRIPT = "
sudo apt-get install git -y
git clone https://gitlab.com/davidawad/tbd-murder murder
sudo chown -R vagrant: murder
"

#use eth0 if the network is public, eth1 if the network is private
TRACKER_SCRIPT="
export IP=$(hostname -I | cut -d' ' -f 2)
export ROLE='TRACKER'
echo $ROLE : $IP
cd murder
python murder_tracker.py &
echo 'TRACKER STARTED'
"

SEEDER_SCRIPT="
export IP=$(hostname -I | cut -d' ' -f 2)
export ROLE='SEEDER'
echo $ROLE : $IP
cd murder
bash setup.sh
python murder_client.py seed ../deploy.torrent 200.zip $IP &
"

PEER_SCRIPT="
export IP=$(hostname -I | cut -d' ' -f 2)
export ROLE='PEER'
echo $ROLE : $IP
cd murder
bash setup.sh
python murder_client.py peer ../deploy.torrent 200.zip $IP &
"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "shell", inline: BASE_PROVISIONING_SCRIPT

  # CHEF config management
  # config.vm.provision :chef_solo do |chef|

    # chef.cookbooks_path = ["cookbooks"]
    # config.berkshelf.enabled = true

    # # stuff that should be in base box
    # chef.add_recipe "vim"
    # chef.add_recipe "git"

    # chef.log_level = :debug
  # end


  # DEFINE TRACKER
  config.vm.define "tracker" do |machine|
     machine.vm.box = CLUSTER_OS
     machine.vm.network "private_network", ip: "192.168.33.2"

     machine.trigger.after :up do
       machine.vm.provision "shell", privileged: false, inline: TRACKER_SCRIPT
     end
  end


  # DEFINE SEEDER
  config.vm.define "seeder" do |machine|
     machine.vm.box = CLUSTER_OS
     machine.vm.network "private_network", ip: "192.168.33.3"

     machine.trigger.after :up do
      config.vm.provision "shell", privileged: false, inline:  SEEDER_SCRIPT
     end
  end


  # DEFINE PEER
  config.vm.define "peer" do |machine|
     machine.vm.box = CLUSTER_OS
     machine.vm.network "private_network", ip: "192.168.33.4"

     machine.trigger.after :up do
       config.vm.provision "shell", privileged: false, inline:  PEER_SCRIPT
     end
  end
end

```

### Expected behavior
What should have happened?

I have a project i'm working on that creates 3 vagrant vm's. 

### Actual behavior
What actually happened?

vagrant ssh -c fails when run without the `&` for some reason, making it impossible to automate running commands on certain vm's. 

### Steps to reproduce
1. clone https://gitlab.com/davidawad/tbd-murder/tree/master/test/test_cluster
2. run `make boot`, it will create 3 vm's
3. try to run the commands at the end of that makefile (lines 19-21) here: https://gitlab.com/davidawad/tbd-murder/blob/master/test/test_cluster/Makefile#L19 

For example in our case, the command `vagrant ssh tracker -c "nohup $(cd ~/murder && python murder_tracker.py) &"` fails. I don't understand why, nothing about making a process run in the background on the host machine should cause vagrant or the processes in my VM to behave differently. 

#### So to be specific, when I run these commands on the guest machine: 

THIS WORKS: `vagrant ssh tracker -c 'nohup $(cd ~/murder && python murder_tracker.py)'`

THIS DOESN'T: `vagrant ssh tracker -c 'nohup $(cd ~/murder && python murder_tracker.py)' &`

Any ideas? Thanks

**Comment by chrisroberts** [comment]
Hi there,

This is because using the `-c` flag for the `vagrant ssh` command uses `-t` with the `ssh` binary under the hood. You can get the behavior you want doing:

```
> vagrant ssh tracker -- 'nohup $(cd ~/murder && python murder_tracker.py)' &
```

Cheers!
