### ISSUE TITLE
Unknown Error Setting Up Virtual Machine

### ISSUE THREAD

**Issue by madelinekinnaird** [hashicorp/vagrant#10033]
Question: 
I am having trouble setting up the virtual machine. I read online that a lot of issues occur in the partnering of versions between Vagrant and Virtual Box. So I tried to use the most stable version (according to my googling). The error is listed below, please note – I have already tried googling this error. Let me know any advice, tips, etc.

Versions: 
Vagrant 1.8.5 
Virtual Box 5.1.0 
Windows 7 Professional

Errors: 
Bringing machine ‘default’ up with ‘virtualbox’ provider… ==> default: Box ‘bento/ubuntu-16.04’ could not be found. Attempting to find and install… default: Box Provider: virtualbox default: Box Version: = 2.3.5 The box ‘bento/ubuntu-16.04’ could not be found or could not be accessed in the remote catalog. If this is a private box on HashiCorp’s Atlas, please verify you’re logged in via vagrant login. Also, please double-check the name. The expanded URL and error message are shown below:

URL: [“https://atlas.hashicorp.com/bento/ubuntu-16.04”] Error: Failed to connect to atlas.hashicorp.com port 443: Timed out

**Comment by wangrangzhi** [comment]
there is no box in your computer.
find a public box in this website :https://app.vagrantup.com/boxes/search

**Comment by briancain** [comment]
Hi there @madelinekinnaird - This was due to a bug that has since been resolved with the latest version of Vagrant. If you upgrade to Vagrant version 2.1.2, do you still receive your error? Thanks!

**Comment by madelinekinnaird** [comment]
@briancain I updated to vagrant 2.1.2 and this is the error I received:

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/ubuntu-16.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: = 2.3.5
==> default: Waiting for cleanup before exiting...
The box 'bento/ubuntu-16.04' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/bento/ubuntu-16.04"]
Error:

**Comment by briancain** [comment]
hello @madelinekinnaird ! Could you re-run `vagrant up` with the `--debug` flag and send us the result in a gist? Are you also by chance behind a network proxy? Thanks!

**Comment by madelinekinnaird** [comment]
@briancain I am on my work computer and it isn't letting me create a gist....so perhaps I am behind a network proxy, is there a way I can check?

Here is the error message I received: https://github.com/madelinekinnaird/Udacity/blob/master/Vagrant%20Error%20Message

**Comment by madelinekinnaird** [comment]
Thanks @briancain for your help -- this is the new error I received: https://github.com/madelinekinnaird/Udacity/blob/master/Vagrant%20Error%20Message%202

**Comment by madelinekinnaird** [comment]
@briancain -- yes I'm able to visit the vagrantcloud website in my browser...

**Comment by briancain** [comment]
@madelinekinnaird - it seems like you are probably behind a network proxy if Vagrant is timing out trying to connect to Vagrant Cloud. You might need to either whitelist vagrantcloud.com on the network proxy to allow for requests to be sent to that address or set the `HTTP_PROXY` environment variable to your proxy servers address so that Vagrant can use that proxy when making HTTP requests.

**Comment by madelinekinnaird** [comment]
Thanks @briancain - I'm now going off of this http://tmatilai.github.io/vagrant-proxyconf/
Let me know if you have any other resources to move past the issue.

**Comment by briancain** [comment]
Not that I can think of! I'll go ahead and close the issue. Thanks!
