### ISSUE TITLE
Add support for provisioner groups

### ISSUE THREAD

**Issue by DDSGooch** [hashicorp/vagrant#10034]
For some complex vagrant setups, you can end up with a lot of provisioners, most of which you want to run _once_ (i.e. when you do a _vagrant up_) but other times you only want to run some of them. For example, we have a situation where we have a _prepare_ phase and then an _init_ phase. Normally we want to run both phases but sometimes just the _prepare_ phase.
Ideally these phases would consist of multiple of provisioners but as this can't be done, we've got around this by running multiple scripts from the _prepare_ and _init_ provisioners. However, we also want the ability to run these scripts individually using a provisioner, so we have to duplicate that and write another provisioner.
If it was possible to group provisioners, we could select which provisioners exist in the _prepare_ and _init_ provisioner groups, then do things like _vagrant up --provision-with prepare_

### Vagrant version
Vagrant 2.1.1

### Host operating system
Windows 7

### Guest operating system
Windows Server 2016

### Vagrantfile
Example non-functional vagrantfile
```ruby
Vagrant.configure("2") do |config| 
     config.vm.provision "prepare", type: "shell", inline: "install.sh; config.sh", run:"once"
     config.vm.provision "init", type: "shell", inline: "create.sh; start.sh", run:"once"
     config.vm.provision "install", type: "shell", inline: "install.sh", run:"never"
     config.vm.provision "config", type: "shell", inline: "config.sh", run:"never"
     config.vm.provision "create", type: "shell", inline: "create.sh", run:"never"
     config.vm.provision "start", type: "shell", inline: "start.sh", run:"never"
end
```

In this example, the _prepare_ phase run _install.sh_ and _config.sh_ and the _init_ phase runs _create.sh_ and _start.sh_. If this could be configured by provioner groups or something like that, it would remove the need for duplication.
This is a very simple example but hopefully it gives the idea.
Many thanks

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant by the introduction of dependency provisioners. Here are some docs https://www.vagrantup.com/docs/provisioning/basic_usage#dependency-provisioners. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
