### ISSUE TITLE
SSH-Agent-Forwarding does not work consistent on Windows

### ISSUE THREAD

**Issue by func0der** [hashicorp/vagrant#10032]
### Vagrant version
2.1.1

### Host operating system
Windows

### Guest operating system
Linux

### Vagrantfile
irrelevant

### Expected behavior
vagrant provision should consider the ssh-agent running.

### Actual behavior
It doesn't.

### Steps to reproduce
- Run an ssh-agent
- Try provisioning and use something where you need ssh-agent-forwarding for (for example: composer install or just a simple `ssh -T git@github.com whoami`)

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- https://github.com/mitchellh/vagrant/issues/1735
- https://github.com/net-ssh/net-ssh/issues/192

**Comment by chrisroberts** [comment]
I have isolated this issue to how we are building Ruby for Windows and am hoping to have the updated build ready for the 2.2.1 release.

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
