### ISSUE TITLE
[vagrant 2.1.2/VBox 5.2.14+] Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long

### ISSUE THREAD

**Issue by ZoranStojsavljevic** [hashicorp/vagrant#10039]
### Problem description
https://gitlab.com/cip-project/cip-testing/testing/issues/193

Compliance matrix:

https://github.com/ZoranStojsavljevic/referent_lava_BatD/blob/master/Documentation/VBox+Vagrant_Versions.md

### Vagrant version
Vagrant 2.1.2 is problematic with VirtualBox 5.2.14 (inclusive) and up.
Vagrant 2.1.1 does not have such problems.

### Host operating system
Debian Stretch amd64

Good Luck!
Zoran Stojsavljevic

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by ZoranStojsavljevic** [comment]
> However, there is not enough information here to reproduce or provide a recommendation.

The issue is solved. It is, basically, internal issue, which has nothing, but at the same time everything to do with Vagrant 2.1.2.

Thank you,
Zoran

**Comment by ZoranStojsavljevic** [comment]
Resolved. Closed.

Zoran
