### ISSUE TITLE
vagrant package

### ISSUE THREAD

**Issue by chenye2017** [hashicorp/vagrant#10031]
vagrant package --output E:\itbasic.box, when action success,my c drive is taking up a lot of space，i dont know how to reslove this question

**Comment by chrisroberts** [comment]
The most likely cause is that your Vagrant environment is located on your `c:` drive. Is the space freed after you destroy the guest?

**Comment by chenye2017** [comment]
no, my aim at package a box give my classmate,and i dont want destory my vm,my english is poor,i hope you can know what i mean.finally，i use a software for cleaning up garbage for my c driver,and freed some space。I am a junior engineer in China，so many english document is hard for me，and less Chinese resources for vagrant, so, i ask in this issue.

**Comment by chenye2017** [comment]
But still thank you for your answer

**Comment by chrisroberts** [comment]
No problem. Your English is good and I understand your question. I am happy you were able to find a resolution. :smiley:

**Comment by chenye2017** [comment]
谢啦，我是把vm的镜像放到了别的盘，但是vagrant box add 的时候，往容器里面添加box文件，这个容器的存储位置我曾经用环境变量修改过，通过vagrant home,但是不知道出啥原因了，还是失败了。
when i carry out 'vagrant box add', i insert into container a box file, i try to modify vagrant home to modify container location not c driver ,but failed,so,i only put the virtualbox file on other disk.

**Comment by wangrangzhi** [comment]
重装就行了。

**Comment by wangrangzhi** [comment]
我花了很长时间才弄出来一个合适的环境。
