### ISSUE TITLE
vagrant up hung here default: SSH auth method: private key.

### ISSUE THREAD

**Issue by Bhanukiran117** [hashicorp/vagrant#10045]
I have followed all workarounds given in git. Enabled network adapter cable connected and other stuff. I have destroyed and created multiple times but nothing really worked out. could some please help me. I am new to vagrant. 

```
[root@moonlight centos]# vagrant -v
Vagrant 2.1.2

[root@moonlight centos]# vboxmanage --version
5.2.16r123759

[root@moonlight virtualbox]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)


[root@moonlight centos]# cat Vagrantfile
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
end
```

What actually happened?

```
[root@moonlight centos7]# vagrant destroy && vagrant up
==> default: VM not created. Moving on...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/7' is up to date...
==> default: Setting the name of the VM: centos7_default_1532083277111_17188
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    **default: SSH auth method: private key**
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by briancain** [comment]
Hi there @Bhanukiran117 - I suggest using a different Vagrant box. Have you tried `bento/centos-7.5`?

**Comment by Bhanukiran117** [comment]
Hi Brain,  Thanks for trying to help me.

yes, I tried. bento/centos-7.5 and bento/centos-7..I landed on the same situation. 

[root@moonlight centos]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/centos-7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'bento/centos-7'
    default: URL: https://vagrantcloud.com/bento/centos-7
==> default: Adding box 'bento/centos-7' (v201803.24.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/bento/boxes/centos-7/versions/201803.24.0/providers/virtualbox.box
==> default: Successfully added box 'bento/centos-7' (v201803.24.0) for 'virtualbox'!
==> default: Importing base box 'bento/centos-7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/centos-7' is up to date...
==> default: Setting the name of the VM: centos_default_1532160537613_36148
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key

$$$$$$$$$$$$$$$$$$$$$$

[root@moonlight centos]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/centos-7.5' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'bento/centos-7.5'
    default: URL: https://vagrantcloud.com/bento/centos-7.5
==> default: Adding box 'bento/centos-7.5' (v201807.12.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/bento/boxes/centos-7.5/versions/201807.12.0/providers/virtualbox.box
==> default: Successfully added box 'bento/centos-7.5' (v201807.12.0) for 'virtualbox'!
==> default: Importing base box 'bento/centos-7.5'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/centos-7.5' is up to date...
==> default: Setting the name of the VM: centos_default_1532159240935_86650
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key

**Comment by Bhanukiran117** [comment]
[debug.log](https://github.com/hashicorp/vagrant/files/2216011/debug.log)

Attached debug file.

**Comment by ZoranStojsavljevic** [comment]
Hello Bhanu,

Didi you try to run the following commands (with Vagrant version 2.1.2):
[1] vagrant plugin list
[2] vagrant plugin update

Could you, please, do this for me (please, do NOT change neither Vagrant, neither VBOx versions)!?

Thank you,
Zoran

**Comment by Bhanukiran117** [comment]
Thanks Zoran helping me. I will run the list and update commands  and share the results.  I can not do immediately since I am not at my machine now. I will share details after 3 hours.

Thank you very much.
- Bhanu

**Comment by briancain** [comment]
@Bhanukiran117 - Are you able to bring up virtual machines outside of using Vagrant? In otherwords, try bringing up a vm through the VirtualBox GUI and see if you are successful.

**Comment by ZoranStojsavljevic** [comment]
@briancain. could you, please, retain calm?! We are all here after The Truth about Vagrant... You know what I mean, right? 

Truth is out there,and I am, after all, trying to find it out out there, no matter how ugly The Truth is?! :smile:

Zoran

**Comment by Bhanukiran117** [comment]
Zonran,

Here is the output.

[root@moonlight vag_cent]# vagrant plugin list
No plugins installed.
[root@moonlight vag_cent]# vagrant plugin update
Updating installed plugins...
All plugins are up to date.
[root@moonlight vag_cent]# vagrant plugin list
No plugins installed.
[root@moonlight vag_cent]#

Thank you.
Bhanu

**Comment by ZoranStojsavljevic** [comment]
Hello Bhanu,

> **default: SSH auth method: private key**
> Timed out while waiting for the machine to boot. This means that
> Vagrant was unable to communicate with the guest machine within
> the configured ("config.vm.boot_timeout" value) time period.

Could you, please, go to your host ~/.ssh directory, and delete file in it called: known_hosts? And try again?

Thank you,
Zoran

**Comment by Bhanukiran117** [comment]
Hi Zonran,

I deleted the known_hosts file and vagrant up in progress. looks like its hung at this step
default: SSH auth method: private key

[root@moonlight .ssh]# ls -ltr
total 8
-rw------- 1 root root 1675 Jul 20 15:12 insecure_private_key
-rw-r--r-- 1 root root  520 Jul 21 15:47 known_hosts
[root@moonlight .ssh]# date
Mon Jul 23 22:36:29 IST 2018
[root@moonlight .ssh]# rm known_hosts
rm: remove regular file ‘known_hosts’? y
[root@moonlight .ssh]# ls -ltr
total 4
-rw------- 1 root root 1675 Jul 20 15:12 insecure_private_key


[root@moonlight centos]# cat Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
end
[root@moonlight centos]# ls -ltr
total 12
-rw-r--r-- 1 root root 3015 Jul 20 17:29 Vagrantfile.Org
-rw-r--r-- 1 root root  878 Jul 20 19:09 debug.file
-rw-r--r-- 1 root root   75 Jul 21 14:27 Vagrantfile
[root@moonlight centos]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' for provider 'virtualbox' is
==> default: available! You currently have version '20180709.0.8'. The latest is version
==> default: '20180709.0.10'. Run `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key

**Comment by Bhanukiran117** [comment]
This error out with

[root@moonlight centos]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' for provider 'virtualbox' is
==> default: available! You currently have version '20180709.0.8'. The latest is version
==> default: '20180709.0.10'. Run `vagrant box update` to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
[root@moonlight centos]#

**Comment by briancain** [comment]
@Bhanukiran117 - please refer to my [comment above](https://github.com/hashicorp/vagrant/issues/10045#issuecomment-407116136) and let me know the results of attempting to bring up a virtual machine through the GUI instead of with Vagrant.

If you can't bring up a vm through the GUI, then Vagrant won't be able to either.

**Comment by Bhanukiran117** [comment]
I got it. I am going to install with CentOS-7-x86_64-Minimal-1804.iso via VB GUI and let you know the results.

**Comment by Bhanukiran117** [comment]
I have allocated 8G for vdi, and selected Cent O Install option via VB GUI, and its not showing any progress. I see only black screen in VBox


[root@moonlight /]# ls -ltr "/home/bhanu/VirtualBox VMs/linux/linux.vdi"
-rw------- 1 bhanu bhanu 8592031744 Jul 24 00:04 /home/bhanu/VirtualBox VMs/linux/linux.vdi

[root@moonlight /]# ls -ltrh "/home/bhanu/VirtualBox VMs/linux/linux.vdi"
-rw------- 1 bhanu bhanu 8.1G Jul 24 00:04 /home/bhanu/VirtualBox VMs/linux/linux.vdi
[root@moonlight /]# free -gh
              total        used        free      shared  buff/cache   available
Mem:           3.7G        1.2G        2.0G         16M        509M        2.2G
Swap:          3.9G          0B        3.9G
[root@moonlight /]#


Thanks
Bhanu

**Comment by Bhanukiran117** [comment]
my current environment:

Windows 7 PC.
VirtualBox Version 5.2.14
[root@moonlight /]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

On the above environment:

[root@moonlight /]# vagrant -v
Vagrant 2.1.2
[root@moonlight /]#  vboxmanage --version
5.2.16r123759

Trying to create new VM through vagrant,

**Comment by ZoranStojsavljevic** [comment]
Hello Bhanu,

Before destroying the environment, you should try just one more, one single thing: to downgrade Vagrant from 2.1.2 to 2.1.1 .

Instructions how to do are here (they work for my environment, since I have host 86x_64, and Debian stretch:

```
Please, go to site: https://releases.hashicorp.com/vagrant/

Please, download the following: https://releases.hashicorp.com/vagrant/2.1.1/vagrant_2.1.1_x86_64.deb

Execute the following script as root:

dpkg -i vagrant_2.1.1_x86_64.deb
vagrant --version

```
And see if this environment will make you the problems!

Thank you,
Zoran

**Comment by Bhanukiran117** [comment]
Thanks Zoran,

I missed your comment, I destroyed the VM and recreated, installed virtualbox and vagrant vagrant-2.1.2-1.x86_64. my efforts are back to square one.

It halt here. Now I am going to install vagrant_2.1.1_x86_64 version and try. I update the thread. 

[root@moonlight vagrant-home]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos/7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'centos/7'
    default: URL: https://vagrantcloud.com/centos/7
==> default: Adding box 'centos/7' (v1804.02) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/centos/boxes/7/versions/1804.02/providers/virtualbox.box
    default: Download redirected to host: cloud.centos.org
==> default: Successfully added box 'centos/7' (v1804.02) for 'virtualbox'!
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/7' is up to date...
==> default: Setting the name of the VM: vagrant-home_default_1532405537502_81879
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key

**Comment by Bhanukiran117** [comment]
with lower version also, I hit the same issue.

[root@moonlight Downloads]# ls -ltr
total 161056
-rw-r--r--. 1 root root 42714923 Jul 24 09:18 vagrant_2.1.2_x86_64.rpm
-rw-r--r--. 1 root root 79472464 Jul 24 09:18 VirtualBox-5.2-5.2.16_123759_el7-1.x86_64.rpm
-rw-r--r--. 1 root root 42727867 Jul 24 09:48 vagrant_2.1.1_x86_64.rpm
[root@moonlight Downloads]# yum localinstall vagrant_2.1.1_x86_64.rpm
Loaded plugins: fastestmirror, langpacks
Examining vagrant_2.1.1_x86_64.rpm: 1:vagrant-2.1.1-1.x86_64
Marking vagrant_2.1.1_x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package vagrant.x86_64 1:2.1.1-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================
 Package                                   Arch                                     Version                                     Repository                                               Size
==============================================================================================================================================================================================
Installing:
 vagrant                                   x86_64                                   1:2.1.1-1                                   /vagrant_2.1.1_x86_64                                   113 M

Transaction Summary
==============================================================================================================================================================================================
Install  1 Package

Total size: 113 M
Installed size: 113 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : 1:vagrant-2.1.1-1.x86_64                                                                                                                                                   1/1
  Verifying  : 1:vagrant-2.1.1-1.x86_64                                                                                                                                                   1/1

Installed:
  vagrant.x86_64 1:2.1.1-1

Complete!
[root@moonlight Downloads]# vagrant --version
Vagrant 2.1.1
[root@moonlight Downloads]# cd
[root@moonlight ~]# mkdir ~/vagrant-home
[root@moonlight ~]# cd ~/vagrant-home
[root@moonlight vagrant-home]# vagrant plugin list
No plugins installed.
[root@moonlight vagrant-home]# vi Vagrantfile
[root@moonlight vagrant-home]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/7' is up to date...
==> default: Setting the name of the VM: vagrant-home_default_1532406069808_75235
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key

**Comment by ZoranStojsavljevic** [comment]
Bhanu,

I know that debian/stretch64 works for sure. Please, try this pressed-ed Hashicorp. VM, and see what happens/if you have the same issue?

Zoran

**Comment by Bhanukiran117** [comment]
Zoran, sure I am downloading debain from the you have given. can I install that on centos ?

Thanks
Bhanu

**Comment by Bhanukiran117** [comment]
-rw-r--r--. 1 root root 43539450 Jul 24 11:12 vagrant_2.1.1_x86_64.deb
[root@moonlight Downloads]# dpkg -i vagrant_2.1.1_x86_64.deb
bash: dpkg: command not found...
[root@moonlight Downloads]# yum install vagrant_2.1.1_x86_64.deb
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: ftp.iitm.ac.in
 * extras: ftp.iitm.ac.in
 * updates: ftp.iitm.ac.in
No package vagrant_2.1.1_x86_64.deb available.
Error: Nothing to do
[root@moonlight Downloads]# rpm -ivh vagrant_2.1.1_x86_64.deb
error: vagrant_2.1.1_x86_64.deb: not an rpm package (or package manifest):
[root@moonlight Downloads]# yum install dpkg
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: ftp.iitm.ac.in
 * extras: ftp.iitm.ac.in
 * updates: ftp.iitm.ac.in
No package dpkg available.
Error: Nothing to do
[root@moonlight Downloads]#

**Comment by ZoranStojsavljevic** [comment]
No, no. On Centos (which is a derivate from RHEL, as I know) host you have
to have rpm (Red hat Package Manager). And to take .rpm vagrant package!

So, in nutshell, the following should be true:
dnf install rpm (but you should have it)
rpm -i vagrant_2.1.1_x86_64.rpm (you should find centos look alike dnf/rmp
support, if I am not mistaken).

Zoran

**Comment by Bhanukiran117** [comment]
I am not confident on my approach or hardware/software.

1. I have windows 7 Professional host, on it I have installed virtual box. Enabled NAT + Bridge network with connected cable.

2. I have CentOS  guest, and I have installed virtual box on it and vagrant. I observed virtual box installed on centos not showing 64 bit option in CentOS->virtual box GUI, even though I have enabled VT-x /AMD on my virtual box installed on Windows.

3. I am trying to spin new centos or ubuntu via vagrant.. however I am not able,  got stuck at this step vagrant up,  with following error.

    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

################ 

 Please direct me right steps, so that I follow and share results to you.

- Bhanu

**Comment by ZoranStojsavljevic** [comment]
Yayayaaaiiii... Bhanu!

> default: SSH auth method: private key
> Timed out while waiting for the machine to boot. This means that
> Vagrant was unable to communicate with the guest machine within
> the configured ("config.vm.boot_timeout" value) time period.
I guess, you are, after all, using UEFI boot on your Centos VM. Could you
switch your UEFI option off?

https://www.linuxbabe.com/wp-content/uploads/2016/03/arch_arch-uefi-Settings_001.png

(Enable EFI - Special OSes ONLY) ==>> make this box OFF (untick) Make it
Legacy!

The CLI vboxmanage command which does this is: vboxmanage modifyvm $vmname
--firmware bios

Zoran
_______

**Comment by briancain** [comment]
Hi @Bhanukiran117 - As mentioned above, you need to enable VT-X in your bios before you can bring up VMs. This is why I was asking if you could bring one up with the VirtualBox GUI instead of Vagrant. Enabling that setting should allow you to bring up VMs just fine, which means Vagrant will be able to create VMs. I'll go ahead and close this issue, but feel free to ask any more questions here or redirect them to be discussed on the Vagrant mailing list. Thanks!

**Comment by Bhanukiran117** [comment]
Thanks Zoran and Brian

1. I will check the UEFI options an hour later and update you.
2. Brain,  I tried to bring up the VM using CentOS-> Virtual box but I could not. I was able to select Install option from iso file but after the blank. Not able select VT-X options in Centos->Virtual box GUI.the option is greyed out.  one more thing I noticed, I am not getting 64 bit options select box CentOS-> Virtual box. 

I will share more details with screen-shots after an hour.

Thank you very much for your kind help.

- Bhanu

**Comment by Bhanukiran117** [comment]
Zoran, and Brain

I have selected legacy and unselected EFI - Special OSes ONLY in my Windows->virtual box
and tried to create vm using centos->vagrant.
no luck.

[root@moonlight vag]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/7' is up to date...
==> default: Setting the name of the VM: vag_default_1532452466558_78764
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key

**Comment by Bhanukiran117** [comment]
if you would like to see my screen, I share the team viewer details.

**Comment by Bhanukiran117** [comment]
![error](https://user-images.githubusercontent.com/22053367/43155826-17d0f5ee-8f96-11e8-85b5-b23fb154ac08.jpg)

I am attaching jpeg screen shot, the error I see centos->virtual box gui.

**Comment by Bhanukiran117** [comment]
Also,

I see following error in VBox.log file.

00:00:00.106672 HM: HMR3Init: Falling back to raw-mode: VT-x is not available

**Comment by Bhanukiran117** [comment]
![error2](https://user-images.githubusercontent.com/22053367/43156940-18e72568-8f99-11e8-8f19-7afd4e234132.jpg)

with that error, and I see this link from
https://forums.virtualbox.org/viewtopic.php?f=6&t=87827

It says, my computer is not good enough for latest virtualbox and os.

**Comment by Bhanukiran117** [comment]
I am able to vagrant 32 bit virtual box.

==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /root/precise32


[root@moonlight precise32]# vagrant ssh
Welcome to Ubuntu 12.04.5 LTS (GNU/Linux 3.13.0-32-generic i686)

 * Documentation:  https://help.ubuntu.com/
New release '14.04.5 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

vagrant@precise32:~$ uptime
 18:08:54 up 1 min,  1 user,  load average: 0.35, 0.23, 0.09
vagrant@precise32:~$

Thank you very much Brain & Zoran for your valuable time.

**Comment by romainnorberg** [comment]
delete all boxes from `/Users/xxx/.vagrant.d` (macOs) and delete `~/.ssh/known_hosts` file work for me. 🦀 

Thanks @ZoranStojsavljevic (https://github.com/hashicorp/vagrant/issues/10045#issuecomment-407130487)

**Comment by idreesandroid** [comment]
E:\vagrant>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'chrislentz/trusty64-lamp' version '3.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 22 (guest) => 22222 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

i also facing same problem, suggest me any solution if possible

**Comment by ZoranStojsavljevic** [comment]
Hello @idreesandroid,

>> default: 22 (guest) => 22222 (host) (adapter 1)
>> default: 22 (guest) => 2222 (host) (adapter 1)

This two lines look to me suspicious. Please, delete the first line from Vagrantfile:
default: 22 (guest) => 22222 (host) (adapter 1)

And see if this helps!

Zoran

**Comment by vladislavradonjic** [comment]
I've been bashing my head against this for hours. None of the solutions worked, unfortunately.

Finally, I deleted the VM from VirtualBox graphical interface and than ran vagrant up from terminal. It went through the whole build, downloading and installing guest OS and everything.

I'm still installing missing software, but, what can you do.

I'm seriously considering moving to linux and droping the whole vagrant thing.

Vladislav

**Comment by gimgunwoo** [comment]
I just had this issue after swapping my laptop with a spare. Vagrant was stuck in starting all VMs at "default: SSH auth method: private key". I quickly checked BIOS menu if this spare laptop had virtualization enabled, and it wasn't. Enabling virtualization fixed for me.

**Comment by cespurgeon** [comment]
Had the same issue and the BIOS fix reported by gimgunwoo resolved it for me. Turned on Intel virtualization and everything worked after that. Thanks!

**Comment by ZoranStojsavljevic** [comment]
Please, note to all: please, turn on Virtualization HW extensions (2 of 'em) in your BIOS/UEFI driven PCs, laptops, DTs, WS, servers... Turn on VT-x (MMU virtualization) and DO NOT forget also to turn on VT-d (IO-MMU) device space virtualization. The second one is (for some features) very crucial/important!

Zoran

**Comment by praveenmj2001** [comment]
Removing Known_host file helped me... I had tried lots of stuff...uninstall/ goto older vagrant version etc...On Windows 10 on AMD

**Comment by praveenmj2001** [comment]
Thanks Zoran
