### ISSUE TITLE
Vagrant up failed on Ubuntu w/ Virtualbox because libcurl in AppImage cause VBoxManage `CURL_OPENSSL_4' not found

### ISSUE THREAD

**Issue by at15** [hashicorp/vagrant#10052]
### Vagrant version

2.1.2 AppImage

### Host operating system

Ubuntu 18.04

Virtualbox 5.2.8r121009

### Guest operating system

Ubuntu 16.04

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 2.0.2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "mesos-vagrant.local"
  config.vm.box = "ubuntu/xenial64"

  config.vm.define "mesos-vagrant" do |m|
    m.vm.network :private_network, ip: "192.168.33.8"
    m.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "3072"]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
  end
end
```

### Debug output

````
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["--version"]

Stderr: /usr/lib/virtualbox/VBoxManage: /tmp/.mount_vagranu0Au3x/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/virtualbox/VBoxRT.so)
`````

### Expected behavior

The vm up and running when using AppImage

### Actual behavior

Failed because `VBoxManage --version` failed with curl version error

The `.deb` version works fine (I tried AppImage first).  btw: I didn't find how AppImage is packaged in vagrant repo

### Steps to reproduce

1. use the AppImage instead of the `.deb` version
2. pick a normal vagrantfile and run vagrant up

### References

- https://github.com/hashicorp/vagrant/issues/9875 Dynamically linked version of OpenSSL in AppImage "container" causes `vagrant ssh` to fail
- https://github.com/at15/code-i-read/issues/6

**Comment by chrisroberts** [comment]
@at15 Just a note that latest vbox packages on ubuntu 18.04 don't reproduce your original issue so the 2.1.2 appimage should be working again. The 2.1.3 release will prevent the breakage seen in the future. Thanks for the report!
