### ISSUE TITLE
Vagrant Up fails with encrypted ansible file

### ISSUE THREAD

**Issue by brandonkal** [hashicorp/vagrant#10054]
`vagrant up` fails when including an encypted ansible vault file. Vagrant should add the ability to include vault encrypted YAML files by also using the `vault_password_file` to decrypt the contents.

As it is now, I cannot start a vagrant vm without first manually decrypting the vaulted files.

### Vagrant version
2.1.2

### Host operating system
MacOS 12.12.6

### Guest operating system
Ubuntu 18.04

### Vagrantfile
```ruby
require 'yaml'
settings = YAML.load_file 'group_vars/all.yml'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version.
Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/bionic64"
   config.vm.hostname = "domainvm"
   config.vm.network "private_network", ip: "192.168.50.4"
   config.vm.synced_folder settings['website_local_git_path'], "/home/vagrant/domain.com/website"
   config.vm.synced_folder ".", "/vagrant", disabled: true
   config.vm.synced_folder "../image-archive", "/image-archive"
   config.vm.provider :virtualbox do |v|
     v.name = "domain.test"
     v.memory = 1024
     v.cpus = 1
   end

   config.vm.provision :ansible do |ansible|
     # ansible.verbose = "vvv"
     ansible.extra_vars = { "ansible_python_interpreter" => "/usr/bin/env python3" }
     ansible.playbook = "bootstrap.yml"
     ansible.groups = {
       "development" => ["default"]
     }
   end
```

**Comment by gildegoma** [comment]
Hey @brandonkal! Thank you for asking with full details.

I think you're looking for the [vault_password_file](https://www.vagrantup.com/docs/provisioning/ansible_common.html#vault_password_file) option of the Ansible provisioners.

**Comment by brandonkal** [comment]
@gildegoma My understanding is that vault_password_file is used by the Ansible provisioner but not before. As it is now, I have vault_password_file specified in a local ansible.cfg file, which vagrant seems to have no trouble using. My problem is that I need to set the `config.vm.synced_folder` location on the host based on a variable specified in an ansible vaulted file. Since that happens before the ansible provisioner is triggered by vagrant, vagrant does not understand how to read the included yml file.

If there is a way to configure the vagrant synced folders with the ansible provisioner,  then I suppose such a feature would not be useful, and I would appreciate information on how to accomplish that. But as it is now, my understanding is that bringing in the yml file directly is the only way to accomplish this.

**Comment by gildegoma** [comment]
> My understanding is that vault_password_file is used by the Ansible provisioner but not before.

This is totally correct. Vagrant (without additional plugins) supports Ansible integration only at the `provision` stage.

If you really want to load an "ansible-vaulted" file from the `Vagrantfile`, you should extend your `settings = YAML.load_file 'group_vars/all.yml'` code (e.g. with a call to `ansible-vault decrypt`).

But in a Vagrant context (i.e. development environment), I suppose that the `website_local_git_path` variable doesn't have to be a secret. In such situation, I usually recommend to override such variables, as illustrated in the example below:

```ruby
# Tip: this variable could also depend on environment variable(s)
WEBSITE_LOCAL_GIT_PATH='/my/local/git/path'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version.
Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/bionic64"
   config.vm.hostname = "domainvm"
   config.vm.network "private_network", ip: "192.168.50.4"
   config.vm.synced_folder WEBSITE_LOCAL_GIT_PATH, "/home/vagrant/domain.com/website"
   config.vm.synced_folder ".", "/vagrant", disabled: true
   config.vm.synced_folder "../image-archive", "/image-archive"
   config.vm.provider :virtualbox do |v|
     v.name = "domain.test"
     v.memory = 1024
     v.cpus = 1
   end

   config.vm.provision :ansible do |ansible|
     # ansible.verbose = "vvv"
     ansible.extra_vars = { 
       "ansible_python_interpreter" => "/usr/bin/env python3",
       "website_local_git_path" => WEBSITE_LOCAL_GIT_PATH
     }
     ansible.playbook = "bootstrap.yml"
     ansible.groups = {
       "development" => ["default"]
     }
   end

end
```

I am closing this issue because, we won't add such "Ansible Vault" support (i.e. ability to parse Ansible Vault encrypted YAML file into Vagrantfile/Settings). But feel free to comment here if you have more questions or inputs about your specific use case. Thank you 😃
