### ISSUE TITLE
Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)

### ISSUE THREAD

**Issue by EthanLXGu** [hashicorp/vagrant#10056]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Vagrant 2.1.2

### Host operating system
Centos7 cloud platform.

### Guest operating system
Centos7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "hashicorp/precise64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
Vagrant up should start this vm

### Actual behavior
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "b4293ed5-0a7a-4fb2-bd62-23d47fe87557", "--type", "headless"]

Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by ZoranStojsavljevic** [comment]
Hello Ethan,

You should stop in your host's BIOS, and enable in CMOS two settings:
[1] VT-x
[2] VT-d.

Best Regards,
Zoran

**Comment by EthanLXGu** [comment]
@ZoranStojsavljevic Hi, Thanks for your reply. actually, i plan to use vagrant in the cloud platform of centos7 system, i think for this cloud platform, it is not a real machine.. how to enable the BIOS setting? Is it possible?

**Comment by ZoranStojsavljevic** [comment]
hashicorp/vagrant issue 10045, my latest comment there:

https://github.com/hashicorp/vagrant/issues/10045#issuecomment-407433468

Zoran

**Comment by briancain** [comment]
@EthanLXGu - I believe the only cloud that supports enabling VT-X right now is GCE? There are instructions here if that's what you're using centos-7 on: https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances

Otherwise, you won't be able to bring up VMs if VT-X is disabled. I'll go ahead and close this issue, but if you want further help enabling VT-X or finding another solution feel free to email the Vagrant mailing list. Thanks!

**Comment by briancain** [comment]
@apoorva-shah - you need to go into your bios and enabled virtualization.

**Comment by apoorva-shah** [comment]
Hello @briancain ,
I did not see option in BIOS to enable virtualization. May be i missed something? Can you please guide me?
I have core2 duo, 32 bit, ubuntu 16.04 LTS.

Thanks,
Apoorva Shah

**Comment by cyrilthank** [comment]
> @EthanLXGu - I believe the only cloud that supports enabling VT-X right now is GCE? There are instructions here if that's what you're using centos-7 on: https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances
> Otherwise, you won't be able to bring up VMs if VT-X is disabled. I'll go ahead and close this issue, but if you want further help enabling VT-X or finding another solution feel free to email the Vagrant mailing list. Thanks!

Just wanted to ask if there are any changes to this ever since
in terms of additional cloud vendors supporting this
