### ISSUE TITLE
JSON::ParserError 751 unexpected token at ' '

### ISSUE THREAD

**Issue by pasa-edoardo** [hashicorp/vagrant#10057]
### Vagrant version
2.1.2

### Host operating system
CentOS Linux release 7.5

### Guest operating system
CentOS

### Vagrantfile
>Vagrant.configure("2")  do |config|
>  config.vm.box = 'ovirt4'
>  config.vm.box_url = 'https://github.com/myoung34/vagrant-ovirt4/blob/master/example_box/dummy.box?raw=true'
>
>  config.vm.provider :ovirt4 do |ovirt|
>    ovirt.url = 'https://server/ovirt-engine/api'
>    ovirt.username = "admin@internal"
>    ovirt.password = "password"
>    ovirt.insecure = true
>    ovirt.debug = true
>  end
> end

### Debug output
https://gist.github.com/pasa-edoardo/c79ec8f3f7e495bcd9fbab45126a97e9

### Expected behavior
It should create vm on ovirt

### Actual behavior
Apparently pass the authentication but crash when try to parse the configuration for create the vm.

### Steps to reproduce
1. I have done an installation from scratch of vagrant and vagrant-ovirt 4.
2. Edited Vagrantfile after "vagrant init"
3. vagrant up --debug

**Comment by briancain** [comment]
Hi there @pasa-edoardo - the stacktrace you shared leads me to believe that the issue is with the provider you are using, [vagrant-ovirt4](https://github.com/myoung34/vagrant-ovirt4). Please open an issue on their repo. Thanks!
