### ISSUE TITLE
static ip is unreachable

### ISSUE THREAD

**Issue by lyashevska** [hashicorp/vagrant#10055]
### Vagrant version
Vagrant 1.9.1

### Host operating system
Debian GNU/Linux 9

### Guest operating system
centos7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "jasonc/centos7"
  config.vm.hostname = "testbox01"
  config.vm.network "private_network", ip: "10.9.8.7"
end
```
### Debug output
https://gist.github.com/lyashevska/ba4cbad68f4b5238c33885c958654747

### Expected behavior
ping should not fail

### Actual behavior
ping to a specified static ip fails

### Steps to reproduce
1. add config.vm.network "private_network", ip: "10.9.8.7" in Vagrantfile
2. ping 10.9.8.7 --> fails
3. ping 127.0.0.1 --> works

**Comment by briancain** [comment]
Hi there @lyashevska - If you upgrade to the latest version of Vagrant, do to still receive this issue? And if so, please provider the output of running `vagrant up --debug` for us, thanks!

**Comment by lyashevska** [comment]
hi @briancain - thanks, Vagrant version 2.1.2 works fine.
