### ISSUE TITLE
Navigating a Corporate Proxy

### ISSUE THREAD

**Issue by madelinekinnaird** [hashicorp/vagrant#10060]
### Vagrant version
Vagrant 2.1.2

### Host operating system
Windows 10

### Guest operating system
Virtual Machine 5.1.0

I'm trying to get vagrant set up on a computer that has a corporate proxy. I found this article: https://dev.to/shriharshmishra/behind-the-corporate-proxy-2jd8

I have downloaded a plugin for the proxy and try to use the pugin install command but am having errors, I feel like it must be a basic fix?

### Debug output
mk720x@TXCDTL01MK720X MINGW64 ~/Downloads
$ vagrant plugin install /vagrant-proxyconf-1.5.2.gem
bash: vagrant: command not found

**Comment by briancain** [comment]
Hi @madelinekinnaird - from the error you posted, it just looks like Vagrant is not on your path. Did something change recently on your system? Does running `vagrant --help` in your command window work? Or maybe try running that command in Powershell? If none of that works you could always try re-installing the Vagrant package.

**Comment by madelinekinnaird** [comment]
@briancain I made some progress and worked with some of our company's system admins to work around our proxy. I'm now getting a time out error. I increased config.vm.boot_timeout = 600 , but it still timed out. 

This is the debug message from vagrant up. Do you see anything that gives you a clue of what I need to do? https://github.com/madelinekinnaird/Udacity/blob/master/Vagrant%20Error%20Message%203

**Comment by briancain** [comment]
@madelinekinnaird - does the issue go away if you halt the vm with `vagrant halt` or through the VirtualBox GUI, and then bring it up again with a `vagrant up`?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
