### ISSUE TITLE
vagrant up not working in my local

### ISSUE THREAD

**Issue by connectamakwana** [hashicorp/vagrant#10062]
D:\roots\roots-example-project.com\trellis>vagrant up
Installing plugin vagrant-bindfs
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not fetch specs from https://gems.hashicorp.com/

Warning: this Gemfile contains multiple primary sources. Using `source` more tha
n once without a block is a security risk, and may result in installing unexpect
ed gems. To resolve this warning, use a block to indicate which gems should come
 from the secondary source. To upgrade this warning to an error, run `bundle con
fig disable_multisource true`.Retrying fetcher due to error (2/4): Bundler::HTTP
Error Could not fetch specs from https://gems.hashicorp.com/Retrying fetcher due
 to error (3/4): Bundler::HTTPError Could not fetch specs from https://gems.hash
icorp.com/Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetc
h specs from https://gems.hashicorp.com/

D:\roots\roots-example-project.com\trellis>

**Comment by connectamakwana** [comment]
INFO manager: Registered plugin: salt
DEBUG global: Loading core plugin: D:/HashiCorp/Vagrant/embedded/gems/gems/vagra
nt-1.8.7/plugins/provisioners/shell/plugin.rb
 INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: D:/HashiCorp/Vagrant/embedded/gems/gems/vagra
nt-1.8.7/plugins/pushes/atlas/plugin.rb
 INFO manager: Registered plugin: atlas
DEBUG global: Loading core plugin: D:/HashiCorp/Vagrant/embedded/gems/gems/vagra
nt-1.8.7/plugins/pushes/ftp/plugin.rb
 INFO manager: Registered plugin: ftp
DEBUG global: Loading core plugin: D:/HashiCorp/Vagrant/embedded/gems/gems/vagra
nt-1.8.7/plugins/pushes/heroku/plugin.rb
 INFO manager: Registered plugin: heroku
DEBUG global: Loading core plugin: D:/HashiCorp/Vagrant/embedded/gems/gems/vagra
nt-1.8.7/plugins/pushes/local-exec/plugin.rb
 INFO manager: Registered plugin: local-exec
DEBUG global: Loading core plugin: D:/HashiCorp/Vagrant/embedded/gems/gems/vagra
nt-1.8.7/plugins/pushes/noop/plugin.rb
 INFO manager: Registered plugin: noop
DEBUG global: Loading core plugin: D:/HashiCorp/Vagrant/embedded/gems/gems/vagra
nt-1.8.7/plugins/synced_folders/nfs/plugin.rb
 INFO manager: Registered plugin: NFS synced folders
DEBUG global: Loading core plugin: D:/HashiCorp/Vagrant/embedded/gems/gems/vagra
nt-1.8.7/plugins/synced_folders/rsync/plugin.rb
 INFO manager: Registered plugin: RSync synced folders
DEBUG global: Loading core plugin: D:/HashiCorp/Vagrant/embedded/gems/gems/vagra
nt-1.8.7/plugins/synced_folders/smb/plugin.rb
 INFO manager: Registered plugin: SMB synced folders
 INFO global: Loading plugins!
 INFO manager: Registered plugin: vagrant-share
 INFO vagrant: `vagrant` invoked: ["--debug"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#<Vagrant::Environment:0x21e9c28>)
 INFO environment:   - cwd: D:/roots/roots-example-project.com/trellis
 INFO environment: Home path: D:/d/.vagrant.d
DEBUG environment: Effective local data path: D:/roots/roots-example-project.com
/trellis/.vagrant
 INFO environment: Local data path: D:/roots/roots-example-project.com/trellis/.
vagrant
DEBUG environment: Creating: D:/roots/roots-example-project.com/trellis/.vagrant

 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Buil
der:0x284fc70>
 INFO environment: Running hook: environment_load
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x277e
fd8>
 INFO cli: CLI: [] nil []
 INFO interface: Machine: cli-command ["box"]
 INFO interface: Machine: cli-command ["connect"]
 INFO interface: Machine: cli-command ["destroy"]
 INFO interface: Machine: cli-command ["global-status"]
 INFO interface: Machine: cli-command ["halt"]
 INFO interface: Machine: cli-command ["help"]
 INFO interface: Machine: cli-command ["init"]
 INFO interface: Machine: cli-command ["login"]
 INFO interface: Machine: cli-command ["package"]
 INFO interface: Machine: cli-command ["plugin"]
 INFO interface: Machine: cli-command ["port"]
 INFO interface: Machine: cli-command ["powershell"]
 INFO interface: Machine: cli-command ["provision"]
 INFO interface: Machine: cli-command ["push"]
 INFO interface: Machine: cli-command ["rdp"]
 INFO interface: Machine: cli-command ["reload"]
 INFO interface: Machine: cli-command ["resume"]
 INFO interface: Machine: cli-command ["share"]
 INFO interface: Machine: cli-command ["snapshot"]
 INFO interface: Machine: cli-command ["ssh"]
 INFO interface: Machine: cli-command ["ssh-config"]
 INFO interface: Machine: cli-command ["status"]
 INFO interface: Machine: cli-command ["suspend"]
 INFO interface: Machine: cli-command ["up"]
 INFO interface: Machine: cli-command ["version"]
 INFO interface: info: Usage: vagrant [options] <command> [<args>]

    -v, --version                    Print the version and exit.
    -h, --help                       Print this help.

Common commands:
     box             manages boxes: installation, removal, etc.
     connect         connect to a remotely shared Vagrant environment
     destroy         stops and deletes all traces of the vagrant machine
     global-status   outputs status Vagrant environments for this user
     halt            stops the vagrant machine
     help            shows the help for a subcommand
     init            initializes a new Vagrant environment by creating a Vagrant
file
     login           log in to HashiCorp's Atlas
     package         packages a running vagrant environment into a box
     plugin          manages plugins: install, uninstall, update, etc.
     port            displays information about guest port mappings
     powershell      connects to machine via powershell remoting
     provision       provisions the vagrant machine
     push            deploys code in this environment to a configured destinatio
n
     rdp             connects to machine via RDP
     reload          restarts vagrant machine, loads new Vagrantfile configurati
on
     resume          resume a suspended vagrant machine
     share           share your Vagrant environment with anyone in the world
     snapshot        manages snapshots: saving, restoring, etc.
     ssh             connects to machine via SSH
     ssh-config      outputs OpenSSH valid configuration to connect to the machi
ne
     status          outputs status of the vagrant machine
     suspend         suspends the machine
     up              starts and provisions the vagrant environment
     version         prints current and latest Vagrant version

For help on any individual command run `vagrant COMMAND -h`

Additional subcommands are available, but are either more advanced
or not commonly used. To see all subcommands, run the command
`vagrant list-commands`.

Usage: vagrant [options] <command> [<args>]

    -v, --version                    Print the version and exit.
    -h, --help                       Print this help.

Common commands:
     box             manages boxes: installation, removal, etc.
     connect         connect to a remotely shared Vagrant environment
     destroy         stops and deletes all traces of the vagrant machine
     global-status   outputs status Vagrant environments for this user
     halt            stops the vagrant machine
     help            shows the help for a subcommand
     init            initializes a new Vagrant environment by creating a Vagrant
file
     login           log in to HashiCorp's Atlas
     package         packages a running vagrant environment into a box
     plugin          manages plugins: install, uninstall, update, etc.
     port            displays information about guest port mappings
     powershell      connects to machine via powershell remoting
     provision       provisions the vagrant machine
     push            deploys code in this environment to a configured destinatio
n
     rdp             connects to machine via RDP
     reload          restarts vagrant machine, loads new Vagrantfile configurati
on
     resume          resume a suspended vagrant machine
     share           share your Vagrant environment with anyone in the world
     snapshot        manages snapshots: saving, restoring, etc.
     ssh             connects to machine via SSH
     ssh-config      outputs OpenSSH valid configuration to connect to the machi
ne
     status          outputs status of the vagrant machine
     suspend         suspends the machine
     up              starts and provisions the vagrant environment
     version         prints current and latest Vagrant version

For help on any individual command run `vagrant COMMAND -h`

Additional subcommands are available, but are either more advanced
or not commonly used. To see all subcommands, run the command
`vagrant list-commands`.
 INFO environment: Running hook: environment_unload
 INFO loader: Set :root = ["#<Pathname:D:/roots/roots-example-project.com/trelli
s/Vagrantfile>"]
DEBUG loader: Populating proc cache for #<Pathname:D:/roots/roots-example-projec
t.com/trellis/Vagrantfile>
DEBUG loader: Load procs for pathname: D:/roots/roots-example-project.com/trelli
s/Vagrantfile
 INFO interface: warn: Installing plugin vagrant-bindfs
Installing plugin vagrant-bindfs
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::BundlerError: Bundler, the underlying system V
agrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not fetch specs from https://gems.hashicorp.com/

Warning: this Gemfile contains multiple primary sources. Using `source` more tha
n once without a block is a security risk, and may result in installing unexpect
ed gems. To resolve this warning, use a block to indicate which gems should come
 from the secondary source. To upgrade this warning to an error, run `bundle con
fig disable_multisource true`.Retrying fetcher due to error (2/4): Bundler::HTTP
Error Could not fetch specs from https://gems.hashicorp.com/Retrying fetcher due
 to error (3/4): Bundler::HTTPError Could not fetch specs from https://gems.hash
icorp.com/Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetc
h specs from https://gems.hashicorp.com/>
ERROR vagrant: Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not fetch specs from https://gems.hashicorp.com/

Warning: this Gemfile contains multiple primary sources. Using `source` more tha
n once without a block is a security risk, and may result in installing unexpect
ed gems. To resolve this warning, use a block to indicate which gems should come
 from the secondary source. To upgrade this warning to an error, run `bundle con
fig disable_multisource true`.Retrying fetcher due to error (2/4): Bundler::HTTP
Error Could not fetch specs from https://gems.hashicorp.com/Retrying fetcher due
 to error (3/4): Bundler::HTTPError Could not fetch specs from https://gems.hash
icorp.com/Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetc
h specs from https://gems.hashicorp.com/
ERROR vagrant: D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant
/plugin/manager.rb:87:in `rescue in install_plugin'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/plugin/manager
.rb:44:in `install_plugin'
D:/roots/roots-example-project.com/trellis/lib/trellis/vagrant.rb:21:in `block i
n ensure_plugins'
D:/roots/roots-example-project.com/trellis/lib/trellis/vagrant.rb:13:in `each'
D:/roots/roots-example-project.com/trellis/lib/trellis/vagrant.rb:13:in `ensure_
plugins'
D:/roots/roots-example-project.com/trellis/Vagrantfile:18:in `<top (required)>'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.
rb:207:in `load'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.
rb:207:in `block in procs_for_path'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config.rb:53:i
n `block in capture_configures'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config.rb:48:i
n `synchronize'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config.rb:48:i
n `capture_configures'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.
rb:205:in `procs_for_path'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.
rb:191:in `procs_for_source'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.
rb:67:in `block in set'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.
rb:61:in `each'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/config/loader.
rb:61:in `set'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb
:441:in `config_loader'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb
:746:in `vagrantfile'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb
:492:in `host'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb
:214:in `block in action_runner'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.
rb:33:in `call'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.
rb:33:in `run'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb
:479:in `hook'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb
:728:in `unload'
D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.7/bin/vagrant:192:in `<main>
'
 INFO interface: error: Bundler, the underlying system Vagrant uses to install p
lugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not fetch specs from https://gems.hashicorp.com/

Warning: this Gemfile contains multiple primary sources. Using `source` more tha
n once without a block is a security risk, and may result in installing unexpect
ed gems. To resolve this warning, use a block to indicate which gems should come
 from the secondary source. To upgrade this warning to an error, run `bundle con
fig disable_multisource true`.Retrying fetcher due to error (2/4): Bundler::HTTP
Error Could not fetch specs from https://gems.hashicorp.com/Retrying fetcher due
 to error (3/4): Bundler::HTTPError Could not fetch specs from https://gems.hash
icorp.com/Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetc
h specs from https://gems.hashicorp.com/
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not fetch specs from https://gems.hashicorp.com/

Warning: this Gemfile contains multiple primary sources. Using `source` more tha
n once without a block is a security risk, and may result in installing unexpect
ed gems. To resolve this warning, use a block to indicate which gems should come
 from the secondary source. To upgrade this warning to an error, run `bundle con
fig disable_multisource true`.Retrying fetcher due to error (2/4): Bundler::HTTP
Error Could not fetch specs from https://gems.hashicorp.com/Retrying fetcher due
 to error (3/4): Bundler::HTTPError Could not fetch specs from https://gems.hash
icorp.com/Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetc
h specs from https://gems.hashicorp.com/
 INFO interface: Machine: error-exit ["Vagrant::Errors::BundlerError", "Bundler,
 the underlying system Vagrant uses to install plugins,\nreported an error. The
error is shown below. These errors are usually\ncaused by misconfigured plugin i
nstallations or transient network\nissues. The error from Bundler is:\n\nCould n
ot fetch specs from https://gems.hashicorp.com/\n\nWarning: this Gemfile contain
s multiple primary sources. Using `source` more than once without a block is a s
ecurity risk, and may result in installing unexpected gems. To resolve this warn
ing, use a block to indicate which gems should come from the secondary source. T
o upgrade this warning to an error, run `bundle config disable_multisource true`
.Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs f
rom https://gems.hashicorp.com/Retrying fetcher due to error (3/4): Bundler::HTT
PError Could not fetch specs from https://gems.hashicorp.com/Retrying fetcher du
e to error (4/4): Bundler::HTTPError Could not fetch specs from https://gems.has
hicorp.com/"]

D:\roots\roots-example-project.com\trellis>.editorconfig

**Comment by briancain** [comment]
Hi @connectamakwana - is this issue resolved if you upgrade to the latest version of Vagrant? Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
