### ISSUE TITLE
From version 2.1.2, vagrant fails to install plugin when check for plugin existence is present in Vagrantfile

### ISSUE THREAD

**Issue by gbdlin** [hashicorp/vagrant#10061]
### Vagrant version
2.1.2

### Host operating system
Any host system

### Guest operating system
Any guest system

### Vagrantfile
(relevant part)
```ruby
    if not Vagrant.has_plugin?("vagrant-vbguest")
        puts("Please install vagrant-vbguest".red)
        puts("vagrant plugin install vagrant-vbguest\n".green)
        exit 1
    end
```

### Executed command
`vagrant plugin install vagrant-vbguest`

### Expected behavior
Vagrant should install specified plugin

### Actual behavior
Vagrant prints information that plugin is not installed, from config above

### Steps to reproduce
1. Update vagrant to 2.1.2 (in previous versions, this doesn't occur)
2. Put above lines in Vagrantfile
3. Run `vagrant plugin install vagrant-vbguest` with Vagrantfile present in current directory

### References
Issue is caused by commit: https://github.com/hashicorp/vagrant/commit/1bba1f86bbec387a9297ffd0b705783805b959df, especially by removing  `opts[:vagrantfile_name] = ""` when `plugins` command is invoked. That causes vagrant to parse Vagrantfile when plugins are installing.

**Comment by AntonioMeireles** [comment]
@gbdlin afaict, at sight, fixed by #10030 (relates to #10013 (workaround [here](
https://github.com/hashicorp/vagrant/issues/10013#issuecomment-407553559)) / #9972)

**Comment by briancain** [comment]
Hi @gbdlin - @AntonioMeireles is correct, this was fixed by #10030 and the fix will be out in the next release of Vagrant. For now I just recommend installing the previous version until we can get the fix pushed out. Thanks!

**Comment by herpaderpaldent** [comment]
getting errors too:

those are my lines

```
plugins_dependencies = %w( vagrant-docker-compose )
plugin_status = false
plugins_dependencies.each do |plugin_name|
  unless Vagrant.has_plugin? plugin_name
    system("vagrant plugin install #{plugin_name}")
    plugin_status = true
    puts " #{plugin_name}  Dependencies installed"
  end
end

# Restart Vagrant if any new plugin installed
if plugin_status === true
  exec "vagrant #{ARGV.join' '}"
else
  puts "All Plugin Dependencies allready installed"
end
```

**Comment by chrisroberts** [comment]
Please see: https://github.com/hashicorp/vagrant/issues/10161#issuecomment-417701063
