### ISSUE TITLE
Vagrant provision with chef client STDOUT

### ISSUE THREAD

**Issue by jurek7** [hashicorp/vagrant#1006]
Is this this possible to enable STDOUT from chef client recipes after launch vagrant provision?
Now i only see e.g: 

INFO: ruby_block[test] called
INFO: ruby_block[test2] called

**Comment by bassrock** [comment]
Is there a workaround for this? I am trying to see the full chef output, when using ```vagrant provision``` When I run chef after a vagrant ssh I can see all the live output, however when using vagrant provision I only see some very basic output only after each block has executed.
