### ISSUE TITLE
Vagrant playing up after installing docker

### ISSUE THREAD

**Issue by spawankumar** [hashicorp/vagrant#10070]
**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Vagrant 2.1.2

### Host operating system
Win 10 pro

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
C:\Users\pawan>vagrant up
Bringing machine 'logger' up with 'virtualbox' provider...
Bringing machine 'dc' up with 'virtualbox' provider...
Bringing machine 'wef' up with 'virtualbox' provider...
Bringing machine 'win10' up with 'virtualbox' provider...
==> logger: Checking if box 'bento/ubuntu-16.04' is up to date...
==> logger: Resuming suspended VM...
==> logger: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "aa9d78bd-3322-4b5d-949a-38afecc5858e", "--type", "gui"]

Stderr: VBoxManage.exe: error: Raw-mode is unavailable courtesy of Hyper-V. (VERR_SUPDRV_NO_RAW_MODE_HYPER_V_ROOT)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

### Expected behavior
What should have happened?
vagrant should have to spin up all my vm as per config
### Actual behavior
What actually happened?
After installing docker my vagrant wasnt opening up.  Currently ive uninstalled docker so that I could use vagrant.  Hyper V has been unselected. Virtual box have reinstalled and few restarts on the system was done. 
_V_
- ...

**Comment by briancain** [comment]
Hi there - you likely still have some Hyper-V related libraries still lying around. I recommend reading this post on [stackoverflow](https://stackoverflow.com/questions/50053255/virtualbox-raw-mode-is-unavailable-courtesy-of-hyper-v-windows-10). Thanks!
