### ISSUE TITLE
Vagrant Powershell interleaving with host powershell

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/vagrant#10088]
I am not sure exactly at what point this happens, but I get commands that are running on the guest Powershell session (from `vagrant powershell`) and then some commands run on the host's PowerShell session. 

### Vagrant version
Vagrant 2.1.2
Virtual Box 5.2.16r123759

### Host operating system
Windows 8.1

### Guest operating system
Windows 2016

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "my/windows2016"
end
```

### Expected behavior

After `vagrant powershell` session, commands would only run on the guest.

### Actual behavior

With `vagrant powershell` session active, some commands run on host, some commands run on guest.

### Steps to reproduce

1. `vagrant init my/windows2016`
2. `vagrant up`
3. `vagrant powershell`
4. type some commands.

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. If you can include why you think you are seeing commands running on the host that would help us reproduce your issue. Thanks!

**Comment by darkn3rd** [comment]
In Japan at the moment, so have no access to Windows host.  I can get this later (after Aug 28).

**Comment by briancain** [comment]
Have you been able to attempt to reproduce your issue?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
