### ISSUE TITLE
Vagrant guests not appearing in VBox Manager GUI

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/vagrant#10082]
### Vagrant version
Vagrant 2.1.2
Virtual Box 5.2.16r123759

### Host operating system
Windows 8.1

### Guest operating system
Windows 2016
Manjaro 17

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "mloskot/manjaro-i3-17.0-minimal"
  config.vm.box_version = "1.0.0"
end
```

### Expected behavior

Vagrant created systems would appear in VirtualBox Manager GUI.

### Actual behavior

Guest systems created by Vagrant are not appearing in the VirtualBox Manager GUI.

### Steps to reproduce
0. Open PowerShell (with Run As Administrator mode), `mkdir mymanjaro`, `sl mymanjaro`
1. `vagrant init mloskot/manjaro-i3-17.0-minimal`
2. `vagrant up`
3. open Virtualbox Manager application

### Debug Gist

https://gist.github.com/darkn3rd/d62a698c035da3e9b9de0d7840d74671

### Notes
I created systems using Test Kitchen, Docker-Machine, and MiniKube, and all guest systems they create register fine with Virtualbox and appear there.  However, systems created with Vagrant do not seem to be registering.  I created both a Manjaro linux guest system, and a Windows 2016 guest system.

In the command line tool, the systems are there, but for whatever reason, they do not show for ones created in Vagrant.  

```PowerShell
vboxmanage list runningvms | ForEach-Object {$_.Split('"')[1]}
default
minikube
default-ubuntu-1604_default_1533101176498_15519
default-centos-7_default_1533101311605_33025
mymanjaro_default_1533104982161_27022
mywindows_default_1533137872957_21551
```

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by darkn3rd** [comment]
What command should I run the --debug on?  The `vagrant up`?

**Comment by mrsombre** [comment]
@darkn3rd in virtualbox machines created by admin and user stored in different environments.
Check exactly that you run vb gui and vagrant from the same user.

**Comment by darkn3rd** [comment]
@mrsombre https://gist.github.com/darkn3rd/d62a698c035da3e9b9de0d7840d74671

**Comment by darkn3rd** [comment]
The `vagrant status` does that it is successfully running.  The `vboxmanage list runningvms` command lists all the images.

**Comment by briancain** [comment]
@darkn3rd - if you create a vm with the `vboxmanage startvm` cli tool, does it appear in the virtualbox gui? For example, this is the command in your debug gist that Vagrant used to start a vm...

```ruby
INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "startvm", "bd8e12b1-6665-4c9c-a862-34f8859c92a6", "--type", "headless"]
```

You might need to use a different uuid or vmname as an argument.

I can't seem to reproduce this on my windows machine with virtualbox and Vagrant 🤔

**Comment by darkn3rd** [comment]
Ack this, have to wait until I get back to US, no access to Windows box until Aug 28.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
