### ISSUE TITLE
Do not require base_mac on import

### ISSUE THREAD

**Issue by chrisroberts** [hashicorp/vagrant#10080]
Remove requirement of `base_mac` when importing guests with the VirtualBox provider. By default it should allow the mac addresses to be regenerated if no base_mac is provided. Needs investigation on change impact and possible addition of user warnings when multi guest setup is in use.

Related: #9200

**Comment by pisymbol** [comment]
There is currently no real workaround I can come up with. The suggestions made in #9200 do not work for me.
