### ISSUE TITLE
Error assigning IPs to private network interfaces during `vagrant up`. Loopback interfaces are not always filtered out.

### ISSUE THREAD

**Issue by jmaness** [hashicorp/vagrant#10098]
### Vagrant version
Vagrant 2.1.2

### Host operating system
macOS High Sierra 10.13.6

### Guest operating system
Cumulus Linux 3.6.2

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "mgmt1" do |mgmt1|
    mgmt1.vm.box = "CumulusCommunity/cumulus-vx"
    mgmt1.vm.network "private_network", ip: "10.5.5.254", nic_type: "virtio"
  end
end
```

### Debug output
https://gist.github.com/jmaness/e677be19c79c03fa7601c95a399f770d

### Expected behavior
The private network IP should have been associated to a network interface. Loopback interfaces should also be filtered out so that the private network IP is not associated to one of them.

This is also an issue if the IP is dynamically assigned (i.e. `type: "dhcp"`).

### Actual behavior
An error occurred because of an issue parsing the names of the network interfaces.

```/sbin/ifdown '' || true
/sbin/ip addr flush dev ''
# Remove any previous network modifications from the interfaces file
sed -e '/^#VAGRANT-BEGIN/,$ d' /etc/network/interfaces > /tmp/vagrant-network-interfaces.pre
sed -ne '/^#VAGRANT-END/,$ p' /etc/network/interfaces | tac | sed -e '/^#VAGRANT-END/,$ d' | tac > /tmp/vagrant-network-interfaces.post
cat \
  /tmp/vagrant-network-interfaces.pre \
  /tmp/vagrant-network-entry \
  /tmp/vagrant-network-interfaces.post \
  > /etc/network/interfaces
rm -f /tmp/vagrant-network-interfaces.pre
rm -f /tmp/vagrant-network-entry
rm -f /tmp/vagrant-network-interfaces.post

/sbin/ifup ''

Stdout from the command:



Stderr from the command:

error: cannot find interfaces:  (interface was probably never up ?)
Device "" does not exist.
error: /etc/network/interfaces: line15: invalid auto line 'auto'
error: /etc/network/interfaces: line16: iface inet: unsupported address family 'static'
error: cannot find interfaces: 
```

### Steps to reproduce
1. With the Vagrantfile above, run `vagrant up --debug`

### References
PR with a proposed fix - https://github.com/hashicorp/vagrant/pull/10092

**Comment by briancain** [comment]
Closing since the PR has been merged!
