### ISSUE TITLE
yum update command is not working on centos 7

### ISSUE THREAD

**Issue by irfanjs** [hashicorp/vagrant#10094]
Using VirtualBox , i have spin up the CentOS 7 VM. able to successfully login to box and execute few commands.
however, `yum update` command is not working. the command prints all the packages needs to be updated and installed , but moment i press the yes button , it throws the following error :
```
 sudo                     x86_64 1.8.19p2-14.el7_5                updates 1.1 M
 yum-plugin-fastestmirror noarch 1.1.31-46.el7_5                  updates  33 k
 yum-utils                noarch 1.1.31-46.el7_5                  updates 120 k

Transaction Summary
================================================================================

Install   1 Package
Upgrade  40 Packages

Total size: 153 M
Total download size: 67 M
Downloading packages:
/usr/share/doc/e2fsprogs-1.42.9/COPYING: No such file or directory
cannot reconstruct rpm from disk files
/usr/share/doc/yum-plugin-fastestmirror-1.1.31/COPYING: No such file or directory
cannot reconstruct rpm from disk files

kernel-3.10.0-862.9.1.el7. 78% [============    ]  0.0 B/s |  36 MB   --:-- ETA
kernel-3.10.0-862.9.1.el7. 78% [============-   ]  32 kB/s |  36 MB   05:20 ETA
kernel-3.10.0-862.9.1.el7. 78% [============-   ]  34 kB/s |  36 MB   04:58 ETA
kernel-3.10.0-862.9.1.el7. 78% [============-   ]  41 kB/s |  36 MB   04:08 ETA
```  
Vagrantfile used is as follows:

```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
  config.vm.provider :virtualbox do |vb|
  
  vb.memory = "3024"
  vb.cpus = "4"
end
end
``` 
not getting what is the issue with yum update ... 
vagrant version : 2.0.2
oracle VirtualBox version : Version 5.2.6 r120293 (Qt5.6.2)

please suggest 
Regards,

**Comment by briancain** [comment]
I suggest maybe using the `bento/centos-7.2` box and seeing if that works for you. However this is not a Vagrant bug so I'm going to go ahead and close this issue. If you would like any more help I recommend emailing the Vagrant up mailing list. Thanks!
