### ISSUE TITLE
Stderr: VBoxManage: error: Could not find a registered machine with UUID on first vagrant up

### ISSUE THREAD

**Issue by valjar** [hashicorp/vagrant#10107]
### Vagrant version
Vagrant 2.1.2

### Host operating system
MacOS High Sierra
Version 10.13.5

### Guest operating system
Ubuntu 16.04 
Following boxes all have the same issue

- hashicorp-vagrant/ubuntu-16.04
- ubuntu/xenial64
- bento/ubuntu-16.04 

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    config.vm.provider :virtualbox do |vb|
        vb.name = "certify-dev"
        vb.customize ["modifyvm", :id, "--memory", 4252, "--cpus", "1", '--cableconnected1', 'on']
    end
    config.vm.box = "bento/ubuntu-16.04"
    config.vm.provision :shell, keep_color: true, path: "provision.sh"

    ## sync folder path for different users
    config.vm.synced_folder "/Users/davorpecnik/workspace/certify", "/home/vagrant/workspace/certify", type: "nfs", nfs_udp: false, mount_options: ['rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=2']

	config.vm.define "certify" do |node|
        node.vm.hostname = 'certify-dev'
        node.vm.network :private_network, ip: "192.168.100.100"
        # I have also tried with :private_network, :public_network, ip or dhcp options. Result is always the same
        node.vm.hostname = "certify.test"
    end

end
```

### Debug output
without debug option 
https://gist.github.com/valjar/bcfd4ef466fb3fb3664b139a430e47d6

with debug option
https://gist.github.com/valjar/3472c5a857aa1953c526039ce64d4e86

### Expected behavior
On first vagrant up, virtual box should start and provision

### Actual behavior
When vagrant up comes to Configuring and enabling network interfaces, errors are thrown and virtual machine is not created

```ruby
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "1bb94e06-bf08-479b-99ae-7f7cd5e41bc5", "--machinereadable"]

Stderr: VBoxManage: error: Could not find a registered machine with UUID {1bb94e06-bf08-479b-99ae-7f7cd5e41bc5}
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2834 of file VBoxManageInfo.cpp
```

### Steps to reproduce
1. Vagrant up

Already provisioned vagrant boxes (with ubuntu 16.04 version) are working properly, so there is a problem just creating a new ones

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
