### ISSUE TITLE
Vagrant up failed for windows RS4 arabic language with chef-solo provision

### ISSUE THREAD

**Issue by sharavanan2010** [hashicorp/vagrant#10108]
### Vagrant version
vagrant 2.0.2
vagrant-omnibus 1.5.0
vagrant-vmware-desktop 1.0.0
python 3.4

### Host operating system
Windows 7

### Guest operating system
windows 10 enterprise RS4 32bit Arabic

### Vagrantfile

```ruby
Vagrant.configure(2) do |config|
  config.vm.communicator = "winrm"

  config.vm.box = "windows_10_enterprise_rs4_32_ara_vmware"
  config.vm.box_url = "https://x.y.com/repo/folderName/windows-10/windows_10_enterprise_rs4_32_ara_vmware.box"
  config.vm.box_download_insecure = true

  config.omnibus.chef_version = :latest
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "C:\\devstack\\windows_10_enterprise_rs4_32_ara_vmware-1"
    chef.add_recipe "cookbook::mason"
  end

  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.winrm.transport = :plaintext
  config.vm.guest = :windows
  config.windows.halt_timeout = 120

  config.vm.provider "vmware_workstation" do |v|
    # Display the VirtualBox GUI when booting the machine
    v.gui = true

    # Customize the amount of memory on the VM:
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
	  v.vmx["isolation.tools.dnd.enable"] = "TRUE"
    v.enable_vmrun_ip_lookup = false
    v.ssh_info_public = true
  end
end
```

### Debug output
https://gist.github.com/sharavanan2010/cfcd3ac820e2a20e65e53a43d3187e66

###mason.rb
require 'chef/win32/version'
windows_version = Chef::ReservedNames::Win32::Version.new
execute 'tempdir' do
    command 'mkdir C:\\temp'
    action :run
end
......
......

### Expected behavior
Vagrant should work for any languages supported by windows

### Actual behavior
Vagrant not working for other than ENG language

### Steps to reproduce
1. Try to spin a non-english windows image with chef-solo provisioning.
2. Vagrant up command failed with attached error message

The same provisioning script and provisioner working for english language image. Seems something went wrong here.

If anyone has any thoughts add your comments here. This would really helps to resolve this issue. We're currently blocked with issue to continue regression testing for release.

**Comment by briancain** [comment]
Hello there @sharavanan2010 - From what I can see on your debug gist, the error looks to be coming from chef solo. Specifically the `chef-solo.bat` file [here](https://gist.github.com/sharavanan2010/cfcd3ac820e2a20e65e53a43d3187e66#file-gistfile1-txt-L9511):

```ruby
DEBUG winrmshell: Output: #<WinRM::Output:0x0000000007241bf0 @data=[{:stderr=>"c
hef-solo.bat : C:/opscode/chef/embedded/lib/ruby/2.5.0/win32/registry.rb:72:in `
find': unknown encoding name - CP720 (ArgumentError)\n    + CategoryInfo
  : NotSpecified: (C:/opscode/chef...(ArgumentError):String) [], RemoteException
\n    + FullyQualifiedErrorId : NativeCommandError\n"}, ...
...
```

That error is likely the reason why Vagrant thinks it couldn't find the binary for chef-solo. That said, I did some looking around and it seems like there is a workaround:

- https://stackoverflow.com/a/22861206
- https://github.com/hashicorp/vagrant/issues/6736

It looks like this is an issue with Ruby itself, but those links above have a workaround that should hopefully work for you.

Thanks!
