### ISSUE TITLE
Run Vagrant up failed at Centos7 by Vmware WorkStation12

### ISSUE THREAD

**Issue by tangxuye** [hashicorp/vagrant#10101]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.1.2

### Host operating system
Centos7

### Guest operating system
Centos7

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos7"

  config.vm.define "s1" do |s1|
      s1.vm.hostname = "s1"
      s1.vm.network "private_network", ip: "172.20.20.20"
  end

  config.vm.define "s2" do |s2|
      s2.vm.hostname = "s2"
      s2.vm.network "private_network", ip: "172.20.20.21"
  end

  config.vm.define "s3" do |s3|
      s3.vm.hostname = "s3"
      s3.vm.network "private_network", ip: "172.20.20.22"
  end    

end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output

```
vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
```

### Expected behavior
The virtual servers that I defined in Vagrantfile will be running

### Actual behavior
vagrant up --provider=centos7
The provider 'centos7' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.

### Steps to reproduce
1. vagrant box add centos7 /usr/vagrant/centos7/centos-7.0-x86_64.box 
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'centos7' (v0) for provider: 
    box: Unpacking necessary files from: file:///usr/vagrant/centos7/centos-7.0-x86_64.box
==> box: Successfully added box 'centos7' (v0) for 'virtualbox'!

2.vagrant box list
centos7 (virtualbox, 0)

3.vagrant init centos7
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

4.vim Vagrantfile

5.vagrant up

**Comment by briancain** [comment]
Hi there @tangxuye - do you have virtualbox and or vmware installed on your system? The box you added was a virtualbox machine, but maybe you don't have virtualbox installed since the title of your issue has vmware?

**Comment by tangxuye** [comment]
Yes,I have installed vmware. But the Vagrant official website is declare that it is compatible with the vmware. I am not entangled with this problem at present.It was just a test of my work with Consul Cluster. Thanks for your reply.
