### ISSUE TITLE
Script knowing the provider

### ISSUE THREAD

**Issue by shurick81** [hashicorp/vagrant#10112]
How can I make my provisioning script agnostic to current vagrant provider?
For example, before the complex farm provisioning, I need to run the script that makes sure that machines belong to the same DNS server. However, in order to implement this, I need to make the script aware of what exactly provider is in user currently: is it virtualbox, hyperv or Azure, for example. Thank you in advance.

### Vagrant version
2.1.1

### Host operating system
Windows 10

### Guest operating system
Windows Server 2016

**Comment by chrisroberts** [comment]
Hi there,

This can be done by defining the provision entry within the provider block in the Vagrantfile. Doing this allows for the provision arguments to be tailored to the provider used for the guest. For example:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = 'A_BOX'
  config.vm.provider :virtualbox do |v, override|
    override.vm.provision :shell, path: "./script.sh", args: "virtualbox"
  end
  config.vm.provider :hyperv do |h, override|
    override.vm.provision :shell, path: "./script.sh", args: "hyperv"
  end
end
```

Cheers!
