### ISSUE TITLE
Ansible Local provisioner enhance request - sync folder relative to playbook.yml

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/vagrant#10110]
*Enhancement request*.  Currently, the Ansible Local provisioner just sources the playbook.yml relative to the default mount.  This is an enhancement request to share the directory relative to where it is specified.

This way I can have one location for the code, for example:

```
.
├── centos
│   └── Vagrantfile
├── debian
│   └── Vagrantfile
├── fedora
│   └── Vagrantfile
├── provisioning
│   ├── playbook.retry
│   ├── playbook.yml
│   └── roles
│       └── hello_web
│           ├── defaults
│           │   └── main.yml
│           ├── files
│           │   └── index.html
│           └── tasks
│               └── main.yml
└── ubuntu
    └── Vagrantfile
```

### Vagrant version
```
Vagrant 2.1.2
```

### Host operating system
```
ProductName:	Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
```

### Guest operating system

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "../provisioning/playbook.yml"
    ansible.verbose = true
  end
end
```

### Debug output

n/a for enhancement request, or is it? 

### Expected behavior

I would love it if the directory `provisioning` in this case would be copied or mounted, so that it is accessible on the guest.

### Actual behavior

Errors out : 

```
`playbook` does not exist on the guest: /provisioning/playbook.yml
```

### Steps to reproduce
1. `vagrant up`

Basic structure is the following (if you need test environment)
```bash 
mkdir -p ~/vagrant-ansible/provision/roles
cd ~/vagrant-ansible
mkdir -p ./{debian,centos,fedora,ubuntu}
touch {debian,centos,fedora,ubuntu}/Vagrantfile
# Create Structure with Ansible
mkdir -p provision/roles/hello_web/{defaults,files,tasks}
touch provision/roles/hello_web/{defaults/main.yml,tasks/main.yml}
copy <<-PLAYBOOK > provision/playbook.yml
---
- hosts: all
  gather_facts: yes
  become: true
  roles:
    - hello_web
PLAYBOOK

copy <<-DEFAULTS > provision/roles/hello_web/defaults/main.yml
---
hello_web:
  docroot: /var/www/html
  package: apache2
  service: apache2
DEFAULTS

copy <<-TASKS > provision/roles/hello_web/tasks/main.yml
---
- name: "Install Web Service"
  package:
    name: "{{ hello_web.package }}"
    state: present

- name: "Start Web Service"
  service:
    name: "{{ hello_web.service }}"
    state: started
    enabled: yes

- name: "Copy Content"
  copy:
    src: "{{ role_path }}/files/index.html"
    dest: "{{ hello_web.docroot }}/index.html"
TASKS

cat <<-'HTML' > provision/roles/hello_web/files/index.html
<html>
  <body>
    <h1>Hello World!</h1>
  </body>
</html>
HTML

```

**Comment by gildegoma** [comment]
@darkn3rd Thank you for open this issue.

For this kind of use case, you have to configure the [`provisioning_path`](https://www.vagrantup.com/docs/provisioning/ansible_local.html#provisioning_path) option, and the ansible commands will be executed from this location. 

For instance:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.5"
  config.vm.synced_folder "../provisioning/", "/srv/provisioning"
  config.vm.provision "ansible_local" do |ansible|
    ansible.provisioning_path = "/srv/provisioning"
    ansible.playbook = "playbook.yml"
    ansible.verbose = true
    ...
  end
end
```

Please let me know if this solution works for you.

**Comment by darkn3rd** [comment]
Interesting, I don't missed that one, slaps self. What would be the difference mechanically (or other words config/code wise), between putting the absolute path for `playbook.yml` vs. adding `provisioning_path`?  I was wondering implications between one or the other.

The provisioning path is adequate, avoids the need for this request.  

For the documentation, if you are well versed in Ansible, the explanation is straight forward.  I wish the example matched the explanation (better at reading code, at least I think I am).  Maybe have introduction to simplest configuration in, then continue with the `provisioning_path`, and have an example of that after?

**Comment by gildegoma** [comment]
As stated in the documentation, 

> The ansible-galaxy and ansible-playbook commands are executed from this directory. This is the location to place an ansible.cfg file, in case you need it.

The key advantage of `provisioning_path` (over using the absolute path for the playbook) is the ability to load a local `ansible.cfg` file (which is looked up in the working directory, but relatively to the playbook).

> Maybe have introduction to simplest configuration in, then continue with the provisioning_path, and have an example of that after?

This sounds good to have more examples. The Vagrant documentation is in this same git repository, and pull requests to improve/fix the documentation are always welcome 😍.

I'm closing this issue as I think that the original question has been answered.
