### ISSUE TITLE
Unexpected behaviour of config.vm.hostname

### ISSUE THREAD

**Issue by DominikTo** [hashicorp/vagrant#10125]
According to the [docs](https://www.vagrantup.com/docs/vagrantfile/machine_settings.html) `config.vm.hostname` does the following:

```txt
The hostname the machine should have.
Defaults to nil. If nil, Vagrant will not manage the hostname.
If set to a string, the hostname will be set on boot.
```

### Expected result:
1. Vagrant should set the hostname on the guest.

### Actual result:
1. Vagrant sets the hostname on the guest.
2. AND tries to update `/etc/hosts` on the host.

Updating `/etc/hosts` on the host (2.) is unexpected and in many cases also undesired.
Ideally config.vm.hostname should just set the guest hostname (1.) and nothing else. Updating `/etc/hosts` should be moved to another setting.

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!

**Comment by DominikTo** [comment]
### Vagrant version
Vagrant 2.1.2

### Host operating system
Apple macOS 10.14

### Guest operating system
ubuntu/bionic64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    # config.vm.hostname has unexpected behaviour.
    # According to the docs it sets the hostname on the guest machine,
    # but it actually sets the hostname on the guest machine AND(!)
    # adds an entry to /etc/hosts on the host machine
    config.vm.hostname = "some-host"

    config.vm.provision "shell", inline: <<-SHELL
        echo foo
    SHELL
end
```

### Debug output
n/a here.

### Expected behavior
Vagrant should set the hostname on the guest, as documented.

### Actual behavior
Vagrant sets the hostname on the guest.
AND tries to update /etc/hosts on the host.
Updating /etc/hosts on the host (2.) is unexpected and in many cases also undesired.
Ideally config.vm.hostname should just set the guest hostname (1.) and nothing else. Updating /etc/hosts should be moved to another setting.

### Steps to reproduce
1. Spin up a Vagrant VM using `config.vm.hostname`.

### References
n/a

**Comment by briancain** [comment]
Hi there @DominikTo - Thanks for opening an issue! I've made a pull request to update the documentation around how the configuration settting `hostname` is modifying /etc/hosts.
