### ISSUE TITLE
Windows 10 <--> Windows EC2: unable to sync SMB folders

### ISSUE THREAD

**Issue by degan93** [hashicorp/vagrant#10120]
### Vagrant version
Vagrant 2.1.2 

### Host operating system
Windows 10

### Guest operating system
Windows Server 2016 EC2 Instance

### Vagrantfile

```ruby
Vagrant.require_version ">= 1.6.2"
# Relative path where 'shared-content' can be found
sharedContentRelativePath = '../shared-content'

require 'json'
require 'vagrant-aws'

# Load scenario data configuration file;
scenario = JSON.parse(File.read(File.join(File.dirname(__FILE__), 'deanscenario.json')))
vals = scenario['config']['servers'][0]

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-windows-2016"
    config.vm.box = "C:\\QMI\\AWS-Packer\\packer_amazon-ebs_aws.box"
    config.vm.communicator = "winrm"
    config.vm.hostname = vals["name"]

    # Admin user name and password
    config.winrm.username = "Administrator"
    config.winrm.password = <password from Box File>

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
    config.vm.network :forwarded_port, guest: 445, host: 445, id: "smb", auto_correct: true
    
    # Virtual Machine details
    config.vm.provider :aws do |aws, override|
        aws.access_key_id = 
        aws.secret_access_key = "
        aws.security_groups = <custom security group with TCP, RDP, SSH, WinRM http/https, and SMB ports enabled>
		aws.keypair_name = "Vagrant"
		aws.region = "eu-west-2"
        aws.private_ip_address = 
		aws.ami = <custom ami id generated using Packer>
        aws.instance_type = "t2.micro"
		aws.terminate_on_shutdown = true
        aws.subnet_id = 
    end

    # Shared synced folders setup (Host <-> Guest)
    config.vm.synced_folder '.', '/vagrant', disabled: false, type: "smb", smb_host: <Private IP of my host machine>, smb_username: <myUsername@companyDomain, smb_password: <password used to log into my windows account>, mount_options: ['vers=3.0']

    config.vm.synced_folder "./files", "c:/installations/", disabled: false, type: "smb", smb_host: <Private IP of my host machine>, smb_username: <myUsername@companyDomain, smb_password: <password used to log into my windows account>, mount_options: ['vers=3.0']

    config.vm.synced_folder sharedContentRelativePath, "c:/shared-content/", disabled: false, type: "smb", smb_host: <Private IP of my host machine>, smb_username: <myUsername@companyDomain, smb_password: <password used to log into my windows account>, mount_options: ['vers=3.0']

    # Provision scripts execution
    config.vm.provision :shell, path: sharedContentRelativePath + "/scripts/modules/q-bootstrap.ps1"
    config.vm.provision :shell, path: "./scripts/provisioner.ps1"

end
```

##############################################################################

Vagrant creates the EC2 instance just fine.
It then creates the three folders on the EC2 instance (C:\vagrant C:\installations and C:\shared-content). Here is the powershell output:
    vagrant-windows-2016: C:/QMI/qmi-scenarios/deanscenario => /vagrant
    vagrant-windows-2016: C:/QMI/qmi-scenarios/deanscenario/files => c:/installations
    vagrant-windows-2016: C:/QMI/qmi-scenarios/shared-content => c:/shared-content

It then says that it is running the provisioner:
==> vagrant-windows-2016: Running provisioner: shell...
vagrant-windows-2016: Running: ../shared-content/scripts/modules/q-bootstrap.ps1 as c:\tmp\vagrant-shell.ps1

It eventually comes back with script file does not exist:
 vagrant-windows-2016: Copy-Item : Cannot find path 'C:\shared-content\scripts\modules\qmiCLI.psm1' because it does not exist.

This file should exist because of how it synced, so I logged into the EC2 instance and double clicked the shared-content folder and it came back with "Location is not available. C:\shared-content is not accessible. The network path was not found."

I get this for all three folders that were synced.

![image](https://user-images.githubusercontent.com/39345943/44159120-612ea280-a0ae-11e8-9db8-304a0e7d9898.png)

I feel like this is why it is not finding the powershell file.

I have searched high and low to try and figure out why I am being refused access to the folder on the EC2 instance.

Is the following config syntax correct?
  config.vm.synced_folder '.', '/vagrant', disabled: false, type: "smb", smb_host: <Private IP of my host machine>, smb_username: <myUsername@companyDomain, smb_password: <password used to log into my windows account>, mount_options: ['vers=3.0']

Any help on this will be deeply appreciated!

**Comment by soapy1** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier ☹️

Cheers!
