### ISSUE TITLE
how to fix it thank you !

### ISSUE THREAD

**Issue by qth1991** [hashicorp/vagrant#10122]
![tim 20180816211905](https://user-images.githubusercontent.com/39185602/44211126-dc6d8280-a19a-11e8-9fb4-4886cb764706.png)

**Comment by briancain** [comment]
Hello there @qth1991 - the stacktrace you shared is an issue with the [vagrant-libvirt](https://github.com/vagrant-libvirt/vagrant-libvirt) provider. Please open an issue with them instead. Thanks!
