### ISSUE TITLE
Vagrant 2.1.2 + Windows 8.1 + Hyper-V

### ISSUE THREAD

**Issue by bircoe** [hashicorp/vagrant#10132]
vagrant up fails on Vagrant 2.1.2 + Windows 8.1 + Hyper-V with the below error:

`Failed to configure virtualization extensions: A parameter cannot be found that matches parameter name 'ExposeVirtualizationExtensions'.`

After researching the problem I discovered ExposeVirtualizationExtensions is a feature of Windows 10/Server 2016, I commented line 538 in:
c:\HashiCorp\Vagrant\embedded\gems\2.1.2\gems\vagrant-2.1.2\plugins\providers\hyperv\scripts\utils\VagrantVM\VagrantVM.psm1

`    #Hyper-V\Set-VMProcessor -VM $VM -ExposeVirtualizationExtensions $Enabled`

Which almost got me there but I got another error:

`Failed to disable checkpoints on VM: A parameter cannot be found that matches parameter name 'CheckpointType'.`

Again this is a feature of Windows 10/Server 2016 so I commented out line 91 in:
c:\HashiCorp\Vagrant\embedded\gems\2.1.2\gems\vagrant-2.1.2\plugins\providers\hyperv\scripts\configure_vm.ps1

`#Hyper-V\Set-VM -VM $VM -CheckpointType $checkpoints`

The above 2 changes result in a successful build.

Wrapping these commands in an if block to identify the Hyper-V version would resolve the build issues.
`if ((Get-Item c:\windows\system32\vmms.exe).VersionInfo.FileVersion.Split(".")[2] -gt '9600') { 
  Hyper-V\Set-VMProcessor -VM $VM -ExposeVirtualizationExtensions $Enabled
}`

I have tested the above if block and can confirm that it works but it would need further testing, I believe it should work as the Hyper-V version seems to match the Windows version numbers so a build greater than 9600 would indicate Windows 10/Server 2016.

I know Windows 8.1 is not super common but in some larger organisations that roll out new Windows slowly Windows 8.1 is still common.

### Vagrant version
Vagrant 2.1.2

### Host operating system
Microsoft Windows 8.1 Enterprise (6.3.9600.0)

**Comment by chrisroberts** [comment]
Hi there,

This is fixed by #10079 and will be available in the next release.

Cheers!

**Comment by tellmewhy99** [comment]
Hello, I got this issue too, any quick workaround for the CheckpointType, please?

**Comment by RockAfeller2013** [comment]
Is this bug fixed, I am still having this issues on the latest vagrant, ive logged a bug report 

https://github.com/hashicorp/vagrant/issues/11409
