### ISSUE TITLE
'Vagrant up' triggered by systemd process cannot start VM with gui

### ISSUE THREAD

**Issue by jamestylerwarren** [hashicorp/vagrant#10137]
Vagrant Version
----------------------
2.12

Virtualbox Version
-------------------------
5.2.10_Ubuntu r121806

Host OS
----------------
ubuntu 18.04 amd64 desktop

Guest OS
------------------
fedora 25
 
I have systemd service (located in /etc/systemd/system/) that watches for changes in /vagrant/Vagrantfile on an ubuntu 18 host machine. If it sees changes, the service calls a shell script (also located in /etc/systemd/system/) that 'vagrant up' 's a fedora 25 guest VM. This starts the vagrant machine, but it errors out: 
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant

for controlling VirtualBox. The command and stderr is shown below.


Command: ["startvm", "xxxxxxxxxx", "--type", "gui"]
```

Expected Behavior
---------------------
VM startup with Virtualbox Gui

Actual Behavior
---------------------
VM errors out with above error code

???
--------------------
Could this be a permissions problem? I can chdir into /vagrant and start the machine with 'vagrant up', and the service I've created is working correctly, they just aren't working in tandom

Maybe related -- I also use Ansible to provision this environment to multiple Ubuntu machines in hopes of using vagrant to spin up a VM, including the gui. However, even using the Ansible 'command' and 'shell' modules to 'vagrant up' the machine, I receive this same error.....

Also, I posted under this issue - https://github.com/hashicorp/vagrant/issues/9911

THANKS!!
----------------

**Comment by chrisroberts** [comment]
Hi there,

It cannot be started due to the user attempting to start the process not having GUI environment available. You'll need to update your Vagrantfile to configure the guest to start "headless" which will allow it start and not require a GUI environment:

```ruby
Vagrant.configure("2") do |config|
  ...
  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end
end
```

https://www.vagrantup.com/docs/virtualbox/configuration.html#gui-vs-headless

Cheers!
