### ISSUE TITLE
Path resolution is bugged

### ISSUE THREAD

**Issue by L3tum** [hashicorp/vagrant#10144]
### Vagrant version
2.1.2

### Host operating system
Windows 10

### Guest operating system
ubuntu/trusty64

### Vagrantfile
Does not really matter in this case

### Debug output
Folder C:\Users\UserName\username does not exist
C:\HashiCorp\Vagrant\embedded\gems\2.1.2\gems\vagrant-2.1.2\lib\vagrant\environment.rb:228

### Expected behavior
vagrant should work

### Actual behavior
My VAGRANT_HOME is C:\Users\Username\\.vagrant.d. When Vagrant tries to do its magic with that path in the file mentioned above, it tries to manually resolve that path. While doing so it apparently picks up another folder, called 'username' somewhere. In the file above, on line 237, vagrant compares the found folder, 'username', to each part in the path, so 'Users' and 'Username'. The only issue is that it does that by lowercasing every part, so it compares 'username' and 'username' and thinks it found the correct folder. Due to there being nothing in the 'username' folder, vagrant will not try to resolve the path further. This means that vagrants home suddenly becomes C:\Users\Username\username. In my case this folder does not exist and creates an error, but even if it did exist vagrant chose the wrong folder. 

This happened after I created a user in my WSL named 'username' which probably means that vagrant picks up a wrong folder from somewhere as well, but that's too deep for me. 

A followup error to that is, if I create that folder and everything, vagrant will for some reason try to mount C:\Users\Username\username to every mount I specified in my Vagrantfile, but that's probably due to the issue mentioned here. 

A proposed solution would be to change line 237 from 

```ruby
if entry.downcase == single.downcase
```

to

```ruby
if entry== single
```

But i don't know if that messes up something else. So far it seems to work. 

### Steps to reproduce
1. Create a folder 'username' under your 'Username' folder in C:\Users
2. Start cmd and type 'vagrant' (you might need a valid vagrant file for it to actually try to access this folder, don't know about the workings of vagrant)
3. Presto

### References
I skimmed through the other issues but didn't find any title that implicated this issue.

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
