### ISSUE TITLE
`vagrant ssh -c` may not work in multi-machine environment

### ISSUE THREAD

**Issue by szamuboy** [hashicorp/vagrant#10145]
### Vagrant version
Vagrant 2.1.2

### Host operating system
Linux (Ubuntu Bionic)

### Guest operating system
Linux

### Vagrantfile
Whatever valid Vagrantfile that controls multiple guest VMs

### Debug output
```
$ vagrant ssh -c 'ls /' debian-9 --debug
```

```
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x000000000160fa30>
DEBUG checkpoint_client: starting plugin check
 INFO cli: CLI: [] "ssh" ["-c", "ls", "/", "debian-9"]
DEBUG checkpoint_client: plugin check complete
DEBUG cli: Invoking command class: VagrantPlugins::CommandSSH::Command ["-c", "ls", "/", "debian-9"]
DEBUG checkpoint_client: no information received from checkpoint
DEBUG command: Getting target VMs for command. Arguments:
DEBUG command:  -- names: ["/", "debian-9"]
DEBUG command:  -- options: {:single_target=>true}
DEBUG command: Finding machine that match name: /
 INFO loader: Set :root = ["#<Pathname:/home/xxx/Vagrantfile>"]
DEBUG loader: Populating proc cache for #<Pathname:/home/xxx/Vagrantfile>
DEBUG loader: Load procs for pathname: /home/xxx/Vagrantfile
 INFO loader: Loading configuration in order: [:home, :root]
DEBUG loader: Loading from: root (evaluating)
DEBUG loader: Configuration loaded successfully, finalizing and returning
DEBUG push: finalizing
 INFO environment: Running hook: environment_unload
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/gergely/go/src/github.com/origoss/ebpf/kvt>]
DEBUG host: Trying: alt
DEBUG host: Trying: arch
DEBUG host: Trying: darwin
DEBUG host: Trying: freebsd
DEBUG host: Trying: gentoo
DEBUG host: Trying: redhat
DEBUG host: Trying: slackware
DEBUG host: Trying: suse
DEBUG host: Trying: bsd
DEBUG host: Trying: linux
 INFO host: Detected: linux!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000000010e10b8>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::MachineNotFound: The machine with the name '/' was not found configured for
this Vagrant environment.>
ERROR vagrant: The machine with the name '/' was not found configured for
this Vagrant environment.
ERROR vagrant: /tmp/.mount_vagrangzlIIA/usr/gembundle/gems/vagrant-2.1.2/lib/vagrant/vagrantfile.rb:117:in `machine_config'
```

### Expected behavior
Execute the `ls /` command on the machine `ubuntu-9`

### Actual behavior
Error message: `The machine with the name '/' was not found configured for
this Vagrant environment.`

### Steps to reproduce
1. Create a valid Vagrantfile that controls [multiple guest machines](https://www.vagrantup.com/docs/multi-machine/).
2. Run `vagrant ssh -c` against any provisioned guest machine. When the command contains whitespace, `vagrant ssh` will fail. Otherwise it succeeds.

**Comment by briancain** [comment]
Hello @szamuboy - based on the debug output you provided, it looks like the command you actually ran (or the command your shell actually ran) was this:

```
vagrant ssh -c ls / debian-9
```

From the debug output....

```ruby
 INFO cli: CLI: [] "ssh" ["-c", "ls", "/", "debian-9"]
```

When I try to reproduce this myself, the ssh command works as expected:

```text
brian@localghost:vagrant-sandbox % be vagrant ssh -c 'ls /' bork                                                         ±[●●][master]
bin   dev  home        initrd.img.old  lib64	   media  opt	root  sbin  srv  tmp  vagrant  vmlinuz
boot  etc  initrd.img  lib	       lost+found  mnt	  proc	run   snap  sys  usr  var      vmlinuz.old
Connection to 127.0.0.1 closed.
```

Or when I don't use quotes

```
brian@localghost:vagrant-sandbox % be vagrant ssh -c ls / bork                                                           ±[●●][master]
The machine with the name '/' was not found configured for
this Vagrant environment.
```

I would make sure your shell isn't removing the quotes you are adding when you invoke commands. I'm guessing that is probably the issue? Maybe your shell would be fine if you used double quotes?

**Comment by szamuboy** [comment]
Thank you @briancain for your attempt on reproducing my issue.
Unfortunately, the issue persists on my setup with the correct quoting (both with `"` and `'`). Maybe I'm the only one struggling with this issue. I created a [gist](https://gist.github.com/szamuboy/fbcadfb79d7ad1abea1137a3269a1bda) that shows the issue in more detail.

**Comment by moench-tegeder** [comment]
The correct way to use ssh -c is:
`vagrant ssh host1 -c "ls / /tmp"`
(box first, then command) or
`vagrant ssh host1 -c "ls '/some dir'"`
(note mix of double and single quotes). Alternatively, use
`vagrant ssh host1 -- "ls -l '/some dir'"` .

**Comment by chrisroberts** [comment]
@szamuboy I have been unable to reproduce this behavior locally. My hunch is that there is something loaded within your shell that is interfering with the shell words being split apart. You might try running bash with `--norc` and `--noprofile` to see if that makes any difference. You can also try @moench-tegeder's suggestion of re-ordering to ensure the guest name is defined before the command options.

If you are able to determine that Vagrant is doing something incorrectly that is causing the issue, please do open a new issue. However, at this point I can find no way to reproduce the behavior you have described/shown.

Cheers!
