### ISSUE TITLE
vagrant provision should download remote script

### ISSUE THREAD

**Issue by ferrarimarco** [hashicorp/vagrant#10152]
### Vagrant version
Vagrant 2.1.3

### Host operating system
Windows 10

### Guest operating system
Ubuntu 18.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpus", 1]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--memory", 512]
  end

  provisioning_script_url = "https://raw.githubusercontent.com/ferrarimarco/dotfiles/master/bin/install-linux.sh"

    config.vm.provision "shell" do |s|
      s.path = provisioning_script_url
      s.args = [
        "test"
        ]
    end
end
```

### Debug output
N/A

### Expected behavior
We should be able to specify a "force download" option for remote scripts when manually running `vagrant provision`. Currently a remote script is downloaded just once (on `vagrant up`).

### Actual behavior
Even with `vagrant provision` remote scripts are downloaded just the first time.

### Steps to reproduce
1. vagrant up
2. vagrant provision

**Comment by briancain** [comment]
Hey there @ferrarimarco - from my testing, it looks like it could be just that Vagrant is receiving a cached version of a file from GitHub. If you update a remote script and push it up to GitHub and immediately run `vagrant provision`, it ends up with the old file. But I noticed after a few more attempts it does eventually get the new updated script In that case I'm going to close this, as the shell provisioner is working as expected. I would just wait a few moments before running the provision command after pushing your changes to your dotfiles repo. Thanks!
