### ISSUE TITLE
Problem with windows installer package

### ISSUE THREAD

**Issue by christerjohansson** [hashicorp/vagrant#10162]
### Vagrant version
2.1.2

### Host operating system
Windows 10 Professional

### Guest operating system
Linux Ubuntu

### Vagrantfile
```ruby
# Not applicable
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
Vagrant should update itself to the current version, 2.1.4.

### Actual behavior
Installer quit prematurely due to DLL that could not be run.
The error message says: There is a problem with this Windows Installer Package. A DLL required for this install to complete could not be run. Contact your support personnel och package vendor.

### Steps to reproduce
1. Download latest MSI-package from Vagrant website
2. Run installer.
3. The world is your oyster.
![vagrant_issue](https://user-images.githubusercontent.com/3787897/44921492-faaeb300-ad42-11e8-8685-036f383496a2.png)

**Comment by christerjohansson** [comment]
And yes, I did try to run it as Administrator. Both in command console and Power Shell with msiexec.

**Comment by chrisroberts** [comment]
@christerjohansson If you uninstall vagrant from the system, and then install the package again, do you still receive the same error message?

**Comment by christerjohansson** [comment]
Apparantly it is a problem with the UAC in Windows 10. To fix it, you go to C:\Users\YOURUSERNAME\AppData\Local\ and ricght click the folder 'Temp', then select Security and and add yourself as a user to that folder with FULL RIGHTS. Then, when you run the installer, it will work.
