### ISSUE TITLE
Can't vagrant up always with these error?

### ISSUE THREAD

**Issue by honkkki** [hashicorp/vagrant#10177]
Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting \\?\C:\Users\Administrator\.vagrant.d\boxes\laravel-VAGRANTSLASH-homestead\6.1.0\virtualbox\box.ovf...
OK.
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not create the imported medium 'C:\Users\Administrator\VirtualBox VMs\ubuntu-18.04-amd64_1528981308408_40115\ubuntu-18.04-amd64-disk001.vmdk'.
VBoxManage.exe: error: VMDK: Compressed image is corrupted '\\?\C:\Users\Administrator\.vagrant.d\boxes\laravel-VAGRANTSLASH-homestead\6.1.0\virtualbox\ubuntu-18.04-amd64-disk001.vmdk' (VERR_ZIP_CORRUPTED)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(struct HandlerArg *)" at line 886 of file VBoxManageAppliance.cpp

**Comment by cbj4074** [comment]
What is the SHA1 hash of the disk image file, `C:\Users\Administrator\.vagrant.d\boxes\laravel-VAGRANTSLASH-homestead\6.1.0\virtualbox\ubuntu-18.04-amd64-disk001.vmdk`?

If it's not `5851150903A809CC3C09EB80F35C0150D2085E08`, then it appears that your download was corrupted in some capacity. Have you tired re-downloading it?

**Comment by honkkki** [comment]
Thx bro!  I will try to solve the problem.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Comment by paksniper** [comment]
hi i stuck in this problem as well

**Comment by cbj4074** [comment]
@paksniper Then I would do as @briancain suggested above: open a new issue, fill-out the template, and submit.

**Comment by paksniper** [comment]
@cbj4074 Thanks bro anyway i solved it by destroying the box and reinstalling it ...
