### ISSUE TITLE
Failed to connect to hashicorp-files.hashicorp.com port 443: Timed out

### ISSUE THREAD

**Issue by PandaBoi57** [hashicorp/vagrant#10173]
### Vagrant version
Vagrant 2.1.4

### Host operating system
Windows 8.1

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "lucid32"

  config.vm.box_url = "http://files.vagrantup.com/lucid32.box"

  $script = %Q{
    sudo apt-get update
    sudo apt-get install nasm make build-essential grub qemu zip -y
  }

  
  config.vm.provision :shell, :inline => $script
  
end
```

### Expected behavior
Downloading lucid32

### Actual behavior
A timed out error

### Steps to reproduce
1. Run `vagrant box add lucid32 http://files.vagrantup.com/lucid32.box

**Comment by briancain** [comment]
Hi there @PandaBoi57 - That box is no longer hosted on that URL. I recommend finding one on [Vagrant Cloud](http://vagrantcloud.com/) instead. Thanks!

**Comment by reza1987** [comment]
http://www.github.com/
