### ISSUE TITLE
Vagrant 2.1.4 seems to parse Vagrantfile twice

### ISSUE THREAD

**Issue by kikitux** [hashicorp/vagrant#10186]
reported on the mailing list

Vagrant 2.1.4 seems to parse the Vagrantfile twice. where 2.1.3/2.1.2 did parse it once.

### Vagrant version
2.1.4

### Host operating system
macos

### Guest operating system
not needed

### Vagrantfile
```
puts "Loading Vagrantfile"
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
end
```

### Expected behavior
puts happen once

### Actual behavior
puts happen twice

### Steps to reproduce
install vagrant 2.1.4
run vagrant status

### References
None found

**Comment by zenonuk** [comment]
This bug is also responsible for breaking our Vagrantfile using ruby variables.  See snippet below.

The provisioning fails because the entered (user input) values are not passed to the provisioning script.  Printing the contents of the variables shows the reported defect... the print is executed twice, first with the correct user input values and a second time second without.

```
Vagrant.configure("2") do |config|

  username = nil
  password = nil
  if ARGV[0] == "up"
    machines = ARGV
    machines.shift
    machines.each do |name|
      if Dir.glob("#{File.dirname(__FILE__)}/.vagrant/machines/#{name}/*/*").empty? && username.nil?
        begin
          system 'stty -echo'
          print "Nexus username: "
          username = STDIN.gets.chomp
          print "\nNexus password: "
          password = STDIN.gets.chomp
          print "\n"
        ensure
          system 'stty echo'
        end
      end
    end
  end
  
  print "'#{username}' '#{password}' admin\n"

  config.vm.define "admin" do |admin|
    admin.vm.network "private_network", ip: "192.168.50.4"
    admin.vm.hostname = "admin.local"
    admin.vm.box = "bento/centos-7.2"
    admin.vm.network "forwarded_port", guest: 80, host: 8000
    admin.vm.network "forwarded_port", guest: 8080, host: 8080
    admin.vm.network "forwarded_port", guest: 8081, host: 8081
    admin.vm.network "forwarded_port", guest: 8082, host: 8082
    admin.vm.provision "shell", path: "provision-always.sh", run: "always"
    admin.vm.provision "shell", path: "provision.sh", args: "'#{username}' '#{password}' admin"
  end

end
```

**Comment by ygt-rclarke** [comment]
Reproducible on Ubuntu 16.04 LTS as well, so it seems to be OS independent, if that helps?

I have ruby constants at the top of my Vagrantfile so get warnings every time I run `status`, `up`, `halt` etc. that look like this:

```
/home/rob/Vagrantfile:3: warning: already initialized constant VAGRANTFILE_API_VERSION
/home/rob/Vagrantfile:3: warning: previous definition of VAGRANTFILE_API_VERSION was here
```

**Comment by briancain** [comment]
Hi all - this is an issue with the latest Vagrant release (2.1.4). We will try to get it fixed and out in the next release, but for now I recommend using the previous release (2.1.3). Thanks for your patience while we get this fixed!

**Comment by bbrala** [comment]
Unfortunately 2.1.3 broke SMB shares (see #10151) which makes it unusable on (some?) Windows hosts.
