### ISSUE TITLE
vagrant share falls into deadlock when ngrok returns error

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/vagrant#10187]
I managed to reproduce this two different ways:

1. enabling UI via config (as described below)
2. spinning up one VM with share via `vagrant share` and trying to spin up another one with a license that is limited to 1

I assume the root cause is the same - `vagrant-share` expecting `ngrok` to always return JSON, even in case of failures.

### Vagrant version

```
2.1.4
```

### Host operating system

macOS Sierra `10.12.6` with Virtualbox `5.2.18,124319` from https://github.com/Homebrew/homebrew-cask/blob/master/Casks/virtualbox.rb

### Guest operating system

[`ubuntu/trusty64`](https://app.vagrantup.com/ubuntu/boxes/trusty64)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get install -y nginx
  SHELL
end
```

### Debug output

UI enabled: https://gist.github.com/radeksimko/5df7c3fd631b1d8c4a782f2f17f7d127
License: https://gist.github.com/radeksimko/58170213f53e20cc6862f06fcd96111f

### Expected behavior

Open tunnel via ngrok

### Actual behavior

```
==> default: Creating Vagrant Share session...
/Users/radeksimko/.vagrant.d/gems/2.4.4/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2409:in `join': No live threads left. Deadlock? (fatal)
2 threads, 2 sleeps current:0x0000000104325090 main thread:0x000000010060a990
* #<Thread:0x00000001008670a8 sleep_forever>
   rb_thread_t:0x000000010060a990 native:0x00007fffac0403c0 int:0
   /Users/radeksimko/.vagrant.d/gems/2.4.4/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2409:in `join'
   /Users/radeksimko/.vagrant.d/gems/2.4.4/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2409:in `start_share'
   /Users/radeksimko/.vagrant.d/gems/2.4.4/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2967:in `execute'
   /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/cli.rb:54:in `execute'
   /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/environment.rb:294:in `cli'
   /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/bin/vagrant:164:in `<main>'
* #<Thread:0x0000000100b7f4c0@/Users/radeksimko/.vagrant.d/gems/2.4.4/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2506 sleep_forever>
   rb_thread_t:0x00000001041c1e40 native:0x000070000b7af000 int:0
    depended by: tb_thread_id:0x000000010060a990
   /Users/radeksimko/.vagrant.d/gems/2.4.4/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2507:in `pop'
   /Users/radeksimko/.vagrant.d/gems/2.4.4/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2507:in `block in start_connect_info_watcher'
	from /Users/radeksimko/.vagrant.d/gems/2.4.4/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2409:in `start_share'
	from /Users/radeksimko/.vagrant.d/gems/2.4.4/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:2967:in `execute'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/cli.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/lib/vagrant/environment.rb:294:in `cli'
	from /opt/vagrant/embedded/gems/2.1.4/gems/vagrant-2.1.4/bin/vagrant:164:in `<main>'
```

### Steps to reproduce

1. `vagrant up`
1. `echo 'console_ui: "true"' > ~/.ngrok2/ngrok.yml`
1. `vagrant share`

**Comment by briancain** [comment]
Hi @radeksimko - thanks for the report! You're right, the vagrant-share plugin is failing to validate output from ngrok as it's not json but the help text. Your issue however seems to be an invalid configuration file for ngrok? Fixing that should at least fix the error:

> DEBUG subprocess: stdout: {"err":"You can't enable the console UI and log stdout or stderr","lvl":"crit","msg":"failed to validate configuration","t":"2018-09-06T21:49:15.381858072Z"}

**Comment by radeksimko** [comment]
@briancain My original config file is valid, see below:

```yaml
authtoken: REDACTED
region: eu
update_channel: stable
update: true
log_level: debug
log_format: json
console_ui: "true"
inspect_db_size: 50000000
tunnels:
  default:
    addr: 8080
    inspect: true
    proto: http
    subdomain: radeksimko
  hashibot:
    addr: 9876
    inspect: true
    proto: http
    subdomain: hashibot
```
but it _becomes_ invalid when it is merged with the one Vagrant generates, or in this case one particular CLI option `--log` (in theory it can be either of these).

I do not specify log output in my config, just `console_ui`, Vagrant does that, as you can tell from this line in the debug log:

> INFO subprocess: Starting process: ["/usr/local/bin/ngrok", "start", "--config", "/Users/radeksimko/.ngrok2/ngrok.yml", "--config", "/var/folders/87/cmk1pvjx01d3xwgzs5_44ttc0000gn/T/vagrant-share20180906-72239-qfcemo", "--all", **"--log", "stdout",** "--log-format", "json", "--log-level", "debug"

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
