### ISSUE TITLE
Error "stack level too deep (SystemStackError)" with Vagrant 2.1.4

### ISSUE THREAD

**Issue by jtyr** [hashicorp/vagrant#10205]
### Vagrant version
```
$ vagrant -v
Vagrant 2.1.4
```

### Host operating system
Arch Linux

### Guest operating system
CentOS 7

### Vagrantfile
```ruby
class VagrantPlugins::ProviderVirtualBox::Action::SetName
  alias_method :original_call, :call

  def call(env)
    machine = env[:machine]

    #puts machine.id

    original_call(env)
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end
```

### Debug output
https://gist.github.com/jtyr/e4168f7c819f468bdfb052933962de16

### Expected behavior
I would expect that it will work like it did in Vagrant 2.1.2.

### Actual behavior
The above `Vagrantfile` crashes with this message:
```
`call': stack level too deep (SystemStackError)
```
When I downgrade Vagrant to version 2.1.2 then the same `Vagrantfile` works just fine.

### Steps to reproduce
1. Install Vagrant 2.1.4
2. Use the above `Vagrantfile`
3. Run `vagrant up`

### References
N/A

**Comment by briancain** [comment]
Hi @jtyr , this was fixed via Vagrant 2.1.5 (which was just released!) I just tested it with your Vagrantfile and it does not get the error. Try that one instead, thanks!
