### ISSUE TITLE
Getting "Command not found" when running "vagrant up" 

### ISSUE THREAD

**Issue by JagritiJ** [hashicorp/vagrant#10202]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
This is the operating system that you run locally.

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by JagritiJ** [comment]
![screen shot 2018-09-11 at 11 17 24](https://user-images.githubusercontent.com/20701006/45340937-3274f080-b5b6-11e8-837a-8c706b23e7d8.png)


jagritij-a01:vagrant-env-setup-master jagritij$ cd ..
jagritij-a01:Vagrant jagritij$ vagrant -v
-bash: vagrant: command not found

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Comment by edinaldo-at** [comment]
Eu enfrentei esse problema hoje utilizando o Virtualbox 6.
Após algumas tentativas sem sucesso, fiz o downgrade do Virtualbox para a versão 5.2.12
E funcionou perfeitamente.

Quanto ao Vagrant mantive a versão atual do site

**Comment by mrgunner-amz** [comment]
<img width="670" alt="vagrant" src="https://user-images.githubusercontent.com/53989817/62830840-fcf7dd80-bc32-11e9-83da-f1ff405badc6.PNG">

**Comment by MahmoudHegazi** [comment]
I have the same issue

**Comment by LavanyaChennampalli** [comment]
I have the same problem.If anyone knows the solution please,share answer.
