### ISSUE TITLE
Need equivalent to `vagrant winrm-config` despite warning about `vagrant-winrm` plugin

### ISSUE THREAD

**Issue by cheeseplus** [hashicorp/vagrant#10204]
Howdy folks, over on kitchen-vagrant we've noticed an issue where it seems that in Vagrant 2.1.3+ users are being warned against `vagrant-winrm` but we've been leveraging specifically the `vagrant winrm-config` functionality to get the same sort of information as `vagrant ssh-config`.

Could we get an equivalent command in core Vagrant or alternately how can we access that kind of information _without_ a Vagrant plugin?

Related issue: https://github.com/test-kitchen/kitchen-vagrant/issues/372

### Vagrant version
2.1.4

### Host operating system
macOS 10.13

### Guest operating system
Windows 10

**Comment by cheeseplus** [comment]
I should add that I know we can tell folks to use the env var `VAGRANT_IGNORE_WINRM_PLUGIN` but that's not something we'd want to set for users. The other alternative that's come up while noodling is making a new vagrant plugin like `vagrant-winrm-config` but then we' mostly just be copying code which feels less than elegant.

Either way, happy to help with the fix itself but want to step on the least amount of toes possible.

**Comment by cheeseplus** [comment]
As a bonus: if the vagrant-winrm functionality is moved internal to Vagrant then it'd also be great if we could get the auto-forwarded RDP port returned (the one from `vagrant port`) as noted in https://github.com/test-kitchen/kitchen-vagrant/issues/224

**Comment by chrisroberts** [comment]
#10263 Adds the winrm commands with some slight changes. The winrm-config will output `RDP` prefixed information and is dynamically generated to resolve the issue seen with test-kitchen/kitchen-vagrant#224. The `upload` command is the other change which is now generic using the available configured communicator.
