### ISSUE TITLE
ubuntu/xenial64 failing to bypass key permissions check in User Profile directories (within WSL)

### ISSUE THREAD

**Issue by jmscraig** [hashicorp/vagrant#10201]
If this is not a bug please let me know how to configure or execute a ubuntu/xenial64 build to as expected bypass permissions checks of the private_key file within the WSL environment.   Thx!

The issue straight-up and simple:  ubuntu/xenial64 (latest 20180831.0.0) using a nearly default simple install is failing to execute the bypass, and is requiring enforcement of 600 permissions on the private_key for vagrant projects installed in the Windows user profile directory hierarchy in a WSL deployment.  

Key Context:  

Windows env values:  
      USERNAME=dev1    USERPROFILE=C:\Users\JC-dev1
           - Note the windows user account name and user profile directory name do not match.  
           - This is normal and expected in Windows, but could be a possible source of the bug.

Vagrant project located dead center where permissions check should be bypassed:  
      -  /mnt/c/Users/dev1/x/vagrant-project   

Consistent, repeatable failure.  ubuntu/trusty64  succeeds and ubuntu/xenial64 fails everytime. 

WSL was deleted and reinstalled, Vagrant and VirtualBox installs are brand new.  

...............

In the exact same Win10 user home direct structure and same ubuntu session where build ubuntu/trusty64 (@ lastest) correctly consistently bypasses permissions for the private_key file, build ubuntu/xenial64 (@ lastest) fails to bypass the permissions check for the private_key file and causes the ssh login to abort.  

Same ubuntu session ...  each in a new sub-dir under the same parent directory.
$ vagrant init ubuntu/trusty64   >>  Success
$ vagrant init ubuntu/xenial64  >>  Fail:  aborted due to permissions check on private_key
$ vagrant init ubuntu/trusty64   >>  Success
$ vagrant init --box-version '20180831.0.0' ubuntu/xenial64  >>  Fail: permissions on private_key
$ vagrant init --box-version '20180831.0.0' ubuntu/xenial64  >>  Fail: permissions on private_key 
$ vagrant init ubuntu/trusty64   >>  Success
$ vagrant init ubuntu/trusty64   >>  Success

The following command (which should not be needed within the WSL user profile directory tree) had no effect on the results.
$  export VAGRANT_WSL_WINDOWS_ACCESS_USER_HOME_PATH="/mnt/c/Users/not-real-name/x/v-base-ub-16-0-4"

Completely default ubuntu/xenial64 init and Vagrantfile three changes (and only three) were made to the Vagrantfile after "$ vagrant init " to address the COM1 issue on this build.
 1.  The comment # was removed from line 54 to enable 
 -  config.vm.provider "virtualbox" do |vb|
2.   This line was added.  
 -   vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected"]
3.  The comment # was removed to enable the 'end' to properly code this section.
 -  end   

### Vagrant version
Vagrant 2.1.4 

### Host operating system
Window 10 - & WSL latest-updated, WSL deleted and reinstalled, Vagrant just installed for the first time.
Same version of Vagrant on both WSL and Windows

### Guest operating system
Ubuntu that comes with these two templates.. zero changes to the OSs 

### Vagrantfile   -   Is simplest default with the addition of three line changes to address COM1 issue

```ruby 
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected"]
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end 
```

###  Debug Output 
7 tests using these two commands, different sessions, re-installs and full reboots
      $  vagrant init ubuntu/xenial64
      $  vagrant init --box-version '20180831.0.0' ubuntu/xenial64
consistently produce this error    "Permissions 0777 for '/mnt/c/Users/JC-dev1/x/rc-ub-16-0-4-v2/.vagrant/machines/default/virtualbox/private_key' are too open."

debug1: Trying private key: /mnt/c/Users/JC-dev1/x/rc-ub-16-0-4-v2/.vagrant/machines/default/virtualbox/private_key
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0777 for '/mnt/c/Users/JC-dev1/x/rc-ub-16-0-4-v2/.vagrant/machines/default/virtualbox/private_key' are too open.

### Expected behavior
vagrant ssh should have bypassed permissions check on the private_key file

### Actual behavior
see debug error above

### Steps to reproduce
1.  create a new sub-directory using a WSL session known to create and execute successful builds under that same parent directory.  
2.  cd into the sub directory 
3. Execute  $ vagrant init ubuntu/xenial64  and then vagrant ssh 
4.  If you have a COM1 error execute the three line changes to Vangrantfile mentioned above and repeat step 3.  
5.   See error, bang head on desk.  Seek to debug and then repeat.  

### References
I searched both open and closed issues and found many on ssh permissions topics but none quite like this.

**Comment by chrisroberts** [comment]
@jmscraig Could you provide a gist of the `--debug` output from running a `vagrant ssh` to one of these guests? Thanks!

**Comment by jmscraig** [comment]
yes.  will do.   Thx!

**Comment by shrimptankz** [comment]
I'm also experiencing a similar issue on ubuntu/bionic64 while using vagrant on Windows 10. A screenshot of output of `vagrant ssh -- -v` is shared below reporting the private_key doesn't have the right permissions and openssh won't use it as a result. This behavior seems to contradict what is written [here](https://github.com/chrisroberts/vagrant/blob/a1d23b4e9763cdad6738bdce98728f23265b81f6/lib/vagrant/util/ssh.rb#L28) about Windows checking key permissions.
>  Don't do anything if we're on Windows, since Windows doesn't worry
>    about key permissions.

![image](https://user-images.githubusercontent.com/33560517/72689221-3f282380-3add-11ea-8ddf-5b32cc19ad13.png)

I saw your request for a `--debug` output on 09/11/2018 so here is link to a gist of the debug output from running a vagrant ssh to my ubuntu/bionic64 guest:  [https://gist.github.com/shrimptankz/1da6eeb8a563ca2e69fe1b2a41825556](https://gist.github.com/shrimptankz/1da6eeb8a563ca2e69fe1b2a41825556) 

Please note that I manually scrubbed the following sensitive data points from the log file: hardware uuid, username, SCSI-ImageUUID-0-0, SCSI-ImageUUID-1-0, macaddress1. 

Adding to this issue because I would love for vagrant to securely assign the correct permissions to the default private_key during provisioning so that I don't need to [manually change the key's permissions in file explorer](https://superuser.com/questions/1296024/windows-ssh-permissions-for-private-key-are-too-open). Let me know if I can provide more information or if there is a permanent solution to this issue, thanks! ❤️

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
