### ISSUE TITLE
SMB-Share provides messed-up files on hyper-v and windows 10

### ISSUE THREAD

**Issue by hirsche** [hashicorp/vagrant#10203]
I am currently using vagrant to virtualize an Ubuntu system with hyper-v for development.  In order to share and edit sources on the windows host as well as the linux guest I've configured an smb-share using the Vagrantfile with "config.vm.synced_folder".
Creating and provisioning the machine with the initial "vagrant up" works fine. Files get copied and the install scripts are working.
However, when running the machine it is not possible to work with the files on the shared folder. Files are messed-up and partly contain things from other files => thus the shared files are completely unusable.
I tried executing `net config server /autodisconnect:-1` as recommended to avoid [idle disconnects](https://www.vagrantup.com/docs/synced-folders/smb.html#preventing-idle-disconnects), but this didn't solve the issues.
I am happy to provide any additional information needed.

### Version
- Tested with vagrant 2.1.2 and 2.1.4
- Windows 10 host
- Ubuntu 16.04 guest - box: bento/ubuntu-16.04
- Hyper-V Manager Version: 10.0.17134.1

### Host operating system
Windows 10

### Guest operating system
Ubuntu 16.04 - box: bento/ubuntu-16.04

### Vagrantfile
Can be found at github: [Vagrantfile](https://github.com/hirsche/hyperledger/blob/master/Vagrantfile)

### Expected behavior
Correct files, which are readable

### Actual behavior
Files are messed-up, scrambled and contain parts from other files.

### Steps to reproduce
See [this set-up](https://github.com/hirsche/hyperledger) at github.

### References
- [stackoverflow: Messed up file contents in vagrant smb shared file](https://stackoverflow.com/questions/50114255/messed-up-file-contents-in-vagrant-smb-shared-file/50115401)

**Comment by chrisroberts** [comment]
I was able to reproduce SMB related errors with Ubuntu 16.04 and found they were resolved when I either ran with 14.04 or 18.04 instead. It appears there may be some issues with the cifs module in 16.04 which we have no control over and cannot fix within Vagrant.

Cheers!
