### ISSUE TITLE
vagrant ssh is broken badly

### ISSUE THREAD

**Issue by zaldy1028** [hashicorp/vagrant#10212]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Vagrant 2.0.2

### Host operating system
4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Guest operating system
ubuntu/trusty64

### Vagrantfile

```ruby
  config.vm.define "acs" do |acs|
    acs.vm.box = "ubuntu/trusty64"
    acs.vm.hostname = "acs"
    acs.vm.network "private_network", ip: "192.168.33.10"
  end
```

### Debug output

```
OpenSSH_7.6p1 Ubuntu-4, OpenSSL 1.0.2n  7 Dec 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "127.0.0.1" port 2200
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 127.0.0.1 [127.0.0.1] port 2200.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/zaldy/.vagrant.d/insecure_private_key type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/zaldy/.vagrant.d/insecure_private_key-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6p1 Ubuntu-4
ssh_exchange_identification: read: Connection reset by peer
```

### Expected behavior
Expecting to be able SSH. Following a video tutorial from Pluralsight.
Even following your guide from https://www.vagrantup.com/intro/getting-started/boxes.html and https://www.vagrantup.com/intro/getting-started/up.html yielded the same result

### Actual behavior
Unable to perform vagrant ssh. No other documentation mention if any additional setup is required.

### Steps to reproduce
1. prepare Vagrantfile with contents as provided in this issue
2. vagrant up (then it starts to wait and terminate)
3. vagrant ssh acs (nothing just wait and terminate)

**Comment by briancain** [comment]
Hello @zaldy1028 - please install the latest version of Vagrant and see if that resolves your issue. Thanks!

**Comment by zaldy1028** [comment]
Thank you all for the help. Managed to get it running. The quirk was coming from virtualbox.
