### ISSUE TITLE
Problem apt-get update on a new box

### ISSUE THREAD

**Issue by avifatal** [hashicorp/vagrant#10210]
### Vagrant version 
2.1.2

### Host operating system windows 
10 pro

### Guest operating system 
ubuntu/xenial64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
   config.vm.provider "virtualbox" do |vb|
      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
   end
  end
```

### Debug output
`
sudo apt-get update: 
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/by-hash/SHA256/e6a9bbd1e41d3bba36bbec9957d930c943f7f1fc05244947e1eb57e17b4b4ba7  Hash Sum mismatch
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/universe/binary-amd64/by-hash/SHA256/a76c1bc8b7385d245d0805322b03ffc04209a177622de6f214ee1686f7a2cf25
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

### Expected behavior
no error Hash Sum mismatch

On a fresh new machine, when ruining `apt-get update` the error above is shown.  
I have built a new source list, and this one is working fine.

```
###### Ubuntu Main Repos
deb http://il.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse
deb-src http://il.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse

###### Ubuntu Update Repos
deb http://il.archive.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse
deb http://il.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse
deb http://il.archive.ubuntu.com/ubuntu/ xenial-proposed main restricted universe multiverse
deb http://il.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
deb-src http://il.archive.ubuntu.com/ubuntu/ xenial-security main restricted universe multiverse
deb-src http://il.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse
deb-src http://il.archive.ubuntu.com/ubuntu/ xenial-proposed main restricted universe multiverse
deb-src http://il.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
```

What is the reason for that?

Thanks

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the Vagrant mailing list. There are many more people who will be able to get you a faster answer there. Thank you and have a great day!
