### ISSUE TITLE
"box prune" needs TTY on linux

### ISSUE THREAD

**Issue by zimmski** [hashicorp/vagrant#10228]
### Vagrant version
Vagrant 2.1.5 from vagrantup.com
VirtualBox 5.2.18 from openSUSE repository

### Host operating system
openSUSE Tumbleweed 20180920

### Expected behavior
Boxes that are marked for removal should be removed.

### Actual behavior
An error is throne that a TTY is needed.

### Steps
1. `vagrant box prune --dry-run` outputs
```
The following boxes will be kept...
bento/ubuntu-16.04 (virtualbox, 201808.24.0)
bento/ubuntu-18.04 (virtualbox, 201807.12.0)

Checking for older boxes...
Would remove bento/ubuntu-16.04 virtualbox 201801.02.0
```

1. `vagrant box prune` outputs
```
The following boxes will be kept...
bento/ubuntu-16.04 (virtualbox, 201808.24.0)
bento/ubuntu-18.04 (virtualbox, 201807.12.0)

Checking for older boxes...
Vagrant is attempting to interface with the UI in a way that requires
a TTY. Most actions in Vagrant that require a TTY have configuration
switches to disable this requirement. Please do that or run Vagrant
with TTY.
```

Since I never had this problem with Vagrant 1.x and since I can only find entries for Cygwin via Google, I am reporting this as a bug. Please let me know how I can help.

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by zimmski** [comment]
I will do that next time. Looks like this has been fixed for me by some update. Sorry for the inconvenience.
