### ISSUE TITLE
Friendly Fusion 11.0.0 vagrant plugin support ticket

### ISSUE THREAD

**Issue by punkrokk** [hashicorp/vagrant#10237]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
2.1.5

### Host operating system
OSX Mojave 10.14

### Guest operating system
Various

### Vagrantfile
N/A

MacBook-Pro: punkrokk$ vagrant up
Bringing machine 'irflow-dev' up with 'vmware_fusion' provider...
This provider only works with VMware Fusion 8 or lower. You have
Fusion '11.0.0'. Please install the proper version of VMware
Fusion and try again.

### Debug output
N/A

### Expected behavior
Support Fusion 11

### Actual behavior
Above error
### Steps to reproduce
1. Update to MacOS Mojave
2. Update Fusion to 11.0.0
3. vagrant up

### References
None

**Comment by chrisroberts** [comment]
Hi there,

Please upgrade to the `vagrant-vmware-desktop` plugin. Installation instructions can be found here: https://www.vagrantup.com/docs/vmware/installation.html

Cheers!

**Comment by punkrokk** [comment]
thanks!

**Comment by chrisroberts** [comment]
@punkrokk It also looks like I still need to push an update to the new plugin. Apologies, I was still getting my :coffee: . Will ping back here once it's released.

**Comment by punkrokk** [comment]
Great - thanks. It’s still < 24 hours old, I can’t really complain :)
Cheers, 

JP

**Comment by sinoru** [comment]
Might be helpful to make this open until new plugin pushed.

**Comment by ndobbs** [comment]
Any details as to when this plugin update will be published?

**Comment by tobiasvielmetter** [comment]
Is there any ETA for the the plugin to be upgraded for VMware Fusion 11? Thanks

**Comment by Fashaun** [comment]
Hi, I still can not work with
- fusion 1
- vagrant 2.2.2
