### ISSUE TITLE
Vagrant up command failed with license issue

### ISSUE THREAD

**Issue by sharavanan2010** [hashicorp/vagrant#10246]
Hi Team, 
I'm new to VMWare Fusion and MAC, currently trying to setup vagrant in MAC OS. We're using vagrant on windows and plans for MAC also.

### Vagrant version
vagrant 2.0.2
Vagrant VMWare Utility 1.0.0
Vagrant vmware desktop plugin 1.0.0 and **licensed**

### Host operating system
MAC OS
VMWare Fusion Profesional Edition 8.5.10 (7527438)

### Expected behavior
Should able to spin a box from MAC OS without any issues

### Actual behavior
vagrant up failed

From the error message I understood that installed version not supported. I don't know what thats one.
is there a mapping like VMWare version + vagrant version + vagrant utility version ?

**Comment by sharavanan2010** [comment]
![vagrant up failed in mac os](https://user-images.githubusercontent.com/39905551/46165155-8f0e2600-c2ad-11e8-9bb6-c37785106fc3.PNG)

Console Error Message

**Comment by chrisroberts** [comment]
Would you please provide a gist of the output with the `--debug` flag. Thanks!

**Comment by sharavanan2010** [comment]
@chrisroberts 
Debug level output,
https://gist.github.com/sharavanan2010/7c4883b73ffc731d3ccb8af93d872823

**Comment by sharavanan2010** [comment]
The same issue occurring for vmware fusion of 10.1.3, 8.x.x and 7.1.3 versions.

**Comment by chrisroberts** [comment]
When you ordered the license you are currently attempting to use, was it for the vagrant-vmware-workstation plugin, or the vagrant-vmware-desktop plugin? The behavior you are seeing suggests you are using a workstation specific license.

**Comment by sharavanan2010** [comment]
@chrisroberts 
I will check with procurement team and get back you.
I got below information from debug logs,
DEBUG activation: Last ping time: 1538069164
DEBUG activation: License file ID: d38594b1-78be-4b8b-af9e-802509f88e67

Is it possible to verify the license details using above GUID in your database?

**Comment by sharavanan2010** [comment]
We purchased as vagrant-vmware-desktop plugin

**Comment by sharavanan2010** [comment]
Today I verified for another license that purchased recently, the same error is occurring. any updates

**Comment by chrisroberts** [comment]
@sharavanan2010 Hi, sorry for the delay here. You can always send support requests for the plugin to support@hashicorp.com

For the license you describe using above, that license was for VMware Workstation 14 which is why it will not work with VMware Fusion. You said you also experienced it with another license you purchased recently. Was it purchased for Workstation as well?

**Comment by sharavanan2010** [comment]
We purchased  the new license for vagrant-vmware-desktop and its working
fine. Thanks for your support, you can close this ticket now.
