### ISSUE TITLE
BUG: should not create /tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory/vagrant_ansible_local_inventory

### ISSUE THREAD

**Issue by hoatle** [hashicorp/vagrant#10258]
### Vagrant version
Vagrant 2.1.5

### Host operating system
macOS

### Guest operating system
Ubuntu

### Vagrantfile

Just configure for simple ansible_local

```ruby
```

### Expected behavior
`/tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory` is the inventory file

### Actual behavior
`/tmp/vagrant-ansible/inventory/vagrant_ansible_local_inventory/vagrant_ansible_local_inventory` was the inventory file since the bug introduced in vagrant 2.1.5

I'm going to send a PR for this fix.

**Comment by hoatle** [comment]
bug introduced due to this change: https://github.com/hashicorp/vagrant/commit/0d23724a1fcf87e1ab86be85e15516eca9e32e8d#diff-c379a6054318dfc48824835501d40778

**Comment by gildegoma** [comment]
@hoatle thank you for the good catch. I'm so sorry to have missed it during #10140 review (where I hadn't time to run a true test, shame on me).
