### ISSUE TITLE
"Vagrant box outdated" and "vagrant up" both are not showing latest version of box from locally hosted catalog file

### ISSUE THREAD

**Issue by mohdemraan** [hashicorp/vagrant#10254]
### Vagrant version
version 2.1.4

### Host operating system
Windows 10 Professional

### Guest operating system
Windows 10 Professional

### Vagrantfile
```ruby
Vagrant.require_version ">= 2.1.4"

Vagrant.configure("2") do |config|
  config.vm.define "LDB_Sitecore"
  # Name of box to install with
  config.vm.box = "LDB_Sitecore"
  
  config.vm.box_check_update = true

  config.vm.box_url = "file:////~/LDB_Sitecore.json"

  # Communicator type
  config.vm.communicator = "winrm"  

  # Guest OS
  config.vm.guest = :windows
  config.windows.halt_timeout = 15

  # Disabling synced_folder
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # Config networks on guest.
  config.vm.network "forwarded_port", guest: 3389, host: 3389, auto_correct: true
  config.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true
  config.vm.network "forwarded_port", guest: 443, host: 443, auto_correct: true
  config.vm.network "forwarded_port", guest: 445, host: 445, auto_correct: true
  config.vm.network "forwarded_port", guest: 1433, host: 1433, auto_correct: true

  # Admin user name and password
  config.winrm.username = "hidden"
  config.winrm.password = "hidden"
  config.vm.post_up_message = "Your Sitecore VM is ready for use. If you want to RDP into this machine then type 'vagrant rdp'"
  
  # Hyperv configuration
  config.vm.provider :hyperv do |h|
    h.vmname = "LDB_Sitecore"
    h.cpus = 2
    h.memory = 4098
    h.enable_virtualization_extensions = true
    h.linked_clone = true
  end  
end 
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/mohdemraan/1468a5f0c125b63253193523438dbde5

### Expected behavior
PS>Vagrant box outdated
Checking if box 'LDB_Sitecore' is up to date...
* 'LDB_Sitecore' for 'hyperv' is outdated! Current: 1.0. Latest: 1.1

### Actual behavior
PS>Vagrant box outdated
Checking if box 'LDB_Sitecore' is up to date...
and nothing

However, when I'm running "Vagrant box outdated --global", it is showing correctly

### Steps to reproduce
1. I'm using catalog for box versioning as you can see in my vagrantfile and I have this file on shared location on server.
2. I have even tried putting this file at same path of vagrantfile but still no success
3. Box updates are not even being check on vagrant up

**Comment by chrisroberts** [comment]
@mohdemraan Do you see this same behavior with the latest Vagrant release (2.1.5)?

**Comment by mohdemraan** [comment]
Is there any fix in 2.1.5 related to my particular problem? As I don't want to upgrade right now.

**Comment by mohdemraan** [comment]
@chrisroberts I was trying some more ways to find what is happening and I upgraded to latest 2.1.5 version also but nothing changed, same results. So I destroyed the box using "vagrant destroy LDB_Sitecore" and after that "vagrant box outdated" is giving correct response as mentioned below

````
Checking if box 'LDB_Sitecore' is up to date...
A newer version of the box 'LDB_Sitecore' for provider 'hyperv' is
available! You currently have version '1.0'. The latest is version
'1.1'. Run `vagrant box update` to update.
````

Now without updating I ran "vagrant up" and it didn't check for update. Also same result of "Vagrant box outdated"

Is this the expected behavior?

Thanks,
Imran

**Comment by mohdemraan** [comment]
Any update on this please?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
