### ISSUE TITLE
 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 50

### ISSUE THREAD

**Issue by onsattia** [hashicorp/vagrant#10257]
While installing laravel/homestead i get this error 
i'm using the version 2.1.5 of Vagrant 
 And MacOs High Sierre

Any help please?

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by briancain** [comment]
Closing this, as it seems to be a duplicate of https://github.com/hashicorp/vagrant/issues/10260
