### ISSUE TITLE
vagrant up destroying VM and associated drives

### ISSUE THREAD

**Issue by Iraj66** [hashicorp/vagrant#10252]
Hey everybody
Hope you doing well
i have a problem with vagrant up command. first i added laravel/homestead virtualbox file successfully. then when i wanna run vagrant up, unfortunately i got this message. 
could you please help me with this
![1](https://user-images.githubusercontent.com/43480733/46261197-f66de500-c4fc-11e8-9593-b76fbdd5bb05.jpg)

**Comment by briancain** [comment]
Hello @Iraj66 - Please see the comment on this issue: https://github.com/hashicorp/vagrant/issues/9640#issuecomment-380574611

Let me know if that works for you. Thanks!

**Comment by Iraj66** [comment]
> Hello @Iraj66 - Please see the comment on this issue: [#9640 (comment)](https://github.com/hashicorp/vagrant/issues/9640#issuecomment-380574611)
> 
> Let me know if that works for you. Thanks!

Hi there, actually i tired to check any solution and fail. so decided to uninstall all staff for Homestead and try to write code in PhpStorm application with composer. :(

**Comment by Iraj66** [comment]
> Hello @Iraj66 - Please see the comment on this issue: [#9640 (comment)](https://github.com/hashicorp/vagrant/issues/9640#issuecomment-380574611)
> 
> Let me know if that works for you. Thanks!
