### ISSUE TITLE
How to exit with warnings from Vagrantfile?

### ISSUE THREAD

**Issue by leth** [hashicorp/vagrant#1026]
We have a rather complicated chef setup which involves some per-developer settings loaded from a file being passed through to chef in the vagrantfile.

Is there a way for us to abort Vagrant if certain conditions are not met, and display a nice error message.

Currently we just throw an exception, but this causes a stacktrace, so if your terminal isn't big enough the message will be lost off the top.

**Comment by JoelBCarter** [comment]
Since this was the top Google result for the topic, to make it explicit, something like this should suffice:
```
if !Vagrant.has_plugin?('vagrant-vbguest')
  puts 'vagrant-vbguest plugin required. To install simply do `vagrant plugin install vagrant-vbguest`'
  abort
end
```
