### ISSUE TITLE
Problem with port redirection (80 guest | 8080 host), the virtual machine does not start.

### ISSUE THREAD

**Issue by SideMasterGM** [hashicorp/vagrant#10268]
I'm trying to boot a virtual machine exposing port 80, via port 8080 to the host host. Where said virtual machine will have installed the apache service, to be later consulted from the host.

At the moment, the start of the virtual machine with its operating system and version, has been correct, with an amount of memory, cpus and hostname, so the possible parameters to automate that, goes well.

The problem comes with port exposure. I destroyed the virtual machine, loaded the new Vagrantfile file with the necessary configurations and at the moment of starting the machine, it gives me errors in its output; I have checked the instruction and it is correct, but it does not give me the expected outputs, since it does not start it.

### Vagrant version
2.1.5

### Host operating system
Windows 10

### Guest operating system
debian/jessie64 (virtualbox, 8.11.0)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  	config.vm.box = "debian/jessie64"
  	config.vm.hostname = "http"
	config.vm.network "forwarded_port", guest: 80, host: 8080

	config.vm.provider "virtualbox" do | vb |
		vb.name = "PortsRedirections"
		vb.memory = "512"
		vb.cpus = "2"
		vb.linked_clone = true
	end
end
```

### Debug output
I provide the GitHub Gits link where all the outputs are, corresponding to the instruction: vagrant up --debug 2> 1 vagrant.log.

The link is: https://gist.github.com/SideMasterGM/fb30d8f6ca18d3056952f7acbeaac200

### Expected behavior
I expected the virtual machine to be booted with port 80 exposed through 8080 to the host host so that I could start to install apache2 and run it.

### Actual behavior
It throws me the following results: 
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:156:in `initialize': negative string size (or size too big) (ArgumentError)
	from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:156:in `new'
	from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:156:in `parse'
	from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:335:in `load'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine_index.rb:293:in `unlocked_reload'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine_index.rb:53:in `block in initialize'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine_index.rb:323:in `block in with_index_lock'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine_index.rb:321:in `open'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine_index.rb:321:in `with_index_lock'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/machine_index.rb:52:in `initialize'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/environment.rb:724:in `new'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/environment.rb:724:in `machine_index'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/environment.rb:208:in `block in action_runner'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:33:in `run'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/environment.rb:526:in `hook'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/environment.rb:775:in `unload'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/bin/vagrant:167:in `ensure in <main>'
	from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/bin/vagrant:167:in `<main>'

### Steps to reproduce
1. vagrant init -m -f debian/jessie64
2. vagrant up (With the Vagrantfile already configured)

### References
I have the version of VirtualBox 5.1.26.
- ...

**Comment by briancain** [comment]
Hi there @SideMasterGM - This is a duplicate issue of https://github.com/hashicorp/vagrant/issues/9146 so I'll go ahead and close this.

That being said, what is the file size and contents of `C:\Users\YOUR_USERNAME\.vagrant.d\data\machine-index\index`?

**Comment by SideMasterGM** [comment]
Thanks @briancain. Regards!
