### ISSUE TITLE
Vagrant 

### ISSUE THREAD

**Issue by nn222** [hashicorp/vagrant#10261]
Which tool should I use in order to run a file (lets call it for now file) on a machine on virtual box or vmware that do the following:
1- specify and set the specs of the hardware of my machine.
2- install the os or Iso image (example: Ubuntu)
3- Run a linux script or ansible script (example: set lamp environment on the machine).

I want this file to be used on regular basis.I want to edit it (example: editing the hardware specs)
so is vagrant solution ??

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
