### ISSUE TITLE
Firewalld zone to interface mapping removed by vagrant

### ISSUE THREAD

**Issue by gulassi** [hashicorp/vagrant#10271]
### Vagrant version
2.1.5

### Host operating system
Windows 10

### Guest operating system
Centos 7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", inline: <<-SHELL
    yum -y install firewalld
    systemctl enable firewalld
    systemctl start firewalld
    firewall-cmd --zone dmz --add-interface eth1
  SHELL
end
```

### Expected behavior
Firewall zone to interface mapping is persisted across reboots through Vagrant.

### Actual behavior
Interfaces are mapped to the default public zone of the firewall after virtual machine is rebooted through Vagrant.

### Steps to reproduce
1. vagrant up
2. run ` sudo firewall-cmd --get-zone-of-interface=eth1` inside virtual machine. Output should be `dmz`
3. vagrant reload
4. re-run ` sudo firewall-cmd --get-zone-of-interface=eth1` inside virtual machine. Output is `public`, instead of `dmz`

### Cause
This is caused by the method that Vagrant uses to configure network interfaces. Firewalld stores the interface firewall zone in the ifcfg configuration file and that is overwritten by Vagrant during startup of the virtual machine as part of network configuration.

I have fixed this locally by modifying the configuration process so that before overwriting the old configuration the zone is fetched from it by grep and injected to the end of the new configuration file.

**Comment by chrisroberts** [comment]
Using `vagrant reload --provision` will cause the provisioner to run again when the guest is brought up and re-apply the zone.

Cheers!

**Comment by gulassi** [comment]
Sorry I should have elaborated more on the actual use case, that Vagrantfile is only to demonstrate the problem. Actual environment isn't using Vagrant to manage the firewall zone using provisioning, but it is configured by external Ansible. So Vagrant provisioning is not going to help. And because the correct firewall zone for a interface is determined by some Ansible calculations, moving the firewall mapping configuration to Vagrant provisioning is not possible easily.

**Comment by chrisroberts** [comment]
If ansible is being invoked outside of Vagrant then it will have to be invoked some way after the guest system has been brought up to replace the overwritten rules. Outside of that, you could use triggers to cache the configuration in a backup file before the guest is halted. This would allow trigger to be used after the guest is brought up to check for the remote file, and apply it.
