### ISSUE TITLE
Docker Provisioner Munges Windows Paths

### ISSUE THREAD

**Issue by jamiejackson** [hashicorp/vagrant#10274]
### Vagrant version

2.0.2

### Host operating system

Windows

### Guest operating system

N/A

### Vagrantfile
```ruby
...
  config.vm.define "centos-jenkins" do |c|
    c.vm.provider "docker" do |d|
      d.name = "centos-jenkins2"
      d.image = "jenkins/jenkins:2.91-alpine"
      d.ports  = ["9898:8080"]
      d.volumes = ['/c/Users/15037/workspace/centos-vagrant-fresh:/var/jenkins_home']
    end
  end
...
```

### Debug output

I gathered this info back in February, in [this thread](https://groups.google.com/d/topic/vagrant-up/fIDYv4c322Y/discussion). I don't have the windows box now on which to create proper debug output, but here is what I had:

```
Command: ["docker", "run", "--name", "centos-jenkins2", "-d", "-p", "9898:8080", "-v", "c\\Users\\15037\\workspace\\centos-vagrant-fresh:/var/jenkins_home", "jenkins/jenkins:2.91-alpine", {:notify=>[:stdou
t, :stderr]}]

Stderr: C:\Program Files\Docker Toolbox/docker.EXE: Error response from daemon: create c\Users\15037\workspace\centos-vagrant-fresh: "c\\Users\\15037\\workspace\\centos-vagrant-fresh" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'C:\Program Files\Docker Toolbox/docker.EXE run --help'.
```

### Workaround

```diff
--- /cygdrive/c/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/docker/driver.orig.rb	2018-02-22 13:11:00.934731600 -0500
+++ /cygdrive/c/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/providers/docker/driver.rb	2018-02-22 13:01:42.703345200 -0500

@@ -48,7 +48,7 @@
         run_cmd += ports.map { |p| ['-p', p.to_s] }
         run_cmd += volumes.map { |v|
           v = v.to_s
-          if v.include?(":") && @executor.windows?
+          if false && v.include?(":") && @executor.windows?
             host, guest = v.split(":", 2)
             host = Vagrant::Util::Platform.windows_path(host)
             # NOTE: Docker does not support UNC style paths (which also
```

### References

- https://groups.google.com/d/topic/vagrant-up/fIDYv4c322Y/discussion

**Comment by briancain** [comment]
Hi there @jamiejackson - I recommend upgrading to the latest version of Vagrant and trying again. We've had some updates to that code since version 2.0.2. Thanks!

https://github.com/hashicorp/vagrant/blob/master/plugins/providers/docker/driver.rb#L51-L67

**Comment by jamiejackson** [comment]
I added my old issue because a colleague on Windows just got bitten in 2.1.2. I'll see if it's truly the same issue or not.

**Comment by jamiejackson** [comment]
Same issue on 2.1.2 (which she's on), and the same patch works around the issue.

**Comment by briancain** [comment]
The latest version of Vagrant is 2.1.5: https://www.vagrantup.com/downloads.html

**Comment by jamiejackson** [comment]
Once my project upgrades to 2.1.5, I'll report back as to whether it works without my patch, thanks.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. Thanks!
