### ISSUE TITLE
Vagrant up fails with Inappropriate ioctl for device

### ISSUE THREAD

**Issue by pkaramol** [hashicorp/vagrant#10284]
### Vagrant version

```
(master)$ vagrant --version
Installed Version: 1.8.1

Vagrant was unable to check for the latest version of Vagrant.
Please check manually at http://www.vagrantup.com

```

### Host operating system

```
(master)$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
/home/pkara/Workspace/gitlab/awx-mesos-inf-update
(master)$ uname -a
Linux pkara-pc01 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:44:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
### Hypervisor
`5.1.38_Ubuntu r122592`

### Guest operating system
`ubuntu/xenial64`

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.box_check_update = true

  config.vm.network "private_network", ip: "192.168.33.10"

 
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "4096"
  end

  config.vm.provision "ansible" do |ansible|
   ansible.limit = "all"
   ansible.compatibility_mode = "2.0"
   ansible.playbook = "ansible/install.yml"
  end
end

```

### Debug output
[gist](https://gist.github.com/pkaramol/1c8eac274ceeb6fbb41918b8c3a397d2)

### Expected behavior
vagrant box should be up an running

### Actual behavior
Creating the vm fails with the following error:

> The following SSH command responded with a non-zero exit status.
>
> Vagrant assumes that this means the command failed!
> 
> /sbin/ifdown eth1 2> /dev/null
> 
> Stdout from the command:
> 
> 
> 
> Stderr from the command:
> 
> mesg: ttyname failed: Inappropriate ioctl for device
>

**Comment by chrisroberts** [comment]
Hi there. Please upgrade your Vagrant to the latest version. You can download the latest version from: https://www.vagrantup.com/downloads.html

Cheers!

**Comment by pkaramol** [comment]
But I just downgraded it because of [this](https://github.com/hashicorp/vagrant/issues/10281#issuecomment-428586479) advice.

**Comment by chrisroberts** [comment]
@pkaramol There is a `.deb` package on the downloads page which is the current release. Just uninstall the version you installed with `apt`, download the `.deb` package and install it with `dpkg -i`.

Cheers!

**Comment by OZZlE** [comment]
I have the latest vagrant as of writing this now, and also get this issue...

Could it be because I upgraded from; MacOs High Sierra to Mojave, Vagrant 2.1 to 2.2.5 and VirtualBox 5.x to latest? Do I have to destroy and re-create my box? (will take a lot of time due to big db)

**Comment by OZZlE** [comment]
I have Catalina now with vagrant 2.2.5 (2.2.6 doesn't work mounting nfs for me)

I had vagrant working fine but then my computer crashed and when I tried to start up my vagrant box again I get this issue.

If I disable nfs and use the built-in virtual box file syncing it works fine, but it's very slow file syncing.. 

I'm quite certain it's some kind of cache that isn't deleted or some service not terminated on the host that is preventing it to start again. From other issues I've read it seems like on Catalina it only works mounting 1 nfs volume with vagrant, otherwise it won't mount at all.. So I am thinking the one I had before my Mac crashed is still running.. but I don't know how to terminate it..

**Comment by OZZlE** [comment]
This fixed it for me now in your host Mac:

    vagrant halt
    sudo ifconfig vboxnet0 down
    sudo ifconfig vboxnet0 up
    vagrant up

https://github.com/hashicorp/vagrant/issues/1941#issuecomment-42274573
