### ISSUE TITLE
Vagrant up is not working after upgrade

### ISSUE THREAD

**Issue by amontalban** [hashicorp/vagrant#10285]
### Vagrant version
```
Andres-MacBook-Pro:devserver andres$ vagrant version
Installed Version: 2.1.5
Latest Version: 2.1.5
 
You're running an up-to-date version of Vagrant!
```

### Host operating system
macOS High Sierra (10.13.6)

### Guest operating system
FreeBSD

### Vagrantfile
Unfortunately I can't share the box Vagrantfile because it's really custom and have couple of confidential information.

But based on the debug the problematic line in our Vagrant file is the first of this snippet is:

```ruby
p = Vagrant::Environment.new.home_path.to_s
if not p.ascii_only? or p.index(' ') then
  abort('Perceptyx Developer: This code snippet detected that vagrant path contains non ASCII or spaces chars. Maybe your system username have those chars?. You can override the vagrant path by setting VAGRANT_HOME environment var to a new location. On Windows: `set VAGRANT_HOME=C:\folder`')
end
```

### Debug output
https://gist.githubusercontent.com/amontalban/cf25f097ce08d4bb65f547367da2a8c5/raw/d14472e0dcbebb6b4cba27920f681e044da269a7/vagrant.log

### Expected behavior
Have VM started

### Actual behavior
```
Andres-MacBook-Pro:devserver andres$ vagrant up
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/andres/.vagrant.d/boxes/perceptyx-VAGRANTSLASH-devserver/20181005.74/virtualbox/Vagrantfile
Line number: 0
Message: ThreadError: deadlock; recursive locking
```
### Steps to reproduce
This works in version 2.1.2 but not in 2.1.5.

### References
- GH-9893 (Specially https://github.com/hashicorp/vagrant/issues/9893#issuecomment-423426725)

**Comment by chrisroberts** [comment]
Hi there,

You'll want to use `Vagrant.user_data_path.to_s` instead of `Vagrant::Environment.new.home_path.to_s`.

Cheers!

**Comment by BR0kEN-** [comment]
Use of `Vagrant::Environment.new.root_path` also causes `Message: ThreadError: deadlock; recursive locking`. 

Vagrant 2.2.5

**Comment by BR0kEN-** [comment]
For now I took this snippet as a replacement:

```ruby
def find_project_dir()
  root_finder = lambda do |path|
    return path if path.join("Vagrantfile").file?
    return nil if path.root? || !File.exist?(path)

    root_finder.call(path.parent)
  end

  root_finder.call(Pathname.pwd)
end
```

Basically it's a copy of the `root_path` method of `Environment` with a small amendment.
