### ISSUE TITLE
Support both `service` and `systemctl` for controlling NFS on SUSE guests

### ISSUE THREAD

**Issue by briancain** [hashicorp/vagrant#10287]
Rather than only supporting `service` for controlling the NFS service on SUSE, we should allow for both `service` and `systemctl` to work so that both older and newer guests can continue to use NFS.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
