### ISSUE TITLE
vagrant ssh fails with error : Permission denied (publickey,gssapi-keyex,gssapi-with-mic)

### ISSUE THREAD

**Issue by absolutarin** [hashicorp/vagrant#10280]
### Vagrant version
2.1.5

### Host operating system
MacOS Mojave (10.14)

### Guest operating system
centos/6 or centos/7

### Vagrantfile
```
Vagrant.configure('2') do |config|

  # Box / OS
  VAGRANT_BOX = 'centos/6'
  user_id = ENV['USER']
  MACHINE_NAME = user_id
  PROJECTS_HOME = '~/projects'
  
  VM_USER = 'vagrant'
  
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = MACHINE_NAME
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = MACHINE_NAME
    vb.memory = '4096'
    vb.cpus = '2'
    vb.gui = false
  end
  config.vm.network "private_network", type: "dhcp"
  
  unless ENV['PROJECTS_TO_SYNC']
    config.vm.synced_folder PROJECTS_HOME, '/projects', disabled: false
  end
  config.vm.synced_folder '.', '/home/vagrant/'
  
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    sudo yum upgrade -y
    sudo yum install vim -y
    sudo yum install git -y
    # sudo yum groupinstall 'Development Tools' -y
  SHELL
end
```

### Debug output
https://gist.github.com/absolutarin/beed89ed8cda68cc9df07ca64d34d750

### Expected behavior
I should have been able to SSH into the vagrant workstation

### Actual behavior
I was not able to authenticate to workstation owing to the mismatched/wrong SSH key(s). Error ::
```
hostmac projects: 
hostmac projects: vagrant ssh
vagrant@127.0.0.1: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
hostmac projects: 
```

### Steps to reproduce
1. Install vagrant 2.1.5 or 2.1.3 
2. Use the Vagrantfile provided
3. Run 'vagrant up'
4. Run 'vagrant ssh'

### References
None found so far

**Comment by chrisroberts** [comment]
Does a fresh `vagrant up` complete successfully?

**Comment by absolutarin** [comment]
> Does a fresh `vagrant up` complete successfully?

I have tried re-installing vagrant and virtualbox and even destroying existing boxes - starting from scratch. No success.

**Comment by chrisroberts** [comment]
Do you have multiple keys added to your ssh-agent? Would you provide a gist of the output from: `vagrant ssh --debug`

**Comment by manishrw** [comment]
I'm facing the same issue.

**Comment by absolutarin** [comment]
> Do you have multiple keys added to your ssh-agent? Would you provide a gist of the output from: `vagrant ssh --debug`

Chris, I posted the debug logs. Were you able to find anything?

**Comment by thuyettiensinh** [comment]
I can not use `vagrant ssh`, so I'm using ` ssh root@192.168.30.10 ` 
And has same problem, but you can fix it by add below to the `Vagrantfile`

`config.vm.provision :shell, :inline => "sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sudo systemctl restart sshd;", run: "always"`

and run `vagrant reload`
 ` ssh root@192.168.30.10 ` 
passwod: `vagrant`

**Comment by hamadatakaki** [comment]
Hello.  I have an idea of cause of this problem. 

I think that `config.vm.synced_folder '.', '/home/vagrant/'` caused this problem.
Because the configure makes home directory on the host overwritten and destroy `.ssh` settings on the host.
I got the same problem a few seconds ago. I checked the `.ssh` was overwritten by Vagrant GUI.

I am sorry that my english is so bad...(I am Japanese student...).
I wish that this comment  can solve your problem.

**Comment by houqianming** [comment]
@hamadatakaki  you are right. I encountered the same problem, and changed the target mount directory from /home/vagrant/ to /opt/vagrant/,  avoiding under the /home,  and fixed it.

**Comment by chrisroberts** [comment]
@hamadatakaki is correct (https://github.com/hashicorp/vagrant/issues/10280#issuecomment-452166293). Changing the mount point will resolve the issue. Thanks @hamadatakaki!

Cheers!

**Comment by joshlsullivan** [comment]
> Hello. I have an idea of cause of this problem.
> 
> I think that `config.vm.synced_folder '.', '/home/vagrant/'` caused this problem.
> Because the configure makes home directory on the host overwritten and destroy `.ssh` settings on the host.
> I got the same problem a few seconds ago. I checked the `.ssh` was overwritten by Vagrant GUI.
> 
> I am sorry that my english is so bad...(I am Japanese student...).
> I wish that this comment can solve your problem.

This fixed my issue.

**Comment by Ba7er** [comment]
im having the same problem after changing the synced folder conf.
And as i understood from the comments dont try to sync to /home/vagrant ......but what if i want my files to be synced to /home/vagrant ???
note: i want mt to code to be in /home/vagrant  because my code generates some ".sock" file and only there im allowed to generate 
What do you think ?
thanks .

**Comment by chrisroberts** [comment]
@Ba7er In general you won't be able to mount a synced folder to `/home/vagrant` since that directory will likely never be empty. However, you could just mount it to a subdirectory of the home directory (like `/home/vagrant/my-folder`) as long as that folder doesn't already exist on the guest with content within it.

**Comment by Matt-CloudEngineering** [comment]
Hi @hamadatakaki & @chrisroberts, this also worked for me. However on my previous box 'ubuntu/trusty' i had it setup that way in my config and didn't have an issue. What has changed now that I am using 'ubuntu/xenial64' that makes this an issue?

**Comment by dcalsky** [comment]
> Hello. I have an idea of cause of this problem.
> 
> I think that `config.vm.synced_folder '.', '/home/vagrant/'` caused this problem.
> Because the configure makes home directory on the host overwritten and destroy `.ssh` settings on the host.
> I got the same problem a few seconds ago. I checked the `.ssh` was overwritten by Vagrant GUI.
> 
> I am sorry that my english is so bad...(I am Japanese student...).
> I wish that this comment can solve your problem.

So, change this line of the config: `config.vm.synced_folder '.', '/home/vagrant/'` to `config.vm.synced_folder '.', '/home/vagrant/foo'` can solve this problem.

**Comment by enderandpeter** [comment]
@hamadatakaki Congratulations, sir! You've won!!!

Indeed if you map anything to `/home/vagrant` it will totally blow away everything that Vagrant has so carefully setup in there.
