### ISSUE TITLE
Error when installing plugin (Errno::ECONNRESET when download spec)

### ISSUE THREAD

**Issue by bbrala** [hashicorp/vagrant#10293]
For some reason plugin installs stopped working suddenly on our machines.

### Vagrant version
2.1.5

### Host operating system
Windows 10 1804

### Vagrantfile
None

### Debug output
https://gist.github.com/bbrala/913628d4512682ae457315acfc92bf2a

### Expected behavior
Plugin should install

### Actual behavior
Weird error

### Steps to reproduce
1. Fresh install (or not) with latest updates for Windows 10 (1804)
2. `vagrant plugin install vagrant-hostmanager`
3. error

### References
Maybe since the last comment mentions this problem.
 - #7780

**Comment by bbrala** [comment]
Some extra info.

When running gem from `C:\HashiCorp\Vagrant\embedded\mingw64\bin` and installing manually it works without a problem. So that is kinda weird.

**Comment by lanoumet** [comment]
hey, 
first, I'm sorry I can't help you. I don't understand almost nothing about this.
I have the same error trying to run vagrant plugin install vagrant-vbguest on windows 10
It would be very kind if you could tell me how to install it manually.

**Comment by bbrala** [comment]
I removed vagrant completely and reinstalled, and the problems disappeared...
