### ISSUE TITLE
add new option to vagrant destroy to poweroff vm 

### ISSUE THREAD

**Issue by kikitux** [hashicorp/vagrant#10292]
As today, vagrant destroy will try to do a graceful vm poweroff.

would be nice to have a modifier, ie 

```
vagrant destroy --poweroff
```

That would power off directly the VM instead of doing a graceful stop.

This will help to speedup vm destroy in cases like windows guest doing windows update, as wait for this task to complete and then destroy the VM seems pointless.

Thanks!

**Comment by michalmiddleton** [comment]
Hi, to further clarify, I am not necessarily asking for a new feature. 
`vagrant destroy` powers off (forcefully) a vm when it's used with virtualbox provider. 

The behavior differs with vmware_desktop provider, which shuts down the VM gracefully (calls `vmrun stop <path to vmx>`). 

After some digging, it appears that vmrun syntax is `vmrun stop <path to vmx> (soft|hard)` where `soft` is the default. 

Assuming your plugin has a dedicated routine for destroy and halt, it may be as simple as adding `hard` to the end of your vmrun call.

**Comment by chrisroberts** [comment]
@michalmiddleton Thanks for the clarification. I'll have a look at the plugin and update its behavior to match the virtualbox provider (force stop when graceful stop fails). We're also looking to add a `--poweroff` feature as well so we'll be leaving this issue open for the original request. Cheers!

**Comment by StefanScherer** [comment]
<img width="1440" alt="vagrant-destroy-run-windows-updates-first" src="https://user-images.githubusercontent.com/207759/48047853-b94edf80-e199-11e8-8f46-b4ae8ed17eda.png">

It would be a huge time safer if the VMware plugin behaves the same as in VirtualBox. I often see this when I just want to get rid of a Windows Vagrant box :-)

**Comment by StefanScherer** [comment]
Thanks @soapy1 
I saw the PR for virtualbox and first thought I have to create a new ticket for us VMware users still missing the now two features.
But I looked into the lesser known https://github.com/hashicorp/vagrant-plugin-changelog/blob/master/vagrant-vmware-desktop-changelog.md#211 changelog and found version 2.1.1

> 2.1.1
> Halt guest immediately when destroying

I'll update my plugin and hopefully be much faster now 🏎 :-)
