### ISSUE TITLE
Rsync folder

### ISSUE THREAD

**Issue by beb59** [hashicorp/vagrant#10296]
### Vagrant version
vagrant -v

### Host operating system
windows 10

### Guest operating system
Debian 9

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
	config.vm.define "web" do |web|
		web.vm.box = "debian/stretch64"
		web.vm.hostname = "web"

		web.vm.synced_folder "sites/", "/var/www/sites", type: "nfs"
		web.vm.network "public_network"
	end

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
	end
end

```

==> web: Rsyncing folder: /cygdrive/d/vm/main/ => /vagrant ???? but in config only "sites/"

Error
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL   -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'D:/vm/main/.vagrant/machines/web/virtualbox/private_key'" "--exclude" ".vagrant/" "/cygdrive/d/vm/main/" "vagrant@127.0.0.1:/vagrant"
Error: rsync: write failed on "/vagrant/push/template/assets/fonts/fontawesome-webfont.ttf": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(393) [receiver=3.1.2]

**Comment by briancain** [comment]
Hi there @beb59 -

Vagrant defaults to always sharing your home folder to the path `/vagrant` on your guest. This box must default to rsync, and it looks like it doesn't have much space left either after attempting to sync your folder, thus the error. You can disable syncing your current working dir by adding this line to your Vagrantfile inside your `web` guest:

```ruby
web.vm.synced_folder ".", "/vagrant", disabled: true
```

Thanks!
