### ISSUE TITLE
Encoding error while trying to install any vagrant plugin! Help!

### ISSUE THREAD

**Issue by mrbagoda** [hashicorp/vagrant#10303]
Using the latest cygqwin64 **OR** git bash i cannot install any vagrant plugins! I keep getting an encoding error. I've already tried to change the active page code to 65001 or 1252 and nothing works.
Im using windows 7, and i read something about the registry.rb script looking through the uninstall folder in the registry and encountering bad characters, but I dont see anything funny in there.  I've tried everything and it seems like a lot of people are having the same issue if you search the web.  Please help!

**ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]**

**$ vagrant -v
Vagrant 2.1.5**

> $ vagrant plugin install vagrant-proxyconf
> Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
> C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:651:in `encode': incomplete "\x00" on UTF-16LE (Encoding::InvalidByteSequenceError)
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:651:in `read'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:67:in `read_s'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:119:in `block (5 levels) in get_info'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:117:in `each'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:117:in `find'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:117:in `block (4 levels) in get_info'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:434:in `open'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:541:in `open'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:116:in `block (3 levels) in get_info'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:611:in `each_key'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:115:in `block (2 levels) in get_info'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:434:in `open'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:541:in `open'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:114:in `block in get_info'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:434:in `open'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:541:in `open'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:91:in `get_info'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:21:in `get_resolv_info'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1002:in `default_config_hash'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1019:in `block in lazy_initialize'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1012:in `synchronize'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1012:in `lazy_initialize'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:358:in `block in lazy_initialize'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:356:in `synchronize'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:356:in `lazy_initialize'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:516:in `fetch_resource'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:510:in `each_resource'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:491:in `getresource'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:105:in `api_endpoint'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source.rb:47:in `api_uri'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source.rb:183:in `load_specs'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/bundler.rb:424:in `block in validate_configured_sources!'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each'
>         from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each_source'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/bundler.rb:422:in `validate_configured_sources!'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/bundler.rb:330:in `internal_install'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/bundler.rb:128:in `install'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/action/install_gem.rb:30:in `call'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/warden.rb:34:in `call'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/builder.rb:116:in `call'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `block in run'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/util/busy.rb:19:in `busy'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/action/runner.rb:66:in `run'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/command/base.rb:14:in `action'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/command/install.rb:70:in `block in execute'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/command/install.rb:69:in `each'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/command/install.rb:69:in `execute'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/plugins/commands/plugin/command/root.rb:66:in `execute'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/cli.rb:54:in `execute'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant/environment.rb:291:in `cli'
>         from C:/HashiCorp/Vagrant/embedded/gems/2.1.5/gems/vagrant-2.1.5/bin/vagrant:164:in `<main>'
> 
> 
> 
>

**Comment by chrisroberts** [comment]
@mrbagoda Does your project path or home directory path include unicode characters? Providing a gist with the `--debug` output would be helpful to see the origin of the error.

**Comment by mrbagoda** [comment]
@chrisroberts thanks for the quick reply! What do you mean by providing a gist with --debug output? Sorry, I'm a n00b :-) 
Do you want me to provide you with my path or something?

**Comment by chrisroberts** [comment]
@mrbagoda Hi there. If you run the command and include the `--debug` flag, it will generate a bunch of output which makes it easier for us to diagnose the problem. So the command you would run would look like this:

```
vagrant plugin install vagrant-proxyconf --debug
```

Then you can copy the output and paste it into a new gist (https://gist.github.com). After you save the gist, copy the URL and paste it into a comment here.

**Comment by germaino** [comment]
I have the same issue and even with the latest version 2.2.0.  I found a workaround by patching the file C:\HashiCorp\Vagrant\embedded\mingw64\lib\ruby\2.4.0\win32\registry.rb with the following code:

diff --git a/registry.rb b/registry.rb
index a88d7e6..442986d 100644
--- a/registry.rb
+++ b/registry.rb
@@ -649,7 +649,12 @@ For detail, see the MSDN[http://msdn.microsoft.com/library/en-us/sysinfo/base/pr
       end
       case type
       when REG_SZ, REG_EXPAND_SZ
-        [ type, data.encode(name.encoding, WCHAR).chop ]
+        #OG Fix, do not encode if empty
+        if data.chop.empty?
+        [ type, data ]
+        else
+          [ type, data.encode(name.encoding, WCHAR).chop ]
+        end
       when REG_MULTI_SZ
         [ type, data.encode(name.encoding, WCHAR).split(/\0/) ]
       when REG_BINARY

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
