### ISSUE TITLE
Mojave error: Please fix the following errors and try again

### ISSUE THREAD

**Issue by jeffPOG** [hashicorp/vagrant#10318]
I'm running mac OS Mojave 10.14 vagrant 2.1.5 

When I run` vagrant up `I get this:
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

salt provisioner:
* The following settings shouldn't exist: verbase
* The specified minion_config '/Users/jeff.sikala.i/Documents/Devops_training/Salt_training/saltstates/vagrant-salt/minion_config' file could not be found.
```

what is this minion_config file I need and what is the verbase part about? 
Anybody know what's going on here?

**Comment by briancain** [comment]
@jeffPOG - we can't be very helpful without seeing your Vagrantfile but you should read the Salt provisioner docs first: https://www.vagrantup.com/docs/provisioning/salt.html

`verbase` is not an option, and it looks like it is a typo of `verbose`. The other error is just saying that a file doesn't exist. It needs to exist if you want to use that config.

Any other general questions should be directed at the mailing list, so I'm going to go ahead and close this as they are not bugs. Thanks!
