### ISSUE TITLE
rsync__auto not working on windows 10

### ISSUE THREAD

**Issue by noshky** [hashicorp/vagrant#10327]
### Vagrant version
``Vagrant 2.2.0``

### Host operating system
Windows 10 64 bit

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
config.vm.synced_folder ".", "/home/vagrant/sync", type: "rsync", rsync__auto: true
```

### Expected behavior
Changes in the host directory should be synced automatically to the guest file system. This should even be the case if I omit the ``rsync__auto`` parameter, because it's default value should be ``true`` (https://www.vagrantup.com/docs/synced-folders/rsync.html#rsync__auto).

### Actual behavior
No changes are synced automatically, with or without the ``rsync__auto: true`` parameter specified.
``vagrant rsync-auto`` needs to be run in an background process. This is annoying, and at least misleading from the documentation of ``rsync__auto``.

### Steps to reproduce
1. ``vagrant up``
2. ``cd /home/vagrant/sync"
3. ``ls``
4. (in the host) ``touch test.txt`` (or equivalent under Windows)
5. (in the guest) ```ls`` -> Notice that no file ``test.txt`` exists

### References
This issue was reported multiple times in the past, but always closed in the hope that new vagrant versions had fixed the problem already. Well, it hasn't:
- https://github.com/hashicorp/vagrant/issues/4862
- https://github.com/hashicorp/vagrant/issues/3350

**Comment by chrisroberts** [comment]
Hi there,

The `rsync-auto` command must be run explicitly within the Vagrant project directory. This requirement is stated in the documentation:

> rsync__auto (boolean) - If false, then rsync-auto will not watch and automatically sync this folder. By default, this is true. **Note: This option will not automatically invoke the rsync-auto subcommand.**

https://www.vagrantup.com/docs/synced-folders/rsync.html#rsync__auto

Vagrant will not automatically start the `rsync-auto` subcommand. It is up to the user to start the command to enable syncing. 

Cheers!
