### ISSUE TITLE
ERROR loader: Unknown config sources / CheckpointType is not available. Cannot enable checkpoints.

### ISSUE THREAD

**Issue by vchrizz** [hashicorp/vagrant#10323]
### Vagrant version
Vagrant 2.2.0

### Host operating system
Windows Server 2012 R2 [Version 6.3.9600] (German)

### Guest operating system
[generic/debian8](https://app.vagrantup.com/generic/boxes/debian8)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  #config.vm.box = "debian/stretch64" # does not support provider hyperv
  config.vm.box = "generic/debian8"
  config.vm.network "public_network", bridge: "Extern Silver-Server"
  config.vm.define "vchrizz-testhost"
  config.vm.hostname = "dev8"
  config.vm.provider :hyperv do |hv|
    hv.vmname = "vchrizz-testhost"
    hv.cpus = 2
    hv.memory = 2048
    hv.vlan_id = 1100
    hv.enable_checkpoints = true
    # hv.enable_virtualization_extensions = true
    hv.linked_clone = true
    hv.auto_start_action = "StartIfRunning"
    hv.auto_stop_action = "Save"
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "Europe/Vienna" > /etc/timezone
    ln -fs /usr/share/zoneinfo/Europe/Vienna /etc/localtime
    apt-get update
    apt-get install -y ssh sudo
    useradd -m -s /bin/bash onetrix
    echo 'onetrix:newpassword' | chpasswd
    #adduser onetrix sudo
    echo 'onetrix   ALL=NOPASSWD: ALL' >> /etc/sudoers
    # setup jenkins-debian-glue
    wget https://raw.github.com/mika/jenkins-debian-glue/master/puppet/apply.sh
    sudo bash ./apply.sh changemenow
    # add custom user
    echo 'jenkins.model.Jenkins.instance.securityRealm.createAccount("newuser", "newpassword")' | sudo java -jar /var/cache/jenkins/war/WEB-INF/jenkins-cli.jar -s "http://localhost:8080" -auth jenkins-debian-glue:changemenow -noKeyAuth groovy =
    # access http://<ip-of-vm>:8080
  SHELL
end
```

### Debug output
https://gist.github.com/vchrizz/fda1704c649518ab2a11e6c96ef1b7b3

### Expected behavior
Expected a vm to be created according to Vagrantfile

### Actual behavior
VM was created without a vlan set but not startet because error interrupted

### Steps to reproduce
1. install vagrant, copy write_messages.ps1 (see #10320)
2. create new folder, copy Vagrantfile into it
3. vagrant up
(I tried to uninstall vagrant, reboot, install vagrant, reboot, but it still happens)

The same happens when I try in a new empty directory:
1. vagrant init generic/debian9
2. vagrant up
ERROR loader: Unknown config sources: [:"26064080_generic/debian9_hyperv", :"34531540_vm_default_gen
eric/debian9_hyperv"]

### References
- #10320

**Comment by vchrizz** [comment]
I could fix it by setting enable_checkpoint to false:

```
  config.vm.provider :hyperv do |hv|
    hv.enable_checkpoints = false
  end
```

By default it is set to true, thats why new instances also have this problem.
As soon as I've set this to false in the new instance, it worked (and also my vm with given Vagrantfile works now)

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
