### ISSUE TITLE
share --ssh doesn't return name to connect to

### ISSUE THREAD

**Issue by dimisjim** [hashicorp/vagrant#10328]
I am trying to do a `vagrant share --ssh` for my running box, but the output is stuck at (no error outputted):

>     share: Inserting generated public key within guest...
>     share: Removing insecure key from the guest if it's present...
>     share: Key inserted! Disconnecting and reconnecting using new SSH key...
>     share: Machine booted and ready!

So, based on this: https://www.vagrantup.com/docs/share/ssh.html I should get a name after that, which I don't.

Tested this on ubuntu 18.04, with vagrant 2.2.0, using vagrant-share 0.1.0 and virtualbox provider. 

Here's my full output:

> $ vagrant share --ssh
> Vagrant Share now defaults to using the `ngrok` driver.
> The `classic` driver has been deprecated.
> 
> For more information about the `ngrok` driver, please
> refer to the documentation:
> 
>   https://www.vagrantup.com/docs/share/
> 
> ==> y-dev-env-base: Detecting network information for machine...
>     y-dev-env-base: Local machine address: 127.0.0.1
>     y-dev-env-base:  
>     y-dev-env-base: Note: With the local address (127.0.0.1), Vagrant Share can only
>     y-dev-env-base: share any ports you have forwarded. Assign an IP or address to your
>     y-dev-env-base: machine to expose all TCP ports. Consult the documentation
>     y-dev-env-base: for your provider ('virtualbox') for more information.
>     y-dev-env-base:  
>     y-dev-env-base: An HTTP port couldn't be detected! Since SSH is enabled, this is
>     y-dev-env-base: not an error. If you want to share both SSH and HTTP, please set
>     y-dev-env-base: an HTTP port with `--http`.
>     y-dev-env-base:  
> ==> y-dev-env-base: Generating new SSH key...
>     y-dev-env-base: Please enter a password to encrypt the key: 
>     y-dev-env-base: Repeat the password to confirm: 
> /home/jim/.vagrant.d/gems/2.4.4/gems/vagrant-share-1.1.9/lib/vagrant-share/activate.rb:590: warning: constant OpenSSL::Cipher::Cipher is deprecated
>     y-dev-env-base: Inserting generated SSH key into machine...
>     y-dev-env-base: Local HTTP port: disabled
>     y-dev-env-base: Local HTTPS port: disabled
>     y-dev-env-base: SSH Port: 2222
>     y-dev-env-base: Port: 2222
> ==> y-dev-env-base: Creating Vagrant Share session...
>     share: Box 'hashicorp/vagrant-share' could not be found. Attempting to find and install...
>     share: Box Provider: virtualbox
>     share: Box Version: >= 0
>     share: Loading metadata for box 'hashicorp/vagrant-share'
>     share: URL: https://vagrantcloud.com/hashicorp/vagrant-share
>     share: Adding box 'hashicorp/vagrant-share' (v0.1.0) for provider: virtualbox
>     share: Downloading: https://vagrantcloud.com/hashicorp/boxes/vagrant-share/versions/0.1.0/providers/virtualbox.box
>     share: Download redirected to host: s3.amazonaws.com
>     share: Successfully added box 'hashicorp/vagrant-share' (v0.1.0) for 'virtualbox'!
>     share: Importing base box 'hashicorp/vagrant-share'...
>     share: Matching MAC address for NAT networking...
>     share: Setting the name of the VM: share-1368ccd9-e05f-4daf-a516-be650730ab5c
>     share: Fixed port collision for 22 => 2222. Now on port 2200.
>     share: Clearing any previously set network interfaces...
>     share: Preparing network interfaces based on configuration...
>     share: Adapter 1: nat
>     share: Forwarding ports...
>     share: 31338 (guest) => 65535 (host) (adapter 1)
>     share: 22 (guest) => 2200 (host) (adapter 1)
>     share: Running 'pre-boot' VM customizations...
>     share: Booting VM...
>     share: Waiting for machine to boot. This may take a few minutes...
>     share: SSH address: 127.0.0.1:2200
>     share: SSH username: tc
>     share: SSH auth method: password
>     share: 
>     share: Inserting generated public key within guest...
>     share: Removing insecure key from the guest if it's present...
>     share: Key inserted! Disconnecting and reconnecting using new SSH key...
>     share: Machine booted and ready!

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by dimisjim** [comment]
No problem. Here's the full log https://gist.github.com/dimisjim/3b26e1e8dc2169de346c58c2c53212b9

**Comment by ronmcmillian** [comment]
I'm having this same issue

**Comment by akukhar** [comment]
I am having the same issue – no data after the line"Machine booted and ready" when running `vagrant share --ssh`

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
