### ISSUE TITLE
Vagrant winrm fetches ipv6 address and fails to connect. 

### ISSUE THREAD

**Issue by RashmiRamanna** [hashicorp/vagrant#10334]
I see this issue is fixed for hiper-v 

https://github.com/hashicorp/vagrant/pull/8831/files

It will be great if you provide the solution for vsphere as well.

This issue is same as https://github.com/hashicorp/vagrant/issues/8759

**Comment by chrisroberts** [comment]
Hi there,

The vSphere provider for Vagrant is provided as a Vagrant plugin by a third party and is not part of Vagrant. Please refer any issues to the source repository for the plugin which can be found here: https://github.com/nsidc/vagrant-vsphere

Cheers!
