### ISSUE TITLE
`encode': "\xC7" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to WINDOWS-1256 (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by Anas133** [hashicorp/vagrant#10331]
Hi, I had a problem when I run "vagrant init ubuntu/trusty64" in my Git Bash.

my operating system is Windows 8.1 and I just download Vagrant and VirtualBox.

This what I got.

> $ vagrant init ubuntu/trusty64
C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/platform.rb:255:in `encode': "\xC7" to UTF-8 in conversion from ASCII-8BIT to UTF-8 to WINDOWS-1256 (Encoding::UndefinedConversionError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/platform.rb:255:in `block (2 levels) in fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/platform.rb:253:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/platform.rb:253:in `block in fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/platform.rb:252:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/util/platform.rb:252:in `fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:124:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:144:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:144:in `<main>'

>

**Comment by briancain** [comment]
Hi @Anas133 - if you follow the instructions on this comment, does the error go away? https://github.com/hashicorp/vagrant/issues/9640#issuecomment-380574611

**Comment by Anas133** [comment]
> Hi @Anas133 - if you follow the instructions on this comment, does the error go away? [#9640 (comment)](https://github.com/hashicorp/vagrant/issues/9640#issuecomment-380574611)

Hi thanks for that but I have changed it and then change the directory of the file since the user is in the Arabic language and got this error.

> $ vagrant init ubuntu/trusty64
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:230:in `mkdir': Invalid argumen                                                             t @ dir_s_mkdir - C:/Users/??? (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:230:in `fu_mkdir'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:208:in `block (2 l                                                             evels) in mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:206:in `reverse_ea                                                             ch'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:206:in `block in m                                                             kdir_p'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:191:in `each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:191:in `mkdir_p'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.                                                             rb:824:in `block in setup_home_path'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.                                                             rb:819:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.                                                             rb:819:in `setup_home_path'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.                                                             rb:135:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:144:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:144:in `<mai                                                             n>'

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
