### ISSUE TITLE
chef-solo provision failed when downloading cookbook from artifactory

### ISSUE THREAD

**Issue by sharavanan2010** [hashicorp/vagrant#10337]
Running chef-solo provision script by specifying the chef.recipe_url in vagrantfile is failing to up the machine

### Vagrant version
vagrant 2.0.2
Vagrant VMWare Utility 1.0.0
Vagrant vmware desktop plugin 1.0.0 
Python 3.4.3

### Host operating system
Windows 10

### Guest operating system
windows_10_client_pro_rs5_32_eng

### Vagrantfile
https://gist.github.com/sharavanan2010/7fa4e3afa78ef2487cc0b897469ca820

### Debug output
https://gist.github.com/sharavanan2010/2f7e8e2b26f982d2dc03f9dac953c093

I have attached the cookbook tar file for reference

### Expected behavior
Able to trigger chef-solo provision by specifying the recipe_url from artifactory

### Actual behavior
chef-solo provision was failing

### References

**Comment by sharavanan2010** [comment]
Cookbook
[mason.zip](https://github.com/hashicorp/vagrant/files/2518940/mason.zip)

Created VM C Drive
![image](https://user-images.githubusercontent.com/39905551/47563154-72155300-d93e-11e8-9026-2542c68c63ff.png)

JFROG Artifactory Structure of cookbook
![image](https://user-images.githubusercontent.com/39905551/47563229-b3a5fe00-d93e-11e8-87da-011c0da602d2.png)

**Comment by sharavanan2010** [comment]
Couple of queries:
1. Is anything wrong in cookbook format
2. Is anything wrong in provision tag config in vagrantfile

**Comment by sharavanan2010** [comment]
Error Message:
=> default: [2018-10-26T23:52:50-07:00] DEBUG:
==> default: --- RESPONSE (412) ---
==> default: {
==> default:   "error": [
==> default:     "No such cookbook: mason"
==> default:   ]
==> default: }
==> default: --- END RESPONSE ---
==> default: ================================================================================
==> default: Error Resolving Cookbooks for Run List:
==> default: ================================================================================
==> default: Missing Cookbooks:
==> default: ------------------
==> default: No such cookbook: mason
==> default: Expanded Run List:
==> default: ------------------
==> default: * mason
==> default: System Info:
==> default: ------------
==> default: chef_version=14.6.47
==> default: platform=windows

Vagrantfile chef-solo config:
  config.vm.provision "chef_solo" do |chef|
       chef.recipe_url = "https://jfrog_artifactory.x.y.com/artifactory/ssa-chef-local-dev/mason/0.1.6/mason-0.1.6.tgz"
       chef.log_level = :debug
       chef.add_recipe "mason"
  end

I would like to know,
1. Where vagrant downloads chef cookbook from artifactory to local VM path?

is anything wrong in my config?

**Comment by sharavanan2010** [comment]
Need your help to get right direction

**Comment by chrisroberts** [comment]
Closing as this appears to be an issue with local chef-zero configuration. The error indicates that the node data is unavailable from the chef-zero instance which points to likely an initial setup error.

Cheers.
