### ISSUE TITLE
Feature request: add a 'vagrant box current' subcommand

### ISSUE THREAD

**Issue by RohanTalip** [hashicorp/vagrant#10344]
Being able to determine what the current box version is would be useful.  It could be similar to the output from `vagrant box list`, just showing one line for the current box version:
```
$ vagrant box current
ubuntu/bionic64 (virtualbox, 20181024.0.0)
```

An alternative could be to show the current box version in the output from `vagrant box list`, e.g. : 
```
$ vagrant box list
ubuntu/bionic64 (virtualbox, 20181018.0.0)
ubuntu/bionic64 (virtualbox, 20181024.0.0) -- current
```

If necessary, this change in output could be triggered by a command line argument (e.g. -v or -i), in case anyone has scripts depending on the current output format.

See also #10339.

**Comment by RohanTalip** [comment]
@briancain, thanks for the info, however `vagrant cloud box show ...` requires me to create a Vagrant Cloud account:

```
$ vagrant cloud box show ubuntu/bionic64
In a moment we will ask for your username and password to HashiCorp's
Vagrant Cloud. After authenticating, we will store an access token locally on
disk. Your login details will be transmitted over a secure connection, and
are never stored on disk locally.

If you do not have an Vagrant Cloud account, sign up at
https://www.vagrantcloud.com

Vagrant Cloud username or email: 
```

It seems like a little overkill to just display the version number of a box that has already been downloaded (but may be out of date). 😄 

Just to clarify, by "current version", I mean the version that the current machine (as inferred from the local Vagrantfile) will be running or is already running, not the most recent version that is available on vagrantcloud.com (although that is useful too).

**Comment by briancain** [comment]
Ah I see, I misunderstood what the feature request was then. In that case, I think it probably makes sense to modify `vagrant box list` still over a single subcommand. If people want to see only "current" boxes they could always use grep to filter out the list itself like `vagrant box list | grep current`

**Comment by briancain** [comment]
It could also include a `--current` flag as well to only display the latest boxes.

**Comment by briancain** [comment]
Hi there - after some thought on this, I don't know if this enhancement makes sense to add. I think the `current` indicator will cause some confusion, misleading people to believe the box is the current, up-to-date latest release. If you want to see the latest downloaded box, I don't think it's too bad to just look at the box list output and find it there. I can't really think of any automated reason why you would want to know the newest locally downloaded box, but if you think of one we can re-open this ticket if it's a valid use case. Thanks for the issue though! :heart:
