### ISSUE TITLE
synced_folder: mount_options: SELinux context not a supported option?

### ISSUE THREAD

**Issue by apolopena** [hashicorp/vagrant#10354]
vagrant synced_folders command by default sets the the SELinux context of the directory to: 
`system_u:object_r:vmblock_t:s0'` no matter what.  `system_u:object_r:vmblock_t:s0` context is incompatible with httpd (apache), I need to be able to set the SELinux context via the synced_folder command to `unconfined_u:object_r:httpd_sys_content_t:s0`. So far I have tried the following commands with no success:
``config.vm.synced_folder "sync/host/html", "/var/www/virtualhost1/public_html/synced", :owner => "apache", :group => "apache", mount_options:[context='httpd_sys_content_t']``

``config.vm.synced_folder "sync/host/html", "/var/www/virtualhost1/public_html/synced", :owner => "apache", :group => "apache", mount_options:['context=httpd_sys_content_t']``

``config.vm.synced_folder "sync/host/html", "/var/www/virtualhost1/public_html/synced", :owner => "apache", :group => "apache", mount_options:['context=unconfined_u:object_r:httpd_sys_content_t:s0']``

The following error is returned from vagrant
mount -t vboxsf -o httpd_sys_content_t,uid=48,gid=48 var_www_virtualhost1_public_html_synced /var/www/virtualhost1/public_html/synced

The error output from the command was:

``unknown mount option `httpd_sys_content_t'``
valid options:
  rw         mount read write (default)
  ro         mount read only
  uid       =<arg> default file owner user id
  gid       =<arg> default file owner group id
  ttl       =<arg> time to live for dentry
  iocharset =<arg> i/o charset (default utf8)
  convertcp =<arg> convert share name from given charset to utf8
  dmode     =<arg> mode of all directories
  fmode     =<arg> mode of all regular files
  umask     =<arg> umask of directories and regular files
  dmask     =<arg> umask of directories
  fmask     =<arg> umask of regular files

I am unsure if this is a bug or if I simply have incorrect syntax for setting the mount_options.

**Comment by apolopena** [comment]
I think this issue has been differed ad probably should be closed
see:
https://github.com/hashicorp/vagrant/issues/8261

**Comment by chrisroberts** [comment]
Correct as it's not a supported mount option. Closing.
