### ISSUE TITLE
Failing to re-install vagrant 2.2.0 on CentOS 7

### ISSUE THREAD

**Issue by RashmiRamanna** [hashicorp/vagrant#10367]
Hi There,

I had previously installed vagrant 2.2.0 on to my Cent OS 7 machine. because of the other issue, I tried to uninstall and install it again. But it is failing to install.

Steps I followed to uninstall vagrant

rm -rf /opt/vagrant
rm -f /usr/bin/vagrant
rm -rf ~/.vagrant.d

Steps I followed to install vagrant again

sudo yum -y install https://releases.hashicorp.com/vagrant/2.2.0/vagrant_2.2.0_x86_64.rpm

Error I am seeing on install command:

Loaded plugins: fastestmirror, langpacks
vagrant_2.2.0_x86_64.rpm
Examining /var/tmp/yum-toot-zXcI2a/vagrant_2.2.0_x86_64.rpm: 1:vagrant-2.2.0-1.x86_64
/var/tmp/yum-toot-zXcI2a/vagrant_2.2.0_x86_64.rpm: 1:vagrant-2.2.0-1.x86_64.rpm: does not update installed package.
Error: Nothing to do

**Comment by briancain** [comment]
Hi @RashmiRamanna - You need to _remove_ the package with yum. Deleting certain directories is not sufficient enough for uninstalling Vagrant.

 ```
sudo yum remove vagrant
sudo yum -y install https://releases.hashicorp.com/vagrant/2.2.0/vagrant_2.2.0_x86_64.rpm
```

Thanks!
