### ISSUE TITLE
vagrant destroy -f sometimes fails to destroy the VM

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10377]
I think I have noticed `vagrant destroy -f` leaving VM's around in VirtualBox, though the VM's are absent from `vagrant global-status` .

**Comment by briancain** [comment]
Hi @mcandre - thanks for the report, however without a debug log showing the problem it's very difficult for us to really help out. If you happen to reproduce it while running `vagrant destroy --debug` then open a new issue with the debug log. Thanks!

**Comment by mcandre** [comment]
Noted, I'll try to include as much debugging information as I can the next time this happens. However, I don't normally run `vagrant destroy -f` with the `--debug` flag, from that standpoint, there is not much to report. It's an annoyance that appears to happen maybe 5% of the time.

**Comment by briancain** [comment]
It would also be helpful if there was anything in the VirtualBox logs. I bring up and destroy VirtualBox machines all the time and haven't seen this behavior :thinking: It could also depend on what version of VirtualBox you're using and on what platform.
