### ISSUE TITLE
Cannot get any boxes to work - Always 404 error.

### ISSUE THREAD

**Issue by tjtaylo** [hashicorp/vagrant#10378]
I've went through the getting started tutorial 3 times. Then attempted to setup the following boxes:

- ubuntu/trusty64
- hashicorp/precise64
- ncaro/php7-debian8-apache-nginx-mysql

No matter what I use I always get 404 errors. I've tried putting html files in the root folder, var, var/www, var/www/html. Nothing works. I've tried putting "ServerName localhost" in the vhosts.conf file, no luck. I've spent hours searching the web and reading through documentation; tried every solution online and nothing works. I tried setting it up on a different machine, no luck there either. What could I possibly be doing wrong?

### Vagrant version
2.2.0

### Host operating system
10.10.5

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 4567
end

### Debug output
https://gist.github.com/tjtaylo/16f369bb21a8950777d4ed007bf27699

### Expected behavior
Loaded index.html

### Actual behavior
404 errors 

### Steps to reproduce
1. Getting started tutorial

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
