### ISSUE TITLE
global-status incorrect

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10380]
`vagrant global-status` often reports innacurate results, even with `--prune` applied.

Using Vagrant 2.2.0, VirtualBox 5.2.20r125813, macOS Mojave.

<img width="834" alt="vagrant-status" src="https://user-images.githubusercontent.com/5316/48107247-783fe500-e204-11e8-97d0-1b37ade1a35c.png">

<img width="1552" alt="virtualbox-status" src="https://user-images.githubusercontent.com/5316/48107248-783fe500-e204-11e8-9a11-4c3ce84422e9.png">

**Comment by chrisroberts** [comment]
Hi there,

Can you please provide more context on when you are seeing issues and what issues you are experiencing. I am assuming the images in this issue are referencing the fact that the freebsd entry is missing from the global-status output. Was that guest brought up successfully or did Vagrant fail during the initial provisioning of the guest? Has the `.vagrant.d` directory or any of the files within been modified by anything other than Vagrant? If you are seeing inaccurate results often, is there any common situation that causes the issue to reproduce itself?

Would you also please provide a gist of the debug output so we can inspect it and identify if there are any issues affecting the results.

Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
