### ISSUE TITLE
(EDITED) FR: Sanity checks for boxes (usable in multi machine environments, etc.)

### ISSUE THREAD

**Issue by danowar2k** [hashicorp/vagrant#10407]
### Vagrant version
2.2.0

### Host operating system
Windows 7

### Guest operating system
Solaris 11.3

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  (2..3).each do |i|
    config.vm.define "dev-#{i}", autostart: false do |dev_vm_config|
      dev_vm_config.vm.hostname = "dev-#{i}"
      dev_vm_config.vm.box = "heavybeans/solaris11-small-server"
      dev_vm_config.vm.network "private_network", ip: "192.168.33.#{i}"
      dev_vm_config.vm.synced_folder ".", "/vagrant", disabled: true
    end
  end
end
```
### Debug output
https://gist.github.com/danowar2k/6a2c423b5a7f85cd5559b8f2289ab873

### Expected behavior
There should be some fail-safe mechanism that checks if a host port (in this case 2222) is being forwarded to by multiple machines and maybe throw an error if the Vagrantfile would result in such fail state. Ideally Virtualbox would prevent forwarding to the same port twice, but it doesn't, so....

### Actual behavior
dev-2 forwarded 22 to 2222.
dev-3 forwarded 22 to 2222.
No one was warned of anything and so the up process was broken as soon as the second forward existed.

### Steps to reproduce
1. export VAGRANT_LOG=debug; vagrant up dev-2 dev-3

**Comment by danowar2k** [comment]
The gist above is sloooow as molasses. So here's the link to the raw gist:
https://gist.githubusercontent.com/danowar2k/6a2c423b5a7f85cd5559b8f2289ab873/raw/285ece76c17607f0f4d5301f67670679763b98c0/vagrant-up.out

**Comment by danowar2k** [comment]
More info: The relevant lines in the box.ovf:
``` xml
<NAT>
   <DNS pass-domain="true" use-proxy="false" use-host-resolver="false"/>
   <Alias logging="false" proxy-only="false" use-same-ports="false"/>
   <Forwarding name="SSH" proto="1" hostport="2222" guestport="22"/>
</NAT>
```
The relevant code in Vagrant (at least I think it is):
Source: https://github.com/hashicorp/vagrant/blob/master/plugins/providers/virtualbox/driver/version_5_0.rb
``` ruby
def ssh_port(expected_port)
  @logger.debug("Searching for SSH port: #{expected_port.inspect}")

  # Look for the forwarded port only by comparing the guest port
  read_forwarded_ports.each do |_, _, hostport, guestport|
    return hostport if guestport == expected_port
  end

  nil
end
```

**Comment by danowar2k** [comment]
Waaaait! *sigh* This is NOT what happens with this configuration! See later in the gist:
```
 INFO handle_port_collisions: Repaired FP collision: 2222 to 2200
 INFO interface: info: Fixed port collision for 22 => 2222. Now on port 2200.
 INFO interface: info: ==> dev-3: Fixed port collision for 22 => 2222. Now on port 2200.
==> dev-3: Fixed port collision for 22 => 2222. Now on port 2200.
[...]
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG virtualbox_5_2:   - [1, "SSH", 2222, 22, ""]
DEBUG virtualbox_5_2:   - [1, "ssh", 2200, 22, "127.0.0.1"]
 INFO interface: detail: SSH address: 127.0.0.1:2222
 INFO interface: detail:     dev-3: SSH address: 127.0.0.1:2222
    dev-3: SSH address: 127.0.0.1:2222
```
Vagrant takes the first port 22 forwarding (the one that is baked into the ovf, the 2222 one) and uses it for SSH connections.

Maybe a better request would be ... to be able to check if boxes are usable for multi machine environments?

**Comment by chrisroberts** [comment]
I see, the port forward directive is embedded in the source guest. The ideal fix for this would be to rebuild the box without port forwards baked into the guest. However, I can see how the driver method to detect the ssh port can be cleaned up to be a bit more restrictive in how it detects a valid match. I'll update the check to be a bit more thorough to prevent false positive matches in cases like this.

**Comment by danowar2k** [comment]
Yes, the ideal fix would be to fix the box. Some problems with Vagrant boxes on Vagrant Cloud that play into this are:

- I can't add comments to boxes on Vagrant Cloud so I can't warn other people to not use the box for a multi machine configuration
- I can't contact the box publisher because I haven't found any contact form or contact data apart from "heavybeans"
- A box isn't connected to a github or other source repository where the ovf files would be stored (if they could be updated independently from the box file)

Could Vagrant validate box files (or only ovf files) and print out a warning if there are baked in port forwards and print out a warning if there are any?

**Comment by chrisroberts** [comment]
I don't think that adding box validation for issues like this are something that we would include within Vagrant. While it may not be recommended, or ideal, there are use cases where it is correct for a given user. Fixing the ssh port detection to properly pick the correct entry from multiple results will fix this issue you are seeing.

Cheers!

**Comment by danowar2k** [comment]
An idea for the detection: How about adding port forwarding ids that have the prefix "vagrant." ?
Then you could be reasonably sure that the port forward entry was made by Vagrant...

**Comment by danowar2k** [comment]
There are use cases where allowing the same host port to be forwarded to by multiple machines is correct? Okay, I always thought that would only lead to chaos...

**Comment by danowar2k** [comment]
One final thought: If I create a VirtualBox VM with Vagrant and then proceed to package the VM to a Vagrant box, an OVF file is generated in the process. So if you want to prevent the "mistake" where forwarded ports are "baked in" the OVF file, you always have to manually remove the forwarded port from the OVF file. Is that correct?

If that is correct, is the workflow
Vagrant -> create VirtualBox VM by using a Vagrant box -> change VM -> package new Vagrant Box
can always lead to forgotten port forwards in the box, can't it?

Just saying...
