### ISSUE TITLE
Vagrant     wget : cmd not found 

### ISSUE THREAD

**Issue by adelhendou** [hashicorp/vagrant#10411]
![image](https://user-images.githubusercontent.com/25694954/48470129-e1b98800-e7f0-11e8-9fe2-a5b0c7c1ea27.png)
After entering vagrant ssh
wget -qO- 127.0.0.1
i get a error wget : command not found

**Comment by chrisroberts** [comment]
The program is not installed on your guest. You will need to install it using the guest's package manager or build it from source. 

Cheers!
