### ISSUE TITLE
error during vagrant up

### ISSUE THREAD

**Issue by dhirusrijan** [hashicorp/vagrant#10412]
Dhirendras-MacBook-Pro:~ dhiru$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/xenial64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "11abc8f6-7270-41c1-8c6b-a7b932c280dc", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'dhiru_default_1542217976426_5822' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by opening a new one. Thank you!

**Comment by Quix0r** [comment]
I'm having the same issue now. I have installed proper kernel modules and I rely on software-based virtualization as my CPU cannot do it. Please just don't close a ticket but ask for providing more information (and what). Then people are not getting drifted away to other software.

**Comment by Quix0r** [comment]
````
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' version '20190514.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3700 (guest) => 13700 (host) (adapter 1)
    default: 3820 (guest) => 13820 (host) (adapter 1)
    default: 3920 (guest) => 13920 (host) (adapter 1)
    default: 4848 (guest) => 14848 (host) (adapter 1)
    default: 5900 (guest) => 15900 (host) (adapter 1)
    default: 7676 (guest) => 17676 (host) (adapter 1)
    default: 8080 (guest) => 18080 (host) (adapter 1)
    default: 8181 (guest) => 18181 (host) (adapter 1)
    default: 8686 (guest) => 18686 (host) (adapter 1)
    default: 9009 (guest) => 19009 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "4ec25a51-a29c-48e8-877e-5728dd8a44e6", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'payara-vagrant_default_1581026728058_30516' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
````

**Comment by Quix0r** [comment]
Ah, okay. He may have ignored the template then. Sorry!

**Comment by briancain** [comment]
@Quix0r please refer to this comment to resolve your issue https://github.com/hashicorp/vagrant/issues/8687#issuecomment-308813850

Next time I recommend opening an new issue or sending message to the mailing list, thanks!
