### ISSUE TITLE
"vagrant version" still shows latest version is 2.2.0, even though version 2.2.1 is available on vagrantup.com

### ISSUE THREAD

**Issue by RohanTalip** [hashicorp/vagrant#10418]
### Vagrant version
```
$ vagrant -v
Vagrant 2.2.0
```

### Host operating system
macOS High Sierra 10.13.6

### Guest operating system
Irrelevant

### Vagrantfile
Irrelevant

### Debug output
https://gist.github.com/RohanTalip/bb348f658fe08dadcb7c9c366aa05638

### Expected behavior
`vagrant version` should indicate that the latest version is 2.2.1, as that version is now available on the vagrantup.com website.

### Actual behavior
```
$ vagrant version
Installed Version: 2.2.0
Latest Version: 2.2.0
 
You're running an up-to-date version of Vagrant!
```

### References
https://github.com/hashicorp/vagrant/commit/e905ab8c8c85ef53e7b3c9709e408f99bae9730e
https://github.com/hashicorp/vagrant/commit/30d2e52c46df1200f9cc0b1e0c4ca55f204e55d4

**Comment by chrisroberts** [comment]
Latest version lookups are cached for 48 hours. A new lookup will occur once your local cache has expired. Cheers!

**Comment by RohanTalip** [comment]
Ah, good to know.
