### ISSUE TITLE
winssh communicator fails on PowerShell execution policy

### ISSUE THREAD

**Issue by dakcarto** [hashicorp/vagrant#10415]
### Vagrant version
Vagrant 2.2.0

### Host operating system
macOS 10.13.6

### Guest operating system
Windows 10 (latest)

### Provider
VMware 11.0.0

### Vagrantfile
```ruby
Vagrant.require_version ">= 2.2.0"

Vagrant.configure("2") do |config|
    config.vm.guest = :windows
    config.vm.define "my-box-name"
    config.vm.box = "my-user/my-box-name"
    config.vm.box_check_update = true

    config.vm.ignore_box_vagrantfile = true

    config.windows.halt_timeout = 15

    config.vm.communicator = "winssh"
    config.ssh.username = "my_admin_user"
    config.ssh.keys_only = true
    config.ssh.private_key_path = "my_key"
    config.ssh.keep_alive = true

    config.vm.network :forwarded_port, guest: 22, host: 7777, id: "ssh", auto_correct: true

    config.vm.synced_folder "..", "/vagrant"

    config.vm.provision "shell",
        privileged: "true",
        path: 'provision/update-hosts.ps1',
        powershell_args: '-ExecutionPolicy Bypass',
        run: "always"

end
```

### Debug output
(Clipped to just error, but shows the error and internal .ps1 code being run.)
https://gist.github.com/dakcarto/704decee4ee30178fe91133598dd3912

### Expected behavior
`vagrant up` should bring up machine with shared folder without error.

### Actual behavior
Shared folder creation fails on default Win 10 box where the PowerShell script execution policy does not permit running scripts.

This is not during provisioning, but internally, when Vagrant is running its own setup script(s) for shared folder(s). Thus, `vagrant up` never gets to provisioning.

### Steps to reproduce
1. Use latest Win 10 box
2. vagrant up

### References
This line in the` winssh` communicator indicates that `powershell` calls do not try to override `ExecutionPolicy`:
https://github.com/hashicorp/vagrant/blob/master/plugins/communicators/winssh/communicator.rb#L39

Whereas, the `shell` provisioner ensures that `-ExecutionPolicy Bypass` is set, even if it is _not_ in `powershell_args`:
https://github.com/hashicorp/vagrant/blob/master/plugins/provisioners/shell/provisioner.rb#L118-L125

### Suggested fix
Shouldn't the `winssh` communicator also always try to run...
```
powershell -ExecutionPolicy Bypass -File #{remote_name}
```
instead of just
```
powershell -File #{remote_name}
```

Or, maybe the `winssh` communicator could use a `powershell_args` option as well?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
