### ISSUE TITLE
Update net-ssh version

### ISSUE THREAD

**Issue by pkliczewski** [hashicorp/vagrant#10421]
During my work on [vagrant-kubevirt](https://github.com/pkliczewski/vagrant-kubevirt/) I noticed a bug in `SyncedFolders` action. I pushed a PR https://github.com/net-ssh/net-ssh/pull/641 to fix it. Once the PR is merged and new version is tag we need to update net-ssh version to use fixed version.

**Comment by chrisroberts** [comment]
Hi there,

There is no action to be taken on this issue. No new release of net-ssh is currently available and the constraints currently imposed by our dependency will result in the latest version of the library being used until the minor version is bumped.

Cheers
