### ISSUE TITLE
[2.2.1] Unable to install vagrant-aws plugin dependent on nokogiri MacOS 

### ISSUE THREAD

**Issue by lubouski** [hashicorp/vagrant#10420]
### Vagrant version
$ vagrant -v                                                                              
Vagrant 2.2.1

### Host operating system
$ uname -a                                                                                  
Darwin josh-macpro 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

### Debug output
$ sudo vagrant plugin install vagrant-aws                                                 
Installing the 'vagrant-aws' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

    current directory: /Users/xxx-ttttt/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.5/ext/nokogiri
/opt/vagrant/embedded/bin/ruby -r ./siteconf20181116-9142-1m5b9us.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:410:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/xxx-tttt/.vagrant.d/gems/2.4.4/extensions/x86_64-darwin-13/2.4.0/nokogiri-1.8.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/xxx-ttt/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.5 for inspection.
Results logged to /Users/xxx-ttt/.vagrant.d/gems/2.4.4/extensions/x86_64-darwin-13/2.4.0/nokogiri-1.8.5/gem_make.out

### Expected behavior
Plugin installed

### Actual behavior
Errors probably caused by nokogiri gem 

### Steps to reproduce
1. Upload and Install vagrant form https://releases.hashicorp.com/vagrant/2.2.1/vagrant_2.2.1_linux_amd64.zip
2. run plugin installation

**Comment by chrisroberts** [comment]
Hi there,

From the error message you have provided it appears that you do not have development tools installed:

```
The compiler failed to generate an executable file. (RuntimeError) You have to install development tools first.
```

You will need to install development tools on your system to be able to install plugins which include extensions that must be compiled. You can add these tools to macos using:

```
xcode-select --install
```

Cheers!
