### ISSUE TITLE
publish.rb:141:in `absolute_path': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10432]
### Summary

`vagrant cloud publish` produces two different errors:

* When the local box filename is missing, publish.rb reveals an internal nil error. The CLI usage description and validation code should perhaps be updated to require the provider filename.
* Even when the provider filename is provided, the `--description` is ignored in the resulting Vagrant Cloud page.

### Vagrant version

```console
$ vagrant -v
Vagrant 2.2.1
```

### Host operating system

macOS 10.14 Mojave

### Guest operating system

Debian stretch

### bootstrap.sh

```sh
#!/bin/sh
sudo apt-get update &&
    sudo apt-get install -y clang &&
    sudo apt-get autoclean -y &&
    sudo apt-get clean -y &&
    sudo rm -rf /var/lib/apt/lists/* \
        /var/cache/apt/pkgcache.bin \
        /var/cache/apt/srcpkgcache.bin
```

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "mcandre/debian-i386"
    config.vm.box_version = "0.0.1"

    # Prepare for vagrant package
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true

    config.vm.provision "shell", path: "bootstrap.sh"
end
```

### Debug output

https://gist.github.com/mcandre/aeb581b5c2d1cd5c4bb6e5e84a27ae3d

### Expected behavior

Either `vagrant cloud publish`... succeeds, or presents a clear error message about what the user needs to fix in order to be able to publish the box.

### Actual behavior

A strange `no implicit conversion of nil into String` error is presented during a method internal to Vagrant's publish.rb code.

Also, the previous description posted on Vagrant Cloud is now gone!

> There isn't a description.

https://app.vagrantup.com/mcandre/boxes/vagrant-debian-cpp-i386

Evidently `vagrant cloud publish` did not fail atomically :/

### Steps to reproduce

```console
$ git clone https://github.com/mcandre/vagrant-debian-cpp.git
$ git checkout rake
$ cd i386
$ vagrant up
$ vagrant package --output vagrant-debian-cpp-i386.box --vagrantfile export.Vagrantfile
$ vagrant cloud publish <your-namespace-here>/vagrant-debian-cpp-i386 --force --release --description "a Vagrant box for building C/C++ binaries for GNU/Linux (Debian) x86" --short-description "Source: https://github.com/mcandre/vagrant-debian-cpp" 0.0.1 virtualbox
```

# Partial mitigation

I am working around this by mindfully supplying a provider box filename:

```console
$ vagrant cloud publish mcandre/vagrant-debian-cpp-i386 \
    --force \
    --release \
    --description "a Vagrant box for building C/C++ binaries for GNU/Linux (Debian) x86" \
    --short-description "Source: https://github.com/mcandre/vagrant-debian-cpp" \
    0.0.1 \
    virtualbox \
    vagrant-debian-cpp-i386.box
```

This appears to resolve the nil string error in publish.rb, uploading the box contents to Vagrant Cloud. However, the full description configuration continues to be dropped on Vagrant Cloud, displaying:

> There isn't a description.

https://app.vagrantup.com/mcandre/boxes/vagrant-debian-cpp-i386

Am I doing something wrong?

**Comment by briancain** [comment]
Hi @mcandre - A provider/box file is required when running the `vagrant cloud publish` command. Your original command seems to have left that off from the command, which results in the error. The CLI should at least be smart and make sure a file is provided rather than showing that error.

As for the description issue, it could be an issue with your shell. This works for me:

```ruby
brian@localghost:vagrant-sandbox % be vagrant cloud publish briancain/test123 \                             ±[master]
> --force \
> --release \
> --description "a Vagrant box for building C/C++ binaries for GNU/Linux (Debian) x86" \
> --short-description "Source: https://github.com/mcandre/vagrant-debian-cpp" \
> 0.0.1 \
> virtualbox \
> ../packer-templates/bento/builds/debian-9.5.virtualbox.box

You are about to publish a box on Vagrant Cloud with the following options:
briancain/test123:   (v0.0.1) for provider 'virtualbox'
Automatic Release:     true
Box Description:       a Vagrant box for building C/C++ binaries for GNU/Linux (Debian) x86
Box Short Description: Source: https://github.com/mcandre/vagrant-debian-cpp
==> cloud: Creating a box entry...
==> cloud: Box already exists, updating instead...
==> cloud: Creating a version entry...
==> cloud: Version already exists, updating instead...
==> cloud: Creating a provider entry...
==> cloud: Provider already exists, updating instead...
==> cloud: Uploading provider with file /home/brian/code/packer-templates/bento/builds/debian-9.5.virtualbox.box
Progress: 1% (Rate: 1486k/s, Estimated time remaining: 0:04:22)
```
