### ISSUE TITLE
Rewrite in Go

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10431]
Any interest in rewriting Vagrant in Go? We could speed up a lot of the wrapper code by adopting a lightweight compiled language.

I realize this represents a burned in particular for plugin authors, not sure how we could address that. But it would be awesome to not have to depend on a Ruby runtime and simplify the software stack!

**Comment by chrisroberts** [comment]
While the idea is nice, it is not very practical as it would break all existing plugins as well as core features of Vagrant (like the Vagrantfile). The pragmatic approach leads us to perhaps replacing parts where it makes sense, but not an overall rewrite.

Cheers
