### ISSUE TITLE
SHA-256 Checksums are corresponding to other Operating Systems

### ISSUE THREAD

**Issue by ejean555** [hashicorp/vagrant#10434]
Seems like the Checksums are corresponding to the wrong OS. I checked for the:
32bit Windows Vagrant download and that equals Debian Checksum
64bit Windows Vagrant download and that equals Apple OS Checksum 

![image](https://user-images.githubusercontent.com/4504373/48831437-d3b1bd00-ed44-11e8-87d5-cd4c74ca91cd.png)

**Comment by briancain** [comment]
Hey there @ejean555 - The checksums are correct, Notepad is just not displaying the proper line breaks after each entry. This is what the file should look like if you use a different editor:

```
b1b38523d59c4c447f14a9ee0f9e177bf7e2d31222796b9aa2fc697ccc75073a  vagrant_2.2.1_i686.deb
54eda24258bbcdff17a69344dd7a08b7c16e1d7e6892c6a578d5374c3bc72dde  vagrant_2.2.1_i686.msi
8c66b6d016608f4234601c84cda13df1619fe40e53b942e0c4e61a90e62246ae  vagrant_2.2.1_i686.rpm
8dc5e9b2ca0780463c404b277aaacd334868d20654a4a3d17f7f7641beb16d17  vagrant_2.2.1_linux_amd64.zip
c4ed572fff3fa2c6dd02280df6dfaebdeef2d1b9ec3daa2fb7f4193078fb4d82  vagrant_2.2.1_x86_64.deb
84794e12d0037fbd580ff3bc61418c0027dc01ec777a638cae2351c97a758d41  vagrant_2.2.1_x86_64.dmg
54e062d8214cdd99e792d4dc0f85f7c3ac4275d3822102992b4003590371e65f  vagrant_2.2.1_x86_64.msi
3f92fa6135f5dd53a46e06ece9b74124f98b7ea167dc42e78dee8c0e947f68b5  vagrant_2.2.1_x86_64.rpm
b9dc297569329d58fb8b629ac7e43b894f3ad897bbaca6dd810a359b98e4d9a9  vagrant_2.2.1_x86_64.tar.xz
```

I did a check on the two windows packages you mentioned and they are correct. The SHAs for each package are in front of the file, not after. Thanks for checking though! :heart:
