### ISSUE TITLE
network configuration

### ISSUE THREAD

**Issue by junsionzhang** [hashicorp/vagrant#10441]
1. vagrantfile 
`Vagrant.configure("2") do |config|

  config.vm.box = "CENTOS7"
  config.ssh.username = "root"
  config.ssh.password = "111111"

  N = 2
  (1..N).each do |id|
    config.vm.define "haproxy#{id}" do |node|
      node.vm.box = "CENTOS7"
      node.vm.hostname = "haproxy#{id}"
      node.vm.network "private_network", ip: "172.28.128.#{75+id}"
      #node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", auto_config: true
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 4
           vb.name = "haproxy#{id}"
        vb.customize ["modifyvm", :id, "--groups", "/haproxy"]
        vb.customize ["modifyvm", :id, "--nic1", "natnetwork","--nat-network1","natnet1"]
      end
    end
  end
end`
2. operating system:  mac mojave
3. vargant version: 2.2.0
4. error
```
root@127.0.0.1's password:
root@127.0.0.1's password:
    haproxy1: Warning: Authentication failure. Retrying...
```
when comment the` vb.customize ["modifyvm", :id, "--nic1", "natnetwork","--nat-network1","natnet1"]` it works fine.
I want set two NICs ,one is hostonly and the other one is "nat network"

**Comment by junsionzhang** [comment]
I solved it  by changing it to "["modifyvm", :id, "--nic2", "natnetwork","--nat-network2","natnet1"]"

**Comment by deepvoice** [comment]
Are the external IP's getting passed through with this config?

**Comment by junsionzhang** [comment]
> Are the external IP's getting passed through with this config?

yes. what can i do if vm has two nics, one is hostonly and the other one is "nat network"

**Comment by chrisroberts** [comment]
@junsionzhang I believe the root cause of the problem is you are modifying the NAT interface Vagrant configures for communication with the guest. Since Vagrant creates and configures a device, and then you add two networks, there are three devices configured on the guest. The NIC list indexed starting with 1, so you would want to update the NIC at index 2. Changing your argument from `--nic1` to `--nic2` should resolve the issue.

Cheers!

**Comment by junsionzhang** [comment]
> @junsionzhang I believe the root cause of the problem is you are modifying the NAT interface Vagrant configures for communication with the guest. Since Vagrant creates and configures a device, and then you add two networks, there are three devices configured on the guest. The NIC list indexed starting with 1, so you would want to update the NIC at index 2. Changing your argument from `--nic1` to `--nic2` should resolve the issue.
> 
> Cheers!
hello,  thanks you so much . It has been solved now.
