### ISSUE TITLE
There was an error loading a Vagrantfile. The file being loaded and the error message are shown below. This is usually caused by an invalid or undefined variable.  Path: /Users/MacBookPro/hands-on-ansible/Vagrantfile Line number: 10 Message: undefined local variable or method `acs' Macs-MBP:hands-on-ansible MacBookPro$ 

### ISSUE THREAD

**Issue by na3eel** [hashicorp/vagrant#10447]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
This is the operating system that you run locally.

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment]
[The syntax in your Vagrantfile is incorrect. This line:

```ruby
config.vm.define "acs" do [acs]
```

should be updated to:

```ruby
config.vm.define "acs" do |acs|
```

Cheers!

**Comment by na3eel** [comment]
Thank you so much for you help, im now stuck with another error


There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/Users/MacBookPro/hands-on-ansible/Vagrantfile:28: syntax error, unexpected end-of-input, expecting keyword_end


can you please tell why am i seeing this error?

**Comment by na3eel** [comment]
Sorry, i got that above error fixed but i've no clue what this means

Macs-MacBook-Pro:hands-on-ansible MacBookPro$ vagrant up
Bringing machine 'acs' up with 'virtualbox' provider...
Bringing machine 'web' up with 'virtualbox' provider...
Bringing machine 'db' up with 'virtualbox' provider...
==> acs: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    acs: Box Provider: virtualbox
    acs: Box Version: >= 0
==> acs: Loading metadata for box 'ubuntu/trusty64'
    acs: URL: https://vagrantcloud.com/ubuntu/trusty64
==> acs: Adding box 'ubuntu/trusty64' (v20181103.0.0) for provider: virtualbox
    acs: Downloading: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/20181103.0.0/providers/virtualbox.box
    acs: Download redirected to host: cloud-images.ubuntu.com
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
Macs-MacBook-Pro:hands-on-ansible MacBookPro$ ;
