### ISSUE TITLE
Vagrant Cloud: Allow wildcard queries

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10449]
As a curious user, I want Vagrant Cloud to be able to search for available boxes with wildcard queries, such as `alpine3*`, so that I can quickly find related boxes that can suit my needs.

**Comment by briancain** [comment]
I believe this is actually an enhancement on the Vagrant Cloud webapp itself, as the cloud library the cli uses just builds a query param based on the input provided by the user and sends it off to Vagrant Cloud. Just an FYI for myself or others for this issue in the future.

**Comment by chrisroberts** [comment]
Hi there,

This as been resolved on Vagrant Cloud and running a search with the term `alpine3` will provide the expected results.

Cheers
