### ISSUE TITLE
CentOS7 ip_resolver to detect both eth0 and enp0s8

### ISSUE THREAD

**Issue by lubosdz** [hashicorp/vagrant#10445]
Hi, 

could please somebody advise how to rewrite custom `ip_resolver` to work with networking-scripts for both `eth1` (old format) and `enp0s8` (new format)? Some boxes have set `net.ifnames=0 biosdevname=0` some not, it's a [naming mess](https://wiki.centos.org/FAQ/CentOS7) which discourages updating boxes because one never knows what will stop working. I couldn't find example which could auto-detect proper device name format. Currently I use following - with a little tuning it perhaps could auto detect also `eth1`:

```ruby
  config.hostmanager.ip_resolver = proc do |machine|
	result = ""
	machine.communicate.execute("ifconfig enp0s8") do |type, data|
		result << data if type == :stdout
	end
	(ip = /inet (\d+\.\d+\.\d+\.\d+) /.match(result)) && ip[1]
  end
```

Thank you.

### Vagrant version
2.1.1

### Host operating system
Windows 7 x64

### Guest operating system
CentOS 7

**Comment by chrisroberts** [comment]
Hi there,

Easiest path would probably be to use the guest capability to grab the address:

```ruby
machine.guest.capability(:read_ip_address)
```

or if you want to get the interface name and pull the address manually from the guest you can use the `:network_interfaces` capability to get the list of interfaces and use the first value (which is the NAT interface)

network interfaces cap: https://github.com/hashicorp/vagrant/blob/master/plugins/guests/linux/cap/network_interfaces.rb
read ip address cap: https://github.com/hashicorp/vagrant/blob/master/plugins/guests/linux/cap/read_ip_address.rb

Cheers!

**Comment by lubosdz** [comment]
Hi Chris, 
thanx for your answer, but I am not a ruby guy, have no clue how to write proper syntax.
Is this what you mean?

```
config.hostmanager.ip_resolver = proc do |machine|
   ip = machine.guest.capability(:read_ip_address)
end
```

or

```
config.hostmanager.ip_resolver = proc do |machine|
   result = ""
   machine.communicate.execute("ifconfig {machine.guest.capability(:NetworkInterfaces[0])}") do |type, data|
      result << data if type == :stdout
   end
   (ip = /inet (\d+\.\d+\.\d+\.\d+) /.match(result)) && ip[1]
end
```
