### ISSUE TITLE
Synced Folders plugin wrongly assumes root group when using rsync on freebsd

### ISSUE THREAD

**Issue by nrocco** [hashicorp/vagrant#10443]
### Vagrant version

Vagrant:

    % vagrant -v
    Vagrant 2.2.1

Plugins;

    % vagrant plugin list
    vagrant-berkshelf (5.1.2, global)
      - Version Constraint: > 0
    vagrant-cloudstack (1.5.0, global)
      - Version Constraint: > 0
    vagrant-omnibus (1.5.0, global)
      - Version Constraint: > 0

### Host operating system

MacOS Mojave

    Darwin xxxx 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin

### Guest operating system

FreeBSD 10.3

### Vagrantfile

```ruby
Vagrant.configure(2) do |config|
  config.ssh.shell = 'sh'
  config.ssh.forward_agent = true
  config.ssh.username = "root"
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.vm.allowed_synced_folder_types = [:rsync]

  config.vm.define 'node01' do |box|
    box.vm.hostname = 'node01'

    config.vm.provider :cloudstack do |cloudstack, _|
      # Cloudstack api key and other configuration redacted
      cloudstack.display_name  = box.vm.hostname
      cloudstack.template_name = 'freebsd-10.3-20181124'
    end
  end
end
```

### Debug output

https://gist.github.com/nrocco/93f7f7943a59a244d03bcacbf83f52f0

### Expected behavior

I expect that - given the above configuration - when running

    vagrant up

Vagrant successfully finishes with an exit code of `0` and the current working directory on my workstation is rsync'ed to the guest.

### Actual behavior

When running

    vagrant up

Vagrant terminates with the following error:

     INFO interface: Machine: error-exit ["Vagrant::Errors::VagrantError", "The following SSH command responded with a non-zero exit status.\nVagrant assumes that this means the command failed!\n\nfind /vagrant '!' -type l -a '(' ! -user root -or ! -group root ')' -exec chown root:root '{}' +\n\nStdout from the command:\n\n\n\nStderr from the command:\n\nfind: -group: root: no such group\n"]

The problem seems to originate from `plugins/synced_folders/rsync/helper.rb` on line 66

    64         # Folder options
    65         opts[:owner] ||= ssh_info[:username]
    66         opts[:group] ||= ssh_info[:username]

The `helper.rb` script assumes that the name of the group is the same as the name of the user. But in FreeBSD a group with name `root` does not exist. Instead the `root` user belongs to the `wheel` group.

### Steps to reproduce

1. Take the above `Vagrantfile`
2. Use a FreeBSD based box with root user access
3. Run `vagrant up`

**Comment by nrocco** [comment]
In the spirit of `Fix It, Don’t Complain` I have made an attempt to address this issue, pull request is open here #10566

**Comment by briancain** [comment]
Closing this issue via my comment here: https://github.com/hashicorp/vagrant/pull/10566#issuecomment-452411101. Thanks again for reporting it.
