### ISSUE TITLE
Guest-specific operations were attempted on a machine that is not ready for guest communication. This should not happen and a bug should be reported.

### ISSUE THREAD

**Issue by arvingui** [hashicorp/vagrant#10452]
# Vagrant Version
vagrant version: 2.2.0

# Provider 
virtualbox version: 5.2.22

# Host
The host machine: Centos7 64bit

# Guest
Package box version: Centos6.5 64bit

# Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos65-full-desktopBox2"

  #config.ssh.username="vagrant"
  #config.ssh.password="vagrant"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

# Debug output

https://github.com/arvingui/vagrant/blob/master/vagrant%20debug

# Expected behavior

I wanted to create a box of my own with “vagrant package --base ” commands，and vagrant up no errors，and the Shared directory mounted successfully

# Actual behavior

When I vagrant up I report an error:

```
[root@localhost test4-centos65-fullBox]# vagrant halt
==> default: Attempting graceful shutdown of VM...
    default: Guest communication could not be established! This is usually because
    default: SSH is not running, the authentication information was changed,
    default: or some other networking issue. Vagrant will force halt, if
    default: capable.
==> default: Forcing shutdown of VM...
[root@localhost test4-centos65-fullBox]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...

[root@localhost test4-centos65-fullBox]# 
[root@localhost test4-centos65-fullBox]# vagrant vbguest --status
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
[root@localhost test4-centos65-fullBox]# 
```

# Steps to reproduce

1.Install a centos6.5 64bit iso image file with virtualbox
2.Find the centos6.5 installation directory in virtualbox
3.Perform the command: vagrant package --base centos65-fullbox
4.vagrant box add centos65 package.box
5.vagrant init centos65
6.vagrant up

**Comment by briancain** [comment]
@arvingui - When you bring up the guest with Vagrant, what do you see when you look at the vm inside the VirtualBox gui?

**Comment by arvingui** [comment]
Hello, thanks for your reply.When I bring up the guest with Vagrant,virtualbox boot box is fine, no errors are reported, and the virtualbox boots up and into the virtual machine successfully.And I've seen similar reports from others on github, and I've tried them all, and still haven't solved the problem

**Comment by briancain** [comment]
@arvingui when you log into the machine through the VirtualBox GUI, does it have any networking?

**Comment by briancain** [comment]
I would also look at your syslog, as according to your Vagrant log, ssh timed out while trying to negotiate its SSH protocol:

```ruby
INFO ssh: SSH not ready: #<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating>
```

**Comment by arvingui** [comment]
Hi @briancain :
Yes, the virtual machine can surf the Internet normally, DHCP or static mode is ok."vagrant ssh" command can also be used to enter the virtual machine.

Before packaging, I inserted vagrnant key into the virtual machine:
wget --no-check-certificate https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub -O .ssh/authorized_keys

The following is the result of executing the "vagrant ssh-config" command:
[root@localhost test4-centos65-fullBox]# vagrant ssh-config
Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /root/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL

**Comment by arvingui** [comment]
I just tried it once with a hashicorp/precise64 box,vagrant up it successfully.Then I switch to the installation directory of virtualbox hashicorp/precise64 /root/virtualbox VMs/ubuntu_default_1542079745897_64877/, I execute the package command: 
$ vagrant package --base ubuntu_default_1542079745897_64877
$ vagrant box add ubuntu-packageBox package.box
$ vagrant init ubuntu-packageBox
$vagrant up
Then execute the vagrant vbguest --status command, vagrant is still reported as guests-specific operations were first encountered on a machine that is not ready for Guest communication. Then I re-convert the vagrant key in the virtual machine and it is successful,So I don't know if centos is different from ubuntu in any way

**Comment by arvingui** [comment]
Hello?

**Comment by briancain** [comment]
@arvingui I asked this before, but you should check your syslog. The debug log you posted said that ssh timed out during server version negotiation. The syslog might give you more of idea as to why it failed to ssh. Thanks!

**Comment by arvingui** [comment]
@briancain You mean it's a host OS problem?Or vagrant operation problem, how should it be solved?

**Comment by arvingui** [comment]
@briancain Can you give me a detailed solution to this problem? Thank you

**Comment by briancain** [comment]
@arvingui - After re-reading your original issue description, my best guest is your Vargant box was not properly set up to be used with Vagrant (i.e. it's likely missing a `vagrant` user). Please review the guides here on how to properly make a Vagrant box https://www.vagrantup.com/docs/boxes/base.html#default-user-settings

I'll go ahead and close this. If you run into any more issues with the guide I recommend emailing the Vagrant mailing list, as they will be more helpful. Thanks!
