### ISSUE TITLE
There was an error while executing `VBoxManage`, a CLI used by Vagrant for controlling VirtualBox.

### ISSUE THREAD

**Issue by lyrapedro** [hashicorp/vagrant#10456]
### Vagrant version
Vagrant 1.8.5

### Host operating system
Windows 7 64

### Guest operating system
bento/ubuntu-16.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_version = "= 2.3.5"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"

  # Work around disconnected virtual network cable.
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get -qqy update

    # Work around https://github.com/chef/bento/issues/661
    # apt-get -qqy upgrade
    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade

    apt-get -qqy install make zip unzip postgresql

    apt-get -qqy install python3 python3-pip
    pip3 install --upgrade pip
    pip3 install flask packaging oauth2client redis passlib flask-httpauth
    pip3 install sqlalchemy flask-sqlalchemy psycopg2-binary bleach requests

    apt-get -qqy install python python-pip
    pip2 install --upgrade pip
    pip2 install flask packaging oauth2client redis passlib flask-httpauth
    pip2 install sqlalchemy flask-sqlalchemy psycopg2-binary bleach requests


    vagrantTip="[35m[1mThe shared directory is located at /vagrant\\nTo access your shared files: cd /vagrant[m"
    echo -e $vagrantTip > /etc/motd

    wget http://download.redis.io/redis-stable.tar.gz
    tar xvzf redis-stable.tar.gz
    cd redis-stable
    make
    make install

    echo "Done installing your virtual machine!"
  SHELL
end
```

### Debug output
https://gist.github.com/lyrapedro/3da8e8fd83c5e373552ec37472791d5c

### Expected behavior
Should have taken the virtual machine environment after the vagrant up

### Actual behavior
error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

### Steps to reproduce
1. vagrant up

### References
- #8501

**Comment by lyrapedro** [comment]
I have updated both to the latest versions and the error continues, I also recreated the vagrantfile

**Comment by chrisroberts** [comment]
@lyrapedro Your best bet will likely be to open the VirtualBox UI and try to start the VM from there. It will likely provide you with an error message containing more information. Another place to look is in the log file which is usually in the `~/VirtualBox VMs/VM_NAME/` directory.

**Comment by lyrapedro** [comment]
@chrisroberts 
When I try to start a VM through the VirtualBox UI, the same error is generated
 `

Código de Resultado: | E_FAIL (0x80004005)
-- | --
Componente: | MachineWrap
Interface: | IMachine {85cd948e-a71f-4289-281e-0ca7ad48cd89}

`

**Comment by lyrapedro** [comment]
[VBoxHardening.log](https://github.com/hashicorp/vagrant/files/2624881/VBoxHardening.log)

this is the generated error log

**Comment by chrisroberts** [comment]
@lyrapedro VirtualBox is having a problem verifying the required system DLLs on your machine. The first notice of this in your log file is here:

> 1c4c.1658: supR3HardenedScreenImage/NtCreateSection: cache hit (Unknown Status 22900 (0x5974)) on \Device\HarddiskVolume1\Windows\System32\kernel32.dll [lacks WinVerifyTrust]

My best guest would be that it's your anti-virus software interfering with VirtualBox. This thread on the vbox forums should provide more information on how to resolve it:

https://forums.virtualbox.org/viewtopic.php?f=6&t=86950

Cheers!
