### ISSUE TITLE
HyperV provider enhancement: add command line options

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/vagrant#10453]
During process to bring up a HyperV vm, I'm prompted for user / password.  So that I am not prompted, I would like to supply a user + password from the command line, so that I have some level of automation.  Alternatively, it would be nice to get some credentialed access w/o user/password, but in the interim, this would be nice.

### Vagrant version

```
Vagrant 2.2.0
```

### Host operating system

* Windows 10 Pro, 64-bit

### Guest operating system

* Ubuntu 16.04 Xenial

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
end
```

### Steps to reproduce
1. `vagrant up --provider=hyperv`

### Actual Results

Prompted for Credentials
```
==> default: Machine booted and ready!
==> default: Preparing SMB shared folders...
        default: You will be asked for the username and password to use for the SMB
        default: folders shortly. Please use the proper username/password of your
        default: account.
        default:
        default: Username: joaquin
        default: Password (will be hidden):
```

### Expected Results

Either to use existing credentials, supply a way have credentials without a username and password, or have a command line option to supply them at `vagrant up`

**Comment by briancain** [comment]
Hi there @darkn3rd - If you want to automate this, you can specify the SMB username and password inside your Vagrantfile:

https://www.vagrantup.com/docs/synced-folders/smb.html#options

Be advised that this is your _systems_ username and password accessing the mount, not the machine. Storing this, or having it show up in the command line could potentially leak your password. Thanks!
