### ISSUE TITLE
HyperV: Vagrant doesn't respond to CTRL-C in PowerShell?

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/vagrant#10458]
CTRL-C does not stop vagrant in PowerShell (maybe this is the expected behavior in PowerShell?).  I bring up system `vagrant up --provider=hyperv`, when prompted to choose network switch, hit CTRL-C, and later do this again, process is still running.

Workaround is to run something like this to terminate the running process.

```PowerShell
$p = Get-WmiObject Win32_Process -Filter "name = 'ruby.exe'" | `
  Where { $_.Commandline -Match "vagrant" } 
Stop-Process -Id $p.Handle
```

### Vagrant version

```
Vagrant 2.2.0
```

### Host operating system
* Windows 10 Pro, 64-bit
### Guest operating system

* Ubuntu 16.04 Xenial

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
end
```

### Expected behavior

I should be able to do vagrant up after aborting command, 

### Actual behavior

```
An action 'read_state' was attempted on the machine 'default',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.
```

### Steps to reproduce
1. `vagrant up --provider=hyperv`
1. when prompted, CTRL-C

```
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
==> default: Importing a Hyper-V instance
    default: Creating and registering the VM...
    default: Successfully imported VM
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) Default Switch
    default: 2) DockerNAT
    default:
    default: What switch would you like to use?
```

**Comment by briancain** [comment]
Hi @darkn3rd - I did not experience this behavior in powershell. I was able to ctrl-c just fine that that prompt, and run vagrant again with no issue. Do you have the full debug log for when this occurs?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
