### ISSUE TITLE
Creating a file within the shared folder sometimes results in a file that cannot be read

### ISSUE THREAD

**Issue by axsuul** [hashicorp/vagrant#1045]
**Guest OS is Ubuntu 11.04, Ubuntu 11.10, Ubuntu 12.04 (Problem occurs on all three)
Host OS is Windows 7 x64 Ultimate
VirtualBox 4.1.18 r78361**

This issue has plagued me for some time. I can't be the only one having this issue. If I create a file within the shared folder, doesn't matter if from the guest or host OS, I will sometimes get a file that cannot be accessed. 

```
ls: cannot access sign_up_controller.rb: No such file or directory
```

It only happens sometimes and I cannot reproduce it reliably. If I rename the problem file to something else on Windows, it can be read again. If I rename it back to the original filename on Windows, I get the same error.

How I get past this problem is I have to first rename the file to something else on Windows, and then from within Ubuntu rename it back to the original filename. Another way to fix this is to simply reload the vagrant box, therefore remounting the shared folder.

I'm aware this is probably a VirtualBox issue, but posting it here wondering if anyone might have insight into this.

**Comment by TomBZombie** [comment]
I'm having this exact issue on a Windows 7 host, Linux Guest. The files show:

```
ls: cannot access $file: No such file or directory
```

And the permissions are ? reloading the box fixes the problem, but it happens roughly 50% of the time when creating a new file inside the shared folder. Is there any way to fix this? The guest is using additions 5.0.4
