### ISSUE TITLE
Default FreeBSD NIC type to 82543GC

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10465]
NIC 82543GC seems to work well with FreeBSD guests, and is not as vulnerable as E1000. So rather than present a warning for bad defaults, could Vagrant simply select a more appropriate NIC for FreeBSD guests?

**Comment by chrisroberts** [comment]
Hi. No, Vagrant won't modify the NIC type (was already attempted and caused more problems). The next vbox release resolves the issue and the warning will go away after upgrading virtualbox.

Cheers!
