### ISSUE TITLE
Vagrant fails with There was an error mounting the Shared Folders file system inside the guest operating system

### ISSUE THREAD

**Issue by asoki** [hashicorp/vagrant#10464]
After I upgraded wmware fusion and vagrant, binging up a previously functioning guest fails with the errormessage
Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

My working old configuration was:
vmware fusion pro 10 with the corresponding latest vmware-plugin

Broken new configuration:
vmware fusion pro Version 11.0.2 (10952296)
Vagrant 2.2.2
vagrant-vmware-desktop (2.0.1, global)
i installed the new vmware tools on the guest: VMwareTools-10.2.0-7259539

## Vagrant version
vagrant -v
Vagrant 2.2.2

### Host operating system
macOS High Sierra 10.13.6 (17G65)

### Guest operating system
Linux foomdv3 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
Devuan-Jessie64

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.define 'foo' do |foo_config|
    foo_config.vm.box = 'foo3'
    foo_config.vm.guest = :debian
    foo_config.vm.box_url = 'an-url-to-a-private-box'
    foo_config.vm.host_name = 'foomdv3'
    foo_config.vm.network "private_network", ip: "192.168.1.1"
    foo_config.vm.synced_folder "./","/path/to/files", id:"foo-code-sync", type:"nfs", mount_options: ["actimeo=2"]
    foo_config.vm.provision "shell", path: "vagrant_config/foo_provisioner.sh"
    foo_config.vm.provider "vmware_fusion" do |v|
      v.vmx['displayname'] = 'foo-Trunk foo (Linux)'
      v.vmx["memsize"] = "2048"
      v.vmx["numvcpus"] = "2"
      v.linked_clone = false
      v.vmx["tools.upgrade.policy"] = "manual"
      v.gui = true
    end
  end
end
```

### Debug output
https://gist.github.com/asoki/09764a2c19beff44b3cb321a60535e37

### Expected behavior
should bring up the box without errors.

### Actual behavior
the synced "/path/to/file" share gets mounted and working
but vagrant fails with:
Command: ["enableSharedFolders", "/Users/foobar/develop/foo/.vagrant/machines/foo/vmware_fusion/a985431e-6d6f-44ec-b2c3-519324832c0c/Devuan-Jessie64-basebox.vmx", {:notify=>[:stdout, :stderr]}]
Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

looking into the guest settings over the vmware-gui, the checkbox enable shared folders is already on.

As workaround, is there a way to deactivate this vmrun command via the Vagrantfile?

### Steps to reproduce
upgrade vmware fusion pro to V11
upgrade vagrant
remove the old vmware-plugin
install the new vagrant-vmware-desktop
buy and install a licence
execute: vagrant up previously-working-guest

**Comment by chrisroberts** [comment]
Hi there,

Yes it can be disabled by adding this to your Vagrantfile:

```ruby
config.vm.synced_folder '.', '/vagrant', disabled: true
```

Does any relevant information end up in the vmware.log file? It will be located in the same directory as the `.vmx` file.

Thanks!

**Comment by asoki** [comment]
Hi Chris,

thanks for the workaround i will try it.

When i execute the following command:
`
/Applications/VMware\ Fusion.app/Contents/Library/vmrun enableSharedFolders /Users/foo/develop/foo/.vagrant/machines/foo/vmware_fusion/a985431e-6d6f-44ec-b2c3-519324832c0c/Devuan-Jessie64-basebox.vmx
`

I get the following lines in vmware.log
```
2018-12-05T09:52:33.779+01:00| vmx| A100: ConfigDB: Setting ide1:0.fileName = "auto detect"
2018-12-05T09:52:33.783+01:00| vmx| A100: ConfigDB: Setting ide1:0.fileName = "auto detect"
2018-12-05T09:52:33.828+01:00| vmx| I125: SOCKET 64 (204) recv detected client closed connection
2018-12-05T09:52:33.828+01:00| vmx| I125: Vix: [mainDispatch.c:2828]: VMAutomation: Connection Error (4) on connection 26.
```

**Comment by asoki** [comment]
I added 
`config.vm.synced_folder '.', '/vagrant', disabled: true`
to the Vagrantfile as suggested by @chrisroberts and now vagrant brings the machine up without errors

thank you again

**Comment by chrisroberts** [comment]
The error suggests there an issue with vmware connecting to the vmware tools on the guest. You'll have to inspect the logs on the guest to determine the problem, and might need to update the guest tools on the guest.

Cheers!
