### ISSUE TITLE
Halt leaves box in "shutoff" state rather than "poweroff"

### ISSUE THREAD

**Issue by kwill** [hashicorp/vagrant#10462]
### Vagrant version

Vagrant 2.1.5

### Host operating system

PureOS 8 (~= Debian testing)

### Guest operating system

debian/stretch64

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

end
```

### Debug output

Result of `vagrant halt 1a2b3c4d --debug`

https://gist.github.com/kwill/9c5e3a0ba92dbed524eac1f0f1189351

```
$ vagrant global-status                                                                                                                                             
id       name    provider state   directory                                       
----------------------------------------------------------------------------------
1a2b3c4d  default libvirt shutoff /home/user/Documents/vagranttest                
 
The above shows information about all known Vagrant environments...
```

### Expected behavior

Box appears with state *poweroff*

### Actual behavior

Box appears with state *shutoff*

### Steps to reproduce

1. vagrant up 1a2b3c4d
2. vagrant halt 1a2b3c4d
3. vagrant global-status

### References

- https://github.com/fffilo/gnome-vagrant-indicator/issues/8 (issue as it manifests in a GNOME-based client for controlling boxes)

### Notes

* What is the *expected* state after halting? Has this changed?

**Comment by briancain** [comment]
Hey there @kwill - the state of a guest is determined by the provider that backs it. In this case, the guest is reporting to use libvirt. That project lives [here](https://github.com/vagrant-libvirt/vagrant-libvirt). Perhaps you are used to seeing `poweroff` from the virtualbox provider. Thanks!
