### ISSUE TITLE
 version `CURL_OPENSSL_4' not found

### ISSUE THREAD

**Issue by allen-munsch** [hashicorp/vagrant#10471]
### Vagrant version
Vagrant 2.2.2

### Host operating system
Distributor ID:	Ubuntu
Description:	Pop!_OS 18.04 LTS
Release:	18.04
Codename:	bionic

```
10:31:21 jmunsch@pop-os propertymeld ±|PM-998-jm-1 ✗|→ uname -a
Linux pop-os 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Guest operating system
debian/stretch64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -y build-essential git wget
    wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.10.3.linux-amd64.tar.gz
    mkdir ~/go
    echo "export GOPATH=$HOME/go" >> .bashrc
    echo "export PATH=$PATH:/usr/local/go/bin" >> .bashrc
    source ~/.profile
    go get github.com/OpenBazaar/openbazaar-go
  SHELL
end
```
### Debug output

`vagrant up`

 

> INFO global: Vagrant version: 2.2.2
>  INFO global: Ruby version: 2.4.5
>  INFO global: RubyGems version: 2.6.14.3
>  INFO global: VAGRANT_USR_DIR="/tmp/.mount_vagranBjVrIN/usr"
>  INFO global: VAGRANT_APPIMAGE_LD_LIBRARY_PATH="/tmp/.mount_vagranBjVrIN/usr/lib/:/tmp/.mount_vagranBjVrIN/usr/lib/i386-linux-gnu/:/tmp/.mount_vagranBjVrIN/usr/lib/x86_64-linux-gnu/:/tmp/.mount_vagranBjVrIN/usr/lib32/:/tmp/.mount_vagranBjVrIN/usr/lib64/:/tmp/.mount_vagranBjVrIN/lib/:/tmp/.mount_vagranBjVrIN/lib/i386-linux-gnu/:/tmp/.mount_vagranBjVrIN/lib/x86_64-linux-gnu/:/tmp/.mount_vagranBjVrIN/lib32/:/tmp/.mount_vagranBjVrIN/lib64/::/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:"
>  INFO global: VAGRANT_PKG_CONFIG_PATH="/tmp/.mount_vagranBjVrIN/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig"
>  INFO global: VAGRANT_INSTALLER_ENV="1"
>  INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/tmp/.mount_vagranBjVrIN"
>  INFO global: VAGRANT_RUBYLIB="/tmp/.mount_vagranBjVrIN/usr/local/lib/site_ruby/2.4.0:/tmp/.mount_vagranBjVrIN/usr/local/lib/x86_64-linux-gnu/site_ruby:/tmp/.mount_vagranBjVrIN/usr/local/lib/site_ruby:/tmp/.mount_vagranBjVrIN/usr/lib/ruby/vendor_ruby/2.4.0:/tmp/.mount_vagranBjVrIN/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.4.0:/tmp/.mount_vagranBjVrIN/usr/lib/ruby/vendor_ruby:/tmp/.mount_vagranBjVrIN/usr/lib/ruby/2.4.0:/tmp/.mount_vagranBjVrIN/usr/lib/x86_64-linux-gnu/ruby/2.4.0"
>  INFO global: VAGRANT_LOG="debug"
>  INFO global: VAGRANT_BIN_DIR="/tmp/.mount_vagranBjVrIN/usr/bin"
>  INFO global: VAGRANT_APPIMAGE="1"
>  INFO global: VAGRANT_ROOT_DIR="/tmp/.mount_vagranBjVrIN"
>  WARN global: resolv replacement has not been enabled!
> DEBUG global: Loading core plugin: /tmp/.mount_vagranBjVrIN/usr/gembundle/gems/vagrant-2.2.2/plugins/commands/box/plugin.rb
>  ...a_bunch_of_plugins
>  INFO manager: Registered plugin: RSync synced folders
> DEBUG global: Loading core plugin: /tmp/.mount_vagranBjVrIN/usr/gembundle/gems/vagrant-2.2.2/plugins/synced_folders/smb/plugin.rb
>  INFO manager: Registered plugin: SMB synced folders
>  INFO vagrant: `vagrant` invoked: ["up"]
> DEBUG vagrant: Creating Vagrant environment
>  INFO environment: Environment initialized (#<Vagrant::Environment:0x0000000002224500>)
>  INFO environment:   - cwd: /home/jmunsch/PycharmProjects/propertymeld
>  INFO environment: Home path: /home/jmunsch/.vagrant.d
> DEBUG environment: Effective local data path: /home/jmunsch/PycharmProjects/propertymeld/.vagrant
>  INFO environment: Local data path: /home/jmunsch/PycharmProjects/propertymeld/.vagrant
> DEBUG environment: Creating: /home/jmunsch/PycharmProjects/propertymeld/.vagrant
> DEBUG manager: Enabling localized plugins
>  INFO manager: Plugins:
> DEBUG bundler: Current generated plugin dependency list: []
> DEBUG bundler: Generating new builtin set instance.
> DEBUG bundler: Generating new plugin set instance. Skip gems - []
> DEBUG bundler: Activating solution set: []
>  INFO manager: Loading plugins...
> DEBUG manager: Enabling globalized plugins
>  INFO manager: Plugins:
> DEBUG bundler: Current generated plugin dependency list: []
> DEBUG bundler: Generating new builtin set instance.
> DEBUG bundler: Generating new plugin set instance. Skip gems - []
> DEBUG bundler: Activating solution set: []
>  INFO manager: Loading plugins...
>  INFO loader: Set :root = ["#<Pathname:/home/jmunsch/PycharmProjects/propertymeld/Vagrantfile>"]
> DEBUG loader: Populating proc cache for #<Pathname:/home/jmunsch/PycharmProjects/propertymeld/Vagrantfile>
> DEBUG loader: Load procs for pathname: /home/jmunsch/PycharmProjects/propertymeld/Vagrantfile
>  INFO loader: Loading configuration in order: [:home, :root]
> DEBUG loader: Loading from: root (evaluating)
> DEBUG config: Trigger defined for command: destroy
> DEBUG provisioner: Provisioner defined: 
> DEBUG provisioner: Provisioner defined: 
> DEBUG loader: Configuration loaded successfully, finalizing and returning
> DEBUG push: finalizing
>  INFO environment: Running hook: environment_plugins_loaded
>  INFO runner: Preparing hooks for middleware sequence...
>  INFO runner: 1 hooks defined.
>  INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Builder:0x00000000017ff7c8>
>  INFO environment: Running hook: environment_load
>  INFO runner: Preparing hooks for middleware sequence...
>  INFO runner: 1 hooks defined.
>  INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x000000000268bc10>
> DEBUG checkpoint_client: starting plugin check
>  INFO cli: CLI: [] "up" []
> DEBUG checkpoint_client: plugin check complete
> DEBUG cli: Invoking command class: VagrantPlugins::CommandUp::Command []
> DEBUG checkpoint_client: no information received from checkpoint
> DEBUG command: 'Up' each target VM...
> DEBUG command: Getting target VMs for command. Arguments:
> DEBUG command:  -- names: ["default"]
> DEBUG command:  -- options: {:provider=>nil}
> DEBUG command: Finding machine that match name: default
>  INFO command: Active machine found with name default. Using provider: virtualbox
>  INFO environment: Getting machine: default (virtualbox)
>  INFO environment: Uncached load of machine.
>  INFO base: VBoxManage path: VBoxManage
>  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "--version"]
>  INFO subprocess: Command not in installer, restoring original environment...
>  INFO subprocess: Detected AppImage environment and request to external binary. Updating library path.
> DEBUG subprocess: Setting LD_LIBRARY_PATH to /tmp/.mount_vagranBjVrIN/usr/lib/:/tmp/.mount_vagranBjVrIN/usr/lib/i386-linux-gnu/:/tmp/.mount_vagranBjVrIN/usr/lib/x86_64-linux-gnu/:/tmp/.mount_vagranBjVrIN/usr/lib32/:/tmp/.mount_vagranBjVrIN/usr/lib64/:/tmp/.mount_vagranBjVrIN/lib/:/tmp/.mount_vagranBjVrIN/lib/i386-linux-gnu/:/tmp/.mount_vagranBjVrIN/lib/x86_64-linux-gnu/:/tmp/.mount_vagranBjVrIN/lib32/:/tmp/.mount_vagranBjVrIN/lib64/::/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:
> DEBUG subprocess: Selecting on IO
> DEBUG subprocess: stderr: /usr/lib/virtualbox/VBoxManage: /tmp/.mount_vagranBjVrIN/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/virtualbox/VBoxRT.so)
> DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
> DEBUG subprocess: Exit status: 1
>  INFO environment: Running hook: environment_unload
>  INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/jmunsch/PycharmProjects/propertymeld>]
> DEBUG host: Trying: alt
> DEBUG host: Trying: arch
> DEBUG host: Trying: darwin
> DEBUG host: Trying: freebsd
> DEBUG host: Trying: gentoo
> DEBUG host: Trying: redhat
> DEBUG host: Trying: slackware
> DEBUG host: Trying: suse
> DEBUG host: Trying: bsd
> DEBUG host: Trying: linux
>  INFO host: Detected: linux!
>  INFO runner: Preparing hooks for middleware sequence...
>  INFO runner: 1 hooks defined.
>  INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00000000025c5b28>
> ERROR vagrant: Vagrant experienced an error! Details:
> 

> The provider 'virtualbox' that was requested to back the machine
> 'default' is reporting that it isn't usable on this system. The
> reason is shown below:
> 
> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["--version"]
> 
> Stderr: /usr/lib/virtualbox/VBoxManage: /tmp/.mount_vagranbKIbag/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/virtualbox/VBoxRT.so)
> 
> 

```
ldd /usr/bin/openssl

	linux-vdso.so.1 (0x00007ffeecf19000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f0275ab5000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f027563d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f027541e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f027502d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0274e29000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0275fc0000)
```

### virtualbox version

VBoxManage --version
5.2.22r126460

### Expected behavior
vm builds

### Actual behavior
An error

### Steps to reproduce
1. install virtualbox5.2
2. install vagrant 2.2.2
3. run vagrant up

related:

- https://github.com/hashicorp/vagrant/issues/9908
- https://askubuntu.com/questions/830466/libcrypto-so-1-0-0-no-version-information-available-required-by-ssh/830532#830532
- https://github.com/openssl/openssl/issues/1631#issuecomment-250021959

I am able to boot the machine from the virtualbox GUI, as well as using `VBoxManage startvm some_id` 

vagrant is looking for `/usr/lib/virtualbox/VBoxManage`, however `which VBoxManage` is located at `/usr/bin/VBoxManage`, they are the same version.

```
09:30:53 jmunsch@pop-os → /usr/lib/virtualbox/VBoxManage --version
5.2.22r126460

09:31:26 jmunsch@pop-os → file /usr/lib/virtualbox/VBoxManage
/usr/lib/virtualbox/VBoxManage: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=8a5d363d384a54233fc5c0368a113b6c4658d089, stripped

09:31:47 jmunsch@pop-os → file /usr/bin/VBoxManage
/usr/bin/VBoxManage: symbolic link to VBox

09:31:57 jmunsch@pop-os → file /usr/bin/VBox
/usr/bin/VBox: POSIX shell script, ASCII text executable

09:32:27 jmunsch@pop-os → head -n 100 /usr/bin/VBox | grep -v '#'


PATH="/usr/bin:/bin:/usr/sbin:/sbin"

TARGET=`readlink -e -- "${0}"` || exit 1
MY_DIR="${TARGET%/[!/]*}"


if test -f /usr/lib/virtualbox/VirtualBox &&
    test -x /usr/lib/virtualbox/VirtualBox; then
    INSTALL_DIR=/usr/lib/virtualbox
elif test -f "${MY_DIR}/VirtualBox" && test -x "${MY_DIR}/VirtualBox"; then
    INSTALL_DIR="${MY_DIR}"
else
    echo "Could not find VirtualBox installation. Please reinstall."
    exit 1
fi


if [ "$1" = "shutdown" ]; then
    SHUTDOWN="true"
elif ! lsmod|grep -q vboxdrv; then
    cat << EOF
WARNING: The vboxdrv kernel module is not loaded. Either there is no module
         available for the current kernel (`uname -r`) or it failed to
         load. Please recompile the kernel module and install it by

           sudo /sbin/vboxconfig

         You will not be able to start VMs until this problem is fixed.
EOF
elif [ 
```

I have also tried `INFO global: VAGRANT_SKIP_SUBPROCESS_JAILBREAK="true"
`

```shell
10:00:32 jmunsch@pop-os propertymeld ±|PM-998-jm-1 ✗|→ file /usr/lib/virtualbox/VBoxRT.so
/usr/lib/virtualbox/VBoxRT.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=c68c07e2498f74a126f4165ef1312446bc312dd4, stripped

10:01:06 jmunsch@pop-os propertymeld ±|PM-998-jm-1 ✗|→ ldd /usr/lib/virtualbox/VBoxRT.so
	linux-vdso.so.1 (0x00007ffe1bdda000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f753ee80000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f753ec63000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f753ea44000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f753e83c000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f753e638000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f753e277000)
	libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f753dff8000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f753dd8e000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f753d916000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f753d58d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f753d375000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f753cf84000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f753f594000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f753cbcd000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f753c9a7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f753c609000)
	libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f753c3e4000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f753c1c7000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f753bfab000)
	libpsl.so.5 => /usr/lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f753bd9d000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f753bb52000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f753b900000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f753b6f2000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f7539b49000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f75397cb000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f7539466000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f7539232000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f7538ffc000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f7538d7b000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f7538aa5000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f7538873000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f753866f000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f7538464000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f7538249000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f753802e000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f7537ded000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f7537abe000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f75378ab000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f75376a7000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f753749e000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f7537211000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f7536f6f000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f7536d39000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f7536b23000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f753691b000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f75366f2000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f75364e3000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f7536299000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f7535f90000)
```

```
10:19:09 jmunsch@pop-os propertymeld ±|PM-998-jm-1 ✗|→ ldd /usr/lib/x86_64-linux-gnu/libcurl.so.4.5.0
	linux-vdso.so.1 (0x00007ffc1df28000)
	libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007fbdeed0c000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007fbdeeaef000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007fbdee8d3000)
	libpsl.so.5 => /usr/lib/x86_64-linux-gnu/libpsl.so.5 (0x00007fbdee6c5000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fbdee45b000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fbdedfe3000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007fbdedd98000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007fbdedb46000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007fbded938000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fbded71b000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbded4fc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbded10b000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007fbdecd8d000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007fbdeca28000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007fbdec7f4000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007fbdec5be000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007fbdec33d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbdec139000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007fbdebe63000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007fbdebc31000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007fbdeba2d000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007fbdeb822000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fbdeb607000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007fbdeb3ec000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007fbdeb1ab000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbdef1b0000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007fbdeae7c000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007fbdeac69000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007fbdeaa65000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007fbdea85c000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007fbdea5cf000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007fbdea32d000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007fbdea0f7000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007fbde9ee1000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fbde9cd9000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007fbde9ab0000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007fbde98a1000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007fbde9657000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fbde934e000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fbde9116000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbde8d78000)
```

I also attempted to rename the `.so` files, and got the same error:

```
sudo mv /usr/lib/x86_64-linux-gnu/libcurl.so.4.5.0 /usr/lib/x86_64-linux-gnu/hmm.libcurl.so.4.5.0
sudo mv /usr/lib/x86_64-linux-gnu/libcurl.so.4 /usr/lib/x86_64-linux-gnu/hmm.libcurl.so.4
```

**Comment by briancain** [comment]
Hi @allen-munsch - this looks to be an issue with the appimage package. You should be able to install the `.deb` package for debian systems without an issue for now. Thanks!

**Comment by allen-munsch** [comment]
@briancain thanks for the reply, just to clarify. Do you mean the .deb of appimage, vagrant, or virtualbox? The current `vagrant` deb file is kind of old: https://packages.ubuntu.com/bionic/vagrant at 2.0.2. Do you have a link to the particular deb?

**Comment by briancain** [comment]
@allen-munsch - Ah sorry, I meant the `.deb` package for Vagrant: https://www.vagrantup.com/downloads.html

**Comment by allen-munsch** [comment]
@briancain You rock! Worked like a charm. https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.deb

**Comment by stolinzeev** [comment]
I am running vagrant 2.2.3
 and have this error


There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["--version"]

Stderr: /usr/lib/virtualbox/VBoxManage: /tmp/.mount_vagran6xXMBW/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/virtualbox/VBoxRT.so)

**Comment by briancain** [comment]
Hey @stolinzeev - This looks to be a different bug with the appimage installer. I recommend opening a new issue. Thanks!

**Comment by allen-munsch** [comment]
@chrisroberts just wanted to highlight that I installed it by doing a `mv` and `chmod +x` of the precompiled binary, if you got any questions for me. just at me.

**Comment by chrisroberts** [comment]
Just for an update on this issue: After a bunch of debugging last week the root cause is the libcurl packages used to build the appimage. Installing vbox using the ubuntu repos results in a working installation. Installing vbox from oracle packages/repos results in the curl/openssl error referenced. The appimage is built from ubuntu 14.04, and while libcurl4 is available, it's a weird hybrid of libcurl3 and libcurl4 with both `.so` symlinks for 3 and 4 pointing at the same location. When something is depending on version specific defined symbols (like we see happening with vbox) it ends up getting this error. ([some related background information](https://bugs.launchpad.net/ubuntu/+source/curl/+bug/1754294))

I'm working to come up with a viable solution for the next release.

**Comment by chrisroberts** [comment]
@johnthomas22 I was referencing the default ubuntu repos which include virtualbox, just not up-to-date versions of virtualbox.
