### ISSUE TITLE
Provision triggers run only on 'vagrant provision'

### ISSUE THREAD

**Issue by cheretbe** [hashicorp/vagrant#10480]
### Vagrant version
Vagrant 2.2.2

### Host operating system
Windows 8.1 Pro x64, Ubuntu 16.04 x64

### Guest operating system
Tested on Ubuntu 16.04, but most likely does not depend on guest OS.

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", inline: "uname -a"
  
  config.trigger.before :provision do |trigger|
    trigger.info = "before provision test"
  end

  config.trigger.after :provision do |trigger|
    trigger.info = "after provision test"
  end
end
```

### Expected behavior
Both inline provision scripts and provision triggers should run during initial `vagrant up`,
`vagrant up --provision`, `vagrant reload --provision` and `vagrant provision`.

### Actual behavior
Provision triggers run only on `vagrant provision`.

**Comment by briancain** [comment]
Hello @cheretbe - Unfortunately this is not how triggers work currently with Vagrant. Currently, triggers will only run before or after certain commands, not specific machine actions/steps inside a Vagrant run. We have an issue tracking this enhancement already here https://github.com/hashicorp/vagrant/issues/9846

If your trigger is ok to run before or after those commands, you can always define your trigger to fire on multiple commands like:

```ruby
config.trigger.before :up, :reload, :provision do |trigger|
end
```

Thanks!

**Comment by NoahO** [comment]
This is really bad behaviour because it means I can’t run a step before provisioning either... if I use the before: provision it works, but doesn’t run on the initial provision, and if I try and fix that by using before [:up, :provision] then it runs before the machine exists and fails... there’s no way to run it after UP and before provision..
