### ISSUE TITLE
vagrant halt not work on Alpine Linux

### ISSUE THREAD

**Issue by ptux** [hashicorp/vagrant#10492]
### Vagrant version

Vagrant 2.2.2

### Host operating system

MacOS 

### Guest operating system

Alpine Linux

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "alpine/alpine64"
end
```

### Debug output

```
$ alpine vagrant halt
==> default: Attempting graceful shutdown of VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

shutdown -h now

Stdout from the command:



Stderr from the command:

bash: line 4: shutdown: command not found
```

### Expected behavior

Alpine Linux should be shutdown.

### Actual behavior

bash: line 4: shutdown: command not found

halt command for Alpine Linux is `poweroff`

**Comment by ptux** [comment]
any news?

**Comment by chrisroberts** [comment]
Hi there,

This can be resolved by using the vagrant-alpine plugin - https://rubygems.org/gems/vagrant-alpine

Cheers!
