### ISSUE TITLE
HyperV smb breaks if Docker for windows installed

### ISSUE THREAD

**Issue by smiteshNVIDIA** [hashicorp/vagrant#10503]
### Vagrant version
PS C:\windows\system32> vagrant -v
Vagrant 2.2.2

### Host operating system
Windows 10

### Guest operating system
centos/7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "centos/7"
    master.vm.network "private_network", bridge: "Default Switch"

    master.vm.provider "hyperv" do |hv|
      hv.vmname = "myVM"
      hv.memory = 2048
      hv.maxmemory = 4096
      hv.enable_virtualization_extensions = true
      hv.cpus = 2
      hv.linked_clone = true
    end

    master.vm.synced_folder ".", "/vagrant", type: "smb", mount_options: ['vers=3.0'], smb_username: "<myuser>", smb_password: "<mypass>"

    master.vm.hostname = "myVM"
  end
end

```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/smiteshNVIDIA/d6cbe68daf88877bca9feef9f9e757fb

### Expected behavior
Guest is able to mount smb share from host

### Actual behavior
Somehow guest is trying to mount smb share with IP under dockerNAT switch and failing

### Steps to reproduce
1. vagrant up with above file

**Comment by briancain** [comment]
Hi @smiteshNVIDIA - I don't have that issue when I install docker and use hyper-v to bring up a `centos/7` vm. Do you have the full debug output with the `--debug` flag enabled?

Also if you look at the Vagrant log, it is saying that the host is down when it was trying to mount your shared folder. Do you see the vm running after the command finishes, or is it reported as down in the hyper-v gui?

![screenshot from 2018-12-14 10-19-26](https://user-images.githubusercontent.com/810277/50020137-e60cc880-ff89-11e8-8dd6-f78e1a196739.png)

**Comment by sXe79** [comment]
I have the same issue with an Homestead box (6.4.0), or at least I think it's related. Vagrant succeed mounting smb folders only when also docker is running. No matter if I choose the default or another custom switch at "vagrant up", I guess it always connect to docker switch.
If docker is not running, smb share fails.

**Comment by chrisroberts** [comment]
My guess is that it is caused by the DockerNAT switch "taking over" the functionality of the Default Switch. I'll investigate this a bit more today to get a reproduction and try to confirm.

**Comment by smiteshNVIDIA** [comment]
@briancain Sorry for delay. I was out on vacation. 
here is the debug gist - https://gist.github.com/smiteshNVIDIA/1fc51d9b1490067cffddf1770cd309ee

Note the part where vagrant listing potential host IPs. The first IP is from DockerNAT instead of my wifi adapter IP and vagrant chooses that

IPAddress         : 10.0.75.1
InterfaceIndex    : 27
InterfaceAlias    : vEthernet (DockerNAT)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 24
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 172.27.107.161
InterfaceIndex    : 18
InterfaceAlias    : vEthernet (Default Switch)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 28
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 10.112.76.188
InterfaceIndex    : 20
InterfaceAlias    : Wi-Fi
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 21
PrefixOrigin      : Dhcp
SuffixOrigin      : Dhcp
AddressState      : Preferred
ValidLifetime     : 02:31:34
PreferredLifetime : 02:31:34
SkipAsSource      : False
PolicyStore       : ActiveStore


The problem can be worked around by specifying smb_host as 10.112.76.188 from above example but that makes me change my vagrant file every time my DHCP IP on wifi changes. It would be much cleaner if vagrant handles this automatically

**Comment by chrisroberts** [comment]
It looks like the wrong address is being selected (picking the first network, dockernat in this case, instead of the default switch).
