### ISSUE TITLE
Hyper-V does not detect Secure Boot Template for Generation 2 VMs

### ISSUE THREAD

**Issue by pizzapie** [hashicorp/vagrant#10508]
They Hyper-V Provider correctly sets EnableSecureBoot from the source Box, but does not detect/set SecureBootTemplate when calling `Hyper-V\Set-VMFirmware`

### Vagrant version
Vagrant 2.2.2

### Host operating system
Windows 10 Pro 1809 build 17763.194

### Guest operating system
Oracle Linux 7 version 7.5

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "tc_ol7/7.5"
  config.ssh.keys_only = false
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.provider "hyperv" do |hv|
    hv.enable_virtualization_extensions = true
    hv.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: true,
      shutdown: true,
      time_synchronization: true,
      vss: true
    }
  end
  
  config.vm.network "public_network", bridge: "Default Switch" 
  config.vm.provision "shell", inline: "sudo yum makecache"

end
```

### Expected behavior
`vagrant up` should start an Oracle Linux instance

### Actual behavior
VM starts and hangs at Microsoft UEFI screen, which reports the virtual HDD's boot image is not recognized/signed.

#### Work-Around
Halt the VM from Hyper-V Manager, change its Settings: Security->Template to "Microsoft UEFI Certificate Authority" and run `vagrant up` again.

### Steps to reproduce
1. Download & install an Oracle Enterprise Linux guest, enabling SecureBoot using the Microsoft UEFI Certificate Authority.
2. With Packer, create a Generation 2 Box with SecureBoot enabled using the Microsoft UEFI Certificate Authority with the following template https://gist.github.com/pizzapie/2c878e11d79d1b8b1dc05b07a09b605a
3. Register the resulting box with `vagrant box add --provider hyperv --name tc_ol7/7.5 .\packer_hyperv-vmcx_hyperv.box` 
4. Bring up virtual machine with `vagrant up` and above Vagrantfile

### References
#5210
and commit https://github.com/hashicorp/vagrant/commit/21e2f33fb0e6ed9acd23f279b2806d0d9761e609

**Comment by chrisroberts** [comment]
Fixed with #11756
