### ISSUE TITLE
Setting hostname on debian8 with systemd / without dbus #7973

### ISSUE THREAD

**Issue by abbbi** [hashicorp/vagrant#10501]
im stumbling about this with the recently released version. 
I downgraded to v2.1.5 , the version i used before to make it work again.
Seems like this issue was re-introduced.

See old issue for detailed information. My debian9/10 boxes do not include dbus and fail the same way.

_Originally posted by @abbbi in https://github.com/hashicorp/vagrant/issues/7973#issuecomment-447063454_

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!

**Comment by abbbi** [comment]
Hi have debian9/debia10 boxes which do no include dbus. I was using vagrant version

Vagrant 2.1.5

Vagrant up in one those VM's never was a problem:

```
# vagrant --version
Vagrant 2.1.5
# cd test-debian/
# vagrant up --no-provision 2>&1 > /dev/null 
# echo $?
0
```

After updating vagrant to the latest version, vagrant up fails with the same error message as shown in the gist attached to issue #7973:

```

> # vagrant --version
> Vagrant 2.2.2
> # vagrant up --no-provision
> [..]
> ==> default: Waiting for domain to get an IP address...
> ==> default: Waiting for SSH to become available...
>     default: 
>     default: Vagrant insecure key detected. Vagrant will automatically replace
>     default: this with a newly generated keypair for better security.
>     default: 
>     default: Inserting generated public key within guest...
>     default: Removing insecure key from the guest if it's present...
>     default: Key inserted! Disconnecting and reconnecting using new SSH key...
> ==> default: Setting hostname...
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> hostnamectl set-hostname 'debian10'
> 
> Stdout from the command:
> 
> 
> 
> Stderr from the command:
> 
> Failed to create bus connection: No such file or directory
> 

```

**Comment by abbbi** [comment]
@chrisroberts yes, the have been created using vmdebootstrap with default settings, so systemd is the default init system on those boxes.

```
ii  systemd                       239-13                                amd64        system and service manager
ii  systemd-sysv                  239-13                                amd64        system and service manager - SysV links
```

**Comment by abbbi** [comment]
i have added a debian9 box for you here:

 http://www.grinser.de/~abi/stretch.box

its been created with the scripts here:

git clone https://salsa.debian.org/cloud-team/vagrant-boxes

and im able to reproduce this with vagrant version 2.2.2:

> vagrant box add --name bugtest stretch.box
> [..]
> vagrant up
> ==> default: Waiting for domain to get an IP address...
> ==> default: Waiting for SSH to become available...
>     default: 
>     default: Vagrant insecure key detected. Vagrant will automatically replace
>     default: this with a newly generated keypair for better security.
>     default: 
>     default: Inserting generated public key within guest...
>     default: Removing insecure key from the guest if it's present...
>     default: Key inserted! Disconnecting and reconnecting using new SSH key...
> ==> default: Setting hostname...
> The following SSH command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> hostnamectl set-hostname 'foo'
> 
> Stdout from the command:
> 
> 
> 
> Stderr from the command:
> 
> Failed to create bus connection: No such file or directory
