### ISSUE TITLE
problem in rsync

### ISSUE THREAD

**Issue by ankitachandel** [hashicorp/vagrant#10517]
rsync: mkstemp "/home/.1.UjG2wW" failed: Permission denied (13)
rsync: mkstemp "/home/.1.txt.sWtgWW" failed: Permission denied (13)
rsync: mkstemp "/home/.10.2mGulX" failed: Permission denied (13)
rsync: mkstemp "/home/.10.txt.C5bJKX" failed: Permission denied (13)
rsync: mkstemp "/home/.2.qbZX9X" failed: Permission denied (13)
rsync: mkstemp "/home/.2.txt.Ag2czY" failed: Permission denied (13)
rsync: mkstemp "/home/.3.s6psYY" failed: Permission denied (13)
rsync: mkstemp "/home/.3.txt.Qk4HnZ" failed: Permission denied (13)
rsync: mkstemp "/home/.4.8ZYXMZ" failed: Permission denied (13)
rsync: mkstemp "/home/.4.txt.s0aec0" failed: Permission denied (13)
rsync: mkstemp "/home/.5.Q8DuB0" failed: Permission denied (13)
rsync: mkstemp "/home/.5.txt.UwnL00" failed: Permission denied (13)
rsync: mkstemp "/home/.6.SVn2p1" failed: Permission denied (13)
rsync: mkstemp "/home/.6.txt.ckFjP1" failed: Permission denied (13)
rsync: mkstemp "/home/.7.6uhBe2" failed: Permission denied (13)
rsync: mkstemp "/home/.7.txt.KZaTD2" failed: Permission denied (13)
rsync: mkstemp "/home/.8.Ialb32" failed: Permission denied (13)
rsync: mkstemp "/home/.8.txt.0tMts3" failed: Permission denied (13)
rsync: mkstemp "/home/.9.ISuMR3" failed: Permission denied (13)
rsync: mkstemp "/home/.9.txt.Mqu5g4" failed: Permission denied (13)
rsync: mkstemp "/home/.an.txt.CrKoG4" failed: Permission denied (13)

**Comment by ankitachandel** [comment]
help me

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information by opening a new ticket. Thank you! 😄
