### ISSUE TITLE
Feature request: Generate QR code for ngrok URL when using vagrant share

### ISSUE THREAD

**Issue by donkkis** [hashicorp/vagrant#10518]
Hi!

The title pretty much sums it up. In web dev context it is a pretty common use case to check the site being developed on a mobile device, which is really straightforward using the shareable public URL with vagrant share. 

It would even further speed up the workflow, however, if we could print out a scannable qr code in the meantime, as many mobile OSes now support qr scanning natively. Probably it would involve generating a popup window in the host OS.

Let me know what you guys think and i'd be happy to start working on something, if it seems like a good idea.

**Comment by Chad-Ballay** [comment]
Why not use an external tool that'll do that for you from the command line?  

https://github.com/gtanner/qrcode-terminal

**Comment by donkkis** [comment]
It's the workflow thing, really. I still want to ba able to do stuff with a
single command.

Although I guess it could be a feasible approach to write a custom wrapper
script that will execute vagrant share, parse the ngrok url from vagrant's
output and then pass it on to qrcode-terminal or something similar.

Chad Ballay <notifications@github.com> kirjoitti pe 21. jouluk. 2018 klo
5.48:

**Comment by chrisroberts** [comment]
Hi there! This is an interesting idea but not one that I see being integrated in the near term. Providing it as a plugin would definitely be ideal to keep introduced dependencies to a minimum and allow users to "opt-in" to the feature.

Cheers!
