### ISSUE TITLE
Enable shared folder issue in Centos 7 Guest on Windows Host

### ISSUE THREAD

**Issue by sharavanan2010** [hashicorp/vagrant#10520]
**Vagrant version**
VMware Workstation 15 Pro 
Vagrant 2.0.2
Plugins:
vagrant-hostmanager (1.8.9)
vagrant-omnibus (1.5.0)
vagrant-vbguest (0.16.0)
vagrant-vmware-desktop (1.0.0)
- Version Constraint: 1.0.0

**Host operating system**
Windows 10 Pro

**Guest operating system**
Centos 7

### Vagrantfile
https://gist.github.com/sharavanan2010/090e1ad80c3511cc6b076ed41314a955

### Debug output
https://gist.github.com/sharavanan2010/a8e2a66b707838d38c690fe8211d5ad0

### Expected behavior
Mount shared folder inside guest

### Actual behavior
vagrant up "enableSharedFolders error"

**Comment by chrisroberts** [comment]
Are you able to enable shared folders on the guest via the GUI interface? Does VMware log any errors within the guest after attempting to enable the shared folders?

**Comment by sharavanan2010** [comment]
Manually i could able to create shared folder via VMware workstation GUI. But when i vagrant up it is not created. But it works fine with windows guest.

**Comment by jbonhag** [comment]
Hi there,

Glad to hear that the issue was resolved by updating the VMware tools in the box. I'm going to go ahead and close this issue. If it comes up again, please open a new issue using the issue template. Thanks! 😄
