### ISSUE TITLE
Vagrant + vmware plugin: only one port forward set (windows)

### ISSUE THREAD

**Issue by 81square** [hashicorp/vagrant#10523]
I'm having problems with vagrant and port forwarding on VMware (workstation) on Windows. This might be just related to/same as the [known issues for the vmware provider](https://www.vagrantup.com/docs/vmware/known-issues.html) and other reported issues about port forwarding. If so, sorry for duplicating stuff.

### Vagrant/plugin versions
vagrant 2.2.2
vagrant-vmware-desktop 2.0.2
vagrant-vmware-utility: 1.06
VMware workstation 12.5.6 / 12.5.9

_Also tested (same behaviour):_
vagrant 2.2.2
vagrant-vmware-desktop 2.0.0
vagrant-vmware-utility: 1.04
VMware workstation 12.5.6

### Host operating system
Windows 10 pro 1809

### Guest operating system
Ubuntu 16.04, specifically bento/ubuntu-16.04

### Vagrantfile
My vagrant files come from puphpet so bit complex to show for this purpose. Only the port forwarding matters. You could reproduce the issue with a single box having multiple forwards (for example):
```ruby
config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct:true
config.vm.network :forwarded_port, guest: 443, host: 8443, auto_correct:true
config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct:true

```
Note that the first forwarded port is the 80 => 8080, not 22 => 2222.

### Debug output
Here's and example of output when settings 2 extra port forwards on top of the default one:
80 => 8080
443 => 8443
22 => 2222 (default by vagrant)

[Debug gist](https://gist.github.com/81square/09c61f2ee148265cd5b4373d732a5c3e)

### Expected behavior
All port forwards to be set, so 127.0.0.1:8080 _and_ 127.0.0.1:2222 works. Also expect these to be shown in Virtual Network Editor of VMware.

### Actual behavior
Only the first port forward is set. Because the config defines the 80 => 8080 forward first, only that one is active. The 22 => 2222 is not active, vagrant is not able to connect to 127.0.0.1:2222.

Sometimes vagrant falls back on to using the BOX_IP:22 instead and can continue, but usually it tries 127.0.0.1:2222 which fails, because that forward has not been set.

Virtual Network Editor also only shows the first port forward (80 => 8080).

Note that the vmware-utility seems to respond with 200 OK response for setting the port forwards (see debug output), but they are not actually working, nor present in Virtual Network Editor

### Steps to reproduce
1. Create vagrant box with two port forwards, first one being NOT 22 => 2222
2. Vagrant up
3. Vagrant will fail to connect to 127.0.0.1:2222 and stop with error, OR try to use <actual-ip>:22 to connect

Other way to reproduce same type of problem, with two separate vagrant boxes without any extra port forwarding:
1. Create box1, vagrant up (will use 22 => 2222 port forward, works)
2. Create box2, vagrant up (will detect collision, tries to use 22 => 10201, but fails to set that forward)

### Workaround (partly)
Setting `ssh_info_public=true` ([see here](https://www.vagrantup.com/docs/vmware/configuration.html#ssh_info_public)) will force vagrant to be using BOX_IP:22 instead of 127.0.0.1:2222 and at least solve the issue of vagrant not being able to complete the 'up'.
This will not solve the issue if you really need more than one port forward tho.

### Notes
Note that I did not use the Virtual Network Editor while using vagrant (because that may cause errors anyway).

**Comment by chrisroberts** [comment]
@81square If you upgrade VMware to the latest version of 12 (12.5.9) do you experience the same behavior?

**Comment by 81square** [comment]
@chrisroberts Upgraded tot 12.5.9 and ran some more tests. Same result (only first port forward set).

Might this be VMware workstation 12.x related?

**Comment by jbonhag** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
