### ISSUE TITLE
Vagrant Cloud: Auto-roll downstream boxes when upstream boxes update

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10547]
First, I would like to thank HashiCorp for handling the massive job of maintaining Vagrant Cloud, an amazing resource for productivity! Keep it up, yall!

I wonder if it would be feasible to provide an automatic build system, similar to Docker Hub, so that boxes can automatically re-build and re-publish themselves when the upstream boxes republish. This would help provide more security to our users, who rely on us to serve up to date, secure VM's. I think this is technically possible, and wanted to know what HashiCorp and the FOSS community think about how we could turn on this additional build strain on Vagrant Cloud.

Happy coding!

**Comment by chrisroberts** [comment]
Hi! Can you expand a bit on this as I'm not quite following:

> so that boxes can automatically re-build and re-publish themselves when the upstream boxes republish

Thanks!

**Comment by briancain** [comment]
This seems to be a duplicate of https://github.com/hashicorp/vagrant/issues/10949, so I'm going to just close this one since there is no response. Thanks.
