### ISSUE TITLE
E:\Vagrant install doesn't work?

### ISSUE THREAD

**Issue by cjeddie2003** [hashicorp/vagrant#10549]
I have installed Vagrant to E:\Vagrant

I have added a Vagrantfile into E:\VagrantFiles\Vagrantfile

When in E:\VagrantFiles running "vagrant up" results in

""""""""""""""
PS E:\VagrantFiles> vagrant up
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: E
Line number: 0
Message: private method `load' called for nil:NilClass
""""""""""""""

**Comment by briancain** [comment]
Hello there @cjeddie2003 - Do you have the full debug log when you run `vagrant up --debug`?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
