### ISSUE TITLE
Vagrant up hangs at default: WinRM transport: negotiate for Windows 10 Enterprise guest box, but VM is running

### ISSUE THREAD

**Issue by insachin** [hashicorp/vagrant#10540]
Hello Guys,
I am trying to bring up my custom windows10En box which I create using vagrant package command and provided details in vagrantFile.
But when i run vagrant up, I can see my VM is successfully running in VirtualBOX, but Vagrant up hangs at below

![image](https://user-images.githubusercontent.com/35165846/50414173-06fed480-083a-11e9-94e7-01c33ba2d3e2.png)

This seems to be one of most common issues, as i got a lot of material when i looked on web. but trying most of them didn't helped me as lot of boxes were taken from cloud and not custom box.

I also tried enabling PSRemoting and ran all set of commands  related to it etc etc but didnt help.
Since I am New to Vagrant and Virtualization, Please provide help where my set-up is wrong.
Please note the Box is custom box which i created from VirtualBOX files using Vagrant Package command.

is issue related to Vagrant file or could it be my box issue or some sort of guest machine settings/configuration ?

please help.

### Vagrant version
Vagrant 2.2.2

### Host operating system
Windows 10 Enterprise

### Guest operating system
Windows 10 Enterprise

### Vagrantfile
```# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |configWindows10En|
   configWindows10En.vm.box = "Windows10En"
  configWindows10En.vm.box_url = "file:///C:/VM_SetUP/Windows10En/Windows10En.box"
  #config.vm.hostname = "Window81Enter"
  #winClientIP = "192.168.99.103"
  #config.vm.network "private_network", ip: winClientIP
  configWindows10En.vm.network "forwarded_port", host: 1234 , guest: 3389
  #config.vm.network :forwarded_port, guest: 80, host: 8931, auto_correct: true
  configWindows10En.vm.communicator = "winrm"
  #config.ssh.username = "vagrant"
  #config.ssh.password = "vagrant"
  #config.ssh.insert_key = false
  configWindows10En.vm.synced_folder "./", "/var/www", create: true, group: "www-data", owner: "www-data"
  
  configWindows10En.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # configWindows10En.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

### Expected behavior
Vagrant up should be successful

### Actual behavior
Vagrant up hangs

### Steps to reproduce
Vagrant up

**Comment by chrisroberts** [comment]
Most likely you need to disable the firewall within the guest all allow remote connections. You can either disable the firewall completely, or only allow specific connections through. In general that is the origin of this error.

Cheers!

**Comment by crusy** [comment]
Thanks @chrisroberts, that did it.

But still: I had a running VM which needed to be reset. I fired `vagrant destroy`, followed by `vagrant up` and there comes "default: WinRM transport: negotiate". What would be the reason for the firewall to interfere the second negotiation but not the one before? I mean, the firewall is inside the VM, which only purpose is to remain unchanged
