### ISSUE TITLE
No guest IP was given to the Vagrant core NFS helper. centos/7

### ISSUE THREAD

**Issue by nhojpatrick** [hashicorp/vagrant#10559]
Upgraded to vagrant v2.2.2 and virtualbox v6.0.0. Recreated centos vm and get error message.

Have done `vagrant plugin repair` and `vagrant plugin update` and still get the issue.

### Vagrant version
```$ vagrant --version
Vagrant 2.2.2
$```

### Host operating system
`mac 10.14.2`

### Guest operating system
centos 7 `centos/7`

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
	config.vm.provider :virtualbox do |vb|
		vb.gui = false
		vb.customize ["modifyvm", :id, "--memory", "384"]
		vb.customize ["modifyvm", :id, "--audio", "none"]
	end
	config.vm.network "private_network", type: "dhcp"
	config.vm.synced_folder ".", "/vagrant", type: "nfs"
	config.vm.define "centos-7" do |inst|
		inst.vm.box = "centos/7"
	end
end
```

### Debug output
```
$ vagrant up centos-7
Bringing machine 'centos-7' up with 'virtualbox' provider...
==> centos-7: Importing base box 'centos/7'...
==> centos-7: Matching MAC address for NAT networking...
==> centos-7: Checking if box 'centos/7' is up to date...
==> centos-7: Setting the name of the VM: centos_centos-7_1546555094386_10909
==> centos-7: Fixed port collision for 22 => 2222. Now on port 2200.
==> centos-7: Clearing any previously set network interfaces...
==> centos-7: Preparing network interfaces based on configuration...
    centos-7: Adapter 1: nat
    centos-7: Adapter 2: hostonly
==> centos-7: Forwarding ports...
    centos-7: 22 (guest) => 2200 (host) (adapter 1)
==> centos-7: Running 'pre-boot' VM customizations...
==> centos-7: Booting VM...
==> centos-7: Waiting for machine to boot. This may take a few minutes...
    centos-7: SSH address: 127.0.0.1:2200
    centos-7: SSH username: vagrant
    centos-7: SSH auth method: private key
    centos-7: 
    centos-7: Vagrant insecure key detected. Vagrant will automatically replace
    centos-7: this with a newly generated keypair for better security.
    centos-7: 
    centos-7: Inserting generated public key within guest...
    centos-7: Removing insecure key from the guest if it's present...
    centos-7: Key inserted! Disconnecting and reconnecting using new SSH key...
==> centos-7: Machine booted and ready!
==> centos-7: Checking for guest additions in VM...
    centos-7: No guest additions were detected on the base box for this VM! Guest
    centos-7: additions are required for forwarded ports, shared folders, host only
    centos-7: networking, and more. If SSH fails on this machine, please install
    centos-7: the guest additions and repackage the box to continue.
    centos-7: 
    centos-7: This is not an error message; everything may continue to work properly,
    centos-7: in which case you may ignore this message.
==> centos-7: Configuring and enabling network interfaces...
No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.
```

### Expected behavior
`vagrant up` doesn't tell me to report bug.

### Actual behavior
`vagrant up` tells me to report bug.

### Steps to reproduce
1. `vagrant up`

### References
Have looked at the following bugs and all have same title, all reported as `Closed` so assume similar defect with new version.
#2737
#6523
#7070
#9118

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by nhojpatrick** [comment]
gist https://gist.github.com/nhojpatrick/778facef087019d7d2c70f15c3cb665a

**Comment by briancain** [comment]
Thanks @nhojpatrick - I believe the issue here is that the guest box `centos/7` does not have the proper guest additions installed with VirtualBox. Because of that, Vagrant can't properly read the IP address, so it can't pass along that ip to the NFS helper.

I tried a different centos box that _does_ have the virtualbox guest additions and it worked just fine. I recommend using `bento/centos-7.5` instead. Thanks!

**Comment by nhojpatrick** [comment]
1) What is the proper guest additions that should be installed?
2) Is that pre-installed in the box?
3) Can it be upgraded as part of `vagrant up`?
4) Is this an issue because I've upgraded to VirtualBox 6.0?

**Comment by briancain** [comment]
@nhojpatrick The guest additions are from VirtualBox. There's some information here on how to install it on Centos manually: https://wiki.centos.org/HowTos/Virtualization/VirtualBox/CentOSguest

In general though the box author is the one that sets them up on the Vagrant box, but it doesn't look like that's the case with the `centos/7` box. I don't think it's an issue because of VirtualBox 6 because I was able to reproduce the issue myself and I'm on 5.22.x.
