### ISSUE TITLE
vagrant up fails with private networks when setting the hostname

### ISSUE THREAD

**Issue by hieberst** [hashicorp/vagrant#10558]
I have a Linux box build with Yocto 2.1 Krogoth. It worked with Vagrant up to version 2.2.0.
Since Vagrant version 2.2.1 the initial "vagrant up" fails, because setting the hostname includes restarting all interfaces with ifupdown, but the interfaces are configured later (after setting the hostname), so not yet included in /etc/network/interfaces.

### Vagrant version
2.2.2

### Host operating system
Windows 7 64-Bit

### Guest operating system
Yocto-based qemux86 Linux with Busybox (Yocto 2.1 Krogoth)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.box = "poky"
  config.vm.guest = :debian

  config.vm.network "private_network", type: "dhcp"
  config.vm.network "private_network", type: "dhcp", adapter: 3
  config.vm.hostname = "foo"

end
```

### Debug output
https://gist.github.com/hieberst/b4a1144dada235a5ad66793a5eeb8b2d

### Expected behavior
Setting the hostname should succeed, even if the network is configured later.
The exit code of ifup should be ignored.
I.e. instead of "ifdown eth2; ifup eth2" it could be "ifdown eth2; ifup eth2; true"

### Actual behavior
Since the network is not configured yet, the network interface of the private network is still unknown (not in /etc/network/interfaces). Unfortunately, the Busybox version of ifup exits with exit code 1 in this case, which results in vagrant up to fail (the original ifupdown exits with code 0).

### Steps to reproduce
Unfortunately I am not aware of another box with sysvinit and busybox. Using my box reproducing is simply creating a new machine.
1. Create a new machine (vagrant destroy -f; vagrant up)

### References
- [GH-7155](https://github.com/hashicorp/vagrant/issues/7155)

### Possible solution
[aba2088](https://github.com/hieberst/vagrant/commit/aba20886bcd375f8305d3d06464f81f5b07863ef) Ignore exit code of ifup when setting hostname

**Comment by jbonhag** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
