### ISSUE TITLE
vagrant-reload plugin installation fails

### ISSUE THREAD

**Issue by ulfklose** [hashicorp/vagrant#10551]
### Vagrant version
2.1.5

### Host operating system
Kali Linux Rolling Release (updates from today)

### Guest operating system
N/A

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.define "ub1404" do |ub1404|
    ub1404.vm.box = "rapid7/metasploitable3-ub1404"
    ub1404.vm.hostname = "metasploitable3-ub1404"
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'

    ub1404.vm.network "private_network", ip: '172.28.128.3'

    ub1404.vm.provider "virtualbox" do |v|
      v.name = "Metasploitable3-ub1404"
      v.memory = 2048
    end
  end

  config.vm.define "win2k8" do |win2k8|
    # Base configuration for the VM and provisioner
    win2k8.vm.box = "rapid7/metasploitable3-win2k8"
    win2k8.vm.hostname = "metasploitable3-win2k8"
    win2k8.vm.communicator = "winrm"
    win2k8.winrm.retry_limit = 60
    win2k8.winrm.retry_delay = 10

    win2k8.vm.network "private_network", type: "dhcp"

    # Configure Firewall to open up vulnerable services
    case ENV['MS3_DIFFICULTY']
      when 'easy'
        win2k8.vm.provision :shell, inline: "C:\\startup\\disable_firewall.bat"
      else
        win2k8.vm.provision :shell, inline: "C:\\startup\\enable_firewall.bat"
        win2k8.vm.provision :shell, inline: "C:\\startup\\configure_firewall.bat"
    end

    # Insecure share from the Linux machine
    win2k8.vm.provision :shell, inline: "C:\\startup\\install_share_autorun.bat"
    win2k8.vm.provision :shell, inline: "C:\\startup\\setup_linux_share.bat"
    win2k8.vm.provision :shell, inline: "rm C:\\startup\\*" # Cleanup startup scripts
  end
end
```
### Debug output
https://gist.github.com/ulfklose/e65fd3b3da96580a918569fd247c56df

### Expected behavior
The plugin should have installed.

### Actual behavior
The installation fails because of a Bundler error as can be seen in the error log. I installed the json Gem in version 2.1 without problems. Installing 1.6 fails with the following error:

https://gist.github.com/ulfklose/39e8a8d8b3ed4c066c362d18dabbb940

This seems to be related to a change introduced in Ruby 2.4, json 1.6 seems to be written for Ruby 2.3 or older if I understood that correctly: https://github.com/srawlins/gmp/issues/13. So it's not really an issue with Vagrant but with the plugin itself which, for my understanding, is a part of the plugin vagrant-reload which kind of makes it a problem with Vagrant again. Please correct me if I'm wrong.

Ruby 2.5.3 is part of Kali at the moment of creating this issue.

### Steps to reproduce
1. Use the most recent version of Kali Linux and all of its updates
2. vagrant plugin install vagrant-reload

### References
- https://github.com/srawlins/gmp/issues/13

**Comment by chrisroberts** [comment]
This appears to be an issue with dm-serializer attempting to be loaded which is imposing the the `~> 1.6` constraint on the json library. That is the source of this specific error. However, it appears that you did not install Vagrant using an official package (https://www.vagrantup.com/downloads.html). Using the official package will likely resolve this issue as it does proper setup to isolate Vagrant specific gems in use.

Cheers!
