### ISSUE TITLE
json plugin install fails

### ISSUE THREAD

**Issue by TerrePorter** [hashicorp/vagrant#10556]
### Vagrant version
2.2.2

### Host operating system
windows 10

### Guest operating system
ubuntu

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.9.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON::parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if Vagrant.has_plugin?('vagrant-hostsupdater')
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    elsif Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.aliases = settings['sites'].map { |site| site['map'] }
    end
end

```
This is homestead but the error is related to vagrant plugins

### Debug output
vagrant plugin install json
Installing the 'json' plugin. This can take a few minutes...
C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/plugin/manager.rb:156:in `install_plugin': undefined method `name' for nil:NilClass (NoMethodError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/plugin/action/install_gem.rb:30:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/plugin/command/base.rb:14:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/plugin/command/install.rb:70:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/plugin/command/install.rb:69:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/plugin/command/install.rb:69:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/plugins/commands/plugin/command/root.rb:66:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/cli.rb:58:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/environment.rb:291:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/bin/vagrant:164:in `<main>'

full debug - https://gist.github.com/TerrePorter/b9b2d7f513dc4d0fe5632d6aa20485a3

### Expected behavior
Installation of json plugin

### Actual behavior
error

**Comment by chrisroberts** [comment]
Thanks for reporting this error. It is due to the gem already being installed (it is an internal dependency and thus shipped within Vagrant) and a check just needs to be added to report to the user instead of allowing this error.

**Comment by jbonhag** [comment]
Hi @TerrePorter ,

Just following up -- you can still use the `json` gem in your Vagrantfile by using `require 'json'` without needing to install any extra plugins. This gem is bundled with the Vagrant installation.

Cheers!
