### ISSUE TITLE
Vagrant execute external Script repeatedly 

### ISSUE THREAD

**Issue by xayangjing** [hashicorp/vagrant#10567]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Vagrant 2.2.2

### Host operating system
Microsoft Windows Server 2012 R2 Standard

### Guest operating system
Centos/7

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
         config.vm.box_check_update = false
         config.vm.provider "virtualbox" do |vb|
                vb.gui = false
                vb.cpus = "1"
                vb.memory = "512"
        config.vm.hostname = "runbook"
        config.vm.provision:"shell" ,path:"bootstrap.sh"
        config.vm.network "forwarded_port", guest: 80, host: 8888
        end
  end

### Debug output
D:\Vagrant_lab\runbook
λ vagrant.exe up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: runbook_default_1546778857236_70879
==> default: Vagrant has detected a configuration issue which exposes a
==> default: vulnerability with the installed version of VirtualBox. The
==> default: current guest is configured to use an E1000 NIC type for a
==> default: network adapter which is vulnerable in this version of VirtualBox.
==> default: Ensure the guest is trusted to use this configuration or update
==> default: the NIC type using one of the methods below:
==> default:
==> default:   https://www.vagrantup.com/docs/virtualbox/configuration.html#default-nic-type
==> default:   https://www.vagrantup.com/docs/virtualbox/networking.html#virtualbox-nic-type
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8888 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Setting hostname...
==> default: Rsyncing folder: /cygdrive/d/Vagrant_lab/runbook/ => /vagrant
==> default: Running provisioner: shell...
    default: Running: C:/Users/jyang3/AppData/Local/Temp/vagrant-shell20190106-4196-qz3ri5.sh
    default:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    default:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1572  100  1572    0     0   1763      0 --:--:-- --:--:-- --:--:--  1764
    default: Loaded plugins: fastestmirror
    default: Determining fastest mirrors
    default: No packages marked for update
    default: Loaded plugins: fastestmirror
    default: Examining /var/tmp/yum-root-3cd8lQ/ius-release.rpm: ius-release-1.0-15.ius.centos7.noarch
    default: Marking /var/tmp/yum-root-3cd8lQ/ius-release.rpm to be installed
    default: Resolving Dependencies
    default: --> Running transaction check
    default: ---> Package ius-release.noarch 0:1.0-15.ius.centos7 will be installed
    default: --> Processing Dependency: epel-release = 7 for package: ius-release-1.0-15.ius.centos7.noarch
    default: Loading mirror speeds from cached hostfile
    default: --> Running transaction check
    default: ---> Package epel-release.noarch 0:7-11 will be installed
    default: --> Finished Dependency Resolution
    default:
    default: Dependencies Resolved
    default:
    default: ================================================================================
    default:  Package           Arch        Version                  Repository         Size
    default: ================================================================================
    default: Installing:
    default:  ius-release       noarch      1.0-15.ius.centos7       /ius-release      8.5 k
    default: Installing for dependencies:
    default:  epel-release      noarch      7-11                     extras             15 k
    default:
    default: Transaction Summary
    default: ================================================================================
    default: Install  1 Package (+1 Dependent package)
    default:
    default: Total size: 23 k
    default: Total download size: 15 k
    default: Installed size: 33 k
    default: Downloading packages:
    default: Public key for epel-release-7-11.noarch.rpm is not installed
    default: warning: /var/cache/yum/x86_64/7/extras/packages/epel-release-7-11.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
    default: Retrieving key from http://mirrors.163.com/centos/RPM-GPG-KEY-CentOS-7
    default: Importing GPG key 0xF4A80EB5:
    default:  Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
    default:  Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
    default:  From       : http://mirrors.163.com/centos/RPM-GPG-KEY-CentOS-7
    default: Running transaction check
    default: Running transaction test
    default: Transaction test succeeded
    default: Running transaction
    default:   Installing : epel-release-7-11.noarch                                     1/2
    default:
    default:   Installing : ius-release-1.0-15.ius.centos7.noarch                        2/2
    default:
    default:   Verifying  : ius-release-1.0-15.ius.centos7.noarch                        1/2
    default:
    default:   Verifying  : epel-release-7-11.noarch                                     2/2
    default:
    default:
    default: Installed:
    default:   ius-release.noarch 0:1.0-15.ius.centos7
    default:
    default: Dependency Installed:
    default:   epel-release.noarch 0:7-11
    default:
    default: Complete!
    default: Loaded plugins: fastestmirror
    default: Loading mirror speeds from cached hostfile
    default:  * epel: ftp.cuhk.edu.hk
    default:  * ius: hkg.mirror.rackspace.com
    default: http://ftp.cuhk.edu.hk/pub/linux/fedora-epel/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml does not match metalink for epel
    default: Trying other mirror.
    default: Resolving Dependencies
    default: --> Running transaction check
    default: ---> Package python36u.x86_64 0:3.6.7-1.ius.centos7 will be installed
    default: ---> Package python36u-devel.x86_64 0:3.6.7-1.ius.centos7 will be installed
    default: ---> Package python36u-libs.x86_64 0:3.6.7-1.ius.centos7 will be installed
    default: ---> Package python36u-pip.noarch 0:9.0.1-1.ius.centos7 will be installed
    default: --> Processing Dependency: python36u-setuptools for package: python36u-pip-9.0.1-1.ius.centos7.noarch
    default: --> Running transaction check
    default: ---> Package python36u-setuptools.noarch 0:39.0.1-1.ius.centos7 will be installed
    default: --> Finished Dependency Resolution
    default:
    default: Dependencies Resolved
    default:
    default: ================================================================================
    default:  Package                   Arch        Version                   Repository
    default:                                                                            Size
    default: ================================================================================
    default: Installing:
    default:  python36u                 x86_64      3.6.7-1.ius.centos7       ius       57 k
    default:  python36u-devel           x86_64      3.6.7-1.ius.centos7       ius      839 k
    default:  python36u-libs            x86_64      3.6.7-1.ius.centos7       ius      8.9 M
    default:  python36u-pip             noarch      9.0.1-1.ius.centos7       ius      1.8 M
    default: Installing for dependencies:
    default:  python36u-setuptools      noarch      39.0.1-1.ius.centos7      ius      642 k
    default:
    default: Transaction Summary
    default: ================================================================================
    default: Install  4 Packages (+1 Dependent package)
    default:
    default: Total download size: 12 M
    default: Installed size: 55 M
    default: Downloading packages:
    default: Public key for python36u-3.6.7-1.ius.centos7.x86_64.rpm is not installed
    default: warning: /var/cache/yum/x86_64/7/ius/packages/python36u-3.6.7-1.ius.centos7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 9cd4953f: NOKEY
    default: http://archive.linux.duke.edu/ius/stable/CentOS/7/x86_64/python36u-devel-3.6.7-1.ius.centos7.x86_64.rpm: [Errno 14] curl#56 - "Recv failure: Connection reset by peer"
    default: Trying other mirror.
    default: --------------------------------------------------------------------------------
    default: Total                                              3.0 MB/s |  12 MB  00:04
    default: Retrieving key from file:///etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY
    default: Importing GPG key 0x9CD4953F:
    default:  Userid     : "IUS Community Project <coredev@iuscommunity.org>"
    default:  Fingerprint: 8b84 6e3a b3fe 6462 74e8 670f da22 1cdf 9cd4 953f
    default:  Package    : ius-release-1.0-15.ius.centos7.noarch (installed)
    default:  From       : /etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY
    default: Running transaction check
    default: Running transaction test
    default: Transaction test succeeded
    default: Running transaction
    default:   Installing : python36u-3.6.7-1.ius.centos7.x86_64                         1/5
    default:
    default:   Installing : python36u-libs-3.6.7-1.ius.centos7.x86_64                    2/5
    default:
    default:   Installing : python36u-setuptools-39.0.1-1.ius.centos7.noarch             3/5
    default:
    default:   Installing : python36u-pip-9.0.1-1.ius.centos7.noarch                     4/5
    default:
    default:   Installing : python36u-devel-3.6.7-1.ius.centos7.x86_64                   5/5
    default:
    default:   Verifying  : python36u-devel-3.6.7-1.ius.centos7.x86_64                   1/5
    default:
    default:   Verifying  : python36u-libs-3.6.7-1.ius.centos7.x86_64                    2/5
    default:
    default:   Verifying  : python36u-pip-9.0.1-1.ius.centos7.noarch                     3/5
    default:
    default:   Verifying  : python36u-3.6.7-1.ius.centos7.x86_64                         4/5
    default:
    default:   Verifying  : python36u-setuptools-39.0.1-1.ius.centos7.noarch             5/5
    default:
    default:
    default: Installed:
    default:   python36u.x86_64 0:3.6.7-1.ius.centos7
    default:   python36u-devel.x86_64 0:3.6.7-1.ius.centos7
    default:   python36u-libs.x86_64 0:3.6.7-1.ius.centos7
    default:   python36u-pip.noarch 0:9.0.1-1.ius.centos7
    default:
    default: Dependency Installed:
    default:   python36u-setuptools.noarch 0:39.0.1-1.ius.centos7
    default:
    default: Complete!
==> default: Running provisioner: shell...
    default: Running: C:/Users/jyang3/AppData/Local/Temp/vagrant-shell20190106-4196-1s4dvbq.sh
    default:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    default:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1572  100  1572    0     0   1797      0 --:--:-- --:--:-- --:--:--  1796
    default: Loaded plugins: fastestmirror
    default: Loading mirror speeds from cached hostfile
    default:  * epel: ftp.cuhk.edu.hk
    default:  * ius: archive.linux.duke.edu
    default: No packages marked for update
    default: Loaded plugins: fastestmirror
    default: Examining /var/tmp/yum-root-3cd8lQ/ius-release.rpm: ius-release-1.0-15.ius.centos7.noarch
    default: /var/tmp/yum-root-3cd8lQ/ius-release.rpm: does not update installed package.
    default: Error: Nothing to do
    default: Loaded plugins: fastestmirror
    default: Loading mirror speeds from cached hostfile
    default:  * epel: mirrors.tuna.tsinghua.edu.cn
    default:  * ius: archive.linux.duke.edu
    default: Package python36u-3.6.7-1.ius.centos7.x86_64 already installed and latest version
    default: Package python36u-libs-3.6.7-1.ius.centos7.x86_64 already installed and latest version
    default: Package python36u-devel-3.6.7-1.ius.centos7.x86_64 already installed and latest version
    default: Package python36u-pip-9.0.1-1.ius.centos7.noarch already installed and latest version
    default: Nothing to do
==> default: Running provisioner: shell...
    default: Running: C:/Users/jyang3/AppData/Local/Temp/vagrant-shell20190106-4196-1ux4eqp.sh
    default:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    default:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1572  100  1572    0     0   2567      0 --:--:-- --:--:-- --:--:--  2568
    default: /tmp/vagrant-shell: /bin/yum: /usr/bin/python22: bad interpreter: No such file or directory
    default: /tmp/vagrant-shell: /bin/yum: /usr/bin/python22: bad interpreter: No such file or directory
    default: /tmp/vagrant-shell: /bin/yum: /usr/bin/python22: bad interpreter: No such file or directory

### Expected behavior
I want to  run the external script with VM once after I run Vagrant up.

### Actual behavior
but the Vagrant programe run 2 times of the external secript when I run vagrant up

### Steps to reproduce
you will found the programe execute the external script from debug logs.
vagrant.exe up

default: Running: C:/Users/jyang3/AppData/Local/Temp/vagrant-shell20190106-4196-qz3ri5.sh
default: Running: C:/Users/jyang3/AppData/Local/Temp/vagrant-shell20190106-4196-1s4dvbq.sh
 default: Running: C:/Users/jyang3/AppData/Local/Temp/vagrant-shell20190106-4196-1ux4eqp.sh
### References
Are there any other GitHub issues (open or closed) that should be linked here?
No.

**Comment by briancain** [comment]
Hi @xayangjing - This was already fixed by #8680 and shouldn't need any documentation updated. I just tried on the latest version and the script only runs once:

```
brian@localghost:vagrant-sandbox % be vagrant up bork                                                    ±[●][master]
Bringing machine 'bork' up with 'virtualbox' provider...
==> bork: Importing base box 'bento/ubuntu-18.04'...
==> bork: Matching MAC address for NAT networking...
==> bork: Checking if box 'bento/ubuntu-18.04' is up to date...
==> bork: Setting the name of the VM: vagrant-sandbox_bork_1546882475779_12682
==> bork: Fixed port collision for 22 => 2222. Now on port 2200.
==> bork: Clearing any previously set network interfaces...
==> bork: Preparing network interfaces based on configuration...
    bork: Adapter 1: nat
==> bork: Forwarding ports...
    bork: 22 (guest) => 2200 (host) (adapter 1)
==> bork: Booting VM...
==> bork: Waiting for machine to boot. This may take a few minutes...
    bork: SSH address: 127.0.0.1:2200
    bork: SSH username: vagrant
    bork: SSH auth method: private key
    bork:
    bork: Vagrant insecure key detected. Vagrant will automatically replace
    bork: this with a newly generated keypair for better security.
    bork:
    bork: Inserting generated public key within guest...
    bork: Removing insecure key from the guest if it's present...
    bork: Key inserted! Disconnecting and reconnecting using new SSH key...
==> bork: Machine booted and ready!
==> bork: Checking for guest additions in VM...
==> bork: Mounting shared folders...
    bork: /vagrant => /home/brian/code/vagrant-sandbox
==> bork: Running provisioner: file...
==> bork: Running provisioner: shell...
    bork: Running: /tmp/vagrant-shell20190107-12864-1arnalo.sh
    bork: hello there
```

```ruby
 config.vm.define "bork" do |b|
    b.vm.box = "bento/ubuntu-18.04"
    b.vm.provision "file",
      source: "linux-sandbox/Vagrantfile",
      destination: "/home/vagrant/test/Vagrantfile"
    b.vm.provision "shell", path: "scripts/linux/hello.sh"
    b.vm.provider :virtualbox
  end
```

If you have a debug log of output showing multiple shell scripts running on the latest version, feel free to comment here with the log and I'll reopen the issue.  Thanks!
