### ISSUE TITLE
Config: apache2 on hashicorp/precise64

### ISSUE THREAD

**Issue by akokarev** [hashicorp/vagrant#10560]
### Vagrant version
2.2.2

### Host operating system
Mac OS X

### Guest operating system
hashicorp/precise64 (Ubuntu 12.04 LTS)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
	config.vm.define "web" do |web|
		#Ubuntu 12.04 LTS 64bit
		web.vm.box = "hashicorp/precise64"
		web.vm.hostname = "web-server"

		#ssh port 4022 => 22
		web.vm.network :forwarded_port, id: "ssh", guest: 22, host: 4022

		#apache2 port 4080 => 80
		web.vm.synced_folder "www", "/var/www"
		web.vm.provision "shell", inline: <<-SHELL 
			export DEBIAN_FRONTEND=noninteractive
			mkdir -p /etc/apache2/conf.d/
			echo "ServerName localhost" >> /etc/apache2/conf.d/servername.conf
			apt-get update
			apt-get install -y apache2
			SHELL
		web.vm.network :forwarded_port, guest: 80, host: 4080
	end
end
```

### Comments
This is work config file for start apache2 without errors.
Default config have some error:
> dpkg-preconfigure: unable to re-open stdin: No such file or directory

> Could not reliably determine the server’s fully qualified domain name, using 127.0.0.1 for ServerName

**Comment by briancain** [comment]
Hi there @akokarev - This just seems to be a warning with Apache, not an error or bug: https://askubuntu.com/a/256018

If you have any more questions I suggest directing them to the mailing list for Vagrant! This issue tracker is for Vagrant bugs. Thanks!

**Comment by akokarev** [comment]
Sorry, but i don't find any contacts author package "hashicorp/precise64". I think, he can do some thing to prevent this warning.

**Comment by briancain** [comment]
@akokarev - `apache2` is not software HashiCorp develops, and it isn't part of the Vagrant box you are using. The warning you are seeing is not from the Vagrant box or from Vagrant, but from `apache2`.
