### ISSUE TITLE
I moved my vm to another location and now that VM does not list of  $ vagrant global-status

### ISSUE THREAD

**Issue by ederrafo** [hashicorp/vagrant#10572]
Hello guys

 I'm organizing my projects and recently I moved the folder of a VM.
When I executed : $ vagrant global-status , I see that the VM that I moved,  it's directory did not update, and worse it disapear of listed when I executed $ vagrant reload ID

VM is running but not listed in vagrant global-status
Why? 
is strange

Thanks for help

Best regards
Eder Rafo

**Comment by ederrafo** [comment]
how can I update/refresh the file **C:\Users\Usuario\.vagrant.d\data\machine-index** here is my problem
, manually not is recommended :(

**Comment by chrisroberts** [comment]
Hi there. Moving a guest is not recommended for reasons like this. Running a `vagrant reload` on the guest will likely resolve the issue. Cheers!
