### ISSUE TITLE
Vagrant up (2.2.2) not working in WSL

### ISSUE THREAD

**Issue by ivan-radic** [hashicorp/vagrant#10576]
Hi there,

On fresh install of Windows 10, fresh install of latest Vagrant, trying to create Ubuntu 18.04 VM, I get:

```
vagrant up
/opt/vagrant/embedded/gems/2.2.2/gems/vagrant-2.2.2/lib/vagrant/util/which.rb:37: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is not supported from WSL. Host
path of the shared folder must be located on a file system with
DrvFs type. Host path: .

```
### Vagrant version
vagrant -v
Vagrant 2.2.2

### Host operating system
Windows 10 Enterprise 1709

### Guest operating system
Ubuntu 18.04
https://app.vagrantup.com/ubuntu/boxes/bionic64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  # tried below line, as suggested in another bug report, but no luck
  # vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
end
```

### Debug output
https://gist.github.com/ivan-radic/9545bf66b793dff0c6794619cc7c6cd9

### Expected behavior
I am looking for a workaround, if there is one.
Note that Vagrant for Windows in powershell console works fine, and successfully creates Ubuntu 18.04 machine.

If you need more info, just ask.

Thanks,
Ivan

**Comment by chrisroberts** [comment]
Hi there,

This is because you are attempting to use vagrant project directory located within the WSL and synced folders with paths inside the WSL are not supported. Moving the project directory to a DrvFs mounted file system will fix the issue (this is the mounted local `C:\` drive which can be found either at `/c` or `/mnt/c`). If you don't need the synced folder you can disable it by adding this to your Vagrantfile:

```ruby
config.vm.synced_folder '.', '/vagrant', disabled: true
```

Cheers!

**Comment by ivan-radic** [comment]
Hi Chris,

thanks a lot, I can confirm that both methods work.
I guess this thread can serve as documentation of sorts, but may I suggest a small improvement.

Rephrase the wording a bit:

```
vm:
* The host path of the shared folder is not supported from WSL. Host
path of the shared folder must be located on a file system with
DrvFs type. Host path: .
Either move your project to /mnt/C/ or disable folder synching by adding this line to your Vagrantfile:
config.vm.synced_folder '.', '/vagrant', disabled: true
```

... or something similar. That would be really helpful for noobs like me.

Best regards,
Ivan

**Comment by krjohnston** [comment]
I am having this same problem but my project folder is in a directory on Host D:  mounted at /d as a drvfs mount. Any help welcome. 

Vagrantfile:
`Vagrant.configure("2") do |config|`
    `config.vm.box = "ubuntu/bionic64"`
    `config.vm.provider "virtualbox" do |vb|`
    `vb.memory = "4096"`
  `end`
`end`

/etc/wsl.conf
`[automount]`
`enabled=true`
`root = /`
`options = "metadata,umask=0033"`

Host: Windows 10.0.19030 Build 19030
Guest: Ubuntu 18.04
WSL Version 2

Output from vagrant up
`kev@Kev-Asus:/d/Kev/VagrantD/w2/source$ vagrant up`
`Bringing machine 'default' up with 'virtualbox' provider...`
`There are errors in the configuration of this machine. Please fix`
`the following errors and try again:`

`vm:`
`* The host path of the shared folder is not supported from WSL. Host`
`path of the shared folder must be located on a file system with`
`DrvFs type. Host path: .`

**Comment by brendonrapp** [comment]
I am having the same issue as @krjohnston, though with a /mnt/c mountpoint.

Host: Windows 10 Pro build 19033.1  
Guest: Ubuntu 18.04

**Comment by shadowc** [comment]
Same thing happens to me on a `mnt/c` mountpoint and with vagrant 2.2.6 :(
