### ISSUE TITLE
the feature you are trying to use is on a network resource that is unavailable

### ISSUE THREAD

**Issue by motsmanish** [hashicorp/vagrant#10587]
Trying to upgrade to vagrant_2.2.3_x86_64.msi.
The error messages read, to provide 2.1.4 file path, the last setup I did was 2.1.5

![image](https://user-images.githubusercontent.com/930516/51073342-5136e100-1695-11e9-80d8-ec09b15edc5f.png)

### Vagrant version
2.1.5

### Host operating system
Windows 10

### Guest operating system
Ubuntu 16.

### Expected behavior
The upgrade should have been successful.

### Actual behavior
It shows the error (screenshot attached) for all higher version than the installed one.

### Steps to reproduce
1. Have 2.1.5 version installed
2. Upgrade any higher version than 2.1.5
3. You get to see the above attached error

**Comment by motsmanish** [comment]
![image](https://user-images.githubusercontent.com/930516/51073351-84797000-1695-11e9-9aef-8b99b70984e8.png)

**Comment by briancain** [comment]
Hey there @motsmanish - This seems to just be an issue with Windows. I found a few resources which seem to lay out how to fix this issue:

https://answers.microsoft.com/en-us/protect/forum/all/the-feature-you-are-trying-to-use-is-in-a-network/80d4be22-aab6-47f0-a7dc-8a3131fc8df0

https://www.windowscentral.com/how-fix-network-resource-unavailable-install-error-windows-10

Thanks!

**Comment by motsmanish** [comment]
Thanks, The Registry technique worked.
