### ISSUE TITLE
config vagrant gem path

### ISSUE THREAD

**Issue by chunglam1999** [hashicorp/vagrant#10583]
### Vagrant version
2.1.1

### Host operating system
centos 7

I install the vagrant-2.1.1.gem at /opt/vagrant/embedded/gems/2.1.1/cache/vagrant-2.1.1.gem instead of at /usr/lib64/ruby/gems/2.5.0/cache

When I run 'vagrant, it has error:[root@localhost util]# vagrant
Traceback (most recent call last):
2: from /usr/bin/vagrant:23:in `<main>'
1: from /usr/lib64/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib64/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem vagrant (>= 0.a) with executable vagrant (Gem::GemNotFoundException)
[root@localhost util]# 

May I ask how can I config the vagrant gem path? I would like to set it inside vagrant code instead of using the GEM_PATH.

Thanks

Chung

**Comment by chrisroberts** [comment]
Hi there,

Vagrant should be installed using the appropriate package from the downloads page here:

https://www.vagrantup.com/downloads.html

If Vagrant has been installed using any other method, it should be uninstalled using those methods. 

Cheers!

**Comment by chunglam1999** [comment]
I did the vagrant.spec by myself using it to build the vagrant rpm.
I use the vagrant-2.1.1.tar.bz2 as source.
Please let me know any additional changes required.

Thanks

Chung
