### ISSUE TITLE
Disabling all vm contact after spin-up

### ISSUE THREAD

**Issue by drozdziak1** [hashicorp/vagrant#10588]
Ditching the template cause it appears to just be a missing feature.

# What?
I'd like to be able to ask Vagrant to just move on right after hitting "power on" on a VM and tend to the next VM or exit.

# Use case
I'm trying to use Vagrant to model a small server room environment where a supervisor node serves OS images to some servers using PXE and later provisions them. 

The PXE works great, but Vagrant gets upset about not being able to contact the first client VM for provisioning. This is bad, because it just stops bringing machines up after the first one while we'd like to be able to at least ignore this. 

We explicitly don't want Vagrant to prepare anything on the client VMs because the role of provisioning is meant for the supervisor node and we'd like to keep the setup as life-like as possible.

**Comment by briancain** [comment]
Hey there @drozdziak1 - You can essentially accomplish this with the following settings inside your Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "your-box"
  config.ssh.insert_key = false
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.vm.network "private_network", ip: "192.168.33.10", auto_config: false, adapter: 1
  config.vm.shared_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox
end
```

Then when you run `vagrant up`, use the `--no-provision` flag, and then no provisioners will run at all. It won't set up shared folders, or insert the private key for ssh, or the NAT interface either. Thanks!
