### ISSUE TITLE
Vagrant encountered an error while attempting to inspect VMware for current version information

### ISSUE THREAD

**Issue by EdanBrooke** [hashicorp/vagrant#10580]
### Vagrant version
Vagrant 2.2.2, same outcome after upgrading to Vagrant 2.2.3.
Logs below from 2.2.2.

### Host operating system
Windows 7 Enterprise
Version 6.1 (Build 7601: Service Pack 1)

### Guest operating system
hashicorp/precise64 but also applies to any other box.

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
  end
end
```
### Debug output
https://gist.github.com/EdanBrooke/ec0c57b11ad11d5879159c27a9bb80b9

### Expected behavior
The box should be downloaded from Vagrant and provisioned within VMWare Workstation.

### Actual behavior
```
The system cannot find the file specified.
Vagrant encountered an error while attempting to inspect VMware
for current version information:

The system cannot find the file specified.
```

### Steps to reproduce
1. Install VMWare Workstation
2. Install Vagrant and VMWare plugin for Vagrant
3. Create C:\DEV\TEST
4. `vagrant init` within TEST.
5. Configure Vagrantfile
6. `vagrant up`

**Comment by EdanBrooke** [comment]
Apologies, this is just me being stupid.
You need to use VMWare Workstation Pro and not VMWare Workstation Player.

**Comment by njtman** [comment]
I run into this issue all the time and I am running VMware Fusion 11 Pro.
Host macOS 10.14.3, guest macOS 10.14.4.
