### ISSUE TITLE
vagrant-vmware-utility: OS X firewall 'allow' or 'deny' dialogue appears after every restart

### ISSUE THREAD

**Issue by DanHam** [hashicorp/vagrant#10596]
### Info

```
$ vagrant -v
Vagrant 2.2.3

$ vagrant plugin list
vagrant-aws (0.7.2, global)
vagrant-google (2.2.1, global)
vagrant-reload (0.0.1, global)
vagrant-share (1.1.9, global)
vagrant-vmware-desktop (2.0.2, global)

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.2
BuildVersion:   18C54
```

I have the following settings configured for my firewall:

![image](https://user-images.githubusercontent.com/4364798/51326931-1b647480-1a68-11e9-881e-c0bd5a71ef94.png)

### Actual behaviour

As can be seen in the screenshot above, incoming connections for the vagrant-vmware-utility are allowed.

However, *everytime* I restart my machine, when I first log in I am greeted with the following dialogue box:

![image](https://user-images.githubusercontent.com/4364798/51327131-8ada6400-1a68-11e9-951e-3c20b4eef370.png)

This happens despite the fact the settings for the application are *already* set to 'Allow incoming connections'.

### Expected behaviour

Once incoming connections have been allowed I should not continually see the 'Allow/Deny' incoming network connections dialogue box every time the program is started. This is the behaviour for all other applications that I've configured this way. 

### Further Info

The Apple firewall help doc [HERE](https://support.apple.com/en-us/HT201642) suggests that the issue would not occur if the application was signed. From the 'Automatically allow signed software to receive incoming connections' section of the doc:

> Some apps check their own integrity when they are opened without using code signing. If the firewall recognizes such an app it doesn't sign it. Instead, it the "Allow or Deny" dialog appears every time the app is opened. This can be avoided by upgrading to a version of the app that is signed by its developer.

Any help with this would be much appreciated.

**Comment by jbonhag** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. We have started signing all recent releases of the Vagrant VMware Utility. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
