### ISSUE TITLE
NFS BSD automatic /etc/exports file incorrect

### ISSUE THREAD

**Issue by jcrben** [hashicorp/vagrant#10609]
I've been having trouble with NFS permissions errors so I tested NFS exports with a Linux laptop that I've got and noticed that the Vagrant entry wasn't properly evaluating `maproot` there either. 

Careful reading of the manpage https://www.freebsd.org/cgi/man.cgi?query=exports revealed that the options need to be before the host.

Note that there's another bug - the options are not completely overriden: the docs https://www.vagrantup.com/docs/synced-folders/nfs.html say:
> tweak the arguments specified in the /etc/exports ... bsd__nfs_options keys. Note that these options completely override the default arguments that are added by Vagrant automatically...

The automatic one below doesn't do that - also, I realize that my leading dashes are my user error.

It's important that these options be entirely replaced because `maproot` and `mapall` are mutually exclusive.

### Vagrant version
`Vagrant 2.2.3`

### Host operating system
macOS High Sierra 10.13.6

### Guest operating system
`config.vm.box = "hashicorp/precise32"` - i.e., Ubuntu 14.04

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise32"
  config.vm.define "some-name"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  for i in 8000..8009
    config.vm.network "forwarded_port", guest: i, host: i
  end

  config.vm.network "private_network", ip: "192.168.57.10"

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.synced_folder "./", "/var/www/twweb", type: "nfs", bsd__nfs_options: ["-maproot=0:0"]
    # nfs_export: false
    # mount_options: ['rw', 'vers=3', 'tcp', 'fsc', 'actimeo=2'],

  config.vm.provider "virtualbox" do |vb|
    vb.customize [
      "modifyvm", :id,
      "--memory", "1024",
      "--cpus", "1"
    ]
  end

config.vm.provision "shell", path: "scripts/vagrant/init_environment_minimal.sh"
```

Full version is probably at https://github.com/jcrben/inthe.am/tree/nfs-experimentation

### Debug output
N/A

### Expected behavior
The `/etc/exports` should abide by the rules for the file on BSD https://www.freebsd.org/cgi/man.cgi?query=exports&sektion=5&manpath=freebsd-release-ports:
`The secondcomponent of a line specifies how the file system is to be exported to the host set. The option flags ... third component of a line specifies the host set to which the line  applies.` Proper entry would look something like this:
`"/Users/bencreasy/code/open-source/taskwarrior-group/inthe.am" -maproot=root 192.168.57.10`

### Actual behavior
Meanwhile, the automatically added `/etc/exports` looks like this:

```
# VAGRANT-BEGIN: 503 7db477f2-fac6-45b7-b605-c178588f9db7
"/Users/bencreasy/code/open-source/taskwarrior-group/inthe.am" 192.168.57.10 --maproot=0:0 --mapall=1000:1000 -mapall=503:20
# VAGRANT-END: 503 7db477f2-fac6-45b7-b605-c178588f9db7
```

### Steps to reproduce
1. `vagrant up` with above Vagrantfile
2. `mount`, notice the nfs share - I don't think it is supposed to show options like maproot, however
3. `sudo -i` to become root, `chown root:root` and see `Permission denied` errors.
4. Bring it up again with the proper configuration, and try again. No errors.

### Manual setup tips
Tutorials which helped in testing via manual setup include https://www.ev3dev.org/docs/tutorials/setting-up-an-nfs-file-share/ and https://www.tecmint.com/how-to-setup-nfs-server-in-linux/ for mounting the share on my linux box - also used `nfs-ls -D nfs://<ip>`, `sudo nfsd restart` on mac, etc).

**Comment by briancain** [comment]
Hey there @jcrben - Sorry it took me so long to take a look at this issue. It looks like this has been broken for quite some time...but was fixed for freeBSD at least. The fix should be pretty straight forward though :+1: thanks for the report.
