### ISSUE TITLE
How to build the vagrant binary at /opt/vagrant/bin

### ISSUE THREAD

**Issue by chunglam1999** [hashicorp/vagrant#10600]
### Vagrant version
2.1.1
### Host operating system
Centos  7

Please let me know to to build the Vagrant executable located at /opt/vagrant/bin since  I need to make some changes to the code for debugging.

Thanks

**Comment by chrisroberts** [comment]
Launcher can be found here:

https://github.com/hashicorp/vagrant-installers/blob/master/substrate/launcher/main.go

Cheers!
