### ISSUE TITLE
Support for VMware Workstation 15.x

### ISSUE THREAD

**Issue by chris1984** [hashicorp/vagrant#10613]
### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

`Vagrant 2.2.3`

### Host operating system
This is the operating system that you run locally.

`Ubuntu 18.04 LTS`

### Guest operating system
This is the operating system you run in the virtual machine.

`CentOS 7.6 box v1812.01`

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)

$ cat Vagrantfile
# rubocop:disable Naming/FileName
# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['LANG'] = 'en_US.UTF-8'
VAGRANTFILE_DIR = File.dirname(__FILE__)

require "#{VAGRANTFILE_DIR}/vagrant/lib/forklift"

def migrate_boxes!
  old = "#{VAGRANTFILE_DIR}/boxes.d/99-local.yaml"
  new = "#{VAGRANTFILE_DIR}/vagrant/boxes.d/99-local.yaml"

  return if File.symlink?(old) || !File.exist?(old)

  if File.exist?(new)
    raise "File #{new} already exists, refusing to overwrite. Remove boxes.d/99-local.yaml in favor of vagrant/boxes.d/99-local.yaml"
  end

  File.rename(old, new)
end

def migrate_settings!
  old = "#{VAGRANTFILE_DIR}/settings.yaml"
  new = "#{VAGRANTFILE_DIR}/vagrant/settings.yaml"

  return if !File.exist?(old)

  if File.exist?(new)
    raise "File #{new} already exists, refusing to overwrite. Remove settings.yaml in favor of vagrant/settings.yaml"
  end

  File.rename(old, new)
end

migrate_boxes!
migrate_settings!
loader = Forklift::BoxLoader.new("#{VAGRANTFILE_DIR}/vagrant")
loader.load!
distributor = Forklift::BoxDistributor.new(loader.boxes)
distributor.distribute!

# rubocop:enable Naming/FileName
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

https://gist.github.com/chris1984/2c5e19d35928deb91f88575ea818bc8d

### Expected behavior
VM should spin up with VMware Workstation provider.

### Actual behavior
Get the following error:
```bash
This provider only works with VMware Workstation 9.x, 10.x, 11.x, 12.x,
and 14.x. You have Workstation '15.0.2'. Please install the proper
version of VMware Workstation and try again.
```
### Steps to reproduce
1. Install VMware Workstation 15
2. Install the latest Vagrant
3. Try to `vagrant` up a box

**Comment by chrisroberts** [comment]
Hi there!

VMware Workstation 15 is supported with the `vagrant-vmware-desktop` plugin and an up-to-date license. The `vagrant-vmware-desktop` plugin has replaced the `vagrant-vmware-workstation` and `vagrant-vmware-fusion` plugins. More information about the plugin and installation directions can be found here: https://www.vagrantup.com/docs/vmware/installation.html

Cheers!
