### ISSUE TITLE
Infinite "Warning: Authentication failure. Retrying..." with WinRM communicator

### ISSUE THREAD

**Issue by sjroman** [hashicorp/vagrant#10610]
Hi,

I was originally running Vagrant 2.2.2 when this issue arose. I upgraded VBox from 5.2 to 6.0 which had no affect. Then I upgraded Vagrant to 2.2.3. After restarting my host machine `vagrant up` produced the desired results. About 5 minutes later I was forced to restart my host machine again. I `vagrant suspend`ed the machine and rebooted my host. I am now getting the same error as before upgrading Vagrant. 

### Vagrant version
`2.2.3`

### Host operating system
`Microsoft Windows 10 Pro Version 10.0.17134 Build 17134`

### Guest operating system
`Microsoft Server 2008 R2 Standard Version	6.1.7600 Build 7600`

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 600 
  config.vm.graceful_halt_timeout = 120
  config.vm.box = "opentable/win-2008r2-standard-amd64-nocm"
  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
  config.vm.network :forwarded_port, guest: 1521, host: 1555

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
end
```

### Debug output
https://gist.github.com/sjroman/724e6d962741a4367c273abb7adf28b4

### Expected behavior
Vagrant successfully communicates with the box through WinRM and mounts shared drives

### Actual behavior
WinRM communication fails and shared drives are never mounted. WinRM communication attempts time out.

### Steps to reproduce
1. Install Vagrant 2.2.3
2. `vagrant up` with the above Vagrantfile

May be related
### References
- GH-4839

**Comment by sjroman** [comment]
To add, I'm getting the same error using this box as well
`senglin/win-10-enterprise-vs2015community`

**Comment by xplicit** [comment]
This command helped for me to resolve the issue:

Login into guest machine and run (as administrator)

    winrm quickconfig

After doing this vagrant can authenticate now.

**Comment by sjroman** [comment]
@xplicit Looks like that works for me as well. I had already run various WinRM setup commands but it appears I must run `winrm quickconfig` upon each new startup of the Windows guest. `vagrant suspend` , `vagrant up` doesn't break it so this is a guest configuration error.

Thanks!
