### ISSUE TITLE
Vagrant box completely crash after NO SPACE LEFT ON DEVICE

### ISSUE THREAD

**Issue by ophyr** [hashicorp/vagrant#10612]
Hi everyone, I just wanted to try a framework and the easy solution was using vagrant to simplify the task. But it brings only problems on top of others... I'm a newbie at this, never used it so maybe I am doing something wrong.
So I was supposed to pull vagrant and a pre-maid environnment read-to-use on vagrant, launch it and the end. BUT, when I finally was able to start the vagrant box, command 'python run.py' fails, whereas virtualenv supposed to work, so I installed pip and run pip install -r requirements.txt and then ultimate crash because of space on device. But i can't figured out which space where. help please.

### Vagrant version
Vagrant 2.2.3

### Host operating system
(It's a VM cause I don't have administrator rights on my Windows 7)
Linux ipf7028 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Guest operating system
Ubuntu

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# PyBossa Vagrantfile

VAGRANTFILE_API_VERSION = "2"

# Ansible install script for Ubuntu
$ansible_install_script = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive
echo Check if Ansible existing...
if ! which ansible >/dev/null; then
  echo update package index files...
  apt-get update -qq
  echo install Ansible...
  apt-get install -qq ansible
fi
SCRIPT

$ansible_local_provisioning_script = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive
export PYTHONUNBUFFERED=1
echo PyBossa provisioning with Ansible...
ansible-playbook -u vagrant /vagrant/provisioning/playbook.yml -i /vagrant/provisioning/ansible_hosts -c local
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.network :forwarded_port, host: 5000, guest: 5000
  config.vm.network :forwarded_port, host: 5001, guest: 5001
  # turn off warning message `stdin: is not a tty error`
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  # be sure that there  is Ansible for local provisioning
  config.vm.provision "shell", inline: $ansible_install_script
  # do the final Ansible local provisioning
  config.vm.provision "shell", inline: $ansible_local_provisioning_script
end
```

I got the vagrantfile directly from tutorial at : https://docs.pybossa.com/installation/vagrant/

### Debug output
/opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:836:in `initialize': No space left on device @ rb_sysopen - /root/.vagrant.d/perm_test_MEPOSYZGZHAZREOKLLTYNTYKUGRCXSIK (Errno::ENOSPC)
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:836:in `open'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:836:in `open'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:836:in `setup_home_path'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:135:in `initialize'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/bin/vagrant:145:in `new'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/bin/vagrant:145:in `<main>'

### Expected behavior
Nothing, everything should be running fine as expected in the tutorial.

### Actual behavior
I can't do anything... Command lines not responding anymore... Tried halt -f, status, destroy, ssh... nothing working.

**Comment by briancain** [comment]
Hey there @ophyr - This is to be expected if your host machine has no space left, and there's not much we can do about it. I recommend adding more space to your host vm.

Also, unless you are using VMWare, you won't be able to bring up another virtual machine inside your VM. VirtualBox doesn't allow for nested virtualization. Just something to be aware of in case you are using VirtualBox for your host vm...

**Comment by ophyr** [comment]
@briancain So the problem comes from the host machine ? But where goes the files generated from inside the vagrant box ?
Vagrant deploy with VirtualBox on my case.

**Comment by briancain** [comment]
@ophyr - Your VM you are using you run Vagrant needs to have more disk space. But if that VM is running in VirtualBox, you won't be able to bring up another virtual machine anyway (see my comment above).

**Comment by briancain** [comment]
@ophyr yes, it sounds like your vm doesn't have enough space for Vagrant to save files on it.
