### ISSUE TITLE
vagrant-box-list command output to include location of Vagrantfile

### ISSUE THREAD

**Issue by am11** [hashicorp/vagrant#10618]
### Vagrant version
```cmd
C:\>vagrant -v
Vagrant 2.2.2
```

### Host operating system

```cmd
C:\>ver

Microsoft Windows [Version 10.0.18317.1000]
:: latest insider build
```

### Description

With `vagrant box list` command, I get the following output:

```cmd
C:\>vagrant box list
generic/freebsd11  (hyperv, 1.8.54)
generic/ubuntu1804 (hyperv, 1.8.54)
```

I switched to this machine after some days, and forgot where did I placed the Vagrantfile, so I was hoping to find it using some built-in vagrant command. Eventually, I had to resort to full file system scan.

It would be great if vagrant box list also list the path where user initialized the box, e.g.:

```cmd
generic/freebsd11  (hyperv, 1.8.54, E:\work\boxes\fbsd11)
generic/ubuntu1804 (hyperv, 1.8.54, E:\work\boxes\ubuntu-bionic-beaver)
```

**Comment by chrisroberts** [comment]
Hi there. The `vagrant box list` command generates a list of currently installed base boxes which vagrant will create guests from (either by doing a full copy, linking, etc). If you have guests that are currently active, you can use the `vagrant global-status` command which will include the path to the project directory.

Cheers!
