### ISSUE TITLE
Exit status always 0 from "vagrant resume"

### ISSUE THREAD

**Issue by carlhoerberg** [hashicorp/vagrant#10616]
The exit code from `vagrant resume` always seem to be 0:
```
$ vagrant resume alpine
==> alpine: VM not created. Moving on...
$ echo $?
0
```
That makes it hard to automate vagrant in scripting. 

Version: Vagrant 2.2.3

**Comment by chrisroberts** [comment]
Hi there. This is the expected behavior of the command (and this behavior can be seen in other commands as well). In a scripting environment it may be better to simply use `vagrant up` which will resume a suspended guest, or create the guest if it does not exist.

Cheers!
