### ISSUE TITLE
vmdk file is created in a seperate folder from the VM folder with VirtualBox 6.0.2 and 6.0.4

### ISSUE THREAD

**Issue by sakisdog** [hashicorp/vagrant#10623]
After updating to VirtualBox 6.0.x i noticed that when running `vagrant up` a different folder is created in 
 C:\Users\username\VirtualBox VMs with the name of the box that contains only the vmdk file of the VM.
When i downgrade to VirtualBox 5.2.xx  `vagrant up` creates the vmdk in the virtual machine's folderas it is expected.

### Vagrant version
2.2.3

### Host operating system
Windows 10 Pro x64 + VirtualBox 6.0.x

### Guest operating system
ubuntu/trusty64

### Vagrantfile
```ruby
agrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 4
  end
  config.vm.provision "shell", inline: "apt-get update"
end
```

### Expected behavior
vmdk file (box-disk1.vmdk) should be created inside of C:\Users\username\VirtualBox VMs\vagrant_machine_name

### Actual behavior
vmdk is created in C:\Users\username\VirtualBox VMs\ubuntu-cloudimg-trusty-vagrant-amd64\box-disk1.vmdk and the other 

### References
Are there any other GitHub issues (open or closed) that should be linked here?
https://github.com/hashicorp/vagrant/issues/3584#issue-32538948

**Comment by chrisroberts** [comment]
Would you please provide a gist of the debug output from running `vagrant up --debug`.

Thanks!
