### ISSUE TITLE
Docker provisioning args expose ports

### ISSUE THREAD

**Issue by Perseus101** [hashicorp/vagrant#10626]
### Vagrant version
Vagrant 2.2.3

### Host operating system
Ubuntu 16.04

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network :private_network, ip: "10.10.10.30"
  config.vm.provider :virtualbox do |vb|
    vb.name = "interop"
  end
  config.vm.provision "docker" do |d|
    d.run "auvsisuas/interop-server", args: "-p '8000:80'"
  end
end
```

### Debug output
https://gist.github.com/Perseus101/84f0c673e3c1da4fa2d4884691c66aed

### Expected behavior
After running vagrant provision, this vagrant file should create a docker container with port 80 exposed on port 8000.

### Actual behavior
The docker image is created correctly, but the port is not exposed.

### Steps to reproduce
1. vagrant provision
2. vagrant ssh
3. docker ps

**Comment by briancain** [comment]
Hey there @Perseus101 - It looks like there might be an issue with your container. It might be exiting right away, which is why you wouldn't see the ports listed.

For example, here is a basic container that runs forever and uses the same `args` that you used:

```ruby
config.vm.define "dockervm" do |d|
    d.vm.box = "bento/ubuntu-18.04"
    d.vm.provider :virtualbox

    d.vm.provision "Install", type: "shell", path: "scripts/linux/install-docker.sh"

    d.vm.provision "docker" do |d|
        d.run "ubuntu",
            cmd: "tail -f /dev/null",
            args: "-p '8080:80'"
    end
end
```

```
brian@localghost:vagrant-sandbox % be vagrant ssh dockervm -c "docker ps -a"                               ±[●][master]
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS                  NAMES
4d67c5bbb265        ubuntu              "tail -f /dev/null"   7 seconds ago       Up 5 seconds        0.0.0.0:8080->80/tcp   ubuntu
Connection to 127.0.0.1 closed.
brian@localghost:vagrant-sandbox %      
```

For reference, this is the command Vagrant ran with my provisioner:

> INFO ssh: Execute: docker run --cidfile=/var/lib/vagrant/cids/24bf68e341ce0fbd9259a5d51feed79682ea4eba -d --name ubuntu --restart=always -p '8080:80' ubuntu tail -f /dev/null (sudo=true)

An example of what might be happening with your container...if I change it to a command that exits right away, `docker ps` doesn't show any ports exposed:

```ruby
config.vm.define "dockervm" do |d|
    d.vm.box = "bento/ubuntu-18.04"
    d.vm.provider :virtualbox

    d.vm.provision "Install", type: "shell", path: "scripts/linux/install-docker.sh"

    d.vm.provision "docker" do |d|
        d.run "ubuntu",
            cmd: "bash -l",
            args: "-p '8080:80'"
    end
end
```

>  INFO ssh: Execute: docker run --cidfile=/var/lib/vagrant/cids/24bf68e341ce0fbd9259a5d51feed79682ea4eba -d --name ubuntu --restart=always -p '8080:80' ubuntu bash -l

```
brian@localghost:vagrant-sandbox % be vagrant ssh dockervm -c "docker ps -a"                               ±[●][master]
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                         PORTS               NAMES
16a322e26f03        ubuntu              "bash -l"           15 seconds ago      Restarting (0) 5 seconds ago                       ubuntu
Connection to 127.0.0.1 closed.
```

Now, compare that to the command Vagrant ran for your container:

> docker run --cidfile=/var/lib/vagrant/cids/e15b0a548e1ddd450f19d515a6b07913d1db2aba -d --name auvsisuas-interop-server --restart=always -p '8000:80' auvsisuas/interop-server

It looks the same to me besides the container used. Hope that helps you figure it out....thanks!
