### ISSUE TITLE
mixin_synced_folders.rb:137:in `block in synced_folders': Internal error. Report this as a bug. Invalid: vboxsf (RuntimeError)

### ISSUE THREAD

**Issue by thorntos** [hashicorp/vagrant#10624]
### Vagrant version
Vagrant 2.2.3

### Host operating system
Linux 3.10.0-957.1.3.el7.x86_64
CentOS Linux release 7.6.1810 (Core)

### Guest operating system
VirtualBox 5.2.26 r128414 (Qt5.6.1)
CentOS-7-x86_64-Vagrant-1812_01.VirtualBox.box

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
   config.vm.define "Testbed_VM" do |testbed|
      testbed.vm.provider "virtualbox" do |vb|
         vb.memory = 2048
         vb.cpus = 1
         vb.name = "Testbed_VM"
      end
      testbed.vm.box = "Testbed_CentOS_7x64"
      testbed.vm.synced_folder ".", "/vagrant", type: "vboxsf"
      # above line does not fail if type: "rsync"
   end
end
```

### Debug output
https://gist.github.com/thorntos/1dc6f8c2f9fffd0c402a78299894a5e3

### Expected behavior
VM should have been created and brought up

### Actual behavior
VM creation crashed during synced folder creation

### Steps to reproduce
1. vagrant plugin install vagrant-vbguest
2. vagrant box add --name Testbed_CentOS_7x64 CentOS-7-x86_64-Vagrant-1812_01.VirtualBox.box
3. vagrant up

**Comment by chrisroberts** [comment]
Hi there. The type you are defining for the synced folder is not a valid type. When using native virtualbox file sharing for synced folders, the type is `virtualbox`. This will also require the guest additions being installed on the guest. 

Cheers!

**Comment by thorntos** [comment]
Thank you, that works!  Not sure why I thought it was vboxsf...
