### ISSUE TITLE
vagrant destroy don't work

### ISSUE THREAD

**Issue by tmoreno** [hashicorp/vagrant#10620]
### Vagrant version
2.1.0

### Host operating system
Windows Server 2016

### Guest operating system
Windows Server 2016
Windows 10

### Expected behavior
Destroy a running vagrant box

### Actual behavior
When my CI launch destroy command, I have this error:

```
26-ene-2019 03:47:09	C:\path-to-my-project>vagrant destroy -f 
26-ene-2019 03:48:47	The version of powershell currently installed on this host is less than
26-ene-2019 03:48:47	the required minimum version. Please upgrade the installed version of
26-ene-2019 03:48:47	powershell to the minimum required version and run the command again.
26-ene-2019 03:48:47	
26-ene-2019 03:48:47	  Installed version: N/A
26-ene-2019 03:48:47	  Minimum required version: 3
```

If you look, the command has been launch at 3:47:09 and the error is throwed at 3:48:47, almost 2 minutes!!!

This error happen sometimes.

Due to this error my host machine has a lot virtual machines that are running and cosuming a lot of memory :(

**Comment by chrisroberts** [comment]
Hi there. This can occur when vagrant times out waiting for powershell to be invoked and return a value, which is defaulted to 30 seconds. You can modify this timeout by setting the `VAGRANT_POWERSHELL_VERSION_DETECTION_TIMEOUT` environment variable to a larger number. You can find more information about this environment variable in the docs here:

https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_powershell_version_detection_timeout

Cheers!
