### ISSUE TITLE
Reduce noise about guest additions

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10634]
When I `vagrant up`, Vagrant often clutters the console with messages about guest additions, and even claims that these are important for getting shared folders, networking, and SSH connectivity to work (they are not). In fact, I have installed more than a dozen guest types in Vagrant without using guest additions without issue. Could we drop this output, so that it is easier to find more important text while debugging?

```console
$ vagrant up
...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
...
```

**Comment by chrisroberts** [comment]
I don't think that the warning should be removed but I am :+1: on adding an env var that can be set to suppress the warning.

**Comment by jbonhag** [comment]
Hi there,

You can suppress the guest additions check by setting the following option in your Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  ...
  config.vm.provider :virtualbox do |v|
    v.check_guest_additions = false
  end
end
```

If you add this provider configuration to a Vagrantfile located under `$VAGRANT_HOME` (typically ~/.vagrant.d/Vagrantfile), then it will be applied to all Vagrant guests.

Cheers! 😄
