### ISSUE TITLE
[Docs] Ansible Auto-Generated Inventory

### ISSUE THREAD

**Issue by swpease** [hashicorp/vagrant#10640]
**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
2.2.3

### Host operating system
macOS Mojave 10.14.2

### Guest operating system
ubuntu/xenial64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8088

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "testplaybook.yml"
    ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
  end
end
```

### Expected behavior
A note in the docs to the effect of "If Ansible cannot find Python on your VM, you can specify a path using `ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }`". Or if there is an easier / better / alt way to specify, say to do that.

### Actual behavior
Ansible by default (currently) assumes to find Python 2 at `/usr/bin/python`. Ubuntu 16 (and I'm sure other OSes) just has Python 3 installed by default. Using the auto-generated inventory, which does not specify an alternate path to Python (how could it), results in an error. This appears to be [decently common](https://stackoverflow.com/questions/47423488/vagrant-ansible-python3).

**Comment by gildegoma** [comment]
Thank you @swpease for creating this request. You are reporting here a well-known issue in the Ansible project, which is however not specific to Vagrant context.

If your target system requires to set the `ansible_python_interpreter` variable, you're free to choose the way that best suit your needs (e.g. extra variable, host variable, group variable, `all`, ...). You can put it in your `Vagrantfile`, or simply in an Ansible variable files. Up to you 😃 

From Vagrant maintenance point of view, this is cumbersome to give general tips about third-party tools. Therefore, I'm closing wishing you'll understand and agree.

**References:**
- Ansible Docs FAQ: [How do I handle python not having a Python interpreter at /usr/bin/python on a remote machine?](https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-handle-python-not-having-a-python-interpreter-at-usr-bin-python-on-a-remote-machine)
- https://github.com/ansible/ansible/pull/50163 (Python interpreter discovery, to no longer blindly default to `/usr/bin/python`)

**Comment by gildegoma** [comment]
PS. If you want to set `ansible_python_interpreter` in the auto-generated inventory, you can use either the [host_vars](https://www.vagrantup.com/docs/provisioning/ansible_common.html#host_vars) option or the [groups](https://www.vagrantup.com/docs/provisioning/ansible_common.html#groups) option.
