### ISSUE TITLE
Vagrant up fails! Virtualbox

### ISSUE THREAD

**Issue by maczamora** [hashicorp/vagrant#10652]
### Vagrant version
Vagrant 2.2.3

### Host operating system
Windows 10 Version 1709 OS Build 16299.904

### Guest operating system
bento/ubuntu-16.04 - Ubuntu

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  os = "bento/ubuntu-16.04"
  net_ip = "192.168.50"

  config.vm.define :master, primary: true do |master_config|
    master_config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 1
        vb.name = "master"
    end
    
    master_config.vm.box = "#{os}"
    master_config.vm.host_name = 'saltmaster.local'
    master_config.vm.network "private_network", ip: "#{net_ip}.10"
    master_config.vm.synced_folder "saltstack/salt/", "/srv/salt"
    master_config.vm.synced_folder "saltstack/pillar/", "/srv/pillar"

    master_config.vm.provision :salt do |salt|
      salt.master_config = "saltstack/etc/master"
      salt.master_key = "saltstack/keys/master_minion.pem"
      salt.master_pub = "saltstack/keys/master_minion.pub"
      salt.minion_key = "saltstack/keys/master_minion.pem"
      salt.minion_pub = "saltstack/keys/master_minion.pub"
      salt.seed_master = {
                          "minion1" => "saltstack/keys/minion1.pub",
                          "minion2" => "saltstack/keys/minion2.pub"
                         }

      salt.install_type = "stable"
      salt.install_master = true
      salt.no_minion = true
      salt.verbose = true
      salt.colorize = true
      salt.bootstrap_options = "-P -c /tmp"
    end
  end


  [
    ["minion1",    "#{net_ip}.11",    "1024",    os ],
    ["minion2",    "#{net_ip}.12",    "1024",    os ],
  ].each do |vmname,ip,mem,os|
    config.vm.define "#{vmname}" do |minion_config|
      minion_config.vm.provider "virtualbox" do |vb|
          vb.memory = "#{mem}"
          vb.cpus = 1
          vb.name = "#{vmname}"
      end

      minion_config.vm.box = "#{os}"
      minion_config.vm.hostname = "#{vmname}"
      minion_config.vm.network "private_network", ip: "#{ip}"

      minion_config.vm.provision :salt do |salt|
        salt.minion_config = "saltstack/etc/#{vmname}"
        salt.minion_key = "saltstack/keys/#{vmname}.pem"
        salt.minion_pub = "saltstack/keys/#{vmname}.pub"
        salt.install_type = "stable"
        salt.verbose = true
        salt.colorize = true
        salt.bootstrap_options = "-P -c /tmp"
      end
    end
  end
end
```
### Debug output
https://gist.github.com/maczamora/00eb000804c50179ba997605e90e55bf

### Expected behavior
It should have spun up all virtual machines to use for the Saltstack demo!!! Here is my biggest concern. Something like this should just work with all appropriate versions after restarting and running everything as admin. I do understand that won't happen. However, when I try this a few months back and try again with the same issue that can't just happen. I was going to write my own demo but I have to pay for vmware? Can I get a free  license from you hashicorp? 👍 

### Actual behavior
vagrant up
Vagrant detected that VirtualBox appears installed on your system,
but calls to detect the version are returning empty. This is often
indicative of installation issues with VirtualBox. Please verify
that VirtualBox is properly installed. As a final verification,
please run the following command manually and verify a version is
outputted:

C:/Program Files/Oracle/VirtualBox/VBoxManage.exe --version

### Steps to reproduce
1. Tried both with the salt-stack demo and the Get started hashicorp/precise64 box
https://github.com/UtahDave/salt-vagrant-demo
2. Setup and installed everything neeed
3. Ran vagrant up and failed to the above output

### References
Exact same issue #9695 but I don't believe I'm using gitbash.. just powershell by default. It doesn't appear this was ever fixed in the previous ticket.

**Comment by briancain** [comment]
Hello @maczamora - A couple of questions....

- What program are you using to run Vagrant?
- Have you tried uninstalling and reinstalling the latest VirtualBox?
- What is the output of running `C:/Program Files/Oracle/VirtualBox/VBoxManage.exe --version` after re-installing VirtualBox?

**Comment by maczamora** [comment]
- Using powershell from cli
- I have tried uninstalling and re-installing. First with virtualbox and then vagrant. Before I tried vagrant then vbox.
- Output was something along the lines of this 6.0.4 r128413. I can double check this later.

**Comment by maczamora** [comment]
> * Using powershell from cli
> * I have tried uninstalling and re-installing. First with virtualbox and then vagrant. Before I tried vagrant then vbox.
> * Output was something along the lines of this 6.0.4 r128413. I can double check this later.

**Comment by maczamora** [comment]
@briancain

**Comment by briancain** [comment]
After running the version command with successful output, can you run Vagrant right after that?

**Comment by maczamora** [comment]
After running the version command I can run vagrant again asking but it asks me to check the version again.

**Comment by briancain** [comment]
@maczamora can you please share the output of running those comands?

**Comment by maczamora** [comment]
Hi @briancain , the output from running the commands is here at another gist. I've never used this before but it helps a lot to get the correct information out. https://gist.github.com/maczamora/62cd08cdf57069df0e1dbb23e5464721

**Comment by maczamora** [comment]
@briancain Any status on this?

**Comment by briancain** [comment]
@maczamora - it would probably be worth completely uninstalling VirtualBox and Vagrant and then reinstalling them to see if that fixes anything. Maybe even installing an older version of VirtualBox in case it has something to do with the 6.0 release.

**Comment by maczamora** [comment]
Okay, I'll try those suggestions. I haven't touched vagrant for a few weeks. I'll follow up at a later time.

**Comment by briancain** [comment]
Hey there @maczamora - I still haven't been able to reproduce this. And since I haven't heard back in a while I'm going to go ahead and close this. If you're still experiencing this issue after completely removing VirtualBox and Vagrant and reinstalling them feel free to let us know and we can reopen this ticket, or open a new one! Thanks.
