### ISSUE TITLE
Port forwarding is not working in Windows Hyper-V linux VM

### ISSUE THREAD

**Issue by micemuni** [hashicorp/vagrant#10653]
### Host operating system
Windows server 2012 

### Guest operating system
Customized Linux AMI i used in VM

### Expected behavior
I am using powershell script to automate the VM launch and setup in windows hyper-V server
I have deployed the application in VM linux machine 
its running docker container and i am able to see the application is loading fine in Windows hyper-V server browser. I have added port forwarding in windows hyperV server using below commands 
But application is not loading outside of Windows hyperV server

Note:- Even telnet to that port also not working when i try from outside from WIndows HyperV server 

### Actual behavior
When i hit the Windows hyper-V server IP or application domain, then its not loading 

### Powershell commands used for port forwarding 
Add-NetNatStaticMapping -ExternalIPAddress "0.0.0.0" -ExternalPort 80 -InternalIPAddress "192.168.0.10" -InternalPort 80 -NatName VM-Nat-name 
Add-NetNatStaticMapping -ExternalIPAddress "0.0.0.0" -ExternalPort 443 -InternalIPAddress "192.168.0.10" -InternalPort 443 -NatName VM-Nat-name

**Comment by briancain** [comment]
Hi there @micemuni -

Thank you for opening an issue. Do you have the Vagrantfile you are using, version of Vagrant, and debug gist available?

**Comment by chrisroberts** [comment]
Hi there. Port forwarding is not currently implemented in the Vagrant Hyper-V provider but will be included in an upcoming release. 

We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
