### ISSUE TITLE
Struggling with static IP + Docker provider

### ISSUE THREAD

**Issue by jesusgn90** [hashicorp/vagrant#10656]
Hi team,

I'm struggling with static IP assignment for Docker provider.

```rb
  config.vm.define "dockeragent" do |dockeragent|
    dockeragent.vm.provider "docker" do |d|
      d.build_dir = "../installers/docker/"
    end
    dockeragent.vm.network :private_network, ip: "172.16.1.3"
  end
```

I want my container named `dockeragent` uses `172.16.1.3` but it's using always `172.16.1.1`, my problem is that I want multiple containers, and each container must have its own IP.

Help!

Thanks in advance!

**Comment by briancain** [comment]
Hey there @jesusgn90 - It looks like this isn't currently supported with the docker provider :thinking: https://www.vagrantup.com/docs/docker/basics.html#synced-folders-and-networking

> Private and public networks are not currently supported.

I _think_ this should be covered in this issue here https://github.com/hashicorp/vagrant/issues/9873

**Comment by jesusgn90** [comment]
This use case is critical for us, is there an ETA for this feature?

Regards!

**Comment by briancain** [comment]
@jesusgn90 - I'm going to try to get started on it soon, but it won't be a small feature by any means so I can't give you a definite time frame. It does look possible that you could use triggers as a work around for setting up networking with docker in the meantime:

```ruby
config.trigger.before :up do |trigger|
  trigger.name = 'Create network vagrant'
  trigger.run = { inline: 'docker network create vagrant' }
end

config.trigger.after :destroy do |trigger|
  trigger.name = 'Remove network vagrant'
  trigger.run = { inline: 'docker network rm vagrant' }
end
```

But replace the inline scripts with the networks you _actually_ wish to create and delete, of course!
