### ISSUE TITLE
Vagrant 2.2.3 :  Timed out while waiting for the machine to boot

### ISSUE THREAD

**Issue by zwl1619** [hashicorp/vagrant#10669]
##environment:   
windows 10 1809 x64   
[Vagrant 2.2.3][1]    
[centos/7 v1901.01][2]   
[VirtualBox 6.0.4][3]    

##Vagrantfile:

    # -*- mode: ruby -*-
    # vi: set ft=ruby :
    
    Vagrant.configure("2") do |config|
     
      config.vm.box = "centos7"
      
      config.vm.network :private_network, ip: "192.168.33.3"
      config.vm.synced_folder "d:/workspace/www/", "/var/www"  
      
      config.vm.hostname = "vagrant-dev"
      
      
      config.ssh.username = 'root'
      config.ssh.password = 'vagrant'
      config.ssh.insert_key = 'true'
      
      config.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = "2048"
      end
    end

##error:

    λ vagrant up
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Clearing any previously set forwarded ports...
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
        default: Adapter 2: hostonly
    ==> default: Forwarding ports...
        default: 22 (guest) => 2222 (host) (adapter 1)
    ==> default: Running 'pre-boot' VM customizations...
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 127.0.0.1:2222
        default: SSH username: root
        default: SSH auth method: password
        default: Warning: Connection aborted. Retrying...
        default: Warning: Connection reset. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
        default: Warning: Authentication failure. Retrying...
    Timed out while waiting for the machine to boot. This means that
    Vagrant was unable to communicate with the guest machine within
    the configured ("config.vm.boot_timeout" value) time period.
    
    If you look above, you should be able to see the error(s) that
    Vagrant had when attempting to connect to the machine. These errors
    are usually good hints as to what may be wrong.
    
    If you're using a custom box, make sure that networking is properly
    working and you're able to connect to the machine. It is a common
    problem that networking isn't setup properly in these boxes.
    Verify that authentication configurations are also setup properly,
    as well.
    
    If the box appears to be booting properly, you may want to increase
    the timeout ("config.vm.boot_timeout") value.

What should I do?

  [1]: https://www.vagrantup.com/downloads.html
  [2]: https://app.vagrantup.com/centos/boxes/7
  [3]: https://www.virtualbox.org/wiki/Downloads

**Comment by PsyLogic** [comment]
remove this lines
config.ssh.username = 'root'
config.ssh.password = 'vagrant'
config.ssh.insert_key = 'true'

and try
vagrant reload && vagrant ssh

**Comment by burasuk** [comment]
I have the same issue, but it show even when i run:
`vagrant init hashicorp/precise64` and then `vagrant up`.
I think that it start show after Windows 10 update.

**Comment by kaw18thar** [comment]
I had this issue too,
I updated vagrant to the latest version then I enabled virtualization from the BOIS settings. Apparently they disabled virtualization after windows 10 update

**Comment by jackluo2012** [comment]
+1
