### ISSUE TITLE
Openssh unsupported key type - Windows 10

### ISSUE THREAD

**Issue by yusufscott** [hashicorp/vagrant#10668]
### Vagrant version
Vagrant 2.2.3

### Host operating system
Windows 10

### Guest operating system
Ubuntu 16.04.5

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
	# Setup Guest OS from Image (Ubuntu 16.04)
	config.vm.box = "./base.box"

	config.ssh.username = SSH_USER
	config.ssh.private_key_path = ".ssh/devkey"

	# Setup Hostname
	config.vm.hostname = 'base.ugen.local'

	# Setup Networking
	config.vm.network "private_network", ip: "192.168.222.100"
	config.vm.network "public_network"

	# Setup VM Provider Configuration
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
	end
end
```

### Debug output
[debug.txt](https://github.com/hashicorp/vagrant/files/2862336/debug.txt)

### Expected behavior
Vagrant should be able to successfully connect via ssh.

### Actual behavior
The private key you're attempting to use with this Vagrant box uses
an unsupported encryption type. The SSH library Vagrant uses does not support
this key type. Please use `ssh-rsa` or `ssh-dss` instead. Note that
sometimes keys in your ssh-agent can interfere with this as well,
so verify the keys are valid there in addition to standard
file paths.

### Steps to reproduce
I have attempted this on different hosts, and have the same issue.

### References
[9035](https://github.com/hashicorp/vagrant/issues/9035)

**Comment by briancain** [comment]
Hey there @yusufscott - the debug log you shared does not actually contain the error message you mentioned in your issue. Do you have a log that shows this behavior? Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
