### ISSUE TITLE
Vagrantfile forwarded_port with IPv6?

### ISSUE THREAD

**Issue by ajmas** [hashicorp/vagrant#10678]
I am looking for any indication whether it is possible to use IPv6 for forwarded_port, since I am having difficulty finding any clear documentation. 

The general expectation is that it should work out of the box, in the same way as IPv4. 

**Details**

I am running a Nginx server in the VM, which I can connect to from within the VM as:

```
wget "http://localhost/" --> works
wget "http://127.0.0.1/" --> works
wget "http://[::1]/" --> works
```

From my host environment I try:

```
wget "http://localhost:8080/" --> works
wget "http://127.0.0.1:8080/" --> works
wget "http://[::1]:8080/" --> Connection refused.
wget -6 "http://localhost:8080/" --> Connection refused.
```

Doing an 'lsof' on the host I see 8080 is only bound to IPv4, while in guest it is IPv6.

**Environment**

 - Host OS: macOS 10.14.2
 - Vagrant version: 2.1.4
 - VirtualBox version: 5.2.18
 - Guest OS: Ubuntu 18.04.1 LTS, Server edition

**Vagrantfile**

```
require 'yaml'

Vagrant.configure("2") do |config|
  config.vbguest.auto_update = false
  config.vm.box = "ubuntu/bionic64"

  config.ssh.forward_agent = true
    
  config.vm.provider :virtualbox do |vb, override|
    vb.name = 'prod-equiv-devbox'    
    
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 443, host: 8443
    
    override.vm.provision :shell do |s|
      s.path = "provision/install.sh"
      s.args = "/home/ubuntu ubuntu"
      #s.privileged = false
    end
  end
end
```

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Comment by josdotso** [comment]
Hi @briancain. Can this be reopened?

I am seeing this same issue, with a remarkably similar setup. I'm on MacOS using Vagrant w/ the bento/ubuntu-18.04 box.

Here is my gist: https://gist.github.com/josdotso/986504a0d5841ed8a76aac0bdfa0869e

Here is my vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"

  config.vm.network "forwarded_port",
    guest: 6443,
    guest_ip: "::1",
    host: 6443,
    host_ip: "::1"

  config.vm.network "public_network",
    bridge: [  # Vagrant falls back to first match.
      "en8: Belkin USB-C LAN"
    ]

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "2"
    vb.memory = "2048"
  end

#  config.vm.provision "shell",
#    path: "provision.sh",
#    privileged: false

  if Vagrant.has_plugin?("vagrant-cachier")
    # Copy/Paste from: https://github.com/fgrehm/vagrant-cachier#quick-start
    #
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box

    # For more information please check http://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  end
end
```

**Comment by josdotso** [comment]
Here's where I'm hitting the issue: https://github.com/josdotso/k6

Here's the command I used to evaluate that Vagrant/VirtualBox is the issue:

```bash
curl -vkgs6 https://[::1]:6443 -o /dev/null
# * Rebuilt URL to: https://[::1]:6443/
# *   Trying ::1...
# * TCP_NODELAY set
# * Connection failed
# * connect to ::1 port 6443 failed: Connection refused
# * Failed to connect to ::1 port 6443: Connection refused
# * Closing connection 0
```
