### ISSUE TITLE
Inline shell triggers don't recognize IO redirection

### ISSUE THREAD

**Issue by anasbouzid** [hashicorp/vagrant#10674]
On triggers, I/O redirection doesn't work with the `inline` shell setting, using the `path` shell setting works normally.

### Vagrant version
2.2.3

### Host operating system
Ubuntu 16.04

### Guest operating system
Ubuntu 18.04

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/bionic64"

  config.trigger.before :up do |trigger|
    trigger.run = {
      inline: "date >> outfile"
    }
  end
end
```

### Debug output
https://gist.github.com/anasbouzid/e1144379ee8213c63d6370295234b053

### Expected behavior
Append current date to `outfile`

### Actual behavior
fails:
```
    default: /bin/date: extra operand ‘outfile’
    default: Try '/bin/date --help' for more information.
==> default: Trigger run failed
```

### Steps to reproduce

Run `vagrant up`

**Comment by briancain** [comment]
Hey there @anasbouzid - This is actually something I've been meaning to document. When you use the run option with inline scripts, you are executing a shell subprocess, not a bash session. You are not the first person to run into this.....IO redirection with that operator is actually something within bash, so you'll want to do something like this to execute your script in bash:

```ruby
 config.trigger.after :up do |t|
      t.run = {inline: "/bin/bash -c 'date >> outfile'"}
end
```

```
brian@localghost:vagrant-sandbox % be vagrant up bork                                                    ±[●][master]
Bringing machine 'bork' up with 'virtualbox' provider...
==> bork: Checking if box 'bento/ubuntu-18.04' version '201812.27.0' is up to date...
==> bork: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> bork: flag to force provisioning. Provisioners marked to run always will still run.
==> bork: Running action triggers after up ...
==> bork: Running trigger...
    bork: Running local: Inline script
    bork: /bin/bash -c 'date >> outfile.txt'
brian@localghost:vagrant-sandbox % ls outfile.txt                                                       ±[●●][master]
outfile.txt
brian@localghost:vagrant-sandbox % cat outfile.txt                                                      ±[●●][master]
Thu Feb 21 11:22:43 PST 2019
```

**Comment by anasbouzid** [comment]
Thanks for your help, much appreciated.
