### ISSUE TITLE
Vagrant builder boxes based on Ubuntu contain dangling reference to build path

### ISSUE THREAD

**Issue by haggaie** [hashicorp/vagrant#10680]
When building a vagrant box using the vagrant builder based on the ubuntu/bionic64 image, the resulting box contains a path to the build directory in the build machine.

The resulting OVF file has a UART virtual device that is set to store its log in the build directory. I believe the problem is due to the ubuntu/bionic64 image setting up this device as part of its Vagrantfile (see [here](https://git.launchpad.net/livecd-rootfs/tree/live-build/ubuntu-cpc/hooks.d/base/vagrant.binary)), and I guess `vagrant package` leaves this setting in the new box as well.

Is there a way to clean this setting before creating the box?

**Comment by kiwivogel** [comment]
To be honest I think this is an ubuntu issue. The line that creates the breaking reference is commented out in ubuntu/master with a note that it should not bet set.

**Comment by haggaie** [comment]
I noticed that simply disabling the serial port causes the VM to slow down significantly or to get stuck during boot. Would it make sense to package the same Vagrantfile script that was in the original box into the new box?

**Comment by kiwivogel** [comment]
I've "solved" the issue on my end by simply adding     
```
config.vm.provider "virtualbox" do |vb|
  vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ] 
```
To negate the problematic line in the base image Vagrantfile. (If you want the logs you could also just add the to update the link to a directory that does exist.

**Comment by haggaie** [comment]
Yes, I used
```
vb.customize [ "modifyvm", :id, "--uartmode1", "file", File.join(Dir.pwd, "console.log") ]
```
otherwise, on Windows / Mac OS the resulting VM is too slow.

By the way, is there a way to tell packer to add this line to the Vagrantfile of the resulting box?

**Comment by kiwivogel** [comment]
I hadn’t noticed any slowdown. Will just do a vagrant-console.log then. Thanks for the headsup!

**Comment by chrisroberts** [comment]
Hi! This is definitely a problem with the way the ubuntu boxes are configured and is an issue within VirtualBox. Simply disabling the serial port causes an issue because the guest is still attempting to use it. More information here: https://github.com/hashicorp/vagrant/issues/10578#issuecomment-459081990

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
