### ISSUE TITLE
One SSH session ending disconnects all sessions

### ISSUE THREAD

**Issue by grimmn** [hashicorp/vagrant#10687]
### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
Vagrant 2.2.3

### Host operating system
Ubuntu 18.04

### Guest operating system
Ubuntu 14.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mvx-trusty"
  config.vm.box_url = "https://artifactory.domain.com:443/artifactory/mvx/mvx-trusty.json"
  config.vm.box_version = "1.0.2"

  config.ssh.forward_env = ["SVN_USERNAME", "SVN_PASSWORD", "BUILD_NUMBER"]
end
```

### Debug output
https://gist.github.com/grimmn/4427a0118ca5a4538693c6803d4a7cef

### Expected behavior
Simultaneous Jenkins jobs containing `vagrant ssh` commands run to completion.

### Actual behavior
Once the first of multiple simultaneous Jenkins jobs finishes running a shell script step containing `vagrant ssh -c "./build_script.sh"` all currently running `vagrant ssh` sessions using the same base box disconnect simultaneously. The console log for the prematurely disconnecting boxes show regular output, then `Connection to 127.0.0.1 closed by remote host.` then fail because the build step failed. I verified with the console log timestamps that the disconnects happen at the exact point in time when the first job's SSH session ends naturally.

### Steps to reproduce
1. Start multiple Jenkins jobs which use the same Vagrant box and wait for the first one that finishes running `vagrant ssh`.

**Comment by chrisroberts** [comment]
Hi there,

This is something that appears to be isolated behavior to your specific environment. I have not been able to reproduce the behavior you describe locally. My best guess is that the script you are running is causing the sshd to restart or perhaps is restarting the network services on the guest. If you can provide specific details (minimal Vagrantfile + script) to reproduce the behavior you are encountering, I'd be happy to investigate further. But based on the details provided, this appears to be an issue with the specific script being executed on the guest.

Cheers!

**Comment by grimmn** [comment]
Hi Chris,

The exact Vagrantfile being used is included in my original post. As for the script I'm running it's really simple, just running a few static analysis tools over the codebase as part of our CI builds. There's nothing in there that I would expect to affect sshd or network services in the guest.

```
!#/bin/bash

# Strip out unsupported GCC warning flags from compile command database before using with clang-tidy
sed -i '/Wlogical-op/d' ./compile_commands.json

run-clang-tidy 2>&1 | tee clang-tidy.log
cppcheck --project=compile_commands.json --enable=all --std=c++11 --std=posix --inline-suppr --xml --xml-version=2 --output-file=cppcheck.xml
```

**Comment by chrisroberts** [comment]
@grimmn In your setup you have multiple jenkins jobs running a `vagrant ssh` command. Is that all these jobs are doing? Is the guest cleanup (either halt or destroy) handled by a different jenkins job? If so, how is that job invoked?

**Comment by grimmn** [comment]
Hi @chrisroberts, thanks for getting back to me. The Jenkins jobs start by `vagrant up`ing the build environment VM, then build the actual project through `vagrant ssh` running a `make` command. After that completes they run a second `vagrant ssh` command running the script which runs the static analysis tools over the codebase. The jobs have a post-build task which runs `vagrant destroy` to clean things up as the job completes.

From my observations the first `vagrant ssh` call which runs `make target` in the Jenkins jobs never seems to cause any problems with the SSH sessions. Only the second `vagrant ssh` which runs the static analysis script seems to trigger the issue.

**Comment by chrisroberts** [comment]
@grimmn I'm not sure since I can't see how your things are setup, but my best guess is that you have something triggering the `vagrant destroy` prematurely which is causing anything with an active ssh connection to get disconnected. Unfortunately, unless you can provide a Vagrantfile and scripts to run which reliably reproduce the behavior, a best guess is all that I can provide.

Cheers!
