### ISSUE TITLE
vagrant.provision runs inline powershell script twice

### ISSUE THREAD

**Issue by alldayanyday** [hashicorp/vagrant#10689]
In my vagrantfile, I define an inline powershell script as a provisioner which, among other things, installs chocolatey on the vm then installs google chrome using chocolatey.  However, at the time that I was attempting to provision a vm, this google chrome chocolatey package was not configured correctly (the hash configured in the package did not match the hash of the installation file downloaded), which caused the inline script to return an error code of -1 and fail.  **NOTE** The reason I say "at the time that I was attempting to provision a vm" is due to the fact that the person who maintains the google chrome chocolatey package may, by the time you see this issue, fix the configuration error, thus changing the behavior of the inline script.  I just want to make sure that is 100% clear.  However, rather than the script ending (since the inline script was the last part of the vagrantfile), the vagrant ran the provisioned inline powershell script a second time.  Not sure why, as I only configured to run once.  I suspect it is due to the fact that the chocolatey package install generated an error. If the install had succeeded, I suspect vagrant would not have run the inline script again.

### Vagrant version
vagrant -v
Vagrant 2.2.3

### Host operating system
Windows 10 x64 version 1809

### Guest operating system
Windows Server 2016 Datacenter

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "whiggs/mybox"
  config.vm.box_check_update = true
  config.vm.provider :virtualbox do |v|
		v.gui = true
		# 4GB RAM
		v.customize ["modifyvm", :id, "--memory", "4096"]
		# 2 CPUs
		v.customize ["modifyvm", :id, "--cpus", "2"]
		# Video RAM is 32 MB
		v.customize ["modifyvm", :id, "--vram", 32]
		# For better DNS resolution
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		# No audo
		v.customize ["modifyvm", :id, "--audio", "none"]
		# Clipboard enabled
		v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
		v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
		v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
	end
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 500
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 5985, host: 55985
  config.vm.provision "shell", privileged: true, powershell_elevated_interactive: true, inline: <<-EOH
  net.exe config server /autodisconnect:-1
$ErrorActionPreference = "SilentlyContinue"
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
$env:PATH +=";$($env:SystemDrive)\\ProgramData\\chocolatey\\bin"
Get-PackageProvider -Name NuGet -ForceBootstrap -Force
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory private
choco.exe install googlechrome -y
EOH
end

```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/alldayanyday/74d982984537d210ff614a60a8aa9426

### Expected behavior
The inline script should only run once when an error is encountered.

### Actual behavior
Inexplicably runs twice

### Steps to reproduce
1. Vagrant up

**Comment by jkohrman** [comment]
Hello @alldayanyday - Please note that you have previously been restricted from contributing to HashiCorp repositories under your alias account @whiggs due to continued violations of our [Code of Conduct](https://www.hashicorp.com/community-guidelines).

Attempts to create additional accounts to bypass this restriction are also in violation of our community guidelines.  As such, we regret to inform you that this account has also been restricted effective immediately.

If you feel this has been done in error or would like to discuss a reasonable alternative, please contact us at any time at security@hashicorp.com and we will be happy to help you.
