### ISSUE TITLE
translation missing: en.login_command.middleware.authentication.different_target

### ISSUE THREAD

**Issue by rawbertp** [hashicorp/vagrant#10682]
### Vagrant version
2.2.3

### Host operating system
Same for both Linux and Windows

### Guest operating system
CentOs 7

### Vagrantfile
`config.vm.box_url` is set to a custom Artifactory server.
`ATLAS_TOKEN` is set.

As discussed/explained in #9928 this leads to a warning message being displayed. However, for me (Linux) and other users (Windows) it just says "translation missing: en.login_command.middleware.authentication.different_target" instead of printing the actual message.

### Debug output
```
...
 WARN client: ATLAS_TOKEN detected within environment. Using ATLAS_TOKEN in place of VAGRANT_CLOUD_TOKEN.
 INFO interface: warn: translation missing: en.login_command.middleware.authentication.different_target

translation missing: en.login_command.middleware.authentication.different_target
...
```

### Expected behavior
Print the message defined here: https://github.com/hashicorp/vagrant/blob/master/plugins/commands/login/locales/en.yml#L5

### Actual behavior
The key is printed instead of the message.

### Steps to reproduce
1. `config.vm.box_url` is set to a custom repository
2. `ATLAS_TOKEN` is set
3. `vagrant up`

### References
N/A

**Comment by briancain** [comment]
Hey there @rawbertp - For reference, what is the exact command you ran, and please include the debug output too. Thanks!

**Comment by rawbertp** [comment]
Hi Brian,
It happens for `vagrant up|destroy|ssh`... 

Debug for `vagrant ssh`: https://gist.github.com/rawbertp/c08526b142d3aa85b2f48fc12b4d0e59
