### ISSUE TITLE
Cannot connect to Mysql via SSH

### ISSUE THREAD

**Issue by paul-gene** [hashicorp/vagrant#10684]
Using Sequel Pro, I get this error:

Received disconnect from 192.168.100.100 port 22:2: Too many authentication failures for vagrant from 192.168.100.1 port 55647 ssh2
Disconnected from 192.168.100.100 port 22

I've tried looking for a way to fix it, but I have no idea how to fix this.

I'm using the private key file from the vagrant folder.

**Comment by briancain** [comment]
Hey @paul-gene - this issue tracker on Github is specifically for bugs with the software Vagrant. It just looks like that error is referring to your machines user "vagrant", but it is not a reference to the software.

Please refer to the Sequel Pro documentation for how to use that software. Thanks!
