### ISSUE TITLE
Mkdir permission denied for vagrant user in synced folder

### ISSUE THREAD

**Issue by paul-gene** [hashicorp/vagrant#10683]
After SSHing into the Vagrant box, I am unable to run `mkdir` in the root synced folder.

`config.vm.synced_folder ".", "/var/www", :owner => "www-data", :group => "www-data"`

Inside `/var/www` running `mkdir test` gives a permission denied error.

I have added the vagrant user to the www-data group, but that didn't help.

```
vagrant@contrib-jessie:~$ groups
vagrant cdrom floppy sudo audio dip www-data video plugdev netdev
vagrant@contrib-jessie:~$ cd /var/www/
vagrant@contrib-jessie:/var/www$ mkdir test
mkdir: cannot create directory 'test': Permission denied
vagrant@contrib-jessie:/var/www$
```

**Comment by briancain** [comment]
Hey there @paul-gene - You need to probably also give the vagrant user write permissions to write to that folder. I recommend looking up file permissions for debian and seeing what you might need to change or modify. Either way this is not a Vagrant bug. Thanks!

**Comment by paul-gene** [comment]
Any help there?

I tried `chown -R vagrant:www-data /var/www` but tat didn't seem to work
