### ISSUE TITLE
Vagrant is supposed to only configure a public network, but there is a private one as well.

### ISSUE THREAD

**Issue by queglay** [hashicorp/vagrant#10695]
Hey guys.  I'm configuring a vagrant image in virtualbox with this network config-

    config.vm.network "public_network"

so I do get a bridged adapter (192.168.80.34) , which is fine, but there is also a private adaptor that I have not specified anywhere (10.0.2.15).  this seems like undesireable behaviour since I didn't specify anywhere that it should exist, and there appears to be no docs on how to ensure this doesn't exist.

Here is a list of my adapters-
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:3e:59:1c:26:9a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::3e:59ff:fe1c:269a/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:df:aa:a5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.80.34/24 brd 192.168.80.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fedf:aaa5/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!

**Comment by queglay** [comment]
Apologies, here it is

### Vagrant version
Vagrant 2.2.3

### Host operating system
RHEL 7.5

### Guest operating system
ubuntu/xenial64 or bento/ubuntu-16.04
- I've replicated the issue in both.

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"
end

```

### Debug output
I'll provide network information, since this is actually intended behaviour

vagrant@ubuntu-xenial:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:3e:59:1c:26:9a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::3e:59ff:fe1c:269a/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:22:f8:38 brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.10/24 brd 192.168.33.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe22:f838/64 scope link 
       valid_lft forever preferred_lft forever
4: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:9f:4d:ab brd ff:ff:ff:ff:ff:ff
    inet 192.168.92.42/24 brd 192.168.92.255 scope global enp0s9
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe9f:4dab/64 scope link 
       valid_lft forever preferred_lft forever
vagrant@ubuntu-xenial:~$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.2.2        0.0.0.0         UG    0      0        0 enp0s3
10.0.2.0        0.0.0.0         255.255.255.0   U     0      0        0 enp0s3
192.168.33.0    0.0.0.0         255.255.255.0   U     0      0        0 enp0s8
192.168.92.0    0.0.0.0         255.255.255.0   U     0      0        0 enp0s9


### Expected behavior
What I'd like to do is ensure this extra interface is removed - enp0s3 10.0.2.15/24, and just use the public interface as the default gatteway -192.168.92.0
My understanding is this is used as a nat for the ssh access, but because it is the default gateway it is causing problems.  I would like the gateway to be on the interface with 192.168.92.0/24 (192.168.92.1) 
in this case - enp0s9

I was hoping that the public network could just be used, the 10.0.2.0/24 interface isn't necesary.

In my case, I'm trying to start an open vpn client, to connect to an ec2 openvpn access server, but this nat interface is preventing it from working.

it appears this is expected behaviour from 2 different ubuntu images I tested, ubuntu and bento.

### Actual behavior
default gateway is through enp0s3

### Steps to reproduce
vagrant up.
vagrant ssh
ip a

### References
this is a good discussion on stackexchange, but not a solution-
https://stackoverflow.com/questions/35208188/how-can-i-define-network-settings-with-vagrant

**Comment by chrisroberts** [comment]
Hi there,

The first interface you see on the guest is the NAT interface which is generated by Vagrant and is required. Users have posted methods in the past for disabling the NAT interface but that setup is not supported by Vagrant. It seems the underlying issue affecting you is that you want the default gateway to be through enp0s9. You can easily do that with a shell provisioner and the `ip` command.

Cheers!

**Comment by queglay** [comment]
Thanks for your reply.  if its not recommended to disable it, is it possible to change the ip of that addres for the NAT?  it is causing a conflict with another subnet.

**Comment by chrisroberts** [comment]
You can use the customize option in the virtualbox provider:

https://www.vagrantup.com/docs/virtualbox/configuration.html#vboxmanage-customizations

to adjust the subnet for the NAT network. An example of the command required can be seen here: https://superuser.com/questions/398478/change-virtualbox-dhcp-to-issue-192-168-x-x-adresses-instead-of-10-0-x-x-adresse/398480#398480

Cheers!
