### ISSUE TITLE
File provisioner produces unexpected names when copying a file into an existing directory

### ISSUE THREAD

**Issue by edmcman** [hashicorp/vagrant#10697]
### Vagrant version
2.2.3

### Host operating system
Ubuntu 14.04

### Guest operating system
Ubuntu 14.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = 'sei'
  config.vm.provider :vsphere do |vsphere|
    vsphere.template_name = 'packer-templates/ubufuzz-cli-amd64-vmware-sas'
    vsphere.cpu_count = 8
    vsphere.memory_mb = 16000
  end

  config.vm.provision "shell", inline: "mkdir dir1 dir2 dir3", privileged: false
  config.vm.provision "file", source: "dir/a", destination: "dir1/"
  config.vm.provision "file", source: "dir/a", destination: "dir2/a"
  config.vm.provision "file", source: "dir/a", destination: "dir3"

end
```

### Expected behavior
`dir/a` should have been copied to `dir1/a`, `dir2/a`, and `dir3/a`.

### Actual behavior
`dir/a` was copied to `dir1/dir1`, `dir2/a`, and `dir3/dir3`.

### Steps to reproduce
1. `mkdir dir/a`
2. `vagrant up`
3. `vagrant ssh default -- find dir{1,2,3}`

### Debug output
https://gist.github.com/edmcman/ac13480a60aaa691c35ab10c34260e87

**Comment by briancain** [comment]
Hey there @edmcman - This is expected, as stated in the file provisioner docs:

https://www.vagrantup.com/docs/provisioning/file.html#destination

> Is the remote path on the guest machine where the source will be uploaded to

In other words, the destination is where your file or folder will end up. If you want each folder to have a subfolder called `a`, you need to define them as:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = 'box'
  config.vm.provision "file", source: "dir/a", destination: "dir1/a"
  config.vm.provision "file", source: "dir/a", destination: "dir2/a"
  config.vm.provision "file", source: "dir/a", destination: "dir3/a"
end
```

You also shouldn't need to create the folders on the guest, as the the provisioner can handle that already. Creating those folders might be a reason why you are getting unexpected behavior as well.

```
vagrant@vagrant:~/sshtest$ mkdir -p dir/a
vagrant@vagrant:~/sshtest$ touch dir/a/test.txt
vagrant@vagrant:~/sshtest$ tree dir
dir
└── a
    └── test.txt

1 directory, 1 file
vagrant@vagrant:~/sshtest$ vim Vagrantfile
vagrant@vagrant:~/sshtest$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/ubuntu-18.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-18.04' version '201812.27.0' is up to date...
==> default: Setting the name of the VM: sshtest_default_1551120503533_99154
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key

    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.2.22
    default: VirtualBox Version: 6.0
==> default: Mounting shared folders...
    default: /vagrant => /home/vagrant/sshtest
==> default: Running provisioner: file...
    default: /home/vagrant/sshtest/dir/a/. => dir1/a
==> default: Running provisioner: file...
    default: /home/vagrant/sshtest/dir/a/. => dir2/a
==> default: Running provisioner: file...
    default: /home/vagrant/sshtest/dir/a/. => dir3/a
vagrant@vagrant:~/sshtest$
vagrant@vagrant:~/sshtest$ vagrant ssh -c "find dir{1,2,3}"
dir1
dir1/a
dir1/a/test.txt
dir2
dir2/a
dir2/a/test.txt
dir3
dir3/a
dir3/a/test.txt
Connection to 127.0.0.1 closed.
```

Thanks!

**Comment by edmcman** [comment]
> Is the remote path on the guest machine where the source will be uploaded to

This is vague.  If the destination is an existing directory, it doesn't say what it will be named.  Almost all unix tools that I know of use the original filename in this case.  Do you really want Vagrant to behave differently?

> You also shouldn't need to create the folders on the guest, as the the provisioner can handle that already. Creating those folders might be a reason why you are getting unexpected behavior as well.

Are you saying that provisioning a file in an existing directory is not supported?  I created the folders because in my real world usage I am provisioning into an existing directory.

**Comment by briancain** [comment]
> Are you saying that provisioning a file in an existing directory is not supported? I created the folders because in my real world usage I am provisioning into an existing directory.

No. It's supported. I'm saying you need to be explicit in what path you are using with the destination option. If you just tell Vagrant `dir1` is the destination, that is where it will provision your `source`. If you don't want to specify the exact folder and want to preserve the original name, you can simply say the destination will be `folder/` like I have below.

```
vagrant@vagrant:~/sshtest$ cat Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "shell", inline: "mkdir dir1 dir2 dir3", privileged: false
  config.vm.provision "file", source: "dir/a", destination: "dir1/"
  config.vm.provision "file", source: "dir/a", destination: "dir2/"
  config.vm.provision "file", source: "dir/a", destination: "dir3/"
end
vagrant@vagrant:~/sshtest$ vagrant ssh -c "find dir{1,2,3}"
dir1
dir1/a
dir1/a/test.txt
dir2
dir2/a
dir2/a/test.txt
dir3
dir3/a
dir3/a/test.txt
Connection to 127.0.0.1 closed.
vagrant@vagrant:~/sshtest$ vagrant ssh
vagrant@vagrant:~$ tree
.
├── dir1
│   └── a
│       └── test.txt
├── dir2
│   └── a
│       └── test.txt
└── dir3
    └── a
        └── test.txt

6 directories, 3 files
vagrant@vagrant:~$ ls
dir1  dir2  dir3
```

Otherwise If your `destination` is an existing directory or no, it will drop your `source` file or folder and its contents exactly as is defined in the destination folder specified:

```
vagrant@vagrant:~/sshtest$ cat Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "shell", inline: "mkdir dir1 dir2 dir3", privileged: false
  config.vm.provision "file", source: "dir/a", destination: "dir1"
  config.vm.provision "file", source: "dir/a", destination: "dir2"
  config.vm.provision "file", source: "dir/a", destination: "dir3"
end
vagrant@vagrant:~/sshtest$ vagrant ssh
vagrant@vagrant:~$ tree
.
├── dir1
│   └── test.txt
├── dir2
│   └── test.txt
└── dir3
    └── test.txt

3 directories, 3 files
```

**Comment by edmcman** [comment]
> If you don't want to specify the exact folder and want to preserve the original name, you can simply say the destination will be `folder/` like I have below.

Perfect, that is sensible behavior.  If you look at my original example, I copy the file `dir/a` to the existing directory `dir1/`, but this names the new file as `dir1` instead of `a`.  In other words, from the original path, the new file is `dir1/dir1`.  I don't think is the expected behavior.

Also, in my example `a` is a file, not a directory.  It looks like Vagrant is doing the right thing when `a` is a directory from your examples.

**Comment by edmcman** [comment]
Oops, I realized my reproduction steps were wrong.  It should be `mkdir dir`, `touch dir/a`.  Sorry!

**Comment by chrisroberts** [comment]
Closing this up as #10698 resolves it. Thanks for the report @edmcman !

**Comment by edmcman** [comment]
Thanks for the quick turnaround! @chrisroberts @briancain
