### ISSUE TITLE
The guest machine entered an invalid state Virtualbox

### ISSUE THREAD

**Issue by giper45** [hashicorp/vagrant#10699]
### Vagrant version
 Vagrant 2.2.3
### Host operating system
This is the operating system that you run locally.

### Guest operating system
This is the operating system you run in the virtual machine.
Linux gx1 4.4.14 #2 SMP Fri Jun 24 13:38:27 CDT 2016 x86_64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz GenuineIntel GNU/Linux
Slackware 14.2
### Virtualbox version 
Versione 6.0.4 r128413 (Qt5.6.1)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "hashicorp/precise32"
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Vagrant Error:  https://gist.github.com/giper45/18ae4ce65ac2467d7b16b51d1ef6b716
Virtualbox machine error: https://gist.github.com/giper45/1751d4ef3fa8a8818041cb3214cccd24
### Expected behavior
Vagrant should normally up the machine as the previous Virtualbox machines...

### Actual behavior
What actually happened?
The Virtualbox machine should be run... it stops and it is not possible to run up by using Vagrant... the virtual machine properly works by using normal virtualbox. 
 it seems that the %10...90 is very fast respect to old Virtualbox version. The issue was not present with Vbox 5.x . Now I will try tu downgrade Vbox to previous version. 

### Steps to reproduce
1. vagrant init hashicorp/precise32 (or another)
2. vagrant up

**Comment by giper45** [comment]
After an "hellish morning" I have solved by: 
1. Removing all vagrant directories inside the /tmp directory  
2. Removing the .vagrant.d directory (I don't know it it cares)  
3. ``` 
ln -s libncurses.so.5.9 libtinfo.so.5 
```
under /lib64/ directory ... 
Slackware, love it but sometimes ... :) ! 
Vbox + vagrant combination is very fast with latest versions! 
Thanks anyway,
GX1

**Comment by LotarProject** [comment]
@giper45 Slackware loves you!

You can install AlienBob `libtinfo` package (http://www.slackware.com/~alien/slackbuilds/libtinfo/). This package containing symbolic links to the ncurses libraries required by some binary-only software which assumes that libtinfo was split off the ncurses libraries.

Joseph

**Comment by chrisroberts** [comment]
Closing since this appears to be resolved. Cheers!
