### ISSUE TITLE
Vagrant on windows 7 failed with embedded gems NameError

### ISSUE THREAD

**Issue by Harihara-Gunda** [hashicorp/vagrant#10703]
### Vagrant version
$ vagrant -v
Vagrant 2.2.4

### Host operating system
Windows 7 64 bit

### Guest operating system
ubuntu

### Expected behavior
Vagrant file creation

### Actual behavior
$ vagrant init ubuntu/xenial64
C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/i18n-1.1.1/lib/i18n/backend/simple.rb:23:in `<module:Implementation>': uninitialized constant I18n::Backend::Simple::Implementation::Base (NameError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/i18n-1.1.1/lib/i18n/backend/simple.rb:22:in `<class:Simple>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/i18n-1.1.1/lib/i18n/backend/simple.rb:19:in `<module:Backend>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/i18n-1.1.1/lib/i18n/backend/simple.rb:4:in `<module:I18n>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/i18n-1.1.1/lib/i18n/backend/simple.rb:3:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/i18n-1.1.1/lib/i18n/config.rb:21:in `backend'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/i18n-1.1.1/lib/i18n.rb:175:in `translate'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/errors.rb:103:in `translate_error'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/errors.rb:72:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/init/command.rb:56:in `exception'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/init/command.rb:56:in `raise'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/init/command.rb:56:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/cli.rb:66:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:292:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:182:in `<main>'

### Steps to reproduce
1.install Vagrant from website msi file
2.open Command prompt and run below command
vagrant init ubuntu/xenial64

**Comment by briancain** [comment]
Hey there @Harihara-Gunda - Which msi did you download, 32-bit or 64-bit? Can you successfully run any other Vagrant commands? Have you tried uninstalling the package and reinstalling it? Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
