### ISSUE TITLE
Vagrant up failing on Centos 7.4

### ISSUE THREAD

**Issue by amrit3327** [hashicorp/vagrant#10708]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Vagrant 2.2.4

### Host operating system
Centos 7.4
### Guest operating system
Centos 7.1
### Vagrantfile
Vagrantfile

```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
`# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "bento/centos-7.1"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Progress: 90%There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/root/.vagrant.d/boxes/bento-VAGRANTSLASH-centos-7.1/2.2.2/virtualbox/box.ovf", "--vsys", "0", "--vmname", "centos-7.1-x86_64_1551658131512_34614", "--vsys", "0", "--unit", "11", "--disk", "/root/VirtualBox VMs/centos-7.1-x86_64_1551658131512_34614/centos-7.1-x86_64-disk1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /root/.vagrant.d/boxes/bento-VAGRANTSLASH-centos-7.1/2.2.2/virtualbox/box.ovf...
OK.
0%...10%...20%...
Progress state: NS_ERROR_INVALID_ARG
VBoxManage: error: Appliance import failed
VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 957 of file VBoxManageAppliance.cpp

### Expected behavior
It should bring up the machine

### Actual behavior
Progress: 90%There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/root/.vagrant.d/boxes/bento-VAGRANTSLASH-centos-7.1/2.2.2/virtualbox/box.ovf", "--vsys", "0", "--vmname", "centos-7.1-x86_64_1551658131512_34614", "--vsys", "0", "--unit", "11", "--disk", "/root/VirtualBox VMs/centos-7.1-x86_64_1551658131512_34614/centos-7.1-x86_64-disk1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /root/.vagrant.d/boxes/bento-VAGRANTSLASH-centos-7.1/2.2.2/virtualbox/box.ovf...
OK.
0%...10%...20%...
Progress state: NS_ERROR_INVALID_ARG
VBoxManage: error: Appliance import failed
VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 957 of file VBoxManageAppliance.cpp

### Steps to reproduce
1. use this file 
2. vagrant up on Centos 7.4 

``

**Comment by briancain** [comment]
Hey there @amrit3327 - I recommend upgrading your VirtualBox and Vagrant to the latest version and try again. Does this happen with other Vagrant boxes as well? Also after that, please provide the full debug log using a gist so that we can see what might be going wrong. Thanks!

**Comment by amrit3327** [comment]
Hello Team,
I am using latest version of vbox
vboxmanage --version
6.0.4r128413
and for vagrant as well.
vagrant --version
Vagrant 2.2.4
Debug logs vagarant up

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Debug logs vagarant up

Debug logs vagarant up. GitHub Gist: instantly share code, notes, and snippets.
 |

 |

 |




RegardsAps


    On ‎Monday‎, ‎March‎ ‎4‎, ‎2019‎ ‎11‎:‎58‎:‎27‎ ‎AM‎ ‎EST, Brian Cain <notifications@github.com> wrote:  
 
 
Hey there @amrit3327 - I recommend upgrading your VirtualBox and Vagrant to the latest version and try again. Does this happen with other Vagrant boxes as well? Also after that, please provide the full debug log using a gist so that we can see what might be going wrong. Thanks!

**Comment by briancain** [comment]
@amrit3327 - Does this happen with other Vagrant boxes as well? Please provide the full debug log using a gist so that we can see what might be going wrong. Thanks!

**Comment by amrit3327** [comment]
Brian , i have attached the debug logs in previous email.
RegardsAmrit pal Singh

Sent from Yahoo Mail on Android 
 
  On Mon, Mar 4, 2019 at 14:45, Amritpal Singh<amrit_3327@yahoo.com> wrote:    Hello Team,
I am using latest version of vbox
vboxmanage --version
6.0.4r128413
and for vagrant as well.
vagrant --version
Vagrant 2.2.4
Debug logs vagarant up

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Debug logs vagarant up

Debug logs vagarant up. GitHub Gist: instantly share code, notes, and snippets.
 |

 |

 |




RegardsAps


    On ‎Monday‎, ‎March‎ ‎4‎, ‎2019‎ ‎11‎:‎58‎:‎27‎ ‎AM‎ ‎EST, Brian Cain <notifications@github.com> wrote:  
 
 
Hey there @amrit3327 - I recommend upgrading your VirtualBox and Vagrant to the latest version and try again. Does this happen with other Vagrant boxes as well? Also after that, please provide the full debug log using a gist so that we can see what might be going wrong. Thanks!

**Comment by briancain** [comment]
Hi @amrit3327 - we are collaborating on GitHub not email.

https://github.com/hashicorp/vagrant/issues/10708

**Comment by amrit3327** [comment]
https://gist.github.com/amrit3327/9af7e2e474b85d46094d186d41e27f14

Gist logs as asked.

**Comment by briancain** [comment]
Great, thanks @amrit3327 ! So from what I can tell this seems to be an issue with your host machine not having enough space on disk to start up the virtual machine.

https://www.virtualbox.org/ticket/18343

If you clean up the space on disk, you should be able to get around this VirtualBox issue. Thanks for the logs!

**Comment by rzr** [comment]
Shouldn't vagran parse this error message and print human readable message or at least link to troubleshooting page ?

**Comment by LC43** [comment]
uf, :+1:  on that! Lack of space wasn't a issue. Turned out i used the wrong path for new vms and was bad permissions. could use a better error message.
