### ISSUE TITLE
Failed to connect to hashicorp-files.hashicorp.com port 443: Timed out

### ISSUE THREAD

**Issue by BlackmanWhite** [hashicorp/vagrant#10714]
### Vagrant version
Vagrant 2.2.4.

### Host operating system
Windows 10.

### Guest operating system
I want to run "lucid32".

### Debug output
"C:\Users\kosmo>vagrant box add lucid32 http://files.vagrantup.com/lucid32.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'lucid32' (v0) for provider:
    box: Downloading: http://files.vagrantup.com/lucid32.box
    box: Download redirected to host: hashicorp-files.hashicorp.com
    box: Progress: 0% (Rate: 0*/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Failed to connect to hashicorp-files.hashicorp.com port 443: Timed out"

### Expected behavior
Install lucid32 in the machine.

### Actual behavior
It failed to connect to the download source.

### How to reproduce
Execute the command "vagrant box add lucid32 http://files.vagrantup.com/lucid32.box".

### Additional information
Looks like the source is only down for me.

**Comment by briancain** [comment]
@BlackmanWhite - Hey there, it looks like you are using an old box with a deprecated box URL that no longer exists. I recommend removing it and finding a new box on [Vagrant Cloud](https://vagrantcloud.com). Thanks!

**Comment by BlackmanWhite** [comment]
Thank you! I will try!

**Comment by GAjayKumar** [comment]
I am getting below, could you help.

URL: ["https://vagrantcloud.com/hashicorp/precise32"]
Error: Failed to connect to vagrantcloud.com port 443: Timed out
