### ISSUE TITLE
after the upgrade from 2.2.3 to 2.2.4 : fileutils.rb:470:in `rename': No such file or directory @ rb_file_s_rename

### ISSUE THREAD

**Issue by cjfq** [hashicorp/vagrant#10718]
### Vagrant version

2.2.4

### Host operating system
Windows 10

### Guest operating system
Oracle Linux 7.6

### Vagrantfile

```ruby
VAGRANTFILE_API_VERSION  = 2

ENV["LC_ALL"] = "en_US.UTF-8"
ENV["LC_CTYPE"] = "en_US.UTF-8"
VAGRANT_FORCE_COLOR = 1
VAGRANT_DEFAULT_PROVIDER = "Virtualbox"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  @ui = Vagrant::UI::Colored.new

  VAGRANT_DISABLE_RESOLV_REPLACE = 1

  if Vagrant::Util::Platform.windows? then
    VAGRANT_LOG = "info"
    MYHOME = ENV["HOMEPATH"]
    VAGRANT_PREFER_SYSTEM_BIN = 0
    VAGRANT_DISABLE_VBOXSYMLINKCREATE = 0
    plugins = %w( os
                  oscar
                  vagrant-share
                  vagrant-hosts
                  vagrant-vbguest
                  vagrant-cachier
                  vagrant-pe_build
                  vagrant-proxyconf
                  vagrant-auto_network
                  vagrant-norequiretty
                  vagrant-config_builder )
  else
    VAGRANT_PREFER_SYSTEM_BIN = 1
    VAGRANT_DISABLE_VBOXSYMLINKCREATE = 1
    VAGRANT_LOG = "info"
    MYHOME = ENV["HOME"]
    plugins = %w( os
                  oscar
                  vagrant-share
                  vagrant-hosts
                  vagrant-cachier
                  vagrant-pe_build
                  vagrant-proxyconf
                  vagrant-auto_network
                  vagrant-norequiretty
                  vagrant-config_builder )
  end

  plugins.each do |plugin|
    unless Vagrant.has_plugin? plugin
      system "vagrant plugin install #{plugin}"
      _retry=true
    end
  end

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = false
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.enabled   = false
    #config.proxy.enabled   = { apt: false, git: false, docker: false, npm: false, pear: false, svn: false, yum: false }
    #config.proxy.enabled   = { apt: false, docker: false, pear: false, svn: false,  npm: true, git: false, yum: true  }
    #config.proxy.http      = $PROXY
    #config.proxy.https     = $PROXY
    #config.proxy.ftp       = $PROXY
    #config.proxy.no_proxy  = $NO_PROXY
  end

  config.vm.box = 'some-box'

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.enable :yum
    config.cache.enable :gem
    config.cache.auto_detect = true
    config.cache.synced_folder_opts = {
      type: "virtualbox", owner: "vagrant", group: "vagrant"
    }
  end


end

if defined? Oscar
  VAGRANT_DIR = File.dirname(__FILE__)
  #Dir.chdir(VAGRANT_DIR)
  CONFIG_DIR = %w[
    files/vms
  ].map{ |d| File.expand_path(d, VAGRANT_DIR) }
  Vagrant.configure(VAGRANTFILE_API_VERSION, &ConfigBuilder.load(:yaml_erb, :yamldir, CONFIG_DIR)) if defined? Oscar
  #Vagrant.configure('2', &Oscar.run(File.expand_path('../files/vms', __FILE__))) if defined? Oscar
end

```

### Debug output
cant add any box in vagrant, and the missing CreDB.CEF file error due not found in ".vagrant.d/tmp" folder, but actually this file suddenly exist after the error in local folder project inside same of the yaml files folder

### Expected behavior
It should load like the previous version, but after the upgrade from 2.2.3 to 2.2.4 does not work anymore,
already reinstalled 2.2.3 and issue still persist

### Actual behavior

```
$ vagrant box add ~\build\box\OEL76.box --name OEL7X  --force
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'OEL7X' (v0) for provider: 
    box: Unpacking necessary files from: file://C:/Users/username/build/box/OEL76.box
    box: Progress: 100% (Rate: 451M/s, Estimated time remaining: --:--:--)
C:/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:469:in `rename': No such file or directory @ rb_file_s_rename - (C:/Users/username/.vagrant.d/tmp/vagrant-box-add-temp-20190307-2352-1n6qkwc/CredDB.CEF, C:/Users/username/.vagrant.d/tmp/vagrant-box-add-temp-20190307-2352-63z2xw/CredDB.CEF) (Errno::ENOENT)
        from C:/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:469:in `block in mv'
        from C:/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1461:in `block in fu_each_src_dest'
        from C:/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1477:in `fu_each_src_dest0'
        from C:/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1459:in `fu_each_src_dest'
        from C:/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:458:in `mv'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/box_collection.rb:435:in `block in v1_upgrade'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/box_collection.rb:429:in `each'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/box_collection.rb:429:in `v1_upgrade'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/box_collection.rb:128:in `block (2 levels) in add'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/box_collection.rb:470:in `with_temp_dir'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/box_collection.rb:115:in `block in add'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/box_collection.rb:457:in `block in with_collection_lock'
        from C:/Vagrant/embedded/mingw64/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/box_collection.rb:456:in `with_collection_lock'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/box_collection.rb:104:in `add'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/box_add.rb:357:in `box_add'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/box_add.rb:146:in `add_direct'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/box_add.rb:120:in `call'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/Users/username/.vagrant.d/gems/2.4.4/gems/vagrant-pe_build-0.18.2/lib/pe_build/action/pe_build_dir.rb:17:in `call'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/box/command/add.rb:78:in `execute'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/box/command/root.rb:66:in `execute'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/cli.rb:66:in `execute'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:292:in `cli'
        from C:/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:182:in `<main>'

$  git status
On branch develop
Your branch is up to date with 'origin/develop'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        CredDB.CEF
        files/vms/CredDB.CEF

no changes added to commit (use "git add" and/or "git commit -a")
```

### Steps to reproduce
1.  vagrant box add ~\build\box\OEL76.box --name OEL76  --force

### References
N/A

**Comment by briancain** [comment]
Hey there @cjfq - Do you experience this behavior outside of your Vagrantfile? It seems to be using a lot of third party plugins. What if you make a new folder with a minimal Vagrantfile (maybe just with the `config.vm.box` option set only and no extra plugin stuff)? Does it still happen then? Also please provide the full output of running the `vagrant box add` command with the `--debug` flag, preferably a [gist](https://gist.github.com). Thanks!

**Comment by cjfq** [comment]
hi, sure I will try that, for now just adding the debug output, since its very small output due error in early beginning as shown below:

[...]
==> box: Box file was not detected as metadata. Adding it directly...
 INFO interface: output: Adding box 'OEL7X' (v0) for provider:
 INFO interface: output: ==> box: Adding box 'OEL7X' (v0) for provider:
==> box: Adding box 'OEL7X' (v0) for provider: 
 INFO box_add: Downloading box: file://C:/Users/cassio_quaresma/OneDrive/@/pe/build/box/OEL76.box => C:/Users/cassio_quaresma/.vagrant.d/tmp/box086d2341d1ee4812bc033d6ecb20cc826a0b0ca5
 INFO interface: detail: Unpacking necessary files from: file://C:/Users/cassio_quaresma/OneDrive/@/pe/build/box/OEL76.box
 INFO interface: detail:     box: Unpacking necessary files from: file://C:/Users/cassio_quaresma/OneDrive/@/pe/build/box/OEL76.box
    box: Unpacking necessary files from: file://C:/Users/cassio_quaresma/OneDrive/@/pe/build/box/OEL76.box
 INFO downloader: Downloader starting download:
 INFO downloader:   -- Source: file://C:/Users/cassio_quaresma/OneDrive/@/pe/build/box/OEL76.box
 INFO downloader:   -- Destination: C:/Users/cassio_quaresma/.vagrant.d/tmp/box086d2341d1ee4812bc033d6ecb20cc826a0b0ca5
 INFO subprocess: Starting process: ["C:\\PWKit\\Vagrant\\embedded\\mingw64\\bin/curl.EXE", "-q", "--fail", "--location", "--max-redirs", "10", "--verbose", "--user-agent", "Vagrant/2.2.4 (+https://www.vagrantup.com; ruby2.4.4) ", "--continue-at", "-", "--output", "C:/Users/cassio_quaresma/.vagrant.d/tmp/box086d2341d1ee4812bc033d6ecb20cc826a0b0ca5", "file://C:/Users/cassio_quaresma/OneDrive/@/pe/build/box/OEL76.box"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: * Rebuilt URL to: file:///C:/Users/cassio_quaresma/OneDrive/@/pe/build/box/OEL76.box
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1083M  100 1083M    0     0   378M      0  0:00:02  0:00:02 --:--:--  365M
* Closing connection 0
 INFO interface: info:
 INFO interface: detail: Progress: 100% (Rate: 365M/s, Estimated time remaining: --:--:--)
 INFO interface: detail:     box: Progress: 100% (Rate: 365M/s, Estimated time remaining: --:--:--)
    box: Progress: 100% (Rate: 365M/s, Estimated time remaining: --:--:--)DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31997
DEBUG subprocess: Exit status: 0
 INFO interface: info:
 INFO interface: detail:
 INFO interface: detail:     box:
    box:
DEBUG box_collection: Adding box: OEL7X (any provider) from C:/Users/cassio_quaresma/.vagrant.d/tmp/box086d2341d1ee4812bc033d6ecb20cc826a0b0ca5
DEBUG box_collection: Unpacking box into temporary directory: C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1ag6v6q
 INFO subprocess: Starting process: ["C:\\PWKit\\Vagrant\\embedded\\mingw64\\bin/bsdtar.EXE", "-v", "-x", "-m", "-s", "|\\\\|/|", "-C", "C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1ag6v6q", "-f", "C:/Users/cassio_quaresma/.vagrant.d/tmp/box086d2341d1ee4812bc033d6ecb20cc826a0b0ca5"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: x OEL76-disk001.vmdk
DEBUG subprocess: stderr:
x OEL76.mf
x Vagrantfile
x box.ovf
x metadata.json
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31994
DEBUG subprocess: Exit status: 0
DEBUG box_collection: Added box is a V1 box. Upgrading in place.
DEBUG box_collection: Upgrading box in directory: C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1ag6v6q
DEBUG box_collection: Temporary directory for upgrading: C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1rc6mjs
DEBUG box_collection: Copying to upgrade directory: C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1ag6v6q/box.ovf
[ C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1ag6v6q/box.ovf ] [ C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1rc6mjs/box.ovf ]
DEBUG box_collection: Copying to upgrade directory: C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1ag6v6q/CredDB.CEF
[ C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1ag6v6q/CredDB.CEF ] [ C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1rc6mjs/CredDB.CEF ]
DEBUG box_add: Deleting temporary box: C:/Users/cassio_quaresma/.vagrant.d/tmp/box086d2341d1ee4812bc033d6ecb20cc826a0b0ca5
ERROR warden: Error occurred: No such file or directory @ rb_file_s_rename - (C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1ag6v6q/CredDB.CEF, C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1rc6mjs/CredDB.CEF)
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 8 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000004143f08>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x00000000040f8e40>
 INFO warden: Calling IN action: #<PEBuild::Action::PEBuildDir:0x00000000040f8e18>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x00000000040f8d50>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x00000000040f8d50>
 INFO warden: Calling OUT action: #<PEBuild::Action::PEBuildDir:0x00000000040f8e18>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x00000000040f8e40>
C:/PWKit/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:470:in `rename': No such file or directory @ rb_file_s_rename - (C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1ag6v6q/CredDB.CEF, C:/Users/cassio_quaresma/.vagrant.d/tmp/vagrant-box-add-temp-20190308-18644-1rc6mjs/CredDB.CEF) (Errno::ENOENT)
        from C:/PWKit/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:470:in `block in mv'
        from C:/PWKit/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1462:in `block in fu_each_src_dest'
        from C:/PWKit/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1478:in `fu_each_src_dest0'
        from C:/PWKit/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:1460:in `fu_each_src_dest'
        from C:/PWKit/Vagrant/embedded/mingw64/lib/ruby/2.4.0/fileutils.rb:458:in `mv'
[...]

**Comment by briancain** [comment]
Hi @cjfq , have you tried to reproduce this outside of using the oscar plugin? Thanks.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
