### ISSUE TITLE
Vagrant up error on windows 10 pro with bento/ubuntu-16.04

### ISSUE THREAD

**Issue by ankur-fbd** [hashicorp/vagrant#10710]
### Vagrant version
Vagrant 2.2.4

### Host operating system
Microsoft Windows 10 Pro
Version	10.0.15063 Build 15063

### Guest operating system
config.vm.box = "bento/ubuntu-16.04"

### Vagrantfile
Vagrant.configure("2") do |config|

    # Change made - May 13th. Using a box that is available on 
    # hyperv (Windows 10 Pro)  and   VirtualBox (Windows 10 Home)
    # Ubuntu 64 bit
    # config.vm.box = "ubuntu/trusty64"
    config.vm.box = "bento/ubuntu-16.04"

    config.vm.synced_folder "./", "/home/vagrant/workspace"
    config.vm.synced_folder "./scripts", "/home/vagrant/scripts"

    # Ports foward
    # For Docker Deamon
    config.vm.network "forwarded_port", guest: 2375, host: 2375

    # FIXED IP Address => Change this if you have a conflict
    # config.vm.network "private_network", ip: "192.168.50.4"

    # This gets executed for both vm1 & vm2
    config.vm.provision "shell", inline:  "echo 'All good'"
  
    # To use a diffrent Hypervisor create a section config.vm.provider
    # And comment out the following section
    # Configuration for Virtual Box
    # Note for windows 10 Pro users : change the provider to hyperv
    #config.vm.provider :hyperv do |vb|
      # Change the memory here if needed - 2 Gb memory on Virtual Box VM
      #vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "1"]
      # Change this only if you need destop for Ubuntu - you will need more memory
      #vb.gui = false
      # In case you have DNS issues
      # vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    #end
  end

### Debug output
https://gist.github.com/ankur-fbd/8e44cacf3cdde0752107a8f3e769b490

### Expected behavior
Ubuntu VM should have been created

### Actual behavior
An error occurred while executing a PowerShell script. This error is shown below. Please read the error message and see if this is a configuration error with your system. If it is not, then please report a bug.
Script: import_vm.ps1
Error:
Failed to import a virtual machine.
Error Code: 32784

### Steps to reproduce
1. Run powershell with administrator rights
2. vagrant up

**Comment by briancain** [comment]
Hey there @ankur-fbd - this looks to be an issue with the Vagrant box you are using and what version it was built for Hyper-V. You might be on a version that doesn't work with the bento box you downloaded. If you notice in the error message it also says:

```
Script: import_vm.ps1
Error:

Failed to import a virtual machine.

Error Code: 32784
Cause: VM version is unsupported
```

I would recommend trying a different Vagrant box or contacting the Bento folks if you have to use theirs!
This thread might be helpful for you as well: https://github.com/hashicorp/vagrant/issues/10384#issuecomment-439539740

Thanks.
