### ISSUE TITLE
It appears your machine doesn't support NFS

### ISSUE THREAD

**Issue by narasimhulumada** [hashicorp/vagrant#10711]
narasimhulu@PWSLTP079:~/my-project/vendor/geerlingguy/drupal-vm$ vagrant up
/home/narasimhulu/my-project/vendor/geerlingguy/drupal-vm/lib/drupalvm/vagrant.rb:6: warning: Insecure world writable dir /mnt/c in PATH, mode 040777
Bringing machine 'drupalvm' up with 'virtualbox' provider...
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.

**Comment by briancain** [comment]
Hey there @narasimhulumada - It looks like you are using Windows. According to the error message, NFS isn't supported on windows. I recommend trying to sync folders another way. Thanks!
