### ISSUE TITLE
storage_prefix is not defined when using qemu_use_session == true

### ISSUE THREAD

**Issue by rrusinov** [hashicorp/vagrant#10712]
### Vagrant version
Vagrant 2.1.2

### Host operating system
Linux 4.20.11-200.fc29.x86_64 

### Guest operating system
Debian9

### Debug output
https://gist.github.com/rrusinov/8e9ad5fe44596d5ce25a68b8144374bd

### Steps to reproduce
1. set for the libvirt provider lv: lv.qemu_use_session = true
2. add additional storage: lv.storage :file, :path => 'disk.img'
3. start the machine

### Additional Info:
At file **/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_domain.rb +156** the **storage_prefix** is undefined. And if you check the code few lines above line **136**, the **storage_prefix** is set only if  **qemu_use_session** is not true.

**Comment by briancain** [comment]
Hey @rrusinov -

The issue you are running into is with the vagrant-libvirt provider, which is located here: https://github.com/vagrant-libvirt/vagrant-libvirt. Thanks!
