### ISSUE TITLE
Vagrant up fails due to VBoxManage failing with [\"showvminfo\", \"\x00\\x00\\x00...]

### ISSUE THREAD

**Issue by HenryFBP** [hashicorp/vagrant#10722]
Windows 7, Vagrant 2.2.4, VBoxManage 6.0.4r128413, VirtualBox 6.0.4.28413.

[vagrantup_error.log](https://github.com/hashicorp/vagrant/files/2950543/vagrantup_error.log)

[Vagrantfile.txt](https://github.com/hashicorp/vagrant/files/2950549/Vagrantfile.txt)

```
P:\GitHub\...\2019-team-07f>vagrant up
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"]

Stderr:
```

Vagrantfile is attached, as well as an error log.

I've tried:
- Deleting all VMs
- Deleting ~/.vagrant.d/
- Deleting ~/.VirtualBox/
- Installing VirtualBox 5.2.2
- Reinstalling VirtualBox 6.0.4

EDIT: I just got this to fix. Posting this for the sake of documentation. I fixed it by deleting `P:\GitHub\...\2019-team-07f\.vagrant\`!

The `.vagrant/` folder was CORRUPTED. Consider adding something to catch this, as the error was totally cryptic!

**Comment by HenryFBP** [comment]
Posting corrupted `./vagrant/` folder for analysis purposes.

[DOTvagrant.zip](https://github.com/hashicorp/vagrant/files/2950566/DOTvagrant.zip)

**Comment by HenryFBP** [comment]
Steps to reproduce:

1. Copy contents of `DOTvagrant.zip` into a folder, say, `folder/`.
2. Copy `Vagrantfile.txt` into `folder/Vagrantfile`
3. Try `vagrant up`. It should error with a bunch of `\x00\x00\x00(...)`!

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this issue. I have a fix to prevent this error from occurring currently staged and it will be included in the next release.

Cheers!
