### ISSUE TITLE
I can't find the cause of the mistake,/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/tmpdir.rb:86:in `mkdir': No such file or directory @ dir_s_mkdir

### ISSUE THREAD

**Issue by dhailing** [hashicorp/vagrant#10728]
E:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/tmpdir.rb:86:in `mkdir': No such file or directory @ dir_s_mkdir - C:/Users/Public/Documents/Wondershare/CreatorTemp/vagrant-fs-case-sensitive20190312-10060-rikd8k (Errno::ENOENT)
        from E:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/tmpdir.rb:86:in `block in mktmpdir'
        from E:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/tmpdir.rb:132:in `create'
        from E:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/tmpdir.rb:86:in `mktmpdir'
        from E:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/platform.rb:229:in `fs_case_sensitive?'
        from E:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/platform.rb:247:in `fs_real_path'
        from E:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:124:in `initialize'
        from E:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `new'
        from E:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `<main>'

**Comment by briancain** [comment]
Hi @dhailing - Please provide us with the information requested in the [issue template](https://github.com/hashicorp/vagrant/blob/master/.github/ISSUE_TEMPLATE.md). Specifically having your Vagrantfile, the command you ran, and a [gist](https://gist.github.com) log of running the command with the `--debug` flag. Thanks!

**Comment by dhailing** [comment]
@briancain Thank you very much for answering my question, but I have found a solution, I modified VAGRANT_HOME to other directories, the error disappeared.

**Comment by dhailing** [comment]
vagrant box add ubuntu-1604 ubuntu-16.04.box
E:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/tmpdir.rb:86:in `mkdir': No such file or directory @ dir_s_mkdir - C:/Users/Public/Documents/Wondershare/CreatorTemp/vagrant-fs-case-sensitive20190313-6392-7ex8fz (Errno::ENOENT)
        from E:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/tmpdir.rb:86:in `block in mktmpdir'
        from E:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/tmpdir.rb:132:in `create'
        from E:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/tmpdir.rb:86:in `mktmpdir'
        from E:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/platform.rb:229:in `fs_case_sensitive?'
        from E:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/platform.rb:247:in `fs_real_path'
        from E:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:124:in `initialize'
        from E:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `new'
        from E:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `<main>'

@briancain Before executing vagrant box list, an error would be reported. Now the error has disappeared, but it appears in the following commands. I am very sorry, but the error still exists.

**Comment by briancain** [comment]
@dhailing - please provide us with the full output of running `vagrant box add ubuntu-1604 ubuntu-16.04.box --debug`. Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
