### ISSUE TITLE
Long build time when forwarding multiple IP addresses to the same ports

### ISSUE THREAD

**Issue by DJviolin** [hashicorp/vagrant#10729]
I want to forward the guests `192.168.27.240/28` ip addresses with the `8080` and `4433` ports to the same IPs and ports on the host also. This is needed for a bare metal Kubernetes dev environment with MetalLB load balancer, which is creating External-IPs in the `192.168.27.240/28` range.

The issue is that the build time is way slower when I creating port forwarding for the same port multiple times.

### Vagrant version

v2.2.4

### Host operating system

Windows 10.0.17763.316

### Guest operating system

debian/stretch64 v9.8.0

### Vagrantfile

Build time with this Vagrantfile: `12m20.788s`

```ruby
Vagrant.require_version ">= 2.1.1"

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
	config.vm.box = "debian/stretch64"
	config.vm.box_version = "9.8.0"
	config.vm.network :private_network, ip: "192.168.27.100"

	#(240..255).each do |i|
	for i in 240..255
		config.vm.network "forwarded_port", guest_ip: "192.168.27.#{i}", guest: 8080, host_ip: "192.168.27.#{i}", host: 8080, id: "http_#{i}"
		config.vm.network "forwarded_port", guest_ip: "192.168.27.#{i}", guest: 4433, host_ip: "192.168.27.#{i}", host: 4433, id: "https_#{i}"
	end
end
```

Build time without the loop: `2m33.554s`

```ruby
Vagrant.require_version ">= 2.1.1"

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
	config.vm.box = "debian/stretch64"
	config.vm.box_version = "9.8.0"
	config.vm.network :private_network, ip: "192.168.27.100"

	config.vm.network "forwarded_port", guest: 80, guest_ip: "192.168.1.240", host: 80, host_ip: "192.168.1.240", id: "http_240"
	config.vm.network "forwarded_port", guest: 443, guest_ip: "192.168.1.240", host: 443, host_ip: "192.168.1.240", id: "https_240"
end
```

### Debug output

```sh
$ time vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'debian/stretch64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'debian/stretch64' version '9.8.0' is up to date...
==> default: Setting the name of the VM: vagrant-port-forward-error_default_1552401793510_99712
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 4433 (guest) => 4433 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
...
```

### Expected behavior

I expect faster build times (or should I?).

### Actual behavior

Because of the port forwarding placed within a loop, or forwarding multiple IPs WITH the same port, the build time is marginally slower.

### Steps to reproduce

1. `$ time vagrant up`

### References

None that I known of.

**Comment by briancain** [comment]
It does seem a little slower on my windows machine...but not 12 minutes slow. I go from about 44 seconds (no port forwards) to around 4 minutes with all the port forwards you defined. :thinking:

**Comment by DJviolin** [comment]
In your case, it's 5.45x slowdown and my case, it's 7.88x (with two defined ports). I think the type of CPU and backend processes can be a factore too. I still don't feel justified such slowdowns because of lot of ports defined for the same port, but with different IPs. I hope there's a solution for this (or use a shell script with `vboxmanage` after `vagrant up`?).

**Comment by briancain** [comment]
It looks like there's some potential ways we can optimize trying to make port forwards faster in virtualbox. We can at least try that and see how much of a difference it makes.

I should also say that I don't experience the port forward slowdown on linux :( It goes from 30 seconds to about 1 minute which doesn't seem unreasonable, but also I wasn't running it in a VM like I was with windows....

Anyway we can take a look :eyes: Thanks for the report!

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
