### ISSUE TITLE
multi-machine alias

### ISSUE THREAD

**Issue by graingert** [hashicorp/vagrant#10724]
I currently have a vagrantfile configuring a pair of machines: 'master' and 'slave'. I want to be able to rename them to 'leader' and 'follower' without breaking any scripts that use those names. Some sort of alias would be useful here.

**Comment by briancain** [comment]
@graingert - What scripts are you talking about, exactly? How are they using Vagrant guest names? An example would be helpful, thanks!

**Comment by briancain** [comment]
Why can't you just change the Vagrant guest names on your computer?

**Comment by graingert** [comment]
sure, but this is what I want to get around - having to tell people to update their workflow

**Comment by briancain** [comment]
You could just have two guests, but define them like this:

```ruby
 ["guest", "machine"].each do |m|
    config.vm.define m do |v|
      v.vm.box = "hashicorp/precise64"
    end
  end
```

**Comment by graingert** [comment]
I don't see how that would help

**Comment by briancain** [comment]
That is essentially a guest alias. You would have each guest with the exact same configuration. Then you  can choose what name you want for your guest.

**Comment by graingert** [comment]
@briancain but they'd have the same Virtualbox name?

**Comment by chrisroberts** [comment]
Hi there,

Responding to the initial issue feature request around being able to alias existing guests, this is not an enhancement that we would be including within Vagrant core. While I can understand the use case for it, it introduces quite a bit of overhead (with easy potential of confusion). 

Cheers!
