### ISSUE TITLE
`vagrant up` throws `undefined method 'downcase' for nil:NilClass`

### ISSUE THREAD

**Issue by Lavode** [hashicorp/vagrant#10733]
### Vagrant version

```
› vagrant -v
Vagrant 2.2.4

› ruby -v
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
```

### Host operating system
Arch Linux, Kernel `5.0.0`

### Guest operating system
Debian 9 (via `debian/contrib-stretch64` `v9.8.0`)

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'debian/contrib-stretch64'

  config.vm.define 'test' do |cfg|
  end
end
```

### Debug output
https://gist.github.com/Lavode/3f1a260c654146b931839275eb1d670f

### Expected behavior
Vagrant should spawn the machine - or provide a useful error message if something goes wrong.

### Actual behavior
Exception thrown within `net-sftp` library.

### Steps to reproduce
1. `vagrant up`

### Notes
- Downgrading to vagrant `2.2.3` fixed the issue.

**Comment by ssherman** [comment]
I'm having the exact same issue since upgrading

**Comment by ssherman** [comment]
here's debug log of a very single ubuntu vagrant that fails
`Vagrant.configure("2") do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.network :private_network, ip: '33.33.33.25'


  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '2048'
  end
end`

https://gist.github.com/ssherman/ae3d91bd2e0d04e4f30049f373a5ed97

**Comment by chrisroberts** [comment]
The origin of the error is quite odd. It's happening while the net-sftp library is loading, however since the sftp upload option was never used (since it required as many manual steps as the required scp updates) we can just remove the loading.

**Comment by GabLeRoux** [comment]
I had to downgrade to 2.2.2 too because of this issue. Here's how to install `2.2.2` on macos:

```bash
cd /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/
git log master -- Casks/vagrant.rb
# this will give you the hash of the 2.2.2 version
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/51a87e70b29adb6efc9f85c54b1f6c163955c0ae/Casks/vagrant.rb
```

:v: Thanks
