### ISSUE TITLE
ACCESSING WEB SERVER (NGINX) USING PUBLIC IP

### ISSUE THREAD

**Issue by r00nscapenab** [hashicorp/vagrant#10739]
![image](https://user-images.githubusercontent.com/24377641/54575706-1ef88580-4a30-11e9-8447-5ab96f485aec.png)

**Comment by briancain** [comment]
Hello @r00nscapenab - I recommend reading the documentation on how to create public networks in Vagrant: https://www.vagrantup.com/docs/networking/public_network.html

Creating a public network with a port forward like:

```ruby
config.vm.network "public_network", ip: "192.168.0.17"
config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "192.168.0.17"
```

Should work. If you just have questions I recommend mailing the Vagrant up mailing list. Thanks!

**Comment by r00nscapenab** [comment]
@briancain hello sir, I have indeed tried that, you can see it above... Is there anyway to put it to port 80? so I could acccess it just like this: 202.137.X.X (without the port)

**Comment by r00nscapenab** [comment]
@briancain <https://github.com/briancain> hello sir, I have indeed tried
that, you can see it above... Is there anyway to put it to port 80? so I
could acccess it just like this: 202.137.X.X (without the port)

**Comment by briancain** [comment]
Hi @r00nscapenab - You should be able to just change the value of the forwarded port if you want it to be 80 instead.
