### ISSUE TITLE
mac下用vagrant up 成功启动虚拟机，在virtualBox管理页面里面，看不到虚拟机

### ISSUE THREAD

**Issue by maiguangyang** [hashicorp/vagrant#10746]
mac下用vagrant up 成功启动虚拟机，在virtualBox管理页面里面，看不到虚拟机

![image](https://user-images.githubusercontent.com/22783048/54734003-ea273280-4bd7-11e9-8f52-4b75879d89ba.png)

**Comment by briancain** [comment]
Hello @maiguangyang - Your virtual machine should exist inside the VirtualBox GUI. When you open an issue on our repository on GitHub, there is an issue template which asks for certain information. Without that it is very difficult for us to assist you and help solve your problem. If you could, please fill out the template so we can get more information about what you have tried. Thanks!
