### ISSUE TITLE
failing to install any vagrant plugin

### ISSUE THREAD

**Issue by visibilityspots** [hashicorp/vagrant#10743]
### Vagrant version
```$ vagrant --version```
``` Vagrant 2.2.4 ```

### Host operating system
```Arch Linux```

### Debug output

https://gist.github.com/visibilityspots/ede24eba7aee0aa5c71f1c7b72dcda21

### Expected behavior
Successful installation of any vagrant plugin

### Actual behavior
The installer failed on
``` /usr/lib/ruby/2.6.0/rubygems/uninstaller.rb:264:in `remove': uninitialized constant Gem::RDoc (NameError)```

**Comment by briancain** [comment]
Hi there @visibilityspots - do you have a lot of other vagrant plugins installed at the moment? You could try running `vagrant plugin expunge` to remove everything, and then try to re-install the plugin to see if that fixes anything.

**Comment by visibilityspots** [comment]
hi @briancain there are no plugins installed.. Already expunged everything.

**Comment by visibilityspots** [comment]
after swiping everything related to vagrant and lxc before completely reinstalling both I could install the plugins I needed again.

**Comment by attila123** [comment]
I also ended up uninstalling the vagrant distro package, deleting /opt/vagrant and ~/.vagrant.d (this will of course delete all your plugins and boxes, etc.) and re-installing vagrant (from distro package).
