### ISSUE TITLE
Vagrant VMs are not functional if the laptop lid is closed for sometime.

### ISSUE THREAD

**Issue by nshahn** [hashicorp/vagrant#10750]
### Expected behavior
I did vagrant up. All the VMs were in running state. I was able to access my local env url. Then i closed my laptop lid and came home from office. After coming home, when i opened laptop, all the vm's were still running, but i could not access my local env url.

I did vagrant --provision reload but it did not work either.

I had to destroy vagrant and do vagrant up again but it is a wate of time.

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by briancain** [comment]
Hey there @nshahn - When you close your laptop, it might be going to sleep and losing networking and or suspending your virtual machines. This is a setting that you can configure in your operating system, and is not related to Vagrant at all. A reload should bring up the vms properly, but not being able to reach whatever your local env url might have something to do with your app. How are you determining that you can't access your local env url?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
