### ISSUE TITLE
vagrant ssh line endings in variable

### ISSUE THREAD

**Issue by janw-me** [hashicorp/vagrant#10759]
- Vagrant version 2.2.4
- Ubuntu 18.10 
- [VVV 2.4.0](https://github.com/Varying-Vagrant-Vagrants/VVV/releases/tag/2.4.0)
- [default Vagrantfile](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/2.4.0/Vagrantfile)

### Debug output
[vagrant ssh -c'head -n2 /etc/hosts' --debug](https://gist.github.com/janw-me/3d9b00b437dbb6a6dcd4e1823f227461)

### Expected behaviour
I tried to get some data from within Vagrant. And set this as a variable.
This problem happens with every command. But for the test case I'm tying to get the first 2 lines from the host file.

### Actual behaviour
Only the last line of the string is in the variable. I guess. I don't really understand this myself.

### Steps to reproduce
run `$ vagrant ssh -c'head -n2 /etc/hosts'` shows the first 2 lines of hosts.
So far so good.
```
127.0.1.1	vvv	vvv
127.0.0.1 localhost
```

run `$ VARIABLE="$(vagrant ssh -c'head -n2 /etc/hosts')"; echo ${VARIABLE}`
Shows only the 2nd line.
```
127.0.0.1 localhost
```

run `$ VARIABLE="$(vagrant ssh -c'head -n2 /etc/hosts' | cat -v)"; echo ${VARIABLE}`
```
127.0.1.1 vvv vvv^M 127.0.0.1 localhost^M
```

![image](https://user-images.githubusercontent.com/1026882/55076924-df1c4880-5096-11e9-89b9-9377d28ca69b.png)

I don't really understand what is happening here.  
Maybe this is normal expected behaviour.  
How can I format the output to use this multiline into a variable?

**Comment by briancain** [comment]
Hey there @janw-me - This looks to be an issue with bash. You need to quote the variable you are echoing, otherwise it doesn't show everything:

```
vagrant@vagrant:~/test$ VARIABLE="$(vagrant ssh -c 'head -n2 /etc/hosts' ubuntu)"; echo ${VARIABLE}
Connection to 127.0.0.1 closed.
 127.0.0.1 local.vm
vagrant@vagrant:~/test$ VARIABLE="$(vagrant ssh -c 'head -n2 /etc/hosts' ubuntu)"; echo "${VARIABLE}"
Connection to 127.0.0.1 closed.
127.0.0.1 localhost
127.0.0.1 local.vm
```

Thanks!

**Comment by janw-me** [comment]
That might looks like it works, but does not always/
Because once I start appending data after the echo it overrides part of the output of the variable
run `$ VARIABLE="$(vagrant ssh -c 'head -n2 /etc/hosts')"; echo "${VARIABLE}"appending`

```
127.0.1.1	vvv	vvv
appending localhost
```

![image](https://user-images.githubusercontent.com/1026882/55168615-68a14880-5173-11e9-8487-66bf593e6b36.png)

**Comment by briancain** [comment]
Hi @janw-me - I seem to get that behavior too, but it's not a Vagrant bug. It's just something with Bash it looks like. I'm not an expert in bash, but you can reproduce this behavior outside of Vagrant using the same ssh command it uses:

```
vagrant@vagrant:~/test$ VARIABLE=$(/usr/bin/ssh vagrant@127.0.0.1 -p 2222 -o LogLevel=FATAL -o Compression=yes -o DSAA
uthentication=yes -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /home/vagrant/t
est/.vagrant/machines/ubuntu/virtualbox/private_key -t "bash -l -c 'head -n2 /etc/hosts'")
Connection to 127.0.0.1 closed.
vagrant@vagrant:~/test$ echo "${VARIABLE}"
127.0.0.1       localhost
127.0.1.1       vagrant.vm      vagrant
vagrant@vagrant:~/test$ echo "${VARIABLE}"append
127.0.0.1       localhost
append1.1       vagrant.vm      vagrant
```
