### ISSUE TITLE
Enhancement: Don't require perfect syntax in Vagrantfile in order to vagrant destroy

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10779]
When debugging complicated boxes, it is more helpful to allow `vagrant destroy` to proceed regardless of the validity of the `Vagrantfile`, so that a bad box can be cleaned up and the programmer can continue to work on the Vagrantfile. Currently, `vagrant destroy` borks when there is any kind of error with the `Vagrantfile`.

**Comment by briancain** [comment]
Hey there @mcandre - I recommend simply moving outside of your working directory and destroying using the global id obtained from `vagrant global-status` instead. The issue with adding a feature like this is that Vagrant really needs to parse your Vagrantfile to determine all of the right context for your working environment. It would be difficult to know when to "stop" parsing and attempt to work with a broken context. There's also a chance that if your guest is really beyond parsing, it might not even exist to Vagrant if you ignore syntax. Thanks!
