### ISSUE TITLE
Vagrant does not catch: VT-x/AMD-V hardware acceleration is not available on your system

### ISSUE THREAD

**Issue by eamanu** [hashicorp/vagrant#10777]
### Vagrant version
Vagrant 2.2.4

### Host operating system
Linux debianPC 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

### Guest operating system
bento/Ubuntu18.04

### Expected behavior
I am new using vagrant and I have this problem. Please, close this issue if is not appropriate. 

The VT-x/AMD-V error should appear on command line. 

### Actual behavior
When SVM on my BIOS is disabled, VBox get the next error:

>  VT-x/AMD-V hardware acceleration is not available on your system. Certain guests (e.g. OS/2 and QNX) require this feature and will fail to boot without it

But vagrant doesn't say me anything.

**Comment by briancain** [comment]
Hello! Do you have a debug log showing the behavior at all? Is it something Vagrant is ignoring, or does it show up, just in a stack trace? Thanks!

**Comment by kikitux** [comment]
@eamanu Hello

So, if you have a VM that is 32 bits, it will just work, with or without VT enabled.

Now, if you want to use a 64 bits VM, its a pre-requirement to have AMD VT enabled.

Vagrant is just a wrapper, will do the best to run the commands, however if the pre-requirements are not met, then it get very hard for vagrant to check this before hand.

similar to when VT is enabled, but Virtualbox can't use it, say on Windows machine with HyperV enabled.

I am sorry for the inconvenience.

Alvaro.

**Comment by eamanu** [comment]
Hi @kikitux, 

Thanks for your response and sorry for the delay of me. 

> Vagrant is just a wrapper, will do the best to run the commands, however if the pre-requirements are not met, then it get very hard for vagrant to check this before hand.

Thanks for the clarification. I was thinking about catch the message of Virtual Box, this way Vagrant doesn't need check the pre-requirements. BTW, I don't know if that is possibly, so just is an idea. 

Thanks!

**Comment by chrisroberts** [comment]
@eamanu We have discussed detecting error messages like this previously, however, the issue is that the format and content of logging information isn't guaranteed in any way to be consistent from one version to the next which makes it very error prone. We might circle back around to it again, but that is why what you are describing hasn't been implemented at this point.
