### ISSUE TITLE
Vagrant options, feature request enhancement

### ISSUE THREAD

**Issue by wolfpackmars2** [hashicorp/vagrant#10783]
### Vagrant version
Vagrant 2.2.4

### Host operating system
Linux Mint 18.3

### Guest operating system
Ubuntu 18.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/bionic64"
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.hostname = "MyHost"

  config.vm.synced_folder "/salt/prod", "/srv/salt"
  config.vm.synced_folder "/config", "/etc/salt/minion.d"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 4
  end

  config.vm.provision :shell, inline: "touch /root/vagrantvm"
  config.vm.provision :shell, path: "bootstrap.sh"

end
```

1) request - add ability to restart the vm during provisioning
2) request - add ability to declare or include plugins with the Vagrantfile
3) request - set default of vagrant snapshot pop to NOT delete the snapshot

Discussion for/against?

There are work arounds for 1 and 2. #1 requires installation of a plugin. #2 is not currently possible without third party tools (bindler).

https://stackoverflow.com/questions/19492738/demand-a-vagrant-plugin-within-the-vagrantfile
https://superuser.com/questions/1338429/how-do-i-reboot-a-vagrant-guest-from-a-provisioner

**Comment by briancain** [comment]
Hi there @wolfpackmars2 - Thanks for opening an issue.

> 1. request - add ability to restart the vm during provisioning

This exists for windows guests, and there's an open issue to support linux guests too:

https://github.com/hashicorp/vagrant/issues/10753

> 2. request - add ability to declare or include plugins with the Vagrantfile

You can do this today with the `config.vagrant.plugins` setting:

https://www.vagrantup.com/docs/vagrantfile/vagrant_settings.html#config-vagrant-plugins

> 3. request - set default of vagrant snapshot pop to NOT delete the snapshot

In this case pop is behaving as expected. The push and pop operations save and delete snapshots on a stack. Traditionally with that data structure when you 'push' something onto a stack, it adds it to that data structure. When you 'pop', it removes that element from the stack. Changing that to operate differently from that would be more confusing as "pop" and "push" have very specific meanings.

If you want to keep the snapshot around, that is what `vagrant snapshot restore` is for. If you want to restore from a specific snapshot that you `push`ed into the stack, you should be able to run the `vagrant snapshot restore` command and provide the snapshot name.

Thanks!

**Comment by wolfpackmars2** [comment]
> > 3. request - set default of vagrant snapshot pop to NOT delete the snapshot
> 
> In this case pop is behaving as expected. The push and pop operations save and delete snapshots on a stack. Traditionally with that data structure when you 'push' something onto a stack, it adds it to that data structure. When you 'pop', it removes that element from the stack. Changing that to operate differently from that would be more confusing as "pop" and "push" have very specific meanings.
> 
> If you want to keep the snapshot around, that is what `vagrant snapshot restore` is for. If you want to restore from a specific snapshot that you `push`ed into the stack, you should be able to run the `vagrant snapshot restore` command and provide the snapshot name.

Makes sense. I was sort of wondering why the command was called 'pop'. The example use case given in the documentation for using push\pop leads me to believe it would be common for someone to want to keep the  snapshot around.

Maybe instead of an error message when not specifying a snapshot name for save/restore a default is used instead. `vagrant snapshot save/restore` would create/restore a snapshot called "default".

I imagine people use their vagrants to try something out, then wipe it clean, try something else, wipe again... My particular use case is developing infrastructure using SaltStack. When working on states, I want to start with a clean build to make sure the states will work for provisioning new machines.

**Comment by briancain** [comment]
Hi @wolfpackmars2 - I see what you mean about default named snapshots with the `save` subcommand. I think in this case, that is what `push` is for. It gives you a default name. And then you should be able to just simply use `restore` back to your original state from push if you want to keep that snapshot on the stack around. Hopefully that makes more sense!
