### ISSUE TITLE
Vagrant destroy does not clears up VMware Fusion Library

### ISSUE THREAD

**Issue by vikas027** [hashicorp/vagrant#10797]
### Vagrant version
```
🍺  ~$ vagrant -v
Vagrant 2.2.4
🍺  ~$ 
```

### Host operating system
OSX 10.14.3 (18D109)

### Guest operating system
CentOS 7 x86_64

### Vagrantfile
```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'
Vagrant.configure('2') do |config|
  config.vm.box = 'centos7_base'
  config.vm.define 'node1' do |node1|
    node1.vm.hostname = 'vikas027.example.com'
    node1.vm.provider :vmware_desktop do |v|
      v.gui = true
    end
  end
end
```

### Expected behavior
Vagrant destroy should clean up the images from VMware Fusion (`Professional Version 11.0.3 (12992109)`) library

### Actual behavior
VMs are not removed from the VMware Fusion library
![2019-04-17_02-06-12](https://user-images.githubusercontent.com/6998650/56225831-6e74b480-60b5-11e9-8b04-b125f3c421de.png)

### Steps to reproduce
1. `vagrant up`
2. `vagrant destroy`

**Comment by briancain** [comment]
Hey there @vikas027 - This is due to a limitation for how VMWare Fusion/Workstation currently works. We have requested this feature from them, but currently it's not supported/not possible in a programmatic way. Sorry about that!
