### ISSUE TITLE
bento/ubuntu-17.10 issue with virtualbox-guest-dkms service

### ISSUE THREAD

**Issue by queglay** [hashicorp/vagrant#10795]
### Vagrant version
Vagrant 2.2.4

### Host operating system
macos 10.13.6

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
config.vm.box = "bento/ubuntu-17.10"
config.vm.provision "shell", inline: "sudo apt-get install -y virtualbox-guest-dkms"
```

### Expected behavior
In trying to get a gnome gui working with this bento vagrant box, Im trying to install a few packages required to do that.  I should be able to install vbox guest dkms but I get errors with vbox-add-service.service

### Actual behavior
upon boot, we see the error
Failed to start vboxadd-service.service

### Steps to reproduce
1. vagrant up

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
