### ISSUE TITLE
key "io" is duplicated and overwritten 

### ISSUE THREAD

**Issue by lhorace** [hashicorp/vagrant#10805]
Hello Devs!

A warning is thrown every time vagrant command is called.

```
vagrant-libvirt (0.0.45, global)
vagrant-vbguest (0.17.2, global)
virtualbox (0.8.6, global)
```

### Vagrant version
Vagrant 2.2.4

### Host operating system
ElementaryOS 5.0 (Ubuntu Bionic)

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior
No warning thrown

### Actual behavior
/storage/vagrant/conf.d/gems/2.4.4/gems/virtualbox-0.8.6/lib/virtualbox/com/ffi/util.rb:93: warning: key "io" is duplicated and overwritten on line 107

### Steps to reproduce
1. vagrant plugin install virtualbox
2. vagrant

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:

Not that I know of.

P.S. I wasn't sure if this a community plugin or distributed by hashicorp, please feel free to redirect me to the correct repository if necessary.

Cheers

**Comment by briancain** [comment]
Hi @lhorace - There is no need to install a plugin for the VirtualBox provider. It is packaged by default as a core part of Vagrant. Uninstall that and you should be good to go!
