### ISSUE TITLE
Vagrant not working on Japanese Windows OS - Encoding problem

### ISSUE THREAD

**Issue by JordanJapan** [hashicorp/vagrant#10801]
### Vagrant version
2.2.4

### Host operating system
Windows 8.1 (Japanese)

### Debug output 1
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/childprocess-0.6.3/lib/childprocess/windows/process_builder.rb:43:in `join': incompatible character encodings: Windows-31J and UTF-8 (Encoding::CompatibilityError)

### Debug output 2
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/providers/virtualbox/driver/base.rb:408:in `block in execute': invalid byte sequence in UTF-8 (ArgumentError)

### Description
I'm new to using this and I was following a video online.  However, when I got the step of using vagrant up, I got an encoding error (debug 1).  After looking around, I tried changing command prompt's code page to 65001 from 932.  Unfortunately, a new error occurred (debug 2)

Is there a clean and simple solution to just make it work or even better automatically set the encoding as needed?  Thanks.

**Comment by briancain** [comment]
Hey there @JordanJapan - could you please provide the full output of running `vagrant up --debug` in a [gist](https://gist.github.com/)?  Thanks!

**Comment by JordanJapan** [comment]
Hello.  Thanks for the reply.

When I tried that command a lot of output appeared and I couldn't copy it all.  I was looking for a way to try outputting the entire log to a file, but with command prompt it refuses to do so even with the redirect command.

vagrant up --debug > c:\file.txt

It only copies the first 2 lines of the debug output.  Is there another way to output to a log file in Windows?  Thanks in advance.

**Comment by briancain** [comment]
@JordanJapan - you should be able to do something like....

```
vagrant up --debug 2>&1 | Tee-Object -FilePath ".\vagrant.log"
```

Hopefully that works!

**Comment by JordanJapan** [comment]
Alright.  The above command wasn't working in command prompt, but I installed Power Shell after reading about it and I got a file this time.  Same errors still occur, however.

I attached the .txt file with the complete output.

Thanks for taking the time to help.

[log.txt](https://github.com/hashicorp/vagrant/files/3114694/log.txt)

**Comment by briancain** [comment]
Thanks for the information! I will put this issue in our next milestone so that we can try to fix it in the next release. :heart:

**Comment by voxik** [comment]
Isn't childprocess 1.x the solution?

https://github.com/enkessler/childprocess/pull/134

**Comment by soapy1** [comment]
Hey there, 
thanks for submitting this issue. I've tried to recreate this on a windows 10 machine with no success. It seems like there is some extra support for language encodings that aren't available on windows 8. Closing this issue but if this is still a problem or updating to windows 10 does not resolve this please open a new issue.
