### ISSUE TITLE
[Question] : Why do i need to reboot my host every time i need to boot up vagrant machine

### ISSUE THREAD

**Issue by tbhaxor** [hashicorp/vagrant#10815]
This is in context with #10807 

````
Why do i need to reboot my host every time i need to boot up vagrant machine
````

**Comment by briancain** [comment]
Hi @tbhaxor - Why are you rebooting your host? You shouldn't be if you are just trying to get around the retry messages from ssh in the issue you linked to.

**Comment by tbhaxor** [comment]
What i did is  tried vagrant ssh , the command is exited with code 1 and then i tried to kill all the vbox processes still its not working....

**Comment by tbhaxor** [comment]
The issue is sorted.. Idk how i upgraded my system and also it upgraded virtualbox
