### ISSUE TITLE
[default] VM not created. Moving on...

### ISSUE THREAD

**Issue by runemadsen** [hashicorp/vagrant#1082]
After installing and running my VM for almost a month, Vagrant is now giving me this message when I try to `vagrant resume`. It happened before, and I needed to install the whole box setup again. It's really weird, like Vagrant just forgets about the box.

I'm on OSX 10.6.8.

Any clue?

**Comment by knightsamar** [comment]
I just had the same problem on vagrant 1.7.4 and VirtualBox v5.0.2. This happened abrubptly while I had made no changes to VirtualBox or vagrant installation. The most interesting observation was that the whole **virtualbox** directory inside the vm was completely missing! 

This is the workaround that fixed it:

I copied the files from inside a different *virtualbox* directory of another vagrant vm's **.vagrant** directory, to my vm. Then, I got the VirtualBox machine id of the vm by running 

``
VBoxManage list vms
```

And then put that id inside **id** and **action_provision** files. I didn't change the string before the **:** inside **action_provision** file, but only the id after.

And it works! Except for the problem that now I have to type my password and login as the private key was lost.
