### ISSUE TITLE
Script: start_vm.ps1 Error:  Failed to start VM 'AWX' failed to start.

### ISSUE THREAD

**Issue by zachryall** [hashicorp/vagrant#10821]
### Vagrant version
Vagrant 2.2.4

### Host operating system
Windows 10 Enterprise 1803, build 17134.706

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'hyperv'
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-18.04"

  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

   config.vm.network "public_network", ip: "192.168.0.100"

   config.vm.provider "hyperv" do |h|
     h.memory = 2048
     h.maxmemory = 2048
     h.cpus = 1
     h.vmname = "AWX"
     h.enable_virtualization_extensions = true 
   end

   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install ansible -y
   SHELL
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: start_vm.ps1
Error:

Failed to start VM 'AWX' failed to start.

Synthetic SCSI Controller (Instance ID 8CA29255-D5B0-4402-98C2-74D85A88A665): Failed to Power on with Error 'The process cannot access the file because it is being used by another process.'.

Attachment 'C:\Users\DR25721\Desktop\Vagrant\AWX\.vagrant\machines\default\hyperv\Virtual Hard Disks\ubuntu-18.04-amd64.vhdx' failed to open because of error: 'The process cannot access the file because it is being used by another process.'.

'AWX' failed to start. (Virtual machine ID AAB7A85F-401A-4395-9EF0-8E7D743FF3FA)

'AWX' Synthetic SCSI Controller (Instance ID 8CA29255-D5B0-4402-98C2-74D85A88A665): Failed to Power on with Error 'The process cannot access the file because it is being used by another process.' (0x80070020). (Virtual machine ID AAB7A85F-401A-4395-9EF0-8E7D743FF3FA)

'AWX': Attachment 'C:\Users\DR25721\Desktop\Vagrant\AWX\.vagrant\machines\default\hyperv\Virtual Hard Disks\ubuntu-18.04-amd64.vhdx' failed to open because of error: 'The process cannot access the file because it is being used by another process.' (0x80070020). (Virtual machine ID AAB7A85F-401A-4395-9EF0-8E7D743FF3FA)

### Expected behavior
Ubuntu vm should have started

### Actual behavior
Produced the above error when running the start_vm.ps1 script

### Steps to reproduce
1. Run vagrant up --provider hyper-v
2. Select switch
3. Error

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-5101
- https://github.com/hashicorp/vagrant/issues/5101#issuecomment-68613793

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by zachryall** [comment]
https://gist.github.com/zachryall/7c4289acfd55e3a344208a68e8ed06a8

**Comment by briancain** [comment]
@zachryall - Is this happening when a virtual machine already exists, or are you bringing up a brand new virtual machine?

Alternatively, are you running your virtual machines on an external hard drive? This post makes me think perhaps it was on a drive that had been removed: https://mesysad.wordpress.com/2016/07/18/hyper-v-vm-failed-to-start-synthetic-scsi-controller-instance-id-the-system-cannot-find-the-file-specified/
