### ISSUE TITLE
Fedora 30 Vagrant rpm packages need to be updated to use libcrypt.so.2

### ISSUE THREAD

**Issue by briancain** [hashicorp/vagrant#10830]
### Vagrant version

2.2.4

### Host operating system

Fedora 30

### Guest operating system

N/A

### Vagrantfile

N/A

### Debug output

```
[vagrant@fedora30 ~]$ vagrant --debug
ruby: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```

### Expected behavior

No ruby error

### Actual behavior

Ruby error for any command run

### Steps to reproduce
1. Install rpm on Fedora 30
2. Run any Vagrant command
3. See results

### References

N/A

**Comment by G-DeKoker** [comment]
Hello, I have the same issue with fedora V30. I have downloaded the last binary for "linux" from the website, and when i want to run it  i get this : 
```TestServer ../vagrant
/tmp/.mount_vagranPTiB6r/usr/bin/ruby2.4: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
/tmp/.mount_vagranPTiB6r/usr/bin/ruby2.4: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
```
From what i have found digging, fedora no-longer include libcrypt.so.1, but only libcrypt.so.2
```ls -al /usr/lib/libcrypt*    
lrwxrwxrwx. 1 root root      19 16 avril 15:07 /usr/lib/libcrypto.so.1.1 -> libcrypto.so.1.1.1b
-rwxr-xr-x. 1 root root 4053752 16 avril 15:08 /usr/lib/libcrypto.so.1.1.1b
lrwxrwxrwx. 1 root root      17 15 mars  12:29 /usr/lib/libcrypt.so.2 -> libcrypt.so.2.0.0
-rwxr-xr-x. 1 root root  271632 15 mars  12:29 /usr/lib/libcrypt.so.2.0.0
```

**Comment by apanteleev-roox** [comment]
Hello, I have the same issue with fedora too.
`$ vagrant up
ruby: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory
`
`$ rpm -ql vagrant | grep libcrypt
/opt/vagrant/embedded/lib64/libcrypto.a
/opt/vagrant/embedded/lib64/libcrypto.so
/opt/vagrant/embedded/lib64/libcrypto.so.1.1
/opt/vagrant/embedded/lib64/pkgconfig/libcrypto.pc
`
vagrant.x86_64  1:2.2.4-1 

on version vagrant-2.2.4-2.fc30.noarch all work correctly

**Comment by briancain** [comment]
Hey all: I've created a pull request that resolves this issue on Fedora 30: https://github.com/hashicorp/vagrant-installers/pull/149

Its fix should be out in the next release of Vagrant (version 2.2.5), which should be coming soon. Thanks!
