### ISSUE TITLE
Add link to the vagrant upload command in toc

### ISSUE THREAD

**Issue by rgl** [hashicorp/vagrant#10837]
Can you please include a link to https://www.vagrantup.com/docs/cli/upload.html in the toc (the left handside of the page that lists all cli commands) https://www.vagrantup.com/docs/cli/?

Do you known why there isn't a `download` command?

**Comment by chrisroberts** [comment]
@rgl Thanks for pointing this out. 

And I was actually thinking about how there should be a `download` command to complement `upload` not too long ago. I'll see if I can whip up PR for it shortly.
