### ISSUE TITLE
vagrant up Ubuntu Disco Dingo (19.04) Netplan 

### ISSUE THREAD

**Issue by midikem** [hashicorp/vagrant#10836]
Hi!

I am using Vagrant 2.2.4 on Linux Mint host. I am trying to get Ubuntu Disco Dingo (19.04) up and running with vagrant, but it fails on networking stuff on vagrant up phase! 

`==> ubuntu_disco_dingo: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mv -f '/tmp/vagrant-network-entry-1557299847' '/etc/netplan/50-vagrant.yaml'
chown root:root '/etc/netplan/50-vagrant.yaml'
chmod 0644 '/etc/netplan/50-vagrant.yaml'
netplan apply

Stdout from the command:

Stderr from the command:

Traceback (most recent call last):
  File "/usr/sbin/netplan", line 23, in <module>
    netplan.main()
  File "/usr/share/netplan/netplan/cli/core.py", line 50, in main
    self.run_command()
  File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command
    self.func()
  File "/usr/share/netplan/netplan/cli/commands/apply.py", line 43, in run
    self.run_command()
  File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command
    self.func()
  File "/usr/share/netplan/netplan/cli/commands/apply.py", line 106, in command_apply
    stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo']' returned non-zero exit status 1.`

If I try to run sudo netplan apply on my guest I get the same problem!

**Comment by briancain** [comment]
Hi there @midikem - I just tried to reproduce this with `generic/ubuntu1904` and `ubuntu/disco64` and both were able to use netplan to set up a private network. Could you please provide us with your Vagrantfile and a link to a debug gist? Thanks

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
