### ISSUE TITLE
InvalidByteSequenceError on vagrant plugin install

### ISSUE THREAD

**Issue by benocms** [hashicorp/vagrant#10845]
### Vagrant version
Vagrant 2.2.4

### Host operating system
Microsoft Windows 10 Home - 10.0.17763 

### Guest operating system
centos/7 - LAST

### Vagrantfile
The error throws on 'vagrant plugin install x'.  The selected plugin does not matter. 
Example: 'vagrant plugin install hostmanager'

### Debug output
https://gist.github.com/benocms/e99b33d6bf32b55fec6b10e12d2aad81

### Expected behavior
A working plugin management.

### Actual behavior
No plugins can be installed.

### Steps to reproduce
1. Install Vagrant on Windows 64bit with Setup
2. Try to run 'vagrant plugin install hostmanager'

**Comment by briancain** [comment]
Hi @benocms - just a quick question: Where does your Vagrant installation live on your windows host? Thanks!

**Comment by benocms** [comment]
Vagrant is installed in: C:\HashiCorp\Vagrant\bin

**Comment by chrisroberts** [comment]
Hi there,

Can you look in your Windows registry for the value at:

`Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\SearchList`

Below is an image of the location of the key in the registry. I do not have this key so it does not show up in the Window, but I believe you will have a key there with the `SearchList` name. Please paste the value here. My guess is that a character in the value is causing the issue.

![resolv-registry-lookup](https://user-images.githubusercontent.com/266674/57737720-84987500-7661-11e9-8d6c-5425c5d9e215.png)

**Comment by benocms** [comment]
Hi, the value of the entry searchList is "9325だ⑂൤蠀�収". 

I have no idea where this value comes from. That makes me a little nervous. I'll run a virus scan.
