### ISSUE TITLE
issues when running the "vagrant up" command after installation.

### ISSUE THREAD

**Issue by bmok** [hashicorp/vagrant#10842]
i get this error right after i run the vagrant up command in command line, what do i do?

`Vagrant failed to initialize at a very early stage:
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.
Path: C
Line number: 144
Message: undefined method 'each' `

**Comment by briancain** [comment]
Hi @bmok - Do you have the Vagrantfile you are using? It just sounds like you have a syntax error. Thanks!

**Comment by mikey-gray** [comment]
I'm seeing this too trying to start the Parcel Homestead box (https://laravel.com/docs/5.8/homestead) on Windows. The Vagrantfile was included in the repo (https://github.com/laravel/homestead/blob/master/Vagrantfile)

**Comment by briancain** [comment]
Hi @mikey-gray - we don't support the homestead Vagrantfile. If you are getting that error with their Vagrantfie I recommend opening an issue with them! Thanks.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
