### ISSUE TITLE
Local box 

### ISSUE THREAD

**Issue by rSetterwall** [hashicorp/vagrant#10857]
I can't add local boxes to vagrant. It worked for me last week but not anymore. I want to open a local .box and repackage it. Visual C++ Redistributable for Visual Studio 2015 is already installed on the system.

### Vagrant version
2.2.4

### Host operating system
Windows 10 Enterprise

### Guest operating system
Ubuntu 18.04

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntuBox"
  config.vm.box_url = "file:///PATH_TO_ubuntuBox"
end

### Debug output
https://gist.github.com/rSetterwall/11aff92827634330d668737f517ded7a#file-gistfile1-txt

### Expected behavior
Be able to enable and run the box with HyperV

### Actual behavior
Couldn't open the .box file

### Steps to reproduce
1. Create new folder
2. Add already downloaded .box file to this folder
3. cd into the folder (using Windows Powershell as admin)
4. Run vagrant init <.box name>
5. Run vagrant up --provider hyperv

**Comment by briancain** [comment]
Hi @rSetterwall - I think the error message is correct, the path you gave is not a valid path on windows. I believe you need to specify the disk drive at the beginning of the path. Something like:

```ruby
config.vm.box_url = "file://C:/Users/you/this/is/a/real/path/ubuntu.box"
```

You can also add boxes directly:

```
vagrant box add <path to box>
```

Let me know if that works for you. Thanks!

**Comment by rSetterwall** [comment]
Hi @briancain thanks for your reply!
I've tried both of these commands with absolute paths and relative paths too. It looks like a parsing error from Vagrant because the error message begins with a / as if starting from the root folder in Linux. 

"Couldn't open file /C:/Users/.../ubuntuBox"

**Comment by briancain** [comment]
Can you show me that the file exists, and then also show a debug log of Vagrant trying to use that file? From the quote it looks like you got it wrong...it needs to be `file://` It's starting with a protocol, not a file path. Thanks!

**Comment by rSetterwall** [comment]
I'll post all of it. The error message after running vagrant up, the contents of the directory and also the contents of the vagrantfile. I've tried shortening the filepath also since I'm running vagrant up from the directory where the .box file is located.


Vagrant log:
PS C:\Users\setterwall\Documents\vagrantTest> vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
==> default: Box 'ubuntuBox' could not be found. Attempting to find and install...
    default: Box Provider: hyperv
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'ubuntuBox' (v0) for provider: hyperv
    default: Unpacking necessary files from: file://C:/Users/setterwall/Documents/vagrantTest/ubuntuBox.box
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/setterwall/Documents/vagrantTest/ubuntuBox.box

Vagrantfile:
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntuBox"
  config.vm.box_url = "file://C:/Users/setterwall/Documents/vagrantTest/ubuntuBox.box"
  config.vm.provider "hyperv"
  config.vm.network "public_network"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = true
    h.linked_clone = true
  end
end

Directory content:
PS C:\Users\setterwall\Documents\vagrantTest> ls


    Directory: C:\Users\setterwall\Documents\vagrantTest


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2019-05-13     11:46                .vagrant
-a----       2019-05-13     10:59    14604663296 ubuntuBox.box
-a----       2019-05-21     15:40            404 Vagrantfile

**Comment by lonemadmax** [comment]
I'm not using vagrant on Windows and don't know how it works internally, but if that's a file URI, shouldn't it be file:///C:/... ? Notice the *three* slashes, I think file://whatever starts a UNC URI, with whatever being the server name.

**Comment by rSetterwall** [comment]
I have tried with one two and three slashes. I've tried with an absolute path and relative path. I can't open a local box on Windows.

**Comment by florentcpt** [comment]
Try to URL encode your path (I had the same issue and solved it this way):

 ```ruby
config.vm.box_url = "file:///C%3A%2FUsers%2Fsetterwall%2FDocuments%2FvagrantTest%2FubuntuBox.box"
```

**Comment by rSetterwall** [comment]
Thanks for the input florentcpt! It doesn't solve my problem unfortunately.

I've tried:
- Absolute and relative path URIs and URLs
- The command "vagrant box add" 
- A minimal vagrantfile and "vagrant up"

This Stackoverflow question addresses my problem and I've tried all of the solutions to no avail.
https://stackoverflow.com/questions/22065698/how-to-add-a-downloaded-box-file-to-vagrant/22091770

It still says "Couldn't open file: <path to file>". The box file should be fine as I'm still able to download and open the box from a server but is there any way I can verify that the box is working?

**Comment by briancain** [comment]
@rSetterwall - Can you show us a debug log with the second thing you had tried, adding the box with `vagrant box add`?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
