### ISSUE TITLE
(Documentation) chef-solo provisioner accepts "common configuration" options

### ISSUE THREAD

**Issue by ciber96** [hashicorp/vagrant#10856]
### Vagrant version
Vagrant 2.2.4

### Host operating system
Windows 10

### Guest operating system
ubuntu/xenial64
ubuntu/trusty64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Production enviorment
  config.vm.define "prod" do |prod|
    prod.vm.box = "production"

    prod.vm.box = "ubuntu/xenial64"

    # prod.vm.network "private_network", ip: "192.168.1.50"
    prod.vm.network "forwarded_port", guest: 8080, host: 3000

    prod.vm.provider "virtualbox" do |vb|
      vb.name = "GO API - Production"
      vb.memory = "512"
    end

    prod.vm.provision "shell", inline: <<-SHELL
    echo -n                                          >  /etc/profile.d/gopath.sh
    echo 'export GOROOT=/usr/lib/go'                 >> /etc/profile.d/gopath.sh
    echo 'export GOPATH=/home/vagrant/go'             >> /etc/profile.d/gopath.sh
    echo 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> /etc/profile.d/gopath.sh
    SHELL

    prod.vm.provision "chef_solo" do |chef|
      chef.run_list = [
        'recipe[git::prod]',
        'recipe[deploy::prod]'
      ]
    end
  end

  # Development Enviorment
  config.vm.define "dev" do |dev|
    dev.vm.box = "development"

    dev.vm.box = "ubuntu/xenial64"

    # dev.vm.network "private_network", ip: "192.168.1.51"
    dev.vm.network "forwarded_port", guest: 8080, host: 3001

    dev.vm.provider "virtualbox" do |vb|
      vb.name = "GO API - Development"
      vb.memory = "512"
    end

    dev.vm.provision "shell", inline: <<-SHELL
    echo -n                                          >  /etc/profile.d/gopath.sh
    echo 'export GOROOT=/usr/lib/go'                 >> /etc/profile.d/gopath.sh
    echo 'export GOPATH=/home/vagrant/go'             >> /etc/profile.d/gopath.sh
    echo 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> /etc/profile.d/gopath.sh
    SHELL
    
    dev.vm.provision "chef_solo" do |chef|
      chef.run_list = [
        'recipe[git::dev]',
        'recipe[deploy::dev]'
      ]
    end
  end
end
```
### Debug output
https://gist.github.com/ciber96/a009d377e65249c507621f80cab60ec0

### Expected behavior
Chef solo should be run and execute my recipes.

### Actual behavior
Chef fails to run outputing: Chef Infra Client cannot execute without accepting the license

### Steps to reproduce
1. vagrant up

### References
-

**Comment by ciber96** [comment]
Doing a manual downgrade to 14.12.9 seems to fix it.

**Comment by exstral** [comment]
Also facing this issue since chef 15.0.293 was released today. How did you manage a manual downgrade? 

Every time I run `vagrant provision` it reinstalls the latest chef again.

**Comment by ciber96** [comment]
@exstral `prod.vm.provision "shell", inline: <<-SHELL
    sudo curl -L https://www.opscode.com/chef/install.sh | sudo bash -s -- -v 14.12.9
    echo -n                                          >  /etc/profile.d/gopath.sh
    echo 'export GOROOT=/usr/lib/go'                 >> /etc/profile.d/gopath.sh
    echo 'export GOPATH=/home/vagrant/go'             >> /etc/profile.d/gopath.sh
    echo 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin' >> /etc/profile.d/gopath.sh
    SHELL
`

**Comment by exstral** [comment]
I want to make it reproducible though with every vagrant up, this solution worked for me:

Install the omnibus plugin
`vagrant plugin install vagrant-omnibus`

then add this line to your Vagrantfile
`config.omnibus.chef_version = '14.10.9'`

Taken from here:
https://stackoverflow.com/questions/11325479/how-to-control-the-version-of-chef-that-vagrant-uses-to-provision-vms

**Comment by briancain** [comment]
Hey all - It looks like there's a way to install a specific version, but it looks like it was never actually hooked up with the chef-solo provisioner. I also noticed that apparently this very important page on how to use the provisioners is buried in the docs instead of a link on the nav bar: https://www.vagrantup.com/docs/provisioning/chef_common.html

I just tried to use the version option and it looks like Vagrant ignored it. If I manually go in and change the version myself it seems to install the right version...so the fix shouldn't be too bad :crossed_fingers: 

I'll mark this as an enhancement to get this all cleaned up. Thanks for the report!

**Comment by briancain** [comment]
Oops, sorry. I had an extra `"chef_solo"` provisioner in my config and that's why I saw that behavior. SO I was wrong, it is already hooked up and working. Something like this should work:

```ruby
 chef.vm.provision :chef_solo do |c|
      c.add_recipe "test"
      c.version = "14.12.9"
    end
```

```
==> chef: Running provisioner: chef_solo...
    chef: Installing Chef (14.12.9)...
```

I'll try to make a PR to make those docs more discoverable though.

**Comment by sharavanan2010** [comment]
Hi Team

I'm also facing the same issue, even if I lock the chef version in Vagrantfile, latest version of chef only installed in the machine.

**Vagrantfile Config for Chef-Solo:**
#config.omnibus.chef_version = :latest
config.omnibus.chef_version = '14.12.9'
config.vm.provision "chef_solo" do |chef|
#chef.arguments = "chef-license=accept"
chef.version = "14.12.9"
chef.cookbooks_path = "C:\\devstack\\windows_10_client_pro_rs4_64_eng_vmware\\cookbook\\test"
chef.add_recipe "test"
chef.json = {
    "devstack" => {
      "JFROG_ARTIFACTORY_URL" => "https://artifactory-jfrog.com",
      "JFROG_ARTIFACTORY_API_KEY" => "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  }
end

**knife --version from machine**
![image](https://user-images.githubusercontent.com/39905551/57718042-1623d900-769a-11e9-8866-e0a27c03f33b.png)

**Console Message:**
==> default: Installing Chef 14.12.9 Omnibus package...
==> default: Downloading Chef 14.12.9 for Windows...
==> default: Installing Chef 14.12.9
==> default: Running provisioner: chef_solo...
    default: Installing Chef (14.12.9)...
Vagrant could not detect Chef on the guest! Even after Vagrant
attempted to install Chef, it could still not find Chef on the system.
Please make sure you are connected to the Internet and can access
Chef's package distribution servers. If you already have Chef
installed on this guest, you can disable the automatic Chef detection
by setting the 'install' option in the Chef configuration section of
your Vagrantfile:

    chef.install = false

**Comment by briancain** [comment]
@sharavanan2010 - That issue doesn't look related at all. It looks like it's installing the version you specified in the console message you shared. I recommend opening a new issue and provide the information requested in the new issue template, including a full debug log with the `--debug` flag.

**Comment by briancain** [comment]
@sharavanan2010 - also you're talking about chef, but you are looking at a different tool knife in your screenshot. If vagrant-omnibus is installing that, then you should open an issue with them.

**Comment by sharavanan2010** [comment]
@briancain Thanks for your quick response. How to check installed chef details?

I see this Cap:
https://github.com/hashicorp/vagrant/blob/v2.0.2/plugins/provisioners/chef/cap/windows/chef_installed.rb. 
From this logic, "knife --version" command is used to check chef installation status. Correct me if I'm wrong?

Initially we configured to install the latest version of chef,
config.omnibus.chef_version = :latest

From the latest chef release(15.0.293) today, vagrant up got failed and can't go back to working chef version.

**Comment by briancain** [comment]
@sharavanan2010 - It does look like that's the case. Still, I'm not sure how the `vagrant-omnibus` plugin works. I was able to properly install the correct requested version of chef with the `version` option like I mentioned above using the chef-solo provisioner.

```
vagrant@vagrant:~$ knife --version
Chef: 14.12.9
vagrant@vagrant:~$ chef-solo --version
Chef: 14.12.9
```

**Comment by sharavanan2010** [comment]
Thanks @briancain
vagrant-omnibus is the culprit here, even If I lock the version "config.omnibus.chef_version = '14.12.9'", always installing the latest version. Now I have uninstalled vagrant-omnibus and decided to use "chef.version = 14.12.9" property. This is working fine and Chef version is locked.

Thanks a lot :)

**Comment by t--o--m** [comment]
Instead of performing a downgrade of the chef you can programmatically accept the chef license.

Use the custom_config_path parameter in the vagrant chef provisioner to point to a custom Chef configuration file

### Vagrantfile
```
chef.vm.provision :chef_solo do |c|
      ...
      c.custom_config_path = "CustomConfiguration.chef"
      ...     
end
```

and in the custom configuration file add the line to accept the chef license

### CustomConfiguration.chef
`Chef::Config.chef_license = 'accept'`

**Comment by Skullyfox** [comment]
> Instead of performing a downgrade of the chef you can programmatically accept the chef license.
> 
> Use the custom_config_path parameter in the vagrant chef provisioner to point to a custom Chef configuration file
> 
> ### Vagrantfile
> ```
> chef.vm.provision :chef_solo do |c|
>       ...
>       c.custom_config_path = "CustomConfiguration.chef"
>       ...     
> end
> ```
> 
> and in the custom configuration file add the line to accept the chef license
> 
> ### CustomConfiguration.chef
> `Chef::Config.chef_license = 'accept'`

Wonderfull ! it's work, thank you

**Comment by clebio** [comment]
Just 

    config.vm.provision :chef_solo do |chef|
      chef.arguments = "--chef-license accept"

Seems to work as well (no config files needed).
