### ISSUE TITLE
Conflicting dependencies for installing any plugin

### ISSUE THREAD

**Issue by graykevinb** [hashicorp/vagrant#10865]
### Vagrant version
2.2.4

### Host operating system
Fedora 30 Workstation

### Expected behavior
The vagrant-unison plugin should have installed

### Actual behavior
https://gist.github.com/graykevinb/cf83fbd59eee9fbbdef04ffbfdcaa648#file-gistfile1-txt
Similar errors happen when I try to install other plugins.

### Steps to reproduce
This was done on a fresh install of Fedora 30 so I can't think of myself doing anything between the os install and the vagrant install that would cause this. Everything worked fine on Fedora 29.

### Steps I have taken to try fixing it.
I have ran `vagrant plugin repair`, `vagrant plugin expunge`, `vagrant plugin update` reinstalled vagrant with both the package manager and the official version and retried all of the previous commands. And yes I have deleted ~/.vagrant.d/ when reinstalling.

Thanks :)

**Comment by briancain** [comment]
Hey there @graykevinb - Did you install the vagrant package through the Fedora repos, or from vagrantup.com? Thanks!

**Comment by graykevinb** [comment]
Sorry for the late reply. I tried both the package manager and vagrantup.com
version with identical results. Currently the package manager version is
installed but I can switch to the official version for the sake of
debugging.

**Comment by briancain** [comment]
Hi @graykevinb - If I remember correctly, I don't think the Fedora package properly isolates Vagrants plugin gem dependencies at the moment. I recommend installing the official vagrant package. You will likely have to install the `libxcrypt-compat` package however until we can get a release out due to this bug: https://github.com/hashicorp/vagrant/issues/10830 Thanks!

**Comment by graykevinb** [comment]
The problem resolved itself. My best guess is when I updated my computer a bug was fixed because it now works. Again I tried both the fedora package and the official rpm provided by vagrantup.com, and they both work.
