### ISSUE TITLE
Unexpected token at '' (JSON::ParserError)

### ISSUE THREAD

**Issue by andythsu** [hashicorp/vagrant#10863]
### Vagrant version
Vagrant 2.2.4

### Host operating system
Windows 10

### Debug output
https://gist.github.com/andythsu/e7fe6c3411853413252bfee43093ffb0

### Expected behavior
It should run the command without error

### Actual behavior
```
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:156:in `parse': 751: unexpected token at '' (JSON::ParserError)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/json/common.rb:156:in `parse'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/vagrantfile.rb:183:in `machine_config'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/vagrantfile.rb:47:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:717:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/v2/command.rb:186:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/commands/up/command.rb:87:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/cli.rb:66:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:292:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:182:in `<main>'
```

### Steps to reproduce
1. vagrant up runbox

### Notes
I have tried to uninstall vagrant, delete ~/.vagrand.d folder, and install vagrant again. The error still persists

**Comment by briancain** [comment]
Hi there @andythsu - It looks like the debug log you provided does not contain the error mentioned. Do you have the debug log showing the JSON error? Also do you have a Vagrantfile? Thanks.

**Comment by andythsu** [comment]
> Hi there @andythsu - It looks like the debug log you provided does not contain the error mentioned. Do you have the debug log showing the JSON error? Also do you have a Vagrantfile? Thanks.

Hi Brian, the debug log does not show the JSON error unfortunately, and I am not able to provide a vagrant file as it contains sensitive information. Do you really need to see the Vagrantfile?

**Comment by andythsu** [comment]
@briancain Also, I have updated the gist, it should show the JSON error now

**Comment by briancain** [comment]
@andythsu  Have you tried removing the local `.vagrant` directory inside your project directory?

**Comment by andythsu** [comment]
@briancain ya.. I deleted it and re-ran the command. It's proceeding without the error anymore. Hopefully it doesn't happen again. Thank you

**Comment by briancain** [comment]
@andythsu - thanks! Sounds good. Sometimes that file gets corrupted but it isn't really clear how it happens. The best fix is usually just removing it and Vagrant is typically good to go! If it happens again and you figure out how it happens feel free to open another issue.
