### ISSUE TITLE
Is there a way to get vagrant command failure error message?

### ISSUE THREAD

**Issue by sharavanan2010** [hashicorp/vagrant#10887]
### Vagrant version
Vagrant 2.0.2

### Host operating system
Windows Platform  & Mac OS X

### Guest operating system
Windows & Mac

###  Requirement:
We have developed a python application that acts as a wrapper for vagrant commands and used by our internal teams for automation. 
Sometimes we're facing runtime issues during vagrant up command, that maybe because of network failure or SSH or mount or chef provisioning script failure. The return value of vagrant command is just status code as 0 or 1 and we're not getting what is the error message. 

Our requirement is to parse this vagrant command execution and pass to sentry in case of failure. Currently we know the failure by checking return code is not 0. But, we should pass the exception details for analysis.

Is there a way to get this?

**Comment by briancain** [comment]
@sharavanan2010 - if you run in debug mode, you might be able to capture the `ERROR` log lines, if any, during vagrant runs. You should also look at the `--machine-readable` flag, as that should make things easier to parse with other tools. You might also be able to redirect stderr into your tool and capture any error output that way. Hopefully that helps!
