### ISSUE TITLE
qemu-img commit <file.img> breaks ssh

### ISSUE THREAD

**Issue by abetkin** [hashicorp/vagrant#10882]
### Vagrant version
Vagrant 2.2.5.dev
tried with stable (2.2.4) too

### Host operating system
Manjaro linux
Linux ssd 4.19.45-1-MANJARO x86_64

### Guest operating system
generic/ubuntu1904

### Vagrantfile
```ruby
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# CPU and RAM can be adjusted depending on your system
CPUCOUNT = "2"
RAM = "2048"


Vagrant.configure(VAGRANTFILE_API_VERSION) do | config |
 config.vm.provider "libvirt"
 config.vm.synced_folder '.', '/vagrant', type: "rsync",

 config.vm.define "vdihost" do | vdihost |
   vdihost.vm.box = "generic/ubuntu1904"
   vdihost.vm.hostname = "vdihost"

   vdihost.vm.provider "libvirt" do | libvirt |
     libvirt.memory = "2048"
     libvirt.cpus = 2
   end
 end
end
```
### Plugins
vagrant-libvirt

### Expected behavior
Steps to reproduce should finish without error

### Actual behavior
`vagrant up` freezes on "Waiting for SSH to become available..."

### Steps to reproduce
1. `vagrant halt`
2. `sudo qemu-img commit /var/lib/libvirt/images/myproj_vdihost.img`
3. `vagrant destroy -f`
4. `vagrant up`

**Comment by abetkin** [comment]
Some debug info that is probably useful: here `@connection` is `nil`:
https://github.com/hashicorp/vagrant/blob/master/plugins/communicators/ssh/communicator.rb#L361

So `Vagrant::Errors::SSHAuthenticationFailed` in `ready?` function during `connect`

In the regular `vagrant destroy && vagrant up` `@connection` is not `nil`

**Comment by briancain** [comment]
Hi @abetkin - It looks like this is likely an issue with the [vagrant-libvirt](https://github.com/vagrant-libvirt/vagrant-libvirt) provider. I recommend opening an issue with the plugin maintainers there. Thanks!
