### ISSUE TITLE
Hyper-V ( Windows 10 ) IP Address

### ISSUE THREAD

**Issue by benlumia007** [hashicorp/vagrant#10892]
When you `vagrant up --provider=hyperv`, it will begin to launch the vm, and detects an IP Address 

`IP: 172.17.x.x`

Is there a way for me to grab the IP address somewhere and use it in my own Vagrantfile, since it works differently with VirtualBox.

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the Vagrant mailing list. There are many more people who will be able to get you a faster answer there. Thank you and have a great day!

**Comment by benlumia007** [comment]
@briancain 

I feel like when I submitted questions at the google vagrantup... it seems like I've been waiting way too long just to get an answer to what I'm trying to do.  

Please check my message please.
