### ISSUE TITLE
windows_hyperv_enabled?'s Get-WindowsOptionalFeature implementation is broken on Windows 10

### ISSUE THREAD

**Issue by j0j00** [hashicorp/vagrant#10897]
This https://github.com/hashicorp/vagrant/pull/9746#issuecomment-499667036 PR regressed existing functionality which makes hyper-v support on Windows 10 no longer functional.

Details in the PR comment.

The basic gist is that, it currently runs:
```
"$(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"
```` 
when it should be:
```
"$(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hypervisor -Online).State"
```` 

So it silently errors out.

### Vagrant version
2.2.4

### Host operating system
Windows 10

### Guest operating system
Ubuntu 16.04

### Expected behavior
It should boot up the image.

### Actual behavior
Fails to detect hyper-v.

### Steps to reproduce
1. Try to use any hyper-v image e.g. `laravel/homestead`

### References

https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1616

**Comment by briancain** [comment]
Hi @j0j00 - Hyper-V is working fine for me...and has been for a while now. I'm on latest windows 10 with the latest version of Vagrant:

![Screenshot from 2019-06-06 15-04-01](https://user-images.githubusercontent.com/810277/59069624-9dfd9d00-886c-11e9-8116-40015927a171.png)

![Screenshot from 2019-06-06 15-05-57](https://user-images.githubusercontent.com/810277/59069627-a05ff700-886c-11e9-9448-572baafbdac5.png)

Without seeing a debug gist or anything it is hard for us to know what you are running into. Please update the issue with a debug log and we should be able to help. Thanks!

**Comment by j0j00** [comment]
That's really weird. It's basically the same stack-trace as https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1616#issuecomment-494971135

In particular the 
```
Get-WindowsOptionalFeature : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:3
```
line.

I then manually confirmed the behaviour by running the internal process it's attempting:
```
λ powershell -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "$(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"
Get-WindowsOptionalFeature : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:3
+ $(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hyperviso ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WindowsOptionalFeature], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand
```

vs

```
λ powershell -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "$(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hypervisor -Online).State"
Enabled
```

Which echoes out the "Enabled" string just fine.

**Comment by briancain** [comment]
From what I can see in that issue it kind of looks like the user is not running powershell with administrator rights:

```
DEBUG subprocess: stderr: Get-VMHost : You do not have the required permission to complete this task. Contact the administrator of the
authorization policy for the computer 'ANETHERON'.
At line:1 char:7
+ $x = (Get-VMHost).Name; if($x -eq [System.Net.Dns]::GetHostName()){ W ...
+       ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-VMHost], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.GetVMHost

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
```

That was the actual error that caused Vagrant to abort.

The error you are seeing earlier about `Get-WindowsFeature` is not really a halting error, but Vagrant trying _both_ options to detect if Hyper-V is enabled. Windows 10 and Windows Server have different commands to do this check, so we try both. But the log only shows one of them being an error, while the other one succeeds.

**Comment by j0j00** [comment]
I've been running it in admin mode on Powershell, Cmder and Git Bash with roughly the same results.

I think you're right about the `Get-Windows` being a red-herring and not being the actual issue. 
I just destroyed the box and re-ran it without debug mode on (and it gets past that stage just fine).

Do you mind sending me a copy of your test `Vagrantfile` if it's simple enough? It's possible it's a VVV/Homestead issue. I'm running it against the `laravel/homestead` box.

If it is an issue with them, then I can close this issue and scamper off in shame :D

My error is that I can't mount the folder:
```
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o vers=2.0,credentials=/etc/smb_creds_vgt-2ffac0b09531df5da40d58f351b865d3-7ea95653249a1e2fe2fb36329b8abc85,uid=1000,gid=1000 //10.0.75.1/vgt-2ffac0b09531df5da40d58f351b865d3-7ea95653249a1e2fe2fb36329b8abc85 /srv/database
```

When it asks for:
```
default: Username:
default: Password (will be hidden):
```

My powershell admin instance doesn't seem to take in any user input, whereas the other terminals do.
For the username, I take it if my windows username is `Jo Joo <jojoo@example.com>`, I have to enter `Jo Joo`?

**Comment by briancain** [comment]
Yep! It's very simple:

```ruby
  config.vm.define "ubuntu" do |b|
    b.vm.box = "bento/ubuntu-18.04"
    b.vm.provider :hyperv
  end
```

The username you input will probably be whatever folder name is under your home folder at say `C:\Users\<username goes here>`.

I'm guessing that mount error is probably from just getting the credentials wrong? I'm not sure what's going on with your powershell window, but you can also store the username and password inside your Vagrantfile if powershell is being weird. But be aware that the password is your system password.... :sweat_smile:

Also if you are talking about the `Password` field, it does take input, but it hides it completely. It won't show `*****` or anything while you type it...that might be what you are encountering.

**Comment by j0j00** [comment]
Just wanted to say that I really appreciate the responsiveness Brian. Thanks 👍.

It was a credential issue, with me using the wrong username.

My powershell wasn't showing the inputs for both username and password, but it's fine though. I'll handle that later.
