### ISSUE TITLE
Salt Provisioner using older Python w/ Deprecation Warning

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/vagrant#10905]
The `salt-minion` installed by salt provisioner says the `Python 2.7.15+` will be deprecated. 

Maybe to avoid deprecation warnings and avoid loss of functionality in 2020, we can use a different python version?   This is non-urgent, at least until 2020... 

### Vagrant version

```
Vagrant 2.2.4
```

### Host operating system
```
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

### Guest operating system

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.synced_folder './roots/salt/', '/srv/salt'
  config.vm.synced_folder './roots/pillar', '/srv/pillar'

  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.run_highstate = true
    salt.verbose = true
  end
end
```

### Debug output
n/a

### Expected behavior

```
salt-minion 2019.2.0 (Fluorine)
```

and 

```
Python 3.7.3
```

### Actual behavior

```
/usr/lib/python2.7/dist-packages/salt/scripts.py:198: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
salt-minion 2019.2.0 (Fluorine)
```
and

```
Python 2.7.15+
```

### Steps to reproduce
1.  `vagrant up`
2. `vagrant ssh`
3. `salt-minion --version`
3. `python --version`

### References
 n/a

**Comment by briancain** [comment]
Hey there @darkn3rd - This is something that the salt bootstrap shell script sets up, and is not managed by Vagrant. You can write a provisioner prior to your salt provisioner that installs a newer version of Python, but Vagrant isn't actually managing python for you. It looks like [on windows](https://www.vagrantup.com/docs/provisioning/salt.html#python_version) you can pass in a python version flag into the bootstrap script. This kind of exists on their Linux bootstrap script, but they don't seem too confident in it working (directly from their bootstrap script doc):

>  Installs a different python version on host. Currently this has only been tested with CentOS 6 and is considered experimental.

If you check out their bootstrap script it basically only checks if the host is centos and then installs python through an rpm

```shell
echoerror "Installing a repo to provide a python package is only supported on Redhat/CentOS.
                If a repo is already available, please try running script with -r."
exit 1
```

So yeah, I suggest setting up a provisioner prior to your salt script that installs a newer version of Python on your guest for salt to use. Thanks!
