### ISSUE TITLE
Setting network to bridge not working

### ISSUE THREAD

**Issue by shukriadams** [hashicorp/vagrant#10903]
### Vagrant version
2.2.3

### Host operating system
Win10

### Guest operating system
Win10

### Vagrantfile
```ruby
    # -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "playdeadbuildbox"
  config.vm.box_url = "vagrant"
  config.ssh.insert_key = false
  config.vm.network "public_network", bridge: "Intel(R) Ethernet Connection (2) I219-V"

  config.vm.provider "virtualbox" do |v|
    unless File.exist?('disk2.vdi')
      v.customize ['createhd', '--filename', 'disk2.vdi' , '--size', 50 * 1024] # 50 GB
    end
    v.customize ['storageattach', :id, '--storagectl', 'SATA', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', 'disk2.vdi']
  end

end
```

### Debug output
n/a

### Expected behavior
Guest should mount with bridged network adapter

### Actual behavior
Guest should mount swith NAT network adapter

I'm trying to do an atteneded mount of my guest machine with bridged network adapter.  No matter what I do, it either mounts NAT, or I get prompted to select a network adapter. For example, if I specify the name "Intel(R) Ethernet Connection (2) I218-V", the guest mounts normally, but in NAT mode. If I use "Intel(R) Ethernet Connection (2) I219-V", it stops and asks for me to to select an adapter. Both adaptors are listed on VirtualBox. If I used "Hyper-V Virtual Ethernet Adapter", which is also listed in VirtualBox, it mounts silently, but still in NAT mode.

Also, having to specify the exact name of the network adapter is a gigantic pain. It would be a lot easier if Vagrant could be forced to silently select the first card, or a card by index number. I see there are older tickets (https://github.com/hashicorp/vagrant/issues/655) where this has already been raised, and apparently solved, but the current documentation and functionality says otherwise.

**Comment by briancain** [comment]
Hey there @shukriadams - A couple of questions....

How are you determining that your network on the vm is in NAT mode? What network interfaces are available when you run `VBoxManage.exe list bridgedifs`? Also please provide us with the full debug log from running `vagrant up --debug` using the bridged adapter you mentioned that succeeds but is in NAT mode. Thanks!

**Comment by shukriadams** [comment]
Sorry, this turned out to be me not understanding how network devices are bound to VirtualBox VMS. I was expecting the _first_ adapter to be bridged (using VirtualBox's UI to determine this), but now I see the first is reserved for NAT and the 2nd is bridged, and is being bound properly. I still can't reach my guest from the host via the bridged adapter, but I don't think that's a vagrant issue. Closing this ticket, sorry about the confusion.
