### ISSUE TITLE
Vagrant ssh asks password however able to login using usual ssh command

### ISSUE THREAD

**Issue by hrajput89** [hashicorp/vagrant#10904]
Hi Folks,

I am having a weird issue of "Vagrant ssh prompt password".
I searched above and tried those solutions which normally didn't work in my case.

My issue is:
`vagrant ssh host1` asks password.

However, ssh using following command:
`ssh vagrant@<ip>` works fine.

My vagrant ssh-config show:

> (venv) dans-test-mbp:public_network dantest$ vagrant ssh-config
> Host host1
>   HostName 127.0.0.1
>   User vagrant
>   Port 2222
>   UserKnownHostsFile /dev/null
>   StrictHostKeyChecking no
>   PasswordAuthentication no
>   IdentityFile /Users/dantest/Desktop/public_network/.vagrant/machines/host1/virtualbox/private_key
>   IdentitiesOnly yes
>   LogLevel FATAL
> 
> Host host2
>   HostName 127.0.0.1
>   User vagrant
>   Port 2200
>   UserKnownHostsFile /dev/null
>   StrictHostKeyChecking no
>   PasswordAuthentication no
>   IdentityFile /Users/dantest/Desktop/public_network/.vagrant/machines/host2/virtualbox/private_key
>   IdentitiesOnly yes
>   LogLevel FATAL
> 
> Host host3
>   HostName 127.0.0.1
>   User vagrant
>   Port 2201
>   UserKnownHostsFile /dev/null
>   StrictHostKeyChecking no
>   PasswordAuthentication no
>   IdentityFile /Users/dantest/Desktop/public_network/.vagrant/machines/host3/virtualbox/private_key
>   IdentitiesOnly yes
>   LogLevel FATAL
> 
> Host host4
>   HostName 127.0.0.1
>   User vagrant
>   Port 2202
>   UserKnownHostsFile /dev/null
>   StrictHostKeyChecking no
>   PasswordAuthentication no
>   IdentityFile /Users/dantest/Desktop/public_network/.vagrant/machines/host4/virtualbox/private_key
>   IdentitiesOnly yes
>   LogLevel FATAL

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!
