### ISSUE TITLE
Vagrant cannot install on Ubuntu 16.04: broken packages

### ISSUE THREAD

**Issue by skmaingi** [hashicorp/vagrant#10918]
The following packages have unmet dependencies:
 vagrant : Depends: bundler but it is not going to be installed
           Depends: ruby-childprocess (>= 0.3.7) but it is not going to be installed
           Depends: ruby-listen but it is not going to be installed
           Depends: ruby-rest-client but it is not going to be installed
           Depends: ruby-nokogiri but it is not going to be installed
           Depends: ruby-rb-inotify but it is not going to be installed
           Depends: ruby but it is not installable

**Comment by briancain** [comment]
Hi @skmaingi - You install Vagrant through the packages on this website: https://www.vagrantup.com/downloads.html

The information you posted is not related to Vagrant packages, but looks like a rubygems issue.

Thanks!

**Comment by skmaingi** [comment]
@briancain Thanks. The installation (https://www.vagrantup.com/downloads.html) worked.
