### ISSUE TITLE
Insufficient permissions error

### ISSUE THREAD

**Issue by lebogan** [hashicorp/vagrant#10913]
I received this error while trying to add files to a newly initialed git repo on a VirtualBox vm:
```
error: insufficient permission for adding an object to repository database .git/objects
error: junk.txt: failed to insert into database
error: unable to index file junk.txt
fatal: adding files failed
```
### Vagrant version
Vagrant 2.2.4 on VirtualBox 6.0.8

### Host operating system
Fedora 29

### Guest operating system
Fedora 28

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/fedora-28"
  config.vm.hostname = 'crystal-dev-box'

  config.vm.network "private_network", ip: "x.x.x.x" #, auto_config: false

  config.ssh.forward_x11 = true
  config.ssh.forward_agent = true

  config.vm.synced_folder "~/bin", "/home/vagrant/bin"
  config.vm.synced_folder "~/Projects/snippets", "/home/vagrant/snippets"
  config.vm.synced_folder "~/Templates", "/home/vagrant/Templates"
  config.vm.synced_folder "~/Projects/ansible_projects/earthsea-site", "/home/vagrant/earthsea-site"

  config.vm.provider 'virtualbox' do |v|
    v.name = "crystal-dev-box"
    v.memory = 8192
    v.cpus = 2
    v.gui = false
  end
  config.vm.provision :shell, path: 'bootstrap.sh', keep_color: true
end
```

### Git config file
```user.name=vagrant
user.email=vagrant@localhost
color.ui=auto
core.editor=gvim -f
core.excludesfile=~/.gitignore
push.default=matching
alias.co=checkout
alias.cm=commit
alias.br=branch
alias.cam=commit -am
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
```

### Expected behavior
Git should have added my files

### Actual behavior
I got the error indicated above

### Steps to reproduce
This fails on the shared directory but works on a local vm directory like /home/vagrant/tmp
1. mkdir junk && cd junk
2. git init
3. touch junk.txt
4. git add -A

### Debug steps
```
chown -R vagrant:vagrant .
chmod -R ug+rwX .
find . -type -d -exec chmod g+s '{}' +
ll .git/objects
total 12K
drwxrwxr-x. 1 vagrant vagrant 4.0K Jun 15 11:16 pack
drwxrwxr-x. 1 vagrant vagrant 4.0K Jun 15 11:16 info
drwxrwxr-x. 1 vagrant vagrant 4.0K Jun 15 11:17 e6
```

**Comment by lebogan** [comment]
I blew away my vm and recreated it via a script I always use, i.e., nothing changed. Now the error is gone and git works as expected! I did this several times before and got the error. Not sure where to go from here. Any sage advice is greatly appreciated.

Thanks

**Comment by briancain** [comment]
Hi @lebogan - It's possible the files you were trying to commit were owned as root. This isn't a vagrant error. I don't remember if vagrant is the default user/group for synced_folders, but you can explicitly set that on each synced folder so that you can be sure the right user can commit those files you synced to your vm:

https://www.vagrantup.com/docs/synced-folders/basic_usage.html#group
https://www.vagrantup.com/docs/synced-folders/basic_usage.html#owner

Thanks!

**Comment by mhoskiso** [comment]
Also experiencing this issue after updating Virtualbox and Vagrant to newest versions. It's only happening inside the Virtualbox shared folder with git operations. Permissions all seem fine, but have to use sudo with git to make the error go away.

Host: OSX Mojave
Guest: Ubuntu 16.04.6 LTS
VIrtualbox: 6.0.8
Vagrant: 2.2.4

serverpilot@local-dev:~/apps2/test$ git init
Initialized empty Git repository in /srv/users/serverpilot/apps2/test/.git/
serverpilot@local-dev:~/apps2/test$ touch test.txt
serverpilot@local-dev:~/apps2/test$ git add test.txt 
error: insufficient permission for adding an object to repository database .git/objects
error: test.txt: failed to insert into database
error: unable to index file 'test.txt'
fatal: adding files failed
serverpilot@local-dev:~/apps2/test$ ll
total 0
drwxr-xr-x 1 serverpilot serverpilot 128 Jun 21 10:05 ./
drwxr-xr-x 1 serverpilot serverpilot 928 Jun 21 10:03 ../
drwxr-xr-x 1 serverpilot serverpilot 320 Jun 21 10:05 .git/
-rw-r--r-- 1 serverpilot serverpilot   0 Jun 21 10:05 test.txt
serverpilot@local-dev:~/apps2/test$ sudo chown -R serverpilot:serverpilot .git
serverpilot@local-dev:~/apps2/test$ git add test.txt 
error: insufficient permission for adding an object to repository database .git/objects
error: test.txt: failed to insert into database
error: unable to index file 'test.txt'
fatal: adding files failed
serverpilot@local-dev:~/apps2/test$ cd .git
serverpilot@local-dev:~/apps2/test/.git$ ll
total 12
drwxr-xr-x 1 serverpilot serverpilot 320 Jun 21 10:06 ./
drwxr-xr-x 1 serverpilot serverpilot 128 Jun 21 10:05 ../
drwxr-xr-x 1 serverpilot serverpilot  64 Jun 21 10:05 branches/
-rw-r--r-- 1 serverpilot serverpilot 111 Jun 21 10:05 config
-rw-r--r-- 1 serverpilot serverpilot  73 Jun 21 10:05 description
-rw-r--r-- 1 serverpilot serverpilot  23 Jun 21 10:05 HEAD
drwxr-xr-x 1 serverpilot serverpilot 416 Jun 21 10:05 hooks/
drwxr-xr-x 1 serverpilot serverpilot  96 Jun 21 10:05 info/
drwxr-xr-x 1 serverpilot serverpilot 160 Jun 21 10:05 objects/
drwxr-xr-x 1 serverpilot serverpilot 128 Jun 21 10:05 refs/
serverpilot@local-dev:~/apps2/test/.git$ cd ..
serverpilot@local-dev:~/apps2/test$ sudo git add test.txt
serverpilot@local-dev:~/apps2/test$ ll
total 0
drwxr-xr-x 1 serverpilot serverpilot 128 Jun 21 10:05 ./
drwxr-xr-x 1 serverpilot serverpilot 928 Jun 21 10:03 ../
drwxr-xr-x 1 serverpilot serverpilot 352 Jun 21 10:06 .git/
-rw-r--r-- 1 serverpilot serverpilot   0 Jun 21 10:05 test.txt

**Comment by lebogan** [comment]
@mhoskiso , I tried everything to do with permissions also - no go. `sudo` works though. Thanks. Now I just need to know why (just my nature).

**Comment by mhoskiso** [comment]
@lebogan ,
Finally got rid of this by rolling back Virtualbox to 5.2.30

**Comment by marauder37** [comment]
I'm getting this too, I'm trying to troubleshoot it. It only happens on one machine.

Both hosts: macOS 10.14.5, vagrant 2.2.4
Both guests: Ubuntu 18.04.2 LTS

Doesn't work on: virtualbox 6.0.8r130520
Does work on: virtualbox 6.0.4r128413

**Comment by ncla** [comment]
Experiencing this issue as well after upgrading to newest VirtualBox for Laravel Homestead needs. The common permissions solutions you find on internet do not help. I tried recloning the repositories on my host, but once you edit a file through IDE, and then try to `git add` through the VM, I get same error.

```
error: insufficient permission for adding an object to repository database .git/objects
error: file.txt: failed to insert into database
error: unable to index file file.txt
fatal: updating files failed
```
Vagrant 2.2.5
VirtualBox 6.0.8 r130520

**Comment by jkeyes** [comment]
FYI confirmed I have this issue too.

Vagrant 2.2.5
VirtualBox 6.0.10 r132072

This bug https://www.virtualbox.org/ticket/18569 indicates it's an issue with VirtualBox. I [downgraded to 6.0.4](https://www.virtualbox.org/wiki/Download_Old_Builds_6_0) and the problem was gone.

**Comment by atrnh** [comment]
Sorry for resurrecting this issue. I'm experiencing the same problem on multiple machines, except downgrading to VirtualBox 6.0.4 isn't working.

**Hosts:** macOS 10.14.5, vagrant 2.2.5
**Guests:** Ubuntu 18.04.2 LTS

VirtualBox revisions that don't work for me:
* 6.0.10
* 6.0.4
* 6.0.2

Steps I follow when downgrading/testing to see if it works:
* Destroy any Vagrant machines (`vagrant destroy`)
* Kill all VirtualBox processes
* Uninstall VirtualBox
* Install downgraded VirtualBox
* Restart host machine
* `vagrant up`
* `vagrant ssh`
* In Vagrant:
  * create git repo
  * attempt to add a file, get permissions error
  * check permissions on `.git/objects` to make sure it looks normal (sadly, permissions always look normal)

Is there something I'm missing, here?

**Comment by jkeyes** [comment]
@atrnh I believe the bug is in the Guest Additions so you need to make sure the correct version of those are installed. Run `modinfo vboxguest` in Ubuntu to find out the version that is installed.

**Comment by atrnh** [comment]
@jkeyes Thanks so much for the insight &mdash; here's what I get from `modinfo vboxguest`

```
filename:       /lib/modules/4.15.0-51-generic/misc/vboxguest.ko
version:        6.0.8 r130520
license:        GPL
description:    Oracle VM VirtualBox Guest Additions for Linux Module
author:         Oracle Corporation
srcversion:     3060C136837BA62E8BF628C
alias:          pci:v000080EEd0000CAFEsv00000000sd00000000bc*sc*i*
depends:        
retpoline:      Y
name:           vboxguest
vermagic:       4.15.0-51-generic SMP mod_unload 
```

**Comment by jjb** [comment]
I appear to have solved this by updating my Virtualbox Guest Additions from 6.0.10 to 6.0.12, using https://github.com/dotless-de/vagrant-vbguest
