### ISSUE TITLE
Duplicate interface eth1

### ISSUE THREAD

**Issue by tgr** [hashicorp/vagrant#1092]
While trying to create a vagrant base box, I created a VM with this in `/etc/network/interfaces`:

```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet dhcp
```

After packaging and `vagrant up`, the contents of /etc/network/interfaces` is this:

```
 # This file describes the network interfaces available on your system
 # and how to activate them. For more information, see interfaces(5).

 # The loopback network interface
 auto lo
 iface lo inet loopback

 # The primary network interface
 allow-hotplug eth0
 iface eth0 inet dhcp

 allow-hotplug eth1
 iface eth1 inet dhcp
 #VAGRANT-BEGIN
 # The contents below are automatically generated by Vagrant. Do not modify.
 auto eth1
 iface eth1 inet static
       address 192.168.56.11
       netmask 255.255.255.0
 #VAGRANT-END
```

(note the two lines before `#VAGRANT-BEGIN`)

The duplicate definition causes `vagrant up` to terminate with an error:

```
/etc/network/interfaces:17: duplicate interface
ifup: couldn't read interfaces file "/etc/network/interfaces"
```

The network-related part of the vagrantfile is

```
config.vm.network :hostonly, "192.168.56.11"
```

After manually deleting the extra lines from `/etc/network/interfaces`, fixing `/etc/udev/rules.d/70-persistent-net.rules` (which now has two lines for eth1) and restarting, `vagrant up` works; but if I repackage and reimport, the extra lines appear again.

**Comment by jippi** [comment]
Hi,

I have this issue as well, on latest version of vagrant - debian 7.7, latest virtualbox, /etc/udev/rules.d/70-persistent-net.rules. is empty
