### ISSUE TITLE
SStderr: VBoxManage.exe: error: The virtual machine 'vagrant_XXX' has terminated unexpectedly during startup with exit code 1 (0x1).

### ISSUE THREAD

**Issue by Jyotsnatesting** [hashicorp/vagrant#10922]
Please find my GIST details any help here would be appreciated.

https://gist.github.com/Jyotsnatesting/70c7199ea0d5d5de140790fab03a703c

**Comment by briancain** [comment]
Hi @Jyotsnatesting - Please fill out the issue template provided and also provide us with the debug log from Vagrant rather than from VirtualBox. Thanks!

**Comment by Jyotsnatesting** [comment]
i dont know how to generate a debug log..i am going to copy what ever the error that i am getting.
![Vagrant Error](https://user-images.githubusercontent.com/46790237/59797502-d5793a00-92ad-11e9-83ec-cf8be1242578.JPG)

**Comment by briancain** [comment]
@Jyotsnatesting - I recommend reading this forum post: https://forums.virtualbox.org/viewtopic.php?f=25&t=82106

It looks like it could be your anti-virus causing the issue with VirtualBox. If you have a vagrant bug feel free to open another issue, but this looks to be an issue with VirtualBox. Thanks!
