### ISSUE TITLE
vagrant upgrade from 1.9 to 2.2 problem conflicts with file from prev package

### ISSUE THREAD

**Issue by compadvance** [hashicorp/vagrant#10931]
Hi , as per your instruction on how to upgarde , I have downloaded 2.2 version and attempted to install on top of existing 1.9 but instead of smooth upgrade 
"Run into troubles upgrading? Please report an issue if you run into problems upgrading. Upgrades are meant to be a smooth process and we consider it a bug if it was not." 
I am having followed errors for every each file : 
Run into troubles upgrading? Please report an issue if you run into problems upgrading.

 file /opt/vagrant/embedded/share/readline/rlversion.c from install of vagrant-1:2.2.4-1.x86_64 conflicts with file from package vagrant-1:1.9.7-1.x86_64

is it not the case that The installers will properly overwrite and remove old files. It is recommended that no other Vagrant processes are running during the upgrade process.

please advise asap, thanks Emil

**Comment by briancain** [comment]
Hey there @compadvance - I recommend trying to uninstall the previous version of Vagrant, and then try installing the newer package. Let me know if that works. :+1:

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
