### ISSUE TITLE
Vagrant 2.2.5 installer is not signed on macOS

### ISSUE THREAD

**Issue by carlosefr** [hashicorp/vagrant#10934]
I'm attempting to install the latest version of Vagrant (2.2.5 as I write this) and the installer package does not seem to be signed. I don't remember this being an issue in previous versions of Vagrant, so I believe this is an error. 

### Vagrant version
Vagrant 2.2.5

### Host operating system
macOS High Sierra 10.13.6

### Expected behavior
The installer macOS `.pkg` should be properly signed.

### Actual behavior
macOS complaints that the installer package is not signed and refuses to run it.

<img width="478" alt="screenshot" src="https://user-images.githubusercontent.com/937276/60218837-6d57c480-9868-11e9-91d1-f90836e50a59.png">

### Steps to reproduce
1. Download `vagrant_2.2.5_x86_64.dmg` from https://www.vagrantup.com/downloads.html;
2. Open it;
3. Run `vagrant.pkg`.

**Comment by chrisroberts** [comment]
Hi @carlosefr. Thanks for reporting this issue. It seems that I had validation disabled on my test system so it did not get flagged. A new macOS package has been generated that is properly signed and can be downloaded from the downloads page.

Thanks again!

**Comment by deviantintegral** [comment]
Is there any way to do new version number or release datestamp on the downloads page? I grabbed the dmg earlier today, and there's no indication on the downloads page that it's been updated in-place.

**Comment by chrisroberts** [comment]
At this point no, but it has been brought up internally and hopefully will have a solution in the future.

**Comment by ljtill** [comment]
Think this is related, the new package which was re-generated has alternated the SHA256 checksum and the list ("SHA256 checksums for Vagrant 2.2.5") on the downloads site needs to be updated.

https://www.vagrantup.com/downloads.html

**Comment by carlosefr** [comment]
I downloaded the package today on another machine, and it's complaining about being unsigned again. 😞

**Comment by carlosefr** [comment]
It's a CDN caching issue.  I've downloaded the `.dmg` and the `SHA256SUMS` files again, but with a random query string added to the URL and it downloaded the correctly signed package.
