### ISSUE TITLE
Unable to mount nfs shared folder on Mountain Lion, Virtualbox 4.1.18 with vagrant 1.01

### ISSUE THREAD

**Issue by mikkin** [hashicorp/vagrant#1093]
The following is the log output that can probably help you out:
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
DEBUG ssh: Re-using SSH connection.
INFO ssh: Execute: printf /opt/workfeed (sudo=false)
DEBUG ssh: stdout: /opt/workfeed
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
INFO ssh: Execute: mkdir -p /opt/workfeed (sudo=true)
DEBUG ssh: Exit status: 0
DEBUG ssh: Re-using SSH connection.
INFO ssh: Execute: mount -o vers=3 33.33.33.1:'/Users/derickson/dev/workfeed' /opt/workfeed (sudo=true)
DEBUG ssh: Exit status: 32
ERROR warden: Error occurred: Mounting NFS shared folders failed. This is most often caused by the NFS
client software not being installed on the guest machine. Please verify
that the NFS client software is properly installed, and consult any resources
specific to the linux distro you're using for more information on how to
do this.

**Comment by wgabka** [comment]
For my case (OSX Maverick) the problem was strictly related to firewall. In case you have the same problem which means, when you disable firewall everything is working correctly. The solution is to allow incoming connections for 

/usr/sbin/rpcbind
/sbin/nfsd
/usr/sbin/rpc.statd
/usr/sbin/rpc.lockd
/usr/libexec/rpc.rquotad  

as @dkubb write above.

**Comment by amontalban** [comment]
For anyone having issues with OSX + NFS you can execute this in your OSX host:

sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "/usr/sbin/rpcbind"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp "/usr/sbin/rpcbind"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "/sbin/nfsd"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp "/sbin/nfsd"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "/usr/sbin/rpc.statd"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp "/usr/sbin/rpc.statd"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "/usr/sbin/rpc.lockd"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp "/usr/sbin/rpc.lockd"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "/usr/libexec/rpc.rquotad"
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblockapp "/usr/libexec/rpc.rquotad"
sudo nfsd restart

That should allow all related daemons in firewall and restart NFS service to allow incoming connections from VM.

Based on @wgabka and @dkubb info.

Hope it helps someone!
