### ISSUE TITLE
Ctrl+C sometimes ignored

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10933]
### Vagrant version

```console
$ vagrant --version
Vagrant 2.2.4
```

I am running some `vagrant`... commands from Rake tasks. Perhaps that affects how the initial SIGINT is propagated to Vagrant?

### Host operating system

Ubuntu 19.10 Disco Dingo

### Guest operating system

Debian 9.8 Stretch ppc64el (A work in progress box)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "mcandre/vagrant-debian-cpp-ppc64el"
end
```

### Expected behavior

Pressing Control+C during `vagrant up` should terminate the Vagrant process.

### Actual behavior

Sometimes, Vagrant continues running for several minutes after SIGINT.

### Steps to reproduce

1. `vagrant up`
2. Ctrl+C
3. `sudo ps aux | grep vagrant`

When no other Vagrant projects are running, then exactly one result should appear, for the `grep vagrant` process, not any Vagrant processes.

I've noticed this kind of behavior happening in Windows with Packer, but now Linux with Vagrant is doing it as well.

**Comment by chrisroberts** [comment]
Are you experiencing this behavior when you run the executables (`vagrant` or `packer`) directly and not via `rake` ?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
