### ISSUE TITLE
Uninstalling vagrant-proxyconf doesn't remove proxy settings

### ISSUE THREAD

**Issue by Arbeliam** [hashicorp/vagrant#10944]
### Vagrant version
2.0.3

### Host operating system
Win10

### Guest operating system
Ubuntu 14.04.5 LTS

### Vagrantfile
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 3306, host: 3306
  
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.synced_folder "www/", "/var/www/html" , type: "nfs"

   config.vm.provider "virtualbox" do |v|

    v.customize ["modifyvm", :id, "--nictype1", "virtio" ]
    v.customize ["modifyvm", :id, "--nictype2", "virtio" ]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	
    v.memory = "2048"
   
  end
   
end

### Steps to reproduce:

1. I installed vagrant-proxyconf
2. add to Vagrantfile:
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://192.168.33.10:3128/"
    config.proxy.https    = "http://192.168.33.10:3128/"
  end
3. Uninstalled vagrant-proxyconf
4. removed above lines from Vagrantfile

### Actual behavior

Now every time I try to use apt-get or npm i , I get this error message:

Failed to connect to 192.168.33.10 port 3128: Connection refused

**Comment by binary-manu** [comment]
Hi,

from [vagrant-proxyconf](https://tmatilai.github.io/vagrant-proxyconf/) documentation:

> Possible values
> 
> If all keys are unset or nil, no configuration is written.
> A proxy should be specified in the form of http://[user:pass@]host:port.
> Empty string ("") or false in any setting also force the configuration files
> to be written, but without configuration for that key. Can be used to clear
> the old configuration and/or override a global setting.

So to remove proxy settings, you should set them to empty strings in the Vagrantfile, reload the impacted VM's, then you can uninstall `vagrant-proxyconf`. Once you uninstall it, Vagrant itself has no idea about how to revert its changes.

**Comment by chrisroberts** [comment]
Hi there,

As @binary-manu mentions, the documentation for the plugin provides a means for removing the settings. Vagrant itself is not controlling those settings and has no way of know how they should be "restored".

Cheers!
