### ISSUE TITLE
[question] Is config.vm.base_mac still required in a base box?

### ISSUE THREAD

**Issue by dcermak** [hashicorp/vagrant#10946]
I'm currently creating Vagrant boxes of various Linux distros (mostly openSUSE) using [KIWI](https://github.com/SUSE/kiwi). KIWI will include a Vagrantfile in the created box with the following contents:
``` ruby
Vagrant.configure("2") do |config|
  config.vm.base_mac = "00163E010101" # <- this value is randomly generated at box build time
end
```

I've seen multiple base boxes with hard coded `base_mac` values, but haven't really found a reason for that. Also I've found reports of this causing issues, e.g. #9200.

Is this setting still required? I found #10080, which removed the need for this config for Virtualbox. But what about other providers?

Assuming I want to be compatible with older Vagrant releases, what is the recommended way to set a randomized MAC address, that differs between instances of the same box but persists over reboots?

### References
- #10080
- #9200

**Comment by briancain** [comment]
Hi @dcermak - if I remember correctly, the base_mac setting is something VirtualBox needs for getting NAT networking working. Today Vagrant will auto-generate one if it doesn't exist inside the Vagrantfile, via https://github.com/hashicorp/vagrant/pull/10255

If you're wanting to stay compatible with older Vagrant releases, you'll probably need to include that option as I believe Vagrant was programmed to fail hard if it didn't exist in the guest. Thanks!

**Comment by dcermak** [comment]
Thanks for the confirmation, it is then as I suspected.
