### ISSUE TITLE
Destroy fails with synced_folder set to ENV

### ISSUE THREAD

**Issue by elfranne** [hashicorp/vagrant#10955]
### Vagrant version
Vagrant 2.2.5

### Host operating system
Ubuntu 18.10

### Guest operating system
ubuntu/xenial64

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.synced_folder ENV['SOME_VAR'], '/path'
end
```
### Debug output
https://gist.github.com/elfranne/c4fd986dcd363dc60ecaf9189b7d147e

### Expected behavior
box should be destroyed

### Actual behavior
box is not destroyed

### Steps to reproduce
1. Open a terminal: export SOME_VAR=/etc/apache2 
2. Open another terminal: vagrant destroy --debug -f

**Comment by briancain** [comment]
Hi @elfranne - I just tried this and it works as expected:

```ruby
config.vm.define "bork" do |b|
    b.vm.box = "bento/ubuntu-18.04"
    b.vm.synced_folder ENV['SOME_VAR'], "/vagrant"
    b.vm.provider :virtualbox
end
```

Before bringing up the guest I exported the environment variable `SOME_VAR` to an existing folder, scripts.

```
brian@localghost:vagrant-sandbox % be vagrant up bork                                                    ±[●][master]
Bringing machine 'bork' up with 'virtualbox' provider...
==> bork: Importing base box 'bento/ubuntu-18.04'...
==> bork: Matching MAC address for NAT networking...
==> bork: Checking if box 'bento/ubuntu-18.04' version '201906.18.0' is up to date...
==> bork: Setting the name of the VM: vagrant-sandbox_bork_1562686375030_2661
==> bork: Clearing any previously set network interfaces...
==> bork: Preparing network interfaces based on configuration...
    bork: Adapter 1: nat
==> bork: Forwarding ports...
    bork: 22 (guest) => 2222 (host) (adapter 1)
==> bork: Booting VM...
==> bork: Waiting for machine to boot. This may take a few minutes...
    bork: SSH address: 127.0.0.1:2222
    bork: SSH username: vagrant
    bork: SSH auth method: private key
    bork:
    bork: Vagrant insecure key detected. Vagrant will automatically replace
    bork: this with a newly generated keypair for better security.
    bork:
    bork: Inserting generated public key within guest...
    bork: Removing insecure key from the guest if it's present...
    bork: Key inserted! Disconnecting and reconnecting using new SSH key...
==> bork: Machine booted and ready!
==> bork: Checking for guest additions in VM...
==> bork: Mounting shared folders...
    bork: /vagrant => /home/brian/code/vagrant-sandbox/scripts
brian@localghost:vagrant-sandbox % echo $SOME_VAR                                                        ±[●][master]
scripts
brian@localghost:vagrant-sandbox % ls -lah scripts                                                       ±[●][master]
total 16K
drwxr-xr-x  4 brian brian 4.0K Nov 16  2018 .
drwxr-xr-x 21 brian brian 4.0K Jul  9 08:32 ..
drwxr-xr-x  4 brian brian 4.0K Apr 26 09:40 linux
drwxr-xr-x  2 brian brian 4.0K Jan 22 09:07 windows
brian@localghost:vagrant-sandbox % be vagrant destroy bork -f                                            ±[●][master]
==> bork: Forcing shutdown of VM...
==> bork: Destroying VM and associated drives...
```

Based on the error vagrant is giving you, it says that:

> no implicit conversion of nil into String (TypeError)

This tells me that your environment variable is probably not set and gets evaluated to nil.

**Comment by elfranne** [comment]
On my report I said to open another terminal to make sure the environment variable was not set.
Yes I understand that because the variable is not set that it make the destroy fail. But I think you should be able to destroy a box anyway.

**Comment by briancain** [comment]
Hi @elfranne - Not having a variable set makes it nil, which is an invalid config. You need to have a valid configuration for Vagrant to successfully execute. I recommend not using environment variables to define your synced folder configurations, because of situations like this. If you really need to have your synced folder options configurable, it would be better to set a default here so that if the env variable is not set, it will at least be _something_ rather than nil.
