### ISSUE TITLE
Docker provider lacks shell script provisioning support

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10952]
When I try to provision my Docker-provided Vagrant boxes with shell scripts, I get:

> ==> default: Provisioners will not be run since container doesn't support SSH.

Fortunately, this is fairly straightforward to correct using `docker exec`. Can we please implement `vagrant ssh` for Docker provider in terms of `docker exec`?

**Comment by briancain** [comment]
Hi @mcandre - this exists already via [vagrant docker-exec](https://www.vagrantup.com/docs/docker/commands.html#docker-exec). Thanks!
