### ISSUE TITLE
Expose more boot error detail

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#10967]
Sometimes a box fails to boot. This wouldn't be so bad, but any boot errors are often obfuscated as DHCP errors, or more likely SSH connection errors. And that makes it harder for users to determine what is going wrong with their boxes!

What if Vagrant offered more hooks, similar to hostname and rsync hooks, for determining which stages of the boot process, from power on, to RAM file systems, to loading a kernel, to launch daemons, to networking to DHCP to SSH, are being successfully completed?

Even something simple like a pre-networking launch service that blinks a virtual LED once, triggering a Vagrant stderr message on timeout, would provide a lot of assistance to Vagrant users for diagnosing `vagrant up` errors. What do you think?

**Comment by briancain** [comment]
Hi @mcandre - This is a relatively new feature still hidden behind our feature flag for development, but vagrant triggers has the ability to run code for any given Vagrant hook or Vagrant action: https://www.vagrantup.com/docs/triggers/configuration.html#hooks

In theory you should be able to run a trigger at any stage of the Vagrant lifecycle. However that being said, I don't think you'll actually be able to get down to the details that you specified. Vagrant simply runs a vboxmanage command to bring up the VM, and isn't actually handling loading a kernel, or anything else related to booting the machine. Thanks!
