### ISSUE TITLE
Create base for multi-machine provision

### ISSUE THREAD

**Issue by brianjmurrell** [hashicorp/vagrant#10965]
When I create multiple machine configurations, often many, if not all of the machines have the same configuration in terms of packages installed, etc.

It would be useful to be able to create a base image with all of the commonality once and then create the multiple machines on top of that base, rather than doing the same thing on every machine.

Obviously this only works with underlying VM technologies that allow creating VMs on top of other VM snapshot images, like [libvirt](https://github.com/vagrant-libvirt/vagrant-libvirt/).  But where it's possible is should be usable.  Where not possible, the configuration could just degenerate into doing the common part on each VM image.

**Comment by briancain** [comment]
Hi @brianjmurrell - You can do this today with the `vagrant package` command, or use tools like [packer](https://www.packer.io/) to create a base vagrant box. With vagrant package you can provision a single vm and then package it up for other guests to use. Or with packer you can use its post-processors to provision the virtual machine and package it up as a box for Vagrant to use. Thanks!

**Comment by brianjmurrell** [comment]
But no way to do it all in one shot in a single `Vagrantfile`, right?

**Comment by briancain** [comment]
Yes:

```ruby
config.vm.define "hashicorp" do |h|
    h.vm.box = "hashicorp/precise64"
    h.vm.provider :virtualbox
    h.vm.provision "shell", inline:<<-SHELL
    echo 'hello there' > file.txt
    SHELL
end
```

```
vagrant up
vagrant package
```

That will package the vm resulting in it having the file.txt, or any other provisioners you ran, to be included in the new base box.

**Comment by brianjmurrell** [comment]
I mean build the new base box and then the multi-boxes based on it, all in the same `Vagrantfile` so that it all happens with just a `vagrant up`.

**Comment by briancain** [comment]
You could do that with a guest trigger configured to run after the base guest has been brought up and provisioned but before the dependent guests. The trigger would run the `vagrant package` command on the guest and `vagrant box add` with the proper name. Then when vagrant brings up the following guests it should be able to use the updated packaged box.
