### ISSUE TITLE
Feature Request - Add a provider for Proxmox

### ISSUE THREAD

**Issue by vikas027** [hashicorp/vagrant#10968]
Proxmox has been lately used by a lot of people in labs and even in production. 

There is already a packer [builder](https://www.packer.io/docs/builders/proxmox.html) for [Proxmox](https://www.proxmox.com/en/), it would be great if we have a vagrant provider too :)

**Comment by briancain** [comment]
Hi there @vikas027 - there seems to be one that already exists! https://github.com/telcat/vagrant-proxmox Thanks.

**Comment by vikas027** [comment]
Hey @briancain ,

That  is not official and is not maintained anymore. It has not been updated since quite a few years.

My feature request was to have an official provider just like we have others [here](https://www.vagrantup.com/docs/providers/).

**Comment by briancain** [comment]
@vikas027 - Ah I see. Generally, we likely won't have the bandwidth to bring in another provider and support something like that. Your best bet will probably be seeing if that project can get a maintainer. The Vagrant team is very small these days (2 people), and adding another provider like that is something that we don't have time for with the current state of things. Sorry!

**Comment by vikas027** [comment]
Ah @briancain ,  I totally understand your situation. As of now, I do not know much of GoLang, otherwise would have opted to help.
