### ISSUE TITLE
Cannot execute locally script shared with vagrant mounted as type smb

### ISSUE THREAD

**Issue by VincentLanglet** [hashicorp/vagrant#10979]
### Vagrant version
Latest

### Host operating system
MacOs

### Guest operating system
Linux

### Expected behavior
When I create a script in my vagrant (`type: smb`) and try to run it locally, it works without error.

### Actual behavior
I get permission denied.

If I use `type: nfs` instead, there is no issue.

### Steps to reproduce
1. Mounting a vagrant with `type: smb`
2. `vagrant ssh' then create a file `script.exe`
3. Run it locally

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included as well as a Vagrantfile. This helps us figure out what's actually going on. Thanks!

**Comment by VincentLanglet** [comment]
I use `nfs` now. Wont be able to provide this.
