### ISSUE TITLE
VM serial default

### ISSUE THREAD

**Issue by jpnielsen** [hashicorp/vagrant#10970]
ubuntu/eoan64 boots are slow 

/etc/default/grub.d/50-cloudimg-settings.cfg
sends boot log to ttys0

https://bugs.launchpad.net/cloud-images/+bug/1829625

after `vagrant init ubuntu/eoan64` i change my vagrantfile to include:

```
config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true

     vb.memory = "2048"
     vb.cpus = 4 

	 vb.customize [ "modifyvm", :id, "--uart1", "0x03f8", "4" ]
	 vb.customize [ "modifyvm", :id, "--uartmode1", "file", "./console.log" ]
	 vb.customize [ "modifyvm", :id, "--uarttype1", "16550A" ]
	 vb.customize [ "modifyvm", :id, "--uart2", "off" ]
	 vb.customize [ "modifyvm", :id, "--uart3", "off" ]
	 vb.customize [ "modifyvm", :id, "--uart4", "off" ]
	 
  end
```

My question and change requests.

1. I request that ttys0 by default is logged to a file - or at least printed in the cmd it was run from - I couldn't figure out why ubuntu boots were so slow, the more experieced users can turn it off if not needed.

2. how do I specify a logfile location default to the working directory of vagrant.exe - "./console.log" puts it in C:\users\%username%
I do:

```
cd e:\vagrantbox\ubuntu\eoan64
e:\vagrant\bin\vagrant.exe up
```

**Comment by briancain** [comment]
Hi @jpnielsen - This is actually something that ubuntu has configured and packaged into their Vagrant boxes. Vagrant by default doesn't generate log files. For your second question, you can do what Ubuntu does by using some ruby:

```ruby
vb.customize [ "modifyvm", :id, "--uartmode1", "file", File.join(Dir.pwd, "./console.log")]
```

Hope that helps! Thanks

**Comment by PAStheLoD** [comment]
Hello,

Anyone else bumping into this, simply redirecting to the Null Device is a crude workaround.

```
	 vb.customize [ "modifyvm", :id, "--uart1", "0x03f8", "4" ]
	 vb.customize [ "modifyvm", :id, "--uartmode1", "file", Vagrant::Util::Platform.windows? ? "NUL" : "/dev/null" ]
```

So far it's not clear where the bug is. (Maybe VirtualBox, as 5.x seems to work well with Eoan, but others experienced this with 5.x too : https://www.virtualbox.org/ticket/12162 . Maybe the Linux kernel, because it gets stuck if COM1 is disabled in the VB GUI. Or some common but very strange external circumstance?)
