### ISSUE TITLE
PowerShell null reference error when importing Hyper-V VM with VMMS not running

### ISSUE THREAD

**Issue by mrshanahan** [hashicorp/vagrant#10973]
### Vagrant version
2.2.5

### Host operating system
Windows 10 (1709)

### Guest operating system
Windows Server 2012 R2

### Vagrantfile
Nothing specific:

    Vagrant.configure("2") do |config|
      config.vm.box = "<custom-hyperv-box>"
    end

### Debug output
https://gist.github.com/mrshanahan/58edae984050bcb94dafae8ddd8545d1

### Expected behavior
The command fails with a helpful error message, possibly indicating that VMMS is down.

### Actual behavior
The `import_vm.ps1` script fails with the following error:

    You cannot call a method on a null-valued expression.

### Steps to reproduce
1. Disable the VMMS service ("Hyper-V Virtual Machine Management"). (PowerShell: `Get-Service vmms | Stop-Service`)
2. Initialize a new Vagrant directory with a bare-bones Vagrantfile pointing at a Hyper-V box:
```
Vagrant.configure("2") do |config|
  config.vm.box = "<some-hyperv-box>"
end
```
3. Run `vagrant up` (with `--provider hyperv` as necessary with the box).

### Root cause
**I've found the root cause and will open a PR ASAP.** Just wanted to create an issue to track it.

Vagrant fails to create a VM due to VMMS not running, which is expected behavior. It then attempts to create a more helpful error message for the failed import, and starts by querying WMI for the VMMS service: https://github.com/hashicorp/vagrant/blob/83ed01869d12152d63a0b9185d05edd65753bdde/plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1#L357

Since this service is not running, the return value is null, and the attempt to import the system definition from the null service fails: https://github.com/hashicorp/vagrant/blob/83ed01869d12152d63a0b9185d05edd65753bdde/plugins/providers/hyperv/scripts/utils/VagrantVM/VagrantVM.psm1#L364

Checking for null after querying the service and throwing a more specific message should do the trick.

**Comment by briancain** [comment]
Closing this since the pull request was merged.

**Comment by mrshanahan** [comment]
Thank you!
