### ISSUE TITLE
Curl SFTP protocol missing

### ISSUE THREAD

**Issue by osc2nuke** [hashicorp/vagrant#10985]
### Vagrant version
2.2.5

### Host operating system
Windows 10

### Guest operating system
Linux homestead 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64
PHP Version 7.3.6-1+ubuntu18.04.1+deb.sury.org+1

### Expected behavior
Download the requested file.

### Actual behavior
Just created an empty file

### Steps to reproduce
Run a php file with the folowing code (tested on a wamp server):
           
            $remote = "sftp://demo:password@test.rebex.net/pub/example/readme.txt";
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $remote);
            curl_setopt($ch, CURLOPT_PROTOCOLS, CURLPROTO_SFTP);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            $response = curl_exec($ch);
            curl_close($ch);

            $fp = fopen ($local, 'w+');
            fwrite($fp, $response);
            fclose($fp);

### References
Not that i am aware of

**Comment by briancain** [comment]
Hi @osc2nuke - What you are describing is php, not vagrant. Vagrant doesn't run PHP, nor does it handle what libraries curl has inside a guest vm. Since you're using the homestead box, I recommend opening an issue with them. Thanks!
