### ISSUE TITLE
`:action` type triggers not firing when defined globally

### ISSUE THREAD

**Issue by jazaval** [hashicorp/vagrant#10990]
### Vagrant version
`Vagrant 2.2.5`

### Host operating system
```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G84
```
### Guest operating system
```
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A512f
```

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "microsoft/macos-catalina"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.trigger.before :"Vagrant::Action::Builtin::WaitForCommunicator", type: :action do |t|
    t.ruby do |env, machine|
      puts "Resetting network for Parallels guest #{machine.id}..."
      puts `prlctl set #{machine.id} --device-set net0 --disconnect && prlctl set #{machine.id} --device-set net0 --connect`
    end
  end
end


```

### Debug output
https://gist.github.com/jazaval/2fbe1a29f22497a8e90a28e70338d2e0

### Expected behavior
Before the `Waiting for machine to boot. This may take a few minutes...` output, the action trigger should `puts` some text output and run a custom `prlctl` command.

### Actual behavior
The trigger is ignored. However, regular `command` triggers like `:up` fire correctly when used in this Vagrantfile, I just require the timing to occur right before the `WaitForCommunicator` phase. 

### Steps to reproduce
I've tried a number of action classes (`Vagrant::Action::Builtin::GracefulHalt` mentioned in docs, plugin-based actions like `VagrantPlugins::Parallels::Action::Boot`, etc) to test this, none have fired. 

### References
- GH-10852
This issue seems similar, in that `action` triggers do not fire but `command` triggers do. However I am defining the trigger globally like @briancain recommended, with no luck.

**Comment by briancain** [comment]
Hi @jazaval - Did you make sure to enable the experimental switch? The action triggers are behind a feature flag at the moment since there are still parts of it that are a little flaky.

```
VAGRANT_EXPERIMENTAL="typed_triggers" vagrant up
```

https://www.vagrantup.com/docs/triggers/configuration.html#trigger-types

**Comment by jazaval** [comment]
So embarrassing. I misread this docs page: https://www.vagrantup.com/docs/triggers/configuration.html. That worked, thank you.

**Comment by briancain** [comment]
That's ok! :heart: If you have any issues feel free to open another GH issue...the action trigger feature is a little tough to work with at the moment :)
