### ISSUE TITLE
Permission denied @ dir_initialize

### ISSUE THREAD

**Issue by mattkoch614** [hashicorp/vagrant#10999]
I've been wrestling with this issue for a few hours. I cannot execute the vagrant command at all. 

### Vagrant version
2.2.5

### Host operating system
Mac OSX 10.12.6 

### Guest operating system
N/A

### Vagrantfile
N/A, cannot even run ``vagrant`` command

### Debug output
https://gist.github.com/mattkoch614/3a4251dcd2100b7abba69096ba0ca623

### Expected behavior
``vagrant`` command runs successfully

### Actual behavior
Error. See Debug output

### Steps to reproduce
1. Install Vagrant 2.2.5
2. Install VirtualBox 6.0
3. Open Terminal
4. Run ``vagrant`` command

**Comment by briancain** [comment]
Hi @mattkoch614 - Do you have the full debug log for running vagrant?

**Comment by mattkoch614** [comment]
@briancain - Sorry, forgot the debug flag for my output. The gist has been updated.

**Comment by briancain** [comment]
Does the user that is invoking `vagrant` have permission to read the `/Users` dir on your filesystem? It seems like that dir might be locked out of whatever user you are using to run vagrant with.

**Comment by mattkoch614** [comment]
I am the user invoking the command, and that user has access to /Users/(my username). I fear that something may have gotten tangled up by running ``sudo vagrant up`` at one point, causing issues with permissions, but I cannot figure out how to get going again.

**Comment by briancain** [comment]
Ahh, yes, That is for sure what happened. What are the permissions for your folder at `~/.vagrant.d`? I'm guessing it's probably locked out from running sudo.

**Comment by mattkoch614** [comment]
```
total 16
drwxr-xr-x  2 kochm  DOMAIN\Domain Users    68 Aug  2 11:51 boxes
drwxr-xr-x  4 kochm  DOMAIN\Domain Users   136 Aug  2 13:22 data
drwxr-xr-x  4 kochm  DOMAIN\Domain Users   136 Aug  2 13:22 gems
-rw-------  1 kochm  DOMAIN\Domain Users  1675 Aug  2 11:51 insecure_private_key
drwxr-xr-x  3 kochm  DOMAIN\Domain Users   102 Aug  2 11:51 rgloader
-rw-r--r--  1 kochm  DOMAIN\Domain Users     3 Aug  2 11:51 setup_version
drwxr-xr-x  2 kochm  DOMAIN\Domain Users    68 Aug  2 11:51 tmp
```

**Comment by briancain** [comment]
It would be the actual directories permissions rather than the content inside it. I'm guessing it's probably owned my root, or only readable/writable by root.

**Comment by mattkoch614** [comment]
Here we are:
```
drwxr-xr-x  10 kochm  DOMAIN\Domain Users     340 Aug  2 13:22 .vagrant.d
```

**Comment by briancain** [comment]
And what about your `/Users` directory?

**Comment by mattkoch614** [comment]
That one is owned by root. 
```
d-wx--x--x    6 root  admin    204 Feb 13  2018 Users
```

**Comment by briancain** [comment]
Ah ok, that's the problem it looks like. Whatever happened, your Users folder now doesn't have read permissions set. If you fix that (and there are no other permissions issues) then Vagrant should work. I imagine some other tools might be broke for your local user too with those permissions :sweat_smile:

**Comment by briancain** [comment]
It's fine that they are owned by the root/admin user/groups but the permissions looks wrong to me. I don't know what the default permissions are for macOS, but for example, my home dir on linux has these permissions:

```
brian@localghost:vagrant-sandbox % l / | grep home                                                                                                  ±[master]
drwxr-xr-x   3 root root 4.0K Sep 27  2018 home
```

**Comment by mattkoch614** [comment]
Yeah, tell me about it! This has been driving me crazy for a while. I was hoping it was something basic like this. After running the following:

```
sudo chmod 755 /Users
```

This sorted itself out. Thank you for walking through things with me!
