### ISSUE TITLE
juniper/ffp-12.1X47-D15.4-packetmode / ssh_exchange_identification: read: Connection reset by peer

### ISSUE THREAD

**Issue by ipv6freely** [hashicorp/vagrant#11002]
### Vagrant version
Vagrant 2.2.5

### Host operating system
MacOS 10.5
**Yes, I know this is a beta but this was working previously before I wiped my system and re-installed Vagrant and Virtualbox so I don't THINK it's related, but possibly could be**

### Guest operating system
Juniper vSRX Packet Mode (juniper/ffp-12.1X47-D15.4-packetmode) version 0.5.0

### Vagrantfile
```Vagrant.configure(2) do |config|
  config.vm.box = "juniper/ffp-12.1X47-D15.4-packetmode"
  config.vm.boot_timeout = 300
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
    vb.gui = false
  end

  config.vm.define "vsrx1" do |vsrx1|
    vsrx1.vm.host_name = "vsrx1"
    vsrx1.vm.network "private_network",
                     ip: "10.99.12.1",
                     virtualbox__intnet: "1-2"
  end
end
```

### Debug output
[https://gist.github.com/ipv6freely/8ff668af6a242154f5f493b45fff3e50](https://gist.github.com/ipv6freely/8ff668af6a242154f5f493b45fff3e50)

### Expected behavior
VM Boot up and able to SSH

### Actual behavior
- Had a VMBootTimeout error
- Unable to SSH to the VM (ssh_exchange_identification: read: Connection reset by peer)
**I also tried looking at the console in Virtualbox, where boot output was going character by character slowly - I'm sure this is the cause of the boot timeout and the inability to SSH, but I'm not sure why this is happening** ([webm video link](https://webm.red/jgaW.webm))

### Steps to reproduce
1. Create Vagrantfile
2. vagrant up vsrx1
3. vagrant ssh vsrx1

### References
https://github.com/hashicorp/vagrant/issues/8225

**Comment by ipv6freely** [comment]
Looks like this is some sort of incompatibility between Virtualbox 6.x, Vagrant, and this particular box. I downgraded virtualbox to 5.2 and the issue was resolved.

**Comment by briancain** [comment]
Hi @ipv6freely - I imagine there might be an issue with VirtualBox 6 and the box you are using, especially if the VM doesn't seem to properly boot with 6, but works with 5. I don't think this would be anything related to Vagrant based on the video and description of what is happening. Maybe it's worth contacting the maintainer of the box to see if they could rebuild it with VirtualBox 6. If you do find something that is specific to Vagrant feel free to re-open this issue or open a new one. Thanks!

**Comment by ipv6freely** [comment]
Yeah, looks like its the box. I'm talking to somebody right now who is actively using Vagrant with Virtualbox 6.x with no issues. He tried the same box and it also failed for him. Unfortunately the box is 4+ years old so I don't think it's going to get fixed. Oh well, it's always good to open an issue here anyway in case somebody else comes across the same behavior so they aren't pulling their hair out like I have been. Thanks!

**Comment by briancain** [comment]
@ipv6freely - Ahhh, makes sense! I am guessing that is probably another reason why it's not working with VirtualBox 6 if it was build 4+ years ago.
