### ISSUE TITLE
Vagrant failed to load a configured plugin source. 

### ISSUE THREAD

**Issue by mnuestc** [hashicorp/vagrant#11008]
I work on a restrictive network which can not be accessible to https://gems.hashicorp.com/. I have also tried to install offline, but failed with same result.

##Steps to reproduce
my vagrant version is 2.25
I have updated my vagrant plug, and it shows "All plugins are up to date".
"vagrant plugin install vagrant-vbguest" always be faild with below info：
“”Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

no such name (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/“”

##System configuration
OS/Distro version::

31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##Output of vagrant version; vagrant plugin list:
No plugins installed

I also have tried install offline ,but failed with same result
![image](https://user-images.githubusercontent.com/36103788/62694258-92faf080-ba06-11e9-89b2-73e67a64d4ff.png)

**Comment by briancain** [comment]
@mnuestc - Are you able to ping or access the URL mentioned in the error message outside of Vagrant?

**Comment by mnuestc** [comment]
not accessible，my network is restrictive，so I try to install offline

> @mnuestc - Are you able to ping or access the URL mentioned in the error message outside of Vagrant?

**Comment by denzelkwan** [comment]
@mnuestc , not sure if you've solved it yet but if another solution to try is turning off IPv6. A lot of users have been getting issues in regards to that.

**Comment by jsanxez** [comment]
I have the same problem, my vagrant version is 2.2.5

**Comment by denzelkwan** [comment]
Please use version 2.2.4 . There's something wrong with version 2.2.5

**Comment by charlesrocket** [comment]
Same on `2.2.5` over ipv4, testing with `2.2.4`

**Comment by chrisroberts** [comment]
Hi there,

Does the following work:

```
vagrant plugin install vagrant-vbguest --plugin-clean-sources --plugin-source https://rubygems.org
```

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
