### ISSUE TITLE
Feature: VNC communicator

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#11007]
### Summary

Would be helpful to provide a VNC communicator, for legacy guests that don't have sshd, telnetd, etc., like plain vanilla MS-DOS and FreeDOS. With a VNC communicator, at least the keyboard and and a console line reader would be sufficient to be able to run commands over `vagrant ssh [-e]`.

### Host operating system

(any)

### Guest operating system

(any)

**Comment by briancain** [comment]
Hi @mcandre - Thanks for opening a feature issue! While I do think this is a good idea, I don't know how soon our team could work on a request since the majority of our users aren't using legacy systems like this. I recommend trying to write a plugin for Vagrant, thanks!

**Comment by briancain** [comment]
I'm going to go ahead and close this, mostly because I don't foresee the Vagrant team having time to work on a feature like this. Your best bet is to write your own plugin, thanks!
