### ISSUE TITLE
Let's make docs forkable!

### ISSUE THREAD

**Issue by Asalle** [hashicorp/vagrant#11005]
### Expected behavior
Being able to fork the documentation and submit a pull request with corrections/additions.

### Actual behavior
I'm not able to fork the documentation and submit a pull request with corrections/additions.

----------------------------------------

Let's make docs on the website (https://www.vagrantup.com/docs/index.html) a public repo and have a "Fork me on github!" ribbon on the corner, see pic:

<a href="https://github.com/you"><img width="149" height="149" src="https://github.blog/wp-content/uploads/2008/12/forkme_right_green_007200.png?resize=149%2C149" class="attachment-full size-full" alt="Fork me on GitHub" data-recalc-dims="1"></a>

**Comment by briancain** [comment]
Hi @Asalle - The docs are forkable already. You can find them inside this exact repo under the `website` folder. Thanks!
