### ISSUE TITLE
Feature: telnet communicator

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#11006]
### Summary

There aren't many ssh server implementations for DOS, but there are telnet servers for DOS. Would be nice to have a telnet communicator for Vagrant, so that DOS guests can receive commands from the host.

### Host operating system

(any)

### Guest operating system

MS-DOS / FreeDOS

### References

http://www.bttr-software.de/products/jhoffmann/#rmenu

**Comment by briancain** [comment]
Hi @mcandre - Thanks for opening a feature issue! While I do think this is a good idea, I don't know how soon our team could work on a request since the majority of our users aren't using legacy systems like this. I recommend trying to write a plugin for Vagrant, thanks!

**Comment by briancain** [comment]
I'm going to go ahead and close this, mostly because I don't foresee the Vagrant team having time to work on a feature like this. Your best bet is to write your own plugin, thanks!
