### ISSUE TITLE
Enhancement: Local shell provisioning like Packer

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#11017]
Some complex provisioning setups require custom commands to be executed on the host, such as telnet commands for legacy guest operating systems. Packer provides such local shell provisioning:

http://packer.io/docs/provisioners/shell-local.html

Can Vagrant receive a similar option?

**Comment by briancain** [comment]
Hi @mcandre ! You can do that with the `run` option with vagrant triggers: https://www.vagrantup.com/docs/triggers/configuration.html#run
