### ISSUE TITLE
openSUSE Leap 15.1: Vagrant 2.2.0 + VirtualBox 6.0 = ERROR

### ISSUE THREAD

**Issue by lebvlad** [hashicorp/vagrant#11026]
Vagrant not working on openSUSE Leap 15.1

**Vagrant version**
Vagrant 2.2.0

**Host operating system**
openSUSE Leap 15.1

**Vagrantfile**
Vagrantfile default, through vagrant init ubuntu/bionic64

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
end

```
**Debug output**
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.

**Steps to reproduce**
vagrant init ubuntu/bionic64
vagrant up

**Comment by briancain** [comment]
Hi @lebvlad - VirtualBox 6 support was added in version 2.2.1. Please upgrade to the latest version of Vagrant to get VirtualBox 6 support. Thanks!
