### ISSUE TITLE
Feature: VNC Provisioner

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#11021]
Some legacy operating systems, including MS-DOS and FreeDOS, are primarily single process, single user systems with many limitations regarding network applications. This presents some challenges for manipulating VM's, such as provisioning new configurations.

For DOS in particular, telnet servers are available (rmenu), however the legacy limitations prevents commands over the telnet session from successfully launching any other network applications, meaning typical provisioning commands like `wget`, `curl`, `ftp`, and so on are not able to establish connections to external resources. Oh, and rmenu frequently drops the signals from the host's telnet client, making it improbable that any provisioning commands are accurately entered on the guest.

The good news is, these network applications *do* tend to work, as long as they are executed directly from the primary guest shell, such as COMMAND.COM, by sending the keystrokes over VNC. This works, for example, with Packer `boot_command` provisioning during base image builds.

I request that Vagrant provide a similar capability to `boot_command`, in order to support legacy guests such as DOS. Vagrant can wrap the very same `VBoxManage controlvm`... structure employed by Packer, based on JSON `boot_command` strings, so that Vagrant users can customize boxes just like building base images! What do you think?

Of course, one caveat with VNC commands is that you never quite know whether the commands succeeded, unlike with ssh commands. We could accept a parameter to display the screen during VNC provisioning, again matching Packer idioms. That way, DevOps can at least visually compare the final guest state with how they intended provisioning to occur.

As a workaround, any data that usually transfers by network, could be input over telnet to legacy guests with `echo`, a base64 or hex decoder, and some cryptographic hash checks. Not for the faint of heart.

**Comment by briancain** [comment]
Hi @mcandre - while I understand the usecase, as with the other recent issues you have requested, I think you might be better off writing your own plugin for this. As you laid out in this issue, this would be quite a large feature. From our side of things, we don't have a demand at all for supporting DOS in Vagrant, so building something like this for our team won't be something that we would get to any time soon.

Sorry about that, but I'll leave this open in case someone feels excited about writing their own plugin for these features!

**Comment by briancain** [comment]
I'm going to go ahead and close this, mostly because I don't foresee the Vagrant team having time to work on a feature like this. Your best bet is to write your own plugin, thanks!
