### ISSUE TITLE
Nothing happens on vagrant up

### ISSUE THREAD

**Issue by ved-roflas** [hashicorp/vagrant#11035]
## Versions
  - Vagrant: 1.9.5
  - Provider: Virtualbox 5.2.30
  - Guest: precise32
  - Host: windows 7 -32bit, build:7600
  - Powershell: 2.0

## Vagrant destroy & up output
nothing happens here...just an empty directory " .vagrant " is being created

## Expected behavior
virtualbox should be picked up by vagrant

## Actual behavior
Cursor blinks ..that's it
nothing happens on -> vagrant up and on -> vagrant global-status ->it shows "There are no active Vagrant environments on this computer! "

##possible reasons for this behavior
I thinks there are some version dependecies between vagrant, virtualbox & powershell. I dont know i'm just guessing..

##NOTE: I have read numerous official docs and similar previous issue.., nothing worked. when vagrant up command is issued, it does nothing, the cursor keeps blinking forever.

##NOTE: I know this is dumb question, i can use latest releases  but looking for a solution in this setup
 
Debug :
![debug](https://user-images.githubusercontent.com/54432022/63579229-c6657f80-c5af-11e9-8f61-85d350b70cd4.JPG)

**Comment by briancain** [comment]
Hi @ved-roflas - please upgrade your version of Vagrant. 1.9.5 is fairly old at this point. Once upgraded, try running `vagrant up --debug`, and capture the output in a text file so that we can see what's going on. Thanks.

**Comment by ved-roflas** [comment]
hi @briancain - thanks for the response  ...so you're saying that we cant do anything with this setup..but i'm kind of stuck with this setup & not even able to upgrade my powershell......

**Comment by briancain** [comment]
@ved-roflas We can't really help you without a proper debug log. But looking up with what Vagrant supports, the latest version doesn't allow for Powershell below version 3. If you can upgrade Vagrant and Powershell then we can help you, otherwise you're using versions that we don't support. Sorry!

**Comment by ved-roflas** [comment]
thanks @briancain ....i'm closing the issue
