### ISSUE TITLE
Hyper-V integration services does not work with non ASCII names

### ISSUE THREAD

**Issue by 111andre111** [hashicorp/vagrant#11039]
### Vagrant version
`> vagrant -v
Vagrant 2.2.5`

### Host operating system
Windows 10 v1903 build 18362.239 German language version
for sure simiar issues with other languages

### Guest operating system
rhel7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel7"
  config.vm.network "public_network", bridge: "Default Switch"
config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = true 
    h.linked_clone = true 
    h.vm_integration_services = {
        guest_service_interface: true,
        key_value_pair_exchange: true,
        time_synchronization: true,
        heartbeat: true,
    }
  end
end
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://gist.github.com/111andre111/e65f66a90ba129677ad60e4335da0183

### Expected behavior
What should have happened?
Machine should start through, but it stuck with error.

The original reason why I added these fields, especially
`key_value_pair_exchange`, was this error:
`Hyper-V failed to determine your machine's IP address within the configured timeout. Please verify the machine properly booted and the network works. To do this, open the Hyper-V manager, find your virtual machine, and connect to it.
The most common cause for this error is that the running virtual machine doesn't have the latest Hyper-V integration drivers. Please research for your operating system how to install these in order for the VM to properly communicate its IP address to Hyper-V.`
Increase timeout didn't help, so I hoped it is the reason adding field `key_value_pair_exchange`.

### Actual behavior
Stuck with error:
`Failed to enable VM integration service Key-Value Pair Exchange: Es wurde keine Integrationskomponente mit dem angegebenen Namen gefunden.`

### Steps to reproduce
1. added the values from integration services
2. execute `vagrant up --provider=hyperv`
3. found error

### References
Are there any other GitHub issues (open or closed) that should be linked here?
similar issue:
- GH-9679

### fast Solution
I digged a bit into this topic.
At first searching what I get back for integration services with this command:
```
> Get-VMIntegrationService -VMName generic-rhel7-hyperv
             VMName               Name                               Enabled PrimaryStatusDescription SecondaryStatusDescription
             ------               ----                               ------- ------------------------ --------------------------
             generic-rhel7-hyperv Gastdienstschnittstelle            False
             generic-rhel7-hyperv Takt                               True
             generic-rhel7-hyperv Austausch von Schlüsselwertepaaren True
             generic-rhel7-hyperv Herunterfahren                     True
             generic-rhel7-hyperv Zeitsynchronisierung               True
             generic-rhel7-hyperv VSS                                True
```
Like you see especially `Name` column is in national language.
And here:
https://github.com/hashicorp/vagrant/blob/master/plugins/providers/hyperv/driver.rb#L13
I've seen that there is a hard coded mapping to the configuration values.

So I found out that it is enough to replace the values from Englisch with the German ones like that:

| ConfigValue                  | English Name                    | German Name                        |
| ---------------------------- | ------------------------------- | ---------------------------------- |
| guest_service_interface      | Guest Service Interface         | Gastdienstschnittstelle            |
| heartbeat                    | Heartbeat                       | Takt                               |
| key_value_pair_exchange      | Key-Value Pair Exchange         | Austausch von Schlüsselwertepaaren |
| shutdown                     | Shutdown                        | Herunterfahren                     |
| time_synchronization         | Time Synchronization            | Zeitsynchronisierung               |
| vss                          | VSS                             | VSS                                |

I corrected all these values in `drivers.rb` and everything was fine apart from 3 issues:
1. For config value `vss` is it's Name both in German and English the same, so no correction needed.
2. For config value `shutdown` was German `Herunterfahren` but that didn't work, I had to change it back to `Shutdown`, but didn't find the source for that.
Maybe the issue is here, but maybe I am wrong...
https://github.com/hashicorp/vagrant/blob/master/plugins/guests/windows/scripts/reboot_detect.ps1#L21
So I don't know where this is used:
https://www.vagrantup.com/docs/hyperv/configuration.html#shutdown
Possibly it is for using Windows hosts because there is an open issue, that documentation is not good documented:
https://github.com/hashicorp/vagrant/issues/8449
3. The most hard issue to resolve for me as a starting point was the `key_value_pair_exchange` with it's German name containing an "Umlaut" called `ü`.
The solution was then after reading lots of how encoding works under JRuby for me here:
https://github.com/hashicorp/vagrant/blob/master/plugins/providers/hyperv/driver.rb#L206
I added following line between line 206 and 207, which resolved my issue:
```
          args[:Name] = args[:Name].encode!( 'ISO-8859-1', 'UTF-8', invalid: :replace, undef: :replace, replace: '?' )
```
The exact issue was here, that Ruby got the `ü` correctly, but it wasn't transported correctly to the Powershell script.

### long term Solution

Now, this is no good long term solution, because of that I didn't do a pull request and maybe others have better ideas.
My assumption is, there in other language versions of Windows can potentially happen similar issues.
So how to get that solved, because Windows delivers these language specific values through HyperV.
But here for instance is a workaround established to handout a default network device to vagrant:
https://github.com/hashicorp/vagrant/blob/master/plugins/providers/hyperv/action/configure.rb#L24
with something like that in `Vagrantfile`:
```  config.vm.network "public_network", bridge: "Default Switch"```

So I could imagine the similar solution can be like that in Vagrantfile
```
        guest_service_interface: true, lang_guest: "Gastdienstschnittstelle"
        key_value_pair_exchange: true, lang_key_value_pair: "Austausch von Schlüsselwertepaaren"
        time_synchronization: true, lang_time_sync: "Zeitsynchronisation"
        heartbeat: true, lang_heartbeat: "Takt",
        shutdown: true, lang_shutdown: "Herunterfahren"
        vss: true, lang_vss: "VSS"
```
And if the values for `lang_*` don't exist, fall back to the English mapping values as default.

Identify VM Name:
```
Get-VM
```
And for exact identification having on the documentation page the command:
```
 Get-VMIntegrationService -VMName <VMName>
```
Ideally last command can even be executed inside vagrant, with will document the values in the case vagrant is in debug mode.

Any propositions or opinions to that? Because I am not able to correct that with my Ruby knowledge, possibly.

**Comment by pfitzer** [comment]
Hi,

same for me. Debug ouput under https://gist.github.com/pfitzer/0b5689b23f8e2fc8e8c3399236ac6566

**Comment by pfitzer** [comment]
One more hint. With GuestServiceInterface disabled the box is starting without any problems.
