### ISSUE TITLE
Can you change `config.vm.post_up_message` to not trim?

### ISSUE THREAD

**Issue by johnpancoast** [hashicorp/vagrant#11044]
This is a _very_ minor issue, probably of the lowest priority :) but I figured I'd open it anyway.

### Vagrant version
2.2.5

### Host operating system
macOS 10.14.6

### Guest operating system
Applies to any guest OS I assume.

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2"
vagrant_api_version = "2"

print <<-HEREDOC
This line is followed by a blank line that is printed properly.

HEREDOC

Vagrant.configure(vagrant_api_version) do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.post_up_message = <<-HEREDOC
This line is followed by a blank line that is being trimmed by Vagrant.

HEREDOC

end
```
### Debug output
Will provide if necessary.

### Expected behavior
I'd expect that `config.vm.post_up_message` would print output as defined and not trim it. If I have the following post up message, I'd expect the blank line to be returned.

```
  config.vm.post_up_message = <<-HEREDOC
This line is followed by a blank line that is being trimmed by Vagrant.

HEREDOC
```

### Actual behavior
The blank line is trimmed.

### Steps to reproduce
1. Run the included vagrant file.
2. Notice that the first heredoc properly includes the blank line.
3. Notice that the heredoc from `config.vm.post_up_message` is trimmed.

**Comment by briancain** [comment]
Hi @johnpancoast - if I recall correctly, the `post_up_message` uses the exact same class that all Vagrant messages use for printing to stdout and stderr. I'm not really sure how difficult it would be to change this behavior, or if there are folks relying on this to _not_ trim the blank space. I'll leave this as an enhancement for now.
