### ISSUE TITLE
create a hostonly network adapter

### ISSUE THREAD

**Issue by cuisongliu** [hashicorp/vagrant#11049]
i need a hostonly network adapter.but default create a nat network adapter.

### Vagrant version
v2.2.5

### Host operating system
Linux cuisongliu-PC 4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018 x86_64 GNU/Linux

### Guest operating system
Centos7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  # vagrant plugin install vagrant-disksize
  config.disksize.size = "50GB"
  config.vm.synced_folder "../data", "/data", create: true, owner: "root", group: "root", mount_options: ["dmode=755","fmode=755"]
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 2048
     vb.cpus   = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
      sh /data/base.sh
      sh /data/docker.sh
  SHELL
  (1..1).each do |i|
    config.vm.define "master#{i}" do |master|
      master.vm.hostname = "master#{i}"
      master.vm.network "private_network",ip:"172.16.3.24#{i}"
      master.vm.provider "virtualbox" do |vb|
         vb.name = "master#{i}"
      end
    end
  end
  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.network "private_network",ip:"172.16.3.25#{i}"
      node.vm.provider "virtualbox" do |vb|
         vb.name = "node#{i}"
      end
    end
  end
end

```

**Comment by briancain** [comment]
Hi @cuisongliu - By default, private networks are hostonly networks:

https://www.vagrantup.com/docs/virtualbox/networking.html

You are probably noticing the default eth0 NAT network, which is a requirement for VirtualBox machines. If you wish, you can disable it and configure your bridge yourself: https://www.vagrantup.com/docs/networking/public_network.html#disable-auto-configuration

Thanks!
