### ISSUE TITLE
ansible_local provisioner in Vagrant 2.2.5 fails to install Ansible on an Arch, SuSE and FreeBSD guests

### ISSUE THREAD

**Issue by binary-manu** [hashicorp/vagrant#11048]
### Vagrant version

Vagrant 2.2.5

### Host operating system

* Arch Linux x86_64
* Windows 10 1903 64-bit

### Guest operating system
archlinux/archlinux (virtualbox, 2019.08.05)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.provision "ansible_local" do |ansible|
    ansible.install = true
    ansible.playbook = "playbook.yml"
  end
end
```

### Debug output

https://gist.github.com/binary-manu/de9bfcc5ab92ddd687947341e6a010ac

### Expected behavior
The `ansible_local` provisioner should install Ansible on the Arch Linux box.

### Actual behavior
Vagrant fails to install Ansible on the box and bails out. This used to work with Vagrant 2.2.4 against the very same box.

### Steps to reproduce
1. Create a `playbook.yml` files alongside the `Vagrantfile`. This can even be empty: Ansible will fail when trying to execute it but this will prove that it was installed at least;
2. `vagrant up` the provided `Vagrantfile`.

**Comment by binary-manu** [comment]
I have updated the issue after testing it under Windows 10. it gives the same error.
I also added a step to reproduce in order to create a (possible empty) playbook file.

**Comment by mnarrell** [comment]
I see this as well..

**Comment by skoenen** [comment]
Same situation on:

Archlinux: `5.3.7-arch1-1-ARCH`
Vagrant: `2.2.6`
Ruby: `ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]`

Image: `archlinux/archlinux (virtualbox, 2019.04.05)`
Image: `archlinux/archlinux (virtualbox, 2019.10.02)`

```
/opt/vagrant/embedded/gems/gems/vagrant-2.2.6/plugins/provisioners/ansible/cap/guest/arch/ansible_install.rb:10:in 'ansible_install': wrong number of arguments (given 5, expected 4) (ArgumentError)
```

**Comment by gildegoma** [comment]
Renaming the issue, as the same bug (introduced by ) affects `freebsd` and `suse` guests.

Bug fix is coming...
