### ISSUE TITLE
Serial port provisioning

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#11041]
For legacy guests without sshd available, another way for users to customize the machines would be through inline shell commands over serial (e.g. COM1, COM2, ...) ports.

http://www.vcfed.org/forum/archive/index.php/t-5210.html

Could we get support for serial port provisioning in the inline shell?

**Comment by briancain** [comment]
Hi @mcandre - as mentioned before, this is not something that could be worked on by the Vagrant team any time soon. I recommend writing your own plugin for these features...thanks!
