### ISSUE TITLE
"No usable default provider"  Though VAGRANT_DEFAULT_PROVIDER is defined to docker, seems to be due to "password" argument

### ISSUE THREAD

**Issue by allan-simon** [hashicorp/vagrant#11051]
### Vagrant version
Vagrant 2.2.4
Vagrant 2.2.5                                                                                                                                                                
### Host operating system
Ubuntu 18.10 cosmic
Ubuntu 18.04

### Guest operating system
We're using docker

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 expandtab :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
Vagrant.configure(2) do |config|

  config.vm.define "dev", primary: true do |app|
    app.vm.provider "docker" do |d|
      d.username = "foobar"
      d.password = "foobar"  # <- commenting this line make it "works"
      d.image = "registry.example.com/foo/bar"
    end
  end
end

```
### Debug output
https://gist.github.com/allan-simon/83469293f0c23a6aef9c464d42a44b2f
### Expected behavior

it should connect to the docker registry, and pull the image using the given credentials 

### Actual behavior

it fails with the error message 
```
No usable default provider could be found for your system.
```

### Steps to reproduce
1.  copy the vagrantfile
2.  vagrant up
3.   the bug error message above  appears

Note that  it seems very specific to  the "password" argument , if we comment it out, it "works"

On the other side , if we install virtualbox, it works too , but it should not be required as before when we were using public images, we were able to use only vagrant+docker without virtualbox

**Comment by briancain** [comment]
Thanks @allan-simon - I was able to reproduce this. Seems like a bug to me.

**Comment by allan-simon** [comment]
awesome, thanks a lot :)
