### ISSUE TITLE
vagrant rpms are not published in a repository

### ISSUE THREAD

**Issue by ssbarnea** [hashicorp/vagrant#11070]
Apparently there is no vagrant (yum/dnf) repository for installing vagrant, which makes its deployment and maintenance (update) much harder and non-standard.

For example Virtualbox, provides such repositories and it can easily be upgraded when needed.

As you are already publishing the rpms, it should be very easy to also expose them a repository.

Apparently I am not the only one that raised this bug as I was able to find https://github.com/hashicorp/vagrant/issues/3262 which was closed for no clear reason. 

RPMs are supposed to be distributed via repositories and is clear a vagrant bug the fact that it does not have a repository. How is this achieved is an implementation detail.

**Comment by chkpnt** [comment]
> RPMs are supposed to be distributed via repositories and is clear a vagrant bug the fact that it does not have a repository.

I disagree. It's up to HashiCorp, if they want to provide repositories or not, but this shouldn't be called a bug.

**Comment by ssbarnea** [comment]
A very good example of third-party package publication as a repository is VirtualBox which happens to be related to vagrant too. Example instructions https://linuxconfig.org/how-to-install-virtualbox-on-centos-8-linux include

* how to add repository
* how to install package

**Comment by mafalb** [comment]
Not having a repo is bad from a sysadmins perspective. Checking for updates is more difficult as it needs to be, signing key is more complicated than it needs to be. Please provide package manager repositories.

**Comment by soapy1** [comment]
Vagrant rpms are now available from the hashicorp rpm repo. See the downloads page for more info https://developer.hashicorp.com/vagrant/downloads.
