### ISSUE TITLE
No guest IP was given to the Vagrant core NFS helper.

### ISSUE THREAD

**Issue by henning** [hashicorp/vagrant#11079]
### Vagrant version

$ vagrant -v
Vagrant 2.2.5

### Host operating system

Mac OS 10.14.16

### Guest operating system

Box used is 'debian/buster64' version '10.0.0'

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provider "virtualbox" do |vb|
    host = RbConfig::CONFIG['host_os']
    if host =~ /darwin/
        cpus = `sysctl -n hw.ncpu`.to_i
        mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
    elsif host =~ /linux/
        cpus = `nproc`.to_i
        mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
    else
        cpus = 2
        mem = 1024
    end
    vb.customize ["modifyvm", :id, "--memory", mem]
    vb.customize ["modifyvm", :id, "--cpus", cpus]
    vb.customize ["modifyvm", :id, "--ioapic", "on" ]
  end
  config.vm.synced_folder "../..", "/work", nfs:true
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 8888, host: 9998
  config.vm.network "forwarded_port", guest: 80, host: 9999
end
```

### Debug output

https://gist.github.com/henning/eb3ad6bfc44585586fa34bc031ed0b5c

### Expected behavior

VM started and /work mounted via NFS

### Actual behavior

The message from subject here is shown, and that it should be reported as a bug.

### Steps to reproduce

1. With the Vagrantfile given above, run "vagrant up"

### References

There are many similar issues, all are closed, but the issue still occurs.

- https://github.com/hashicorp/vagrant/issues?utf8=%E2%9C%93&q=%22No+guest+IP+was+given+to+the+Vagrant+core+NFS+helper.%22

**Comment by henning** [comment]
After an upgrade of the OS inside the VM and a reboot it worked:

Inside the VM:

```
apt update
apt dist-upgrade
```

In my project dir on the host:

```
vagrant reload
```

**Comment by deviantintegral** [comment]
I'm seeing the same issue on `ubuntu/bionic64`. A `dist-upgrade` doesn't solve it. Reverting this config to Ubuntu 16.04 worked for me.

```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
end
```
