### ISSUE TITLE
If logged in vagrant machine, activating wifi or VPN connection terminate the ssh session abruptly

### ISSUE THREAD

**Issue by Yivan** [hashicorp/vagrant#11081]
### Vagrant version
Vagrant 2.2.5 (latest one at this date)

### Host operating system
Windows 10 Pro (up to date)
Hyper-V provider is used.

### Guest operating system
Debian 10 stable

### Expected behavior
Connect to a network (wifi) or to a VPN should not terminate abruptly the ssh session.
Same effect by putting widows in sleep mode or hibernating.

### Actual behavior
The ssh session temrinate abruptly if connecting to a network (wifi) or vpn is done, or sleep/hibernate windows.

### Steps to reproduce
With the host disconnected: vagrant up && vagrant ssh
Connect on the wifi
Ssh connection temrinate abrubtly and go back to the host shell. `client loop: send disconnect: Connection reset by peer` message is displayed in the host shell.

**Comment by briancain** [comment]
Hey there @Yivan - This is not something that Vagrant can actually handle. When you run `vagrant ssh` it executes your local ssh binary to log into the virtual machine. What you are experiencing is something outside of Vagrants control. You should also experience this behavior if you ssh into the box yourself as well. Apologies for this!

**Comment by Yivan** [comment]
Yes you are totally right, thanks for your answer !
