### ISSUE TITLE
first time install getting message "Failed to connect to hashicorp-files.hashicorp.com port 443: Timed out"

### ISSUE THREAD

**Issue by davidcheever** [hashicorp/vagrant#11087]
Tried it several times today, same issue each time. 

Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
This is the operating system that you run locally.

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by briancain** [comment]
@davidcheever  - Hey there, it looks like you are using an old box with a deprecated box URL that no longer exists. I recommend removing it and finding a new box on [Vagrant Cloud](https://vagrantcloud.com). Thanks!

**Comment by davidcheever** [comment]
I am a Windows developer looking to learn PHP/Wordpress development. I was given the command below to set up a website on my Windows PC.
(source:) https://premium.wpmudev.org/blog/wordpress-development-beginners-php/

curl -L -o "install.sh" http://bit.ly/1hBfq57 && curl -L -o "Vagrantfile" http://bit.ly/1mE3Qt9 && vagrant up

Is there a better URL to download the OS?  Thanks for any help.

**Comment by briancain** [comment]
@davidcheever - This is where that box lives now: https://app.vagrantup.com/hashicorp/boxes/precise64

You can use that with your Vagrantfile, you shouldn't need the box_url option.

**Comment by davidcheever** [comment]
thanks
