### ISSUE TITLE
The same ip are set for the public network when dhcp is enabled

### ISSUE THREAD

**Issue by tarmacmonsterg** [hashicorp/vagrant#11091]
Vagrant 2.2.5

I have problem. When I create few VM's and set bridge network for this VM's, all VM's get same IP address. 

Each VM has a different MAC address. If you manually update the IP on the VM, then it receives a normal new IP. But after the vagrant reload, the IP returns.
OS host: Ubuntu 18.04
Guest OS: Ubuntu 18.04
Hypervisor: VirtualBox

**Comment by tarmacmonsterg** [comment]
Vagrantfile Example:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "api" do |api|
    api.vm.box = "cs-ubuntu18"
    api.vm.network "public_network", bridge: "enp5s0", auto_config: false
    api.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end

  config.vm.define "apiexplorer" do |apiexplorer|
    apiexplorer.vm.box = "cs-ubuntu18"
    apiexplorer.vm.network "public_network", bridge: "enp5s0", auto_config: false
    apiexplorer.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

  config.vm.define "sofit" do |sofit|
    sofit.vm.box = "cs-ubuntu18"
    apiexploler.vm.network "public_network", bridge: "enp5s0", auto_config: false
    sofit.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

  config.vm.provision "docker", type: "ansible", run: "never" do |s|
    s.playbook = "./docker-install.yml"
  end

end

```

**Comment by briancain** [comment]
Hey there @tarmacmonsterg - This is because you are disabling auto_config on your network interface. This option means that you'll be the one in charge of setting up the interface rather than Vagrant. You should either have a shell provisioner to set up the interface for you, or remove the option and allow Vagrant to configure the interface. https://www.vagrantup.com/docs/networking/public_network.html#disable-auto-configuration

Thanks!

**Comment by tarmacmonsterg** [comment]
Also it doesn't work with auto config. First time, when I created vms, I use auto config (with DHCP). And when I start all vms, they took same ip adrress.

Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "api" do |api|
    api.vm.box = "cs-ubuntu18"
    api.vm.network "public_network", bridge: "enp5s0"
    api.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

  config.vm.define "apiexplorer" do |apiexplorer|
    apiexplorer.vm.box = "cs-ubuntu18"
    apiexplorer.vm.network "public_network", bridge: "enp5s0"
    apiexplorer.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end

  config.vm.define "sofit" do |sofit|
    sofit.vm.box = "cs-ubuntu18"
    sofit.vm.network "public_network", bridge: "enp5s0"
    sofit.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
end
```

Interface output:
* api
```
$ vagrant ssh api -c "ifconfig enp0s8"
enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.22  netmask 255.255.252.0  broadcast 192.168.11.255
        inet6 fe80::a00:27ff:fe93:50c4  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:93:50:c4  txqueuelen 1000  (Ethernet)
        RX packets 22066  bytes 2084502 (2.0 MB)
        RX errors 0  dropped 120  overruns 0  frame 0
        TX packets 23  bytes 3313 (3.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

* apiexplorer:
```
$ vagrant ssh apiexplorer -c "ifconfig enp0s8"
enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.22  netmask 255.255.252.0  broadcast 192.168.11.255
        inet6 fe80::a00:27ff:fe0d:f3ec  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:0d:f3:ec  txqueuelen 1000  (Ethernet)
        RX packets 20744  bytes 1961417 (1.9 MB)
        RX errors 0  dropped 122  overruns 0  frame 0
        TX packets 22  bytes 3172 (3.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

* sofit:
```
$ vagrant ssh sofit -c "ifconfig enp0s8"
enp0s8: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.22  netmask 255.255.252.0  broadcast 192.168.11.255
        inet6 fe80::a00:27ff:fea7:1e32  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:a7:1e:32  txqueuelen 1000  (Ethernet)
        RX packets 19795  bytes 1872350 (1.8 MB)
        RX errors 0  dropped 123  overruns 0  frame 0
        TX packets 22  bytes 3172 (3.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by briancain** [comment]
It works for me on Ubuntu using VirtualBox with a proper interface that has an internet connection:

```
brian@localghost:vagrant-sandbox % iwconfig                                                              ±[●][master]
wlp4s0    IEEE 802.11  ESSID:"<REMOVED>"
          Mode:Managed  Frequency:5.765 GHz  Access Point: <REMOVED>
          Bit Rate=650 Mb/s   Tx-Power=22 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          Link Quality=59/70  Signal level=-51 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:57   Missed beacon:0

brian@localghost:vagrant-sandbox % ifconfig                                                              ±[●][master]
wlp4s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.1.152  netmask 255.255.255.0  broadcast 10.0.1.255
        inet6 fe80::53eb:d99a:55dc:8f4c  prefixlen 64  scopeid 0x20<link>
        ether 34:e1:2d:0f:92:86  txqueuelen 1000  (Ethernet)
        RX packets 21576  bytes 18123424 (18.1 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9039  bytes 2375734 (2.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```ruby
(1..3).each do |i|
  config.vm.define "hashicorp-#{i}" do |h|
    h.vm.box = "hashicorp/bionic64"
    h.vm.provider :virtualbox
    h.vm.network :public_network, bridge: "wlp4s0"
  end
end
```

Notice that `eth1` is the interface for the public network for each guest.

```
brian@localghost:vagrant-sandbox % vagrant ssh -c "ip addr" hashicorp-1;vagrant ssh -c "ip addr" hashicorp-2;vagrant ssh -c "ip addr" hashicorp-3
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:bb:14:75 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86301sec preferred_lft 86301sec
    inet6 fe80::a00:27ff:febb:1475/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:bd:7a:0c brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.225/24 brd 10.0.1.255 scope global dynamic eth1
       valid_lft 1706sec preferred_lft 1706sec
    inet6 fe80::a00:27ff:febd:7a0c/64 scope link
       valid_lft forever preferred_lft forever
Connection to 127.0.0.1 closed.
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:bb:14:75 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86333sec preferred_lft 86333sec
    inet6 fe80::a00:27ff:febb:1475/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:75:23:e5 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.226/24 brd 10.0.1.255 scope global dynamic eth1
       valid_lft 1735sec preferred_lft 1735sec
    inet6 fe80::a00:27ff:fe75:23e5/64 scope link
       valid_lft forever preferred_lft forever
Connection to 127.0.0.1 closed.
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:bb:14:75 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86366sec preferred_lft 86366sec
    inet6 fe80::a00:27ff:febb:1475/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:ce:47:20 brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.227/24 brd 10.0.1.255 scope global dynamic eth1
       valid_lft 1783sec preferred_lft 1783sec
    inet6 fe80::a00:27ff:fece:4720/64 scope link
       valid_lft forever preferred_lft forever
Connection to 127.0.0.1 closed.
```

Do you have a full debug log showing the result of bringing up your VMs, as well as the kind of information I posted above?

**Comment by briancain** [comment]
Another potential reason for why you might be getting the same IP address for each guest is an issue with how your Vagrant box is configured. Have you tried using a different box? Such as `hashicorp/bionic64` or `bento/ubuntu-18.04`?

**Comment by tarmacmonsterg** [comment]
Probably I have problem with my system, because this Vagrantfile works fine on another PC. I have not yet found a reason. I analyzed the log, but did not find anything supernatural. But interestingly, if I just start the VM through VirtualBox, the network works fine.

**Comment by tarmacmonsterg** [comment]
> It works for me on Ubuntu using VirtualBox with a proper interface that has an internet connection:
> 
> ```
> brian@localghost:vagrant-sandbox % iwconfig                                                              ±[●][master]
> wlp4s0    IEEE 802.11  ESSID:"<REMOVED>"
>           Mode:Managed  Frequency:5.765 GHz  Access Point: <REMOVED>
>           Bit Rate=650 Mb/s   Tx-Power=22 dBm
>           Retry short limit:7   RTS thr:off   Fragment thr:off
>           Power Management:on
>           Link Quality=59/70  Signal level=-51 dBm
>           Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
>           Tx excessive retries:0  Invalid misc:57   Missed beacon:0
> 
> brian@localghost:vagrant-sandbox % ifconfig                                                              ±[●][master]
> wlp4s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 10.0.1.152  netmask 255.255.255.0  broadcast 10.0.1.255
>         inet6 fe80::53eb:d99a:55dc:8f4c  prefixlen 64  scopeid 0x20<link>
>         ether 34:e1:2d:0f:92:86  txqueuelen 1000  (Ethernet)
>         RX packets 21576  bytes 18123424 (18.1 MB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 9039  bytes 2375734 (2.3 MB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> ```
> 
> ```ruby
> (1..3).each do |i|
>   config.vm.define "hashicorp-#{i}" do |h|
>     h.vm.box = "hashicorp/bionic64"
>     h.vm.provider :virtualbox
>     h.vm.network :public_network, bridge: "wlp4s0"
>   end
> end
> ```
> 
> Notice that `eth1` is the interface for the public network for each guest.
> 
> ```
> brian@localghost:vagrant-sandbox % vagrant ssh -c "ip addr" hashicorp-1;vagrant ssh -c "ip addr" hashicorp-2;vagrant ssh -c "ip addr" hashicorp-3
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host
>        valid_lft forever preferred_lft forever
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
>     link/ether 08:00:27:bb:14:75 brd ff:ff:ff:ff:ff:ff
>     inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
>        valid_lft 86301sec preferred_lft 86301sec
>     inet6 fe80::a00:27ff:febb:1475/64 scope link
>        valid_lft forever preferred_lft forever
> 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
>     link/ether 08:00:27:bd:7a:0c brd ff:ff:ff:ff:ff:ff
>     inet 10.0.1.225/24 brd 10.0.1.255 scope global dynamic eth1
>        valid_lft 1706sec preferred_lft 1706sec
>     inet6 fe80::a00:27ff:febd:7a0c/64 scope link
>        valid_lft forever preferred_lft forever
> Connection to 127.0.0.1 closed.
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host
>        valid_lft forever preferred_lft forever
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
>     link/ether 08:00:27:bb:14:75 brd ff:ff:ff:ff:ff:ff
>     inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
>        valid_lft 86333sec preferred_lft 86333sec
>     inet6 fe80::a00:27ff:febb:1475/64 scope link
>        valid_lft forever preferred_lft forever
> 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
>     link/ether 08:00:27:75:23:e5 brd ff:ff:ff:ff:ff:ff
>     inet 10.0.1.226/24 brd 10.0.1.255 scope global dynamic eth1
>        valid_lft 1735sec preferred_lft 1735sec
>     inet6 fe80::a00:27ff:fe75:23e5/64 scope link
>        valid_lft forever preferred_lft forever
> Connection to 127.0.0.1 closed.
> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
>     link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
>     inet 127.0.0.1/8 scope host lo
>        valid_lft forever preferred_lft forever
>     inet6 ::1/128 scope host
>        valid_lft forever preferred_lft forever
> 2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
>     link/ether 08:00:27:bb:14:75 brd ff:ff:ff:ff:ff:ff
>     inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
>        valid_lft 86366sec preferred_lft 86366sec
>     inet6 fe80::a00:27ff:febb:1475/64 scope link
>        valid_lft forever preferred_lft forever
> 3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
>     link/ether 08:00:27:ce:47:20 brd ff:ff:ff:ff:ff:ff
>     inet 10.0.1.227/24 brd 10.0.1.255 scope global dynamic eth1
>        valid_lft 1783sec preferred_lft 1783sec
>     inet6 fe80::a00:27ff:fece:4720/64 scope link
>        valid_lft forever preferred_lft forever
> Connection to 127.0.0.1 closed.
> ```
> 
> Do you have a full debug log showing the result of bringing up your VMs, as well as the kind of information I posted above?

Here is the log.а
[vagrant.log](https://github.com/hashicorp/vagrant/files/3749804/vagrant.log)
