### ISSUE TITLE
`process_public_network': undefined method `prefix' 

### ISSUE THREAD

**Issue by arnaldoperez** [hashicorp/vagrant#11094]
### Vagrant version
2.2.5

### Host operating system
ZorinOs 15 - Based on Ubuntu Bionic-Beaver

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Using the default file, with some uncommented lines and a repo installation on the provision
Vagrant.configure("2") do |config|
  config.vm.box = "tknerr/baseimage-ubuntu-16.04"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.network "public_network"

 
  config.vm.provision "shell", inline: <<-SHELL
    curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    sudo apt-get update
    sudo apt-get install -y nodejs
  SHELL
end

```

### Debug output
https://gist.github.com/arnaldoperez/8051ccdba6ba932a7a282590c24c4685

### Expected behavior
Container up and working

### Actual behavior
Error related with the bridge interface setup

### Steps to reproduce
1. Set enviroment variable $VAGRANT_DEFAULT_PROVIDER="docker"
2. vagrant init
3. Update the Vagrantfile as described
4. vagrant up

**Comment by arnaldoperez** [comment]
shouldn't this go to a hotfix kind of branch to get into a minor update as soon as posible?? it is a bug that comes by default in vagrant....

**Comment by briancain** [comment]
Hey there @arnaldoperez - I find it interesting in your debug log that Vagrant is reporting 3 identically named bridge interfaces:

```
Available bridged network interfaces:
1) wlp2s0
2) docker0
3) wlp2s0
4) wlp2s0
```

Have you tried restarting your machine and bringing up the container afterwords? What is the result of running `ip addr` on your machine after restarting?

Also, please provide us with the full debug log with the `--debug` flag. Thanks.

**Comment by briancain** [comment]
@arnaldoperez - I was able to reproduce the issue on a vm, not my host machine :thinking: Anyway we will try to get a fix soon! Thanks for the report.
