### ISSUE TITLE
cpu increased suddenly while wake up the os 

### ISSUE THREAD

**Issue by pain400** [hashicorp/vagrant#11095]
### Vagrant version
Vagrant 2.2.0

### Host operating system
macOS Mojave
10.14

### VirtualBox
5.2.20 r125813 (Qt5.6.3)

### Guest operating system
centos7
3.10.0-957.12.2.el7.x86_64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
  {
    :name => "s1",
    :eth1 => "192.168.1.10",
    :mem => "2048",
    :cpu => "2"
  }
]

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  boxes.each do |box|
    config.vm.define box[:name] do |config|
      config.vm.hostname = box[:name]

      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", box[:mem]]
        v.customize ["modifyvm", :id, "--cpus", box[:cpu]]
        v.name = box[:name]
      end

      config.vm.network "private_network", ip: box[:eth1]
    end
  end
end
```

### Expected behavior
I hope cpu usage is not so high

### Actual behavior
The process VBoxHeadless uses 100% of cpu

### Steps to reproduce
1. start virtual machine by executing command `vagrant up`
2. At first time, cpu usage of process VBoxHeadless is only 1% - 5%
3. And second, I let the computer sleep
4. After a while, I wake up the computer again, and the cpu usage of process VBoxHeadless reach to 95% - 100%

**Comment by briancain** [comment]
Hi @pain400 - The behavior you are describing is from the VirtualBox tool, `VBoxHeadless`. Vagrant uses this command line tool to manage VirtualBox VMs, but it is not something Vagrant owns. If you have general questions about VirtualBox or its command line tool VBoxHeadless, you could ask on our Google group Vagrant Up, or go to the VirtualBox forums. Thanks!
