### ISSUE TITLE
 Allow using a config file instead of environment variables

### ISSUE THREAD

**Issue by TomyLobo** [hashicorp/vagrant#11110]
Setting environment variables reliably on Linux is pretty annoying.
Why not allow a .vagrantrc file or something similar?

https://github.com/bkeepers/dotenv this seems like an easy way to get environment variables from a file.
It says it's only for development, but I don't see why you can't use this for production code.
The place where you would add the call to Dotenv.load is in bin/vagrant, after the handler for the  --debug-timestamp flag.

Suggested places for the config file:
- ~/.vagrantrc
- ~/.vagrant.d/env

VAGRANT_CHECKPOINT_DISABLE is the variable that prompted me to write this suggestion, btw.

### Vagrant version
2.2.5, but affects any

### Host operating system
Linux, but affects any

### Guest operating system
N/A

### Vagrantfile
This is a suggestion, not a bug report.

### Debug output
This is a suggestion, not a bug report.

### Expected behavior
This is a suggestion, not a bug report.

### Actual behavior
This is a suggestion, not a bug report.

### Steps to reproduce
This is a suggestion, not a bug report.

### References
None.

**Comment by chrisroberts** [comment]
Hi there. Thank you for taking the time to make this feature request. Unfortunately, this is not a feature that we would integrate directly into Vagrant. Depending on the local shell you are using, you can define variables within rc or profile files (like `.bashrc` and `.bash_profile` for bash). 

If you would like to use a local file to define environment variables, tools like [direnv](https://github.com/direnv/direnv) solve this very well.

Cheers!

**Comment by TomyLobo** [comment]
What I'm getting at is that there has been some proliferation of environment variables, some necessary for everyday operation of Vagrant.
My colleagues use Windows and I had to hook them up with certain environment variables:
- VAGRANT_HOME - so they don't litter their C: drive
- VAGRANT_PREFER_SYSTEM_BIN=1 - so they can use vagrant from within Cygwin/Babun (Vagrant's msys ssh binary doesn't play well with Cygwin/Babun)

And now VAGRANT_CHECKPOINT_DISABLE so their Vagrant doesn't try to phone home every time they run any Vagrant command.
When will this end and can't you find a better place to store global configuration for Vagrant?

**Comment by Yivan** [comment]
I didn't know direnv (https://github.com/direnv/direnv) but it can be a solution on linux yes. It work on Windows too it seems, so for people interested please see: https://github.com/direnv/direnv/issues/343#issuecomment-463502726

@chrisroberts Can you provide us some insight why it won't be implemented in Vagrant please? It will be more developer friendly. Docker and more and more tools do it and it is very used/know by developpers to easily set env variable without having to rely on other packages / system global config.
