### ISSUE TITLE
Vagrant can't start network device

### ISSUE THREAD

**Issue by urajio** [hashicorp/vagrant#11114]
After update MacOS to Catalina, vagrant/fusion can't start vm:

```
vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Checking if box 'centos/7' version '1905.1' is up to date...
==> default: Verifying vmnet devices are healthy...
The VMware network device 'vmnet1' can't be started because
its routes collide with another device: ''. Please
either fix the settings of the VMware network device or stop the
colliding device. Your machine can't be started while VMware
networking is broken.

Routing to the IP '172.16.109.0' should route through 'vmnet1', but
instead routes through ''.
```

### Vagrant version

Vagrant 2.2.5

### Host operating system

This is the operating system that you run locally.
MacOS Catalina

### Guest operating system

Centos 7
### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 3306, host: 3306, host_ip: "127.0.0.1"
  # my long config
end
```

### Debug output
https://gist.github.com/urajio/b99abb548b0f3aabe8e62f984d80309e

**Comment by chrisroberts** [comment]
Hi there. The vagrant-vmware-fusion plugin has been deprecated and is no longer maintained. Please see installation instruction here for upgrading to the vagrant-vmware-desktop plugin:

https://www.vagrantup.com/docs/vmware/installation.html

After upgrading, and ensuring that VMware Fusion is running correctly, if the error persists, please create a new issue with an updated debug output gist and I'll be happy to have a look.

Cheers!

**Comment by urajio** [comment]
After upgrading to vagrant-vmware-desktop, destroy/re-create vm, notebook reboot, Fusion network config cleanup, vmnet-cli start/stop
It works!

**Comment by markdrayton247** [comment]
I'm trying to follow the same path but getting errors reporting a clash of ports already in use. Could you please expand on what you mean by 'Fusion network config cleanup' ?

thank you
