### ISSUE TITLE
Vagrant broken in Fedora 30 (libvirt)

### ISSUE THREAD

**Issue by rvalle** [hashicorp/vagrant#11122]
### Vagrant version

Vagrant 2.2.5 (Distributed with fedora @updates)

### Host operating system
Fedora 30

### Guest operating system
Debian stretch

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|

  # disable default folder sync
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.box = "debian/stretch64"

  # VM Resources, allow nested virtualization
  config.vm.provider "libvirt" do |l|
    l.nested = true
    l.cpu_mode = "host-model"
    l.memory = 1024
    l.cpus   = 1
    l.storage :file, :size => '10G'
  end

end

```

### Debug output

https://gist.github.com/rvalle/091ad3c8d69383aca25b2f43196bfe90

### Expected behavior
Should start the VM
### Actual behavior
Crashes

### Steps to reproduce
1. dnf install vagrant-libvirt
2. vagrant up
3. Just crashes

### Other
I believe the issue is related to gem dependency versioning. I suspect the gem  fog-core, but I have no idea as I am not a ruby developer.

**Comment by briancain** [comment]
Hey there @rvalle - According to the stacktrace, this just seems to be a bug with the `vagrant-libvirt` provider:

> /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/create_domain.rb:156:in `block in call': undefined method `+' for nil:NilClass (NoMethodError)

I recommend opening an issue with that project instead, thanks!
