### ISSUE TITLE
Ansible provisioner failed on vagrant up, on retry, it says Machine already provisioned

### ISSUE THREAD

**Issue by Iliyass** [hashicorp/vagrant#11123]
I have an ansible playbook and have been hooked in vagrant file, when I try to execute `vagrant up` my ansible playbook failed (which is totally ok) and it throws ansible errors, which is good, but when I retry to run `vagrant up` I got no error again, and it says the machine is already provisioned, which it shouldn't, but in `vagrant provision` still it shows the ansible error.

### Vagrant version
Vagrant 2.1.1

### Host operating system
macOS 10.14.6 (18G87)

### Guest operating system
VirtualBox 5.2.32

### Vagrantfile
```ruby
PROJECTS = ["project1", "project2"]
PROJECT_NAME = ARGV[1]
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    for project in PROJECTS do
        config.vm.define project do |config|
            config.vm.box = "ubuntu/trusty64"

            # vagrant-hostsupdater plugin to add hostnames
            config.hostsupdater.remove_on_suspend = true
            config.hostsupdater.aliases = ["www.localhost.com"]

            # message to show at the end
            config.vm.post_up_message = "You can now open your browser at www.localhost.com"
            config.vm.network :forwarded_port, guest: 80, host: 8080
            config.vm.network "private_network", ip: "192.168.3.10"
            config.vm.hostname = "localhost.com"
            config.vm.synced_folder "..", "/var/www/myproject/"
            config.ssh.forward_agent = true
            config.ssh.username = "vagrant"
            config.ssh.password = "vagrant"

            config.vm.provision "ansible" do |ansible|
                ansible.inventory_path = "hosts"
                ansible.playbook = "vagrant.yml"
                ansible.limit = 'all'
                ansible.verbose = "vvvv"
                ansible.start_at_task = "Supervisord - config file"
                #ansible.tags = "upgrade"
                ansible.extra_vars = {
                  project_name: "myproject"
                }
            end

            config.vm.provider "virtualbox" do |v|
                v.memory = 4096
                v.cpus = 2
            end
        end
    end
end
```

### Debug output
https://gist.github.com/Iliyass/f80f1e88b2f16bd154e074a4c04cff31

### Expected behavior
if ansible playbook failed, if `vagrant up` executed again, it should throw an error

### Actual behavior
no errors show up on the second `vagrant up` execution

### Steps to reproduce
1. run `vagrant up` (should throw error on ansible playbook)

**Comment by briancain** [comment]
Hello @Iliyass - You are describing the expected behavior of Vagrant provisioners. Provisioners are only run once, even if those provisioners fail. This is by design, from the [Vagrant Docs](https://www.vagrantup.com/docs/provisioning/basic_usage.html#run-once-always-or-never):

> By default, provisioners are only run once, during the first vagrant up since the last vagrant destroy, unless the --provision flag is set, as noted above.

If you want the provisioner to always run, you can set it as such. Or if your provisioner has failed, you can be explicit and run it with the `--provision` or `--provision-with` flags. Thanks!

**Comment by Iliyass** [comment]
@briancain thank you for your help
