### ISSUE TITLE
Unable to install activesupport plugin

### ISSUE THREAD

**Issue by gwritz** [hashicorp/vagrant#11125]
### Vagrant version
2.2.5 (installed via homebrew)

### Host operating system
macOS Catalina

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
This looks to me like a failure to parse the ruby version, hence I am showing the full non-debug output here as it is short.

```bash
~ vagrant plugin install activesupport
Installing the 'activesupport' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

activesupport requires Ruby version >= 2.5.0.

~ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
```

### Expected behavior
What should have happened? The plugin should have been installed as the version of ruby is >= 2.5.0

### Actual behavior
What actually happened? The plugin was not installed. The error says the version isn't >= 2.5.0, but it is. Seems like it is trying to parse 5p114 as a number.

### Steps to reproduce
1. vagrant plugin install activesupport

**Comment by briancain** [comment]
Hi @gwritz - `activesupport` is not a vagrant plugin. Currently in the official Vagrant installer, we do not ship with Ruby >= 2.5.0. If you wish to use this gem in your environment for development purposes with Vagrant, you might want to run Vagrant from source, but that is not supported with the official installer or with `vagrant plugin install`. Thanks!

**Comment by Mte90** [comment]
I have the same issue on debian, seems an issue by a dependence of a plugin.
I installed the package as root on my machine but I am still getting this issue.

**Comment by Mte90** [comment]
Seems that update bundler on debian fixed the issue

**Comment by secureideas** [comment]
Should this bug be closed?   While yes activesupport is not a plugin, the error is with the installer for MacOS.  Since it was fixed in the debian version, it seems reasonable to fix it here as well?
