### ISSUE TITLE
The docker inside the vagrant does not clean the images

### ISSUE THREAD

**Issue by pashak09** [hashicorp/vagrant#11131]
the docker inside the vagrant does not clean the image.
Install vm "ubuntu / xenial64"
install docker
sudo apt-get install docker.io -y
download any image and then delete it
docker rmi $ (docker images -q)
Docker writes that resources are freed, but this is not so.

**Comment by briancain** [comment]
HI there @pashak09 - From your description, it sounds like you are simply using docker inside a virtual machine. Vagrant does have ways of managing docker for you through provisioners, but it doesn't sound like you are using that. I recommend using that instead if you wish to have Vagrant control docker on your guest. Thanks!
