### ISSUE TITLE
vagrant cloud auth logout doesn't appear to work

### ISSUE THREAD

**Issue by tas50** [hashicorp/vagrant#11136]
### Vagrant version
2.2.6

### Host operating system
macOS 10.15

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
```
❰tsmith❙~❱✔≻ vagrant cloud auth logout
You are logged out.
❰tsmith❙~❱✔≻ vagrant cloud auth whoami
Currently logged in as tas50
```
### Expected behavior
After running vagrant cloud auth logout I should be logged out

### Actual behavior
I am still logged in

### Steps to reproduce
1. Run: vagrant cloud auth logout
2. Run: vagrant cloud auth whoami and note you're still logged in

**Comment by briancain** [comment]
Hi @tas50 - When you run `vagrant cloud auth logout`, can you confirm that your token file has been removed? For example, by default it exists at `~/.vagrant.d/data/vagrant_login_token`.

If you are making vagrant requests with your token exported as an environment variable, you will still be "logged in". The logout command simply deletes your local token file in the Vagrant data directory.

Thanks!

**Comment by tas50** [comment]
Yep that's it. Thanks for the reply
