### ISSUE TITLE
Multiple-machines not loaded within the Vagrantfile load order.

### ISSUE THREAD

**Issue by SagivZ** [hashicorp/vagrant#11130]
### Vagrant version

2.2.5

### Host operating system 

Windows 10 64bit

### Guest operating system 

ubuntu\xenial64

### Vagrantfile - pasted below -

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "consul_installation.sh"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
	  vb.cpus = 1
  end
  config.vm.define "sdp" do |sdp|
    sdp.vm.hostname = "consul-server"
    sdp.vm.network "private_network", ip: "192.168.10.2"
	sdp.vm.provision "file", source: "server_config.json", destination: "/tmp/config.json"
    sdp.vm.provision :shell, path: "consul_server_configuration.sh"
  end
  config.vm.define "web" do |web|
    web.vm.hostname = "apache-server"
    web.vm.network "private_network", ip: "192.168.10.3"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "forwarded_port", guest: 8500, host: 8500
    web.vm.provision :shell, path: "apache_installation.sh"
	web.vm.provision "file", source: "client_config.json", destination: "/tmp/config.json"
	web.vm.provision :shell, path: "consul_member_join.sh"
  end
end
```

### Expected behavior

After configuring multiple-machine within a vagrant file.
First machine is a consul server V1.6.1, and the second one is an apache agent with consul agent installed locally.

### Actual behavior

After initiating the 'vagrant up' command, vagrant successfully installing the first box and set it as a consul server mode, the terminal receiving logs the logs of the consul server and do not continue with loading the second box.

[consul_installation.txt](https://github.com/hashicorp/vagrant/files/3733095/consul_installation.txt)
[consul_member_join.txt](https://github.com/hashicorp/vagrant/files/3733096/consul_member_join.txt)
[consul_server_configuration.txt](https://github.com/hashicorp/vagrant/files/3733097/consul_server_configuration.txt)
[server_config.txt](https://github.com/hashicorp/vagrant/files/3733098/server_config.txt)
[apache_installation.txt](https://github.com/hashicorp/vagrant/files/3733099/apache_installation.txt)
[client_config.txt](https://github.com/hashicorp/vagrant/files/3733100/client_config.txt)

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by SagivZ** [comment]
### Debug output

https://gist.github.com/SagivZ/b8dc1787b34d7abf06203f128cf34a84
