### ISSUE TITLE
Unable to mount VirtualBox shared folders - bad mount command

### ISSUE THREAD

**Issue by axcxl** [hashicorp/vagrant#11135]
### Vagrant version
```
vagrant -v
Vagrant 2.2.6
```

### Host operating system
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
```
Other notes:
- Virtualbox version: 6.0.14

### Guest operating system
```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
```

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

    config.vm.box = "axcxl/debian11_xfce"

    config.vm.provider :virtualbox do |vb|
        vb.gui = true
        vb.memory = 4096
        vb.cpus = 4
    end
end
```

### Debug output
https://gist.github.com/axcxl/013474e5dd785c006a0a81d7734ba93b

### Expected behavior
VM boot up without errors, shared folders mounted properly

### Actual behavior
```
==> default: Mounting shared folders...
    default: /vagrant => /home/andreic/vagrant/box_debian11_xfce
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000
,gid=1000 vagrant /vagrant

The error output from the command was:

bash: line 5: $'\E[3J,gid=1000': command not found
```

### Steps to reproduce
1. Using included Vagrantfile do "vagrant up"
2. Wait for command to complete
3. See error. NOTE: VM is up and running ok, just no shared folders are mounted. If mounted manually, shared folders work ok.

**Comment by briancain** [comment]
Hi there @axcxl - From what I can tell reading the debug gist, it seems like your Vagrant box just doesn't have the virtualbox guest tools installed. I would make sure you have those installed, and try bringing up the virtual machine again and see if that solves your issue. Thanks!

**Comment by axcxl** [comment]
Hi @briancain. Thank you for the reply. I've checked the VM and the guest addition tools are installed and working (the VMs screen is resized, shared folders work manually):
```
vagrant@hexiwear:~$ sudo service vboxadd-service status
● vboxadd-service.service
   Loaded: loaded (/opt/VBoxGuestAdditions-6.0.14/init/vboxadd-service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-10-21 23:03:50 EEST; 23s ago
```
```
vagrant@hexiwear:~$ sudo service vboxadd status
● vboxadd.service
   Loaded: loaded (/opt/VBoxGuestAdditions-6.0.14/init/vboxadd; enabled; vendor preset: enabled)
   Active: active (exited) since Mon 2019-10-21 23:03:50 EEST; 44s ago
```

After looking a bit into the debug log and checking the VM, I noticed that the VBoxManage command indeed does not exist on the VM. It only has VBoxControl and this works properly:
```vagrant@hexiwear:~$ sudo /usr/bin/VBoxControl guestproperty get  /VirtualBox/GuestAdd/Version
Oracle VM VirtualBox Guest Additions Command Line Management Interface Version 6.0.14
(C) 2008-2019 Oracle Corporation
All rights reserved.

Value: 6.0.14
```

**Comment by briancain** [comment]
Hey there @axcxl - Apologies for the delay in getting back to you. The CLI command `vboxmanage` should only really exist on the host, fyi. But good to know that it has guest additions at least.

From what I can tell in the debug log, it seems to be an issue with Vagrant trying to build up the proper command to run mount. Thanks again for the report and the extra information!

**Comment by mcrocker** [comment]
Same Problem on 2.2.7 with VB 6.1.4
=======================

I'm seeing a very similar problem with Vagrant 2.2.7 and Virtualbox 6.1.4 with centos/6 1905.01 that did not occur with 6.1.2 last week. 

The problem is that this occurs on a fresh VM before Guest Additions can be installed. 

Work-Around
--------------

Disabling the share in Vagrantfile allows the VM to start, then causes provisioning to fail because files in /vagrant that are expected are not present. At that point a manual `vagrant vbguest --do install` works, then a `vagrant halt` and putting the `override.vm.synced_folder` back into the Vagrantfile and, finally a `vagrant up --provision` can be run... but what a PITA!
