### ISSUE TITLE
Windows 10 Hyper-V: `vagrant powershell` Unable to establish a remote PowerShell connection with the guest.

### ISSUE THREAD

**Issue by vpaladino778** [hashicorp/vagrant#11145]
I'm trying to use `vagrant powershell` but I keep receiving an ' Unable to establish a remote PowerShell connection with the guest.' error. I'm unsure if I am correctly provisioning my windows box. 

### Host operating system
Windows 10 Pro

### Guest operating system
Windows 10 Enterprise Eval 1903
Hyper-V Provider

### Vagrantfile
```ruby
# Disable windows guest machine firewall
$script = <<-SCRIPT
Enable-PSRemoting -SkipNetworkProfileCheck
netsh advfirewall firewall add rule name="WinRM-HTTP" dir=in localport=5985 protocol=TCP action=allow
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.box = "StefanScherer/windows_10"
  config.vm.synced_folder "./my-project", "/my-project"
  config.vm.provision "shell", inline: $script
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

end
```

### Debug output
Here is the basic error message i'm getting
```
PS C:\Vagrant\my-project-hyperv> vagrant powershell
==> default: Detecting if a remote PowerShell connection can be made with the guest...
Unable to establish a remote PowerShell connection with the guest.
Check if the firewall rules on the guest allow connections to the
Windows remote management service.
```
And [here](https://gist.github.com/vpaladino778/e8dd9a03dbcf87a5a29a1d7fc2cef257) is a gist of the debug output. 

### Expected behavior
What should have happened?
Should have received powershell access to the guest machine

### Actual behavior
What actually happened?
Received an error

### Steps to reproduce
1. `vagrant up`
2. `vagrant powershell`

### References
Are there any other GitHub issues (open or closed) that should be linked here?
I haven't found any other github issues relating to this.

**Comment by briancain** [comment]
It looks like your host was just denied access from the debug log....I tried the same vagrant box and I was able to run `vagrant powershell` without an issue. If you remove the provision script, do you see the same behavior?

**Comment by vpaladino778** [comment]
Hi Brian, thanks for your reply. I removed the provisioning script from the Vagrantfile. I then performed a `vagrant halt` followed by a `vagrant up` and then finally a `vagrant powershell`, unfortunately it results in the same result. I'll try on a fresh box as well and see if it works.

**Comment by vpaladino778** [comment]
@briancain So after creating a fresh vagrant environment. I created a new folder, a clean vagrantfile, and used `vagrant up`, i still ran into the same issue.

Here's the vagrantfile i used, with no provisioning:
```
Vagrant.configure("2") do |config|

  config.vm.box = "StefanScherer/windows_10"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

end
```

**Comment by vpaladino778** [comment]
Using the same windows box with a VirtualBox provider, i ran into no issue using `vagrant powershell`. After attempting to `vagrant powershell` on a clean version of the Hyper-V box, i'm running to the same `Unable to establish a remote PowerShell connection with the guest` error. This appears to be exclusively with Hyper-V. 

I don't believe that SMB is being used with the VirutalBox box. So could this be an issue with SMB?

**Comment by briancain** [comment]
@vpaladino778 - I don't think so, but you could try to disable the default share and see if that works for you:

```ruby
config.vm.synced_folder ".", "/vagrant", disabled: true
```

That being said, I was able to use `vagrant powershell` with that box and the hyper-v provider without issue... :thinking:

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
