### ISSUE TITLE
Permission Denied from Windows Hyper-V Shared Folder

### ISSUE THREAD

**Issue by vpaladino778** [hashicorp/vagrant#11140]
My vagrant shared folder is returning Permission denied any time i try to access the folder on the guest machine via `vagrant powershell`

### Vagrant version
Vagrant 2.2.5

### Host operating system
Windows 10 Pro x64

### Guest operating system
Windows 10 Version 1903

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.synced_folder "my-shared-folder/", "C:/Users/vagrant/Documents/my-shared-folder/", group:'www-data', owner:'vagrant', mount_options: ["dmode=775,fmode=644"]
end
```
I tried this vagrantfile as well:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"
  config.vm.synced_folder "my-shared-folder/", "C:/Users/vagrant/Documents/my-shared-folder/"
end
```
As well as one with `type: smb` added to syned_folder
### Debug output
```powershell
[192.168.160.23]: PS C:\Users\vagrant\Documents\my-shared-folder> ls
ls : Access to the path 'C:\Users\vagrant\Documents\my-shared-folder' is denied.
    + CategoryInfo          : PermissionDenied: (C:\Users\vagran...shared-folder:String) [Get-ChildItem], UnauthorizedAccessException
    + FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand
```

### Expected behavior
What should have happened?
The folders contents should have been listed

### Actual behavior
What actually happened?
I received a `Permission denied` error

### Steps to reproduce
1. `vagrant up`
2. `vagrant powershell`
3. `ls my-shared-folder`

**Comment by briancain** [comment]
Hey there @vpaladino778 - What permissions are the `my-shared-folder`? Who has access to it? And what user are you when you connect with `vagrant powershell`? Do you have access to the default shared folder `/vagrant` at all?

**Comment by vpaladino778** [comment]
The folder was created via a `git clone` on the host machines side. I used git clone in the `c:\vagrant\my-project` directory on the host machine. Could working in the C:\ directory be causing permissions issues?

It looks like i don't have access to `c:\vagrant` on the guest machine either (Same issue with permission denied when performing `ls`. 

Here's the console output when i perform `vagrant powershell`, not sure if it's helpful at all:
```
PS C:\Vagrant\my-project> vagrant powershell
==> default: Detecting if a remote PowerShell connection can be made with the guest...
    default: Creating powershell session to 192.168.160.23:5985
    default: Username: vagrant
```

Hopefully i answered all your questions. Thanks for taking the time to respond.

**Comment by briancain** [comment]
@vpaladino778 - If you log into the virtual machine through the GUI, are you able to access those shared folders in powershell as the `vagrant` user, or do you get the same error message?

**Comment by vpaladino778** [comment]
@briancain I just tried it now, it says for `C:\vagrant` that 'The user name or password is incorrect', same with my folder. The username and password on this box is `vagrant` and `vagrant`. Do i have to specify my username and password from my host machine to access it?

**Comment by briancain** [comment]
@vpaladino778 - Yep...if you are logging into Windows through the GUI, the username and password should be `vagrant`/`vagrant`. Since you're using a box I'm not familiar with though, I can't say what it might be if they changed the default. That's up to the box publisher, which could have changed the default settings.

**Comment by briancain** [comment]
@vpaladino778 - If you're not set on that box, I've had lots of good luck using this box with Vagrant in the past: https://app.vagrantup.com/StefanScherer/boxes/windows_10

**Comment by vpaladino778** [comment]
@briancain I think i may have realized my problem (But i have already deleted the old box before being able to test it) When running `vagrant up` towards the end, i get the following output:
```
Vagrant requires administrator access for pruning SMB shares and
may request access to complete removal of stale shares.
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: account.
    default:
    default: Username: vagrant
    default: Password (will be hidden):

Vagrant requires administrator access to create SMB shares and
may request access to complete setup of configured shares.
==> default: Mounting SMB shared folders...
    default: C:/Vagrant/chimera-hyperv => /*****
==> default: Machine already provisioned. Run `***** provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
```

When asking for the username and password, i had been putting in 'vagrant' and 'vagrant'. But I'm realizing now that i think i'm supposed to be using the username/password from my personal host machine. If this is true, i feel like a real bozo

**Comment by briancain** [comment]
Hey @vpaladino778 - Yes! That should be the username and password of your local host account, not the vagrant account on the guest.
