### ISSUE TITLE
Vagrant Commands Slow to Start (Due to `Generating new plugin set instance. Skip gems - []`)

### ISSUE THREAD

**Issue by jamiejackson** [hashicorp/vagrant#11142]
### Vagrant version

Vagrant 2.2.5

### Host operating system

Mac OSX Mojave

### Guest operating system

Irrelevant

### Vagrantfile

Irrelevant

### Debug output

Note that I have turned on timestamps for all of the stdout/stderr lines.

https://gist.github.com/jamiejackson/9dd3e99868766d06af47b965717f8c2b

### Expected behavior

Vagrant commands should execute quickly, say, in within a second.

### Actual behavior

Vagrant commands take at least 15 seconds to initialize.

I realize I have a gem that has lots of dependencies, but I think that whatever Vagrant's doing, that it should be faster or should have a way to be bypassed during normal operation.

### Steps to reproduce

Have plugins installed. Run any vagrant command (e.g., `vagrant help`). You don't even have to be in a project directory.

**Comment by xelarate86** [comment]
Seeing this too on Ubuntu on 2.2.6
