### ISSUE TITLE
vagrant status --show ip

### ISSUE THREAD

**Issue by willzhang** [hashicorp/vagrant#11149]
is there a way to show all the vm's ipaddress?
vagrant status --show ip ?
```
$ vagrant status
Current machine states:

centosvm01                running (virtualbox)
centosvm02                running (virtualbox)
centosvm03                running (virtualbox)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.

Administrator@DESKTOP-2798TU8 MINGW64 /d/vagrant/k8s-test
$
```

**Comment by briancain** [comment]
Hi @willzhang - You could run `vagrant ssh -c` to execute a shell script against the guests in your environment. The status command isn't for displaying metadata like that about guests. Thanks for opening an issue on Vagrant! If you have more questions, I recommend asking in the Vagrant Up mailing list.
