### ISSUE TITLE
vagrant not updating plugin information

### ISSUE THREAD

**Issue by rememberthebear** [hashicorp/vagrant#11156]
After I upgrade vagrant to the most current version, I suddenly got this error:

```
 vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: Unable to resolve dependency: user requested 'vagrant-proxyconf (= 2.0.7)'
```

While it is true that I had, at one point, used the third party vagrant plugin "vagrant-proxyconf" in that particular vagrantfile, I had commented out the portions of the vagrantfile which use that particular plugin a while ago, and the vagrantfile continued to run fine when using vagrant 2.2.5.  I had thought that the new version of vagrant couldn't recognize that I had commented out the parts of the vagrantfile that reference the plugin, so I just completely removed the section with the referenced plugin and tried running the command again.  Same error.  Even when the plugin is no longer referenced in the vagrantfile, vagrant keeps failing before it ever properly runs because it still thinks this vagrantfile needs a plugin which it no longer references.  In order to finally get past this issue, I had to go into the .vagrant folder that is in the same directory as the vagrantfile and delete the plugin.json file and the references to the plugin in question in the "plugins" directory inside the ".vagrant" directory.

### Vagrant version
vagrant 2.2.6

### Host operating system
Windows 10 x64

### Guest operating system
NA

### Vagrantfile
Original vagrantfile:

```ruby
Vagrant.configure("2") do |config|
	config.vm.box_check_update = true
	config.vm.provider :virtualbox do |v|
		v.gui = true
		v.customize ["modifyvm", :id, "--memory", "4096"]
		v.customize ["modifyvm", :id, "--cpus", "2"]
		v.customize ["modifyvm", :id, "--vram", 32]
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--audio", "none"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
		v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
		v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
		v.linked_clone = true
	end
	config.vm.guest = :windows
	config.vm.communicator = "winrm"
	config.vm.boot_timeout = 500
	config.winrm.transport = :plaintext
	config.winrm.basic_auth_only = true
	config.vm.network "forwarded_port", guest: 5985, host: 55985
	config.vm.network "forwarded_port", guest: 3389, host: 3389
config.vm.network "public_network", bridge: "Realtek USB GbE Family Controller"
config.proxy.http = "http://192.168.0.2:3128/"
    config.proxy.https = "http://192.168.0.2:3128/"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
end
```

Current vagrantfile:

```ruby
Vagrant.configure("2") do |config|
	config.vm.box_check_update = true
	config.vm.provider :virtualbox do |v|
		v.gui = true
		v.customize ["modifyvm", :id, "--memory", "4096"]
		v.customize ["modifyvm", :id, "--cpus", "2"]
		v.customize ["modifyvm", :id, "--vram", 32]
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--audio", "none"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
		v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
		v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
		v.linked_clone = true
	end
	config.vm.guest = :windows
	config.vm.communicator = "winrm"
	config.vm.boot_timeout = 500
	config.winrm.transport = :plaintext
	config.winrm.basic_auth_only = true
	config.vm.network "forwarded_port", guest: 5985, host: 55985
	config.vm.network "forwarded_port", guest: 3389, host: 3389
config.vm.network "public_network", bridge: "Realtek USB GbE Family Controller"
end
```

### Debug output

```
 vagrant up
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: Unable to resolve dependency: user requested 'vagrant-proxyconf (= 2.0.7)'
```

### Expected behavior
Vagrant should realize when a Vagrantfile no longer uses a plugin and update the local cache accordingly

### Actual behavior
It does not.  

### Steps to reproduce
1. create a vagrantfile that utilizes a third party plugin and install that plugin with vagrant plugin install
2. Successfully Run vagrant up to cache the plugin configuration in .vagrant folder
3. Remove reference to the plugin in vagrantfile and save
4. run vagrant up again

**Comment by briancain** [comment]
Hi there @rememberthebear - Have you tried running the commands that Vagrant asks you to run? Commenting out config options from a plugin still won't prevent Vagrant from loading the plugins you have installed in your local environment.

**Comment by jchermoso** [comment]
I had the same issue and I solved it typing vagrant plugin repair. I think this was due to an issue about versions.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
