### ISSUE TITLE
Ansible_local does not install with ubuntu/bionic64-18.04

### ISSUE THREAD

**Issue by rodrigorpgsc** [hashicorp/vagrant#11157]
### Vagrant version
Vagrant 2.2.5

### Host operating system
Win 10 PRO
10.0.18362

### Guest operating system
ubuntu/bionic64' version '20191023.0.0

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.50.4"
  config.vm.provision "ansible_local" do |a|
	a.install  = true
    a.playbook = "provisioning/setup_vagrant.yml"
    a.verbose  = false
  end
end

### Debug output
https://gist.github.com/rodrigorpgsc/c7944f22882b1553cc45836a322c7a39

### Expected behavior
Sucessful instalation of ansible

### Actual behavior
E: Failed to fetch http://ppa.launchpad.net/ansible/ansible/ubuntu/pool/main/a/ansible/ansible_2.8.6-1ppa~bionic_all.deb  Connection timed out [IP: 91.189.95.83 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

### Steps to reproduce
1. Vagrant up using my vagrantfile

### References
- I believe no

**Comment by briancain** [comment]
Hi @rodrigorpgsc - Sometimes connections time out, but this is not a Vagrant bug. I recommend waiting and trying again, or seeing if you can `curl` or access the package in another way. There could be an issue with your network if your guest can't reach the sever where the ansible package is located. I just tried to install ansible with the ansible_local provider and my guest was able to reach the server and install ansible, for reference. Thanks!

**Comment by rodrigorpgsc** [comment]
Thanks Brian. I`ll check the network connnection.
