### ISSUE TITLE
FreeBSD does not mount default share

### ISSUE THREAD

**Issue by FlipGer** [hashicorp/vagrant#11159]
### Vagrant version
Vagrant 2.2.6

### Host operating system
Windows 10 1903

### Guest operating system on Virtualbox 6.0.14
FreeBSD 12
https://app.vagrantup.com/generic/boxes/freebsd12

### Short debug Info:
GuestAdditionsRunLevel=2
GuestAdditionsVersion="5.2.32 r132056"
GuestAdditionsFacility_VirtualBox Base Driver=50,1572159523414
GuestAdditionsFacility_VirtualBox System Service=50,1572159534561
GuestAdditionsFacility_Seamless Mode=0,1572159523413
GuestAdditionsFacility_Graphics Mode=0,1572159523412

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/freebsd12"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end

```

### Expected behavior
Mounting of default  share "." "vagrant" to /vagrant in Guest System.

### Actual behavior
Mounting does not take place. The line with mounting drive is simply missing on startup after machine booted an ready.

### Steps to reproduce
1. vagrant init generic/freebsd12
2. vagrant up

    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!

Thats the last line on vagrant up after fresh init.

3. No share added to the VirtualBox and nothing mounted in Freebsd
4. Mouting by "hand" does work:
5. Adding Share to VirtualBox
6. Mounting in FreeBSD:

vagrant ssh
$ cd /
$ sudo mkdir vagrant
$ mount_vboxvfs -w vagrant /vagrant
$ sudo mount_vboxvfs -w vagrant /vagrant

**Comment by briancain** [comment]
Hi there @FlipGer - That's because the Vagrantfile packaged with that box explicitly disables the default mount. If you wish you use it, you can always enable it again:

```ruby
config.vm.synced_folder ".", "/vagrant", disabled: false
```

Thanks!

**Comment by FlipGer** [comment]
Hi.

thanks for the fast answer. But this does also not work as expected. Now the Box tries to add the synced folder as SMB share and not via mounting.


==> default: Clearing any previously set forwarded ports...
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: account.
    default:
    default: Username:

Sorry if this is also just a config thing, but i am very new to vagrant and especially FreeBSD.

Greetings!

**Comment by briancain** [comment]
Hi @FlipGer - Yes, if you have questions about how the box was prepared and configured I recommend asking the box maintainer: https://github.com/lavabit/robox

Thanks!
