### ISSUE TITLE
Getting started guide mentions ubuntu 12.04 but uses bionic box

### ISSUE THREAD

**Issue by mahmoud-ashi** [hashicorp/vagrant#11168]
Following the getting started guide here https://www.vagrantup.com/intro/getting-started/index.html, the command suggests to use `vagrant init hashicorp/bionic64` however the text describing the command mentions ubuntu 12.04.
```
After running the above two commands, you will have a fully running virtual machine in VirtualBox running Ubuntu 12.04 LTS 64-bit.
```

**Comment by dnck** [comment]
The website still displays the incorrect Ubuntu version.
