### ISSUE TITLE
Best practice for changing default network adapter type with VirtualBox?

### ISSUE THREAD

**Issue by poige** [hashicorp/vagrant#11162]
Or in general — how is it advised to change any property of that "automatically created and managed" service network that gets created by Vagrant by default.

How to refer it from the config?

I've found a workaround in #7741 but it's kinda clumsy as to me.

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue! You might find some work-arounds listed on this issue: https://github.com/hashicorp/vagrant/issues/2093

We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the Vagrant mailing list. There are many more people who will be able to get you a faster answer there. Thank you and have a great day!

**Comment by poige** [comment]
well, it might be considered a "feature request" if you don't have any decent interface for what I've asked. And "a workaround in #7741 but it's kinda clumsy as to me.".
