### ISSUE TITLE
Vagrant 2.2.6 on mac Os Catalina : Failed to start The Apache HTTP Server

### ISSUE THREAD

**Issue by henbulls** [hashicorp/vagrant#11161]
macOS Catalina 10.15
Vagrant 2.2.6 (installed via homestead)

When I do "vagrant ssh" and "flip" ngix to appache, the process fails around this spot:
`nginx stopped `
`Job for apache2.service failed because the control process exited with error code.`
`See "systemctl status apache2.service" and "journalctl -xe" for details.`
`apache started`

When I do "systemctl status apache2.service" showing like below:

`vagrant@homestead:~$ systemctl status apache2.service`
` apache2.service - The Apache HTTP Server`
   `Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)`
  `Drop-In: /lib/systemd/system/apache2.service.d`
           `└─apache2-systemd.conf`
   `Active: failed (Result: exit-code) since Mon 2019-10-28 03:43:18 UTC; 26s ago`
  `Process: 3468 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)`

`Oct 28 03:43:18 homestead systemd[1]: Starting The Apache HTTP Server...`
`Oct 28 03:43:18 homestead apachectl[3468]: AH00526: Syntax error on line 7 of /etc/apache2/sites-enabled/landingpage.local-ssl.conf:`
`Oct 28 03:43:18 homestead apachectl[3468]: DocumentRoot takes one argument, Root directory of the document tree`
`Oct 28 03:43:18 homestead apachectl[3468]: Action 'start' failed.`
`Oct 28 03:43:18 homestead apachectl[3468]: The Apache error log may have more information.`
`Oct 28 03:43:18 homestead systemd[1]: apache2.service: Control process exited, code=exited status=1`
`Oct 28 03:43:18 homestead systemd[1]: apache2.service: Failed with result 'exit-code'.`
`Oct 28 03:43:18 homestead systemd[1]: Failed to start The Apache HTTP Server.` 

Has anyone experienced the same problem as me?

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
