### ISSUE TITLE
Ultra old dependency log4r

### ISSUE THREAD

**Issue by micheelengronne** [hashicorp/vagrant#11189]
Vagrant has log4r as dependency.

The last update of log4r is nearly 8 years old. It is impossible to access the source code as it was developed on rubyforge (down since 2014). We can not access the license either.

It is dangerous (understatement) to still use this gem in 2019.

Is it possible to remove it ?

**Comment by chrisroberts** [comment]
Hi there,

One can download and unpack the RubyGem from rubygems.org using the `gem fetch` and `gem unpack` commands. The source is also available within the Vagrant installer packages as it is a vendored dependency. The source code also lives on GitHub now and can be located here: https://github.com/colbygk/log4r

We currently have no reasons for removing this library from Vagrant's current list of dependencies. It has been, and continues to be, a good library for logging and a lack of new development or releases does not automatically make a software library dangerous. If there are specific concerns with implementation details within the library, I would be happy to review them. 

The license for the library is GPL or conditions defined within the license file. It can be located at `./doc/content/license.html` within the unpacked RubyGem contents.

Cheers!

**Comment by micheelengronne** [comment]
The source code "lives" :) Last commits are 2 years old bu the gem used by Vagrant is 7 years old.

The "lack of new development or releases does not automatically make a software library dangerous", that's really debatable. I can see that you are strongly opinionated but utterly wrong.

A library has to be constantly developed to ensure its resiliance against deprecations (that can become faults, bugs, security issues with enough time) and against 0-day attacks. The fact that is actively maintained increases the response time and its ductility (adaptability) when a bug and security issue occurs.

What happens if a security issue is discovered on this library ? Who can update its code ? How is it distributed ?

As a reference: https://www.owasp.org/index.php/Top_10-2017_A9-Using_Components_with_Known_Vulnerabilities

Anyway, as Vagrant is used in development environment, the attack surface may be considered reduced.

But reopening this issue should be a good idea.

**Comment by briancain** [comment]
Hi @micheelengronne - We appreciate your diligence for helping keep Vagrant safe for all who use it. We also want to ensure that Vagrant continues to be safe for those who use it, and want to reduce the attack surface that could threaten that safety.

If you have a specific CVE for the log4r ruby gem, we will be happy to address it. That being said, log4r has been open source for a long time, and is [used by almost 3,000 projects](https://github.com/colbygk/log4r/network/dependents?dependent_type=REPOSITORY&package_id=UGFja2FnZS02NzAyMA%3D%3D) to date. It has been a stable and reliable logging library for us and many others.

Do you have a security vulnerability to report? If so, the Vagrant repo is not the proper channel to report such an issue. Please follow the guide listed at [rubygems](https://guides.rubygems.org/security/#reporting-security-vulnerabilities) for reporting security vulnerabilities. When the time comes that a CVE shows up for log4r, we will address it at that time based on the severity of the threat.

Again, thanks for taking the time to report your concerns. We appreciate it.
