### ISSUE TITLE
Vagrant up times out, but then vagrant ssh works good

### ISSUE THREAD

**Issue by janvanveldhuizen** [hashicorp/vagrant#11199]
I have vagrant on Windows 10. No matter what I try, vagrant up always ends up in retrying connection and finally timing out. 
However when I then do vagrant ssh, it successfully connects. So in the end everything is okay.
Is there any way I can fix the vagrant up issue?

Vagrant version 2.2.6
Host OS: Windows 10
Guest OS: any Linux box
Vagrantfile: just did vagrant init ubuntu/xenial64, but same issue with other linux boxes

vagrant up output:
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/xenial64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/xenial64' version '20191108.0.0' is up to date...
==> default: Setting the name of the VM: test_default_1573846317753_8703
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

```

Then vagrant ssh:
```
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-166-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

vagrant@ubuntu-xenial:~$
```

So... end good, all good. But I want to understand what is wrong during vagrant up.

I already tried a lot of tips I found on forums, like removing OpenSSH from the PATH, but to no avail.

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket. If you just have a general usage question, please direct them to the vagrant up mailing list. Thank you!

**Comment by janvanveldhuizen** [comment]
Sorry briancain. I updated the issue.

**Comment by briancain** [comment]
Thanks @janvanveldhuizen for the information.

Generally, it can take a VM longer than expected to actually have SSH available. This is actually fairly common with these Ubuntu boxes.

Since it eventually does work, you can likely extend the boot timeout and just have Vagrant wait a little longer before giving up:

```ruby
# Default is 300, so you could double it at first to see if that works
config.vm.boot_timeout = 600
```
https://www.vagrantup.com/docs/vagrantfile/machine_settings.html#config-vm-boot_timeout

That should help you get past the default timeout waiting for the machine to boot.

**Comment by janvanveldhuizen** [comment]
I will try that.
But why can't the behavior be similar to what happens from a linux OS?
When I boot from my Ubuntu partition, and do the same, then:
` ` `
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
` ` `

How can I make vagrant on Windows aware of that insecure key?

**Comment by janvanveldhuizen** [comment]
config.vm.boot_timeout = 600

on Windows doesn't help :-(

**Comment by janvanveldhuizen** [comment]
[vagrant.log](https://github.com/hashicorp/vagrant/files/3854023/vagrant.log)

**Comment by janvanveldhuizen** [comment]
In the meantime I have some more information. I compared the logs of my Linux and my Windows systems.

At some point vagrant up on Linux says:
```
D, [2019-11-16T17:31:18.771455 #5077] DEBUG -- socket[1bea11c]: read 80 bytes
D, [2019-11-16T17:31:18.771604 #5077] DEBUG -- socket[1bea11c]: received packet nr 6 type 52 len 12
D, [2019-11-16T17:31:18.771665 #5077] DEBUG -- net.ssh.authentication.methods.publickey[1bb79c4]: publickey succeeded (dd:3b:b8:2e:85:04:06:e9:ab:ff:a8:0a:c0:04:6e:d6)

DEBUG ssh: == Net-SSH connection debug-level log END ==
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
```

At that point the Windows version says:
```
D, [2019-11-16T10:14:18.872848 #15560] DEBUG -- socket[3872fb4]: read 96 bytes
D, [2019-11-16T10:14:18.872848 #15560] DEBUG -- socket[3872fb4]: received packet nr 4 type 51 len 28
D, [2019-11-16T10:14:18.872848 #15560] DEBUG -- net.ssh.authentication.session[3846590]: allowed methods: publickey
D, [2019-11-16T10:14:18.873815 #15560] DEBUG -- net.ssh.authentication.methods.none[3843534]: none failed
D, [2019-11-16T10:14:18.873815 #15560] DEBUG -- net.ssh.authentication.session[3846590]: trying publickey

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not ready: #<Vagrant::Errors::SSHConnectEACCES: SSH is getting permission denied errors when attempting to connect
to the IP for SSH. This is usually caused by network rules and not being
able to connect to the specified IP. Please try changing the IP on
which the guest machine binds to for SSH.>
```

But still no clue what to do.
Why does it say 'permission denied'? Even when I open another command window when vagrant up is still retrying, then I can successfully ssh into the vm from that other window.

![ssh issue](https://user-images.githubusercontent.com/43573150/69007403-a1c63d00-093d-11ea-9ecd-9208e91dbfa4.png)

**Comment by janvanveldhuizen** [comment]
YES!! Found it !!!

Because of the dual boot configuration both using the same vagrant home folder, the insecure ssh key couldn't no longer be read by the Windows user.  I have to make a startup script to take back the ownership when booting Windows. 

I did that manually and it works again :-)
