### ISSUE TITLE
Set dhcp-identifier to mac address

### ISSUE THREAD

**Issue by jeromelefeuvre** [hashicorp/vagrant#11193]
I try to set the dhcp-identifier to mac according the new configuration on Ubuntu using netplan

Any tips for that ?

Thanks

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, when you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either updating this ticket. If you simply have a question about dhcp and netplan, I recommend either directing it towards the Ubuntu folks or asking in the Vagrant mailing list if it's related to Vagrant. Thanks!

**Comment by jeromelefeuvre** [comment]
I find my solution to set `auto_config: false` ^^
