### ISSUE TITLE
WinRM ip addr show — Do vagrant's devs assume Windows has iproute2? O_o

### ISSUE THREAD

**Issue by poige** [hashicorp/vagrant#11203]
### Vagrant version
`Vagrant 2.2.6`

### Host operating system
`Ubuntu 18.04.3 LTS`

### Guest operating system
https://vagrantcloud.com/stooj/windows7

### Vagrantfile
```
vagrant init stooj/windows7
vagrant up
```

### Debug output
```
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

ip=$(which ip); ${ip:-/sbin/ip} addr show | grep -i 'inet ' | grep -v '127.0.0.1' | tr -s ' ' | cut -d' ' -f3 | cut -d'/' -f 1

Stdout from the command:



Stderr from the command:

Unexpected token 'addr' in expression or statement.
    + CategoryInfo          : ParserError: (addr:String) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by poige** [comment]
Debug output above contains such info.

**Comment by briancain** [comment]
@poige - Please give us the entire output from running `vagrant up --debug`, otherwise it will be difficult to assist you and your issue. Thanks.

**Comment by poige** [comment]
Brain it looks you aren't really into solving issues but following stupid protocols instead as a way to avoid solving them.  I'm even surprised you didn't suggest to reboot Windows first, and all other devices next as a matter of issue isolation when assisting. Hashicorp — you suck here big times.

**Comment by chrisroberts** [comment]
Hi there,

First off, I'd like to remind you of the [HashiCorp code of conduct](https://www.hashicorp.com/community-guidelines) which this project, as well as all HashiCorp projects, follow. While I understand that the specific problem you are encountering may be frustrating for you, being disrespectful to the developers who are attempting to help you is not acceptable. I would encourage you to read the code of conduct document before replying to existing issues or opening new ones.

The debug gist is a requirement we make on all issues with regards to the behavior of Vagrant when it seems to be acting improperly. This makes it easier for us to properly locate the underlying issue as well as identify any host related configurations which may be causing this issue. 

Given the guest capability being run looks like a linux guest capability (which is explicitly identified within the debug output) I can make a pretty confident assumption that the box you are using has not properly overridden the `guest` option within its Vagrantfile. You can work around this by setting it in your local project Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "stooj/windows7"
  config.vm.guest = :windows
end
```

You can find information about this option in the Vagrant documentation here:

* https://www.vagrantup.com/docs/vagrantfile/machine_settings.html#config-vm-guest

**Comment by poige** [comment]
>  being disrespectful to the developers who are attempting to help you is not acceptable

Could you refrain from false claims (or, IOW, lying)?

It's a q-n what's more disrespectful — to demand gist when it's not really needed (IOW always, because it's just "easier for" you). In fact I don't see how is it easier in this very case.

> has not properly overridden the guest option within its Vagrantfile

Thanks, this is the real answer which everybody would value. You answered w/o any gist — that's what I'm talking about.

**Comment by poige** [comment]
@chrisroberts I'm not sure if it's any useful but generally it looks weird — to use WinRM and expect the guest to be Linux.

**Comment by chrisroberts** [comment]
Providing a debug gist allows us to be more effective at resolving issues by identifying the root cause. It is standard operating procedure for how we triage and process issues. This is why it is requested in the issue template, and also why it was requested at the start of this issue. Had I been the one to provide the first response on this issue, I would have made the same request.

I'm glad that your issue has been resolved, and I would like to again refer you to the [HashiCorp code of conduct](https://www.hashicorp.com/community-guidelines). Cheers.
