### ISSUE TITLE
Vagrant assumes that — any way to convince otherwise?

### ISSUE THREAD

**Issue by poige** [hashicorp/vagrant#11204]
Or at least to convince it to continue anyways?

Arisen from #11203

**Comment by briancain** [comment]
Hi @poige - I'm going to go ahead and close this to due lack of any information. It seems like you've already opened an issue, so please update that one instead. Thanks.

**Comment by poige** [comment]
I'm asking how to work around #11203 and other similar cases here, closing looks absurd.

**Comment by briancain** [comment]
If you have a question about #11203 then please ask it on that issue. If you are looking for a general discussion about it, then please use our mailing list. Thank you!
