### ISSUE TITLE
Vagrant should recover from missing global data in machine index file

### ISSUE THREAD

**Issue by briancain** [hashicorp/vagrant#11214]
In some cases, it's possible to have Vagrant fail and not be able to add a local guests metadata to the global state file that keeps track of all running guests on a host machine (at `~/.vagrant.d/data/machine-index/index`). Although the guest still exists and is being tracked locally inside the project dirs `.vagrant` folder, it's missing from `global-status`. This issue should tackle trying to recover from this bad state so that the guest is added back into the global state file.

### Vagrant version

Any version

### Host operating system

n/a

### Guest operating system

n/a

### Vagrantfile

n/a

### Debug output

n/a

### Expected behavior

Vagrant should attempt to re-add the locally defined guest into the global state file if it is still valid locally.

### Actual behavior

The guest remains missing from `global-status`.

### Steps to reproduce

1. Bring up a guest
2. Delete its entry or the entire global index file at `~/.vagrant.d/data/machine-index/index`
3. Run `vagrant global-status` and see that it's missing

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-11187

**Comment by mprey** [comment]
I can try working on this issue. Do you have any pointers for getting started?
