### ISSUE TITLE
Inquiry -> Possible to `vagrant up` & not attempt SSH connectivity?

### ISSUE THREAD

**Issue by cappetta** [hashicorp/vagrant#11222]
Is it possible to tell vagrant "don't attempt to connectivity into this box"?  I tried --no-provision yet I still see the attempt in the debugging output.

My usecase relates to using vagrant to create AWS ec2 instances using dedicated AMIs.  In my situation, I simply want vagrant to launch the AMI and not login/provision.  Thoughts?

> 
> INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x0000000102b10bb8>
>  INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x0000000102b10be0>
>  INFO interface: Machine: action ["read_ssh_info", "end", {:target=>:myTarget}]
> DEBUG ssh: Checking key permissions: /my/key/path
>  INFO ssh: Attempting SSH connection...
>  INFO ssh: Attempting to connect to SSH...
>  INFO ssh:   - Host: 3.xxx.xx.xxx
>  INFO ssh:   - Port: 22
>  INFO ssh:   - Username: ec2-user
>  INFO ssh:   - Password? false
>  INFO ssh:   - Key Path: ["/my/key/path"]

**Comment by briancain** [comment]
Hey there @cappetta - I don't believe there is an officially supported way to disable ssh when using Vagrant. I'll also mention that the vagrant-aws provider is not supported any longer, if you are using that plugin. If you have more questions I suggest mailing the Vagrant Up mailing list, as more people will be able to guide you there. Thanks!

**Comment by cappetta** [comment]
Thanks @briancain -- oh man that sux!  vagrant+AWS is an awesome combo...  Will start connecting with folks in the project via mailing list & browsing the knowledge base - thanks!  While I have you -- Are you aware of any replacement for integrating with AWS?  Wondering if I need to upgrade / redesign my project solution

**Comment by briancain** [comment]
@cappetta - Generally we recommend folks use the [AWS Provider for Terraform](https://www.terraform.io/docs/providers/aws/index.html). It should be fully featured and better supported for your needs! :heart:
