### ISSUE TITLE
"vagrant halt" command without adding machine name suddenly deletes files from machines folder

### ISSUE THREAD

**Issue by frwxworx** [hashicorp/vagrant#11224]
Have not made any changes in vagrantfile. At the end of the day, did "vagrant halt" and forgot to mention which machine I want to shutdown. In this case it should be "vagrant halt Ubuntu-18-04-server".
In the next morning I was surprised that machine won't boot up after command "vagrant up Ubuntu-18-04-server" and it kept trying to remote connected. I was suspicious, something happened.

As it seems it deleted everything sitting in the vagrant home folder, in that machine folder, is empty: (C:\VagrantHome\my-env\.vagrant\machines\Ubuntu-18-04-server\virtualbox)

Therefore I am not able anymore to boot up this very necessary machine via Vagrant anymore. 

Is that a bug or it is supposed to be like that with command "vagrant halt", I guess not? 

Any advice how to setup vagrant needed files to boot it up with vagrant commands as before? The VM itself is still present in ("C:\Users\username\VirtualBox VMs\ubuntu1804"), it is possible to boot it up and use it as before, without any changes in it via Virtualbox.

### Vagrant version
Vagrant 2.2.6

### Host operating system
Win10

### Guest operating system
Ubuntu 18.04 LTS server

**Comment by briancain** [comment]
Hey there @frwxworx - Vagrant should not be doing anything with your filesystem when you halt a guest. It should simply just call the halt command for the given provider, in this case virtualbox. Please provide us with a simplified Vagrantfile, and a debug log (i.e. running `vagrant halt --debug`) that shows the behavior, if you can.

**Comment by frwxworx** [comment]
I have already created a new copy of that VM to continue work, but also added --halt debug [vagrant.log](https://pastebin.com/TzQ8cS9K) as you requested of current state, if it helps. 

Simplified Vagrantfile at the time of the issue was:
> Vagrant.configure("2") do |config|
> 
>   config.vm.define "Ubuntu-18-04-server" do |master|
>   master.vm.box = "peru/my_ubuntu-18.04-server-amd64"
>   master.vm.box_version = "20191101.01"
>   master.vm.hostname = "ubuntu1804server"
>   master.vm.network "private_network", ip: "172.28.128.3", virtualbox__intnet: true, auto_config: true
>     master.vm.provider "virtualbox" do |v|
>       v.gui = false
>       v.customize ["modifyvm", :id, "--memory", "2048"]
>       v.cpus = 1
>       v.name = "ubuntu1804server"
>     end
>   end

**Comment by briancain** [comment]
@frwxworx - If you run `vagrant global-status` does the vm still show up there, or is it also gone there?

**Comment by frwxworx** [comment]
> @frwxworx - If you run `vagrant global-status` does the vm still show up there, or is it also gone there?

Yes, it does show up still there, indeed.
![missing_vm](https://user-images.githubusercontent.com/48279670/70213294-a8c4bc00-1741-11ea-9473-6ff22efd3983.png)

**Comment by briancain** [comment]
Hi @frwxworx - Vagrant should not be deleting these files when you run `vagrant halt`. Are you able to reliably reproduce this issue, or did it happen that one time? :thinking:

**Comment by frwxworx** [comment]
This morning again, the same issue appeared. Both VM's is shown as "not created" in vagrant status, and the .vagrant/machines folders are completely self-cleared after 2 day shutdown of PC, except leaving only 1 file - "private_key". Both VM were safely halted in the end of the last run. Vagrantfile was untouched for the last month or so.

**Comment by briancain** [comment]
Hi @frwxworx - Sorry, Vagrant doesn't run as a daemon at all, so unless you invoked Vagrant during the shutdown, it wasn't Vagrant that removed those machine folders. It's possible that maybe your anti-virus or some other service cleaned up your folders. If you have a debug log showing the behavior of Vagrant removing these folders we could be able to help you, but if it's happening outside of Vagrant running then it's likely something else removing these files! Sorry we couldn't be more help.
