### ISSUE TITLE
swap will be enabled again when reload vm

### ISSUE THREAD

**Issue by willzhang** [hashicorp/vagrant#11237]
when i install kubernetes cluster in centos7.x，i must disable swap
```
sed -i '/swap/d' /etc/fstab
swapoff -a
```

but when i restart vagrant vm ,the swap will be enabled automatic,it let my kubelet Service failed to start,why?
```
[root@k8smaster ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:           1837         164        1315           8         357        1527
Swap:          2047           0        2047
[root@k8smaster ~]# cat /etc/fstab 

#
# /etc/fstab
# Created by anaconda on Tue Nov  5 15:29:48 2019
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=3c8e36bd-8118-440d-9ec7-8aaf5959e6c9 /                       xfs     defaults        0 0
/swapfile none swap defaults 0 0
```

**Comment by jbonhag** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!
