### ISSUE TITLE
macOS Catalina: NFS version or transport protocol is not supported

### ISSUE THREAD

**Issue by tomasnagy** [hashicorp/vagrant#11234]
### Vagrant version
2.2.6

### Host operating system
macOS Catalina

### Issue
Vagrant up sometimes fails on NFS.
```The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp,rw,vers=3,tcp,fsc,nolock,actimeo=2 192.168.33.1:/System/Volumes/Data/Users/*******/Sites/*******/***** /vagrant

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```

Most times when running `vagrant up` this fails, sometimes it just works. It's inconsistent.

Syslog reports:

`Dec  4 11:38:51 com.apple.xpc.launchd[1] (com.apple.nfsd[32543]): Service did not exit 5 seconds after SIGTERM. Sending SIGKILL`

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant!  This issue sounds a lot like #11209 -- we've been seeing that same `nsfd` crash in other places as well, and these crashes seem to be resolved by changing the format that Vagrant writes to /etc/exports.

Since we have already committed a fix to master (https://github.com/hashicorp/vagrant/pull/11216) to address this, I'm going to go ahead and close this as a duplicate.

Thanks, and have a great day!

**Comment by tomasnagy** [comment]
Hi, 

I don't think that this is the same issue.
There is only 1 shared folder in my case and it is correctly formatted in the exports file.

```
# VAGRANT-BEGIN: 502 0aadf232-632f-4f73-9d3e-59395323cd2b
/System/Volumes/Data/Users/****/Sites/******/***** -alldirs -mapall=502:20 192.168.33.119
# VAGRANT-END: 502 0aadf232-632f-4f73-9d3e-59395323cd2b
```

But it still fails when trying to build.

**Comment by jbonhag** [comment]
Hi @tomasnagy,

Thank you for clarifying -- sounds like this is something worth looking into.  Would you mind editing your issue to provide some additional information:

* A copy of the Vagrantfile you're using (with any sensitive data removed/obfuscated)
* A link to a [Gist](https://gist.github.com/) containing the output of `vagrant up --debug` that demonstrates the issue

That will help us investigate the issue more thoroughly.

For what it's worth, we've also seen some NFS issues be resolved by installing Catalina update 1 -- if you haven't already done that, it might be worth a shot.

Cheers!

**Comment by OZZlE** [comment]
https://github.com/hashicorp/vagrant/pull/11216

**Comment by tomasnagy** [comment]
Hi,

Already on the latest version of Catalina and the problem persists (vagrant destroy => reboot => vagrant up will make it work sometimes, I think it times out at the NFS part).

Gist: https://gist.github.com/tomasnagy/95aafad23c99484bce0c4d71ab802aa3
Vagrant file:
`# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define :********** do |**********_config|
        **********_config.vm.box = "**********/Debian10"

        **********_config.vm.provider "virtualbox" do |v|
            # show a display for easy debugging
            v.gui = false

            # RAM size
            v.memory = 2048

            # Allow symlinks on the shared folder
            v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]

            # Share host VPN connections with guest
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end

        # allow external connections to the machine
        #**********_config.vm.forward_port 80, 8080

        # Shared folder over NFS
        **********_config.vm.synced_folder ".", "/vagrant", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc', 'nolock', 'actimeo=2']

        **********_config.vm.network "private_network", ip: "192.168.33.90"

        # Provide access to ********** Gitlab with the SSH key of your host machine
        **********_config.ssh.forward_agent = true

        # Shell provisioning
        **********_config.vm.provision :shell, :path => "shell_provisioner/run.sh"
    end
end
`

Thanks!

**Comment by tomasnagy** [comment]
@jbonhag Found the culprit, when FortiClient the VPN is active this will result in these NFS issues on macOS. This can be closed.

**Comment by OZZlE** [comment]
@tomasnagy I have a similar issue, when my VPN "Cisco AnyConnect Secure Mobility Client" is connected and I up vagrant I cannot access it from browser, but if I halt it, disconnect the vpn, up vagrant again, and connect to the vpn again everything works fine for some reason, perhaps it's some MacOs bug I don't know..

**Comment by jbonhag** [comment]
@tomasnagy That's great to hear! Thanks for sharing that discovery.

@OZZlE Interesting! Sounds like it could be related to the routes that the VPN sets up.  In any event I'll keep that in mind when troubleshooting these issues in the future. Cheers! 😄

**Comment by Srijeeta** [comment]
> @jbonhag Found the culprit, when FortiClient the VPN is active this will result in these NFS issues on macOS. This can be closed.

Thanks! This saved my day.
