### ISSUE TITLE
vagrant box update --box does not check version correctly

### ISSUE THREAD

**Issue by pharazon** [hashicorp/vagrant#11243]
When I run vagrant box update the version checking works ok. I'm using customly hosted private boxes from metadata.json. I'm running these two commands from the dir where I have the Vagrantfile present. Example working ok:

```
vagrant box update
==> api: Checking for updates to 'my/box'
    api: Latest installed version: 1.0.104
    api: Version constraints: 
    api: Provider: virtualbox
```

But when I run vagrant box update --box my/box then then the version checking doesnt work but it gives error like this:

```
vagrant box update --box my/box
Checking for updates to 'my/box'
Latest installed version: 1.0.84
Version constraints: > 1.0.84
Provider: virtualbox
Updating 'my/box' with provider 'virtualbox' from version
'1.0.84' to '1.0.104'...
Loading metadata for box 'file:/home/user/my/box/metadata.json'
Adding box 'my/box' (v1.0.104) for provider: virtualbox
The box you're attempting to add already exists. Remove it before
adding it again or add it with the `--force` flag.

Name: my/box
Provider: virtualbox
Version: 1.0.104
```

Vagrant version Vagrant 2.2.4
OS: Ubuntu 16.04

```
vagrant box list |grep my/box
my/box                       (virtualbox, 1.0.84)
my/box                       (virtualbox, 1.0.104)

```
### References
This is little bit similar could be related but not exactly the same:
- GH-11228

**Comment by briancain** [comment]
Hi @pharazon - Could you please provide us with the full debug log of running `vagrant box update --box my/box --debug`? Thanks.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
