### ISSUE TITLE
The term 'vagrant' is not recognized as the name of a cmdlet in WIN 10

### ISSUE THREAD

**Issue by schel4ok** [hashicorp/vagrant#11241]
I just downloaded VirtualBox 6.0.14 and Vagrant 2.2.6 (vagrant_2.2.6_x86_64.msi) on Windows 10 Pro
```
PS C:\Users\Anastasia> $env:path -split ';'
C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\HashiCorp\Vagrant\bin
C:\Users\Anastasia\AppData\Local\Microsoft\WindowsApps
```

### Expected behavior
I expect vagrant command will be available in powershell

### Actual behavior
```
PS C:\Users\Anastasia> vagrant
vagrant : The term 'vagrant' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ vagrant
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (vagrant:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Steps to reproduce
1. install VirtualBox 6.0.14
2. install vagrant_2.2.6_x86_64.msi
3. reboot
4. open powershell and write vagrant

I found one solution here https://stackoverflow.com/questions/37941182/unable-to-run-vagrant-commands-through-powershell-script-in-virtualbox

but for me it gives the same error

**Comment by jbonhag** [comment]
Hi there,

Where is Vagrant installed on your system?  Judging from the path entries above, it looks like Vagrant was installed to `C:\HashiCorp\Vagrant`.  Would you mind trying the following:

1. Running Vagrant with the full path to the Vagrant executable (such as `C:\HashiCorp\Vagrant\bin\vagrant.exe`)
2. Running `(Get-Command vagrant.exe).Path` -- this will help to see whether Vagrant really is on the PATH or not.

This will help us investigate the issue further.  Thanks!

**Comment by schel4ok** [comment]
When I try it with full path I got message Access is denied. 
But I have only one user in windows and of course with admin rights. 
I don't know how it is possible

**Comment by schel4ok** [comment]
If I run this in power shell

```
PS C:\Users\Anastasia> (Get-Command vagrant.exe).Path
Get-Command : The term 'vagrant.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+ (Get-Command vagrant.exe).Path
+  ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (vagrant.exe:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand
```

**Comment by jbonhag** [comment]
Hi there,

Thanks for the additional info. It sounds like something isn't quite right with your folder permissions.  Generally I would recommend uninstalling and reinstalling Vagrant first. If that doesn't fix the issue, you could try opening Powershell as an Administrator.  If you search for "Powershell" in the Start Menu, you should see an icon that says "Run as Administrator".  Click that, and you should no longer see that "Access Denied" error when you run Vagrant.

Cheers!

**Comment by schel4ok** [comment]
I tried to reinstall vagrant more than 3 times. And also run PS as admin. 
No difference

**Comment by chrisroberts** [comment]
Do you currently have antivirus software running. This can be a common cause for behavior like this.

**Comment by schel4ok** [comment]
I have eset nod32 running

**Comment by chrisroberts** [comment]
You will have to add the executable to the allow list in your virus scanner (or remove it from quarantine, or what ever process your antivirus uses) to regain access to the binaries. Unfortunately there is nothing else we can do to help solve this problem.

Cheers!
