### ISSUE TITLE
Network is unrealiable in generic/ubuntu1804 box

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/vagrant#11256]
### Vagrant version
`Vagrant 2.2.6`

### Host operating system
Windows 10 build `1909`

### Guest operating system
[`generic/ubuntu1804`](https://app.vagrantup.com/generic/boxes/ubuntu1804)

### Vagrantfile
Please look at the following repository:
https://github.com/Wenzel/vagrant-oswatcher

Provider: `Hyper-V`

~~~Ruby
Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.box_version = "2.0.6"
    config.vm.define "oswatcher"
    # OSWatcher local git repo
    oswatcher_path = "/path/to/oswatcher"

    config.vm.provider "hyper-v" do |hyperv|
        hyperv.vmname = "oswatcher"
        hyperv.cpus = 2
        hyperv.memory = 2048
        # allow nested virtualization
        hyperv.enable_virtualization_extensions = true
    end

    config.vm.synced_folder ".", "/vagrant"
    # make oswatcher local path accessible as /vagrant/oswatcher
    config.vm.synced_folder oswatcher_path, "/vagrant/oswatcher"

    config.vm.provision "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "ansible/playbook.yml"
        ansible.extra_vars = {
          'oswatcher_path': "/vagrant/oswatcher",
        }
    end
end
~~~

### Debug output
I don't believe Vagrant's debug log are useful here,
since the box configuration seems to be the root cause of this issue.

### Expected behavior
The box should have been provisionned without any issues.

### Actual behavior
The Ansible playbook systematically fails because of a network issue:
- `Temporary failure resolving us.archive.ubuntu.com`
- `400 bad request`
- `404 not found`

Or even before the Ansible playbook is executed, the network fails.
![dns1](https://user-images.githubusercontent.com/964610/70867270-fa581c80-1f73-11ea-9017-9dbe930836cd.png)
![dns2](https://user-images.githubusercontent.com/964610/70867272-fcba7680-1f73-11ea-98ac-e2171bf2c645.png)
![dns3](https://user-images.githubusercontent.com/964610/70867273-ffb56700-1f73-11ea-875a-0b23ff7c3bd2.png)

And if it manages to execute the playbook, it systematically fails here:
![dns4](https://user-images.githubusercontent.com/964610/70867274-017f2a80-1f74-11ea-82d9-b64fde3384e0.png)

I had to add a `retry` statement in my Ansible task to force retry until the network is reachable:
~~~YAML
    - name: install OSWatcher system dependencies
      package:
        name: "{{ item }}"
      with_items:
        - virtualenv
        - python3-virtualenv
        - libguestfs0
        - libguestfs-dev
        - python3-guestfs
        - python3-dev
        - pkg-config
        - libvirt-dev
      register: result
      until: result is succeeded
      retries: 3
      delay: 10
~~~

Result:
![retry](https://user-images.githubusercontent.com/964610/70867327-9d109b00-1f74-11ea-9f8a-640341344498.png)

### Steps to reproduce
1. `git clone https://github.com/Wenzel/vagrant-oswatcher`
2. `git clone https://github.com/Wenzel/oswatcher`
3. Edit `vagrant-oswatcher/Vagrantfile` and set the local path to oswatcher's repo
4. `vagrant up --provider hyperv`

Note: I suppose the Vagrant team manages `generic` boxes on Vagrant's Cloud.

Thanks !

**Comment by briancain** [comment]
Hey there @Wenzel - Since you mentioned you didn't think it was Vagrant but the box configuration you are using, please open an issue with the Generic group who maintains those boxes. You can find the repository here: https://github.com/lavabit/robox

If it's actually an issue with Vagrant feel free to ping us on here or open a new issue, thanks!

**Comment by Wenzel** [comment]
@briancain thanks for the link, will open an issue there !
