### ISSUE TITLE
The vagrant_2.2.6_x86_64.dmg  cannot be opened on macOS Catalina(10.15.1) because of apple security check

### ISSUE THREAD

**Issue by vincent10111** [hashicorp/vagrant#11253]

**Comment by jbonhag** [comment]
Hi there,

There are new restrictions for applications imposed by Apple starting with Catalina. Included in these new restrictions is the requirement for notarization which requires submission of the application build to Apple and an acceptance before it can be packaged and distributed.

We are working on integrating this process into our build system and will have it available for our next release. In the meantime, please check out issue #11127 for some suggested workarounds.

I'll go ahead and close this issue as a duplicate, but thanks for taking the time to report your findings.

Have a great day! 😀
