### ISSUE TITLE
Inconsistent between documentation and source code for Hyper-V plugin, configuration option "enable checkpoints"

### ISSUE THREAD

**Issue by richard-pare** [hashicorp/vagrant#11269]
### Vagrant version

Vagrant 2.2.6

### Host operating system

Windows 8.1

### Guest operating system

Windows 10

### Issue

We can read on online documentation, that the default value of configuration option "enable_checkpoints" is "false".

Ref: https://www.vagrantup.com/docs/hyperv/configuration.html

But the source code differs from the documentation.

Ref: plugins/providers/hyperv/config.rb

```ruby
if @enable_checkpoints == UNSET_VALUE
    @enable_checkpoints = true
 else
    @enable_checkpoints = !!@enable_checkpoints
 end
```

**Comment by jbonhag** [comment]
Hi there,

Thanks for bringing this to our attention.  The docs will get updated as part of the next release.

Cheers!
