### ISSUE TITLE
Can't launch vagrant after fresh installation on win10.

### ISSUE THREAD

**Issue by paulollivier** [hashicorp/vagrant#11260]
Hello,

I'm having issues with vagrant for windows. It complains about a missing file, `C:\Users\MY_USER\.local\embedded\manifest.json`. And that quite literally all the vagrant binary does. I'm under the impression that vagrant doesn't even get to cli args parsing.

This happens after a fresh install, and i tried reintalling multiple times, even disabling the antivirus, to no avail.

And googling shows nothing related to my issue at all. I'm at a loss.

I should also say that i'm in no way a windows expert as it's my first time on windows after 10 years.

### Vagrant version
```
$ vagrant -v 
Failed to read Vagrant manifest file at C:\Users\MY_USER\.local\embedded\manifest.json: open C:\Users\MY_USER\.local\embedded\manifest.json: Le fichier spécifié est introuvable.
```

### Host operating system
Windows 10

### Expected behavior
I should be able to execute Vagrant, at least to see some help message
### Actual behavior
Whatever argument i give to vagrant, the same text shows up.
To non-French speakers: "Le fichier spécifié est introuvable" means "File not found".

### Steps to reproduce
1. Install vagrant via the windows installer
2. set $PATH; reboot
3. weep

**Comment by paulollivier** [comment]
I forgot to say that I tried creating the file, putting '{}' in it, it just changes the error message to "could not parse version", or something like that.

**Comment by jbonhag** [comment]
Hi there,

First of all, I am sorry that Vagrant is causing you to weep 😄 -- hopefully we can get this sorted out.  That file is in the Vagrant installation directory, for example it would be at `C:\HashiCorp\Vagrant\embedded\manifest.json` with the default installation.

The Vagrant installer will set the $PATH for you, so that step shouldn't be necessary.  I wonder if something on your $PATH is confusing Vagrant.

Would you mind telling me which shell you're using (Command Prompt, Powershell, Git Bash, etc.) so I can investigate this issue further?

Thanks!

**Comment by paulollivier** [comment]
Hey, @jbonhag.

I'm using git bash for windows, and my env is this: 
```
OS=Windows_NT
COMMONPROGRAMFILES=C:\Program Files\Common Files
PROCESSOR_LEVEL=6
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
CommonProgramW6432=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
LANG=fr_FR.UTF-8
MSYSTEM_CARCH=x86_64
PUBLIC=C:\Users\Public
CONFIG_SITE=/mingw64/etc/config.site 
EXEPATH=C:\Program Files\Git\bin 
MSYSTEM_CHOST=x86_64-w64-mingw32
USERNAME=MY_USER
JAVA_HOME=C:\Program Files\Java\jdk-13.0.1
PROCESSOR_ARCHITECTURE=AMD64
LOCALAPPDATA=C:\Users\MY_USER\AppData\Local
COMPOSE_CONVERT_WINDOWS_PATHS=true 
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
DOCKER_MACHINE_NAME=windocker
SYSTEMDRIVE=C:
USERPROFILE=C:\Users\MY_USER
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW
SYSTEMROOT=C:\WINDOWS
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel 
MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
PWD=/c/Users/MY_USER/work/projects/my_project
SSH_ASKPASS=/mingw64/libexec/git-core/git-gui--askpass
HOME=/c/Users/MY_USER
TMP=/tmp
TERM_PROGRAM=Terminus
MSYSTEM_PREFIX=/mingw64
OneDrive=C:\Users\MY_USER\OneDrive
PROCESSOR_REVISION=8e0a
FPS_BROWSER_USER_PROFILE_STRING=Default
TMPDIR=/tmp
ProgramW6432=C:\Program Files
COMSPEC=C:\WINDOWS\system32\cmd.exe
APPDATA=C:\Users\MY_USER\AppData\Roaming
SHELL=/usr/bin/bash
TERM=cygwin
WINDIR=C:\WINDOWS 
MINGW_CHOST=x86_64-w64-mingw32
ProgramData=C:\ProgramData
SHLVL=1
PLINK_PROTOCOL=ssh
ACLOCAL_PATH=/mingw64/share/aclocal:/usr/share/aclocal
PROGRAMFILES=C:\Program Files
MANPATH=/mingw64/local/man:/mingw64/share/man:/usr/local/man:/usr/share/man:/usr/man:/share/man
ORIGINAL_TEMP=/tmp
ORIGINAL_TMP=/tmp
ALLUSERSPROFILE=C:\ProgramData
TEMP=/tmp
DriverData=C:\Windows\System32\Drivers\DriverData 
MSYSTEM=MINGW64
MINGW_PREFIX=/mingw64
SESSIONNAME=Console
ProgramFiles(x86)=C:\Program Files (x86)
PATH=/c/Users/MY_USER/.cargo/bin/:/c/Users/MY_USER/.local/bin/:/c/Users/MY_USER/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/MY_USER/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/Microsoft VS Code/bin:/cmd:/mingw64/bin:/usr/bin:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/c/Ruby26-x64/bin:/c/Users/MY_USER/AppData/Local/Microsoft/WindowsApps:/c/Users/MY_USER/AppData/Local/hyper/app-3.0.2/resources/bin:/c/Program Files/Java/jdk-13.0.1/bin:/c/Users/MY_USER/AppData/Local/Polycom/RealPresence Desktop:/usr/bin/vendor_perl:/usr/bin/core_perl
PS1=\[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$
HOMEDRIVE=C:
PKG_CONFIG_PATH=/mingw64/lib/pkgconfig:/mingw64/share/pkgconfig
INFOPATH=/usr/local/info:/usr/share/info:/usr/info:/share/info
HOMEPATH=\Users\MY_USER
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
OLDPWD=/c/Users/MY_USER
_=/usr/bin/env
```

I have excluded some vars for anonymisation.

Thank you!

**Comment by chrisroberts** [comment]
Hi there,

That file is not something which is used or referenced within Vagrant itself. Would you please provide a gist of the output from running:

```
vagrant --debug
```

Thanks!

**Comment by paulollivier** [comment]
```
$ vagrant --debug
Failed to read Vagrant manifest file at C:\Users\MY_USER\.local\embedded\manifest.json: open C:\Users\MY_USER\.local\embedded\manifest.json: Le fichier spécifié est introuvable.
```
Sorry, it's a bit frustrating...

**Comment by jbonhag** [comment]
Hi,

There should be two subdirectories in the Vagrant installation directory:

* `bin`
* `embedded`

Judging from this error, it seems like vagrant.exe (or maybe a symlink) is located at `C:\Users\MY_USER\.local\bin\vagrant.exe`, but the embedded directory is someplace else.
Could you please post the output of `which vagrant`?  Does this match the actual Vagrant installation directory?

Thanks!

**Comment by paulollivier** [comment]
Hey,
I can confirm that's there's supposed to be a vagrant symlink in ~/.local/bin, and `which` indeed reports ~/.local/bin/vagrant.

However, something puzzles me, as the vagrant "symlink" seems to in fact be a hardlink:
```
$ ls -lah ~/.local/bin/vagrant  
-rwxr-xr-x 1 MY_USER 1049089 2,8M oct.  11 03:52 /c/Users/PAOR/.local/bin/vagrant*
```

Does that mean Windows can't handle symlinks?

**Comment by chrisroberts** [comment]
When Vagrant is installed using the official Windows installer found at:

* https://www.vagrantup.com/downloads.html

it does not generate any user specific files. This includes the path you are describing above. It appears that you have installed Vagrant via an unofficial installer. Even if you have installed using the official installer there appears to be residual artifacts present from the previous installation. If the `./local/bin` path is at the start of your `PATH` there is nothing we can do to fix that. You will either need to remove that path or remove the vagrant executable found within that directory.

Cheers!
