### ISSUE TITLE
Error with vagrant up

### ISSUE THREAD

**Issue by githubuser123171** [hashicorp/vagrant#11274]
I am trying to run vagrant up on my Windows PC via git-bash, but I am receiving the below error:

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/precise64' version '20170427.0.0' is up to date...
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

I then run vagrant provision and this stop sat the below stage (lsast 10 lines added)

    default: pear/MDB2 is already installed and is the same as the released version 2.4.1
    default: install failed
    default: WARNING: channel "pear.php.net" has updated its protocols, use "pear channel-update pear.php.net" to update
    default: Skipping package "pear/MDB2", already installed as version 2.4.1
    default: No valid packages found
    default: install failed
    default: pear/Mail is already installed and is the same as the released version 1.4.1
    default: install failed
    default: pear/Net_SMTP is already installed and is the same as the released version 1.6.3
    default: install failed

I have run vagrant destroy and vagrant up and that worked, but when I try vagrant up again it brings the error which implies it hasn't installed properly.

I have also restarted my machine.

**Comment by chrisroberts** [comment]
Hi there. The issue you are describing is not from Vagrant itself. It appears you have a provisioner script which is not successfully completing. You will need to inspect that script and determine what error it is encountering to resolve this issue.

Cheers!
