### ISSUE TITLE
Invoking `vagrant ssh{,-config}` creates Traceback with docker provided machines without SSH capability

### ISSUE THREAD

**Issue by adrianbroher** [hashicorp/vagrant#11273]
### Vagrant version
$ vagrant -v
Vagrant 2.2.6

### Host operating system
$ cat /etc/fedora-release 
Fedora release 31 (Thirty One)

### Guest operating system
$ podman -v
podman version 1.6.2

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.define "myon.test" do |myon|
    myon.vm.box = "centos/8"

    myon.vm.provider "virtualbox" do |vb|
      vb.name = 'myon.test'
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end

    myon.vm.provider "libvirt" do |lv|
      lv.cpu_mode = 'host-passthrough'
    end

    myon.vm.synced_folder ".", "/vagrant", :disabled => true
  end

  config.vm.define "pebble.test" do |pebble|
    pebble.vm.provider "docker" do |docker|
      docker.image = "letsencrypt/pebble:v2.2.0"
      docker.ports = [ "14000:14000", "15000:15000" ]
      docker.cmd = [ "/usr/bin/pebble" ]
    end
  end
end
```

### Debug output
https://gist.github.com/adrianbroher/f4c80ac038757ef64bafc37cbb195696

### Expected behavior
When running the `vagrant ssh` or `vagrant ssh-config` command with a docker provided machine  present in a multi-machine setup and the docker image provides no SSH service the command should should fail with an error message notifying the user about the missing SSH capability of the Docker provided machine.

### Actual behavior
Both operations fail with a traceback as noted in the debug output.

Last line of traceback:

```
/usr/share/vagrant/gems/gems/vagrant-2.2.6/plugins/providers/docker/provider.rb:152:in `ssh_info': no implicit conversion of String into Integer (TypeError)
```

### Steps to reproduce
1. vagrant up pebble.test --provider=docker
2. vagrant ssh pebble.test
**OR**
3. vagrant ssh-config
**OR**
4. vagrant ssh-config pebble.test

### Additional notes:

Locally I could fix this by adding the following patch to the docker provider:

```
index 5a4779a..548b073 100644
--- a/plugins/providers/docker/provider.rb
+++ b/plugins/providers/docker/provider.rb
@@ -146,6 +146,9 @@ module VagrantPlugins
         # If the container isn't running, we can't SSH into it
         return nil if state.id != :running
 
+        # If the provider does not expose SSH, we can't provide a SSH config
+        return nil if !@machine.provider_config.has_ssh
+
         port_name = "#{@machine.config.ssh.guest_port}/tcp"
         network   = driver.inspect_container(@machine.id)['NetworkSettings']
```

However I neither have written any line of ruby code in my life nor I'm sure if this fix would be the correct approach for this issue as there a several place that may be more fitting for fixing this issue (e.g. the `cap`(abilities) module).

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
