### ISSUE TITLE
Network is unreliable in Vagrant for Windows

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/vagrant#11270]
Hi, I'm reopening a previously closed issue https://github.com/hashicorp/vagrant/issues/11256

At first I believed it was a bug in the `generic/ubuntu1804` box.
But I'm unable to reproduce the same bugs on Linux.
So I think it's a Vagrant issue, specific to Windows, or even `Hyper-V`

### Vagrant version
`Vagrant 2.2.6`

### Host operating system
Windows 10 build `1909`

### Guest operating system
[`generic/ubuntu1804`](https://app.vagrantup.com/generic/boxes/ubuntu1804)

### Vagrantfile
Please look at the following repository:
https://github.com/Wenzel/vagrant-oswatcher

Provider: `Hyper-V`

~~~Ruby
Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.box_version = "2.0.6"
    config.vm.define "oswatcher"
    # OSWatcher local git repo
    oswatcher_path = "/path/to/oswatcher"

    config.vm.provider "hyper-v" do |hyperv|
        hyperv.vmname = "oswatcher"
        hyperv.cpus = 2
        hyperv.memory = 2048
        # allow nested virtualization
        hyperv.enable_virtualization_extensions = true
    end

    config.vm.synced_folder ".", "/vagrant"
    # make oswatcher local path accessible as /vagrant/oswatcher
    config.vm.synced_folder oswatcher_path, "/vagrant/oswatcher"

    config.vm.provision "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "ansible/playbook.yml"
        ansible.extra_vars = {
          'oswatcher_path': "/vagrant/oswatcher",
        }
    end
end
~~~

### Debug output
I don't believe Vagrant's debug log are useful here,
since the box configuration seems to be the root cause of this issue.

### Expected behavior
The box should have been provisionned without any issues.

### Actual behavior
The Ansible playbook systematically fails because of a network issue:
- `Temporary failure resolving us.archive.ubuntu.com`
- `400 bad request`
- `404 not found`

Or even before the Ansible playbook is executed, the network fails.
![dns1](https://user-images.githubusercontent.com/964610/70867270-fa581c80-1f73-11ea-9017-9dbe930836cd.png)
![dns2](https://user-images.githubusercontent.com/964610/70867272-fcba7680-1f73-11ea-98ac-e2171bf2c645.png)
![dns3](https://user-images.githubusercontent.com/964610/70867273-ffb56700-1f73-11ea-875a-0b23ff7c3bd2.png)

And if it manages to execute the playbook, it systematically fails here:
![dns4](https://user-images.githubusercontent.com/964610/70867274-017f2a80-1f74-11ea-82d9-b64fde3384e0.png)

I had to add a `retry` statement in my Ansible task to force retry until the network is reachable:
~~~YAML
    - name: install OSWatcher system dependencies
      package:
        name: "{{ item }}"
      with_items:
        - virtualenv
        - python3-virtualenv
        - libguestfs0
        - libguestfs-dev
        - python3-guestfs
        - python3-dev
        - pkg-config
        - libvirt-dev
      register: result
      until: result is succeeded
      retries: 3
      delay: 10
~~~

Result:
![retry](https://user-images.githubusercontent.com/964610/70867327-9d109b00-1f74-11ea-9f8a-640341344498.png)

### Steps to reproduce
1. `git clone https://github.com/Wenzel/vagrant-oswatcher`
2. `git clone https://github.com/Wenzel/oswatcher`
3. Edit `vagrant-oswatcher/Vagrantfile` and set the local path to oswatcher's repo
4. `vagrant up --provider hyperv`

I tried to execute the same playbook on Linux, **multiple times**, with `vagrant-libvirt`, and it works:
![build_1](https://user-images.githubusercontent.com/964610/71184262-c9c8f900-2279-11ea-8b55-e8ffb4f3febd.png)
![build_2](https://user-images.githubusercontent.com/964610/71184269-cc2b5300-2279-11ea-8bc1-8ae870b1352d.png)

So the box is actually working, and the bug must on the Vagrant side I believe.

cc @briancain since you handled this issue the first time.

Thanks !

**Comment by Wenzel** [comment]
Hi @briancain,

I have more information regarding the mysterious DNS failures, via `journalctl`.
I see 2 kinds of errors:
- `NXDOMAIN`
- `DNSSEC validation`
![dns_failure](https://user-images.githubusercontent.com/964610/71321584-a3929b80-24bb-11ea-8901-306eb23dbd42.png)

**Comment by briancain** [comment]
Hey there @Wenzel - A question for you....have you tried a different ubuntu box in your testing? Like `bento/ubuntu-18.04`? Or `hashicorp/bionic64`? Additionally if both of those boxes have the same failure, it might be worth trying to add a Hyper-V machine manually outside of Vagrant to see if you experience the same networking issues. It doesn't look like your Vagrantfile is doing any network configuration. However, if those other boxes are fine then it's likely an issue with the box and not something Vagrant is doing. Thanks!

**Comment by Wenzel** [comment]
@briancain I installed Vagrant 2.2.7 and I cannot repro this issue so far.

i'm closing it for now.
Thanks !
