### ISSUE TITLE
Vagrant Hyper-V doesn't enable virtualization extensions

### ISSUE THREAD

**Issue by Wenzel** [hashicorp/vagrant#11279]
### Vagrant version
~~~
Installed Version: 2.2.6
Latest Version: 2.2.6

You're running an up-to-date version of Vagrant!
~~~

### Host operating system
Windows 10 Build `1909`

### Guest operating system
`generic/ubuntu1804`

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.box_version = "2.0.6"


    config.vm.provider "hyper-v" do |hyperv|
        hyperv.vmname = "test"
        hyperv.cpus = 1
        hyperv.memory = 128
        # allow nested virtualization
        hyperv.enable_virtualization_extensions = true
    end

    config.vm.provision "shell" do |s|
        s.inline = "egrep '(vmx|svm)' /proc/cpuinfo"
    end
end
```

### Debug output
[gist](https://gist.github.com/Wenzel/4269caab334cbf0e5d89a97bdc5ce81d)

### Expected behavior
the shell command should have returned 0, since the `vmx` extensions should have been detected in `cpuinfo`

### Actual behavior
![Sans titre](https://user-images.githubusercontent.com/964610/71315402-c6da2e00-245c-11ea-9583-40d7e77d62dc.png)

### Steps to reproduce
1. `vagrant up --provider hyperv`

Thanks Vagrant team !

**Comment by Wenzel** [comment]
hi @jbonhag , 

you tagged the issue as `needs-repro`.
I provided the Vagrantfile, and I can repro the bug on the latest release (2.2.7).

Is there something else that you need ?

Thanks.

**Comment by jbonhag** [comment]
Hi @Wenzel,

I'm very sorry about the slow reply -- you did a great job providing us with information but it seems like we lost track of this issue. Thanks for the ping today to bring it back to our attention.

It looks like the the provider name should be `hyperv` and not `hyper-v`. In other words, this configuration worked for me:

```
  config.vm.provider "hyperv" do |hyperv|
    hyperv.vmname = "test"
    hyperv.cpus = 1
    hyperv.memory = 2048
    # allow nested virtualization
    hyperv.enable_virtualization_extensions = true
  end
```

Result of `vagrant up`:
```
==> default: Running provisioner: shell...
    default: Running: inline script
    default: flags              : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid fsgsbase bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt xsaveopt xsavec xsaves md_clear flush_l1d arch_capabilities
```

I'm going to go ahead and close this issue, but feel free to open a new one if you have any issues in the future.

Cheers! 😄
