### ISSUE TITLE
Prompting for smb_username when it's already specified in the Vagrantfile

### ISSUE THREAD

**Issue by BradyDonovan** [hashicorp/vagrant#11289]
### Vagrant version
2.2.6

### Host operating system
Windows 10 Version 1909, Build 18363.535

### Guest operating system
Windows 10 Version 1909, Build 18363.535

### Vagrantfile
(relevant bit included)
```ruby
config.vm.synced_folder "C:/ShareFolder", "/vagrant", type: "smb", smb_username: "xxxx"
```

### Debug output
N/A

### Expected behavior
Not be prompted for smb_username when it's already defined in the Vagrantfile.

### Actual behavior
Prompted for the smb_username.

### Steps to reproduce
1. Create a Vagrantfile with the line above.
2. `vagrant up`
3. Wait for prompt.

### References
I took a look at the code and was wondering if this makes more sense:
```ruby
unless data[:smb_username] # or smb_username?
    username = machine.ui.ask("Username: ")
    smb_username = username if username != ""
    modify_username = true
end
```

instead of [what you have now](https://github.com/hashicorp/vagrant/blob/master/plugins/synced_folders/smb/synced_folder.rb#L55):
```ruby
while retries < CREDENTIAL_RETRY_MAX do
    if smb_username
        username = machine.ui.ask("Username (#{smb_username}): ")
        smb_username = username if username != ""
        modify_username = true
    else
        smb_username = machine.ui.ask("Username: ")
    end
```

Please pardon any Ruby mistakes. Still learning. :)

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening this issue.  We appreciate the suggestion, but unfortunately we aren't going to make the change at this time.  Unless both the SMB username and password are set in the Vagrantfile, user input is required when bringing up the guest.  This also gives the user a chance to override the default username (for example if multiple developers are sharing a single Vagrantfile).

I understand that it may seem like a pain to have to press enter to accept the username, but this behavior has been in place for quite some time and we are reluctant to change it now.

Cheers and have a great day!
