### ISSUE TITLE
vagrant provision --provision-with name only accepts types, not names

### ISSUE THREAD

**Issue by anon8675309** [hashicorp/vagrant#11287]
### Vagrant version
Vagrant 2.2.6

### Host operating system
Ubuntu 18.04 x64

### Guest operating system
Ubuntu 18.04 x64

### Vagrantfile
Any Vagrantfile 
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  #config.vm.provision "shell", path: "test.sh", name: "test.sh"
end
```

### Debug output
https://gist.github.com/anon8675309/028b034f30726e4bdae89f5a141a2999

The punchline is just this:
```
$ # Attempt to provision by name
$ vagrant provision --provision-with "test.sh"
$ # Attempt to provision by type
$ vagrant provision --provision-with "shell"
==> default: Running provisioner: shell...
    default: Running: script: test.sh
$ # Confirm that the help text shows that --provision-with takes either type or name as an argument
$ vagrant provision -h
Usage: vagrant provision [vm-name] [--provision-with x,y,z]
        --provision-with x,y,z       Enable only certain provisioners, by type or by name.
-h, --help Print this help
```

### Expected behavior
The test.sh script should run when the name given to --provision-with matches the name in the Vagrantfile.

If this feature worked, it would be fantastic tool for iterating and debugging a provisioner that is not working as expected!  The work flow would be: snapshot, run provisioner (which will fail because writing scripts is hard), change script, restore snapshot, re-run provisioner.

The key here is the ability to just run one of the shell script, as opposed to running all the shell scripts.  My workaround is to keep editing the Vagrantfile to comment out the scripts which ran successfully and then re-run all of the file and shell provisioners.

### Actual behavior
The test.sh script does not run.

### Steps to reproduce
See gist link above

### References
I searched for this issue, expecting to find it, but I went through 5 pages of issues and was unable to find this having been reported.  I also noticed the the documentation on the web does not match the help text: https://www.vagrantup.com/docs/cli/provision.html The web documentation makes no mention of running it by name, then again the word "type" is nowhere to be found in that documentation either.

If this is a missing feature, then this ticket is just to update the help text to stop advertising the feature.

**Comment by efussi** [comment]
I hit the same issue and worked around it by using the following style in **Vagrantfile**:
```ruby
config.vm.provision "install_git", type: "shell", inline: install_git
```
With this, I can run `vagrant up --provision-with install_git` even if I have quite a few shell provisioners.

**Comment by jbonhag** [comment]
Hi @anon8675309, and thanks for opening an issue with Vagrant!

It definitely seems like this is a bug, but as @efussi pointed out, you might be able to work around it by setting your provisioners up in a certain way.  So given this config:

```
config.vm.provision "test.sh", path: "test.sh", type: "shell"
```

You can either provision by name (which will only run this provisioner):

```
vagrant provision --provision-with test.sh
```

or type (which will run all the shell provisioners):

```
vagrant provision --provision-with shell
```

We'll look into fixing this issue.  Thanks again!
