### ISSUE TITLE
Time out error while connecting to centos/7 guest machine

### ISSUE THREAD

**Issue by VijayaAlbu** [hashicorp/vagrant#11297]
Setup on my machine
Virtualbox version - Version 6.0.14 r133895
Vagrant 2.2.6
I was able to install ubuntu successfully on vagrant and connect also
But when I tried centos7
it is giving me below error message
"default: SSH username: vagrant
default: SSH auth method: private key

Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well."

Could you please help me to resolve the above error?

Regards
Vijaya

**Comment by jbonhag** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by VijayaAlbu** [comment]
Raised new issue.
