### ISSUE TITLE
trying to run vagrant package using developer build throwing error

### ISSUE THREAD

**Issue by rememberthebear** [hashicorp/vagrant#11301]
Since Hashicorp is taking its time in releasing an updated version of vagrant with support for virtualbox 6.1, I have been using vagrant's dev build which does have support for virtualbox 6.1.  While vagrant up works perfectly using the dev build, vagrant package is not working.  I am attempting to upload an updated virtualbox vagrant box to the vagrant cloud, so I run the below command with the vagrant repo folder as the CWD:

```ruby
bundle exec vagrant --base go --vagrantfile ../../vagrant/vagrantfile
```

The command will then appear to work for an extended period of time, but will then inevitably throw this error:

```
The executable 'bsdtar' Vagrant is trying to run was not found in the %PATH% variable. This is an error. Please verify this software is installed and on the path.
```

So, it would appear we need to figure out why the local vagrant executable is unable to locate the executables it needs

### Vagrant version
Vagrant 2.2.7.dev

### Host operating system
Windows 10 x64

### Guest operating system
Server 2016

### Vagrantfile
```ruby
NA
```

### Debug output
https://gist.github.com/rememberthebear/7925cabff93f68d5a1672ee0f25d5281

### Expected behavior
The vagrant box should be created successfully

### Actual behavior
got above error

### Steps to reproduce
1. using the current dev build of vagrant, try to create a virtualbox vagrant box using command above
2.
3.

**Comment by chrisroberts** [comment]
Vagrant uses the `bsdtar` command for compressing and decompressing boxes. This command needs to be installed and available on the system's configured PATH. You are receiving this error because Vagrant cannot find the executable. Installing the bsdtar executable and making it available on the PATH will resolve this issue.

Cheers!
