### ISSUE TITLE
There was an error while executing `VBoxManage`, a CLI used by Vagrant for controlling VirtualBox. 

### ISSUE THREAD

**Issue by aliahmadcse** [hashicorp/vagrant#11325]
> Can anyone help me with the issue? I am using Windows 10 home.

laravel-essentials: 27017 (guest) => 27017 (host) (adapter 1)
    laravel-essentials: 22 (guest) => 2222 (host) (adapter 1)
==> laravel-essentials: Running 'pre-boot' VM customizations...
==> laravel-essentials: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "8641023c-7df8-4c81-998d-76195cc551ad", "--type", "headless"]

Stderr: VBoxManage.exe: error: Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant!  This error indicates that VirtualBox cannot start the VM with your current setup. Please check your computer's BIOS settings to make sure that CPU virtualization options are turned on -- it could also be the case that your CPU doesn't support virtualization.

In any event, this doesn't appear to be an issue with Vagrant, so I'm going to close this issue. I'd recommend searching the [VirtualBox forums](https://forums.virtualbox.org/) for that specific error message if you have further questions.

Cheers and have a great day! 😄
