### ISSUE TITLE
Vagrant not starting automatically upon restart on Windows 10

### ISSUE THREAD

**Issue by jared-d-nye** [hashicorp/vagrant#11343]
### Vagrant version
Newest one, 2.2.6

### Host operating system
Windows 10

### Guest operating system
Ubuntu 18.4

### Actual behavior
Vagrant installer must be opened, and asks whether I would like to Repair or Remove Vagrant. Upon repairing, the same issue of Vagrant not automatically starting after restart occurs. If removing and uninstalling Vagrant, the same issues occur upon installing it again.

### Expected behavior
Vagrant should have automatically started up and opened VirtualBox.

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! Vagrant is a command-line tool, so you shouldn't need to re-open the Vagrant installer after Vagrant is installed. For example, creating and running a virtual machine can be accomplished by typing the following into the Windows command prompt:

```
vagrant init hashicorp/bionic64
vagrant up
```

By default, this will bring up a "headless" VM, so it won't open the VirtualBox window.

I hope that solves your issue -- if not, would you mind providing a copy of the Vagrantfile you're using?

**Comment by jared-d-nye** [comment]
The problem is that the installation is not completing/taking affect after I restart my computer. Instead, when I go to open the vagrant_installer it prompts me to Repair or Remove Vagrant. There is no application of Vagrant to open either, so vagrant init/vagrant up does not run. The vagrant installer file I am using is from the vagrant website, 2.2.6 edition. I have already downloaded Virtual Box and a Virtual Box Extension Pack. The download worked on my laptop for Windows 10, however I don't have the RAM to run it on my laptop without a very bad lag.

**Comment by chrisroberts** [comment]
Hi there,

Vagrant does not install as an application that you open via the GUI. After you have installed Vagrant you do not need to run the installer again. Open either a `cmd.exe` window or a `powershell.exe` window and then type `vagrant`. You should then see the available Vagrant commands displayed. Vagrant is not a system process and does not start automatically. It is a tool that you can call from a command or powershell window.

Cheers!
