### ISSUE TITLE
Provider vmware_desktop on macOS Catalina throws cannot load such file -- vagrant/vmware/desktop - RubyEncoder bundlers are not signed

### ISSUE THREAD

**Issue by jmoody** [hashicorp/vagrant#11348]
### Vagrant
Vagrant 2.2.7

### Host operation system
macOS Catalina 10.15.2

### Guest operating system
ubuntu 18.04

### Vagrantfile

Doesn't matter.

### Debug output

https://gist.github.com/jmoody/6050b50ca0571f3730c0b6d769bc3131

### Expected behavior

The vmware_desktop plugin should have loaded.

### Actual behavior

The plug-in did not load because the bundles in `/opt/vagrant/embedded/rgloader` are not signed.

If you try to sign ad hoc or properly sign these binaries, you get a different error:

```
not valid for use in process using Library Validation: mapping process and mapped file (non-platform) have different Team IDs
```

I needed to add some debugging statements to `/opt/vagrant/embedded/rgloader/loader.rb` to see what the actual problem was.

I don't know if this bug should be filed here or whether I should contact http://www.rubyencoder.com

On first run, macOS pops a GUI alert saying that the bundle is not safe to load.  If you have System Preferences open, you will be prompted to allow the load - this appears to have no effect.

**Comment by AntonioMeireles** [comment]
same here fwiw.

**Comment by jmoody** [comment]
On Mojave, the encoder is signed:

```
Authority=Developer ID Application: Hashicorp, Inc. (D38WU7D763)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
```

**Comment by jmoody** [comment]
I checked all the archives here https://www.rubyencoder.com/loaders.html - none of the *.bundle have code signatures.

**Comment by chrisroberts** [comment]
@jmoody Thanks for the report. I'm investigating now and will have a fix up as soon as possible.

**Comment by spencerhakim** [comment]
This also breaks vagrant-parallels and vagrant-libvirt, which both depend on nokogiri

```
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/shakim/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle, 9): no suitable image found.  Did find: (LoadError)
	/Users/shakim/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle: code signature in (/Users/shakim/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. - /Users/shakim/.vagrant.d/gems/2.4.9/gems/nokogiri-1.10.7/lib/nokogiri/nokogiri.bundle
```

**Comment by spencerhakim** [comment]
[This change](https://github.com/hashicorp/vagrant-installers/commit/e3ed0f36bbee1008c9d793f3b5af6f3a77169da7#diff-08a9aaf4fc61fe775056fac77740a2acR108) is causing the issue, specifically the addition of `--options=runtime` argument to `codesign`. From the man page, `runtime` is a superset of the other hardening options, including `library`, which says:

>Forces the signed code's library validation flag to be set when the code begins execution.  The code will only be able to link against system libraries and frameworks, or libraries, frameworks, and plug-in bundles **with the same team identifier embedded** in the code directory.  Team identifiers are automatically recorded in signatures when signing with suitable Apple-issued signing certificates.  Note that the flag is not supported for i386 binaries, and only applies to the main executable.  The flag has no effect when set on frameworks and libraries.

Obviously any bundles installed via plugins likely won't be signed with the same Team ID as vagrant, if they're signed at all.

**Comment by ndobbs** [comment]
Just wanted to chime in and mention I'm seeing the same issues after just upgrading from vagrant `2.2.6` to `2.2.7`.

**Comment by chrisroberts** [comment]
Hi everyone. Thanks for the reports. My apologies for the issues with the new release. The additions of the code signing within the installer as well as the notarization process introduced some new complexity that I've still been getting ironed out.

I've rebuilt the 2.2.7 install DMG to address the issues here and it is now available at https://releases.hashicorp.com/vagrant/2.2.7

If you encounter any other issues please open a new issue with the details.

Cheers!

**Comment by jmoody** [comment]
Thanks for the fast turn around!

It might be helpful to improve the error reporting in the rgloader/loader.rb file.

The LoadError error had the necessary information in it to uncover the problem, but it was silently ignored.  I had to edit the loader.rb to uncover the real problem.

**Comment by chrisroberts** [comment]
@jmoody Thanks for the suggestion. I will be including an update to it in the next release to prevent it from being suppressed.
