### ISSUE TITLE
Error fsevent on rsync-auto

### ISSUE THREAD

**Issue by willoucom** [hashicorp/vagrant#11346]
### Vagrant version
Vagrant 2.2.7

### Host operating system
MacOS 10.15.2
 
### Guest operating system
debian buster

### Vagrantfile
default (generated by vagrant init)

### Debug output
https://gist.github.com/willoucom/e16100ae2cad31ac01baa37eb07d16f9

### Expected behavior
vagrant rsync-auto watch the directory and perform rsync operations

### Actual behavior
Ruby error (fsevent: running worker failed: No such file or directory)

### Steps to reproduce
1. fresh install on MacOs
2. vagrant init debian/buster64
3. vagrant up
4. vagrant rsync-auto
5. error after the initial rsync

**Comment by willoucom** [comment]
Workaround : 
1. install fswatch (https://github.com/emcrisostomo/fswatch)
2. run in your directory `fswatch -0 . | xargs -0 -I {} vagrant rsync`

**Comment by jbonhag** [comment]
Hi @willoucom, thank you for reporting this issue.  It appears that the `fsevent_watch` binary was excluded from the macOS install.

You might also have some luck downloading that binary directly from the [source repo](https://github.com/thibaudgg/rb-fsevent/tree/v0.10.3/bin) and copying it into your installer:

    /opt/vagrant/embedded/gems/2.2.7/gems/rb-fsevent-0.10.3/bin/fsevent_watch

Sorry you ran into this, and thanks again for letting us know.

**Comment by chrisroberts** [comment]
@willoucom Hi and thanks for the report. I've updated the 2.2.7 installer for macOS which includes a fix for this issue. Re-downloading and installing should resolve the issue. 

Cheers!

**Comment by willoucom** [comment]
New version work as intended, thanks @chrisroberts
