### ISSUE TITLE
Installing an OSX VM using vagrant and VirtualBox

### ISSUE THREAD

**Issue by Skitoris** [hashicorp/vagrant#11340]
Hi, 

i'm learning how to use vagrant with virtualbox. I've install with ease an Ubuntu VM, a CentOS VM, a WinServ VM and i'm trying now with an OSX VM. I have plenty of space on my SSD (220GO available), but still get the same error.

Can anyone help me with that ?

Vagrant V.2.2.6
VirtualBox 6.0.16

![Error2](https://user-images.githubusercontent.com/60368216/73217634-49be6a80-4126-11ea-94c2-224820de3f0e.PNG)

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by bitsydarel** [comment]
@Skitoris you can use my box of osx mojave

https://app.vagrantup.com/bitsydarel/boxes/macOSSandBox

Tested it on windows and it's seems to work.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
