### ISSUE TITLE
Box fetching still slow....  hashibot very unhelpful

### ISSUE THREAD

**Issue by bradisbell** [hashicorp/vagrant#11342]
This issue has been closed, but shouldn't be:  https://github.com/hashicorp/vagrant/issues/8434#issuecomment-579043095_

Fetching boxes is still slow.  Plenty of detail captured in the previous ticket, which should not have been closed.

**Comment by bradisbell** [comment]
Also auto-closed is this issue:  https://github.com/hashicorp/vagrant/issues/1248#issuecomment-579044538

This problem still exists.  These sort of auto-close bots are very frustrating.

**Comment by taurus-forever** [comment]
The same here: https://github.com/hashicorp/vagrant/issues/10976
and here: https://github.com/hashicorp/vagrant/issues/10972

I am actively searching Vagrant alternatives now,
such way of solving bug reports in unacceptable.
Folks any options here?

Hashisoft, consider to provide commercial support if you have no resources for bugfixing.

**Comment by chrisroberts** [comment]
This is a duplicate of older issues and is addressed here: #11354

Cheers!
