### ISSUE TITLE
vagrant takes more time while executing the simple command :(

### ISSUE THREAD

**Issue by gyoganandhan** [hashicorp/vagrant#11351]
Hi Team,

Its takes more time while executing the simple command (ex:  PS C:\Users\yogan> measure-command { vagrant | out-host }).. 

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 5
Milliseconds      : 886
Ticks             : 58866677
TotalDays         : 6.81327280092593E-05
TotalHours        : 0.00163518547222222
TotalMinutes      : 0.0981111283333333
TotalSeconds      : 5.8866677
TotalMilliseconds : 5886.6677

I am using windows 10 Home edition 
--------------------------------------------
![image](https://user-images.githubusercontent.com/20402478/73361358-d2760b80-42ca-11ea-95d0-0d40fe5d3610.png)

Kindly help to fix this issue. i am so upset while take more time to execute any command in vagrant.

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! It's normal for Vagrant to take a few seconds to load.  When you run a `vagrant` command, it registers the plugins that Vagrant needs.  It also detects the virtual machine providers (VirtualBox, Hyper-V, etc.) installed on your system.

If you'd like to see exactly what Vagrant is doing behind the scenes, you can add the `--debug` flag to any Vagrant command to get detailed logs.  For example:

```
measure-command { vagrant --debug | out-host }
```

Cheers and have a great day! :smile:
