### ISSUE TITLE
vagrant up win2k8 .... network issues

### ISSUE THREAD

**Issue by IsaacSxm** [hashicorp/vagrant#11364]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
2.2.7
### Host operating system
Windows 10

### Guest operating system
Metasploitable 3.

I need help to solve this problem. Thank you.

PS C:\Users\rhyme\metasploitable3-master> vagrant up win2k8
Bringing machine 'win2k8' up with 'virtualbox' provider...
==> win2k8: Checking if box 'rapid7/metasploitable3-win2k8' version '0.1.0-weekly' is up to date...
==> win2k8: Clearing any previously set network interfaces...
A host only network interface you're attempting to configure via DHCP
already has a conflicting host only adapter with DHCP enabled. The
DHCP on this adapter is incompatible with the DHCP settings. Two
host only network interfaces are not allowed to overlap, and each
host only network interface can have only one DHCP server. Please
reconfigure your host only network or remove the virtual machine
using the other host only network.

**Comment by IsaacSxm** [comment]
I tried running `VBoxManage dhcpserver remove --netname 
`

C:\Program Files\Oracle\VirtualBox>VBoxManage dhcpserver remove --netname HostInterfaceNetworking-vboxnet0
VBoxManage.exe: error: Failed to find DHCP server for network 'HostInterfaceNetworking-vboxnet0'

**Comment by briancain** [comment]
@IsaacSxm - Please provide us with the Vagrantfile you are using to bring up the guest. Thanks!

**Comment by j3mdamas** [comment]
I am facing the same issue.

Vagrant version: 2.2.7
VM provider: VirtualBox version 6.1.2 r135662
Host OS: Windows 10

Vagrantfile (simplified to maximum):
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", type: "dhcp"
end
```

Specifically, it's an issue when there is already a network adapter setup. If I remove all adapters from VirtualBox, it will not fail. But after that it always fails with:
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/xenial64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/xenial64' version '20200212.0.0' is up to date...
==> default: Setting the name of the VM: test_default_1581522643782_42165
==> default: Clearing any previously set network interfaces...
A host only network interface you're attempting to configure via DHCP
already has a conflicting host only adapter with DHCP enabled. The
DHCP on this adapter is incompatible with the DHCP settings. Two
host only network interfaces are not allowed to overlap, and each
host only network interface can have only one DHCP server. Please
reconfigure your host only network or remove the virtual machine
using the other host only network.
```

I'll have to revert all the software to previous versions to fix this, I guess.

**Comment by briancain** [comment]
Hey all, this seems to be a duplicate issue of https://github.com/hashicorp/vagrant/issues/8878. Please put all relevant information in that thread instead such as a Vagrantfile used, and a complete debug log from running `vagrant up --debug`, saved on a [gist](https://gist.github.com/). Thanks!
