### ISSUE TITLE
Starting Vagrant share with ngrok crashes if there is a space in the path to ngrok.yml

### ISSUE THREAD

**Issue by jmdishaw** [hashicorp/vagrant#11372]
### Vagrant version
2.2.7

### ngrok version
2.2.8

### Host operating system
Windows 10

### Guest operating system
Ubuntu 18.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"
	config.vm.provision :shell, path: "bootstrap.sh"
	config.vm.network :forwarded_port, guest: 80, host: 4567
end
```

### Debug output
Clipped to what I believe is the relevant part.
https://gist.github.com/jmdishaw/7e15cce811d190bf5c952b05f8ceb287

### Expected behavior
Ngrok finds and reads ngrok.yml

### Actual behavior
Vagrant parses the space in the filepath as a parameter separator. In this case, the filepath is "C:/Users/Jonathan Dishaw/.ngrok2/ngrok.yml". However, Vagrant seems to pass "C:/Users/Jonathan" and "Dishaw/.ngrok2/ngrok.yml" as two separate parameters, which confuses ngrok.

### Steps to reproduce
As described in Vagrant's Getting Started series. https://www.vagrantup.com/intro/getting-started/share.html
1. vagrant up
2. vagrant share

**Comment by briancain** [comment]
Hey there - I believe this has been fixed with the recent update to the plugin. Please update your vagrant-share plugin. If you are still experiencing this issue or a different one, feel free to open a new issue. Thanks!
