### ISSUE TITLE
Boot issue on vagrant VM

### ISSUE THREAD

**Issue by luisdiaswiz** [hashicorp/vagrant#11377]
### Vagrant version
2.2.7

### VirtuaBox version
Version 6.0.16 r135674 (Qt5.6.3)

[homestead.webm.zip](https://github.com/hashicorp/vagrant/files/4165546/homestead.webm.zip)

### Host operating system
MacOs High Sierra
10.13.6

### Guest operating system
Ubunto (64)

### Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
customizationScriptPath = confDir + "/user-customizations.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 2.2.4'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases && chown vagrant:vagrant /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON::parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if File.exist? customizationScriptPath then
        config.vm.provision "shell", path: customizationScriptPath, privileged: false, keep_color: true
    end

    if Vagrant.has_plugin?('vagrant-hostsupdater')
        config.hostsupdater.remove_on_suspend = false
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    elsif Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.aliases = settings['sites'].map { |site| site['map'] }
    end

    if Vagrant.has_plugin?('vagrant-notify-forwarder')
        config.notify_forwarder.enable = true
    end

    config.vm.boot_timeout = 300

    config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    end

    config.vm.provider "virtualbox" do |v|
        v.gui = true
    end
end
```

Hello,

I am using a Homestead vagrant VM and the strangest thing is happening.  After working fine for a few months the VM just stopped working. I tried reinstalling everything and setting up again and what happened was that after installing everything and running the VM for the first time with vagrant up everything works fine. It takes some time to provision the VM but it runs for the first time.

The subsequent times after halting the VM for the first time, the VM stops booting, entering emergency mode.
I am attaching a recording of the VM's boot sequence with the errors.
[homestead.webm.zip](https://github.com/hashicorp/vagrant/files/4165560/homestead.webm.zip)

I have tried removing the box twice and reinstalling VirtualBox and Vagrant but the same keeps happening.

Can anyone provide some help?

Thanks in advance.

Luis Dias

**Comment by briancain** [comment]
Hey there @luisdiaswiz - I recommend opening an issue with the [Homestead](https://github.com/laravel/homestead) folks instead. It is a separate project from Vagrant. Thanks!

**Comment by luisdiaswiz** [comment]
Hi,

I did that, but since it can be a vagrant issue I also posted here. Did you get a chance to see the boot sequence?

**Comment by briancain** [comment]
If you have a specific vagrant log that demonstrates an error or issue we'll be happy to help! Generally VM errors can be any number of things, and Homestead does a lot of configuration that is non-standard to a plain Vagrant config. I recommend speaking to them, as they will be more familiar with their setup and the VM used.
