### ISSUE TITLE
winrm-fs 1.3.4 requires rubyzip ~> 2.0, conflicts with vagrants rubyzip ~> 1.3 

### ISSUE THREAD

**Issue by StefanBruens** [hashicorp/vagrant#11375]
### Vagrant version
2.2.7

### Host operating system
openSUSE Tumbleweed

### Expected behavior
vagrant has a an up-to-date, non-conflicting dependency set.

### Actual behavior
vagrant wants rubyzip ~> 1.3
winrm-fs 1.3.4 wants rubyzip ~> 2.0

### References
https://github.com/WinRb/winrm-fs/commit/6b20529b088c15fe5d4c606d49eebf318cc8b2f6

**Comment by StefanBruens** [comment]
Fixed by https://github.com/hashicorp/vagrant/pull/11339

**Comment by briancain** [comment]
Closing this, as the PR is now merged.
