### ISSUE TITLE
Problem with macOs Catalina and multiple boxes on an encrypted secondary Volume

### ISSUE THREAD

**Issue by jschlier** [hashicorp/vagrant#11374]
I'm running Vagrant 2.2.7 on macOs 10.15.3 and am trying to use boot up several Vagrant boxes running Ubuntu 18.04 at the same time.

I have a separate partition or "Volume", as Apple calls them, for all my development projects.
This Volume is case-sensitive and encrypted.

The Vagrant files are in each in a seperate folder and include their root path to mount into the Vagrant box:
```ruby
  config.vm.synced_folder '.', '/mnt/vagrant', OSX ? { nfs: true } : nil
```

This works fine as long as one box is running, as soon as I try to boot a second Vagrant box mounting the NFS shared folders fails with the following message:

```
==> vagrant: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 192.168.33.1:/System/Volumes/Data/Volumes/development/projects/ukhd /mnt/vagrant

Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 192.168.33.1:/System/Volumes/Data/Volumes/development/projects/ukhd
```

This also works when all boxes are running on the main macOs Volume, e.g. when all projects and their folders are in the user directory.

**Comment by chrisroberts** [comment]
Hi there,

Would you please provide a gist of the debug output from running `vagrant up` which results in the failure. Thanks!

**Comment by jschlier** [comment]
Hey,
sorry I forgot about the debugging gist. Here's the link to it:
https://gist.github.com/jschlier/7ad39e88e16da67312c4a005fe18e016

**Comment by chrisroberts** [comment]
@jschlier Thanks for the debug gist! Just to confirm the behavior you are encountering:

* Multiple Vagrant projects exist on a secondary volume
* Starting a guest in one project works
* Starting an additional guest in that project, or another on the secondary volume, fails

Is that the behavior you are encountering?

Thanks!

**Comment by jschlier** [comment]
Correct.
Starting another Project on the same Volume is the problem.

Starting a second project that lies somewhere within the mac's user folder works. It seems to be specific to the secondary volume.

**Comment by LikeAJohny** [comment]
I ran into the same Error today. I'm running the exact same setup as the OP though I may add that my VirtualBox Version is 6.1.4.

`config.vm.synced_folder '.', '/vagrant', nfs: true,`
`config.vm.synced_folder '.', '/vagrant', nfs: true, nfs_udp: false`

Both giving the same error that's already mentioned.

There's one thing I wanna add that hopefully comes in handy for someone:

### `showmount` on VM
When I `vagrant ssh` into one of the machines and check for the output of `sudo showmount -e <HOST_IP>` I end up with the same mount directory entered on both of them. For example:
`/System/Volumes/Data/Volumes/Dev/bugsolving/nfs_catalina/bar 192.168.101.123`.
This is while one of the machines lives in `/System/Volumes/Data/Volumes/Dev/bugsolving/nfs_catalina/foo`.
The `/etc/exports` file holds both of the mount directories correctly entered like:
```shell
# VAGRANT-BEGIN: 501 3cbb6f7b-75e9-43bd-9286-3f1a4717c17d
/System/Volumes/Data/Volumes/Dev/bugsolving/nfs_catalina/bar -alldirs -mapall=501:80 192.168.101.123
# VAGRANT-END: 501 3cbb6f7b-75e9-43bd-9286-3f1a4717c17d
# VAGRANT-BEGIN: 501 a604d524-741e-4750-8496-d5ce56c9d6a4
/System/Volumes/Data/Volumes/Dev/bugsolving/nfs_catalina/foo -alldirs -mapall=501:80 192.168.101.124
# VAGRANT-END: 501 a604d524-741e-4750-8496-d5ce56c9d6a4
```
What bugs me though is that every time I reload one of the machines the `exports` file changes. The entry order changes on every reload or halt|up, meaning the entry gets removed and reentered?! Why is that?

I've tried this with up to 5 seperated machines - all on the same Volume ofc, like OP mentioned - all with the same outcome.
The output of `showmount` shows the directory of the first created machine to this point.

@jschlier Do you have something new found out?

**Comment by jschlier** [comment]
Thanks for debugging @LikeAJohny. Unfortunately I don't have anything new.

Good thing you mention VirtualBox. I forgot to mention that I use that. I don't know which version I used when creating this ticket, but I am on VirtualBox 6.1.4 as well (and still having this issue).

I hope your debugging can help some of the people at HashiCorp though. 👍

**Comment by jschlier** [comment]
**Update**

Updating VirtualBox to version 6.1.6 seems to resolve this issue.
As I (and others from our team) don't have the problem anymore I'm going to close this issue.

Thanks for looking into it @chrisroberts  and @LikeAJohny.

**Comment by LikeAJohny** [comment]
Can confirm, VB 6.1.6 fixes the odd behaviour.
