### ISSUE TITLE
vagrant up fails - /opt/vagrant/embedded/lib/ruby/2.4.0/fileutils.rb:1052: [BUG] Segmentation fault at 0x0000000000000000

### ISSUE THREAD

**Issue by noi5e** [hashicorp/vagrant#11376]
### Vagrant version
Vagrant 2.2.7

### Host operating system
MacOS Sierra 10.12.6

### Guest operating system
Unsure? hashicorp/bionic64

### Vagrantfile
Nothing fancy in there, just the above hashicorp/bionic64

### Debug output
1st line of the output is: /opt/vagrant/embedded/lib/ruby/2.4.0/fileutils.rb:1052: [BUG] Segmentation fault at 0x0000000000000000

Full output here: https://gist.github.com/noi5e/3a0d1f8927212cc426898a3ceedec704

**Comment by briancain** [comment]
Hey there @noi5e - Could you provide us with the full debug log by including the `--debug` flag? Also, generally you shouldn't be running Vagrant with `sudo`. Do you get a different result if you run Vagrant without it? Thanks!

**Comment by noi5e** [comment]
Hey @briancain thanks, yeah, I get the same error with or without `sudo`.

Here's the debug log for `vagrant up --debug` without `sudo`: https://gist.github.com/noi5e/c2245c8187ef12bfb1affb735a167430

**Comment by noi5e** [comment]
@briancain Upgrading to High Sierra has fixed this problem. Closing the issue.

**Comment by johnfrancismccann** [comment]
@noi5e @briancain 

I reproduced this same behavior on my machine (gist below):

### Vagrant version
2.2.7

### Host operating system
MacOS Sierra 10.12.4 (16E195)
Darwin 16.5.0

### Guest operating system
Ubuntu 18.04 64-bit

### Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
end
```
### Debug output
[stdout](https://gist.github.com/johnfrancismccann/d8b12927f2bf079c8ef2151e37baa498) (Search for "Segmentation Fault")
[~/Library/Logs/DiagnosticReports/ruby_2020-03-04-225558_Johns-MacBook-Air.crash](https://gist.github.com/johnfrancismccann/629384777b36e614feb4877e2c23e505)

### Expected behavior
Vagrant doesn't segfault.

### Actual behavior
Vagrant segfaults.

### Steps to reproduce

1.  `vagrant up --debug`

**Comment by johnfrancismccann** [comment]
The segfault can be more quickly reproduced:
```
$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin16]
$ /opt/vagrant/embedded/bin/ruby --version
ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-darwin19]
$
$
$ cat utime.rb
File.utime(nil, nil, 'hello.txt')
$ ruby utime.rb
Traceback (most recent call last):
	1: from utime.rb:1:in `<main>'
utime.rb:1:in `utime': No such file or directory @ apply2files - hello.txt (Errno::ENOENT)
$ /opt/vagrant/embedded/bin/ruby utime.rb
utime.rb:1: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-darwin19]
.
.
.
```

I’m not sure if this would have anything to do with the fact that the kernel on my machine is Darwin 16.5.0 while the Vagrant ruby installation appears to be complied for Darwin 19.

**Comment by johnfrancismccann** [comment]
Also, this segmentation fault doesn't occur while using Vagrant 2.2.6 with the above-described environment.
```
$ vagrant --version
Vagrant 2.2.6
$ /opt/vagrant/embedded/bin/ruby --version
ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-darwin13]
$ /opt/vagrant/embedded/bin/ruby utime.rb
utime.rb:1:in `utime': No such file or directory @ utime_internal - hello.txt (Errno::ENOENT)
	from utime.rb:1:in `<main>'
$
```

**Comment by cartaviam** [comment]
Was able to solve this! While running Mac OS Sierra (which won't allow to upgrade to High Sierra), every single vm been vagrant up-ed would fail with same ruby/2.4.0/fileutils.rb:1052 Segmentation Fault.

Solution: Make sure Vagrant and Virtualbox are compatible with OS Sierra. Which are: Vagrant 2.1.0 and Virtualbox 5.2.0
