### ISSUE TITLE
Error with vagrant up --provider=aws 

### ISSUE THREAD

**Issue by nickpwhite** [hashicorp/vagrant#11371]
### Vagrant version
```bash
$ vagrant --version
Vagrant 2.2.7
```

This worked in version 2.2.6 but not in 2.2.7 which is why I've opened the issue here instead of with the `vagrant-aws` plugin. If it's the case that this is an issue with the plugin I'll open an issue there instead.

### Host operating system
Observed on both Ubuntu 18.04 and MacOS

### Guest operating system
Ubuntu 14.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|
    aws.ami = "ami-2f15061f"
    aws.aws_profile = ENV["AWS_PROFILE"]

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "~/.ssh/id_rsa"
  end
end
```

### Debug output
[https://gist.github.com/nickpwhite/98e13c65eb5f269db2e0c6e6d3f371b5](https://gist.github.com/nickpwhite/98e13c65eb5f269db2e0c6e6d3f371b5)

### Expected behavior
The machine should have been created in EC2.

### Actual behavior
There was an exception and the box was not created.

### Steps to reproduce
1. Install the vagrant-aws plugin `vagrant plugin install vagrant-aws`
2. Add the dummy box for vagrant-aws `vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box`
3. Using the provided Vagrantfile, bring up the machine `vagrant up --provider=aws`

**Comment by chrisroberts** [comment]
Hi there. Please see mitchellh/vagrant-aws#566 for more information. Cheers!
