### ISSUE TITLE
Vagrant fails to run AutoHotKey scripts

### ISSUE THREAD

**Issue by snowe2010** [hashicorp/vagrant#11383]
### Vagrant version
```
➜ vagrant -v
Vagrant 2.2.7
```

### Host operating system
macOS Mojave 10.14.6

### Guest operating system
Windows 2019 Server (https://github.com/StefanScherer/docker-windows-box)

### Vagrantfile

**Vagrantfile**

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # uses https://github.com/StefanScherer/docker-windows-box
  config.vm.box = "../../packer-windows/windows_2019_virtualbox.box"
  config.vm.communicator = "winrm"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", 128]
    v.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
  end

  config.vm.provision "shell", path: "test.ps1", privileged: false

end
```

**test.ps1**

```powershell
# install chocolatey
iex (wget 'https://chocolatey.org/install.ps1' -UseBasicParsing)
choco feature disable --name showDownloadProgress
choco install autohotkey -y
# run script
Invoke-Item "C:\vagrant\test.ahk"
```

**test.ahk**

```autohotkey
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

MsgBox, Test
```

### Debug output

`vagrant up --debug &> vagrant.log`
https://gist.github.com/snowe2010/3659589c1816f799bf3d3d06c0f48581

### Expected behavior
Script should run

### Actual behavior
Logoff message is shown, no script runs

[Here is a link to the StackOverflow post and a gif demonstrating the issue.](https://stackoverflow.com/questions/60156328/running-an-autohotkey-script-through-vagrant-provision-fails)
[![https://i.stack.imgur.com/KE7u2.gif](https://i.stack.imgur.com/KE7u2.gif)]()

### Steps to reproduce
1. `vagrant up`
2. verify there is no message box after provision
3. verify that the message box shows up by running the exact same autohotkey script from within a powershell window. `Invoke-Item "C:\vagrant\test.ahk"`

**Comment by chrisroberts** [comment]
Hi there. `Invoke-Item` will return immediately, which results in the provision script completing before the `Invoke-Item` finishes running. There are a variety of ways you can modify you script to force waiting before the provision script completes and logs out:

https://stackoverflow.com/questions/2700589/how-to-get-powershell-to-wait-for-invoke-item-completion

Cheers!

**Comment by snowe2010** [comment]
@chrisroberts In my SO post I detail that I had tried those things already. They do not work.

**Comment by chrisroberts** [comment]
@snowe2010 The stackoverflow post does not provide any indication that the methods described in the link I provided were attempted. The `Invoke-Item` commandlet does not provide the functionality to wait natively, so you'll need to use an approach like the one described in the link above.

**Comment by snowe2010** [comment]
>I've attempted with several different styles of execution (&, plain call to the script, referencing the AutoHotKey.exe and passing the ahk script as a parameter),

was supposed to indicate that. I didn't think I needed to list off all the ways I've done it since I've tried every single way available. 

If I modify the above ps1 to have all the ways I've tried (since none of them work), will you reopen the issue? Or would a video of all the ways provided (and other ways I've tried as well) be better?

**Comment by snowe2010** [comment]
Here is a new `test.ps1` with just about every possible way to start a process in the background while waiting. I didn't include all of them because, frankly I think it's kind of ridiculous that I have to prove I tested these methods, but anyway vagrant refuses to run the AHK script even if you wait for it to finish. It just never runs at all. 


```powershell# install chocolatey
# iex (wget 'https://chocolatey.org/install.ps1' -UseBasicParsing)
# choco feature disable --name showDownloadProgress
# choco install autohotkey -y


# run script

# Attempt 1
# function Invoke-Command() {
#     param ( [string]$program = $(throw "Please specify a program" ),
#             [string]$argumentString = "",
#             [switch]$waitForExit )

#     $psi = new-object "Diagnostics.ProcessStartInfo"
#     $psi.FileName = $program 
#     $psi.Arguments = $argumentString
#     $proc = [Diagnostics.Process]::Start($psi)
#     if ( $waitForExit ) {
#         $proc.WaitForExit();
#     }
# }

# Invoke-Command -program 'C:\Program Files\AutoHotkey\AutoHotkey.exe' -argumentString "C:\vagrant\test.ahk"

# Attempt 2
# Start-Process -Wait "C:\vagrant\test.ahk"

# Attempt 3
# Start-Process "C:\vagrant\test.ahk" | Out-Null

# Attempt 4
# Start-Process -FilePath "C:\Program Files\AutoHotkey\AutoHotkey.exe" -ArgumentList "C:\vagrant\test.ahk" -NoNewWindow -Wait

# Attempt 5
# "C:\vagrant\test.ahk" | Out-Null

# Attempt 6
# & "C:\vagrant\test.ahk" | Out-Null

# Attempt 7
# & C:\vagrant\test.ahk | Out-Null

# Attempt 8
# & "C:\Program Files\AutoHotkey\AutoHotkey.exe" C:\vagrant\test.ahk | Out-Null

# Attempt 9
# $proc = Start-Process "C:\vagrant\test.ahk" -NoNewWindow -PassThru
# $proc.WaitForExit()

# Attempt 10
# $job = Start-Job { "C:\vagrant\test.ahk" }
# Wait-Job $job
# Receive-Job $job

# Attempt 11
# & "C:\Program Files\AutoHotkey\AutoHotkey.exe" "C:\vagrant\test.ahk" | Out-Null

# Attempt 12
# $exitCode = [Diagnostics.Process]::Start("C:\Program Files\AutoHotkey\AutoHotkey.exe","C:\vagrant\test.ahk").WaitForExit(60000)

# Attempt 13
# cmd /c start /wait C:\vagrant\test.ahk

# Attempt 14
# $session = New-PSSession
# $Job = Invoke-Command -Session $session -FilePath "C:\vagrant\test.ahk" -AsJob
# Wait-Job -Job $Job

# Attempt 15
# $proc = Start-Process -FilePath "C:\Program Files\AutoHotkey\AutoHotkey.exe" -ArgumentList "C:\vagrant\test.ahk" -NoNewWindow -PassThru
# $proc.WaitForExit()
```

**Comment by briancain** [comment]
Hi @snowe2010 - The solution @chrisroberts mentioned works just fine for me. I wrote a quick script to open the calculator program. As you can see from the gif, it opens when I run the Vagrant provisioner and the method for running applications from the stackoverflow post:

![Peek 2020-02-10 13-44](https://user-images.githubusercontent.com/810277/74193168-be57d580-4c0b-11ea-9f53-1e16f102086a.gif)


```ruby
config.vm.define "windows-hyperv" do |windows|
    windows.vm.box = "StefanScherer/windows_10"

    windows.vm.provider :vmware_desktop do |v|
      v.gui = true
      v.memory = "15000"
      v.cpus = 4
      v.vmx['vhv.enable'] = 'TRUE'
      v.vmx['vhv.allow'] = 'TRUE'
      v.vmx["hypervisor.cpuid.0"] = "FALSE"
    end

    windows.vm.provision "TestFile", type: "file",
      source: "test.ahk",
      destination: "/Users/vagrant/test.ahk"

    windows.vm.provision "Test", type: :shell, inline:<<-SHELL
function Invoke-Command() {
    param ( [string]$program = $(throw "Please specify a program" ),
            [string]$argumentString = "",
            [switch]$waitForExit )

    $psi = new-object "Diagnostics.ProcessStartInfo"
    $psi.FileName = $program
    $psi.Arguments = $argumentString
    $proc = [Diagnostics.Process]::Start($psi)
    Write-Host "Hi"
    if ( $waitForExit ) {
        $proc.WaitForExit();
    }
    Write-Host "Bye"
}

Invoke-Command("C:/Users/Vagrant/test.ahk")
    SHELL
end
```

The AHK script:

```
run calc.exe
```

This is not a Vagrant issue. Vagrant is doing the right thing by invoking the powershell script defined. Sorry that you are having trouble with it! Powershell can sometimes be tricky to debug, so it's understandable that you thought there was something wrong with Vagrant. Hopefully the example I shared will help you get past your issue. Thanks!

**Comment by snowe2010** [comment]
@briancain, you're not running in Mac, you're not running in VirtualBox, you're not running with a script, but instead using inline, you're using a Windows 10 box rather than Windows Server 2019, you're using the published box instead of the one I provided (he recently made updates and only pushes on Tuesdays, so the new box will not be uploaded until tomorrow), you're not running with the test file located in the folder, but instead providing it with the vm.provision, you're literally not even tangentially doing what I have described as the issue. 

I don't know how you can say you've confirmed it works when I've provided data, gifs, etc, showing that it does not. Just because it works on your computer does not mean it works. Using _the exact script you've provided_ results in failures. 

```
	default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default:     + CategoryInfo          : OperationStopped: (:) [], ArgumentException
    default:     + FullyQualifiedErrorId : System.ArgumentException
    default: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
    default: At line:74 char:1
    default: + $registered_task = $folder.GetTask("\$task_name")
    default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default:     + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
    default:     + FullyQualifiedErrorId : System.IO.FileNotFoundException
    default: You cannot call a method on a null-valued expression.
    default: At line:75 char:1
    default: + $registered_task.Run($null) | Out-Null
    default: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    default:     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    default:     + FullyQualifiedErrorId : InvokeMethodOnNull
```

I added this line `puts "command : #{command}"` to the [`handle_output` function](https://github.com/hashicorp/vagrant/blob/master/plugins/communicators/winrm/shell.rb#L143) in order to figure out what command vagrant was sending to trigger the powershell script. I saw that it was `powershell -ExecutionPolicy Bypass -OutputFormat Text -file "c:\tmp\vagrant-shell.ps1"` so I simply go into the guest and run that command and it works fine. If instead of using `run calc.exe` you use `MsgBox, Test` you can see that `Invoke-Command` _doesn't_ actually wait until the script is done, as the MsgBox is still on screen. If you instead use `Start-Process` you can see in my gif that it _does_ wait for the MsgBox to be closed, but that vagrant still fails to start the AHK script. 

# Invoke-Command gif
![2020-02-10 16-35-08 2020-02-10 16_38_40](https://user-images.githubusercontent.com/1534535/74200670-ca9c5c80-4c24-11ea-9939-023e5b36659a.gif)

# Start-Process gif
![2020-02-10 16-40-43 2020-02-10 16_44_14](https://user-images.githubusercontent.com/1534535/74200689-d4be5b00-4c24-11ea-84f6-467f8603710e.gif)



Note that that exception _only happens_ when I run the script as inline. Even if my script is as simple as `echo 'hi'`, if it's inline it throws the above exception.
