### ISSUE TITLE
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

### ISSUE THREAD

**Issue by Quix0r** [hashicorp/vagrant#11380]
### Vagrant version
2.2.6

### Host operating system
```
$ cat /proc/version
Linux version 4.16.0-2-amd64 (debian-kernel@lists.debian.org) (gcc version 7.3.0 (Debian 7.3.0-23)) #1 SMP Debian 4.16.16-2 (2018-06-22)
```

### Guest operating system
ubuntu/trusty64' version '20190514.0.0'

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
   config.vm.box = "ubuntu/trusty64"
   
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
   end
   
   config.vm.provision "shell", path: "provision.sh"
   config.vm.network :forwarded_port, guest: 3700, host: 13700   # IIOP ORB
   config.vm.network :forwarded_port, guest: 3820, host: 13820   # IIOP SSL
   config.vm.network :forwarded_port, guest: 3920, host: 13920   # IIOP SSL mutual auth
   config.vm.network :forwarded_port, guest: 4848, host: 14848   # Admin listener
   config.vm.network :forwarded_port, guest: 5900, host: 15900   # Hazelcast
   config.vm.network :forwarded_port, guest: 7676, host: 17676   # JMS
   config.vm.network :forwarded_port, guest: 8080, host: 18080   # HTTP
   config.vm.network :forwarded_port, guest: 8181, host: 18181   # HTTPS
   config.vm.network :forwarded_port, guest: 8686, host: 18686   # JMX
   config.vm.network :forwarded_port, guest: 9009, host: 19009   # JVM debug

end
```

### Debug output
````
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' version '20190514.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 3700 (guest) => 13700 (host) (adapter 1)
    default: 3820 (guest) => 13820 (host) (adapter 1)
    default: 3920 (guest) => 13920 (host) (adapter 1)
    default: 4848 (guest) => 14848 (host) (adapter 1)
    default: 5900 (guest) => 15900 (host) (adapter 1)
    default: 7676 (guest) => 17676 (host) (adapter 1)
    default: 8080 (guest) => 18080 (host) (adapter 1)
    default: 8181 (guest) => 18181 (host) (adapter 1)
    default: 8686 (guest) => 18686 (host) (adapter 1)
    default: 9009 (guest) => 19009 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "4ec25a51-a29c-48e8-877e-5728dd8a44e6", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'payara-vagrant_default_1581026728058_30516' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
````

### Expected behavior
The VM should start up (initial setup phase seems to be completed).

### Actual behavior
The above shown crash happened.

### Steps to reproduce
1. `$ git clone git@github.com:Quix0r/payara-vagrant.git`
2. `$ cd payara-vagrant`
3. `$ vagrant up`

### References
- #10412

**Comment by Quix0r** [comment]
Yes, I'm referencing my modified (read: upgraded) fork because the original one is referencing out-dating and already deleted @Paraya versions.

**Comment by briancain** [comment]
Hey there @Quix0r - As mentioned previously in https://github.com/hashicorp/vagrant/issues/10412#issuecomment-583559636, please refer to this issue to resolve your problem: https://github.com/hashicorp/vagrant/issues/8687#issuecomment-308813850

As mentioned on that issue, this is generally a failure to allocate resources on your machine. You can look at the VirtualBox logs to see what might be going wrong. These logs should tell you explicitly what went wrong when VirtualBox tried to boot your vm. There are also other potential fixes like reloading kernel modules for VirtualBox which you might have to do to resolve your problem. But these are all issues with VirtualBox, and not Vagrant. Hopefully that solves your issue, thanks!

**Comment by Quix0r** [comment]
Where are they located? No output hints it.

**Comment by Quix0r** [comment]
I already have updated my kernel modules to matching version:
````
$ ls -l /usr/src/vboxhost-6.1.2
lrwxrwxrwx 1 root root 32 Jan 13 12:42 /usr/src/vboxhost-6.1.2 -> ../share/virtualbox/src/vboxhost
$
````

**Comment by briancain** [comment]
@Quix0r  https://www.virtualbox.org/manual/ch12.html#collect-debug-info

> Every time Oracle VM VirtualBox starts up a VM, a so-called release log file is created, containing lots of information about the VM configuration and runtime events. The log file is called VBox.log and resides in the VM log file folder, which is $HOME/VirtualBox VMs/VM-name/Logs by default

**Comment by Quix0r** [comment]
Ah, okay. :-( The there linked website says this:

> Welcome to Oracle Blogs.
> The content that you're looking is no longer on this page.
> Try visiting our Blog Directory to find what you're looking for.
> Thank you.

**Comment by Quix0r** [comment]
Sorry but, no such directory exist:
````
quix0r@daedalus:~/VirtualBox VMs$ ls -l 
total 4
drwx------ 2 quix0r quix0r 4096 Feb  7 20:04 payara-vagrant_default_1581026728058_30516
quix0r@daedalus:~/VirtualBox VMs$ ls -l payara-vagrant_default_1581026728058_30516/
total 1542716
-rw------- 1 quix0r quix0r 1584726016 Feb  6 23:03 box-disk1.vmdk
-rw------- 1 quix0r quix0r       3823 Feb  7 20:04 payara-vagrant_default_1581026728058_30516.vbox
-rw------- 1 quix0r quix0r       3823 Feb  7 20:04 payara-vagrant_default_1581026728058_30516.vbox-prev
quix0r@daedalus:~/VirtualBox VMs$
````

**Comment by Quix0r** [comment]
So even @Oracle don't know their own application.

**Comment by briancain** [comment]
@Quix0r - Have you tried bringing up a vm using the VirtualBox GUI? Or reinstalling VirtualBox and rebuilding your kernel modules? Purging your current installation and installing a previous version of VirtualBox?

**Comment by Quix0r** [comment]
No, the payara box is only started up through vagrant only. I know the GUI will mess up the box' files and configuration. And as you can see, no other box is around? I have upgraded virtualbox from a older version. So if upgrading fails this way, it is not really nice. This needs fixing.

**Comment by briancain** [comment]
@Quix0r - Please try bringing up a machine in virtualbox outside of Vagrant. It doesn't have to be that specific Vagrant box. As I've been trying to mention here, this is a virtualbox error, not a vagrant error. The error from VirtualBox is telling you that VirtualBox had a problem bringing up a VM. Maybe try bringing up a vm and see what happens? It might give you a clue as to why Vagrant could not bring up a VM. The comment I had linked you to earlier says that this error is most often caused by your host machine not having enough resources. Bringing up a different VM in the GUI might actually show you an error message that's more useful than the vboxmanage error message from the command line.

I'm just trying to give you some additional tools to debug why VirtualBox is failing for you. I'm sorry that you just upgraded, but if the latest version is failing for you, the solution would be to downgrade to a working version of VirtualBox. But again, this is a VirtualBox issue, and not a Vagrant one.

**Comment by Quix0r** [comment]
Looks like it the used `payara-vagrant` works. At work (Windows 10) it launches. I can check what I can do.
