### ISSUE TITLE
Name `[name]` of domain about to create is already taken.

### ISSUE THREAD

**Issue by Ricky-Tigg** [hashicorp/vagrant#11389]
Vagrant 2.2.6; vagrant-libvirt 0.0.45; OS Fedora

Command `vagrant up` produces "`Waiting for domain to get an IP Address...`". As an attempt to avoid the production of this message, i used `destroy` option then removed from _Libvirt|Virtual Manager_ the machine still present and kept the downloaded image file. I removed manually from local home directory Vagrant folders , thus the hidden one as well, then started a new project.
```
$ vagrant box list
There are no installed boxes! Use `vagrant box add` to add some.
$ vagrant global-status
id       name   provider state  directory                           
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or, you haven't destroyed and recreated Vagrant environments that were started with an older version of Vagrant.
```
### Steps to reproduce
```
$ vagrant init generic/fedora31
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
Name `fedora_default` of domain about to create is already taken. Please try to run `vagrant up` command again.
```
Renewing that operation has no beneficial effect. `VAGRANT_LOG=debug vagrant up 2>vagrant_up.txt`: [vagrant_up.txt](https://github.com/hashicorp/vagrant/files/4190777/vagrant_up.txt)

**Comment by chrisroberts** [comment]
Hi there,

The libvirt provider is a third party vagrant plugin. You can report the error on their github repository here: https://github.com/vagrant-libvirt/vagrant-libvirt

Cheers!
