### ISSUE TITLE
Installing Vagrant 2.2.7 doesn't overwrite 2.1.4 version installed

### ISSUE THREAD

**Issue by iiRobin** [hashicorp/vagrant#11387]
### Vagrant version
Vagrant 2.1.4

### Host operating system
Windows 10 Home

### Debug output
https://gist.github.com/iiRobin/880fd6bebf2ab42a10523af9dac3b6db

### Expected behavior
After installing the lastest version 'vagrant version' should show me the latest version of Vagrant is installed.

### Actual behavior
'vagrant version' is still showing my last version, which was 2.1.4, even after I installed the latest version 2.2.7

**Comment by chrisroberts** [comment]
Hi there,

It appears that you have installed Vagrant in the past using a non-official installer. This can be seen in the debug log when Vagrant outputs the executable being called:

```
> INFO global: VAGRANT_EXECUTABLE="C:\\Users\\Robin\\embedded\\gems\\2.1.4\\gems\\vagrant-2.1.4\\bin\\vagrant"
```

Removing this previous installation will fix the issue and the latest version you have installed (using the official installer) will show up.

Cheers!
