### ISSUE TITLE
No IP address assigned to the guest

### ISSUE THREAD

**Issue by Ricky-Tigg** [hashicorp/vagrant#11395]
- OS: Fedora;
- libvirt.x86_64 5.6.0-5.fc31;
- vagrant version: 2.2.6;
- vagrant-libvirt (0.0.45, system);
- Vagrantfile:
Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora31"
end
- Using distros packages

### Actual behavior
No IPv4 address assigned to the guest.

### Steps to reproduce
```
$ vagrant init generic/fedora31
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
[...]
==> default: Waiting for domain to get an IP address...
^Z
[1]+  Stopped                 vagrant up
$ vagrant halt
An action 'halt' was attempted on the machine 'default',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.
$ vagrant halt
[1]+  Killed                  vagrant up
$ vagrant --debug up
[...]
==> default: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
```
- Tested as well with following addition to Vagrantfile; no beneficial effect:

   'config.vm.provider "libvirt" do |lv|
      lv.cpu_mode = 'host-passthrough'
  end'

- At the same time, guest is reported by **QEMU-KVM** as running under **Libvirt URI** qemu:///session, it is there unexpectedly named _fedora_default_, instead of _default_ assigned by Vagrant.

![URI_user-session_fedora_default](https://user-images.githubusercontent.com/26058215/74530062-da23ea00-4f31-11ea-8b69-823ecf8f3158.png)

**Comment by jbonhag** [comment]
Hi there,

This is an issue with vagrant-libvirt, which is a third-party Vagrant plugin. It looks as though this issue has been reported here: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/841

Cheers!
