### ISSUE TITLE
Vagrant fails to run executables that result in GUI on Mac host with VirtualBox provider

### ISSUE THREAD

**Issue by snowe2010** [hashicorp/vagrant#11392]
### Vagrant version

```
➜ vagrant -v
Vagrant 2.2.7
```

### Host operating system

# `macOS Mojave 10.14.6`

### Guest operating system

```ruby
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.box_version = "2020.02.12"
```

### Vagrantfile

https://github.com/snowe2010/vagrantbug

Last time I provided the Vagrantfile here I was immediately told it wasn't a bug with Vagrant. 

I have created a repo that duplicates the exact issue on a **brand new Mac install**, with no software installed except VirtualBox 6.1 and Vagrant 2.2.7. 
I also tested on VirtualBox 6.0 to verify that it wasn't an issue with VB.

### Debug output

https://gist.github.com/snowe2010/cf57ecdddbc8a1c47a51402bdf0a8e05
https://github.com/snowe2010/vagrantbug/blob/master/vagrant.log

### Expected behavior

Calculator GUI should pop up on screen like [this gif demonstrates in a Linux Host](https://user-images.githubusercontent.com/810277/74193168-be57d580-4c0b-11ea-9f53-1e16f102086a.gif)

### Actual behavior

Vagrant gets stuck trying to run `calc.exe`.

### Steps to reproduce

1. `git clone git@github.com:snowe2010/vagrantbug.git` or `git clone https://github.com/snowe2010/vagrantbug.git`
2. `vagrant up`
3. verify there is no message box after provision
4. verify that vagrant is stuck trying to run this script since it never ends and never actually runs. 

### Comments

As already pointed out in #11383, this does not happen on Linux hosts or in VMWare. **This is reproducible _every time_ on a MacBook Pro 15in on macOS Mojave 10.14.6 using VirtualBox 6.0 and 6.1.** It was a wiped computer, so I freshly installed macOS Mojave on it. I then installed Vagrant and VirtualBox, using the installers from their websites. I then reproduced the exact issue using the `StefanScherer/windows_2019` box on the _latest version_ **2020.02.12**.

**Comment by chrisroberts** [comment]
Hi there,

The issue you are encountering is due to the usage of Windows Server and not Windows 10. This requires using some different configuration options to properly interact with the logged in session. The `privileged` option and `powershell_elevated_interactive` both need to be enabled on the shell provisioner. Additionally, the username used by winrm needs to be updated to `vagrant\vagrant` (or what ever the WORKGROUP name is) for the task to be properly setup.

Your Vagrantfile should end up looking like:

```ruby
Vagrant.configure("2") do |config|
  config.vm.communicator = "winrm"
  config.vm.box = "StefanScherer/windows_2019"
  config.vm.box_version = "2020.02.12"

  config.winrm.username = 'vagrant\vagrant'

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", 128]
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
  end

  config.vm.provision "RunCalcExe", type: "shell", path: "run.ps1", privileged: true, powershell_elevated_interactive: true
end
```

Cheers!

**Comment by snowe2010** [comment]
Thank you for the help! That worked. Should documentation be added to the `powershell_elevated_interactive` docs mentioning that GUIs will not be able to work through vagrant without it? I spent about 4 full days searching for answers to this question, and none of the docs mention any sort of thing about that.
