### ISSUE TITLE
New versioning scheme - Salt 3000

### ISSUE THREAD

**Issue by max-arnold** [hashicorp/vagrant#11394]
SaltStack has changed its versioning scheme from date-based (e.g., 2019.2.3) to 3000, 3001 , etc for major versions and 3000.1, 3000.2, etc for minior ones (see the [SEP 14](https://github.com/saltstack/salt-enhancement-proposals/blob/master/accepted/0014-dev-overhaul.md) for details).

The powershell bootstrap script in Salt provisioner doesn't support this scheme:

https://github.com/hashicorp/vagrant/blob/master/plugins/provisioners/salt/bootstrap-salt.ps1#L13-L21

This is going to be fixed upstream:

* Issue: https://github.com/saltstack/salt-bootstrap/issues/1394
* Fix: https://github.com/saltstack/salt-bootstrap/pull/1430

Vagrant needs to update the bundled bootstrap script, or maybe just always fetch the upstream one (as it does with `bootstrap-salt.sh`)

P.S. The upstream linux bootstrap script also can't install Salt 3000 and a fix is also in the works: https://github.com/saltstack/salt-bootstrap/issues/1429

**Comment by jbonhag** [comment]
Hi @max-arnold -- thanks for letting us know!

**Comment by dafyddj** [comment]
> Vagrant needs to update the bundled bootstrap script, or maybe just **always fetch the upstream one** (as it does with `bootstrap-salt.sh`)

This!

**Comment by s0undt3ch** [comment]
FYI, the latest stable version for Linux/macOS can be fetched from https://bootstrap.saltstack.com/
The latest stable version for windows can be fetched from https://winbootstrap.saltstack.com/

More info [here](https://github.com/saltstack/salt-bootstrap/issues/1404#issuecomment-586042121)

**Comment by max-arnold** [comment]
Update: the bundled Windows Salt bootstrap script also fails on default version (2018.3.3) because it is 404 now (it was archived because of critical CVEs).

**Comment by max-arnold** [comment]
Could someone review this fixed Windows minion bootstrap script for Salt provisioner in Vagrant (before I submit a PR)? To try it, place it alongside with your Vagrantfile and specify salt.bootstrap_script = "./bootstrap-salt.ps1".

```powershell
# Powershell supports only TLS 1.0 by default. Add support for TLS 1.2
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]'Tls12'

# Download the upstream bootstrap script
(New-Object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.ps1', 'upstream-bootstrap.ps1')

# Run the upstream bootstrap script with passthrough arguments
./upstream-bootstrap.ps1 @arg
```

**Comment by max-arnold** [comment]
@jbonhag or @soapy1 

This issue is fixed in https://github.com/hashicorp/vagrant/pull/12127, plus there are a couple of related changes in https://github.com/hashicorp/vagrant/pull/12135

Both PRs were reviewed by Salt core developers and are waiting to be merged. Is there anything I can do to speed up the approval/merge?
