### ISSUE TITLE
Problem to show real ip client in flask on vagrant VM

### ISSUE THREAD

**Issue by BlackRouter** [hashicorp/vagrant#11399]
# Vagrant version
vagrant 2.2.7

### Host operating system
Centos 7

### Guest operating system
ubuntu 19.10 eoan

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/eoan64"
  #config.disksize.size = '50GB'
  config.vm.hostname = "Moein"
  config.vm.network "public_network"
  #config.vm.network "public_network", :adapter=>1 , type: "dhcp", :bridge => 'eno1'
  

  # Port
  config.vm.network :forwarded_port, guest: 22, host: 2222, host_ip: "0.0.0.0", id: "ssh", auto_correct: true
  #config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 7273, host: 7273
  config.vm.network :forwarded_port, guest: 444, host: 444
  config.vm.box_download_insecure = true
  
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end
end
```

### Expected behavior
https://stackoverflow.com/questions/60133862/how-to-show-real-ip-client-in-flask-on-vagrant-vm/60236440#60236440

**Comment by jbonhag** [comment]
Hi there,

You should have two network interfaces and two IP addresses visible in `ifconfig` (besides the loopback device):
- The NAT device
- The bridged device

If your Flask app is set up to listen on all interfaces, you will get a different result depending how you connect to it.

```
vagrant@Moein:~$ curl http://localhost:5000/ip
{"ip":"127.0.0.1"}
vagrant@Moein:~$ curl http://192.168.1.210:5000/ip
{"ip":"192.168.1.210"}
vagrant@Moein:~$ curl http://10.0.2.15:5000/ip
{"ip":"10.0.2.15"}
```

Are you connecting to the Flask app from the CentOS 7 host or from inside the VM? If you're connecting to it from the host, you will only be able to connect to it through the bridged adapter unless you have a specific port forwarding rule for the Flask app.

**Comment by BlackRouter** [comment]
> Hi there,
> 
> You should have two network interfaces and two IP addresses visible in `ifconfig` (besides the loopback device):
> 
> * The NAT device
> * The bridged device
> 
> If your Flask app is set up to listen on all interfaces, you will get a different result depending how you connect to it.
> 
> ```
> vagrant@Moein:~$ curl http://localhost:5000/ip
> {"ip":"127.0.0.1"}
> vagrant@Moein:~$ curl http://192.168.1.210:5000/ip
> {"ip":"192.168.1.210"}
> vagrant@Moein:~$ curl http://10.0.2.15:5000/ip
> {"ip":"10.0.2.15"}
> ```
> 
> Are you connecting to the Flask app from the CentOS 7 host or from inside the VM? If you're connecting to it from the host, you will only be able to connect to it through the bridged adapter unless you have a specific port forwarding rule for the Flask app.

yes i run flask on server centos 7 host show real ip but in VM just show 10.0.2.2

**Comment by jbonhag** [comment]
Hi @BlackRouter,

Thanks for the additional information -- sorry I misunderstood!

Since you're running the app on the server, the default route from the VM is going to use the VirtualBox NAT gateway, which will have same IP address as the host. If you run `ip route` on the VM you will be able to see which interface the request is going through.

If you'd like to send traffic to the host through the public network, you can use the following configuration:

```
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
```

This will show, for example:
```
vagrant@Moein:~$ curl http://192.168.1.202:5000/ip
{"ip":"192.168.1.214"}
```

Depending on your needs, you can also [override the default router configuration](https://www.vagrantup.com/docs/networking/public_network.html#default-router). However this can be fairly complex and will be operating-system specific.

I hope this gets you on the right track!

Cheers 😄
