### ISSUE TITLE
Error: Configuring the VM...

### ISSUE THREAD

**Issue by RockAfeller2013** [hashicorp/vagrant#11409]
Windows 2012 R2 with Hypver 

### Vagrant version
Vagrant 2.2.7

### Host operating system
Windows 2012 R2 Hyper-V latest updates

### Guest operating system
This is the operating system you run in the virtual machine.
Windows 2012 R2
### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive 
This is just the default..

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
VM should be installed on Hyper-V

### Actual behavior
    default:
    default: 1) External
    default: 2) Internal
    default:
    default: What switch would you like to use? 1
    default: Configuring the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: configure_vm.ps1
Error:

CheckpointType is not available. Cannot enable checkpoints.


Steps to reproduce
1. vagrant init hashicorp/bionic64
2. vagrant up --provider=hyperv
3. What switch would you like to use? 1

### References

**Comment by RockAfeller2013** [comment]
here is the Debug output


 INFO interface: error: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: configure_vm.ps1
Error:

Failed to configure virtualization extensions: ExposeVirtualizationExtensions is not available

An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: configure_vm.ps1
Error:

Failed to configure virtualization extensions: ExposeVirtualizationExtensions is not available


 INFO interface: Machine: error-exit ["VagrantPlugins::HyperV::Errors::PowerShellError", "An error occurred while 
executing a PowerShell script. This error\nis shown below. Please read the error message and see if this is\na 
configuration error with your system. If it is not, then please\nreport a bug.\n\nScript: 
configure_vm.ps1\nError:\n\nFailed to configure virtualization extensions: ExposeVirtualizationExtensions is not 
available"]

**Comment by RockAfeller2013** [comment]
Here is a solution, but its old, https://github.com/hashicorp/vagrant/issues/10132

**Comment by RockAfeller2013** [comment]
Os it seems like vagrant is not compatible with Windows 2012 R2 Hyper as Vagrant requires Nested Virtualization and thats only available in Windows Server 2016 and above as per article - Set-VMProcessor -VMName precise64 -ExposeVirtualizationExtensions $true

**Comment by RockAfeller2013** [comment]
Is there a work around

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! You can set the `enable_checkpoints` provider option to `false` in your Vagrantfile and that will fix the issue. For example:

```
  config.vm.provider "hyperv" do |h|
    h.enable_checkpoints = false
  end
```

This is needed because the Hyper-V module for Windows Server 2012 R2 doesn't have the `CheckpointType` parameter for configuring a VM.

Cheers and have a great day! 😄
