### ISSUE TITLE
Question: Rootless vagrant on libvirt?

### ISSUE THREAD

**Issue by Kreyren** [hashicorp/vagrant#11408]
Disclaimer: I was unable to find the answer in documentation and so i am submitting an issue.

I'm working on contribution to fix https://github.com/gitpod-io/gitpod/issues/1251 which expects rootless vagrant running inside of a docker environment using libvirt since virtualbox has ongoing vulnerability https://www.cybersecurity-help.cz/vdb/SB2018110701?affChecked=1 that prevents deploy for production.

Using this dockerfile (ignore the notice it is invalid):
https://github.com/Kreyren/gitpod-tests1/blob/d3c7179618c720e7f76142891eeaf72a75516786/gitpod/gitpod.Dockerfile

where running `vagrant up --provider=libvirt` results in:
```
gitpod@hostname:/workspace/gitpod-tests1$ vagrant up --provider=libvirt
Bringing machine 'default' up with 'libvirt' provider...
Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/gitpod/.ssh/id_rsa:
Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
```

That should be provided in package `vagrant-libvirt` on debian.

I assume this being problem with configuration to run rootless libvirt where i don't know how this should be configured properly.

**Comment by briancain** [comment]
Hey there @Kreyren - Thanks for opening an issue with Vagrant! Generally, Vagrant should never be run as root. Sometimes Vagrant may ask for privilege escalation if it needs to edit sensitive files on disk (like writing to `/etc/exports` for nfs shared folders), but that being said, libvirt is not an officially supported provider and isn't maintained in this repository. The project page is located at https://github.com/vagrant-libvirt/vagrant-libvirt. Please open an issue with them instead, thanks!

**Comment by Kreyren** [comment]
@briancain will do, thanks for quick answer.
