### ISSUE TITLE
`read_dhcp_servers` function is not compatible with Virtualbox 6.1

### ISSUE THREAD

**Issue by mathiasaerts** [hashicorp/vagrant#11403]
We've been encountering similar issues as in #3083 and we've traced the DHCP server creation in the Vagrant codebase. It seems that the `read_dhcp_servers` function parses the output of `VBoxManage list dhcpservers` which has changed between VirtualBox 6.0 and 6.1.

**VirtualBox 6.0 output:**
```
NetworkName:    HostInterfaceNetworking-vboxnet0
IP:             172.28.128.2
NetworkMask:    255.255.255.0
lowerIPAddress: 172.28.128.3
upperIPAddress: 172.28.128.254
Enabled:        Yes
Global options:
   1:255.255.255.0

```

**VirtualBox 6.1 output:**
```
NetworkName:    HostInterfaceNetworking-vboxnet0
Dhcpd IP:       172.28.128.2
LowerIPAddress: 172.28.128.3
UpperIPAddress: 172.28.128.254
NetworkMask:    255.255.255.0
Enabled:        Yes
Global Configuration:
    minLeaseTime:     default
    defaultLeaseTime: default
    maxLeaseTime:     default
    Forced options:   None
    Suppressed opts.: None
        1/legacy: 255.255.255.0
Groups:               None
Individual Configs:   None

```

It is obvious that the output is different and this line for example will not match the new output from VirtualBox 6.1: https://github.com/hashicorp/vagrant/blob/ac268e26382c17057a20cd24fb1dccd59cc0d9e2/plugins/providers/virtualbox/driver/version_5_0.rb#L441

### Vagrant version
```
$ vagrant --version
Vagrant 2.2.7
```

### Host operating system
```
Description:	Manjaro Linux
Release:	18.1.5
Codename:	Juhraya
```
But this also occurs on Ubuntu 18.04 and Windows 10 with the same version of Vagrant and VirtualBox 6.1

### Guest operating system
Ubuntu 16.04 (although this seems irrelevant) 

### Vagrantfile
It appears to affect any Vagrantfile that uses DHCP and not a fixed IP address.
```ruby
Vagrant.configure("2") do |config|
...
  config.vm.network "private_network", type: "dhcp"
...
end
```

### Debug output
https://gist.github.com/mathiasaerts/404bf35332ffe57f6706bc5f3b3ae145

### Expected behavior
Vagrant should not try to create a new DHCP server when one already exists, or properly increment the counter in the dhcpserver name.

### Actual behavior
Vagrant fails to start the VirtualBox VM with the following error:
```
A host only network interface you're attempting to configure via DHCP
already has a conflicting host only adapter with DHCP enabled. The
DHCP on this adapter is incompatible with the DHCP settings. Two
host only network interfaces are not allowed to overlap, and each
host only network interface can have only one DHCP server. Please
reconfigure your host only network or remove the virtual machine
using the other host only network.
```

### Steps to reproduce
1. Ensure you're using VirtualBox 6.1 and Vagrant 2.2.7
2. Create a Vagrantfile with the configuration mentioned above
3. Run `vagrant up`
4. Run `vagrant halt`
5. Run `vagrant up` again and the error above will be displayed.

### References
- #3083 seems to report the same issue, other people have commented there as well after upgrading to a new VirtualBox version.

**Comment by jbonhag** [comment]
Hi @mathiasaerts -- thank you so much for bringing this to our attention and including a detailed bug report. I've just merged a fix into master that should properly detect the dhcp servers settings on VirtualBox 6.1.

Cheers and have a great day! 😄

**Comment by mathiasaerts** [comment]
Awesome! Thanks for picking this up so quickly. Looking forward to the next release 😉
