### ISSUE TITLE
all vagrant command throw error with stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by stevenruizhang** [hashicorp/vagrant#11401]
### Vagrant version
Vagrant 2.2.7

### Host operating system
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
no

### Debug output
```
/opt/vagrant/embedded/lib/ruby/2.4.0/monitor.rb:198:in `mon_exit': stack level too deep (SystemStackError)
        from /opt/vagrant/embedded/lib/ruby/2.4.0/monitor.rb:216:in `ensure in mon_synchronize'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/monitor.rb:216:in `mon_synchronize'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/repository.rb:75:in `find_ancestor'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/logger.rb:62:in `deal_with_inheritance'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/logger.rb:36:in `initialize'
        from /home/steven_rui_zhang/.vagrant.d/gems/2.4.9/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:12:in `new'
        from /home/steven_rui_zhang/.vagrant.d/gems/2.4.9/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:12:in `initialize'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:122:in `new'
         ... 10180 levels...
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `run'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:525:in `hook'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:774:in `unload'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:185:in `<main>'
```

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1. install the vagrant
2.all vagrant command throw error with stack level too deep (SystemStackError)

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
#9595
export VAGRANT_DISABLE_RESOLV_REPLACE=1  not solved the issue for me too, thanks for the workaround

**Comment by jbonhag** [comment]
Hi there,

Thank you for opening an issue. It looks like you're using the `vagrant-triggers` plugin. Triggers were added to core Vagrant in version 2.1.0, and the core triggers don't work the same as they do in the plugin. It might be the case that an incompatible trigger definition is causing the overflow.

However, there is not enough information here to reproduce or provide a recommendation. Please attach a Vagrantfile as well as a full debug log (`vagrant up --debug`) and we will be able to assist you further.

Thank you! 😄

**Comment by stevenruizhang** [comment]
@jbonhag 
1) vagrantfile : https://raw.githubusercontent.com/udemy-course/Kubernetes-CN/master/section2/vagrant-coreos/Vagrantfile

2) vagrant up --debug
.........
ERROR warden: Error occurred: stack level too deep
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: stack level too deep
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: stack level too deep
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: stack level too deep
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: stack level too deep
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: stack level too deep
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
/opt/vagrant/embedded/lib/ruby/2.4.0/monitor.rb:186:in `mon_enter': stack level too deep (SystemStackError)
        from /opt/vagrant/embedded/lib/ruby/2.4.0/monitor.rb:212:in `mon_synchronize'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/repository.rb:75:in `find_ancestor'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/logger.rb:62:in `deal_with_inheritance'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/logger.rb:36:in `initialize'
        from /home/steven_rui_zhang/.vagrant.d/gems/2.4.9/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:12:in `new'
        from /home/steven_rui_zhang/.vagrant.d/gems/2.4.9/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:12:in `initialize'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:122:in `new'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:122:in `finalize_action'
         ... 10180 levels...
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:525:in `hook'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:774:in `unload'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:185:in `ensure in <main>'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:185:in `<main>'

**Comment by baoctac** [comment]
I, too, am running into the same error. Any help is appreciated. thanks.

Vagrant version: 2.2.7
Host OS: Mac
Guest OS: Ubuntu
Vagrantfile:
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  #config.vm.provision "shell", inline: <<-SHELL
  #SHELL
end

[debug.txt](https://github.com/hashicorp/vagrant/files/4243209/debug.txt)

**Comment by emancypage** [comment]
Similar problem here. I downgrade vagrant version to 2.2.6 and it seems works correctly. Maybe it will be some temporary workaround

**Comment by baoctac** [comment]
Thanks. got things working again with the downgrade.

**Comment by barbourkd** [comment]
Experiencing a similar issue on a macOS host after upgrading to 2.2.7 yesterday. Any command I run (`vagrant up`, `vagrant help`, `vagrant status`, etc) gives the following:

```
/opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:76:in `module_eval': stack level too deep (SystemStackError)
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:76:in `set_log'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:39:in `block in toggle_methods'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:35:in `each'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:35:in `toggle_methods'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/loggerfactory.rb:19:in `define_methods'
        from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/logger.rb:37:in `initialize'
        from /Users/kbarbour/.vagrant.d/gems/2.4.9/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:12:in `new'
        from /Users/kbarbour/.vagrant.d/gems/2.4.9/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:12:in `initialize'
         ... 9246 levels...
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:983:in `process_configured_plugins'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:178:in `initialize'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:145:in `new'
        from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:145:in `<main>'
```

Downgraded to 2.2.6 and things are working again for me as well.
