### ISSUE TITLE
getting The Hyper-V Virtual Machine Management Service (VMMS) is not running. when running vagrant up

### ISSUE THREAD

**Issue by jayaprakashkaluva** [hashicorp/vagrant#11406]
### Vagrant version
2.2.7
### Host operating system
Windows 10 pro

### Guest operating system
ubuntu(hashicorp/bionic64")

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
end

### Debug output
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: before_after_trigger_action #<Vagrant::Action::Builder:0x000000000356acb8>
 INFO environment: Running hook: after_after_trigger_action
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: after_after_trigger_action #<Vagrant::Action::Builder:0x0000000004c067d8>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::AfterTriggerAction:0x0000000004e69638>
 INFO environment: Running hook: after_is_state
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: after_is_state #<Vagrant::Action::Builder:0x0000000004b53318>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::IsState:0x0000000004ff7ae0>
 INFO environment: Running hook: after_before_trigger_action
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: after_before_trigger_action #<Vagrant::Action::Builder:0x0000000004a63908>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x0000000004ff4138>
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Warden:0x00000000048e9e10>
 INFO warden: Calling IN action: #<Proc:0x0000000003761dc8@C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:129 (lambda)>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::BeforeTriggerAction:0x00000000048e9c58>
 INFO environment: Running hook: before_before_trigger_action
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: before_before_trigger_action #<Vagrant::Action::Builder:0x0000000003235cc8>
 INFO warden: Calling IN action: #<VagrantPlugins::HyperV::Action::Import:0x00000000048e9c08>
 INFO environment: Running hook: before_import
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: before_import #<Vagrant::Action::Builder:0x000000000267b748>
 INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "$env:PSModulePath=$env:PSModulePath+';C:\\HashiCorp\\Vagrant\\embedded\\gems\\2.2.7\\gems\\vagrant-2.2.7\\plugins\\providers\\hyperv\\scripts\\utils'; &('C:\\HashiCorp\\Vagrant\\embedded\\gems\\2.2.7\\gems\\vagrant-2.2.7\\plugins\\providers\\hyperv\\scripts\\has_vmcx_support.ps1')", "-ErrorAction", "Stop"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: ===Begin-Output===
{
    "result":  true
}
===End-Output===
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
 INFO import: Found box configuration path: C:/Users/jayap/.vagrant.d/boxes/hashicorp-VAGRANTSLASH-bionic64/1.0.282/hyperv/Virtual Machines/47420631-D5E2-4041-9698-C7E0C2633931.vmcx
 INFO import: Found box image path: C:/Users/jayap/.vagrant.d/boxes/hashicorp-VAGRANTSLASH-bionic64/1.0.282/hyperv/Virtual Hard Disks/ubuntu-18.04-amd64.vhdx
 INFO interface: output: Importing a Hyper-V instance
 INFO interface: output: ==> default: Importing a Hyper-V instance
==> default: Importing a Hyper-V instance
 INFO interface: detail: Creating and registering the VM...
 INFO interface: detail:     default: Creating and registering the VM...
    default: Creating and registering the VM...
 INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "$env:PSModulePath=$env:PSModulePath+';C:\\HashiCorp\\Vagrant\\embedded\\gems\\2.2.7\\gems\\vagrant-2.2.7\\plugins\\providers\\hyperv\\scripts\\utils'; &('C:\\HashiCorp\\Vagrant\\embedded\\gems\\2.2.7\\gems\\vagrant-2.2.7\\plugins\\providers\\hyperv\\scripts\\import_vm.ps1')", "-VMConfigFile", "'C:\\Users\\jayap\\.vagrant.d\\boxes\\hashicorp-VAGRANTSLASH-bionic64\\1.0.282\\hyperv\\Virtual Machines\\47420631-D5E2-4041-9698-C7E0C2633931.vmcx'", "-DestinationPath", "'C:\\Users\\jayap\\.vagrant\\machines\\default\\hyperv\\Virtual Hard Disks\\ubuntu-18.04-amd64.vhdx'", "-DataPath", "'C:\\Users\\jayap\\.vagrant\\machines\\default\\hyperv'", "-SourcePath", "'C:\\Users\\jayap\\.vagrant.d\\boxes\\hashicorp-VAGRANTSLASH-bionic64\\1.0.282\\hyperv\\Virtual Hard Disks\\ubuntu-18.04-amd64.vhdx'", "-VMName", "''", "-ErrorAction", "Stop"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: WARNING: The names of some imported commands from the module 'VagrantVM' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose
parameter. For a list of approved verbs, type Get-Verb.
===Begin-Error===
{
    "error":  "The Hyper-V Virtual Machine Management Service (VMMS) is not running."
}
===End-Error===
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31998
DEBUG subprocess: Exit status: 1
ERROR warden: Error occurred: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

The Hyper-V Virtual Machine Management Service (VMMS) is not running.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

The Hyper-V Virtual Machine Management Service (VMMS) is not running.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

The Hyper-V Virtual Machine Management Service (VMMS) is not running.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x0000000002d8b358>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-8b2d8fe9b22224649bc1d3cca8a9290b
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000004819b98>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::HyperV::Errors::PowerShellError: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

The Hyper-V Virtual Machine Management Service (VMMS) is not running.>
ERROR vagrant: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

The Hyper-V Virtual Machine Management Service (VMMS) is not running.
ERROR vagrant: C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/providers/hyperv/driver.rb:60:in `execute'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/providers/hyperv/driver.rb:145:in `import'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/providers/hyperv/action/import.rb:74:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:130:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `run'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/providers/hyperv/action/check_access.rb:19:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/providers/hyperv/action/check_enabled.rb:18:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:57:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/runner.rb:102:in `run'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/machine.rb:238:in `action_raw'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/machine.rb:209:in `block in action'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:613:in `lock'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/machine.rb:195:in `call'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/machine.rb:195:in `action'
C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
 INFO interface: error: An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

The Hyper-V Virtual Machine Management Service (VMMS) is not running.
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

The Hyper-V Virtual Machine Management Service (VMMS) is not running.
 INFO interface: Machine: error-exit ["VagrantPlugins::HyperV::Errors::PowerShellError", "An error occurred while executing a PowerShell script. This error\nis shown below. Please read the error message and see if this is\na configuration error with your system. If it is not, then please\nreport a bug.\n\nScript: import_vm.ps1\nError:\n\nThe Hyper-V Virtual Machine Management Service (VMMS) is not running."]
### Expected behavior
What should have happened?
VM should be created
### Actual behavior
What actually happened?
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
==> default: Importing a Hyper-V instance
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm.ps1
Error:

The Hyper-V Virtual Machine Management Service (VMMS) is not running.

### Steps to reproduce
1.create vagrant file with the configuration above
2.install vagrant(2.2.7)
3.run vagrant up

**Comment by briancain** [comment]
Hey there @jayaprakashkaluva - Thanks for opening an issue on Vagrant! You need to make sure that Hyper-V is enabled prior to using Vagrant. You can find more information about that here on the Microsoft documentation:

- https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/best-practices-analyzer/the-hyper-v-virtual-machine-management-service-must-be-running
- https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

Once Hyper-V is enabled and is running, you will be able to bring up Hyper-V vms. Thanks!

**Comment by jayaprakashkaluva** [comment]
@briancain i verified , hyper-v is running , but i still get this error

**Comment by briancain** [comment]
@jayaprakashkaluva how did you verify hyper-v is running?

**Comment by jayaprakashkaluva** [comment]
![hyperv](https://user-images.githubusercontent.com/41385603/74982363-99c4e000-53f9-11ea-964b-1d2e3066897b.png)
![vmms](https://user-images.githubusercontent.com/41385603/74982374-9d586700-53f9-11ea-8705-7ef77b651e1b.png)
![windows features](https://user-images.githubusercontent.com/41385603/74982379-9fbac100-53f9-11ea-831e-01db32a526ba.png)
@briancain please find the screenshots for your reference

**Comment by jayaprakashkaluva** [comment]
@briancain  i still see this issue.

**Comment by briancain** [comment]
@jayaprakashkaluva Are you able to bring up a Hyper-V VM using the management gui tools, and are you also able to bring up a hyper-v vm using the command line tools `Start-VM`?

**Comment by jayaprakashkaluva** [comment]
@briancain , yes i am able to start vms using cli and gui
![ubuntuvm](https://user-images.githubusercontent.com/41385603/74988007-3ee3b680-5402-11ea-9a0a-71cd35cbc9d3.png)

**Comment by briancain** [comment]
When you run Vagrant, is it in a shell with proper administrative privileges to access Hyper-V? If you bring up a vm using `Start-VM`, and then try to bring up a Vagrant VM in the same command window, does it work and do you have a debug log of that? Thanks

**Comment by jayaprakashkaluva** [comment]
@briancain ehrn i try to run "vagrant up" with admin privileges  i am getting below error.

vagrant : An error occurred while executing a PowerShell script. This error
At line:1 char:1
+ vagrant up
+ ~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error occurr...ipt. This error:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.
Script: check_hyperv_access.ps1
Error:
where : Exception calling "Translate" with "1" argument(s): "Some or all identity references could not be translated."
At C:\HashiCorp\Vagrant\embedded\gems\2.2.7\gems\vagrant-2.2.7\plugins\providers\hyperv\scripts\utils\VagrantVM\Vagrant
VM.psm1:724 char:32
+     $systemACL = $acl.Access | where {
+                                ~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Where-Object], MethodInvocationException
    + FullyQualifiedErrorId : IdentityNotMappedException,Microsoft.PowerShell.Commands.WhereObjectCommand

**Comment by briancain** [comment]
Hey there @jayaprakashkaluva - sorry for taking a while to get back to you. Can you please provide us with the full debug log of running `vagrant up --debug` in a gist that results in that error?
