### ISSUE TITLE
[v2.2.7] rsync-auto command does not include contents of symlinked directories

### ISSUE THREAD

**Issue by chrisd1997** [hashicorp/vagrant#11416]
### Vagrant version
`Vagrant 2.2.7`

### Host operating system
`Debian 4.19.98-1 (2020-01-26)`

### Guest operating system
`Debian 4.9.210-1 (2020-01-20)`

### Vagrantfile
```ruby
config.vm.synced_folder '.', '/vagrant', disabled: true
config.vm.synced_folder 'puppet', '/vagrant'
config.vm.synced_folder 'projects', '/data/projects', type: 'rsync',
   rsync__verbose: true,
   rsync__args: ["--verbose", "--archive", "--delete", "-z", "--links"]
```

### Debug output
https://gist.github.com/chrisd1997/b184b76a17ed7587ea588c50c9cde425

### Expected behavior
Symlinked directories should be included in the automated rsync.

### Actual behavior
Symlinked directories are ignored with the error `Not syncing {SYMLINK_DIR} as it is not part of the current working directory.`

### Steps to reproduce
1. Create a symlinked directory in the CWD
2. Run `vagrant rsync-auto` in the CWD
3. Error is shown `Not syncing {SYMLINK_DIR} as it is not part of the current working directory.`

### References
- [GH-8770](https://github.com/hashicorp/vagrant/issues/8770)

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
