### ISSUE TITLE
VirtualBox: synced_folder mountpath not added to virtualbox settings

### ISSUE THREAD

**Issue by Jasper-Ben** [hashicorp/vagrant#11415]
### Vagrant version
Vagrant 2.2.7

### VirtualBox version
  6.0.14 r133895

### Vagrantfile (relevant parts)
```ruby
  drives = [ "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" ]
  drives.each do |i|
    if Dir.exists?(i+":/")
      config.vm.synced_folder i+":/", "/mnt/"+i, automount: true
    end
  end
  config.vm.synced_folder ".", "/vagrant", automount: true
```

### Expected behavior
Drives should be mounted to /mnt/ (e.g. /mnt/D) at all times.

### Actual behavior
Mountpoints are used when starting with `vagrant up`, however when starting from virtualbox or rebooting from within the VM the synced folders are mounted to /mount/ (e.g. /mount/mnt_D). This happens because vagrant does not set the mountpoint within the virtualbox shared folder settings as seen in https://imgur.com/dDbHUpi. 

### Steps to reproduce
1. create virtualbox VM with syned_folder and custom mountpath
2. start VM with `vagrant up` -> mounted to expected path
3. reboot from within the VM / start VM from virtualbox -> mountpoints are not set

### Proposed Solution
From what I see when looking at the `shared_folders` function in plugins/providers/virtualbox/synced_folders.rb the guestpath variable is never set within the virtualbox shared folder definitions:

```
          # Only setup the shared folders that match our transient level
          if (!!data[:transient]) == transient
            defs << {
              name: os_friendly_id(id),
              hostpath: hostpath.to_s,
              transient: transient,
              SharedFoldersEnableSymlinksCreate: enable_symlink_create,
              automount: !!data[:automount]
            }
          end
```
Unless there is a valid reason for this particular behaviour that I am unaware of, this should be easy enough to fix.

**Comment by Jasper-Ben** [comment]
Well... apparently vboxmanage does not have an option to set a guestpath. https://www.virtualbox.org/manual/ch08.html#vboxmanage-sharedfolder
Which raises the question how virtualbox normaly defines the mountpoint of shared storages

**Comment by ezekiel** [comment]
Seems like this is the final issue for the 2.2.8 milestone. Are there additional changes needed in the PR?

**Comment by Jasper-Ben** [comment]
> Seems like this is the final issue for the 2.2.8 milestone. Are there additional changes needed in the PR?

As far as I am concerned, the PR is ready to be merged. I just rebased it on the current master and re-tested its functionality. Does what it's meant to do: `vagrant up` (re-)sets the mount point in vboxmanager accordingly. @briancain might want to take a last look though.

**Comment by Jasper-Ben** [comment]
duplicate of https://github.com/hashicorp/vagrant/issues/11368
