### ISSUE TITLE
Vagrant non-zero exit status when destroying machine in combination with trigger.before :destroy

### ISSUE THREAD

**Issue by Idefixus** [hashicorp/vagrant#11438]
### Vagrant version
v2.2.7

### Host operating system
Windows 10
VBox 6.1
Plugin: vbguest

### Guest operating system
Ubuntu Trusty

### Vagrantfile
```
  config.vm.define "vulnerable" do |vulnerable|
	vulnerable.vm.box = "$env:VULNERABLE_BOXNAME"
	vulnerable.vm.network "private_network", ip: "$env:IP_VULNERABLE"
	vulnerable.vm.synced_folder "sync/", "$env:PATH_VULNERABLE_SYNC", create: true
	vulnerable.vm.provision "shell", path: "$env:VULNERABLE_PROVISIONING"
	vulnerable.vm.provision "file", source: "../twpol.txt", destination: "/home/vagrant/"
	vulnerable.vm.provision "shell", path: "../tripwire_init.sh"
	# Before destroying the machine get the reports - INFO: The remote script has to end with an echo or sth or it will fail.
	vulnerable.trigger.before :destroy do |trigger|
		trigger.warn = "Checking tripwire against the baseline for differences"
		trigger.run_remote = {inline: "tripwire --check > /vagrant/tripwire_log.txt"}
		trigger.warn = "Test"
	end
  end
```

### Debug output
```
vagrant destroy vulnerable                               
==> vulnerable: Running action triggers before destroy ...       
==> vulnerable: Running trigger...
==> vulnerable: Checking tripwire against the baseline for differences
vulnerable: Running: inline script                                                                                  
==> vulnerable: Trigger run failed
The SSH command responded with a non-zero exit status. 
Vagrant assumes that this means the command failed. 
The output for this command should be in the log above. 
Please read the output to determine what went wrong. 
```

### Expected behavior
Before destroying the machine the tripwire log file should be piped  into a textfile and copied to the sync folder.

### Actual behavior
remote script was excecuted properly but the vagrant script failed with an error.

### Steps to reproduce
1. run vagrant destroy vulnerable

### Notes
Obviously the $env: parameters are replaced by my script and the error disappears when i comment out the trigger.run_remote line

### Workaround
After the remote code trigger another command like: echo 'Workaround' and the problem doesn't occure and a can destroy the machine.
Line should look like this:
trigger.run_remote = {inline: "tripwire --check > /vagrant/tripwire_log.txt; echo 'Tripwire log copied'"}

### Assumption
The problem occures when piping result to a textfile.

### Similar Issues
#9862

**Comment by briancain** [comment]
Hey there @Idefixus - This is likely a result of how the run option for triggers works.

https://www.vagrantup.com/docs/triggers/configuration.html#run

If you want to use a bash operator to output to a file (i.e. `>`), you'll need to execute bash:

```ruby
trigger.run_remote = {inline: "bash -c 'tripwire --check > /vagrant/tripwire_log.txt'"}
```

I know that's not the most intuitive thing, so apologies for the confusion! Updating your run trigger should resolve the issue.

**Comment by Idefixus** [comment]
@briancain Thanks it worked fine :) 
But to be honest I don't completely understand why :P 
Thanks nontheless
