### ISSUE TITLE
Dreaded net-ssh timeout error after hanging for minutes

### ISSUE THREAD

**Issue by jjn1056** [hashicorp/vagrant#11432]
### Vagrant version
Vagrant 2.2.7

### Host operating system
MacOS Mojave 10.14.6

### Guest operating system
uname --all
Linux catme-vagrant 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Its basically CentOS 7.4

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "catme/web"
  config.vm.box_url = $PRIVATE
  config.vm.box_check_update = true
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.ssh.forward_agent = true
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'

  if Vagrant.has_plugin?("vagrant-sshfs")
    config.vm.synced_folder "~/src", "/var/www/src",
      disabled: false,
      type: "sshfs",
      reverse: true
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end
  
  config.vm.define "virtualbox", autostart: true do |vb_vm|
    vb_vm.vm.provider :virtualbox do |v, override| 
      override.vm.network "forwarded_port", guest: 80, host: 8080
      override.vm.network "forwarded_port", guest: 443, host: 8443
      override.vm.network "forwarded_port", guest: 5432, host: 5433
      override.vm.network "private_network", ip: "192.168.33.10"
    end
  end
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    echo "Setting up your git and sqitch accounts"
    git config --global user.name "#{ENV['CATME_USERNAME']}"
    git config --global user.email "#{ENV['CATME_EMAIL']}"
    sqitch config --user user.name "#{ENV['CATME_USERNAME']}"
    sqitch config --user user.email "#{ENV['CATME_EMAIL']}"  
    cd /var/www/src
    echo "Expanding the git history"
    git fetch --unshallow
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    echo "Pull latest git updates"
    git fetch origin --prune
    git pull --rebase origin master
    echo "Updating the development DB and CPAN libs"
    make reset_devdb
    make update
    make restart_httpd
  SHELL
end

```

### Debug output
https://gist.github.com/jjn1056/45499aab61538b0495b535faeafccda0

### Expected behavior
I would expect 'vagrant up' to succeed

### Actual behavior
What actually happened?

I get the following error:

An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout waiting for next packet

Ad sometimes its this:

Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

### Steps to reproduce

vagrant up (or vagrant halt)

### References

It seems like there's tons of people reporting this type of error on and off over the years.  I've read each one and tried all the different things listed to no help

Additional Info

Ok so I completely removed and reinstalled vagrant, that didn't help
Also I disable ssh agent and removed keys as suggested.
Even if vagrant up fails I note that the VM is running and I can ssh into it directly either with 'ssh vagrant@127.0.0.1 -p 2222' and also 'vagrant ssh' works fine.  So this seem more like an annoying thing since I can still get into the box and work.

I have several other VMs managed with vagrant and they all work fine (some older Centos and some Unbuntu and Debian).  The vagrant file is basically the same across the board, nothing particularly fancy.  So its definitely something wrong with my box, I just can't figure it out :)  Weird thing is this worked for for about a month.  Now I get this error consistently.  I get it with 'vagrant halt' as well BTW, here's the gist for that, it looks basically the same (https://gist.github.com/jjn1056/337bac2959fd15f8a2164df477d65b2d).

When I log into the VM after getting this error I'm not seeing any smoking gun issues with the setup.  If anyone has any thoughts would appreciate it.

**Comment by briancain** [comment]
Hey there @jjn1056 - unfortunately, these issues are often problems related to the box itself, and not something specific to Vagrant :disappointed: It is also difficult for us to triage when the box is private. Are you required to use that specific box? Perhaps building off of the `bento/centos-7` boxes would suit your needs just as well? Their packer templates are open source, if you're building your private boxes that way. Or perhaps running `yum update` or rebuilding the box might solve the issue? Sorry to not have a solid answer for you here.

**Comment by jjn1056** [comment]
@briancain yeah I figured so :(  I'm required to build these boxes from scratch, using a packer template off the official ISO.  Its odd because the last fresh build from Dec 2018 was fine so its something in the differences between Centos 7.2 and 7.4

I'm going to review the packer template to see if we changed anything else in the way the image is built.  I figured at least to add whatever info I can find since clearly people have this issue a lot.

**Comment by jjn1056** [comment]
The thing that's really odd here is that when I first provisioned the VM it worked fine expect it would hang at 'virtualbox: Configuring and enabling network interfaces...' for up to a few minutes but then eventually proceed to complete normally.  After about a month of using the box suddenly this happened.  And I can't find any differences in open-ssh between this box and the old imagine from Dec 2018 (built with the same packer scripts).

I'm going to check out the packer scripts for the official centos boxes and see if there's something I'm missing that newer Centos needs.

**Comment by jjn1056** [comment]
@briancain 

So running the script found in the bento box here

https://github.com/chef/bento/blob/master/packer_templates/_common/sshd.sh

Seems like it might have fixed it.

Not only do I get a successful up/halt the process is much faster (whereas before it would hang for up to a few minutes)

I've done up/halt repeat like ten times and it seems fine now.

Not sure how to tag this so that other people getting this issue find my solution.  Its so clearly SSH related.  I was able to see the packet loss when running a trace.  Sadly I'm not an admin ninja so I can't really say why that script fixed it but cargo culting it seemed to turn the trick.

The only issue I have now is I think we need this script in the packer build for the development VMs but I doubt I want it in the part of the pipeline that builds the AWS image.  I'll have one of my smart admins look it over.

Thanks for pointing me to the bento box!  I'm going to leave this open for a bit in case I discover anything else useful to those that come after me.

**Comment by jjn1056** [comment]
After playing a bit more its possible this is related to an equipment change on my side that changed the default DNS provider to one with higher latency than had been configured previously.  Just thought to add that info since it sheds light on the 'why did this start happening yesterday'.  Midweek my DSL modem got taken out by a lightning storm and I replaced it with a newer model which was preconfigured to use the ATnT DNS provider rather then Cloudflare.  I'm not going to experiment right now with that since I've already lost a day on this but figured other people might find that info interesting.

**Comment by jjn1056** [comment]
Just one other bit of info, the script that fixed the problem basically added the following lines to /etc/ssh/sshd_config

GSSAPIAuthentication no
UseDNS no

I was able to comment out 'GSSAPIAuthentication no' without the problem returning but when I tried to comment out 'UseDNS no' the problem returned.  That's no surprise based on my findings about the slow DNS resolution issue I mentioned in the previous comment.  I also note there in the bento box for centos there is a script that applies some additional configuration changes related to a slow DNS issue with this OS.  If I get a bit more time I'll play with that fix as well to see if it also helps.

**Comment by jjn1056** [comment]
Just tried the script 'https://github.com/chef/bento/blob/master/packer_templates/centos/scripts/networking.sh' alone to see if it helped and that script alone doesn't fix it (at least with the current DNS provider configuration).  So looks like you really need that 'UseDNS no' in SSH configuration.  My guess is that the DNS provider change is either adding more latency then the reverse lookup can handle or ATnT is doing something evil (likely) since the reverse DNS lookup to my laptop is likely not returning anything meaningful.  I've run into issues when some DNS providers would attempt to return a default page or alternative when DNS lookup fails.

**Comment by wilsonpenha** [comment]
All those changes to ssh config only help to mess up my machine and many issues arise after, I was hoping to have a fix for it as this issue keeps making our lives very hard when deploying on local containers, please help

**Comment by jjn1056** [comment]
@wilsonpenha 

FWIW I think adding UseDNS no globally isn't a big deal after reading about it.  Most of the time when ssh does reverse DNS lookup on your connecting terminal nothing is going to result that is really extra useful info from a security perspective.  From widely reading there does seem like some sort of issue here with SSH + DNS and VMs or containers as I see reports of it from the docker groups.  In any case I'm fairly sure this isn't a vagrant problem but its worth discussing since so many of us bump into this problem.  You can also turn it off with ~/.ssh/config as well for the vagrant user if you don't want to turn it off globally.  Does turning it off actually fix it for you or not?

The only thing that is odd is that my VM using an older Centos ( 7.4) doesn't have this issue at all.  The problem shows up in the image built with 7.7 as the base.  Its an automated packer script that builds the images and I don't see any other real difference although obviously 7.7 will have newer packages across the board.  I looked at the sshd_config for the older version and the 'UseDNS' isn't in that file so I presume its defaulting to yes, which I think is the default value for a long time for open-ssh.

If I had time I'd build with Centos 7.6 nd 7.5 to see if I can spot the version where it started.  Right now I'm paid by the hour here so no time right now.

best of luck

**Comment by jjn1056** [comment]
I don't really have anything new to add here so I'm closing the issue.  Basically adding that 'UseDNS no' totally solves it for me.  If you are having this problem you should try that and see if it helps.  Otherwise if not you'll need to do some detailed trace on the SSH traffic during the vagrant up process to see if you can ID an actionable error.  Why this is a problem on Centos 7.7 and not Centos 7.4 I have no idea.  I see tickets for this issue going back years so I suspect its not related to Centos version differences.  It's possible there are other tweaks to the packer build templates between now and then which are a root cause.  In any case since it works fine for me now I'm going to have to just let it go :). Best of luck if you run into this and I hope my solution works for you

**Comment by wilsonpenha** [comment]
Sorry guys, but setting UseDNS no has no effect and I still have the issue running vagrant up, that breaks my deployments and I am out options as it seems not 100% of the people are getting the same issue for the same reasons, I've tried many, many things with no rocking roll, if close this issue no one will look at and it will become a huge blocker for us trying to deploy on LXC containers, please don't give up on this.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
