### ISSUE TITLE
vagrant down/halt comes back with error using vmware_desktop provider

### ISSUE THREAD

**Issue by elyobelyob** [hashicorp/vagrant#11448]
### Vagrant version

Vagrant 2.2.7

### Host operating system

OSX 10.15.3

### Guest operating system

generic/ubuntu1910

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1910"
  config.vm.provider "vmware_desktop" do |v|
    v.gui = true
  end
end
```

### Debug output

https://gist.github.com/elyobelyob/7a8eae45becac60e64b8d91e93bc24fa

### Expected behavior

Trying to halt/down a vmware image

### Actual behavior

The vmware image runs fine and can ssh with no issues etc, however vmware (Version 11.5.1 (15018442)) isn't correctly running halt/down ... 

### Steps to reproduce

1. See gist
2.
3.

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! Sorry that you're seeing this error.

`vagrant down` is not a built-in Vagrant command (see #7692) -- is it possible that a plugin or local alias is causing this behavior?

Vagrant keeps track of each machine's provider, so it's surprising that it would switch from VMware to VirtualBox for a running VM. Does `vagrant halt` work if you set the default Vagrant provider:

```
export VAGRANT_DEFAULT_PROVIDER=vmware_desktop
vagrant halt
```

Finally, if you'd be willing to create a Gist with the output of `vagrant halt --debug`, that will help us look into the issue further. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
