### ISSUE TITLE
ssh-agent issues: timeout waiting for next packet (follow-up)

### ISSUE THREAD

**Issue by kongeor** [hashicorp/vagrant#11442]
Apologies for bypassing the template, but this is just a follow up to issue https://github.com/hashicorp/vagrant/issues/11225 because it was closed by the bot.

Last month I upgraded my internet connection. The bandwidth increase was approximately from 16Mbps to 44Mpbs. As of this update all my issues went away (that is bootstrapping and provisioning a box). 

I still assume this is not related to vagrant itself but probably to the way the network components work under the hood.

c.c. @briancain @wilsonpenha

**Comment by kongeor** [comment]
Also please note that although my connection was considerably slower it was stable (no downtimes or other networking issues).

**Comment by chrisroberts** [comment]
@kongeor Hi! Would you please provide a copy of your current Vagrantfile and a recent gist of the `--debug` output showing displaying the error.

I also see from the original issue that you were using a centos 7 guest. Can you try using the `bento/centos-7` box (https://app.vagrantup.com/bento/boxes/centos-7) and see if you experience the same issue? My hunch is that there is an issue with the guest causing the error you are encountering, but without being able to actually test the box you are using, we can't verify that.

Thanks!
