### ISSUE TITLE
Update vagrant-lxd link in wiki

### ISSUE THREAD

**Issue by gregsifr** [hashicorp/vagrant#11452]
Project 'catalyst-it/vagrant-lxd' was moved to 'catalyst-it/devtools/vagrant-lxd'. 

The wiki currently links to the old path.

**Comment by jbonhag** [comment]
Thanks for the pointing this out! This has been updated in the wiki.

https://github.com/hashicorp/vagrant/wiki/Available-Vagrant-Plugins#providers
