### ISSUE TITLE
chef-client provisioner does not create a /etc/chef/client.rb file

### ISSUE THREAD

**Issue by tomdz** [hashicorp/vagrant#1145]
This means that when using chef-client the normal way to update the instance (e.g. `knife ssh <node> "sudo chef-client"`), it fails with:

```
WARN: Did not find config file: /etc/chef/client.rb, using command line options.
```

(which tries localhost:4000 as the chef server).

The `client.rb` file is present on the instance in `/tmp/vagrant-chef-1/client.rb` (in my case) which means that

```
knife ssh <node> "sudo chef-client -c /tmp/vagrant-chef-1/client.rb"
```

works, but I'd rather not rely on the presence and name of that temporary folder.

**Comment by mrjcleaver** [comment]
"Vagrant supports running a chef client multiple times."

Can I presume this means in parallel? Maybe to leave a Vagrant.README file in /etc/chef explaining that would save the next person from googling.
