### ISSUE TITLE
vagrant validate should return a non-zero exit code when warnings are found

### ISSUE THREAD

**Issue by ferrarimarco** [hashicorp/vagrant#11450]
### Vagrant version

`Vagrant 2.2.7`

### Host operating system

Ubuntu 18.04, Windows 10

### Guest operating system

Centos 7.4, Ubuntu 18.04

### Vagrantfile

```ruby
VAGRANT_API_VERSION="2"
Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end
```

### Debug output

```shell
C:/Users/Marco/Downloads/Vagrantfile:1: warning: already initialized constant VAGRANT_API_VERSION
C:/Users/Marco/Downloads/Vagrantfile:1: warning: previous definition of VAGRANT_API_VERSION was here
==> default: Ignoring provider config for validation...
Vagrantfile validated successfully.
```

### Expected behavior

A non-zero exit code, because the validator reports warnings

### Actual behavior

The exit code of the command was 0, despite the warnings.

### Steps to reproduce

1. vagrant validate --ignore-provider

/cc @StefanoSalsano

**Comment by chrisroberts** [comment]
This is resolved via #11446 which will be included in the next release.
