### ISSUE TITLE
cant get into vm thru vagrant ssh

### ISSUE THREAD

**Issue by adrianmak** [hashicorp/vagrant#11475]
I upgraded my virtualbox to 6.1.4 and vagrant 2.2.7
on existing vagrant box, just startup with vagrant up and it updated the vbox guest additions
Everything good.
I couldnt get into vm thru vagrant ssh. no any error messages. just stucked at the prompt till i press crtl-C to break.
However I could get into vm thru ssh client  directly e.g. putty to the vbox ip address. I assumed the ssh daemon in the vm is working properly.

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket. Thank you!

**Comment by adrianmak** [comment]
I got a fix from this
https://github.com/hashicorp/vagrant/issues/9143#issuecomment-401088752

**Comment by briancain** [comment]
Ok, I will go ahead and close the issue then. :+1:
