### ISSUE TITLE
sudo yum install -y getenvoy-envoy: is there a way to specify version number?

### ISSUE THREAD

**Issue by mabukhovsky** [hashicorp/vagrant#11481]
Hi Guys,

Do you own getenvoy tool?
https://www.getenvoy.io/install/envoy/centos/

```sudo yum install -y getenvoy-envoy```

Is there a way to specify which version of Envoy to install?

**Comment by briancain** [comment]
Hey there @mabukhovsky - No, we do not own that tool. You should be able to easily install that tool using a [Shell provisioner](https://www.vagrantup.com/docs/provisioning/shell.html). I imagine you should be able to specify the version using the yum package manager. Thanks!
