### ISSUE TITLE
Disable repo check on Fedora box during vagrant up 

### ISSUE THREAD

**Issue by burnyd** [hashicorp/vagrant#11484]
### Vagrant version

Vagrant 2.2.6

### Host operating system

Mac Catalina 

### Guest operating system

Operating system is based off of 32 bit Fedora 18.

### Vagrantfile

```
config.vm.define "tor" do |tor|
    tor.vm.provision "shell", path: "scripts/tor.sh"
    tor.vm.box = "veoslab4-20"
    tor.vm.network "private_network",  virtualbox__intnet: 'private_network', auto_config: false 
    tor.vm.network "private_network",  virtualbox__intnet: 'peering-vlan-5', auto_config: false

  tor.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--memory", 2048]
    end

    end
```
### Debug output

https://gist.github.com/burnyd/e820d71a189fda9dc557e06f98b18be9

### Expected behavior

I would expect the box to boot without having to check if it were a centos or fedora based box without having to issue that bash command checking for repos.  

`bash -c 'type -p dnf || type -p yum'` install -y kernel-devel-`uname -r` gcc dkms make perl bzip2

I simply need a way to bypass the check so that the box will be able to run a provisioner.  I cannot seem to be able to change to a generic VM type that will allow for this?

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! It looks like this command is coming from the vagrant-vbguest plugin:

https://github.com/dotless-de/vagrant-vbguest/blob/master/lib/vagrant-vbguest/installers/fedora.rb

If you don't want to update the VirtualBox guest additions when you boot the machine, you can set the following in your Vagrantfile:

```
config.vbguest.auto_update = false
```

Cheers! 😄
