### ISSUE TITLE
vagrant freezes and vagrant ssh no longer possible

### ISSUE THREAD

**Issue by bamzi** [hashicorp/vagrant#11488]
When logged into the VM, through `vagrant ssh`, the terminal freezes (tried mac terminal & item2) and the instance has be manually restarted to gain access back to the shell. When attempting to `vagrant ssh` again nothing happens, and null is returned. 

the VM instance is still working, making api requests into the VM still return usual results and there doesn't seem to be any drop in performance. So probably not an issue with VirtualBox.

### Vagrant version

Vagrant 2.2.7

### Host operating system

MacOS Catalina 10.15.4 

### Guest operating system

Debian/Buster64 running on `VirtualBox 6.1.4`

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.synced_folder "../", "/repo", type: "rsync", rsync__exclude: ".git/"
    (1..NODES_NUM).each do |i|
        config.vm.define "#{K8S_NAME}-#{i}" do |cfg|
            cfg.vm.box = IMAGE_NAME
            cfg.vm.provider "virtualbox" do |v|
              v.name = "#{K8S_NAME}-#{i}"
              v.memory = MEMORY
              v.cpus = CPU
              v.customize ["modifyvm", :id, "--audio", "none"]
              v.gui = false
            end
            cfg.vm.network "private_network", ip: "#{IP_BASE}#{IP_RANGE + i}"
            cfg.vm.network 'forwarded_port', guest: 6443, host: 6443
            cfg.vm.hostname = "#{K8S_NAME}-#{i}"
            cfg.vm.provision :shell,
                path: "add_hosts.sh",
                privileged: true,
                args: [
                  "#{IP_BASE}#{IP_RANGE + i}",
                  cfg.vm.hostname
                ]
            # setup master or worker ... first is master, all nodes after are workers
            cfg.vm.provision :shell,
            path: "master_node.sh",
            privileged: true,
            args: [
                "#{IP_BASE}#{IP_RANGE + i}",
                "#{K8S_VERSION}"
             ]
        end
    end
end
```

### Debug output
no output, no log. 

### Expected behavior
When working inside the vm, operation should be normal, but instead after 10-15min the shell instance freezes and have to restart terminal to do anything

What should have happened?

### Actual behavior

What actually happened?
shell freezes, hangs and terminal has to be restarted

**Comment by disaac** [comment]
There has been some buzz about an issue with Catalina 10.15.4 and SSH failing to connect to an SSH service by hostname to a port higher than 8000. **This may be unrelated** but figured I would mention if you find that that `vagrant ssh-config` displays a port higher than 8000 and/or you happen to be using an `.ssh/config` with a host defined instead of the IP address. 

Reference: 
* [Catalina 10.15.4 broke SSH](https://feed.tyler.io/so-uh-i-think-catalina-10154-broke-ssh/) 
* [Catalina 10.15.4 broke SSH - Apple Discussion](https://discussions.apple.com/thread/251226509)

**Comment by Komodoro** [comment]
Have you tried vagrantfile without:
- config-ssh-insert_key turned to false[1]?

You are removing vagrant's auto generated keys. 
Are you giving vagrant the proper keys inside _.vagrant_ folder for the specific node?

I'm assuming your NODES_NUM is 1. Or else, doing vagrant ssh won't open more then one shell ssh connection. You have to explicit write:

$ vagrant ssh "#{K8S_NAME}-1"

AFAIK.

Reference:
[1] https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html#config-ssh-insert_key

**Comment by briancain** [comment]
@bamzi - Does this happen for every Vagrant guest, or just your debian box? Are there any logs on the guest VM that have information about what could of happened (i.e. something in /var/log/syslog when it freezes)? Are you able to keep a connection via the VirtualBox gui as well?

**Comment by bamzi** [comment]
@briancain On mac I've only tried it on a debian box. but on windows i'm experiencing similar case with centos7

i'm going to try @Komodoro advice and will report on the end result

**Comment by bamzi** [comment]
Turning off `config.ssh.insert_key = false` causes `rsync` to malfunction ... If I didn't have similar issues with windows laptop also running vitualbox/vagrant then I would think the Catalina ssh problem is the root cause.

**Comment by briancain** [comment]
@bamzi - Does it still freeze if you ssh outside of Vagrant?

**Comment by bamzi** [comment]
Only when i'm SSH'd inside the VM, after about 10min it freezes

**Comment by briancain** [comment]
So if you bring up a vm outside of Vagrant and ssh into it, it freezes? @bamzi

**Comment by bamzi** [comment]
Yes, When I `vagrant up` and then `vagrant ssh` into the machine, after about 10min it freezes, I can't type or exit out of ssh. I have to manually restart the terminal ... trying to `vagrant ssh` back into the machine no longer works, but worse `vagrant halt` doesn't work either.  

Every time this happens, I have to `vagrant destroy` and bring up the machine from scratch

**Comment by briancain** [comment]
@bamzi Sorry, I'll be more specific. From your description, this doesn't really sound like a Vagrant bug. It sounds like an issue with macOS. If you bring up a VM, not using Vagrant, and you ssh into it, do you still experience the freezing issue?

**Comment by bamzi** [comment]
I'm not too sure which app is causing the bug. I'll close this issue .. it's not resolved but i'll post another one once i narrow it down to vagrant

**Comment by andrey-denisenko** [comment]
I have this issue too. It behave exactly as @bamzi says:
---------------------------------------------
> Yes, When I `vagrant up` and then `vagrant ssh` into the machine, after about 10min it freezes, I can't type or exit out of ssh. I have to manually restart the terminal ... trying to `vagrant ssh` back into the machine no longer works, but worse `vagrant halt` doesn't work either.
> 
> Every time this happens, I have to `vagrant destroy` and bring up the machine from scratch
---------------------------------------------
But in my case it enough to do 'vagrant reload' and then do 'vagrant ssh'.

- Windows 10 x64
- VirtualBox 6.1.6
- Vagrant 2.2.7

**Comment by andrey-denisenko** [comment]
**For myself I found a solution:**
I've migrated to VMWare Workstation + vmware-provider-plugin

In my case I had to move from ubuntu/bionic64 to hashicorp/bionic64 image.

And, I definitly can say, that this solved this issue completely.
