### ISSUE TITLE
Why does Windows install require rebooting?

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#11507]
**Is your feature request related to a problem? Please describe.**

Curious to learn more about how Vagrant works.

**Describe the solution you'd like**

Ideally, no reboot would be necessary to install Vagrant. I mean, it's mostly just a Ruby wrapper around existing hypervisors, right?

Is it about updating PATH environment variable? Because there are some ways to update these for Command Prompt and for PowerShell that at worst require logging out, rather than a full reboot.

**Describe alternatives you've considered**

Using VirtualBox directly.

**Comment by chrisroberts** [comment]
Hi there,

In general, a reboot is not required and can be safely ignored. Closing and re-opening existing cmd/powershell windows will be enough for the path to be updated and the exectuable to be located. However, from a UX perspective, it's easier and more reliable to request the user to reboot. This ensures that they are using a fresh cmd/powershell instance to run Vagrant and don't receive command not found errors.

Cheers!
