### ISSUE TITLE
Vagrant was unable to mount VirtualBox shared folders mount -t vboxsf -o uid=1000,gid=1000

### ISSUE THREAD

**Issue by jc-rode** [hashicorp/vagrant#11506]
### Vagrant version

Vagrant 2.2.7

### Host operating system

macos Catalina 10.15.4

### Guest operating system
hashicorp/bionic64

### Vagrantfile

config.vm.synced_folder "~/ansible", "/ansible"

### Debug output

> vagrant reload
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'hashicorp/bionic64' version '1.0.282' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 9999 (guest) => 9999 (host) (adapter 1)
    default: 8088 (guest) => 8088 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
[default] GuestAdditions 6.0.18 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /python => /Users/jrode/python
    default: /ansible => /Users/jrode/ansible
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 ansible /ansible

The error output from the command was:

/sbin/mount.vboxsf: shared folder '/ansible' was not found (check VM settings / spelling)

### Expected behavior

The ansible directory should be mounted.

### Actual behavior

The ansible directory should be mounted.

### Steps to reproduce

The problem was due to a symbolic link that I had in the /home/vagrant directory:

vagrant:/home/vagrant> ll
total 22736
drwxr-xr-x 13 vagrant vagrant     4096 Apr  2 09:55 ./
drwxr-xr-x  3 root    root        4096 Aug 15  2019 ../
lrwxrwxrwx  1 vagrant vagrant        9 Mar 25 23:31 ansible -> /ansible//

If you delete that sym link, then the mount is successful.

So I think that Vagrant should execute the mount command from an empty temp directory.

There are lots of pages found with this error if a user does a search for it but all the answers are misleading... i just found that solution by chance by running the mount command manually from another directory and it worked so that made me realize that there was something special making it fail in /home/vagrant.

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! We were able to confirm that having a symlink with the same name as the device name will cause the command to fail. This is true even if the symlink is pointing to a random file (like /home/vagrant/ansible -> /home/vagrant/.bashrc). That being said, I don't think we want to change the behavior of the mount command at this time. Instead of creating the symlink, we recommend mounting the synced folder inside your home directory, like this:

```ruby
  config.vm.synced_folder "~/ansible", "/home/vagrant/ansible"
```

This eliminates the need for a symlink and will put the Ansible files where you need them.

Cheers and have a great day!

**Comment by jc-rode** [comment]
There's no need for that sym link... but there's no reason for the mount to fail if there is one.  Why can't we have an "ansible" file or sym link in the home directory if we want a directory mounted under "/ansible" ? These are completely unrelated in theory.

At the very least, there could be a check before running the mount command and warn the user when there's a file with the same name as the directory we are trying to mount and explain how to fix it.  This is currently very difficult to understand why it fails...

Thanks.
