### ISSUE TITLE
Error after 'vagrant up'

### ISSUE THREAD

**Issue by prsly** [hashicorp/vagrant#11504]
### Vagrant version
Vagrant 2.2.7

### Host operating system
Mac OS Catalina 10.15.4

### Guest operating system
Ubuntu on AWS

### Vagrantfile

```ruby
require 'vagrant-aws'
Vagrant.configure('2') do |config|
    config.vm.box = 'dummy'
    config.vm.provider 'aws' do |aws, override|
    aws.access_key_id = "xyz"
    aws.secret_access_key = "zyx"
    aws.keypair_name = 'devops-key-pair-euwest2'
    aws.instance_type = "t2.micro"
    aws.region = 'eu-west-2'
    aws.ami = 'ami-0175365'
    aws.security_groups = ['default']
    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = '~/.ssh/devops-key-pair-euwest2.pem'
  end
end
```

### Debug output

https://gist.github.com/prsly/f79a65372b8279011390c7bc64f9eb66

### Expected behavior
Connect to AWS

### Actual behavior
Nothing

### Steps to reproduce
1. vagrant up --provide=aws

**Comment by soapy1** [comment]
Hey there, this seems to be an issue with the vagrant-aws plugin. The issue is already reported there https://github.com/mitchellh/vagrant-aws/issues/566 including some workarounds
