### ISSUE TITLE
Modification of change_host_name capability

### ISSUE THREAD

**Issue by chrisroberts** [hashicorp/vagrant#11508]
## Changes to Vagrantfile configuration

* ~`config.vm.disable_hosts_modification`~ `config.vm.allow_hosts_modification`

This is a new configuration option. It is a boolean value that when ~enabled~ disabled will prevent Vagrant from making modifications to the guest's `/etc/hosts` file.

* `config.vm.network` - `:hostname`

Add a new `:hostname` option to the `config.vm.network` method. This will be a boolean value that, when set to `true`, will signal that a specific address should be used for configuring a hostname within the `/etc/hosts` file. There are a couple of restrictions that come with using this option:

1. The network configuration _must_ provide a static IP address
2. Only one network configuration for the guest can set this value to `true`

## Changes to `/etc/hosts` modifications

The `change_host_name` capabilities need to be updated to follow:

* If `config.vm.disable_hosts_modifications` is `true`, no modifications are performed
* If `config.vm.disable_hosts_modifications` is `false`
  * If a network configuration has been flagged for hostname
    * Search guest /etc/hosts file for existing entry.
    * Remove entry if found
    * Add new entry using address from network configuration
  * If no network configuration has been flagged for hostname
    * Search guest /etc/hosts file for existing entry
    * If entry is found, make no modifications
    * If no entry is found, add entry for hostname on loopback interface with address not in use

## Updates required

Vagrant configuration:

- [x] Add `config.vm.disable_hosts_modification` configuration
- [x] Add :hostname option to `config.vm.network`

Guest capabilities:

- [x] alpine
- [x] alt
- [x] arch
- [x] atomic
- [ ] coreos
- [x] darwin
- [x] debian
- [x] freebsd
- [x] gentoo
- [x] omnios
- [x] openbsd
- [x] photon
- [x] pld
- [x] redhat
- [x] slackware
- [x] suse

**Comment by soapy1** [comment]
Seems like coreOS doesn't really use `/etc/hosts`, so I think this issue is resolved.
