### ISSUE TITLE
Local Box: An error occurred while downloading the remote file. (macOS)

### ISSUE THREAD

**Issue by micchickenburger** [hashicorp/vagrant#11505]
### Vagrant version

Vagrant 2.2.7

### Host operating system

macOS Catalina 10.15.4

```shell
$ uname -a
Darwin Ol-Betsy.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

### Guest operating system

Windows 10 Pro x64 Version 1909 (OS Build 18363.752)

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "windows10"
end
```

### Debug output

[Debug Output Gist](https://gist.github.com/micchickenburger/d0edf0e05e353042d5fd23063cae5dd2)

<img width="829" alt="image" src="https://user-images.githubusercontent.com/4521230/78930540-eaf06800-7a69-11ea-845e-a0ef4317a743.png">

Shell output (for search)

```shell
➜  win10box ls -l                       
total 16883712
-rwxr--r--  1 micahhenning  staff  8631976113 Apr  9 03:38 windows10.box
➜  win10box vagrant box add --name windows10 windows10.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'windows10' (v0) for provider: 
    box: Unpacking necessary files from: file:///Users/micahhenning/Projects/win10box/windows10.box
==> box: Successfully added box 'windows10' (v0) for 'vmware-desktop'!
➜  win10box cat ~/.vagrant.d/boxes/windows10/0/vmware-desktop/metadata.json
{ "provider": "vmware-desktop" }
➜  win10box ls ~/.vagrant.d/boxes/windows10/0/vmware-desktop
Virtual Disk-cl1-s001.vmdk Virtual Disk-cl1-s011.vmdk Virtual Disk-cl1-s021.vmdk
Virtual Disk-cl1-s002.vmdk Virtual Disk-cl1-s012.vmdk Virtual Disk-cl1.vmdk
Virtual Disk-cl1-s003.vmdk Virtual Disk-cl1-s013.vmdk metadata.json
Virtual Disk-cl1-s004.vmdk Virtual Disk-cl1-s014.vmdk vagrant.nvram
Virtual Disk-cl1-s005.vmdk Virtual Disk-cl1-s015.vmdk vagrant.plist
Virtual Disk-cl1-s006.vmdk Virtual Disk-cl1-s016.vmdk vagrant.vmsd
Virtual Disk-cl1-s007.vmdk Virtual Disk-cl1-s017.vmdk vagrant.vmx
Virtual Disk-cl1-s008.vmdk Virtual Disk-cl1-s018.vmdk vagrant.vmxf
Virtual Disk-cl1-s009.vmdk Virtual Disk-cl1-s019.vmdk
Virtual Disk-cl1-s010.vmdk Virtual Disk-cl1-s020.vmdk
➜  win10box vagrant init windows10                                         
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
➜  win10box vagrant up                                                     
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Box 'windows10' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'windows10' (v0) for provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Downloading: windows10
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/micahhenning/Projects/win10box/windows10
```

### Expected behavior

Vagrant box should start.

### Actual behavior

Error occurred while opening file.

### Steps to reproduce

1. Create Windows 10 VM with VMWare Fusion 
2. Shutdown VM
3. Create metadata.json file:  `{ "provider": "vmware-desktop" }`
4. Tar file:  `tar cvzf /Users/micahhenning/Projects/win10box/windows10.box ./*`
5. `cd ~/Projects/win10box`
6. `vagrant box add --name windows10 windows10.box`
7. `vagrant init windows10`
8. `vagrant up`

**Comment by jbonhag** [comment]
Hi there,

Thanks for the detailed report! It looks like that metadata.json file needs to be `{ "provider": "vmware_desktop" }`, with an underscore instead of a dash. Vagrant tries to bring up the box with the `vmware_desktop` provider, so it doesn't see the box in ~/.vagrant.d/boxes/windows10/0/vmware-desktop. Then, it falls back to looking for a box file called `windows10` (without the .box extension) in the current directory, which can't be found.

Would you mind updating the metadata.json file to see if that fixes the issue?

Cheers!

**Comment by chrisroberts** [comment]
@jbonhag's diagnosis here is correct. Fixing the provider name will make it properly discoverable and will resolve the error.

Cheers!
