### ISSUE TITLE
typed_triggers hook not executed when configured inside a provider block

### ISSUE THREAD

**Issue by rgl** [hashicorp/vagrant#11512]
### Vagrant version

2.2.7

### Host operating system

Windows 2019

### Guest operating system

Ubuntu 18.04

### Vagrantfile

```ruby
ENV['VAGRANT_EXPERIMENTAL'] = 'typed_triggers'

Vagrant.configure(2) do |config|
  config.vm.provider 'hyperv' do |hv, override|
    override.trigger.before 'before_start_instance', type: :hook do |trigger|
      trigger.info = 'NEVER CALLED'
      trigger.ruby do |env, machine|
        raise 'NEVER RAISED'
      end
    end
  end
end
```

### Debug output

https://gist.github.com/rgl/1fd9664542b79e3124fb82dbc00e5538

### Workaround

If the trigger is defined globally it works fine.

**Comment by chrisroberts** [comment]
@rgl Hi! Commented on your other issue and I think the same might apply (https://github.com/hashicorp/vagrant/issues/11513#issuecomment-612943851). If you still find that the provider override defined triggers aren't firing, let me know and I'll dig into the issue further.

Thanks!

**Comment by rgl** [comment]
I'm closing this one, as I confirm it's now working with the nightly mentioned in #11513
