### ISSUE TITLE
Enhancement Request: Support Ruby 2.5 or higher

### ISSUE THREAD

**Issue by bitfactory-henno-schooljan** [hashicorp/vagrant#11516]
On March 31st, version 1.18 of the `async-io` gem has been released which is used as a dependency trhough `async-dns` for DNS plugins like `vagrant-dns`. It now requires at least Ruby 2.5, so it does no longer install because Vagrant uses its own Ruby version which is older.

This will only start happening more when time goes on, so It would be nice if Vagrant supports a newer version soon.

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! We've got good news -- the next Vagrant release (v2.2.8) will include Ruby 2.6.5 or higher. That should resolve the issue you're seeing currently.

Cheers and have a great day! :smile:

**Comment by FrankHald** [comment]
Hi @jbonhag :)
What's the ETA of v2.2.8?

**Comment by mffahey** [comment]
Until 2.2.8 is released, I was able to work around this by swapping out the ruby binary included with the vagrant install (`/opt/vagrant/embedded/bin/ruby` on OSX) with a newer version.
