### ISSUE TITLE
Vagrant up results in mount.nfs connection timeout for debian/buster64 - libvirt provider

### ISSUE THREAD

**Issue by gkwan** [hashicorp/vagrant#11527]
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=4 192.168.121.1:/home/user/vagrant-debian /vagrant

Stdout from the command:



Stderr from the command:

mount.nfs: Connection timed out
```

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!

**Comment by gkwan** [comment]
Sorry I clicked new issue from reply from the search list for this mount.nfs connection timeout problem.  It does not take you to the new issue template link but here is the additional information.

### Vagrant version
```
Vagrant 2.2.7
```
### Host operating system
```
LSB Version:	1.4
Distributor ID:	ArchLabs
Description:	ArchLabs Linux
Release:	2019.10.29
Codename:	ArchLabs

Kernel 5.4.33-3-lts
```
### Guest operating system
```
debian/buster64
```
### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  
  config.vm.define "d-01" do |config|
  config.vm.hostname = "debian-01"
  config.vm.box = "debian/buster64"
  config.vm.box_check_update = false
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true
  config.vm.provider :libvirt do |v|
    v.memory = 1024
  end
  end

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```
### Debug output
https://gist.github.com/gkwan/3b730268ecbeed30056051ca0d9210aa
### Expected behavior

What should have happened?

no mount.nfs connection timeout should occur

What actually happened?
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=4 192.168.121.1:/home/user/vagrant-debian /vagrant

Stdout from the command:



Stderr from the command:

mount.nfs: Connection timed out
```

### Steps to reproduce

1.vagrant up

**Comment by gkwan** [comment]
@briancain 
Hi Brian,
Doing a following up. Any thoughts or progress?

**Comment by axelsimon** [comment]
I ran into a similar problem, here are a few things to consider to help you fix it:
- The vagrant VM connects **to** the host's NFS server, so…
- You need to check the NFS server is running properly on your OS. For instance, i had a `/etc/exports.d/backup.exports` to share over NFS a backup drive, which wasn't plugged in at the time and therefore made the NFS service fail. Check your NFS service with something like `systemctl status nfs-server`.
- A time out when everything else should be working sounds like a firewall is dropping the packets. You should check your firewall if your distro uses one, which is the case by default in Fedora. I had to add the `virbr0` interface to the `FedoraWorkstation` zone and allow the following services: rcp-bind (111), nfs and nfs3 (2049).

Hope this helps!

**Comment by gkwan** [comment]
@axelsimon 
Thank you for your input and assistance.
- Yeah the nfs-server service is loaded and active, I even chmod /etc/exports.d to 777 from 755, just in case. Vagrant creates the linux bridges (virbrX interfaces) automatically so it's there.  My firewall enables everything to pass through within my network. I don't have Fedora on my setup for zones.
- The thing is ... it only happens on the vagrant debian-buster64 and vagrant arch images. This problem does not exist in the centos7 and ubuntu1804 images.

**Comment by briancain** [comment]
@gkwan It sounds like this is just an issue with the boxes you are using. The command is timing out, so I imagine there's probably something in the logs on the guest side for why the mount connection timed out. I'd look there first. Otherwise, this isn't a Vagrant issue, but an issue with the boxes. Vagrant is doing the right thing with a retryable connection, the mount command is just not completing successfully. If you still can't figure it out, it might be worth asking on the mailing list or discuss channels to see if other libvirt users encountered this. Thanks!
