### ISSUE TITLE
vmware getGuestIPAddress issue

### ISSUE THREAD

**Issue by bogutskyy** [hashicorp/vagrant#11528]
I planned use vmware as vagrant prvider, I thought it's better. I am very disappointed. I spent money for VMWare Workstation Pro and for vagrant vmware plugin, but now I can't normally work with vagrant. Can comebody help?

```
 INFO vmware_driver: Trying vmrun getGuestIPAddress...
 INFO subprocess: Starting process: ["/usr/bin/vmrun", "getGuestIPAddress", "/var/www/torrenter/.vagrant/machines/torrenter/vmware_workstation/b87c27c9-70af-4e07-b080-04c41a1a17d6/ubuntu-18.04-amd64.vmx"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: Error: The VMware Tools are not running in the virtual machine: /var/www/torrenter/.vagrant/machines/torrenter/vmware_workstation/b87c27c9-70af-4e07-b080-04c41a1a17d6/ubuntu-18.04-amd64.vmx
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 255
 INFO vmware_driver: vmrun getGuestIPAddress failed: VMRunError
```

### Vagrant version
Vagrant 2.2.7

### Host operating system
Ubuntu 18.04.4

### Guest operating system
Ubuntu 18.04 from box https://app.vagrantup.com/laravel/boxes/homestead

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path("vendor/laravel/homestead", File.dirname(__FILE__))

homesteadYamlPath = File.expand_path("Homestead.yaml", File.dirname(__FILE__))
homesteadJsonPath = File.expand_path("Homestead.json", File.dirname(__FILE__))
afterScriptPath = "after.sh"
customizationScriptPath = "user-customizations.sh"
aliasesPath = "aliases"

require File.expand_path(confDir + '/scripts/homestead.rb')

Vagrant.require_version '>= 2.2.4'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON::parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in " + File.dirname(__FILE__)
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if File.exist? customizationScriptPath then
        config.vm.provision "shell", path: customizationScriptPath, privileged: false, keep_color: true
    end

    if Vagrant.has_plugin?('vagrant-hostsupdater')
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    elsif Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.aliases = settings['sites'].map { |site| site['map'] }
    end
end
```

### Debug output

https://gist.github.com/bogutskyy/98f92dc38c45d01e8d00b6135f5a7ae4

### Expected behavior

Virtual machine start successfully.

### Actual behavior

Start process stuck on `Waiting for the VM to receive an address...`

### Steps to reproduce

1. Use `vmware_workstation` provider

**Comment by chrisroberts** [comment]
Hi there,

Based on the output provided in the debug log it appears that your VMware installation isn't fully setup. Would you open the VMware GUI and validate that it is fully setup and properly licensed. If so, please attempt to create a local VM via the GUI interface. If VMWare is properly setup, and local VM creation and startup are successful then I will investigate further to determine root cause.

Cheers!

**Comment by bogutskyy** [comment]
@chrisroberts Thanks for reply. I installed Ubuntu 20.04 in VMware GUI. It works. 
![image](https://user-images.githubusercontent.com/10667800/80302361-4765be00-87b2-11ea-87d0-bdabe71b5c94.png)

**Comment by chrisroberts** [comment]
@bogutskyy Would you please try creating a new Vagrant project and see if it generates the same error:

```
mkdir test-project
cd test-project
vagrant init hashicorp/bionic64 -m
vagrant up
```

Thanks!

**Comment by bogutskyy** [comment]
https://gist.github.com/bogutskyy/6209bb9409510e5a5044e54b5be85dac @chrisroberts

**Comment by bogutskyy** [comment]
@chrisroberts Sorry, I have reinstalled vmware workstation and now it works, finally. I don't know how. I reinstalled it because even in vmware GUI my previously created ubuntu 20 virtual machine has been broken. Now it works everywhere.

**Comment by bogutskyy** [comment]
Linux headers have been upgraded from 4.15.0-106 to 4.15.0-108, and again, the same issue. It's a big headache! Each time I have issues with commercial products. It's not good. I have reinstalled vmware and vagrant. And again 
```
DEBUG vmware_driver:  -- MAC: 00:0c:29:9b:32:fc
 INFO vmware_driver: Reading DHCP lease for '00:0c:29:9b:32:fc' on 'vmnet8'
DEBUG vagrant_utility: request METHOD=GET PATH=/vmnet/vmnet8/dhcplease/00:0c:29:9b:32:fc RESPONSE=400 ERROR=open /etc/vmware/vmnet8/dhcpd/dhcpd.leases: no such file or directory
 WARN vmware_driver: Non-NAT interface on slot 1. We can only read IPs of NATs for now.
 INFO vmware_driver: Trying vmrun getGuestIPAddress...
 INFO subprocess: Starting process: ["/usr/bin/vmrun", "getGuestIPAddress", "/var/www/test-project/.vagrant/machines/test-project/vmware_desktop/8ebdb17f-c5a8-43f9-9427-22ec2134541e/ubuntu-18.04-amd64.vmx"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: Error: The VMware Tools are not running in the virtual machine: /var/www/test-project/.vagrant/machines/test-project/vmware_desktop/8ebdb17f-c5a8-43f9-9427-22ec2134541e/ubuntu-18.04-amd64.vmx
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 255
 INFO vmware_driver: vmrun getGuestIPAddress failed: VMRunError
```

**Comment by briancain** [comment]
Hey there @bogutskyy It seems like based on the error you posted, the issue is with your guest not having VMWare tools running on the virtual machine. Can you use a box with vmware tools, or can you install them and try again?

**Comment by soapy1** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
