### ISSUE TITLE
Vagrant requires bash to be installed/present on box

### ISSUE THREAD

**Issue by jmgurney** [hashicorp/vagrant#11532]
### Vagrant version

$vagrant -v
Vagrant 2.1.2

Required due to old host system, running 2.2.7 results in no command output.

### Host operating system

MacOSX 10.10.5 w/ VirtualBox 5.1.38 r122592

### Guest operating system

FreeBSD 13.0-CURRENT

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-13.0-CURRENT"
  config.vm.provision "shell",
    inline: "touch /root/testfile"
end

```

### Debug output

The debug output for the second `vagrant up` command, which is the one that fails, is:
[vagrant.debug.txt](https://github.com/hashicorp/vagrant/files/4504499/vagrant.debug.txt)

The most relevant lines are:
```
DEBUG ssh: == Net-SSH connection debug-level log END ==
DEBUG ssh: Checking whether SSH is ready...
DEBUG ssh: Re-using SSH connection.
 INFO ssh: SSH is ready!
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute:  (sudo=false)
DEBUG ssh: stderr: bash: Command not found.

DEBUG ssh: Exit status: 1
 INFO ssh: SSH not ready: #<Vagrant::Errors::SSHInvalidShell: The configured she
ll (config.ssh.shell) is invalid and unable
to properly execute commands. The most common cause for this is
using a shell that is unavailable on the system. Please verify
you're using the full path to the shell and that the shell is
executable by the SSH user.>
```

### Expected behavior

That after a second `vagrant up` (first one fails due to no MAC address), that it should not report that there was no shell found.  The same issue happens when `vagrant halt` command is issued.

### Actual behavior

It attempts to find bash on the guest OS, which is not a defined POSIX command.

### Steps to reproduce

1. Install Vagrantfile in a directory
2. `vagrant up` (first time reports MAC NAT issue)
3. `vagrant up`

### References

Twitter thread that prompted the opening of the issue:
[thread](https://twitter.com/radeksimko/status/1252153596252172288?s=20)

**Comment by chrisroberts** [comment]
Hi there,

Vagrant does not hardcode the usage of bash. It is simply the default value set for the shell when using the SSH communicator. This can be modified by setting the `shell` option for the SSH communicator: https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html#config-ssh-shell

In your Vagrantfile, the update would look something like:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "freebsd/FreeBSD-13.0-CURRENT"
  config.vm.provision "shell",
    inline: "touch /root/testfile"

  config.ssh.shell = "/bin/sh"
end
```

Cheers!

**Comment by radeksimko** [comment]
I'm going to add a little bit of extra context, just for completeness:

Vagrant also has a concept of [base boxes](https://www.vagrantup.com/docs/boxes/base.html), which allow you to publish/distribute a box with any settings (including `config.ssh.shell`) and such settings then becomes effectively default settings for any consumers of that box. In short - if you are building a BSD box, it makes sense to build a simple base box and set the shell to `/bin/sh` there, to avoid having to duplicate that.

As for changing Vagrant's own default shell: As you can imagine Vagrant has a long history and large user base, which means that changing such settings involves a high risk of breaking existing setups.

**Comment by jmgurney** [comment]
Can you provide more information on how to fix FreeBSD's base box such that it sets the shell properly?

I briefly reviewed the page you linked above about base boxes, and a few of the related pages, and could find no references to config, ssh or shell in any of them.  So it's not clear how to fix this from the FreeBSD end.

**Comment by jkugler** [comment]
@radeksimko How does one go about setting the default shell on a base box? I find no relevant setting in the Packer template documentation. Do you mean simply set the default shell for the `vagrant` user to `/bin/sh`? Or is there another setting?

**Comment by jbonhag** [comment]
Hi there,

You should set Vagrant's default shell in your Vagrantfile using the `config.ssh.shell` setting, for example:

```ruby
Vagrant.configure(2) do |config|
  config.ssh.shell = "sh"
  ...
```

If you want to include this setting in a Packer-built base box, you can add it to a [Vagrantfile template](https://www.packer.io/docs/post-processors/vagrant.html#vagrantfile_template) for the Vagrant post-processor.

For a more complete example, have a look at the [FreeBSD Vagrantfile template](https://github.com/chef/bento/blob/master/packer_templates/freebsd/vagrantfile_templates/freebsd.rb) from the Bento project.

Cheers!

**Comment by jmgurney** [comment]
This implies using a tool (packer) that FreeBSD is not using for building their box. I'm trying to figure out how to make the build process that is at: https://svnweb.freebsd.org/base/head/release/Makefile.vagrant?revision=313044&view=markup do the correct thing so people don't have to modify their Vagrantfile to provide the `config.ssh.shell` line.

Also, question about the vagrantfile template.  Is the template used for `vagrant init`, or is that sourced and applied to ALL vagrantfiles?  If it's the former, is there a better option?  Excepting everyone to modify their Vagrantfile to include this line, when it may change in the future is not a scalable solution.

If you have suggestions on how to modify FreeBSD's building of vagrant boxes to fix this, I'm all ears.  If it's use packer, that likely won't fly w/ FreeBSD's release engineering team as they try to ensure that the build process has minimal third party dependencies.

**Comment by briancain** [comment]
@jmgurney when you build a Vagrant box, you have the option to include a Vagrantfile where you can set these kinds of configuration options that will be used when others bring up the box as a guest. That Vagrantfile template is just a packer setting that's used to package a Vagrantfile inside the box. If you include that, then downstream users won't need to set that setting, because it will already be configured for that specific guest. This Vagrantfile is one of the few that gets auto-loaded and configured when bringing up a guest: https://www.vagrantup.com/docs/vagrantfile/#load-order

If they're not using packer, they can also use the `vagrant package --vagrantfile Vagrantfile` command to include it in the box: https://www.vagrantup.com/docs/cli/package.html#vagrantfile-file

If they're making the box another way, it is probably good enough to include the Vagrantfile along side where the `metadata.json` file is located inside the box itself before it gets packaged up. But either way, if that Vagrantfile exists with the config setting you need, it will be present when users bring up the guest. Hope that makes some sense!

**Comment by jmgurney** [comment]
Thanks, I'll run a test, but I think that this will work!
