### ISSUE TITLE
Vagrant 2.1.5 C:/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- vagrant/util/credential_scrubber (LoadError)

### ISSUE THREAD

**Issue by ak1ash** [hashicorp/vagrant#11531]
Have tried reinstalling vagrant on windows 10. Now I am not even able to uninstall vagrant because of the following issue. 

### Vagrant version

vagrant 2.1.5 is the version I am using.
Oracle virtualBox version 6.0.8.

### Host operating system

Windows 10

### Guest operating system

Windows 10

### Debug output

C:\Users\admin\Desktop\Blue Planet\ra_devops_toolkit_19.0.2>vagrant global-status
C:/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- vagrant/util/credential_scrubber (LoadError)
        from C:/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/embedded/gems/2.1.5/gems/vagrant-2.1.5/lib/vagrant.rb:2:in `<top (required)>'
        from C:/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/embedded/gems/2.1.5/gems/vagrant-2.1.5/bin/vagrant:88:in `<main>'

### Expected behavior

What should have happened?
When I give command
--> vagrant up 
It must execute properly (Bring up VM)

### Actual behavior

What actually happened?
It is showing the above issue.

**Comment by briancain** [comment]
@ak1ash - I recommend uninstalling the current version of Vagrant you have, and upgrading to the latest version of Vagrant. Doing so should resolve your issue, thanks!

**Comment by ak1ash** [comment]
Note: I am unable to install vagrant -2.1.5 in my present windows operating system. It displays error as follows:
#The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2330.

**Comment by briancain** [comment]
@ak1ash - It seems like your Vagrant installation is just missing a bunch of files. The path you shared is also interesting. How did you install Vagrant originally? I'd say if you can remove it through the add and remove programs option, or maybe just try deleting the package directory, then install the latest Vagrant, that should solve your issue.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
