### ISSUE TITLE
Ubuntu 20.04 missing support on ansible repo/python 3

### ISSUE THREAD

**Issue by matuskosut** [hashicorp/vagrant#11544]
### Vagrant version

2.2.7

### Host operating system

macOS 10.15.3

### Guest operating system

Ubuntu 20.04 Focal Fossa

### Vagrantfile

```
Vagrant.configure("2") do |config|
  config.vm.box = "matuskosut/ubuntu-20.4-beta"
  config.vm.box_version = "202022.04.0"
end
```

### Debug output

https://gist.github.com/matuskosut/40225b48d53111191bdddbc53a031e18

```
Stderr from the command:

E: The repository 'http://ppa.launchpad.net/ansible/ansible/ubuntu focal Release' does not have a Release file.
```

### Expected behavior

Setup ansible on a VM.

### Actual behavior

Repository does not yet support neither Ubuntu 20.04 Focal nor Python 3.
Ansible recommends using official debian/ubuntu repos for now (just not adding PPA), e.g.: `apt update && apt install -qy ansible` (ref. below)

- https://github.com/hashicorp/vagrant/blob/58687e6c4485790670fead7b579e3a1a60927b77/plugins/provisioners/ansible/cap/guest/ubuntu/ansible_install.rb

### Steps to reproduce

1. vagrant up

### References

- https://github.com/ansible/ansible/issues/57342 - Until this is done install the package from the Debian repos as it is based on python3 there.

**Comment by jbonhag** [comment]
Hi there, and thanks for opening an issue with Vagrant!

While we appreciate the request, I don't think we want to make a temporary change to Vagrant to work around an upstream issue. However, I can suggest a couple of options to get Ansible installed on this version of Ubuntu:

Option 1: Use a shell provisioner to install Ansible from the Debian repos

```
Vagrant.configure("2") do |config|
  config.vm.box = "matuskosut/ubuntu-20.4-beta"
  config.vm.box_version = "202022.04.0"

  config.vm.provision :shell, inline: "apt update && apt install -qy ansible"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
```

Option 2: Installing Ansible with pip

```
Vagrant.configure("2") do |config|
  config.vm.box = "matuskosut/ubuntu-20.4-beta"
  config.vm.box_version = "202022.04.0"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.install_mode = :pip
  end
end
```

If neither of these workarounds is an option, let us know and we'd be happy to take another look at this issue.

Cheers! 😄
