### ISSUE TITLE
Setting config.nfs.verify_installed to false has no effect

### ISSUE THREAD

**Issue by akarasulu** [hashicorp/vagrant#11552]
I run ganesha nfs rather than the kernel nfs server. The kernel module check to verify installation is a blocker. I set `config.ssh.verify_installed = false` but it has no effect. The checks are still being used as can be seen in the [gist](https://gist.github.com/akarasulu/57a1d214ef3b1e78047dc45f9c6cacfa) with the debug output.

### Vagrant version

2.2.7

### Host operating system

Ubuntu -- both WSL and direct (all deb based systems tried)

### Guest operating system

NA

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.ssh.forward_agent = true
  config.ssh.proxy_command = "ssh root@xxxx netcat %h %p"
  config.ssh.insert_key = false

  # Try to get vagrant to stop complaining about nfs installation
  config.nfs.verify_installed = false

  config.vm.synced_folder ".", "/vagrant", disabled: false, type: "nfs", nfs_export: false

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.host = "vms0"
    libvirt.memory = 1024
    libvirt.nested = true
    libvirt.uri = "qemu+ssh://root@xxxx/system"
    libvirt.connect_via_ssh = true
  end

  config.vm.network "forwarded_port", guest: 4242, host: 4242, host_ip: "127.0.0.1"
end
```

### Debug output

https://gist.github.com/akarasulu/57a1d214ef3b1e78047dc45f9c6cacfa

### Expected behavior

Bypass check for kernel NFS server installation.

### Actual behavior

Continues to complain that it is not installed.

### Steps to reproduce

Try up on Vagrantfile on Linux or WSL. This occurs both on Ubuntu and Debian.

### References

- GH-5269 and fix https://github.com/hashicorp/vagrant/commit/964f340f099cd56a93b7b97cd3e1c22504862d3b

**Comment by akarasulu** [comment]
Shouldn't there be a check here for the `verify_installed` property:

```ruby
      def usable?(machine, raise_error=false)
        # If the machine explicitly said NFS is not supported, then
        # it isn't supported.
        if !machine.config.nfs.functional
          return false
        end
        return true if machine.env.host.capability(:nfs_installed)
        return false if !raise_error
        raise Vagrant::Errors::NFSNotSupported
      end
```

Incidentally modifying the logic here made my `vagrant up` work perfectly.

**Comment by briancain** [comment]
Hey there @akarasulu - Could you provide the full debug log from running `vagrant up --debug`? Thanks!

**Comment by akarasulu** [comment]
> Hey there @akarasulu - Could you provide the full debug log from running vagrant up --debug? Thanks!

Hiya @briancain let me re-setup that environment configuration again and get back to you shortly. Had destroyed the remote virtual machine server. 

Thank you for responding.

**Comment by briancain** [comment]
Any progress on giving us the debug log?

**Comment by akarasulu** [comment]
Sorry for taking so long. Here's the output of `vagrant up --provider libvirt --debug`:

[typescript.log](https://github.com/hashicorp/vagrant/files/4665556/typescript.log)

**Comment by briancain** [comment]
@akarasulu - It looks like you just need to install a nfs helper function here to avoid the mount command from failing:

https://askubuntu.com/a/525246

**Comment by akarasulu** [comment]
Thanks that worked out for me.
