### ISSUE TITLE
Vagrant 2.2.7 does not work on Windows

### ISSUE THREAD

**Issue by jozefizso** [hashicorp/vagrant#11557]
### Vagrant version

Vagrant 2.2.7

### Host operating system

Windows 10 1909 Enterprise, 64-Bit

### Guest operating system

(none)

### Vagrantfile

(any valid vagrant configuration)

### Debug output

https://gist.github.com/jozefizso/817427f97bef108994988a0d75847eaf#file-vagrant-info-debug-log

### Expected behavior

Vagrant 2.2.7 should work.

### Actual behavior

I cannot get Vagrant to work after upgrade to latest version.

### Steps to reproduce

1. Upgrade to Vagrant 2.2.7
2. Run any vagrant command (eg. `up`, `info`...)
3. Vagrant fails to run because of issues with plugins

### References

I tried to fully uninstall Vagrant, the Vmware plugin and all the files in C:\HashiCorp\Vagrant directory and I did clean installation of Vagrant 2.2.7 with PC restarts between.

I tried to run `vagrant plugin repair` and afterswards `vagrant plugin expunge --reinstall`

**Comment by chrisroberts** [comment]
Hi there,

Would you please try running:

```
vagrant plugin uninstall vagrant-sshfs
```

and then performing the expunge with reinstall. Alternatively, if that does not work, try expunging the plugins (without the `--reinstall` flag) and installing them again manually. It appears that `vagrant-sshfs` plugin is causing a constraint conflict and it may be that the `--reinstall` option is being too strict.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
