### ISSUE TITLE
Enhancement Request: Publish to Windows App Store

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#11551]
**Is your feature request related to a problem? Please describe.**

I'm lazy and wanna Windows+app+Enter+vagrant+Enter+Enter to install

**Describe the solution you'd like**

Vagrant is not presently available via the Windows App Store.

Not sure if Windows Store supports Ruby-based apps, but would be cool

**Describe alternatives you've considered**

Chocolatey

**Comment by chrisroberts** [comment]
Hi there,

At this point in time we have no plans on distributing through the Windows App Store. That may change at some point in the future but currently all official releases are published through releases.hashicorp.com.

Cheers!
