### ISSUE TITLE
Vgarant up freezing at " SSH auth method: private key"

### ISSUE THREAD

**Issue by prasho20099** [hashicorp/vagrant#11556]
Vgarant up freezing at " SSH auth method: private key"

I am running latest version of vagrant and virtual box on windows 10.
Tried uninstalling vagrant and virtual box and installing again 
Checking virtualization enabled.

Regards,
Prashant

**Comment by soapy1** [comment]
Hey @prasho20099 thanks for opening up an issue. In order to better understand your issue we'll need a bit more information. Could you provide a gist of the debug log (https://www.vagrantup.com/docs/other/debugging.html) and the contents of your Vagrantfile. Thanks!

**Comment by prasho20099** [comment]
[VBox.log](https://github.com/hashicorp/vagrant/files/4549889/VBox.log)
[VBoxHardening.log](https://github.com/hashicorp/vagrant/files/4549890/VBoxHardening.log)
[VBoxSVC.log](https://github.com/hashicorp/vagrant/files/4549893/VBoxSVC.log)

**Comment by prasho20099** [comment]
Hi Soapy1,

Thank you for looking into it. Please find below my vagrant file and error.
<img width="457" alt="Capture" src="https://user-images.githubusercontent.com/64457512/80563334-68bfe780-8a08-11ea-8528-929eedaf7fb3.PNG">


Vagrant.configure("2") do |config|
  config.vm.define :webapp do |webapp|
    webapp.vm.box = "centos/7"
	webapp.vm.box_url = "centos/7"
    webapp.vm.network :public_network
    webapp.vm.hostname = "webapp"

  end
 end

**Comment by soapy1** [comment]
This is a known issue on the centos/7 box. From the centos blog

> Some people reported "could not resolve host" errors when running the centos/7 image for VirtualBox on Windows hosts.

The blog has a fix as well, you can add `vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]`. So, your Vagrantfile should look something like
```
 config.vm.define :webapp do |webapp|
    webapp.vm.box = "centos/7"
   # whatever other config

    webapp.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
  end
```
here's a link: https://blog.centos.org/2019/07/updated-centos-vagrant-images-available-v1905-01/

**Comment by prasho20099** [comment]
Thank you so much @soapy1  It helps :)
