### ISSUE TITLE
2.2.7 installer fails on fresh install due to 2.2.6 reference

### ISSUE THREAD

**Issue by Uberroot** [hashicorp/vagrant#11564]
### Vagrant version 
2.2.7

### Host operating system
Windows 10 Pro

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior

Installer completed

### Actual behavior

Installer prompts "The feature you are trying to use is on a network resource that is unavailable. Click OK to try again or enter an alternative path to folder containing the installation package 'vagrant_2_2_6_x86_64.msi' in the box below"

Note the version number.

This is followed by "The older version of Vagrant cannot be removed. Contact your technical support group."

### Steps to reproduce

1. Download 2.2.7 x86_64 to %USERPROFILE%\Downloads
2. Verify SHA (successful)
3. Run installer on system without Vagrant, selecting defaults.

### References
This does not appear to be the same as:
- GH-11529
- GH-11382

**Comment by briancain** [comment]
Hey there @Uberroot - Are you saying you are trying to install Vagrant without a prior install, and you're getting an error saying an older version of Vagrant cannot be moved? Did you install and then uninstall Vagrant 2.2.6 prior to trying to install 2.2.7? Have you tried running the uninstall tool again?

**Comment by Uberroot** [comment]
It looks like this was the result of a restore from an automated backup where artifacts were included for some reason. Wiped them out running uninstall through the 2.2.6 msi and it ran cleanly.
