### ISSUE TITLE
Vagrant up fails with vagrant-vmware-desktop/helper/vagrant_utility.rb:66:in `initialize': undefined method `[]'

### ISSUE THREAD

**Issue by Badsworth** [hashicorp/vagrant#11575]
### Vagrant version
2.2.7

### VMware Utility version
1.0.7

### vagrant-vmware-desktop plugin version
2.0.3

### Host operating system
Windows 10 Pro

### Guest operating system
hashicorp/bionic64

### Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
end

### Debug output

https://gist.github.com/Badsworth/93e8f966eddb078eb0b54af7d8938c99

### Expected behavior

VM created and available in VMware Workstation

### Actual behavior

Vagrant up failed with errror:-

vagrant-vmware-desktop/helper/vagrant_utility.rb:66:in `initialize': undefined method `[]'

### Steps to reproduce
1. vagrant up

**Comment by eproxus** [comment]
Same on macOS 10.15.4.

**Comment by briancain** [comment]
Actually, going to close this in favor of https://github.com/hashicorp/vagrant/issues/11572 since this was a duplicate
