### ISSUE TITLE
Cannot insert ssh public key in ESXi 7.0

### ISSUE THREAD

**Issue by rgl** [hashicorp/vagrant#11574]
### Vagrant version

2.2.7

### Guest operating system

ESXi 7.0

### Expected behavior

SSH keys should be inserted without errors.

### Actual behavior

The code at https://github.com/hashicorp/vagrant/blob/v2.2.7/plugins/guests/esxi/cap/public_key.rb#L23-L31

Fails with:

```
==> esxi: Waiting for SSH to become available...
    esxi: 
    esxi: Inserting generated public key within guest...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

set -e
SSH_DIR="$(grep -q '^AuthorizedKeysFile */etc/ssh/keys-%u/authorized_keys$' /etc/ssh/sshd_config && echo -n /etc/ssh/keys-${USER} || echo -n ~/.ssh)"
mkdir -p "${SSH_DIR}"
chmod 0700 "${SSH_DIR}"
cat '/tmp/vagrant-insert-pubkey-1588517835' >> "${SSH_DIR}/authorized_keys"
chmod 0600 "${SSH_DIR}/authorized_keys"
rm -f '/tmp/vagrant-insert-pubkey-1588517835'


Stdout from the command:



Stderr from the command:

chmod: /etc/ssh/keys-root: Operation not permitted

```

Here are the ESXi 7.0 filesystem permissions:

```
[root@localhost:~] ll /etc/ssh/
total 596
drwxr-xr-x    1 root     root           512 May  3 14:56 .
-r-------T    1 root     root             0 Mar 16 10:34 .#ssh_host_rsa_key
-r--r--r-T    1 root     root             0 Mar 16 10:34 .#ssh_host_rsa_key.pub
-r-------T    1 root     root          1396 Mar 16 10:34 .#sshd_config
drwxr-xr-x    1 root     root           512 May  3 14:57 ..
drwxr-xr-x    1 root     root           512 May  3 14:56 keys-root
-r--r--r--    1 root     root        577388 Mar 16 10:34 moduli
-rw------T    1 root     root           551 Mar 16 10:34 ssh_config
-rw------T    1 root     root             0 Mar 16 10:34 ssh_host_dsa_key
-rw-r--r-T    1 root     root             0 Mar 16 10:34 ssh_host_dsa_key.pub
-r--------    1 root     root          1704 May  3 14:56 ssh_host_rsa_key
-rw-------    1 root     root           381 May  3 14:56 ssh_host_rsa_key.pub
-rw-------    1 root     root          1397 May  3 14:56 sshd_config
```

And:

```
[root@localhost:~] ll /etc/ssh/keys-root/
total 8
drwxr-xr-x    1 root     root           512 May  3 14:56 .
drwxr-xr-x    1 root     root           512 May  3 14:56 ..
-rw------T    1 root     root             0 Mar 16 10:34 authorized_keys
```

In this new ESXi 7 version something is now preventing the `chmod` to change the directory permissions.

To fix this one just needs to remove the first `chmod` line.

**NB** the second `chmod` works correctly. thou... it will remove the `T` permission bit from the `authorized_keys` file.

Can I submit the PR with that or do you have any other suggestion?

**Comment by soapy1** [comment]
> To fix this one just needs to remove the first chmod line.

I think removing this chmod line might lead to some unexpected behavior once the box is up. The permissions on the ssh config dir need to be something like 0700, more permissive is also ok. To get around this, could do something like check for the permissions of the dir and only try to change them if they are not permissive enough.  This could look like `if [ $(stat -c '%a' $SSH_DIR) -lt 700 ]; chmod 0700 "${SSH_DIR}" ; fi`

**Comment by rgl** [comment]
I think we should only create the directory (and set its permissions) only when it does not already exist. Because when it exists, something else already take care of it, and this code is not the owner of that change/directory. What do you think?

**Comment by rgl** [comment]
@soapy1 please see #11587
