### ISSUE TITLE
vagrant 2.2.8 trigger :all no longer working

### ISSUE THREAD

**Issue by Jeansen** [hashicorp/vagrant#11599]
### Vagrant version
2.2.8

### Host operating system
Debian Buster

### Guest operating system
Debian Buster

### Vagrantfile

```ruby
# This example shows the before trigger, but it also applies to the after trigger !!!
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64
    config.trigger.before :all do |t|
        t.info = "TEST TRIGGER"
    end
end


```

### Debug output
https://gist.github.com/Jeansen/535636d4715f6c2c54c1e52c54fffd3d

### Expected behavior
The before trigger should have been executed and there should be a line "TEST TRIGGER" shown when calling 'vagrant up'.

### Actual behavior
Trigger not executed, the line  "TEST TRIGGER" does not appear in the terminal when calling `vagrant up`

### Steps to reproduce
1. Install Vagrant 2.2.7
2. Copy the snipped from above to a Vagrantfile and run `vagrant up`
3 Install Vagrant 2.2.8
4. Run `vagrant up` again.
5. Compare the first and second output.

**Comment by arnaudveron** [comment]
Same issue with trigger `after_boot`, worked fine in 2.2.7, no more working in 2.2.9
```
        config.trigger.after :after_boot, type: :hook do |trigger|
                trigger.info = "After Boot : Trigger"
                trigger.run = {inline: "/path/to/trigger.sh"}
        end
```
