### ISSUE TITLE
To Many Warnings About Custom vagrant server and authenication token

### ISSUE THREAD

**Issue by bellds** [hashicorp/vagrant#11597]
I feel the vagrant command is overly warning to the point of user unfriendliness when my box has been downloaded from a custom server.

Every` vagrant ssh` command results in the following text:

```
Vagrant has detected a custom Vagrant server in use for downloading
box files. An authentication token is currently set which will be
added to the box request. If the custom Vagrant server should not
be receiving the authentication token, please unset it.

  Known Vagrant server:  vagrantcloud.com
  Custom Vagrant server: xxxxx.xyz.com

Press ctrl-c to cancel...
```

### Vagrant version
2.2.8

### Host operating system
Mac OS X

### Guest operating system
Centos 7

### Vagrantfile

```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

### Expected behavior

This warning should not be printed on every vagrant command related to the box.

I personally do not want to see this on `vagrant ssh` or `vagrant scp` or `vagrant suspend` or `vagrant halt`

### Actual behavior

This warning is getting generated when I issue the following commands
1. `vagrant ssh`
2. `vagrant scp`
3. `vagrant suspend`
4. `vagrant halt`

**Comment by chrisroberts** [comment]
Hi there. This warning is to prevent an auth token from being unintentionally sent to a remote server which it was not intended. The warning is only shown when the authentication token is set. Unsetting the token will stop the warning from being displayed. 

Cheers!

**Comment by bellds** [comment]
So the Box Repo Server is communicated with (and token) sent on every command (including ssh and halt)?

**Comment by chrisroberts** [comment]
Yes, when loading the project environment it will check if there is a new version of the box available to provide an update availability notification.

**Comment by bellds** [comment]
Thanks for the clarification.
