### ISSUE TITLE
Unable to build native extensions on Mac with Vagrant version 2.2.8

### ISSUE THREAD

**Issue by bryansoto** [hashicorp/vagrant#11593]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use
HashiCorp Discuss: https://discuss.hashicorp.com/c/vagrant/24 Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version

2.2.8

### Host operating system

Mac OSX

### Guest operating system

n/a

### Vagrantfile

n/a

The problem is the embedded ruby file, rbconfig.rb, is filled with includes of -isysroot /Users/vagrant/SDKs/MacOSX10.9.sdk .

Removing all those allows native extensions to build again.

**Comment by bryansoto** [comment]
A gist of the modified file if it's needed: https://gist.github.com/bryansoto/e42e644251a56adf22ce8821ff225a7d

**Comment by jbonhag** [comment]
Hi @bryansoto,

Thanks for reporting this issue and including the helpful gist. We are tracking this under https://github.com/hashicorp/vagrant-installers/issues/163 and should have a patch release out soon.

Cheers!
