### ISSUE TITLE
Timed out while waiting for the machine to boot

### ISSUE THREAD

**Issue by Tanoro** [hashicorp/vagrant#11595]
Vagrant 2.2.7
VirtualBox 6.1.6
Host: Windows 10 Pro 64-bit
Guest: ubuntu/bionic64

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = 'ubuntu/bionic64'

	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "forwarded_port", guest: 443, host: 8081

	config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
		vb.customize ['modifyvm', :id, "--natdnshostresolver1", "on"]
	end
end
```

### Debug output

https://gist.github.com/Tanoro/d530914754bf48e2f437f367cb2295e3

### Expected behavior

The VM boots as normal, allowing me to access via vagrant ssh command.

### Actual behavior

Vagrant hangs at "default: SSH auth method: private key" before throwing a timeout error. VM is automatically destroyed. This problem is intermittent! Sometimes, the machine boots properly. Most of the time, it errors in this way. I have checked BIOS. Virtualization is on.

```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

### Steps to reproduce

Simply run `vagrant up` command.

**Comment by briancain** [comment]
Hey there @Tanoro - Generally these issues seem to be fairly common with the Ubuntu box you are using. I recommend increasing the boot_timeout option past it's default value. Typically this solves most of the intermittent issues. Otherwise, I recommend a different box, such as the Bento boxes, as they typically do not have these issues. Thanks!
