### ISSUE TITLE
vagrant up for windows guest always reports sync folder path error, but the folder works

### ISSUE THREAD

**Issue by stolowski** [hashicorp/vagrant#11603]
### Vagrant version

2.2.9

### Host operating system

Mac OS Catalina 10.15.4, VMWare Fusion 11.5.3 (15870345)

### Guest operating system

Windows 10 Pro

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "windows-10-pro"
  config.vm.hostname = "builder"
  config.vm.define "yyy-windows"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "../yyy"

  config.vm.provision "shell", path: "vs-prep.ps1"
  config.vm.provision "shell", path: "meson-prep.ps1"
  config.vm.provision "shell", path: "boost-prep.ps1"
  # increase mem limit for winrm processes (by default 800MB only), otherwise
  # build fails with "fatal error C1060: compiler is out of heap space"
  config.vm.provision "shell", inline: 'Set-Item WSMan:\localhost\Shell\MaxMemoryPerShellMB 8192'

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "8192"
    v.vmx["numvcpus"] = "4"
  end
end

```

### Debug output

https://gist.github.com/stolowski/424b8bc163e11bfea311f4fd375b4ccd

(note, I've replaced some parts of the paths and project name with xxx and yyy for privacy reasons).

### Expected behavior

No error related to synced folder on Windows guest.

### Actual behavior

On 'vagrant up' the box starts, but when mounting the synced folder, an error about a non-existing path is reported. **Sync folder however works fine**, VMWare shared folders are mounted as Z: drive in the guest and work as expected. This happes every time when bringing up the machine.

https://gist.github.com/stolowski/7a305a6c3645fd8aab544008dba69d2a

### Steps to reproduce

1. Windows 10 Pro base box created with https://github.com/Baune8D/packer-win10-basebox (it's a bare Windows 10 Pro with winrm enabled).
2. vagrant up to create the instance and run provisioning, then vagrant halt once succesful.
3. vagrant up

**Comment by briancain** [comment]
Hey there @stolowski - It seems you me that your config is wrong:

```ruby
  config.vm.synced_folder "../yyy"
```

You need a destination for this folder. I'm surprised however that Vagrant didn't throw a validation error, are you sure you didn't leave off the destination by chance when copying your Vagrantfile into GitHub?

Either way, according to the debug log it seems like your destination path ended up being your host folder: `$MountPoint = [System.IO.Path]::GetFullPath("/home/vagrant/go/src/xxx/stolowski/yyy")`. So it seems the error is correct, and I'm guessing your config probably had that folder as the destination path, which does not exist on your guest.

**Comment by stolowski** [comment]
@briancain Thanks for looking into it. You're right, I messed my synced folder definition (although I copied/edited it wrong in this issue report adding to the confusion, I did have destination there, sorry about that). I missed that because - surprisingly - the folder worked in the guest despite this mess-up. Thanks again, the issue solved.
