### ISSUE TITLE
Installed VMware fusion license and plugin not working with 11.5.0

### ISSUE THREAD

**Issue by provenvelocity** [hashicorp/vagrant#11616]
Installed VMware fusion license and plugin not working with 11.5.0

My system works with Virtualbox and my builds all work but a guy we hired uses VMware.... 

### Vagrant version
      Vagrant 2.2.9

### Host operating system
      System Version: macOS 10.14.6 (18G3020)
      Kernel Version: Darwin 18.7.0

### Guest operating system
      never got it running

### Vagrantfile

```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

### Debug output

vagrant plugin license vagrant-vmware-desktop ~/license.lic
Installing license for 'vagrant-vmware-desktop'...
The license for 'vagrant-vmware-desktop' was successfully installed!

desktop plugin 
https://gist.github.com/provenvelocity/5e09093099000f582913651b594297d9

vagrant plugin license vagrant-vmware-fusion ~/license.lic
Installing license for 'vagrant-vmware-fusion'...
The license for 'vagrant-vmware-fusion' was successfully installed!

fusion plugin  
https://gist.github.com/provenvelocity/8703924a6da27cd267808076251181c2

### Expected behavior

The images should spin up in vmware fusion 

### Actual behavior

error

### Steps to reproduce

1. install vagrant
2. install VMware-fusion
3. ins stall VMware utility
3.5 install vmware-desktop plugin
4. add license 
5. run vagrant up --provider=vmware_desktop
6. get: 
Your license to use 'vagrant-vmware-desktop' hasn't been verified in
months. We'll attempt to verify it now. This requires an internet
connection. If the verification fails, you'll need to connect to the
internet. If verification continues to fail, please contact support
at support@hashicorp.com
Verification successful. Please use Vagrant while connected to the
internet from time to time so Vagrant can keep your license verified.
Bringing machine 'iperfServer' up with 'vmware_fusion' provider...
Bringing machine 'agentTargetServer' up with 'vmware_fusion' provider...
You're using a license that doesn't allow you to use the installed
version of Fusion. This error message occurs if you upgraded Fusion
without also upgrading your license. Please upgrade your license to
unlock features and support for the latest version of VMware Fusion,
or revert your version of Fusion back to the supported version.
You can upgrade your license by going to the following URL:

http://license.hashicorp.com/upgrade/vmware

7. uninstall desktop plugin install fusion plugin re license same.... 

vagrant up  --provider=vmware_fusion
Bringing machine 'iperfServer' up with 'vmware_fusion' provider...
Bringing machine 'agentTargetServer' up with 'vmware_fusion' provider...
You're using a license that doesn't allow you to use the installed
version of Fusion. This error message occurs if you upgraded Fusion
without also upgrading your license. Please upgrade your license to
unlock features and support for the latest version of VMware Fusion,
or revert your version of Fusion back to the supported version.
You can upgrade your license by going to the following URL:

http://license.hashicorp.com/upgrade/vmware

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
https://github.com/hashicorp/vagrant/issues/10237
- ...

**Comment by provenvelocity** [comment]
licensed version of fusion also fails...

**Comment by provenvelocity** [comment]
cant install an older version of vmware it is not out for download

**Comment by kikitux** [comment]
Hello

Lets work on the support ticket you did open.

Thanks
Alvaro.
