### ISSUE TITLE
Debian guest -> host sync not happening

### ISSUE THREAD

**Issue by zellerman** [hashicorp/vagrant#11612]
### Vagrant version
Vagrant 2.2.5

### Host operating system
Macos 10.15.3

### Guest operating system
Debian buster 64

### Vagrantfile

```ruby

Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant", type: "rsync", automount: true
  config.vm.provider "virtualbox" do |vb|  
     vb.memory = "1024"
  end
  
  config.vm.define "server" do |s|
    s.vm.box = "debian/buster64"
    s.vm.hostname="server1"
    s.vm.network "private_network", ip: "192.168.50.4"
  end
  config.vm.define "server2" do |s|
    s.vm.box = "debian/buster64"
    s.vm.hostname="server2"
    s.vm.network "private_network", ip: "192.168.50.5"
  end
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt install -y postgresql-server-dev-11 postgresql-11 postgresql-client-11
  SHELL
end
```

### Expected behavior

Files created in the guest under /vagrant should be available on the host.
### Actual behavior

Nothing is visible on the host that is copied to the /vagrant folder regardless `vagrant rsync-auto` is running or not. Works the other way around, i.e. when a new file appears on the host, it is available from the guest as well. 
Bidirectional sync works with ubuntu based images.
 
### Steps to reproduce

1. `vagrant ssh server` then  `cp <anything> /vagrant`
2. the copied file is unavailable from the host

**Comment by briancain** [comment]
Hey there! First, I recommend upgrading to the latest version of Vagrant. Then, please provide us with the full debug log from running `vagrant up --debug` in a [gist](https://gist.github.com/). Thanks!

**Comment by zellerman** [comment]
Hello Here is the gist, after upgrade: https://gist.github.com/zellerman/08e814c744e6333eb187180d5502f230

**Comment by briancain** [comment]
Using that same guest and this Vagrantfile:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder "../", "/vagrant", type: "rsync", automount: true
  config.vm.box = "debian/buster64"

  config.vm.provider :virtualbox
end
```

Rsync worked just fine for me: https://gist.github.com/briancain/defa3e99551ae8c8c1a7fa99562243e6

**Comment by zellerman** [comment]
I've tried the simple Vagrantfile above (except that I'm still syncing '.' instead of '../', as '../' has a broken symlink which bothers rsync) and I still have the issue. After copying the files, they are not visible on the host, at the mounted folder.

**Comment by briancain** [comment]
@zellerman Can you `ls /vagrant` and see the contents after bringing up the guest? Are you just saying that the files exist in `/vagrant` but when you `cp` them else where, `/vagrant` is no longer visible? Can you also show that the files in `/vagrant` actually have content and aren't empty? Thanks!

**Comment by zellerman** [comment]
Acutally, the other way around, I copy things to `/vagrant` inside the vm.
1. I create a file in `/home/vagrant` inside the vm
2. `cp /home/vagrant/bob /vagrant`
3. outside the vm: `ls mountdir` -> `Vagrantfile x-console.log` (should contain `bob`)

After `vargrant reload` the `/vagrant` folder no longer contains `bob`. I can also add, that under Virtualbox->vm settings->shared folders, the mount dir (/Users/zeller/work/kifur/dbpoc) is not listed. 
I switched to ubuntu/bionic64 and the mount is listed in virtualbox AND syncing works in both directions i.e. from guest to host and from host to guest.

**Comment by briancain** [comment]
Hey there @zellerman - Ok I see. This is by design, this is how rsync works. It only syncs folders one way. And when you resync, it overwrites everything in place.

> The rsync synced folder does a one-time one-way sync from the machine running to the machine being started by Vagrant.

https://www.vagrantup.com/docs/synced-folders/rsync.html

You can configure it to not overwrite everything, but it sounds like you also want your files to be available on the host.

If you want to have two way synced folders between your guest and host, I recommend a different synced folder option like the default virtualbox sharefolder type.

Hope that makes sense, thanks!

**Comment by zellerman** [comment]
@briancain I see. Still, why the scenario I outlined works with ubuntu boxes?

**Comment by briancain** [comment]
If you changed boxes and the shared folder was listed in VirtualBox that means it used the virtualbox sharedfolder implementation for syncing folders. That's why it works both directions, because it wasn't rsync.
