### ISSUE TITLE
Invalid mac addresses when using VMWare plugin 

### ISSUE THREAD

**Issue by simon-4c** [hashicorp/vagrant#11611]
We have a couple of private boxes hosted on Vagrant Cloud which run fine on Linux host, using vmware as the provider and the Vagrant VMWare plugin. On Windows, they start but vagrant ssh fails, saying the MAC address provided for `base_mac` is invalid. Looking at the .vmx file for one of the boxes shows the following entries (snippet):

```
ethernet0.pciSlotNumber = "32"
ethernet1.pciSlotNumber = "33"
ethernet0.generatedAddress = "00:0c:29:98:47:26"
ethernet0.generatedAddressOffset = "0"
ethernet1.generatedAddress = "00:0c:29:98:47:30"
ethernet1.generatedAddressOffset = "10"
```
What seems to be happening is that MAC addresses have been generated which Vmware is subsequently unhappy with.

This has only started happening recently. Things of note since then:
1. I had to do a repair install on my Windows machine at the weekend. Since then I have completely removed and reinstalled all of VMWare Workstation Pro, vagrant and all plugins.
2. Vagrant has been up-versioned to 2.2.8

### Vagrant version
2.2.9

### Host operating system
Windows 10 x64

### Guest operating system
Ubuntu 18.04 LTS (based on Hashicorp Bionic image)

### Vagrantfile

```ruby
# script to set up /etc/hosts
$script = <<-SCRIPT
sed -i '/4cng-/d' /etc/hosts
echo '33.33.33.2	4c-backend.local' >> /etc/hosts
echo '33.33.33.3	4c-mysql.local' >> /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|

# general settings

	# suppress vmware warnings
	config.vm.provider "vmware_desktop" do |vmware|
		vmware.whitelist_verified = true
	end

	# mac specific
	if Vagrant.has_plugin?("vagrant-gatling-rsync") 
		config.gatling.latency = 0.2
	end
	
	# nfs-specific
	config.nfs.map_uid = 1000
	config.nfs.map_gid = 1000
  
	# Windows specific
	if Vagrant::Util::Platform.windows? then
		config.winnfsd.uid = 1000
		config.winnfsd.gid = 1000
	end
	
	# Provisioning script
	config.vm.provision "shell", inline: $script
  
	# 4c-backend
	config.vm.define "4c-backend" do |backend|
	  backend.vm.box = "4cplatform/4cngbackend"
	  backend.vm.box_version = "1.0.1"
	  backend.vm.hostname = "4c-backend.local"
	  backend.vm.network "private_network", ip: "33.33.33.2"
	  backend.vm.network "forwarded_port", guest: 8080, host: 8080
	  backend.vm.provider "vmware_desktop" do |v|
		v.vmx["memsize"] = 4096
		v.vmx["numvcpus"] = 2
	  end
	  if ENV['USE_RSYNC'] == 'yes'
		backend.vm.synced_folder File.expand_path("src/4c-backend"), "/home/vagrant/src",
		type: "rsync",
		rsync__chown: true,
		owner: "vagrant",
		group: "vagrant",
		mount_options: ["uid=1000", "gid=1000"],
		rsync__exclude: [
			"Vagrantfile",
			".git/",
			".idea/",
			"node_modules/",
			"vendor/"
		]
	  else
		# NFS
		# mount_options info:
		# rw      : give rw permissions on mount(ed) drive
		# noatime : prevents the modification of the last-updated timestamp on files
		# vers=3  : version of NFS to use (v4 not good on MacOS)
		# udp     : change from tcp(default) to udp because faster
		# actimeo : time in seconds NFS will cache files for
		backend.vm.synced_folder "src/4c-backend", "/home/vagrant/src",
		type: "nfs",
		mount_options: ['rw', 'vers=3', 'udp', 'actimeo=1', 'noatime', 'noacl', 'nolock']
	  end
	end
  
	# 4c-mysql
	config.vm.define "4c-mysql" do |mysql|
	  mysql.vm.box = "4cplatform/4cngmysql"
	  #mysql.vm.box_version = "1.0.0"
	  mysql.vm.hostname = "4c-mysql.local"
	  mysql.vm.network "private_network", ip: "33.33.33.3"
	  mysql.vm.network "forwarded_port", guest: 3306, host: 3306
	  mysql.vm.provider "vmware_desktop" do |v|
		v.vmx["memsize"] = 4096
		v.vmx["numvcpus"] = 2
	  end
	end
end
```

### Debug output
https://gist.github.com/simon-4c/09b263c5439ce27ac222494051af713b

### Expected behavior

Ssh login to box

### Actual behavior

Received this error:
 ```
INFO interface: error: There are errors in the configuration of this machine. Please fix
the following errors and try again:

VMware Desktop Provider:
* The MAC address provided for `base_mac` is invalid.
```

### Steps to reproduce
vagrant ssh machine_name

**Comment by simon-4c** [comment]
Follow-up: I now can't do anything e.g. `vagrant reload` or `vagrant halt` - it gives me the same error.

**Comment by simon-4c** [comment]
Further to this: same error manifests itself when using the hashicorp Bionic base box

**Comment by simon-4c** [comment]
Commenting again - I finally resolved this by cleaning every trace of vmware or vagrant stuff from my machine, using a reg cleaner to remove orphan entries, rebooting and reinstalling

**Comment by simon-4c** [comment]
Closed because I thought the issue had gone away but it hadn't, I'd left a base_mac setting in the Vagrantfile to test and forgot to remove it. When I remove it it comes back.

**Comment by simon-4c** [comment]
Anyone?
I've raised a ticket with hashicorp too and absolutely zero response.

We are very disappointed with the lack of stability of Vagrant on VMWare and the lack of support from anyone. We were led to believe the vmware plugin was a stable product and we feel like we've wasted our money here. Currently breaking our dev environment.

**Comment by kikitux** [comment]
Working on the support ticket open
