### ISSUE TITLE
VBoxGuestAdditions.iso upload randomly fails

### ISSUE THREAD

**Issue by samy** [hashicorp/vagrant#11627]
### Vagrant version

2.2.9

### Host operating system

Windows 10

### Guest operating system

Linux (debian/stretch64)

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# VARIABLES TO CONFIGURE
GUEST_USER_NAME = "###"
GUEST_USER_PRIVATE_KEY_SOURCE = "###"
GUEST_USER_PUBLIC_KEY_SOURCE = "###"

# VARIABLES TO CONFIGURE AT YOU OWN RISK
GUEST_OS = "debian/stretch64"
GUEST_IP = "192.168.42.13"
GUEST_VM_NAME = "######"
GUEST_VM_MEMORY = "4096"
GUEST_VM_CPUS = "4"

# Required plugins installation
required_plugins = %w(vagrant-winnfsd vagrant-vbguest vagrant-fsnotify)
plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

# Vagrant configure
Vagrant.configure("2") do |config|
  config.vm.box = GUEST_OS
  config.vm.hostname = GUEST_VM_NAME
  config.vm.synced_folder "code", "/var/www/html/", type: "nfs", fsnotify: true
  config.vm.provider "virtualbox" do |v|
    v.memory = GUEST_VM_MEMORY
    v.cpus = GUEST_VM_CPUS
    v.name = GUEST_VM_NAME
  end
  
  # SHELL
  config.vm.provision "file", source: GUEST_USER_PRIVATE_KEY_SOURCE, destination: "/home/vagrant/id_rsa"
  config.vm.provision "file", source: GUEST_USER_PUBLIC_KEY_SOURCE, destination: "/home/vagrant/id_rsa.pub"
  config.vm.provision :shell, :path => "./common_bootstrap.sh", :args => [GUEST_USER_NAME]

  # Network
  config.vm.network "private_network", ip: GUEST_IP
end

```

### Debug output

Debug log : https://gist.github.com/samy/0891f6538093316d907ecb3b7af093f0#file-debug-log

### Expected behavior

The `vagrant up` command should not fail and the VM should start.

### Actual behavior

The VM doesn't not start (fails on VBoxGuestAdditions.iso upload and shutdowns)

Note : sometimes it works, after 3 or 4 cycles `vagrant destroy -f && vagrant up`.
The same VM starts on the other computers of my team without any problem, with same version

Tests I made and result :
- changing my Ethernet network from "Public" to "Private" in Windows Network and Sharing Center : 👎
- downgrading *vagrant-vbguest* to older versions (0.21 and 0.23) 👎 
- making free space on my hard drive (70GB left) 👎 
- installing plugins as local (using _config.vagrant.plugins_) 👎 
- downgrading Virtualbox to 6.1.4 and 6.1.6 👎 

### Steps to reproduce

1. Fill the Vagrantfile with a random username and an existing SSH key path
2. Copy the provided [*common_bootstrap.sh*](https://gist.github.com/samy/0891f6538093316d907ecb3b7af093f0#file-common_bootstrap-sh) in the same folder
3. Use `vagrant up` command in the folder

### References

No referefence

**Comment by briancain** [comment]
Hey there @samy - This seems to be an issue with the plugin you are using to install virtualbox guest additions: https://github.com/dotless-de/vagrant-vbguest/issues/372

When you get the error, I would look at the logs inside your debian guest to see if there's anything that could tel you why it failed. From the error you received, it seems like it's likely an issue with the guest connection which is what made net-ssh fail and disconnect.
