### ISSUE TITLE
WSL vagrant up hangs on SSH auth private key step

### ISSUE THREAD

**Issue by ziadoz** [hashicorp/vagrant#11626]
# Vagrant version

2.2.9 on Windows 10
2.2.9 on WSL Ubuntu 20.04
VirtualBox 6.1.8

### Host operating system

Windows 10 Home 1909
WSL Ubuntu 20.04 LTS

### Guest operating system

Ubuntu 18.04 LTS

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
  end
end
```

### Debug output

https://gist.github.com/ziadoz/dc1100928190eeaa3cf6d78a4175751b#file-vagrant_up_output-txt
https://gist.github.com/ziadoz/dc1100928190eeaa3cf6d78a4175751b#file-vboxhardening-log

### Expected behavior

The virtual machine should up.

### Actual behavior

Running `vagrant up` hangs at the SSH auth private key step and the VM becomes unresponsive and ultimately needs killing via the task manager.

### Steps to reproduce

1. Run `bash` from Windows Terminal.
2. Run `vagrant up` from inside WSL.

My `.bashrc` file is configured with these env vars: 
```
export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
export VAGRANT_WSL_WINDOWS_ACCESS_USER_HOME_PATH="/mnt/d/Code"
export PATH="${PATH}:/mnt/c/Program Files/Oracle/VirtualBox"
```

The `Vagrantfile` is located in `/mnt/d/Code/vm`.

**Comment by sus1ov** [comment]
This happened with my Ubuntu 19.10 too. 
This line has stopped working
  `v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]`
I removed it ,but logs go in the folder that I don't want.

**Comment by ziadoz** [comment]
@sus1ov If I comment out that line in the `Vagrantfile` I get an error when Vagrant tries to write the log: `Stderr: VBoxManage: error: RawFile#0 failed to create the raw output file: ... VERR_FILE_NOT_FOUND`.

**Comment by ziadoz** [comment]
I actually think this might be related to this issue: https://github.com/hashicorp/vagrant/issues/10578#issuecomment-459081990 As when I use a Bento box it ups without any problems.

**Comment by Miosss** [comment]
I experience the same issue.
After upgrading Vagrant from 2.2.7 to 2.2.9 and upgrading VirtualBox to 6.1.8 (from 6.1.2 I think), `ubuntu/bionic-64` stopped working. `bento/ubuntu-18.04` works just fine

The ubuntu box hangs during boot, even when started from VirtualBox - the VBox GUI hangs during booting the machine. The box process has to be killed for the entire GUI to unfreeze.

Chaning boxes is not ideal solution, especialy from the ubuntu official releases.

It seems safer for now not to upgrade vagrant at all, as every release breaks something (2.2.7 was incompatible with vbox 6.1 just beacause of explicit assert).
