### ISSUE TITLE
Vagrant OSX 2.2.9 issue: invalid mask 0.0.0.24 (IPAddr::InvalidPrefixError)

### ISSUE THREAD

**Issue by flavio-fernandes** [hashicorp/vagrant#11636]
### Vagrant version

$ vagrant version
Installed Version: 2.2.9
Latest Version: 2.2.9

Also broken on 2.2.8

### Host operating system

OS-X
macOS Catalina Version 10.15.4

### Guest operating system

It does not matter

### Vagrantfile

https://github.com/flavio-fernandes/mqtt2cmd/blob/96db9fc96d52f2949a23eb21b3cb44c0c313d2ff/Vagrantfile

```ruby
# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version.
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">=1.7.0"

Vagrant.configure(2) do |config|
    config.vm.hostname = "foo"
    config.vm.box = "centos/7"
    config.vm.network 'private_network', ip: "192.168.123.123"
end
```

### Debug output

https://gist.github.com/flavio-fernandes/54efab0832c011621e3e1cc1fe1d4740

https://gist.github.com/flavio-fernandes/ca8872fecdc72f0aa03e6ca5df507306

### Expected behavior

```shell
from /opt/vagrant/embedded/lib/ruby/2.6.0/ipaddr.rb:161:in `mask'
/opt/vagrant/embedded/lib/ruby/2.6.0/ipaddr.rb:509:in `mask!': invalid mask 0.0.0.24 (IPAddr::InvalidPrefixError)
```

Should be able to handle default mask value.

What should have happened?

It should have worked, as it does on version 2.2.7

### Actual behavior

What actually happened?

### Steps to reproduce

on osx system

git clone https://github.com/flavio-fernandes/mqtt2cmd.git && \
cd mqtt2cmd && vagrant up

### References

broken in osx only?
works fine on libvirt provider

**Comment by chrisroberts** [comment]
Thanks for reporting this issue. There appears to be an issue with the netmask value that's being read from VirtualBox. The version of Ruby used prior to the 2.2.8 release did not have any issue accepting the value. On the newer versions of Ruby, it is now throwing this error. We'll need to add a bit of value sanitizing on the netmask value in the VirtualBox driver to resolve this.

**Comment by flavio-fernandes** [comment]
> Thanks for reporting this issue. There appears to be an issue with the netmask value that's being read from VirtualBox. The version of Ruby used prior to the 2.2.8 release did not have any issue accepting the value. On the newer versions of Ruby, it is now throwing this error. We'll need to add a bit of value sanitizing on the netmask value in the VirtualBox driver to resolve this.

Glad to help. Shame ci/cd did not catch that...
