### ISSUE TITLE
vagrant and virtualbox can't play with each other on mac os x catalina

### ISSUE THREAD

**Issue by kundeng** [hashicorp/vagrant#11639]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use
HashiCorp Discuss: https://discuss.hashicorp.com/c/vagrant/24 Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version

Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
2.2.9
### Host operating system
mac os x
This is the operating system that you run locally.

### Guest operating system
centos 7.4
This is the operating system you run in the virtual machine.

### Vagrantfile
Not specific to any vagrantfile

### Expected behavior

What should have happened?

### Actual behavior
It can't seem to control virtualbox or virtualbox can't seem to make changes

 bringing machine 'c7401' up with 'virtualbox' provider...
==> c7401: Checking if box 'bento/centos-7.4' version '201803.24.0' is up to date...
==> c7401: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: Permission denied
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
What actually happened?

### Steps to reproduce

1.
2.
3.

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by briancain** [comment]
Hey there @kundeng - You need to give VirtualBox on your Mac security permissions. This link seems to be the issue you are running into: https://stackoverflow.com/a/21363356

> Go to System Preferences > Security & Privacy Then hit the "Allow" button to let Oracle (VirtualBox) load.

**Comment by kundeng** [comment]
Hi, the issue is that Oracle Virtualbox is not shown as System Preferenes->security & privacy. 

I had to restart the mac and then remove and  reinstall virtualbox a couple of times to get it to work.  

This issue has been around with virtualbox, which is very annoying,  here are a few things that people can try:

0.  restart virtualbox;
sudo /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart
1.  restart mac; 

2.  completely remove and reinstall virtualbox;

3.  make sure virtualbox net kernel is loaded properly; 

4.  make sure virtualbox is given the permission in system preferences;
sudo chown -R  root:admin  /Applications/VirtualBox.app

5.  make sure /app folder has the right permission.

**Comment by briancain** [comment]
OK! Well gad you were able to figure out the permissions for VirtualBox! I'm going to go ahead and close this.
