### ISSUE TITLE
New Vagrant users can't easily verify their downloads ( just need a 5 character fix )

### ISSUE THREAD

**Issue by wwalker** [hashicorp/vagrant#11638]
New users of Vagrant cannot easily verify their download of Vagrant because the link to Hashicorp's GPG Key page on the Vagrant Download page is broken.

On the page "Download - Vagrant by Hashicorp" ( https://www.vagrantup.com/downloads.html ) There is a link to get the Hashicorp GPG key "HashiCorp's GPG key" that is broken.

That link points to ( https://www.hashicorp.com/security.html ) which generates a "Page Not Found" , 404 page.

That page has moved from:

https://www.hashicorp.com/security.html

To:

https://www.hashicorp.com/security

**Comment by briancain** [comment]
Thanks for the report @wwalker - This has been fixed via the recent website refresh. Cheers!
