### ISSUE TITLE
Shell provisioner: Change double-quoted values of environment variables to single-quotes (2)

### ISSUE THREAD

**Issue by simplytech** [hashicorp/vagrant#11646]
In reference to:

https://github.com/hashicorp/vagrant/pull/11538#issuecomment-618023469_

sorry I forgot to mention the most obvious point, which is that the password is not specified in a script - it is actually retrieved from another program, e.g. lastpass CLI, therefore your suggestion to escape the $ does not work. It is impossible to know what a password might contain, so it is quite difficult to write a filter that escapes characters that might be interpreted by the shell.

In order not to break other people's code who rely on the shell expansion, would you consider making this optional? For example, the shell provisioner could take a boolean option called 'single_quoted' which defaults to false. If set to true, Vagrant will not handle quoting for the environment variables.

**Comment by chrisroberts** [comment]
Hi there,

I don't think that any new option needs to be provided for this. If you are receiving the value via some automated method, then you can easily sanitize the value in your Vagrantfile which will give you the desired behavior. For example, lets say when I run my vagrant command an environment variable is automagically created for me which contains a service password. For this example we can just call it `SERVICE_EXAMPLE`. In my Vagrantfile, I can simply sanitize the value when I set it for my provisioner:

```ruby
require "shellwords"

Vagrant.configure("2") do |config|
  config.vm.provision :shell, path: "./script.sh", env: {
    MY_PASSWORD: Shellwords.escape(ENV["SERVICE_EXAMPLE"]) 
  }
end
```

This uses a library in Ruby's stdlib to escape any special characters which may be included in your string, and thus will prevent special characters from being interpreted. While we are using an environment variable for this example, the string value can be acquired in any valid way. It's just the `Shellwords.escape` part that's important.

Hope that helps.

Cheers!
