### ISSUE TITLE
Port forwarding to loopback addresses no longer works

### ISSUE THREAD

**Issue by hieberst** [hashicorp/vagrant#11640]
### Vagrant version:

Vagrant 2.2.9

### Host operating system

Microsoft Windows 10 Version 1803

### Guest operating system

Linux

### Vagrantfile

```ruby
Vagrant.configure(2) do |config|
    config.vm.hostname = "bionic64"
    config.vm.box = "hashicorp/bionic64"
    config.vm.network "forwarded_port", id: "ssh2", guest: 22, host: 22, host_ip: "127.1.2.40"
end
```

### Expected behavior
```
==> default: Forwarding ports...                                                       
    default: 22 (guest) => 22 (host) (adapter 1)                                       
    default: 22 (guest) => 2222 (host) (adapter 1)                                     
```

The machine should be reachable via SSH on the loopback address 127.1.2.40.

### Actual behavior

```
You are trying to forward a host IP that does not exist. Please set `host_ip`
to the address of an existing IPv4 network interface, or remove the option
from your port forward configuration.

VM: default
Host IP: 127.1.2.40
```

The machine fails to start.

### Steps to reproduce

``vagrant up``

### Proposal

The method ``HandleForwardedPortCollisions::port_check()`` in [handle_forwarded_port_collisions.rb](https://github.com/hashicorp/vagrant/blob/dfad00f/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb) should include a check if the given IPv4 address is a loopback address by calling ``Addrinfo#ipv4_loopback?``

Instead of 

```ruby
if test_host_ip == "0.0.0.0" || ipv4_interfaces.detect { |iface| iface[1] == test_host_ip }
```

I propose to do something like

```ruby
if test_host_ip == "0.0.0.0" || Addrinfo.ip(test_host_ip).ipv4_loopback? || ipv4_interfaces.detect { |iface| iface[1] == test_host_ip }
```

**Comment by jbonhag** [comment]
Hi @hieberst,

Thanks so much for reporting the issue! Sorry you ran into this. I just pushed up a commit with your proposed change and it's working great.
