### ISSUE TITLE
NFS share fails due to fragile connection between host and guest

### ISSUE THREAD

**Issue by scottrigby** [hashicorp/vagrant#1165]
When using Vagrant, Puppet, and Virtualbox - several of our team members are experiencing an unpredictable connection between the host and guest. NFS mounting does not work until this connection is made, which is why we looked into this problem in the first place. So far have not been able to find reliable steps to reproduce the problem.

Everything else - including `vagrant ssh` - works perfectly. But pinging from host to guest or vice versa will fail and resume intermittently. We do not seem to have this issue on non-vagrant boxes.

**Comment by Artistan** [comment]
similar Mac OSX issue here. with Sierra, 
VirtualBox 5.1.6
Vagrant 1.8.6
trying to do an nfs share.

I ended up destroying the box.
starting to PING the NON-EXISTANT box
vargant up on that box (new) .... while still pinging.
this somehow allowed the server to complete the nfs share while being provisioned.

hope this helps someone else.
