### ISSUE TITLE
Upgrade to Vagrant 2.2.9 breaks vmware-workstation plugin

### ISSUE THREAD

**Issue by nuxy** [hashicorp/vagrant#11653]
### Vagrant version

```
$ vagrant -v
Vagrant 2.2.9
```

### Host operating system

Ubuntu 16.04 (x86_64) 

### Guest operating system

VMware® Workstation 12 Pro with licensed plug-in

### Vagrantfile

On fresh install the following commands result with an error:
```
$ vagrant init
$ vagrant plugin install vagrant-vmware-workstation
$ vagrant up

Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- vagrant/vmware/workstation
```
### Debug output

https://gist.github.com/nuxy/3dc7994ddd0a99e92abf73d24755990e

### Expected behavior

The plug-in should be loaded without errors.

**Comment by nuxy** [comment]
### Additional info

```
$ gem list

*** LOCAL GEMS ***

ast (2.4.0)
bigdecimal (1.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
jaro_winkler (1.5.4)
json (2.3.0, 1.8.3)
minitest (5.14.0, 5.8.4)
net-telnet (0.2.0, 0.1.1)
parallel (1.19.1)
parser (2.7.0.4)
power_assert (1.1.6, 0.2.7)
psych (3.1.0, 2.0.17)
rainbow (3.0.0)
rake (13.0.1, 10.5.0)
rdoc (4.2.1)
rexml (3.2.4)
rubocop (0.80.1)
ruby-progressbar (1.10.1)
test-unit (3.3.5, 3.1.7)
unicode-display_width (1.7.0, 1.6.1)
```

**Comment by nuxy** [comment]
Looking into this further my suspicion is that something has either changed with the licensing server or the `vagrant-vmware-workstation` gem is not remotely accessible (and no, I'm not behind a proxy).

I have confirmed this by installing an older release (1.9.8) and attempting an upgrade path back to 2.2.7 (which was working prior to the 2.2.9 update).

```
$ vagrant plugin repair
Repairing currently installed plugins. This may take a few minutes...
Fetching: vagrant-hostmanager-1.8.9.gem (100%)
Fetching: vagrant-share-1.1.10.gem (100%)
Fetching: micromachine-3.0.0.gem (100%)
Fetching: vagrant-vbguest-0.24.0.gem (100%)
Fetching: vagrant-vmware-workstation-0.0.1.gem (100%)
Thank you for installing the Vagrant VMware Workstation gem. This
is a placeholder gem for the RubyGems server. The real gem is in
the HashiCorp gem servers. For more information, please visit
the page below.

  https://www.vagrantup.com/vmware
Installed plugins successfully repaired!
```

At this point, I would say the issue is partly resolved (it works with an old version) but what I really want is clarification as to why the version I had installed before no longer works.  If this is a licensing issue proper messaging that indicates this would have save several hours of debugging.

**Comment by briancain** [comment]
Hi @nuxy - You should be installing `vagrant-vmware-desktop`:

```
vagrant plugin install vagrant-vmware-desktop
```

The plugin has been renamed a couple of years ago...so the error you recieved is accurate. Those files no longer exist in the latest versions of that plugin:

```
 INFO manager: Loading plugin `vagrant-vmware-workstation` with default require: `vagrant-vmware-workstation`
ERROR manager: Failed to load plugin `vagrant-vmware-workstation` with default require. - LoadError: cannot load such file -- vagrant-vmware-workstation
 INFO manager: Loading plugin `vagrant-vmware-workstation` with slash require: `vagrant/vmware/workstation`
ERROR manager: Plugin loading error: LoadError - cannot load such file -- vagrant/vmware/workstation
```

I recommend checking out the installation guide, because there's more than just a gem to install now with the vmware provider: https://www.vagrantup.com/docs/vmware/installation.html

Thanks!
