### ISSUE TITLE
Vagrant guest showing incorrect incoming IP from host

### ISSUE THREAD

**Issue by simon-4c** [hashicorp/vagrant#11652]
### Vagrant version

2.2.9

### Host operating system

Windows 10

### Guest operating system

Ubuntu 18.04

My vagrant VM is assigned an IP address of 192.168.42.128 (via the default NAT on eth0 - I've not specified any network config in my Vagrantfile). When I use `vagrant ssh` to enter the VM, it shows me coming in from 192.168.42.2. Likewise, if I enable PHP Xdebug, the log shows the incoming request comes from 192.168.42.2:9000.

The problem here is my host isn't 192.168.42.2 - it's 192.168.42.1. A call to `nc -zv 192.168.42.1 9000` shows a bound port. Because somehow the incoming IP is wrong, the convenient 'connect to caller' config for xdebug fails. It works if I hard-code the remote IP to 192.168.42.1, but I can't do that as multiple people use the vagrantfile and the IP address may be different for them.

So here's my question - why is the incoming connection from the host showing as coming from the wrong IP? Even the documentation says the host is .1 on the IP range.

**Comment by simon-4c** [comment]
By the way, the provider is VMWare.

**Comment by briancain** [comment]
Hi @simon-4c - When you open an issue on github, there are certain fields we ask users to fill out so that we have the full picture of what's going on. Please provide us with a minimally reproducible Vagrantfile, as well as a full debug log from bringing up the two VMs with the `--debug` flag included. And also please include the vagrant provider and box that you are using as well. Thanks!

**Comment by simon-4c** [comment]
Hi

Sorry but nobody replied in over a month and we had to find a different way to get this working  so we ended up generating the host IP by taking the first three parts of the IP and adding a 1. The VMware implementation of vagrant seems much less stable than the virtualbox one, which is disappointing given that it's a paid product.

**Comment by briancain** [comment]
Hi @simon-4c - Alright. I'm going to go ahead and close this issue then. Sorry we didn't get back to you sooner. Without any debug logs it's hard to say what's actually going on. Unfortunately a lot of the instability and frustrating user experience with networking and VMWare is a fault with VMWare. There's not much Vagrant can do about that considering Vagrant is just a layer on top of that.
