### ISSUE TITLE
vagrant add box jasonc/centos7 is not helping. giving error like below.

### ISSUE THREAD

**Issue by vidyaau** [hashicorp/vagrant#11658]
vagrant up --provider virtualbox

Bringing machine 'default' up with 'virtualbox' provider...

==> default: Box 'centos/7' could not be found. Attempting to find and install...

       default: Box Provider: virtualbox

       default: Box Version: >= 0
==> default: Loading metadata for box 'centos/7'

    default: URL: https://vagrantcloud.com/centos/7

==> default: Adding box 'centos/7' (v1905.1) for provider: virtualbox

    default: Downloading: https://vagrantcloud.com/centos/boxes/7/versions/1905.1/providers/virtualbox.box

==> default: Box download is resuming from prior download progress

    default: Download redirected to host: cloud.centos.org

    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 416

**Comment by jbonhag** [comment]
Hey there,

The CentOS boxes are hosted externally on cloud.centos.org. Is there a chance that a proxy server is preventing the download? Could you please see if you're able to download the box file directly from the following link:

https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1905_01.VirtualBox.box

Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue with centos directly, as Vagrant does not host or manage that box.Thanks!
