### ISSUE TITLE
Vagrant Init Fails for Open-Source PowerShell 7

### ISSUE THREAD

**Issue by MBetters** [hashicorp/vagrant#11651]
### Vagrant version

2.2.9

### Host operating system

Win10

### Guest operating system

Ubuntu 20.04

### Vagrantfile

N/A

### Debug output

https://gist.github.com/MBetters/3250de58a8493ac536409c24b90bb273

### Expected behavior

Create a Vagrantfile with `ubuntu_base` as the base box.

### Actual behavior

See end of gist:

```
...
Vagrant failed to initialize at a very early stage:

The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: N/A
  Minimum required version: 3
```

### Steps to reproduce

1. Get latest PowerShell 7 from https://github.com/PowerShell/PowerShell/releases
2. cd into empty folder
3. `vagrant init ubuntu_base`

### References

N/A

**Comment by briancain** [comment]
Hey @MBetters - A couple of questions for you:

What is the result of running the Powershell command below?

```powershell
Write-Output $PSVersionTable.PSVersion.Major
```

Also, if you increase the timeout for detecting the Powershell version, does that work? https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_powershell_version_detection_timeout

**Comment by MBetters** [comment]
```
PS C:\Users\Mbetters> Write-Output $PSVersionTable.PSVersion.Major
7
```

This succeeded in creating a Vagrantfile:

```
PS C:\> $Env:VAGRANT_POWERSHELL_VERSION_DETECTION_TIMEOUT=99999999
PS C:\> vagrant init --debug ubuntu_base > d.txt
```

https://gist.github.com/MBetters/351c2a9cd302f8d08f1c2213695fc679

**Comment by briancain** [comment]
OK! Thanks @MBetters . You shouldn't need to set the timeout to be quite so long, but I'm glad that worked. Sometimes the check is slow on peoples computers, and that's why the timeout is there. I'll go ahead and close this, since it seems like adjusting the timeout worked for you! Thanks.

**Comment by MBetters** [comment]
Sounds good, thanks!
