### ISSUE TITLE
Vagrant on Fedora 31 requires 'net-ssh' (~> 5.1.0) and fails on never version: net-ssh-5.2.0

### ISSUE THREAD

**Issue by elkoniu** [hashicorp/vagrant#11663]
### Vagrant version
Vagrant 2.2.6

### Host operating system
Fedora release 31 (Thirty One)
Linux chopper 5.6.13-200.fc31.x86_64 #1 SMP Thu May 14 23:26:14 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Debug output
https://gist.github.com/elkoniu/ba74f7e71d5d2239455f67a18d9268a6

### Expected behavior
Vagrant should show default help screen

### Actual behavior
Vagrant is complaining about net-ssh version installed in system.

### Steps to reproduce
$ dnf update
$ vagrant
DNF update will install latest version of rubygem-net-ssh which in case of Fedora 31 is version rubygem-net-ssh-5.2.0
After manually downgrading rubygem-net-ssh to rubygem-net-ssh-5.1.0 vagrant is working fine.

**Comment by chrisroberts** [comment]
Hi there. The package you installed is not something which we generate / control and are unable to resolve this issue. You'll need to contact that package maintainer (https://src.fedoraproject.org/rpms/vagrant) to resolve the issue.

Cheers!
