### ISSUE TITLE
Enhancement Request: Add env variable to support Hyperv share folder authentification

### ISSUE THREAD

**Issue by survivant** [hashicorp/vagrant#11675]
I have to create multiple VMs with a VagrantFile.  But I can't automatize the process because I have to enter my credentials for the share drive each time.  

I could bypass that if we have a env variable that could be use by Vagrant to pass the user/password.

**Comment by briancain** [comment]
Hey there @survivant - based on your description, it sounds like you are probably using SMB synced folders. You can define the username and password in your Vagrantfile, you don't need an environment variable. I recommend reading the docs here! https://www.vagrantup.com/docs/synced-folders/smb#options Thanks.

**Comment by survivant** [comment]
but my concern was that in a company we will use the same project and our crendentials won't be in that file but someone could commit the modify file by error and it will be a security issue.  It could be good to have a variable as place holder

**Comment by briancain** [comment]
@survivant - I recommend updating your Vagrantfile to read in a json or yaml file of credentials from disk and use those as values for the username/password config options. Then your team can write down their own file, and you won't have to worry about sharing passwords.
