### ISSUE TITLE
Enhancement Request: Add command : create

### ISSUE THREAD

**Issue by survivant** [hashicorp/vagrant#11674]
Sometime Vagrant is not able to configure the VM because some functionnalities are not implemented.

I'll like to have a command : create.

That command will create the VM without provisionning and quit after the create.

that will allow me to create a VM and run a script to update the VM :  ex : VBManage, some script for Vmware or powershell for HyperV.

after that I could relaunch the VM and go with the provisionning

**Comment by soapy1** [comment]
Vagrant supports bringing up a machine without provisioning. This is done using the [`--no-provision` option](https://www.vagrantup.com/docs/cli/up#no-provision). If you are in particular interested in having a `vagrant create` command, you might find aliases interesting as well https://www.vagrantup.com/docs/cli/aliases.html.

**Comment by survivant** [comment]
I use a blank vagrant file  with vagrant init generic/ubuntu1804

but the command doesn't quit.   I can connect by ssh in the VM or by Connect In hyperv manager.  

until the process exit, I can't continue with my scripts.

Windows 10

```
PS C:\test> vagrant up --no-provision
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
==> default: Importing a Hyper-V instance
    default: Creating and registering the VM...
    default: Successfully imported VM
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) Default Switch
    default: 2) packer-hyperv-iso
    default:
    default: What switch would you like to use? 2
    default: Configuring the VM...
==> default: Starting the machine...
==> default: Waiting for the machine to report its IP address...
    default: Timeout: 120 seconds
    default: IP: 172.18.40.119
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 172.18.40.119:22
    default: SSH username: vagrant
    default: SSH auth method: private key
```

**Comment by soapy1** [comment]
Part of the `vagrant up` process is to set sync folders and networks specified in the Vagrantfile. In order to do this, Vagrant must establish a connection with the guest. Once that is done the process will exit.
