### ISSUE TITLE
vagrant snapshot in the latest version 2.2.9  is completely broken

### ISSUE THREAD

**Issue by kundeng** [hashicorp/vagrant#11671]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use
HashiCorp Discuss: https://discuss.hashicorp.com/c/vagrant/24 Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version

Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
2.2.9
### Host operating system
Linux 
This is the operating system that you run locally.

### Guest operating system
linux
This is the operating system you run in the virtual machine.

What actually happened?
vagrant snapshot gives complete different options than older version, and it doesn't work

$ vagrant snapshot save abc
Usage: vagrant snapshot <command> [<args>]

Available subcommands:
     back
     delete
     go
     list
     take

For help on any individual command run `vagrant snapshot <command> -h`
        --[no-]color                 Enable or disable color output
        --machine-readable           Enable machine readable output
    -v, --version                    Display Vagrant version
        --debug                      Enable debug output
        --timestamp                  Enable timestamps on log output
        --debug-timestamp            Enable debug output with timestamps
        --no-tty                     Enable non-interactive output

The old/normal vagrant snapshot commands include save and restore and they don't work

### Steps to reproduce

1. 
$ vagrant snapshot take abc
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Snapshot taken. UUID: b7be0523-b2e3-464a-a560-048498a4e9d9
VBoxManage: error: Could not find a registered machine named 'take'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(bstrMachine.raw(), pMachine.asOutParam())" at line 333 of file VBoxManageSnapshot.cpp

**Comment by briancain** [comment]
Hey there @kundeng - It looks like you're using the plugin listed here: https://github.com/dergachev/vagrant-vbox-snapshot

Vagrant has its own built in snapshot command, and `take` is not a valid command:

https://www.vagrantup.com/docs/cli/snapshot.html

Removing that plugin and using the built in snapshot command should solve your problem! Thanks.

**Comment by kundeng** [comment]
That's strange. I ran 
vagrant plugin list

>No plugins installed.
