### ISSUE TITLE
Enhancement Request: choose input file

### ISSUE THREAD

**Issue by survivant** [hashicorp/vagrant#11680]
I have a issue configuring multiple VM with hyperV because of the MAC address.  Hyperv assign the same MAC to all VM that I create using bridge.

to fix that I want to create separate vagrantFile by VM and run a script to change the MAC address in the VM within powershell.

I which I could have sometime like  : 
vagrant up --no-provision -f vagrantMaster
vagrant up --no-provision -f vagrantNode1
vagrant up --no-provision -f vagrantNode2

where vagrantXXX are separate files.

like docker.  it will use the default Dockerfile, but we can choose a different file from command line

**Comment by chrisroberts** [comment]
Hi there,

The Hyper-V provider can modify the MAC address for multiple guests within the same Vagrantfile. For example:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "example-box"
  config.vm.define "guest1" do |c|
    c.vm.provider :hyperv do |p|
      p.mac = "XX:XX:XX:XX:XX:XX"
    end
  end
  config.vm.define "guest2" do |c|
    c.vm.provider :hyperv do |p|
      p.mac = "YY:YY:YY:YY:YY:YY"
    end
  end
end
```

You can find this option in the provider specific configuration for the Hyper-V provider here: https://www.vagrantup.com/docs/providers/hyperv/configuration#mac

Cheers!

**Comment by survivant** [comment]
the feature is still requested.
