### ISSUE TITLE
 Guest Additions Version doesn't match VirtualBox version

### ISSUE THREAD

**Issue by survivant** [hashicorp/vagrant#11685]
I did a vagrant init generic/ubuntu1804

vagrant up  and I obtain this error message with a big stacktrace.  

I also did a vagrant plugin update... I always end up this a error.

Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
==> master: Checking for guest additions in VM...
    master: The guest additions on this VM do not match the installed version of
    master: VirtualBox! In most cases this is fine, but in rare cases it can
    master: prevent things such as shared folders from working properly. If you see
    master: shared folder errors, please make sure the guest additions within the
    master: virtual machine match the version of VirtualBox you have installed on
    master: your host and reload your VM.
    master:
    master: Guest Additions Version: 5.2.34
    master: VirtualBox Version: 6.1
==> master: Forcing shutdown of VM...
==> master: Destroying VM and associated drives...

Vagrant 2.2.9

virtualbox 6.1.8 (latest version)
Windows 10

**Comment by briancain** [comment]
Hey @survivant - This is not a Vagrant error or bug. It's just a warning saying guest additions don't match the version of VirtualBox that you are using. I'm going to go ahead and close this.

**Comment by survivant** [comment]
but I have a error in console (python error).  and why the guest addition is not overidden with the version that I have locally ?

**Comment by briancain** [comment]
@survivant  Vagrant doesn't manage guest additions. Again, it's not an error. It's just a warning.
