### ISSUE TITLE
Vagrant 2.2.9 - GuestAdditions seems to be installed (6.1.10) correctly, but not running.

### ISSUE THREAD

**Issue by queglay** [hashicorp/vagrant#11683]
### Vagrant version
2.2.9

### Host operating system

Centos 7

### Guest operating system

Centos 7

### Vagrantfile

```ruby
# https://codingbee.net/vagrant/vagrant-enabling-a-centos-vms-gui-mode

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.disk :disk, size: "100GB", primary: true
    
    config.vagrant.plugins = ['vagrant-vbguest', 'vagrant-reload']
    config.vm.provider "virtualbox" do |v|
        v.gui = true
        v.memory = 2048
        v.cpus = 2
    end
    config.vm.network "public_network", use_dhcp_assigned_default_route: true
    config.vm.provision "shell", inline: "sudo yum groupinstall -y 'gnome desktop'"
    config.vm.provision "shell", inline: "sudo yum install -y 'xorg*'"
    config.vm.provision "shell", inline: "sudo yum remove -y initial-setup initial-setup-gui"
    config.vm.provision "shell", inline: "sudo systemctl isolate graphical.target"
    config.vm.provision "shell", inline: "sudo systemctl set-default graphical.target"
    config.vm.provision :reload
end

```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output

https://gist.github.com/queglay/07d107ad07dd03f15729a86bb4333318

### Expected behavior

Vagrant up should not produce errors with guest additions and disk size should be correct.

### Actual behavior

Vagrant up will not produce a box without errors relating to Guest Additions, and the disk size will not be correct.  No guest editions problems were present in vagrant 2.2.7

### Steps to reproduce
Vagrant up.

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by briancain** [comment]
Hey there @queglay - This to me looks like a bug in the vagrant-vbguest plugin. Or maybe at least a case it doesn't handle. It looks to be wanting you to run a certain command on the guest:

```
Stdout from the command:

VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel 
modules.  This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Kernel headers not found for target kernel 
3.10.0-1127.10.1.el7.x86_64. Please install them and execute
  /sbin/rcvboxadd setup


Stderr from the command:

modprobe vboxguest failed
The log file /var/log/vboxadd-setup.log may contain further information.
```

Vagrant doesn't manage guest additions, so it's not something we can fix here. It might be worth opening an issue with the plugin maintainer. Thanks!
