### ISSUE TITLE
Ansible is being run in a world writable directory (/vagrant), ignoring it as an ansible.cfg source

### ISSUE THREAD

**Issue by abhishekkarigar** [hashicorp/vagrant#11707]
### Vagrant version

Vagrant 2.2.9

### Host operating system

windows 10  ( + cygwin )

### Guest operating system

ubuntu/trusty64

### Vagrantfile

    Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.synced_folder ".", "/vagrant"
        config.vm.provision "ansible_local" do |ansible|
          ansible.become = true
          ansible.playbook = "playbook.yml"
          ansible.inventory_path = ".vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"  
          ansible.limit = "all"
          ansible.verbose = true
          ansible.install = true
          vagrant_synced_folder_default_type = ""
      end
    end

### Debug output

https://gist.github.com/abhishekkarigar/3dce6b3caf2fe6a868e288c76ad70582

### Expected behavior

successfull provisioned 

### Actual behavior

    [WARNING] Ansible is being run in a world writable directory (/vagrant), ignoring it as an 
    ansible.cfg source. For more information see https:// 
    docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
### Steps to reproduce

1. minimal playbook.yml file
2. **vagrant provision** or **vagrant up --provision**

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- https://github.com/geerlingguy/drupal-vm/issues/1404
- ...

**Comment by gildegoma** [comment]
The relevant error is not the warning you mentioned, but the following Ansible Playbook Task that failed:
 
```
TASK [Gathering Facts] *********************************************************
 INFO interface: info: fatal: [default]: UNREACHABLE! => 
{"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 2222: Connection refused", "unreachable": true}

fatal: [default]: UNREACHABLE! => 
{"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 2222: Connection refused", "unreachable": true}
```

From your Vagrantfile and your [log ouptut](https://gist.github.com/abhishekkarigar/3dce6b3caf2fe6a868e288c76ad70582#file-vagrant-log-L422-L427), I guess that you initially used the Ansible remote (`ansible`) provisioner, and then switched to the `ansible_local` provisioner. Ansible is trying to SSH from the guest into itself via localhost:2222, which doesn't make sense (unlike from the Vagrant host).

Please fully remove your `ansible.inventory_path` (and maybe `ansible.limit`) option(s). This should resolve your problem. If you face further problem, could you please ask on https://discuss.hashicorp.com/c/vagrant/24. Thank you ❤️

**Comment by abhishekkarigar** [comment]
Thank you @gildegoma  , it worked now for **ansible_local** from cygwin  

silly to have asked this question.  
yes, you are right, i tried first with ansible provisioner then switched to ansible_local provisioner.  

i was  exploring these different provisioners from cygwin  
anyway good lesson for me ,  
thanks again
