### ISSUE TITLE
Command 'vagrant up' fails with 'An error occurred in the underlying SSH library'

### ISSUE THREAD

**Issue by nellileinonen** [hashicorp/vagrant#11702]
### Vagrant version

2.2.9

### Host operating system

Manjaro 20.0.3

### Guest operating system

Ubuntu 18.04.4

### Vagrantfile

https://github.com/Seravo/wordpress/blob/beta/Vagrantfile

### Debug output

https://gist.github.com/nellileinonen/bf9b65b638a9ed7921f754f2e5dd4685

https://gist.github.com/nellileinonen/31ffe63398e9d9064800ac4540989ac4

### Expected behavior

Command "vagrant up" should start the virtual machine.

### Actual behavior

Running "vagrant up" hangs on "SSH auth method: private key" for a long time and eventually gives the following error:

"Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value."

After that, running "vagrant up" again gives the following error:

"An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating"

The error occurs with combination:

Manjaro 20.0.3
vagrant --version
Vagrant 2.2.9
vboxmanage --version
6.1.8r137981

However, when downgrading the virtualbox 6.1.8. --> 6.1.6. everything works ok. So the following combination works:

Manjaro 20.0.3
vagrant --version
Vagrant 2.2.9
vboxmanage --version
6.1.6r137129

### Steps to reproduce

1. git clone https://github.com/Seravo/wordpress.git
2. cd wordpress
3. git checkout beta
4. vagrant up

### References

https://github.com/Seravo/wordpress/issues/141

**Comment by briancain** [comment]
@nellileinonen - Have you tried the latest VirtualBox, 6.1.10? If the result changes between VirtualBox versions, I'd first upgrade to the latest virtualbox. Halt or better yet destroy the guest, then bring it back up with the latest version of VirtualBox to see if that resolves your issue. Generally however these errors are due to guest issues rather than something Vagrant handles. I recommend doing what the error message says and try disabling your ssh agent if the VirtualBox upgrade does not work.
