### ISSUE TITLE
Support host shared folders when Vagrant is executed inside WSL2

### ISSUE THREAD

**Issue by jstangroome** [hashicorp/vagrant#11705]
### Vagrant version

```
$ vagrant -v
Vagrant 2.2.9
```

### Host operating system

Windows 10 Version 2004 (OS Build 19041.329)

### Expected behavior

From within WSL2, with the working directory set to a path on the host filesystem.

```
$ export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS=1
$ cd /mnt/c/example
$ vagrant up
...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is not supported from WSL. Host
path of the shared folder must be located on a file system with
DrvFs type. Host path: .
```

In WSL1 the `mount` command returns:
```
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,umask=22,metadata,case=off)
```

But in WSL2 the `mount` command returns:
```
C:\ on /mnt/c type 9p (rw,noatime,dirsync,aname=drvfs;path=C:\;uid=1000;gid=1000;metadata;umask=22;symlinkroot=/mnt/,mmap,access=client,msize=65536,trans=fd,rfd=8,wfd=8)
```

Modifying [platform.rb:564](https://github.com/hashicorp/vagrant/blob/6efdcd2068a97411240878318a360e65b0237067/lib/vagrant/util/platform.rb#L564) from:
```
if info && info[:type] == "drvfs"
```
to
```
if info && (info[:type] == "drvfs" || info[:type] == "9p")
```
solves the issue and specifies the correct host-relative Shared Folder paths in the Virtualbox VM configuration.

### Actual behavior

```
* The host path of the shared folder is not supported from WSL. Host
path of the shared folder must be located on a file system with
DrvFs type. Host path: .
```

### References

Not to be confused with:
- GH-11623
- GH-11311

**Comment by asciifaceman** [comment]
I'm going to wager there is no workaround for this issue without building from source?

**Comment by strarsis** [comment]
@jstangroome: Thanks for this fix! After each Vagrant update I have to reapply it. It would be nice to have this fixed in a new Vagrant release, so synced folders can indeed be used in WSL 2.

**Comment by cristian-hostpapa** [comment]
Any ETA on when this will be available ?  right now, vagrant is useless on WSL2.

**Comment by chrisroberts** [comment]
We are tossing this patch into the next release (#12056) so you won't need to patch locally.

**Comment by chrisroberts** [comment]
#12056 is merged so I'm going to close this issue. It will be available in the next release which will be published soon. Cheers!
