### ISSUE TITLE
Vagrant fails due to recent upstream changes

### ISSUE THREAD

**Issue by nuxy** [hashicorp/vagrant#11710]
### Vagrant version

```
$ vagrant -v
Vagrant 1.9.8
```

### Host operating system

Ubuntu 16.04 (x86_64) 

### Guest operating system

VMware® Workstation 12 Pro with **`vagrant-vmware-workstation` licensed plug-in**

### Vagrantfile

First off, I would like to state that there was no OS upgrades that have occurred on my system since the last time I was able to successfully launch the Vagrant.  This was _working as of two weeks ago without changes_.  I have confirmed this by reverting to a system backup which results in the same failure.

That said, this seems to be an upstream issue.

```
$ vagrant init

Vagrant failed to initialize at a very early stage:

Vagrant has detected that the VMware plugin is not properly setup.
Please reinstall the VMware plugin and run this command again. If
this error persists please contact support.

$ ls -al /home/.vagrant.d/gems/2.3.4/gems/
total 32
drwxr-xr-x 8 mbrooks mbrooks 4096 Jun 21 02:58 .
drwxr-xr-x 8 mbrooks mbrooks 4096 Nov 15  2017 ..
drwxr-xr-x 5 mbrooks mbrooks 4096 Jun 30  2018 micromachine-2.0.0
drwxr-xr-x 5 mbrooks mbrooks 4096 Dec 20  2017 vagrant-hostmanager-1.8.7
drwxr-xr-x 5 mbrooks mbrooks 4096 Nov 15  2017 vagrant-share-1.1.9
drwxr-xr-x 4 mbrooks mbrooks 4096 Jun 30  2018 vagrant-vbguest-0.15.2
drwxr-xr-x 4 mbrooks mbrooks 4096 Jun 21 02:58 vagrant-vmware-desktop-2.1.0
drwxr-xr-x 6 mbrooks mbrooks 4096 May 27 23:00 vagrant-vmware-workstation-5.0.4

$ vagrant plugin expunge --reinstall
$ vagrant up
$ vagrant init

RubyEncoder Loader - Incompatible loader version. This protected script has been encoded with a newer version of RubyEncoder. Please download and install the latest loaders http://www.rubyencoder.com/loaders/ Error code [19]

ls -al /home/.vagrant.d/gems/2.3.4/gems/
total 16
drwxr-xr-x 4 mbrooks mbrooks 4096 Jun 21 04:43 .
drwxr-xr-x 8 mbrooks mbrooks 4096 Jun 21 04:43 ..
drwxr-xr-x 4 mbrooks mbrooks 4096 Jun 21 04:43 vagrant-share-1.1.10
drwxr-xr-x 2 mbrooks mbrooks 4096 Jun 21 04:43 vagrant-vmware-workstation-0.0.1
```
As you can see above both the `vagrant-vmware-workstation-5.0.4` and `vagrant-vmware-desktop-2.1.0` are no longer installed.

### Debug output

https://gist.github.com/nuxy/f272f5a3490431ee276a196eda0cdb64

### Expected behavior

1. Builds do not randomly break when no changes or updates have occurred.
2. The plug-in, when reinstalled, does not break the underlying system.

**Comment by nuxy** [comment]
Looking into this this further I was able to successfully reinstall the original Vagrant plug-ins.

```
vagrant plugin list
vagrant-hostmanager (1.8.9)
  - Version Constraint: > 0
vagrant-share (1.1.10, system)
vagrant-vbguest (0.24.0)
  - Version Constraint: > 0
vagrant-vmware-workstation (0.0.1)
  - Version Constraint: > 0
```

Issue still persists and has been narrowed down to the `vagrant-share` plug-in and third-party commercial licensed plug-in `rubyencoder`.

```
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

RubyEncoder Loader - Incompatible loader version. This protected script has been encoded with a newer version of RubyEncoder. Please download and install the latest loaders http://www.rubyencoder.com/loaders/ Error code [19]
```

I should not have to...
- Install a third-party encoder that not only _is not supported by the OS_ but costs $180 for a license.
- Upgrade ruby when there _is no compelling reason to_ support said encoder.
- Upgrade my provider `VMware Workstation Pro` which cost me $249 for a license.
- Deal with the myriad of issues that will stem from doing any of the above.

All because of a forced update of a plug-in!!!

I have over **40 VMs that are now blocked from further development** due to this issue.  Furthermore, I cannot simply recreate these images considering the the data (and related GuestOS changes) are no longer accessible due to this issue.

**Comment by chrisroberts** [comment]
Hi there,

Upgrading your Vagrant installation and installing the `vagrant-vmware-desktop` plugin + utility should be all that is required. There is no need for updating the provider license if you do not want to upgrade. The Vagrant VMware desktop plugin can still use the existing license, it will just not work on later versions of VMware. Upgrading the Vagrant installation will also upgrade the underlying tools and libraries provided by the installer. Many of the libraries and applications have had various maintenance and security updates since the release of Vagrant 1.9.8, including the Ruby version which was shipped in that release (and is now EOL).

The `vagrant-vmware-desktop` plugin should be used instead of the `vagrant-vmware-workstation` plugin as it was deprecated a couple years ago (https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin). 

The appearance of the 0.0.1 version also indicates that the plugin was fetched from RubyGems directly instead of the HashiCorp RubyGem repository which stores the released versions. You can force the plugin install to only use the HashiCorp RubyGem repository by providing the following options to the install command:

```
$ vagrant plugin install --plugin-clean-sources --plugin-source https://gems.hashicorp.com PLUGIN_NAME
```

Cheers!

**Comment by nuxy** [comment]
Thank you for your detailed response.

With this information I was able to finally upgrade Vagrant but not without issues. I found there was additional steps required in order to ensure that errors didn't occur during the build/runtime process. That said, I'm documenting what I did here in case someone else experiences similar issues during the Vagrant upgrade process.

**Pre-install**

```
$ sudo apt-get remove vagrant virtualbox
$ rm -rf ~/.vagrant.d
```
Note: I was not able to start the Vagrant when Virtualbox was running due to a `vmnet` conflict with VMWare workstation.  Removing the Virtualbox package resolved the issue.

```
$ vagrant up
The VMware "vmnet" devices are failing to start. The most common
reason for this is collisions with existing network services. For
example, if a hostonly network space collides with another hostonly
network (such as with VirtualBox), it will fail to start. Likewise,
if forwarded ports collide with other listening ports, it will
fail to start.
```

**Install**

```
$ sudo dpkg -i <vagrant>.deb
$ sudo dpkg -i <vagrant-vmware-utility>.deb
$ sudo /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility certificate generate
$ sudo /opt/vagrant-vmware-desktop/vagrant-vmware-utility service install
```

Note: The documented command to install the `vagrant-vmware-utility` is incorrect. This should be `/opt` vs `/usr/local` in Ubuntu and Debian-based systems.

```
$ /usr/local/vagrant-vmware-desktop/vagrant-vmware-utility service install
sudo: /usr/local/vagrant-vmware-desktop/vagrant-vmware-utility: command not found
```

**Post-install**

```
$ vagrant plugin license vagrant-vmware-desktop ~/license.lic
```

**Possible bug?**

@chrisroberts 
One thing I did notice is that using `customize` no longer works post-upgrade.  The following `Vagrantfile` settings fail with the error...

```
Vagrant.configure("2") do |config|
  config.vm.provider :vmware_desktop do |vmware|
    vmware.customize ["modifyvm", :id, "--cpus", 1]
    vmware.customize ["modifyvm", :id, "--memory", 2048]
    vmware.customize ["modifyvm", :id, "--usb", "on"]
    vmware.customize ["modifyvm", :id, "--usbehci", "on"]
    ..

There are errors in the configuration of this machine. Please fix
the following errors and try again:

VMware Desktop Provider:
* The following settings shouldn't exist: customize
```

Outside of that, everything works as expected.

Thank you, Chris!

**Comment by chrisroberts** [comment]
@nuxy The `#customize` method is used by the virtualbox provider (which runs `VBoxManage` commands using the arguments provided). For VMware, you'd want to use `#vmx` which provides access to the vmx configuration Hash and allows customized guest configurations. For example:

```ruby
Vagrant.configure("2") do |config|
  config.vm.provider :vmware_desktop do |vmware|
    vmware.vmx["numvcpus"] = 1
    vmware.vmx["memsize"] = 2048
  end
end
```
