### ISSUE TITLE
Slow networking (due to IPv6?) on CentOS 6.x

### ISSUE THREAD

**Issue by dcrosta** [hashicorp/vagrant#1172]
I've been struggling with this issue for a while, and I think I've finally narrowed it down to something Vagrant is doing (though I am not sure what). Here's the situation:
1. I create a [CentOS 6.3 box](http://boxes.zeroclues.net/centos-6.3-x86_64.box) by way of manually installing the CentOS 6.3 minimal ISO.
2. I configure the box until it passes Veewee validation
3. I [disable IPv6](http://wiki.centos.org/FAQ/CentOS6#head-d47139912868bcb9d754441ecb6a8a10d41781df).
   
   This deserves a little explanation: I've found that in VirtualBox (on my machines at least), a CentOS guest with IPv6 enabled has approximately a 5 second delay while it attempts to make network calls. Presumably there is a 5 second timeout trying to use an IPv6 address, after which it falls back to the IPv4 address.
   
   In any event, disabling IPv6 makes using the box much more pleasant than with it enabled, and nothing I am doing requires IPv6.
4. I package the box using `vagrant basebox export centos-6.3-x86_64` and add to Vagrant with `vagrant add centos-6.3 centos-6.3-x86_64.box`
5. I `vagrant init` and `vagrant up`
6. Once inside the VM, I run `time curl http://www.google.com/`. Inside the Vagrant-launched box, I get a time just over 5 seconds, strongly suggesting the same behavior as I attempted to disable in step 3.
7. If manually import the `~/.vagrant.d/centos-6.3-x86_64/box.ovf` file into VirtualBox, and run through the VirtualBox GUI, I do not experience the delay described in step 6.

I don't have any reason to believe that IPv6 is being re-enabled by Virtualbox -- the changes made in step 3 are present in the Vagrant-launched VM -- but the fact that the delay is the same suggests that at least something similar, if not identical, is going on.

I'm a little bit at a loss as to where to look next. Does anyone have any experience solving or working around this issue, or have any suggestions on where to look next?

**Comment by seeafish** [comment]
If anyone needs to workaround this issue in test-kitchen, the vbox settings are mapped like this:
```yaml
---
driver:
  name: vagrant
  customize:
    natdnsproxy1: "off"
    natdnshostresolver1: "off"
```

**Comment by filex** [comment]
I have used the RES_OPTIONS-workaround on CentOS 7. But it stopped working with CentOS 7.1. (To be precise: The box was fine after initial creation, but the resolv.conf was broken after a vagrant reload).

This is due to a bug in RHEL/CentOS that I have filed today: http://bugs.centos.org/view.php?id=8490

**Comment by drocsid** [comment]
centOS 7 uses a systemd service to set hostname, you might want to have a look at that. I don't know why they bother including /etc/sysconfig/network anymore. It's not populated by a manual install.
