### ISSUE TITLE
Vagrant problem with initialization

### ISSUE THREAD

**Issue by Srywards** [hashicorp/vagrant#11723]
### Vagrant version

Vagrant 2.2.9

### Host operating system

Windows 10 2004

### Guest operating system

GNU/Linux

### Vagrantfile

require 'getoptlong'
require 'io/console'

installPlugin=0

unless Vagrant.has_plugin?("vagrant-ansible-local")
  system("vagrant plugin install vagrant-ansible-local")
  installPlugin=1
end

unless Vagrant.has_plugin?("vagrant-timezone")
  system("vagrant plugin install vagrant-timezone")
  installPlugin=1
end

if installPlugin == 1
  puts "Dependencies installed, please try the command again."
  exit
end

After a day of searching i can't find a solution to my problem with vagrant.

I have tested several versions of vagrant as well as virtualbox, I have another pc that has exactly the same versions of software installed and no worries.

I tried vagrant plugin repair, vagrant expunge, nothing helps.

Virtualbox version : 6.1.6

If i remove ansible local plugin, then vagrant will prompt the same error with the next plugin.

If someone could shed some light on this problem...

![uvjwbtvx3c751](https://user-images.githubusercontent.com/15232456/85908356-08d19b80-b815-11ea-99c5-470cb1e1e01f.png)

![g7zm6bzz3c751](https://user-images.githubusercontent.com/15232456/85908369-138c3080-b815-11ea-96b9-a3db109eb555.png)

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by Srywards** [comment]
Resolved, my nickname on windows contained an é, vagrant couldn't find the path.
