### ISSUE TITLE
Nested Virtualization support for Oracle VirtualBox

### ISSUE THREAD

**Issue by stdevel** [hashicorp/vagrant#11726]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to set-up Vagrant boxes that run a hypervisor (*e.g. XEN or KVM*). Currently, I need to set the appropriate setting via the GUI or the following command:

```shell
$ VBoxManage modifyvm my-box --nested-hw-virt on
```

**Describe the solution you'd like**
It would be great to have support for setting this behavior in the `Vagrantfile`, e.g.:

```yaml
    myvm.vm.provider "virtualbox" do |vb|
      vb.nested = true
    end
```

**Describe alternatives you've considered**
The alternative is manually set this setting.

**Additional context**
-

**Comment by briancain** [comment]
Hey there @stdevel - You can already do this today with Vagrant:

```ruby
config.vm.provider :virtualbox do |v|
  v.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
end
```

Last I checked, nested virtualization for VirtualBox only worked if you have an AMD processor. This might not be the case with the most recent version, but if it's not working and you have an intel CPU, there's a chance this is why. Thanks!

**Comment by stdevel** [comment]
Thanks for sharing @briancain - that's exactly what I needed! :tada: 

Nested Virtualization support for Intel was introduced in version 6.1.0 released on 10th Dec 2019: https://www.virtualbox.org/wiki/Changelog-6.1#v0

Best wishes!
