### ISSUE TITLE
File provisioner doesn't copy empty folders

### ISSUE THREAD

**Issue by jvalrog** [hashicorp/vagrant#11737]
### Vagrant version

2.2.9

### Host operating system

Ubuntu 20.04

### Guest operating system

Ubuntu 20.04

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.provision "file", source: "./", destination: "./app"
end
```

### Expected behavior

Empty folders are copied.

### Actual behavior

Empty folders are ignored.

### Description

So, I have a number of empty folders in my project that are required to stay there. 
The `file` provisioner ignores them and my application fails.

Yes, I could handle creating those directories in my app but I didn't see any mention about this in the documentation.

Don't know if it's a bug or intended behaviour.

**Comment by briancain** [comment]
Hey there @jvalrog - This seems to be a bug in the vagrant ssh communicator. For now, an easy fix for you would be placing an empty dot file in the folders like a `.keep` file. Or you could use a synced_folder instead which would probably behave more like what you are expecting!

**Comment by jvalrog** [comment]
@briancain that works, thanks.
