### ISSUE TITLE
  Error: No such file or directory @ rb_sysopen - C:/ProgramData/hashicorp/vagra nt-vmware-desktop/certificates/vagrant-utility.client.crt

### ISSUE THREAD

**Issue by RockAfeller2013** [hashicorp/vagrant#11742]
Vagrant version

vagrant -v
Vagrant 2.2.9

vagrant plugin list
vagrant-reload (0.0.1, global)
vagrant-vmware-desktop (2.1.1, global)

Host operating system

VMware Workstation 15 Pro v15.5.6 build-16341506
Host Windows 2012 R2 Version 6.3 Build 9600

Guest operating system
Debian stretch

Vagrantfile

Debug output

Expected behavior

Actual behavior

Steps to reproduce

vagrant plugin install vagrant-vmware-desktop
vagrant plugin license vagrant-vmware-desktop G:\vmware\license.lic
vagrant init hashicorp/precise64
vagrant up --provider vmware_desktop

Just bought Vagrant for VMware Desktop, Windows 2012 R2 (all updates) Vmware Workstation Pro 15.5.6 build-16341506 Vagrant is the latest. Getting below error;

vagrant box add hashicorp/precise64 --provider=vmware_desktop
vagrant init
vagrant up --provider=vmware_desktop

 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_LOG="info"
 WARN global: resolv replacement has not been enabled!
 INFO manager: Registered plugin: box command
 INFO manager: Registered plugin: cap command
 INFO manager: Registered plugin: vagrant-cloud
 INFO manager: Registered plugin: destroy command
 INFO manager: Registered plugin: global-status command
 INFO manager: Registered plugin: halt command
 INFO manager: Registered plugin: help command
 INFO manager: Registered plugin: init command
 INFO manager: Registered plugin: list-commands command
 INFO manager: Registered plugin: vagrant-login
 INFO manager: Registered plugin: package command
 INFO manager: Registered plugin: plugin command
 INFO manager: Registered plugin: port command
 INFO manager: Registered plugin: powershell command
 INFO manager: Registered plugin: provider command
 INFO manager: Registered plugin: provision command
 INFO manager: Registered plugin: push command
 INFO manager: Registered plugin: rdp command
 INFO manager: Registered plugin: reload command
 INFO manager: Registered plugin: resume command
 INFO manager: Registered plugin: snapshot command
 INFO manager: Registered plugin: ssh command
 INFO manager: Registered plugin: ssh-config command
 INFO manager: Registered plugin: status command
 INFO manager: Registered plugin: suspend command
 INFO manager: Registered plugin: up command
 INFO manager: Registered plugin: upload command
 INFO manager: Registered plugin: validate command
 INFO manager: Registered plugin: version command
 INFO manager: Registered plugin: winrm command
 INFO manager: Registered plugin: winrm-config command
 INFO manager: Registered plugin: ssh communicator
 INFO manager: Registered plugin: winrm communicator
 INFO manager: Registered plugin: windows ssh communicator
 INFO manager: Registered plugin: Alpine guest
 INFO manager: Registered plugin: ALT Platform guest
 INFO manager: Registered plugin: Amazon Linux guest
 INFO manager: Registered plugin: Arch guest
 INFO manager: Registered plugin: Atomic Host guest
 INFO manager: Registered plugin: BSD-based guest
 INFO manager: Registered plugin: CentOS guest
 INFO manager: Registered plugin: CoreOS guest
 INFO manager: Registered plugin: Darwin guest
 INFO manager: Registered plugin: Debian guest
 INFO manager: Registered plugin: DragonFly BSD guest
 INFO manager: Registered plugin: Elementary guest
 INFO manager: Registered plugin: ESXi guest.
 INFO manager: Registered plugin: Fedora guest
 INFO manager: Registered plugin: FreeBSD guest
 INFO manager: Registered plugin: Funtoo guest
 INFO manager: Registered plugin: Gentoo guest
 INFO manager: Registered plugin: Haiku guest
 INFO manager: Registered plugin: Kali guest
 INFO manager: Registered plugin: Linux guest.
 INFO manager: Registered plugin: Mint guest
 INFO manager: Registered plugin: NetBSD guest
 INFO manager: Registered plugin: NixOS guest
 INFO manager: Registered plugin: OmniOS guest.
 INFO manager: Registered plugin: OpenBSD guest
 INFO manager: Registered plugin: VMware Photon guest
 INFO manager: Registered plugin: PLD Linux guest
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
 INFO manager: Registered plugin: Slackware guest
 INFO manager: Registered plugin: SmartOS guest.
 INFO manager: Registered plugin: Solaris guest.
 INFO manager: Registered plugin: Solaris 11 guest.
 INFO manager: Registered plugin: SUSE guest
 INFO manager: Registered plugin: TinyCore Linux guest.
 INFO manager: Registered plugin: Trisquel guest
 INFO manager: Registered plugin: Ubuntu guest
 INFO manager: Registered plugin: Windows guest.
 INFO manager: Registered plugin: ALT Platform host
 INFO manager: Registered plugin: Arch host
 INFO manager: Registered plugin: BSD host
 INFO manager: Registered plugin: Mac OS X host
 INFO manager: Registered plugin: FreeBSD host
 INFO manager: Registered plugin: Gentoo host
 INFO manager: Registered plugin: Linux host
 INFO manager: Registered plugin: null host
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
 INFO manager: Registered plugin: Slackware host
 INFO manager: Registered plugin: SUSE host
 INFO manager: Registered plugin: Void host
 INFO manager: Registered plugin: Windows host
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: docker-provider
 INFO manager: Registered plugin: Hyper-V provider
 INFO manager: Registered plugin: VirtualBox provider
 INFO manager: Registered plugin: ansible
 INFO manager: Registered plugin: CFEngine Provisioner
 INFO manager: Registered plugin: chef
 INFO manager: Registered plugin: container
 INFO manager: Registered plugin: docker
 INFO manager: Registered plugin: file
 INFO manager: Registered plugin: podman
 INFO manager: Registered plugin: puppet
 INFO manager: Registered plugin: salt
 INFO manager: Registered plugin: shell
 INFO manager: Registered plugin: atlas
 INFO manager: Registered plugin: ftp
 INFO manager: Registered plugin: heroku
 INFO manager: Registered plugin: local-exec
 INFO manager: Registered plugin: noop
 INFO manager: Registered plugin: NFS synced folders
 INFO manager: Registered plugin: RSync synced folders
 INFO manager: Registered plugin: SMB synced folders
 INFO vagrant: `vagrant` invoked: ["up"]
 INFO environment: Environment initialized (#<Vagrant::Environment:0x00000000069
84828>)
 INFO environment:   - cwd: G:/vmware/test1
 INFO environment: Home path: D:/Users/Administrator/.vagrant.d
 INFO environment: Local data path: G:/vmware/test1/.vagrant
 INFO manager: Plugins:
 INFO manager: Loading plugins...
 INFO manager: Plugins:
 INFO manager:   - vagrant-reload = [installed: 0.0.1 constraint: > 0]
 INFO manager:   - vagrant-vmware-desktop = [installed: 2.1.1 constraint: > 0]
 INFO manager: Loading plugins...
 INFO manager: Loading plugin `vagrant-reload` with default require: `vagrant-re
load`
 INFO manager: Registered plugin: Reload
 INFO manager: Loading plugin `vagrant-vmware-desktop` with default require: `va
grant-vmware-desktop`
 INFO manager: Registered plugin: VMware Workstation Provider
 INFO loader: Set :root = ["#<Pathname:G:/vmware/test1/Vagrantfile>"]
 INFO loader: Loading configuration in order: [:home, :root]
 INFO loader: Set "55382700_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "55382700_machine_d
efault"]
 INFO box_collection: Box not found: base (vmware_desktop)
 WARN vagrantfile: Failed to locate base with version
 WARN vagrantfile: Performing lookup with inital values base with version
 INFO box_collection: Box not found: base (vmware_desktop)
 INFO box_collection: Box not found: base (vmware_desktop)
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Running action: environment_plugins_loaded #<Vagrant::Action::Buil
der:0x00000000069f87c8>
 INFO environment: Running hook: environment_load
 INFO runner: Running action: environment_load #<Vagrant::Action::Builder:0x0000
000007269e70>
 INFO warden: Calling IN action: #<HashiCorp::VagrantVMwareDesktop::SetupPlugin:
0x000000000731d420>
 INFO warden: Calling IN action: HashiCorp Background Check: Start
 INFO warden: Calling OUT action: HashiCorp Background Check: Start
 INFO warden: Calling OUT action: #<HashiCorp::VagrantVMwareDesktop::SetupPlugin
:0x000000000731d420>
 INFO cli: CLI: [] "up" []
 INFO vmware_driver: VMX file:
 INFO environment: Getting machine: default (vmware_desktop)
 INFO environment: Uncached load of machine.
 INFO loader: Set "55382700_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "55382700_machine_d
efault"]
 INFO box_collection: Box not found: base (vmware_desktop, vmware_fusion, vmware
_workstation)
 WARN vagrantfile: Failed to locate base with version
 WARN vagrantfile: Performing lookup with inital values base with version
 INFO box_collection: Box not found: base (vmware_desktop, vmware_fusion, vmware
_workstation)
 INFO box_collection: Box not found: base (vmware_desktop, vmware_fusion, vmware
_workstation)
 INFO machine: Initializing machine: default
 INFO machine:   - Provider: HashiCorp::VagrantVMwareDesktop::Provider
 INFO machine:   - Box:
 INFO machine:   - Data dir: G:/vmware/test1/.vagrant/machines/default/vmware_de
sktop
 INFO vmware_driver: VMX file:
 INFO environment: Running hook: environment_unload
 INFO host: Autodetecting host type for [#<Vagrant::Environment: G:/vmware/test1
>]
 INFO host: Detected: windows!
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00
000000072590e8>
 INFO warden: Calling IN action: HashiCorp Background Check: End
 INFO logger: Cleaning up background activation thread...
 INFO warden: Calling OUT action: HashiCorp Background Check: End
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<HashiCorp::VagrantVMwareDesktop::Errors::DriverAPICertificateEr
ror: Vagrant encountered an error while attempting to load the utility
service key file. This error can occur if the Vagrant VMware Utility
has not yet been installed, or if it was installed incorrectly. If
this error persists after running the Vagrant VMware Utility installer
again, please contact support at: support@hashicorp.com

Information about the Vagrant VMware Utility, including installation
instruction, can be found here:

  https://www.vagrantup.com/docs/vmware/vagrant-vmware-utility.html

  Path:  C:/ProgramData/hashicorp/vagrant-vmware-desktop/certificates/vagrant-ut
ility.client.crt
  Error: No such file or directory @ rb_sysopen - C:/ProgramData/hashicorp/vagra
nt-vmware-desktop/certificates/vagrant-utility.client.crt>
ERROR vagrant: Vagrant encountered an error while attempting to load the utility

service key file. This error can occur if the Vagrant VMware Utility
has not yet been installed, or if it was installed incorrectly. If
this error persists after running the Vagrant VMware Utility installer
again, please contact support at: support@hashicorp.com

Information about the Vagrant VMware Utility, including installation
instruction, can be found here:

  https://www.vagrantup.com/docs/vmware/vagrant-vmware-utility.html

  Path:  C:/ProgramData/hashicorp/vagrant-vmware-desktop/certificates/vagrant-ut
ility.client.crt
  Error: No such file or directory @ rb_sysopen - C:/ProgramData/hashicorp/vagra
nt-vmware-desktop/certificates/vagrant-utility.client.crt
ERROR vagrant: D:/Users/Administrator/.vagrant.d/gems/2.6.6/gems/vagrant-vmware-
desktop-2.1.1/lib/vagrant-vmware-desktop/helper/vagrant_utility.rb:80:in `rescue
 in initialize'
D:/Users/Administrator/.vagrant.d/gems/2.6.6/gems/vagrant-vmware-desktop-2.1.1/l
ib/vagrant-vmware-desktop/helper/vagrant_utility.rb:76:in `initialize'
D:/Users/Administrator/.vagrant.d/gems/2.6.6/gems/vagrant-vmware-desktop-2.1.1/l
ib/vagrant-vmware-desktop/driver.rb:160:in `new'
D:/Users/Administrator/.vagrant.d/gems/2.6.6/gems/vagrant-vmware-desktop-2.1.1/l
ib/vagrant-vmware-desktop/driver.rb:160:in `initialize'
D:/Users/Administrator/.vagrant.d/gems/2.6.6/gems/vagrant-vmware-desktop-2.1.1/l
ib/vagrant-vmware-desktop/driver.rb:1155:in `new'
D:/Users/Administrator/.vagrant.d/gems/2.6.6/gems/vagrant-vmware-desktop-2.1.1/l
ib/vagrant-vmware-desktop/driver.rb:1155:in `create'
D:/Users/Administrator/.vagrant.d/gems/2.6.6/gems/vagrant-vmware-desktop-2.1.1/l
ib/vagrant-vmware-desktop/provider.rb:48:in `machine_id_changed'
D:/Users/Administrator/.vagrant.d/gems/2.6.6/gems/vagrant-vmware-desktop-2.1.1/l
ib/vagrant-vmware-desktop/provider.rb:31:in `initialize'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.
rb:139:in `new'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/machine.
rb:139:in `initialize'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/vagrantf
ile.rb:81:in `new'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/vagrantf
ile.rb:81:in `machine'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environm
ent.rb:715:in `machine'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/plugin/v
2/command.rb:180:in `block in with_target_vms'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/plugin/v
2/command.rb:204:in `block in with_target_vms'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/plugin/v
2/command.rb:186:in `each'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/plugin/v
2/command.rb:186:in `with_target_vms'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/plugins/commands/up/
command.rb:87:in `execute'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/cli.rb:6
7:in `execute'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/lib/vagrant/environm
ent.rb:290:in `cli'
C:/HashiCorp/Vagrant/embedded/gems/2.2.9/gems/vagrant-2.2.9/bin/vagrant:205:in `
<main>'
 INFO interface: error: Vagrant encountered an error while attempting to load th
e utility
service key file. This error can occur if the Vagrant VMware Utility
has not yet been installed, or if it was installed incorrectly. If
this error persists after running the Vagrant VMware Utility installer
again, please contact support at: support@hashicorp.com

Information about the Vagrant VMware Utility, including installation
instruction, can be found here:

  https://www.vagrantup.com/docs/vmware/vagrant-vmware-utility.html

  Path:  C:/ProgramData/hashicorp/vagrant-vmware-desktop/certificates/vagrant-ut
ility.client.crt
  Error: No such file or directory @ rb_sysopen - C:/ProgramData/hashicorp/vagra
nt-vmware-desktop/certificates/vagrant-utility.client.crt
Vagrant encountered an error while attempting to load the utility
service key file. This error can occur if the Vagrant VMware Utility
has not yet been installed, or if it was installed incorrectly. If
this error persists after running the Vagrant VMware Utility installer
again, please contact support at: support@hashicorp.com

Information about the Vagrant VMware Utility, including installation
instruction, can be found here:

  https://www.vagrantup.com/docs/vmware/vagrant-vmware-utility.html

  Path:  C:/ProgramData/hashicorp/vagrant-vmware-desktop/certificates/vagrant-ut
ility.client.crt
  Error: No such file or directory @ rb_sysopen - C:/ProgramData/hashicorp/vagra
nt-vmware-desktop/certificates/vagrant-utility.client.crt
 INFO interface: Machine: error-exit ["HashiCorp::VagrantVMwareDesktop::Errors::
DriverAPICertificateError", "Vagrant encountered an error while attempting to lo
ad the utility\nservice key file. This error can occur if the Vagrant VMware Uti
lity\nhas not yet been installed, or if it was installed incorrectly. If\nthis e
rror persists after running the Vagrant VMware Utility installer\nagain, please
contact support at: support@hashicorp.com\n\nInformation about the Vagrant VMwar
e Utility, including installation\ninstruction, can be found here:\n\n  https://
www.vagrantup.com/docs/vmware/vagrant-vmware-utility.html\n\n  Path:  C:/Program
Data/hashicorp/vagrant-vmware-desktop/certificates/vagrant-utility.client.crt\n
 Error: No such file or directory @ rb_sysopen - C:/ProgramData/hashicorp/vagran
t-vmware-desktop/certificates/vagrant-utility.client.crt"]

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! You need to install the Vagrant VMware Utility from here:
https://www.vagrantup.com/docs/providers/vmware/vagrant-vmware-utility.html

In order to use VMware with Vagrant, you need both the VMware plugin and the Vagrant VMware Utility. If you have any issues with installing the utility, feel free to reopen this issue and we'll be happy to help you out.

Cheers!
