### ISSUE TITLE
Vagrant up error 416

### ISSUE THREAD

**Issue by drchibs** [hashicorp/vagrant#11740]
this happens every time I run vagrant up on homestead folder, and the vagrant version is Vagrant 2.2.9
is there a fix, please?

```
$ vagrant up
Bringing machine 'homestead' up with 'virtualbox' provider...
==> homestead: Box 'laravel/homestead' could not be found. Attempting to find and install...
    homestead: Box Provider: virtualbox
    homestead: Box Version: ~> 9.5.0
==> homestead: Loading metadata for box 'laravel/homestead'
    homestead: URL: https://vagrantcloud.com/laravel/homestead
==> homestead: Adding box 'laravel/homestead' (v9.5.1) for provider: virtualbox
    homestead: Downloading: https://vagrantcloud.com/laravel/boxes/homestead/versions/9.5.1/providers/virtualbox.box
==> homestead: Box download is resuming from prior download progress
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
    homestead:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 416
```

**Comment by soapy1** [comment]
Hey there, thanks for the report. In order to better understand what's going on, could you also provided the (smallest) Vagrantfile to reproducing this error and a [debug gist](https://www.vagrantup.com/docs/other/debugging.html).

**Comment by chrisroberts** [comment]
Hi there,

It appears that you may have tried to download this once before unsuccessfully, and Vagrant is attempting to resume the download but the partial file is corrupted or incorrect. You should be able to resolve this by removing any files within the `tmp` directory in your VAGRANT_HOME. This is usually in your home directory (`~/.vagrant.d/tmp`).

Once they are removed, the download should successfully restart from the beginning.

Cheers!
