### ISSUE TITLE
 libvirt: Undefined method [] for nil on 'vagrant up'

### ISSUE THREAD

**Issue by thomarite** [hashicorp/vagrant#11745]
### Vagrant version
Vagrant 2.2.9

### Host operating system

Debian 10

### Guest operating system

Cumulus VX 4.1.1

### Vagrantfile

```
Vagrant.configure(2) do |config|

config.vm.provider "libvirt"

config.vm.define "cvx1" do |cvx1|
  cvx1.vm.box = "cumulus-vx-4.1.1"
  cvx1.vm.network :private_network, ip: "192.168.50.1/30"
  cvx1.vm.network :private_network, ip: "10.1.1.254/24"
  end

config.vm.define "cvx2" do |cvx2|
  cvx2.vm.box = "cumulus-vx-4.1.1"
  cvx2.vm.network :private_network, ip: "192.168.50.2/30"
  cvx2.vm.network :private_network, ip: "20.1.1.254/24"
  end
 
end
```

### Debug output

https://gist.github.com/thomarite/6a82ec5d875008c7d64bbadf0f05f768

### Expected behavior

Both Cumulus boxes should be up and I should to connect to them

### Actual behavior

It seems vagrant crashes nearly at the end of bringing up the boxes. This is the error:

```
==> cvx2: An error occurred. The error will be shown after all tasks complete.
==> cvx1: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An unexpected error occurred when executing the action on the
'cvx1' machine. Please report this as a bug:

undefined method `[]' for nil:NilClass
```

### Steps to reproduce

1. Download cumulus-vx-4.1.1 from cumulus site. It is free. Add it to your vagrant box
2. vagrant up with the Vagrant file above.

### References

I think this is similar but I think I running the latest version of vagrant and libvirt. I updated the plugins and rebooted my laptop just in case.

https://github.com/hashicorp/vagrant/issues/11572

**Comment by thomarite** [comment]
This is the output of vagrant up just in case:

https://gist.github.com/thomarite/8b145de2c825a00f4a204b0831c02fcb

thanks

**Comment by briancain** [comment]
Hey @thomarite . From the debug log you shared, the error is coming from the [vagrant-libvirt](https://github.com/vagrant-libvirt/vagrant-libvirt) plugin. I recommend opening an issue on that repo instead, as that plugin isn't supported here. Thanks!
