### ISSUE TITLE
Solution set not being cached

### ISSUE THREAD

**Issue by sowmyanayak** [hashicorp/vagrant#11757]
### Vagrant version

Vagrant 2.2.9

### Host operating system

MacOS Catalina

### Debug output

https://gist.github.com/sowmyanayak/7a7644fb1ae76852a2a55e1bba37689b

### Expected behavior

When running vagrant commands, it should have executed quickly within a few seconds

### Actual behavior
Resolving the solution set took really long. It wasn't caching it. 

### Steps to reproduce

1. Run vagrant --help --debug 2>&1 | ts -s

### References

I think this might be missing - https://github.com/hashicorp/vagrant/pull/11363

**Comment by sowmyanayak** [comment]
I wanted to give an update. I re-installed vagrant, destroyed and recreated my VM and that seemed to fix it. It is now using a cached solution set.

**Comment by chrisroberts** [comment]
@sowmyanayak Thanks for the update. I started to look into this today and found things working as expected so I'll close this up.

Cheers!
