### ISSUE TITLE
Vagrant Cloud commands are not available on v2.0.1 for Windows

### ISSUE THREAD

**Issue by AllanOricil** [hashicorp/vagrant#11760]
### Vagrant version
2.0.1

### Host operating system
Windows 10

### Expected behavior
`vagrant list-commands` should show the cloud commands.

### Actual behavior
`vagrant list-commands` does not show the cloud commands.

### References
Vagrant Cloud commands: https://www.vagrantup.com/docs/cli/cloud

**Comment by soapy1** [comment]
The `vagrant cloud` command was added in [2.2.0](https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md#220-october-16-2018.) Please update your version of Vagrant in order to use this feature.
