### ISSUE TITLE
Environment freezes on vagrant up using ubuntu/focal64

### ISSUE THREAD

**Issue by tdimitrov** [hashicorp/vagrant#11769]
### Vagrant version

Vagrant 2.2.9

### Host operating system

Ubuntu 20.04, 64bit, latest patches (as of 16 July 2020).

### Guest operating system

Ubuntu 20.04 (Focal), installed via box ubuntu/focal64 -> ubuntu/focal64  (virtualbox, 20200714.0.0)

### Vagrantfile

Default vagrant file, generated from vagrant init ubuntu/focal64:
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
end
```

### Debug output

https://gist.github.com/tdimitrov/c1c05255cdb6fd1a77723f3e28a04da1

Note: at some point I stop init with ctrl+c.

### Expected behavior

The environment should start.

### Actual behavior

The vagrant up process freezes at:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/focal64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/focal64' version '20200714.0.0' is up to date...
==> default: Setting the name of the VM: test_default_1594849056911_58394
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
```
Opening VirtualBox GUI causes it (the vbox gui) to freeze. 
Stopping VM manually also freezes:
```
$ vboxmanage controlvm  test_default_1594849056911_58394  poweroff 
0%...10%...
```
Sometimes I manage to stop the VM and then I can successfully remove it, but more often I need to kill the VM process.
The issue doesn't happen with other boxes (e.g. ubuntu/focal64  (virtualbox, 20200714.0.0)).

Also manually installed VMs (e.g. Kali Linux) work fine.
### Steps to reproduce

1. vagrant init ubuntu/focal64
2. vagrant up

I tried two versions of virtualbox - no difference:
```
$ apt-cache policy virtualbox
virtualbox:
  Installed: (none)
  Candidate: 6.1.10-dfsg-1~ubuntu1.20.04.1
  Version table:
     6.1.10-dfsg-1~ubuntu1.20.04.1 500
        500 http://bg.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages
        100 /var/lib/dpkg/status
     6.1.6-dfsg-1 500
        500 http://bg.archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages
```
and
```
$ apt-cache policy virtualbox-6.1
virtualbox-6.1:
  Installed: 6.1.12-139181~Ubuntu~eoan
  Candidate: 6.1.12-139181~Ubuntu~eoan
  Version table:
 *** 6.1.12-139181~Ubuntu~eoan 500
        500 https://download.virtualbox.org/virtualbox/debian focal/contrib amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by briancain** [comment]
Hey there @tdimitrov - This is an issue with the Ubuntu box: https://bugs.launchpad.net/cloud-images/+bug/1829625 They add this customize command that breaks the box from booting `vb.customize [ "modifyvm", :id, "--uart1", "0x3F8", "4" ]`

I'd probably opt for using something like `bento/ubuntu-20.04` over the Ubuntu boxes. Ubuntu boxes have been notorious for these kinds of issues, where as the bento boxes typically just work.

**Comment by tdimitrov** [comment]
Thanks for the fast reply @briancain
