### ISSUE TITLE
Error - Packer is not recognized 

### ISSUE THREAD

**Issue by robotbond** [hashicorp/vagrant#11778]
Hi Chris, 

I'm new to Detection Lab. While running powershell script with virtualbox, I'm getting an related to packer. The error log is mentioned below. By the way, I haven't purchased vagrant plugin license. 

DetectionLab-master> .\build.ps1 virtualbox
[preflight_checks] Running..
[preflight_checks] Checking if Packer is installed
Get-Command : **The term 'packer' is not recognized** as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\ABC\Downloads\DetectionLab-master\build.ps1:78 char:8
+   if ((Get-Command packer).Path) {
+        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (packer:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

check_packer : Packer not found at C:\Hashicorp\packer.exe
At C:\Users\ABC\Downloads\DetectionLab-master\build.ps1:186 char:5
+     check_packer
+     ~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,check_packer

Re-run the script setting the PackerPath parameter to the location of packer
Example: build.ps1 -PackerPath 'C:\packer.exe'
Exiting..

**Comment by soapy1** [comment]
Hey there, thanks for opening up an issue, however this seems like this is not a bug in Vagrant. From your error message it looks like the script that is being run is looking for Packer in a specific location

> check_packer : Packer not found at C:\Hashicorp\packer.exe

So, the `packer.exe` executable needs to be made available at `C:\Hashicorp`.

Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use HashiCorp Discuss: https://discuss.hashicorp.com/c/vagrant/24 Thank you!
