### ISSUE TITLE
vagrant-vmware-utility not starting - `-pid` arg is not supported.

### ISSUE THREAD

**Issue by AlexBaranowski** [hashicorp/vagrant#11770]
Hi,
I have problem with the vagrant-vmware-utility package

### Vagrant and vagrant-vmware-utility version

```
[user@jenkins-slave-vmware-workstation ~]# rpm -qi vagrant-vmware-utility | head -5; vagrant --version
Name        : vagrant-vmware-utility
Epoch       : 1
Version     : 1.0.9
Release     : 1
Architecture: x86_64
Vagrant 2.2.9
[jenkins@jenkins-slave-vmware-workstation make-basebox]$ vagrant plugin list
vagrant-vmware-desktop (2.1.1, global)
```

### Host operating system

CentOS 7 or 8

### Guest operating system

N/A

### Vagrantfile

N/A

### Debug output

N/A

### Expected behaviour

vagrant-vmware-utility service starts

### Actual behaviour

vagrant-vmware-utility service didn't start

### Steps to reproduce

1. Install vagrant-vmware-utility rpm on Enterprise Linux 7 or 8
2. Start the vagrant-vmware-utility
3. Watch it fail due to `-pid` option not being supported by. (You can use `journalctl -u vagrant-vmware-utility` or any other solution to find startup log).

Some commands that I used during debugging process
```shell
[user@jenkins-slave-vmware-workstation ~]# rpm -ql vagrant-vmware-utility
/etc/init.d/vagrant-vmware-utility
/opt/vagrant-vmware-desktop
/opt/vagrant-vmware-desktop/bin
/opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility
```
So the package is one binary and service (btw. I'm surprised that it's not a systemd service file).

Let's go deeper to check where the problem is.

```
[user@jenkins-slave-vmware-workstation ~]# grep -v '^#' /etc/init.d/vagrant-vmware-utility | head -10

name=$(basename $0)
pid_file="/var/run/$name.pid"
log="/var/log/$name.log"
cmd="/opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility"
cmdargs="api -port=9922 -pid=$pid_file -level=info -log-file=$log"
```
So `-pid=$pid_file` from `cmdargs` is the problem. Any invocation with `-pid` will fail. Example:

```
[user@jenkins-slave-vmware-workstation ~]# /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility api -pid
flag provided but not defined: -pid
Usage of api:
  -debug
    	enable debug output
  -driver string
    	Driver to use (simple or advanced)
  -level string
    	logger output level
  -log-file string
    	log file path
  -port int
    	Port for API to listen (default 9922)
Failed to initialize: flag provided but not defined: -pid
```

## Workaround
Start service manually without `-pid` option.
```
nohup /opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility api -port=9922 -level=info -log-file=/var/log/vagrant-vmware-utility.log  &
```

Best,
Alex

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this issue. The latest release of the `vagrant-vmware-utility` has this fix included.

Cheers!
