### ISSUE TITLE
vagrant plugin install vagrant-libvirt

### ISSUE THREAD

**Issue by wurstdog** [hashicorp/vagrant#11775]
**Vagrant version**

$ vagrant -v
Vagrant 2.2.9

**OS version **

$ cat /etc/redhat-release 
CentOS Linux release 8.2.2004 (Core)

** issue**

$ vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Building native extensions. This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /home/jmecklenburg/.vagrant.d/gems/2.6.6/gems/ruby-libvirt-0.7.1/ext/libvirt
/opt/vagrant/embedded/bin/ruby -I /opt/vagrant/embedded/lib/ruby/2.6.0 -r ./siteconf20200717-16037-1ddkd9q.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
        --with-libvirt-include
        --without-libvirt-include
        --with-libvirt-lib
        --without-libvirt-lib
        --with-libvirt-config
        --without-libvirt-config
        --with-pkg-config
        --without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/jmecklenburg/.vagrant.d/gems/2.6.6/extensions/x86_64-linux/2.6.0/ruby-libvirt-0.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/jmecklenburg/.vagrant.d/gems/2.6.6/gems/ruby-libvirt-0.7.1 for inspection.
Results logged to /home/jmecklenburg/.vagrant.d/gems/2.6.6/extensions/x86_64-linux/2.6.0/ruby-libvirt-0.7.1/gem_make.out

cat /home/jmecklenburg/.vagrant.d/gems/2.6.6/extensions/x86_64-linux/2.6.0/ruby-libvirt-0.7.1/gem_make.out
current directory: /home/jmecklenburg/.vagrant.d/gems/2.6.6/gems/ruby-libvirt-0.7.1/ext/libvirt
/opt/vagrant/embedded/bin/ruby -I /opt/vagrant/embedded/lib/ruby/2.6.0 -r ./siteconf20200717-16037-1ddkd9q.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
        --with-libvirt-include
        --without-libvirt-include
        --with-libvirt-lib
        --without-libvirt-lib
        --with-libvirt-config
        --without-libvirt-config
        --with-pkg-config
        --without-pkg-config
extconf.rb:73:in `<main>': libvirt library not found in default locations (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/jmecklenburg/.vagrant.d/gems/2.6.6/extensions/x86_64-linux/2.6.0/ruby-libvirt-0.7.1/mkmf.log

**mkmf.log **

cat /home/jmecklenburg/.vagrant.d/gems/2.6.6/extensions/x86_64-linux/2.6.0/ruby-libvirt-0.7.1/mkmf.log
"pkg-config --exists libvirt"
| pkg-config --libs libvirt
=> "-lvirt \n"
"gcc -o conftest -I/opt/vagrant/embedded/include/ruby-2.6.0/x86_64-linux -I/opt/vagrant/embedded/include/ruby-2.6.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.6.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include   -I/opt/vagrant/embedded/include -fPIC conftest.c  -L. -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib64 -Wl,-rpath=/opt/vagrant/embedded/lib:/opt/vagrant/embedded/lib64 -fstack-protector-strong -rdynamic -Wl,-export-dynamic -L/opt/vagrant/embedded/lib  -Wl,-rpath,/opt/vagrant/embedded/lib     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

"gcc -o conftest -I/opt/vagrant/embedded/include/ruby-2.6.0/x86_64-linux -I/opt/vagrant/embedded/include/ruby-2.6.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.6.0 -I. -I/opt/vagrant/embedded/include -I/opt/vagrant/embedded/include   -I/opt/vagrant/embedded/include -fPIC conftest.c  -L. -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -Wl,-rpath,/opt/vagrant/embedded/lib -L. -L/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib64 -Wl,-rpath=/opt/vagrant/embedded/lib:/opt/vagrant/embedded/lib64 -fstack-protector-strong -rdynamic -Wl,-export-dynamic -L/opt/vagrant/embedded/lib  -Wl,-rpath,/opt/vagrant/embedded/lib     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby -lvirt -lm   -lc"
//usr/lib64/libk5crypto.so.3: undefined reference to `EVP_KDF_derive@OPENSSL_1_1_1b'
//usr/lib64/libk5crypto.so.3: undefined reference to `EVP_KDF_ctrl@OPENSSL_1_1_1b'
//usr/lib64/libk5crypto.so.3: undefined reference to `EVP_KDF_CTX_free@OPENSSL_1_1_1b'
//usr/lib64/libk5crypto.so.3: undefined reference to `EVP_KDF_CTX_new_id@OPENSSL_1_1_1b'
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

package configuration for libvirt is not found

**installed packages**

$rpm -qa|grep libvirt
libvirt-daemon-driver-storage-scsi-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-interface-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-network-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-storage-logical-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-nwfilter-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-config-network-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-storage-disk-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-storage-mpath-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-bash-completion-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-secret-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-storage-gluster-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-storage-rbd-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-qemu-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-client-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-devel-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-nodedev-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-storage-iscsi-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-libs-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-storage-core-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-driver-storage-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64
libvirt-daemon-config-nwfilter-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64

**Comment by soapy1** [comment]
Hey there, it looks you are missing a couple of libvirt related libraries. In order for me to get this to work on centos I needed the following installed:

```
[vagrant@localhost ~]$ rpm -qa|grep libvirt
libvirt-python-4.5.0-1.el7.x86_64
libvirt-daemon-driver-network-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-secret-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-lxc-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-storage-disk-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-storage-4.5.0-33.el7_8.1.x86_64
libvirt-4.5.0-33.el7_8.1.x86_64
libvirt-bash-completion-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-storage-core-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-nodedev-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-config-network-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-storage-scsi-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-storage-mpath-4.5.0-33.el7_8.1.x86_64
libvirt-client-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-qemu-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-config-nwfilter-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-storage-logical-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-storage-iscsi-4.5.0-33.el7_8.1.x86_64
libvirt-libs-4.5.0-33.el7_8.1.x86_64
libvirt-glib-1.0.0-1.el7.x86_64
libvirt-daemon-driver-nwfilter-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-interface-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-storage-rbd-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-driver-storage-gluster-4.5.0-33.el7_8.1.x86_64
libvirt-daemon-kvm-4.5.0-33.el7_8.1.x86_64
libvirt-devel-4.5.0-33.el7_8.1.x86_64
```

which I got from running `sudo yum install libvirt-devel qemu-kvm libvirt virt-manager libguestfs-tools bridge-utils virt-install`

**Comment by wurstdog** [comment]
Hi, thanks for the your feedback and see below

Last metadata expiration check: 0:52:30 ago on Thu 23 Jul 2020 08:13:28 AM CEST.
Package libvirt-devel-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64 is already installed.
Package qemu-kvm-15:2.12.0-99.module_el8.2.0+385+c644c6e8.2.x86_64 is already installed.
Package libvirt-4.5.0-42.module_el8.2.0+320+13f867d7.x86_64 is already installed.
No match for argument: bridge-utils

virt-manager is a desktop tool and i don't need it on a server

thx

**Comment by soapy1** [comment]
hmmmm, from the error message I'm pretty convinced that libvirt is not available in some capacity. Maybe it's not running? Is the libvirt service running (`sudo systemctl start libvirtd `) and is KVM/QEMU working (`sudo virsh version`)?

It looks like the vagrant-libvirt project has some [troubleshooting steps](https://github.com/vagrant-libvirt/vagrant-libvirt#possible-problems-with-plugin-installation-on-linux), including help for building `ruby-libvirt`. Maybe something like setting `CONFIGURE_ARGS` to point to libvirt will sort out this issue:

```
CONFIGURE_ARGS='with-ldflags=-L/opt/vagrant/embedded/lib with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib' GEM_HOME=~/.vagrant.d/gems GEM_PATH=$GEM_HOME:/opt/vagrant/embedded/gems PATH=/opt/vagrant/embedded/bin:$PATH vagrant plugin install vagrant-libvirt
```

**Comment by pvalena** [comment]
From the error it seems there are issues with OpenSSL, maybe openssl-devel is missing? 

FYI: I've packaged Vagrant for CentOS in my COPR:
  https://copr.fedorainfracloud.org/coprs/pvalena/vagrant/

You can use it instead, or at least for debugging (also let me know if you experience any issues with it).
I'm using Ruby from the CentOS system, so that's not an issue.

**Comment by kcem** [comment]
```dnf install openssl-devel``` will push your installation farther

**Comment by kcem** [comment]
I struggle with the same problem on Centos 8.2 (on Centos7 it works fine).

/usr/lib64/libk5crypto.so.3: undefined reference to EVP_KDF_CTX_free@OPENSSL_1_1_1b'

Probably there is packet broken in Centos8.2 because in system there is openssl1.1.1c installed and there is no openssl1.1.1b.
/usr/lib64/libk5crypto.so.3 (that belongs to package: krb5-libs-1.17-18) has reference to openssl1.1.1b

I think this is OS problem rather than vagrant-libvirt plugin. Maybe vagrant-libvirt can ignore this error during linking stage but I am not sure.

**Comment by BeRoots** [comment]
After debuging step by step with the advise around missed `libvirt-devel qemu-kvm libvirt virt-manager libguestfs-tools bridge-utils virt-install`. It seems is only libvirt-devel. But there is another problem after with ssl on my f32 workstation. So the comment from @kcem is also another problem.

**Comment by jchook** [comment]
1. There are ~12 different issues that all mention using `CONFIGURE_ARGS` to specify exact library locations. Why is this needed? Are `/usr/lib/libvirt` and `/usr/lib64` not expected locations for these libraries? Isn't this a bug in itself?

2. I finally got vagrant-libvirt to compile by using `ld.gold` instead of `ld`, described [in this issue comment](https://github.com/hashicorp/vagrant/issues/7039#issuecomment-441291810).

```
rm /usr/bin/ld
ln -s /usr/bin/ld.gold /usr/bin/ld
```

**Comment by kcem** [comment]
I solved this issue using Ruby from OS, instead of Vagrant.

```
sudo -i
yum install ruby
cd /opt/vagrant/embedded/bin
mv ruby ruby-2.6.0
ln -s /usr/bin/ruby
```

**Comment by kcem** [comment]
I solved this issue by using Ruby from OS instead of embedded.

```
sudo -i
yum install ruby ruby-devel redhat-rpm-config
cd /opt/vagrant/embedded/bin
mv ruby ruby-2.6.0
ln -s /usr/bin/ruby
```

**Comment by pvalena** [comment]
> This is workaround only.

@kcem Wouldn't using `vagrant` and `vagrant-libvirt` from my COPR work for you? (I'm Fedora Ruby+Vagrant packager.)

**Comment by nqb** [comment]
On a Debian buster host, I was able to install upstream Debian package (vagrant 2.2.10) with vagrant-libvirt 0.2.1.

**Comment by kcem** [comment]
> > This is workaround only.
> 
> @kcem Wouldn't using `vagrant` and `vagrant-libvirt` from my COPR work for you? (I'm Fedora Ruby+Vagrant packager.)

Thanks. I missed your post. I'll try it.

**Comment by soapy1** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
