### ISSUE TITLE
Git push on vagrant not working

### ISSUE THREAD

**Issue by paramda** [hashicorp/vagrant#11785]
Trying a lab from Linux Foundation for vagrant/virtualbox with git and running into issues- 
  -Version vagrant 2.2.9
  -Created a Hello repo on github and git clone in vagrant worked
  -Made minor changes to README & comitted. 
  -Pushing changes like this "git push origin master", When asked for username and password ,I enter creds. These work on github.
  -2FA is enabled but getting error "Fatal: Authentication failed for https://github.com/username/Hello.git"

It doesn't ask for a token or anything. What am I doing wrong? Thanks in advance.

**Comment by jbonhag** [comment]
Hi @paramda,

Thanks for checking out Vagrant! If you're using 2FA with GitHub, you need to create a personal access token to push to HTTPS URLs on the command line:

https://docs.github.com/en/github/authenticating-to-github/accessing-github-using-two-factor-authentication#authenticating-on-the-command-line-using-https

You might also consider [caching your GitHub credentials](https://docs.github.com/en/github/using-git/caching-your-github-credentials-in-git) so Git will remember your credentials.

Cheers and have a great day! 😄

**Comment by paramda** [comment]
Worked like a charm! Thank you @jbonhag :)
