### ISSUE TITLE
Vagrant complains about no guest additions when they are actually there

### ISSUE THREAD

**Issue by cayblood** [hashicorp/vagrant#1179]
When I do an initial up on a veewee box that has the guest additions installed on it, vagrant seems to be erroneously reporting that they are not installed. If I run the up with debug info on, as follows:

<pre>
$ VAGRANT_LOG=INFO vagrant up --no-provision
...
INFO subprocess: Starting process: ["VBoxManage", "guestproperty", "get", "715acd52-07f1-4322-a69f-ef7a7d2fd3fa", "/VirtualBox/GuestAdd/Version"]
 INFO interface: warn: No guest additions were detected on the base box for this VM! Guest
additions are required for forwarded ports, shared folders, host only
networking, and more. If SSH fails on this machine, please install
the guest additions and repackage the box to continue.
</pre>

After startup, when I try to run the same command, it works:

<pre>
$ VBoxManage guestproperty get 715acd52-07f1-4322-a69f-ef7a7d2fd3fa /VirtualBox/GuestAdd/Version
Value: 4.2.0
</pre>

It might be that vagrant is being a little over-eager in running this check before all the necessary services have been started up.

**Comment by tnt** [comment]
I also get a similar warning with 1.7.2.
