### ISSUE TITLE
Inconsistent behavior with the eval command in the inline shell provisioning 

### ISSUE THREAD

**Issue by theJaxon** [hashicorp/vagrant#11796]
### Vagrant version
Vagrant 2.2.9

### Host operating system
Ubuntu 20.04 LTS 

### Guest operating system
bento/centos-8

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.box_check_update = false

  config.vm.provision "shell", inline: <<-SHELL
  #sudo yum update -y
  sudo yum install -y python3 python3-pip
  alternatives --set python /usr/bin/python3 
  sudo useradd ansible
  echo ansible | passwd --stdin ansible # Set default ansible password to ansible
  echo "ansible ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible # Grant ansible user the sudo priviliges without demanding a password [privilege escalation]
  SHELL

  (1..3).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "bento/centos-8"
      node.vm.hostname = "ansible-#{i}"
      node.vm.network "private_network", ip: "192.168.50.#{i + 210}"
      node.vm.provision "shell", inline:  <<-SHELL
      SHELL
    end
  end

  config.vm.define "controller" do |controller|
    controller.vm.box = "bento/centos-8"
    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "192.168.50.210"

    controller.vm.provision "shell", inline: <<-SHELL
            
    sudo echo "192.168.50.211 ansible1" >> /etc/hosts
    sudo echo "192.168.50.212 ansible2" >> /etc/hosts
    sudo echo "192.168.50.213 ansible3" >> /etc/hosts
    
    sudo yum update -y
    sudo yum install -y python3-pip # Required for installing ansible using pip3

    # Use ansible user instead of vagrant
    sudo echo "sudo su - ansible" >> /home/vagrant/.bash_profile

    # [1]
    sudo -u ansible /bin/sh <<\ANSIBLE_USER
      cd /home/ansible
      mkdir -v .ssh
      # Install sshpass from source 
      wget http://sourceforge.net/projects/sshpass/files/latest/download -O sshpass.tar.gz
      tar xvf sshpass.tar.gz && cd sshpass-1.06
      sudo yum install -y gcc vim 
      sudo ./configure && sudo make install && sudo mv /usr/local/bin/sshpass /bin

      pip3 install ansible --user
      echo $(ansible --version)

      ssh-keygen -N "" -f ansible # Generate public and private key pairs (ansible, ansible.pub)

      # Add public key to all managed servers [2]
      sshpass -p "ansible" ssh-copy-id -o StrictHostKeyChecking=no -i ansible.pub ansible@ansible1
      sshpass -p "ansible" ssh-copy-id -o StrictHostKeyChecking=no -i ansible.pub ansible@ansible2
      sshpass -p "ansible" ssh-copy-id -o StrictHostKeyChecking=no -i ansible.pub ansible@ansible3


      # use ansible user & cd into the directory containing ssh keys [3][4]
      sudo echo 'eval "$(ssh-agent -s)"' >> /home/ansible/.bash_profile # Still problematic and must be replaced with wget
      sudo echo "ssh-add /home/ansible/sshpass-1.06/ansible" >> /home/ansible/.bash_profile

ANSIBLE_USER
  SHELL
  end

end

```

### Expected behavior
`sudo echo 'eval "$(ssh-agent -s)"' >> /home/ansible/.bash_profile` should just add the line `eval "$(ssh-agent -s)"` to the file but the command gets evaluated anyway and i end up with 
```
eval "SSH_AUTH_SOCK=/tmp/ssh-vAiPBABpKf3B/agent.4576; export SSH_AUTH_SOCK;
SSH_AGENT_PID=4577; export SSH_AGENT_PID;
echo Agent pid 4577;"
```
What should have happened?
Running this command again normally after `vagrant ssh controller` gives the expected output (so provisioning behavior is just different i don't know why)
so now after typing `sudo echo 'eval "$(ssh-agent -s)"' >> /home/ansible/.bash_profile ` and checking the file again i find the line `eval "$(ssh-agent -s)" ` correctly added

### Steps to reproduce

1. use the Vagrantfile provided, and then after provisioning do `cat /home/ansible/.bash_profile` you'll find the command executed (so the text wasn't added to the file just the result of the eval command)
2. `vagrant ssh controller` then `sudo echo 'eval "$(ssh-agent -s)"' >> /home/ansible/.bash_profile` now you see the line correctly added

### References
https://stackoverflow.com/questions/28037232/escape-eval-command-when-appending-to-file

- ...

**Comment by jbonhag** [comment]
Hi there,

Thanks for opening an issue with Vagrant! Because of the way that strings are handled in Ruby, the `<<\ANSIBLE_USER` actually gets read in as `<<ANSIBLE_USER`, which performing the subshell evaluation earlier than you want. I'd suggest using the quoted-heredoc style of `<<'ANSIBLE_USER'` instead.

Alternatively, you could put your provisioning script into an external file and use the `path` option of the shell provisioner:

```ruby
config.vm.provision "shell", path: "provision.sh"
```

Cheers! 😄

**Comment by theJaxon** [comment]
> <<'ANSIBLE_USER'
Using the quoted style did fix the issue, thank you, much appreciated.
