### ISSUE TITLE
Vagrant Not Using Hyperv Provider

### ISSUE THREAD

**Issue by ossie-git** [hashicorp/vagrant#11808]
### Vagrant version

```
C:\Users\test01\VMs\Vagrant\Ubuntu2004>vagrant --version
Vagrant 2.2.9
```

### Host operating system

Windows 10 Professional

```
PS C:\Users\test01\VMs\Vagrant\Ubuntu2004> (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ReleaseId).ReleaseId
1909
```

### Guest operating system

Ubuntu 20.04

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.provider "hyperv"
  config.vm.box = "generic/ubuntu2004"
end
```

### Debug output

https://gist.github.com/ossie-git/d89faad2b9d224b38afce6361c66e9a8 

### Expected behavior

It should use the Hyperv provider instead of looking for VirtualBox

### Actual behavior

It looks for the VirtualBox provider

### Steps to reproduce

1. create a Vagrantfile as shown above
2. run "vagrant up --provider hyperv"

**NOTE** Hyperv is enabled as shown below:

```
PS C:\> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All


Path          :
Online        : True
RestartNeeded : False
```

**Comment by demdante** [comment]
From what I see in the output, It looks like the vagrant box that you reference is already stored on your computer.  What I would do (as I have run into similar issues in the past) is navigate to the directory containing your downloaded vagrant boxes (C:/Users/test01/.vagrant.d/boxes/) and take a look at the vagrantfile that came packaged with the box (if there is one).  Maybe the packaged vagrantfile has a declared provider that is overriding your vagrantfile provider..

**Comment by ossie-git** [comment]
Thanks. But the vagrant box is a hyperv box as shown below:

```
PS C:\Users\test01> vagrant box list
generic/ubuntu2004 (hyperv, 3.0.22)
```

**Comment by ossie-git** [comment]
Based on your comment, I decided to delete the directory with the Vagrant box and start from scratch and it appears to have worked. For some strange reason, it appears that the first time I ran **vagrant up** or **vagrant box add**, I didn't tell it to use the **hyperv** provider and this added something to the boxes directory that forces it to use Virtualbox (even though the output of the command shows that it downloaded the hyperv version as shown below)

```
PS C:\Users\test01> vagrant box list
generic/ubuntu2004 (hyperv, 3.0.22)
```

I also deleted the .vagrant directory that resulted from the last failed **vagrant up** run

This is what I got after removing the directory and starting from scratch:

```
PS C:\Users\test01\VMs\Vagrant\Alpine38> cat .\Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.provider "hyperv"
  config.vm.box = "generic/alpine38"
end
```

```
PS C:\Users\test01\VMs\Vagrant\Alpine38> vagrant up --provider hyperv
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
==> default: Box 'generic/alpine38' could not be found. Attempting to find and install...
    default: Box Provider: hyperv
    default: Box Version: >= 0
==> default: Loading metadata for box 'generic/alpine38'
    default: URL: https://vagrantcloud.com/generic/alpine38
==> default: Adding box 'generic/alpine38' (v3.0.22) for provider: hyperv
    default: Downloading: https://vagrantcloud.com/generic/boxes/alpine38/versions/3.0.22/providers/hyperv.box
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
    default:
    default: Calculating and comparing box checksum...
==> default: Importing a Hyper-V instance
    default: Creating and registering the VM...
    default: Successfully imported VM
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) Default Switch
    default: 2) External Switch 1
    default:
    default: What switch would you like to use? 2
    default: Configuring the VM...
==> default: Starting the machine...
==> default: Waiting for the machine to report its IP address...
    default: Timeout: 120 seconds
    default: IP: 192.168.1.114
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.1.114:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
PS C:\Users\test01\VMs\Vagrant\Alpine38> vagrant ssh
alpine38:~$
```

So my suggestion for anyone who runs into the same problem:

- delete your Vagrant boxes directory
- delete any .vagrant directory from failed attempts in the same directory as your Vagrantfile

**Comment by chrisroberts** [comment]
Based on the backtrace provided within the debug output this appears to be something which was caused from the disksize plugin. Likely some configuration which was leftover and cleaning the local project directory resolved. Closing as this appears to be resolved.

Cheers!
