### ISSUE TITLE
[FCOS] Private network interface improperly configured

### ISSUE THREAD

**Issue by thegreenbear** [hashicorp/vagrant#11804]
### Vagrant version
Vagrant 2.2.9

### Host operating system
Ubuntu 20.04.1 LTS
5.4.0-42-generic

### Guest operating system
Fedora CoreOS 31.20200517.3

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "thegreenbear/fedora-coreos"
  config.vm.box_version = "31.20200517.3.0"
  config.vm.network "private_network", ip: "192.168.33.10"
end
```

### Debug output
Here is the gist: https://gist.github.com/thegreenbear/f1a9be227ea50b2537bf8378cca9357e

### Expected behavior
An network interface should have been created with IP 192.168.33.10.

### Actual behavior
The network interface is created but the IP is not configured.
```
[vagrant@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:06:42:03 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic noprefixroute eth0
       valid_lft 85448sec preferred_lft 85448sec
    inet6 fe80::3a8b:86cb:d872:1082/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:33:28:9c brd ff:ff:ff:ff:ff:ff
```

### What actually happened?
It seems vagrant fails to configure properly the interface.
This part is especially interesting:
```
 INFO ssh: Execute: nmcli d disconnect iface 'eth1'
mv -f '/tmp/vagrant-network-entry-eth1-1596624057-0' '/etc/sysconfig/network-scripts/ifcfg-eth1'
(test -f /etc/init.d/NetworkManager && /etc/init.d/NetworkManager restart) || ((systemctl | grep NetworkManager.service) && systemctl restart NetworkManager) (sudo=true)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
**DEBUG ssh: stderr: Error: Device 'iface' not found.
DEBUG ssh: stderr: Error: not all devices found.**
DEBUG ssh: Exit status: 0
```
### Steps to reproduce

1. Copy vagrant file 
2. Vagrant up

### More

I am happy to contribute if someone points me in the right direction.
It seems vagrant tries to configure the network interface using a script in /etc/config/network-scripts but it is not clear to me why the interface is not found.

The content of is /etc/sysconfig/network-scripts/ifcfg-eth1 :
```
[vagrant@localhost ~]$ cat /etc/sysconfig/network-scripts/ifcfg-eth1 
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
NM_CONTROLLED=yes
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.33.10
NETMASK=255.255.255.0
DEVICE=eth1
PEERDNS=no
#VAGRANT-END
```
Looks correct to me. So I maybe an integration issue sysconfig / NetworkManager?

**Comment by thegreenbear** [comment]
Digging a bit more, the problem is the following:
- the network manager is not configured to use the ifcfg-rh plug in so it cannot process the ifcfg-eth1 file
- enabling the plugin did not fix the issue as the library of the plugin itself is missing from the image

I tried to install it using rpm-ostree but could not find a package with it.

As a work-around, I create the interface using nmcli using a provisioner in the Vagrant file.

**Comment by MisterWS** [comment]
I have a similar use case (for public network interfaces) on FCOS. Is there any likelihood of this being progressed? It looks like there's a general move away from ifcfg-rh [https://fedoraproject.org/wiki/Changes/NetworkManager_keyfile_instead_of_ifcfg_rh](https://fedoraproject.org/wiki/Changes/NetworkManager_keyfile_instead_of_ifcfg_rh).

**Comment by chrisroberts** [comment]
Just an update on this, after I looked into it a bit the coreos guest support wasn't working automatically. The coreos network configuration currently uses cloud-init (which has been deprecated), but the atomic guest's detection implementation was so loose that it would match against coreos. So coreos networking was simply be treated like fedora. The PR linked above fixes up the guest detection and adds network manager based configuration via keyfiles. It'll be getting included in the next release.

**Comment by thegreenbear** [comment]
Super! Thanks for the fix.
