### ISSUE TITLE
Broken docs link

### ISSUE THREAD

**Issue by Muheli** [hashicorp/vagrant#11812]
Reporting broken links from "Learn" tab on hashicorp.com home page to documentation pages

Affects Vagrant and Packer. May affect other products.

The "Learn" tab on hashicorp.com home page contains the following links which result in a 404 error:
- https://www.vagrantup.com/docs/index.html
- https://www.packer.io/docs/index.html

Manually removing the trailing "index.html" fixes this
- https://www.vagrantup.com/docs
- https://www.packer.io/docs

**Comment by chrisroberts** [comment]
@Muheli Thanks for letting us know. The links have been updated and should be working as expected.

Cheers!
