### ISSUE TITLE
SSH auth method: private key

### ISSUE THREAD

**Issue by Johnpc123** [hashicorp/vagrant#11817]
#11759 
# Vagrant version
Vagrant 2.2.9

### Host operating system
Windows 7 

### Guest operating system
Ubuntu 20.04 server

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# # vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = true
  config.vm.provider "virtualbox"
  
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.gui = false
    v.cpus = 2
    #v.linked_clone = true
    v.customize ['modifyvm', :id, '--audio', 'none']
    v.customize ['modifyvm', :id, '--cableconnected1', 'on']
  end
      config.vm.hostname = "kubemain.cluster.test"
      config.vm.network :private_network, ip:"192.168.58.12", name: "VirtualBox Host-Only Ethernet Adapter #3"
 end
```

### Debug output
https://gist.github.com/Johnpc123/1a1498a0b9cfe0015e0d390ca1bad52a

### Expected behavior
Vagrant should bring up a VM on a pre existing host-only private_network with a static ip

### Actual behavior
Vagrant hangs

### Steps to reproduce
1. configure a host-only private_network 
2. select an ip in the target network range for the config.vm.network
3. find `VBoxNetworkName` with `vboxmanage list hostonlyifs`
4. `vagrant up`
5. ...

### References
My setup was working perfectly.  I was able to provision, destroy and re-provision without issue. This problem started at a seemingly random point in my workflow. 

Then this happened, ssh stopped connecting on initial vagrant up. Smells like a virtual networking bork up.  
There are many, many, similar references   

For example:
- https://github.com/hashicorp/vagrant/issues/8157#issuecomment-579041680
- https://github.com/hashicorp/vagrant/issues/11626
- https://github.com/hashicorp/vagrant/issues/9898
- https://github.com/hashicorp/vagrant/issues/9323
- https://github.com/hashicorp/vagrant/issues/9406
...
...

Due to suggestions in previous issues I tried a few things.
I verified VT/x is on in my bios. .. didn't work.
Set the network adapter to cable attached. .. didn't work.
Reinstalled both Vagrant and VirtualBox .. didn't work.
Recreated the virtual network adapter and retried ... didn't work.
Changing to creating a new private network and dhcp `config.vm.network :private_network ,type: "dhcp"`  .. didn't work.
Someone suggested running `FOR /L %%A IN (2,1,11) DO vboxmanage hostonlyif remove "VirtualBox Host-Only Network #%%A"` .. didn't work.

Foolishly tried nesting in a VM host and bridging to it's host network network adapter ... nada, but that was never going to work.

No clue.

**Comment by chrisroberts** [comment]
Hi there,

Please try adding the following to your Vagrantfile within the virtualbox provider block:

`v.customize ["modifyvm", :id, "--uart1", "off"]`

and see if that resolves your issue.

**Comment by Johnpc123** [comment]
No, didn't resolve my issue.   Vagrant is still hanging.  



I've done the following to generate as clean a debug log as possible:

> re-reinstalled both Vagrant and VirtualBox 
> deleted extra Virtual adapters and the .vagrant folder
> removed all other VirtualBox registrations
> Pruned the Vagrant global config
> reset hostonly adapter ip in Vbox so that it appears in the debug log

https://gist.github.com/Johnpc123/1a1498a0b9cfe0015e0d390ca1bad52a

There is a long history for this behaviour https://www.virtualbox.org/ticket/8796?cversion=0&cnum_hist=16
Is the initial step of setup, port forwarding for ssh 22:127.0.0.1:222x the problem?  

Is there any other way to configure networking / set the ip addresses in the Guest? ... Building a install image with an init script baked in would be fine. Anything that's reliably reusable.  Does Vagrant have a library of those?

**Comment by Johnpc123** [comment]
PS G:\vm\jpc> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/focal64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/focal64' version '20200804.0.0' is up to date...
==> default: Setting the name of the VM: jpc_default_1597236075101_37777
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

**Comment by chrisroberts** [comment]
Hi there,

After reproducing this locally, adding the following to your provider block should resolve the issue:

```ruby
v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
```

This is due to a serial setup included within the Ubuntu Vagrant boxes. Just disabling the serial port is ineffective due to the boot parameters which are configured within the image in the box. More information about this can be found here: https://bugs.launchpad.net/cloud-images/+bug/1829625

The bento boxes are highly reliable alternative and may be worth looking into as a replacement.

Cheers!

**Comment by Johnpc123** [comment]
Using a 'bento box' by replacing this line has solved my issue 

`config.vm.box = "bento/ubuntu-20.04"`

That other thing about serial ports and TTY, not so much, interesting to see though.

Thank you
