### ISSUE TITLE
Vagrant Up fails with VMware

### ISSUE THREAD

**Issue by jeremymcgee73** [hashicorp/vagrant#11823]
### Vagrant version

Vagrant 2.2.9

### Host operating system

Windows 10 Pro - 1909

### Guest operating system

See below

### Vagrantfile

```ruby
# vagrant init hashicorp/bionic64
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
end
```

### Debug output

https://gist.github.com/jeremymcgee73/fcf71079fcbe4f9187556c9c6433a430

### Expected behavior

Vagrant should spin up a VM on VMware Workstation Pro 15.5.6 build-16341506. I'm not 100% sure what is going on. It seems that vagrant is having issues calling the vmnet API. I am able to run VMs in VMware Workstation without Vagrant.

### Actual behavior
I get an error related to an API call.

### Steps to reproduce

1. Run Vagrant Up

**Comment by soapy1** [comment]
Hmmm, I wonder if this is the same issue as https://github.com/hashicorp/vagrant/issues/11815? 

Which version of the vmware-utility is installed? The latest version is 1.0.11 and is available [on the utility download page](https://www.vagrantup.com/vmware/downloads.html).

**Comment by jeremymcgee73** [comment]
Installing the new version did solve the problem. Thanks!
