### ISSUE TITLE
VirtualBox VAGRANT_EXPERIMENTAL="disks" works only for SATA Controller and not for SCSI Controller

### ISSUE THREAD

**Issue by BeckerFrank** [hashicorp/vagrant#11821]
### Vagrant
2.2.9

### Host operating system 

Mac OS X 10.15.6

### Guest operating system

bionic64

### Vagrantfile

```
Vagrant.configure("2") do |config|
  config.vm.define "hashicorp" do |h|
    h.vm.box = "ubuntu/bionic64"
    h.vm.provider "virtualbox" do |v|
    h.vm.disk :disk, size: "100GB", primary: true
    end
  end
end
```
### Debug output

```
==> vagrant: You have requested to enabled the experimental flag with the following features:
==> vagrant: 
==> vagrant: Features:  disks
==> vagrant: 
==> vagrant: Please use with caution, as some of the features may not be fully
==> vagrant: functional yet.
Bringing machine 'hashicorp' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* There are more than one primary disks defined for guest 'hashicorp'. Please ensure that only one disk has been defined as a primary disk.
* Duplicate disk names defined: 'vagrant_primary'. Disk names must be unique.

```
### Expected behavior

Start of the virtual machine with a primary disk of 100GB

### Actual behavior

Error: There are more than one primary disks defined for guest 'hashicorp'.

Reason is that the box ubuntu/bionic64 use SCSI Controller and not the SATA Controller

### Steps to reproduce

1. export VAGRANT_EXPERIMENTAL="disks"
2. vagrant up
3. change the box from ubuntu/bionic64 to hashicorp/bionic64 solve this because this box use the SATA Controller

### References

GH-11349

**Comment by soapy1** [comment]
Heya, I was able to reproduce this issue with the provided Vagrant file. However, I noticed that the disk was defined in an unexpected spot. I was able to resolve the issue by moving the disk out of the virtual box config:

```
Vagrant.configure("2") do |config|
  config.vm.define "hashicorp" do |h|
    h.vm.box = "ubuntu/bionic64"
    h.vm.disk :disk, size: "100GB", primary: true   
    h.vm.provider "virtualbox" do |v|
    end
  end
end
```

Then I can see in virtualbox that I have a 100 GB primary disk.

**Comment by BeckerFrank** [comment]
> Heya, I was able to reproduce this issue with the provided Vagrant file. However, I noticed that the disk was defined in an unexpected spot. I was able to resolve the issue by moving the disk out of the virtual box config:
> 
> ```
> Vagrant.configure("2") do |config|
>   config.vm.define "hashicorp" do |h|
>     h.vm.box = "ubuntu/bionic64"
>     h.vm.disk :disk, size: "100GB", primary: true   
>     h.vm.provider "virtualbox" do |v|
>     end
>   end
> end
> ```
> 
> Then I can see in virtualbox that I have a 100 GB primary disk.

What version of VirtualBox did you use?
I have 6.1.12 and if I try this I got the following error.
```
VAGRANT_EXPERIMENTAL="disks" vagrant up
==> vagrant: You have requested to enabled the experimental flag with the following features:
==> vagrant: 
==> vagrant: Features:  disks
==> vagrant: 
==> vagrant: Please use with caution, as some of the features may not be fully
==> vagrant: functional yet.
Bringing machine 'hashicorp' up with 'virtualbox' provider...
==> hashicorp: Importing base box 'ubuntu/bionic64'...
==> hashicorp: Matching MAC address for NAT networking...
==> hashicorp: Checking if box 'ubuntu/bionic64' version '20200812.0.0' is up to date...
==> hashicorp: Setting the name of the VM: test_hashicorp_1597341210347_16985
==> hashicorp: Fixed port collision for 22 => 2222. Now on port 2200.
==> hashicorp: Clearing any previously set network interfaces...
==> hashicorp: Preparing network interfaces based on configuration...
    hashicorp: Adapter 1: nat
==> hashicorp: Forwarding ports...
    hashicorp: 22 (guest) => 2200 (host) (adapter 1)
==> hashicorp: Configuring storage mediums...
    hashicorp: Disk 'vagrant_primary' not found in guest. Creating and attaching disk to guest...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["storageattach", "771b4b3a-eb82-430c-9ec2-16768aec4fcd", "--storagectl", "SATA Controller", "--port", "0", "--device", "0", "--type", "hdd", "--medium", "/Users/frank/VirtualBox VMs/test_hashicorp_1597341210347_16985/vagrant_primary.vdi", "--comment", "This disk is managed externally by Vagrant. Removing or adjusting settings could potentially cause issues with Vagrant."]

Stderr: VBoxManage: error: Could not find a controller named 'SATA Controller'

```

**Comment by soapy1** [comment]
Ah right. Can confirm this is broken in Vagrant 2.2.9. This PR https://github.com/hashicorp/vagrant/pull/11613 fixes it, so the fix is available on Vagrant's main branch and will be included in the next release.

**Comment by BeckerFrank** [comment]
Should I close this Issue or should we wait until the next release is available?

**Comment by soapy1** [comment]
Closing this issue, as a fix has been merged and will be included in the upcoming release 😄
