### ISSUE TITLE
Vagrantfile intermittently fails with winrm_port undefined method

### ISSUE THREAD

**Issue by shoddyguard** [hashicorp/vagrant#11828]
Occasionally when trying to `vagrant up` from the below vagrantfile we're getting the error: 
`C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/winrm/helper.rb:61:in winrm_port': undefined method each for nil:NilClass (NoMethodError)`

This happens randomly and re-running `vagrant up` will result in the machines getting built correctly. This is happening across multiple hosts.

I've tried to remove a lot of the fluff from the included vagrantfile while still including the parts relevant to our build process, hopefully it contains all the relevant info.

### Vagrant version

2.2.7

### Host operating system

Windows Server 2019

### Guest operating system

Various Windows - though in the specific example provided Windows Server 2019

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'getoptlong'

opts = GetoptLong.new(
  [ '--noDevTools', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--nodevtools', GetoptLong::OPTIONAL_ARGUMENT ]
)

installDevToolsLocally = true

opts.ordering=(GetoptLong::REQUIRE_ORDER)

opts.each do |opt, arg|
  case opt
    when '--noDevTools'
        installDevToolsLocally=false
    when '--nodevtools'
        installDevToolsLocally=false
  end
end

machines_for_application_tests=[
   {
    :name => "sql2019", # tests a clean installation
    :box_name => "red-gate/windows-2019-sql2019",
    :box_version => '>= 2020.03.24',
    :sql_server_instance_name => "sql2019",
    :ip => "192.168.254.119"
   },
]

Vagrant.configure(2) do |config|
  machines_for_application_tests.each do |machine|

    config.vm.define machine[:name] do |node|

      node.vm.box = machine[:box_name]
      node.vm.box_version = machine[:box_version]
      config.vm.network "private_network", ip: machine[:ip]
      node.vm.boot_timeout = 600

      node.vm.provider "virtualbox" do |vb|
        vb.customize 'pre-boot', ["setextradata", :id, "GUI/LastGuestSizeHint", "1152,864"]
        vb.gui = ENV['TEAMCITY_VERSION'].nil?
        vb.linked_clone = true
        vb.memory = "2048"
        vb.cpus = 2
      end
  end
end
```

### Expected behavior

The machine should come up

### Actual behavior

We get the error: `C:/HashiCorp/Vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/plugins/communicators/winrm/helper.rb:61:in winrm_port': undefined method each for nil:NilClass (NoMethodError)`

### Steps to reproduce

1. `vagrant up`

### References

Cli output: https://gist.github.com/shoddyguard/0540a1c849d5f9a024b7fedb5c91980e

**Comment by soapy1** [comment]
Thanks for submitting an issue. It looks like the bit that is causing the issue to surface is [this part](https://gist.github.com/shoddyguard/0540a1c849d5f9a024b7fedb5c91980e#file-gistfile1-txt-L59) that is halting the vm part way through bringing the machine up. https://github.com/hashicorp/vagrant/pull/11831 should resolve the error, however I expect it may still leave the Vagrant machine a little borked.

> I've tried to remove a lot of the fluff from the included vagrantfile 

Is there any part of the omitted Vagrantfile that will force a halting of the vm? Or are there any additional Vagrant plugins installed?

**Comment by shoddyguard** [comment]
Thanks for looking into this so qucikly.

We are not using any additional plugins with Vagrant (and the machines running Vagrant are rebuilt nightly).
In terms of the rest of the stuff cut out from the Vagrant file it was a bunch of `node.provision` blocks which all pointed to PowerShell scripts, I'll check in with the team that wrote the scripts and ensure there's nothing in there that would force a reboot or shutdown of the VM.

The full vagrantfile can be found here: https://gist.github.com/shoddyguard/ea98ae87049a1533fc564c1789dc43d7 in case there's anything obvious missing 

The weird thing is, after the `vagrant up` fails if we `vagrant destroy` and `vagrant up` again it'll work.

**Comment by soapy1** [comment]
@shoddyguard a new version of Vagrant has been released (2.2.10). Are you able to update, does it resolve the issue?

**Comment by shoddyguard** [comment]
Thank you @soapy1 I'll update that on our infrastructure today and report back. :)

**Comment by shoddyguard** [comment]
I'm going to close this one off now as you've kindly made the fix and as this was super intermittent anyways I don't think we'd see it for a while even if it does come back.

Thanks again for getting this rolled out so quickly. :)
