### ISSUE TITLE
MacOS Catalina vagrant hangs on Mounting NFS shared folders....

### ISSUE THREAD

**Issue by bardsoleim** [hashicorp/vagrant#11834]
Vagrant hangs after using command vagrant up on  Mounting NFS shared folders
### Vagrant version

2.2.9

### Host operating system

MacOS Catalina 10.15.6

### Guest operating system

Red Hat 64bit

### Vagrantfile

```ruby
# coding: utf-8

require 'fileutils'

# Module to check for OS version. Vagrant shared folder config will vary depending on the OS.
# Windows users will have to make due with rsync.
module OS
    def OS.windows?
        (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    end
    def OS.mac?
        (/darwin/ =~ RUBY_PLATFORM) != nil
    end
    def OS.unix?
        !OS.windows?
    end
    def OS.linux?
        OS.unix? and not OS.mac?
    end
end

# Make sure we have vagrant-vbguest installed
if !Vagrant.has_plugin?('vagrant-vbguest')
	puts 'vagrant-vbguest plugin required. Run `vagrant plugin install vagrant-vbguest` to install'
	abort
end



Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 4
    v.memory = 4048
    v.customize ["modifyvm", :id, "--audio", "none"]
  end

  is_windows_host = "#{OS.windows?}"
  puts "is_windows_host: #{OS.windows?}"
  if OS.windows?
    # puts "Vagrant launched from windows. Using rsync for shared folder."
    # config.vm.synced_folder '.', '/vagrant', type: "rsync", rsync__auto: true
    puts "Vagrant launched from windows. Using NFS for shared folder."
    config.vm.synced_folder '.', '/vagrant', nfs: true, type: "nfs", nfs_export: false
  else
    puts "Vagrant launched from *nix, using NFS for shared folder."
    config.vm.synced_folder '.', '/vagrant', nfs: true
    end
    config.vm.synced_folder nfsPath, "/vagrant", type: "nfs"
  end
  # Use NFS for shared folders for better performance

  
  config.vm.network "private_network", ip: "192.168.99.50"
  # Forwarde port 8080 for Tomcat og 8000 for remote debugging
  config.vm.network "forwarded_port", guest: 8090, host: 8090 # Tomcat HTTP
  config.vm.network "forwarded_port", guest: 5005, host: 5005 # Java Debug

  # Execute provision script
  config.vm.provision :shell, :path => "vagrant/bootstrap.sh"
  config.vm.provision "file", source: "vagrant/.bashrc", destination: "~/.bashrc"
  config.vm.provision "shell", privileged: true, inline: "timedatectl set-timezone Europe/Oslo"

  ssh_key_path = ENV['SSH_KEY'] || File.join(Dir.home, ".ssh", "id_rsa")
  if File.exist?(ssh_key_path)
    ssh_key = IO.read(ssh_key_path)
  else
    raise Vagrant::Errors::VagrantError.new, "Key missing #{ssh_key_path}, set SSH_KEY=/path/to/ssh/key, or comment out this feature."
  end
  config.vm.provision :shell, :inline => "echo 'Windows-specific: Copying a local SSH Key to VM for provisioning...' && mkdir -p /home/vagrant/.ssh && echo '#{ssh_key}' > /home/vagrant/.ssh/id_rsa && chmod 600 /home/vagrant/.ssh/id_rsa  && chown vagrant:vagrant /home/vagrant/.ssh/id_rsa"
end
```

### Debug output
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mount -o vers=3,udp 192.168.99.1:/System/Volumes/Data/Users/USERNAME/src/project /vagrant
Stdout from the command:
Stderr from the command:

mount.nfs: Connection timed out
### Expected behavior

It should share NFS folder

### Actual behavior
hangs on:   default: Mounting NFS shared folders...

### Steps to reproduce
vagrant up

**Comment by soapy1** [comment]
From the connection time out error, it seems like the nfs server is not running or the export is not happening successfully. You could check for if the mount is available using the command `showmount -e <ip>`. If the export does not appear to be available on the guest and host, check if the nfs server is running using `ps aux | grep nfsd` on the host. Further, ensure that the folder being exported is included in `/etc/exports`. This file can be verified using the command `nfsd checkexports`.

**Comment by FugueDev** [comment]
folder is included in /etc/exports,
"showmount -e" prints out correct folder however "nfsd checkexports" does and returns nothing.

showmount -e ip returns cannot retrive info from host.

**Comment by soapy1** [comment]
hmmm, it seems like nfs it probably all in order. Another thing that might be causing issues is firewalls including iptables. Can you verify that the ports required for nfs are not being blocked on the guest. I believe they are 111 and 2049.

**Comment by FugueDev** [comment]
Firewall was off and encryption was off.

**Comment by soapy1** [comment]
If this is still an issue for you, please check out the Vagrant guide for troubleshooring NFS issues here:
https://www.vagrantup.com/docs/synced-folders/nfs.html#troubleshooting-nfs-issues. It covers the most common hiccups in setting up NFS with Vagrant.

**Comment by edwardcasbon** [comment]
Did you get anywhere with this please @FugueDev ? I'm having the same issue.

**Comment by FugueDev** [comment]
No, sorry. Tried everything. Works flawlessly on linux or windows.

**Comment by lcihaeon** [comment]
I had the exact same issue as @FugueDev, and now something that I've tried has made it work. I'm not entirely sure if all of them mattered, but these are the changes I've made:

1. granted Full Disk Access privilege to `/sbin/nfsd` on my Mac, as suggested in [this article](https://blog.docksal.io/nfs-access-issues-on-macos-10-15-catalina-75cd23606913)
2. wiped out the contents of `/etc/exports` on my Mac, and restarted the nfs daemon `sudo nfsd restart`
3. destroyed vagrant and rerun `vagrant up`

after the first three steps, the error went away. Hope it helps.

**Comment by tmm1** [comment]
It appears that vagrant is prefixing `/System/Volumes/Data` to its entries in `/etc/exports`. This causes mounts to fail. I had to replicate the lines myself without the prefix and then things started working.

**Comment by joelpittet** [comment]
@tmm1 I've had no luck with trimming that off them, and that is something that Catalina brought in. https://github.com/hashicorp/vagrant/issues/10961

**Comment by darwinjerome** [comment]
> It appears that vagrant is prefixing `/System/Volumes/Data` to its entries in `/etc/exports`. This causes mounts to fail. I had to replicate the lines myself without the prefix and then things started working.

How did you remove the line? It seems that vagrant is adding `/System/Volumes/Data` on reload.

**Comment by tmm1** [comment]
My solution is to edit the file, replicate the line without the vagrant comments and remove the prefix. That works for me.

**Comment by FugueDev** [comment]
FYI the problem persist in Big Sur

**Comment by darwinthefold** [comment]
I have compiled a solution that worked for my setup (after days of going in circles):

On Apple OSX Catalina (10.15.7):

1.  Ensure ownership of the following files:
`~/.ssh/config`
`~/private/etc/hosts`
`~/private/etc/exports`

2. Also you will need to allow the following files with Full Disk access:
  - Go to Settings > Security & Privacy > Privacy tab
  - Select Full Disk Access and add the following files:
 `~/sbin/mount`
 `~/sbin/mount_nfs`
 `~/sbin/nfsd`
 `/Applications/Virtual Box`

If you still encounter the nfs mounting issues when running `vagrant up`, you can replace the mounting type from ‘nfs’ to ‘rsync’ file:

1. Change synced_folder `type: "nfs"` to `type: "rsync"`
2. Then destroy current vagrant machine `vagrant destroy`
3. Restart nfsd and make sure its status is set to running and enabled
`$ sudo nfsd restart`
`$ nfsd status`
4. Create a new vagrant box
`$ vagrant up`

You will then need to run `vagrant rsync-auto` to ensure that files are sync between host and guest machine.

**Comment by azahraoui** [comment]
Hello, you can find a solution here that has been tested and that works for me: https://issueexplorer.com/issue/laravel/homestead/1717
