### ISSUE TITLE
Vagrant trigger "before provision" not working during "vagrant up"

### ISSUE THREAD

**Issue by y1y123** [hashicorp/vagrant#11838]
Hey Brian,

This is related to the issue https://github.com/hashicorp/vagrant/issues/11762#issuecomment-661100518
which we discussed recently.

I changed the default shell to bash for user "vagrant" to make sync_folder work but changing shell type to bash resulted in another issue where provisioning with ansible failed.  Ansible provisioning plays commands which are understood by NXOS CLI shell. 

To overcome the limitation I tried Vagrant trigger "before: provision", expecting that shell type to change to CLI before ansible playbook is played. 

```ruby
n9kv1.trigger.before :provision do |trigger|
            trigger.info = "Change default shell for user vagrant to NXOS CLI"
            trigger.run_remote = {inline: "vsh -r /var/tmp/restoredefault.cmd"}
end
```

With above change when I try "Vagrant provision --provision-with ansible", triggered worked fine but this trigger is not called when I bring box up first time "vagrant up".

In brief,  
1) How do I need to manage my VMs using more than one provisioners which work with different shells?
2) Provisions are called during "vagrant up" but "before/after provision" triggers do not work.
3) I also noticed that even sync_folder config is treated as one provisioner even though it is not explicitly configured with "config.vm.provision = xxx".  When I try to do "vagrant provision", vagrant tries to mount the directory.

Here is my Vagrantfile:

```ruby
config.vm.define "n9kv1" do |n9kv1|
        n9kv1.vm.box = "nexus9300v.9.4.1.IJB9.0.192.box"

        n9kv1.ssh.insert_key = false
        n9kv1.vm.boot_timeout = 600

        if Vagrant.has_plugin?("vagrant-vbguest")
          config.vbguest.auto_update = false
        end

        n9kv1.vm.synced_folder ".", "/vagrant", disabled: true
        n9kv1.vm.box_check_update = false

        config.vm.synced_folder "/Users/y1y123/N9Kv", "/bootflash/home/vagrant/james_data/"

        n9kv1.trigger.before :provision do |trigger|
            trigger.info = "Change default shell for user vagrant to NXOS CLI"
            trigger.run_remote = {inline: "vsh -r /var/tmp/restoredefault.cmd"}
        end

        n9kv1.vm.provision "ansible" do |ansible|
          ansible.playbook = "ansible_provision.yaml"
          ansible.compatibility_mode = "2.0"
        end
  end
```

**Comment by briancain** [comment]
@y1y123 The trigger `n9kv1.trigger.before :provision` only runs before the command `vagrant provision`. If you want to run that before the provision _action_, you need to use an action trigger: https://www.vagrantup.com/docs/triggers/configuration#actions

But if you simply just want to run that script before your ansible provisioner, it might be easier to just define a shell script and place it before the ansible provisioner block, since Vagrant evaluates and runs provisioners linearly as they are defined.

**Comment by soapy1** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
