### ISSUE TITLE
`vagrant up --no-parallel` can't work normally.

### ISSUE THREAD

**Issue by haxifang-aircos** [hashicorp/vagrant#11845]
Hello, I am using vagrant for the first time. I pulled the code from this address: https://github.com/scalingexcellence/scrapybook.git, executed the command **vagrant up --no-parallel**, and it seems to be completed soon When, an error was thrown, the error screenshot is as follows:
![image](https://user-images.githubusercontent.com/61681123/91056039-08f4e880-e658-11ea-9c33-1bfba0dc0fff.png)

Version: Vagrant 2.2.9

Looking forward to your help. Thank you.

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved in Vagrant 2.2.10 so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
