### ISSUE TITLE
Conflicting Host Only Adapter In Vagrant

### ISSUE THREAD

**Issue by himadriganguly** [hashicorp/vagrant#11851]
### Vagrant version

Vagrant 2.2.10

### Host operating system

Fedora 32

### Guest operating system

Ubuntu  16.04

### Vagrantfile

```
config.vm.network "private_network", type: "dhcp", name: "vboxnet0", adapter: 2
```

### Debug output

https://gist.github.com/himadriganguly/9d48474f5e728a4885784817acf46933

### Expected behavior

The box should be up and running.

### Actual behavior

> A host only network interface you're attempting to configure via DHCP already has a conflicting host only adapter with DHCP enabled. The
DHCP on this adapter is incompatible with the DHCP settings. Two
host only network interfaces are not allowed to overlap, and each
host only network interface can have only one DHCP server. Please
reconfigure your host only network or remove the virtual machine
using the other host only network.

### Steps to reproduce

1. Create a Host-Only Network and enable it in VirtualBox
2. Add the above line to the Vagrant file
3. vagrant up --debug

**Comment by himadriganguly** [comment]
Any update on this issue?

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
