### ISSUE TITLE
vagrant up import issue

### ISSUE THREAD

**Issue by campherkurt** [hashicorp/vagrant#1185]
On "vagrant up" an import error occurs, details below thanks.

System: OS X 10.7
Vagrant: 1.0.5
VirtualBox: 4.2.1 r80871

INFO global: Vagrant version: 1.0.5
 INFO vagrant: `vagrant` invoked: ["up"]
 INFO environment: Environment initialized (#Vagrant::Environment:0x0000010116b078)
 INFO environment:   - cwd: /Users/kurtcampher/Projects/vagrant/lucid_box
 INFO environment: Home path: /Users/kurtcampher/.vagrant.d
 INFO plugin: Searching and loading any available plugins...
 INFO plugin: Loaded 0 plugins.
 INFO environment: Loading configuration...
 INFO cli: CLI: [] "up" []
 INFO datastore: Created: /Users/kurtcampher/Projects/vagrant/lucid_box/.vagrant
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["VBoxManage", "--version"]
 INFO virtualbox: Using VirtualBox driver: Vagrant::Driver::VirtualBox_4_2
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["VBoxManage", "showvminfo", "1c838864-3bba-4ca9-a4d9-a45c0327686d"]
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO subprocess: Starting process: ["VBoxManage", "--version"]
 INFO virtualbox: Using VirtualBox driver: Vagrant::Driver::VirtualBox_4_2
 INFO virtualbox_base: VBoxManage path: VBoxManage
 INFO vm: Loading guest: linux
 INFO up: Creating: default
 INFO hosts: Host class: Vagrant::Hosts::BSD
 INFO runner: Running action: up
 INFO warden: Calling action: #Vagrant::Action::General::CheckVirtualbox:0x000001010a7088
 INFO subprocess: Starting process: ["VBoxManage", "list", "hostonlyifs"]
 INFO warden: Calling action: #Vagrant::Action::General::Validate:0x000001010a7060
 INFO warden: Calling action: #Vagrant::Action::VM::CheckAccessible:0x000001010a7010
 INFO warden: Calling action: #Vagrant::Action::VM::CheckBox:0x000001010a6fe8
 INFO warden: Calling action: #Vagrant::Action::VM::Import:0x000001010a6fc0
 INFO interface: info: Importing base box 'lucid_guest_adds'...
[default] Importing base box 'lucid_guest_adds'...
 INFO subprocess: Starting process: ["VBoxManage", "import", "/Users/kurtcampher/.vagrant.d/boxes/lucid_guest_adds/box.ovf"]
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["import", "/Users/kurtcampher/.vagrant.d/boxes/lucid_guest_adds/box.ovf"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
 INFO warden: Calling recover: #Vagrant::Action::VM::Import:0x000001010a6fc0
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["import", "/Users/kurtcampher/.vagrant.d/boxes/lucid_guest_adds/box.ovf"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["import", "/Users/kurtcampher/.vagrant.d/boxes/lucid_guest_adds/box.ovf"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["import", "/Users/kurtcampher/.vagrant.d/boxes/lucid_guest_adds/box.ovf"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR warden: Error occurred: There was an error executing the following command with VBoxManage:

["import", "/Users/kurtcampher/.vagrant.d/boxes/lucid_guest_adds/box.ovf"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VBoxManageError: There was an error executing the following command with VBoxManage:

["import", "/Users/kurtcampher/.vagrant.d/boxes/lucid_guest_adds/box.ovf"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.>
ERROR vagrant: There was an error executing the following command with VBoxManage:

["import", "/Users/kurtcampher/.vagrant.d/boxes/lucid_guest_adds/box.ovf"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
ERROR vagrant: /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/driver/virtualbox_base.rb:278:in `block in execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/util/retryable.rb:14:in`retryable'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/driver/virtualbox_base.rb:268:in `execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/driver/virtualbox_4_2.rb:183:in`import'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/vm/import.rb:14:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/vm/check_box.rb:28:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/vm/check_accessible.rb:18:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/general/validate.rb:13:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/general/check_virtualbox.rb:23:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/warden.rb:33:in`call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/builder.rb:92:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/runner.rb:49:in`block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/action/runner.rb:49:in`run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/vm.rb:192:in `run_action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/vm.rb:145:in`up'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/command/up.rb:31:in `block in execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/command/base.rb:116:in`block in with_target_vms'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/command/base.rb:111:in `each'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/command/base.rb:111:in`with_target_vms'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/command/up.rb:24:in `execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/cli.rb:42:in`execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/lib/vagrant/environment.rb:167:in `cli'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.0.5/bin/vagrant:43:in`<top (required)>'
/Applications/Vagrant/bin/../embedded/gems/bin/vagrant:19:in `load'
/Applications/Vagrant/bin/../embedded/gems/bin/vagrant:19:in`<main>'
 INFO interface: error: There was an error executing the following command with VBoxManage:

["import", "/Users/kurtcampher/.vagrant.d/boxes/lucid_guest_adds/box.ovf"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.
There was an error executing the following command with VBoxManage:

["import", "/Users/kurtcampher/.vagrant.d/boxes/lucid_guest_adds/box.ovf"]

For more information on the failure, enable detailed logging with
VAGRANT_LOG.

**Comment by martinacortes** [comment]
@camd had same issue, thank you!!

**Comment by cdaf** [comment]
For anyone who finds this thread on google, and is using windows, I found that if I set the "Default Machine Folder" in VirtualBox to another drive, it would return VERR_PATH_NOT_FOUND. The solution was to create a directory in the drive and point to that.

Note: this is when running Vagrant in-elevated.
