### ISSUE TITLE
Strange error after 2.2.9 -> 2.2.10

### ISSUE THREAD

**Issue by dburba** [hashicorp/vagrant#11856]
After updating to v2.2.10 I get error on vagrant up:

```
Traceback (most recent call last):
	17: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/bin/vagrant:205:in `<main>'
	16: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/environment.rb:290:in `cli'
	15: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/cli.rb:67:in `execute'
	14: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/commands/up/command.rb:87:in `execute'
	13: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/plugin/v2/command.rb:232:in `with_target_vms'
	12: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/plugin/v2/command.rb:232:in `each'
	11: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/plugin/v2/command.rb:233:in `block in with_target_vms'
	10: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine_index.rb:150:in `include?'
	 9: from /opt/vagrant/embedded/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
	 8: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine_index.rb:151:in `block in include?'
	 7: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine_index.rb:347:in `with_index_lock'
	 6: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine_index.rb:347:in `open'
	 5: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine_index.rb:349:in `block in with_index_lock'
	 4: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine_index.rb:153:in `block (2 levels) in include?'
	 3: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine_index.rb:266:in `find_by_prefix'
	 2: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine_index.rb:266:in `each'
	 1: from /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine_index.rb:267:in `block in find_by_prefix'
/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/machine_index.rb:267:in `start_with?': no implicit conversion of nil into String (TypeError)
```

Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/precise64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 22, host: 2200, id: 'ssh', auto_correct: true
  config.vm.network "private_network", ip: "192.168.33.103"
  config.vm.network "public_network", :bridge => 'enp4s0'

  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_udp: false

  config.vm.provider :virtualbox do |vb|
    vb.name = 'zope'
    vb.memory = 2048
    vb.customize ["modifyvm", :id, "--cpus", 2]
  end
  
  config.vm.hostname = 'zope'

end
```

Host OS: Linux Mint 20, guest: Ubuntu 12.04 (64bit). Virtualbox version 6.1.12. Vagrant v2.2.9 works correctly

**Comment by wpsamurai** [comment]
I can confirm the same problem. 

My setup:
- Vagrant: 2.2.10
- VirtualBox: 6.1.12
- Host OS: Windows 10 (19041.388) 
- Guest OS: Debian

After Vagrant downgrade to 2.2.9 the error is gone.

**Comment by soapy1** [comment]
Thanks for the bug report! It looks like there is something strange going on in the machine index. I'm not able to reproduce this error 😞. In order to better understand this issue, are you able to share the contents of this index file. It should be located at `<VAGRANT_HOME>\data\machine-index`.

ref: https://github.com/hashicorp/vagrant/pull/11656

**Comment by dburba** [comment]
> Thanks for the bug report! It looks like there is something strange going on in the machine index. I'm not able to reproduce this error . In order to better understand this issue, are you able to share the contents of this index file. It should be located at `<VAGRANT_HOME>\data\machine-index`.
> 
> ref: #11656

`{"version":1,"machines":{"ffdf324b35de4e8baa7185989a4e4300":{"local_data_path":"/home/donatas/dev/dl/.vagrant","name":"default","provider":"virtualbox","state":"poweroff","vagrantfile_name":null,"vagrantfile_path":"/home/donatas/dev/dl","updated_at":null,"extra_data":{"box":{"name":"ubuntu/bionic64","provider":"virtualbox","version":"20190503.0.0"}}},"2b79e437ec504f949838ac0f700909ab":{"local_data_path":"/home/donatas/dev/psqlslave/.vagrant","name":"default","provider":"virtualbox","state":"poweroff","vagrantfile_name":null,"vagrantfile_path":"/home/donatas/dev/psqlslave","updated_at":null,"extra_data":{"box":{"name":"ubuntu/bionic64","provider":"virtualbox","version":"20190503.0.0"}}},"b8e0389dc62d4d0299286ea28c59f28a":{"local_data_path":"/home/donatas/dev/dl/.vagrant","name":"main","provider":"virtualbox","state":"poweroff","vagrantfile_name":null,"vagrantfile_path":"/home/donatas/dev/dl","updated_at":null,"extra_data":{"box":{"name":"ubuntu/bionic64","provider":"virtualbox","version":"20190508.0.0"}}},"6bdcaf19c9d948e8ae4145c9026e10f8":{"local_data_path":"/home/donatas/dev/alcocloud/.vagrant","name":"default","provider":"virtualbox","state":"poweroff","vagrantfile_name":null,"vagrantfile_path":"/home/donatas/dev/alcocloud","updated_at":null,"extra_data":{"box":{"name":"centos/7","provider":"virtualbox","version":"1902.01"}}}}}`

As I see there is no record containing "zope" machine. Below are result of `vboxmanage list vms` command.

```
"ave" {56c5aa34-4ee5-4555-a39d-454c9945e856}
"alco" {a0937c24-32a3-41c8-af6b-f5a9f5f50b78}
"bionic" {5bff4fc4-ec10-4688-b6c6-21e115a8026e}
"grand4" {0f98afa0-0131-4e40-b5ba-1b763802197c}
"omron" {62aeab58-d92e-43a5-b6e7-b5fef25b43a9}
"w2p" {3f8552f4-4a8c-4e32-a993-700e7734eb8c}
"web2py" {de1553b0-9332-4be7-98ed-d799c55ec4a5}
"xenial" {4ca89cc2-6a3a-46ba-8bf8-95ac0f2447f5}
"zope" {6be0db2c-0f3e-4d9b-a7c4-6ffdea25beb8}
"dl" {279ccc6d-9d9a-438a-8d70-69a92e97d97b}
"dlsqlslave" {963b263f-e5ee-4e6e-beeb-bd5cd87b6059}
"alcocloud" {32a2a0fc-bae1-4be7-85b0-9e1b3ba0aacf}
```

**Comment by soapy1** [comment]
Awesome, thanks for the extra info!
I found I was able to reproduce this issue if I messed up my `.vagrant` directory (located in the same directory as my `Vagrantfile`). Specifically by removing the index_uuid file for the box. I was able to get around this issue is by removing the `.vagrant` directory, manually removing the machine in virtualbox and recreating the machine.
