### ISSUE TITLE
SSH connection failed after provisioning step with reboot

### ISSUE THREAD

**Issue by skudra** [hashicorp/vagrant#11852]
### Vagrant version 

2.2.10
Also happens on 2.2.8 and 2.2.9
Works fine on 2.2.7

### Host operating system 

Windows 10, 2004

### Guest operating system

Ubuntu 18.04.3 LTS

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "hashicorp/bionic64"
  
  config.vm.provision "Before", type: "shell",  run: "always" do |s|
    s.inline="echo 'Before reboot' | tee before.txt"
    s.reboot = true
  end
  
  config.vm.provision "After", type: "shell",  run: "always" do |s|
    s.inline="echo 'After reboot' | tee after.txt"
  end
  
end
```

### Debug output

https://gist.github.com/skudra/9b9e5777bbffbd1c804cd2171c0700c6

### Expected behavior

Vagrant should wait some time before checking if guest is available. This would give time for guest to properly reboot.

### Actual behavior

Looks like this code: https://github.com/hashicorp/vagrant/blob/ce1fb54a04f6c85e0a3b8c0427a3a5530ebced48/plugins/guests/linux/cap/reboot.rb#L41
detected that ssh is available *before* guest stopped sshd and proceeded with provisioning. Moments later guest actually rebooted and ssh connection was lost.
After looking at the code I noticed that this issue started to happen when systemctl support was added. If I modify reboot.rb to always use "reboot" as reboot_script the issue does not happen. Also, if I modify  reboot.rb for Vagrant 2.2.7 - the issue appears.

### Steps to reproduce

1. Launch provided Vagrantfile
2. Observe error:

> SSH connection was reset! This usually happens when the machine is
> taking too long to reboot. First, try reloading your machine with
> `vagrant reload`, since a simple restart sometimes fixes things.
> If that doesn't work, destroy your machine and recreate it with
> a `vagrant destroy` followed by a `vagrant up`. If that doesn't work,
> contact support.

This issue seems to related to time it takes for sshd to stop, before Vagrant checks for host. Reproduces in about 4 runs out of 5.

### References

Merge request that added systemd reboot support:
- https://github.com/hashicorp/vagrant/pull/11483

**Comment by irfanjunaid** [comment]
Hi,
I am facing the same exact issue on the latest version of vagrant. The command prompt immediately exits with connection abort error.

###  Host operating system
Windows 10 Version 2004 Build 19041.508

### Virtualbox version
Version 6.1.14 r140239 (Qt5.6.2)

### Guest operating system
Ubuntu 18.04.5 LTS

### Vagrant provisioning output
```
==> ubuntu: Running provisioner: Rebooting (shell)...
==> ubuntu: Waiting for machine to reboot...
SSH connection was aborted! This usually happens when the machine is taking
too long to reboot or the SSH daemon is not properly configured on the VM.
First, try reloading your machine with `vagrant reload`, since a simple
restart sometimes fixes things. If that doesn't work, destroy your machine
and recreate it with a `vagrant destroy` followed by a `vagrant up`. If that
doesn't work, contact support.
```

### Vagrantfile
```
  config.vm.provision :shell do |shell|
    shell.name = 'Rebooting'
    shell.reboot = true
  end
```

**Comment by soapy1** [comment]
This should be resolved by https://github.com/hashicorp/vagrant/pull/12302
