### ISSUE TITLE
Virtualbox guest freezes without responding on Arch Linux

### ISSUE THREAD

**Issue by Egor-Koldasov** [hashicorp/vagrant#11869]
### Issue description
When trying to start vagrant with `vagrant up --provision` it doesn't complete the process.
It gets stuck at
`SSH auth method: private key`
Or if I start it clean with doing `vagrant destroy` it gets stuck at
`Configuring and enabling network interfaces…`
An important note is that the Virtualbox guest becomes frozen, I can't even shut it down. If I kill the process I can't start vm again, Virtualbox gui just pops the windows saying `Starting virtual machine`, I am only able to proceed after the reboot.
The guest terminal has messages `Detected Tx Unit Hang` and `Reset adapter`
![first_attempt_vbox_guest](https://user-images.githubusercontent.com/15964628/91844716-9cce4200-ec60-11ea-8773-66399d90b425.png)
If I just start the image from the Virtualbox it's working fine, issues start to happen during the vagrant setup process.

### Side notes
This issue started to happen only recently around August 20th when I did the system update. I can't tell exactly but it probably wasn't more than a month since I did the last system update before this issue, I don't think there were Vagrant updates, only Virtualbox package updates. I have 2 laptops both running Arch Linux and I have this issue on both. I tried `bento/ubuntu-18.04` image and `ubuntu/trusty64` image with the same result.

### Vagrant version

2.2.9

### Virtualbox version

6.1.12r139181
Arch Linux package version 6.1.12-4

### Host operating system

Arch Linux

### Guest operating system

Ubuntu

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = 6144
    vb.cpus = 4
  end
end
```

### Debug output
The first clean attempt after `vagrant destroy`.
https://gist.github.com/Egor-Koldasov/c19b1f83ea629ee330316705689629a2
Subsequent attempts on the existing image.
https://gist.github.com/Egor-Koldasov/db271ec8bca4b0d0e2b0f1ec04634611

### Steps to reproduce
Having the latest Arch Linux
1. `vagrant destroy`
2. `vagrant up --provision`

### References

Might be related https://github.com/hashicorp/vagrant/issues/11865

**Comment by soapy1** [comment]
Hey there, thanks for submitting an issue. This is a bug in Virtualbox. Here is a link to the Virtualbox issue: https://www.virtualbox.org/ticket/19644, https://bbs.archlinux.org/viewtopic.php?id=258217

ref: https://github.com/hashicorp/vagrant/issues/11825
