### ISSUE TITLE
Not Been able to Bring up the centos VM on Mac OS Catalina 

### ISSUE THREAD

**Issue by prem548** [hashicorp/vagrant#11873]
Vagrant Version --> Vagrant 2.2.10
Virtual Box --> 6.1.12r139181
Host Operating System: Mac OS Catalina version 10.15.1
Guest Operating System --> "vitals/centos-6.10"

**Vagrant File:** 
   require 'yaml'

if Vagrant.plugins_enabled?
  if !Vagrant.has_plugin?('vagrant-vbguest')
    raise "Guest Additions not installed. To fix this please run:\n\n\tvagrant plugin install vagrant-vbguest\n"
  end
end

VAGRANTFILE_API_VERSION = "2"
os_name = `sw_vers -productName`
os_version = `sw_vers -productVersion`.to_f
ROOT_DIR = (os_name.include?('Mac OS') && os_version >= 10.15) ? "/System/Volumes/Data#{Dir.pwd}" : '/System/Volumes/Data/Users/UserName/Documents'
BOOTSTRAP_ENVIRONMENT = 'some_environment'
DEBUG = %w(1 true).include?(ENV['DEBUG'])
DEFAULTS = {
  name: "testone.vitals.vm",
  hostname: "testone.vitals.vm",
  box: "vitals/centos-6.6",
  box_version: "1.0.0",
  centos_version: 6,
  organization: ENV.fetch('ORGANIZATION', "engineering"),
  client: ENV.fetch('CLIENT', "engineering"),
  env: ENV.fetch('ENV', "localdev"),
  variant: ENV.fetch('VARIANT', nil),
  role: ENV.fetch('ROLE', 'myrole'),
  sub_role: ENV.fetch('SUB_ROLE', nil),
  ip: "IP Goes here"
  login_as_deploy: false,
  modules_dir: ["#{ROOT_DIR}/modules/"],
  manifests_path: "#{ROOT_DIR}/manifests/",
  manifest_file: 'site.pp',
  memory: 1024,
  cpus: 1,
  forward_agent: false,
  auto_nat_dns_proxy: 'false',
  natdnshostresolver1: 'on',
  natdnsproxy1: 'on'
}

boxes = [{}]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  boxes.each do |box_conf|
    instance = DEFAULTS.merge(box_conf)

    config.vm.define instance[:name] do |config|
      config.vm.box = "vitals/centos-6.10"
      config.vm.box_version = "1.0.0"

      config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
        v.customize ["modifyvm", :id, "--natdnshostresolver1", instance[:natdnshostresolver1]]
        v.customize ["modifyvm", :id, "--natdnsproxy1", instance[:natdnsproxy1]]
        v.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10_000]
        v.customize ["setextradata", :id, "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled", 0]
      end

      config.vm.hostname = "vagrant-centos64.vagrantup.com"
      config.ssh.forward_agent = true
      config.vm.network "private_network", ip: "IP Goes here"

      sync_type = RbConfig::CONFIG['host_os'] =~ /mswin|windows|cygwin|mingw/i ? 'smb' : 'nfs'
      sync_dirs = [
        { source: ROOT_DIR, target: '/vagrant', disabled: true },
        { source: "#{ROOT_DIR}/#{instance[:hiera_dir]}", target: '/host/hieradata' }
      ]

      sync_dirs.each do |sync|
        config.vm.synced_folder(sync[:source], sync[:target], type: sync_type, nfs_export: false, disabled: sync.fetch(:disabled, false))
      end
    end
  end
end

**Error message while running Vagrant up command.**
   The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -F /etc/hostname

Stdout from the command:

Stderr from the command:

hostname: can't open `/etc/hostname'

**Debug Output:** 
   vagrant up --debug

  INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-47be6889d69251bb4c9fac1e6c2f86e2
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007fe4fc2384d8>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::VagrantError: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -F /etc/hostname

Stdout from the command:

Stderr from the command:

hostname: can't open `/etc/hostname'
>
ERROR vagrant: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

hostname -F /etc/hostname

Stdout from the command:

Stderr from the command:

hostname: can't open `/etc/hostname'

ERROR vagrant: /opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/communicators/ssh/communicator.rb:268:in `execute'
/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/communicators/ssh/communicator.rb:278:in `sudo'
/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/guests/redhat/cap/change_host_name.rb:27:in `change_host_name'
/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/capability_host.rb:111:in `call'
/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/capability_host.rb:111:in `capability'
/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/guest.rb:43:in `capability'
/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/builtin/set_hostname.rb:23:in `call'
/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/lib/vagrant/action/warden.rb:48:in `call'
/opt/vagrant/embedded/gems/2.2.10/gems/vagrant-2.2.10/plugins/providers/virtualbox/action/forward_ports.rb:31:in `call'

What should have happened?
   Should have Installed VM properly
What actually happened?
  Throwing the Above Error. on running Vagrant up 

### Steps to reproduce
1. Create Vagrantfile and paste the above data. 
2. Change the user name ROOT_DIR = (os_name.include?('Mac OS') && os_version >= 10.15) ? "/System/Volumes/Data#{Dir.pwd}" : '/System/Volumes/Data/Users/**UserName**/Documents'
3.run the vagrant up command.

**Comment by ikari7789** [comment]
Also happening to me. Reason is due to [this commit](https://github.com/hashicorp/vagrant/commit/91ac0681cfa5e8b278c006d59cb8db125bf5d72c#), which got merged into v2.2.10 as part of #11565. It removed some logic that originally created the `/etc/hostname` file that is now missing when it attempts to create a VM. Downgrading to v2.2.9 should fix your issue for now until the fix from #11877 is released.
