### ISSUE TITLE
Set LC_ALL to en_US.UTF-8 instead of en.US in box generation script

### ISSUE THREAD

**Issue by dittaeva** [hashicorp/vagrant#1188]
With issue #1102 LC_ALL in Ubuntu is set to `en.US`, which solved one problem, but introduced another. `en.US` means that for example postgresql will be set up in LATIN1 mode instead of UTF8, and i suspect it will "degrade" default internationalization support in other software also.

Please set it to `en_US.UTF-8` instead. This seems to be the default on debian at least, autocomplete will work, and the locale should already be generated and ready for use.

BTW: I found `echo "LC_ALL=\"en_US\"" > /etc/default/locale` in `postinstall.sh` on the precise32.box. I suppose that is "the scripts to generate the boxes" that is mentioned in #1102, and those scripts are not shared on github? (I tried grepping to no avail).

**Comment by mssguavus** [comment]
LC_ALL=en_US.UTF-8
LC_CTYPE=en_US.UTF-8

add these lines to ~/.bash_profile of VM, and restart VM via vagrant
