### ISSUE TITLE
KMODE_EXCEPTION_FAILED with BSOD on Windows Build 20206 Insiders

### ISSUE THREAD

**Issue by tvvignesh** [hashicorp/vagrant#11881]
Hi. While this may be related more towards Virtualbox rather than Vagrant, still posting it here in case you want to have a look at it. 

I was using `Windows 10 Build 20201` Insiders Preview and everything was working fine but when I updated to `Windows 10 Build 20206` it started causing BSOD everytime after Vagrant up was about to start my Virtualbox VM with error `KMODE_EXCEPTION_FAILED` and when I rolled back my version to `Build 20201` it started working again.

I am running Windows 10 Home as host and Ubuntu Server (`bento/ubuntu-20.04`) as guest with SMB as the share in the latest version of Virtualbox with latest version of guest additions.

I have also tweeted this to microsoft (not sure where the error is): https://twitter.com/techahoy/status/1302239845662638081

Thanks.

**Comment by tvvignesh** [comment]
Looks like they are tracking the bug now.

Virtualbox: https://forums.virtualbox.org/viewtopic.php?f=38&t=99649

Microsoft: https://aka.ms/AA9jvm3

You can close this issue if you want.

**Comment by soapy1** [comment]
@tvvignesh thanks for sharing!
