### ISSUE TITLE
vagrant + docker desktop - vagrant reload fails - Guest-specific operations were attempted on a machine that is not ready for guest communication

### ISSUE THREAD

**Issue by unicman** [hashicorp/vagrant#11895]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use
HashiCorp Discuss: https://discuss.hashicorp.com/c/vagrant/24 Thank you!

When submitting a bug report, please provide the minimal configuration and required information necessary to reliably reproduce the issue. It
should include a basic Vagrantfile that only contains settings to reproduce the described behavior.

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version

 $ vagrant -v
Vagrant 2.2.10

### Host operating system

Mac OS 10.15.6

### Guest operating system

Docker Desktop 2.3.0.4

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|

  config.vm.define "db" do |ms|
      ms.trigger.before :reload do |trigger|
        trigger.name = "Network Bandwidth Usage Warning"
        trigger.warn = "Reloading this vagrant will trigger considerable download of base docker images."
        trigger.run = { inline: 'cd %s/opensource-git/blabla && git pull' % [ ENV['HOME'] ] }
      end

      ms.vm.provider "docker" do |d|
        d.name = 'helloworld-db'
        d.build_dir = '/path_to_folder'
        d.dockerfile = 'Dockerfile'
        d.build_args = [ '--tag', 'helloworld-db:latest', '--shm-size', '1g' ]
        d.create_args = [ '-d', '--shm-size', '1g', '-e', 'TZ=%s' % Time.now.zone ]
        d.ports = [ '1521:1521' ]
        d.remains_running = true
      end
  end

  config.vm.define "workflow" do |ms|
      ms.vm.provider "docker" do |d|
        d.name = 'helloworld-workflow'
        d.image = 'image:tag'
        d.create_args = [ '-d', '-e', 'TZ=%s' % Time.now.zone ]
        d.ports = [ '39000:39000' ]
        d.remains_running = true
      end
  end

  config.vm.define "dev" do |ms|
      ms.vm.provider "docker" do |d|
        d.name = 'helloworld-vagrant'
        d.build_dir = 'vagrant'
        d.dockerfile = 'Dockerfile'
        d.cmd = [ 'tail', '-f', '/dev/null' ]
        d.build_args = [
            '--tag', 'helloworld-vagrant:latest'
            '--build-arg', 'http_proxy=%s' % ENV["http_proxy"],
            '--build-arg', 'https_proxy=%s' % ENV["https_proxy"],
            '--build-arg', 'no_proxy=%s' % ENV["no_proxy"],
        ]
        d.create_args = [
            '-d',
            '-w', File.expand_path("."),
            '-e', 'TZ=%s' % Time.now.zone,
            '--link', 'helloworld-db:helloworld-db',
            '--link', 'helloworld-workflow:helloworld-workflow'
        ]
        d.env = {
            'TZ' => Time.now.zone,
            'VAGRANT_HOST_HOME' => File.expand_path("~"),
            'MAVEN_OPTS' => '-Dmaven.repo.local=%s/.m2/repository' % File.expand_path("~")
        }
        d.remains_running = true
      end

      # Uncomment to optimise download traffic by caching libraries on host.
      # That way files wont' download if container gets destroyed.
      # OR,
      # Uncomment if you would like to configure IDE. Instead of downloading
      # jars twice, it will download only once.
      ms.vm.synced_folder "~/.m2/repository", File.expand_path("~/.m2/repository")
      ms.vm.synced_folder ".", File.expand_path(".")
  end
end

```

Please ensure the Vagrantfile provided is a minimal Vagrantfile which contains
only the required configuration to reproduce the behavior. Please note that if
your Vagrantfile contains an excess of configuration unrelated the the reported
issue, or is in a different format, we may be unable to assist with your issue.
Always start with a minimal Vagrantfile and include only the relevant configuration
to reproduce the reported behavior.

### Debug output

https://gist.github.com/unicman/431b2015c6c7d913c47a27a8db684207

### Expected behavior

Following command used to create docker images properly and boot them up as docker container for so many days. Same is expected behavior.

vagrant reload 

### Actual behavior

Following command creates first image for helloworld-db correctly but fails every time after that with error pasted below:

vagrant reload 

    ****: Container created: dd2e2a3276493a30
==> ****: Enabling network interfaces...
==> ****: Starting container...
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

### Steps to reproduce

1. Created Vagrantfile that builds two docker images as shown above without SSH daemon in it.
2. run command vagrant reload 

### References

None.

**Comment by rwky** [comment]
Same issue using Ubuntu 20.04 as the host. This appeared in 2.2.10.
