### ISSUE TITLE
Vagrant freezes on 'SSH auth method: private key' when using Ubuntu box

### ISSUE THREAD

**Issue by tvvignesh** [hashicorp/vagrant#11890]
### Vagrant version

2.2.10

### Host operating system

Windows 10 Home Insiders Build `20201.rs`

### Guest operating system

Ubuntu 20.04

Hi. I face the same issue as mentioned in https://github.com/hashicorp/vagrant/issues/8157 where Vagrant hangs after doing `'SSH auth method: private key'` and I tried all solutions they have mentioned but nothing worked.

What worked for me was changing the base image from `ubuntu/groovy64` to `bento/ubuntu-20.04` keeping everything else the same. 

**PS:** I am mounting my folder as a SMB share on Windows since I faced a lot of trouble with native share and symlinks.

### References

https://github.com/hashicorp/vagrant/issues/8157

**Comment by teplyuska** [comment]
Hello, i had this issue with this configuration:

Host: Ubuntu 20.04.1 LTS (5.4.0-48-generic)
Guest: ubuntu/focal64
Vagrant: 2.2.10  
VirtualBox: 6.1.14 r140239 (Qt5.12.8)

After reading somewhere that USB was causing problems i attempted to disable all the stuff i do not need. Then it got the guest OS to start properly.

    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ['modifyvm', :id, '--usb', 'off']
    vb.customize [ "modifyvm", :id, "--uart1", "off" ]
    vb.customize [ "modifyvm", :id, "--uart2", "off" ]
    vb.customize [ "modifyvm", :id, "--uart3", "off" ]
    vb.customize [ "modifyvm", :id, "--uart4", "off" ]

I am not exactly sure which one did the trick.

**Comment by soapy1** [comment]
Thanks @teplyuska, yup!
There is a [confirmed bug](https://bugs.launchpad.net/cloud-images/+bug/1829625) that causes some of the newer Ubuntu boxes to boot slowly, which is causing the SSH timeout in this case.
You can work around this by adding the following customizations to your Vagrantfile:
```ruby
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end
```
Cheers!
