### ISSUE TITLE
'vagrant up' or 'vagrant up --provision' do not work on a Mac

### ISSUE THREAD

**Issue by seffw** [hashicorp/vagrant#11903]
I normally love discovering and trying new things, but this has been a mess from the start. I knew I should have bailed after seeing install instructions that just didn't care ("download the zip" - And what? ).

Anyway, after trial and error, figure out I needed to create a directory of my choose, unzip, put the folder contents in that new directory, and then all look good.

Except after all that, on a Mac, it doesn't work.

If I run vagrant up, I'm told I need to run vagrant provision or vagrant up --provision

I installed VCCW, just so it's clear what I am trying to do. 

None of those work. Nothing is started, no local server is available.

On the first run I had it working, but then the connection went for no apparent reason while I was navigating Wordpress admin. After that, it was the runaround of the 3 commands above.

Before I give up on this, is there any sensible way to make this work on a Mac?

I'm not looking for vagrant destroy then vagrant up. Not only does that not work, but it takes ages and ends up at the same place.

It's clear this is a big issue. You look aroung and see the questions, but there are not solutions out there that I have found. Just vague references to needing to use --provision, but that actually doesn't work (no local server is run). Lets gets some proper Mac instructions out there and save this huge time-waste for those new to Vagrant.

If there's any chance I can figure this out soon, I'll help write some tutorial. I absolutely hate the time that these things waste for other people.

**Comment by soapy1** [comment]
Hey there,
in order to better understand the issue here could you please provide a bit more information. In particular, 
* what OS are you running
* what version of Vagrant
* what does the Vagrantfile look like
* please provider a debug gist following the instructions https://www.vagrantup.com/docs/other/debugging

You might also find this guide to Vagrant useful https://learn.hashicorp.com/collections/vagrant/getting-started 😄

**Comment by soapy1** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
