### ISSUE TITLE
Vagrant with VMware provider connects VM to first NAT bridge rather than vmnet8

### ISSUE THREAD

**Issue by jmcvaughn** [hashicorp/vagrant#11906]
### Overview

On my machine I frequently use Vagrant to provision VMs that provide DHCP (e.g. MAAS). I therefore create bridges that only provide NAT. However, Vagrant with the VMware provider connects subsequent VMs to the first detected NAT network, not the default vmnet8 (i.e. "Share with my Mac" in the Fusion GUI).

### Vagrant version

- Vagrant 2.2.10
- vagrant-vmware-desktop (2.1.2, global)

### Host operating system

macOS Catalina 10.15.6

### Guest operating system

Any

### Vagrantfile

Issue isn't related to the Vagrantfile but an example of what I used for testing:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"
  config.vm.provider "vmware_desktop" do |v|
    v.vmx["numvcpus"] = 1
    v.vmx["memsize"] = 1024
    v.vmx["virtualhw.version"] = "16"
    v.vmx["vmx.buildType"] = "release"
  end
end
```

### Debug output

https://gist.github.com/jmcvaughn/773edf012e5fae979010e2256579ba1d

Note that at line 1826 I cut the output as it is merely repeated as Vagrant retries. Line 1827 is just the command termination (Ctrl+C).

### Expected behavior

VM should be connected to vmnet8, or in Fusion's GUI, the "Share with my Mac" network. This bridge is always expected to exist, and is therefore a reasonable default.

### Actual behavior

VM is connected to the first available NAT bridge. This is even after starting with a fresh configuration in Fusion and the VMware provider, by clearing `/Library/Preferences/'VMware Fusion'/` and removing `/opt/vagrant-vmware-desktop/settings/nat.json` respectively.

Note that with DHCP enabled on this "incorrect" bridge, Vagrant does provision the VM without issue (and completes, shares folders etc.). However, in the VM's settings in the Fusion GUI, it is shown as connected to "Unrecognized Network Device" rather than the actual bridge:
![Screenshot 2020-09-13 at 16 23 44](https://user-images.githubusercontent.com/24993138/93021912-984d4600-f5dd-11ea-97c5-6b4beba8c5a2.png)

### Steps to reproduce

1. Create multiple bridges numbered under 8 (i.e. numbered lower than Fusion's default bridge)
2. Enable NAT on one of these bridges
3. `vagrant up`

### Workaround

A valid workaround in my eyes is to create multiple "dummy" bridges numbered under vmnet8 without NAT or DHCP enabled. Vagrant's networks will start from vmnet9 and up.

### References

- This comment can be interpreted in multiple ways but I have a feeling it'll be misconstrued more often than not. vmnet8 will be default, it seems only if no other NAT networks exist. https://discuss.hashicorp.com/t/vagrant-and-multiple-vmware-nat-networks-command-line-option/5668/4

**Comment by jmcvaughn** [comment]
Apologies for the craziness above; part of some rebasing for my dotfiles. Have now used a shortened URL.

I did just have this occur with vmnet9, but I cannot reproduce this. This was after some contiguous creation/destroy/creation operations on a single VM.

**Comment by tcataldo** [comment]
Same here after updating to vmware desktop plugin 2.1.2 + reboot.
He keeps on creating vmnet2 and ignores vmnet8 even if I destroy it, vmnet-cli stop, configure, start.

**Comment by jmcvaughn** [comment]
Even with the "dummy" networks created, I still intermittently get VMs with vmnet9. If I destroy and recreate them (sometimes a few times), they'll eventually use vmnet8.

https://gist.github.com/jmcvaughn/91c903bbae69b6107af0d63a2a917316

**Comment by chrisroberts** [comment]
Hi,

NAT device detection was added for users that were modifying the device used for their default NAT. In testing I was unable to force multiples to match, however I can see that the issue is being encountered. The latest plugin release (2.1.4) includes a specific check on the default NAT device (vmnet8) before moving on to detection of other devices. It is also possible to force the plugin to use a specific device using the `nat_device` provider configuration option: https://www.vagrantup.com/docs/providers/vmware/configuration#nat_device

Cheers!
