### ISSUE TITLE
CentOS 6 returns hostname: can't open `/etc/hostname' Vagrant 2.2.10

### ISSUE THREAD

**Issue by comrade1809** [hashicorp/vagrant#11917]
I upgraded from Vagrant 1.9.1 to 2.2.10 two days ago, since then I have not been able to run my CentOS 6 cookbooks. CentOS 7 works just fine but CentOS 6 returns the error below:
### Vagrant version
Vagrant 2.2.10
### Host operating system
Windows 10
### Guest operating system
CentOS 6
### Vagrantfile
Base Vagrantfile, nothing altered since installation/upgrade.

### Debug output
https://gist.github.com/comrade1809/1d76f5f7a8bb45e87befe3bbf975640f

### Expected behavior
Hostname should be set and the machine comes up without any initial errors

### Actual behavior
Error:

==> default: Setting hostname...
STDERR: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
hostname -F /etc/hostname
Stdout from the command:
Stderr from the command:
hostname: can't open `/etc/hostname'
---- End output of vagrant up --no-provision --provider virtualbox ----

### Steps to reproduce
Run Kitchen Verify on a CentOS cookbook

**Comment by soapy1** [comment]
Thanks for submitting an issue! This has been resolved by https://github.com/hashicorp/vagrant/pull/11877
