### ISSUE TITLE
Creations of snapshots fail

### ISSUE THREAD

**Issue by Ricky-Tigg** [hashicorp/vagrant#11928]
**OS**:Fedora 32; **Windows system**: Gnome on Wayland; **Vagrant version**:  2.2.9. Issue not listed as corrected in release  2.2.10 (August 24, 2020)

Invoking `vagrant snapshot push` produces an error message. VM was created as intended from its box when executing `vagrant up`.

Vagrantfile: [Vagrantfile.txt](https://github.com/hashicorp/vagrant/files/5298449/Vagrantfile.txt). Debug file: [vagrant_debug.txt](https://github.com/hashicorp/vagrant/files/5298426/vagrant_debug.txt).

File properties indicate that the format is expected to support the creation of snapshots.  I did not yet manage to investigate the cause of  disproportion of file size produced by `file -b`; One is **717 MiB** while the other is **128 GiB**!
```
$ ls -lh .local/share/libvirt/images/fedora_default.img | cut -d' ' -f1-5
-rw-------. 1 yk yk 717M
$ file -b .local/share/libvirt/images/fedora_default.img
QEMU QCOW2 Image (v2), has backing file (path
/home/yk/.local/share/libvirt/images/generic-VAGRANTSLASH-
fedora32_vagrant_box_image_3.0.32.img), 137438953472 bytes
```
```
$ vagrant plugin list --local
vagrant-libvirt (0.0.45, system)
$ vagrant box list
generic/fedora32 (libvirt, 3.0.32)
$ vagrant ssh -- `virt-manager -c qemu:///session`
```
Vagrant boxes can only be listed by a connection established with Libivirt URI _qemu:///session_. In case that conection is opened manually, for example within interface from `virt-manager`, the following message is displayed

![libvirt-client x86_64_v6 1 0](https://user-images.githubusercontent.com/26058215/94551941-c8901800-025e-11eb-837c-9caf771e481e.png)

**Comment by chrisroberts** [comment]
Hi there, thanks for reporting this issue. Unfortunately, the Vagrant libvirt provider plugin is a third party plugin that we do not maintain. You can find the repository, and file an issue, here: https://github.com/vagrant-libvirt/vagrant-libvirt

Cheers!
