### ISSUE TITLE
"vagrant cloud publish" will randomly fail with ECURL_GOT_NOTHING

### ISSUE THREAD

**Issue by gregnorz** [hashicorp/vagrant#11925]
Periodically when we run our automated process to create a new version of a Vagrant box, the command line listed in the title will indicate that the upload completed (progress from `curl` reads as 100%), but the final error returned will be "52" or `ECURL_GOT_NOTHING`. The full command line we use (with redacted org information) is listed below in **Steps to reproduce**.

We can find ZERO consistency in the error. About 25% of the time we run this, whether through an automated process or manually on the command line, `ECURL_GOT_NOTHING` is returned. Testing across multiple systems with 2 different versions of Vagrant has revealed the same inconsistency in success/failure.

### Vagrant version

Tested with 2.2.8 and 2.2.9

### Host operating system

Tested on both Windows 10 Enterprise and Windows Server 2019

### Guest operating system

The .box files being uploaded are targeting "hyperv" and Windows Server 2019.

### Expected behavior

.box should be successfully uploaded and released in Vagrant Cloud.

### Actual behavior

The following error is logged and the box does not appear to be uploaded successfully. However, the box version is actually in Vagrant Cloud just unreleased. Manually releasing the version makes the box available for download. This is negatively affecting automated pipelines for keeping our boxes updated.

```
Progress: 100% (Rate: 0/s, Estimated time remaining: --:--:--) WARN uploader: Uploader exit code: 52
Failed to create box <redacted>
An error occurred while uploading the file. The error
message, if any, is reproduced below. Please fix this error and try
again.

exit code: 52
Empty reply from server
```

### Steps to reproduce

1. .box is created with Packer; a Windows Server 2019 image for Hyper-V
2. The following command line is run to upload the .box:

`vagrant cloud publish <redacted> 0.1.666 hyperv .\output\server-2019-base.box --private --release --force`

3. The upload completes according to the progress (assuming that is from `curl`) but a failure occurs with no error that specifies exactly why. 

4. The .box is not actually released but it appears to be uploaded to Vagrant Cloud. Manually releasing the version in question works and the box version can be downloaded successfully through the Vagrant CLI.

**Comment by gregnorz** [comment]
Update: Gist with full debug log on a failed run.

https://gist.github.com/gregnorz/61d3c7538772e91058ffe97c7f17498c

**Comment by gregnorz** [comment]
We haven't seen this particular issue recently, but we have had other upload problems which support has helped with. Perhaps it is safe to close this out for now as [12026](https://github.com/hashicorp/vagrant/issues/12026) has also been closed.

**Comment by soapy1** [comment]
Heya,
we have recently made some updates to Vagrantcloud uploading which should resolve this issue. Going to go ahead and close it out, however if this is still occurring, please open a new issue and follow the provided issue template
