### ISSUE TITLE
 /vagrant => C:/Users/Teng/Desktop/csci515 ==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision` ==> default: flag to force provisioning. Provisioners marked to run always will still run.

### ISSUE THREAD

**Issue by txiong11** [hashicorp/vagrant#11926]
before i give up, when i run vagrant up it give me this error: 

vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection aborted. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => C:/Users/Teng/Desktop/csci515
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

**Comment by soapy1** [comment]
Heya @txiong11,
could you provide a bit more information about what issue you are running into. From the log you have provided, it seems like Vagrant is doing the "right" thing, that is, starting the machine and doing some configuration. Could you provide a debug log that includes the error, as well as describe what the expected behavior is for the command you are running. Thanks!

**Comment by txiong11** [comment]
I got it run in ubuntu, So for now I will use ubuntu. I don't know why is not boot up the virtual box in windows 10 pro.
