### ISSUE TITLE
Centos/8 box randomly issuing Error: Unknown repo: 'C*-base'

### ISSUE THREAD

**Issue by strus38** [hashicorp/vagrant#11921]
Using the box 'centos/8' or 'bento/centos-8.2' randomly raises `Error: Unknown repo: 'C*-base'`
Launching the `vagrant up` again and again seems to at one point working, but this is very frustrating.
Environment:
- Windows10 PRO
- Latest version of vagrant & virtualbox.
Thanks

**Comment by darkn3rd** [comment]
Could you try it with `generic/centos8`?

**Comment by konstruktoid** [comment]
See https://github.com/dotless-de/vagrant-vbguest/issues/382

**Comment by strus38** [comment]
Seems to be better with generic one, at least for the first try. I will
keep you posted.

Le jeu. 24 sept. 2020 à 21:09, Thomas Sjögren <notifications@github.com> a
écrit :

**Comment by konstruktoid** [comment]
@soapy1, have a look at https://github.com/dotless-de/vagrant-vbguest/issues/367 and https://github.com/dotless-de/vagrant-vbguest/issues/382.
Don't think this is Vagrant specific.

**Comment by strus38** [comment]
tried with the generic centos 8 as requested and it seems to work.
Thanks

**Comment by fnordfish** [comment]
Just FYI: vagrant-vbguest 0.25.0 removed the `C*-base` repo stuff.
