### ISSUE TITLE
cannot run vagrant on windows 7 64 bits

### ISSUE THREAD

**Issue by areaboy** [hashicorp/vagrant#11922]
I downloaded vagrant  for windows at this link
https://www.vagrantup.com/downloads

I have just installed vagrant on windows 7 64 bits. when i type vagrant up to start it. it displays the following error below

**Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\ann>cd C:\hhvm-vagrant

C:\hhvm-vagrant>vagrant up
Vagrant failed to initialize at a very early stage:

The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.**

  Installed version: 2

  Minimum required version: 3

**Comment by soapy1** [comment]
Hey there,
thanks for submitting an issue. Can you confirm the version of powershell you currently have installed. You should be able to do this by opening up powershell and running `$PSVersionTable`. Could you also provide a debug gist following the instructions here https://www.vagrantup.com/docs/other/debugging

**Comment by soapy1** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
