### ISSUE TITLE
Unable to load the project using vagrant up

### ISSUE THREAD

**Issue by naresh-qed42** [hashicorp/vagrant#11930]
Facing an issue while setup the project on vagrant with virtualhox:
<pre>
/Applications/MAMP/htdocs/myproject-d9(master*) » vagrant up                                                                                                    1 ↵ nareshbavaskar@Nareshs-MacBook-Pro
Bringing machine 'myproject-d9' up with 'virtualbox' provider...
==> myproject-d9-d9: Cloning VM...
==> myproject-d9-d9: Matching MAC address for NAT networking...
==> myproject-d9-d9: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> myproject-d9-d9: Setting the name of the VM: local.blted-10.com
==> myproject-d9-d9: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
</pre>

My system info:
<pre>
Virtualbox: 5.2.44
vagrant: 2.2.1
mac os 10.15.6 Catalina
</pre>
Let please let me know  if you need any further information to debug the issue

**Comment by soapy1** [comment]
Thanks for opening up an issue. 
Could you provide a Vagrantfile that reproduces this issue as well as the full debug log (https://www.vagrantup.com/docs/other/debugging)
Thanks!

**Comment by soapy1** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
