### ISSUE TITLE
Enhancement Request: Add support for setting cloud_init mime part filename

### ISSUE THREAD

**Issue by rgl** [hashicorp/vagrant#11948]
**Is your feature request related to a problem? Please describe.**

In order to be able to use a `text/x-shellscript` with [cloudbase-init](https://github.com/cloudbase/cloudbase-init) we need to be able to set the mime part filename as we can in terraform:

https://github.com/rgl/terraform-libvirt-windows-example/blob/2d7bbfcf1e26c88fca2f4bf841ee4b5391dd936f/main.tf#L49-L51

**Describe the solution you'd like**

Add a `content_disposition_filename` argument like in:

```ruby
  config.vm.cloud_init :user_data, content_type: 'text/x-shellscript', content_disposition_filename: 'cloud-init-config-example.ps1', inline: <<~EOF
    #ps1_sysnative
    Start-Transcript -Append "C:/cloud-init-config-example.ps1.log"
    function Write-Title($title) {
      Write-Output "`n#`n# $title`n#"
    }
    Write-Title "whoami"
    whoami /all
    Write-Title "Windows version"
    cmd /c ver
    Write-Title "Environment Variables"
    dir env:
    Write-Title "TimeZone"
    Get-TimeZone
    EOF
```

The mime part should have the `Content-Disposition` header alike:

```
--Boundary_a8ifpgorjudubug4drvo4f3fnk
Content-ID: <8e76zrorjudubug4drvo4f3f36@44ghegorjudubug4drvo4f3f5k.local>
Content-Type: text/x-shellscript
Content-Disposition: attachment; filename="cloud-init-config-example.ps1"

```

**Comment by soapy1** [comment]
resolved by https://github.com/hashicorp/vagrant/pull/11961 (building on https://github.com/hashicorp/vagrant/pull/11950)
