### ISSUE TITLE
virtualbox__driver_queues do not work like  libvirt__driver_queues

### ISSUE THREAD

**Issue by glennWang** [hashicorp/vagrant#11947]
When I use vagrant-libvirt, I can specified the guest number of the nic queues with :libvirt__driver_queues on Ubuntu Host.

However, virtualbox__driver_queues not work when I use it on MacOS and always is 1.

You can verify it by using cmd `$ ethtool -l eth1`

You can see the `:libvirt__driver_queues` on the following link.
https://github.com/vagrant-libvirt/vagrant-libvirt

```
Vagrant.configure(2) do |config|
  config.vm.box = "generic/fedora32"

  config.vm.box_check_update = false
  config.vm.define "virtio" do |m|
    m.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 4
      v.customize ["modifyvm", :id, "--name", "virtio"]

      v.customize ["modifyvm", :id, "--nictype1", "virtio"]
      v.customize ["modifyvm", :id, "--nictype2", "virtio"]
      v.customize ["modifyvm", :id, "--nictype3", "virtio"]
    end

    m.vm.hostname = "virtio"

    m.vm.synced_folder ".", "/vagrant", disabled: false

    m.vm.network "private_network", ip: "172.18.2.3", netmask: "255.255.255.0", :mac => "040404161204", :virtualbox__driver_queues => 8

    m.vm.provision :shell, run: "always", :inline => "ip a add 172.18.2.4/24 dev eth1"

    m.vm.provision :shell, run: "always", :inline => "echo \"Hi, I'm virtio 🍁 \n\" && uname -a"
    m.vm.provision :shell, run: "always", :inline => "echo \"ulimit\" && ulimit -l"

    # manager
    m.vm.network "private_network", ip: "172.18.3.6", netmask: "255.255.255.0", :mac => "040404161208"
  end
end
```

**Comment by soapy1** [comment]
Hey there, thanks for opening up an issue. 
By convention, configuration parameters of the form `<provider>__<attribute>` are provider specific configurations. So, they are pretty unlikely to work in the same way across multiple providers. Vagrant's [Virtualbox provider](https://www.vagrantup.com/docs/providers/virtualbox/configuration) does not support this option. Digging through some of the Virtualbox documentation, I couldn't find any analogous configuration. But perhaps I'm missed something? I'm going to close this issue for now, but I'm happy to reopen it if there is a VirtualBox setting similar to libvirt's `driver_queues` that Vagrant could potentially surface for users.
Cheers.
