### ISSUE TITLE
Network disconnect of another VMs on vagrant up even with Fusion Pro license

### ISSUE THREAD

**Issue by stolowski** [hashicorp/vagrant#11940]
### Vagrant version

Vagrant 2.2.10
vagrant-vmware-desktop (2.1.4, global)

VMWare Fusion Professional Version 12.0.0 (16880131)

### Host operating system

Mac OS Catalina 10.15.7 (19H2)

### Guest operating system

Not relevant I think, but mostly Linux.

### Vagrantfile

Not relevant, but here is one example:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "focal-standalone"
  config.vm.define "ubuntu-focal-standalone" 
  config.vm.network "public_network"
  config.vm.provision "shell", path: "snapd-prep.sh"
  config.vm.provider "vmware_desktop" do |v|
    v.linked_clone = true
    v.vmx["memsize"] = "8192"
    v.vmx["numvcpus"] = "2"
    v.gui = true
  end
end
```

### Debug output

https://gist.github.com/stolowski/2cb8394b239d0e77a996e7f6358a3e8a

### Expected behavior

Stable network connectivity across all running VMs with VMWare Pro license.

This is listed in Known issues section (https://www.vagrantup.com/docs/providers/vmware/known-issues) BUT the documentation states that Pro version is not affected, which appears to be wrong:

"Please note that this issue is resolved when using VMware Workstation 15 or VMware Fusion 11 with a professional license. Due to advanced networking tools not being available when using a standard VMWare license, this behavior is still experienced when using a standard license."

### Actual behavior

Network is momentarily dropped in other VMs (e.g. ssh disconnects).

### Steps to reproduce

1. Start a linux box (vagrant up).
2. Connect to it with vagrant ssh.
3. Start another box with vagrant up.

**Comment by chrisroberts** [comment]
Hi there. After re-testing this I found the resets did continue even when using the advanced networking features. It appears my initial local testing unintentionally had different host terminals next to each other. Thank you for pointing out this mistake.

Cheers!
