### ISSUE TITLE
Vagrant SSH disconnects after some time ( really irritating )

### ISSUE THREAD

**Issue by sidharthpunathil** [hashicorp/vagrant#11953]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use
HashiCorp Discuss: https://discuss.hashicorp.com/c/vagrant/24 Thank you!

When submitting a bug report, please provide the minimal configuration and required information necessary to reliably reproduce the issue. It
should include a basic Vagrantfile that only contains settings to reproduce the described behavior.

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
Vagrant 2.2.10
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
Windows 10 Pro
This is the operating system that you run locally.

### Guest operating system

This is the operating system you run in the virtual machine.

```ruby

### Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", host_ip: "127.0.0.1", guest: 8080, host: 8080

  config.vm.provision "shell", inline: <<-SHELL

    # Update and upgrade the server packages.
    sudo apt-get update
    sudo apt-get -y upgrade

    # Set Ubuntu Language
    sudo locale-gen en_GB.UTF-8

    # Install Python, SQLite and pip
    # sudo apt-get install -y python3-dev sqlite python-pip

    # Upgrade pip to the latest version.
    # sudo pip install --upgrade pip

    # Install and configure python virtualenvwrapper.
    # sudo pip install virtualenvwrapper
    # if ! grep -q VIRTUALENV_ALREADY_ADDED /home/ubuntu/.bashrc; then
    #     echo "# VIRTUALENV_ALREADY_ADDED" >> /home/ubuntu/.bashrc
    #     echo "WORKON_HOME=~/.virtualenvs" >> /home/ubuntu/.bashrc
    #     echo "PROJECT_HOME=/vagrant" >> /home/ubuntu/.bashrc
    #     echo "source /usr/local/bin/virtualenvwrapper.sh" >> /home/ubuntu/.bashrc
    # fi

  SHELL

end
```

Please ensure the Vagrantfile provided is a minimal Vagrantfile which contains
only the required configuration to reproduce the behavior. Please note that if
your Vagrantfile contains an excess of configuration unrelated the reported
issue, or is in a different format, we may be unable to assist with your issue.
Always start with a minimal Vagrantfile and include only the relevant configuration
to reproduce the reported behavior.

### Debug output

Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior

What should have happened?
It should have worked without disconnecting

### Actual behavior

What actually happened?
I was connecting to Vagrant via ssh-remote ( vscode ) and it is getting disconnected after some minutes. 
It will again work if I restart my vagrant server. 
### Steps to reproduce

1. Connect to vagrant
2. A few moments later
3. Disconnect

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by soapy1** [comment]
I wonder if this is at all related to https://github.com/hashicorp/vagrant/issues/11953?

**Comment by chrisroberts** [comment]
I'm unsure of how the ssh connection setup configuration is defined, but it may be worth looking at adding/adjusting the `ServerAliveInterval` and `ServerAliveMaxCount` settings (and ensure they are configurable in the sshd settings within the server guest) as this looks very much like an idle timeout causing the connection to close.
