### ISSUE TITLE
Vagrant 2.2.10 - VirtualBox Extension Pack Upgrade Broken

### ISSUE THREAD

**Issue by cloudguyxyz** [hashicorp/vagrant#11960]
### Vagrant version
Vagrant 2.2.10

### Host operating system
Debian 10 Stable (Buster)
4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux

### Guest operating system
bento/centos-8
bento/debian-10
bento/ubuntu-18.04

### Vagrantfile
This is my main Vagrant file, but the issue occurs with a very basic Vagrant file generated by vagrant init

```ruby
Vagrant.configure("2") do |config|
    config.vm.define "testvm01" do |testvm01|
    testvm01.vm.box = "bento/centos-8"
    testvm01.vm.hostname = 'testvm01'

    testvm01.vm.network :private_network, ip: "192.168.56.101"

    # For additional netowkring make sure you use the correct
    # network interfaace based upon your system.
    # Below are some of mine from my Linux box.

      #config.vm.network "public_network", bridge: "enp0s31f6"
      #config.vm.network "public_network", bridge: "enx3ce1a1d0c90d"
      #config.vm.network "public_network", bridge: "wlp4s0"

    testvm01.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--name", "testvm01"]
    end
  end
end
```
### Debug output
https://gist.github.com/cloudguyxyz/68b3612201796328f3f87e07403d2715

### Expected behavior
vagrant up boots up the guest machine, if extensions are outdated updates extensions in guest OS.

### Actual behavior
**This is the actual behavior, but different errors occur based upon different troubleshooting methods to try and self-resolve. In any case the outcome is the same. Any attempt to upgrade the extensions results in a error with the guest VM.**

==> ansibledojo01: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r`

Stdout from the command:

Last metadata expiration check: 10:50:11 ago on Tue 13 Oct 2020 10:40:20 PM UTC.
No match for argument: kernel-devel-4.18.0-193.14.2.el8_2.x86_64

Stderr from the command:

Error: Unable to find a match: kernel-devel-4.18.0-193.14.2.el8_2.x86_64

### Steps to reproduce
1. vagrant up
2. GuestAdditions versions on your host (6.1.14) and guest (6.1.12) do not match.
Last metadata expiration check: 10:50:08 ago on Tue 13 Oct 2020 10:40:20 PM UTC.
3. After Vagrant tries to update the extensions erros out with different guest OSs. I have tried other troubleshooting methods such as ensuring the vagrant-vbguest plugin is installed.

### References
Was not able to find exact open issue.

**Comment by cloudguyxyz** [comment]
If anyone else has this issue. In the meantime as a work around I added the following to my Vagrantfile.
testvm01.vbguest.auto_update = false

**Comment by Mixka** [comment]
Workaround was updating vagrant-vbguest plugin with `vagrant plugin install vagrant-vbguest` to version 0.26.0.

And after that adding `conf.vbguest.installer_hooks[:before_install] = ["dnf install -y https://people.centos.org/arrfab/shim/results.c8/kernel/20190604090648/4.18.0-80.el8.x86_64/kernel-devel-4.18.0-80.el8.x86_64.rpm", "sleep 1"]` to Vagrantfile.
