### ISSUE TITLE
On vagrant up, process fails after attempting to run provisioner (shell) 

### ISSUE THREAD

**Issue by l0010o0001l** [hashicorp/vagrant#11970]
### Vagrant version
2.2.10

### Host operating system
Ubuntu 18.04.4 LTS and Ubuntu 20.04 LTS

### Guest operating system
Ubuntu Server 18.04

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "peru/ubuntu-18.04-server-amd64"
  config.vm.box_version = "20201001.01"
  config.vm.synced_folder ".", "/home/vagrant"
  config.vm.provision "shell", path: "provision/install-go.sh"
end
```

### Debug output
https://gist.github.com/l0010o0001l/4041faf94df8a9720d9d062abc715549

### Expected behavior

`vagrant up` should succeed and run the shell script on the guest machine.

### Actual behavior

`vagrant up` fails:

```
==> default: Running provisioner: shell...
==> default: Attempting graceful shutdown of VM...
    default: Guest communication could not be established! This is usually because
    default: SSH is not running, the authentication information was changed,
    default: or some other networking issue. Vagrant will force halt, if
    default: capable.
```

### Steps to reproduce

1. Include a provisioner type of shell with a path to a script
2. Run `vagrant up`

### References

Unsure.

**Comment by chrisroberts** [comment]
Hi there,

Would you please provide a gist with the debug output showing the behavior you are encountering. It can be generated by adding the `--debug` flag to the command:

```
vagrant up --debug
```

Thanks!

**Comment by l0010o0001l** [comment]
Hi @chrisroberts, I updated the Gist, thank you!

https://gist.github.com/l0010o0001l/4041faf94df8a9720d9d062abc715549

**Comment by soapy1** [comment]
Hey there,

it looks like this issue was being caused by an [error](https://gist.github.com/l0010o0001l/4041faf94df8a9720d9d062abc715549#file-vagrant-provision-debug-output-txt-L7990) in the `.bash_profile` that was being pushed up to the guest from this line
```
  config.vm.synced_folder ".", "/home/vagrant"
```
