### ISSUE TITLE
I had the same problem. 

### ISSUE THREAD

**Issue by JeffreyMaurer** [hashicorp/vagrant#11973]
I had the same problem. It was caused by an incorrect permission in the file .vagrant\machines\default\virtualbox\private_key. When I enabled read permission on the file to my user, I was able to connect.

_Originally posted by @danielmurguia in https://github.com/hashicorp/vagrant/issue_comments/390022827_

I was able to solve the issue by simply creating a file named "private_key"

**Comment by soapy1** [comment]
Hey there, looks like this is maybe suppose to be a comment on another issue? So, I'm going to go ahead and close this. Feel free to open another issue, maybe with a bit more background information 😄
