### ISSUE TITLE
vmware provider: base_address and nat_device options do not work together

### ISSUE THREAD

**Issue by Henkru** [hashicorp/vagrant#11981]
### Vagrant version

```
$ vagrant -v
Vagrant 2.2.1
```

### Host operating system

macOS Catalina (10.15.16)

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.base_mac = "12:34:56:78:9a:ab"
  config.vm.base_address = "10.0.1.3"

  config.vm.provider "vmware_desktop" do |v, override|
    v.nat_device = "vmnet3"
  end
end
```

### Expected behavior

The box should have one interface with MAC: `12:34:56:78:9a:ab` and IP: `10.0.1.3`.

### Actual behavior

The box has the correct MAC address but the IP came from DHCP.

```
$ ifconfig
        eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.1.130  netmask 255.255.255.0  broadcast 10.0.50.255
        ether 12:34:56:78:9a:ab  txqueuelen 1000  (Ethernet)
```

Vagrant added the MAC based static IP for the default NAT network (`vmnet8`).

```
$ grep -r 12:34:56 /Library/Preferences/VMware\ Fusion
/Library/Preferences/VMware Fusion/networking:add_dhcp_mac_to_ip 8 12:34:56:78:9A:AB 10.0.1.3
/Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf:	hardware ethernet 12:34:56:78:9A:AB;
```

### Steps to reproduce

1. Create a new VMware network (`vmnet3`) with a network range `10.0.1.0/24`
2. `vagrant up`

**Comment by soapy1** [comment]
Thanks for submitting an issue. A fix has been applied to the vmware plugin. It will be available next release 🎉
