### ISSUE TITLE
NFS fix has broken Vagrant on Windows

### ISSUE THREAD

**Issue by adamc-be** [hashicorp/vagrant#11986]
I just updated to vagrant 2.2.10.
My vagrant box, which worked fine on 2.2.9 now reports that it can't start as NFS is not supported on the Guest - and Windows does not support NFS at all.

This is caused by this line in the VagrantFile:
`    config.vm.synced_folder ".", "/vagrant", type: "nfs"`
Even though Windows does not support NFS, this synced folder worked fine - I can read/edit/save files in there.
Removing the `type:"nfs"` and although the error went away, there was no /vagrant folder

I uninstalled 2.2.10 and reinstalled 2.2.9 and it worked fine again.

I looked at the change log for 2.2.10 and found this line:
`config/vm: Don't ignore NFS synced folders on Windows hosts [GH-11631]`

So, it looks like vagrant now forces compliance with  `type:"nfs"`  on Windows, even though (in my experience anyway) this worked fine before.

This vagrant file is used on several guest platforms, and so the ability to use what is available but also work when feattures are not available (such as NFS) is important

Host Platform: Windows 10 build 2004
Guest Platform: Ubuntu 18.04 (bento/ubuntu-18.04)
Vagrant File:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')

Vagrant.configure('2') do |config|
  # Set Box
  config.vm.box = "bento/ubuntu-18.04"
  #config.vm.box = "ubuntu/bionic64"
  #config.vm.box = "precise64"
  #config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Set hostname
  config.vm.hostname = "britisheventing-Master"

  config.vm.define "britisheventing-Master"
  config.vm.provider :virtualbox do |vb|
    vb.name = "britisheventing-Master"
  end

  # Prevent vagrant-vbguests from being auto updated, this is time consuming and causes version mismatch with host
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = false
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  # Enable vagrant-bindfs support, if the plugin is installed
  # see https://github.com/gael-ian/vagrant-bindfs for details
  if Vagrant.has_plugin?("vagrant-bindfs")
    # The bindfs option has one more option, and the /var/nfs
    # is where the the folder is synced then it binds it to the
    # guest_path after.
    config.vm.synced_folder ".", "/var/nfs", type: "nfs"
    # This uses uid and gid of the user that started vagrant.
    config.nfs.map_uid = Process.uid
    config.nfs.map_gid = Process.gid
    config.bindfs.bind_folder "/var/nfs", "/vagrant",
      # perms: 'u=rwx:g=rwx:o=rwx',
      # perms: 'u=rwX:g=rD:o=rD',
      perms: 'u=rwX:g=rwD',
      u: 'vagrant',
      g: 'vagrant',
      o: 'nonempty'
  else
    # Enable NFS file system
    config.vm.synced_folder ".", "/vagrant", type: "nfs"
    # This uses uid and gid of the user that started vagrant.
    config.nfs.map_uid = Process.uid
    config.nfs.map_gid = Process.gid
  end

  # This uses the vagrant-disksize support, if the plugin is installed
  if Vagrant.has_plugin?("vagrant-disksize")
    config.disksize.size = '20GB'
  end

  # Configure RAM
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Specify private network
  config.vm.network "private_network", ip: "192.168.33.222"
  # Port requires for postgres
  config.vm.network :forwarded_port, guest: 5432, host: 25432
  config.vm.network :forwarded_port, guest: 80, host: 8081

  # Enable provisioning with a shell script.
#  config.vm.provision :shell, :path => "local/bootstrap.sh"

end
```
**Steps to Reproduce**

- Install Vagrant 2.2.10 on Windows 10
- Run the VagrantFile above
- Vagrant errors saying NFS is not running and it won't run on Windows (sorry, I didn't save the exact error before I rolled back to 2.2.9)

**Expected behaviour**
- Install Vagrant 2.2.9 on Windows 10
- Run the VagrantFile above
- Vagrant runs and the `/vagrant' file is available when connected to the VM

**References**
GH-11631 appears to be responsible for this behaviour (according to 2.2.10 changelog) but I can't find this ticket in Issues here.

**Comment by odeno1** [comment]
Have same issue and verify downgrading to 2.2.9 fixes the nfs error.

**Comment by adamc-be** [comment]
@soapy1 @chrisroberts @briancain 
Change GH-11631 breaks previously working Vagrant installations on Windows, with no apparent benefit.
Could you please explain what you were trying to achieve with that change, and how you intended Windows users should workaround it in mixed environments, where other users can use NFS, and `type: "nfs"` was working previously without error?
Thanks!

**Comment by soapy1** [comment]
The change in [gh-11631](https://github.com/hashicorp/vagrant/pull/11631) was prompted by [gh-9495](https://github.com/hashicorp/vagrant/issues/9495). 

Vagrant does not currently support nfs on windows. As [mentioned in the Vagrant docs](https://www.vagrantup.com/docs/synced-folders/nfs)

> Windows users: NFS folders do not work on Windows hosts. Vagrant will ignore your request for NFS synced folders on Windows.

Previously, if a user specified nfs folders on Windows, Vagrant would ignore the specified type and use the default synced folder type for the given system. This lead to confusing behavior for users that wanted to specify extra nfs options on Windows, as is outlined in [gh-9495](https://github.com/hashicorp/vagrant/issues/9495). Vagrant should do what is defined in the Vagrantfile. So, if the Vagrantfile specifies that nfs should be used for a synced folder, Vagrant should use nfs. Further, if nfs is not available on the system, Vagrant should not try to fallback to another synced folder type.
 
In order to use nfs on some system and another synced folder type on windows you can specify an [override](https://www.vagrantup.com/docs/providers/configuration#overriding-configuration) in the Vagrantfile. For example, something like
```
  config.vm.provider "virtualbox" do |vb, override|
    if Vagrant::Util::Platform.windows?
      override.vm.synced_folder ".", "/vagrant", type: "rsync"
    end
  end
```

**Comment by adamc-be** [comment]
@soapy1 
Thanks for the clarification.
But, it appears (from the message) that Vagrant assumes NFS is not supported in Windows. The message just says:

> If you're on Windows, NFS isn't supported.

Is this correct, or does Vagrant use the Windows built-in NFS support if it is enabled:
![G7ZFZx8i8k](https://user-images.githubusercontent.com/16082552/97414664-2c5c3e00-18fc-11eb-973e-5bdacaefff48.png)

(Sorry - not had time to re-install 2.2.10 to test this, as I don't want to break my existing setup again)

**Comment by adamc-be** [comment]
@soapy1 

OK, I've tried it with 2.2.10 and NFS enabled in Windows - and it still says it is not supported.
Seems like Vagrant just sees Windows and assumes NFS is not supported
![m4gtyq5wjM](https://user-images.githubusercontent.com/16082552/97427921-2a4eab00-190d-11eb-8190-33091f74cfdc.png)

**Comment by soapy1** [comment]
>  Seems like Vagrant just sees Windows and assumes NFS is not supported

Yup, that's true. Vagrant checks if nfs is installed. For example, in the [alt host](https://github.com/hashicorp/vagrant/blob/main/plugins/hosts/alt/cap/nfs.rb#L24) it runs a few commands. For [windows hosts](https://github.com/hashicorp/vagrant/blob/main/plugins/hosts/windows/cap/nfs.rb#L6) Vagrant hardcodes `false` for if nfs is installed. It's important to note here, that this is not a new behavior. But, it is a behavior that has recently surfaced due to Vagrant no longer ignoring nfs synced folders on Windows. The cause of this surfacing are the changes from https://github.com/hashicorp/vagrant/pull/11631

**Comment by odeno1** [comment]
Thanks the updates.

Given it worked on windows, albeit due to fallback functionality and not with additional parms, any reason why it isn’t supported? Many users will see their setup broken with 2.2.10.

Perhaps the change log should be updated to reflect this and issue a workaround for windows users?

many thanks,
________________________________

**Comment by adamc-be** [comment]
@soapy1 

This isn't making much sense.
First, you said that you blocked NFS because:
> This lead to confusing behavior for users that wanted to specify extra nfs options on Windows, as is outlined in gh-9495.
And to block that edge case, you blocked all Windows users from using an NFS fallback which seemed to work for most people.

On top of that, you've hardcoded that Windows users can't use NFS, stating that NFS is just not supported on Windows, despite NFS Client having been introduced in Windows 7/Server 2008 - so it's been available for over 10 years.

If you don't want to support fall back modes like NFS on Windows, that's fine - it is not designed behaviour and, as you point out, there are inconsistencies.

But, if you are going to be strict about this, please at least allow Windows users to install and use NFS in the same way other hosts (Linux, Mac) do - no fallback, but it will detect and use if NFS is available.

Can I make a suggestion? Rollback #11631 until such time Vagrant allows the use of NFS in Windows (when installed), and then republish 11631 so we can all carry on using NFS correctly.

**Comment by odeno1** [comment]
I fully support Adam’s reply.
________________________________

**Comment by chrisroberts** [comment]
Hi there,

The behavior that is being encountered is the correct behavior and it was an error that previous versions of Vagrant did not properly validate the Vagrantfile configuration and flag the error. As @soapy1 explained previously (https://github.com/hashicorp/vagrant/issues/11986#issuecomment-718259523) Windows does not provide builtin support for NFS, and as such, Vagrant does not support NFS synced folders on Windows. While Windows does provide the option to install an NFS client on a Windows system, Vagrant requires an NFS server to be running on the host system to facilitate sharing to guests. Windows does not provide an NFS server (nfsd) to install, and thus Vagrant does not support that type of synced folders on Windows.

Previously, when the type was set to nfs, Vagrant would just silently fallback to whatever synced folder implementation was available and use that. When the type is explicitly set, this behavior is incorrect and an error should be reported.

If you need to set the synced folder type to nfs for non-Windows system where the Vagrantfile may be used, the `Vagrant::Util::Platform.windows?` method can be used for conditionally defining the correct type.

Cheers!

**Comment by odeno1** [comment]
Hi Chris,

Why not make

“fallback to whatever synced folder implementation was available and use that”

optional with a warning? Or, if nfs isn’t specified, will fallback occur in 2.2.10? I’m suspecting not given your email.

That fallback functionality was working adequately for many so why not let them continue to use at their own risk?

Best wishes,
Olu
________________________________
