### ISSUE TITLE
Vagrant up does not work

### ISSUE THREAD

**Issue by Juliaria08** [hashicorp/vagrant#11984]
When submitting a bug report, please provide the minimal configuration and required information necessary to reliably reproduce the issue. It
should include a basic Vagrantfile that only contains settings to reproduce the described behavio
I ran on artix linux 
```
mkdir vagrant-test
vagrant init ubuntu/trusty64
vagrant up
```
Output
```
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' version '20190514.0.0' is up to date...
==> default: Setting the name of the VM: vag_default_1603300293592_18881
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "85d9877d-0e4a-40d5-95ef-96290bdb14cb", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'vag_default_1603300293592_18881' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

```

### Vagrant version

Vagrant 2.2.10

### Host operating system

Artix Linux x86_64

### Guest operating system

ubuntu/trusty64

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
end

```

### Debug output
https://gist.github.com/Juliaria08/ffc7a828fad736dacd947bf1ac6c6a90

### Expected behavior

Ran a vm using ubuntu/trusty64
### Actual behavior

Split out error.

**Comment by chrisroberts** [comment]
Hi there,

The error you are encountering is an issue with your VirtualBox installation, not with Vagrant itself. The error in your output (`NS_ERROR_FAILURE (0x80004005)`) can be caused from a few different things. The two most common are either the directory vbox is attempting to write to is read-only (this is usually `~/VirtualBox VMs`) or the VirtualBox kernel modules need to be rebuilt.

Cheers!

**Comment by Juliaria08** [comment]
Tanks i am going to try to rebuild virtualbox kernel modules.
