### ISSUE TITLE
Vagrant 2.2.10 regression with Docker builder

### ISSUE THREAD

**Issue by jbronn** [hashicorp/vagrant#11982]
### Vagrant version

2.2.10

### Host operating system

Ubuntu 20.04

### Guest operating system

CentOS 7 Docker container

### Vagrantfile

```ruby
['RPMS', 'SPECS', 'SOURCES'].each do |directory|
  if ! File.directory?(directory)
    Dir.mkdir(directory, 0755)
  end
end


Vagrant.configure(2) do |config|
  config.vm.define 'rpmbuild' do |container|
    container.vm.synced_folder '.', '/vagrant', disabled: true
    container.vm.synced_folder 'RPMS', '/rpmbuild/RPMS'
    container.vm.synced_folder 'SPECS', '/rpmbuild/SPECS'
    container.vm.synced_folder 'SOURCES', '/rpmbuild/SOURCES'
    container.vm.provider :docker do |d|
      d.build_dir = '.'
      d.cmd = []
      d.dockerfile = 'Dockerfile'
      d.remains_running = false
    end
  end
end
```

Here's the `Dockerfile`:

```
FROM centos:7

RUN yum -q -y update && \
    yum -q -y install \
        autoconf \
        automake \
        bzip2 \
        createrepo \
        epel-release \
        gcc \
        gcc-c++ \
        gdb \
        git \
        git-core \
        groff \
        less \
        lcov \
        libtool \
        make \
        m4 \
        redhat-lsb-core \
        redhat-rpm-config \
        rpm-build \
        rpm-sign \
        rpmdevtools \
        rpmlint \
        unzip \
        vim \
        wget \
        which \
        zip && \
    yum -q -y clean all
```

This demonstrates the bug and approximates the way we use Vagrant when this was encountered with ngageoint/hootenanny-rpms#301.

### Debug output

[Debug output from `vagrant up`](https://gist.github.com/jbronn/7389e3d52cb675bb759e5d5adca619e2).

### Expected behavior

I expect an `rpmbuild` container to be built from the `Dockerfile` without error.

### Actual behavior

The container builds, but once running through all of the `Dockerfile` steps it errors out with:

```
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

### Steps to reproduce

1. Place `Vagrantfile` and `Dockerfile` in same folder that have write permissions on.
2. Run `vagrant up`.

### References

I suspect the regression is related to one of the following changes introduced since 2.2.9:

- #11602 (refs #9067)
- #11814 (refs #11908)

**Comment by soapy1** [comment]
Heya, thanks for opening up an issue. This is resolved by https://github.com/hashicorp/vagrant/pull/11900 🎉 
I can confirm that this issue no longer exists on the `main` branch of Vagrant. The fix will be included in the next release 🚀 So, I'm going to go ahead an close this issue.
