### ISSUE TITLE
modifyvm command failed

### ISSUE THREAD

**Issue by till** [hashicorp/vagrant#1198]
```
A customization command failed:

["modifyvm", "bd6f6fc8-c3d3-43a8-8f0f-d4565cc1b584", "--name", "Foo Bar VM", "--memory", "512"]

The following error was experienced:

VBoxManage: error: Could not rename the directory '/Users/till/VirtualBox VMs/var_1350669697' to '/Users/till/VirtualBox VMs/Foo Bar VM' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface IMachine, callee nsISupports
Context: "SaveSettings()" at line 2300 of file VBoxManageModifyVM.cpp


Please fix this customization and try again.
```

So, the way to recreate this:
- work with your VMs for one, maybe two weeks
- experience kernel panic
- (hope that one of the VMs was not cleaned up from `~/VirtualBox VMs`)
- try `vagrant up`
- see above error

I'm sure it's not simple to fix this since you cannot just deleted — could probably be from suspended VMs as well? Not sure if there is a way to indicate if this directory belongs to anything still or if it's an artifact of a previous run.

**Comment by swahibi-magari** [comment]
sudo vagrant up

**Comment by egiathamaershada** [comment]
if anybody still experiencing the same error

this is how i managed to fix this manually (basically i just tried to cleanly delete the vm)
1) delete homestead directory in your project and delete all directory in ~/VirtualBox VMs mentioned in virtual box error message Could not rename the directory '<this directory>' to '<and vbox homestead directory>'. after delete both directory and homestead in your project directory,
2) unregister vm using VBoxManage
the name is the same as in <this directory> and the one named homestead
you can check the vms using command VBoxManage list vms
unregister using VBoxManage unregistervm <vmname>
3) done
you can clone the homestead folder again, edit it and do vagrant up again (setup homestead again from the start)

normally i think you can just use VirtualBox GUI delete the VM mentioned in the error and homestead in project folder and set up homestead again from the start. make sure there is no folder named homestead and the one mentioned in the error in ~/VirtualBox VMs

i'm using mac dont know if it works in linux or windows and remember using vagrant suspend and resume because i'm new using vagrant and it happens after i use vagrant up twice

**Comment by JazminGonzalez-Rivero** [comment]
Thanks for the help @mikeknoop !!! Couple years later and this problem is still around :(

**Comment by Blueblau** [comment]
I too, have this issue. :'(

**Comment by kegi** [comment]
I confirm this problem still exists on Linux and Mac. I experienced it yesterday, my VM was running well since months.

**Comment by sethvargo** [comment]
Hi all,

Thank you for responding on this ticket. This issue is almost 3 years old and a lot has changed in Vagrant since. It would be really fantastic if someone could open a new issue that uses the newest version of Vagrant and includes the Vagrantfile and debug output :smile:

**Comment by wesleycoder** [comment]
I have this issue, with:
VBox 5.0.2
Vagrant 1.7.4
Windows 10 x64

The Vagrant file I'm using is the genterated by:
`vagrant init joomlatools/box`

And happens in `vagrant up` two times in sequence, .
But if I use normally with `vagrant up`, then `vagrant halt` and then `vagrant up` there's no issue with this.

**Comment by vince-db** [comment]
I ran into the same issue tonight : "vagrant up" on a config done with PuPHPet. I just changed the hostname in config.yaml, line 6 hostname: local.dev to something else and the problem disappeared. I had another VM using the same hostname.

**Comment by RJ3000** [comment]
Ran into the same issue, it looks like it may be an issue with a space in the name of the directory:

`Stderr: VBoxManage: error: Could not rename the directory '/Users/User/VirtualBox VMs/puppet_14444444577_61868'`

Changed the setting in for the Default Machine Folder in Virtual Box settings to a directory without a space has solved the issue.

**Comment by JamieRead** [comment]
I solved this by doing:
`vagrant box list` 
Then removing all the boxes listed using the command:
`vagrant box remove (box name)`
And finally running:
`vagrant up`

**Comment by tomredhot** [comment]
Same problem here.
I've reinstall everything (vagrant, Oracle VM) and re-generate VagrantFile by puphpet...

**Comment by helloncanella** [comment]
@JamieRead Thank you, your approach worked.

**Comment by josebispo** [comment]
WARNING: The second argument to `vagrant box remove`
is deprecated. Please use the --provider flag. This
feature will stop working in the next version.
@JamieRead

**Comment by wakerman** [comment]
PS D:\work> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: You are trying to forward to privileged ports (ports <= 1024). Most
==> default: operating systems restrict this to only privileged process (typically
==> default: processes running as an administrative user). This is a warning in case
==> default: the port forwarding doesn't work. If any problems occur, please try a
==> default: port higher than 1024.
==> default: Forwarding ports...
    default: 80 (guest) => 80 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "40e0e4ea-9ac5-4b38-bc61-e0d831abb5d8", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'work_default_1470374343616_95683' has terminated
 startup with exit code -1073741819 (0xc0000005).  More details may be available in 'C:\Users\Admini
Ms\work_default_1470374343616_95683\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

=======Help.============
win 10 x64
cpu: Intel
ram:12G

vagrant : vagrant_1.8.5.msi
VirtualBox-5.1.2-108956-Win.exe
![image](https://cloud.githubusercontent.com/assets/3078413/17427326/56c9b2d2-5b12-11e6-8616-acebef06e46e.png)

===================
log
 
[VBoxHardening.txt](https://github.com/mitchellh/vagrant/files/403190/VBoxHardening.txt)

**Comment by IeuanWalker** [comment]
I had this same problem, I ran `vagrant global-status` and it said it was powered off.

I opened up Virtualbox and the machine was running, so I powered it off and ran `vagrant up` again.

And it fixed my problem :D

**Comment by elialbert** [comment]
I had this problem working off of a vagrant config in a github repo. I'd installed the box months ago and tried to `vagrant up` recently, and got this problem.
Long story short the vagrant config was old and out of sync with the box image. I pulled latest from the github repo, rmraffed the Virtual box directory, removed the machine from the virtual box list, and ran vagrant up again - it worked.

**Comment by vuongggggg** [comment]
I had this problem. I've Powered off my box in VirtualBox and up again by `vagrant up`. Solved.

**Comment by MDCurrent** [comment]
@vuongggggg worked for me!

**Comment by dungna7** [comment]
open your virtual machine and increase the Ram size then try again. (or vagrant file enable vb.memory  )
in Virtual Box.   Try going to Settings -> System -> Motherboard on VirtualBox and change the RAM size.

**Comment by danirueda** [comment]
I had the same problem. I opened VirtualBox and I tried to run the machine myself, and a suggestions poped up. I had other configurations for the 5.0 version (now I had 5.2). The only thing I had to do was run the command `sudo vboxconfig` and all was fixed!!!. I hope this will be able helpful!!

**Comment by MajidJafari** [comment]
Had the same issue, I just freed up some RAM and Hard Space on C and the problem is solved, now.

**Comment by akvermaktr** [comment]
config.vm.define "web" do |web|
    web.vm.box = "precise64"
    web.vm.hostname = 'web'
    web.vm.box_url = "ubuntu/precise64"

    web.vm.network :private_network, ip: "192.168.56.101"

    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "db"]
    end
  end

  config.vm.define "db" do |db|
    db.vm.box = "precise64"
    db.vm.hostname = 'db'
    db.vm.box_url = "ubuntu/precise64"

    db.vm.network :private_network, ip: "192.168.56.102"

    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "db"]
    end
  end


// I HAS SAME ISSUE...  I AM USING MULTI VM CONFIGURATION ..
DURING THE CPD I FORGOT TO RENAME VM REFERENCE "DB"

 THE LAST LINE   v.customize ["modifyvm", :id, "--name", "db"]  TRYING TO RENAME VM TO "db" WHICH IS ALREADY EXISTS 
----------
after update config 
vagrant destroy
vagrant up 
vagrant ssh db1
vagrant ssh db2

**Comment by ha-yi** [comment]
in my cases, this is happened when I try to add a USB passthrough to VM...
when I remove it, it start normally.
