### ISSUE TITLE
vagrant up reports error with minio image

### ISSUE THREAD

**Issue by hqstevenson** [hashicorp/vagrant#11990]
### Vagrant version
2.2.10

### Host operating system
OS X Catalina 10.15.7

### Guest operating system
Docker image - minio/minio

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|

  config.vm.provider 'docker' do |d|
    d.name = 'vagrant-minio'
    d.image = 'minio/minio'
    d.ports = [ '9000:9000' ]
    d.cmd = [ 'server', '/data' ]
    d.env = { MINIO_ACCESS_KEY: 'AKIAIOSFODNN7EXAMPLE', MINIO_SECRET_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY' }
  end

end
```

### Debug output
https://gist.github.com/hqstevenson/79f90212955cfdb04336c028cb97e3ca

### Expected behavior
I'm trying to start a Docker container using the MinIO image (https://docs.min.io/docs/minio-quickstart-guide.html) with Vagrant rather than starting it manually for my testing.

When I run 'vagrant up', I'd expect the container to be started without reporting any errors.

### Actual behavior
When I run 'vagrant up', the container is started as I'd expect.  However, the vagrant output says I should report a bug - so I am.

```
quinn$ vagrant up
Bringing machine 'default' up with 'docker' provider...
==> default: Creating and configuring docker networks...
==> default: Fixed port collision for 22 => 2222. Now on port 2213.
==> default: Creating the container...
    default:   Name: vagrant-minio
    default:  Image: minio/minio
    default:    Cmd: server /data
    default: Volume: /Users/quinn/projects/vagrant/testing:/vagrant
    default:   Port: 9000:9000
    default:  
    default: Container created: 74e2f554d5eed0a4
==> default: Enabling network interfaces...
==> default: Starting container...
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

### Steps to reproduce
run 'vagrant up' for the Vagrantfile

**Comment by soapy1** [comment]
Thanks for opening up an issue. This has been resolved by https://github.com/hashicorp/vagrant/pull/11900. It has been merged to the main branch and will be included in the next release of Vagrant 🎉
