### ISSUE TITLE
Fedora 33 crypto-policies prevent ssh access to newly created machines.

### ISSUE THREAD

**Issue by adamprice2** [hashicorp/vagrant#12000]
Updated to Fedora 33 today, and suddenly I can't log into any of my vagrant boxes.
The "issue" is that the Fedora 33 security policy removed rsa from the ssh configuration.

Easy fix on the Fedora side is to modify the security policy back to a level that allows access, but I wonder if you guys want to update the vagrant generated ssh keys to something newer?

**Comment by bowmanjd** [comment]
Curious: what OS and SSH server are your Vagrant boxes running? Any chance that might be the issue?

Would you have interest in adding your own public key to those boxes? If so, adding an ed25519 key would work well. But I hear you asking if vagrant can change their private key, so I understand if that is not the desired solution.

**Comment by adamprice2** [comment]
Several different flavours of vagrant box, Debian, Centos 7, two very custom ones based on 'Yocto', but the boxes are not the point.
The point is that vagrant itself drops an RSA1 key into the box during provisioning and it can't be used anymore.
I can fix it myself, but vagrant won't work 'Out of the box' with Fedora 33 policies anymore.

**Comment by bowmanjd** [comment]
Good points. And it isn't just a Fedora 33 thing, either. As OpenSSH has been stating in their [release notes](https://www.openssh.com/txt/release-8.4), "we will be disabling the 'ssh-rsa' public key signature algorithm by default in a
near-future release."

**Comment by floriplum** [comment]
I had the same problem today and i found out that you can still SSH into it with the default unsecure SSH key.  
When you are stuck at the vagrant up SSH connection try to SSH into it from another terminal(vagrant SSH or by specifying the SSH key manually with the -i flag).  
So it looks like the actual SSH implementation used in vagrant is using a "unsafe" key exchange method since it is working with standard openssh.

**Comment by tabowling** [comment]
I'm not sure if this helps or is a terrible idea, but here is how I resolved it, putting a per host entry in my user's ~/.ssh/config file.  That way it still enforces stronger security except for those older systems I access.

`cat ~/.ssh/config
Host  myrhel6node
      PubkeyAcceptedKeyTypes ssh-rsa`

**Comment by adamprice2** [comment]
Just revisiting to say this is still an issue in Fedora 34 and now in 35.

**Comment by chrisroberts** [comment]
@adamprice2 Can you provide a gist of the debug output from `vagrant up --debug` showing the failure of the SSH communicator? We are currently patching the net-ssh library to handle the ssh-rsa deprecation. If you could also provide the name of the box you are using so I can test it locally, that would be great as well.

Thanks!

**Comment by adamprice2** [comment]
I can't share the boxes I use everyday, but there is no reason so believe it would be any different with a standard centos 7 machine.
I'll give it a try tomorrow if I get a chance.

**Comment by adamprice2** [comment]
Hmm, ok I just tried again with a clean Fedora 35 install and a 'standard' centos/7 vagrant box was unable to reproduce, so it looks like this is now a problem with something at my end.

Going to close this issue now because I can't reproduce it in a way I can share, and I can fix it internally.

Sorry for the false alarm.
