### ISSUE TITLE
config.ssh.extra_args not respected/implemented in `vagrant up`

### ISSUE THREAD

**Issue by acilate** [hashicorp/vagrant#12005]
### Description

While executing the `vagrant up` command, config.ssh.extra_args parameter is not used / respected when Vagrant attempts to SSH to the host.

### Vagrant version

Vagrant 2.2.10

### Host operating system

MacOS Catalina 10.15.7 (19H2)

### Guest operating system

Oracle Server Linux 7.8

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "example.box"
  config.ssh.extra_args = "-oKexAlgorithms=diffie-hellman-group14-sha256"
end
```

### Debug output

Relevant error:
```
 INFO ssh: SSH not ready: #<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

could not settle on kex algorithm
Server kex preferences: diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512
Client kex preferences: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1>
```

Full log: https://gist.github.com/acilate/b164a8e208b7b54b049685995cfd71d8

### Expected behavior

Vagrant should respect the SSH configuration when attempting an SSH connection during the vagrant up command

### Actual behavior

Vagrant used a default kex config which prevented an SSH connection to the server

### Steps to reproduce

1. Build a vagrant base box with heightened SSHd configurations, restricting KexAlgorithms to "diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512"
2. Import the box into vagrant
2. Create Vagrant file
3. Execute `VAGRANT_LOG=info vagrant up`

**Comment by acilate** [comment]
`vagrant ssh` respects these configurations, and `vagrant halt` does NOT

**Comment by chrisroberts** [comment]
Hi there,

The `extra_args` options is specifically for options to be passed to the ssh executable which is invoked via `vagrant ssh` (https://www.vagrantup.com/docs/vagrantfile/ssh_settings#config-ssh-extra_args). A new feature request has been opened recently covering additions of new configuration options related to key algorithms as well as a free style equivalent to the `extra_args` option which can be used with the internal communicator: hashicorp/vagrant#11985

Cheers!

**Comment by acilate** [comment]
Perhaps I'm splitting hairs, but the documentation doesn't seem to make the distinction that these configuration directives ONLY apply to `vagrant ssh`.  The statement I see is "The settings within config.ssh relate to configuring how Vagrant will access your machine over SSH."  Which seems inaccurate given the above response that they are intentionally not respected when accessing the machine over SSH in any command other than `vagrant ssh`

Perhaps an update to the documentation could help, indicating that these directives have a more narrow scope so that users aren't misled into thinking they have a broad scope?

**Comment by chrisroberts** [comment]
@acilate Sure, I've added a note into the documentation to explicitly call out where it is applied.
