### ISSUE TITLE
Vagrant tries to detect ip from windows host with ip command

### ISSUE THREAD

**Issue by marbon87** [hashicorp/vagrant#12009]
### Vagrant version

2.2.6

### Host operating system

Ubuntu 20.04.1 LTS

### Guest operating system

WIndows Server 2016 Standard

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.guest = :windows
  config.vm.box = 'peru/windows-server-2016-standard-x64-eval'
  config.vm.synced_folder './', '/host_data',
        disabled: false,
        type: 'nfs'
end
```

### Debug output

https://gist.github.com/marbon87/7b81eecf56bb8158b59f82c9b93c7622

### Expected behavior

Current folder should me mounted with nfs on guest

### Actual behavior

Error occurs.

### Steps to reproduce

1. vagrant up --provider=libvirt --debug

**Comment by soapy1** [comment]
Thanks for submitting an issue. This looks like its an error coming back from the [libvirt plugin](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/6dfff8414fc0fb2b187a80d21c2a575773bc8fac/lib/vagrant-libvirt/action/prepare_nfs_settings.rb#L57).

I found a similar issue in the [libvirt plugin repo](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/715#issuecomment-320035415). So, I'm going to go ahead and close this issue.
