### ISSUE TITLE
libvirt rsync provisioning fails on rhel

### ISSUE THREAD

**Issue by daebenji** [hashicorp/vagrant#12001]
When submitting a bug report, please provide the minimal configuration and required information necessary to reliably reproduce the issue. It
should include a basic Vagrantfile that only contains settings to reproduce the described behavior.

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
# Redhat 8.2 (rhel82) machine
  config.vm.define "rhel82" do |rhel82|
    rhel82.vm.box = "generic/rhel8"
    # disable default shared folder
    rhel82.vm.synced_folder ".", "/vagrant", disabled: true
    # enable host-to-guest sync of ./shared via rsync to /mnt/shared
    rhel82.vm.synced_folder "./", "/mnt/shared", type: "rsync"
  end
end
```

### Debug output

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

if command -v dnf; then
  dnf -y install rsync
else
  yum -y install rsync
fi

Stdout from the command:

/bin/dnf
Extra Packages for Enterprise Linux 8 - x86_64  5.6 MB/s | 8.2 MB     00:01
Last metadata expiration check: 0:00:03 ago on Wed 28 Oct 2020 10:54:28 AM UTC.
No match for argument: rsync

Stderr from the command:

Error: Unable to find a match: rsync

### Expected behavior

it should let me do shell provision to setup rsync before the plugin tries to do the same. It has to crash, because there is no subscription-management or repo config done during that state. 

### Actual behavior

after vagrant up, the starting of the machine aborts, due to the vagrant plugin is not able to find/install rsync.

### Steps to reproduce

1. Setup Vagrant with the libvirt plugin
2. Apply Vagrantfile
3. vagrant up
4. Find error message

**Comment by lioramilbaum** [comment]
Was this issue solved?

**Comment by daebenji** [comment]
No. But there is a workaround which was provided in the gitter room of  vagrant.

The workaround is using triggers:

(1) typed triggers, like ones based on actions are an experimental Vagrant feature (https://www.vagrantup.com/docs/experimental#typed_triggers). In order to enable them, export the env var VAGRANT_DEFAULT_PROVIDER=typed_triggers

(2) you are using the libvirt, which is likely different from the virtualbox provider that I'm using. So, the specific action that you will need to attach to is likely different. This Vagrantfile works for me (on virtualbox):

ENV["VAGRANT_EXPERIMENTAL"] = "typed_triggers"
Vagrant.configure("2") do |config|
  config.vm.box = "generic/rhel7"
  config.trigger.after :"Vagrant::Action::Builtin::WaitForCommunicator", type: :action do |t|
    t.warn = "installing rsync"
    t.run_remote = {inline: "install....."}
  end
  config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: false
