### ISSUE TITLE
vagrant-vmware-desktop fails to install with vagrant 2.2.11 and vmware-utility 1.0.14

### ISSUE THREAD

**Issue by stolowski** [hashicorp/vagrant#12022]
I've upgraded vagrant to 2.2.11 and vagrant-vmware-utility to 1.0.14, then tried to update all plugins (in case vagrant-vmware-desktop got an update), but it failed on some dependencies (see below). I then removed vagrant and my ~/.vagrant.d data (except for boxes) following https://www.vagrantup.com/docs/installation/uninstallation and reinstalled them anew, but installation of vagrant-vmware-desktop fails with same error on dependencies:

```
$ vagrant plugin install vagrant-vmware-desktop
Installing the 'vagrant-vmware-desktop' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

Unresolved dependency found during sorting - net-ssh (>= 2.6.5) (requested by net-scp-1.2.1)
```

OS is MacOS 10.15.7 (19H2)

**Comment by sasg** [comment]
I faced the same issue after upgrade: 
vagrant to 2.2.11 and vagrant-vmware-utility to 1.0.14 on OS is MacOS 10.15.7 (19H2)

**Comment by fasmat** [comment]
Same issue here. Yesterday with 2.2.10 all good, today I upgrade to 2.2.11 and face the same issue as OP.

**Comment by stolowski** [comment]
I contacted support@ and they are aware of the bug; they suggested installing previous version until a fix is ready; I reainstalled old vagrant, vargant-vmware-utilty (they are available via the website under older versions.. links), and afterwards forced older plugin with:

$ vagrant plugin install vagrant-vmware-desktop --plugin-version=2.1.4

**Comment by fasmat** [comment]
@stolowski Same issue still:

```bash
vagrant plugin install vagrant-vmware-desktop --plugin-version=2.1.4
Installing the 'vagrant-vmware-desktop --version '2.1.4'' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

Unresolved dependency found during sorting - net-ssh (>= 2.6.5) (requested by net-scp-1.2.1)
```

**Comment by stolowski** [comment]
@fasmat Have you downgraded vagrant and vagrant-vmare-utility as well? You need 2.2.10 and 1.0.13, respectively. That solved the problem for me. Anyway, I'll let the developers chime in and hopefully fix this soon.

**Comment by fasmat** [comment]
> @fasmat Have you downgraded vagrant and vagrant-vmare-utility as well? You need 2.2.10 and 1.0.13, respectively. That solved the problem for me. Anyway, I'll let the developers chime in and hopefully fix this soon.

Not yet, I'll try that later. Thanks!

**Comment by zhernosekim** [comment]
I can confirm,. So I had reverted vagrant to 2.2.10 and error disappeared.

**Comment by pedrofurtado** [comment]
Same issue here. Once upgraded to vagrant 2.2.11, this error appears 🤯

**Comment by chrisroberts** [comment]
Hi everyone,

The 2.2.12 release has this issue fixed (it includes this PR: #12023). The root cause was due to my trying to include a fix for the SHA1 host auth deprecation in ssh and the fix is only available in an RC at this point. Vagrant's build was happy and tests were good, but it inadvertently prevented plugin dependency resolution to properly complete. The 2.2.12 release includes an update to the internal plugin manager to properly handle prerelease constraints when they are encountered, which also allows the net-ssh fix to still be included as well.

Apologies for the troubles this caused!

**Comment by eHildy** [comment]
Just downloaded 2.2.12, and I'm sorry to say the error is still exactly the same on Windows 10 with VmWare Utility v1.0.14

**Comment by pedrofurtado** [comment]
V2.2.12 not fixed the error. same situation here 😢

**Comment by pedrofurtado** [comment]
Could you reopen the issue, @chrisroberts ? 🤝

**Comment by chrisroberts** [comment]
Hi, yes we found the issue right after I responded :slightly_frowning_face: . I'm currently waiting on notarization to finish.

**Comment by tobiasdewinter** [comment]
I had the same problem, I can confirm that upgrading Vagrant to version 2.2.13 fixed the issue for me.

**Comment by sorcererstone** [comment]
@tobiasdewinter. I downloaded and installed latest vagrant yesterday (aka V2.2.13). Some error. 
Have anyone experience this error in 2.2.12 or 2.2.11? I skipped these 2 versions and upgraded to 2.2.13 and got this error.
Unresolved dependency found during sorting - net-ssh (>= 2.6.5) (requested by net-scp-1.2.1)
Not really want to go back to 2.2.10 as earlier post suggested.

**Comment by pedrofurtado** [comment]
For a while, to me, the workaround is downgrade to v2.2.10.

**Comment by LinaC404** [comment]
I met the same error message (in Windows10). I update the vagrant to the latest version 2.2.13 which worked for me.

**Comment by sorcererstone** [comment]
@tobiasdewinter. Apologized. Just found out what I downloaded when I access Vagrant web page yesterday. It was version 2.2.11 (which is very weird - not the latest version!) I have since uninstalled 2.2.11 and installed 2.2.13. That unresolved dependency error did not show up anymore. You were right. Sorry.

**Comment by chrisroberts** [comment]
Hi everyone,

So my previous comment https://github.com/hashicorp/vagrant/issues/12022#issuecomment-723335575 is for real in the 2.2.13 release. Some isolation refactoring resulted in missing a required modification preventing the prerelease version for net-ssh to be allowed within the dependency resolution. We haven't needed to utilize prerelease resolutions previously, but the deprecation of SHA1 algos has resulted in a greater need for allowing it. I'm also adding some extra testing to validate expected resolutions in various states when we run acceptance tests which will prevent unexpected errors like this in the future.

Cheers!
