### ISSUE TITLE
Vagrant up not working

### ISSUE THREAD

**Issue by KarthikSivalingam** [hashicorp/vagrant#12036]
E:\shellclass\testbox01>vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

**Comment by soapy1** [comment]
Hey there, it looks like you need to install some provider on your system. Virtualbox is just as good as any, here is a link: https://www.virtualbox.org/wiki/Downloads
I'm going to go ahead and close this issue. If the problem persists after verifying you have one of Virtualbox or Hyper-V installed on your machine, please feel free to reopen the issue 🌞
