### ISSUE TITLE
/sbin/mount.vboxsf: mounting failed with the error: No such device

### ISSUE THREAD

**Issue by xmunoz** [hashicorp/vagrant#12033]
### Vagrant version
2.2.13

### Host operating system
Ubuntu 20.04

### Guest operating system
Debian 10

### Vagrantfile

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian10"
  config.vm.box_version = "3.1.0"
  config.vm.define "permanent"
  config.vm.box_check_update = true
  config.vm.synced_folder "../api", "/data/www/api", owner: "vagrant", group: "www-data"

 config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.memory = "4096"
    vb.cpus = 2
    vb.linked_clone = true
  end
end
```

### Debug output

https://gist.github.com/xmunoz/7fae9f013b268e2032139ac3a238c5d8

### Expected behavior

Vagrant should detect and download the correct version of VBox Guest Additions on the guest VM, and succeed in mounting the shared folders.

### Actual behavior

Vagrant fails to download newer Virtualbox Guest Additions on the guest, and mounting shared folders fails.

### Steps to reproduce

1. vagrant plugin install vagrant-vbguest
2. vagrant up

**Comment by isuftin** [comment]
Possibly linked to https://github.com/hashicorp/vagrant/issues/12035 ?

**Comment by xmunoz** [comment]
Maybe? I also found that downgrading to 2.2.10 fixed the problem for me.

**Comment by jasonaowen** [comment]
I am also affected by this. I am on Ubuntu 18.04, with `virtualbox` version `5.2.42-dfsg-0~ubuntu1.18.04.1` and with Vagrant installed from [Wolfgang Faust's PPA](https://vagrant-deb.linestarve.com/). `1:2.2.10` works; `1:2.2.11` does not.

I downgraded by running:

```
$ sudo apt install vagrant=1:2.2.10
```

**Comment by soapy1** [comment]
This issue is resolved by https://github.com/hashicorp/vagrant/pull/12037. It will be available in the next release of Vagrant. I'm going to go ahead and close this issue. Cheers 🎆

**Comment by xmunoz** [comment]
Awesome! Would that be v2.2.15 @soapy1 ? When would it become publicly available?

**Comment by chrisroberts** [comment]
@xmunoz The release build is currently in process and should be available in an hour or or two
