### ISSUE TITLE
unknown error encountered with vmrest process

### ISSUE THREAD

**Issue by jwbaker-mitre** [hashicorp/vagrant#12041]
### Vagrant version
Vagrant 2.2.13
Vagrant VMware Utility (1.0.16)
vmware-desktop-plugin (2.1.5)

### Host operating system / virtualization
Windows 10 (Build 19041)
VMWare Workstation 16 Pro (16.0.0 build-16894299)

### Guest operating system
DetectionLab (Ubuntu 18.04, Windows Server 2016 x2, Windows 10)
https://detectionlab.network/introduction/

### Vagrantfile
https://raw.githubusercontent.com/clong/DetectionLab/master/Vagrant/Vagrantfile

### Debug output
https://gist.github.com/jwbaker-mitre/fd9ba2f0afde083189614843f04278aa

### Expected behavior

Normal behavior expected to standup VM's

### Actual behavior
```cmd
==> logger: Verifying vmnet devices are healthy...
Vagrant failed to create a new VMware networking device. The following
error message was generated while attempting to create a new device:

  unknown error encountered with vmrest process
```
### Steps to reproduce
https://detectionlab.network/deployment/windowsvm/

### References

https://github.com/clong/DetectionLab/issues/555

**Comment by thorerik** [comment]
I'm encountering the same issue, I can reproduce the error with this Vagrantfile:
```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
  
    config.vm.define "jump", primary: true do |jump|
      jump.vm.network "private_network", ip: "172.17.177.10"
    end
end
```

**Comment by soapy1** [comment]
Hey there, a new version of the vmware utility (1.0.17) was [released](https://www.vagrantup.com/vmware/downloads) 🪂 that includes a fix for this issue. So, I'm going to go ahead and close this issue. Thanks for the report!
