### ISSUE TITLE
Vagrant synced folder issue with pip: Could not install packages due to an EnvironmentError: [Errno 39] Directory not empty

### ISSUE THREAD

**Issue by plowman** [hashicorp/vagrant#12057]
### Overview
At a high level, here's what I'm seeing:
* I'm sharing a single synced_folder with the guest machine
* In the provisioning shell script, when I try to upgrade pip to the latest version using `pip install --upgrade pip`, it gives this error:
    ```
    ERROR: Could not install packages due to an EnvironmentError: [Errno 39] Directory not empty: '_internal'
    ```
* If I comment out that single `vm.synced_folder` line from the Vagrantfile, everything works as expected.

### Additional details
* I suspect that pip is attempting to delete a folder which, due the the synced_folder synchronization, is not being properly deleted inside the guest machine OR the host machine is restoring the files as the guest machine pip tries to delete them.
* It seems as if the synced_folder is interfering with pip as it tries to delete the old version of pip out of `./env/lib/python3.9/site-packages/pip`. When this happens there are two files named "_internal" it could be referring to inside /project/server/env/lib/python3.9/site-packages: pip/_internal and ~ip/_internal. It's not clear to me which of these folders is actually causing the issue.

### Vagrant version
Vagrant 2.2.10

### Host operating system
macOS Big Sur: 11.0.1 (20B29)

### Guest operating system
Ubuntu 20.04 (Using the vm box bento/ubuntu-20.04)

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.hostname = "bug-report-directory-not-empty"

  # If you comment out the following line, it will work
  config.vm.synced_folder ".", "/project/server"

  config.vm.provision "shell", inline: <<-SHELL
    ####################################################################################################################
    sudo apt-get update

    sudo apt-get install -y \
      python3.9 \
      python3.9-dev \
      python3-pip \
      virtualenv

    ####################################################################################################################
    # Initialize virtualenv + install pip packages
    rm -rf /project/server/env
    mkdir -p /project/server/env
    cd /project/server
    virtualenv --python=python3.9 env
    source env/bin/activate

    # This line generates the error
    pip install --upgrade pip
  SHELL
end
```

### Debug output
* [Here is the gist debug output of the failure.](https://gist.github.com/plowman/f7f63711af2e537828f871eb2a5d35e2)

### Expected behavior
* `pip install --upgrade pip` should complete with the message `Successfully installed pip-20.2.4`

### Actual behavior
* `pip install --upgrade pip` fails with the error message: `ERROR: Could not install packages due to an EnvironmentError: [Errno 39] Directory not empty: '_internal'`

### Steps to reproduce
1. vagrant destroy --force
2. vagrant up

**Comment by tdyas** [comment]
I'm just a fellow Vagrant user, but I've seen this issue with `pip` before. Are you using Virtualbox for the underlying VM? If so, the issue is probably https://www.virtualbox.org/ticket/8761 which is a silent failure in deleting files on a `vboxsf` filesystem. (The bug is probably in the kernel driver for the `vboxsf` filesystem.)

I've worked around the issue personally by having `pip` install into a directory that is not on a shared folder (e.g., in /tmp), and then copy that directory to the shared folder, and then use `find/sed` to fix up the path to Python in `#!` references in the scripts in the venv's bin directory.

**Comment by farhour** [comment]
I faced the same problem, and it was related to the synced_folder synchronization. When I put the virtual environment of Python to another directory (that was not synced, such as ~/vagrant/venv), the problem was fixed. @plowman @tdyas

**Comment by hardway** [comment]
Another workaround could be adding parameter "--ignore-installed" to pip
eg: pip install --upgrade pip --ignore-installed

**Comment by pollardld** [comment]
Were you able to sleuth out an answer @plowman? 
I'm all 👂s

**Comment by chrisroberts** [comment]
This unfortunately is not that uncommon with actions like there where a bunch of modifications are happening quickly on the synced folder when it is being provided with vboxfs. A generally easy workaround for this is setting the install to a directory that is not shared between the guest and the host. Another option can be to use a different provider for the synced folder (like NFS or SMB) which don't experience the same issue.

Cheers!
