### ISSUE TITLE
Vagrant 2.2.10 regression on Windows HOST for SMB share folders - incorrect credentials

### ISSUE THREAD

**Issue by okomarov** [hashicorp/vagrant#12058]
### Vagrant version
2.2.10 - 2.2.13
### Host operating system
Windows Version	10.0.19041 Build 19041
### Guest operating system
hashicorp/precise64
### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/precise64"
    config.ssh.forward_agent = true
    config.ssh.insert_key = false
    config.vm.hostname = "myhostname"

    config.vm.provider "hyperv" do |hv, hv_config|
      hv_config.vm.synced_folder ".", "/vagrant",
        type: "smb",
        smb_username: "windows username",
        mount_options: ["mfsymlinks"]
    end
  end
```

### Debug output
https://gist.github.com/okomarov/72634c341c8865674745f25d1fc1449f

### Expected behavior
When prompted for Windows host credentials it should accept them and create the shared folder. This works fine on Vagrant 2.2.9.

### Actual behavior
After entering the credentials, it keeps posting: "Invalid credentials"

* ### Steps to reproduce

1. `vagrant up`
2. Enter your windows account credentials

### References
Potentially caused by:
* host/windows: Properly register SMB password validation capability [GH-11795]

**Comment by Sebjugate** [comment]
Can confirm, I experienced the same with 2.2.16, downgrading to 2.2.9 worked.
