### ISSUE TITLE
Guest machine entered an invalid state while waiting for it to boot.

### ISSUE THREAD

**Issue by sajusat** [hashicorp/vagrant#12066]
### Vagrant version
Installed Version: 2.2.14

### Host operating system
Ubuntu 20.04 LTS

### Guest operating system
vagrant box 'debian/buster64' 

### Vagrantfile

```ruby
    N = 3
      (1..N).each do |machine_id|
        config.vm.define "node#{machine_id}" do |machine|
          machine.vm.box = "debian/buster64"
          machine.vm.hostname = "node#{machine_id}"
          machine.vm.network "public_network", bridge: "wlp59s0", ip: "192.168.100.#{200+machine_id}"
          machine.vm.provider "virtualbox" do |vbox|
            vbox.name = "node#{machine_id}"
            vbox.cpus = "1"
            vbox.memory = "512"
            vbox.gui = true
          end
          machine.vm.provision :ansible do |ansible|
            ansible.playbook = "../dev.site.yaml"
          end
        end
      end
```

### Debug output
https://gist.github.com/sajusat/7264df6f66ee36093e4afb28b8b5cf0b

### Expected behavior
The machines should come back up as it supposed to be.

### Actual behavior

I am using the debian/buster64 image from vagrant cloud to create 3 VM's. Everything works fine. Once I shut down these machines and do a
`vagrant up`

The vagrant machine halts at ` node1: SSH auth method: private key`. My only option is to vagrant destroy and recreate all the machine from scratch. 
This is what I see on the Virtualbox GUI

    error symbol 'grub_calloc' not found
    entering rescue mode
    grub rescue >_
I have VT-x/AMD enabled and I can see that in the GUI on the vm general information as well.

### Steps to reproduce

1. Run the vagrant up.
2. vagrant halt
3. vagrant up

### References

- ...

**Comment by chrisroberts** [comment]
Hi there,

This appears to be an error in grub2: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966575

Closing as this is not an issue with Vagrant itself.

Cheers!
