### ISSUE TITLE
VAGRANT_LOG oddity

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#12068]
VAGRANT_LOG actually shows even more noisy logs when explicitly configured, compared to the medium-noisy behavior. For example, additional logs appear when set to warn or error.

**Comment by soapy1** [comment]
Heya, thanks for opening up an issue. This is the desired behavior. From the [VAGRANT_LOG docs](https://www.vagrantup.com/docs/other/environmental-variables#vagrant_log):

> VAGRANT_LOG specifies the verbosity of log messages from Vagrant. By default, Vagrant does not actively show any log messages.
Log messages are very useful when troubleshooting issues, reporting bugs, or getting support. At the most verbose level, Vagrant outputs basically everything it is doing.
