### ISSUE TITLE
Plugin hooks executed multiple times

### ISSUE THREAD

**Issue by Mte90** [hashicorp/vagrant#12070]
### Vagrant version

2.2.14

### Host operating system

Linux

### Guest operating system

Linux

### Vagrantfile

```
config.goodhosts.aliases = ["alias.testing.de", "alias2.somedomain.com"]
config.goodhosts.remove_on_suspend = true
```

### Debug output
![Screenshot_vvv](https://user-images.githubusercontent.com/403283/99972195-838bec00-2d9e-11eb-8c2c-7b69323a5737.png)

### Expected behavior

Plugin hook executed just once.

### Actual behavior

Multiple execution of hooks.

### Steps to reproduce

1. Install vagrant 2.2.14
2. Install GoodHosts vagrant plugin -> https://github.com/goodhosts/vagrant
3. Add in a vagrant file the code above

The goodhosts plugin is a fork of [hostsupdater plugin](https://github.com/agiledivider/vagrant-hostsupdater) that instead use a cli utility to update the hosts file. So has less code but the engine use hooks https://github.com/goodhosts/vagrant/blob/master/lib/vagrant-goodhosts/plugin.rb and before that version they were executed just once.

**Comment by chrisroberts** [comment]
Hi there,

The root cause of the behavior you are experiencing is due to previous versions of Vagrant not properly calling all hooks. This has been resolved, and is now causing the issue you describe due to the plugin using multiple hooks which are called during a single run. The plugin will have to adjust how the hooks are used, either to reduce the number of hooks or to utilizing some marking pattern to flag when the plugin has run so subsequent hooks do not execute it again.

Cheers!

**Comment by Mte90** [comment]
I tested and seems that code like:
```
      action_hook(:goodhosts, :machine_action_up) do |hook|
        hook.append(Action::UpdateHosts)
      end

      action_hook(:goodhosts, :machine_action_provision) do |hook|
        hook.before(Vagrant::Action::Builtin::Provision, Action::UpdateHosts)
      end

      action_hook(:goodhosts, :machine_action_halt) do |hook|
        hook.append(Action::RemoveHosts)
      end

      action_hook(:goodhosts, :machine_action_suspend) do |hook|
        hook.append(Action::RemoveHosts)
      end

      action_hook(:goodhosts, :machine_action_destroy) do |hook|
        hook.append(Action::RemoveHosts)
      end

      action_hook(:goodhosts, :machine_action_reload) do |hook|
        hook.prepend(Action::RemoveHosts)
        hook.append(Action::UpdateHosts)
      end

      action_hook(:goodhosts, :machine_action_resume) do |hook|
        hook.prepend(Action::RemoveHosts)
        hook.append(Action::UpdateHosts)
      end
```

It is executed just once, so I don't understand why a hook should be executed multiple times during a `action_up` as example.

Ref: https://github.com/goodhosts/vagrant/blob/master/lib/vagrant-goodhosts/plugin.rb

**Comment by Mte90** [comment]
The issue @chrisroberts is happening also with other plugins don't updated anymore.
Ours is based on one of them but I don't understand how the the latest version changed that behavior.
Our code should append the hook when the vm is in a specific state not in others.

This is the reason why I don't understand what was the wrong behavior of Vagrant on that side. If I need to append an hook on a state why this should happens also with the others?

**Comment by Mte90** [comment]
I am looking to other plugins and they do the same way as ours https://github.com/search?l=Ruby&o=desc&q=action_hook&s=indexed&type=Code

There is in case documentation for plugin developers to avoid this issue @chrisroberts ?
