### ISSUE TITLE
windows10/vagrant/virualbox/centos8 synced folder not work

### ISSUE THREAD

**Issue by LY1806620741** [hashicorp/vagrant#12073]
### Vagrant version
Installed Version: 2.2.14
Latest Version: 2.2.14
### Host operating system

windows10

### VM

Virtualbox 6.0

### Guest operating system

Centos8

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.box_version = "1905.1"
  config.vagrant.plugins = ['vagrant-disksize']
  config.disksize.size='50GB'
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf install -y cloud-utils-growpart
    sudo growpart /dev/sda 1
    sudo xfs_growfs /
  SHELL
end
```

### Expected behavior

[vagrant doc  test-the-synced-folder](https://learn.hashicorp.com/tutorials/vagrant/getting-started-synced-folders?in=vagrant/getting-started#test-the-synced-folder) work.

### Actual behavior

I touch foo, And look at my host OS. foo  is not on my host machine.

### Steps to reproduce

1. `vagrant up` and see the log `default: Rsyncing folder: /cygdrive/c/Users/xxx/Desktop/centos8/ => /vagrant`
2. then I `vagrant ssh` entry centos8 and `touch /vagrant/foo`
3. open host OS Files explorer and go to path `c/Users/xxx/Desktop/centos8`
4. can't find the file `foo` in there
5. I open Virtrualbox's GUI manager found that shared folder is empty.
6. I try `vagrant rsync-auto --debug`, It work, but only watch host folder's change.It can't watch Guest OS Path` /vagrant/` change, The same is `rm $file`.

**Comment by soapy1** [comment]
Hey there, this behavior is expected for the rsync synced folder type. From the [documentation](https://www.vagrantup.com/docs/synced-folders/rsync)

> The rsync synced folder does a one-time one-way sync from the machine running to the machine being started by Vagrant.

The [rsync-auto](https://www.vagrantup.com/docs/cli/rsync-auto) feature will watch files in the local directory. However this is still only a one way sync from host -> guest. 

If you want to be able to have a 2 way sync then I would suggest using a different synced folder type. You could alternatively use [SMB](https://www.vagrantup.com/docs/synced-folders/smb). If you are using a Virtualbox provider, use [the virtualbox type](https://www.vagrantup.com/docs/synced-folders/virtualbox). You can change the type of synced folder in your Vagrantfile by using the [type option](https://www.vagrantup.com/docs/synced-folders/basic_usage#type)

```
  config.vm.synced_folder ".", "/vagrant", type: "smb"
```

Cheers!

**Comment by LY1806620741** [comment]
Actually, I don't want to use smb or rsync-auto, Neither or  rsync.exe, I hope vagrant can work as document say's  [Virtual machines are convenient for developing in, but not many people want to edit files using a plain terminal-based editor over SSH. Vagrant automatically syncs files to and from the guest machine. This way you can edit files locally and run them in your virtual development environment.](https://learn.hashicorp.com/tutorials/vagrant/getting-started-synced-folders?in=vagrant/getting-started). Maybe this example is Base on Linux/Mac, so I give up. Now I use vscode ssh remote to edit my guest OS's file.
