### ISSUE TITLE
OpenSSL SSL_read: Connection was reset, errno 10054

### ISSUE THREAD

**Issue by Nazmulho71** [hashicorp/vagrant#12071]
After using `vagrant box add laravel/homestead`, I selected virtualbox (option: 3). But when it starts downloading, it shows the following error:
```
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_read: Connection was reset, errno 10054
```

**Comment by soapy1** [comment]
Hey there, thanks for opening up an issue. Could you include some extra information about this. In particular, the host OS, and a [debug gist](https://www.vagrantup.com/docs/other/debugging). Thanks!

**Comment by soapy1** [comment]
Looking into the error `OpenSSL SSL_read: Connection was reset, errno 10054` a little bit more, this seems to be a local networking issue. You might be able to resolve this issue by retrying on a more stable/faster internet connection.

**Comment by Nazmulho71** [comment]
> Looking into the error `OpenSSL SSL_read: Connection was reset, errno 10054` a little bit more, this seems to be a local networking issue. You might be able to resolve this issue by retrying on a more stable/faster internet connection.

It perfectly works now. Thanks!
