### ISSUE TITLE
Vagrant is installing the guest additions before provisioning gives an error

### ISSUE THREAD

**Issue by DennisvG** [hashicorp/vagrant#12084]
With vagrant 2.2.14 I wanted to install a new centos 8 virtualbox image. I always want to use my provisioning script (yum update all) before the installation of the "Virtualbox guest additions". That worked fine for me. But now vagrant tries to install the guest addtions before provisioning which causes errors like:
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
yum install -y kernel-devel-`uname -r` --enablerepo=C*-base --enablerepo=C*-updates
Stdout from the command:
Stderr from the command:
Error: Unknown repo: 'C*-base'

And after upgrading the vagrant-vbguest plugin:
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
umount /mnt
Stdout from the command:
Stderr from the command:
umount: /mnt: not mounted.

Workarround:
run first "vagrant up" with config.vbguest.auto_update = false
run "vagrant halt"
and run   "vagrant up" with config.vbguest.auto_update = true
The guest additions are installed.

**Comment by achubb** [comment]
Thanks @DennisvG got my Vagrant box (Debian 9 image) back up. Can confirm had exact same issue.

**Comment by chrisroberts** [comment]
Unfortunately this appears to be an issue with the vbguest plugin, and not vagrant itself so I'm going to close this issue up. Cheers.
