### ISSUE TITLE
vagrant up fails when base_address is set with VMware Fusion 12.1

### ISSUE THREAD

**Issue by hqstevenson** [hashicorp/vagrant#12094]
I upgraded OS X to Big Sur 11.0.1 and VMware Fusion to 12.1.0 at the same time and after the upgrades I can no longer start VMs previously created with base_address set.  I can't create new VMs this way either.

I don't know if the issue was caused by the VMware Fusion upgrade or the Big Sur upgrade since I did them at the same time.  However, VMware Fusion started giving lower IP addresses after the upgrade when I'm using DHCP.  Before the upgrade, I would receive addresses in the range of 192.168.23.128 - 192.168.23.254, but after the upgrade I'm getting IP addresses starting with 192.168.23.3

### Vagrant version
2.2.14 

### Host operating system
OS X Big Sur (11.0.1)

### Guest operating system
Linux (CentOS)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh", disabled: true

  config.vm.hostname = 'static-ip'
  config.vm.base_mac = '00:0c:29:c4:81:23'
  config.vm.base_address = '192.168.23.41'

  config.hostmanager.enabled = false

  config.vm.provider :vmware_desktop do |vmware|
    vmware.gui = false
    vmware.linked_clone = false
    vmware.ssh_info_public = true
    vmware.unmount_default_hgfs = true
    vmware.vmx["ulm.disableMitigations"] = "TRUE"
    vmware.vmx["memsize"] = "16384"
    vmware.vmx["numvcpus"] = "4"
  end

end
```

### Debug output
https://gist.github.com/hqstevenson/d30de90d598d34ae09500f682b9a8dfc

### Expected behavior
VM should start with static/reserved ip
### Actual behavior

What actually happened?
Vagrant reports error

Vagrant encountered an error while attempting to create a DHCP
reservation for the base adapter.

  Address: 192.168.23.41
  Device:  vmnet8
  MAC:     00:0C:29:C4:81:23
  Reason:  failed to create dhcp reservation

### Steps to reproduce
1.  run 'vagrant up' with this Vagrantfile

**Comment by chrisroberts** [comment]
Hi there,

The latest version of the vagrant-vmware-utility will provide an error message that is more clear. VMware Fusion 12 on macOS no longer uses VMware's vmnet and has lost the ability to perform dhcp reservations for guests.

Cheers
