### ISSUE TITLE
Vagrant 2.2.14:  vbguest plugin doesn't trigger 

### ISSUE THREAD

**Issue by mspruthv** [hashicorp/vagrant#12095]
### Vagrant version
Vagrant 2.2.14

### Host operating system
macOS Catalina 10.15.7

### Guest operating system
centos/7

### Vagrantfile

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-disksize", "vagrant-vbguest"]
  config.vm.box = "centos/7"
  config.disksize.size = '120GB'
  config.vm.provider 'virtualbox' do |v|
    # Increase VM default memory/cpu:
    v.memory = "2048"
    v.cpus = "2"
    # No audio needed (can cause high cpu via logd after hibernation):
    v.customize ['modifyvm', :id, '--audio', 'none']
  end
end
```

### Debug output

https://gist.github.com/mspruthv/cef999d7316a41f1e3676957854c896a

### Expected behavior

vbguest plugin should trigger & mount vbguest iso should proceed

### Actual behavior

No package kernel-devel-3.10.0-1127.el7.x86_64 available.
Error: Nothing to do
Unmounting Virtualbox Guest Additions ISO from: /mnt
umount: /mnt: not mounted

### Steps to reproduce

1.  Copy paste above Vagrantfile
2. vagrant up

**Comment by veics** [comment]
Hey @mspruthv,
This is an ongoing and old issue whenever CentOS updates their repos, but not their CentOS base box.
Basically the CentOS that you're installing is containing an old kernel version which has been removed from CentOS repositories.
Vagrant is trying to install Guest Additions, which has as a dependency the kernel-devel package. kernel-devel package must be the same version as the kernel package that you have it installed in your CentOS box, version which is removed from the CentOS repos.

As a **manual** workaround, you can connect to the box via `vagrant ssh` and update the kernel package

Reference: https://github.com/dotless-de/vagrant-vbguest/issues/351
My issue: https://github.com/hashicorp/vagrant/issues/12101

**Comment by chrisroberts** [comment]
Closing as error encountered is not due to Vagrant. Cheers
