### ISSUE TITLE
Trigger before action not working

### ISSUE THREAD

**Issue by veics** [hashicorp/vagrant#12101]
### Vagrant version

Vagrant 2.2.14

### Host operating system

macOS Catalina 10.15.7

### Guest operating system

centos/7

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|

  config.trigger.before :"VagrantPlugins::ProviderVirtualBox::Action::CheckGuestAdditions", type: :action do |trigger|
      trigger.warn = "Updating kernel first..."
      trigger.run = {inline: "sudo yum -y update kernel*"}
  end
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  [...]
end
```

### Debug output

https://gist.github.com/veics/54b043595dba545c6be5f766e24fc14c

### Expected behavior

Should trigger the warning message and run the shell command line.

### Actual behavior

==> ubs-ra-dev-local: Waiting for machine to boot. This may take a few minutes...
    zzz: SSH address: 127.0.0.1:2222
    zzz: SSH username: vagrant
    zzz: SSH auth method: private key
    zzz: 
    zzz: Vagrant insecure key detected. Vagrant will automatically replace
    zzz this with a newly generated keypair for better security.
    zzz: 
    zzz: Inserting generated public key within guest...
    zzz: Removing insecure key from the guest if it's present...
    zzz: Key inserted! Disconnecting and reconnecting using new SSH key...
==> zzz: Machine booted and ready!
[zzz] No Virtualbox Guest Additions installation found.
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile

### Steps to reproduce

Create a CentOS box with the latest base box and add the trigger from my Vagrantfile

### References

The latest CentOS base box provided by CentOS has an outdated kernel version, while the kernel devel package is not in repos anymore.

Workaround using triggers taken from here: https://github.com/dotless-de/vagrant-vbguest/issues/351
Proof that I'm not the only one encountering this issue: https://github.com/hashicorp/vagrant/issues/12095

**Comment by soapy1** [comment]
Hey there, 
taking a look at your debug output it seems like this is the correct behavior for Vagrant. [Typed triggers](https://www.vagrantup.com/docs/experimental#typed_triggers) are a an experimental Vagrant feature. To enable them set the `VAGRANT_EXPERIMENTAL` environment variable to `typed_triggers`.

You can tell that this feature has been enabled when the Vagrant output includes a message like:
```
==> vagrant: You have requested to enabled the experimental flag with the following features:
==> vagrant: 
==> vagrant: Features:  typed_triggers
==> vagrant: 
==> vagrant: Please use with caution, as some of the features may not be fully
==> vagrant: functional yet.
```

Once this feature is enabled, then Vagrant should have your desired behavior.

**Comment by veics** [comment]
Hi @soapy1,

My bad, I have missed this thing. In the meantime I ended up building my own custom vagrant base image.

I will come back trying "typed triggers" as soon as I'll have some spare time.

Thanks!

**Comment by soapy1** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue. Thanks! 😄
