### ISSUE TITLE
Mac OS Big Sur with M1 Mini:   There was an error while executing `VBoxManage`, a CLI used by Vagrant for controlling VirtualBox

### ISSUE THREAD

**Issue by jmpreston** [hashicorp/vagrant#12105]
### Vagrant version

2.2.14.

### Host operating system

Mac OS 11.0.1 Big Sur on a 2020 Mac Mini with the new M1 chip and Rosetta installed to emulate an Intel chip.

### Guest operating system

Ubuntu 18

### Vagrantfile

```

Vagrant.configure("2") do |config|
    config.vm.define "xyz" do |xyz|
        pfzr.vm.box = "bento/ubuntu-18.04"
        pfzr.vm.network "forwarded_port", host: 8086, guest: 80
        pfzr.vm.network "forwarded_port", host: 3000, guest: 3000
        pfzr.vm.provision :shell, path: ".provision/bootstrap.sh"
        pfzr.vm.synced_folder "ubuntu/", "/home/vagrant"
        pfzr.vm.box_check_update = "true"
        pfzr.vm.hostname = "xyz"
        pfzr.ssh.insert_key = false
        # VirtualBox setup
              config.vm.provider "virtualbox" do |vb|
                    # vb.gui = true
                    vb.name = "xyz" # friendly name for Oracle VM VirtualBox Manager
                    vb.memory = 2048 # memory in megabytes 2.0 GB
                    vb.cpus = 1 # cpu cores, can't be more than the host actually has.
              end
    end
```

### Debug output

There seems to be a problem around line 2377.

https://gist.github.com/jmpreston/bd2a8fc52df400c66b12df3d38f735b9

### Expected behavior

Vagrant boots and I can get to work.  

I have Vagrant working fine with the same Vagrantfile and setup on my 2016 MBP.

### Actual behavior

The following error is after the boot up says "Booting VM..."

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "631a6bcf-0479-4362-8972-0fc17c6a085c", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'pfzr' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

### Steps to reproduce

1.  Vagrant up

### Steps to fix the problem

1.  I purchased a 2020 Mac Mini with the new M1 chip and transferred the apps, files, and setting from a 2014 Mac Mini.
2.  Uninstalled older VirtualBox with their uninstaller and installed the latest version.
3.  Uninstalled an older Vagrant with the uninstaller and installed the latest version of Vagrant.
4.  Deleted .vagrant.d in the user directory.  Deleted .vagrant in the directory with the Vagrantfile.

### References

There are other issues with similar but not the same problem.  I tried all their remedies but no help.

**Comment by schwemmer** [comment]
Sadly, VirtualBox does not work on the new ARM-based Macs with the M1 chip. See for example this forum topic: https://forums.virtualbox.org/viewtopic.php?t=98742

**Comment by jmpreston** [comment]
Thank you for the link.  Interesting thread and I learned more about hypervisors.  I have the Mac's Rosetta running to emulate x86 but apparently that won't work.  VB checks for system compatibility when I installed it and it passed but maybe Rosetta fooled it.

**Comment by jmpreston** [comment]
At this time there are no VM's that run on the M1 per research I've done on 11 December 2020.  The VMware Fusion site says it will run on all 2020 Macs but it appears to be outdated.  I hope this helps others get to an answer faster than I did and lose less time.  Meanwhile, I'm excited about the M1 for video editing, just a hobby, and waiting anxiously for a VM that will work with Vagrant on the M1.  Apparently Ubuntu will run on the M1 per forums.

**Comment by schwemmer** [comment]
> At this time there are no VM's that run on the M1 per research I've done on 11 December 2020.

That was my conclusion too, after some research. I was excited to get an M1 and almost got one when I found out that I couldn't use it for work. I need VMs and Vagrant (and Ansible) to work. The VirtualBox forum thread indicates that it's very unlikely for VirtualBox to be rewritten for ARM CPUs, so I'm hoping for a VMware Vagrant plugin in the future.

**Comment by jmpreston** [comment]
The VMware Fusion blog seems to indicate that they are working on it.  Guesses are that it will be ready in a few months.  I'm fine with dumping VirtualBox.  Vagrant has a VMware plugin but I have no idea if it will work with an ARM Fusion.  Too technical for me.  Meanwhile, the M1 is terrific.  I wanted to buy it this year for the business tax write-off anyway.

**Comment by jimlongo56** [comment]
New Macbook Air with M1.
Mac OS 11.1
VirtualBox 6.1
Vagrant 2.2.14

I get the errors mentioned in this tread https://github.com/hashicorp/vagrant/issues/12049

Starts with the error `Command: ["hostonlyif", "create"]`

Follow recommendation to uninstall/reinstall and check the Privacy Prefs.
But the Privacy pane does not show the untrusted Oracle software in question.

Follow suggestion to start VirtualBox manually to generate the Privacy option.
When starting VirtualBox manually it fails with the following error

<img width="394" alt="Screen Shot 2021-01-08 at 5 02 24 PM" src="https://user-images.githubusercontent.com/6787988/104068871-51f6a500-51d3-11eb-8452-6857f03e1d09.png">
