### ISSUE TITLE
Very slow download speeds

### ISSUE THREAD

**Issue by nessor** [hashicorp/vagrant#12112]
### Vagrant version
2.2.14

### Host operating system
Win10 64bit

### Guest operating system

Ubuntu (?)

### Expected behavior

Normal download speeds

### Actual behavior

very very slow speeds

### Steps to reproduce

1. ```vagrant box add laravel/homestead```

### References

- https://github.com/hashicorp/vagrant/issues/11730
- https://github.com/hashicorp/vagrant/issues/11354

Hey guys,

is there any update on the slow download speeds? I am unfortunately also affected (from Germany) by very slow speeds:

```bash
vagrant box add laravel/homestead
==> box: Loading metadata for box 'laravel/homestead'
    box: URL: https://vagrantcloud.com/laravel/homestead
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) hyperv
2) parallels
3) virtualbox
4) vmware_desktop

Enter your choice: 3
==> box: Adding box 'laravel/homestead' (v10.1.1) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/laravel/boxes/homestead/versions/10.1.1/providers/virtualbox.box
==> box: Box download is resuming from prior download progress
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
Progress: 0% (Rate: 22853/s, Estimated time remaining: 31:14:07)
```

**Comment by nessor** [comment]
Turns out it was a general routing issue on the part of Deutsche Telekom with AWS servers.
If you are also affected by this problem in the future and have Telekom as your ISP, you should check if other downloads from AWS S3 are slow as well (e.g. Git for windows). If this is the case, simply call Telekom.

**Comment by L1lle** [comment]
I'm having the same issue, still today. My ISP is "1&1". I haven't tried any other download from S3 yet. I got up to 60% of 1.7GB two days ago while waiting a couple of hours. Today nothing is happening anymore. 

`==> box: Adding box 'laravel/homestead' (v10.1.1) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/laravel/boxes/homestead/versions/10.1.1/providers/virtualbox.box
==> box: Box download is resuming from prior download progress
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
Progress: 0% (Rate: 20d/s, Estimated time remaining: 0:47:54)`

Just saying, @nessor you are not alone.

**Comment by nessor** [comment]
It’s super annoying. It would be interesting if other downloads from Amazon Servers are also effected. My colleague (also ISP 1&1) has the same issues for some days now. Maybe a call will help? 

Found this some days ago: https://www.golem.de/news/deutsche-telekom-peering-zu-us-servern-scheint-langsam-zu-sein-2012-152982.html

**Comment by L1lle** [comment]
I got up to 77% yesterday, then nothing more.

I solved this by connecting my computer to a tethering cellular connection with my phone. Using up some leftover data on my plan. The download finished in just a few minutes. Fun fact, I'm using "1&1" as cellular provider as well. So no problem on a mobile connection.

But the problem seems not to be related with Vagrant.

**Comment by nessor** [comment]
> But the problem seems not to be related with Vagrant.

nono. It's not. Idk what is going on with the AWS connection from germany at the moment. I could imagin that some CDN issue or so. However. It's annoying :D
