### ISSUE TITLE
Update to macOS 11.1 running VMWare private_network ip not working

### ISSUE THREAD

**Issue by kaplan** [hashicorp/vagrant#12122]
Hello, I've updated to Big Sur MacOS 11.1. I had some VMWare machines originally brought up with the vmware_fusion provider. In the past I've used the MacOS /etc/hosts file to create a private_network and set a domain name for local work. 

I've updated the MacOS, Vagrant, added the vagrant-vmware-desktop and vagrant-vmware-utility_1.0.17_x86_64. I can bring the box up, all the syncing is working but I can reach the domain/local ip in the browser.

In my MacOS `/etc/hosts/` I have:

    127.0.0.1	localhost
    255.255.255.255	broadcasthost
    ::1             localhost
    192.169.43.17	workalicious.dvlp

The result in the browser is an error page that say:
This site can’t be reached
http://workalicious.dvlp/ is unreachable.
ERR_ADDRESS_UNREACHABLE

I ran vagrant up --debug, here's the Gist: https://gist.github.com/kaplan/26cf1b8b59088eca9bb89821becae435

### Vagrant version
Installed Version: 2.2.14
Latest Version: 2.2.14

### Host operating system
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69

### Guest operating system
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-87-generic x86_64)
Apache/2.4.46 (Ubuntu)
PHP 7.4.9 (cli) (built: Aug  7 2020 14:29:10) ( NTS )

### Vagrantfile
https://gist.github.com/kaplan/22461fa6b97195a613439580d22da3cd

```ruby
#@IgnoreInspection BashAddShebang
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "workalicious/ubuntu1604"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.169.43.17"
  config.vm.synced_folder "www/html", "/var/www/html"

  # for VMWare 12 and Big Sur update (purchase new lic)
  config.vm.provider :vmware_fusion do |v|
    v.ssh_info_public = true
  end

  # add macOS public key, needed for SequelPro
  config.vm.provision "shell", 
  	inline: "echo \033[47m\033[31m - adding public key - \033[0m", keep_color: true
  ssh_pub_key = File.readlines("/etc/ssh/ssh_host_rsa_key.pub").first.strip
  config.vm.provision "shell", inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys" 

end
```

### Debug output
https://gist.github.com/kaplan/26cf1b8b59088eca9bb89821becae435

#### Update: 
I've reverted my MacOS back to Catalina. If you are on a Mac and you've done the same thing, note you have to erase your drive to reinstall Catalina after Big Sur, then do a Time Machine restore to the fresh drive and Catalina OS machine with your last backup prior to Big Sur. This is no small project so I was grateful to be running TM.

**Comment by DrDonk** [comment]
I suspect this is due to changes VMware had to implement to use virtual networking on Big Sur. VMware now uses virtual networking provided by macOS and the bottom half of the address range is used for DHCP. This is documented here https://kb.vmware.com/s/article/80793 and many threads in the VMware community forums.

**Comment by mengdodo** [comment]
**anybody can help me ?**  

1、mac  `Big Sur11.1 (20C69)`
2、parallels desktop  ` 16.1.2 (49151)  for MAC pro Edition`
3、Vagrant `2.2.14`
4、homestead `laravel/homestead (parallels, 8.2.0)`
5、homestead.yml  `ip: "192.168.10.10"`

Ping in mac terminal
```
(base) 🌸 xxx@超级本 ➜  ~  ping 192.168.10.10
PING 192.168.10.10 (192.168.10.10): 56 data bytes
64 bytes from 192.168.10.10: icmp_seq=0 ttl=59 time=5.184 ms
64 bytes from 192.168.10.10: icmp_seq=1 ttl=59 time=3.976 ms
64 bytes from 192.168.10.10: icmp_seq=2 ttl=59 time=3.538 ms
64 bytes from 192.168.10.10: icmp_seq=3 ttl=59 time=4.744 ms
```
is ok, but can\`t curl homestead and can\`t  open web project in homestead from mac Browser

```
(base) 🌸 libingrong@超级本 ➜  ~  curl 192.168.10.10
curl: (7) Failed to connect to 192.168.10.10 port 80: Operation timed out
```
final, i login homestead by `vagrant ssh` and input `ip addr`.
```
➜  ~ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:1c:42:fd:d9:a8 brd ff:ff:ff:ff:ff:ff
    inet 10.211.55.18/24 brd 10.211.55.255 scope global dynamic eth0
       valid_lft 1721sec preferred_lft 1721sec
    inet6 fdb2:2c26:f4e4:0:21c:42ff:fefd:d9a8/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 2591901sec preferred_lft 604701sec
    inet6 fe80::21c:42ff:fefd:d9a8/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:1c:42:f9:98:d5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.10/24 brd 192.168.10.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fdb2:2c26:f4e4:2:21c:42ff:fef9:98d5/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 2591901sec preferred_lft 604701sec
    inet6 fe80::21c:42ff:fef9:98d5/64 scope link
       valid_lft forever preferred_lft forever
```

i can see 192.168.10.10 in my terminal ,but why can\`t use ip ( 192.168.10.10) , this ip is not working ,help me please!

**Comment by chrisroberts** [comment]
Hi there. The latest version of the vagrant vmware utility includes specialized error messages for vmware fusion on big sur when attempting to set private network addressing on guests. It is no longer supported due to fusion moving to the vmnet framework on macos instead of using their own vmnet implementation. 

Cheers
