### ISSUE TITLE
Stuck on "Waiting for machine to boot"

### ISSUE THREAD

**Issue by jehutyy** [hashicorp/vagrant#12137]
I'm getting stuck with following log when trying to up a host on virtualbox provider : 
```
==> default: Importing base box 'generic/opensuse15'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'generic/opensuse15' version '3.1.22' is up to date...
==> default: Setting the name of the VM: suse_default_1610541464218_67780
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
```

I tried with different box with same result. 

After 7 minutes I stopped vagrant up command and checked what could be wrong and it appears that vm is listed running, but I'm
not able to connect to it with `vagrant ssh` which hangs forever.

# How to reproduce
1. vagrant init centos/7
2. vagrant up

# Versions
vagrant: 2.2.14
virtualbox: 6.1.16
host: Debian 10 vm.

**Comment by chrisroberts** [comment]
If you open the VirtualBox GUI, can you log in to the machine directly? If so, does it have a properly configured network and is the sshd running?

**Comment by jehutyy** [comment]
Hi, 

I kind of give up on this issue as it appears virtualbox doesn't really like to run inside a vm.
Maybe it is an anti-pattern to do so, thus giving up on it.
