### ISSUE TITLE
configure_networks fails in alpine 3.13.0

### ISSUE THREAD

**Issue by AsharLohmar** [hashicorp/vagrant#12134]
### Vagrant version
2.2.14

### Guest operating system

Alpine 3.13.0_rc2, built with packer from apline-virt iso

### Vagrantfile

All it takes is `config.vm.network :private_network, ip: 192.168.56.200`.

The problem is in the `/plugins/guests/alpine/cap/configure_networks.rb` on line 48, when it calls `/sbin/ifdown eth1` the command fails because/when the interface is not yet present (it doesn't showup in `ifconfig`'s output). 

My workaround was to add an "dummy command", in order to hide the failure exit code.
```
comm.sudo("/sbin/ifdown eth#{interface} 2> /dev/null; /bin/echo -n ''")
```

**Comment by LKHN** [comment]
FYI: [Introduction of ifupdown-ng, a replacement for busybox ifupdown.](https://alpinelinux.org/posts/Alpine-3.13.0-released.html)

**Comment by AsharLohmar** [comment]
Thanks @LKHN ... the 3.13.0 uses `ifupdown-ng` by default
```
alpine [~]$ which ifdown
/sbin/ifdown
alpine [~]$ ls -al /sbin/ifdown
lrwxrwxrwx    1 root     root            14 Jan  6 22:00 /sbin/ifdown -> /sbin/ifupdown
```
and it's behavior is consistent with other "flavors" of ifdown and with one would/should usually expect from a program called with incorrect inputs.
For example in Centos:
```
[vagrant@axsaio ~]$ cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
[vagrant@axsaio ~]$ ifdown eth2; echo $?
usage: ifdown <configuration>
1
```

In the meanwhile, althogh the busybox version changed between Alpine 3.12.3 and 3.13.0, it's  `ifdown`'s behavior remains the same.
```
alpine [~]$ cat /etc/alpine-release
3.12.3
alpine [~]$ busybox --help | head -1
BusyBox v1.31.1 () multi-call binary.
####
alpine [~]$ cat /etc/alpine-release
3.13.0_rc2
alpine [~]$ busybox --help | head -1
BusyBox v1.32.1 () multi-call binary.
```


```
alpine [~]$ busybox ifdown eth2; echo $?
ifdown: interface eth2 not configured
0
```
