### ISSUE TITLE
Vagrant DHCP server does not respect host-only interface IP network

### ISSUE THREAD

**Issue by rpmzandwijk** [hashicorp/vagrant#12143]
### Vagrant version

Vagrant 2.2.14

### Host operating system

macOS Catalina (10.15.7)

### Guest operating system

Alpine 3.8 (Vagrant box 'generic/alpine38'), but the problem is guest OS independent.

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"
  config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet3', :adapter => 1
end
```

### The problem

When creating a new host-only interface in VirtualBox, it is assigned an IP address. When starting a vm with the above Vagrant file, Vagrant will create an DHCP server. However, the DHCP server runs in a different IP space and therefore, the vm cannot be accessed. 

Create a new host-only interface:
```
$ VBoxManage hostonlyif create
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interface 'vboxnet3' was successfully created
```

The interface is assigned the 192.168.59.0/24 network:
```
$ VBoxManage list hostonlyifs
<snip>
Name:            vboxnet3
GUID:            786f6276-656e-4374-8000-0a0027000003
DHCP:            Disabled
IPAddress:       192.168.59.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet3
```

Start Vagrant (and use `vboxnet3` as network, see Vagrantfile above:
```
$ vagrant up
```

Now look at the DHCP server Vagrant creates:
```
$ VBoxManage list dhcpservers
<snip>
NetworkName:    HostInterfaceNetworking-vboxnet3
Dhcpd IP:       172.28.128.2
LowerIPAddress: 172.28.128.3
UpperIPAddress: 172.28.128.254
NetworkMask:    255.255.255.0
Enabled:        Yes
Global Configuration:
    minLeaseTime:     default
    defaultLeaseTime: default
    maxLeaseTime:     default
    Forced options:   None
    Suppressed opts.: None
        1/legacy: 255.255.255.0
Groups:               None
Individual Configs:   None
```

Obviously, the vm cannot be accessed. A work-around would be to assign the host-only interface the first IP number in the 172.28.128.2 network.

In my opinion, the created DHCP server should respect the IP network of the host-only interface.

A related problem is that if you have created multiple host-only interfaces (of which each has it's own unique IP address/network), Vagrant always creates DHCP servers with the same IP settings. Thus, multiple DHCP servers with the same IP scope exist and that is not going to work.

**Comment by soapy1** [comment]
Setting the ip address of the private network to the address of the manually created network should resolve this issue. For example,

```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"
  config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet3',  :ip => "192.168.59.1"
end
```

The resulting dhpc server should have the ip address `192.168.57.2`.

**Comment by rpmzandwijk** [comment]
That works indeed, even if you omit `:name => 'vboxnet3'`. Still, I would expect that specifying the network name would suffice and that Vagrant finds out which IP numbers belong to that network. Specifying both name and IP number is kind of redundant.

In the Vagrantfile I gave as example, I added `:adapter => 1`. In that case, Vagrant still thinks the interface is in a NAT network in stead of a host-only network.

**Comment by soapy1** [comment]
Looking into this issue a little more I found the following 2 Vagrantfiles results in successful booting and ssh connection:

```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"
  config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet3'
end
```

```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"
  config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet3', :adapter => 2
end
```

Also note, in these 2 cases the dhcp server created is at the default `172.28.128.2`.

> In the Vagrantfile I gave as example, I added :adapter => 1. In that case, Vagrant still thinks the interface is in a NAT network in stead of a host-only network.

Yes! The first adapter being NAT is an [assumption for Vagrant](https://github.com/hashicorp/vagrant/issues/2093#issuecomment-23458455). This is where all port forwards go through and is required for Vagrant to modify the guest.  

So, I think this is the desired behavior for Vagrant. 
- Users should expect modifying adapter 1 with result in broken behavior.
- If the user does not specify an ip address for the dhcp network, then a default one gets set (and the machine is reachable).
- If the user chooses to set an ip for the network, the ip is successfully setup (and the machine is reachable).

**Comment by rpmzandwijk** [comment]
I understand that the first adapter being NAT is an assumption for Vagrant. However, the documentation doesn't make that clear. It would be nice if this is documented in the 'Basic usage' section of networking.

I don't agree with you regarding the first bullet in the 'desired behaviour' part though. It should be possible the modify adapter 1 being a host-only interface, so one can create a 'true' private network (for example, it cannot talk to the outside world and there are use cases where that behaviour is desirable). Technically, this should be possible to create. I mean, when using a NAT network, Vagrant is able to figure out the IP of the vm to setup port forwarding. I guess it should be possible to determine the IP of a vm in a private (DHCP) network too and set ssh.host accordingly.

I understand if this won't be fixed/implemented, as this is probable a nice use case. Having said that, I could live with the documentation being more explicit about adapter 1 and fixing bullet 2 and 3. :-)

**Comment by soapy1** [comment]
> However, the documentation doesn't make that clear. It would be nice if this is documented in the 'Basic usage' section of networking.

Great suggestion! https://github.com/hashicorp/vagrant/pull/12209

 >  It should be possible the modify adapter 1 being a host-only interface, so one can create a 'true' private network (for example, it cannot talk to the outside world and there are use cases where that behaviour is desirable).... . I mean, when using a NAT network, Vagrant is able to figure out the IP of the vm to setup port forwarding. I guess it should be possible to determine the IP of a vm in a private (DHCP) network too and set ssh.host accordingly.

This sounds like a neat idea. It probably needs some investigation. I made an issue for this https://github.com/hashicorp/vagrant/issues/12210.

> fixing bullet 2 and 3

Vagrant already supports these 🎉 

I think this issue can be closed, unless I'm missing something else?

**Comment by rpmzandwijk** [comment]
Thanks Sophia. Regarding:

> If the user does not specify an ip address for the dhcp network, then a default one gets set (and the machine is reachable).

That is not true and was the reason to open this issue: the DHCP server IP range differs from the host-only IP of the host and thus, the guest cannot be accessed. See opening post. Albeit the workaround by specifying the IP address in the Vagrantfile, I think this should be fixed. Agree?

**Comment by soapy1** [comment]
Right, I think I see were I have gone astray here.
If the user does not specify an ip address for the dhcp network, then a default one gets set and the machine is reachable by Vagrant. Since Vagrant just needs that NAT adapter. However, the machine is not accessible on the ip given to the machine by the dhcp server. 
So, this is resolved by https://github.com/hashicorp/vagrant/pull/12211
Thanks for bringing that up!

**Comment by rpmzandwijk** [comment]
Oh, duh, you are absolutely right. Sorry for that. I guess this issue can be closed then. Thanks for all your effort!
