### ISSUE TITLE
trigger.after [:up] with `vagrant reload` action failure

### ISSUE THREAD

**Issue by RedHawker** [hashicorp/vagrant#12149]
### Vagrant version

`Vagrant 2.2.14`

### VirtualBox version

`6.1.16r140961`

### Host operating system

CentOS 7
```sh
uname -r
3.10.0-1160.11.1.el7.x86_64
```
### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.trigger.after [:up] do |t|
    t.name = "Reboot after provisioning"
    t.run = { :inline => "vagrant reload" }
  end
end

```

### Debug output

https://gist.github.com/RedHawker/2fe9e491182be90fa8b14184c7599e1c

### Expected behavior

The box should have reloaded once the `vagrant up` finished.

**I tested previous versions, and the last version that this worked with was 2.2.7**

~This was tested with Vagrant 2.2.4 and it worked fine~

### Actual behavior

The error text below was displayed:
```
    default: An action 'reload' was attempted on the machine 'default',
    default: but another process is already executing an action on the machine.
    default: Vagrant locks each machine for access by only one process at a time                                                             .
    default: Please wait until the other Vagrant process finishes modifying this
    default: machine, then try again.
    default:
    default: If you believe this message is in error, please check the process
    default: listing for any "ruby" or "vagrant" processes and kill them. Then
    default: try again.
    default:
==> default: Trigger run failed
==> default: A script exited with an unacceptable exit code 1.

```

### Steps to reproduce

1. run `vagrant up`

### Script to test different versions in CentOS

Pass the version number you want to test to it

```bash
#!/bin/bash

vagrant destroy

wget https://releases.hashicorp.com/vagrant/$1/vagrant_$1_x86_64.rpm

sudo yum remove vagrant

sudo yum localinstall vagrant_$1_x86_64.rpm

rm vagrant_$1_x86_64.rpm

vagrant plugin repair

vagrant up

vagrant destroy
```

**Comment by soapy1** [comment]
Hey there,
this is the desired result for that vagrantfile. Invoking vagrant from vagrant can lead to corrupting state. The error that is bubbling up here shows that Vagrant is trying to prevent that state corruption from happening. If you want to restart the machine after every vagrant up a safer method is to use a shell provisioner. Something like:

```
config.vm.provision :shell do |shell|
    shell.inline = 'echo rebooting'
    shell.reboot = true
  end
```
