### ISSUE TITLE
Query on a Vagrant  and Virtual Box start up error in Azure VM

### ISSUE THREAD

**Issue by harishmce2005** [hashicorp/vagrant#12156]
It is regarding an issue with Vagrant and Virtual Box.

We are trying to up a Virtual Box in an Azure VM (Windows 10). As suggested by Microsoft documentation, we upgraded the VM size to v3 and disabled Hyper-V in that machine.

Here the problem is that when it is trying to start virtual Box the Azure VM is getting disconnected. We updated the network settings on the Virtual Box from ‘NAT’ to “Bridge Adapter” and tried to start Virtual Box but again the network got disconnected.

Could someone please help me to fix the above-mentioned issue?

**Comment by soapy1** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant discuss page](https://discuss.hashicorp.com/c/vagrant/24). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
