### ISSUE TITLE
Provisioners order aren't respected when they are in a different places sequentially 

### ISSUE THREAD

**Issue by seavba** [hashicorp/vagrant#12151]
I'm trying to deploy a cluster, so I need to do something like this:
1- deploy master vbox
2- Apply ansible runbook on master vbox
3- deploy nodes (2 slaves) vboxes
4- Apply ansible runbook on slaves vboxes
5- Apply other ansible runbooks on master now.

However, step 2 is being added as the step 3. All my ansible provisioners are declared as a vm.provisioner not config.provisioner. 

So, why is Vagrant doing that?

**Comment by seavba** [comment]
@sethvargo could you please help me?

**Comment by soapy1** [comment]
Hi there,

I think the feature you are looking for here is the [dependency provisioner](https://www.vagrantup.com/docs/provisioning/basic_usage#dependency-provisioners). This is an experimental feature which allows for ordering provisioning steps.

For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant discuss page](https://discuss.hashicorp.com/c/vagrant/24). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
