### ISSUE TITLE
Vagrant Not working on Windows Server 2019

### ISSUE THREAD

**Issue by ayushpratap2494** [hashicorp/vagrant#12158]
Simply running Vagrant up command from terminal, Not working! giving errors.
Same file is running smoothly on local setup in Windows 10 pro.

### Vagrant version

Vagrant 2.2.14

### Host operating system

Windows Server 2019

### Guest operating system

Ubuntu : hashicorp/bionic64

### Vagrantfile

```ruby

#Node Counts.
NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 

#Network IP.
IP_NETWORK = "100.0.0."
MASTER_IP_START = 1
NODE_IP_START = 7

#Configuration Start.
Vagrant.configure("2") do |config|
    config.vm.synced_folder "./files", "/home/vagrant_data/files", type:"virtualbox"
    #Provisioning Kubernetes Master Nodes. 
    (1..NUM_MASTER_NODE).each do |i|
        config.vm.define "master#{i}" do |master|
            master.vm.box_download_insecure = true
            master.vm.box = "hashicorp/bionic64"
            master.vm.network "public_network", ip: IP_NETWORK + "#{MASTER_IP_START + i}"
            master.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"
            master.vm.hostname = "master#{i}"
            master.vm.provider "virtualbox" do |v|
                v.name = "master#{i}"
                v.memory = 4096
                v.cpus = 2
            end
            master.vm.provision "setup-hosts", :type => "shell", :path => "scripts/network.sh" do |s|
            s.args = ["enp0s8"]
            end
            master.vm.provision "shell",path:"scripts/setup.sh"
        end
    end

    #Provisioning Kubernetes Worker Nodes.
    (1..NUM_WORKER_NODE).each do |i|
        config.vm.define "worker#{i}" do |worker|
            worker.vm.box_download_insecure = true
            worker.vm.box = "hashicorp/bionic64"
            worker.vm.network "public_network", ip: IP_NETWORK + "#{NODE_IP_START + i}"
            worker.vm.network "forwarded_port", guest: 22, host: "#{2710 + i*2}"
            worker.vm.hostname = "worker#{i}"
            worker.vm.provider "virtualbox" do |v|
                v.name = "worker#{i}"
                v.memory = 4096
                v.cpus = 2
            end
            worker.vm.provision "setup-hosts", :type => "shell", :path => "scripts/network.sh" do |s|
            s.args = ["enp0s8"]
            end
            worker.vm.provision "shell",path:"scripts/setup.sh"
        end
    end
    
end
#Configuration End.


```
### Debug output

E:\Projects\k8s-vagrant>vagrant up
Traceback (most recent call last):
        13: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/bin/vagrant:168:in `<main>'
        12: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/bin/vagrant:168:in `new'
        11: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:178:in `initialize'
        10: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:973:in `process_configured_plugins'
         9: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:792:in `vagrantfile'
         8: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:792:in `new'
         7: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/vagrantfile.rb:29:in `initialize'
         6: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/config/loader.rb:116:in `load'
         5: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/config/loader.rb:116:in `each'
         4: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/config/loader.rb:119:in `block in load'
         3: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/config/loader.rb:119:in `each'
         2: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
         1: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/config/v2/loader.rb:37:in `load'
E:/Projects/k8s-vagrant/Vagrantfile:35:in `block in <top (required)>': bad value for range (ArgumentError)

### Expected behavior

Should have started spinning the virtual Machines !

### Actual behavior

Vagrant up command should have started the Virtual Machines.

**Comment by soapy1** [comment]
Hey there,
It looks like this error is coming from a bad value for `NUM_WORKER_NODES`. At the beginning of the Vagrantfile it is unset.

```
#Node Counts.
NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 
```

This issue is resolved by setting a value >= 1 to `NUM_WORKER_NODE`
