### ISSUE TITLE
I can't install Vagrant in VirtualBox (Ubuntu)

### ISSUE THREAD

**Issue by Yeikop** [hashicorp/vagrant#12154]
Hello team,

When I try install vagrant in my Ubunyu Machine with Virtualbox I receive this error

**_The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue**_**

![ubu errror](https://user-images.githubusercontent.com/43439042/105710581-9a25ff00-5f17-11eb-8d4c-76c9fde431b3.JPG)

I don't know what more to do. I have activate 

![ubu errror2](https://user-images.githubusercontent.com/43439042/105710686-bcb81800-5f17-11eb-84dc-ff876e6fb532.JPG)

Hiper V disconnected

![ubu errror3](https://user-images.githubusercontent.com/43439042/105710769-d9ece680-5f17-11eb-8577-4ce641232a4c.JPG)

My VirtualBoz is the 6.1 Version
Ubuntu 16.04 , but I tried with the 20.04 and I had the same error.

Please could you help me please???

Thanks!!!

**Comment by soapy1** [comment]
Hey there, 
it looks like somehow your Vagrant state has been messed up. A `vagrant global-status --prune` might put your Vagrant setup in a better state.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
