### ISSUE TITLE
Slow download speed for boxes

### ISSUE THREAD

**Issue by slaway** [hashicorp/vagrant#12160]
### Vagrant version
2.2.6

### Host operating system
Tested on Ubuntu and Windows

### Debug output

https://gist.github.com/slaway/68834b3388397238b147a751f16c97d7

### Expected behavior

Speeds above 200Kb/s

### Actual behavior

Speeds below 200Kb/s

### Steps to reproduce

Unknown

### Thoughts

Maybe there's something wrong with what region I'm being redirected to?

```
$ ping vagrantcloud-files-production.s3.amazonaws.com
PING s3-1-w.amazonaws.com (52.217.1.204) 56(84) bytes of data.
64 bytes from s3-1-w.amazonaws.com (52.217.1.204): icmp_seq=1 ttl=43 time=175 ms
```
 `s3-1-w` is about 200ms away depending on noise. I'm not sure if that's located in the US or if that's an incorrect guess from what I've found online, but I'm in Europe so that could explain it.

My bandwidth seems fine via `speedtest-cli`:

```
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Testing download speed................................................................................
Download: 304.41 Mbit/s
``` 

I've seen other issues being posted regarding this but they seem to have been closed due to this being hard to reproduce, which I can understand, but I'm happy to supply any information that may help to check if this is somehow related to region routing issues.

Judging by the debug output above, it looks like it's fetching the file from `us-east-1` which is a bad idea if you're in Europe.

**Comment by oliverhr** [comment]
I have been trying the whole day to download `gbailey/amzn2` without success sometimes the remaining time marked up to 8 hours, I tested my internet connection but is steady and fast.

**Comment by chrisroberts** [comment]
Hi there,

The download speeds in regions remote from us-east-1 should be resolved now via updates deployed to Vagrant Cloud.

Cheers
