### ISSUE TITLE
Allow persistence of synced folders to be enabled/disabled via option

### ISSUE THREAD

**Issue by Shadowesque** [hashicorp/vagrant#12172]
**Is your feature request related to a problem? Please describe.**

I don't like that Vagrant makes synced folders persistent with no option to disable the behavior.

**Describe the solution you'd like**

I would like an option added to `synced_folder` which allows for disabling persistence.

Something like this:
```
Vagrant.configure("2") do |config|
  config.vm.synced_folder "/path/to/host/folder", "/path/to/guest/folder", persist: false
end
```

**Additional context**

Recent versions of Vagrant make synced folders persistent.

For example, for a Linux guest, Vagrant adds a line to `/etc/fstab` for each synced folder.

This changes the behavior from how synced folders have worked in the past. While this may be an improvement and desired by some users, it may not be the desired behavior for others.

For example, if a VM is a release artifact for a project and the shared folders are removed from the VM before deploying, then there are now entries in `/etc/fstab` that should not be there. I guess I could remove them while provisioning, but I do not think I should be required to do that.

This is just one example that directly relates to my issue with how this currently works. However, I am sure there are other situations where users just `vagrant up` their VM and then after that no longer need the synced folders.

I looked at the Vagrant documentation and I see no option in `synced_folder` that allows for disabling this persistence.

**Comment by soapy1** [comment]
Hey there,
this option exists on the vm config level. It's called [`allow_fstab_modification`](https://www.vagrantup.com/docs/vagrantfile/machine_settings#config-vm-allow_fstab_modification). By default it is set to true. To disable it you can do something like:

```
Vagrant.configure("2") do |config|
  config.vm.synced_folder "/path/to/host/folder", "/path/to/guest/folder"
  config.vm.allow_fstab_modification = false
end
```
