### ISSUE TITLE
Condition to check if provisioning

### ISSUE THREAD

**Issue by Michael-Pascale** [hashicorp/vagrant#12187]
How can I modify the condition below to only run the code inside the condition when it is the first time vagrant up is being run. Is there a condition to check if vagrant is going to run provisions? My goal is to not have vagrant run those prompts for input every time `vagrant up` is run, but only when it needs to run provisioning, such as the first time `vagrant up` is run.

```
if (ARGV[0] == 'up' || ARGV[1] == '--provision')
    print 'Please enter your username: '
    username = STDIN.gets.chomp
    print('Please enter your password: ')
    password = STDIN.noecho(&:gets).chomp
    print "\n"
    config.vm.provision :shell, path: "bootstrap.sh", args: [username, password]
end
```

**Comment by soapy1** [comment]
Hi there,

Thank you for opening an issue! Vagrant doesn't support interactive input for provisioners. However, you might find the [run option](https://www.vagrantup.com/docs/provisioning/basic_usage#run-once-always-or-never) useful for achieving this goal.

We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant discuss page](https://discuss.hashicorp.com/c/vagrant/24). In general there are many more people who will be able to get you a faster answer there.
