### ISSUE TITLE
How to run Vagrant inside an Ubuntu guest virtual machine on a Windows host with VMware

### ISSUE THREAD

**Issue by dattphan15** [hashicorp/vagrant#12193]
Hi,

As stated in the title, I'm currently using a Windows 10 laptop and I've downloaded VMWare to work within a Linux environment.  I'm having issues running Vagrant within VMWare, and I'm wondering if there's a solution to setup this type of nested VM environment. Up until now, I've been dual-booting Linux on my Windows laptop, however, I'd prefer to use Windows and then tab in or out of my Linux system in my task bar if possible.  Any help is appreciated, thanks!

Windows 10 (host) > VMWare (Linux - Ubuntu 20.04.1 LTS) > Vagrant (issue here)
![image](https://user-images.githubusercontent.com/31554101/107907624-c979cb80-6f19-11eb-9e1d-a88bd4136bfa.png)

I've also tried to enable the VT-X/AMD option in the VM Settings, but after that, I'm unable to launch the VM.
![image](https://user-images.githubusercontent.com/31554101/107908040-c206f200-6f1a-11eb-8c64-ffc6801f417d.png)
![image](https://user-images.githubusercontent.com/31554101/107908080-d4812b80-6f1a-11eb-858f-3eb6891abd42.png)

**Comment by soapy1** [comment]
In order to enable nested virtualization with vmware you will need to include the following config in your Vagrantfile:

```
 config.vm.provider :vmware_desktop do |v|
   v.vmx['vhv.enable'] = 'TRUE'
   v.vmx['vhv.allow'] = 'TRUE'
   v.vmx["hypervisor.cpuid.0"] = "FALSE"
end
```
