### ISSUE TITLE
Vagrant failed to load a configured plugin source

### ISSUE THREAD

**Issue by palsumitdev** [hashicorp/vagrant#12190]
Installing the 'vagrant-librarian-chef' plugin. This can take a few minutes...
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  no such name (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/

**Comment by soapy1** [comment]
Hey there, could you provide a bit more information about the issue. In particular:

- what version of vagrant
- what is the host OS
- can you provide a full debug gist https://www.vagrantup.com/docs/other/debugging

**Comment by chrisroberts** [comment]
Given there has been no response, I'm going to close this issue. Most likely there is a proxy preventing access to the hashicorp gems server, which results in this error. Resolution options are to get the gems server placed on the proxies allow list, or to remove it when installing the plugin like this:

```
vagrant plugin install vagrant-librarian-chef --plugin-clean-sources --plugin-source https://rubygems.org
```

Cheers!
