### ISSUE TITLE
OutOfMemoryException thrown when not using 'privileged: true'

### ISSUE THREAD

**Issue by hoppy1977** [hashicorp/vagrant#12197]
### Vagrant version
Vagrant 2.2.14

### Host operating system
Windows 10

### Guest operating system
Windows Server 2019 Standard

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

#####################################################################################
# Configuration settings
#####################################################################################
machine_name = "out-of-memory"
hyperv_switch = "Default Switch"

#####################################################################################

Vagrant.configure("2") do |config|
  # The name specified here is used for logging
  config.vm.define machine_name

  # Name of box to install with
  #config.vm.box = "mwrock/Windows2016"
  config.vm.box = "StefanScherer/windows_2019"

  # Communicator type
  config.vm.communicator = "winrm"

  # Guest OS
  config.vm.guest = :windows
  config.windows.halt_timeout = 15

  # Config networks on guest.
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
  
  # The time in seconds that Vagrant will wait for the machine to boot and be accessible
  config.vm.boot_timeout = 300

  # Admin user name and password
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"

  # The amount of time that is allowed to complete task
  config.winrm.execution_time_limit = "PT6H" # 6 Hours

  # The maximum amount of time to wait for a response from the endpoint
  config.winrm.timeout = 5400 # seconds

  # VirtualBox configuration
  config.vm.provider :virtualbox do |vb, override|
    # The name specified here is used for the name of the generated VM
    vb.name = machine_name
    vb.gui = true
    vb.memory = 20480
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]

    if defined? VagrantVbguest
      # Update VirtualBox Guest Additions if required
      config.vbguest.auto_update = true

      # Reboot the VM if VirtualBox Guest Additions are updated
      config.vbguest.auto_reboot = true
    end
  end

  # Hyperv configuration
  config.vm.provider :hyperv do |h|
    h.vmname = machine_name
    h.memory = 20480

    # Specify the virtual switch we want to use
    config.vm.network "public_network", bridge: hyperv_switch
  end

  # Disable the shared folder as it doesn't work on Hyper-V
  config.vm.synced_folder ".", "/vagrant", disabled: true

  #####################################################################################
  # Provisioners
  #####################################################################################

  # Configure powershell
  config.vm.provision "Give PowerShell admin rights",
    privileged: false,
    type: "shell",
    inline: %q"Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force -Scope CurrentUser",
    powershell_args: "-ExecutionPolicy Unrestricted"

  # Choco
  config.vm.provision "Install choco", privileged: false, type: "shell", inline: "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"

  # ReSharper
  config.vm.provision "Install ReSharper", privileged: false, type: "shell", inline: "cinst -y --no-progress resharper" # This will FAIL - will give inexplicable 'OutOfMemoryException'
  #config.vm.provision "Install ReSharper", privileged: true, type: "shell", inline: "cinst -y --no-progress resharper" # This will work!
end
```

### Debug output
See Actual Behaviour.

### Expected behavior
* ReSharper should install successfully with 'privileged: false' like other choco provisioners.

### Actual behavior
This is the error I get when I try to install ReSharper using choco in a provisioner with 'privileged: false':
https://github.com/hoppy1977/out-of-memory-test/blob/master/resharper_with_privileged_false.png
Note:
* ReSharper has failed to install with an OutOfMemoryException.

This is the result when I try to install ReSharper using choco in a provisioner with 'privileged: true':
https://github.com/hoppy1977/out-of-memory-test/blob/master/resharper_with_privileged_true.png
Note:
* The strange red error(?) at the start of the provisioner. I get this whenever using 'privileged: true', but it does not seem to cause any problems.
* ReSharper installs successfully

### Steps to reproduce

1. Run the Vagrantfile above. Note that ReSharper will fail to install regardless of how much memory is allocated to the VM
2. Run the provisioner with 'privileged: true'. Note that ReSharper will install successfully.

### Notes
Note that this seems to be a Vagrant probelm (not a R# or choco problem) because:
* I have observed the exact same problem with a different provisioner (one that was building Angular code with 'ng build'). I have just used ReSharper for this example for simplicity.
* The problem does not occur when I perform the equivalent actions on the VM client directly.

Why should changing the privileged state cause an error like this?

**Comment by chrisroberts** [comment]
Hi there. None of the items flagged appear to be causing any issues. The OOM error you are encountering is originating from the chocolatey install process (not Vagrant itself) and would need to be resolved there. The error output you note when setting privileged to true is simply Vagrant attempting to connect to the guest. Depending on the box configuration when connecting for setting up a privileged task, the username may work without a workspace/machine/domain prefix, or it may require it. So vagrant will try username values of variations it can determine when attempting to connect. 

The output you see is just the streamed output from the standard error stream. It's not a Vagrant provisioning error (since it is retrying with a different credential set). If it were an actual provisioning error, Vagrant would have halted and a non-zero return value would be given.

Cheers!
