### ISSUE TITLE
Code from PR #10717 is missing?

### ISSUE THREAD

**Issue by jlduran** [hashicorp/vagrant#12203]
Is the code introduced in #10717 gone?

It allowed FreeBSD guests to use VirtualBox shared folders.

**Comment by soapy1** [comment]
This feature is still available. 
However, the provider setting `functional_vboxsf` disables using virtualbox folders. It might be that this is set to false in the Vagrantfile embedded in the box being used. For example, inspecting the Vagrantfile for `roboxes/freebsd11` reveals

```
config.vm.provider :virtualbox do |v, override|
    v.gui = false
    v.functional_vboxsf = false
    v.check_guest_additions = false
    v.customize ["modifyvm", :id, "--vram", 256]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--memory", 2048]
  end
```

This can be overridden the your Vagrantfile, for example:

```
Vagrant.configure("2") do |config|
  config.vm.box = "roboxes/freebsd11"
  config.vm.synced_folder "/Users/sophia/project/other", "/other", type: :virtualbox
  config.vm.provider :virtualbox do |v, o|
    v.functional_vboxsf = true
  end
end
```

Though, I would assume that the box author disabled this feature with a particular intention.

**Comment by jlduran** [comment]
Sorry, I hit this bug when testing a box with FreeBSD 13:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253934
