### ISSUE TITLE
Documentation error: VAGRANT_EXPERIMENTAL="cloud_init" not sufficient to enable "cloud_init" feature

### ISSUE THREAD

**Issue by t-hofmann** [hashicorp/vagrant#12207]
https://www.vagrantup.com/docs/cloud-init/usage

In order to activate the experimental feature "cloud_init". The documentation (see https://www.vagrantup.com/docs/cloud-init/usage) states to configure the environmental with VAGRANT_EXPERIMENTAL="cloud_init".

Instead also adding "disks" seems necessary:
VAGRANT_EXPERIMENTAL="cloud_init, disks"

Tested with Vagrant version 2.2.14

Please fix the documentation at https://www.vagrantup.com/docs/cloud-init/usage

**Comment by soapy1** [comment]
fixed by #12104
