### ISSUE TITLE
everything that goes ba with basic vagrant isntallation in fedora

### ISSUE THREAD

**Issue by boistordu** [hashicorp/vagrant#12214]
Fedora 33
So we are 3 iterations after [this](https://github.com/hashicorp/vagrant/issues/11020) happened
Seems to way more enough time to fix it no? 

So first problem is the build of the libvirt plugin.
With `dnf installl vagrant` it doesn't work because then you got again the : 
```
conflicting dependencies racc (= 1.4.16) and racc (= 1.5.1)
  Activated racc-1.5.1
  which does not match conflicting dependency (= 1.4.16)

  Conflicting dependency chains:
    racc (= 1.5.1), 1.5.1 activated

  versus:
    racc (= 1.4.16)

  Gems matching racc (= 1.4.16):
    racc-1.4.16
```
`ruby-devel` doesn't cut it 
`export CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64"` doesn't cut it either
but the 3 combinations with the installation of the official installer that does work(not the one from official repo from fedora)...

But Then it comes the problem[ pre-cited](https://github.com/hashicorp/vagrant/issues/11020): 
the openssl problem...
And I really don't want to install from source each time so could you please just package it in the official installer and put it hardcoded in your code that it takes the libraries in your root folder and not system please?

**Comment by boistordu** [comment]
So in the end I've succeeded.
But a few questions need to be adressed I think to change or the documentation/ or the way the packages are created and maintained. 
For fedora 3 big ressources need to be combined:
this : https://github.com/vagrant-libvirt/vagrant-libvirt
this : https://fedoramagazine.org/vagrant-qemukvm-fedora-devops-sysadmin/
this: https://github.com/hashicorp/vagrant/issues/11020
and more precisely this: https://github.com/hashicorp/vagrant/issues/11020#issuecomment-630022362

Indeed the use of the package provided by official repo from fedora and the remove of the optional packages like the vagrant-libvirt to make it compile from the official sources of vagrant does work. 

But then it means also that we are using an older version than the official package.

So 2 or 3 remarks here.
There is a problem in the doc, because we shouldn't grind 5 differents sources of documentation to actually get an answer on how to install basic stuffs on a specific distro that is officially supported.
I had to combine the vagrant installation doc sources + the plugin installation doc sources + issues to actually make it working... This is a bit too much no?

Another thing is that there is a need to make choice here. I don't know who is maintaining the fedora official package. But based on the current situation, as I stated before and as it is stated in the other ticket, 2 smalls increments of code needs to differ between the fedora version and the official vagrant version because of the problem libraries version. path need to be hardcoded in the official version and lib needs to be packaged in it... But again this is based on the current situation.

And a third thing, there is a need of clarification into the the error codes we are receiving. 
Because of this instructions I didn't put in place at first :  `dnf install -y gcc libvirt libvirt-devel libxml2-devel make ruby-devel`
where actually some of those important packages were already installed:
Last metadata expiration check: 1:32:34 ago on Mon 01 Mar 2021 12:56:11 AM CET.
```
Package libvirt-6.6.0-5.fc33.x86_64 is already installed.
Package libvirt-devel-6.6.0-5.fc33.x86_64 is already installed.
Package ruby-devel-2.7.2-135.fc33.x86_64 is already installed.
```
I was still getting there error: 
```
Building native extensions. This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: /root/.vagrant.d/gems/2.7.2/gems/ruby-libvirt-0.7.1/ext/libvirt
/usr/bin/ruby -I /usr/share/rubygems -r ./siteconf20210301-9929-13ifxyo.rb extconf.rb
checking for virConnectOpen() in -lvirt... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib64
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --with-libvirt-include
        --with-libvirt-lib
        --with-virt-dir
        --without-virt-dir
        --with-virt-include
        --without-virt-include=${virt-dir}/include
        --with-virt-lib
        --without-virt-lib=${virt-dir}/lib64
        --with-virtlib
        --without-virtlib
/usr/share/ruby/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/share/ruby/mkmf.rb:564:in `try_link0'
        from /usr/share/ruby/mkmf.rb:582:in `try_link'
        from /usr/share/ruby/mkmf.rb:794:in `try_func'
        from /usr/share/ruby/mkmf.rb:1029:in `block in have_library'
        from /usr/share/ruby/mkmf.rb:971:in `block in checking_for'
        from /usr/share/ruby/mkmf.rb:361:in `block (2 levels) in postpone'
        from /usr/share/ruby/mkmf.rb:331:in `open'
        from /usr/share/ruby/mkmf.rb:361:in `block in postpone'
        from /usr/share/ruby/mkmf.rb:331:in `open'
        from /usr/share/ruby/mkmf.rb:357:in `postpone'
        from /usr/share/ruby/mkmf.rb:970:in `checking_for'
        from /usr/share/ruby/mkmf.rb:1024:in `have_library'
        from extconf.rb:63:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /root/.vagrant.d/gems/2.7.2/extensions/x86_64-linux/2.7.0/ruby-libvirt-0.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /root/.vagrant.d/gems/2.7.2/gems/ruby-libvirt-0.7.1 for inspection.
Results logged to /root/.vagrant.d/gems/2.7.2/extensions/x86_64-linux/2.7.0/ruby-libvirt-0.7.1/gem_make.out
```

maybe, just maybe there should be a verification of the neccesary packages before compiling stuffs with a clear message of what's missing?

I will leave this ticket open just in case of one of the author wants to answer. I've tried be as constructive as possible. 
Every combination of these isntallations have been tested in fedora workstation but also the server edition. So it's highly reproductible

**Comment by chrisroberts** [comment]
Hi there. Sorry about the frustration you encountered installing the libvirt plugin. The changes in #12225 should help to alleviate some of the problems that you encountered. Along with providing clearer error messages when it's possible for us to extract them, it also includes update to handle plugin resolution while running within environments other than Bundler and our installer package.

Cheers!
