### ISSUE TITLE
"Vagrant up" alternative download and install 

### ISSUE THREAD

**Issue by IsraelAbebe** [hashicorp/vagrant#12222]
Vagrant up takes too much time and since the Virtualbox.box file is too large it is impossible for me to continue with the process.
alternatively, I was able to download the file faster from https://vagrantcloud.com/arrikto/boxes/minikf/versions/20200305.1.0/providers/virtualbox.box.

can you tell me where to put the file so that the "vagrant up" command continues assuming the file is downloaded?

**Comment by chrisroberts** [comment]
@IsraelAbebe You can use the `vagrant box add` command to directly add the box asset: 

https://www.vagrantup.com/docs/cli/box#box-add

So it'll look something like:

```
vagrant box add ./virtualbox.box --name minikf
```

assuming the downloaded box file is located in the current directory.

Cheers!
