### ISSUE TITLE
Vagrant::Util::PowerShell does not seem to "capture" stdout from powershell

### ISSUE THREAD

**Issue by ThoughtProcess** [hashicorp/vagrant#12221]
### Vagrant version
2.2.14

### Host operating system
Edition	Windows 10 Pro
Version	20H2
Installed on	‎6/‎22/‎2020
OS build	19042.844
Experience	Windows Feature Experience Pack 120.2212.551.0

### Guest operating system
N/A - any Vagrant command that checks for PowerShell fails

### Vagrantfile
N/A - any Vagrant command that checks for PowerShell fails

### Debug output
This was generated by `vagrant status --debug > out.txt 2>&1`:
https://gist.github.com/ThoughtProcess/4b5beb43616e16460495a352af9f3a70

### Expected behavior
Vagrant should adequately bootstrap in order to execute basic commands.

### Actual behavior
Vagrant successfully finds the location of the PowerShell executable, but cannot properly evaluate the messages that PowerShell sends to stdout.  The error message is:

```
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "Write-Output $PSVersionTable.PSVersion.Major"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
5
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 30
DEBUG subprocess: Exit status: 0
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::PowerShellInvalidVersion: The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.

  Installed version: N/A
  Minimum required version: 3>
ERROR vagrant: The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.
```

### Steps to reproduce

1. Run any vagrant command from any directory.  The gist that I have linked above comes from running `vagrant status`.

### References
- This seems to be connected to #9629

### Additional details:

PowerShell.rb uses the following command to detect the current version of PowerShell:
```powershell.EXE -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command Write-Output $PSVersionTable.PSVersion.Major```

When I run this directly from a Windows command prompt, I get the following result:

```5```

Interstingly enough, that number appears in the log that's captured for the gist.  It almost seems as if the piping or redirection is broken between PowerShell and the rest of the Vagrant stack.

Here is my full $PSVersionTable:
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ThoughtProcess** [comment]
I should mention that I don't use vagrant very frequently (perhaps once a month) but the last time I ran it, it worked without issues.  I am curious if a recent Windows update might have broken some internal plumbing.  

I uninstalled and reinstalled Vagrant, but the issue is still there.

**Comment by ThoughtProcess** [comment]
It occurred to me that my terminal emulator, ConEmu (https://conemu.github.io/) might be part of the issue.  Sure enough, when I run cmd.exe directly (e.g. Start-->Run-->cmd.exe) without any emulator, Vagrant works correctly.

cmd.exe behavior (works fine):
```
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "Write-Output $PSVersionTable.PSVersion.Major"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 5
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 30
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "(new-object System.Security.Principal.WindowsPrincipal([System.Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([System.Security.Principal.WindowsBuiltInRole]::Administrator)"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: False
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "Write-Output ([System.Security.Principal.WindowsIdentity]::GetCurrent().Groups | Select-Object Value | ConvertTo-JSON)"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
```

ConEmu behavior (I suspect this happens for other terminal emulators as well):
```
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "Write-Output $PSVersionTable.PSVersion.Major"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
5
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 30
DEBUG subprocess: Exit status: 0
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::PowerShellInvalidVersion: The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.
```

The key difference is the `DEBUG subprocess: stdout: 5` line.  I'll likely need to open a ticket with the ConEmu team (and perhaps with some other project depending on where in the stack this particular piping / redirection bug comes from).

I'll leave the issue open for a few days on the off-chance that other Vagrant users are experiencing the same issue.

**Comment by chrisroberts** [comment]
Closing as this is an upstream issue with ConEmu. Cheers!
