### ISSUE TITLE
Fedora Linux detection should use ID from /etc/os-release instead of /etc/redhat-release

### ISSUE THREAD

**Issue by mattdm** [hashicorp/vagrant#12228]
In Fedora Linux 35, we plan to change the "pretty" name to "Fedora Linux" instead of just "Fedora" (because making the base distro isn't all we do!). This will result in `/etc/redhat-release` saying `Fedora Linux release 35 (Thirty Five)` instead of the current `Fedora release 34 (Thirty Four)`.

It [looks like](https://github.com/hashicorp/vagrant/blob/main/plugins/guests/fedora/guest.rb) the existing detection code does this:

    machine.communicate.test("grep 'Fedora release' /etc/redhat-release")

Which isn't the best approach anyway since `/etc/os-release` has an `ID` field meant to be machine-readable. (For that reason, we are changing `NAME` to "Fedora Linux" but leaving `ID` as "fedora".)

I suggest changing the test to something like:

    machine.communicate.test("grep '^ID=fedora' /etc/os-release")

This will work both now and in the future.

**Comment by voxik** [comment]
I think that one important think to consider is backward compatibility. @mattdm do you by a chance remember how long is `/etc/os-release` in use? Maybe the `/etc/redhat-release` should still be used as a fallback.

**Comment by mattdm** [comment]
I don't remember, but fortunately we have machines which do. :) This was added in February 2012:
https://src.fedoraproject.org/rpms/fedora-release/c/c6a541628ffd96e6f97378883e7cf1acde06232c?branch=rawhide
and released into both F17 and F18: https://bugzilla.redhat.com/show_bug.cgi?id=733117.

I don't know if you support EOL releases going that far back, but if you do `/etc/redhat-release` does seem like a reasonable fallback, and we do have the benefit of knowing that the text in those releases will not change. :)

Incidentally, it's also the right thing to look at for RHEL 7 and CentOS Linux 7 and newer (so all currently-supported releases of those, too, although I know there's definitely a lot of 6 still out there.)
