### ISSUE TITLE
VBoxHardening issue on window 10 - Please fix the issue

### ISSUE THREAD

**Issue by Jpanda124** [hashicorp/vagrant#12237]
Good evening!

We are using Vagrant and Oracle Virtual machine to build virtual box for our application team .
Recently we have upgraded our laptop  from windows 7 to windows 10 .
After this upgradation we are facing below issue while starting and provisioning the vagrant environment in some of our laptops .

 
Issue : 
$ vagrant reload anvm
==> anvm: Clearing any previously set forwarded ports...
==> anvm: Clearing any previously set network interfaces...
==> anvm: Preparing network interfaces based on configuration...
    anvm: Adapter 1: nat
==> anvm: Forwarding ports...
    anvm: 22 (guest) => 2222 (host) (adapter 1)
==> anvm: Running 'pre-boot' VM customizations...
==> anvm: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "cbd7c4d9-9068-4d57-bab4-9567f6ac4a83", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'anvm' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\2232599\VirtualBox VMs\anvm\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

We have upgraded to latest version of Vagrant V2.2.14 and Oracle Virtual Machine6.18 to fix the issue , but still same issue is there .
Please provide the resolution for this issue as this issue is a blocker for us .

**Comment by soapy1** [comment]
It looks like this is an issue coming from Virtualbox. Are you able to start the virtual machine from the vbox ui? It is possible that trying that will yield a more useful error message. From the error message, it looks like there is more information about the issue in the output log provided by virtalbox `C:\Users\2232599\VirtualBox VMs\anvm\Logs\VBoxHardening.log`

**Comment by Jpanda124** [comment]
> It looks like this is an issue coming from Virtualbox. Are you able to start the virtual machine from the vbox ui? It is possible that trying that will yield a more useful error message. From the error message, it looks like there is more information about the issue in the output log provided by virtalbox `C:\Users\2232599\VirtualBox VMs\anvm\Logs\VBoxHardening.log`

While starting the virtual machine , it says the same error .
Some time the same "vagrant up" is working fine but some times its throwing this error.


Printing the error message in log file :
700.3c1c: supR3HardenedWinFindAdversaries: 0x40000
700.3c1c: \SystemRoot\System32\drivers\SophosED.sys:
700.3c1c:     CreationTime:    2021-02-11T02:17:08.957723300Z
700.3c1c:     LastWriteTime:   2021-02-11T04:27:08.588846700Z
700.3c1c:     ChangeTime:      2021-02-11T04:27:08.588846700Z
700.3c1c:     FileAttributes:  0x20
700.3c1c:     Size:            0x122450
700.3c1c:     NT Headers:      0xe0
700.3c1c:     Timestamp:       0x5ee27ff5
700.3c1c:     Machine:         0x8664 - amd64
700.3c1c:     Timestamp:       0x5ee27ff5
700.3c1c:     Image Version:   10.0
700.3c1c:     SizeOfImage:     0x128000 (1212416)
700.3c1c:     Resource Dir:    0x120000 LB 0x6740
700.3c1c:     [Version info resource found at 0x570! (ID/Name: 0x1; SubID/SubName: 0x409)]
700.3c1c:     [Raw version resource data: 0x120580 LB 0x4b4, codepage 0x0 (reserved 0x0)]
700.3c1c:     ProductName:     Sophos Endpoint Defense
700.3c1c:     ProductVersion:  2.2.4
700.3c1c:     FileVersion:     2.2.4.517
700.3c1c:     FileDescription: Sophos Endpoint Defense Mini-Filter Driver
700.3c1c: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume4\Program Files\Oracle\VirtualBox'
700.3c1c: Calling main()
700.3c1c: SUPR3HardenedMain: pszProgName=VBoxHeadless fFlags=0x0
700.3c1c: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume4\Program Files\Oracle\VirtualBox'
700.378c: supR3HardenedWinVerifyCacheScheduleImports: Import todo: #0 'msvcrt.dll'.
700.378c: supR3HardenedWinVerifyCacheScheduleImports: Import todo: #6 'sechost.dll'.
700.378c: supR3HardenedWinVerifyCacheScheduleImports: Import todo: #27 'rpcrt4.dll'.
700.378c: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume4\Windows\System32\advapi32.dll)
700.378c: supR3HardenedWinVerifyCacheInsert: \Device\HarddiskVolume4\Windows\System32\advapi32.dll
700.378c: supR3HardenedWinVerifyCacheProcessImportTodos: Processing 'msvcp120.dll'...
700.378c: supR3HardenedWinVerifyCacheProcessImportTodos: 'msvcp120.dll' -> '\Device\HarddiskVolume4\Windows\System32\msvcp120.dll' [rcNtRedir=0xc0150008]
700.378c: \Device\HarddiskVolume4\Windows\System32\msvcp120.dll: Signature #1/2: info status: 24202
700.378c: supR3HardenedWinVerifyCacheScheduleImports: Import todo: #0 'msvcr120.dll'.
700.378c: supHardenedWinVerifyImageByHandle: -> 24202 (\Device\HarddiskVolume4\Windows\System32\msvcp120.dll)
700.378c: supR3HardenedWinVerifyCacheInsert: \Device\HarddiskVolume4\Windows\System32\msvcp120.dll
700.378c: supR3HardenedWinVerifyCacheProcessImportTodos: Processing 'msvcr120.dll'...
700.378c: supR3HardenedWinVerifyCacheProcessImportTodos: 'msvcr120.dll' -> '\Device\HarddiskVolume4\Windows\System32\msvcr120.dll' [rcNtRedir=0xc0150008]
700.378c: \Device\HarddiskVolume4\Windows\System32\msvcr120.dll: Signature #1/2: info status: 24202
700.378c: supHardenedWinVerifyImageByHandle: -> 24202 (\Device\HarddiskVolume4\Windows\System32\msvcr120.dll)
700.378c: supR3HardenedWinVerifyCacheInsert: \Device\HarddiskVolume4\Windows\System32\msvcr120.dll
700.378c: supR3HardenedWinVerifyCacheProcessImportTodos: Processing 'oleaut32.dll'...
700.378c: supR3HardenedWinVerifyCacheProcessImportTodos: 'oleaut32.dll' -> '\Device\HarddiskVolume4\Windows\System32\oleaut32.dll' [rcNtRedir=0xc0150008]
700.3c1c: \Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe: Signature #1/2: info status: 24202
700.3c1c: '\Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe' has no imports
700.3c1c: supHardenedWinVerifyImageByHandle: -> 24202 (\Device\HarddiskVolume4\Program Files\Oracle\VirtualBox\VBoxHeadless.exe)
700.3c1c: SUPR3HardenedMain: Respawn #2
700.3c1c: Error (rc=-5640):
700.3c1c: More than one thread in process
700.3c1c: Error -5640 in supR3HardenedWinReSpawn! (enmWhat=1)
700.3c1c: More than one thread in process
284c.e84: supR3HardNtChildWaitFor[1]: Quitting: ExitCode=0x1 (rcNtWait=0x0, rcNt1=0x0, rcNt2=0x103, rcNt3=0x103, 248 ms, the end);

**Comment by chrisroberts** [comment]
Hi there. The issue you are encountering is due to the antivirus software in use improperly flagging virtualbox and preventing it from running. You'll either need to disable the antivirus software or include the virtualbox executables (and maybe some other files depending on what all it's flagging) in an allowlist to prevent them from being flagged.

Cheers

**Comment by Jpanda124** [comment]
I tried to add virtual box in the exclusion list , still same issue persists .

![image](https://user-images.githubusercontent.com/80794653/112883993-f256ba00-909c-11eb-88d7-6641a82dba43.png)
