### ISSUE TITLE
shared_folders

### ISSUE THREAD

**Issue by cuky23** [hashicorp/vagrant#12236]
Owner, group setting!   While this is really handy!  I feel we are missing a trick as regards the usage.

Senario!
user quoted dont exit!
current  action!  exit with a failure message, zip end of story!

What if! a flag was put on sync-folders call to allow the create of the user quoted.

this would us devs that are not deep dive vagrant developes a very painful learning curve with triggers( which needs , the option of AND so u can pin where down more.

please consider this a Request for enhancement on create user for share as part of the code

I will update with my current LAB on this issue!  as I dont think triggers is the solution here!   making shared_folders work with its options correctly is!

Going to look into the code around mounting!  as if it has enough access to mount, it can add the owner if it does exist. my ruby is rusty, but I think enhancement of that code block is the correct method.  not triggers?  thoughts welcome.  i want this fixed for ALL

**Comment by cuky23** [comment]
LAB says 
a tweek here would sort it
./embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/synced_folder.rb

            # Calculate the owner and group
            ssh_info = machine.ssh_info
            data[:owner] ||= ssh_info[:username]
            data[:group] ||= ssh_info[:username]

A call around checking this exist not jumping to FAIL!  trap this and send it to create a user if flag exists!

can anyone help me hack this working?

**Comment by cuky23** [comment]
currently this happens
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

id -u apache

The error output from the command was:

id: apache: no such user

**Comment by cuky23** [comment]
user apache, needs to be injected to the host if not exist!  why have Owner and Group if not to make use of them in code
fix on vbox 1st

**Comment by cuky23** [comment]
could the shared_folders be bent to allow  "id -u apache &>/dev/null || useradd apache"  instead of just a flat check , this would add the user if it didnt exist.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for the suggestions, unfortunately the way in which synced folders are implemented they depend on the user and/or group to be available on the guest when run. For instances where the user is created later by a package installation or some other method via provisioners the workaround is to create the users via a trigger or customize the underlying box to include the required user and/or group. When it's undesirable to use a before trigger, customizing a box is an easy solution.

Cheers.
