### ISSUE TITLE
Issues bringing machine ldap and mongo up for M310 mongoDB University training

### ISSUE THREAD

**Issue by vinnybc** [hashicorp/vagrant#12241]
Hi there.
It's a little bit frustrating because every time I have to bring up machines to follow the M310 mongoDB University training I'm having a lot of issue. At first because my company is running ZScaler but when we go around that I have a lot of problems with provisioning. All the resources are on the mongo versions that are basically deprecated which also don't understand. It's making me waist a lot of time taking into consideration I have to finish the training at specific time if that make sense.
I'm having problems bringing up the ldap and mongodb machines. The errors are:

with ldap:
Bringing machine 'ldap' up with 'virtualbox' provider...
==> ldap: Importing base box 'CentoOS 6.4'...
==> ldap: Matching MAC address for NAT networking...
==> ldap: Setting the name of the VM: ldap-server
==> ldap: Clearing any previously set forwarded ports...
==> ldap: Clearing any previously set network interfaces...
==> ldap: Preparing network interfaces based on configuration...
ldap: Adapter 1: nat
ldap: Adapter 2: hostonly
==> ldap: Forwarding ports...
ldap: 22 (guest) => 2222 (host) (adapter 1)
==> ldap: Running 'pre-boot' VM customizations...
==> ldap: Booting VM...
==> ldap: Waiting for machine to boot. This may take a few minutes...
ldap: SSH address: 127.0.0.1:2222
ldap: SSH username: vagrant
ldap: SSH auth method: private key
==> ldap: Machine booted and ready!
[ldap] GuestAdditions versions on your host (6.1.16) and guest (4.2.10) do not match.
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
Error: Cannot find a valid baseurl for repo: base
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
Eg. Invalid release/repo/arch combination/
removing mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt
Unmounting Virtualbox Guest Additions ISO from: /mnt
umount: /mnt: not mounted
==> ldap: Checking for guest additions in VM...
ldap: The guest additions on this VM do not match the installed version of
ldap: VirtualBox! In most cases this is fine, but in rare cases it can
ldap: prevent things such as shared folders from working properly. If you see
ldap: shared folder errors, please make sure the guest additions within the
ldap: virtual machine match the version of VirtualBox you have installed on
ldap: your host and reload your VM.
ldap:
ldap: Guest Additions Version: 4.2.10
ldap: VirtualBox Version: 6.1
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

umount /mnt

Stdout from the command:

Stderr from the command:

umount: /mnt: not mounted

With the mongodb one:

Bringing machine 'mongod-m034' up with 'virtualbox' provider...
==> mongod-m034: Importing base box 'ubuntu/trusty64'...
==> mongod-m034: Matching MAC address for NAT networking...
==> mongod-m034: Setting the name of the VM: mongod-m034
==> mongod-m034: Clearing any previously set forwarded ports...
==> mongod-m034: Fixed port collision for 22 => 2222. Now on port 2200.
==> mongod-m034: Clearing any previously set network interfaces...
==> mongod-m034: Preparing network interfaces based on configuration...
mongod-m034: Adapter 1: nat
mongod-m034: Adapter 2: hostonly
==> mongod-m034: Forwarding ports...
mongod-m034: 22 (guest) => 2200 (host) (adapter 1)
==> mongod-m034: Running 'pre-boot' VM customizations...
==> mongod-m034: Booting VM...
==> mongod-m034: Waiting for machine to boot. This may take a few minutes...
mongod-m034: SSH address: 127.0.0.1:2200
mongod-m034: SSH username: vagrant
mongod-m034: SSH auth method: private key
mongod-m034:
mongod-m034: Vagrant insecure key detected. Vagrant will automatically replace
mongod-m034: this with a newly generated keypair for better security.
mongod-m034:
mongod-m034: Inserting generated public key within guest...
mongod-m034: Removing insecure key from the guest if it's present...
mongod-m034: Key inserted! Disconnecting and reconnecting using new SSH key...
==> mongod-m034: Machine booted and ready!
[mongod-m034] A Virtualbox Guest Additions installation was found but no tools to rebuild or start them.
* Stopping VirtualBox Additions
...done.
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
acl at-spi2-core colord dconf-gsettings-backend dconf-service dkms fakeroot
fontconfig fontconfig-config fonts-dejavu-core gcc gcc-4.8
hicolor-icon-theme libasan0 libasound2 libasound2-data libatk-bridge2.0-0
libatk1.0-0 libatk1.0-data libatomic1 libatspi2.0-0 libavahi-client3
libavahi-common-data libavahi-common3 libc-dev-bin libc6-dev
libcairo-gobject2 libcairo2 libcanberra-gtk3-0 libcanberra-gtk3-module
libcanberra0 libcolord1 libcolorhug1 libcups2 libdatrie1 libdconf1
libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libexif12 libfakeroot
libfontconfig1 libfontenc1 libgcc-4.8-dev libgd3 libgdk-pixbuf2.0-0
libgdk-pixbuf2.0-common libgl1-mesa-dri libgl1-mesa-glx libglapi-mesa
libgomp1 libgphoto2-6 libgphoto2-l10n libgphoto2-port10 libgraphite2-3
libgtk-3-0 libgtk-3-bin libgtk-3-common libgudev-1.0-0 libgusb2
libharfbuzz0b libice6 libieee1284-3 libitm1 libjasper1 libjbig0
libjpeg-turbo8 libjpeg8 liblcms2-2 libllvm3.4 libltdl7 libnotify-bin
libnotify4 libogg0 libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0
libpciaccess0 libpixman-1-0 libquadmath0 libsane libsane-common libsm6
libtdb1 libthai-data libthai0 libtiff5 libtsan0 libtxc-dxtn-s2tc0 libv4l-0
libv4lconvert0 libvorbis0a libvorbisfile3 libvpx1 libwayland-client0
libwayland-cursor0 libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0
libxcb-glx0 libxcb-present0 libxcb-render0 libxcb-shm0 libxcb-sync1
libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxfont1 libxi6
libxinerama1 libxkbcommon0 libxkbfile1 libxmu6 libxpm4 libxrandr2
libxrender1 libxshmfence1 libxt6 libxtst6 libxxf86vm1 linux-libc-dev
manpages-dev notification-daemon sound-theme-freedesktop x11-common
x11-xkb-utils xfonts-base xfonts-encodings xfonts-utils xserver-common
xserver-xorg-core
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
virtualbox-guest-dkms* virtualbox-guest-utils* virtualbox-guest-x11*
0 upgraded, 0 newly installed, 3 to remove and 0 not upgraded.
After this operation, 12.2 MB disk space will be freed.
(Reading database ... 63238 files and directories currently installed.)
Removing virtualbox-guest-dkms (4.3.40-dfsg-0ubuntu14.04.1) ...

-------- Uninstall Beginning --------
Module: virtualbox-guest
Version: 4.3.40
Kernel: 3.13.0-170-generic (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

vboxguest.ko:
- Uninstallation
- Deleting from: /lib/modules/3.13.0-170-generic/updates/dkms/
- Original module
- No original module was found for this module on this kernel.
- Use the dkms install command to reinstall any previous module version.

vboxsf.ko:
- Uninstallation
- Deleting from: /lib/modules/3.13.0-170-generic/updates/dkms/
- Original module
- No original module was found for this module on this kernel.
- Use the dkms install command to reinstall any previous module version.

vboxvideo.ko:
- Uninstallation
- Deleting from: /lib/modules/3.13.0-170-generic/updates/dkms/
- Original module
- No original module was found for this module on this kernel.
- Use the dkms install command to reinstall any previous module version.

depmod....

DKMS: uninstall completed.

------------------------------
Deleting module version: 4.3.40
completely from the DKMS tree.
------------------------------
Done.
Removing virtualbox-guest-x11 (4.3.40-dfsg-0ubuntu14.04.1) ...
Purging configuration files for virtualbox-guest-x11 (4.3.40-dfsg-0ubuntu14.04.1) ...
Removing virtualbox-guest-utils (4.3.40-dfsg-0ubuntu14.04.1) ...
Purging configuration files for virtualbox-guest-utils (4.3.40-dfsg-0ubuntu14.04.1) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for libc-bin (2.19-0ubuntu6.15) ...
Reading package lists...
Building dependency tree...
Reading state information...
dkms is already the newest version.
dkms set to manually installed.
linux-headers-3.13.0-170-generic is already the newest version.
linux-headers-3.13.0-170-generic set to manually installed.
The following packages were automatically installed and are no longer required:
acl at-spi2-core colord dconf-gsettings-backend dconf-service fontconfig
fontconfig-config fonts-dejavu-core hicolor-icon-theme libasound2
libasound2-data libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data libatspi2.0-0
libavahi-client3 libavahi-common-data libavahi-common3 libcairo-gobject2
libcairo2 libcanberra-gtk3-0 libcanberra-gtk3-module libcanberra0 libcolord1
libcolorhug1 libcups2 libdatrie1 libdconf1 libdrm-intel1 libdrm-nouveau2
libdrm-radeon1 libexif12 libfontconfig1 libfontenc1 libgd3
libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-common libgl1-mesa-dri libgl1-mesa-glx
libglapi-mesa libgphoto2-6 libgphoto2-l10n libgphoto2-port10 libgraphite2-3
libgtk-3-0 libgtk-3-bin libgtk-3-common libgudev-1.0-0 libgusb2
libharfbuzz0b libice6 libieee1284-3 libjasper1 libjbig0 libjpeg-turbo8
libjpeg8 liblcms2-2 libllvm3.4 libltdl7 libnotify-bin libnotify4 libogg0
libpango-1.0-0 libpangocairo-1.0-0 libpangoft2-1.0-0 libpciaccess0
libpixman-1-0 libsane libsane-common libsm6 libtdb1 libthai-data libthai0
libtiff5 libtxc-dxtn-s2tc0 libv4l-0 libv4lconvert0 libvorbis0a
libvorbisfile3 libvpx1 libwayland-client0 libwayland-cursor0 libx11-xcb1
libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
libxcb-render0 libxcb-shm0 libxcb-sync1 libxcomposite1 libxcursor1
libxdamage1 libxfixes3 libxfont1 libxi6 libxinerama1 libxkbcommon0
libxkbfile1 libxmu6 libxpm4 libxrandr2 libxrender1 libxshmfence1 libxt6
libxtst6 libxxf86vm1 notification-daemon sound-theme-freedesktop x11-common
x11-xkb-utils xfonts-base xfonts-encodings xfonts-utils xserver-common
xserver-xorg-core
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: block device /tmp/VBoxGuestAdditions.iso is write-protected, mounting read-only
Installing Virtualbox Guest Additions 6.1.16 - guest version is 4.3.40
Verifying archive integrity... All good.
Uncompressing VirtualBox 6.1.16 Guest Additions for Linux........
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules. This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions: /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions: /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel 3.13.0-170-generic.
Adding system startup for /etc/init.d/vboxadd ...
/etc/rc0.d/K90vboxadd -> ../init.d/vboxadd
/etc/rc1.d/K90vboxadd -> ../init.d/vboxadd
/etc/rc6.d/K90vboxadd -> ../init.d/vboxadd
/etc/rc2.d/S10vboxadd -> ../init.d/vboxadd
/etc/rc3.d/S10vboxadd -> ../init.d/vboxadd
/etc/rc4.d/S10vboxadd -> ../init.d/vboxadd
/etc/rc5.d/S10vboxadd -> ../init.d/vboxadd
Adding system startup for /etc/init.d/vboxadd-service ...
/etc/rc0.d/K65vboxadd-service -> ../init.d/vboxadd-service
/etc/rc1.d/K65vboxadd-service -> ../init.d/vboxadd-service
/etc/rc6.d/K65vboxadd-service -> ../init.d/vboxadd-service
/etc/rc2.d/S35vboxadd-service -> ../init.d/vboxadd-service
/etc/rc3.d/S35vboxadd-service -> ../init.d/vboxadd-service
/etc/rc4.d/S35vboxadd-service -> ../init.d/vboxadd-service
/etc/rc5.d/S35vboxadd-service -> ../init.d/vboxadd-service
Building the VirtualBox Guest Additions kernel modules. This may take a while.
To build modules for other installed kernels, run
/sbin/rcvboxadd quicksetup <version>
or
/sbin/rcvboxadd quicksetup all
Running kernel modules will not be replaced until the system is restarted
vboxadd-service.sh: Starting VirtualBox Guest Addition service.
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel
modules. This may take a while.
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions: /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions: /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Running kernel modules will not be replaced until
the system is restarted
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> mongod-m034: Checking for guest additions in VM...
==> mongod-m034: Setting hostname...
==> mongod-m034: Configuring and enabling network interfaces...
==> mongod-m034: Mounting shared folders...
mongod-m034: /shared => C:/m310-vagrant-env/MongoDB/shared
mongod-m034: /vagrant => C:/m310-vagrant-env/MongoDB
mongod-m034: /dataset => C:/m310-vagrant-env/MongoDB/dataset
==> mongod-m034: Running provisioner: shell...
mongod-m034: Running: C:/Users/I28666/AppData/Local/Temp/vagrant-shell20210312-30256-1aii91q
mongod-m034: + config
mongod-m034: + sudo su
mongod-m034: + echo -e never
mongod-m034: + echo -e never
mongod-m034: + echo manual
mongod-m034: + sudo tee /etc/init/mongod.override
mongod-m034: manual
mongod-m034: + update_repo
mongod-m034: + echo 'Install MongoDB Enterprise Repository'
mongod-m034: Install MongoDB Enterprise Repository
mongod-m034: + sudo tee /etc/apt/sources.list.d/mongodb-enterprise.list
mongod-m034: ++ lsb_release -sc
mongod-m034: + echo 'deb http://repo.mongodb.com/apt/ubuntu trusty/mongodb-enterprise/3.3 multiverse'
mongod-m034: deb http://repo.mongodb.com/apt/ubuntu trusty/mongodb-enterprise/3.3 multiverse
mongod-m034: + sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
mongod-m034: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.TW1fNOR4eH --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/ubuntu-advantage-esm-infra-trusty.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
mongod-m034: gpg:
mongod-m034: requesting key A15703C6 from hkp server keyserver.ubuntu.com
mongod-m034: gpg: key A15703C6: public key "MongoDB 3.4 Release Signing Key <packaging@mongodb.com>" imported
mongod-m034: gpg: Total number processed: 1
mongod-m034: gpg: imported: 1 (RSA: 1)
mongod-m034: + echo 'Update Repositoryies'
mongod-m034: Update Repositoryies
mongod-m034: + sudo apt-get update -y
mongod-m034: Ign http://archive.ubuntu.com trusty InRelease
mongod-m034: Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
mongod-m034: Get:2 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
mongod-m034: Hit http://archive.ubuntu.com trusty-backports InRelease
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-security InRelease
mongod-m034: Ign http://repo.mongodb.com trusty/mongodb-enterprise/3.3 InRelease
mongod-m034: Hit http://archive.ubuntu.com trusty Release.gpg
mongod-m034: Get:3 http://archive.ubuntu.com trusty-updates/main Sources [431 kB]
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-updates InRelease
mongod-m034: Get:4 http://archive.ubuntu.com trusty-updates/restricted Sources [6,313 B]
mongod-m034: Get:5 http://archive.ubuntu.com trusty-updates/universe Sources [231 kB]
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-security Release.gpg
mongod-m034: Get:6 http://archive.ubuntu.com trusty-updates/multiverse Sources [7,535 B]
mongod-m034: Get:7 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1,177 kB]
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-updates Release.gpg
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-security Release
mongod-m034: Get:8 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [17.2 kB]
mongod-m034: Get:9 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [525 kB]
mongod-m034: Get:10 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [14.6 kB]
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-updates Release
mongod-m034: Get:11 http://archive.ubuntu.com trusty-updates/main Translation-en [582 kB]
mongod-m034: Get:12 http://security.ubuntu.com trusty-security/main Sources [172 kB]
mongod-m034: Get:13 http://archive.ubuntu.com trusty-updates/multiverse Translation-en [7,616 B]
mongod-m034: Get:14 http://repo.mongodb.com trusty/mongodb-enterprise/3.3 Release.gpg [801 B]
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-security/main amd64 Packages/DiffIndex
mongod-m034: Get:15 http://archive.ubuntu.com trusty-updates/restricted Translation-en [4,028 B]
mongod-m034: Get:16 http://archive.ubuntu.com trusty-updates/universe Translation-en [281 kB]
mongod-m034: Get:17 http://archive.ubuntu.com trusty-backports/main Sources [9,709 B]
mongod-m034: Get:18 http://archive.ubuntu.com trusty-backports/restricted Sources [28 B]
mongod-m034: Get:19 http://archive.ubuntu.com trusty-backports/universe Sources [35.4 kB]
mongod-m034: Get:20 http://archive.ubuntu.com trusty-backports/multiverse Sources [1,896 B]
mongod-m034: Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages
mongod-m034: Get:21 http://security.ubuntu.com trusty-security/universe Sources [103 kB]
mongod-m034: Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
mongod-m034: Get:22 http://repo.mongodb.com trusty/mongodb-enterprise/3.3 Release [4,439 B]
mongod-m034: Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-updates/main amd64 Packages/DiffIndex
mongod-m034: Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages
mongod-m034: Hit http://archive.ubuntu.com trusty-backports/main Translation-en
mongod-m034: Hit http://archive.ubuntu.com trusty-backports/multiverse Translation-en
mongod-m034: Hit http://archive.ubuntu.com trusty-backports/restricted Translation-en
mongod-m034: Hit http://archive.ubuntu.com trusty-backports/universe Translation-en
mongod-m034: Hit http://archive.ubuntu.com trusty Release
mongod-m034: Get:23 http://repo.mongodb.com trusty/mongodb-enterprise/3.3/multiverse amd64 Packages [11.6 kB]
mongod-m034: Get:24 http://archive.ubuntu.com trusty/main Sources [1,064 kB]
mongod-m034: Get:25 http://archive.ubuntu.com trusty/restricted Sources [5,433 B]
mongod-m034: Get:26 http://archive.ubuntu.com trusty/universe Sources [6,399 kB]
mongod-m034: Get:27 http://security.ubuntu.com trusty-security/main amd64 Packages [835 kB]
mongod-m034: Get:28 http://archive.ubuntu.com trusty/multiverse Sources [174 kB]
mongod-m034: Hit http://archive.ubuntu.com trusty/main amd64 Packages
mongod-m034: Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
mongod-m034: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
mongod-m034: Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
mongod-m034: Hit http://archive.ubuntu.com trusty/main Translation-en
mongod-m034: Hit http://archive.ubuntu.com trusty/multiverse Translation-en
mongod-m034: Hit http://archive.ubuntu.com trusty/restricted Translation-en
mongod-m034: Hit http://archive.ubuntu.com trusty/universe Translation-en
mongod-m034: Get:29 http://security.ubuntu.com trusty-security/universe amd64 Packages [295 kB]
mongod-m034: Ign http://archive.ubuntu.com trusty/main Translation-en_US
mongod-m034: Ign http://archive.ubuntu.com trusty/multiverse Translation-en_US
mongod-m034: Ign http://archive.ubuntu.com trusty/restricted Translation-en_US
mongod-m034: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
mongod-m034: Get:30 http://security.ubuntu.com trusty-security/main Translation-en [448 kB]
mongod-m034: Ign http://repo.mongodb.com trusty/mongodb-enterprise/3.3/multiverse Translation-en_US
mongod-m034: Get:31 http://security.ubuntu.com trusty-security/universe Translation-en [162 kB]
mongod-m034: Ign http://repo.mongodb.com trusty/mongodb-enterprise/3.3/multiverse Translation-en
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-security/main Translation-en_US
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-security/main Translation-en
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-updates/main Translation-en_US
mongod-m034: Ign https://esm.ubuntu.com trusty-infra-updates/main Translation-en
mongod-m034: Err https://esm.ubuntu.com trusty-infra-security/main amd64 Packages
mongod-m034: gnutls_handshake() failed: Bad record MAC
mongod-m034: Err https://esm.ubuntu.com trusty-infra-updates/main amd64 Packages
mongod-m034: gnutls_handshake() failed: Bad record MAC
mongod-m034: Fetched 13.1 MB in 7s (1,709 kB/s)
mongod-m034: W: Failed to fetch https://esm.ubuntu.com/ubuntu/dists/trusty-infra-security/main/binary-amd64/Packages gnutls_handshake() failed: Bad record MAC
mongod-m034:
mongod-m034: W: Failed to fetch https://esm.ubuntu.com/ubuntu/dists/trusty-infra-updates/main/binary-amd64/Packages gnutls_handshake() failed: Bad record MAC
mongod-m034:
mongod-m034: E: Some index files failed to download. They have been ignored, or old ones used instead.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I have renamed the fine vagrantfile for the mongodb one to Vagrantfile - mongodb to be allowed to attach it here.

Looking forward to hearing from you soon.

Have a great day.

Cheers.

Vinny.

**Comment by soapy1** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier ☹️

Cheers!
