### ISSUE TITLE
Vagrant error installing vagrant-vbguest in ArchLinux

### ISSUE THREAD

**Issue by VictorMorenoJimenez** [hashicorp/vagrant#12248]
### Vagrant version
Using `main` branch to build from sources. Followed https://www.vagrantup.com/docs/installation/source to install.

### Host operating system
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

### Expected behavior
Plugin installed without errors and Vagrant able to run Virtualbox as provider.

### Actual behavior
Plugin install exits with errors. 
After installing Vagrant following https://www.vagrantup.com/docs/installation/source to have the latest version to fix a bug in Archlinux solved in this PR https://github.com/hashicorp/vagrant/pull/12213 explained in this issue https://github.com/hashicorp/vagrant/issues/12202. 

### Steps to reproduce
- In ArchLinux host.
- Install Vagrant from sources `main` branch.
- Added `~/vagrant/exec/vagrant` to $PATH and required executables. 
- Installed `rsync`.
- Install plugin: `vagrant plugin install vagrant-vbguest vagrant-share`

```
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies rexml (= 3.2.4) and rexml (= 3.2.3)
  Activated rexml-3.2.3
  which does not match conflicting dependency (= 3.2.4)

  Conflicting dependency chains:
    rexml (= 3.2.3), 3.2.3 activated

  versus:
    rexml (= 3.2.4)

  Gems matching rexml (= 3.2.4):
    rexml-3.2.4
```

I'm unable to use Vagrant right now in ArchLinux. Using the installed package `2.2.14` fails due to an other dependecy error, which was solved in `main` branch in this  [PR](https://github.com/hashicorp/vagrant/pull/12213. ). Using vagrant `2.2.14` leads me to the issue  https://github.com/hashicorp/vagrant/issues/12202.

Hope it helps!
Víctor.

**Comment by antOnioOnio** [comment]
Hi, is this already solved ? Having the same issue.

**Comment by qlyoung** [comment]
+1, I switched to a git build of vagrant to attempt to work around #12202 and am hitting this also.

**Comment by kittensteak** [comment]
I was able to install both `vagrant-libvirt` and `vagrant-vbguest` by applying this [patch](https://github.com/hashicorp/vagrant/pull/12213#issuecomment-805345709) on vagrant 2.2.14 installed from Arch repos.

**Comment by chrisroberts** [comment]
@VictorMorenoJimenez Can you please provide a debug gist of the error you are encoutering? Thanks!

**Comment by qlyoung** [comment]
@chrisroberts https://gist.github.com/qlyoung/f0c8202504c1c5753c3dd8527a48f04f

**Comment by VictorMorenoJimenez** [comment]
@chrisroberts the one provided by @qlyoung will work. Thanks!
