### ISSUE TITLE
Unsupported semver prerelease tag when downloading a box from artifactory

### ISSUE THREAD

**Issue by aacebedo** [hashicorp/vagrant#12240]
### Vagrant version

2.2.14

### Host operating system

Linux

### Guest operating system

Linux

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box_url = <artifactory_url>
  config.vm.box = <box_name>
  config.vm.box_version = 1.1.0-alpha
  config.vm.box_check_update = true
  config.vm.provider "docker"
end
```

### Expected behavior

The machine should have been created after a complete box download.

### Actual behavior

Vagrant does not parse the version correctly, it reports an invalid version. I think it is related to #6892.

```bash
A version of the box you're loading is formatted in a way that
Vagrant cannot parse: '-alpha'. Please reformat the version
to be properly formatted. It should be in the format of
X.Y.Z.
```

### Steps to reproduce

1. Upload a box on a artifactory server with version x.y.z-prerelease
2. Create a machine with a Vagrantfile referencing this version
3. Enjoy the bug :)

### References
- GH-6892

**Comment by soapy1** [comment]
Hey there,
I'm trying to reproduce this issue, but I'm not able to. Could you provide a [debug log](https://www.vagrantup.com/docs/other/debugging) for the error. 
For reference, the Vagrantfile I'm testing against looks like:
```
Vagrant.configure("2") do |config|
  config.vm.box = "scastellarin/mybox"  
  config.vm.box_version = '0.1.0-alpha'
end
```
I would expect it to fail in the same way, but instead it brings the box up just fine.

**Comment by aacebedo** [comment]
Hi thanks you to take some time to investigate this.

I'll try to get some additional info in the coming days especially about the debug bug.

**Comment by aacebedo** [comment]
I close the issue, the problem was an incorrect variable in a template vagrant file used by packer.
