### ISSUE TITLE
Vagrant on windows

### ISSUE THREAD

**Issue by Georgy-Garnov** [hashicorp/vagrant#12246]
I'm sorry guys but working with vagrant on windows is realy hard. It feels like very unstable program.

**Comment by tschuchortdev** [comment]
It's not much better on Arch either. Just once I'd like to make an update without Vagrant breakage... that's Ruby for you I guess.

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information by opening a new issue. Thank you! 😄
