### ISSUE TITLE
Archlinux fails to bootstrap Salt due to missing python2-futures package

### ISSUE THREAD

**Issue by raqua** [hashicorp/vagrant#12286]
Vagrant up fails to bootstrap salt with archlinux due to missing python2 package.

[bug.txt](https://github.com/hashicorp/vagrant/files/6277886/bug.txt)

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
