### ISSUE TITLE
'vagrant up' | Disk type and size unit

### ISSUE THREAD

**Issue by Ricky-Tigg** [hashicorp/vagrant#12287]
**OS:** Fedora; **Vagrant version:** vagrant-2.2.9-6.fc34.noarch

1. Lack of **descriptive type** of disk whose size is exhibited.
- It can then be interpreted as a _physical disk size_ – what it is not.
- When interpreted as such, its unusual size may legitimately be reported as an issue.
2. Lack of **exhaustive unit**; "`G`". It can then be interpreted either as "`GiB`", "`GB`", "`Gib`" or "`Gb`".

```
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
(...)
==> default:  -- Image:  /(...)/fedora_default.img (128G)
```
As comparison, disk types are here descriptive – _virtual size_ and _disk size_ –, hence there is no place for a non valid interpretation. Values are clearly exhibited since they are not attached to their units (#_value_# #_units_#) like Vagrant exhibits them  (#_value_##_units_#).
```
$ qemu-img info ~/.local/share/libvirt/images/fedora_default.img | sed -n '2,4p'
file format: qcow2
virtual size: 128 GiB (137438953472 bytes)
disk size: 147 MiB
```
A proper exhibition model would be:
```
$ vagrant up
(...)
==> default:  -- Image:  /(...)/fedora_default.img (virtual size / disk size; 128 GiB / 147 MiB)
```

**Comment by electrofelix** [comment]
This would be an enhancement request for the vagrant-libvirt project, consider logging over at https://github.com/vagrant-libvirt/vagrant-libvirt/issues

Would need to add retrieval of the disk size field at the following point https://github.com/vagrant-libvirt/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/handle_box_image.rb#L178 as well inject it at https://github.com/vagrant-libvirt/vagrant-libvirt/blob/f221daaaaf538ca973888da5c921a357c761218a/lib/vagrant-libvirt/action/handle_box_image.rb#L42 and then it can be reported on.

Essentially all of these details are coming from the provide which vagrant doesn't control.
