### ISSUE TITLE
libtinfo.so.5 error

### ISSUE THREAD

**Issue by sanchil** [hashicorp/vagrant#12313]
### Vagrant version

Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

version: 2.2.15

### Host operating system

Linux: openSuse Leap 15.2
kernel: 5.3.18-lp152.69-default

This is the operating system that you run locally.

### Guest operating system

virtualbox : version 6.1.18 r142142 (Qt5.12.7)

### Expected behavior

Upgrade from 2.2.14 to 2.2.15 should have worked. But did not.
2.2.14 works 

### Actual behavior

I get this error as below :

bash: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory

### Steps to reproduce

(back up older 2.2.14 vagrant file)
1. Download vagrant_2.2.15_linux_amd64.zip
2. unzip it and copy it to /opt which is in my PATH
3. Run vagrant -v

**Comment by fridyle** [comment]
I had the same issue, I installed libncurses5

**Comment by sanchil** [comment]
Thank you fridyle. That resolved the issue for me. Although I now get the following version error, I will leave it at that and wait for hashicorp to fix this in next release. 
lib/x86_64-linux-gnu/libreadline.so.7: no version information available (required by bash)

**Comment by sanchil** [comment]
Thank you fridyle. That resolved the issue for me. Although I still receive a version error message, it seems to be working. Hopefully hashicorp will resolve these version issues for linux in the next round. 
/lib/x86_64-linux-gnu/libreadline.so.7: no version information available (required by bash)

**Comment by soapy1** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier ☹️

Cheers!
