### ISSUE TITLE
Vagrant script option is not compatible with ruby 3.0

### ISSUE THREAD

**Issue by ddrazyk** [hashicorp/vagrant#12318]
Hi,
I have an issue running vagrant on Fedora 34 which has ruby 3.0. The script option throws an error about number of arguments. If I remove this part: _config.vm.provision "shell", inline: $script_ it works fine. It works fine on Fedora 33 and earlier.

### Vagrant version
2.2.9

### Host operating system

Linux fedora 5.11.3-300.fc34.x86_64 #1 SMP Thu Mar 4 19:03:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Guest operating system
Centos 7. Vagrant box: centos/7.

### Vagrantfile

$script = <<SCRIPT
rpm -ivh https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
yum install -y epel-release
yum install -y puppet-agent git curl wget
SCRIPT

Vagrant.configure(2) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false

  config.vm.define "es01" do |subconfig|
    subconfig.vm.box = "centos/7"
    subconfig.vm.hostname = "elastic"
    subconfig.vm.network "private_network", ip: "172.16.0.21"
  end

  config.vm.provision "shell",
    inline: $script

  config.vm.provider "libvirt" do |v|
    v.memory = 2048
    v.cpus = 2
    v.driver= 'kvm'
    v.storage_pool_name = 'default'
    v.qemu_use_session = false
  end

  config.ssh.insert_key = false

end

### Debug output

https://gist.github.com/ddrazyk/afb2c86c31601bd46334d19fa35d7759

### Expected behavior

Vagrant should run as usual and execute the script in Vagrantfile. (just like it does on Fedora 33 or without script option).

### Actual behavior

Vagrant throws an error during Running: inline script.

### Steps to reproduce

1. Install vagrant-libvirt and vagrant-hostmanager plugins.
2. Run the above Vagrant file with vagrant up --provider=libvirt

**Comment by pietrobaricco** [comment]
Lost a good few hours trying everything to make vagrant work on F34.
Managed to make it work by downgrading ruby to 2.7, then installing vagrant from F33 repos

`dnf module reset ruby
dnf module enable ruby:2.7
dnf --allowerasing distro-sync
dnf install vagrant vagrant-libvirt --releasever=33
`

I always wait a couple months before updating the distro, this time I did it early...never again

**Comment by ddrazyk** [comment]
Thanks a lot @pietrobaricco ! I faced the issue on a test box and held off my workstation upgrade. Now it's working fine. I hope someone will look into this issue and solves it permanently without workarounds.

**Comment by der-eismann** [comment]
There's also a fix in https://github.com/hashicorp/vagrant/pull/12273, but nobody has looked at it yet.

**Comment by h3o66** [comment]
I made a build to fix this for fedora 34:
https://copr.fedorainfracloud.org/coprs/birkch/vagrant-f34-fix/
I might do a PR for these changes that this is patched on fedora side.

**Comment by der-eismann** [comment]
@h3o66 the Fedora packagers are already [aware of this](https://bugzilla.redhat.com/show_bug.cgi?id=1945740#c3), so I guess there's no need to open a PR at Fedora

**Comment by voxik** [comment]
@pvalena Do we have patch for this issue applied in Fedora?

**Comment by pvalena** [comment]
> @pvalena Do we have patch for this issue applied in Fedora?

All PRs linked in the tracking issue #12417 are already in Fedora (actually, I'm author of two of those), applied with an update to vagrant 2.2.16:

https://src.fedoraproject.org/rpms/vagrant/c/4a3ce0bd3844aa1897e9fb27c5c0af3530a7cb30?branch=rawhide

Let me know if more issues occur in Fedora. Those that I know of (and I'm unsure how to solve), I've also reported, and are tracked in the issue.
