### ISSUE TITLE
"URL using bad/illegal format or missing URL" with Vagrant 2.2.15

### ISSUE THREAD

**Issue by mictaege** [hashicorp/vagrant#12320]
Since Update 2.2.15 I'm getting a warning message 

```
There was a problem while downloading the metadata for your box
to check for updates. This is not an error, since it is usually due
to temporary network problems. This is just a warning. The problem
encountered was:

URL using bad/illegal format or missing URL
```

if starting up an existing vagrant box with `vagrant up` and a corresponding error message if the vagrant box is not yet present.

In my case the `box_url` refers to a custom `json` metadata file present in the local file system where a custom base box is configured. The `box` files of the base box are also present in the local file system within the same directory.

I think that this problems relates in some way how vagrant is passing the `box_url` to curl. 

### Vagrant version

Update from 2.2.14 to 2.2.15

### Host operating system

Windows

### Guest operating system

Ubuntu

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|

	config.vm.box = "ologis-ops-mt"
	config.vm.box_url = "file://C:/Users/micta/OneDrive/boxes/ologis-ops-mt.json"
	config.vm.define "ologis-ops-mt"

	config.ssh.username = "mictaege"
	config.ssh.password = "mictaege"

	config.vm.synced_folder ".", "/vagrant", disabled: true

	config.vbguest.allow_downgrade = false

	config.vm.provider "virtualbox" do |v|
	    v.linked_clone = true
	    v.memory = 8192
	    v.cpus = 8
	    v.gui = true
            # ...
	end
end
```

### Expected behavior

Vagrant should find the meta data file and the base box.

### Actual behavior

- the version check for existing boxes fails
- not able to create new vagrant boxes referring to a locally stored meta data file / base box

**Comment by soapy1** [comment]
Hey there,
thanks for opening up an issue! Could you please include a [full debug log](https://www.vagrantup.com/docs/other/debugging)

**Comment by mictaege** [comment]
> Hey there,
> thanks for opening up an issue! Could you please include a [full debug log](https://www.vagrantup.com/docs/other/debugging)

Thanks for your quick reply.

Meanwhile I downgraded my Vagrant installation to 2.2.14 to avoid these problem.

So in order the create a debug log I uninstalled 2.2.14 and installed 2.2.15 once again ... and then the problem was gone ...

Seems as if the problem in finding the box meta data has either been temporarily or it has been fixed by the reinstallation in some way. Whatever it was, I think this issue can be closed for now.

**Comment by chris-ti-an-g** [comment]
hi...
i have the same error on 2 different equally deployed newly set up windows maschines

see full debug log:
https://gist.github.com/chris-ti-an-g/f045aaacf8171728fb33b732196c6c15

**Comment by neikei** [comment]
Hi @mictaege, please check if the following change fixes your problem.

```
Old: config.vm.box_url = "file://C:/Users/micta/OneDrive/boxes/ologis-ops-mt.json"
New: config.vm.box_url = "file:///C:/Users/micta/OneDrive/boxes/ologis-ops-mt.json"
```

**Comment by neikei** [comment]
Hi @mictaege , please check if the following change of the path fixes you problem:

```
Old:	 config.vm.box_url = "file://C:/Users/micta/OneDrive/boxes/ologis-ops-mt.json"
New:     config.vm.box_url = "file:///C:/Users/micta/OneDrive/boxes/ologis-ops-mt.json"
```

**Comment by chris-ti-an-g** [comment]
Old:   config.vm.box_url = "file://./metadata/meta.json" - not working

New:  config.vm.box_url = "file:///./metadata/meta.json" - not working
https://gist.github.com/chris-ti-an-g/1ab00e6dfe2c69a57eb06e673cc3ac93

New:  config.vm.box_url = "file://u:/devbox/metadata/meta.json" - working
https://gist.github.com/chris-ti-an-g/17a727dbba7b22cfe10bee2e615ed299

New:  config.vm.box_url = "file:///u:/devbox/metadata/meta.json" - working
https://gist.github.com/chris-ti-an-g/acece824cfbd4e79640e497ca50c95d4

but this is not acceptable, i need relative paths

**Comment by mictaege** [comment]
> Hi @mictaege , please check if the following change of the path fixes you problem:
> 
> ```
> Old:	 config.vm.box_url = "file://C:/Users/micta/OneDrive/boxes/ologis-ops-mt.json"
> New:     config.vm.box_url = "file:///C:/Users/micta/OneDrive/boxes/ologis-ops-mt.json"
> ```

Hi neikei. Yes, adding an additional slah to the url will fix the problem in my case.
