### ISSUE TITLE
vagrant 2.2.16 add local box error "using bad/illegal format or missing URL"

### ISSUE THREAD

**Issue by ShynHan** [hashicorp/vagrant#12340]
### Vagrant version

Vagrant 2.2.16

### Host operating system

Windows 10 x64 20H2（19042.964）

### Guest operating system

ubuntu/focal64 v20210429.0.0

### Debug output

[vagrant.log](https://gist.github.com/ShynHan/f97afb2837e73c0623d0a3f65752da52#file-vagrant-log)

### Expected behavior

> vagrant box add --name ubuntu **D:\Vagrant\ubuntu\focal-server-cloudimg-amd64-vagrant.box**
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'ubuntu' (v0) for provider:
    box: Unpacking necessary files from: **file:///D:/Vagrant/ubuntu/focal-server-cloudimg-amd64-vagrant.box**
    box:
==> box: Successfully added box 'ubuntu' (v0) for 'virtualbox'!

use absolute path is success

### Actual behavior

> vagrant box add --name ubuntu **.\focal-server-cloudimg-amd64-vagrant.box**
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'ubuntu' (v0) for provider:
    box: Unpacking necessary files from: **file://D/Vagrant/ubuntu/focal-server-cloudimg-amd64-vagrant.box**
    box:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
URL using bad/illegal format or missing URL

use relative path is fail, the vagrant 2.2.14 is no error

### References

**Comment by breisig** [comment]
Im getting the exact same error.

**Comment by AtreusAuditore** [comment]
how you get the url to say file:/// ? It will only show up as file:// for me

**Comment by tidytrax** [comment]
I gotta the same issue,  on windows power shell I get thist error  using the short path
`vagrant box add name ./boxPath`

but works if use the full path
`vagrant box add nameC:\Users\user\....boxname.box`
