### ISSUE TITLE
NAT DNS Proxy Option?

### ISSUE THREAD

**Issue by devans** [hashicorp/vagrant#1234]
I've spent a few days trying to isolate the cause of really bad instability (I'd only get through the whole up process, including chef provisioning, a fraction of the time) with a Win 7 x64 host and Ubuntu 12.04 32-bit guest. I finally got it down to the NAT DNS proxy option in the sane defaults. 

Basically the host Ubuntu would run for a while then crash hard before finishing the bootstrapping process. I noticed it was usually associated with network transfers (i.e. lots of apt-gets in Chef). I checked out #909 (but it seems like that discussion had more to do with Ubuntu 12.04 hosts?). Finally I ended up manually turning off --natdnsproxy1 in my Vagrantfile, and suddenly everything's humming along fine. 

I'm wondering if anyone has any more insight into why this was happening, and also to raise the question of whether there should be an option in the Vagrant config object to turn it off.

**Comment by nathan-fiscaletti** [comment]
Ah, the god tier issue that is referenced by everyone that is too lazy to remove the template portions in their issue.
