### ISSUE TITLE
Vagrant doesn't utilize Podman as provider.

### ISSUE THREAD

**Issue by Thisisguillermo** [hashicorp/vagrant#12378]
When submitting a bug report, please provide the minimal configuration and required information necessary to reliably reproduce the issue. It
should include a basic Vagrantfile that only contains settings to reproduce the described behavior.

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version

Vagrant 2.2.9

### Host operating system
**Operating system:** Fedora 34 
**Kernel:** 5.11.20-300.fc34.x86_64 #1 SMP Wed May 12 12:45:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Guest operating system
Podman
**podman version:** 3.1.2

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.provision "podman" do |d|
    d.run "rabbitmq"
  end
end
```

### Debug output

https://gist.github.com/Thisisguillermo/224c51131a48d883571f2019bfe2da88

### Expected behavior

Start podman, download the image.

### Actual behavior

What actually happened?

error with:
```
Vagrant knows about the following providers: docker, hyperv, virtualbox
The provider 'podman' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.

Vagrant knows about the following providers: docker, hyperv, virtualbox
```

### Steps to reproduce

1. Use Fedora 34
2. Install podman
3. Install the newest Vagrant from the official website.
4. Make a vagrantfile from the docs: https://www.vagrantup.com/docs/provisioning/podman
5. Run it.

**Comment by soapy1** [comment]
Hey there,
thanks for opening up an issue, however, Vagrant does not have a podman provider, only a podman provisioner. This provisioner runs on the guest machine. So, you need to define a guest box in the Vagrantfile. For example,

```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provision "podman" do |d|
    d.run "rabbitmq"
  end
end
```

This will start rabbitmq in a centos 7 VM. 

I've updated the docs to make this a bit more clear, https://github.com/hashicorp/vagrant/pull/12387
