### ISSUE TITLE
Complete reinstall ohttps://gist.github.com/NicholasBracey/daab5b798dd5caaa43c2cd30b3c0b671#gistcomment-3745375f both vagrant and virtual box has done the trick, not sure what the hell happened here.

### ISSUE THREAD

**Issue by javagovindsharma** [hashicorp/vagrant#12373]
Complete reinstall of both vagrant and virtual box has done the trick, not sure what the hell happened here. 

Thanks for quick response!

_Originally posted by @NicholasBracey in https://github.com/hashicorp/vagrant/issues/7655#issuecomment-235646382_

**Comment by javagovindsharma** [comment]
https://gist.github.com/NicholasBracey/daab5b798dd5caaa43c2cd30b3c0b671#gistcomment-3745375

i getting as like same error vagrant ubuntu

**Comment by soapy1** [comment]
From the debug log in the attached gist, it looks like you are using an old version of Vagrant (2.2.6). Please [upgrade to the latest version](https://www.vagrantup.com/downloads). If this does not resolve your issue, please open a new issue. If that is required, please also be sure to fully fill in the issue template.
