### ISSUE TITLE
Shared hosting deploy using ftp vagrant push

### ISSUE THREAD

**Issue by zarakkhan421** [hashicorp/vagrant#12376]
I am trying to push my app from the vagrant environment to Namecheap shared hosting and it gives me many problems. If any one has any experience with it please share the configuration. Thanks

**Comment by soapy1** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant discuss page](https://discuss.hashicorp.com/c/vagrant/24). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
