### ISSUE TITLE
Enhancement Request: The value of ansible_host should be the assigned IP address in the generated inventory file

### ISSUE THREAD

**Issue by eastack** [hashicorp/vagrant#12386]
In the generated ansible inventory file, `ansible_host` is always 127.0.0.1. Shouldn't this be the actual assigned IP address?

Is it possible to use the assigned IP directly?

Or is there any other way to obtain the assigned IP address in the Vagrantfile, so that I can configure `host_vars` to manually configure `ansible_host` and I plan to use the DHCP to automatically assign the IP address and don't want to manually specify the IP address.

`ansible_host`: The ip/name of the target host to use instead of inventory_hostname.

[Ansible special variables](https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html)

**Comment by soapy1** [comment]
Vagrant supports setting ansible `host_var`. Please see the [Vagrant Ansible documentation](https://www.vagrantup.com/docs/provisioning/ansible_intro#host-variables). Cheers!

**Comment by eastack** [comment]
I know this, but how should I get the IP address assigned by DHCP in the Vagrantfile?

**Comment by eastack** [comment]
Logically speaking, the virtual machine is also an independent machine. The official Ansible definition of `ansible_host` is, "**The ip/name of the target host to use instead of inventory_hostname.**" So shouldn’t it be the IP address assigned by Vagrant for the virtual machine? Why is it always 127.0.0.1?
