### ISSUE TITLE
Does vagrant init not enable synced project folder by default any longer? ls: cannot access '/vagrant'

### ISSUE THREAD

**Issue by coxoperationsengineer** [hashicorp/vagrant#12396]
Hello Team,

"By default, Vagrant will share your project directory (the directory with the Vagrantfile) to /vagrant."

Everywhere I read in the doc's and tutorials indicates that I should be able to by default see my folder mounted where vagrant up was called, and minimally see my Vagrantfile, however, I have tried multiple distro's, and that doesn't seem to be the case.  Did this feature go away?  I recall this working previously, and I didn't have to enable anything extra, but I'm unsure as to when it stopped, as typically I will git clone in the provisioner, but as of late I've needed to share local files in the project.  I do remember it being deceiving in that you had /home/vagrant, and you needed to explicitly navigate to /vagrant, so what am I missing here?

    vagrant@ubuntu2010:~$ ls /vagrant
    ls: cannot access '/vagrant': No such file or directory
    vagrant@ubuntu2010:~$ cd ..
    vagrant@ubuntu2010:/home$ ls
    vagrant
    vagrant@ubuntu2010:/home$ cd ..
    vagrant@ubuntu2010:/$ ls
    bin   cdrom  etc   lib    lib64   lost+found  mnt  proc  run   snap  swap.img  tmp  var
    boot  dev    home  lib32  libx32  media       opt  root  sbin  srv   sys       usr

### Vagrant version

Vagrant 2.2.16
vagrant-vmware-utility: 1.0.20
vagrant-vmware-plugin: 2.1.5
VMWare Fusion Pro: Player Version 12.1.2 (17964953)

### Host operating system

Mac OS Big Sur 11.4

### Guest operating system

generic/ubuntu2010

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu2010"

end
```

### Debug output

https://gist.github.com/coxoperationsengineer/e4e8f1477c15ca036d5df78630fb36de

### Expected behavior

The project folder /ubuntu where the vagrantfile lives, would by synced by default to the guest and available at /vagrant

### Actual behavior

ls: cannot access '/vagrant': No such file or directory

### Steps to reproduce

1.  mkdir ubuntu
2. vagrant init generic/ubuntu2010
3. vagrant up

**Comment by soapy1** [comment]
Hey there, 
this is expected behavior. Vagrant loads Vagrantfiles from a [couple of different sources](https://www.vagrantup.com/docs/vagrantfile#load-order) on the users machine. One being from the box itself. Inspecting the Vagrantfile that is packaged with `generic/ubuntu2010`, you can see this line

`config.vm.synced_folder ".", "/vagrant", disabled: true`

So, Vagrant is doing the right thing here by not sharing the project directory. You can re-enable this by adding the line `config.vm.synced_folder ".", "/vagrant", disabled: false` to your Vagrantfile.

Cheers!

**Comment by coxoperationsengineer** [comment]
Thanks @soapy1 that is interesting, I see the stock file provided via vagrant init on generic/ubuntu2010 in my project folder has a commented out line of:

      # config.vm.synced_folder "../data", "/vagrant_data"
  
  Where do you see: 

     config.vm.synced_folder ".", "/vagrant", disabled: true

I guess it wasn't clear if the fact that line was commented out for that path, meant no path's, including the default /vagrant would work, is that the case?

**Comment by soapy1** [comment]
The Vagrantfile I'm referring to is part of the `generic/ubuntu2020` box. It'll be located in `~/.vagrant.d/boxes/generic-VAGRANTSLASH-ubuntu2010/3.2.20/virtualbox/Vagrantfile`. Or, if you have your box directory somewhere else, `$BOX_DIR/eneric-VAGRANTSLASH-ubuntu2010/3.2.20/virtualbox/Vagrantfile`.

**Comment by coxoperationsengineer** [comment]
@soapy1 thank you again for taking the time to show me what was going on!
