### ISSUE TITLE
Vagrant cloud auth does not still work

### ISSUE THREAD

**Issue by Yohnah** [hashicorp/vagrant#12393]
### Vagrant version

2.2.16

### Host operating system

MacOS Big Sur

### Guest operating system

N/A

### Vagrantfile

N/A

### Debug output

https://gist.github.com/Yohnah/65d2b60baebdfa2c2b59cf21d72d73bd

### Expected behavior

What should have happened?

Allow performing the login

### Actual behavior

What actually happened?

Getting an error raised

### Steps to reproduce

1. vagrant cloud auth login
2.
3.

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- https://github.com/hashicorp/vagrant/issues/12390
- https://github.com/hashicorp/vagrant/issues/12392

I open this bug report because I didn't see how to reopen the related GitHub issues above.

It is not possible to login by cli

**Comment by sio** [comment]
Relevant information from closed issue thread:
> This is CDN misconfiguration. POST requests to `https://vagrantcloud.com/api/v1/authenticate` are dropped by CloudFront.
> https://github.com/hashicorp/vagrant/issues/12392#issuecomment-848555110

**Comment by Yohnah** [comment]
Using OpenDNS DNS services the auth login works like yesterday.

**Comment by dcermak** [comment]
For some reason the API is now responding with `302 Found` and tries to redirect to the same location. My guess would be that something is still missconfigured on CloudFlare?

**Comment by sio** [comment]
> For some reason the API is now responding with 302 Found and tries to redirect to the same location.

I can not reproduce this. The behavior is the same for me (broken):

- POST requests to `https://vagrantcloud.com/api/v1/authenticate` are dropped by CloudFront with "403 Forbidden"
- `vagrant cloud login` works correctly with `VAGRANT_SERVER_URL=https://app.vagrantup.com`

Could you try the curl command from my [other post](https://github.com/hashicorp/vagrant/issues/12392#issuecomment-848555110)? 
```
$ curl -X POST -H "Content-type: application/json" -H "Accept: application/json" -iL -d '{"user":{"login":"baduser","password":"badpassword"}}' "https://vagrantcloud.com/api/v1/authenticate"
```

**Comment by dcermak** [comment]
> > For some reason the API is now responding with 302 Found and tries to redirect to the same location.
> 
> I can not reproduce this. 

I can via this script:
```ruby
require 'vagrant_cloud'
account = VagrantCloud::Account.new(access_token: ENV['VAGRANT_CLOUD_TOKEN`])
```
which throws a big stack trace including lines like this one:
```
/home/dan/suse/github.com/dcermak/obs-to-vagrantcloud/vendor/ruby/3.0.0/gems/excon-0.81.0/lib/excon/middlewares/expects.rb:13:in `response_call': Expected([200, 201, 204]) <=> Actual(302 Found) (Excon::Error::Found)
```

> The behavior is the same for me (broken):
> 
>     * POST requests to `https://vagrantcloud.com/api/v1/authenticate` are dropped by CloudFront with "403 Forbidden"
> 
>     * `vagrant cloud login` works correctly with `VAGRANT_SERVER_URL=https://app.vagrantup.com`
> 
> 
> Could you try the curl command from my [other post](https://github.com/hashicorp/vagrant/issues/12392#issuecomment-848555110)?
> 
> ```
> $ curl -X POST -H "Content-type: application/json" -H "Accept: application/json" -iL -d '{"user":{"login":"baduser","password":"badpassword"}}' "https://vagrantcloud.com/api/v1/authenticate"
> ```

```
HTTP/2 403 
server: CloudFront
date: Wed, 26 May 2021 10:56:29 GMT
content-type: text/html
content-length: 1053
x-cache: Error from cloudfront
via: 1.1 b88825ad151091557d336c3519215162.cloudfront.net (CloudFront)
x-amz-cf-pop: TXL52-C1
x-amz-cf-id: GzBA3I_D_Ef52rd2mmcfsNrCYX6lV2DBCCm8AImzPaXbnV20Vn9b7w==

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: GzBA3I_D_Ef52rd2mmcfsNrCYX6lV2DBCCm8AImzPaXbnV20Vn9b7w==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by sio** [comment]
Ah, that's a different error produced (probably) by the same misconfiguration. 

Token logins are using GET requests instead of POST for password logins.

GET request to `https://vagrantcloud.com/api/v1/authenticate?access_token=*****` is incorrectly redirected to `https://app.vagrantup.com//api/v1/authenticate` (missing access_token) which results in a "401 Unauthorized" error.

Here is a curl command for checking if this part of the issue is fixed (access_token should not be dropped on redirect):

```
$ curl -iIL "https://vagrantcloud.com/api/v1/authenticate?access_token=BADTOKEN"
```

**Comment by soapy1** [comment]
Hey folks,

Sorry about the inconvenience this has caused. The DNS configuration that has caused this issue has been updated. However, it may take some time before users will see that it is in fact resolved as the DNS changes propagate. 

In the mean time, users can get around this issue by exporting the `VAGRANT_SERVER_URL` environment variable to `https://app.vagrantup.com/`.

Thanks!
