### ISSUE TITLE
`vagrant up` crashes with `rsa_compat_build_request': undefined method '[]' for nil:NilClass (NoMethodError)`

### ISSUE THREAD

**Issue by ggiesen** [hashicorp/vagrant#12408]
### Vagrant version

Vagrant 2.2.16

### Host operating system

CentOS Linux release 8.3.2011

### Guest operating system

Cisco IOS-XE 16.09.07

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end
  config.vm.define "router1" do |router1|
    router1.vm.box = "cisco/csr1000v"
    # Turn off shared folders
    router1.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
    # Do not try to insert new SSH key
    router1.ssh.insert_key = false
    # Give the VM time to boot as Vagrant cannot tell when it is booted
    router1.vm.boot_timeout = 900
    router1.vm.network :private_network, virtualbox__intnet: "link1", ip: "192.168.50.21", auto_config: false, nic_type: "virtio"
    router1.vm.network "forwarded_port", guest: 22, host: 20001
    router1.trigger.after :up do |trigger|
      trigger.info = "Configuring interfaces"
      trigger.run = {inline: "./configure_ips.py -P 20001 127.0.0.1"}
    end
  end
```

### Debug output

https://gist.github.com/ggiesen/7d97219467a4ebb3d82899262963eb9a

The Gist contains 3 files:

1. vagrant_up_router1-debug-1.txt - The first time `vagrant up router1` is run
2. vagrant_up_router1-debug-2.txt - The second time `vagrant up router1` is run
3. vagrant_ssh_router1-debug.txt - Then `vagrant ssh router1` is run

### Expected behavior

Bring up box

### Actual behavior

The first time I run `vagrant up router1`, vagrant provisions the VM, and then crashes with the following error:

`/opt/vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/lib/vagrant/patches/net-ssh.rb:10:in `rsa_compat_build_request': undefined method `[]' for nil:NilClass (NoMethodError)`

The VM is left running, however, and I can run `vagrant up router1` a second time and finishes running the trigger. I also encounter no issues using `vagrant ssh router1`

If I use password-based authentication, vagrant does not crash (but I have to log into all devices manually).

### Steps to reproduce

1. Use above Vagrantfile with Cisco CSR1000v box built using https://github.com/hpreston/vagrant_net_prog
2. Run `vagrant up router1`

**Comment by gdams** [comment]
I'm also getting this error and it's driving me crazy

**Comment by gdams** [comment]
This was broken in vagrant 2.2.16, reverting to 2.2.15 fixes this for me
