### ISSUE TITLE
Ansible version compatibility mode detection doesn't work with current ansible versions

### ISSUE THREAD

**Issue by FloSchwalm** [hashicorp/vagrant#12405]
The output format of `ansible --version` changed with https://github.com/ansible/ansible/pull/72287

Version used to be reported as `ansible 2.9.0` etc., now the output is formatted like `ansible [core 2.11.1]`.

Thus the regular expressions to detect ansible version for compatibility mode need to be updated here:
https://github.com/hashicorp/vagrant/blob/9e706d9d4c0d58ff03f3f8bcbd125481b0a66377/plugins/provisioners/ansible/provisioner/base.rb#L384-L396

Note that as of now the `ansible --version` output contains a trailing space, though this may be fixed if https://github.com/ansible/ansible/issues/74875 is resolved.

**Comment by soapy1** [comment]
Hey there, 
thanks for opening up an issue! I believe this has been resolved by https://github.com/hashicorp/vagrant/pull/12391.

**Comment by FloSchwalm** [comment]
> Hey there,
> thanks for opening up an issue! I believe this has been resolved by #12391.

Ah, I see. You're totally right :)
So I only have to wait for the next release version. Thank you!
