### ISSUE TITLE
Vagrant crashes after provisioning when trying to write box metadata to file box_meta

### ISSUE THREAD

**Issue by mmohrwinkel** [hashicorp/vagrant#12407]
### Vagrant version

Vagrant 2.2.14, 2.2.16

### Host operating system

Windows 10

### Guest operating system

Debian 9, Debian 10

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
end
```

### Debug output

https://gist.github.com/mmohrwinkel/774f266ffade8ff04c8eb17c4d49b4de

### Expected behavior

The box should start normally and I should be able to login via vagrant ssh afterwards

### Actual behavior

The box shuts down after all provisioning is done. When vagrant tries to write into the file box_meta, it says it doesn't have the rights to write into the file. The error message thrown is the following, for the full stacktrace please refer to the gist link provided above:

C:/HashiCorp/Vagrant/embedded/gems/2.2.16/gems/vagrant-2.2.16/plugins/commands/up/middleware/store_box_metadata.rb:27:in `initialize': Permission denied @ rb_sysopen - D:/test/.vagrant/machines/default/virtualbox/box_meta (Errno::EACCES)

### Steps to reproduce

1. create new folder on any of my disks or an external drive
2. vagrant init generic/debian10
3. vagrant up

Steps I unsuccessfully tried so far:

- uninstalling vagrant and reinstalling it after rebooting
- uninstalling vagrant, deleting vagrant.d in home folder and reinstalling after rebooting
- uninstalling vagrant, uninstalling ruby, deleting vagrant.d and everything looking remotely like ruby and then reinstalling vagrant after rebooting
- checked file permissions, they are the same on my colleagues machine, where vagrant works just fine
- vagrant may have run once in a shell that had administrative privileges
- please help, I'm desperate

### References

- none I could find unfortunately

**Comment by mmohrwinkel** [comment]
I also tried updating to vagrant 2.2.16, but the error persists

**Comment by mmohrwinkel** [comment]
https://github.com/hashicorp/vagrant/issues/10919 this Issue seems to be somehow related. But as written above, I have already tried removing everythin. I also updated and reinstalled virtualbox. I tried several new folders on different drives all with the same result.

**Comment by mmohrwinkel** [comment]
If I comment out Lines 27-29 in C:\HashiCorp\Vagrant\embedded\gems\2.2.16\gems\vagrant-2.2.16\plugins\commands\up\middleware\store_box_metadata.rb, everything seems to work perfectly.

**Comment by chrisroberts** [comment]
Hi,

The error you are encountering is a permissions error when attempting to write the metadata file. I would suggest first looking at the permissions that are set on machine's data directory (`D:/test/.vagrant/machines/default/virtualbox/` based on your gist) and the inherited permissions as that's most likely the culprit. If the permissions seem fine, validate by writing a file to that location with the system user that is running the Vagrant command.

Cheers!

**Comment by mmohrwinkel** [comment]
Hi Chris,

thank you for answering! The file permissions sadly are fine. I tried writing and deleting files as the same user and had no problem whatsoever. This also happens wherever I create a new folder and initialize it with vagrant init. To make this even more strange, the file in question even existed in some cases and vagrant crashed nevertheless.

I have never seen such behaviour before and it is really puzzling me. Maybe it has to do with the software management the company I work for installs on every machine? I noticed, that while vagrant and virtualbox are not in the managed software catalogue, strangely the virtualbox guest additions are. And around the time my troubles started, It unsuccessfully tried to install an older version of the guest additions than I already had installed. Could that have something to do with my problem?

Greetings,

Max

**Comment by chrisroberts** [comment]
That very well could be the case. You also mentioned that Vagrant may have been run once with elevated privileges. If that was in the `D:\test` directory, you can try deleting the directory and re-creating it as a regular user (which ensure all subdirectories including `D:\test\.vagrant` get recreated) or just a new directory altogether. Otherwise I would assume it's other software interfering with Vagrant as it's attempting to write to disk.

Cheers!

**Comment by mmohrwinkel** [comment]
Hi @chrisroberts sorry for replying so late! I opened a ticket at my company and that went through all the departments which naturally took some time. Apparently this is a rare Windows bug that randomly appears since Vista and just sets the write protect flag on every folder and file and can only be cured by reinstalling Windows. So this is definately not a vagrant issue. Thank you for your support! 

All the best, Max
