### ISSUE TITLE
Ansible version detection doesn't work with current ansible versions

### ISSUE THREAD

**Issue by FloSchwalm** [hashicorp/vagrant#12404]
### Vagrant version
2.2.14

### Host operating system
Ubuntu 20.04.2 LTS

### Guest operating system
Ubuntu 20.04.2 LTS

### Vagrantfile

```ruby
config.vm.provision :ansible do |ansible|
    ansible.version = "[core 2.11.1]"
  end
```

Left out everything not required for this issue.

### Expected behavior

ansible version matches

### Actual behavior

ansible version reported as not matching

### Steps to reproduce

1. Install ansible version that has the bug
2. Specify ansible

### How to fix
This is not necessarily a bug in vagrant, but rather a bug in ansible, check https://github.com/ansible/ansible/issues/74875
However, vagrant's version check for ansible could be made more resilient by adding a whitespace trim here:  
https://github.com/hashicorp/vagrant/blob/9e706d9d4c0d58ff03f3f8bcbd125481b0a66377/plugins/provisioners/ansible/provisioner/host.rb#L110-L132
and here

https://github.com/hashicorp/vagrant/blob/9e706d9d4c0d58ff03f3f8bcbd125481b0a66377/plugins/provisioners/ansible/provisioner/guest.rb#L74-L91

### Workaround in the meantime
When specifying `ansible.version` option, add a trailing space to the version string.

### References
https://github.com/ansible/ansible/issues/74875

**Comment by Akasurde** [comment]
@soapy1 https://github.com/ansible/ansible/issues/74875 is resolved. Do you think this issue is still valid? Thanks

**Comment by FloSchwalm** [comment]
> @soapy1 [ansible/ansible#74875](https://github.com/ansible/ansible/issues/74875) is resolved. Do you think this issue is still valid? Thanks

Since we can't be sure that users always use the latest ansible version (may differ depending on package manager and sometimes you may deliberately stay on a later version if you have to update your playbooks for newer versions) I think a fix for vagrant would still be worthwhile. I can make a PR within the next days.
