### ISSUE TITLE
"vagrant up" SSH Authentication Failure, but "vagrant ssh" Works

### ISSUE THREAD

**Issue by DirectRoot** [hashicorp/vagrant#12418]
### Vagrant version

Vagrant 2.2.16

### Host operating system

macOS BigSur on Apple M1

### Guest operating system

Ubuntu Focal (Docker)

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.name = "cpcm-prometheus"
    d.has_ssh = true
    config.ssh.private_key_path = "./ssh/vagrant.pem"
    config.ssh.username = "root"
  end
end

```

### Dockerfile
```dockerfile
FROM ubuntu:focal

RUN apt update && apt install -y openssh-server \
    vim \
    iproute2 \
    netcat

COPY ssh/demo.conf /etc/ssh/sshd_config.d/
RUN mkdir /root/.ssh
COPY ssh/vagrant.pem.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys

RUN service ssh start
EXPOSE 22

CMD ["/usr/sbin/sshd","-D"]
```

### Debug output

https://gist.github.com/DirectRoot/9f04f9d6f1e295fc214879eb87a3184a

### Expected behavior

`vagrant up` completes

### Actual behavior

`vagrant up` does not complete because of an authentication failure, but when cancelled `vagrant ssh` works. I have also manually used the `ssh` command to connect to the container.

### Steps to reproduce

1. `ssh-keygen -b 4096 -C vagrant -f ./ssh/vagrant.pem`
1. `vagrant up`
2. `Ctrl+c`
3. `vagrant ssh`

### References

Reading through other issues I suspect the problem is with the `net-ssh` library, but I'm not big enough on Ruby to debug.

**Comment by chrisroberts** [comment]
Hi there, thanks for reporting this issue. This has already been reported here: #12344 so I'm going to close this as a duplicate.

Cheers!

**Comment by DirectRoot** [comment]
@chrisroberts you're my hero for responding so quick. I did not correlate these two issues 👍
