### ISSUE TITLE
System freeze approximately 5 minutes after vagrant up

### ISSUE THREAD

**Issue by kerby-dog** [hashicorp/vagrant#12434]
**Vagrant version**

vagrant -v
Vagrant 2.2.16

**Host operating system**

macOS Big Sur
Version 11.4

**Guest operating system**

_[~]$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)_ 

**VirtualBox version 6.1**

**Vagrantfile**

-*- mode: ruby -*-
vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

   we use our own users and folders so don't mount /vagrant!
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.hostname = "dataplan-dev"

  config.vm.provider "virtualbox" do |vb, override|
    vb.name = "dataplan-dev"
    vb.linked_clone = true
    vb.cpus = 2

    USB off
    vb.customize ["modifyvm", :id, "--usb", "off"]
    vb.customize ["modifyvm", :id, "--usbehci", "off"]

    vb.memory = "8192"  

    override.vm.network "private_network", ip: "192.168.2.2"

    override.vm.synced_folder "work", "/home/"+ENV['USER']+"/work", create: true, type:'nfs',
        mount_options: ['rw', 'vers=3', 'tcp'], 
        linux__nfs_options: ['rw','no_subtree_check','all_squash','async']

    override.vm.network "forwarded_port", guest: 8080, host: 8080
  end

  class Password
    def to_s
        print "SMB Password for Windows shared folder. Press enter to skip on Mac: " 
        STDIN.gets.chomp
    end
  end

  config.vm.provider "hyperv" do |h, override|
   override.vm.box = "cdhutch/centos7-cifs-puppet"
   override.vm.network "public_network" # the only option on hyper-v

    h.vmname = "dataplan-dev"

    h.enable_virtualization_extensions = true
    h.vm_integration_services = {
        guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: false
    }

    h.cpus = 2
    h.memory = "2048"
    h.maxmemory = "4096" # running MATE requires a reasonable amount of RAM

    h.differencing_disk = true

    h.auto_start_action = "Nothing"
    h.auto_stop_action = "ShutDown"

    h.mac = "00155D2057DB"

    override.putty.username = ENV['USERNAME']
   override.putty.session = "dataplan-dev"
    override.putty.private_key_path = :agent # key from pagent
  end

  config.vm.provision "shell", name: "bootstrap", path:"setup.sh"
  config.vm.provision "puppet", synced_folder_type:'rsync', run: "always"
  uid = `id -u`
  guid = `id -g`
  config.vm.provision "shell" do|s|
      s.name = "finish"
      s.path = "post-setup.sh"
      s.env = {
        'HOST_USER' => ENV['USERNAME'] || ENV['USER'],
        'HOST_PASS' => Password.new,
        'HOST_UID' => uid,
        'HOST_GUID' => guid,
      }
  end    

end

**Debug output**

https://gist.github.com/kerby-dog/8445c3f36f21e94cf55e518b16d9e887

**Expected behaviour**

What should have happened
_VM should not freeze after about 5 mins._ 

**Actual behaviour**

After 5 mins I cannot type any command e.g.
[~]$ ls -l
nothing happens

**Additional notes**

This all started happening when I was forced to upgrade to Big Sur. This triggered an upgrade of VirtualBox, which in turn mean an upgrade to vagrant. I suspect that because I am using nfs to mount a partition that can be accessible to the host os, things have gone awry.

**Comment by chrisroberts** [comment]
Hi there,

Unfortunately the behavior you are encountering is not something that would be triggered by Vagrant. If the VM itself is becoming unresponsive, that indicates that there is an issue with VirtualBox and it may be related to the VirtualBox installation. Inspecting the VirtualBox logs and/or your system logs to identify any errors or warning that are being logged just before and after the VM has become unresponsive will probably be your best bet on determining a root cause.

Cheers!
