### ISSUE TITLE
Vagrant up get stuck on "Waiting for domain to get an IP address..."

### ISSUE THREAD

**Issue by hayk99** [hashicorp/vagrant#12438]
### Vagrant version

Vagrant 2.2.6

### Host operating system

Ubuntu 20.04.2 LTS

### Guest operating system

Ubuntu server 20.04.2 LTS

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "slurmBoxNew"
end
```

### Debug output

https://gist.github.com/hayk99/c2243cd7c1ec3697486bffac0d0bafc9

### Expected behavior

Box should get up correctly

### Actual behavior

Box get stuck on waiting ip

### Steps to reproduce

1.Vagrant up --provider=libvirt

###Aditional Info
This box was created from virt-manager VM which works properly and it starts up correctly

**Comment by chrisroberts** [comment]
Hi there,

The libvirt plugin is supported here: https://github.com/vagrant-libvirt/vagrant-libvirt

The README there has instructions on creating boxes, and troubleshooting steps to take when a box is not working correctly. 

Cheers!
