### ISSUE TITLE
Hyper-V support

### ISSUE THREAD

**Issue by Iristyle** [hashicorp/vagrant#1244]
I see an issue for [VMWare here](https://github.com/mitchellh/vagrant/issues/605).. but I don't see any mention of Hyper-V.

I see the list mentioned in the blog post [here](http://www.hashicorp.com/blog/announcing-hashicorp.html) as well...  but also no Hyper-V.

Hyper-V support would be great to see on the roadmap.

**Comment by brizzbane** [comment]
Does this for sure not work on windows server 2008 R2?  Have been using Hyper-V with windows servers for quite a while, and really wanted to start using Hyper-V.

Windows 8.1 is only version of windows that works, or will later windows server versions work?

It's hanging at checking for hyper-v for me (Windows 2008 R2 Standard)
