### ISSUE TITLE
conflicting dependencies net-ssh (= 6.1.0) and net-ssh (= 6.2.0.rc1)

### ISSUE THREAD

**Issue by rekcus2** [hashicorp/vagrant#12441]
How do I find out if [the patch](https://github.com/hashicorp/vagrant/pull/12213) has landed on a version that landed on Tumbleweed? It was merged long ago all the issues get bot closed, https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1210#issuecomment-789552251 sounds like its NOT fixed, yet he closed his issue, I do not get it. This is going on for weeks now, I tried deleting vagrant.d ... these vagrant and virtualbox issues will probably make me go back to Ubuntu again as they keep coming up again and again.

### Vagrant version

vagrant-2.2.16-1.1.x86_64
vagrant -v
Vagrant 2.2.16

### Host operating system

Open Suse Tumbleweed.

### Guest operating system

Ubuntu 20.04

### Steps to reproduce

```
vagrant up
Installing plugin vagrant-bindfs
Vagrant failed to initialize at a very early stage:

Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies net-ssh (= 6.1.0) and net-ssh (= 6.2.0.rc1)
  Activated net-ssh-6.2.0.rc1
  which does not match conflicting dependency (= 6.1.0)

  Conflicting dependency chains:
    net-ssh (= 6.2.0.rc1), 6.2.0.rc1 activated

  versus:
    net-ssh (= 6.1.0)

  Gems matching net-ssh (= 6.1.0):
    net-ssh-6.1.0
```

**Comment by chrisroberts** [comment]
The last two releases patch the net-ssh library dynamically and do not rely on the prerelease version so this error should be resolved. Cheers!
