### ISSUE TITLE
Vagrant 2.2.17 upgrade from Ruby 2.6.7 to 3.0.1 broke vagrant-libvirt

### ISSUE THREAD

**Issue by rgl** [hashicorp/vagrant#12445]
Vagrant 2.2.17 upgraded Ruby 2.6.7 to 3.0.1 and this brake [the vagrant-libvirt provider](https://github.com/vagrant-libvirt/vagrant-libvirt) because it depends on the [libvirt-ruby](https://gitlab.com/libvirt/libvirt-ruby), which has a native extension, which now fails to build.

Does it make sense that the Vagrant release process would also build/smoke-test popular providers before making a release?

Or/and maybe coordinate the upgrades with those authors?

For reference, this is the last bit of the build failure:

```
checking for libvirt/libvirt-lxc.h... yes
checking for virDomainLxcOpenNamespace() in -lvirt-lxc... yes
checking for virDomainLxcOpenNamespace() in libvirt/libvirt-lxc.h... yes
checking for virDomainLxcEnterNamespace() in libvirt/libvirt-lxc.h... yes
checking for virDomainLxcEnterSecurityLabel() in libvirt/libvirt-lxc.h... yes
creating extconf.h
creating Makefile

current directory: /home/rgl/.vagrant.d/gems/3.0.1/gems/ruby-libvirt-0.7.1/ext/libvirt
make DESTDIR\= clean

current directory: /home/rgl/.vagrant.d/gems/3.0.1/gems/ruby-libvirt-0.7.1/ext/libvirt
make DESTDIR\=
compiling _libvirt.c
compiling common.c
common.c:27:10: fatal error: st.h: No such file or directory
   27 | #include <st.h>
      |          ^~~~~~
compilation terminated.
make: *** [Makefile:245: common.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/rgl/.vagrant.d/gems/3.0.1/gems/ruby-libvirt-0.7.1 for inspection.
Results logged to /home/rgl/.vagrant.d/gems/3.0.1/extensions/x86_64-linux/3.0.0/ruby-libvirt-0.7.1/gem_make.out
```

**Comment by rgl** [comment]
This seems related to https://github.com/vagrant-libvirt/vagrant-libvirt/issues/1269.

**Comment by AntonioMeireles** [comment]
HOTFIX bellow.

```
sudo ln -s /opt/vagrant/embedded/include/ruby-3.0.0/ruby/st.h /opt/vagrant/embedded/include/ruby-3.0.0/st.h
```

woreks as is above uncer MacOS. under other OSs you may need to adapt paths.

**Comment by AntonioMeireles** [comment]
@chrisroberts 

**PLEASE** consider re-releasing latest version with the fix above. IMHO latest couple vagrant releases are severely eroding Vagrant's credibility in the field. 2nd release in a row that broke all vagrant workflows here (at least this one is trivial to fix without reverting to 2.2.15) 

António

**Comment by chrisroberts** [comment]
Hi @rgl, thanks for reporting the issue! It's unfortunate that a fix has landed upstream that hasn't yet been released. There's no need for symlinking files to modify the installation structure to get a successful compilation. Just adding the directory to the cflags will get the desired result:

```
vagrant@vagrant:~$ CFLAGS="-I/opt/vagrant/embedded/include/ruby-3.0.0/ruby" vagrant plugin install vagrant-libvirt
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Building native extensions. This could take a while...
Fetching formatador-0.3.0.gem
Fetching fog-core-2.2.4.gem
Fetching fog-xml-0.1.3.gem
Fetching fog-json-1.2.0.gem
Fetching fog-libvirt-0.8.0.gem
Fetching vagrant-libvirt-0.5.3.gem
Installed the plugin 'vagrant-libvirt (0.5.3)'!
vagrant@vagrant:~$
```

We'll run some tests to determine if we can drop this modification directly into the launcher's env setup without any unexpected side effects, and if so will push out a patch release with the update.

**Comment by rgl** [comment]
@chrisroberts thank you! I'ts working nicely!

I will test this again when vagrant is pre-released.

**Comment by muratcabuk** [comment]
> HOTFIX bellow.
> 
> ```shell
> sudo ln -s /opt/vagrant/embedded/include/ruby-3.0.0/ruby/st.h /opt/vagrant/embedded/include/ruby-3.0.0/st.h
> ```
> 
> works as is above uncer MacOS. under other OSs you may need to adapt paths.
> 
> after this `vagrant plugin install vagrant-libvirt` builds smoothly as it should.

it works on ubuntu 21.04

**Comment by rgl** [comment]
Just tried 2.2.18 and this now works out of the box. Thank you!
