### ISSUE TITLE
rabbitmqctl status error from >=2.2.10

### ISSUE THREAD

**Issue by LukasJerabek** [hashicorp/vagrant#12450]
### Vagrant version

Does now work on versions 2.2.10-2.2.16, works on versions 2.2.7-2.2.9

### Host operating system

Centos stream (colleague has same issue on Ubuntu, other on Void and other on MacOS)

### Guest operating system

Centos7

### Vagrantfile

```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos7"
  config.vm.box_check_update = true
  config.vm.hostname = "devcentos7"
  config.vm.network "private_network", ip: "192.168.56.110"
  config.vm.synced_folder "../../../rss", "/home/vagrant/repo/rss",
    mount_options: ["rw"], SharedFoldersEnableSymlinksCreate: false
  config.vm.define "devcentos7"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "devcentos7"
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 1
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: 'ssh'
  config.ssh.extra_args = ["-L", "8000:localhost:8000"]
  end
end
```

### Debug output

https://gist.github.com/LukasJerabek/2b016c3cd60ac6afe629dbf045094eec

### Expected behavior

sudo rabbitmqctl status should not throw error

### Actual behavior
if I issue `$ sudo rabbitmqctl status`
```
Error: unable to perform an operation on node 'rabbit@devcentos7'. Please see diagnostics information and suggestions below.

Most common reasons for this are:

 * Target node is unreachable (e.g. due to hostname resolution, TCP connection or firewall issues)
 * CLI tool fails to authenticate with the server (e.g. due to CLI tool's Erlang cookie not matching that of the server)
 * Target node is not running

In addition to the diagnostics info below:

 * See the CLI, clustering and networking guides on https://rabbitmq.com/documentation.html to learn more
 * Consult server logs on node rabbit@devcentos7
 * If target node is configured to use long node names, don't forget to use --longnames with CLI tools

DIAGNOSTICS
===========

attempted to contact: [rabbit@devcentos7]

rabbit@devcentos7:
  * connected to epmd (port 4369) on devcentos7
  * epmd reports node 'rabbit' uses port 25672 for inter-node and CLI tool traffic 
  * can't establish TCP connection to the target node, reason: econnrefused (connection refused)
  * suggestion: check if host 'devcentos7' resolves, is reachable and ports 25672, 4369 are not blocked by firewall

Current node details:
 * node name: 'rabbitmqcli-329-rabbit@devcentos7'
 * effective user's home directory: /var/lib/rabbitmq
 * Erlang cookie hash: wyGYBpmlFk6oRdIR/pjOcg==
```

### Steps to reproduce

1. `vagrant up && vagrant ssh`
2. `sudo yum install dnf`
3. `sudo dnf upgrade`
4. create rabbitmq-server repository by `sudo vim /etc/yum.repos.d/rabbitmq.repo` and insert:
> [rabbitmq_rabbitmq-server]
> name=rabbitmq_rabbitmq-server
> baseurl=https://packagecloud.io/rabbitmq/rabbitmq-server/el/7/$basearch
> repo_gpgcheck=1
> gpgcheck=0
> enabled=1
> gpgkey=https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
> sslverify=1
> sslcacert=/etc/pki/tls/certs/ca-bundle.crt
> metadata_expire=300

5. create erlang repository `sudo vim /etc/yum.repos.d/rabbitmq_erlang.repo` and insert:
> [rabbitmq_erlang]
> name=rabbitmq_erlang
> baseurl=https://packagecloud.io/rabbitmq/erlang/el/7/$basearch
> repo_gpgcheck=1
> gpgcheck=0
> enabled=1
> gpgkey=https://packagecloud.io/rabbitmq/erlang/gpgkey
> sslverify=1
> sslcacert=/etc/pki/tls/certs/ca-bundle.crt
> metadata_expire=300
6. mod of previous two files should be 0644
7. `sudo dnf install rabbitmq-server` (you should get the 3.8.19 version)
8. Next you are gonna need to create these three files, all in /etc/rabbitmq/
rabbitmq-env.conf:
```
# Note that the variables do not have the RABBITMQ_ prefix.

NODE_IP_ADDRESS=127.0.0.1

# Specifies new style config file location
CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf

# Specifies advanced config file location
ADVANCED_CONFIG_FILE=/etc/rabbitmq/advanced.config
```
rabbitmq.conf:
```
listeners.tcp.local = 127.0.0.1:5672
num_acceptors.tcp = 10
reverse_dns_lookups = true
loopback_users.admin = true
loopback_users.eps = true
password_hashing_module = rabbit_password_hashing_sha256
heartbeat = 60
vm_memory_high_watermark.relative = 0.4
vm_memory_high_watermark_paging_ratio = 0.5
disk_free_limit.absolute = 50mb
management.http_log_dir = /var/log/rabbitmq/mgmt-http-access.log
management.listener.port = 15672
management.listener.ip   = 127.0.0.1
log.dir = /var/log/rabbitmq
log.file = rabbit.log
log.file.level = info
log.console = false
```
advanced.config:
```
[
 {kernel, [{inet_dist_use_interface,{127,0,0,1}}]},
 {rabbitmq_shovel, [{shovels,[]}]},
 {rabbitmq_auth_backend_ldap, []}
].
```
8. `sudo systemctl enable rabbitmq-server`
9. `sudo systemctl start rabbitmq-server`
10. now I get error if I issue `sudo rabbitmqctl status` specified in "Actual behaviour" section. **The obvious problem is in advanced.config. Somehow, new vagrant version cant handle it. If I remove advanced.config and referation variable from rabbitmq-env.conf it suddenly works. If I remove only the kernel line, it works also - so that is the core problem** 
11. if you dont get the error, try `sudo systemctl restart rabbitmq-server`

**Comment by LukasJerabek** [comment]
### Update:
## before removing "kernel line" from advanced.config - which **fails**
`$ sudo netstat -uptan | grep beam`
```
tcp        0      0 127.0.0.1:5672          0.0.0.0:*               LISTEN      28839/beam.smp      
tcp        0      0 127.0.0.1:25672         0.0.0.0:*               LISTEN      28839/beam.smp      
tcp        0      0 127.0.0.1:46113         127.0.0.1:4369          ESTABLISHED 28839/beam.smp   
```   
## after removing "kernel line" from advanced.config - which **works**
`$ sudo netstat -uptan | grep beam`
```
tcp        0      0 127.0.0.1:5672          0.0.0.0:*               LISTEN      29181/beam.smp      
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      29181/beam.smp      
tcp        0      0 127.0.0.1:37757         127.0.0.1:4369          ESTABLISHED 29181/beam.smp  
```
but if I ping devcentos I get:
`$ ping devcentos7`
```
PING devcentos7 (127.0.1.1) 56(84) bytes of data.
64 bytes from devcentos7 (127.0.1.1): icmp_seq=1 ttl=64 time=0.043 ms
64 bytes from devcentos7 (127.0.1.1): icmp_seq=2 ttl=64 time=0.075 ms
```

After reading this:
[127.0.1.1 reasoning](https://serverfault.com/questions/363095/why-does-my-hostname-appear-with-the-address-127-0-1-1-rather-than-127-0-0-1-in)
I have changed /etc/hosts from
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

127.0.0.1 centos7.localdomain
127.0.1.1 devcentos7 devcentos7
```
to:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 devcentos7
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 devcentos7

127.0.0.1 centos7.localdomain
```
And it worked. But I dont thing this is the correct way. Obviously this `sudo rabbitmqctl status` command works on our production server and should also in VM without having to change the original /etc/hosts file, If newer version of vagrant supresses it, I consider it a bug. Previously 127.0.0.1 was probably interchangeable with

**Comment by chrisroberts** [comment]
Hi there,

The updates to Vagrant's behavior for `/etc/hosts` modifications can be found in the original issue the work was based upon: hashicorp/vagrant#11508

There are different opinions on the "correct" setup/behavior and what is described in that issue is what we landed on for default behavior that was the least likely to result in unexpected issues and provided enough flexibility for users to do something different if they so desired.

For the behavior you are describing in your issue, it sounds like you will likely want to disable `/etc/hosts` file modifications using the [`allow_hosts_modification`](https://www.vagrantup.com/docs/vagrantfile/machine_settings#config-vm-allow_hosts_modification) option. With Vagrant no modifying that file, a shell provisioner can be defined to update your `/etc/hosts` file in the specific way you expect.

Cheers!
