### ISSUE TITLE
SSH fails to initialize after installing ufw on generic/debian10

### ISSUE THREAD

**Issue by tmmagee** [hashicorp/vagrant#12465]
### Vagrant version

Vagrant 2.2.16

### Host operating system

Windows 10. But for what it is worth I was using cygwin when running all commands. However, vagrant was installed through Windows.

### Guest operating system

Debian 10

### Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
end

### Debug output

https://gist.github.com/tmmagee/c12e63a43f7ea6ffda47b37343ff641b

### Expected behavior

I did a vagrant up of a generic debian10 box. 
I installed ufw and enabled it on the virtual machine. 
After enabling ufw, I expect vagrant up and vagrant halt to be able to use ssh to access the virtual machine from the host machine.

### Actual behavior

After installing and enabling ufw on the virtual machine, the virtual machine cannot be accessed through ssh. Vagrant up hangs, and vagrant halt (when the machine is up) is forced to shut down the machine without gracefully shutting it down through ssh.

### Steps to reproduce

1. vagrant up (debian buster virtual machine)
2. vagrant ssh into machine
3. (in the virtual machine) sudo apt install ufw
4. (in the virtual machine) sudo ufw enable
5. Ctrl-d to logout of virtual machine
6. (in host machine) vagrant halt - Vagrant will not be able to contact the machine through ssh and will have to force it to shutdown
7. (in host machine) vagrant up - Vagrant will hang while trying to setup ssh. No error message is given.

It appears clear that enabling ufw on a base install of Debian 10 kills the ability to communicate with the box through ssh. I am assuming that it is simply a matter of updated the firewall rules, but vagrant should handle the issue more gracefully.

**Comment by tmmagee** [comment]
I should add that I resolved the issue by starting up the virtual machine through VirtualBox, logging in as vagrant, and then executing "sudo ufw disable." After disabling ufw, vagrant up and vagrant halt once again could access the guest machine through ssh.

**Comment by chrisroberts** [comment]
This is the expected behavior when enabling ufw. Vagrant expects to be able to establish a connection to the guest and enabling ufw makes that not possible. The solution for this problem is to either not enable ufw, or to configure rules to allow ssh connections before enabling it.

Cheers
