### ISSUE TITLE
Windows 11 - VBoxManage.exe: error: Failed to get device handle and/or partition 

### ISSUE THREAD

**Issue by andreasrosdal** [hashicorp/vagrant#12471]
Vagrant with VirtualBox doesn't work on Windows 11., when Hyper-V is enabled.

Vagrant version 2.2.17_x86_64
VirtualBox version 6.1.24-145767-Win

https://github.com/Lexxie9952/fcw.org-server/blob/master/Vagrantfile

This is the console output from 'vagrant up':

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "c695fe19-58c7-4be6-8f5a-9d6f55fc6b70", "--type", "headless"]

Stderr: VBoxManage.exe: error: Failed to get device handle and/or partition ID for 00000000018dfd50 (hPartitionDevice=0000000000000a51, Last=0xc0000002/1) (VERR_NEM_VM_CREATE_FAILED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by andreasrosdal** [comment]
A workaround fix for this is to disable Hyper-V as described here:
https://forums.virtualbox.org/viewtopic.php?f=25&t=99390

**Comment by chrisroberts** [comment]
Hi there. The error you are encountering is not a Vagrant specific error, and is related to the system setup with VirtualBox and Hyper-V. However, VirtualBox can be configured to use Hyper-V as the virtualization engine so VirtualBox can run with Hyper-V enabled, but the feature is still listed as experimental.

Cheers
