### ISSUE TITLE
Add Astra Linux platforms guest detection and support

### ISSUE THREAD

**Issue by astralnx** [hashicorp/vagrant#12475]
Hi! These changes are necessary for correct work with Astra Linux images hosted on Vagrantcloud. What should I do to have my pool request accepted?
https://github.com/hashicorp/vagrant/pull/12460

Thank you.

**Comment by soapy1** [comment]
Hey there,
I just respond to this over at: https://github.com/hashicorp/vagrant/pull/12460#issuecomment-888409370.
I'm going to go ahead and close this issue now. 
Cheers
