### ISSUE TITLE
Support BitTorrent for adding boxes

### ISSUE THREAD

**Issue by sferik** [hashicorp/vagrant#1248]
Downloading boxes is slow. It could be faster if Vagrant supported BitTorrent.

**Comment by v6** [comment]
// , Mitchell obviously knows the direction he wants Vagrant to take, but for what it's worth, I, personally, feel like optional torrent use would be in keeping with the "batteries included" approach Vagrant and Atlas usually take with box management. 

Perhaps this could be a "pro" plugin for paid Atlas users?

On the one hand, it brings in revenue, and on the other hand, it limits (for now) the amount of support necessary.

**Comment by v6** [comment]
// , Plus, torrents iz kew.

**Comment by faddat** [comment]
Forget the plus, torrents iz kew.... well, except they are.  Mitchell, you've clearly not been to some of the more bandwidth constrained places on the planet.  

It's not really "as fast as my network connection can allow" if traffic gets slaughtered at the border of a country I'm in, now is it?  plus, yay resilience and making your tool more robust.  

Bittorrent support for vagrant is a great idea, and really, should be baked into anything that downloads large files routinely.

**Comment by wkretzsch** [comment]
+1

**Comment by timcharper** [comment]
Not supporting bittorrent for this action is a tremendous lost opportunity. Bandwidth can't be free for hashicorp.

**Comment by faddat** [comment]
![screenshot from 2016-03-17 14-03-16](https://cloud.githubusercontent.com/assets/7142025/13838839/9cd85964-ec49-11e5-8635-dc1012d1cd13.png)

what would / could fix this situation, I wonder?

**Comment by eisnerd** [comment]
I was really surprised to find that there's no built in p2p/torrenting in a modern tool used for downloading massive files. Even in our fairly well connected office, having a whole team cURL a 1GB image simultaneously would be a bit obnoxious. Workarounds with `vagrant box add` really spoil the experience. Most of the team, not being vagrant evangelists, will be wondering why they didn't just torrent the ISOs and set up a VM in their tried and tested way.

**Comment by v6** [comment]
// , Well, I guess there's always room for someone to develop a plugin to support torrent magnet links in the value for `vagrantfile config.vm.box_url`.

**Comment by v6** [comment]
@eisnerd, if an image gets frequent usage, there's always artifactory or something for storing images on the local network.

**Comment by bradisbell** [comment]
@mitchellh Please consider revisiting this issue.  Hashicorp's hosting is not sufficient.

```
    default: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20160509.1.0/providers/virtualbox.box
    default: Progress: 10% (Rate: 45088/s, Estimated time remaining: 2:08:43)
```

This is a typical experience for me, on various networks, even in various cities.  I'm able to download from the rest of the internet fine.  SpeedTest.net typically reports download speeds of 100+ mbit.

There are command line tools available for torrents.  If you don't want to bundle one with Vagrant, perhaps there could be an option for a user to specify their own tool for downloading torrents?  Then Vagrant Cloud could store Magent URIs, allowing the client to decide whether to use HTTPS or BitTorrent for the download.

**Comment by faddat** [comment]
Or, the metalink protocol, which combines bittorrent, HTTP and FTP.

**Comment by gschwarz** [comment]
Adding torrent support for downloading images sounds like a terrific idea, and that is exactly what I would need to make some presentation where everyone can follow instructions and hopefully download something from my machine by simply typing "vagrant up".

How to do this exactly?

One possibility would be that you are serving files from all computers which have vagrant installed, but that would be very bad for people who once installed vagrant and then begun unknowingly serving files for the rest of their life... people would complain that it looks like a virus.

Another possibility would be that yu have to explcitly type:

vagrant serve

or something like that to serve files on the internet, so that you know exactly when you are serving files.

**Comment by DirtyB** [comment]
@gschwarz is right about the question of how to make users serve boxes. If it would be downloaded on vagrant up it would never be served,

I think it would be just great to have ability to download image via torrent client and manually add it to Vagrant as alternative way if regular download is too slow.

**Comment by rogue780** [comment]
+1 This would be amazingly helpful

**Comment by lucascdsilva** [comment]
+1

**Comment by mcandre** [comment]
+1

**Comment by poige** [comment]
What about allowing _external URLs to be magnet links_?

Even if you guys (at Hashicorp) don't want to host a tracker, it still can be useful a lot!
