### ISSUE TITLE
vagrant ssh does not work on Windows if spaces in path

### ISSUE THREAD

**Issue by pszlazak** [hashicorp/vagrant#12488]
## Description

If Vagrant machine is located in directory where space(s) is in the path, Vagrant fails to set permissions for generated SSH private key.

### Vagrant version

`Vagrant 2.2.16`

### Host operating system

`Windows 10, Version 21H1 (OS build 19043.1023)`

### Guest operating system

N/A

### Vagrantfile

N/A

### Debug output

N/A

### Expected behavior

Successful login to guest machine.

### Actual behavior

Login does not work due to wrong permissions:
```
PS D:\Vagrant Machines\debian_buster64> vagrant ssh
vagrant@127.0.0.1: Permission denied (publickey).
```

### Steps to reproduce

1. Create machine in the place where you have space(s) in the path.
2. Try to login using `vagrant ssh`.

### References

Pull Request with fix for the problem: #12398

**Comment by chrisroberts** [comment]
PR merged, thanks!
