### ISSUE TITLE
Incorrect checksum for 2.2.18 x64 msi

### ISSUE THREAD

**Issue by Pyker** [hashicorp/vagrant#12486]
### Vagrant version
2.2.18

The checksum of `aed44d72e72d2183354c7e2e0f6118e289becba0491a67eb2e5551701b70d359` mentioned in https://releases.hashicorp.com/vagrant/2.2.18/vagrant_2.2.18_SHA256SUMS for `vagrant_2.2.18_x86_64.msi` is wrong.

The current checksum is `8ce913bee9debcbf39f313f4255e56f37dac5281cd62458c0c0040e5c76ee93e`, and it appears the binary was signed only 2 days ago (August 2nd), despite the release having happened 7 days ago? Was there a re-release for this particular file?

**Comment by chrisroberts** [comment]
Hi there,

I am currently seeing the correct checksum when fetching the shasums file:

```
❯ curl -s https://releases.hashicorp.com/vagrant/2.2.18/vagrant_2.2.18_SHA256SUMS | grep vagrant_2.2.18_x86_64.msi
8ce913bee9debcbf39f313f4255e56f37dac5281cd62458c0c0040e5c76ee93e  vagrant_2.2.18_x86_64.msi
```

There was a re-release for both the Windows packages due to an issue with the installer that would result in a broken installation when upgrading (#12476).

Is the shasums file a copy you downloaded recently?

**Comment by Pyker** [comment]
Ok, that's weird. I tried running the exact same command you ran there and got the same result as you. Then I tried downloading it from the link at https://www.vagrantup.com/downloads and I get the wrong checksum again.

**Comment by Pyker** [comment]
As an example, the response in Firefox: 
![image](https://user-images.githubusercontent.com/528849/128174401-458c72f0-68b1-4e11-9437-02098885d3b9.png)

And the exact same request in curl (via Copy -> Copy as cURL (POSIX) in Firefox dev tools):
![image](https://user-images.githubusercontent.com/528849/128174552-944d2365-474f-465a-a6a7-49ba762ac816.png)

**Comment by chrisroberts** [comment]
I'm guessing there must be a caching issue happening some where here. Pulling the file down using Firefox locally also results in the expected values:

![screenshot](https://user-images.githubusercontent.com/266674/128198446-5f0a1ce8-3995-431f-9940-dc40bf10c475.png)

Are you running on a corporate network or do you have any proxy configuration defined (either in your browser configurations or globally for the entire system)?

**Comment by Pyker** [comment]
Not in a corporate network, no proxies whatsoever. Tried it out in a Tails VM as well, got the same (wrong) result. Could be it some weird CDN caching?

**Comment by chrisroberts** [comment]
Interesting, thanks for the information and for going the extra step to check in an isolated VM. Investigating on the CDN side now and will let you know if I find anything there.

**Comment by StudioMaX** [comment]
Found this because the old checksum was specified in the [Chocolatey package](https://community.chocolatey.org/packages/vagrant), because of this it was impossible to update it. In my opinion, the most correct way is to release a new version 2.2.19, or 2.2.18.1, precisely because of corporate caches and because various content providers have already picked up the old checksum. Maybe it doesn't even make sense to release this new version for various Linux repositories, but only for Windows.

**Comment by chrisroberts** [comment]
@StudioMaX Yes, I agree on the "most correct" way, that being the ability to release a 2.2.18-1 release. However, our release setup does not currently support that, and the original Windows MSI would leave upgraded systems in a broken state. I believe the ability is on the roadmap in the future, but is not something that is currently available. The issue only affected the Windows packages as it was a Windows Installer issue specifically. 

@Pyker After investigating on the CDN side we were able to determine that there was some weirdness with the shasums file. While I was receiving the correct file locally, we were able to verify the old version was being served on a different network. The file has been flushed and reloaded. We are seeing the correct file being served now. Would you mind verifying that you are seeing the correct shasums file now too?

Thanks!

**Comment by Pyker** [comment]
> Found this because the old checksum was specified in the [Chocolatey package](https://community.chocolatey.org/packages/vagrant), because of this it was impossible to update it.

@StudioMaX FWIW, I also ran into that issue. I also ran into the issue with the previous installer (#12476), and I got confused when I tried to reinstall and ran into the hash mismatch. You can simply specify the correct hashes until it's updated in the Chocolatey package:

```
choco install vagrant --checksum 8a82e4185aab1bc801d0ddfeee1ee7a64931500df0151a8048cbad32e467a89c --checksum64 8ce913bee9debcbf39f313f4255e56f37dac5281cd62458c0c0040e5c76ee93e
```

**Comment by Pyker** [comment]
> @Pyker After investigating on the CDN side we were able to determine that there was some weirdness with the shasums file. While I was receiving the correct file locally, we were able to verify the old version was being served on a different network. The file has been flushed and reloaded. We are seeing the correct file being served now. Would you mind verifying that you are seeing the correct shasums file now too?

I'm indeed seeing the correct file now! Thank you :)
