### ISSUE TITLE
Vagrant/windows errors with "could not detect virtualbox" when using hyperv

### ISSUE THREAD

**Issue by derekwbrown** [hashicorp/vagrant#12483]
### Vagrant version

2.2.18

### Host operating system

Windows 10 21h1

### Guest operating system

All

### Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.box_version = "202005.21.0"### Debug output
end
```
https://gist.github.com/derekwbrown/4da92249aca490c37495dc06c918b2a5

### Expected behavior

box should have started

### Actual behavior

failed

### Steps to reproduce

1. install latest vagrant on windows 10 
2. enable hyperv
3. attempt to start box with hyper-v support.

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment]
Hi there,

The error you are encountering is due to the `vagrant-disksize` plugin you have installed. Uninstalling that plugin will resolve the error.

Cheers

**Comment by derekwbrown** [comment]
Thank you for the prompt reply. 
We have a vagrantfile that's cross-platform (want to use it on windows with hyperv and, for example, linux & macos with vbox).  Our vagrantfile uses `vagrant-disksize`.  I can conditionally remove it I suppose, but ideally it'd just be the same everywhere.

Where would be the appropriate place to file an issue against the `vagrant-disksize` plugin, and what additional information could I provide?

**Comment by chrisroberts** [comment]
It looks like an issue has already been filed about this but has received no reply: sprotheroe/vagrant-disksize#45

Conditionally using it would likely be the only resolution in its current state. Isolating the configuration within a provider block and having the plugin configured as a local plugin only within a provider block (provider block for virtualbox) should allow things to work as expected when virtualbox is unavailable.

Other options could be to just install virtualbox but not use it (though I'm not familiar enough with the plugin to know if it will attempt virtualbox specific modifications even if not using the virtualbox provider). This would allow the vboxmanage.exe file to be found and executed during the provider detection phase (which is where it's failing now). Another option could be to enable experimental hyper-v support for virtualbox and just use the virtualbox interface to interact with hyperv. 

The provider configuration block based approach will probably be the easiest and least amount of friction for other users, but just wanted to note some other options that may work too.

Cheers!
