### ISSUE TITLE
vm: * The following settings shouldn't exist: disk

### ISSUE THREAD

**Issue by schulzalbrecht** [hashicorp/vagrant#12480]
## Background

My vagrant file is:
```
Vagrant.configure "2" do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.hostname = "lvm"
    3.times {|i| config.vm.disk :disk, size: "5GB", name: "drive-#{i}"}
    config.vm.provider :virtualbox do |machine|
        machine.memory = 1024
        machine.cpus = 1
        machine.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end
end

# vi: set ft=ruby
```

My OS Host is Ubuntu 20.04

## Error
when I run `$ vagrant up`, I get the below error message:

```
==> vagrant: You have requested to enabled the experimental flag with the following features:
==> vagrant: 
==> vagrant: Features:  disks
==> vagrant: 
==> vagrant: Please use with caution, as some of the features may not be fully
==> vagrant: functional yet.
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The following settings shouldn't exist: disk
```

## Notes
I couldn't find any solution on stackoverflow and the code looks fine according to the documentation. It seems to me that's a bug, reason I'm opening the issue here. 

Thank you.

**Comment by chrisroberts** [comment]
Hi there,

This feature is still in classified as [experimental](https://www.vagrantup.com/docs/experimental) and is not enabled by default. Setting the `VAGRANT_EXPERIMENTAL` environment variable to `disks` will resolve the error you are encountering. You can either export it to make it permanent (`export VAGRANT_EXPERIMENTAL="disks"`) or you can call the command with it set (`VAGRANT_EXPERIMENTAL="disks" vagrant up`).

Cheers!
