### ISSUE TITLE
vagrant up failed Invalid: sshfs (RuntimeError)

### ISSUE THREAD

**Issue by sjstoelting** [hashicorp/vagrant#12491]
### Vagrant version

2.2.18

### Host operating system

Ubuntu Focal

### Guest operating system

CentOS 7

### Vagrantfile

```ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
# General Vagrant VM configuration.
# config.vm.box = "ansible.box"
config.ssh.insert_key = false
config.vm.synced_folder ".", "/vagrant", disabled: true
config.vm.provider :virtualbox do |v|
v.memory = 512
v.linked_clone = true
end

# Ansible Controller
config.vm.define "controller" do |controller|
controller.vm.box = "centos/7"
controller.vm.hostname = "controller.test"
controller.vm.network :private_network, ip: "192.168.60.4"
controller.vm.synced_folder "/home/stefanie/mountpoint/", "/home/vagrant/ansible", type: "sshfs"
end
end
```

### Debug output

https://gist.github.com/sjstoelting/0d8c52ac93b3b3bf4c12289c82baebfe

### Expected behavior

Vagrant should have initialized the machine. 

### Actual behavior

/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builtin/mixin_synced_folders.rb:140:in `block in synced_folders': Internal error. Report this as a bug. Invalid: sshfs (RuntimeError)

### Steps to reproduce

1. vagrant init
2. vagrant box add "centos/7"
3. vagrant up

**Comment by chrisroberts** [comment]
Hi there,

It appears that you are attempting to use `sshfs` as the synced folder type. This synced folder type is not a builtin type supported by Vagrant, rather it is a third party plugin. You'll need to install the plugin for it to work:

```
vagrant plugin install vagrant-sshfs
```

Cheers!

**Comment by sjstoelting** [comment]
Hi @chrisroberts,
Thanks for the reply, but that extension has been installed, version number is 1.3.1-1.
The error occurred while this extension was present.

Cheers,
Stefanie

`
vagrant-sshfs ist schon die neueste Version (1.3.1-1).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
`

**Comment by chrisroberts** [comment]
@sjstoelting Based on the output of the debug log it does not appear that the plugin has been installed. Plugins for Vagrant must be installed via the `vagrant` command, and not the `gem` command (nor via a system package manager).

**Comment by sjstoelting** [comment]
@chrisroberts Thanks for your patience. I didn't know, that it has it's own package management, was following a tutorial where sshfs has been introduced. But obviously without the proper installation path.

But after
`
sudo vagrant plugin install sshfs
vagrant up
`
I still get an error.
`
	33: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	32: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine.rb:201:in `action'
	31: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine.rb:201:in `call'
	30: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:614:in `lock'
	29: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine.rb:215:in `block in action'
	28: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine.rb:246:in `action_raw'
	27: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `run'
	26: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/util/busy.rb:19:in `busy'
	25: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `block in run'
	24: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builder.rb:149:in `call'
	23: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	22: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	21: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	20: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builtin/call.rb:53:in `call'
	19: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `run'
	18: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/util/busy.rb:19:in `busy'
	17: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:89:in `block in run'
	16: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builder.rb:149:in `call'
	15: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	14: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	13: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	12: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	11: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	10: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	 9: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/warden.rb:48:in `call'
	 8: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builtin/config_validate.rb:15:in `call'
	 7: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/config/v2/root.rb:66:in `validate'
	 6: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/config/v2/root.rb:66:in `each'
	 5: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/config/v2/root.rb:71:in `block in validate'
	 4: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/plugins/kernel_v2/config/vm.rb:730:in `validate'
	 3: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine.rb:631:in `synced_folders'
	 2: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builtin/mixin_synced_folders.rb:128:in `synced_folders'
	 1: from /opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builtin/mixin_synced_folders.rb:128:in `each'
/opt/vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/builtin/mixin_synced_folders.rb:140:in `block in synced_folders': Internal error. Report this as a bug. Invalid: sshfs (RuntimeError)
`

**Comment by sjstoelting** [comment]
I solved this, seems I installed the wrong sshfs package.

The package **sshfs** comes in version 0.0.2 and is definitely not working!

Instead use the package **vagrant-sshfs**, documentation can be found here: https://github.com/dustymabe/vagrant-sshfs
