### ISSUE TITLE
Configuring grub-pc

### ISSUE THREAD

**Issue by imagodiern** [hashicorp/vagrant#12508]
Guys I’m in a loop…while I was updating kali Linux I got this pop up saying The GRUB boot loader was previously installed to a disk that is no longer present…..and there is an option which says ok and I click on that another thing pops up saying GRUB install devices and then a list 
    /dev/sda/ 85899 MB; VBOX_HARDDISK
    -  /dev/sda1  (84873 MB;  /)
and then an option saying ok no matter which one I select it pops up another one which says continue without installing the GRUB….should I press yes or no? 
I don’t know what will happen if I select not to install grub because ima complete beginner. Please help. Thanks ❤️
    -

**Comment by chrisroberts** [comment]
Hi there. This information is probably relevant to the issue you encountered: https://askubuntu.com/questions/560685/what-do-i-select-for-grub-install-devices-after-an-update-on-a-vm

Cheers!
