### ISSUE TITLE
RPM & DEB: version 2.2.18 built with ruby-2.7.0 instead of ruby-3.0.0

### ISSUE THREAD

**Issue by LKHN** [hashicorp/vagrant#12506]
### Vagrant version

2.2.18

### Host operating system
RPM: EL8/AlmaLinux OS 8 and Fedora 34
DEB: Debian and Ubuntu

### Expected behavior
`vagrant-2.2.17-1: ruby-3.0.0`
`vagrant-2.2.18-1: ruby-3.0.0`

### Actual behavior
`vagrant-2.2.17-1: ruby-3.0.0`
`vagrant-2.2.18-1: ruby-2.7.0`

### Steps to reproduce

1.

`sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo` [EL]
`sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo` [FEDORA]

2.
RPM 
`sudo dnf download vagrant-2.2.17-1`
`sudo dnf download vagrant-2.2.18-1`
DEB
`curl -O https://releases.hashicorp.com/vagrant/2.2.17/vagrant_2.2.17_x86_64.deb`
`curl -O https://releases.hashicorp.com/vagrant/2.2.18/vagrant_2.2.18_x86_64.deb`
3.
RPM
`rpm2cpio vagrant-2.2.17-1.x86_64.rpm | cpip -imdV`
`rpm2cpio vagrant-2.2.18-1.x86_64.rpm | cpip -imdV`
DEB
`ar x vagrant_2.2.17_x86_64.deb`
`ar x vagrant_2.2.18_x86_64.deb`

`tar xvzf data.tar.gz`

4.
`ls opt/vagrant/embedded/include/ | grep ruby`

**Comment by LKHN** [comment]
@chrisroberts

**Comment by chrisroberts** [comment]
The built packages reverted back to the Ruby 2.7 series due to compatibility issues with Ruby 3.0 and will continue to use the 2.7 series for the foreseeable future. 

Cheers!
