### ISSUE TITLE
ERROR: Internal error. Report this as a bug. Invalid: rsync (RuntimeError)

### ISSUE THREAD

**Issue by nurisezgin** [hashicorp/vagrant#12516]
Hi everyone who will be looking after,

Honestly, I'm posting this issue because printed-out exception logs contain text about "report this is a bug." Otherwise, I didn't want to drive you such an issue.

Let me explain what happened step by step.

1. I intended to do some experimental practices with "podman," but I didn't want to install my machine directly. 
1.1. Therefore, firstly I provisioned a VM (Ubuntu) on my host machine.
1.2. Then, inside the Ubuntu VM, I set up "vagrant" and "VirtualBox" together.
1.3. For now, everything seems to be perfect until typing "vagrant up. " It threw error like I posted "Debug Output" section.

Consequently, it can be technically possible to run a virtual machine inside another. But it is not just about vagrant; VirtualBox, configuration, resource utilization, and so on would be questionable ingredients. As I mentioned, details of the error wanted me to post it.

### Vagrant version
Vagrant 1.4.3

### Host operating system
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71

### Guest operating system
NAME="Ubuntu"
VERSION="14.04.6 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.6 LTS"
VERSION_ID="14.04"

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "fedora/32-cloud-base"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y podman

    groupadd -f -r podman

    #systemctl edit podman.socket
    mkdir -p /etc/systemd/system/podman.socket.d
    cat >/etc/systemd/system/podman.socket.d/override.conf <<EOF
[Socket]
SocketMode=0660
SocketUser=root
SocketGroup=podman
EOF
    systemctl daemon-reload
    echo "d /run/podman 0770 root podman" > /etc/tmpfiles.d/podman.conf
    sudo systemd-tmpfiles --create

    systemctl enable podman.socket
    systemctl start podman.socket

    usermod -aG podman $SUDO_USER
  SHELL
end
```

### Debug output
vagrant@vagrant-ubuntu-trusty-64:~/container$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'fedora/32-cloud-base'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Destroying VM and associated drives...
/usr/lib/ruby/vendor_ruby/vagrant/action/builtin/mixin_synced_folders.rb:71:in `block in synced_folders': Internal error. Report this as a bug. Invalid: rsync (RuntimeError)
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/mixin_synced_folders.rb:59:in `each'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/mixin_synced_folders.rb:59:in `synced_folders'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/synced_folder_cleanup.rb:19:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/provisioner_cleanup.rb:24:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/destroy_unused_network_interfaces.rb:18:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/destroy.rb:14:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:57:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/env_set.rb:19:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:51:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:51:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `run'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/import.rb:48:in `recover'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:67:in `block in recover'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:64:in `each'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:64:in `recover'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:62:in `recover'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:67:in `block in recover'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:64:in `each'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:64:in `recover'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:53:in `rescue in call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:28:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:57:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:57:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:69:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:147:in `action'
	from /usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:63:in `block (2 levels) in run'

### Expected behavior
N/A

### Actual behavior
`vagrant up` didn't work properly and threw above error immediately after I pressed.
### Steps to reproduce

1. Basically just `vagrant up`

**Comment by chrisroberts** [comment]
Yes, 1.4.3 is an extremely old version of Vagrant. Please upgrade and if the error is still encountered we will be happy to have a look.

Cheers!

**Comment by soapy1** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
