### ISSUE TITLE
unable to install vagrant on ubuntu 21.10 following instructions @ https://www.vagrantup.com/downloads

### ISSUE THREAD

**Issue by noahehall** [hashicorp/vagrant#12537]
unable to install on ubuntu 21.10

`'https://apt.releases.hashicorp.com impish Release' does not have a Release file.`

however, specifying hirsute worked perfectly

sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com hirsute main"

**Comment by soapy1** [comment]
Heya, thanks for opening up an issue. The downloads page has been updated and now has all the steps required to get Vagrant installed on all supported platforms 🎉
