### ISSUE TITLE
Fusion 12.2 broke vagrant

### ISSUE THREAD

**Issue by stolowski** [hashicorp/vagrant#12539]
### Vagrant version

2.2.18

### Host operating system

Mac OS 11.6

### Guest operating system

Ubuntu 20.04

The just released Fusion 12.2 broke vagrant for me. Bringing up existing VMs fails  on ssh (using wrong IP address, e.g. 172.162.1.2 instead of 172.162.1.128). Creating a new VM fails with:

Bringing machine 'ubuntu-focal' up with 'vmware_desktop' provider...
==> ubuntu-focal: Checking if box 'bento/ubuntu-20.04' version '202109.07.0' is up to date...
==> ubuntu-focal: Verifying vmnet devices are healthy...
==> ubuntu-focal: Preparing network adapters...
==> ubuntu-focal: Starting the VMware VM...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["start", "/Users/pawel/Vagrant/ubuntu-20.04-snapd/.vagrant/machines/ubuntu-focal/vmware_desktop/cc54a256-87a2-4468-846f-fd45584ee268/ubuntu-20.04-amd64.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: 2021-10-15T12:21:06.567| ServiceImpl_Opener: PID 3947
Error: The operation was canceled

Stderr: 

### Steps to reproduce

1. Update Fusion to 12.2 (I was updating from the previous 12.11.2), reboot.
2. Try to create a new ubuntu VM with vagrant up.

I'm sorry I don't have debug output, I collected the above information and reverted back to Fusion 12.11.2 since this breakage was a major distraction in my work. I may re-try 12.2 later if needed (or maybe someone else experiencing this can add extra info).

**Comment by stolowski** [comment]
Hmm I think the problem may be elsewhere now, when running the failing command manually (with gui):
`vmrun start /Users/pawel/Vagrant/test/.vagrant/machines/default/vmware_desktop/8939eb21-5849-4de5-b938-92177f1b2b16/ubuntu-20.04-amd64.vmx`

I get a vmware popup saying `the device "sata" is not supported by current hwversion`, and that makes vmrun fail. I'm not sure where does hw definition come from, but for what it's worth my bento/ubuntu-20.04 box is up-to-date.

**Comment by stolowski** [comment]
Ok, I think the problem is with bento/ubuntu-20.04 box, the hwversion it uses is 8, without investigating too much what it means it practice I bumped it to 18 (for fusion 12.x) with something like this in my Vagrantfile:
```
Vagrant.configure("2") do |config|
  config.vm.provider :vmware_desktop do |v|
       v.vmx["virtualhw.version"] = 18
    end
 end
```
and this made the vm happy.

I suppose this issue can be closed, but I'd appreciate any comments/ideas as to why this incompatibility occured (if sata worked with hw version 8 before, I would expect it to still work after minor fusion upgrade), whether this is an actual issue of bento boxes that should be reported to bento, and whether there is anything better than my workaround.

**Comment by chrisroberts** [comment]
Going to close this as resolved. Unfortunately, I don't have any useful information to provide as to why it had issues with hwversion on this release.

Cheers!
