### ISSUE TITLE
Vagrant install issues

### ISSUE THREAD

**Issue by OG-BOSSCAT** [hashicorp/vagrant#12541]
Hi, I tried installing Vagrant and there seems to be an issue with the VMware utility service. I couldn't install the amd64 Linux zip package. It doesn't link to anything nor unzips. Also, I am trying to install GameMaker Studio 2 and there seems to be a problem with the vagrant boring SSL certification. 

Any help is appreciated. Thank you so much for your time!

**Comment by chrisroberts** [comment]
Hi there,

Are you having an issue installing Vagrant, or just the Vagrant VMware utility? If you are on Linux, you should use the installer package (`.deb`, `.rpm`, etc) if it is available for your platform. If there is not one available for your platform, you'll need to follow the setup instructions found here:

https://www.vagrantup.com/docs/providers/vmware/vagrant-vmware-utility#manual-installation

**Comment by soapy1** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
