### ISSUE TITLE
Vagrant command not found after vagrant ssh

### ISSUE THREAD

**Issue by kudopark** [hashicorp/vagrant#12546]
I can get the VM running with vagrant up, but as soon as cal vagrant ssh and enter the virtual environment none of the vagrant commands work. 
When I type vagrant destroy the terminal outputs -bash: vagrant: command not found.

**Comment by chrisroberts** [comment]
Hi there,

The `vagrant` command is only available on the host machine. Once you have ssh'd to a guest, you will be within a virtual machine, container, etc. The `vagrant` command is used to interact with guests from the host.

Cheers!
