### ISSUE TITLE
Vagrant encountered an unexpected communications error with the Vagrant VMware Utility driver.

### ISSUE THREAD

**Issue by send9** [hashicorp/vagrant#12551]
First of all, I am sorry for posting this issue -- I know how many times it has been posted in the past.

I am trying to run Vagrant on macOS 11.6 (Big Sur) on an M1 processor. Since VirtualBox won't work here, I am using the VMWare Fusion provider. I have VMWare Fusion Tech Preview, which I believe is the only version that will work. 

```
% vagrant up --provider vmware_desktop
Vagrant encountered an unexpected communications error with the
Vagrant VMware Utility driver. Please try to run the command
again. If this error persists, please contact support@hashicorp.com
```

```
% sudo launchctl list | grep com.vagrant.vagrant-vmware-utility
-       0       com.vagrant.vagrant-vmware-utility-stopper
-       1       com.vagrant.vagrant-vmware-utility
```

```
% sudo cat "/Library/Application Support/vagrant-vmware-utility/service.log"
2021-10-21T22:47:31.159-0500 [INFO]  vagrant-vmware-utility.api: created: vmx=<nil>
2021-10-21T22:47:31.159-0500 [ERROR] vagrant-vmware-utility.api: path loading failure: error="Failed to locate VMware installation directory!"
2021-10-21T22:47:31.159-0500 [ERROR] vagrant-vmware-utility.api: base driver setup failure: error="Failed to locate VMware installation directory!"
Failed to setup Vagrant VMWare API service - Failed to locate VMware installation directory!
```

This log seems different from what I've seen here. Am I doing something wrong?

Thanks in advance.

**Comment by JobeanSmith** [comment]
I have done what you recommended (create a symlink) but it says that it doesn't find the VMware installation folder.
Do you have any idea of what cause this issue ?

<img width="1037" alt="Screenshot 2021-10-30 at 21 59 35" src="https://user-images.githubusercontent.com/62311155/139556939-63a147d7-7ef6-4c35-ad94-02114224d4b5.png">
<img width="232" alt="Screenshot 2021-10-30 at 21 59 52" src="https://user-images.githubusercontent.com/62311155/139556941-e7921f17-bf6b-47f7-aabf-7891f80a5d29.png">

**Comment by chrisroberts** [comment]
Either there is another `vagrant-vmware-utility` process running, or you have another process that is listening on port 9922. You can either use `launchctl` to stop the Vagrant VMware utility, kill any remaining `vagrant-vmware-utility` processes, and then use `launchctl` to start it again. Or, you can reboot. If you are still encountering the "address already in use" error, then another process is using the port.

**Comment by send9** [comment]
@chrisroberts Thanks for the fix. Are you seeing the version parsing issue after the symlink or is it just something on my end?

**Comment by chrisroberts** [comment]
You need to be on the latest vagrant vmware utility version ([1.0.21](https://www.vagrantup.com/vmware/downloads)) for it to properly handle the tech preview version
