### ISSUE TITLE
macOS Monterey and VirtualBox 6.1.28

### ISSUE THREAD

**Issue by petealves** [hashicorp/vagrant#12557]
Hello. I am having some issues with running `vagrant up` in Mac OS Monterey 12.0.1. 
I am running Virtual Box version 6.1.26 (I have tried 6.1.28, same problems) and Vagrant version 2.2.18.
During the installation of VBox I did went into System Preferences -> Privacy -> Allow Oracle....

So, the first problem is the following:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/27501071/138864895-0b8a6a70-2d19-454c-b20d-050200ec2836.png">
However, when I load the kexts (found this suggestion in other threads) by running `sudo kextload -b org.virtualbox.kext.VBoxDrv  
sudo kextload -b org.virtualbox.kext.VBoxNetFlt
sudo kextload -b org.virtualbox.kext.VBoxNetAdp
sudo kextload -b org.virtualbox.kext.VBoxUSB` it throws me another error which I could not find any solution for. 
<img width="911" alt="image" src="https://user-images.githubusercontent.com/27501071/138865536-871a3f73-8963-40fd-8aa3-2f927d6619ad.png">

Is this some problem with MacOS Monterey? Thanks!

**Comment by andresmauro17** [comment]
Same issue Here

![image](https://user-images.githubusercontent.com/10373792/139503708-93349678-46b2-4921-bf62-e0e54b112432.png)

**Comment by andresmauro17** [comment]
> Worked for me just adding:
> 
> Homestead.yaml
> 
> ip: "192.168.10.10" memory: 6144 cpus: 4 provider: virtualbox gui: 1 <----- this ...
> 
> vagrant 2.2.18 VirtualBox 6.1.28

Work for me!

**Comment by sonykey2003** [comment]
> I tried combination of @dsutphin and @rockblings solutions and it worked a bit but not fully.
> 
> I am using: Vagrant 2.2.18 VirtualBox 6.1.28
> 
> I did this:
> 
> 1. Changed "gui" instead "headless" in Vagrantfile.
> 2. Run following commands in Terminal immediately you switch on Mac.
> 
> ```
> sudo kextload -b org.virtualbox.kext.VBoxDrv;
> sudo kextload -b org.virtualbox.kext.VBoxNetFlt;
> sudo kextload -b org.virtualbox.kext.VBoxNetAdp;
> sudo kextload -b org.virtualbox.kext.VBoxUSB;
> ```
> 
> 1. After that run `vagrant up` and it boots well.
> 
> But I have following config in my Vagrantfile
> 
> ```
> config.vm.network "private_network", ip: "192.168.68.35"
> ```
> 
> And these are not working, so vagrant up but it is not able to forward ip properly and hence I cannot access it via local domains pointed to that ip in hosts file.
> 
> Please help if anyone knows about how to fix this IP thing now.

It works for me without the "private_network" part, thanks!

**Comment by WayneDK** [comment]
^^^
See post above but in summary

You should create a network configuration with sudo nano /etc/vbox/networks.conf command. Create /etc/vbox directory if it doesn't exists then create a networks.conf file.

networks.conf

* 0.0.0.0/0 ::/0

**Comment by WayneDK** [comment]
Even with the above fixes, running `Mac OS Monterey 12.0.1.`, `VB 6.1.28`  and `Vagrant version 2.2.18` this is almost unusable. It might boot the box and you might get the local hosts to play on an private IP, but it is completely unreliable and is crashing all the time. Try getting mySQL to run and login to a DB, it either won't connect or crashes the box. 

This has completely broken my development environment, it is unusable right now, a complete mess ;-)

**Comment by justinrclarke** [comment]
> What worked for me is combination of all above:
> 
> Vagrant 2.2.18 VirtualBox 6.1.28
> 
> created `/etc/vbox/networks.conf` on the host machine with the following content
> 
> ```
> * 10.0.0.0/8 192.168.10.0/24
> * 2001::/64
> ```
> 
> These commands after every reboot:
> 
> ```
> sudo kextload -b org.virtualbox.kext.VBoxDrv;
> sudo kextload -b org.virtualbox.kext.VBoxNetFlt;
> sudo kextload -b org.virtualbox.kext.VBoxNetAdp;
> sudo kextload -b org.virtualbox.kext.VBoxUSB;
> ```
> 
> and adding `gui = true` to Vagrantfile
> 
> ```
>  project_config.vm.provider 'virtualbox' do |vb|
>     vb.gui = true  # Add this line
>     ...
> ```
> 
> Thanks everyone and good luck

With a fresh install of Monterey and all of the applications, this finally worked for me.

**Comment by ltutar** [comment]
I want to summarize what helped me based on all the valuable input above.
I am using on MacOS Monterey version 12.0.1:
- Vagrant version 2.2.18
- vagrant-vbguest (0.21.0, global)
- VirtualBox 6.1.26
and had to change vb.gui = false to vb.gui = true

This combination is working for me.

If I use
- a higher version of vagrant-vbguest, mount does not work.
- VirtualBox version 6.1.28, then I Ansible or ssh can not reach my vagrant boxes (unreachable ip address and port). BTW. vagrant ssh keeps working.
- vb.gui = false, then I get the error `VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine`

**Comment by webautosetby** [comment]
I spent a long time solving the issue of virtualbox and switched to docker and this was my best solution, a solution to work with docker and forget about vagrant and virtualbox problems

**Comment by iainhouston** [comment]
I too have finally  lost patience with VirtualBox with niggles for months and finally total failure with Monterey, and, since I had Parallels Desktop already on my Mac, using `geerlingguy/drupal-vm`  I changed my `vagrant.config.yml` to specify `vagrant_box: bento/ubuntu-18.04`; I did `vagrant plugin install vagrant-parallels` and  `vagrant up provider=parallels` and that was pretty much it.
Every other aspect of the development setup remains unchanged. Wish I’d done this years ago. Genuinely very grateful for free use of VirtualBox for many years but my loyalty finally evaporated this month.

**Comment by tomektomczuk** [comment]
I downgraded to Big Sur and doesn't have any problems with 6.1.26. Use Vagrant and Virtualbox with https://roots.io/docs/trellis/master/installation/#create-a-project - both are required

**Comment by jeremykenedy** [comment]
Any ETA on this fix?

**Comment by foxfoobar** [comment]
First of all you need to have 6.1.28 on Monterey to prevent kernel panics.

The second issue with not loading the kexts automatically is because the file
/Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh still has Big Sur as its "MACOS_VERS".
You need to change every line that goes from 
if [[ ${MACOS_VERS} != 11.* ]]; then
to
if [[ ${MACOS_VERS} != 12.* ]]; then
 There should be 3 lines containing "11.*"

Not sure why oracle didn't change this yet.

**Comment by dkoether** [comment]
> First of all you need to have 6.1.28 on Monterey to prevent kernel panics.
> 
> The second issue with not loading the kexts automatically is because the file /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh still has Big Sur as its "MACOS_VERS". You need to change every line that goes from if [[ ${MACOS_VERS} != 11.* ]]; then to if [[ ${MACOS_VERS} != 12.* ]]; then There should be 3 lines containing "11.*"
> 
> Not sure why oracle didn't change this yet.

Unfortunately it still does not work at all. Using 6.1.28 and fixing those lines in VirtualBoxStartup.sh still causes kernel problem while starting the vm. :( Am I missing something or is it currently impossible to use macOS Monterey and Vagrant (with VirtualBox)?

**Comment by ffaridfar** [comment]
> The second issue with not loading the kexts automatically is because the file
/Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh still has Big Sur as its "MACOS_VERS".
You need to change every line that goes from
if [[ ${MACOS_VERS} != 11.* ]]; then
to
if [[ ${MACOS_VERS} != 12.* ]]; then
There should be 3 lines containing "11.*"

This will fix one of the issues. I also restarted VBox:
```
sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart
```
It seems there's another an ongoing issue with `gui` and starting the VM headless [VBoxHeadless does not run in macOS Monterey 12.0.1](https://www.virtualbox.org/ticket/20636). So you have to uncomment this part in `Vagrantfile`: 
```
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  end
```
Then the `vagrant up` worked fine for me.
My problem, however, is that I made my life "easier" by adding another layer of difficulty and calling the Vagrant via Ansible molecule. So far, I couldn't find a way to update the `gui` part in `Vagrantfile` of a molecule VM!

I'm on MacOS 12.0.1:
```
$ VBoxManage -v
6.1.28r147628
vagrant -v
Vagrant 2.2.18
```

**Comment by chrisroberts** [comment]
Hi everyone,

To summarize this issue, there are currently issues with VirtualBox on macOS Monterey. There's three different things which are causing issues:

1. VMs cannot be started headless [VB#20636](https://www.virtualbox.org/ticket/20636)
2. kexts not being loaded properly [VB#20637](https://www.virtualbox.org/ticket/20637)
3. Cannot create network within given subnet [VB#20626](https://www.virtualbox.org/ticket/20626)

For 1, the only way to workaround this is to enable the GUI within the provider configuration:

```ruby
config.vm.provider :virtualbox do |vb|
  vb.gui = true
end
```

For 2, the kernel extensions can be loaded manually (which may be required after reboot):

```shell
sudo kextload -b org.virtualbox.kext.VBoxDrv;
sudo kextload -b org.virtualbox.kext.VBoxNetFlt;
sudo kextload -b org.virtualbox.kext.VBoxNetAdp;
sudo kextload -b org.virtualbox.kext.VBoxUSB;
```

For 3, the 6.1.28 release introduced a new restriction when creating networks which can be found [here](https://www.virtualbox.org/manual/ch06.html#network_hostonly). PR #12564 adds validation to given addresses and returns back useful error message for how to add more ranges to the VirtualBox configuration.

Unfortunately there is nothing we can do directly to resolve these issues (outside of the networking issue which will be included in the next release). The next maintenance release of VirtualBox should include fixes for the other two issues.

Cheers!

**Comment by ckihneman** [comment]
> What worked for me is combination of all above:
> 
> Vagrant 2.2.18 VirtualBox 6.1.28
> 
> created `/etc/vbox/networks.conf` on the host machine with the following content
> 
> ```
> * 10.0.0.0/8 192.168.10.0/24
> * 2001::/64
> ```
> 
> These commands after every reboot:
> 
> ```
> sudo kextload -b org.virtualbox.kext.VBoxDrv;
> sudo kextload -b org.virtualbox.kext.VBoxNetFlt;
> sudo kextload -b org.virtualbox.kext.VBoxNetAdp;
> sudo kextload -b org.virtualbox.kext.VBoxUSB;
> ```
> 
> and adding `gui = true` to Vagrantfile
> 
> ```
>  project_config.vm.provider 'virtualbox' do |vb|
>     vb.gui = true  # Add this line
>     ...
> ```
> 
> Thanks everyone and good luck

To hopefully help some others out there, I'm using Trellis from roots.io. I did all of the above steps, but I was hanging while trying to get admin privileges for mounting NFS shared folders. I was typing my password into the prompt, but then the system would still ask privileges from a system modal. I'd do that, then it would still hang (and timeout eventually), right on this part:

```
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
==> default: Mounting NFS shared folders...
```

As another user mentioned:

> Forgot to mention that the solution that works for me did not work with VirtualBox 6.1.28. so i downgraded to 6.1.26. then it worked after uninstalling and installing the 6.1.26. i hope this helps

After re-installing VirtualBox to 6.1.26 (and accepting the privacy request from Oracle, then rebooting my system), my Trellis VM works once again.

And yes, you do have to run those commands after restarting your computer (every time).

**Comment by songliqiangcn** [comment]
> ```
> $ vagrant up --provision
> Bringing machine 'homestead-7' up with 'virtualbox' provider...
> ==> homestead-7: Importing base box 'lc/homestead'...
> ==> homestead-7: Matching MAC address for NAT networking...
> ==> homestead-7: Checking if box 'lc/homestead' version '11.0.0' is up to date...
> ==> homestead-7: Setting the name of the VM: homestead-7
> ==> homestead-7: Clearing any previously set network interfaces...
> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["hostonlyif", "ipconfig", "vboxnet0", "--ip", "192.168.10.1", "--netmask", "255.255.255.0"]
> 
> Stderr: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
> VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
> ```
> 
> Vagrant : 2.2.18 virtualbox version: 6.1.28 r147628 (Qt5.6.3) macos version: 12.0.1
> 
> Tried all of the above and it still doesn't work :(

Same issue

**Comment by dkoether** [comment]
> What worked for me is combination of all above:
> 
> Vagrant 2.2.18 VirtualBox 6.1.28
> 
> created `/etc/vbox/networks.conf` on the host machine with the following content
> 
> ```
> * 10.0.0.0/8 192.168.10.0/24
> * 2001::/64
> ```
> 
> These commands after every reboot:
> 
> ```
> sudo kextload -b org.virtualbox.kext.VBoxDrv;
> sudo kextload -b org.virtualbox.kext.VBoxNetFlt;
> sudo kextload -b org.virtualbox.kext.VBoxNetAdp;
> sudo kextload -b org.virtualbox.kext.VBoxUSB;
> ```
> 
> and adding `gui = true` to Vagrantfile
> 
> ```
>  project_config.vm.provider 'virtualbox' do |vb|
>     vb.gui = true  # Add this line
>     ...
> ```
> 
> Thanks everyone and good luck

This worked for me. VM is running, thank you!

**Comment by blade2201** [comment]
What i did to make it work was:

- Downgrade VirtualBox to 6.1.16

Than i had "Kernel driver not installed (rc=-1908)" errore and to fix this i just:
`
sudo csrutil clear
sudo reboot
`

after this everything worked like it was supposed to

**Comment by rafmrs** [comment]
> @iMactool
> 
> You can use latest version of Vagrant (2.2.18) and VirtualBox (6.1.28). If you are currently using 6.1.26 version you can delete it.
> 
> Add Homestead.yaml to gui: 1 settings.
> 
> ```
> ---
> ip: "192.168.10.10"
> memory: 8096
> cpus: 4
> provider: virtualbox
> gui: 1 --> this line
> ```
> 
> Then destroy your vagrant box with `vagrant destroy` command.
> 
> You should create a network configuration with `sudo nano /etc/vbox/networks.conf` command. Create `/etc/vbox` directory if it doesn't exists then create a networks.conf file.
> 
> networks.conf
> 
> ```
> * 0.0.0.0/0 ::/0
> ```
> 
> Run this block before `vagrant up` command. Unfortunately running this before every time.
> 
> ```
> sudo kextload -b org.virtualbox.kext.VBoxDrv && sudo kextload -b org.virtualbox.kext.VBoxNetFlt && sudo kextload -b org.virtualbox.kext.VBoxNetAdp  && sudo kextload -b org.virtualbox.kext.VBoxUSB
> ```
> 
> Then run `vagrant up` command. `vagrant reload --provision` when it's new vagrant box.
> 
> It works for me.

This works for me with Laravel Homestead, I didn't need to destroy the machine

**Comment by foxfoobar** [comment]
Headless on VirtualBox version 6.1.29 is working again, not sure if Vagrant is, someone needs to test it since i'm not using it.

https://www.virtualbox.org/wiki/Testbuilds
https://www.virtualbox.org/download/testcase/VirtualBox-6.1.29-147956-OSX.dmg
https://www.virtualbox.org/download/testcase/Oracle_VM_VirtualBox_Extension_Pack-6.1.29-147956.vbox-extpack

**Comment by alimirayman** [comment]
Same roblem 
<html><body><p>Failed to open a session for the virtual machine <b>dashboard</b>.</p><qt><p>The virtual machine <b><nobr>'dashboard'</nobr></b> has terminated unexpectedly during startup with exit code 1 (0x1).</p>

Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | MachineWrap
Interface: | IMachine {85632c68-b5bb-4316-a900-5eb28d3413df}

<br></body></html>

**Comment by alimirayman** [comment]
> Headless on VirtualBox version 6.1.29 is working again, not sure if Vagrant is, someone needs to test it since i'm not using it.
> 
> https://www.virtualbox.org/wiki/Testbuilds https://www.virtualbox.org/download/testcase/VirtualBox-6.1.29-147956-OSX.dmg https://www.virtualbox.org/download/testcase/Oracle_VM_VirtualBox_Extension_Pack-6.1.29-147956.vbox-extpack

Installed them, tried to run create a new instance of Ubuntu didn't work, tried to run headless didn't work either

**Comment by sirproton** [comment]
I was able to get my VM up and running again with the new macOS update by adding this to the Vagrantfile

```
  config.vm.provider "virtualbox" do |v|
      v.gui = true
    end

```

My current setup has:

Vagrant version: 2.2.18
VirtualBox version: 6.1.28 r147628
macOs version: 12.0.1

**Comment by chrisroberts** [comment]
Hi everyone,

I'm locking this issue to help people locate the information they need. For a summary of the current issues with Vagrant using the VirtualBox provider on macOS, please see this comment: https://github.com/hashicorp/vagrant/issues/12557#issuecomment-958183899

I've locked the issue as "resolved" since the things that can be addressed by Vagrant (network range validation) has already been completed and will be available in the upcoming release. The other issues being encountered will be fixed once VirtualBox publishes their next maintenance release. Workarounds for these issues can also be found in this comment: https://github.com/hashicorp/vagrant/issues/12557#issuecomment-958183899

Cheers!
