### ISSUE TITLE
2.2.19 breaks disks experimental feature

### ISSUE THREAD

**Issue by GameBurrow** [hashicorp/vagrant#12579]
### Vagrant version

2.2.19

### Host operating system

Windows 10 Pro

### Guest operating system

Debian 11

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Enable the experimental disks feature via environment variable, requires Vagrant >=2.2.8.
ENV["VAGRANT_EXPERIMENTAL"] = "disks"


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Automatically install needed vagrant plugins
  config.vagrant.plugins = ["vagrant-env", "vagrant-hostmanager", "vagrant-vbguest"]
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # Official debian boxes: https://app.vagrantup.com/debian
  config.vm.box = "generic/debian11"

  # Configure primary disk
  config.vm.disk :disk, size: ENV['VM_DISK_SIZE'], primary: true
end
```

### Debug output

Already reverted back to 2.2.18 because it was blocking my work, thus I'm unable to provide debug log atm.

### Expected behavior

Experiemental features warning should have popped up:
![image](https://user-images.githubusercontent.com/4341091/140736190-9ee15920-f24c-4d90-96ca-a1532a93f4db.png)
and disk resize should have happened. 

This works in 2.2.18

### Actual behavior

No experimental varning and no disk resize. Confirmed it on virtualbox, hyperv and vmware_desktop providers.

### Steps to reproduce

1. Enable experimental features through vagrantfile
2. Add disk resize configuration
3. `vagrant up`
4. Even tried `vagrant reload`

**Comment by chrisroberts** [comment]
Hi there,

I'm not seeing the behavior you are describing. On Windows with 2.2.19 installed, I can set the environment variable within the Vagrantfile and it is still picked up as expected. Do you experience the features not showing as enabled when you set the environment variable in the shell?

**Comment by GameBurrow** [comment]
Tried reinstalling 2.2.19 again and indeed the issue seems to be no longer appearing.
