### ISSUE TITLE
Enhancement Request: Assign ecdsa/ed25519 of insecure keypair 

### ISSUE THREAD

**Issue by akihiro** [hashicorp/vagrant#12589]
**Is your feature request related to a problem? Please describe.**
- CentOS stream 9 or RHEL9 beta reject `ssh-rsa` key.
  - CentOS stream 9 http://mirror.stream.centos.org/9-stream/
  - RHEL9 beta https://developers.redhat.com/products/rhel/rhel9-beta

> Use of SHA-1 is restricted in the DEFAULT crypto policy. With the exception of HMAC and DNSSec usage, SHA-1 is no longer allowed in TLS, DTLS, SSH, IKEv2 and Kerberos protocols.
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html-single/9.0_release_notes/index#overview-major-changes

> In the SSH protocol, the "ssh-rsa" signature scheme uses the SHA-1
hash algorithm in conjunction with the RSA public key algorithm.
OpenSSH will disable this signature scheme by default in the near
future.
https://www.openssh.com/txt/release-8.5

**Describe the solution you'd like**
- Add ecdsa/ed25519 keypair to https://github.com/hashicorp/vagrant/tree/main/keys

**Describe alternatives you've considered**
- Allow ssh_rsa by sshd_config in vagrant box image.

**Additional context**
No

**Comment by bby-bishopclark** [comment]
can we work around this deficiency with a `config.ssh.private_key_path` directive?  Have you tried this and did it work? (it's my next step)

**Comment by cambid** [comment]
This is also a problem for all newer distributions like:

- Debian testing
- Ubuntu Jammy
- Archlinux

AFAIS this should be changed in util/keypair.rb to something more modern like ECDSA or ED25519

**Comment by SilverBut** [comment]
Additionaly, the macOS SSH client is also refusing `ssh-rsa`, resulting to this error:

```
sign_and_send_pubkey: no mutual signature supported
vagrant@127.0.0.1: Permission denied (publickey).
```

A temp workaround is to use ssh command like this:

```
vagrant ssh boxA -- -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedKeyTypes=+ssh-rsa
```

It would be good for me if Vagrant can deploy ecdsa/ed25519 key by default.

**Comment by drawks** [comment]
This is a hassle for sure, I'd suggest we spin a second insecure key that is using a newer algo and just bundling both pubkeys together and on the client side set both keys as arguments to "--identity" and/or add both keys to ssh-agent. Any version of openssh client and server released in the last 8+ years should do the right thing and negotiate a common allowed private/public pair.
