### ISSUE TITLE
> However, the IP address on the VM was not set to the one from the Vagrantfile / config.vm.network 'private_network', ip: '11.0.0.12' /.

### ISSUE THREAD

**Issue by jmchauv** [hashicorp/vagrant#12590]
> However, the IP address on the VM was not set to the one from the Vagrantfile / config.vm.network 'private_network', ip: '11.0.0.12' /.

I ran into this as well. Using `config.vm.network "forwarded_port", guest: 80, host: 8080` for now. Keeping an eye out for better solutions.

_Originally posted by @dsutphin in https://github.com/hashicorp/vagrant/issues/12557#issuecomment-952094241_

Could you help me understand this workaround? What is the IP address you're referencing if you put those details within the VagrantFile

**Comment by jmchauv** [comment]
mistake

**Comment by dsutphin** [comment]
127.0.0.1 is the ip that gets used.
