### ISSUE TITLE
vagrant up and vagrant ssh does not work

### ISSUE THREAD

**Issue by A01258386** [hashicorp/vagrant#12612]
### Vagrant version
ubuntu/hirsute 21.04

### Host operating system
windows

### Vagrantfile
Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/hirsute64"
 config.vm.synced_folder ".", "/home/vagrant/shared_folder"
end

### Errors
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/json/common.rb:156:in `initialize': negative string size (or size too big) (ArgumentError)
	from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/json/common.rb:156:in `new'
	from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/json/common.rb:156:in `parse'
	from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/json/common.rb:335:in `load'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:320:in `unlocked_reload'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:53:in `block in initialize'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:350:in `block in with_index_lock'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:348:in `open'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:348:in `with_index_lock'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/machine_index.rb:52:in `initialize'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:724:in `new'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:724:in `machine_index'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:206:in `block in action_runner'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/action/runner.rb:34:in `run'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:526:in `hook'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/box_collection.rb:321:in `call'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/box_collection.rb:321:in `block (3 levels) in find'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/box_collection.rb:311:in `each'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/box_collection.rb:311:in `block (2 levels) in find'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/box_collection.rb:304:in `each'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/box_collection.rb:304:in `block in find'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/box_collection.rb:457:in `block in with_collection_lock'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/box_collection.rb:456:in `synchronize'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/box_collection.rb:456:in `with_collection_lock'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/box_collection.rb:280:in `find'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/vagrantfile.rb:201:in `block in machine_config'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/vagrantfile.rb:237:in `machine_config'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:959:in `block in find_configured_plugins'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:957:in `each'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:957:in `find_configured_plugins'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:984:in `process_configured_plugins'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/lib/vagrant/environment.rb:178:in `initialize'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/bin/vagrant:194:in `new'
	from C:/HashiCorp/Vagrant/embedded/gems/2.2.18/gems/vagrant-2.2.18/bin/vagrant:194:in `<main>'

### Expected behavior (the history of commands may cause vagrant ssh problem)
 1230  sudo apt update && sudo apt upgrade
 1231  man -k Release | grep Codename
 1232  man -k Release
 1233  lsb_release
 1234  os-release
 1235  distro-info
 1236  distro-info less
 1237  lsb_release -a
 1238  vim ~/exam
 1239  ls
 1240  pwd
 1241  cd
 1242  mkdir exam
 1243  rm exam 
 1244  ls
 1245  mkdir exam
 1246  cd exam
 1247  git clone https://github.com/untemperedschism/script-2420-fall21.git
 1248  ls
 1249  cat script-2420-fall21/
 1250  cd script-2420-fall21/
 1251  ls
 1252  cat README.md 
 1253  cat fzyedt 
 1254  cat fzyedt 
 1255  sudo chmod +x fzyedt
 1256  ./fzyedt 
 1257  sudo fzf install
 1258  sudo install fzf
 1259  sudo apt-get update && sudo apt-get install fzf
 1260  ./fzyedt 
 1261  ./fzyedt
 1262  sudo apt-get install fd-find
 1263  ./fzyedt 
 1264  cd
 1265  mkdir bin backups
 1266  ls
 1267  vim /bin/bckup
 1268  ls
 1269  cd bin
 1270  ls
 1271  touch bckup
 1272  vim bckup 
 1273  ls
 1274  ./bckup
 1275  chmod +x bckup 
 1276  ./bckup
 1277  vim bckup 
 1278  ./bckup
 1279  vim bckup 
 1280  LS
 1281  vim bckup 
 1282  cd /etc/systemd/system
 1283  vim backup.service

### Actual behavior

Today during my linux exam, I was successfully vagrant ssh. I run above commands, but I forgot to sudo for last command "vim backup.service" .  I tried ":w !sudo tee %" , still didn't saved. So I closed the Windows cmd terminal(because I coulnt exit vi). When I tried the vagrant ssh back, I got the errors.

What did I do wrong and how can I fix it. I am student please help. 
Thank you

**Comment by soapy1** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier ☹️

Cheers!
