### ISSUE TITLE
Windows Hyper-V: smb mounted shares are broken after host OS hibernate/resume after some hours

### ISSUE THREAD

**Issue by marcelser** [hashicorp/vagrant#12647]
### Vagrant version
2.2.19

### Host operating system
Windows 10 64-bit

### Guest operating system
CentOS 7

### Vagrantfile

```ruby
...
perl.vm.synced_folder "#{UTM_ANSIBLE_DIR}", "/home/vagrant/ansible_dev", id: "ansible_dev",owner: "vagrant", type:"smb", smb_username: SMB_USER, smb_password: SMB_PASS
...
```

### Expected behavior

smb shares are still mounted on host machine after OS hibernate/resume

### Actual behavior

smb shares are disconnected when I hibernate for some hours (usually over night). When I try to access them next day after resume guest os block very often (for 1-2 minutes) even if I get directory listing, no changes from host os are reflected on guest os. Interestingly if I only do a quick hibernate for some minutes and bring machine backup it still works. So it might be some sort of timeout which breaks smb share.

### Steps to reproduce

1. start vagrant box on hyper-v with smb mounted shares
2. hibernate host os for at lest 8 hours ("real" hibernate where machine powers off completely not just goes in power saving mode and needs power-switch to turn back on. This mode needs to be enabled in Windows and is not enabled by default)
3. connect to hyper-v box and try to access an smb mounted path and you experience the problems

**Comment by kaitlincart** [comment]
Hi,

Thank you for your feedback and recommendation. However, due to limited resources, we have not been unable to prioritize this for over a year. We are now closing this issue so that it is not stagnate.

Thanks,
Kait
