### ISSUE TITLE
How to specify network when provisioning in vagrant

### ISSUE THREAD

**Issue by ShapedTime** [hashicorp/vagrant#12649]
I have multiple networks specified in my vagrantfile and only one of them are accessible from outside. When the vagrant starts provisioning, sometimes it chooses the wrong network (IP) to connect to the VM and it fails. Is it possible to specify which network should vagrant choose when provisioning? If not, I would like to know how vagrant chooses which IP to use when provisioning.

**Comment by soapy1** [comment]
Hey there, thanks for opening an issue with Vagrant. Details about how Vagrant connects to the guest can be different per provisioner. The provisioner documentation should provide this info. You can find that on the Vagrant docs website https://developer.hashicorp.com/vagrant/docs/provisioning. Without more information about the situation, it's hard to make any more specific suggestions.

For general use questions please open up a new topic on the Vagrant discuss forum https://discuss.hashicorp.com/c/vagrant/24. 

I'm going to go ahead and close this issue but if there is still a problem please open up a new issue. Remember to fill in the issue template with important details about the problem you are facing 😄
