### ISSUE TITLE
Vagrant ssh:“posix_spawnp: No such file or directory”

### ISSUE THREAD

**Issue by kunlunsiqu** [hashicorp/vagrant#12655]
![](https://gitee.com/sif_one/drawing-bed/raw/master/1094a460d3446fe7aad1ecf8a98951ae20f529a5.png)

❯ vagrant ssh
posix_spawnp: No such file or directory

I connect to vagrant as usual, but he reports vagrant ssh posix_spawnp: No such file or directory.

I haven't touched vagrant for almost half a month, and the virtual machine. Does anyone have any friends who have encountered similar problems? how did you solve it?

I read the error message, it seems that the exact directory is needed, you can take a look at https://serverfault.com/questions/956613/windows-10-ssh-proxycommand-posix-spawn-no-such-file-or -directory

It was found that the problem was initially caused in the vscode-remote-release Project, which sparked a lot of discussion, and finally vscode-remote-release fixed the problem, I don't know if vagrant also has this problem?

Thank you so much.

**Comment by kunlunsiqu** [comment]
I finally found out that it was a problem with openssh, mainly the configuration of .ssh/config.

**Comment by maruf061** [comment]
Informative!
