### ISSUE TITLE
Vagrant  VMware freezes at vagrant up 

### ISSUE THREAD

**Issue by nimit25** [hashicorp/vagrant#12675]
### Vagrant logs
[vagrant.log](https://github.com/hashicorp/vagrant/files/8018843/vagrant.log)
### Vagrant version
Vagrant 2.2.19

### Host operating system

MacOS 11.6.2 
Vmware Fusion - 12.2.1 
vagrant-vmware-desktop - 3.0.1

### Guest operating system

hashicorp/precise64 ubuntu for vmware

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provider :vmware_desktop do |vmware|
    vmware.vmx["ethernet0.pcislotnumber"] = "32"
  end  
end

```

Please ensure the Vagrantfile provided is a minimal Vagrantfile which contains
only the required configuration to reproduce the behavior. Please note that if
your Vagrantfile contains an excess of configuration unrelated the the reported
issue, or is in a different format, we may be unable to assist with your issue.
Always start with a minimal Vagrantfile and include only the relevant configuration
to reproduce the reported behavior.

### Expected behavior

It should've ran `vagrant up` without any issue. 

### Actual behavior

What actually happened?
```
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Checking if box 'hashicorp/precise64' version '1.1.0' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
==> default: Forwarding ports...
    default: -- 22 => 2222
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```
### Steps to reproduce

1. vagrant box add hashicorp/precise64 (choose 3 for vmware)
2. vagrant init hashicorp/precise64
3. vagrant up

**Comment by kaitlincart** [comment]
Hi,

I'm sorry we weren't able to respond sooner. There have been multiple Vagrant releases since the original report, we recommend that you upgrade if you still have timeout issues. I'm going to close this issue now, but feel free to reopen if needed.

Thanks,
Kait
