### ISSUE TITLE
>

### ISSUE THREAD

**Issue by virgiliojr94** [hashicorp/vagrant#12680]
> 
> 
> For me, the solution came from [this answer](https://askubuntu.com/a/229908/323990):
> 
> ```
> sudo apt-get autoremove virtualbox-dkms
> sudo apt-get install build-essential linux-headers-`uname -r` dkms virtualbox-dkms
> ```

This worked for me

_Originally posted by @palade in https://github.com/hashicorp/vagrant/issues/8687#issuecomment-462148523_

**Comment by oradwell** [comment]
@virgiliojr94 what is this?

**Comment by virgiliojr94** [comment]
is the solution to a problem that occurred when using vagrant with virtual box.
