### ISSUE TITLE
vagrant up still cannot connect via ssh on initial startup. vagrant ssh works fine.

### ISSUE THREAD

**Issue by pmhausen** [hashicorp/vagrant#12681]
### Vagrant version

$ vagrant -v
Vagrant 2.2.19

### Host operating system

MacOS Monterey 12.2.1

### Guest operating system

FreeBSD 13.0-p7 (OPNsense)

### Vagrantfile

This Vagrantfile downloads a standard FreeBSD 13.0 box and on initial provisioning turns it into an OPNsense firewall.
In the process OPNsense replaces the FreeBSD bundled sshd with OpenSSH_8.8p1 from ports. Initial provisioning works,
after that subsequent `vagrant up` commands fail because the builtin ruby SSH cannot authenticate. `vagrant ssh` works.
I need `vagrant up` to work, because without the NFS mount I won't have my development environment available in the box.

My project can be found on github:
https://github.com/punktDe/vagrant-opnsense

```ruby
Vagrant.configure(2) do |config|

  # Which base box to use - this is FreeBSD 12.1 for now according to
  # https://github.com/opnsense/update
  $opnsense_box = 'punktde/freebsd-130-ufs'
  
  # Which OPNsense release to install
  $opnsense_release = '22.1'

  # IP address of the firewall in the host-only network
  $virtual_machine_ip = '192.168.1.1'

  # Configure folder sharing
  $vagrant_mount_path = '/var/vagrant'
  config.vm.synced_folder '.', '/vagrant', id: 'vagrant-root', disabled: true
  config.vm.synced_folder '.', "#{$vagrant_mount_path}", :nfs => true, :nfs_version => 3

  # Enable SSH keepalive to work around https://github.com/hashicorp/vagrant/issues/516
  config.ssh.keep_alive = true

  # Configure proper shell for FreeBSD
  config.ssh.shell = '/bin/sh'

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search
  config.vm.box = $opnsense_box

  # Create a private network, which allows host-only access to the machine
  # using a specific IP
  config.vm.network 'private_network', ip: $virtual_machine_ip, auto_config: true

  # Customize build VB settings
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 4096
    vb.cpus = 1
  end

  # Transfer config file snippets into VM
  config.vm.provision "file", source: "files", destination: "files"

  # Bootstrap OPNsense
  config.vm.provision 'shell', inline: <<-SHELL

    # Download the OPNsense bootstrap script
    fetch -o opnsense-bootstrap.sh https://raw.githubusercontent.com/opnsense/update/master/src/bootstrap/opnsense-bootstrap.sh.in

    # Remove reboot command from bootstrap script
    sed -i '' -e '/reboot$/d' opnsense-bootstrap.sh

    # Start bootstrap
    sh ./opnsense-bootstrap.sh -r #{$opnsense_release} -y

    # Set correct interface names so OPNsense's order matches Vagrant's
    sed -i '' -e 's/mismatch0/em1/' /usr/local/etc/config.xml
    sed -i '' -e 's/mismatch1/em0/' /usr/local/etc/config.xml

    # Remove IPv6 configuration from WAN
    sed -i '' -e '/<ipaddrv6>dhcp6<\\/ipaddrv6>/d' /usr/local/etc/config.xml

    # Remove IPv6 configuration from LAN
    sed -i '' -e '/<ipaddrv6>track6<\\/ipaddrv6>/d' /usr/local/etc/config.xml
    sed -i '' -e '/<subnetv6>64<\\/subnetv6>/d' /usr/local/etc/config.xml
    sed -i '' -e '/<track6-interface>wan<\\/track6-interface>/d' /usr/local/etc/config.xml
    sed -i '' -e '/<track6-prefix-id>0<\\/track6-prefix-id>/d' /usr/local/etc/config.xml

    # Enable SSH by default
    sed -i '' -e '/<group>admins<\\/group>/r files/ssh.xml' /usr/local/etc/config.xml

    # Allow SSH on all interfaces
    sed -i '' -e '/<filter>/r files/filter.xml' /usr/local/etc/config.xml

    # Do not block private networks on WAN
    sed -i '' -e '/<blockpriv>1<\\/blockpriv>/d' /usr/local/etc/config.xml

    # Create XML config for Vagrant user
    key=$(b64encode -r dummy <.ssh/authorized_keys | tr -d '\n')
    echo "      <authorizedkeys>${key}</authorizedkeys>" >files/vagrant2.xml
    cat files/vagrant[123].xml >files/vagrant.xml

    # Add Vagrant user - OPNsense style
    sed -i '' -e '/<\\/member>/r files/admins.xml' /usr/local/etc/config.xml
    sed -i '' -e '/<\\/user>/r files/vagrant.xml' /usr/local/etc/config.xml

    # Change home directory to group nobody
    chgrp -R nobody /usr/home/vagrant

    # Change sudoers file to reference user instead of group
    sed -i '' -e 's/^%//' /usr/local/etc/sudoers.d/vagrant

    # Reboot the system
    shutdown -r now

  SHELL
end
```

### Debug output

https://gist.github.com/pmhausen/d6bec5a244ac6332ed2ddeee888f3586

### Expected behavior

`vagrant up` should work.

### Actual behavior

```
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    ...
 ```

### Steps to reproduce

1. Provision an OPNsense in Vagrant with my project.
2. After initial provisioning and reboot: `vagrant halt`
3. `vagrant up`

### References
 - https://github.com/hashicorp/vagrant/issues/12344
 - https://github.com/hashicorp/vagrant/issues/12418

**Comment by pmhausen** [comment]
Nobody? After 6 weeks? Seriously?

**Comment by landon8848** [comment]
I spent quite a bit of time troubleshooting this myself over the past couple of days, and I'm happy to share my findings with you after I was able to provision successfully.  It looks like your problem is here:

```
E, [2022-02-13T23:37:56.529532 #37927] ERROR -- net.ssh.authentication.session[ddb8]: all authorization methods failed (tried none, publickey)

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not ready: #<Vagrant::Errors::SSHAuthenticationFailed: SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.>
```

...which leads me to believe it's a permissions issue on the guest, further demonstrated by the successful execution of `vagrant ssh`. If you can paste the `ssh` authentication block from the scrollback at runtime (without the debug flag), along with the post-provision output of `vagrant ssh-config`, it should point us in the right direction.

**Comment by pmhausen** [comment]
Access rights for the keys are definitely not the cause. As I wrote current OpenSSH disables rsa pubkey algorithm but offers rsa256 and rsa512 - which is incorrectly interpreted by the bundled Ruby SSH module. As I also wrote `vagrant ssh` works, because it uses the local ssh binary, not the Ruby module.

As soon as I add
```
PubkeyAcceptedAlgorithms +ssh-rsa
```
to the sshd config in the guest, `vagrant up` works again. I updated the documentation for my project accordingly.

**Comment by landon8848** [comment]
Ah, I see. Is your preferred course of action then to:

a. Update the vagrant ssh module to use rsa256/512
b. Provision openssh-server to a release that supports rsa by default
c. Have something execute at runtime that will either enable rsa for openssh-server prior to trying to connect to the machine

**Comment by pmhausen** [comment]
OpenSSH server has deprecated ssh-rsa and will axe it at some point in the future. RSA(1) is dead. RSA 256 or 512 are not (yet). So a. is really the only option. rsa256/512 are still considered reasonably secure. The problem is with this Ruby-thingy (and this is where I am at the end of my wits, no  clue about Ruby beyond Vagrant config files) that incorrectly parses the algorithms offered by OpenSSH (e.g. rsa256) and then decices "hey, that's rsa, let's use that."

And again, `vagrant ssh` works perfectly fine, because it calls a regular locally installed SSH binary. It's the builtin that is used in `vagrant up` that is causing problems.

**Comment by landon8848** [comment]
Yeah I get the `vagrant ssh` functionality, but if it uses the native binary as opposed to the Ruby wrapper, that seems like an odd disparity in the two utilities.

Admittedly i have not looked into the vagrant module source (on my phone atm) so I’m wondering what the reasoning is for the two different invocation methods. If they’re using Ruby gems then these issues should have been resolved with [https://github.com/net-ssh/net-ssh/pull/811](net-ssh PR 811), but maybe their implementation is flawed.

As time permits, I should search for net-ssh issues in hashicorp/vagrant repo and create an issue if none exists. I haven’t run into this with other Hashi products, I would hope it’s limited to Vagrant.

**Comment by landon8848** [comment]
Haha I meant “search other Hashicorp repos, not vagrant since that’s where we are now :)

**Comment by pmhausen** [comment]
Fixed per https://github.com/hashicorp/vagrant/pull/12584
