### ISSUE TITLE
Vagrant up hangs on  vmware boxes if the GUI isn't running - M1 Mac ARM / VMWare tech preview

### ISSUE THREAD

**Issue by mattbryson** [hashicorp/vagrant#12695]
Launching VMware in headless mode hangs on "==> default: Waiting for the VM to receive an address..."

However, With the GUI open, or with the `vm.gui = true` it works fine.

From the logs, it appears to be related to this (which just loops)

```
 INFO vmware_driver: Trying vmrun getGuestIPAddress...
 INFO subprocess: Starting process: ["/Applications/VMware Fusion.app/Contents/Library/vmrun", "getGuestIPAddress", "/Users/matt/test/.vagrant/machines/default/vmware_desktop/6900b117-ab8e-4f1a-aaf1-3a697ddd238a/Other Linux 5.x kernel 64-bit Arm.vmx"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO vmware_driver: vmrun getGuestIPAddress failed: VMRunError
```

### Vagrant version
Vagrant 2.2.19
vagrant-vmware-desktop (3.0.1, global)
vagrant-vmware-utility: 1.0.21

VMware Tech preview Professional Version e.x.p (18656771) (for M1 macs)

Alias has been added to map to the Tech preview, rather than the production version of VMWare.
`sudo ln -s /Applications/VMware\ Fusion\ Tech\ Preview.app /Applications/VMware\ Fusion.app`

### Host operating system
MacOS Monterey 12.2.1 
M1 ARM chip

### Guest operating system
spox/ubuntu-arm

as well as other ARM linux distros (doesn't appear to be distro related)

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "spox/ubuntu-arm"
  config.vm.box_version = "1.0.0"
  
  config.vm.provider :vmware_desktop do |vmware|
    #vmware.gui = true
    vmware.allowlist_verified = true
    vmware.vmx["ethernet0.pcislotnumber"] = "160"
  end
end
```

### Debug output
[gist](https://gist.github.com/mattbryson/d29553e02ba547c2eba85c34c96cc3d9
)
### Expected behavior

Vagrant up should launch and connect to the guest server regardless of the `vm.gui` setting.

### Actual behavior

If `vm.gui` is not true, vagrant up just hangs

### Steps to reproduce

1. M1 Mac ARM Chip
2. Install VM Ware Tech Preview : https://customerconnect.vmware.com/downloads/get-download?downloadGroup=FUS-PUBTP-2021H1
3. Install the VMware tools `vagrant plugin install vagrant-vmware-desktop`
4.  Install the VMware utility `brew install vagrant-vmware-utility`
5.  `vagrant up` using the attached vagrant file

### References
Similar issues found here but with no solutions 

https://github.com/hashicorp/packer/issues/6691
https://github.com/hashicorp/vagrant/issues/9902

**Comment by fredngo** [comment]
I can confirm as well, but it's not consistent. Sometimes I have vm.gui=false and it works as well. I'm pretty flummoxed.

**Comment by fredngo** [comment]
OK, so it **does** seem like the latest kernel is problematic. Other reports [here](https://github.com/utmapp/UTM/issues/2682) and [here](https://communities.vmware.com/t5/Fusion-for-Apple-Silicon-Tech/Unable-to-launch-a-VM-after-fresh-install-with-latest-technology/m-p/2899990).

So, the workarounds are:

1) Keep VMWare Fusion open in the background. `vm.gui = true` is actually **not** necessary, as long as the program is running in the background, the machines will boot up.
2) Do **not** upgrade to the latest kernel. The `bytesguy/ubuntu-server-20.04-arm64` image works just fine.

**Comment by mattbryson** [comment]
Ah great 👍.

I'll try using the older image and see what happen.

**Comment by aman09-git** [comment]
Hey All,

I have followed each steps as given but still getting the below error, can anyone please have a look at this.

amansrivastava@Amans-MacBook-Air ubuntu % vagrant up
Vagrant encountered an unexpected communications error with the
Vagrant VMware Utility driver. Please try to run the command
again. If this error persists, please contact support@hashicorp.com
amansrivastava@Amans-MacBook-Air ubuntu % 

Trying to find out what is happening and what's going wrong here .

Currently I m in ubuntu directory under which I have vagrant file with the content , still Its not getting started. 

Thanks in advance !!

**Comment by sourovroy** [comment]
With `vmware.gui = true` works for me but without it just hang up.

**Comment by bytehow** [comment]
I was running into the same issue on macOS 11.6.8. Solved by upgrading to the following:
- Vagrant VMWare Utility 1.0.21
- `vagrant_vmware_desktop` plugin 3.0.1
- Vagrant VMWare Fusion/Player 12.2.4

**Comment by tikondrus** [comment]
I've caught the same issue

Vagrant VMWare Utility 1.0.21
vagrant_vmware_desktop plugin 3.0.1
Vagrant VMWare Fusion TechPreview  e.x.p (20191287)
Macos 12.6
Chip Apple M1

I've tried the listed bellow boxes and all of them works only with vmware.gui = true

bytesguy/ubuntu-server-20.04-arm64 and 
psemel/ubuntu-17.04 
rkrause/ubuntu-20.04-arm64    
rshash/Ubuntu_20.04-M1-Mac   
spox/ubuntu-arm

**Comment by chrisroberts** [comment]
Hi everybody,

The cause of this issue has been documented [here](https://github.com/hashicorp/vagrant-vmware-desktop/issues/53#issuecomment-1550458042) and is now [resolved](https://github.com/hashicorp/vagrant-vmware-desktop/issues/53#issuecomment-1550458042) by upgrading your Vagrant installation.

Cheers!

**Comment by fredngo** [comment]
I am happy as a clam that this has been fixed. `vm.gui = true` is no longer necessary in my `Vagrantfile`, and it's no longer even necessary to have the VMWare Fusion app open at all. 🎉 Great job!
