### ISSUE TITLE
Proxy is invalid

### ISSUE THREAD

**Issue by taylorren** [hashicorp/vagrant#12696]
This is a replica of https://github.com/hashicorp/vagrant/issues/12227. I would like to re-open it since I have the same issue. 

 try to update my vagrant box using vagrant box update but it throws me an error:

```
        12: from D:/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
        11: from D:/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
        10: from D:/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
         9: from D:/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
         8: from D:/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/cloud/auth/middleware/add_downloader_authentication.rb:25:in `call'
         7: from D:/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/cloud/auth/middleware/add_downloader_authentication.rb:25:in `new'
         6: from D:/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/cloud/client/client.rb:36:in `initialize'
         5: from D:/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/commands/cloud/client/client.rb:36:in `new'
         4: from D:/Vagrant/embedded/gems/2.2.19/gems/vagrant_cloud-3.0.5/lib/vagrant_cloud/client.rb:61:in `initialize'
         3: from D:/Vagrant/embedded/gems/2.2.19/gems/excon-0.88.0/lib/excon.rb:142:in `new'
         2: from D:/Vagrant/embedded/gems/2.2.19/gems/excon-0.88.0/lib/excon.rb:142:in `new'
         1: from D:/Vagrant/embedded/gems/2.2.19/gems/excon-0.88.0/lib/excon/connection.rb:80:in `initialize'
D:/Vagrant/embedded/gems/2.2.19/gems/excon-0.88.0/lib/excon/connection.rb:581:in `setup_proxy': Proxy is invalid (Excon::Error::ProxyParse)
```
My vagrant is 2.2.19 running under Windows 11. I disabled my ShadowSocks proxy but the error persists.

I did a search and tried to `vagrant plugin install vagrant-proxyconf` but it seemed this plugin in no longer available or I'm not able to install it. Frankly speaking, I am not intended to use a proxy to vagrant something. 

`vagrant up` is working, though. 

I have no proxy related configuration in my Vagrantfile.

Your help will be much appreciated.

**Comment by Abdipour** [comment]
I came across this issue today. It's because of `http_proxy` and `https_proxy`. Clear these variables by running the below commands and try again:
```

export http_proxy=
export https_proxy=

```
If you have to use a proxy for this connection, check the proxy address and make sure to start with `http://` or `https://`.

**Comment by chrisroberts** [comment]
The environment variables described above are generally the cause for this type of error. Please feel free to open a new issue if the error persists.
