### ISSUE TITLE
vagrant-vmware-utility crash "Failed to create CSSymbolicatorRef - corpse still valid"

### ISSUE THREAD

**Issue by fhenri** [hashicorp/vagrant#12694]
Vagrant-vmware-utility runs as a service however with latest macOS version, it fails to start with below error

Error Formulating Crash Report:
_dyld_process_info_create failed with 6
dyld_process_snapshot_get_shared_cache failed
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯

EOF

(Full crash report is enclosed)

## Vagrant version

2.2.19

## Vagrant vmware utility version

1.0.21

## VMWare Fusion version

12.2.1 (18811640)

## Host operating system

macOS 12.2.1

[vagrant-vmware-utility-2022-02-24-092009.txt](https://github.com/hashicorp/vagrant/files/8130912/vagrant-vmware-utility-2022-02-24-092009.txt)

**Comment by aspraveen** [comment]
i am also noticing same error during startup
=============
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 389E662C-4D0C-4870-A403-36E36BFFCB00
CrashReporter Key:   AB3DF81F-72FA-91E2-2DB2-1E28A2BEB02E
Hardware Model:      MacBookPro13,2
Process:             vagrant-vmware-utility [126]
Path:                /opt/vagrant-vmware-desktop/*/vagrant-vmware-utility
Identifier:          vagrant-vmware-utility
Version:             ???
Code Type:           X86-64 (Native)
Role:                Unspecified
Parent Process:      launchd [1]
Coalition:           com.vagrant.vagrant-vmware-utility [79]

Date/Time:           2022-05-30 05:54:41.5082 +0300
Launch Time:         2022-05-30 05:54:39.0515 +0300
OS Version:          macOS 12.4 (21F79)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 15 Terminated: 15
Terminating Process: launchd [1]

Highlighted by Thread:  0

Backtrace not available

No thread state (register information) available

Binary Images:
Binary images description not available

Error Formulating Crash Report:
_dyld_process_info_create failed with 6
dyld_process_snapshot_get_shared_cache failed
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯
thread_get_state(PAGEIN) returned 0x10000003: (ipc/send) invalid destination port
thread_get_state(EXCEPTION) returned 0x10000003: (ipc/send) invalid destination port
thread_get_state(FLAVOR) returned 0x10000003: (ipc/send) invalid destination port

EOF

-----------
Full Report
-----------

{"app_name":"vagrant-vmware-utility","timestamp":"2022-05-30 05:54:43.00 +0300","app_version":"","slice_uuid":"00000000-0000-0000-0000-000000000000","build_version":"","platform":0,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.4 (21F79)","incident_id":"389E662C-4D0C-4870-A403-36E36BFFCB00","name":"vagrant-vmware-utility"}
{
  "uptime" : 6,
  "procLaunch" : "2022-05-30 05:54:39.0515 +0300",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 0,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro13,2",
  "procStartAbsTime" : 4360510214,
  "coalitionID" : 79,
  "osVersion" : {
    "train" : "macOS 12.4",
    "build" : "21F79",
    "releaseType" : "User"
  },
  "captureTime" : "2022-05-30 05:54:41.5082 +0300",
  "incident" : "389E662C-4D0C-4870-A403-36E36BFFCB00",
  "bug_type" : "309",
  "pid" : 126,
  "procExitAbsTime" : 6215977060,
  "cpuType" : "X86-64",
  "procName" : "vagrant-vmware-utility",
  "procPath" : "\/opt\/vagrant-vmware-desktop\/*\/vagrant-vmware-utility",
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.vagrant.vagrant-vmware-utility",
  "crashReporterKey" : "AB3DF81F-72FA-91E2-2DB2-1E28A2BEB02E",
  "bridgeVersion" : {"status":"<device not connected>"},
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGKILL (Code Signature Invalid)"},
  "termination" : {"flags":0,"code":15,"namespace":"SIGNAL","indicator":"Terminated: 15","byProc":"launchd","byPid":1},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "legacyInfo" : {
  "threadHighlighted" : 0
},
  "reportNotes" : [
  "_dyld_process_info_create failed with 6",
  "dyld_process_snapshot_get_shared_cache failed",
  "Failed to create CSSymbolicatorRef - corpse still valid ¯\\_(ツ)_\/¯",
  "thread_get_state(PAGEIN) returned 0x10000003: (ipc\/send) invalid destination port",
  "thread_get_state(EXCEPTION) returned 0x10000003: (ipc\/send) invalid destination port",
  "thread_get_state(FLAVOR) returned 0x10000003: (ipc\/send) invalid destination port"
]
}

**Comment by chrisroberts** [comment]
Hi there,

This issue should be resolved in the latest utility release. If you are still encountering this error, please feel free to open a new issue and I'll investigate further.

Cheers
