### ISSUE TITLE
runtime: bsdthread_register error with vagrant 2.0.2 on OSX 12.2

### ISSUE THREAD

**Issue by SharavananEswar** [hashicorp/vagrant#12700]
### Vagrant version
2.0.2

### Host operating system
Mac OSX 12.2

### Debug output
vagrant -v

fatal error: runtime: bsdthread_register errorruntime stack:runtime.throw(0x10e05d8, 0x21)    /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0x7ff7bfeff960 sp=0x7ff7bfeff940runtime.goenvs()    /usr/local/go/src/runtime/os_darwin.go:108 +0xa0 fp=0x7ff7bfeff990 sp=0x7ff7bfeff960runtime.schedinit()    /usr/local/go/src/runtime/proc.go:486 +0xa1 fp=0x7ff7bfeff9d0 sp=0x7ff7bfeff990runtime.rt0_go(0x7ff7bfeffa08, 0x2, 0x7ff7bfeffa08, 0x0, 0x1000000, 0x2, 0x7ff7bfeffb50, 0x7ff7bfeffb58, 0x0, 0x7ff7bfeffb5b, ...)    /usr/local/go/src/runtime/asm_amd64.s:158 +0x183 fp=0x7ff7bfeff9d8 sp=0x7ff7bfeff9d 

vagrant plugin list
fatal error: runtime: bsdthread_register errorruntime stack:runtime.throw(0x10e05d8, 0x21)    /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0x7ff7bfeff950 sp=0x7ff7bfeff930runtime.goenvs()    /usr/local/go/src/runtime/os_darwin.go:108 +0xa0 fp=0x7ff7bfeff980 sp=0x7ff7bfeff950runtime.schedinit()    /usr/local/go/src/runtime/proc.go:486 +0xa1 fp=0x7ff7bfeff9c0 sp=0x7ff7bfeff980runtime.rt0_go(0x7ff7bfeff9f8, 0x3, 0x7ff7bfeff9f8, 0x0, 0x1000000, 0x3, 0x7ff7bfeffb48, 0x7ff7bfeffb50, 0x7ff7bfeffb57, 0x0, ...)    /usr/local/go/src/runtime/asm_amd64.s:158 +0x183 fp=0x7ff7bfeff9c8 sp=0x7ff7bfeff9c0

### Expected behavior

Vagrant should work without any issues

### Actual behavior

Vagrant 2.0.2 installation got completed. But when running CLI commands, getting an error.

### Steps to reproduce

1. Try install vagrant 2.0.2 in Mac OSX 12.2 host machine
2. Once installation completed, try to run vagrant cli commands

### References

**Comment by taigetco** [comment]
I have the same problem after upgrade MAC OS to Monterey. you can refer https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue. After upgrade vagrant to 2.2.19, the error is fixed

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
