### ISSUE TITLE
vagrant up,  "command not found"

### ISSUE THREAD

**Issue by colespen** [hashicorp/vagrant#12701]
Hello, brand new to the coding world here: 
I am setting up a VM for a prep course and I am unable to download the vagrant image from the Lighthouse Labs host machine. I have first installed VirtualBox 6.1.16 then Vagrant 2.2.13 as specified but I cannot make this command function properly in the command line. I am not sure what I am doing wrong. 

```
gutterluck:lighthouse Jingles$ vagrant up
-bash: vagrant: command not found
```

FYI downloading 'Vagrantfile' did work. 
```
gutterluck:lighthouse Jingles$ curl -O http://d10ofk0qhbh8u9.cloudfront.net/vagrant/Vagrantfile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3921  100  3921    0     0  15604      0 --:--:-- --:--:-- --:--:-- 15684
```
I also have installed node.js 16.14.0 if that makes any difference.

Running macOS Mojave 10.14.6.
Thanks in advance for your help. 
Apologies if this is in the wrong repository.

**Comment by mrzasa** [comment]
Vagrant is not installed on your machine apparently, follow the steps described in https://www.vagrantup.com/docs/installation

**Comment by colespen** [comment]
Thanks for your reply @mrzasa but I have since resolved this issues.
Cheers
