### ISSUE TITLE
Windows 2016 with Vagrant

### ISSUE THREAD

**Issue by RochelleNN** [hashicorp/vagrant#12717]
Hello,

I've been trying to install Windows 2016 with vagrant in the command line on my surface 4 laptop with the current windows 11. I keep getting an error message ( I will post it below). Since this has been happening now my other virtual machine's that I created for linux  are not loading. 

If anyone is able to help please do.  Thank you. 

This is the error message that I'm getting.

"Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value."

**Comment by ferxohn** [comment]
I'm also having this problem using Vagrant in Windows 10 and 11. In my case, I'm trying to create an Ubuntu 20.04 VM, but I ended up receiving that message. Vagrant gets stuck trying to connect to the VM. By contrast, this doesn't happen in macOS Monterey 12.3.1.

![WhatsApp Image 2022-03-31 at 11 52 55 PM](https://user-images.githubusercontent.com/35642546/161197275-044e5f0a-8689-4218-ac2d-1008e2388981.jpeg)

I'm using Vagrant 2.2.19 and VirtualBox 6.1.32 r149290 in the three machines (Windows 10 Pro, Windows 11 Pro and macOS Monterey).

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue, however, there is not enough information to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions to collect your host and guest information, Vagrantfile, the version of Vagrant, and the debug output. Without that information it is very challenging for us to assist you.

Please open a new issue with that information included. Thank you!
