### ISSUE TITLE
The following SSH command responded with a non-zero exit status "umount /mnt"

### ISSUE THREAD

**Issue by nbro** [hashicorp/vagrant#12724]
I am getting this error

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

umount /mnt

Stdout from the command:



Stderr from the command:

umount: /mnt: not mounted
```
I'm trying to set up a project I had developed a long time ago with Vagrant and Ansible. I got the error above, but I don't really know why I'm getting it. It seems to be related to `/mnt`. Unfortunately, I cannot share this code, because I had developed it in the context of an internship with a company a few years ago. 

- `Vagrant 2.2.19`
- Provider: VirtualBox 6.1
- Host: Mac OS 12.3 (Monterey)

In any case, I was able to vagrant up (ssh inside the VM).

**Comment by chrisroberts** [comment]
Hi there,

The error you encountered was the result of some provisioner attempting to unmount the `/mnt` directory and it was not mounted. Without a minimal Vagrantfile and a gist of debug output to inspect, I won't be able to provide any more help with this error than that.

Cheers!
