### ISSUE TITLE
Silent installing Vagrant ignore the VAGRANTAPPDIR parameter

### ISSUE THREAD

**Issue by quintonn** [hashicorp/vagrant#12728]
I am trying to set up an unattended install of vagrant using vagrant_2.2.19_i686.msi.  
I have tried both the following commands:  
1. start /wait msiexec /qn /norestart /i "vagrant_2.2.19_i686.msi" VAGRANTAPPDIR="C:\Program Files\HashiCorp\Vagrant"  
2. msiexec /qn /norestart /i "vagrant_2.2.19_i686.msi" VAGRANTAPPDIR="C:\Program Files\HashiCorp\Vagrant"  

And in both cases Vagrant installs to the default location instead.  

I found the VAGRANTAPPDIR setting from this StackOverflow page: https://stackoverflow.com/questions/18932154/silent-install-of-vagrant-to-preferred-directory-on-windows  

How can I silently install Vagrant to my desired location?

**Comment by kaitlincart** [comment]
Hi,  

We're you able to install Vagrant successfully or is this still an issue? If we don't hear from you within 3 days we will go ahead and close this issue. 

Thanks,
Kat

**Comment by quintonn** [comment]
hi,
I think I managed in the end or just moved on, it was a long time ago, sorry, i can't recall exactly.
But you can close this ticket, thanks
