### ISSUE TITLE
mount.nfs: mounting failed, reason given by server: No such file or directory

### ISSUE THREAD

**Issue by nbro** [hashicorp/vagrant#12726]
### Description

I get the following error when `vagrant up --provision-with ansible`

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 192.168.56.1:/Users/nbro/Desktop/path_to_my_project_with_vagrantfile /vagrant

Stdout from the command:



Stderr from the command:

mount.nfs: mounting 192.168.56.1:/Users/nbro/Desktop/path_to_my_project_with_vagrantfile failed, reason given by server: No such file or directory
```

I tried to execute 

```
vagrant ssh -- -t 'yum clean all; sudo yum -y update; exit'
```

Then `vagrant halt` and then `vagrant up --provision-with ansible` again and I get another error

```
...
==> default: Exporting NFS shared folders...
NFS is reporting that your exports file is invalid. Vagrant does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:2: sandbox_check failed. nfsd has no read access to "/Users/nbro/Desktop/path_to_my_project_with_vagrantfile"
```

In the end, though, it logged into the box, even if there's this error.

### Configurations

- Guest/box: generic/centos8
- Host: Mac OS 12.3
- Vagrant 2.2.19

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. There have been multiple Vagrant releases since the original report, we recommend upgrading. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem.

Cheers!
