### ISSUE TITLE
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory

### ISSUE THREAD

**Issue by nbro** [hashicorp/vagrant#12725]
### Description

When I `vagrant ssh` into the CentOS box, I get the following error

> -bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory

There are 1-2 related issues here on this issue tracker (e.g. [here](https://github.com/hashicorp/vagrant/issues/1102) and [here](https://github.com/hashicorp/vagrant/issues/1188)) and there are a few other blog posts on the web about it, but I still don't understand how to solve this problem and what it is caused by.

Do I need to change something in the host or guest machine? It's unclear. I tried to execute `sudo yum reinstall glibc-common` in the guest CentOS box, but this didn't solve the problem. 

In [this issue](https://github.com/hashicorp/vagrant/issues/1102), the author says to add the line `LC_CTYPE="en_US"` to `/etc/default/locale`, but I don't have this file either on the guest or host machine. Should I manually create it? Where? In the guest or host machine?

I tried to add the lines (mentioned [here](https://github.com/hashicorp/vagrant/issues/1188#issuecomment-219366309)) to the `.bash_profile` of my CentOS box (or guest VM), but that didn't solve the problem.

### Configurations

- Box: `config.vm.box = "centos/7"`
- Vagrant 2.2.19
- Mac OS 12.3 (Monterey)

**Comment by ladar** [comment]
Anyways, on CentOS 7 you'll want to run something like:
On CentoOS 7 you might want to try running:
 `sudo localectl set-locale LANG=en_US.UTF8`
or
`sudo localedef -v -c -i en_US -f UTF-8 en_US.UTF-8`
I'm surprised the CentOS guys got that wrong.

**Comment by chrisroberts** [comment]
This issue should be solvable using the last comment. 

Cheers!
