### ISSUE TITLE
synced_folder cannot be disabled

### ISSUE THREAD

**Issue by Nathie1000** [hashicorp/vagrant#12747]
# Vagrant version
Vagrant 2.2.19.

# Host operating system
Windows 10 Enterprise 19043.1586
Hypver-V

# Guest operating system
Debain 9

# Vagrantfile

Vagrant.configure("2") do |config|
 #Note this is my own box but it happens with any box.
  config.vm.box = "forta"
  config.vm.synced_folder "", "", disabled: true
end

# Debug output
<https://gist.github.com/Nathie1000/b1736bf88cefa23a0b0f91377053db85>

# Expected behavior
Nothing happens

# Actual behavior
I get the following prompt:

==> default: Preparing SMB shared folders...
         default: You will be asked for the username and password to use for the SMB
         default: folders shortly. Please use the proper username/password of your
        default: account.
        default: Password (will be hidden):
==> default: Credentials incorrect. Please try again.
==> default:
         default: Username ():
          default: Password (will be hidden):

I do not have SMB setup nor a password, so now i'm stuck on this prompt.
When `vagrant up` is ran for a second time this prompt does not appear again and the process continues normally.

# Workaround
Keep pressing enter until vagrant gives up, or force the process to end. Then running vagrant again.

# Steps to reproduce
1. Initialize any project
2. Add `config.vm.synced_folder "", "", disabled: true` to the vagrant file.
3. run `vagrant up`

**Comment by chrisroberts** [comment]
Hi there,

The synced folder can be disabled by adding the following to your vagrantfile:

```ruby
config.vm.synced_folder "/vagrant", ".", disabled: true
```

Cheers!
