### ISSUE TITLE
working with virtualbox networking mode "Not attached" but serial port enabled

### ISSUE THREAD

**Issue by loynoir** [hashicorp/vagrant#12741]
### Keyword
- vagrant up
- ssh
- virtualbox networking mode: "Not attached"
- serial console

### Usage
Cut networking access from a vm.

https://docs.oracle.com/en/virtualization/virtualbox/6.0/user/networkingmodes.html

Control it by
- Set up guest's grub with serial console config
- Set up host's minicom config

Then `vagrant up` fail, as it try to `ssh` into guest, which have been cut network access.

### Vagrant version

Vagrant 2.2.19

### Host operating system

ArchLinux

### Guest operating system

hashicorp/bionic64

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.provider "virtualbox" do |v|
    # offline mode
    v.customize ["modifyvm", :id, "--nic1", "none"]

    # serial port
    v.customize ["modifyvm", :id, "--uart1", "0x3f8", "4"]
    v.customize ["modifyvm", :id, "--uartmode1", "server", "/tmp/vmserial"]
  end

  # config serial console inside guest
  config.vm.provision "shell", inline: $config_grub_serial_console
end
```

### Debug output

```txt
$ vagrant up && minicom
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'hashicorp/bionic64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'hashicorp/bionic64' version '1.0.282' is up to date...
==> default: Setting the name of the VM: xxx
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH xxx
    default: SSH xxx
    default: SSH xxx
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    (~30 times)
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
```

### Expected behavior

`vagrant up` OK.

### Actual behavior

`vagrant up` FAIL.

### Steps to reproduce

1. `vagrant up` FAIL
2. `minicom` OK
3.

### Workaround
Vagrantfile `config.vm.boot_timeout = 1`

```sh
$ vagrant up || :
$ minicom ...
```

**Comment by loynoir** [comment]
Some solve ideas
- how to disable ssh, to prevent `vagrant up` fail, when guest not attach network
- how to integrate serial console with vagrant
- how to let vagrant ssh over serial port  😃

**Comment by chrisroberts** [comment]
Hi there,

Vagrant requires an initial network connection to fully setup the guest system. There is currently no support for connecting to a guest over the serial port using Vagrant and at this time there are currently no plans for enabling this feature.

Cheers!
