### ISSUE TITLE
Website `Get Started` Button Link Not Working 

### ISSUE THREAD

**Issue by Rafat97** [hashicorp/vagrant#12756]
I visited website. When I press Get Started Button It can not redirect to the `https://www.vagrantup.com/intro/index ` page. I give an screenshot when I click the get started button. It gives me an error. 

My Chrome version - 
Version 100.0.4896.127 (Official Build) (64-bit)

OS:
Windows 10 Pro

Screenshot:
![image](https://user-images.githubusercontent.com/21246862/166118952-115c772e-ffa2-40d4-97d5-250a379b969c.png)

Thank you.

**Comment by thiskevinwang** [comment]
Thanks for reporting this @Rafat97!

This should be resolved by https://github.com/hashicorp/dev-portal/pull/376
