### ISSUE TITLE
Is vagrant still maintained?

### ISSUE THREAD

**Issue by dcermak** [hashicorp/vagrant#12752]
I am starting to worry about the future of vagrant: there hasn't been any development activity since the end of 2021, no commits to `main`, no pull requests (except for website fixes) were merged and issues appear to also just pile up.

It would be nice if we could get some official clarification from someone whether we can expect vagrant to resurrect from its slumber or whether it will join the many abandoned projects out there.

cc @chrisroberts @briancain @soapy1

**Comment by mattfarina** [comment]
I noticed that 2021 had about 1/4 the commits as 2020.

I wonder if it's being maintained at the level it's at instead of being actively developed.

**Comment by chrisroberts** [comment]
Hi @dcermak, 

Vagrant has not been abandoned and is indeed awaking from its slumber over the next few weeks. We have been actively focused on our [initial go implementation](https://www.hashicorp.com/blog/toward-vagrant-3-0) which will be included in our next release. Once that work has landed in the public repository we will be doing a short burn down of high priority issues/PRs currently backlogged and then release 2.3.

We're planning on starting reviewing/labeling/prioritizing issues and PRs next week to prep for what will be included in the 2.3 release, so any outstanding open issues will start to be addressed then. My sincerest apologies for the delays and silence you've encountered here as we are deeply appreciative of all your contributions. 

Cheers!

**Comment by dcermak** [comment]
> I noticed that 2021 had about 1/4 the commits as 2020.
> 
> I wonder if it's being maintained at the level it's at instead of being actively developed.

vagrant is pretty mature software and it being in maintenance mode would be fine imho. All upstream activity suddenly ceasing **completely** for months on the other hand makes me worried.


> Hi @dcermak,
> 
> Vagrant has not been abandoned and is indeed awaking from its slumber over the next few weeks. We have been actively focused on our [initial go implementation](https://www.hashicorp.com/blog/toward-vagrant-3-0) which will be included in our next release. Once that work has landed in the public repository we will be doing a short burn down of high priority issues/PRs currently backlogged and then release 2.3.
> 
> We're planning on starting reviewing/labeling/prioritizing issues and PRs next week to prep for what will be included in the 2.3 release, so any outstanding open issues will start to be addressed then. My sincerest apologies for the delays and silence you've encountered here as we are deeply appreciative of all your contributions.
> 
> Cheers!

Thanks @chrisroberts for the clarification. Please, please state this upfront next time, the extended silence was really worrying especially as there was really no indication why and whether it would be permanent.
