### ISSUE TITLE
Vagrant not working with vmware desktop 

### ISSUE THREAD

**Issue by mrunalhtrivedi** [hashicorp/vagrant#12750]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use
HashiCorp Discuss: https://discuss.hashicorp.com/c/vagrant/24 Thank you!

When submitting a bug report, please provide the minimal configuration and required information necessary to reliably reproduce the issue. It
should include a basic Vagrantfile that only contains settings to reproduce the described behavior.

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version#
$ vagrant.exe -v
Vagrant 2.2.19

Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system

This is the operating system that you run locally.

Windows 10 -> Version 21H1 (OS Build 19043,1645)

### Guest operating system

This is the operating system you run in the virtual machine.
Centos7

### Vagrantfile

$ cat Vagrantfile
BOX_IMAGE = "hashicorp-vagrant/centos-7"
NODE_COUNT = 1
MEMORY = "2048"
CPU = "2"

Vagrant.configure("2") do |config|
        config.vm.define "master" do |subconfig|
                subconfig.vm.box = BOX_IMAGE
                subconfig.vm.provider "vmware_workstation"
                subconfig.vm.hostname = "master"
                subconfig.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8265"
                subconfig.vm.network "private_network", ip: "192.168.19.110"
end
  (1..NODE_COUNT).each do |i|
        config.vm.define "node#{i}" do |subconfig|
                subconfig.vm.box = BOX_IMAGE
                subconfig.vm.provider "vmware_workstation"
                subconfig.vm.hostname = "node#{i}"
                subconfig.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 8265"
                subconfig.vm.network "private_network", ip: "192.168.19.#{i+3}"
    end
end

config.vm.provider "vmware_workstation" do |v|
  v.memory = MEMORY
  v.cpus = CPU
end

# Install on all machines
  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
  SHELL
end

```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please ensure the Vagrantfile provided is a minimal Vagrantfile which contains
only the required configuration to reproduce the behavior. Please note that if
your Vagrantfile contains an excess of configuration unrelated the the reported
issue, or is in a different format, we may be unable to assist with your issue.
Always start with a minimal Vagrantfile and include only the relevant configuration
to reproduce the reported behavior.

### Debug output

Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior

What should have happened?

Should work

### Actual behavior

What actually happened?

$ vagrant.exe up
Vagrant encountered an unexpected communications error with the
Vagrant VMware Utility driver. Please try to run the command
again. If this error persists, please contact support@hashicorp.com

$ vagrant.exe plugin install vagrant-vmware-utility
Installing the 'vagrant-vmware-utility' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

Unable to resolve dependency: user requested 'vagrant-vmware-utility (> 0)'

$ vagrant.exe plugin list
vagrant-hosts (2.9.0, global)
  - Version Constraint: > 0
vagrant-timezone (1.3.0, global)
  - Version Constraint: > 0
vagrant-vmware-desktop (3.0.1, global)
  - Version Constraint: > 0

### Steps to reproduce

1.
2.
3.

### References

Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by chrisroberts** [comment]
Hi there,

The vmware utility must be installed as a separate system package. The instructions for installation can be found [here](https://developer.hashicorp.com/vagrant/docs/providers/vmware/vagrant-vmware-utility).

Cheers!
