### ISSUE TITLE
Error: "mount.nfs: an incorrect mount option was specified" on Ubuntu 22.04 Jammy when nfs_udp is true

### ISSUE THREAD

**Issue by richard-to** [hashicorp/vagrant#12758]
### Vagrant version

Vagrant 2.2.19

### Host operating system

MacOS Monterey 12.3.1

### Guest operating system

I'm using this box: `ubuntu/jammy64`

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.network "private_network", ip: "172.31.1.10"
  config.ssh.forward_agent = true

  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provider "virtualbox" do |vb, override|
    vb.memory = 3072
  end

end
```

Please ensure the Vagrantfile provided is a minimal Vagrantfile which contains
only the required configuration to reproduce the behavior. Please note that if
your Vagrantfile contains an excess of configuration unrelated the the reported
issue, or is in a different format, we may be unable to assist with your issue.
Always start with a minimal Vagrantfile and include only the relevant configuration
to reproduce the reported behavior.

### Debug output

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 172.31.1.1:/Users/richard/Projects/my-repo /vagrant

Stdout from the command:



Stderr from the command:

mount.nfs: an incorrect mount option was specified
```

### Expected behavior

The volume should have been mounted

### Actual behavior

I got the error message: mount.nfs: an incorrect mount option was specified

### Steps to reproduce

1. vagrant up

### Notes

It works if I change the command to:

```
config.vm.synced_folder ".", "/vagrant", type: "nfs",  nfs_udp: false
```

So seems like the mount option changed for udp in Jammy?

**Comment by lucaskanashiro** [comment]
This is expected in Ubuntu 22.04, take a look at the section "UDP disabled for NFS mounts" in the release notes:

https://discourse.ubuntu.com/t/jammy-jellyfish-release-notes/24668

**Comment by richard-to** [comment]
Ah thanks for pointing that out @lucaskanashiro. That's good to know. I also missed the Notes section in the vagrant docs about NFS v4: https://www.vagrantup.com/docs/synced-folders/nfs#other-notes

Closing this issue.
