### ISSUE TITLE
vagrant_2.2.19_x86_64.msi not executing/opening on Windows 10

### ISSUE THREAD

**Issue by Keyne** [hashicorp/vagrant#12757]
### Host operating system

Windows 10 64bits

### Expected behavior

Clicking on the installer should install Vagrant

### Actual behavior

Nothing happens

### Steps to reproduce

1. Just click on it

**Comment by chrisroberts** [comment]
Hi there,

This behavior was not reproducible. You may have antivirus software which is preventing the installer from running. Disabling it and trying again may allow for a successful installation.

Cheers!

**Comment by gubertoli** [comment]
> ### Host operating system
> Windows 10 64bits
> 
> ### Expected behavior
> Clicking on the installer should install Vagrant
> 
> ### Actual behavior
> Nothing happens
> 
> ### Steps to reproduce
> 1. Just click on it

I had the same issue, tried to disable antivirus software but it did not worked. The solution was to install the version [2.2.18](https://releases.hashicorp.com/vagrant/2.2.18/).

Follows the log for reference:
`PS>  msiexec /lvx vagrant.log /i .\vagrant_2.2.19_x86_64.msi`

```
=== Verbose logging started: 04/08/2022  09:41:14  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\windows\system32\msiexec.exe ===
MSI (c) (4C:84) [09:41:14:412]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (4C:84) [09:41:14:413]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (4C:24) [09:41:14:435]: Resetting cached policy values
MSI (c) (4C:24) [09:41:14:435]: Machine policy value 'Debug' is 0
MSI (c) (4C:24) [09:41:14:435]: ******* RunEngine:
           ******* Product: .\vagrant_2.2.19_x86_64.msi
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (4C:24) [09:41:14:436]: Machine policy value 'DisableUserInstalls' is 0
MSI (c) (4C:24) [09:41:14:486]: Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer 3: 2 
MSI (c) (4C:24) [09:41:14:486]: Note: 1: 1324 2: . 3: 1 
MSI (c) (4C:24) [09:41:14:486]: MainEngineThread is returning 2
=== Verbose logging stopped: 04/08/2022  09:41:14 ===
```
