### ISSUE TITLE
configure_networks.rb:135:in `block in configure_nettools': no implicit conversion from nil to integer (TypeError)

### ISSUE THREAD

**Issue by ajcassell** [hashicorp/vagrant#12767]
I installed vagrant 2.2.19 and am trying to run:
vagrant up

I'm on MacOS Mojave 10.14.5

Running into the error in the title. Full log attached below. 

Here's the vagrant file (could not get it properly formatted inline):
[Vagrantfile.txt](https://github.com/hashicorp/vagrant/files/8693988/Vagrantfile.txt)

[vagrantUp.txt](https://github.com/hashicorp/vagrant/files/8693986/vagrantUp.txt)

Ends with a long stack trace ending like so:
```	  9: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
	  8: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	  7: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/providers/virtualbox/action/network.rb:142:in `call'
	  6: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/guest.rb:43:in `capability'
	  5: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/capability_host.rb:111:in `capability'
	  4: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/capability_host.rb:111:in `call'
	  3: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/guests/debian/cap/configure_networks.rb:31:in `configure_networks'
	  2: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/guests/debian/cap/configure_networks.rb:134:in `configure_nettools'
	  1: from /opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/guests/debian/cap/configure_networks.rb:134:in `each'
/opt/vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/guests/debian/cap/configure_networks.rb:135:in `block in configure_nettools': no implicit conversion from nil to integer (TypeError)```

**Comment by soapy1** [comment]
It looks like this issue is happening because Vagrant is adding multiple of the same networks to the vm and hitting the virtualbox limit. Working on a fix, but in the meantime a workaround is to set an `id` for the network. For example:
```
    config.vm.network "private_network", ip: "192.168.56.101", id: "private_network"
```
