### ISSUE TITLE
config.vm.provider seems to get called a lot (instead of just once), leading to slow vagrant status (and other commands)

### ISSUE THREAD

**Issue by tolmasky** [hashicorp/vagrant#12768]
It appears that during the course of loading a `Vagrantfile`, the `config.vm.provider` configuration block is called many many times (on my particular setup, it is around 8 times I think). It is called around 5 times from `vagrant/environment.rb`'s `initialize`, and then another 3 times from `plugins/commands/status/command.rb`'s `execute`.

We happen to read a configuration that takes a small amount of time to process (just because it shells out to `node`). Now, under normal circumstances, this is a non-issue, since the startup time of `node` is around 0.3s and then for the code to run another 0.2, so 0.5s total. So just visually inspecting the code, you'd think that even calling this function 3 times in the Vagrantfile would add at most 1.5s. However, since the configuration seems to be regenerated from scratch every time it's used or something, this actually ends up being called 8 times, adding **10 seconds** to a simple call like `vagrant status`. We've of course been able to work around this issue just by removing these calls from this block, and doing them beforehand (or caching the values, etc.), however this still seems like it is not ideal behavior, and certainly took a while to figure out, since it is not obvious that the contents of this block will be called multiple times. Even setting aside performance implications, it creates the possibility of accidentally providing different configurations at different times. I'm not familiar with the internals here, or ultimate intent of this code, but it seems like the configuration should be "constructed" once, at initialization, and then afterwards every consumer throughout the rest of the program should just be using that one cached/immutable copy, vs. round-tripping through the Vagrantfile to recreated the configuration all over again.

### Vagrant version

Vagrant 2.2.19

### Host operating system

Ubuntu 22.04 LTS

### Guest operating system

Ubuntu 20.04 LTS

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
   config.vm.provider "parallels" do |box, override|
       print "in here!"
       # here get_user_configuration is a "somewhat" slow function, on the order of 0.5s
       box.size = get_user_configuration("size")
       box.cpus = get_user_configuration("cpus")
       box.memory = get_user_configuration("memory")
   end
end
```

### Expected behavior

It should be quick, and the calls to `get_user_configuration` should add around 1.5s to the runtime of something like `vagrant status`.

### Actual behavior

It takes a long time, with the calls to `get_user_configuration` adding closer to **10 seconds** to the total runtime. This is because the `config.vm.provider` block is called around 8 times.

### Steps to reproduce

1. Type `vagrant status`

**Comment by chrisroberts** [comment]
Hi there,

You can prevent this by collecting the information prior to defining the configuration. Updating your Vagrantfile like this should prevent the slowdown you are encountering:

```ruby
user_size = get_user_configuration("size")
user_cpus = get_user_configuration("cpus")
user_memory = get_user_configuration("memory")

Vagrant.configure("2") do |config|
   config.vm.provider "parallels" do |box, override|
       print "in here!"
       # here get_user_configuration is a "somewhat" slow function, on the order of 0.5s
       box.size = user_size
       box.cpus = user_cpus
       box.memory = user_memory
   end
end
```

Cheers!

**Comment by tolmasky** [comment]
Hi @chrisroberts 

I specifically mentioned doing exactly that in my description:

> We've of course been able to work around this issue just by removing these calls from this block, and doing them beforehand (or caching the values, etc.), 

This is of course what we did immediately after discovering the problem. The point of this bug though is to suggest that instead of reprocessing what should be static configuration 8 separate times (which aside from a performance issue also incidentally opens the door to an bug if for whatever reason a different value is returned on subsequent runs), perhaps what would be wiser is to just read the configuration once, at the beginning. Or, at the very least, just memoize the configuration instead of having some sort of accessor that gets treated like a constant-time call but instead refetches all the information over and over. As I mentioned, once this is discovered, the "workaround" is trivial -- but you don't get back the time it takes to figure out why it's taking so long in the first place, and now that this bug is closed, the next person that encounters this will have to rediscover this on their own all over again.
