### ISSUE TITLE
The executable 'sbin/ip' Vagrant is trying to run was not found in the PATH variable

### ISSUE THREAD

**Issue by spencer-vantage** [hashicorp/vagrant#12761]
I am attempting to use a CentOS Stream 8 VM as a development environment for a project I am working on. It is mostly setup correctly, but the shared folder I need setup to actually access my project files on my host machine is not being setup. There is an error right after I get the message `==> dev: Machine booted and ready!` which stops the networking setup. This also means the private network doesn't get set up and I have to connect via localhost. I can ssh into the machine, and everything else seems to have worked except the networking stuff.

The error is `The executable '/sbin/ip' Vagrant is trying to run was not found in the PATH variable. This is an error. Please verify this software is installed and on the path.` I checked the debug logs and it looks like '/sbin' is included in my PATH and when I `vagrant ssh` I can immediately use the `ip` command.

### Vagrant version
2.2.19

### Host operating system
MacOS 12.2.1 (Apple M1 chip)

### Guest operating system
CentOS Stream 8

### Vagrantfile

```ruby
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "dev" do |dev|
    dev.vm.network :private_network, ip: "192.168.100.10"
    dev.vm.network "forwarded_port", id: "ssh", host: 2222, guest: 22

    dev.vm.hostname = "vdev"
    dev.vm.synced_folder "~/data", "/data", nfs: true,
      nfs_export: true, nfs_udp: true, nfs_version: 3,
      :mount_options => ['nolock,vers=3,udp,noatime,actimeo=1']
    dev.ssh.forward_agent = true
    dev.vm.provider :docker do |d|
        d.privileged = true
        d.build_dir = "."
        d.remains_running = true
        d.has_ssh = true
    end
  end
end
```

### Dockerfile

```
FROM tgagor/centos:stream8
ENV container docker

# Add sshd server so we can 'vagrant ssh' later
RUN dnf -y install openssh-server openssh-clients passwd sudo; 
RUN mkdir /var/run/sshd
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
RUN useradd --create-home -s /bin/bash vagrant
RUN echo -e "vagrant\nvagrant" | (passwd --stdin vagrant)
RUN echo 'vagrant ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/vagrant
RUN chmod 440 /etc/sudoers.d/vagrant
RUN mkdir -p /home/vagrant/.ssh
RUN chmod 700 /home/vagrant/.ssh
ADD https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub /home/vagrant/.ssh/authorized_keys
RUN chmod 600 /home/vagrant/.ssh/authorized_keys
RUN chown -R vagrant:vagrant /home/vagrant/.ssh

# Allow public key authentication for 'vagrant ssh'
RUN sed -i 's/^#PubkeyAuthentication yes/PubkeyAuthentication yes/i' /etc/ssh/sshd_config

# Install the replacement systemctl command
RUN yum -y install python3
COPY src/docker-systemctl-replacement/files/docker/systemctl3.py /usr/bin/systemctl
RUN chmod 755 /usr/bin/systemctl

CMD /usr/bin/systemctl
```

### Debug output

[Debug output](https://gist.github.com/spencer-vantage/78026ad2e3835232310d62ebcb73c865)

I checked the path on the env and it seems like '/sbin' is included on the path. Does '/sbin/ip' need to be included specifically?

### Expected behavior

`vagrant up` should have successfully setup a shared folder between my host and my VM without any errors

### Actual behavior

`vagrant up` runs mostly successfully until it attempts to set up networking (I think) where it fails with the error: 
`The executable '/sbin/ip' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.`

### Steps to reproduce

1. Run vagrant up with provided Vagrantfile and Dockerfile
2. See error and no shared folder

**Comment by der-eismann** [comment]
The problem is that your container doesn't have the `/sbin/ip` binary installied. You can add it via
```
dnf install -y iproute
```

**Comment by chrisroberts** [comment]
The last comment is correct. Installing that package should resolve the issue. If you still encounter issues, please feel free to open a new issue. 

Cheers!
