### ISSUE TITLE
Ansible Parallel Execution not working

### ISSUE THREAD

**Issue by MrDuRadis** [hashicorp/vagrant#12779]
Hi,

I try to provide VM with an ansible parallel execution.
I follow [this documentation](https://www.vagrantup.com/docs/provisioning/ansible#ansible-parallel-execution) and modify a little bit the example to match with my case but, there is not parallel execution.

### Vagrant version

The Vagrant version is **2.2.19**.

### Host operating system

`lsb_release -a`
```
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.2.6
Codename:	Qonos
```
`uname -a`
```
Linux 5.15.41-1-MANJARO #1 SMP PREEMPT Wed May 18 09:20:01 UTC 2022 x86_64 GNU/Linux
```
### Guest operating system

The operating system is **ubuntu/focal64**.

### Vagrantfile

```ruby
servers = [
    {
      :hostname => "control-plane",
    },
    {
      :hostname => "worker",
    }
]

Vagrant.configure(2) do |config|
  servers.each do |server|
    config.vm.define server[:hostname] do |node|
      node.vm.box = "ubuntu/focal64"
      if server[:hostname] == "worker"
        config.vm.provision :ansible do |ansible|
          ansible.limit = "all"
          ansible.playbook = "ansible/playbook.yml"
        end
      end
    end
  end
end
```
### Debug output
https://gist.github.com/MrDuRadis/07999b9677a303af988f920aa5e2e371

### Expected behavior
Ansible provision must once start at the end of the worker deployment.

### Actual behavior

Ansible provision start at every creation VM.

### Steps to reproduce

Deploy the vagrant file.

**Comment by gildegoma** [comment]
Hi @MrDuRadis,

I think you just need to replace the "config" word by "**node**" at `config.vm.provision :ansible do |ansible|`, and you should be good to go...

`node.vm.provision :ansible do |ansible|`

**Comment by MrDuRadis** [comment]
Hi @gildegoma ,

Thanks for your answer, everething is ok now.
My bad, I thought to an issue.

Have a good day
