### ISSUE TITLE
openEuler not support

### ISSUE THREAD

**Issue by lbicesea79** [hashicorp/vagrant#12775]
I get the message when i used on openEuler System.
>>
The guest operating system of the machine could not be detected!
Vagrant requires this knowledge to perform specific tasks such
as mounting shared folders and configuring networks. Please add
the ability to detect this guest operating system to Vagrant
by creating a plugin or reporting a bug.

vagrant --verion
Vagrant 2.2.19

**Comment by soapy1** [comment]
Hi there,
thanks for opening up an issue for adding support to a guest plugin. The fastest way to make your plugin available is to build it as an external plugin! We have some template repositories setup so building a new guest plugin should take you no time, and you get to keep control over it's own release cycle. Check out the [Ruby template](https://github.com/soapy1/vagrant-guest-plugin-skeleton) or the [Golang template](https://github.com/hashicorp/vagrant-guest-plugin-skeleton-go).

For more information on writing plugins see the docs on [plugin development](https://www.vagrantup.com/docs/plugins/development-basics). For more information on managing Vagrant plugins see the docs on [plugin usage](https://www.vagrantup.com/docs/plugins/usage).

I'm going to go ahead and close this issue. If you need some help building the plugin, please make a post in the [Vagrant discuss forum](https://discuss.hashicorp.com/c/vagrant/24)
