### ISSUE TITLE
Vagrant uninstallation showing too much completion time.

### ISSUE THREAD

**Issue by subhadeep-klizos-123** [hashicorp/vagrant#12798]
![image](https://user-images.githubusercontent.com/98954378/175349756-d5c4a736-1348-451b-813b-fda98488e3d2.png)

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
