### ISSUE TITLE
Vagrant-aws plugin installation fails due to required "Ruby version >= 2.7.0"

### ISSUE THREAD

**Issue by senser-david** [hashicorp/vagrant#12790]
I try to install the Vagrant AWS plugin, but the command vagrant plugin install vagrant-aws terminates with the following error:
`vagrant plugin install vagrant-aws
Installing the 'vagrant-aws' plugin. This can take a few minutes...
Fetching iniparse-1.5.0.gem
Fetching xmlrpc-0.3.2.gem
Fetching formatador-0.3.0.gem
Fetching excon-0.92.3.gem
Fetching fog-core-1.45.0.gem
Fetching racc-1.6.0.gem
Building native extensions. This could take a while...
Fetching nokogiri-1.13.6-x86_64-linux.gem
Fetching fog-xml-0.1.4.gem
Fetching fog-xenserver-1.0.0.gem
Fetching optimist-3.0.1.gem
Fetching rbvmomi-2.4.1.gem
Fetching fog-vsphere-3.5.1.gem
Fetching fog-voxel-0.1.0.gem
Fetching CFPropertyList-2.3.6.gem
Fetching fission-0.5.0.gem
Fetching fog-vmfusion-0.1.0.gem
Fetching fog-terremark-0.1.0.gem
Fetching fog-json-1.2.0.gem
Fetching fog-storm_on_demand-0.1.1.gem
Fetching fog-softlayer-1.1.4.gem
Fetching fog-serverlove-0.1.2.gem
Fetching fog-sakuracloud-1.7.5.gem
Fetching fog-riakcs-0.1.0.gem
Fetching fog-radosgw-0.0.5.gem
Fetching ipaddress-0.8.3.gem
Fetching fog-rackspace-0.1.6.gem
Fetching fog-profitbricks-4.1.1.gem
Fetching fog-powerdns-0.2.0.gem
Fetching tzinfo-2.0.4.gem
Fetching minitest-5.16.0.gem
Fetching activesupport-7.0.3.gem
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

activesupport requires Ruby version >= 2.7.0. The current ruby version is 2.6.6.146.`

I tried to update ruby,  (e.g. sudo apt install ruby-full)

And ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

But error still persist.

**Comment by chrisroberts** [comment]
Upgrading to the latest release of Vagrant will resolve this issue. It is currently shipping with a 2.7 release of Ruby. 

Cheers!
