### ISSUE TITLE
Port forwarding: Always global

### ISSUE THREAD

**Issue by MBfromOK** [hashicorp/vagrant#12800]
### Vagrant version
Vagrant 2.2.19

### Host operating system
Linux Mint 20.3

### Guest operating system
Ubuntu 22.04 LTS

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

LBCount = 1
MasterCount = 2
NodeCount = 2

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-22.04" #"ubuntu/focal64"
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  # Load Balancer Node(s)
  (1..LBCount).each do |i|
    config.vm.network "forwarded_port", guest: 5910, guest_ip: "0.0.0.0", host: 5910
    config.vm.define "staging-lb#{i}" do |lb|
      lb.vm.network "private_network", ip: "192.168.56.100"
      lb.vm.provider "virtualbox" do |v|
        if LBCount == 1 then
          v.name = "staging-lb"
          lb.vm.hostname = "staging-lb.introvert.beaslnet.space"
        else
          v.name = "staging-lb#{i}"
          lb.vm.hostname = "staging-lb#{i}.introvert.beaslnet.space"
        end
        v.memory = 1024
        v.cpus = 1
      end
    end
  end
end
Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-22.04" #"ubuntu/focal64"
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  # Kubernetes Master Nodes
  (1..MasterCount).each do |i|
  config.vm.network "forwarded_port", guest: 5910, guest_ip: "0.0.0.0", host: 5910 + LBCount + i, host_ip: "0.0.0.0"
    config.vm.define "k8s-StageC1M#{i}" do |masternode|
      masternode.vm.hostname = "k8s-StageC1M#{i}.introvert.beaslnet.space"
      masternode.vm.network "private_network", ip: "192.168.56.10#{i}"
      masternode.vm.provider "virtualbox" do |v|
        v.name = "k8s-StageC1M#{i}"
        v.memory = 2048
        v.cpus = 2
      end
    end
  end
end
```

### Debug output

https://gist.github.com/MBfromOK/2d00c606f9f245a7152d06b20adcd84e

#### config.vm.network "forwarded_port":

1. When placed immediately following the ```Vagrant.configure(2) do |config|```  vagrant should forward all guests to the same port of the host (for api or GET/POST applications) or use a range that will correctly map each guest to a unique port on the host (without shifting other ports for things like ssh to the same range
2. Setting a port forward inside of a machine provision should set it for that machine only
3. Using an if clause comparing to a vm name should limit anything inside the true condition to a machine matching that name and not apply it to other guests.
4. Utilize / provide a flag with `config.vm.usable_port_range` to get an port number from a specific acceptable port list

### Actual behavior

During provisioning / reloading with `auto_correct: true` the first log for the first box shows the following and then the process stops with the message: "Vagrant cannot forward the specified ports on this VM, since they would collide with some other application that is already listening on these ports. The forwarded port to 5910 is already in use on the host machine." 

When you look at the failed process log you see the following proceeding the error:
```
==> staging-lb1: Forwarding ports...
       staging-lb1: 5910 (guest) => 5910 (host) (adapter 1)
       staging-lb1: 5910 (guest) => 5912 (host) (adapter 1)
       staging-lb1: 5910 (guest) => 5913 (host) (adapter 1)
       staging-lb1: 22 (guest) => 2222 (host) (adapter 1)
```

### Steps to reproduce

1. Try to include port forwarding for one machine in a multi-machine Vagrantfile - at least 4 variations tried
7. vagrant reload or vagrant destroy
8. vagrant up

### References:
 - GH: config.vm.usable_port_range applies globally (pending)

**Comment by chrisroberts** [comment]
Hi there,

When defining your port forward entries, you are using `config` which applies the entry to all defined guests. It appears that you want them to be applied to specific guests, so you would need to use the configuration variable for each specific guest. For example, to set the forwarded port on the lb instances, it would look like this:

```ruby
Vagrant.configure("2") do |config|
...
  # Load Balancer Node(s)
  (1..LBCount).each do |i|
    config.vm.define "staging-lb#{i}" do |lb|
      lb.vm.network "forwarded_port", guest: 5910, guest_ip: "0.0.0.0", host: 5910
      lb.vm.network "private_network", ip: "192.168.56.100"
...
```

For how the usable port range is applied, please see #12801

Cheers!
