### ISSUE TITLE
Enhancement Request: Use kitty +kitten ssh on xterm-kitty

### ISSUE THREAD

**Issue by toastal** [hashicorp/vagrant#12808]
**Is your feature request related to a problem? Please describe.**
When I `vagrant ssh`, Vagrant searches and uses `ssh` on the system. Then downstream in the VM a lot of tools don't work properly. I tried installing `kitty-terminfo` on the VM but it didn't help.

**Describe the solution you'd like**
When searching for the SSH bin phase, check if `$TERM` is `xterm-kitty` and if true, search for `which kitty` and if found call `kitty +kitten ssh` instead of `ssh`. If you want to be extra safe, `kitty +kitten | grep "ssh"` can be called to see if the `ssh` extension is indeed there.

**Describe alternatives you've considered**
I can `ssh` into the VM and look to see which IP and ports are being used and then reconnect with those settings using `kitty +kitten ssh` but its a bit of a hassle since the ports sometimes change if the `halt`d and restarted, etc.. I can also `set -x TERM xterm-256colors` in my shell or as an env var in `$HOME/.ssh/config`, but a) I lose true color, b) I lose kitty features, c) kitty isn't fully-compatibly with `xterm`. I tried aliasing `ssh` to `kitty +kitten ssh`, but Vagrant searches for the binary which is fine, but this use case breaks the experience for users.

**Additional context**
https://wiki.archlinux.org/title/Kitty#Terminal_issues_with_SSH

**Comment by chrisroberts** [comment]
Hi there,

It is possible to get the behavior you are requesting by using the `config.ssh.shell` setting. This setting will allow you to modify the prefix of the ssh command used. For example, you can set it in your Vagrantfile like this:

```ruby
Vagrant.configure("2") do |config|
  config.vm.shell = "kitty +kitten"
end
```

Cheers!
