### ISSUE TITLE
Documentation very unclear about how to use docker-compose with vagrant

### ISSUE THREAD

**Issue by bayeslearner** [hashicorp/vagrant#12804]
The documentation mentioned that instead of using docker, vagrant can use docker-compose as a provider.  I'm very confused and I can't find an example anywhere.  Can someone please provide an example demonstrating the following:

1.  use shell provisioner with the containers defined inside the docker-compose file.  How to refer those containers by vagrant names?  
2. enable ssh in the docker image;  
3. use ansible provisoner with the containers defined inside the docker-compse file.  
4. use the compose-configuration hash to merge with docker-compose file.

**Comment by chrisroberts** [comment]
Closing as answer was found.
