### ISSUE TITLE
Vagrant incorrectly reports metadata.json not found when content is not valid.

### ISSUE THREAD

**Issue by Flightkick** [hashicorp/vagrant#12829]
### Vagrant version

Vagrant 2.2.19

### Host operating system

Windows 10 (build not relevant)

### Expected behavior

When the `metadata.json` file is not valid, I expect an error stating that the metadata is not valid.

### Actual behavior

When the metadata file is not valid (does not contain the 'provider' field), vagrant reports the `metadata.json` file as 'not found'.

```plaintext
vagrant box add .\custom.box --name custom 
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'custom' (v0) for provider:
    box: Unpacking necessary files from: file://C:/my-vagrant-project/custom/custom.box
    box: 
The "metadata.json" file for the box 'custom' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:

https://www.vagrantup.com/docs/boxes/format.html
```

### Steps to reproduce

1. Create a custom box, add a `metadata.json` file with the following contents:
```
{
  "name": "custom",
  "description": "This is a dummy box."
}
```
2. Use something like tar to package the box
3. Import the box using `vagrant box add custom.box --name custom`

**Comment by chrisroberts** [comment]
Marking as documentation. Rescued errors should be updated to check if file exists and report file related errors (syntax, format, content, etc) when found.

**Comment by soapy1** [comment]
Heya @Flightkick, thanks for opening up an issue! I'm following your reproduction steps but I'm getting a little bit of a different error. Could you provide a bit more information about your setup. In particular:

1. could I get a [full debug gist](https://www.vagrantup.com/docs/other/debugging) from running `vagrant box add .\custom.box --name custom `
2. and the output you get from extracting the custom box (e.g. Is `metadata.json` a top level file?)

For reference, I created a base box called `my.box` by extracting centos 7 box I had already downloaded. I changed the metadata to 
```
{
  "name": "custom",
  "description": "This is a dummy box."
}
```
and then ran the command
```
$ tar cvf my.box box.ovf metadata.json centos-7.2-x86_64-disk1.vmdk
```
When I try to add the box I get an error
```
$ vagrant box add ~/rando-boxes/my.box --name my
...
INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007f80bb9f6828>
/Users/sophia/project/vagrant/lib/vagrant/box_collection.rb:158:in `block (3 levels) in add': undefined method `to_sym' for nil:NilClass (NoMethodError)
	from /Users/sophia/project/vagrant/lib/vagrant/box_collection.rb:472:in `with_temp_dir'
	from /Users/sophia/project/vagrant/lib/vagrant/box_collection.rb:136:in `block (2 levels) in add'
...
```
This is also a bug.

**Comment by Flightkick** [comment]
@soapy1 I see the issue is closed now after the new PR. I have not been able to find the time to reproduce the issue mentioned in this topic as I do not have access to the same environment anymore.

Hope that PR fixed it and otherwise this issue can be used for future reference. Thank you!
