### ISSUE TITLE
vagrant up doesn't complete due to ssh auth failure, but vagrant ssh works

### ISSUE THREAD

**Issue by ritterwolf** [hashicorp/vagrant#12840]
### Vagrant version

Arch package 2.3.0, and website 2.3.0 zip.

### Host operating system

Arch, up to date as of 2022-08-17 22:30 UTC

### Guest operating system

Ubuntu 22.04

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
end
```

### Debug output

https://gist.github.com/ritterwolf/5586448d537bcc567449bfcf8db6f81f

### Expected behavior

`vagrant up` completes

### Actual behavior

Gets stuck and repeats the following messaging until interrupted or times out:

```
    default: Warning: Authentication failure. Retrying...
```

### Steps to reproduce

1. `vagrant up` and wait until the authentication failure message appears
2. In another terminal log in using `vagrant ssh`

### References

Looks similar to #12681. Adding `PubkeyAcceptedAlgorithms +ssh-rsa` to `/etc/sshd/sshd_config` and reloading `sshd` as mentioned in that ticket allows it to work.

**Comment by robinportigliatti** [comment]
Hello,

I had the same problem with jammy and removing all vagrant packages and reinstall them worked for me.

**Comment by schuam** [comment]
Hello,

I also had the same problem. Unfortunately after deinstalling vagrant and reinstalling it. I have a whole other issue. When running `vagrant up` or `vagrant status` or any other `vagrant ...` command, I get the following error:

```
>> vagrant status
/usr/lib/ruby/3.0.0/rubygems/specification.rb:1453:in `rescue in block in activate_dependencies': Could not find 'delegate' (>= 0) among 99 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/opt/vagrant/embedded/gems/2.3.0' at: /usr/lib/ruby/gems/3.0.0/specifications/weakref-0.1.1.gemspec, execute `gem env` for more information
```

The whole trace can be found [here](https://gist.github.com/schuam/87cb9aab292ccdb1a16f5c2a06b61b6e).

Any idea how to fix that?

**Comment by stjohnfinn** [comment]
@schuam, I'm currently facing the same issue. Any progress?

**Comment by schuam** [comment]
@stjohnfinn: after some sleep, I did make some progress:

So first of all, I'm in fact running Arch (it's up to date), and it seems to be an issue with the version that pacman installs.

When I installed Vagrant from source (see [Installing Vagrant from Source](https://www.vagrantup.com/docs/installation/source)) it worked. The last step they describe (adding a link to the executable in /usr/local/bin) didn't work. Well, adding the link work, but running Vagrant by just calling `vagrant` did not. That yielded to some new error messages.

The downside of this installation is, that auto-completion does not work, but at least Vagrant works for now.

By the way: I also tried to install the missing gem witn `gem install delegate`, which didn't help at first until I realized that vagrant changes the GEM_PATH (which can be seen in the error message that I posted earlier). So I tried `gem install --install-dir /opt/vagrant/embedded/gems/2.3.0 delegate`, which got rid of the error message when running `vagrant up`, but led back to the issue described by @ritterwolf.

**Comment by stjohnfinn** [comment]
@schuam In another issue I posted about this bug, someone recommended I downgrade to ruby version 3.0.4-5 from my pacman cache. This worked for me.

`pacman -U file:///var/cache/pacman/pkg/ruby-3.0.4-5-x86_64.pkg.tar.zst`

**Comment by schuam** [comment]
@stjohnfinn: Thanks for the update.

Just to clarify: You installed Vagrant version 2.3.0-2 and Ruby version 3.0.4-5 via pacman, and that works for you? If so, I might try that as well.

**Comment by stjohnfinn** [comment]
@schuam Yes, I have Vagrant 2.3.0-2 installed and Ruby 3.0.4-5. I'm running into the same SSH error as mentioned above, but only on certain Vagrant boxes. The SSH error occurs with generic/arch, but not generic/centos7, for example.

**Comment by schuam** [comment]
@stjohnfinn: Well, maybe I stick with my setup then for now. No problems so far. At the moment, I'm working with an archlinux/archlinux and an ubuntu/jammy64. Both work fine.

**Comment by ritterwolf** [comment]
I don't know what's going on; I haven't made any changes except Arch upgrades, no box upgrades, didn't upgrade Vagrant and it started working without requiring the workaround.

To confirm I installed the Arch packaged version again and it worked as well. The true test will be what happens after rebooting.

I'm increasingly doubting my own sanity.

**Comment by schuam** [comment]
Well, if you upgraded Arch via pacman, that might have updated vagrant as well. I just checked, apparently vagrant was updated in the Arch repo yesterday ([see here](https://archlinux.org/packages/?name=vagrant)). So maybe that update fixed the problem.

Unfortunately, I won't have time to check myself this week, but I definitely will sometime soon. It would be great to work with the official Arch package without any workaround.

**Comment by ritterwolf** [comment]
That's the thing, I didn't have the Arch package installed, I was using the downloaded executable. It just started working with stuff that wasn't before. Then when I noticed it working I installed the Arch package and it works too. It's inexplicable.

**Comment by ritterwolf** [comment]
That's the thing, I didn't have the Arch package installed, I was using the downloaded executable. It just started working with stuff that wasn't before. Then when I noticed it working I installed the Arch package and it works too. It's inexplicable. I've now rebooted and the Arch version is still working.

I'm going to close this issue, find a dark corner, and sob quietly to myself.
