### ISSUE TITLE
Linux binary no longer works on older supported platforms

### ISSUE THREAD

**Issue by ramereth** [hashicorp/vagrant#12842]
Since 2.3.0, it appears that the Linux binary build no longer works on older supported platforms. For example, this is what it looks like on CentOS 7:

```
vagrant --help
/tmp/.mount_vagranFQ6npf/usr/bin/ruby2.7: /lib64/libcrypt.so.1: version `XCRYPT_2.0' not found (required by /tmp/.mount_vagranFQ6npf/usr/lib/x86_64-linux-gnu/libruby-2.7.so.2.7)
/tmp/.mount_vagranFQ6npf/usr/bin/ruby2.7: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_vagranFQ6npf/usr/lib/x86_64-linux-gnu/libruby-2.7.so.2.7)
/tmp/.mount_vagranFQ6npf/usr/bin/ruby2.7: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_vagranFQ6npf/usr/lib/x86_64-linux-gnu/libruby-2.7.so.2.7)
/tmp/.mount_vagranFQ6npf/usr/bin/ruby2.7: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_vagranFQ6npf/usr/lib/x86_64-linux-gnu/libruby-2.7.so.2.7)
/tmp/.mount_vagranFQ6npf/usr/bin/ruby2.7: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_vagranFQ6npf/usr/lib/x86_64-linux-gnu/libruby-2.7.so.2.7)
```

I assume something changed in how vagrant was built and was possibly built on a newer platform which uses a newer version of glibc. I had similar problems with the following OS platforms which are still supported upstream:

- CentOS 7
- CentOS Stream 8 / Rocky Linux 8 / Alma Linux 8
- Debian 10
- Ubuntu 18.04

Ideally, you should build on CentOS 7 which has the oldest glibc and would provide backwards compatibility to all of the other platforms. It's still supported upstream until June 2024 so it's a good choice for now.

### Vagrant version

2.3.0 (binary version)

### Host operating system

CentOS 7

### Guest operating system

n/a

### Vagrantfile

n/a

### Expected behavior

Linux binary to be backwards compatible to currently supported OS distributions

### Actual behavior

Binaries are linked on a newer glibc, thus making it unusable on some older supported platforms.

**Comment by chrisroberts** [comment]
Hi!

I had to bump the base ubuntu version we build the appimage on to get a Ruby 2.7 package. I'll look at adding a custom Ruby build to the process and rolling back to the previous ubuntu version for the next release. For now, the rpm package in the [2.3.0 release](https://releases.hashicorp.com/vagrant/2.3.0/) should be usable.
