### ISSUE TITLE
If you're running on windows try the following, from [VirtualBox forum post](https://forums.virtualbox.org/viewtopic.php?f=6&t=66442)

### ISSUE THREAD

**Issue by LordZeuz** [hashicorp/vagrant#12877]
If you're running on windows try the following, from [VirtualBox forum post](https://forums.virtualbox.org/viewtopic.php?f=6&t=66442)

Go to C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv directory, right click on VBoxDrv.inf and select Install. 

Go to console and enter 'sc start vboxdrv'.

Then try 'vagrant up'. Worked for my issue.

_Originally posted by @sebaux in https://github.com/hashicorp/vagrant/issues/9318#issuecomment-388014116_

**Comment by LordZeuz** [comment]
i do not have vboxdrv in my drivers folder. Just USB, Network and vboxsup. any other way to solve this issue?

**Comment by soapy1** [comment]
Hey there, thanks for opening up an issue. It looks like the [issue you cited](https://github.com/hashicorp/vagrant/issues/9318#issuecomment-388014116) also has other solutions for the issue. So, I'm going to go ahead and close this issue. If none of the solutions in that issue work, please feel free to open up a new issue with all the information in the issue template filled out. Thanks!
