### ISSUE TITLE
Fedora 36 box session getting killed by systemd-oomd when installing package

### ISSUE THREAD

**Issue by Zlopez** [hashicorp/vagrant#12878]
### Vagrant version

2.2.19

### Host operating system

Fedora 36 Silverblue

### Guest operating system

Fedora 36

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "fedora/36-cloud-base"
  config.vm.synced_folder ".", "/vagrant", type: "sshfs"
end

```

### Debug output
[vagrant.log](https://github.com/hashicorp/vagrant/files/9461025/vagrant.log)

### Expected behavior

New package is installed

### Actual behavior

User session killed by systemd-oomd and connection closed by remote host

### Steps to reproduce

1. vagrant up (with provided Vagrantfile)
2. vagrant ssh
3. sudo dnf install bash-completion

My assumption is that this is caused by default memory for the machine being too low for Fedora 36 box.

**Comment by Zlopez** [comment]
I fixed this by adding following to the Vagrantfile
```ruby
  config.vm.define "kerneltest" do |kerneltest|
    kerneltest.vm.host_name = "kerneltest.example.com"

    kerneltest.vm.provider :libvirt do |domain|
      # Season to taste
      domain.memory = 1024
    end
  end
```

**Comment by soapy1** [comment]
Thanks for opening up an issue. Since it seems like its been resolved, I'm going to go ahead and close this issue.
