### ISSUE TITLE
Allow vagrant ssh to login with different usernames

### ISSUE THREAD

**Issue by ekohl** [hashicorp/vagrant#1295]
In my environment I want to use multiple users inside the VM and while `vagrant ssh` is a very useful concept, I think it could be even better when you add the option log in using different usernames. A parameter for a username (`-u`) comes to mind, but fixing `vagrant ssh -- -l <otheruser>` (which doesn't work in 1.0.6) might be a different solution. The latter that wouldn't clutter the UI with extra parameters while still allowing power users to do what they want.

**Comment by WangWenchao** [comment]
https://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html   
config the ssh username and password and insert_key to be true  could resolve your problem

**Comment by dobando-igd3** [comment]
vagrant ssh -p

**Comment by anthony-malkoun-intrepid** [comment]
This helped me, posting here as Google search is taking me to this [link](http://willhaley.com/blog/different-ssh-users-for-vagrant-ssh-and-vagrant-up/) which references this [issue comment](https://github.com/mitchellh/vagrant/issues/1753#issuecomment-53970750)

Basically as the Vagrantfile is Ruby you can do:

```ruby
VAGRANT_COMMAND = ARGV[0]

Vagrant.configure("2") do |config|
  if VAGRANT_COMMAND == "ssh"
      config.ssh.username = 'other_username'
  end

  ...
end
```

Thanks to [danielfrg](https://github.com/danielfrg) for this!
