### ISSUE TITLE
Vagrant 2.3.2 and Virtualbox 7.0.0

### ISSUE THREAD

**Issue by onecrazygenius** [hashicorp/vagrant#12960]
### Debug output

 INFO batch_action: Enabling parallelization by default.
 INFO batch_action: Disabling parallelization because provider doesn't support it: virtualbox
 INFO batch_action: Batch action will parallelize: false
 INFO batch_action: Starting action: #<Vagrant::Machine:0x00000138b9445d70> up {:destroy_on_error=>true, :install_provider=>false, :parallel=>true, :provision_ignore_sentinel=>false, :provision_types=>nil}
 INFO machine: Calling action: up on provider VirtualBox (new VM)
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-72f296c780a5d532870b48972b5256fc
 INFO interface: Machine: action ["up", "start", {:target=>:conf}]
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x00000138b8dc4ac8>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckVirtualbox:0x00000138b89c7588>
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_7_0
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "list", "hostonlyifs"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "$(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "$(Get-WindowsFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x00000138b8418a38>
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x00000138b91416b0>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Created:0x00000138b8f89818>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderVirtualBox::Action::Created:0x00000138b8f89818>
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Warden:0x00000138b6db3680>
 INFO warden: Calling IN action: #<Proc:0x00000138b856e220 C:/HashiCorp/Vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/action/warden.rb:126 (lambda)>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::HandleBox:0x00000138b6db35e0>
 INFO handle_box: Machine already has box. HandleBox will not run.
 INFO warden: Calling IN action: #<Proc:0x00000138b6e892f8 C:/HashiCorp/Vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/action/warden.rb:126 (lambda)>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x00000138b8418920>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x00000138b8418858>
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x00000138b7bb8348>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Created:0x00000138b71b85a0>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderVirtualBox::Action::Created:0x00000138b71b85a0>
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Warden:0x00000138b8bdf050>
 INFO warden: Calling IN action: #<Proc:0x00000138b818ead8 C:/HashiCorp/Vagrant/embedded/gems/2.3.2/gems/vagrant-2.3.2/lib/vagrant/action/warden.rb:126 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckAccessible:0x00000138b8bdefb0>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Customize:0x00000138b8bdef60>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::PrepareClone:0x00000138b8bdef38>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::PrepareCloneSnapshot:0x00000138b8856c30>
 INFO prepare_clone: no clone master, not preparing clone snapshot
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Import:0x00000138b86c7130>
 INFO interface: info: Importing base box 'centos/stream8'...
 INFO interface: info: ==> conf: Importing base box 'centos/stream8'...
==> conf: Importing base box 'centos/stream8'...
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "import", "-n", "\\\\?\\C:\\Users\\censor\\.vagrant.d\\boxes\\centos-VAGRANTSLASH-stream8\\20210210.0\\virtualbox\\box.ovf"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO virtualbox_7_0: Base path for disk import: D:/vms/CentOS-Stream-Vagrant-8-20210210.0.x86_64
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "import", "\\\\?\\C:\\Users\\censor\\.vagrant.d\\boxes\\centos-VAGRANTSLASH-stream8\\20210210.0\\virtualbox\\box.ovf", "--vsys", "0", "--vmname", "CentOS-Stream-Vagrant-8-20210210.0.x86_64_1666182998848_63256", "--vsys", "0", "--unit", "10", "--disk", "D:/vms/CentOS-Stream-Vagrant-8-20210210.0.x86_64_1666182998848_63256/CentOS-Stream-Vagrant-8-20210210.0.x86_64.vmdk"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO interface: info: Progress: 20%
 INFO interface: info: Progress: 70%
 INFO interface: info: Progress: 90%
Progress: 90% INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "list", "vms"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO machine: New machine ID: "63192d83-3302-44e0-a351-ad4015926dd7"
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_7_0
 INFO base: VBoxManage path: C:/Program Files/Oracle/VirtualBox/VBoxManage.exe
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "63192d83-3302-44e0-a351-ad4015926dd7"]
 INFO subprocess: Command not in installer, restoring original environment...

 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::DiscardState:0x00000138b86c7108>
 INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "63192d83-3302-44e0-a351-ad4015926dd7", "--machinereadable"]
 INFO subprocess: Command not in installer, restoring original environment...

### Expected behavior

Virtual machine is created and provisioned by vagrant

### Actual behavior

Hangs at showvminfo command. Older versions I believe this command was attempted multiple times but it hangs and box doesnt get altered from ISO pull

### Reproduction information 

Vagrant 2.3.2
Oracle Virtualbox 7.0.0

vagrant plugin list 
vagrant-vbguest (0.30.0, global)
virtualbox (0.8.6, global)

#### Vagrant version

Vagrant 2.3.2

#### Host operating system

Windows 10

#### Guest operating system

centos/stream8

#### Steps to reproduce

1. Run vagrant up with following config
2. 
#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|

  # Create config server
  config.vm.define "conf" do |conf|
    conf.vm.box = "centos/stream8"
    conf.vm.box_version = "20210210.0"

    conf.vm.hostname = "config"
    conf.vm.network "private_network", ip: "192.168.33.100", :adapter => 2

    conf.vm.provider "virtualbox" do |vb|
      vb.name = "config"
      vb.memory = "1024"
      vb.cpus = 1
    end

    conf.vm.provision "shell", path: "scripts/bootstrap.sh"
    conf.vm.provision "shell", path: "scripts/config.sh"
  end
 end
-->

**Comment by breisig** [comment]
I am also have very similar issues when trying to run 'vagrant destroy', It's just hanging. I tried cancelling and running it multiple times but nothing. It looks like its frozen

**Comment by onecrazygenius** [comment]
@breisig I have also run vagrant destroy after terminating the above command and see the same issue you describe. I'm currently looking as I think it appears to be an issue with the VBoxManage command itself hanging. 
Here is my output from running the VBoxManage command by itself:
```
C:\Users\me>"C:/Program Files/Oracle/VirtualBox/VBoxManage.exe" showvminfo 04a9dbb6-72b9-4435-b07d-37b756fc1c17
Name:                        CentOS-Stream-Vagrant-8-20210210.0.x86_64_1666187456142_11199
```

**Comment by dsutphin** [comment]
I don't think this is a Vagrant issue. For me all vboxmanage commands were hanging.

Workaround was to downgrade to VirtualBox 6 and `vboxmanage unregistervm <uuid> --delete` all vagrant vms (`vboxmanage list vms`). I was then able to successfully `vagrant destroy` and `vagrant up`.

**Comment by chrisroberts** [comment]
Hi there. Please try the following steps:

1. Reboot your machine (or kill all the virtualbox related processes, but just rebooting is easier)
2. Download and install the [virtualbox extension pack](https://www.virtualbox.org/wiki/Downloads#VirtualBox7.0.0OracleVMVirtualBoxExtensionPack)
3. Run `vagrant destroy` in your project
4. Run `vagrant up` in your project

I made a note in the PR (#12953) for vbox 7 support that the extension pack was required for some reason for the VBoxManage commands not to hang. During my testing it would appear that the first invocation would succeed as expected and then subsequent invocations would result in the command hanging.

**Comment by onecrazygenius** [comment]
I have raised a ticket with VirtualBox [Ticket #21168] as this appears to now pertain to an issue with VBoxManage in 7.0.0. Will try steps listed above to see if issue resolves and update here just to confirm. If successful will close :)

**Comment by breisig** [comment]
@onecrazygenius It looks like your Virtualbox ticket is a duplicate of https://www.virtualbox.org/ticket/21167 . It says its fixed in SVN and as a temporary workaround, is to install the extensions package.

**Comment by onecrazygenius** [comment]
As above from @breisig, my Oracle ticket has been answered and the extension pack 7.0.0r153978 appears to fix this. Will close for now and VirtualBox 7.0.2 should fix. Thanks all
