### ISSUE TITLE
`vagrant plugin install` command not reporting plugin already installed

### ISSUE THREAD

**Issue by ansiblejunky** [hashicorp/vagrant#12987]
Running `vagrant plugin install <plugin>` command will install the plugin the first time, but repeated runs will return the same information. Example:

```
$ vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmanager (1.8.9)'!

$ vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmanager (1.8.9)'!
```

This makes it difficult to run automation, such as Ansible, and ensure that changes are made only when necessary.
It should be quite a simple check for `vagrant` to look at the `~/.vagrant.d/plugins.json` to determine if the plugin is already installed and report a different message or return code.

### Debug output

<script src="https://gist.github.com/ansiblejunky/3a691a49dfd45519f20bd21243158746.js"></script>

### Expected behavior

`vagrant plugin install` should be reporting two different messages - one for when plugin is already installed, and one for when it is not and will be installed.

### Actual behavior

`vagrant plugin install` actually installs the plugin regardless if it's installed or not. This is not optimal.

#### Vagrant version

$ vagrant -v
Vagrant 2.2.19

#### Host operating system

macOS 12.6

#### Steps to reproduce

See above

**Comment by chrisroberts** [comment]
Hi there,

The behavior of `vagrant plugin install` is modeled after the `gem` command and this is the expected behavior. If you want to prevent the install command from running, you can always check for a plugin using the `plugin list` command.

Cheers!
