### ISSUE TITLE
VMware: Vagrant's configuration via SSH doesn't work with static IP

### ISSUE THREAD

**Issue by Urukambas** [hashicorp/vagrant#12984]
### Description
When specifying a static IP address in Vagrantfile - Vagrant itself cannot connect via SSH to the VM. I tried 2 ways: the one that is presented in vagrantfile and second is to set addresstype to static and specify MAC address in VMX options.

### Vagrantfile
Set static IP with vm.base mac + vm.base_address options. 
```ruby
Vagrant.configure("2") do |config|
	config.vm.define "node" do |node|
		node.vm.box = "generic/centos8"
		node.vm.hostname = "node"
		node.ssh.host = "10.1.0.5"
		node.vm.base_mac = "00:0c:29:8b:0a:68"
		node.vm.base_address = "10.1.0.5"
	end
end
```
### Debug
Everything works correctly, the machine gets the correct MAC and IP addresses. Entries are created correctly in vmnetdhcp.conf
```config
host VMnet8Host3 {
    hardware ethernet 00:0c:29:8b:0a:68;
    fixed-address 10.1.0.5;
    option domain-name-servers 10.1.0.2;
    option domain-name "localdomain";
    option routers 10.1.0.2;
}
```
Vagrant correctly recognizes the IP address specified in the Vagrantfile and trying to connect to specified IP
```log
DEBUG vmware_driver:   - guestinfo.detailed.data = bitness='64' distroName='CentOS Linux' distroVersion='8' familyName='Linux' kernelVersion='4.18.0-348.7.1.el8_5.x86_64' prettyName='CentOS Linux 8'
DEBUG vmware_driver: Trying to get MAC address for ethernet0
DEBUG vmware_driver:  -- MAC: 00:0C:29:8B:0A:68
 INFO vmware_driver: Reading DHCP lease for '00:0C:29:8B:0A:68' on 'vmnet8'
DEBUG vagrant_utility: request METHOD=GET PATH=/vmnet/vmnet8/dhcplease/00:0C:29:8B:0A:68 RESPONSE=200
DEBUG vmware: Using localhost lookup for SSH info.
DEBUG vagrant_utility: request METHOD=GET PATH=/vmnet/vmnet8/portforward RESPONSE=200
DEBUG vmware_driver: port forwards for IP 10.1.0.5: {:tcp=>{22=>2222}, :udp=>{}}
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 10.1.0.5
 INFO ssh:   - Port: 2222
```

But Vagrant can't connect via SSH with the following error
```log
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2022-11-04T13:54:06.189078 #8388] DEBUG -- net.ssh.transport.session[14b2c]: establishing connection to 10.1.0.5:2222

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not ready: #<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

Net::SSH::ConnectionTimeout>
```

### Expected behavior

The virtual machine gets the correct IP address, Vagrant connects to this address and configure it

### Actual behavior

Vagrant gets stuck trying to connect via SSH

#### Vagrant version

2.3.1

#### Host operating system

Windows 10 Pro (21H2)

#### Guest operating system

CentOS 8

#### VMware Version

VMware Workstation Pro 16.2.4 build-20089737

#### Steps to reproduce

1. Init new Vagrantfile
2. Set static IP
3. Start VM
4. Get stuck on Vagrant trying to connect via SSH

**Comment by chrisroberts** [comment]
Hi there,

Because you are overriding the host configured for the ssh connection you'll need to override the port as well. Vagrant assumes it is connecting via a forwarded port, so setting the port in the configuration to 22 will prevent that:

```ruby 
Vagrant.configure("2") do |config|
	config.vm.define "node" do |node|
		node.vm.box = "generic/centos8"
		node.vm.hostname = "node"
		node.ssh.host = "10.1.0.5"
                node.ssh.port = 22
		node.vm.base_mac = "00:0c:29:8b:0a:68"
		node.vm.base_address = "10.1.0.5"
	end
end
```

Cheers!
