### ISSUE TITLE
vagrant up failing with hyper-v after upgrading to powershell 7.3.0

### ISSUE THREAD

**Issue by gentooise** [hashicorp/vagrant#12998]
### Debug output

https://gist.github.com/gentooise/ceb05c4dbc25c82c12572817ca299aa5

### Expected behavior

Machine should go up normally.

### Actual behavior

```
PS C:\Users\<myuser>\VMs\vagrant\ubuntu20> vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: check_hyperv_access.ps1
Error:

Check-VagrantHyperVAccess : The 'Get-ACL' command was found in the module 'Microsoft.PowerShell.Security', but the
module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Security'.
At
C:\HashiCorp\Vagrant\embedded\gems\2.3.3\gems\vagrant-2.3.3\plugins\providers\hyperv\scripts\check_hyperv_access.ps1:8
char:10
+ $check = Check-VagrantHyperVAccess -Path $Path
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ACL:String) [Check-VagrantHyperVAccess], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule,Check-VagrantHyperVAccess
```

#### Vagrant version

Vagrant 2.3.3

#### Host operating system

Edition: Windows 11 Enterprise
Version: 21H1

#### Guest operating system

Ubuntu 20.04

#### Steps to reproduce

1. vagrant up

#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2004"

  config.vm.synced_folder "../shared", "/shared", type: "rsync"
  
  config.vm.provider "hyperv" do |h|

    VMName = "generic-ubuntu20-hyperv"

    h.vmname = VMName

    vm_exists = system("powershell.exe", "-Command", "Get-VM -VMNAME #{VMName} -ErrorAction SilentlyContinue | out-null")
    if !vm_exists
      config.vm.network "public_network", bridge: "Default Switch"
    end

  end

end
```

**Comment by lipanpan-hub** [comment]
Anyone know how to resolve ?

**Comment by lipanpan-hub** [comment]
same error

**Comment by chrisroberts** [comment]
Source of this error is a breaking change in Powershell 7.3 which was introduced [here](https://github.com/PowerShell/PowerShell/pull/16355)

**Comment by YouJiacheng** [comment]
Same Error. My workaround is to use powershell(Windows PowerShell) instead of pwsh(PowerShell).

**Comment by gentooise** [comment]
> Same Error. My workaround is to use powershell(Windows PowerShell) instead of pwsh(PowerShell) to run `vagrant up`.

How?

**Comment by gentooise** [comment]
> Source of this error is a breaking change in Powershell 7.3 which was introduced [here](https://github.com/PowerShell/PowerShell/pull/16355)

Thanks for the info. Do you think this can be fixed anytime soon?

**Comment by YouJiacheng** [comment]
@gentooise 
Use `powershell vagrant up` instead of `vagrant up`.

**Comment by maroskukan** [comment]
Just an extension to @YouJiacheng  answer, you can also add the following wrapper to your `$profile` aka `Microsoft.PowerShell_profile.ps1` . and use `vagrant` as you normally would.

```powershell
Function VagrantWrapper()
{
    powershell vagrant $args
}

New-alias vagrant VagrantWrapper
```
