### ISSUE TITLE
Version mismatch after install vagrant-unbundled with wsl2

### ISSUE THREAD

**Issue by KyrineLabs** [hashicorp/vagrant#12993]
i want tu use the plugin vagrant-r10k
after install i have error, the plugin need bcrypt_pbkdf-1.1.0 and other gem plugin

i do gem install vagrant--unbundled (see on google) 
the plugin install is vagrant-unbundled-2.3.2.0
but now when i do vagrant up i have this error

_Vagrant cannot currently enable access to manage machines within the Windows
environment because the version of Vagrant installed on Windows does not
match this version of Vagrant running within the Windows Subsystem for Linux.
Please ensure both installation of Vagrant are the same. If you do not want
update your Vagrant installations you can disable Windows access by unsetting
the `VAGRANT_WSL_ACCESS_WINDOWS_USER` environment variable.

  Windows Vagrant version: 2.3.2
  Windows Subsystem for Linux Vagrant version: 2.3.2.0_

i uninstall the gem plugin 
i uninstall/install vagrant
but the error doesn't disappear

**Comment by chrisroberts** [comment]
Hi there,

Vagrant will validate that the version of Vagrant running in WSL is the same as the version installed on Windows to prevent any discrepancies in behavior between versions causing problems. The `vagrant-unbundled` rubygem is not something that we maintain. Installing the vagrant package from the [downloads page](https://www.vagrantup.com/downloads) will prevent this error.
