### ISSUE TITLE
 Timed out while waiting for the machine to boot while vagran up

### ISSUE THREAD

**Issue by myysophia** [hashicorp/vagrant#13003]
### Debug output
`vagrant reload
==> node1-186: Attempting graceful shutdown of VM...
    node1-186: Guest communication could not be established! This is usually because
    node1-186: SSH is not running, the authentication information was changed,
    node1-186: or some other networking issue. Vagrant will force halt, if
    node1-186: capable.
==> node1-186: Forcing shutdown of VM...
==> node1-186: Clearing any previously set forwarded ports...
==> node1-186: Clearing any previously set network interfaces...
==> node1-186: Preparing network interfaces based on configuration...
    node1-186: Adapter 1: nat
    node1-186: Adapter 2: bridged
==> node1-186: Forwarding ports...
    node1-186: 22 (guest) => 2222 (host) (adapter 1)
==> node1-186: Running 'pre-boot' VM customizations...
==> node1-186: Booting VM...
==> node1-186: Waiting for machine to boot. This may take a few minutes...
    node1-186: SSH address: 127.0.0.1:2222
    node1-186: SSH username: vagrant
    node1-186: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
`

### Expected behavior

- ping failed
- vagrant ssh failed
`vagrant ssh
ssh_exchange_identification: read: Connection reset by peer`

#### Vagrant version

`]#vagrant -v
Vagrant 2.2.19
`

#### Host operating system

`]#cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

]#uname -a
Linux p1edaspk03 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

#### Guest operating system

`Centos7`

#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.provider 'virtualbox' do |vb|
  end
  $num_instances = 1
  (1..$num_instances).each do |i|
    config.vm.define "node#{i}-186" do |node|
      node.vm.box = "centos-7"
      node.vm.hostname = "master#{i}-186"
      node.disksize.size = '200GB'
      ip = "10.50.10.#{i+26}"
      node.vm.network "public_network", ip: ip,bridge: "bond0"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = "65536"
        vb.cpus = 8
        vb.name = "master#{i}-186"
      end
      node.vm.provision "shell", path: "install.sh"
    end
  end
end
```
hi，I have looked up the relevant issue, but I cannot solve it. I hope to get your guidance.
eg： https://github.com/hashicorp/vagrant/issues/10669

**Comment by myysophia** [comment]
virtualbox Version
`virtualbox --help
Oracle VM VirtualBox VM Selector v6.1.32
`

**Comment by myysophia** [comment]
I reproduced the problem just now.

step1.  Partition the disk | restart normal

step2.  mount | restart normal

step3.  modify /etc/fstab | restart abnormal

here is my vagran up log：  https://gist.github.com/myysophia/894d11b98a20f8a002053171740558d6

**Comment by chrisroberts** [comment]
Hi there,

This appears to be an issue with the vagrant-disksize plugin which is a third party plugin that we do not maintain. Your description in the last comment about modifying fstab and it resulting in an abnormal boot indicates that there is likely something wrong with your fstab configuration. The best way to debug it would be to boot the guest and then open the VirtualBox GUI and inspect the guest from there.

Cheers!
