### ISSUE TITLE
VirtualBox Docker Kernel Panic

### ISSUE THREAD

**Issue by goldfita** [hashicorp/vagrant#13011]
### Debug output
I can't provide the full output. There is too much for me to go through and make sure there is nothing sensitive. I'm showing a snippet below, and I can provide more on request.

> DEBUG virtualbox_7_0:   - [1, "docker", 2375, 2375, "127.0.0.1"]
> DEBUG virtualbox_7_0:   - [1, "ssh", 2200, 22, "127.0.0.1"]
>  INFO ssh: Attempting SSH connection...
>  INFO ssh: Attempting to connect to SSH...
>  INFO ssh:   - Host: 127.0.0.1
>  INFO ssh:   - Port: 2200
>  INFO ssh:   - Username: docker
>  INFO ssh:   - Password? true
>  INFO ssh:   - Key Path: []
> DEBUG ssh:   - connect_opts: {:auth_methods=>["none", "hostbased", "publickey", "password"], :config=>false, :forward_agent=>false, :send_env=>false, :keys_only=>true, :verify_host_key=>:never, :password=>"tcuser", :port=>2200, :timeout=>15, :user_known_hosts_file=>[], :verbose=>:debug, :logger=>#<Logger:0x07c30ab8 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x07c30aa0 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x07c30a28 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<StringIO:0x07c30b00>, @binmode=false, @mon_data=#<Monitor:0x07c30a10>, @mon_data_owner_object_id=71208>>, :keys=>[], :remote_user=>"docker"}
>  INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "showvminfo", "f9b64d89-7414-4b27-8b8e-5b83926232d4", "--machinereadable"]
>  INFO subprocess: Command not in installer, restoring original environment...
> DEBUG subprocess: Selecting on IO
> DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
> DEBUG subprocess: Exit status: 0

This last part repeats over and over, eventually it restarts the ssh attempt. This goes on and on until it eventually times out. Eventually it times out with a stack trace.

### Expected behavior
The VM should come up without a panic even if I can't ssh in. My apologies if I have this configured wrong. I don't have much experience with docker.

### Actual behavior
I was having an issue with Vagrant [hanging on SSH](https://github.com/hashicorp/vagrant/issues/11987) and eventually timing out. I tried some of the suggestions in that issue, but it didn't help. I wasn't able to understand what was going on from the debug output, but I noticed that it seems to use user/host 'docker@127.0.01' and password 'tcuser' no matter what I put in my Vagrantfile. Eventually I realized that I can stop the VM and restart it from VirtualBox, and I see the following.
![vagrant_docker_kernel_panic](https://user-images.githubusercontent.com/25371142/205181694-4fc4b3c2-0948-411b-b35f-b561aae94abe.png)

#### Vagrant version
 INFO global: Vagrant version: 2.3.3
 INFO global: Ruby version: 2.7.6
 INFO global: RubyGems version: 3.1.6

#### Host operating system
Windows11 Pro

#### Guest operating system
I started with Rocky base container image and then switched to phusion so that I could try to replicate [this example](https://stackoverflow.com/a/28771401). The guest is the default boot2docker.

VirtualBox 7.0.4 r154605 (QT5.15,2)

#### Steps to reproduce

1. Start the docker engine service
2. Grant full permissions to \\.\pipe\docker_engine
3. vagrant up

#### Vagrantfile

```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
Vagrant.configure("2") do |config|
  config.vm.define "DockerTest"
  config.ssh.username = "root"
  config.ssh.private_key_path = "insecure_key"
  config.vm.provider "docker" do |d|
    d.username = "docker"
    d.password = "tcuser"
    d.build_dir = "."
    d.force_host_vm = true
    d.remains_running = true
    d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
  end
end
```

```
FROM phusion/baseimage
RUN rm -f /etc/service/sshd/down
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh
RUN /usr/sbin/enable_insecure_key
```

Notes: I have WSL2 enabled. I've only installed the windows docker service, not the full docker desktop.

**Comment by phinze** [comment]
Thanks for the report. Unfortunately we don't have much control or visibility on the Virtualbox layer to diagnose that panic.

However, one thing you can try is to remove the `force_host_vm` line in your Vagrantfile and sidestep the Virtualbox VM entirely. The Docker provider should theoretically be able to interact with Docker directly on your Windows host.

**Comment by goldfita** [comment]
Thanks for responding. Maybe I'm a bit confused. I thought that linux containers can only run on a linux machine, hence the need for the VM. When I remove `force_host_vm`, comment username/password, and change the first line of the Dockerfile to `FROM phusion/baseimage:jammy-1.0.1`, I get

> Stderr: no matching manifest for windows/amd64 10.0.22000 in the manifest list entries

I think this is telling me there is no windows version of the container. If you have the full Docker Desktop, I think it runs linux containers on Windows own virtualized solution under the hood. I may be wrong about this, but I don't have Docker Desktop anyway due to licensing concerns. It would be helpful if there was an official example in the docs. I found a few examples online, but I haven't been able to get anything to work.

Should I report this as a bug to Oracle/VirtualBox?

**Comment by goldfita** [comment]
@phinze I found the [following workaround](https://forums.virtualbox.org/viewtopic.php?t=106069), that is, setting cpus to 2.

```ruby
Vagrant.configure("2") do |config|
  config.vm.provision "docker"
  config.vm.define "default"
  config.vm.box = "hashicorp/boot2docker"
  config.vbguest.auto_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.provider :virtualbox do |vb|
      vb.name = "default"
      vb.cpus = 2
      vb.memory = 2048
  end
end
```

And set `d.vagrant_vagrantfile` in Vagrantfile.

```ruby
d.vagrant_machine = "default"
d.vagrant_vagrantfile = "./DockerHostVagrantfile"
```

This gets through the kernel panic. Now it gets stuck asking me for an SMB password. I tried disabling synced_folders, but it doesn't seem to work.

**Comment by goldfita** [comment]
I've posted a question on [superuser ](https://superuser.com/questions/1759155/prevent-vagrant-from-mounting-shared-folder) since the SMB problem is an unrelated issue.

**Comment by phinze** [comment]
I appreciate the continued updates as you've made progress @goldfita. 🙇 

First of all, you're right and I was confused as of my first response, if you install vanilla Docker Engine on a Windows host you can only launch Windows containers. Docker Desktop has a [WSL2 Backend](https://docs.docker.com/desktop/windows/wsl/) that launches Linux containers from inside the WSL2 environment, but if you're trying to avoid using Docker Desktop you need to take another approach to get Linux containers. The boot2docker VM launched by Vagrant is one such approach.

I've finally managed to get a Windows environment where I can test. I'll share my findings and conclusions with you - apologies in advance as it's a long journey! If you'd like to skip to what I'm recommending scroll to "Rethinking the Approach".

## Context

* Using the [windows 11 development VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) at version 21H2. 
* Installed Virtualbox 7.0.4 r154605 and Vagrant 2.3.4 from official installers.
* Installed Docker CE via the [script](https://github.com/microsoft/Windows-Containers/tree/Main/helpful_tools/Install-DockerCE) linked from one of the [Microsoft guides](https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-10-and-11-1).
* Using the Vagrantfile and Dockerfile from your original example.

## Observations

* I get the boot2docker VM coming up okay w/ no kernel panics.
* I also get the SMB prompt... if I type in my username and password then I make it to another mounting error that looks like this:

```
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t cifs -o vers=2.0,credentials=/etc/smb_creds_vgt-fd0aa2db1827a9ad66629fc891b827ee-aff6449c5e624ebd64ab1affe73944e6,uid=1000,gid=50,mfsymlinks,_netdev,nofail //<<MACHINE IP>>/vgt-fd0aa2db1827a9ad66629fc891b827ee-aff6449c5e624ebd64ab1affe73944e6 /var/lib/docker/docker_8126a3d4bf12cfcbc4c02f93a14fd504

The error output from the last command was:

mount: mounting //<<MACHINE IP>>/vgt-fd0aa2db1827a9ad66629fc891b827ee-aff6449c5e624ebd64ab1affe73944e6 on /var/lib/docker/docker_8126a3d4bf12cfcbc4c02f93a14fd504 failed: Invalid argument
```

I started to investigate this error - it looks like the `mount.cifs` command inside the boot2docker VM does not like the `vers=2.0` or the `nofail` options. On manually removing those options then I ran into "Host is down" errors which indicated the VM was having trouble reaching the host to mount the folder.

## Rethinking the approach

At this point I decided to pause and take a step back, as [boot2docker is now deprecated](https://github.com/boot2docker/boot2docker) so we're not likely to have a lot of success trying to squash bugs associated with it.

If your overall goal is to run Linux-based Docker containers without installing Docker Desktop, I think the best strategy might be to use both Vagrant and Docker from inside WSL2. 

I was able to get the following to work:

1. From inside a WSL2 ubuntu environment, install both Docker and Vagrant using their Linux install steps. I mostly followed along the steps from [this blog post](https://betterprogramming.pub/how-to-install-docker-without-docker-desktop-on-windows-a2bbb65638a1) (including the bit towards the end about switching ubuntu to `iptables` so docker boots properly).
2. Download the `insecure_key` from the [phusion baseimage instructions](https://github.com/phusion/baseimage-docker#using-the-insecure-key-for-one-container-only).
3. Use a Vagrantfile and Dockerfile with a couple of tweaks as commented

```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
Vagrant.configure("2") do |config|
  config.vm.define "DockerTest"
  config.ssh.username = "root"
  config.ssh.private_key_path = "insecure_key"
  config.vm.synced_folder ".", "/vagrant", disabled: true # disable synced folders
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.force_host_vm = false # no need for a host VM because we are interacting with the Docker inside WSL
    d.remains_running = true
    d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
  end
end
```

```dockerfile
FROM phusion/baseimage:jammy-1.0.1
# ^^ needed a tag here as there's no default :latest tag for this image
RUN rm -f /etc/service/sshd/down
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh
RUN /usr/sbin/enable_insecure_key
```

With this setup I see `vagrant up` succeed and yield a container that I can `vagrant ssh` into.

I _think_ this setup should be the cleanest way for you to use Vagrant and Docker without installing Docker Desktop. Let me know if this meets your needs!

**Comment by goldfita** [comment]
OK, thanks for the suggestion. I'm only experimenting with docker and WSL2 at this time, due to performance issues with VirtualBox that seem to be getting worse over time. I'm going to table this for now and come back to it when these technologies have matured a bit more.

**Comment by chrisroberts** [comment]
Okay, closing this issue for now. If you want to re-raise this in the future, please feel free to open a new issue.

Cheers
