### ISSUE TITLE
ansible_local provisioner unable to install specific version of Ansible with pip install_mode

### ISSUE THREAD

**Issue by moritzheiber** [hashicorp/vagrant#13010]
The `ansible_local` provisioner is able to install a specific version of Ansible using the `version` attribute. You can combine this with the `install_mode` attribute, specifically using `pip` to install and manage Ansible versions.

Ansible switched their versioning logic to rather display the version of `ansible-core` instead of the actual `ansible` package (i.e. when running `ansible --version` you get `[core 2.x.x.x]` instead of the version of the `ansible` `pip` package, which is higher than than the `ansible-core` package). This leads to the issue of Ansible getting installed correctly when specifying the `version` but the version check itself failing because it detects the version of `ansible-core` instead.

Unfortunately, you also cannot use the version of `ansible-core` because the installation command line that's executed by Vagrant is `pip install --upgrade ansible==<version>`, meaning it's installing the `ansible` package, not `ansible-core`, so using the `ansible-core` version fails since that's not a compatible semantic version of the package `ansible`.

A way out of this would be to use `importlib.metadata` for checking on the Ansible version if `install_mode: 'pip'` is specified:

```console
$ python -c "import importlib.metadata; print(importlib.metadata.version('ansible'))"
7.0.0
```

or `pip` itself:

```console
$ pip show ansible | awk '/Version/ { print $2 }'
```

Either way, there needs to be a remedy for the mismatch in behavior between Vagrant trying to install the `ansible` metapackage and then checking against a version of `ansible-core`.

### Expected behavior

The package `ansible` with the requested version should have been installed using `pip`.

### Actual behavior

The package `ansible` was installed with the requested version but the version check fails because it's looking at `ansible --version` and finds the version string `[core 2.x.x.x]` for `ansible-core`.

#### Vagrant version

2.3.3

#### Host operating system

Ubuntu Kinetic Kudu (22.10)

#### Guest operating system

- Ubuntu Jammy Jellyfish (22.04)
- Ubuntu Focal Fossa (20.04)
- Rocky Linux 8
- Rocky Linux 9

#### Steps to reproduce

Simply run `vagrant up` on the example. The `playbook.yml` just needs to be an empty file in the same directory as the `Vagrantfile`.

#### Vagrantfile

```ruby
Vagrant.configure('2') do |config|
  config.vm.define 'jammy' do |bare|
    bare.vm.box = 'ubuntu/jammy64'
    bare.vm.network 'private_network', type: 'dhcp'

    bare.vm.provision 'ansible_local' do |ansible|
      ansible.version = '7.0.0'
      ansible.playbook = 'playbook.yml'
      ansible.install_mode = 'pip'
    end
  end
end
```

Output from a Vagrant run:

```console
Bringing machine 'jammy' up with 'virtualbox' provider...
==> jammy: Checking if box 'ubuntu/jammy64' version '20221124.0.0' is up to date...
==> jammy: Running provisioner: ansible_local...
    jammy: Installing Ansible...
    jammy: Installing pip... (for Ansible installation)
The requested Ansible version (7.0.0) was not found on the guest.
Please check the Ansible installation on your Vagrant guest system (currently: [core 2.14.0]),
or adapt the provisioner `version` option in your Vagrantfile.
See https://docs.vagrantup.com/v2/provisioning/ansible_common.html#version
for more information.
```

**Comment by evgeni** [comment]
Instead of using importlib, you can also call `ansible-community --version` to get the version of the "community distribution"
