### ISSUE TITLE
Vagrant 2.3.3 AMD64 download is signed with an expired Apple Developer cert

### ISSUE THREAD

**Issue by jeffmcisaac** [hashicorp/vagrant#13019]
When installing the Vagrant 2.3.3 AMD64 release downloaded from [here](https://releases.hashicorp.com/vagrant/2.3.3/vagrant_2.3.3_darwin_amd64.dmg), I received a warning that the application was signed by an expired Apple Developer certificate.

```
Developer ID Installer: Hashicorp, Inc. (D38WU7D763)
Issued by: Developer ID Certification Authority
Expired: Monday, December 5, 2022 at 6:44:55 PM Eastern Standard Time
"Developer ID Installer: Hashicorp, Inc. (D38WU7D763)" certificate is expired
```

### Debug output

n/a

### Expected behavior

Application should be signed with a valid certificate and should not receive any warnings during installation.

### Actual behavior

Application installs successfully, but the installer issues a warning about the expired certificate.

#### Vagrant version

2.3.3 AMD64

#### Host operating system

macOS 12.6.1

#### Guest operating system

Not relevant for installation issue.

#### Steps to reproduce

1. Download https://releases.hashicorp.com/vagrant/2.3.3/vagrant_2.3.3_darwin_amd64.dmg.
2. Mount the disk image.
3. Run the installer.

#### Vagrantfile

Not relevant for installation issue.

**Comment by chrisroberts** [comment]
Thanks for the report! It's currently being worked on to be resolved.

**Comment by jeffmcisaac** [comment]
You're welcome!

**Comment by chrisroberts** [comment]
Certificate has been updated in the 2.3.4 release. Cheers!
