### ISSUE TITLE
Get rid of VAGRANT_EXPERIMENTAL warnings

### ISSUE THREAD

**Issue by poige** [hashicorp/vagrant#13021]
"I'm ~always~ often frustrated" © when using `VAGRANT_EXPERIMENTAL` (in order to get some "officially" missing func. of course) I get tons of ridiculously unneeded, redundant warning in regards.

**the solution I'd like**
Let's either deem adult people adult and thus self-responsible for theirs action and get rid of this silly warnings completely OR if it's shocking for anyone in Hashicorp, let's at least agree on some "magic" value of that variable so that people would stop repeatedly getting 3 lines of the same useless text in console on every `vagrant` invocation.

**Alternatives I've considered**
My lawyer advised me against disclosing it.

**Comment by chrisroberts** [comment]
Hi there,

While we are happy to receive suggestions for changes to the existing behavior of Vagrant, the content of this request is not acceptable. If you would like to open a new issue regarding this that follows our [code of conduct](https://www.hashicorp.com/community-guidelines), I'd be happy to investigate what options are available. 

Cheers
