### ISSUE TITLE
Request: Execute cleanup when using vagrant destroy

### ISSUE THREAD

**Issue by gtmtech** [hashicorp/vagrant#1302]
Vagrant is so useful for a multiVM environment, and bootstrapping is nicely taken care of via various provisioning mechanisms.

Frequently I find myself destroying boxes and recreating them (perhaps in a different configuration), and I keep have to do maintenance tasks such as the following:
- Removing puppet certs from puppetmaster to allow generation of a new puppet cert for a nodename
- Removing items from DNS
- Perhaps removing items from loadbalancer configurations if they are taken out (although most lb confs are happy with nodes not being accessible).

Anyway, I thought it would be better if there were not just a provision setting for a vm config, but also a teardown, so that you could specify these menial tasks in your Vagrantfile and not have to remember.

Unless that already exists? If not I'll happily write it, but dont wish to do work that's already done..

**Comment by spuder** [comment]
+1 looking for documentation on this, if it has been implemented.

**Comment by Junikorn** [comment]
+1 would be grateful for doc if feature has been implemented

**Comment by outcoldman** [comment]
For folks who are looking. The plugin `vagrant-triggers` has been merged in main repository, it allows to execute commands before `destroy`, see https://www.vagrantup.com/docs/triggers/
