### ISSUE TITLE
Vagrant initialization error

### ISSUE THREAD

**Issue by Chanarra** [hashicorp/vagrant#13039]
While initializing the vagrant file I'm getting the below-mentioned error. Please help me out with this

$vagrant init geerlingguy/centos7

**Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
![Screenshot (106)](https://user-images.githubusercontent.com/88634496/210136415-92b1a4dc-9524-435a-95e8-077ab5c16c90.png)

shown below.

cannot load such file -- /**

**Comment by chrisroberts** [comment]
Hi there,

Would you please provide a gist of the output with the `--debug` flag: `vagrant init geerlingguy/centos7 --debug`

Thanks!

**Comment by soapy1** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
