### ISSUE TITLE
SSH Agent Forwarding not available during provisioning (using lucid32 box, maybe others)

### ISSUE THREAD

**Issue by dholdren** [hashicorp/vagrant#1303]
### Problem

During provisioning we cannot leverage ssh agent forwarding for tasks (i.e. cloning a personal github repo) even though agent forwarding is turned on via:
`config.ssh.forward_agent = true`
### Reproduce

you can easily reproduce this by:
1) enabling config.ssh.forward_agent in your Vagrantfile
2) ensuring you ran `ssh-add ~/.ssh/id_rsa`
3) ensure on your (host) OS that `ssh -T git@github.com -o StrictHostKeyChecking=no` works
4) have a shell provision like:
`config.vm.provision :shell, :inline => 'ssh -T git@github.com -o StrictHostKeyChecking=no'`
or chef recipe with:
`execute "ssh -T git@github.com -o StrictHostKeyChecking=no"`

(Even after the fix, this will exit with status 1, but you will see the "authenticated successfully" output when agent forwarding is working)
### Fix

Have the /etc/sudoers file keep the "SSH_AUTH_SOCK" environment variable.  This should be directly integrated into the lucid32 box.
The easiest way is to have a file in /etc/sudoers.d/ with the contents:
`Defaults    env_keep += "SSH_AUTH_SOCK"`
### Workaround

You can get around this issue by using the following shell provisioning before anything that requires agent forwarding to be working:

``` ruby
config.vm.provision :shell do |shell|
    shell.inline = "touch $1 && chmod 0440 $1 && echo $2 > $1"
    shell.args = %q{/etc/sudoers.d/root_ssh_agent "Defaults    env_keep += \"SSH_AUTH_SOCK\""}
end
```

**Comment by edrex** [comment]
Suggestion: split your provision into two scripts, one to run as root and another with `:privileged => false` (as vagrant). This avoids the need to `su vagrant`, which is where the `SSH_AUTH_SOCK` var is being dropped.
