### ISSUE TITLE
Windows Certificate remains outdated meaning unable to install

### ISSUE THREAD

**Issue by longestdrive** [hashicorp/vagrant#13058]
This links to issue #13051 which has been marked as closed.

The certificate on the windows installer remains at 10 December 2022 meaning the issue in #13051 has not been fixed.

It was advised the certificate had been updated to 20 Jan 2023 but this is not reflected in the download and windows continues to block installation

### Debug output
 Window Error - Windows has blocked installation of this app to protect my PC

### Expected behavior

Successful installation of Vagrant

### Actual behavior

Failed install

#### Vagrant version

2.3.4 AMD 64 

#### Host operating system

Windows 10 - fresh installation

#### Steps to reproduce

1. download windows version of installer 
2. Start installation and confirm installation
3. Windows blocks installation

**Comment by DMaxter** [comment]
The keys have been updated and this issue is now solved

**Comment by chrisroberts** [comment]
The CRLs can take a bit of time to fully propagate as they can be cached locally (up to 5 days I believe). Cheers!
