### ISSUE TITLE
vagrant up destroying VM and associated drives

### ISSUE THREAD

**Issue by GauravSonawane07** [hashicorp/vagrant#13075]
operating system- windows 11
vagrant version - 2.3.4

![Screenshot (24)](https://user-images.githubusercontent.com/102862192/214938130-ff33667d-69c8-49ca-91ce-a65e1c8d3b4e.png)

gist link for debug result -- https://gist.github.com/GauravSonawane07/44d4d115b0eabc279a38933045c5e118

**Comment by soapy1** [comment]
It looks like this error is coming from a the rubyhacks gem what was installed https://gist.github.com/GauravSonawane07/44d4d115b0eabc279a38933045c5e118#file-gistfile1-txt-L276. I expect this was probably installed as a plugin (`vagrant plugin install rubyhacks`)? The problem should be resolved if you uninstall that gem (`vagrant plugin uninstall rubyhacks`).

**Comment by chrisroberts** [comment]
Hi there,

As stated previously, removing the plugin will prevent the error from occurring. You can also prevent the guest from being destroyed when the initial `up` command fails by using the `--no-destroy-on-error` flag.

Cheers!

**Comment by iamGodwinAkpa** [comment]
grdf
