### ISSUE TITLE
error happend when i downlouad vagrant-libvirt

### ISSUE THREAD

**Issue by mumong** [hashicorp/vagrant#13077]
i installed vagrant_2.2.15 on my centos 6.4 machine
and when i try to `vagrant plugin install vagrant-libvirt`
fetch me back "nokogiri requires Ruby version >= 2.7, < 3.3.dev. The current ruby version is 2.6.6.146"
what should i do to fix it?
![image](https://user-images.githubusercontent.com/91200009/216505701-967ada38-cf39-4616-b5f4-93dd1b119e98.png)

**Comment by soapy1** [comment]
Hey there, looks like you are running a pretty old version of Vagrant (the latest released version is 2.3.4). Using the newest version of Vagrant should resolve this issue. Here is a link to the official download page https://developer.hashicorp.com/vagrant/downloads. Thanks

**Comment by mumong** [comment]
hi，i use a new version of vagrant,and i can download vagrant-libvirt.but when i build my virtual machine using Vagrantfile.it feed me back about something lack argument.

**Comment by soapy1** [comment]
Great to hear your download issue is resolved, but sorry to hear you are running into another issue. I'm going to go ahead and close this issue. If you are still facing a problem can you open up a new issue with all the relevant information. It'll be important to provide a minimal Vagrantfile, a debug log with the issue and information about your host system. Thanks!
