### ISSUE TITLE
Arch Linux: conflicting dependencies google-protobuf

### ISSUE THREAD

**Issue by northy** [hashicorp/vagrant#13071]
### Debug output

https://gist.github.com/northy/1fb8fed8ac7f598b86a17f9db0f3b26f

### Expected behavior

`vagrant-libvirt` plugin should install correctly

### Actual behavior

Installation failed because `google-protobuf` failed to resolve, even though `vagrant-libvirt` [does not depend on it](https://user-images.githubusercontent.com/8811216/214524788-ff37a07c-4b60-4c78-991e-64713d5bf10c.png)

#### Vagrant version

Vagrant 2.3.4

#### Host operating system

Arch Linux

#### Guest operating system

Can't run any VM because can't even install the plugin.

#### Steps to reproduce

1. `sudo pacman -Sy vagrant`
2. `vagrant plugin-install vagrant-libvirt` (or any other plugin it seems)

#### Vagrantfile

Can't run any VM because can't even install the plugin.

**Comment by soapy1** [comment]
Hey there, I'm trying to dig into this issue but I'm not able to reproduce the problem. One difference I noted between your system and my test setup is your [rubygems version is 3.3.26](https://gist.github.com/northy/1fb8fed8ac7f598b86a17f9db0f3b26f#file-vagrant_debug-txt-L3) and mine is 3.3.25. I don't expect this to be the root issue.

Could you share a bit more information about your system. In particular it would be helpful to know what
1. version of arch you are running
2. if you have any [Vagrant specific environment variables](https://developer.hashicorp.com/vagrant/docs/other/environmental-variables) set
3. if you have any other vagrant plugin installed (output of `vagrant plugin list`)

thanks!

**Comment by northy** [comment]
1. Arch is a rolling release distro so I just had the latest upgrades on the system
2. I just tried to echo all of these variables from the same terminal I'm trying to install the plugins from, and all the variables are unset
3. Nothing is installed:
```text
$ vagrant plugin list
No plugins installed.
```

Can the issue be with rubygems? I'm not sure if the one on arch is broken. I started having problems with vagrant + vagrant-libvirt on arch when openssl was upgraded to 3.0, after that I could never install both plugins and get them to work again

**Comment by soapy1** [comment]
Digging into this a bit more I tried to reproduce this behavior in couple of different ways
1. installing rubygems 3.3.26
2. installing an older version of vagrant (with an older google-protobuf version) upgrading to the latest version of vagrant
3. installing google-protobuf system wide

unfortunately, I was not able to reproduce the issue 😞 I would be curious to know where the rouge version of the google-protobuf gem is coming from. All of Vagrant's dependencies should be in `/opt/vagrant/embedded/gems/2.3.4/gems/`. I wonder if there are some conflicting gems that exist somewhere else on the system.

**Comment by northy** [comment]
It seems like the problem was fixed by running `sudo gem uninstall` on all the gems on this list that appeared on the Debug log:

```text
DEBUG bundler: Dependency list for installation:
 - vagrant-libvirt > 0
 - bcrypt_pbkdf = 1.1.0
 - childprocess = 4.1.0
 - ed25519 = 1.3.0
 - erubi = 1.11.0
 - googleapis-common-protos-types = 1.4.0
 - google-protobuf = 3.21.12
 - grpc = 1.50.0
 - hashicorp-checkpoint = 0.1.5
 - i18n = 1.12.0
 - concurrent-ruby = 1.1.10
 - listen = 3.7.1
 - rb-fsevent = 0.11.2
 - rb-inotify = 0.10.1
 - ffi = 1.15.5
 - log4r = 1.1.10
 - mime-types = 3.4.1
 - mime-types-data = 3.2022.0105
 - net-ftp = 0.2.0
 - net-protocol = 0.2.1
 - timeout = 0.3.1
 - time = 0.2.1
 - date = 3.3.3
 - net-ssh = 7.0.1
 - net-sftp = 4.0.0
 - net-scp = 4.0.0
 - rb-kqueue = 0.2.8
 - rexml = 3.2.5
 - rgl = 0.5.9
 - stream = 0.5.5
 - pairing_heap = 1.0.0
 - rubyzip = 2.3.2
 - vagrant_cloud = 3.0.5
 - excon = 0.95.0
 - wdm = 0.1.1
 - winrm = 2.3.6
 - builder = 3.2.4
 - gssapi = 1.3.1
 - gyoku = 1.4.0
 - httpclient = 2.8.3
 - logging = 2.3.1
 - little-plugger = 1.1.4
 - multi_json = 1.15.0
 - nori = 2.6.0
 - rubyntlm = 0.6.3
 - winrm-elevated = 1.2.3
 - winrm-fs = 1.3.5
 - ipaddr = 1.2.5
 - vagrant = 2.3.4
 - coderay = 1.1.3
 - diff-lcs = 1.5.0
 - diffy = 3.4.2
 - docile = 1.4.0
 - excon = 0.92.4
 - fog-core = 2.3.0
 - fog-json = 1.2.0
 - fog-libvirt = 0.9.0
 - fog-xml = 0.1.4
 - formatador = 1.1.0
 - generator = 0.0.1
 - google-protobuf = 3.21.5
 - googleapis-common-protos-types = 1.3.2
 - grpc = 1.48.0
 - lazy_priority_queue = 0.1.1
 - method_source = 1.0.0
 - minitest = 5.16.3
 - net-scp = 3.0.0
 - net-sftp = 3.0.0
 - net-ssh = 6.1.0
 - nokogiri = 1.13.8
 - power_assert = 2.0.2
 - pry = 0.14.1
 - rake = 13.0.6
 - rb-fsevent = 0.11.1
 - rgl = 0.5.8
 - rspec = 3.11.0
 - rspec-core = 3.11.0
 - rspec-expectations = 3.11.0
 - rspec-mocks = 3.11.1
 - rspec-support = 3.11.0
 - ruby-libvirt = 0.8.0
 - ruby2_keywords = 0.0.5
 - simplecov = 0.21.2
 - simplecov-html = 0.12.3
 - simplecov-lcov = 0.8.0
 - simplecov_json_formatter = 0.1.4
 - stream = 0.5.4
 - test-unit = 3.5.7
 - thor = 0.18.1
 - x25519 = 1.0.10
```

The interesting part is that I didn't have anything ruby-related installed (pacman uninstalled all packages depending on ruby just to make sure) but it didn't solve the problem. It seems that the gems under `/lib/ruby/gems/3.0.0/gems` are being picked up by vagrant though, is it the standard behavior to use the system packages instead of only using the ones in `/opt/vagrant/embedded/gems/2.3.4/gems/`?

**Comment by soapy1** [comment]
> It seems that the gems under /lib/ruby/gems/3.0.0/gems are being picked up by vagrant though, is it the standard behavior to use the system packages instead of only using the ones in /opt/vagrant/embedded/gems/2.3.4/gems/

So, I don't really know how arch works or how the Vagrant package is setup there. I _think_ I would expect globally installed gems to interfere with Vagrant running since Vagrant is running with system Ruby. I would expect gems that aren't installed globally to not interfere with Vagrant. Again, I don't know very many details about how that is all setup so I'm happy to be corrected. On other platforms Vagrant ships ruby in the installer so has an isolated ruby environment to run from.

Glad you got your environment working! I'm going to close out this issue.
