### ISSUE TITLE
Cannot start CentOS vagrant box on apple silicon M1 Pro device

### ISSUE THREAD

**Issue by jasper-s** [hashicorp/vagrant#13081]
### Debug output

https://gist.github.com/jasper-s/4bd686804420a51c0ba01e93050fb818

### Expected behavior

Vagrant starts the VM correctly

### Actual behavior

VM is not started. Instead I get an error like so:
```
INFO interface: error: An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["start", "/Users/<me>/Documents/projects/aem-provision/.vagrant/machines/author1/vmware_desktop/936dbc2c-8437-47f4-acc4-beddd4a1f3b9/packer-vmware-iso.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: 2023-02-09T10:41:53.670| ServiceImpl_Opener: PID 30082
Error: The operation was canceled
```
When this happens, I can start the vm with the vmrun -T fusion start /Users/<me>/Documents/projects/aem-provision/.vagrant/machines/author1/vmware_desktop/936dbc2c-8437-47f4-acc4-beddd4a1f3b9/packer-vmware-iso.vmx, but I miss out on all the vagrant features of course.

#### Vagrant version

Vagrant 2.3.4

#### Host operating system

macOS Ventura 13.2 (22D49)

#### Guest operating system

CentOS 9 Stream (20230131-aarch64 build)

#### Steps to reproduce

1. Create or find a CentOS 9 Stream box (I did this with packer). Regardless of specific configuration, this seemed to fail for me. box is named author1.
2. On an Apple Silicon device, execute `vagrant up author1`.  For reference, you can check https://gist.github.com/sbailliez/2305d831ebcf56094fd432a8717bed93 for more info on what to set up.
3. Observe the errors.

#### Vagrantfile

```ruby
Vagrant.configure('2') do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.define 'author' do |author|
    author.vm.box = 'file://boxes/aem-author.tar.gz'
    author.vm.hostname = 'author.vagrant'
    author.vm.network :private_network, ip: '192.168.56.20'
  end
end
```

**Comment by soapy1** [comment]
This should be fixed with this pr https://github.com/hashicorp/vagrant-vmware-desktop/pull/59. Since this issue is being tracked in the https://github.com/hashicorp/vagrant-vmware-desktop repo I'm going to go ahead and close this.
