### ISSUE TITLE
Docker received unknown output from `docker build`

### ISSUE THREAD

**Issue by rbudiharso** [hashicorp/vagrant#13109]
### Debug output

https://gist.github.com/rbudiharso/c93dbbd4660c905c8c89575ef41f964b

### Expected behavior

Vagrant up successfully
### Actual behavior

`Vagrant received unknown output from `docker build` while building a container: sha256:bd07d17a485a2488972f0b6047109ef78984393b398445cf1f52aedae0485ca0`
### Reproduction information 
run `vagrant up`
#### Vagrant version

Vagrant 2.3.4
#### Host operating system

Mac OS Ventura 13.3
#### Guest operating system

Ubuntu
#### Steps to reproduce

1. vagrant up

#### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.build_args = ["--load", "--quiet"]
    d.remains_running = true
    d.has_ssh = true
  end
end

```
```Dockerfile
FROM ubuntu:lunar

ENV TZ=Asia/Jakarta
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y

RUN apt-get install -y --no-install-recommends ssh sudo

RUN useradd --create-home -s /bin/bash vagrant
RUN echo -n 'vagrant:vagrant' | chpasswd
RUN echo 'vagrant ALL = NOPASSWD: ALL' > /etc/sudoers.d/vagrant
RUN chmod 440 /etc/sudoers.d/vagrant
RUN mkdir -p /home/vagrant/.ssh
RUN chmod 700 /home/vagrant/.ssh
RUN echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ==" > /home/vagrant/.ssh/authorized_keys
RUN chmod 600 /home/vagrant/.ssh/authorized_keys
RUN chown -R vagrant:vagrant /home/vagrant/.ssh
RUN sed -i -e 's/Defaults.*requiretty/#&/' /etc/sudoers
RUN sed -i -e 's/\(UsePAM \)yes/\1 no/' /etc/ssh/sshd_config

RUN mkdir /var/run/sshd

RUN apt-get -y install openssh-client

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

```

Similar to #12245

**Comment by chrisroberts** [comment]
Hi there,

The docker provider uses the output provided by docker to determine the success of the command. The `--quiet` flag that you have added is removing some of the output that Vagrant is expecting and thus causing it to fail. If you remove the `--quiet` flag from your `build_args` then the Vagrant run should succeed. The `--load` flag also does not appear to be a valid flag, but from the output provided it is the `--quiet` flag that is causing the problem.

Cheers!
