### ISSUE TITLE
vagrant ssh permission denied (publickey)

### ISSUE THREAD

**Issue by iameru** [hashicorp/vagrant#13106]
### What did I do?

I want to try vagrant. sadly vbox fails and this one aswell. I followed the guide at https://developer.hashicorp.com/vagrant/tutorials/getting-started but had to get another image as `hashicorp/bionic64` the vbox errored out and it doesnt support libvirt.

```sh
mkdir vagrantfolder
cd vagrantfolder
vagrant init debian/jessie64
vagrant up --provider libvirt
```

### Debug output

```sh
# some content ommitted, this looked interesting though
==> default: Waiting for domain to get an IP address...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 192.168.121.143:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
[sudo] password for user:
==> default: Mounting NFS shared folders...
  ~/vagrantfolder $ vagrant ssh
vagrant@192.168.121.143: Permission denied (publickey).
```

### Expected behavior

`vagrant ssh` should give me access to the mashine

### Actual behavior

`vagrant ssh` errored out:

#### Vagrant version

`Vagrant 2.3.4`

#### Host operating system

manjaro

#### Guest operating system

`debian/jessie64`

#### Steps to reproduce

do all I did, see top

#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
end
```

**Comment by chrisroberts** [comment]
Hi there,

Would you please try using the [`generic/debian8`](https://app.vagrantup.com/generic/boxes/debian8) box and see if you still experience the same error. If you do, would you please provide a gist with the output from a fresh `vagrant up --debug` and `vagrant ssh --debug` so we can determine where the root of the issue may be?

Thanks!

**Comment by iameru** [comment]
> Hi there,
> 
> Would you please try using the [`generic/debian8`](https://app.vagrantup.com/generic/boxes/debian8) box and see if you still experience the same error. If you do, would you please provide a gist with the output from a fresh `vagrant up --debug` and `vagrant ssh --debug` so we can determine where the root of the issue may be?
> 
> Thanks!

Got asked a password with this image and could log in with the default password `vagrant`. :+1: 
```sh
  ~/vagrant $ vagrant ssh
vagrant@192.168.121.175's password:
You have mail.
vagrant@debian8:~$
```

**Comment by phinze** [comment]
Hi @iameru - glad to hear that you got the SSH command to work. For the shared folder issue, we'd need to see more of your config. Can you share the contents of the `Vagrantfile` that you used when you saw this error?

**Comment by chrisroberts** [comment]
Hey there,

I am closing this due to lack of response. If this is still an issue, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us with the reproduction and allow us to provide recommendations. Thanks!
