### ISSUE TITLE
Install instruction for Ubuntu/Debian outputs binary data into terminal

### ISSUE THREAD

**Issue by fumiyas** [hashicorp/vagrant#13101]
Install instruction for Ubuntu/Debian described at https://developer.hashicorp.com/vagrant/downloads shows a command-line: ` wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg`. This command-line dumps binary data in hashicorp-archive-keyring.gpg into terminal.

### Expected behavior

```console
$ wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null
...no output except errors...
```

### Actual behavior

```console
$ wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
...binary data in hashicorp-archive-keyring.gpg...
```

**Comment by phinze** [comment]
Thanks for the report! We're working on getting this fixed over in https://github.com/hashicorp/dev-portal/pull/1737 - I'll follow up once it's been merged and deployed.

**Comment by phinze** [comment]
This is now fixed! Install instructions now read:

```sh
wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt update && sudo apt install vagrant
```
