### ISSUE TITLE
Vagrant needs a configuration option to not globally enable the NatDNSProxy option in Virtualbox

### ISSUE THREAD

**Issue by bmhatfield** [hashicorp/vagrant#1313]
As seen in this pull request (https://github.com/mitchellh/vagrant/issues/749), Vagrant will globally enable "--natdnsproxy1", "on" except if the machine has a resolv.conf that points to localhost.

Unfortunately, the natdnsproxy in Virtualbox is not very reliable. In fact, it's so bad that TCP lookups against it will fail.

For example, 'dig google.com' works fine but SOMETIMES the dnsproxy will fail and 'dig google.com +tcp' will not work.

This is a problem when issuing DNS lookups against hosts with a large response (IE, an AWS ELB or any sort of DNS load balanced service), because DNS falls back to TCP for lookups.

Thus, certain lookups through the NatDNSProxy will fail. I don't need it enabled (I don't fit the use case in the above pull request), and since it's junk, I don't _want_ it enabled.

How can I turn it off? VirtualBox doesn't seem to like me adding a second modifyvm that adds the command again to turn it back off.

**Comment by scottsb** [comment]
This is old, but in case anybody else comes here wondering about the last comments about this not working: I think there was a misunderstanding about the setting's purpose. All the `auto_nat_dns_proxy` setting does is tell Vagrant not to attempt to set the DNS proxying/host resolver settings at all (either off or on). That means that it falls back to VirtualBox-level defaults (possibly defined at the box level--not sure). If you want to turn off all varieties of proxying you need to use the full set of:

```
    vb.auto_nat_dns_proxy = false
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
```
