### ISSUE TITLE
OSX, Vagrant, Fusion, vagrant-vmware-desktop always launches ssh/portforward via ipv6 on host

### ISSUE THREAD

**Issue by EnorMOZ** [hashicorp/vagrant#13143]
When using Vagrant 2.3.4, Fusion 13.0.2 , and vagrant-vmware-desktop (3.0.) provider on a m1 mac running 13.3.1 it will always forward ssh port using ipv6 even if the host currently has ipv6 disable for the network device and host_ip is assigned at localhost/127.0.0.1 and not ipv6.

How do I tell it to use ipv4 and not ipv6 ?

`config.vm.network "forwarded_port", guest: 22, host: 2222, host_ip: "127.0.0.1", id: "ssh"`

On mac it shows 2222 is utilizing ipv6
`vagrant-v 4578 root 12u IPv6 0xeb5f3de393e534d3 0t0 TCP *:2222 (LISTEN)`

### Expected behavior

`vagrant-v 4578 root 12u IPv4 0x2cc683a1668ce0db 0t0  TCP localhost:2222 (LISTEN)`

### Actual behavior

"forwarded_port" is using ipv6 
`vagrant-v 4578 root 12u IPv6 0xeb5f3de393e534d3 0t0 TCP *:2222 (LISTEN)`

### Reproduction information 
Run OSX and run vagrant up

#### Vagrant version

Vagrant 2.3.4

#### Host operating system

OSX 13.3.1 M1 chip

#### Guest operating system

RockyLinux9, Ubuntu 22.04 

#### Steps to reproduce

Run vagrant 

#### Vagrantfile

config.vm.network "forwarded_port", guest: 22, host: 2222, host_ip: "127.0.0.1", id: "ssh"

**Comment by phinze** [comment]
Hi @EnorMOZ - thanks for the report. Looks like you also [reported this on the provider repo](https://github.com/hashicorp/vagrant-vmware-desktop/issues/77), which is probably a better place to track it, so I'll close this one and we can address the issue there.
