### ISSUE TITLE
Vagrant 2.3.5 deb fails to install on Ubuntu 20

### ISSUE THREAD

**Issue by iainelder** [hashicorp/vagrant#13155]
### Debug output

[Failed CI run of Vagrant 2.3.5](https://github.com/iainelder/dotfiles/actions/runs/4999684163).

### Expected behavior

Vagrant 2.3.5 should be installed via apt.

See [last CI execution of Vagrant 2.3.4](https://github.com/iainelder/dotfiles/actions/runs/4988225624/jobs/8930741878) for a successful example.

### Actual behavior

The CI run shows the following error when installing Vagrant 2.3.5 via apt.

```text
+ sudo apt-get install ./vagrant_2.3.5-1_amd64.deb
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  vagrant:none
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/139 MB of archives.
After this operation, 357 MB of additional disk space will be used.
Get:1 /tmp/tmp.DESY5s8fZA/vagrant_2.3.5-1_amd64.deb vagrant none 0:2.3.5-1 [139 MB]
debconf: delaying package configuration, since apt-utils is not installed
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 12 package 'vagrant':
 empty value for 'Architecture' field
dpkg: error processing archive /tmp/tmp.DESY5s8fZA/vagrant_2.3.5-1_amd64.deb (--unpack):
 package architecture () does not match system (amd64)
Errors were encountered while processing:
 /tmp/tmp.DESY5s8fZA/vagrant_2.3.5-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: Process completed with exit code 100.
```

#### Vagrant version

Vagrant 2.3.5

#### Host operating system

Ubuntu 20

#### Guest operating system

Not applicable.

#### Steps to reproduce

Execute [this script](https://github.com/iainelder/dotfiles/blob/master/programs/vagrant/install.bash) as root on Ubuntu 20 to exactly reproduce the CI installation process.

For humans:

1. Download Vagrant 2.3.5 deb
2. Install deb: `sudo apt install ./vagrant.2.3.5.deb`
3. Note error message

#### Vagrantfile

None.

**Comment by rgl** [comment]
Maybe that's because of that that vagrant 2.3.5 is not available at the repository at:

* https://apt.releases.hashicorp.com/dists/jammy/Release
* https://apt.releases.hashicorp.com/dists/jammy/main/binary-amd64/Packages

Maybe the vagrant CI pipeline should check whether is can actually install vagrant from the repository?

**Comment by iainelder** [comment]
Thanks, @rgl , I didn't know about the [Hashicorp Apt repostiory](https://www.hashicorp.com/blog/announcing-the-hashicorp-linux-repository). Maybe it was still missing from the Vagrant documentation when I wrote my installation script back in 2021.

My own CI process runs my custom installation scripts. Feel free to adapt my Vagrant installation script for any installability testing.

Now I see that the Apt repository is already supported by [`deb-get`](https://github.com/wimpysworld/deb-get/tree/main/01-main), so one day I'll replace that custom script with a `deb-get install` command.

**Comment by chrisroberts** [comment]
Fixed deb package is available in the dev build [here](https://github.com/hashicorp/vagrant/releases/tag/2.3.6.dev%2B68b3d94). Will likely be pushing a point release that includes this update tomorrow.

**Comment by iainelder** [comment]
[Today's CI run](https://github.com/iainelder/dotfiles/actions/runs/5030617904/jobs/9023156889)  picked up package version 2.3.6 and installed it correctly. This is fixed now. Thanks, everyone!
