### ISSUE TITLE
Vagrant up fails with supHardenedWinVerifyProcess failed with -5607: ntdll.dll on Windows 11 Pro Insider

### ISSUE THREAD

**Issue by Amitabh1989** [hashicorp/vagrant#13163]
##Configuration info :
Versions : (Vagrant 2.3.4, Oracle VirtaulBox Version 7.0.8 r156879 (Qt5.15.2)).
OS settings : Firewall disabled, Antivirus disabled
RAM assigned to VMs : 2GB
Machine
Dell Inspiron 7501
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
Installed RAM	16.0 GB (15.8 GB usable)
System type	64-bit operating system, x64-based processor

### Debug output
```

3078.3554:   00007ffa4da8b000-00007ffa4da8dfff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
3078.3554:   00007ffa4da8e000-00007ffa4da8efff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
3078.3554:   00007ffa4da8f000-00007ffa4db07fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
3078.3554:   00007ffa4db08000-00007ffa4db09fff 0x0000/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
3078.3554:   00007ffa4db0a000-00007ffffffeffff 0x0001/0x0000 0x0000000
3078.3554: VBoxHeadless.exe: Differences in section #8 (.rsrc) between file and memory:
3078.3554:   00007ff7d09525f8 / 0x01125f8: 00 != 50
3078.3554:   00007ff7d09525f9 / 0x01125f9: 00 != 41
3078.3554:   00007ff7d09525fa / 0x01125fa: 00 != 44
3078.3554:   00007ff7d09525fb / 0x01125fb: 00 != 44
3078.3554:   00007ff7d09525fc / 0x01125fc: 00 != 49
3078.3554:   00007ff7d09525fd / 0x01125fd: 00 != 4e
3078.3554:   00007ff7d09525fe / 0x01125fe: 00 != 47
3078.3554:   00007ff7d09525ff / 0x01125ff: 00 != 58
3078.3554:   Restored 0xa08 bytes of original file content at 00007ff7d09525f8
3078.3554: Error (rc=-5607):
3078.3554: ntdll.dll: SizeOfImage (0x218000) isn't close enough to the mapping size (0x21a000)
3078.3554: Error (rc=-5607):
3078.3554: supHardenedWinVerifyProcess failed with -5607: ntdll.dll: SizeOfImage (0x218000) isn't close enough to the mapping size (0x21a000)
3078.3554: Error -5607 in supR3HardNtChildPurify! (enmWhat=5)
3078.3554: supHardenedWinVerifyProcess failed with -5607: ntdll.dll: SizeOfImage (0x218000) isn't close enough to the mapping size (0x21a000)
```

### Expected behavior
Vagrant up should succeed and my VM should get installed

### Actual behavior
vagrant up command fails and does not inform anything useful to debug further. Could not get information from Vagrant Customer support as well.

#### Host operating system
Windows 11 Pro Insider

#### Guest operating system
geerlingguy/centos7

#### Steps to reproduce

1. vagrant init geerlingguy/centos7
2. vagrant up

#### Vagrantfile

```ruby
# Copy-paste your Vagrantfile here. Remove any sensitive information such as passwords, authentication tokens, or email addresses.
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "geerlingguy/centos7"

end

Vagrant Logs : https://drive.google.com/drive/folders/1R5qOFXrMZaNOrzfk67bfD7wFvpb7Er5y?usp=share_link

**Comment by chrisroberts** [comment]
Hi there,

The error that you are encountering is originating from VirtualBox and not Vagrant. It appears that the issue is likely due to the beta nature of the Windows version you are running. The solution will likely be running a standard install of Windows 11. Some relevant VirtualBox forum posts discussing the same behavior you are encountering:

* https://forums.virtualbox.org/viewtopic.php?t=106200&start=0
* https://forums.virtualbox.org/viewtopic.php?f=6&t=109295

Cheers!
