### ISSUE TITLE
vagrant.exe and other files flagged by AV software CylanceProtect

### ISSUE THREAD

**Issue by mtissington** [hashicorp/vagrant#13172]
The AV software CylanceProtect is flagging multiple files as a threat

2.3.6 => vagrant.exe
2.3.4 => genpeimg.exe, genidl.exe, libquadmath-0.dll

What to do?

**Comment by chrisroberts** [comment]
Hi there,

Most anti-virus software provides the ability to manually allow an executable to be used, which it appears would be needed here.

Cheers
