### ISSUE TITLE
APT repository does not include packages for Ubuntu 23.04 "Lunar Lobster"

### ISSUE THREAD

**Issue by Flimm** [hashicorp/vagrant#13173]
I tried to install Vagrant on Ubuntu 23.04 using [the official instructions](https://developer.hashicorp.com/vagrant/downloads) for Ubuntu/Debian:

```
$ wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
$ echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
$ sudo apt update && sudo apt install vagrant
```

When running `sudo apt update`, I saw this error:

```
Err:11 https://apt.releases.hashicorp.com lunar Release
  404  Not Found [IP: 18.66.171.113 443]
Reading package lists... Done
E: The repository 'https://apt.releases.hashicorp.com lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

To fix it, I opened `/etc/apt/sources.list.d/hashicorp.list` and edited it to replace `lunar` with `kinetic`, which is the codename of Ubuntu 22.10:

```
deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com kinetic main
```

This is not a full solution, because I am not sure that the packages packaged for Ubuntu 22.10 "Kinetic Kudu" will work on Ubuntu 23.04 "Lunar Lobster". Could the repo be fixed to include packages for Ubuntu 23.04, or could the official instructions be fixed?

**Comment by chrisroberts** [comment]
Hi there,

This is being worked on and should be resolved soon. I'll post an update once I have confirmation.

Cheers!

**Comment by chrisroberts** [comment]
This has been resolved and should be properly available now.

Cheers!

**Comment by Flimm** [comment]
When I run `sudo apt update`, I get this warning now:

    W: Conflicting distribution: https://apt.releases.hashicorp.com lunar InRelease (expected lunar but got xenial)

Here are the contents of my configuration file:

```
$ cat /etc/apt/sources.list.d/hashicorp.list
deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com lunar main
```

**Comment by chrisroberts** [comment]
@Flimm Thanks for pointing that out. I was able to reproduce the same behavior locally. It has been reported internally and should be addressed shortly.

**Comment by chrisroberts** [comment]
@Flimm Thank you again for reporting the inconsistency in the repository. This has been resolved. Cheers!
