### ISSUE TITLE
Increase clarity when devel libraries are needed for a plugin

### ISSUE THREAD

**Issue by jkugler** [hashicorp/vagrant#13184]
**Is your feature request related to a problem? Please describe.**
When trying to install a plugin, a missing library message is somewhat misleading

When I was installing the vagrant-libvirt plugin, I got the message:
```
Building native extensions. This could take a while...
Vagrant failed to install the requested plugin because it depends
on a library which is not currently installed on this system. The
following library is required by the 'vagrant-libvirt' plugin:

  libvirt

Please install the library and then run the command again.
```

The libvirt library *was* installed. It took me quite a while to figure out I needed to install the libvirt *development* libraries.

**Describe the solution you'd like**
I understand the reduction in verbosity was part of https://github.com/hashicorp/vagrant/issues/11775 and that was probably needed. However, it wasn't terribly clear at first.

Maybe a message like "The following library (and its development package) is required by the 'vagrant-libvirt' plugin." I think that would have alerted me to the need to install libvirt-dev.

**Comment by chrisroberts** [comment]
Check if more information can be extracted out [here](https://github.com/hashicorp/vagrant/blob/2092df529ae73bd0ae4d01e2d35c8952b9620988/lib/vagrant/plugin/manager.rb#L194)
