### ISSUE TITLE
vagrant 2.3.7 from homebrew on macOS 13.4 throws "Invalid ABI specified" if virtualbox plugin is installed

### ISSUE THREAD

**Issue by defanator** [hashicorp/vagrant#13210]
### Debug output

Output of the `vagrant version --debug`: https://gist.github.com/defanator/3a9d90971c4b6218f2d8a79b7a403767

### Expected behavior

No error.

### Actual behavior

"Invalid ABI specified" when accessing virtualbox plugin.

### Reproduction information 

Reproduces constantly on macOS 13.4 + homebrew 4.0.23, tried to deinstall/reinstall vagrant multiple times, expunge plugins with force, reinstall plugin - nothing changes the results.

#### Vagrant version

```
[2023-06-19 08:30:22] defan@defmbp ~ % vagrant -v
Vagrant 2.3.7
```

#### Host operating system

```
[2023-06-19 08:30:17] defan@defmbp ~ % sw_vers 
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66

[2023-06-19 08:32:38] defan@defmbp ~ % uname -a
Darwin defmbp.lan 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

[2023-06-19 08:30:17] defan@defmbp ~ % brew --version
Homebrew 4.0.23
```

#### Guest operating system

N/A

#### Steps to reproduce

1. Install vagrant from homebrew.
2. Install virtualbox plugin (it gets 0.8.6 as of time of submitting the issue).
3. Try to run `vagrant version`.

#### Vagrantfile

N/A (reproduces with any valid Vagrantfile)

**Comment by chrisroberts** [comment]
Hi there,

The `virtualbox` RubyGem is not a Vagrant plugin. Vagrant provides support for VirtualBox with a builtin plugin, so no plugin installation is required. Uninstalling virtualbox from the plugin system (`vagrant plugin uninstall virtualbox`) will resolve the issue.

Cheers!
