### ISSUE TITLE
vagrant version command doesn't work

### ISSUE THREAD

**Issue by luckeyca** [hashicorp/vagrant#13246]
### Expected behavior

"vagrant -v",  "vagrant --version" and "vagrant version" should work
### Actual behavior

"vagrant -v" and "vagrant --version" command work, but "vagrant version" command doesn't.

#### Vagrant version

vagrant version is 2.3.7 on ubuntu 22.04.

#### Host operating system

Ubuntu 22.04

#### Steps to reproduce

1.   add hashicorp ubuntu repo
2. apt-get install vagrant=2.3.7
3. run "vagrant version" command returns the following error:

root@0a9320761ebf:~# vagrant version
Vagrant failed to initialize at a very early stage:

The executable 'cmd.exe' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.

**Comment by chrisroberts** [comment]
Hi there,

I tested this and it is working as expected. If you are still encountering this behavior, please open a new issue and be sure to include a gist of the debug output from running the command (`vagrant version --debug`).

Cheers!
