### ISSUE TITLE
Install Ansible link in the documentation leads to a 404 page 

### ISSUE THREAD

**Issue by Moandh81** [hashicorp/vagrant#13260]
On this page  : 

https://developer.hashicorp.com/vagrant/docs/provisioning/ansible

in the "setp requirements" section, when you click on the link "Install Ansible", 
the link is broken from Ansible side.

Please review this problem .

**Comment by kaitlincart** [comment]
Thanks for letting us know.  PR #13264 updates the link. 

- Kait
