### ISSUE TITLE
Hyper-v from windows 10 works great with virtualbox and vmware, wrong documentation.

### ISSUE THREAD

**Issue by elico** [hashicorp/vagrant#13262]
The documentation at:
https://github.com/hashicorp/vagrant/blob/main/website/content/docs/providers/hyperv/index.mdx

is way old and doesn't describe the current state of relationship of type 2 hypervisers: Hyper-v, VirtualBOX and Vmware player or Workstation and other related virtualization technologies since windows 10 and up.
Currently Hyper-V can be enabled and co-exist with all other commercial windows workstations technology.
I cannot volunteer to perfect the documentation but can at-least say that the current docs doesn't reflect the reality.

**Comment by nidhi-singh02** [comment]
I would like to work on this, Let me know how we want the documentation to be ?

**Comment by elico** [comment]
@nidhi-singh02 I will first attach the related MS Docs:
https://learn.microsoft.com/en-us/virtualization/api/#windows-hypervisor-platform

and the related VirtualBox docs:
https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/gimproviders.html
