### ISSUE TITLE
Cannot run recent versions of Node.js in Vagrant boxes

### ISSUE THREAD

**Issue by BadIdeaException** [hashicorp/vagrant#13263]
Recent versions of Node.js (v18.18 and newer) fail with an ENOTSUP error when running NPM commands inside a Vagrant box. I have tried this with both versions from the [Nodesource repos](https://downloads.nodesource.com/) and directly from [nodejs.org](https://nodejs.org/en/download).

This error does not occur with Node.js v17.x.

### Debug output

For debug output of `vagrant up` see [vagrant.log](https://github.com/hashicorp/vagrant/files/12671261/vagrant.log).

Error log of `npm start`:
``` 
0 verbose cli /usr/local/lib/nodejs/node-v18.18.0-linux-x64/bin/node /usr/local/lib/nodejs/node-v18.18.0-linux-x64/bin/npm
1 info using npm@9.8.1
2 info using node@v18.18.0
3 timing npm:load:whichnode Completed in 16ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/nodejs/node-v18.18.0-linux-x64/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/vagrant/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/vagrant/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/local/lib/nodejs/node-v18.18.0-linux-x64/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 10ms
17 timing npm:load:configload Completed in 11ms
18 timing config:load:flatten Completed in 4ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 6ms
21 verbose title npm start
22 verbose argv "start"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/home/vagrant/.npm/_logs/2023-09-20T09_14_15_571Z-
26 verbose logfile /home/vagrant/.npm/_logs/2023-09-20T09_14_15_571Z-debug-0.log
27 timing npm:load:logFile Completed in 37ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 129ms
31 timing command:run-script Completed in 15ms
32 timing command:start Completed in 93ms
33 verbose stack Error: Could not read package.json: Error: ENOTSUP: operation not supported on socket, read
34 verbose cwd /vagrant
35 verbose Linux 5.15.0-79-generic
36 verbose node v18.18.0
37 verbose npm  v9.8.1
38 error code ENOTSUP
39 error syscall read
40 error errno -95
41 error Could not read package.json: Error: ENOTSUP: operation not supported on socket, read
42 verbose exit -95
43 timing npm Completed in 848ms
44 verbose code -95
45 error A complete log of this run can be found in: /home/vagrant/.npm/_logs/2023-09-20T09_14_15_571Z-debug-0.log
```

### Expected behavior

`npm start` should run the script.

### Actual behavior

```
npm ERR! code ENOTSUP
npm ERR! syscall read
npm ERR! errno -95
npm ERR! Could not read package.json: Error: ENOTSUP: operation not supported on socket, read

npm ERR! A complete log of this run can be found in: /home/vagrant/.npm/_logs/2023-09-20T08_13_54_770Z-debug-0.log
```
Other operations also result in socket errors, i.e. `npm install mocha`:
```
npm WARN tar TAR_ENTRY_ERROR ENOTSUP: operation not supported on socket, write
```

#### Vagrant version

Vagrant 2.3.7

#### Host operating system

Ubuntu Jammy
```
Linux XXXXXXXXXX 6.2.0-31-generic #31~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Aug 16 13:45:26 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
``` 

#### Guest operating system

Tried with ubuntu/jammy64 and ubuntu/lunar64

#### Steps to reproduce

1. Place the below `Vagrantfile`, `package.json` and `main.js` in a folder and cd to it
2.  `vagrant up`  then `vagrant ssh`
3. `cd /vagrant`
4. `npm start`

#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  # Install Node.JS
  config.vm.provision "shell", name: "Install Node.JS", env: { "NODE_MAJOR" => "18" }, inline: <<-SHELL
    # Install necessary packages for downloading and verifying new repository information
    apt-get install -y ca-certificates curl gnupg
    # Create a directory for the new repository's keyring, if it doesn't exist
    mkdir -p /etc/apt/keyrings
    # Download the new repository's GPG key and save it in the keyring directory
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    # Add the new repository's source list with its GPG key for package verification
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
    # Update local package index to recognize the new repository
    sudo apt-get update
    # Install Node.js from the new repository
    sudo apt-get install -y nodejs
  SHELL
end
``` 
`package.json`:
```
{
  "scripts": {
    "start": "node main.js"
  }
}
``` 
`main.js`:
```
console.log('Hello world');
```

**Comment by ViniciusGularte** [comment]
Facing the same ENOTSUP error with Node.js v18.18 in Vagrant. It works fine with v17.x. Watching this thread for solutions.

**Comment by BadIdeaException** [comment]
Just tried this on another computer, and I am seeing the same behavior there, too.

**Comment by chrisroberts** [comment]
@BadIdeaException Are you still encountering this behavior? I used the provided Vagrantfile and everything worked as expected. Would you mind verifying the error still occurs for you on the latest `ubuntu/jammy64` box release?

Thanks!

**Comment by BadIdeaException** [comment]
I'm still seeing the same thing. Guest OS is now:

`uname -a`:
``` 
Linux ubuntu-jammy 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
`vagrant box list`
```
...
ubuntu/jammy64            (virtualbox, 20230929.0.0)
...
```

**Comment by sunxyw** [comment]
same problem here, any fix?

**Comment by dugwood** [comment]
@sunxyw I've got the issue too. It's only when npm is installed in a mounted directory (shared directory). So I've moved my npm install directory to a non-shared directory, which works. Not great, but does the trick too.

**Comment by ceztko** [comment]
Same error but just on Virtualbox with a much simpler code residing on a shared directory, so probably same as @dugwood. The problem seems to be specifically related on the node ESModule loader. In fact, the same simple code but running as CommonJS doesn't manifest the issue. Possibly something that node upstream should be informed of.

**Comment by owenallenaz** [comment]
Ran into this issue, and was able to switch to `type: "smb"` for the synced_folder and it resolved the issue. I haven't been on it long enough to determine if that new type is going to open up it's own problems, but for now stuff appears to be working.

**Comment by ceztko** [comment]
I'm stopping notifications on this since I have nothing in production that makes use of this setup but if anyone of you is serious about seeing this fixed to the root cause I would create an issue on [node](https://github.com/nodejs/node/issues) doing some further research and reporting these [discoveries](https://github.com/hashicorp/vagrant/issues/13263#issuecomment-1827529957).

**Comment by BadIdeaException** [comment]
Closing this in favor of upstream issue https://github.com/nodejs/node/issues/50876

**Comment by abhishek-ejam** [comment]
I can also confirm that below vagrant/virtualbox config is also affected by this bug:
**Virtualbox: 6.1
Vagrant box: bento/ubuntu-22.04 (>=202309.08.0)**

**Comment by hiAndrewQuinn** [comment]
Confirming this still happens, although it's a Node issue, not a Laravel issue. 

 I'm on Ubuntu 23.10, using VB as a Vagrant provider for Homestead. On the shared folder `code/`,

```bash
composer create-project --prefer-dist laravel/laravel code/
cd code/
composer require laravel/breeze --dev
```

works fine, but
```
php artisan breeze:install
```

does not. Instead it leads to

```bash
┌ Which Breeze stack would you like to install? ───────────────┐
 │ Blade with Alpine                                            │
 └──────────────────────────────────────────────────────────────┘

 ┌ Would you like dark mode support? ───────────────────────────┐
 │ Yes                                                          │
 └──────────────────────────────────────────────────────────────┘

 ┌ Which testing framework do you prefer? ──────────────────────┐
 │ PHPUnit                                                      │
 └──────────────────────────────────────────────────────────────┘

   INFO  Installing and building Node dependencies.  

npm ERR! code ENOTSUP
npm ERR! syscall write
npm ERR! errno -95
npm ERR! ENOTSUP: operation not supported on socket, write

npm ERR! A complete log of this run can be found in: /home/vagrant/.npm/_logs/2024-03-03T11_34_39_227Z-debug-0.log


   INFO  Breeze scaffolding installed successfully.  
```

Doing all of this on a non-shared `testdir/` works fine, but I can't move everything in `testdir/` to `code/`, which is annoying. Gonna try setting up a QEMU provider to see if that works better.
