### ISSUE TITLE
stealing code

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#13280]
### Expected behavior

Process completes

### Actual behavior

Generic error message

#### Vagrant version

HEAD

#### Host operating system

macOS

#### Guest operating system

macOS

#### Steps to reproduce

1. Merge features and bugfixes into HashiCorp products.
2. Present at HashiCorp meetups.
3. Apply to HashiCorp for years.
4. Finally connect with a random recruiter.
5. Schedule interviews.
6. HashiCorp cancels the interviews for no reason.

#### Vagrantfile

Moved to ~/.Trash

**Comment by chrisroberts** [comment]
Hi there,

Thanks for your comment. Please respect our [Community Guidelines](https://www.hashicorp.com/community-guidelines) when posting. If you have questions about the interview process, please reach out to your recruiter or email [people@hashicorp.com](mailto:people@hashicorp.com).
