### ISSUE TITLE
vm.synced_folder not working as excpected

### ISSUE THREAD

**Issue by suikast42** [hashicorp/vagrant#13304]
I try to share host folder with the vm over the config 

`mastercfg.vm.synced_folder "#{$volume_host_base}/master-01", "#{$volume_vm}", create: true,  owner: "root", group: "root"`

I have two isues with that. 

1. I can't define the permissions over 
 'mount_options: ["rw", "dmode=777", "fmode=777"]`. This breaks with fuse: unknown option dmode=777'

2. After reboot the synced_folder  dissapers from system

Env:
Vagrant 2.4.0
Vmware Workstation 17
Host Windows 11
Guest Ubuntu 22.04

**Comment by chrisroberts** [comment]
Hi there. The options `dmode` and `fmode` are not supported by `vmhgfs-fuse`. However, it does support the `umask` option which can probably get you the behavior you're after. Cheers!
