### ISSUE TITLE
Vagrant Up Windows box and WinSSH fails calling ip instead of ipconfig, parsing.

### ISSUE THREAD

**Issue by jabreity** [hashicorp/vagrant#13331]
File to reproduce, including box pushed to cloud:
https://jasonbreitwieser.com/vagrantfile-win11

It would appear WinSSH configuration is attempting to call "ip" and search for "inet", both aren't going to happen on a Windows host, even with Cygwin installed, IP is not included, and the output wouldn't be the same. Is there a way to bypass this behavior?
This would be a favorable workaround, as the host has rekeyed successfully and is otherwise maintaining a successful SSH session.

Error with debug output from vagrant up:

![image](https://github.com/hashicorp/vagrant/assets/83088533/07b02288-3520-4446-8138-342c7284c926)

Plaintext of error below:

DEBUG winssh: == Net-SSH connection debug-level log END ==
 INFO winssh: SSH is ready!
DEBUG winssh: Re-using SSH connection.
 INFO winssh: Execute: dir - opts: {:sudo=>false, :shell=>:powershell, :force_raw=>false}
DEBUG winssh: Base SSH exec command: dir
DEBUG winssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh

DEBUG winssh: Exit status: 0
 INFO interface: output: Machine booted and ready!
 INFO interface: output: ==> veilidchat: Machine booted and ready!
==> veilidchat: Machine booted and ready!
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::ForwardPorts:0x00007f4f6e23ef50>
 INFO warden: Calling IN action: #<Proc:0x00007f4f6dff7648 /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/action/warden.rb:116 (lambda)>
 INFO warden: Calling IN action: #<Proc:0x00007f4f6df38d60 /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/action/warden.rb:116 (lambda)>
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::SetHostname:0x00007f4f6b268218>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::SetupComplete:0x00007f4f6b255cd0>
DEBUG setup_complete: Marking provider setup as completed
 INFO warden: Calling IN action: #<Proc:0x00007f4f6b243698 /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/action/warden.rb:116 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f4f6e690770>
DEBUG storeboxmetadata: Writing box metadata file to /home/jason/projects/wintest/.vagrant/machines/veilidchat/libvirt/box_meta
 INFO warden: Calling OUT action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f4f6e690770>
 INFO warden: Calling OUT action: #<Proc:0x00007f4f6b243698 /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/action/warden.rb:116 (lambda)>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::SetupComplete:0x00007f4f6b255cd0>
 INFO set_hostname: `allow_hosts_modification` set to false. Hosts modification has been disabled, skiping changing hostname.
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::SetHostname:0x00007f4f6b268218>
 INFO warden: Calling OUT action: #<Proc:0x00007f4f6df38d60 /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/action/warden.rb:116 (lambda)>
 INFO warden: Calling OUT action: #<Proc:0x00007f4f6dff7648 /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/action/warden.rb:116 (lambda)>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ForwardPorts:0x00007f4f6e23ef50>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::WaitForCommunicator:0x00007f4f6e23f040>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x00007f4f6e272918>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::StartDomain:0x00007f4f6e63ec68>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::SetBootOrder:0x00007f4f6e69fba8>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ShareFolders:0x00007f4f6eb1eff8>
DEBUG host: Searching for cap: smb_installed
DEBUG host: Checking in: redhat
DEBUG host: Checking in: linux
DEBUG host: Searching for cap: nfs_installed
DEBUG host: Checking in: redhat
DEBUG host: Checking in: linux
DEBUG host: Found cap: nfs_installed in linux
DEBUG host: Searching for cap: nfs_installed
DEBUG host: Checking in: redhat
DEBUG host: Checking in: linux
DEBUG host: Found cap: nfs_installed in linux
 INFO host: Execute capability: nfs_installed [#<Vagrant::Environment: /home/jason/projects/wintest>] (redhat)
 INFO subprocess: Starting process: ["/bin/sh", "-c", "systemctl --no-pager --no-legend --plain list-unit-files --all --type=service | grep nfs-server.service"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31998
DEBUG subprocess: Exit status: 0
 INFO nfs: Using NFS, preparing NFS settings by reading host IP and machine IP
DEBUG ssh: Checking key permissions: /home/jason/projects/wintest/.vagrant/machines/veilidchat/libvirt/private_key
DEBUG winssh: Re-using SSH connection.
 INFO winssh: Execute: ip=$(which ip); ${ip:-/sbin/ip} addr show | grep -i 'inet ' | grep -v '127.0.0.1' | tr -s ' ' | cut -d' ' -f3 | cut -d'/' -f 1 - opts: {:sudo=>false, :shell=>:powershell, :force_raw=>false}
DEBUG winssh: Base SSH exec command: ip=$(which ip); ${ip:-/sbin/ip} addr show | grep -i 'inet ' | grep -v '127.0.0.1' | tr -s ' ' | cut -d' ' -f3 | cut -d'/' -f 1
DEBUG winssh: stderr: #< CLIXML

DEBUG winssh: stderr: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><S S="Error">At line:1 char:215_x000D__x000A_</S><S S="Error">+ ... 873d338b86-vagrant-ssh');ip=$(which ip); ${ip:-/sbin/ip} addr show |  ..._x000D__x000A_</S><S S="Error">+   
DEBUG winssh: stderr:                                                            ~~~~_x000D__x000A_</S><S S="Error">Unexpected token 'addr' in expression or statement._x000D__x000A_</S><S S="Error">    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException_x000D__x000A_</S><S S="Error">    + FullyQualifiedErrorId : UnexpectedToken_x000D__x000A_</S><S S="Error"> _x000D__x000A_</S></Objs>
DEBUG winssh: Exit status: 1
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

ip=$(which ip); ${ip:-/sbin/ip} addr show | grep -i 'inet ' | grep -v '127.0.0.1' | tr -s ' ' | cut -d' ' -f3 | cut -d'/' -f 1

Stdout from the command:

Stderr from the command:

 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

**Comment by chrisroberts** [comment]
Hi there. Would you please provide a gist of the entire debug output the failed `vagrant up --debug` command. Thanks!

**Comment by jabreity** [comment]
Hello, thank you for looking at my issue, here is the debug output as requested.

https://gist.github.com/jabreity/8a02f93837aa0012ea876354487c2480

**Comment by chrisroberts** [comment]
The issue here is that by default Vagrant will attempt to determine a supported mechanism for synced folders to provide the `/vagrant` / `C:\vagrant` folder on the guest. In this case it's detecting NFS is available on the host and is attempting to utilize it on the guest. When libvirt [prepares the nfs settings](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/a94ce0d7b6c90129a38435698ca97b364130313d/lib/vagrant-libvirt/action/prepare_nfs_settings.rb#L25C45-L25C45) it attempts to [read the machine's IP](https://github.com/vagrant-libvirt/vagrant-libvirt/blob/a94ce0d7b6c90129a38435698ca97b364130313d/lib/vagrant-libvirt/action/prepare_nfs_settings.rb#L53) which is causing the error you are encountering. You can resolve this in one of two ways:

You can [disable the default synced folder](https://developer.hashicorp.com/vagrant/docs/synced-folders/basic_usage#disabling):

```ruby
Vagrant.configure("2") do |config|
  ...
  config.vm.synced_folder '/vagrant', disabled: true
end
```

Or, you can mark [NFS as non-functional](https://developer.hashicorp.com/vagrant/docs/synced-folders/nfs#functional) for the guest:

```ruby
Vagrant.configure("2") do |config|
  ...
  config.nfs.functional = false
end
```

In this case I would recommend the first just to remove the detection steps for an available synced folder method.

Cheers!

**Comment by jabreity** [comment]
config.vm.synced_folder '.', '/vagrant', disabled: true
  config.nfs.functional = false
 are required to finish this configuration. This issue has been resolved.

**Comment by jabreity** [comment]
Thank you! You got it before me. I am dense, and was focused on moving forward. This is tremendous, I've been on this build since last Monday, livestreamed all of it.

**Comment by jabreity** [comment]
Thank you! You got it before me. Focused on moving forward. This is tremendous, I've been on this build since last Monday, livestreamed all of it.
