### ISSUE TITLE
Debian/Ubuntu apt repository not up to date

### ISSUE THREAD

**Issue by fretb** [hashicorp/vagrant#13344]
Hi, I hope this is the correct please for this unexpected behaviour report.

I noticed that while latest Vagrant version is 2.4.1, the apt repository is still serving 2.4.0 as latest version. Both on Debian Bullseye, and Debian Bookworm.

Can this be brought up to date?

Thanks!

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this issue. I've confirmed the issue in both the apt and yum repositories and the issue has been resolved. The 2.4.1 versions should now be properly available for install via the repositories. If you still run into any issues, please let me know.

Cheers!
