### ISSUE TITLE
Libvirt Plugin Fails to Install

### ISSUE THREAD

**Issue by Jacob-Riddle** [hashicorp/vagrant#13377]
### Debug output

https://gist.github.com/Jacob-Riddle/215e09b2d59b0c670adcaf07ad5f526f

### Expected behavior

The `libvirt` plugin is installed

### Actual behavior

The `libvirt` plugin fails with the error:

```
conflicting dependencies ffi (~> 0.6.3) and ffi (= 1.16.3)
  Activated ffi-1.16.3
  which does not match conflicting dependency (~> 0.6.3)
```

#### Vagrant version

Vagrant 2.4.1

#### Host operating system

openSUSE Tumbleweed

#### Guest operating system

N/A

#### Steps to reproduce

1. Run `vagrant plugin install libvirt`

#### Vagrantfile

N/A

**Comment by nsrderooy** [comment]
Confirmed, this exists on Debian Sid also.
Compared the debug files and they are virtually the same.
