### ISSUE TITLE
Error with provider libvirt

### ISSUE THREAD

**Issue by nttg8100** [hashicorp/vagrant#13370]
### Debug output

```
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

nokogiri requires Ruby version >= 3.0, < 3.4.dev. The current ruby version is 2.6.6.146.

```
### Expected behavior
Should create successfully

### Actual behavior
Failed because the dependency of ruby version of nokogiri

#### Vagrant version
2.12.14
#### Host operating system
ubuntu 20.04

#### Guest operating system
ubuntu 20.04

#### Steps to reproduce

Just vagrant up

#### Vagrantfile
https://github.com/NVIDIA/deepops/blob/master/virtual/Vagrantfile-ubuntu20.04

**Comment by chrisroberts** [comment]
Hi there,

Installing a recent version of Vagrant will resolve this issue. You can download vagrant here: https://developer.hashicorp.com/vagrant/install

Cheers!
