### ISSUE TITLE
`vagrant halt` throws NoMethodError 

### ISSUE THREAD

**Issue by fekoch** [hashicorp/vagrant#13405]
### Debug output

https://gist.github.com/fekoch/bfa850f213827ea1a697a4cf25633a0f

### Expected behavior

`vagrant halt` should halt the machine without errors.

### Actual behavior

`vagrant halt` throws an error:

```
/usr/share/gems/gems/net-ssh-7.1.0/lib/net/ssh/buffered_io.rb:65:in `block in fill': undefined method `length' for nil (NoMethodError)

        debug { "read #{data.length} bytes" }
                            ^^^^^^
```

#### Vagrant version

Vagrant 2.3.4

#### Host operating system

fedora 40 (Kernel 6.8.10-300.fc40x86_64)

#### Guest operating system

Ubuntu 23.10

#### Steps to reproduce

1. `vagrant up --provider libvirt`
2. `vagrant halt`

#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2310"
end
```

**Comment by chrisroberts** [comment]
This was [fixed upstream](https://github.com/net-ssh/net-ssh/commit/efd0ebe882fce04952dcf1dbe2ba5618172f2172) which will be included in the next release.
