### ISSUE TITLE
Enhancement Request: Still no source RPMs and/or spec file is available

### ISSUE THREAD

**Issue by LKHN** [hashicorp/vagrant#13403]
**Is your feature request related to a problem? Please describe.**

Could you provide any reason for not providing source RPMs through the HashiCorp RPM repository or spec file here, GitHub?
I cannot find any sources how the RPMs are built.

**Describe the solution you'd like**

Publish the source RPMs on the HashiCorp RPM repository also spec file or files which is used to build these source RPMs which creates binary RPM available on the repository.

**Comment by chrisroberts** [comment]
Hi there,

There are no SRPMs available. The vagrant packages are built out of the [hashicorp/vagrant-installers](https://github.com/hashicorp/vagrant-installers) repository.

Cheers!
