### ISSUE TITLE
The specified checksum type is not supported by Vagrant: SHA256

### ISSUE THREAD

**Issue by mikolajpiecuch** [hashicorp/vagrant#13466]
### Debug output
https://gist.github.com/mikolajpiecuch/fc370317e482a21014088ef7ab31c816

### Expected behavior
Box "gusztavvargadr/windows-11" should be normally downloaded and checksum validation pass

### Actual behavior
Checksum validation fails

#### Vagrant version
2.4.1

#### Host operating system
Windows Server

#### Guest operating system
Windows 11

#### Steps to reproduce

1. Download "gusztavvargadr/windows-11"

**Comment by mikolajpiecuch** [comment]
problem related to the box -> https://github.com/gusztavvargadr/packer/issues/444

**Comment by maxkratz** [comment]
@mikolajpiecuch I opened the issue https://github.com/gusztavvargadr/packer/issues/444. Is the error with "SHA256" about a bug in Vagrant or has it something to do with the specific box/template by @gusztavvargadr?

**Comment by mikolajpiecuch** [comment]
@maxkratz firstly I opened an issue to vagrant because I encountered the same problem like you. Then I saw your issue and decided to close this issue

**Comment by maxkratz** [comment]
> @maxkratz firstly I opened an issue to vagrant because I encountered the same problem like you. Then I saw your issue and decided to close this issue

Alright, thank you for the clarification.
