### ISSUE TITLE
typo in install instructions for debian/ubuntu

### ISSUE THREAD

**Issue by parrotrueper** [hashicorp/vagrant#13498]
page: https://developer.hashicorp.com/vagrant/install

Current install instructions for Ubuntu/Debian

`wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
`

Should be

`wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
`

needs a space after the `-O`

**Comment by AmineAouragh** [comment]
i can't find anything in the docs source code related to that issue so i can fix it, it's like the content of that link you shared isn't in the github repository

**Comment by parrotrueper** [comment]
![Screenshot from 2024-11-13 12-18-15](https://github.com/user-attachments/assets/855b6341-ff45-4bdd-bf46-6cf2443bd5b1)
https://developer.hashicorp.com/vagrant/install#linux

**Comment by AmineAouragh** [comment]
oh no no i got you, i meant there is nowhere in here in the repository where i could find the source code of that specific webpage to fix it

**Comment by chrisroberts** [comment]
This has been updated. Cheers!
