### ISSUE TITLE
Wrong download link is presented for the 2.4.2 AMD64 Ubuntu/Debian package in the download page

### ISSUE THREAD

**Issue by brlin-tw** [hashicorp/vagrant#13528]
I was unable to upgrade the installed vagrant package to 2.4.2 in my system using `apt upgrade` so I tried to manually download the package, then I encountered this problem:

### Debug output

N/A

### Expected behavior

A Debian package URL is presented.

### Actual behavior

A RPM package URL is presented:

![Screenshot](https://github.com/user-attachments/assets/53481b20-9815-405d-80e8-56d40e8a6a9a)

### Reproduction information 

Refer to the description in the [the Steps to reproduce section](#steps-to-reproduce).

#### Vagrant version

N/A

#### Host operating system

Ubuntu 24.04 LTS AMD64

#### Guest operating system

N/A

#### Steps to reproduce

1. Launch a web browser.
2. Browse <https://developer.hashicorp.com/vagrant/install#linux>.
3. Hover the mouse pointer on the "Download" link of the 2.4.2 AMD64 version binary download option of the Ubuntu/Debian tab.
4. Examine the link target presented by the web browser.

#### Vagrantfile

N/A

**Comment by rgl** [comment]
To emphasize, 2.4.2 is not available in the apt.releases.hashicorp.com repository.

This seems to infer there's a loophole somewhere in the vagrant release process.

**Comment by chrisroberts** [comment]
Repository update was sorted out and packages are available there now (just FYI). I'm working again to get the downloads page properly fixed. The "Binary download" is supposed to refer to the standalone binary (which the `AMD64` entry properly links to), which Vagrant only has a single version. If you are looking for the package files, you can get them directly from the releases site: https://releases.hashicorp.com/vagrant/2.4.2/

**Comment by AmineAouragh** [comment]
i think this issue is fixed so it should be closed

**Comment by chrisroberts** [comment]
The binary download has been fixed up to only show the single "binary" download available (the AppImage). 

![Screenshot_20241113_173250](https://github.com/user-attachments/assets/264c0bba-f2ae-44fe-9630-65c17ad8f40c)

Cheers!
