### ISSUE TITLE
Vagrant plugins cannot be installed anymore for vagrant 2.4.2 under Windows

### ISSUE THREAD

**Issue by dib42** [hashicorp/vagrant#13527]
In the **Debug output** and **Steps to reproduce** `vagrant-env` plugin is used, but that happened to other plugins I am using (`vagrant-disksize` and `vagrant-vbguest`) as well as picking some random plugins from [here](https://github.com/hashicorp/vagrant/wiki/Available-Vagrant-Plugins).

It seems that adding the dependency of logger ([this PR](https://github.com/hashicorp/vagrant/pull/13499)) breaks the installation of (probably) all plugins under Windows.

When opening a `cmd` in `C:\Program Files\Vagrant\embedded\mingw64\bin` and run `gem search -be logger`

```
C:\Program Files\Vagrant\embedded\mingw64\bin>gem search -be logger

*** LOCAL GEMS ***

logger (1.6.0)

*** REMOTE GEMS ***

logger (1.6.1)

```

### Debug output

https://gist.github.com/dib42/7113c057c40dac93760afe4b813cb763

### Expected behavior

Vagrant should install the plugin

### Actual behavior

Vagrant does not install the plugin because of a ruby dependency problem

#### Vagrant version

Vagrant 2.4.2

#### Host operating system

Windows 10 22H2

#### Guest operating system

Ubuntu 22.04

#### Steps to reproduce

1. Open powershell
2. Run `vagrant plugin install vagrant-env --verbose --debug-timestamp`

#### Vagrantfile
Just for the bug report requirements, as this is not relevant for the bug

```ruby
# Copy-paste your Vagrantfile here. Remove any sensitive information such as passwords, authentication tokens, or email addresses.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
end
```

**Comment by PaulNeumann** [comment]
Same issue on Windows 11 23H2.

**Comment by brlin-tw** [comment]
@hswong3i Would you mind having a look into this one?

**Comment by brlin-tw** [comment]
This problem also affects Linux hosts(and probably all supported platforms of Vagrant as it's a gem dependency issue).

**Comment by djzara** [comment]
Just Same issue on macOS 15.1 as of this morning, so that's to your suggestion @brlin-tw

**Comment by Sn0wCrack** [comment]
The `VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1` environment variable seems to work around this in the meantime if people are having this issue.

**Comment by jeremyanugrah** [comment]
Same Issue on Windows 11 Version 10.0.22631 Build 22631

**Comment by hswong3i** [comment]
> @hswong3i Would you mind having a look into this one?

My manual vagrant RPM/DEB packaging with OBS working correctly: https://build.opensuse.org/package/show/home:alvistack/hashicorp-vagrant-2.4.2

I guess one of the different is: I had vendor all dependency locally before packaging, see https://github.com/alvistack/hashicorp-vagrant/commit/1cec4846cbe54f6d418a478f4caf656e90096b0f:
```
    git clean -xdf
    git submodule sync --recursive
    git submodule update --recursive --init
    git submodule foreach --recursive git clean -xdf
    gem build vagrant.gemspec -o ../vagrant-2.4.2.gem
    bundle config set --local path ./bundle
    bundle install --verbose --standalone
    bundle config set --local cache_all true
    bundle config set --local cache_all_platforms true
    bundle cache
    mv ../vagrant-2.4.2.gem ./vendor/cache/
    rm -rf .bundle bundle vendor/bundle Gemfile.lock
    tar zcvf ../vagrant_2.4.2.orig.tar.gz --exclude=.git .
    debuild -uc -us
    cp vagrant.spec ../vagrant_2.4.2-1.spec
    cp vagrant.rpmlintrc /osc/home\:alvistack/hashicorp-vagrant-2.4.2/
    cp ../vagrant*2.4.2*.{gz,xz,spec,dsc} /osc/home\:alvistack/hashicorp-vagrant-2.4.2/
    rm -rf ../vagrant*2.4.2*.*
```

BTW, refer to your report, I guess setting it as `~> 1.6.0` should be suitable:
```
C:\Program Files\Vagrant\embedded\mingw64\bin>gem search -be logger

*** LOCAL GEMS ***

logger (1.6.0)

*** REMOTE GEMS ***

logger (1.6.1)
```

**Comment by nekotov** [comment]
Same issue on macOS 15.0

**Comment by cjlapao** [comment]
We at Parallels are also having a lot of people reporting the same using our plugin

**Comment by rvalue** [comment]
Same issue with macOS Sequoia 15.1

**Comment by brlin-tw** [comment]
Hello all, I have submitted a merge request(#13532) that should fix this issue, if you are capable of doing a [source installation](https://developer.hashicorp.com/vagrant/docs/installation/source) please help verify the patch(or directly review the code change), thank you!

**Comment by lprimak** [comment]
How would I know if the fix has been released? 2.4.3? Something else?
Thanks!

**Comment by iqbalabd** [comment]
I'm seeing the same issue on Ubuntu 22.04. As vagrant was working well in the previous version, I decided to downgrade and keep it at that version for now:

```
$ apt list -a vagrant (check versions)
$ sudo apt install vagrant=2.4.1-1
$ vagrant plugin install vagrant-libvirt (re-install my plugin)
$ sudo apt-mark hold vagrant (hold the working vagrant version for now so it doesn't automatically gets upgraded)
```

**Comment by lprimak** [comment]
Do we have an ETA for 2.4.3 release? Please release ASAP.
Thank you!

**Comment by marcosvile** [comment]
Solved it for me:

$ VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant plugin install vagrant-vbguest

**Comment by AlekseyKorzun** [comment]
Here is an example of automatic provisioning that leverages @marcosvile solution:

`
required_plugins = %w(vagrant-berkshelf vagrant-vbguest)
required_plugins.each do |plugin|
  if plugin == "vagrant-berkshelf"
    ENV["VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT"] = "1"
  end

  exec "vagrant plugin install #{plugin}; vagrant #{ARGV.join(' ')}" unless Vagrant.has_plugin?(plugin) || ARGV[0] == 'plugin'
  if plugin == "vagrant-berkshelf"
    ENV["VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT"] = "0"
  end
end
`

👍

**Comment by sonnxx** [comment]
Same issue on macOS Sequoia 15.0.1

```
Vagrant failed to properly resolve required dependencies. These errors can commonly be caused by misconfigured plugin installations or transient network issues. The reported error is:

conflicting dependencies logger (= 1.6.0) and logger (= 1.6.1)
  Activated logger-1.6.1
  which does not match conflicting dependency (= 1.6.0)

  Conflicting dependency chains:
    logger (= 1.6.1), 1.6.1 activated

  versus:
    logger (= 1.6.0)

  Gems matching logger (= 1.6.0):
    logger-1.6.0
```

**Comment by Hulidex** [comment]
Same issue ubuntu 24.04:

```
Installing the 'vagrant-disksize' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies logger (= 1.6.0) and logger (= 1.6.1)
  Activated logger-1.6.1
  which does not match conflicting dependency (= 1.6.0)

  Conflicting dependency chains:
    logger (= 1.6.1), 1.6.1 activated

  versus:
    logger (= 1.6.0)

  Gems matching logger (= 1.6.0):
    logger-1.6.0

```

**Comment by chrisroberts** [comment]
Vagrant v2.4.3 has been published which includes the fix for this issue.

**Comment by robkorv** [comment]
If you hold the package with apt-mark you can mark it as manual again with: `sudo apt-mark manual vagrant`
It was still held back on my system though.

```
The following packages have been kept back:                                                                                                                                             
  vagrant
N: Some packages may have been kept back due to phasing.
```

This is because of https://wiki.ubuntu.com/PhasedUpdates.
