### ISSUE TITLE
Publishing box after migrating to HCP Vagrant Registry fails

### ISSUE THREAD

**Issue by klausenbusk** [hashicorp/vagrant#13529]
### Debug output

https://gist.github.com/klausenbusk/4c5a79b1fc84410e51bae21e72f34a84

### Expected behavior

The box should have been uploaded.

### Actual behavior

The box was not uploaded due to an authentication issue.

#### Vagrant version

```sh
$ vagrant -v
Vagrant 2.4.1
```

#### Host operating system

Arch Linux

#### Guest operating system

N/A

#### Steps to reproduce

1. Migrate Vagrant Cloud Organization to HCP Vagrant Registry
2. Follow the [Post Migration](https://developer.hashicorp.com/vagrant/vagrant-cloud/hcp-vagrant/post-migration-guide) documentation for authenticating against HCP Vagrant Registry. I.e. create a Service Principal with the Contributor role and set the `VAGRANT_CLOUD_TOKEN` like this:
    ```sh
    $ hcp auth login --client-id=CLIENT_ID --client-secret=CLIENT_SECRET
    $ export VAGRANT_CLOUD_TOKEN=";$(hcp auth print-access-token)"
    ```
4. Try to use the `vagrant` cli for publishing a box

This has also been reported by a different user on [the HashiCorp forum](https://discuss.hashicorp.com/t/vagrant-cloud-is-moving-to-hcp/66263/8).

#### Vagrantfile

N/A

**Comment by hswong3i** [comment]
I am facing the similar issue but get some new idea: the `hcp auth login` looks like an OAuth2.0 login, so the `hcp auth print-access-token` should be a short-terms non-persistence OAuth2.0 access token.

The reason for this guess is: I had tried the `hcp auth print-access-token` across different days, they are coming with different dynamic values.

From this point of view, we may NOT hard-code the `VAGRANT_CLOUD_TOKEN` with a pre-fetched access token, but ALWAYS combine `hcp auth login` + `hcp auth print-access-token` together for a dynamic value.

E.g. When combine with my GitLab CI pipeline (see https://gitlab.com/alvistack/vagrant-devel/-/blob/master/.gitlab-ci.yml), I could only pre-define my `HCP_CLIENT_ID` and `HCP_CLIENT_SECRET` for dynamic fetching, but not hard coded `VAGRANT_CLOUD_TOKEN` as v1 API.

**Comment by hswong3i** [comment]
Let's see if this works (see https://gitlab.com/alvistack/vagrant-devel/-/blob/b185f3922e5d01ac18d48c14c764e2e1edc0f828/.gitlab-ci.yml#L137-146):
```
    sudo -E hcp auth login --client-id=$HCP_CLIENT_ID --client-secret=$HCP_CLIENT_SECRET
    export _VAGRANT_CLOUD_TOKEN=";$(sudo -E hcp auth print-access-token)"
    cd $CI_PROJECT_DIR/packer/$_BOX-$_PROVIDER
    export _ORG="$CI_PROJECT_NAMESPACE"
    export _CHECKSUM="$(sha256sum output-vagrant/package.box | awk '{ print $1 }')"
    curl -skL \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
      --data "{ \"box\": { \"username\": \"$_ORG\", \"name\": \"$_BOX\", \"is_private\": false } }" \
      https://app.vagrantup.com/api/v2/boxes | jq .
```

**Comment by hswong3i** [comment]
@klausenbusk I could most likely confirm with https://developer.hashicorp.com/vagrant/vagrant-cloud/hcp-vagrant/post-migration-guide#authenticated-requests, now the `$VAGRANT_CLOUD_TOKEN` **MUST BE** a dynamic fetched OAuth2.0 style access token, **JUST BEFORE** calling those API with curl.

My example (see https://gitlab.com/alvistack/vagrant-ubuntu/-/blob/34b35e6e911bdd2a397880d73cda20e6104696e5/.gitlab-ci.yml#L137-177):
```
    sudo -E hcp auth login --client-id=$HCP_CLIENT_ID --client-secret=$HCP_CLIENT_SECRET
    export _VAGRANT_CLOUD_TOKEN=";$(sudo -E hcp auth print-access-token)"
    cd $CI_PROJECT_DIR/packer/$_BOX-$_PROVIDER
    export _ORG="$CI_PROJECT_NAMESPACE"
    export _CHECKSUM="$(sha256sum output-vagrant/package.box | awk '{ print $1 }')"
    curl -skL \
      --request POST \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
      --data "{ \"box\": { \"username\": \"$_ORG\", \"name\": \"$_BOX\", \"is_private\": false } }" \
      https://app.vagrantup.com/api/v2/boxes | jq .
    curl -skL \
      --request POST \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
      --data "{ \"version\": { \"version\": \"$_VERSION\" } }" \
      https://app.vagrantup.com/api/v2/box/$_ORG/$_BOX/versions | jq .
    curl -skL \
      --request DELETE \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
      https://app.vagrantup.com/api/v2/box/$_ORG/$_BOX/version/$_VERSION/provider/$_PROVIDER/$_ARCHITECTURE | jq .
    curl -skL \
      --request POST \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
      --data "{ \"provider\": { \"name\": \"$_PROVIDER\", \"checksum_type\": \"sha256\", \"checksum\": \"$_CHECKSUM\", \"architecture\": \"$_ARCHITECTURE\", \"default_architecture\": true } }" \
      https://app.vagrantup.com/api/v2/box/$_ORG/$_BOX/version/$_VERSION/providers | jq .
    _UPLOAD_PATH=$(curl -skL \
      --request GET \
      --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
      https://app.vagrantup.com/api/v2/box/$_ORG/$_BOX/version/$_VERSION/provider/$_PROVIDER/$_ARCHITECTURE/upload | jq -r .upload_path)
    curl -skL \
      --request PUT \
      --header "Connection: keep-alive" \
      --upload-file output-vagrant/package.box \
      $_UPLOAD_PATH | jq .
    curl -skL \
      --request PUT \
      --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
      https://app.vagrantup.com/api/v2/box/$_ORG/$_BOX/version/$_VERSION/release | jq .
```

And the sample outout (see https://gitlab.com/alvistack/vagrant-ubuntu/-/jobs/8319918807#L148):
```
Successfully logged in!
{
  "code": 3,
  "message": "public_id: cannot be blank.; registry: cannot be blank",
  "details": [
    {
      "@type": "type.googleapis.com/google.rpc.BadRequest"
    }
  ],
  "errors": [
    "public_id: cannot be blank.; registry: cannot be blank"
  ]
}
{
  "version": "20241111.1.2",
  "status": "unreleased",
  "description_html": "",
  "description_markdown": "",
  "created_at": "2024-11-11T07:56:35.143731307Z",
  "updated_at": "2024-11-11T07:56:35.143731307Z",
  "number": "20241111.1.2",
  "release_url": "https://vagrantcloud.com/api/v1/box/alvistack/ubuntu-24.04/version/20241111.1.2/release",
  "revoke_url": "https://vagrantcloud.com/api/v1/box/alvistack/ubuntu-24.04/version/20241111.1.2/revoke",
  "providers": []
}
{
  "code": 5,
  "message": "provider not found",
  "errors": [
    "provider not found"
  ]
}
{
  "name": "libvirt",
  "hosted": true,
  "hosted_token": "",
  "original_url": "",
  "created_at": "2024-11-11T07:56:36.658660818Z",
  "updated_at": "2024-11-11T07:56:36.658660818Z",
  "download_url": "https://vagrantcloud.com/alvistack/boxes/ubuntu-24.04/versions/20241111.1.2/providers/libvirt/amd64/vagrant.box",
  "checksum": "3ba15f3c1e8bf1d762092a9e343fd27e3c5b106dbc6fefddd998361cccca06cc",
  "checksum_type": "sha256",
  "architecture": "amd64",
  "default_architecture": true
}
{
  "version": "20241111.1.2",
  "status": "active",
  "description_html": "",
  "description_markdown": "",
  "created_at": "2024-11-11T07:56:35.143731Z",
  "updated_at": "2024-11-11T08:01:17.189927Z",
  "number": "20241111.1.2",
  "release_url": "https://vagrantcloud.com/api/v1/box/alvistack/ubuntu-24.04/version/20241111.1.2/release",
  "revoke_url": "https://vagrantcloud.com/api/v1/box/alvistack/ubuntu-24.04/version/20241111.1.2/revoke",
  "providers": [
    {
      "name": "libvirt",
      "hosted": true,
      "hosted_token": "",
      "original_url": "",
      "created_at": "2024-11-11T07:56:36.658661Z",
      "updated_at": "2024-11-11T07:56:36.658661Z",
      "download_url": "https://vagrantcloud.com/alvistack/boxes/ubuntu-24.04/versions/20241111.1.2/providers/libvirt/amd64/vagrant.box",
      "checksum": "3ba15f3c1e8bf1d762092a9e343fd27e3c5b106dbc6fefddd998361cccca06cc",
      "checksum_type": "sha256",
      "architecture": "amd64",
      "default_architecture": true
    }
  ]
}
```

**Comment by chrisroberts** [comment]
@klausenbusk Hi there. The authentication error is likely due to the token that was vended from the `hcp auth print-access-token` expiring. Resetting the environment variable with a new token should resolve the issue.

An alternative: if you update to the latest Vagrant release (v2.4.3) it includes support for generating access tokens. You'll just need to unset the `VAGRANT_CLOUD_TOKEN` environment variable and set the `HCP_CLIENT_ID` and `HCP_CLIENT_SECRET` environment variables.

```
unset VAGRANT_CLOUD_TOKEN
export HCP_CLIENT_ID="<CLIENT_ID>"
export HCP_CLIENT_SECRET="<CLIENT_SECRET>"
```

Cheers!

**Comment by klausenbusk** [comment]
Hi @hswong3i and @chrisroberts

The token is generated just before it is used, so it is not expired. I also just tried with Vagrant v2.4.3 but that just hangs, similar to issue https://github.com/hashicorp/vagrant/issues/13392.

Is there anything else worth trying?

**Comment by hswong3i** [comment]
I just get successfully deployed with my new box, after they had debug the v2 api: https://gitlab.com/alvistack/vagrant-ceph/-/jobs/8378740129#L179

**Comment by klausenbusk** [comment]
> I also just tried with Vagrant v2.4.3 but that just hangs, similar to issue #13392.

That was a installation error on my side. The issue is the same with Vagrant v2.4.3 (running on Ubuntu 24.10). Debug log can be found here: https://gist.github.com/klausenbusk/10f73e3cb34af238e22731dbacf73692.

As started in the issue description I have created a service principal with the contributor role, more specifically it is created under the project with the migrated "Vagrant registry" resource and "Vagrant Box (archlinux/archlinux)" resource.  
The vagrant command we are using is `vagrant cloud publish archlinux/archlinux 20241101.275802 virtualbox Arch-Linux-x86_64-virtualbox-20241101.275802.box --release --no-direct-upload -f --debug`, which has been working for over 4 years without issues (\* `--no-direct-upload` was [added 10 months ago tho due to a bug in vagrant](https://gitlab.archlinux.org/archlinux/arch-boxes/-/commit/9c176e628480dd44b13742fc1f9bacb1b8c1bf25)).

Do you see anything we are doing wrong?

> I just get successfully deployed with my new box, after they had debug the v2 api: https://gitlab.com/alvistack/vagrant-ceph/-/jobs/8378740129#L179

I may give it a try calling the API directly instead of using the vagrant CLI, but resorting to calling the API directly is not a viable solution. May I ask if the box you just uploaded, is a migrated registry/box or if it was created from HCP?

**Comment by klausenbusk** [comment]
> I may give it a try calling the API directly instead of using the vagrant CLI, but resorting to calling the API directly is not a viable solution. May I ask if the box you just uploaded, is a migrated registry/box or if it was created from HCP?

Uploading calling the API directly works with the script provided in https://github.com/hashicorp/vagrant/issues/13529#issuecomment-2467688666, like so:
```sh
export HCP_CLIENT_ID=<redacted>
export HCP_CLIENT_SECRET=<redacted>

./hcp auth login --client-id=$HCP_CLIENT_ID --client-secret=$HCP_CLIENT_SECRET
_VAGRANT_CLOUD_TOKEN=";$(./hcp auth print-access-token)"
_ORG=test-13529
_BOX=archlinux
_VERSION=20241101.275802
_PROVIDER=virtualbox
_ARCHITECTURE=amd64
_CHECKSUM="$(sha256sum Arch-Linux-x86_64-virtualbox-20241101.275802.box | awk '{ print $1 }')"
curl -skL \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
  --data "{ \"box\": { \"username\": \"$_ORG\", \"name\": \"$_BOX\", \"is_private\": false } }" \
  https://app.vagrantup.com/api/v2/boxes | jq .

curl -skL \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
  --data "{ \"version\": { \"version\": \"$_VERSION\" } }" \
  https://app.vagrantup.com/api/v2/box/$_ORG/$_BOX/versions | jq .


curl -skL \
  --request DELETE \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
  https://app.vagrantup.com/api/v2/box/$_ORG/$_BOX/version/$_VERSION/provider/$_PROVIDER/$_ARCHITECTURE | jq .

curl -skL \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
  --data "{ \"provider\": { \"name\": \"$_PROVIDER\", \"checksum_type\": \"sha256\", \"checksum\": \"$_CHECKSUM\", \"architecture\": \"$_ARCHITECTURE\", \"default_architecture\": true } }" \
  https://app.vagrantup.com/api/v2/box/$_ORG/$_BOX/version/$_VERSION/providers | jq .

_UPLOAD_PATH=$(curl -skL \
  --request GET \
  --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
  https://app.vagrantup.com/api/v2/box/$_ORG/$_BOX/version/$_VERSION/provider/$_PROVIDER/$_ARCHITECTURE/upload | jq -r .upload_path)

curl -skL \
  --request PUT \
  --header "Connection: keep-alive" \
  --upload-file Arch-Linux-x86_64-virtualbox-20241101.275802.box \
  $_UPLOAD_PATH | jq .

curl -skL \
  --request PUT \
  --header "Authorization: Bearer $_VAGRANT_CLOUD_TOKEN" \
  https://app.vagrantup.com/api/v2/box/$_ORG/$_BOX/version/$_VERSION/release | jq .
```

So I assume there is a bug in the vagrant tool, since the `vagrant cloud publish` command fails?

**Comment by klausenbusk** [comment]
@chrisroberts any chance this issue could be reopened? From my point of view it looks like the Vagrant CLI tool is doing something wrong, as it works correctly if I call the API myself with `curl`.
