### ISSUE TITLE
Vagrant uses wrong provider after migrating box registry to hashicorp cloud

### ISSUE THREAD

**Issue by enthusedcoder** [hashicorp/vagrant#13521]
Let me start by explaining that the specific box displaying the problematic behavior is (as you can see in the vagrantfile) is "fuvagrant/server2019".  Prior to migrating my box registry to the hashicorp cloud, the latest released version of the box only had a virtualbox provider associated with it.  Then, after the migration to hashicorp cloud, I noticed that the migration had done something odd to my boxes, every version of every box had the architecture for the box configured as "unknown":

![image](https://github.com/user-attachments/assets/9007ff72-7ba0-4f58-8381-ef4366de9787)

So, the latest version (1.2.1) of the "fuvagrant/server2019" box 's virtualbox provider (which is the only provider associated with the box at this point) has an unknown architecture.  After the migration, I then decide to add a vmware-desktop provider artifact to the latest version of the "fuvagrant/server2019", and the provider entry in hashicorp cloud displays the correct architecture when I have do so:

![image](https://github.com/user-attachments/assets/fe8b539c-a0e9-4d38-bce8-1fdc20189ade)

This is the environment in which this issue occurs.  No matter what, even if the box that I specify when running ```vagrant up``` explicitly configured to use the virtualbox provider (so, in reference to the vagrantfile linked in the URL below, if I ran the command ```vagrant up windows-vbox```), vagrant ignores what is in the config and uses the vmware provider instead.  This is just an educated guess on my part, I think it is probably because vagrant believes that the fuvagrant/server2019 box's vmware provider is the only valid provider configured for the latest version of the box (since the virtualbox provider's architecture is unknown), which makes sense, but, if that is indeed the case, then I would expect vagrant to either 1) error out because it is smart enough to realize that the latest version of the box does not have a valid virtualbox artifact associated with it, or 2) if the box version is not specified in the config, find the latest version of the box that DOES have a valid virtualbox artifact and use that version's virtualbox artifact.  Instead, vagrant will just deploy the vmware provider, even if the config that the user specified in the ```vagrant up``` command explicitly uses the virtualbox provider:

 
![image](https://github.com/user-attachments/assets/8b0fdbbe-9b93-4596-909a-286ae4f3a76f)

### Debug output

https://gist.github.com/enthusedcoder/46308671235e87e589c6ff9faafbe383

### Expected behavior

If the config that the user specifies in the vagrant up command uses a provider that is unavailable in the latest version/config-defined version of the box also defined in the config, then I would expect vagrant to either 1) error out because it is smart enough to realize that the version of the box does not have the the defined provider's artifact associated with the version of the box, or 2) if the box version is not specified in the config, find the latest version of the box that DOES does have the required provider's artifact and use that version's provider artifact. 

### Actual behavior

Vagrant just uses whatever provider is available in the latest version of the box.

#### Vagrant version

 vagrant -v
Vagrant 2.4.1

#### Host operating system

LAtest version of windows 11: Windows 11 24h2

#### Guest operating system

Windows server 2019

#### Steps to reproduce

1. using the vagrantfile provided below, simply run ```vagrant up windows-vbox```

#### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
config.vm.define "windows" do |cub|
  	cub.vm.box = "fuvagrant/server2019"
	cub.vm.box_check_update = true
	cub.vm.provider :vmware_desktop do |v|
	  v.gui = true
	  v.vmx["ethernet0.pcislotnumber"] = "160"
	end
	cub.vm.guest = :windows
	cub.vm.communicator = "winrm"
	cub.vm.boot_timeout = 500
	cub.winrm.transport = :plaintext
	cub.winrm.basic_auth_only = true
	cub.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "Realtek PCIe GbE Family Controller"
	#sub.vm.network "private_network", type: "dhcp"
	cub.vm.network "forwarded_port", guest: 5985, host: 55985
	cub.vm.synced_folder "packages", "/packages"
	cub.vm.provision "shell", privileged: true, powershell_elevated_interactive: true, inline: <<-EOH
$ErrorActionPreference = "SilentlyContinue"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
$env:PATH +=";$($env:SystemDrive)\\ProgramData\\chocolatey\\bin"
Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory private
Write-Output ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator") | Out-File "C:\\users\\vagrant\\Documents\\file.txt"
choco install nuget.commandline -y
Invoke-webrequest "https://github.com/abbodi1406/vcredist/releases/download/v0.65.0/VisualCppRedist_AIO_x86_x64_65.zip" -outfile "$env:USERPROFILE\Desktop\cpp.zip"
Expand-Archive -Path "$env:USERPROFILE\Desktop\cpp.zip" -DestinationPath "$env:USERPROFILE\Desktop"
Start-Process "$env:USERPROFILE\Desktop\VisualCppRedist_AIO_x86_x64.exe" -ArgumentList "/y" -Wait

EOH
end
  config.vm.define "windows-vbox" do |vb|
    vb.vm.box = "fuvagrant/server2019"
	vb.vm.box_check_update = true
	vb.vm.provider :virtualbox do |v|
	  process = `"#{ENV["VBOX_MSI_INSTALL_PATH"]}vboxmanage.exe" -v`
	  v.gui = true
	  v.customize ["modifyvm", :id, "--memory", "4096"]
	  v.customize ["modifyvm", :id, "--cpus", "2"]
	  v.customize ["modifyvm", :id, "--vram", 32]
	  v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	  v.customize ["modifyvm", :id, "--audio", "none"]
	  if process[0,5] >= '6.1.0' then
	  	v.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
	  else
		v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
	  end
	  v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
	  v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
	end
	vb.vm.guest = :windows
	vb.vm.communicator = "winrm"
	vb.vm.boot_timeout = 500
	vb.winrm.transport = :plaintext
	vb.winrm.basic_auth_only = true
	vb.vm.network "public_network", use_dhcp_assigned_default_route: true, bridge: "Realtek PCIe GbE Family Controller"
	#vb.vm.network "private_network", type: "dhcp"
	vb.vm.network "forwarded_port", guest: 5985, host: 55985
	vb.vm.synced_folder "packages", "/packages"
	vb.vm.provision "shell", privileged: true, powershell_elevated_interactive: true, inline: <<-EOH
	  $ErrorActionPreference = "SilentlyContinue"
	  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
	  iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
	  $env:PATH +=";$($env:SystemDrive)\\ProgramData\\chocolatey\\bin"
	  Get-NetConnectionProfile | Set-NetConnectionProfile -NetworkCategory private
	  Write-Output ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator") | Out-File "C:\\users\\vagrant\\Documents\\file.txt"
	  choco install nuget.commandline -y
	  Invoke-webrequest "https://github.com/abbodi1406/vcredist/releases/download/v0.65.0/VisualCppRedist_AIO_x86_x64_65.zip" -outfile "$env:USERPROFILE\Desktop\cpp.zip"
	  Expand-Archive -Path "$env:USERPROFILE\Desktop\cpp.zip" -DestinationPath "$env:USERPROFILE\Desktop"
	  Start-Process "$env:USERPROFILE\Desktop\VisualCppRedist_AIO_x86_x64.exe" -ArgumentList "/y" -Wait
EOH
end
end
```

**Comment by chrisroberts** [comment]
Hi there,

The architecture attribute is not a new feature, and existed existed prior to the box registry. It was added in 2.4.0 Vagrant release (and introduced in Vagrant Cloud at the same time). The provider configuration within the `Vagrantfile` does not instruct Vagrant what provider should be used for a specific guest. Instead, it supplies provider specific configuration for that guest. Multiple provider blocks for different provider plugins can be provided for individual guests, and those blocks are used when the associated provider is used for the guest.

Vagrant can be told to use a specific provider using the `--provider` flag. If you have multiple providers installed, and want to use something different than the default that Vagrant chooses, you can provide it:

```
vagrant up --provider virtualbox
```

You can see in the [debug output](https://gist.github.com/enthusedcoder/46308671235e87e589c6ff9faafbe383#file-vagrant-log-L439) the list of usable providers which is then [sorted by weight](https://gist.github.com/enthusedcoder/46308671235e87e589c6ff9faafbe383#file-vagrant-log-L440). One important thing to note when looking at the list of providers:

```
[:vmware_desktop, :vmware_workstation, :hyperv]
