### ISSUE TITLE
Enhancement Request: Run vagrant with `libvirt` **only** (and don't depend on VirtualBox)

### ISSUE THREAD

**Issue by fde6-a09a-b373** [hashicorp/vagrant#13536]
**Issue**
By now, `vagrant` checks and depends on *VirtualBox*, even if a `Vagrantfile` configures only the `libvirt` provider.

**Describe the solution you'd like**
I would like to run `vagrant` without the *VirtualBox* provider installed at all.

I would like to have either an "auto detect feature" / a configuration flag / environment variable, so that the *VirtualBox* provider is no longer a requirement during runtime. I would like to be enabled to run `vagrant` with the `libvirt` provider only.

**Comment by chrisroberts** [comment]
Hi there,

Vagrant does not have a dependency on VirtualBox. Can you please provide details on why you believe there is currently a dependency? Examples and/or log output would be helpful.

Thanks!

**Comment by fde6-a09a-b373** [comment]
Hey @chrisroberts 
You are right... I've checked again with a `libvirt` VM running debian/testing64 and installed `vagrant` and `vagrant-libvirt` only, and indeed `vagrant` did not complained about a "missing" virtualbox.

I encountered the initial issue on a machine running Arch Linux, which has newer packages for VirtualBox, then Vagrant supports at the moment. I have VirtualBox installed because from time to time I need it, even I mostly use libvirt. 

I'm not quiet sure (and don't want to break my installation again...) but I think that if VirtualBox is installed, then Vagrant checks the version of `VBoxManage`, even if the `Vagrantfile` uses the `libvirt` provider.

**Comment by chrisroberts** [comment]
Yes, Vagrant will run a `VBoxManage --version` command to determine if VirtualBox is available on the local system, and supported by the installed version of Vagrant. Tests will be run for all providers to determine the valid list of providers Vagrant can support, and then will chose the provider to use based on:

* explicit provider name provided via command flag (`--provider libvirt`)
* provider name set in the [VAGRANT_DEFAULT_PROVIDER](https://developer.hashicorp.com/vagrant/docs/other/environmental-variables#vagrant_default_provider) environment variable
* custom provider configuration detected within Vagrantfile
* selected for weighted sort of available providers

How the provider is selected is [implemented here](https://github.com/hashicorp/vagrant/blob/280b5d8cf310c43264b7b7ef82bc9dbc7c9ac4a6/lib/vagrant/environment.rb#L322) and includes detailed explanations. To ensure that the provider is always defaulting to libvirt, using the DEFAULT_VAGRANT_PROVIDER environment variable will provide that behavior.

Cheers!
*

**Comment by fde6-a09a-b373** [comment]
Yes I know how to use the libvirt provider. My issue is that even if I state libvirt is to be used, that the version of VBoxManage is checked nevertheless.
So in my previous situation, where I'm aware of and can life with the fact that the current local installation of VirtualBox is broken, I can not use libvirt because of that fact.
I don't think that provider need to be checked which are not used by the current environment.

**Comment by chrisroberts** [comment]
I don't understand how Vagrant checking if VirtualBox is available is preventing you from being able to use the libvirt plugin. Are you encountering an error that prevents Vagrant from functioning? Vagrant will check the VirtualBox version to determine if it is an available provider, but it does not halt if it encounters a version of VirtualBox it cannot support. It simply removes it from the list of available providers when determining what provider to use. 

If you can provide an example of the error you are encountering (along with a gist of the `--debug` output) I would be happy to investigate more.
