### ISSUE TITLE
[v2 API] Create a new box with https://app.vagrantup.com/api/v2/boxes not working

### ISSUE THREAD

**Issue by hswong3i** [hashicorp/vagrant#13539]
### Debug output

After [Migrate to HCP Vagrant Registry](https://developer.hashicorp.com/vagrant/vagrant-cloud/hcp-vagrant/migration-guide), running the https://developer.hashicorp.com/vagrant/vagrant-cloud/api/v2#create-a-box no longer working.

My testing script (simplify from https://gitlab.com/alvistack/vagrant-ubuntu/-/blob/f5fdd7425081be309919bac147fddc1afa7b6c50/.gitlab-ci.yml):
```
#!/bin/bash

hcp auth login --client-id=$HCP_CLIENT_ID --client-secret=$HCP_CLIENT_SECRET
export VAGRANT_CLOUD_TOKEN=";$(hcp auth print-access-token)"

curl -skL \
  --request POST \
  --header "Content-Type: application/json" \
  --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
  --data "{ \"box\": { \"username\": \"alvistack\", \"name\": \"ubuntu-24.10\", \"is_private\": false } }" \
  https://app.vagrantup.com/api/v2/boxes | jq .
```

### Expected behavior

In the old good day with https://app.vagrantup.com/alvistack/ + create a new box for Ubuntu 24.04 (see https://gitlab.com/alvistack/vagrant-ubuntu/-/jobs/6617414719#L143):
```
{
  "tag": "alvistack/ubuntu-24.04",
  "username": "alvistack",
  "name": "ubuntu-24.04",
  "private": false,
  "downloads": 0,
  "created_at": "2024-04-13T16:41:05.754+08:00",
  "updated_at": "2024-04-13T16:41:05.754+08:00",
  "short_description": null,
  "description_markdown": null,
  "description_html": null,
  "current_version": null,
  "versions": []
}
```

In case box already created (see https://gitlab.com/alvistack/vagrant-ubuntu/-/jobs/6619715529#L148):
```
{
  "errors": [
    "Type has already been taken"
  ],
  "success": false
}
```

### Actual behavior

Above script now v2 API giving error output:
```
Successfully logged in!
{
  "code": 3,
  "message": "public_id: cannot be blank.; registry: cannot be blank",
  "details": [
    {
      "@type": "type.googleapis.com/google.rpc.BadRequest"
    }
  ],
  "errors": [
    "public_id: cannot be blank.; registry: cannot be blank"
  ]
}
```

**Comment by chrisroberts** [comment]
Hi there,

There was a payload decoding issue that has been identified and fixed. Thank you for reporting the issue and apologies for any trouble it caused.

Cheers!
