### ISSUE TITLE
Ability to set the box hostname and domain from Vagrantfile

### ISSUE THREAD

**Issue by johnae** [hashicorp/vagrant#139]
Well, not much more to say than the title already does but in general this would mean on an Ubuntu system to change the /etc/hostname, /etc/hosts so 127.0.1.1 points to hostname.domain.tld hostname and preferably also change the /etc/resolv.conf so domain and search is set.

Anyone already doing this through vagrant? Am I missing something?

**Comment by guoqiao** [comment]
> Not sure when this was added, but this works for me to set the hostname:
> 
> ```
>  config.vm.host_name = 'foo.bar'
> ```

It should be `hostname`.
