### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by medatech** [hashicorp/vagrant#1399]
Having some trouble with running vagrant on a desktop with Windows 8.  I've had no issues on other machines, and no issues with Virtual Box in general.

I've experienced a combination of random crashes, some Windows reports that VBoxHeadless.exe has an issue, sometimes it goes unnoticed.

The command line outputs the following during the execution of my setup shell script after running "vagrant up":

[default] Destroying VM and associated drives...
C:/vagrant/vagrant/embedded/gems/gems/net-ssh-2.2.2/lib/net/ssh/buffered_io.rb:65:in `recv': An existing connection was forcibly closed by the remote host. - recvfrom(2) (Errno::ECONNRESET)
        from C:/vagrant/vagrant/embedded/gems/gems/net-ssh-2.2.2/lib/net/ssh/buffered_io.rb:65:in`fill'
        from C:/vagrant/vagrant/embedded/gems/gems/net-ssh-2.2.2/lib/net/ssh/connection/session.rb:228:in `block in postprocess'
        from C:/vagrant/vagrant/embedded/gems/gems/net-ssh-2.2.2/lib/net/ssh/connection/session.rb:224:in`each'
        from C:/vagrant/vagrant/embedded/gems/gems/net-ssh-2.2.2/lib/net/ssh/connection/session.rb:224:in `postprocess'
        from C:/vagrant/vagrant/embedded/gems/gems/net-ssh-2.2.2/lib/net/ssh/connection/session.rb:203:in`process'
        from C:/vagrant/vagrant/embedded/gems/gems/net-ssh-2.2.2/lib/net/ssh/connection/session.rb:161:in `block in loop'
        from C:/vagrant/vagrant/embedded/gems/gems/net-ssh-2.2.2/lib/net/ssh/connection/session.rb:161:in`loop'
        from C:/vagrant/vagrant/embedded/gems/gems/net-ssh-2.2.2/lib/net/ssh/connection/session.rb:161:in `loop'
        from C:/vagrant/vagrant/embedded/gems/gems/net-ssh-2.2.2/lib/net/ssh/connection/channel.rb:269:in`wait'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/communication/ssh.rb:223:in `shell_execute'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/communication/ssh.rb:53:in`block in execute'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/communication/ssh.rb:111:in `connect'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/communication/ssh.rb:52:in`execute'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/communication/ssh.rb:72:in `sudo'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/provisioners/shell.rb:88:in`block in provision!'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/provisioners/shell.rb:55:in `with_script_file'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/provisioners/shell.rb:83:in`provision!'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/provision.rb:34:in `block in call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/provision.rb:31:in`each'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/provision.rb:31:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/forward_ports.rb:24:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/check_port_collisions.rb:42:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/env/set.rb:16:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/clear_forwarded_ports.rb:13:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/clean_machine_folder.rb:17:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/check_accessible.rb:18:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/general/validate.rb:13:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/general/check_virtualbox.rb:23:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/match_mac_address.rb:16:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/default_name.rb:17:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/check_guest_additions.rb:33:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/import.rb:31:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/check_box.rb:28:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/vm/check_accessible.rb:18:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/general/validate.rb:13:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/general/check_virtualbox.rb:23:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/warden.rb:33:in`call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/builder.rb:92:in `call'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/runner.rb:49:in`block in run'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/action/runner.rb:49:in`run'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/vm.rb:192:in `run_action'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/vm.rb:145:in`up'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/command/up.rb:31:in `block in execute'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/command/base.rb:116:in`block in with_target_vms'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/command/base.rb:111:in `each'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/command/base.rb:111:in`with_target_vms'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/command/up.rb:24:in `execute'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/cli.rb:42:in`execute'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/lib/vagrant/environment.rb:167:in `cli'
        from C:/vagrant/vagrant/embedded/gems/gems/vagrant-1.0.6.dev/bin/vagrant:43:in`<top (required)>'
        from C:/vagrant/vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in `load'
        from C:/vagrant/vagrant/bin//../embedded/../embedded/gems/bin/vagrant:23:in`<main>'

I've no idea if this is a firewall issue on my machine setup, an issue with Virtual Box or an issue with Vagrant on Windows 8 64-bit pro.

Any hints would be much appreciated.

**Comment by NoelDavies** [comment]
I'm getting this exact error
