### ISSUE TITLE
No host IP was given to the Vagrant core NFS helper.

### ISSUE THREAD

**Issue by guglielmo** [hashicorp/vagrant#1437]
When starting or reloading a vagrant instance on OSX, I receive this error

```
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] VM booted and ready for use!
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /vagrant
No host IP was given to the Vagrant core NFS helper. This is
an internal error that should be reported as a bug.
```

I am on an up-to-date OSX Mountain Lion, Vagrant is in its 1.1.0 version.

Below, the Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"


  config.vm.provision :shell do |s|
      s.path = "provisioning/bootstrap.sh"
  end

  config.vm.network :forwarded_port, guest: 80, host: 8680

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", "1024"]
    v.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.synced_folder ".", "/vagrant", :nfs => true

end
```

**Comment by simple10** [comment]
Just setting the `type: 'rsync'` without changing any IPs worked for me.

**Comment by kororo** [comment]
Hi guys,

This fix will do the jobs as well.

```
config.vm.provider :aws do |aws, override|
    override.nfs.functional = false
```

Hope helps.

**Comment by ynk** [comment]
Still have this bug here.
```
config.vm.box = "maier/alpine-3.1.3-x86_64"
config.vm.network = "private_network", type: "dhcp"
```

I'm popping a bunch of VMs, so `dhcp` is mandatory ; also i use `nfs` share because alpine doesnt wont provide something else. and yes, i installed the `vagrant-alpine` plugin :)

Any help appreciated.

**Comment by amistry79** [comment]
Is there any update on this issue?

I have below configuration
vagrant Installed Version: 1.8.1
virtual box => vboxmanage --version 5.0.16r105871
Mac Book Pro OS X EL Capitan Version 10.11.4

Below is the logs:

ABC-MAC30:src usrname $ sudo vagrant reload
Password:
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'mirth/centos-7.1' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
default: Adapter 1: nat
default: Adapter 2: bridged
default: Adapter 3: hostonly
==> default: Forwarding ports...
default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
default: SSH address: 127.0.0.1:2222
default: SSH username: vagrant
default: SSH auth method: private key
==> default: Machine booted and ready!
GuestAdditions 5.0.16 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
No guest IP was given to the Vagrant core NFS helper. This is an
internal error that should be reported as a bug.

**Comment by heavyengineer** [comment]
If it helps, i only get this error with the Am79C970A nic driver. If i change it to 82543GC or virtio i don't see this issue: host Ubuntu 16, vm centos 6.x

**Comment by COLABORATI** [comment]
This  error still exists with 1.8.5 - after all these years, it would be really great to see some intensity flowing into fixing this error, as this is a *very basic functionality* that is mandatory for working with virtual machines.

I can work with a virtual computer that can not use networking features that exist since 20 years or longer and are expected to just work. Please make it a high priority to finally fix this annoyance that makes vagrant practically unusable in many use cases, thank you very much!

**Comment by venimus** [comment]
I see that hyper-v's synced folders plugin does not support NFS because it does not set env[:nfs_host_ip] and env[:nfs_machine_ip]

**Comment by lonniev** [comment]
It may be self-evident, but proposed workarounds that imply disabling NFS capabilities really aren't useful for people trying to use NFS for the folder sync. For example, yes, `override.nfs.functional = false` is a satisfying hammer when one wants to use SMB, rsync, or WinRM. It's bloody chainsaw for those who are trying to use NFS because SMB, rsync, and WinRM are all themselves busted for the particular combination of Host, Guest, Vagrant release, and Chef release.

(As a community, we REALLY need some reliable way to sync folders from Hosts to Guests when the host is Unix-ish and the guest is Windows.)

**Comment by lonniev** [comment]
For the provider that I am using, I shouldn't expect success but I should at least expect more informative warnings.

In my case, the vagrant-softlayer plugin has no support for NFS synced folders and only supports rsync synced folders.

Therefore, sure, it is not returning guest and host IP address information to core vagrant.

We might have the warning say, "For machine XYZ, using Provider ABC, no Host (and Guest) IP information has been provided for the NFS sync_folder service. Perhaps this provider doesn't support NFS service?"

**Comment by jersten** [comment]
I'm currently experiencing this bug in version 1.8.6

**Comment by openface** [comment]
Also seeing this issue with latest Vagrant and VirtualBox.  Host is OS/X and guest is Centos7.

**Comment by scottjacobsen** [comment]
I get this with this configuration:

```
config.vm.network "private_network", type: "dhcp"
config.vm.synced_folder ".", "/vagrant", type: "nfs"
```

Do I need to hard code an IP address?

Vagrant 1.8.6
Virtualbox 5.1.8

**Comment by tschirmer** [comment]
Same @scottjacobsen with the same versions

**Comment by hasorli** [comment]
Also seeing this issue with Vagrant 1.8.1, VirtualBox 5.0.32. Host is OS/X 10.95, Darwin Kernel Version 13.4.0:, and guest is Centos 7.3 ( CentOS-7-x86_64-Vagrant-1702_01 )

config.vm.network "private_network", type: "dhcp"

config.cache.synced_folder_opts = {
    type: :nfs,
   mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
  }

**Comment by atomic77** [comment]
I'm also hitting this problem on a OSX host using VirtualBox with CentOS 7 guest, but only with DHCP networking. 

From a quick look through the debug logs, seems like we're dependent on a call to 

    $ VBoxManage guestproperty get daf5ba1d-ce15-124d-8be9-1a8fcfe370d6 /VirtualBox/GuestInfo/Net/1/V4/IP
    **No value set!**

Though there is a dynamic IP:

    $ vagrant ssh -c "ip a show dev eth1"
    3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
        inet 172.28.128.5/24 brd 172.28.128.255 scope global dynamic eth1

When I use a static network the GuestInfo property is still empty, but I'm guessing this is not used if the VM is configured with a static IP.

I have a simple workaround for now (static IP), but it would be nice to be able to use DHCP.

**Comment by bitsydarel** [comment]
Any news on this issue ?
