### ISSUE TITLE
Please provide search form for documentation

### ISSUE THREAD

**Issue by kadishmal** [hashicorp/vagrant#1445]
Since the new Vagrant release, there is a new documentation as well which has different syntax and requirements. Since my former Vagrantfile is broken due to the absence of `host_name` method, I need to find the documentation which explains how to use `host_name` in the new Vagrant. But unless I do search on Google which displays tutorials for older version of Vagrant, I have nothing to do but manually traverse every single documentation page.

So, please provide a search form for Vagrant documentation. I would really appreciate it.

Thank you.

**Comment by adam-fineman** [comment]
There is a [middleman-search plugin](https://manas.tech/blog/2015/10/22/middleman-search-client-side-search-in-your-middleman-site.html).
