### ISSUE TITLE
Can't execute sudo commands on machine that requires tty to run sudo

### ISSUE THREAD

**Issue by jonathanq** [hashicorp/vagrant#1482]
I ran in to an issue with vagrant-aws that was documented at https://github.com/mitchellh/vagrant-aws/issues/10

However as I dug into it and found the root of the issue, it appears to be with vagrant itself.  The short version is that Vagrant's SSH code doesn't allow calling sudo commands against a remote machine that requires a tty to execute sudo commands.  The error message returned is `sorry, you must have a tty to run sudo`.  I assume this security feature is only enabled on CentOS, Amazon Linux (and probably other RHEL based AMIs) but not Ubuntu.  But I haven't tested against an Ubuntu instance to verify.  I expect I haven't hit this before with vagrant 1.0.x because all of the .box files I used allowed sudo commands to be run without requiring a tty.  While the AMIs I am using now with the vagrant-aws plugin do have this setup.

I tried to change https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/ssh/communicator.rb to use Net::SSH request_pty method (http://net-ssh.rubyforge.org/ssh/v2/api/index.html).  But I wasn't able to get it to work.  However I suspect that is mostly to do with my limited experience with Ruby.

**Comment by yves-vogl** [comment]
@atulatri That would ne nice.

@mitchellh Can you explain why PTYs are so nasty?

**Comment by ddarbyson** [comment]
Seems like `config.ssh.pty` option isn't working with vagrant-aws plugin
https://github.com/mitchellh/vagrant-aws/issues/340

**Comment by SydOps** [comment]
`config.ssh.pty` option is really bad way which generate un-forecast issue and no debug information you can see any more. 

I fixed it by comment the line of `Defaults    requiretty` in `/etc/sudoers`

Here is the detail explain for this option

```
# Disable "ssh hostname sudo <cmd>", because it will show the password in clear.
#         You have to run "ssh -t hostname sudo <cmd>".
#
# Defaults    requiretty
```

**Comment by revmischa** [comment]
I suppose you think I used that option out of pure spite for all vagrant developers?
Thanks for that fix btw. lol.

**Comment by yves-vogl** [comment]
The whole _requiretty_ thing was ment as a security feature after all, wasn't it?

As far as I know there's a difference between a pty and a tty. _requiretty_ means to me, that it's required to have a tty (= e.g. physically attached) instead of a pseudo-device (= e.g. via SSH).

Can someone clarify this to me?

**Comment by SydOps** [comment]
It is bug and fixed by redhat at March 2014.
```
* Mon Mar 10 2014 Daniel Kopecek <dkopecek@redhat.com> - 1.8.8-3
- remove bundled copy of zlib before compilation
- drop the requiretty Defaults setting from sudoers
```
[default requiretty is problematic and breaks valid usage](https://bugzilla.redhat.com/show_bug.cgi?id=1020147), confirmed by Redhat.

**Comment by revmischa** [comment]
Yeah. I have a realllly old vagrantfile lol.

**Comment by oculushut** [comment]
Looks like the **sudo** version on my CentOS 7 box is older than the one where bug was fixed:

```
[git@gitclient janus-server]$ sudo -V
Sudo version 1.8.6p7
Sudoers policy plugin version 1.8.6p7
Sudoers file grammar version 42
Sudoers I/O plugin version 1.8.6p7
```

This is my box: https://atlas.hashicorp.com/oculushut/boxes/vagrant-centOS64-oculushut

Looks like I may need to add that !requiretty line back in then...

**Comment by ursachec** [comment]
Thanks to you @blalor , a two hour debugging session on a Friday night ended with an actual result.
Disabling ```requiretty``` solves the issue like a charm

**Comment by Jakobud** [comment]
For anyone coming across this issue on CentOS 7, you can fix it by doing `# sudo visudo` and then commenting out the line
```
Defaults    requiretty
```
