### ISSUE TITLE
Problem with network interfaces - 1.1.4

### ISSUE THREAD

**Issue by bkuberek** [hashicorp/vagrant#1513]
I have a Debian 6 base box which has worked for me with an earlier version of Vagrant. Yesterday I upgraded Vagrant to 1.1.4, updated my Vagrantfile to use version 2 of the config. I am using NFS mounts for shared folders and even after the upgrade they worked fine on machines there were already created. It will not work on new machines.

In other words, I had a VM running. I upgraded Vagrant and did a `vagrant reload` and everything was fine. But it does not work when destroying the VM and creating it fresh:

```
vagrant destroy
vagrant up
```

I looked into the VM and compared to one that was still working and the problem seems to be with the network interface eth1 not working. Other VMs have eth1 available and it works fine but the ones freshly created do not have eth1 working even though it is defined in `/etc/network/interfaces`.

Here is a debug gist: https://gist.github.com/bkuberek/5263153

**Comment by bridiver** [comment]
I think this ticket should be re-opened. This completely fails on Fedora 21 because it doesn't use eth0, eth1, etc.. the interfaces I have are enp0s3 and enp0s8

**Comment by bridiver** [comment]
the problem with fedora appears to be that it is using redhat instead of fedora

DEBUG guest: Checking in: redhat
DEBUG guest: Found cap: configure_networks in redhat

but virtualbox shows it as Fedora

**Comment by birgitta410** [comment]
Does anybody know a respective workaround for this when packaging a coreos base box? 

`/etc/udev/rules.d/70-persistent-net.rules` does not exist in mine (`rules.d` folder is empty, actually), but I'm having the "no such device" problem when I try to configure the IP of a re-packaged box with `config.vm.network :private_network, ip: "x.x.x.x"`

(The coreos base box I'm using is `http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json`)
