### ISSUE TITLE
missing NFS support error on Ubuntu hosts could be improved perhaps

### ISSUE THREAD

**Issue by rubiojr** [hashicorp/vagrant#1534]
@mitchellh, I'm just nitpicking but perhaps the missing NFS support error could be improved in Ubuntu hosts?

The error reads:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.
```

nfsd is MacOSX specific (I think) and installing nfs-common package is good enough to make Vagrant 1.1.5 happy in Ubuntu (apparently). Since nfs-common isn't installed by default in Ubuntu installs, I guess this 'issue' will bite more people.

Since the package name is Ubuntu specific and Fedora, RHEL, whatever may need other packages, perhaps adding a link to a KB/wiki article or FAQ in the error output, listing this and recommending a 'fix' may be a good idea?

**Comment by jeremy-bruns** [comment]
same here, u need both 

sudo apt-get install nfs-common nfs-kernel-server

**Comment by Jose-27** [comment]
run this works for Ubuntu 15.10 
sudo apt-get install nfs-common nfs-kernel-server

**Comment by thafner** [comment]
`$ sudo apt-get install nfs-common nfs-kernel-server` also works for me on Ubuntu 16.04

**Comment by corysimmons** [comment]
Just reiterating @faviouz [original comment](https://github.com/mitchellh/vagrant/issues/1534#issuecomment-34242441) for the thumbs up karma.

`sudo apt-get install nfs-common nfs-kernel-server`

**Comment by markl17** [comment]
what exactly does one add to vagrantfile to get it of the ground all of these are post commands how about plain vagrant syntax   
slave.vm.provider "virtualbox" do |vb|
      vb.memory = $ucp_slave_memory
    end

**Comment by inoas** [comment]
### OS X 10.11/10.12

For me the solution was to change whatever `export PATH=` saying to `export PATH="/sbin:`... whatever it was saying before because nfsd was actually installed and running but somehow vagrant didn't find it.

```
mate ~/.bash_profile; # instead of mate you can use: open, vim, atom, etc
```
Change `export PATH=` saying to `export PATH="/sbin:`
```
source ~/.bash_profile;
vagrant up;
```

* * *

**BUT**, I suppose the more secure-by-default solution is to add a symbolic link like so:
```
ln -s /sbin/nfsd /usr/local/sbin/nfsd
```

**Comment by ston3o** [comment]
On arch linux: `pacman -S nfs-utils`

**Comment by jkobus** [comment]
just to confirm, this command still works on Ubuntu 17.10
`sudo apt-get install nfs-common nfs-kernel-server`

**Comment by JimiPedros** [comment]
I've tried sudo apt-get install nfs-common nfs-kernel-server on Ubuntu 14.04 trusty and i'm still gettingt the same error

**Comment by vcollado0** [comment]
This command works still works on Ubuntu 18.04: 
```text
sudo apt-get install nfs-common nfs-kernel-server
```

**Comment by apandrade** [comment]
This works for me on Ubuntu 18.10

`sudo apt-get install nfs-common nfs-kernel-server`

**Comment by dinhtuan242** [comment]
sudo apt-get install nfs-common nfs-kernel-server still working on Ubuntu 18.04 03/07/2019

**Comment by parvind87** [comment]
sudo apt-get install nfs-common nfs-kernel-server still working on Ubuntu 18.04 24 Oct 2019

**Comment by LOMFM** [comment]
Above command works for me ( on Ubuntu 18.04 ).
`sudo apt-get install nfs-common nfs-kernel-server`  
Thanks all.
