### ISSUE TITLE
Bogus error, "Forwarded port 'xxxx' (host port) is declared multiple times"

### ISSUE THREAD

**Issue by twork** [hashicorp/vagrant#1541]
I'm working my way through the "Getting Started" guide, using vagrant 1.1.5 on Debian wheezy/sid.  At the Port Forwarding step under Networking, on "vagrant reload", I'm getting the error:

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* Forwarded port '4567' (host port) is declared multiple times
```

I'm pretty sure that the port is not actually declared multiple times.  To test, I tried changing it to "4568", just in case there's some kruft somewhere that the tutorial and I aren't aware of, but that also draws a "declared multiple times" error.  Removing that line completely gets rid of that error and also doesn't yield any port forwarding to my guest system, so it looks like something is trying to parse that line more than once...?

The relevant section of my Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "mrj-1"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.network :forwarded_port, host: 4567, guest: 80
end
```

My complete Vagrantfile is at: http://pastebin.com/PWPtcHYJ

The URL I loaded the box from is the one from the tutorial, "http://files.vagrantup.com/precise32.box"

**Comment by enoch85** [comment]
Just another confirmation. This worked. Thanks!
