### ISSUE TITLE
Shell provisioning fails to exit

### ISSUE THREAD

**Issue by axelfontaine** [hashicorp/vagrant#1553]
**Host OS:** Win7 x64, Vagrant 1.1.5
**Guest OS:** http://cloud-images.ubuntu.com/vagrant/quantal/current/quantal-server-cloudimg-amd64-vagrant-disk1.box

Using _vagrant provision_ with shell provisioning, when I start a Java process with threads waiting for input (embedded Jetty server), the **ssh session never closes**.

The process is started like this: _nohup java -cp my.jar my.MainClass arg1 arg2 &_

It is then properly started in the background, and the next shell provisioned command executes. Yet, the _vagrant provision_ command never returns.

**Workaround:** adding _pkill ssh_ at the end of the shell provisioning command list and ignoring the stacktrace.

Cheers
Axel

**Comment by shafi-codez** [comment]
This is great solution for nohup.

Thanks !
