### ISSUE TITLE
vagrant add box - failed to unpackage properly - Win8x64 - v1.1.5

### ISSUE THREAD

**Issue by rdeknijf** [hashicorp/vagrant#1560]
Adding **any** box fails on Win8x64:

```
H:\>vagrant box add precise64 precise64.box
Downloading with Vagrant::Downloaders::File...
Copying box to temporary location...
Extracting box...
Cleaning up downloaded box...
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x box-disk1.vmdk: Can't update time for box-disk1.vmdk: Invalid argument
x box.ovf: Can't update time for box.ovf: Invalid argument
x Vagrantfile: Can't update time for Vagrantfile: Invalid argument
bsdtar: Error exit delayed from previous errors.
```

Full DEBUG response: https://gist.github.com/rdeknijf/5345087
- Vagrant 1.1.5
- VirtualBox 4.2.10
- Tried on two machines
- It works on Vagrant 1.0.6.dev
- 2gb ramdrive mounted on h:
- $TEMP = h:\TEMP

I end up with

```
 Directory of h:\TEMP\vagrant-box-add-temp-20130409-8716-1nvhadc

09-04-2013  14:13    <DIR>          .
09-04-2013  14:13    <DIR>          ..
09-04-2013  14:13       320.654.336 box-disk1.vmdk
09-04-2013  14:13            14.108 box.ovf
09-04-2013  14:13               505 Vagrantfile
               3 File(s)    320.668.949 bytes
               2 Dir(s)   1.458.995.200 bytes free
```

I'm at a loss... Is it trying to unpack it twice?

**Comment by HongKilDong** [comment]
WinXp SP3 + vagrant 1.7.2

D:\downloads>vagrant box add precise32 precise32.box
==> box: Adding box 'precise32' (v0) for provider:
    box: Downloading: file://D:/downloads/precise32.box
    box: Progress: 100% (Rate: 9.9M/s, Estimated time remaining: --:--:--)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

**Comment by jeffz2012** [comment]
This issue surfaces again ... just now it fails silently

**Comment by Hukuta** [comment]
In my case  it was out of disk space in home folder
