### ISSUE TITLE
Enable/Disable plugins on a per Vagrantfile basis

### ISSUE THREAD

**Issue by reset** [hashicorp/vagrant#1574]
Some plugins may not fit for every project that is leveraging Vagrant. As is, all plugins which are installed are loaded when Vagrant starts. It would be awesome if a plugin author had the option to lazily load their plugins and require users to manually require these plugins in  their Vagrantfile.

A good example plugin which may not need to be loaded for every project is [Berkshelf-Vagrant](https://github.com/RiotGames/berkshelf-vagrant). We're currently [taking steps](https://github.com/RiotGames/berkshelf-vagrant/pull/16) to add our own 'enable' configuration flag which will cause the middleware to do a no-op.

**Comment by dasgoll** [comment]
Shouldn't this fucntionality be in core??

**Comment by jhoblitt** [comment]
I'm running into vagrant-librarian-puppet being incompatible with puppet-aws when its parallelizing.  It would be great to not have to uninstall a plugin to disable it...

**Comment by romanvbabenko** [comment]
+1

**Comment by dasgoll** [comment]
+1

**Comment by lsloan** [comment]
+1 :+1:

**Comment by amosshapira** [comment]
Same situation as @jhoblitt - I got vagrant [vagrant-vbguest](https://github.com/dotless-de/vagrant-vbguest) which only supports Linux, so it breaks my OSX Vagrant boxes...

**Comment by chillum** [comment]
Same situation as @amontalban, vargrant-vbguest works with Linux, but breaks FreeBSD.

**Comment by varac** [comment]
I love vagrant-sshfs which works great for vagrant-libvirt but breaks with vagrant-lxc :(
So @mitchellh please consider this functionality in vagrant-core, because the the workaround you proposed isn't valid anymore now that vundler is not maintained anymore.

**Comment by robinbowes** [comment]
Really? Is there no native way to disable plugins on a per-environment basis?

**Comment by wmantly** [comment]
Any update on this?
