### ISSUE TITLE
Vagrant Setup Issue

### ISSUE THREAD

**Issue by life2539** [hashicorp/vagrant#1600]
During installation in a Windows 7 PC I get the following message:

"The cabinet file 'Vagrant.cab' required for this installation is corrupt and cannot be used. This could indicate a network error, an error reading from the CD-ROM, or a problem with this package."

I have tried downloading the program multiple times through different channels and still got the same problem.

any alternate installation methods i can use?

**Comment by placidrod** [comment]
I am on Windows 7 machine (64 bit). I have installed VirtualBox version 5.0.10. I am getting the same error when I am trying to install Vagrant 1.7.4. Please do help.

**Comment by keepgoingwm** [comment]
I met the same err. (With a new system but old installation file)
Then I download the installation again. It worked.

**Comment by loncool** [comment]
we have the same err...
