### ISSUE TITLE
Support lsyncd as directory-sharing technique

### ISSUE THREAD

**Issue by wizonesolutions** [hashicorp/vagrant#1602]
Being able to run larger web apps like Drupal against a native filesystem in the VM would be fantastic. The issue is that it's a workflow destroyer. IDEs such as PhpStorm ease this, but being dependent on an IDE for file syncing feels wrong. 

lsyncd by @axkibe uses rsync and SSH, is configurable, and maybe even works in Cygwin (haven't checked).

Could be a great alternative to NFS.

To give an idea:

https://github.com/axkibe/lsyncd/wiki/Lsyncd%202.1.x%20%E2%80%96%20Layer%204%20Config%20%E2%80%96%20Default%20Behavior

**Comment by toobulkeh** [comment]
Did a mechanism ever come for this? Rsync came out in 2014, but I haven't been able to find lsyncd anywhere
