### ISSUE TITLE
Can the vmdk file be compressed with 7zip?

### ISSUE THREAD

**Issue by coding-horror** [hashicorp/vagrant#1614]
We're seeing 40% size reduction in the Vagrant package size if we can switch to 7zip for the .vmdk file in the virtual machine:

http://meta.discourse.org/t/how-can-we-make-our-vagrant-vm-image-smaller/5938/8

However, we'd need to somehow script the unzipping of the .vmdk file using un7zip as part of the Vagrant process -- is this even possible?

**Comment by ktomk** [comment]
Can someone please provide more information on how this can be applied? Is just 7z'ing the .box file created by the package vagrant command enough?
