### ISSUE TITLE
'vagrant destroy' not working correctly in cygwin

### ISSUE THREAD

**Issue by thasmo** [hashicorp/vagrant#1616]
Hello there!

```
vagrant destroy
Vagrant is attempting to interface with the UI in a way that requires
a TTY. Most actions in Vagrant that require a TTY have configuration
switches to disable this requirement. Please do that or run Vagrant
with TTY.
```

That's on vagrant 1.2.1.

**Comment by oliver-dungey** [comment]
Maybe some more clues here ...

I am on Windows 7 64bit but `uname -s` returns **CYGWIN_NT-6.1** without the **WOW64** even though it is a 64bit cygwin install. This error only turned up after changing my configuration to turn on colorize (config.vm.provision.salt.tcolorize) - this error now comes up when trying to destroy existing VM's, --force fixes lets me destroy the VMs, removing tcolorize gets rid of the invalid configuration issue that seems to be hidden when calling destroy.

**Comment by russellvt** [comment]
As-per comments in the bug, above...setting the environment with "VAGRANT_DETECTED_OS=cygwin" is a good workaround, here.

**Comment by mstra001** [comment]
the environment var worked for me.
uname-s CYGWIN_NT-10.0-WOW
