### ISSUE TITLE
"Booting VM" forever (Selecting on IO)

### ISSUE THREAD

**Issue by paulocheque** [hashicorp/vagrant#1631]
It is stucked in "Botting VM" message forever. Any ideas?

Vagrant version 1.2.0

Using quantal64.box
VAGRANT_LOG=debug vagrant up --provider virtualbox
    vb.customize ["modifyvm", :id, "--cpus", "1"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    vb.customize ["modifyvm", :id, "--memory", "256"]

Ubuntu 12.10 64
machine RAM 512mb

[default] Running any VM customizations...
 INFO subprocess: Starting process: ["VBoxManage", "modifyvm", "90c9da4e-2f5b-49c1-8c86-720f6a5ff038", "--cpus", "1"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["VBoxManage", "modifyvm", "90c9da4e-2f5b-49c1-8c86-720f6a5ff038", "--cpuexecutioncap", "50"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["VBoxManage", "modifyvm", "90c9da4e-2f5b-49c1-8c86-720f6a5ff038", "--memory", "256"]
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
 INFO warden: Calling action: #VagrantPlugins::ProviderVirtualBox::Action::Boot:0x00000002cc0d60
 INFO interface: info: Booting VM...
[default] Booting VM...
 INFO subprocess: Starting process: ["VBoxManage", "startvm", "90c9da4e-2f5b-49c1-8c86-720f6a5ff038", "--type", "headless"]
DEBUG subprocess: Selecting on IO

**Comment by ananya0631** [comment]
I am facing the same problem on Windows 7. Using vagrant BOX:  box 'inclusivedesign/windows7-eval-x64' .The machine opens properly in GUI but the Vagrant command does not complete. 
On running without debug mode the "Vagrant UP" command is stuck at 
Booting VM.

In the debug mode i am geeting the following message
-------------------------------------------------------------------------------------------------------------------
INFO subprocess: Starting process: ["C:/Program Files/Oracle/VirtualBox/VBoxManage.exe", "startvm", "b4227a86-887f-488d-8aa6-4e035beaf93e", "--type", "gui"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
---------------------------------------------------------------------------------------------------------

Please help!!!!!!!!!

**Comment by martinsotirov** [comment]
Same problem with Vagrant 1.9.1 on OSX Sierra. It's stuck forever and this is the output I get when I try to boot with the `--debug` flag:
```
INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "b3fb9e67-a0be-4dc4-85d0-7ab9dd3aaa1d"]
DEBUG subprocess: Command not in installer, not touching env vars.
INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
```

**Comment by iddqdidkfa** [comment]
I have the same issue on Windows 7 x64. Running `vagrant up --provider=virtualbox` helps, but I don't like such workarounds. It should work without this spike.
