### ISSUE TITLE
Windows installer defaults to "C:\HashiCorp\Vagrant\"

### ISSUE THREAD

**Issue by thasmo** [hashicorp/vagrant#1652]
Happens for Vagrant 1.2.2 on Windwows 8 and Windows 7 after uninstalling Vagrant 1.2.1 manually. The default path is set to "C:\HashiCorp\Vagrant\" instead of "C:\Program Files (x86)\HashiCorp\Vagrant\".

**Comment by apupier** [comment]
The ruby bug is supposed to be fixed for a very long time: https://bugs.ruby-lang.org/issues/7036

**Comment by renaatdemuynck** [comment]
Just installed it under "C:\Program Files (x86)\HashiCorp\Vagrant" without any issues.

**Comment by alfredomp** [comment]
We just tried it using "C:\Program Files (x86)\HashiCorp\Vagrant"  as @renaatdemuynck suggested but we also had to set VAGRANT_HOME=C:\Program Files (x86)\HashiCorp\Vagrant , as suggested in this post https://github.com/mitchellh/vagrant/issues/2056. Now we don't the error "failed writing body" but we got another saying: "There was an error while execution Vboxmanage as CLI used by Vagrant to control VirtualBox ..." We are using Windows 7.

**Comment by Armfoot** [comment]
I have _Windows 10_ and typed `C:\Program Files\Vagrant` for the destination folder.
The installation went smoothly and when I checked the system's PATH the entire `Vagrant` folder was actually in `C:\Program Files (x86)\Vagrant\bin`. Vagrant's folder has only these folders:

- `bin` folder with only `vagrant.exe` inside;
- `embedded` folder with vagrant's files (e.g. `unins000.exe`, another `bin` folder, etc.).

I opened up a shell and was able to run vagrant commands:
```
> vagrant --version
Vagrant 1.9.5
```
I did not need to set any environment variables by hand.

**Comment by renaatdemuynck** [comment]
On my Windows 7 machine, `C:\Program Files (x86)\HashiCorp\Vagrant\bin` is also in the `PATH` environment variable. I did not have the set anything manually.

**Comment by gregbown** [comment]
Installing in C:\Program Files (x86)\HashiCorp\Vagrant works great.
Environmental path was automatically set to C:\Program Files (x86)\HashiCorp\Vagrant\bin
Vagrant version 2.1.1, Windows 10 proffesional

**Comment by epatr** [comment]
If I try to install the Windows 64-bit version to the main "Program Files" directory, the installer hangs for a bit and then changes it to "Program Files (x86)". This caused some confusion for me when I was trying to upgrade a previously installed 64-bit version, and thought I had installed the 32-bit version. I installed the 32-bit version over top of it, and while there haven't been any problems so far, it is definitely unexpected behavior.

**Comment by commandline-be** [comment]
I'd love for the installer to have at least a flag to be able to define WHERE the installation should land.

**Comment by Mark-Booth** [comment]
It is disappointing that this issue still hasn't been fixed 6 years later.

If I'd been using vagrant on a non windows platform for a while and already discovered it's benefits I might overlook this, but starting off with vagrant on Windows this doesn't give me confidence that Windows is a fully supported platform.
