### ISSUE TITLE
Error when reloading VM: "VBoxManage.exe: error: The object is not ready"

### ISSUE THREAD

**Issue by Symmetric** [hashicorp/vagrant#1653]
Running Vagrant 1.2.1 and VBox 4.2.12-84980, from cygwin on a Win7 machine.

I've had a few issues with the vagrant reload command, which seems to be a bit flaky. Here's one error that I'm seeing when reloading a running VM:

```
$ vagrant reload
[default] Attempting graceful shutdown of VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "402a1a02-d3d5-4147-9b26-9adbaef7d9c1", "--machinereadable"]

Stderr: VBoxManage.exe: error: The object is not ready
VBoxManage.exe: error: Details: code E_ACCESSDENIED (0x80070005), component Console, interface IConsole, callee IUnknown
VBoxManage.exe: error: Context: "COMGETTER(RemoteUSBDevices)(ComSafeArrayAsOutParam(coll))" at line 1840 of file VBoxManageInfo.cpp
```

In VBox Manager, the VM is listed as "Powered off", and I was able to power it on through the VBox Manager. Doing so brought up a Windows Firewall warning (even though I'd already granted it access permissions). Not sure if this last part is relevant. Any other logs that would be useful?

**Comment by manizzle** [comment]
I had the same problem for a while. I fixed it by setting VBoxHeadless to suid. Seems you cant start vms headless without being root. I dont wanna do that because root doesnt have the same vms I made as a normal vboxusers unix user.

**Comment by ArneBachmann** [comment]
I had the `E_ACCESSDENIED` when running a `vagrant up` command through as a Windows Service, even when setting the correct user/profile on ther service's properties. I managed to solve this by using a wrapper batch file that runs
```
@echo off
set MYDIR=%~dp0
runas /profile /savecred /user:DOMAIN\username "cd /D %MYDIR% && python zookeeper-service-wrapper.py"
```
where the latter wrapper issues "vagrant up" and waits for terminate signals before issueing "vagrant halt" (or suspend).

Of course having a Windows service command-line running a cmd.exe Batch file which calls a Python script which calls Vagrant's Ruby code which in turn calls vboxheadless.exe ist quite something around a lightweight ZooKeeper process!
Caveat: When passwords change through company policy, the user is asked for new password in a little shell window that seems to hide itself unless explicitly brought to foreground in th task manager.

**Comment by ArneBachmann** [comment]
I had the E_ACCESSDENIED when running a `vagrant up` command through as a Windows Service, even when setting the correct user/profile on ther service's properties. I managed to solve this by using a wrapper batch file that runs
```
@echo off
set MYDIR=%~dp0
runas /savecred /user:DOMAIN\username "python %MYDIR%zookeeper-service-wrapper.py"
```
where the latter wrapper issues "vagrant up" and waits for terminate signals before issueing "vagrant halt" (or suspend).

Of course having a Windows service command-line running a cmd.exe Batch file which calls a Python script which calls Vagrant's Ruby code which in turn calls vboxheadless.exe ist quite something around a lightweight ZooKeeper process!
Caveat: When passwords change through company policy, the user is asked for new password in a little shell window that seems to hide itself unless explicitly brought to foreground in th task manager.

There are so many intricacies involved - hard top explain how hard it was to achieve this.
