### ISSUE TITLE
'vagrant up' fails to mount linked directory /vagrant

### ISSUE THREAD

**Issue by Symmetric** [hashicorp/vagrant#1657]
I've been slapping the VM about a bit (starting and stopping in VBox as well as vagrant halt, to try and get USB drivers installed), and it appears to have got into a bad state. 

When I run `vagrant up`, I get the following error:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` /vagrant /vagrant
[31mThe following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` /vagrant /vagrant[0m
```

I've repro'd this with debug logs enabled; a gist of the output is [here](https://gist.github.com/Symmetric/5456236).

**Comment by boie0025** [comment]
For anyone else who comes across this using CentOS 7 -- I was getting the same issue with Vagrant 1.7.2, and this box: 'chef/centos-7.0'.  

I can confirm what @tspayde says.  I can reload with the proper mounts until I run `yum update`.  After running `yum update` I can no longer mount the shared folders.

**Comment by marsmensch** [comment]
@boie0025 does it work again after a reboot?

from my past experience it works flawless if you make sure that there is always a current version of the kernel-devel-* and kernel-headers-* packages installed.

yum install kernel-devel-$(uname -r)
yum install kernel-headers-$(uname -r)
yum install dkms

**Comment by boie0025** [comment]
@marsmensch -- Excellent! if I do that along with updating all non-kernel packages, I can restart perfectly.  Thank you for the tip!

**Comment by premyslruzickajr** [comment]
I had this problem on CentOS 7 after running `yum update`. I ran @marsmensch's commands but it didn't work untill I rebuilt VirtualBox Additions with @lenciel's tip `/etc/init.d/vboxadd setup`. Thanks to both!

```
yum update -y
yum install kernel-devel-$(uname -r) kernel-headers-$(uname -r) dkms -y
/etc/init.d/vboxadd setup
```

**Comment by Jeremlicious** [comment]
thanks @lenciel `sudo /etc/init.d/vboxadd setup' worked for me

**Comment by kalyankix** [comment]
I did an yum update after downloading centos7 minimal box that installed kernel-devel as suggested by @premyslruzickajr , and ran vboxadd setup, followed by vagrant reload. Shared folders worked like a charm!! Thanks @premyslruzickajr  and @Jeremlicious

**Comment by Pulber** [comment]
@premyslruzickajr thanks, it worked (centos 6.5)

**Comment by dgoguerra** [comment]
@premyslruzickajr's solution worked for me too, CentOS 6.6. Thanks!

**Comment by rgeraldporter** [comment]
works on CentOS 6.7! Also had to updated Virtual Box and vagrant, and run through the fix noted here as well: https://github.com/mitchellh/vagrant/issues/3341#issuecomment-39015570
