### ISSUE TITLE
Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory

### ISSUE THREAD

**Issue by telemakhos** [hashicorp/vagrant#1671]
Hi, I'm getting this error when 'vagrant up'

```
Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory

VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg*, int, int*)" at line 68 of file VBoxManageHostonly.cpp
```

It appeared suddenly. I assumed this is a Virtualbox issue so I checked the Virtualbox GUI and got this alert.. 

```
Kernel driver not installed (rc=-1908)
```

![Screen Shot 2013-04-29 at 8 58 30 PM](https://f.cloud.github.com/assets/2261077/440546/fa168dda-b100-11e2-8405-d07b5049a2bc.png)

I reinstalled Virtualbox and all was working ok again... for some hours. 

Now and I'm having the same issue. Any clues? I've seen on #vagrant IRC at least one guy with the same problem.

System specs:
Mountain Lion 10.8.3
Vagrant 1.2.2
VirtualBox 4.2.12 r84980

**Comment by steezeburger** [comment]
This works for me on Arch:
````    
sudo vboxreload
````

**Comment by ylove** [comment]
:+1: ` sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart `

**Comment by cperepelitsa** [comment]
@steezeburger Holy crap, thank you. I was desperately hoping for an Arch user in this endless gorram sea of Mac users.
Confirming that this worked for me on Arch:
`sudo vboxreload`

**Comment by steezeburger** [comment]
@cperepelitsa Depending on what's causing the issue, you may also have luck with loading the network adapter kernel module directly via
````
sudo modprobe vboxnetadp
````

**Comment by pcx** [comment]
@cperepelitsa Thanks! 

@steezeburger There seem to be several other kernel modules one might miss loading. `vboxreload` would be a better solution.

**Comment by DamonGant** [comment]
If you're on Arch/any other Linux, try this:

https://wiki.archlinux.org/index.php/VirtualBox#Failed_to_create_the_host-only_network_interface

**Comment by npoggi** [comment]
If you are in Arch or other linuxes:
First make sure modules are loaded with: sudo modprobe vboxdrv vboxnetadp vboxnetflt vboxpci
Then reload: sudo vboxreload

**Comment by leoxopow** [comment]
how fix it on windows?

**Comment by theonlylawislove** [comment]
Having same issue on Windows 10.

**Comment by npoggi** [comment]
@theonlylawislove @leoxopow dual-boot to Linux, or at least use a linux VM for development...

**Comment by theonlylawislove** [comment]
@npoggi So, create a linux virtual to host a linux virtual??

**Comment by ConcernedUsurper** [comment]
@theonlylawislove Don't just upgrade to Windows 10 and expect virtualbox kernel drivers to work out of the box with Vagrant. Vagrant isn't exactly great on Windows to begin with, so the suggestion to dual-boot (not virtualize) seems reasonable.

**Comment by santanusinha** [comment]
On OSX Yosemite the following will work:

sudo  /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart

**Comment by restlessdesign** [comment]
Broken again on El Capitan.

**Comment by wschorn** [comment]
Broken again on El Capitan++

**Comment by rizqidjamaluddin** [comment]
Had the issue with El Capitan, VirtualBox update fixed it for me - the built-in updater was broken on my install so I just downloaded a fresh new 5.0.4 copy.

**Comment by thomasleduc** [comment]
Same error here, after an update on El Capitan

**Comment by tmthyjames** [comment]
Broken in El Capitan. None of the answers above worked for me. Upgrading VirtualBox to 4.3.3 worked.

VirtualBox update link: https://www.virtualbox.org/wiki/Download_Old_Builds_4_3

**Comment by evgeny-l** [comment]
Broken in El Capitan. Reinstall VirtualBox 4.3 fixed the problem.

**Comment by restlessdesign** [comment]
Confirming that re-installing Virtualbox works.

**Comment by kevnk** [comment]
Upgrading to 4.3.30 worked for me (I'm on El Capitan)

**Comment by thomasleduc** [comment]
Same for me, I think it can be close.

**Comment by ericramirez** [comment]
I'm using Arch and I'm experiencing the same issue. Will I need to type sudo vboxreload again and again or does a workaround exist?

**Comment by paolooo** [comment]
Broken in El Capitan too. Installing updates did worked for me. 
Go to `Check for updates > Download > Install`. That's it.

**Comment by josiahsprague** [comment]
I ran into this problem last week after upgrading to El Capitan. Updating VirtualBox to 4.3.3 fixed it, but....

I'm running into the error again this morning (only on one of my Vagrant boxes);
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg*, int, int*)" at line 66 of file VBoxManageHostonly.cpp
```
Running `sudo /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh start` fails with;
```
/Applications/VirtualBox.app/Contents/MacOS/VBoxAutostart => /Applications/VirtualBox.app/Contents/MacOS/VBoxAutostart-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxBalloonCtrl => /Applications/VirtualBox.app/Contents/MacOS/VBoxBalloonCtrl-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxDD2GC.gc => /Applications/VirtualBox.app/Contents/MacOS/VBoxDD2GC.gc-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxDDGC.gc => /Applications/VirtualBox.app/Contents/MacOS/VBoxDDGC.gc-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxExtPackHelperApp => /Applications/VirtualBox.app/Contents/MacOS/VBoxExtPackHelperApp-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless => /Applications/VirtualBox.app/Contents/MacOS/VBoxHeadless-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxManage => /Applications/VirtualBox.app/Contents/MacOS/VBoxManage-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdpCtl => /Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdpCtl-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxNetDHCP => /Applications/VirtualBox.app/Contents/MacOS/VBoxNetDHCP-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxNetNAT => /Applications/VirtualBox.app/Contents/MacOS/VBoxNetNAT-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxSVC => /Applications/VirtualBox.app/Contents/MacOS/VBoxSVC-amd64
/Applications/VirtualBox.app/Contents/MacOS/VBoxXPCOMIPCD => /Applications/VirtualBox.app/Contents/MacOS/VBoxXPCOMIPCD-amd64
/Applications/VirtualBox.app/Contents/MacOS/VMMGC.gc => /Applications/VirtualBox.app/Contents/MacOS/VMMGC.gc-amd64
/Applications/VirtualBox.app/Contents/MacOS/VirtualBox => /Applications/VirtualBox.app/Contents/MacOS/VirtualBox-amd64
/Applications/VirtualBox.app/Contents/MacOS/VirtualBoxVM => /Applications/VirtualBox.app/Contents/MacOS/VirtualBoxVM-amd64
/Applications/VirtualBox.app/Contents/MacOS/vboxwebsrv => /Applications/VirtualBox.app/Contents/MacOS/vboxwebsrv-amd64
Error: VBoxDrv.kext is already loaded
Fatal error: VirtualBox
```
And `sudo /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart` fails with;
```
Unloading VBoxUSB.kext
Unloading VBoxNetFlt.kext
Unloading VBoxNetAdp.kext
Unloading VBoxDrv.kext
(kernel) Can't remove kext org.virtualbox.kext.VBoxDrv; services failed to terminate - 0xe00002c7.
Failed to unload org.virtualbox.kext.VBoxDrv - (iokit/common) unsupported function.
Error: Failed to unload VBoxDrv.kext
Fatal error: VirtualBox
```
I suppose reinstalling VirtualBox will probably work, but I'm trying to avoid that for now, since I'm on my mobile hotspot.

**Comment by cfperea** [comment]
I had the same issue when upgraded from Yosemite to El Capitan. Updated VirtualBox to 4.3.30 and the problem was resolved.

**Comment by imikay** [comment]
Same problem here when I upgraded to Yosemite to El Capitan, reinstalled both new versions of VirtualBox and Vagrant solved the problem.

**Comment by thiagoeliasr** [comment]
Had the same problem after updating to El Capitain. Just here to confirm that I reinstalled VirtualBox version 4.3.34 and the problem was solved. 😀

**Comment by coryschwartz** [comment]
This problem has to do with modules loaded in virtualbox. For those who have re-installed virtualbox, your distro/packaging system might have done this for you.  For correct operation, including the vbox networking, you have to have these:

$ lsmod | grep vbox
vboxpci                24576  0
vboxnetflt             28672  0
vboxnetadp             28672  0
vboxdrv               385024  3 vboxnetadp,vboxnetflt,vboxpci

**Comment by anonRegions** [comment]
I'm having the same problem noted above. As per coryschwartz, I ran this:

$ lsmod | grep vbox

yielding this:

vboxdrv               446786  0

So vboxnetadp,vboxnetflt & vboxpci are missing.

Please advise ASAP. I'm dead in the water.

**Comment by kkiernan** [comment]
Just updated to macOS Sierra and had this same problem. Updating to VirtualBox 5.1.14 fixed the issue for me.

**Comment by javasgl** [comment]
the same error meet up after update to macOS Sierra.

**Comment by snipebin** [comment]
Reinstalling VBox in El Captain fixed for me.

**Comment by austenpayan** [comment]
Updating to Vbox v5.1.26 fixed for me in macOS Sierra v10.12.6

**Comment by chaitanyakumar0** [comment]
**sudo /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh  restart** worked for me.
 Initially, it gave me a message that my system preferences blocked it when I executed the above command. I opened system preferences, privacy settings, and hit allow for oracle plugin and use same command, then it worked.

**Comment by JohnVonNeumann** [comment]
For those of you of the Linux persuasion:

sudo service virtualbox restart

**Comment by saltcod** [comment]
In High Sierra: 
I had to unblock this blocked kext execution attempt here: https://developer.apple.com/library/content/technotes/tn2459/_index.html

Then sudo /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart

Then I could vagrant up.

**Comment by pnoeric** [comment]
Just to echo @saltcod  - this appears to be the solution if you are running **Mac OS High Sierra.**

**Comment by fergalmonaghan** [comment]
Ditto, I am on Mac OS High Sierra and @saltcod 's note worked for me

**Comment by kunth** [comment]
Maybe a little different with saltcod's solution, on Mac High Sierra, I solved this by:
1. close the virtualbox
2. execute the 
```bash
sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart
```
and you would see the following
```bash
Unloading VBoxUSB.kext
Unloading VBoxNetFlt.kext
Unloading VBoxNetAdp.kext
Unloading VBoxDrv.kext
Loading VBoxDrv.kext
Loading VBoxUSB.kext
Loading VBoxNetFlt.kext
Loading VBoxNetAdp.kext
```
3. start the virtualbox, and it would turn out to be all right.

**Comment by smitjainsj** [comment]
This the same error in new release on Mojave !!

VirtualBox 5.2.18

**Comment by piyushkantm** [comment]
Another victim of Mojave update!! :(

**Comment by tohjg** [comment]
Another victom of Mojave update. Just reinstalled virtualbox via homebrew and it works.

`brew cask reinstall virtualbox`

**Comment by piyushkantm** [comment]
I also fixed it by updating the virtualbox and vagrant. I had installed it via package so downloaded the latest from their website.

```
Piyushs-MacBook-Pro:~ piyushkantm$ vboxmanage --version
5.2.18r124319

Piyushs-MacBook-Pro:~ piyushkantm$ vagrant --version
Vagrant 2.1.5

```



Additionally if you're using laravel, also update vagrant box to 6.3.0.


```
Piyushs-MacBook-Pro:~ piyushkantm$ vagrant global-status
id       name        provider   state    directory                           
-----------------------------------------------------------------------------
5d694e6  homestead-7 virtualbox poweroff /Users/piyushkantm/Homestead        




Piyushs-MacBook-Pro:~ piyushkantm$ vagrant box update 5d694e6

```

**Comment by akashnimare** [comment]
This should work on Mojave 
```sh
brew cask reinstall virtualbox
brew cask reinstall vagrant
vagrant plugin update
```

**Comment by mbiang** [comment]
`
brew cask reinstall virtualbox
brew cask reinstall vagrant
vagrant plugin update
`

This did the track after a Mojave upgrade - thanks @akashnimare

**Comment by sheriffderek** [comment]
I had ignored something about "oracle needing some security thing..." during some bash script installs.
: /   Turns out I shouldn't have!

A nice little post about it:
https://matthewpalmer.net/blog/2017/12/10/install-virtualbox-mac-high-sierra/index.html

RE: https://developer.apple.com/library/archive/technotes/tn2459/_index.html

**Comment by yoeridekker** [comment]
This worked for me: 
`sudo launchctl load /Library/LaunchDaemons/org.virtualbox.startup.plist`

**Comment by chantouchsek** [comment]
sudo launchctl load /Library/LaunchDaemons/org.virtualbox.startup.plist

this worked for me.

**Comment by galo4kin** [comment]
After run `sudo launchctl load /Library/LaunchDaemons/org.virtualbox.startup.plist` I have an error
 `/Library/LaunchDaemons/org.virtualbox.startup.plist: No such file or directory`

I find my `org.virtualbox.startup.plist` file on path
`/Library/Application\ Support/VirtualBox/LaunchDaemons/org.virtualbox.startup.plist`

**Comment by metju90** [comment]
This problem came up after upgrading my macOS to Mojave.  Virtual box 5.1 is not compatible with Mojave. Updating Virtual box solved my problem.

**Comment by pynner** [comment]
FIXED on OSX Mojave - I had downloaded VB from the Oracle website, I went to Security & Privacy, noticed at the bottom `Some system software was blocked from loading`, clicked Allow... and checked Oracle. Was forced to restart computer, and now it's working.

**Comment by reard3n** [comment]
On OSX 10.14.2 Mojave:
`sudo /Library/Application\ Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh restart`

Resolved this issue for me. So it seems like some of the VBox drivers (kernel modules) were not loaded based on which ones were unloaded during there restart process. They *were* loaded on restart:

> Unloading VBoxDrv.kext
> Loading VBoxDrv.kext
> Loading VBoxUSB.kext
> Loading VBoxNetFlt.kext
> Loading VBoxNetAdp.kext

Just in case anyone else runs into this. I suspect that a restart would have resolved it also since that would have reloaded modules.

**Comment by iamsidn** [comment]
> For those of you of the Linux persuasion:
> 
> sudo service virtualbox restart

When I try to run this command, I get the following error:

$ sudo service virtualbox restart
Failed to restart virtualbox.service: Unit virtualbox.service not found.

**Comment by johnpc** [comment]
This fixed the problem for me: https://github.com/Homebrew/homebrew-cask/issues/39369#issuecomment-339118861

After running that script and allowing the load from System Preferences I was then able to run 

```brew cask reinstall virtualbox
brew cask reinstall vagrant
vagrant plugin update
vagrant up
``` 

successfully.

**Comment by allen-munsch** [comment]
If anyone else finds themselves here and are running ubuntu 18.04 ( kernel 4.18.0-16-generic ), vagrant 2.2.4, and virtualbox5.x+

I had this issue occur after running `sudo apt upgrade`

remove virtualbox: `sudo apt autoremove virtualbox virtualbox-5.* virtualbox-4.*`
reinstall virtualbox: `sudo apt install virtualbox` ( 5.2.18_Ubuntu r123745 at the time of this post )
Download the latest vagrant debian ( was 2.2.4 at the time of this post ) and run an install/update from it: https://www.vagrantup.com/downloads.html

**Comment by shaunsmiley-xevo** [comment]
On ubuntu 18.04, completing removing and reinstalling was what finally fixed this for me.  I'm using virtualbox-6.0.
