### ISSUE TITLE
Forwarded ports not restored after creating Vagrant package

### ISSUE THREAD

**Issue by gw0** [hashicorp/vagrant#1676]
On Debian 7 (wheezy) using Vagrant 1.0.3-1 with Virtualbox 4.1.18-dfsg-2+deb7u1... After creating a new Virtualbox VM with NAT networking and having a few forwarded ports everything works fine until I try to create a Vagrant package from it, eg:

```
$ vagrant package --base test
[test] Clearing any previously set forwarded ports...
....
```

The Vagrant package created this way works as expected, but the forwarded ports settings get cleared from the original Virtualbox VM (as can be understood from the command output), but not restored afterwards!

Expected result: The original Virtualbox VM and his forwarded ports settings should NOT be affected if the user creates a Vagrant package or not.

**Comment by foobarbecue** [comment]
FWIW, at least in my 1.8.5 install of vagrant `vagrant package` does not mutate the original VM. I'd be surprised if it ever did that.
