### ISSUE TITLE
synced_folder does not work 

### ISSUE THREAD

**Issue by KAllan357** [hashicorp/vagrant#1688]
Using Vagrant 1.1.5. My OS is OS X 10.7.

Here is a snippet from my 

```
artifacts_dir = "C:/mounted-packages"
config.vm.synced_folder build_output_dir, artifacts_dir
```

Vagrant gives me a stack trace, I'll pull out the abbreviated bits:

```
ERROR vagrant: /Applications/Vagrant/embedded/gems/gems/vagrant-1.1.5/lib/vagrant/action/builtin/config_validate.rb:18:in `call'

vm:
* The shared folder guest path must be absolute: C:/mounted-packages
```

I think the problem might exist in master, as well as 1.1.5 --> the relevant code being called can be found here: https://github.com/mitchellh/vagrant/blob/master/plugins/kernel_v2/config/vm.rb#L320

I'm thinking that since I'm running on a Mac, the Pathname object being created for "C:/mounted-packages" is correctly reporting that it is not an absolute path. Unfortunately, this code is validating my Vagrantfile as if I were a Unix machine instead of as a Windows machine.

**Comment by mohanramanujam** [comment]
using ruby inside vagrant. in synced_folder command how can i use variable for guest folder location correctly. I am getting guest folder must be absolute path which y variable is. I have tried assign my array element to a variable and using the variable e.g. a= dirs[1] where latter conains guest folder read from csv file. The error message. The guest happens to be centos and the error is:
* The shared folder guest path must be absolute:  /usr/local/src
i have also used "#{dirs[1]", "#{a} but these did not work as well
