### ISSUE TITLE
SSH agent forwarding does not work with provisioner on Windows

### ISSUE THREAD

**Issue by mconigliaro** [hashicorp/vagrant#1735]
I'm trying to get `vagrant provision` to clone git repos on VMs using the SSH keys on my host machine. I have `ssh.forward_agent = true` in my Vagrantfile (#105), and my base box has the appropriate updates to `/etc/sudoers` to preserve `SSH_AUTH_SOCK` (#377, #1303). I can now prove that SSH agent forwarding is at least partially working. 

First I ensure that the ssh-agent is running with the appropriate keys loaded:

```
$ eval `ssh-agent`
$ ssh-add
$ ssh-add -l
```

Then I `vagrant ssh` to the box and try to authenticate to GitHub:

```
$ sudo ssh -T git@github.com -o StrictHostKeyChecking=no
Hi mconigliaro! You've successfully authenticated, but GitHub does not provide shell access.
```

I've verified that this works as expected on OSX, Linux, and Windows hosts. My assumption is that `vagrant provision` should work similarly, and it seems to on Linux and OSX, but not on Windows. I already ran into #1404 with PuTTY/Pageant, so I tried again with Cygwin's OpenSSH, but it still fails, and I'm not sure why. The provisioner I'm using for testing looks like this:

```
Vagrant::Config.run do |config|
  config.vm.provision :shell, :inline => "ssh -Tv git@github.com -o StrictHostKeyChecking=no"
end
```

If SSH agent forwarding worked with the provisioner, I should get the "You've successfully authenticated" message above.

And here's another interesting thing. When I run `VAGRANT_LOG=info vagrant provision`, I see that the provisioner is writing `/tmp/vagrant-shell` and running it with sudo (which fails). But if I `vagrant ssh` and run `sudo /tmp/vagrant-shell` manually, it works fine. This hints to me that `vagrant provision` and `vagrant ssh` are doing slightly different things SSH-wise, but I don't know what/why.

For what it's worth, here's the log of a successful authentication when I do a `vagrant ssh`:

```
$ sudo ssh -Tv git@github.com -o StrictHostKeyChecking=no
OpenSSH_5.3p1 Debian-3ubuntu7, OpenSSL 0.9.8k 25 Mar 2009
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Applying options for *
debug1: Connecting to github.com [204.232.175.90] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: identity file /root/.ssh/identity type -1
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.5p1 Debian-6+squeeze1+github12
debug1: match: OpenSSH_5.5p1 Debian-6+squeeze1+github12 pat OpenSSH*
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_5.3p1 Debian-3ubuntu7
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-md5 none
debug1: kex: client->server aes128-ctr hmac-md5 none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<1024<8192) sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /root/.ssh/known_hosts:1
debug1: ssh_rsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/Conigliaro Test/.ssh/id_rsa
debug1: Server accepts key: pkalg ssh-rsa blen 279
debug1: Authentication succeeded (publickey).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: Remote: Forced command: gerve mconigliaro 49:ef:54:41:ca:da:7e:17:dc:9e:ac:26:81:af:16:a8
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: Pty allocation disabled.
debug1: Remote: Forced command: gerve mconigliaro 49:ef:54:41:ca:da:7e:17:dc:9e:ac:26:81:af:16:a8
debug1: Remote: Port forwarding disabled.
debug1: Remote: X11 forwarding disabled.
debug1: Remote: Agent forwarding disabled.
debug1: Remote: Pty allocation disabled.
debug1: Sending environment.
debug1: Sending env LANG = en_US.utf8
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
Hi mconigliaro! You've successfully authenticated, but GitHub does not provide shell access.
debug1: channel 0: free: client-session, nchannels 1
Transferred: sent 2272, received 2984 bytes, in 0.5 seconds
Bytes per second: sent 4871.4, received 6397.9
debug1: Exit status 1
```

And here's the unsuccessful log from the provisioner:

```
OpenSSH_5.3p1 Debian-3ubuntu7, OpenSSL 0.9.8k 25 Mar 2009
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Applying options for *
debug1: Connecting to github.com [204.232.175.90] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: identity file /root/.ssh/identity type -1
debug1: identity file /root/.ssh/id_rsa type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: Remote protocol version 2.0, remote software version OpenSSH_5.5p1 Debian-6+squeeze1+github12
debug1: match: OpenSSH_5.5p1 Debian-6+squeeze1+github12 pat OpenSSH*
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_5.3p1 Debian-3ubuntu7
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-md5 none
debug1: kex: client->server aes128-ctr hmac-md5 none
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<1024<8192) sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_GROUP
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /root/.ssh/known_hosts:1
debug1: ssh_rsa_verify: signature correct
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
Error reading response length from authentication socket.
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /root/.ssh/identity
debug1: Trying private key: /root/.ssh/id_rsa
debug1: Trying private key: /root/.ssh/id_dsa
debug1: No more authentication methods to try.
Permission denied (publickey).
```

It looks like things start to go wrong after that "Error reading response length from authentication socket" line.

As far as I know, `SSH_AUTH_SOCK` is the only environment variable that really matters for this, but I've verified that it's defined and pointing to a file that actually exists. For what it's worth, here's my `vagrant ssh` environment:

```
TERM=xterm
LS_COLORS=rs=0:di=01;34:ln=01;36:hl=44;37:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
SSH_AUTH_SOCK=/tmp/ssh-uwjIr13848/agent.13848
MAIL=/var/mail/vagrant
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
LANG=en_US.utf8
HOME=/home/vagrant
SHELL=/bin/bash
LOGNAME=root
USER=root
USERNAME=root
SUDO_COMMAND=/usr/bin/env
SUDO_USER=vagrant
SUDO_UID=1000
SUDO_GID=1000
```

And here's my `vagrant provision` environment:

```
SHELL=/bin/bash
TERM=vt100
USER=root
SUDO_USER=vagrant
SUDO_UID=1000
SSH_AUTH_SOCK=/tmp/ssh-tlsae13632/agent.13632
USERNAME=root
MAIL=/var/mail/vagrant
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
_=/usr/bin/env
PWD=/home/vagrant
LANG=en_US.utf8
HOME=/root
SUDO_COMMAND=/bin/bash -l
SHLVL=2
LOGNAME=root
SUDO_GID=1000
```

**Comment by jeremyBass** [comment]
So just for point of reference, when you only have GitHub for windows loaded, and you are not planning on jumping though a lot of hoops to get `web.ssh.forward_agent = true` to work correctly, I found that only https://github.com/mitchellh/vagrant/issues/1735#issuecomment-25640783 was the right solution.  It's referenced many times out on other sites, including stackoverflow.

The issues are, I'm using a box I didn't create, which uses the highly suggest way of using keys to tunnel and more to the point the `vagrant.pub` key set for the root user that is used on many boxes out there when doing anything like `vmConfig.vm.provision :shell, :inline => "echo 'I would like to git clone now to a private repo but will not just out of the box'"`.  Out of the box I would expect  `web.ssh.forward_agent = true` to be all I needed, but this is what did the whole trick.  

```ruby
 config.ssh.forward_agent = true
if Vagrant::Util::Platform.windows?
	# You MUST have a ~/.ssh/github_rsa (GitHub specific) SSH key to copy to VM
	if File.exists?(File.join(Dir.home, ".ssh", "github_rsa"))
		# Read local machine's GitHub SSH Key (~/.ssh/github_rsa)
		github_ssh_key = File.read(File.join(Dir.home, ".ssh", "github_rsa"))
		# Copy it to VM as the /root/.ssh/id_rsa key
		config.vm.provision :shell, :inline => "echo 'Windows-specific: Copying local GitHub SSH Key to VM for provisioning...' && mkdir -p /root/.ssh && echo '#{github_ssh_key}' > /root/.ssh/id_rsa && chmod 600 /root/.ssh/id_rsa"
	end
end

#dev env so woo hoo
config.vm.provision :shell, :inline => "echo 'Defaults    env_keep+=SSH_AUTH_SOCK' >>  /etc/sudoers"

```
Now I can add something like 
```ruby

config.vm.provision :shell, :inline => "gitploy -q -b product-matrix pm git@github.com:jeremyBass/pleasurers-exts.git"

```
 And bam I have cloned in my private repo and all is right.  Note that I could have left out the 

```ruby

config.vm.provision :shell, :inline => "echo 'Defaults    env_keep+=SSH_AUTH_SOCK' >>  /etc/sudoers"

```

But see I need to `vagrant ssh` in and then `sudo -s` so I have to pass the agent on.  I hope this help someone out there that needs to clone in some private repo right our of the gate on provisioning.  I had to do a lot of testing to get it working just right, but I'm up and running now.  Happy coding ya'll.

**Comment by kouik** [comment]
Hi,

Thanks @ all for your instructions and help. That was a total headache !
Personnaly, im using a personnal gitlab server and had no option to connect without ssh keys.
I am using Varying Vagrant Vagrants, I was stuck on the host key verification asking for rsa fingerprint validation.

I tried with thoses tasks but it didn't work :
```sh
# add git.mydomain.com to the list of known_hosts
  config.vm.provision :shell do |shell|
    shell.inline = "ssh-keyscan -H $2 >> $1 && chmod 600 $1"
    shell.args = %q{/root/.ssh/known_hosts "git.mydomain.com"}
  end

  # add git.mydomain.com to the list of known_hosts
  config.vm.provision :shell do |shell|
    shell.inline = "echo -e 'Host $2\n\tStrictHostKeyChecking no\n' >> $1"
    shell.args = %q{/root/.ssh/config git.mydomain.com}
  end
```

So, instead of trying to add this in the VagrantFile, I've added this in my vvv-init.sh configuration for that site :
```sh
# Adding git.mydomain.com to know hosts.
ssh -o StrictHostKeyChecking=no -p PORT_NUMBER git@git.mydomain.com uptime
```

**Comment by kouik** [comment]
I may correct myself as my previous is not correctly working ^^

Here is the final solution that works for me :
- Using Windows + msysgit + VirtualBox + Pageant
- Created protected key and loaded trough pageant
- Saved the key to ~/.ssh/id_rsa.ppk
- Exported the key to openssh format in Putty, conversions menu, and named it id_rsa
- Created a shortcut to auto load pageant at windows startup
- Added user environment variable : `GIT_SSH` `C:\Users\username\Tools\PUTTY\plink.exe`
- Added this to `path` user environment variable : `;C:\Users\username\Tools\PUTTY\putty.exe`
- Locally created a `~/.ssh/config` config file with :
```
Host                    *
  ForwardAgent          yes
```
- Rebooted
- Updated my vagrant file :
```
  # Forward Agent
  #
  # Enable agent forwarding on vagrant ssh commands. This allows you to use ssh keys
  # on your host machine inside the guest. See the manual for `ssh-add`.

  config.ssh.forward_agent = true

  config.vm.provision :shell do |shell|
    shell.inline = "touch $1 && chmod 0440 $1 && echo $2 > $1"
    shell.args = %q{/etc/sudoers.d/root_ssh_agent "Defaults    env_keep += \"SSH_AUTH_SOCK\""}
  end

  # add git.mydomain.com to the list of known_hosts
  # where 1234 is my hidden ssh port
  config.vm.provision :shell do |shell|
    shell.inline = "echo \"> SSH: add $2 to the list of known_hosts\" && ssh-keyscan -p $3 -H $2 >> $1 && chmod 600 $1"
    shell.args = %q{/etc/ssh/ssh_known_hosts git.mydomain.com 1234}
  end

  # add github.com to the list of known_hosts
  config.vm.provision :shell do |shell|
    shell.inline = "echo \"> SSH: add $2 to the list of known_hosts\" && ssh-keyscan -p $3 -H $2 >> $1 && chmod 600 $1"
    shell.args = %q{/etc/ssh/ssh_known_hosts github.com 22}
  end

  # add bitbucket.com to the list of known_hosts
  config.vm.provision :shell do |shell|
    shell.inline = "echo \"> SSH: add $2 to the list of known_hosts\" && ssh-keyscan -p $3 -H $2 >> $1 && chmod 600 $1"
    shell.args = %q{/etc/ssh/ssh_known_hosts bitbucket.com 22}
  end

  # bypass rsa fingerprint approbation
  config.vm.provision :shell do |shell|
    shell.inline = "echo -e \"Host $2\n\tStrictHostKeyChecking no\n\" >> $1"
    shell.args = %q{/etc/ssh/config *}
  end
```
- Then i've completely destroyed and deleted my box for a `vagrant up --provision` and it finally worked on the first provisioning ...

fiou ...

**Comment by nebffa** [comment]
FYI if you are running a Windows *guest* VM, you can use a modification of [tdonohue's script](https://github.com/mitchellh/vagrant/issues/1735#issuecomment-25640783).

Here is the modification:

```ruby
if File.exists?(File.join(Dir.home, ".ssh", "id_rsa"))
      private_key = File.read(File.join(Dir.home, ".ssh", "id_rsa"))

      # copy the ssh key to the VM
      config.vm.provision "shell" do |s|
        s.args = '"%s"' % [private_key]
        s.path = "copy_ssh_key.ps1"
      end
  else
      # Else, throw a Vagrant Error. Cannot successfully startup on Windows without a GitHub SSH Key!
      raise Vagrant::Errors::VagrantError, "\n\nERROR: SSH Key not found at ~/.ssh/id_rsa\n\n"
  end
```

where the external Powershell script `copy_ssh_key.ps1` is:

```powershell
$path = "C:/users/vagrant/.ssh/id_rsa"
New-Item -Force -Type "File" -Path "$path"

# args[0] is the host's private key
Add-Content $path $args[0]
```

**Comment by bravo-kernel** [comment]
Come on Windows users, there's no need to upload your (github) private keys to your box. 

Here's a [fully functional Vagrantfile](https://github.com/alt3/cakebox/blob/dev/.cakebox/Vagrantfile.rb) for a box that fully supports Windows for both:

- self-generated ssh key pair for the authentication (login)
- ssh-agent forwarded Github private key for checking out private repos etc.

The docs explain the SSH Authentication and Forwarding. It can be done :)

**Comment by sschuberth** [comment]
So the current state of this seems to be that SSH agent forwarding on Windows during provisioning only works with Pageant, not with `ssh-agent` from Cygwin / MSYS due to net-ssh/net-ssh#192.

**Comment by bravo-kernel** [comment]
@sschuberth. SSH agent forwarding works on Windows during provisioning WITHOUT pageant 




So the current state of this seems to be that SSH agent forwarding on Windows during provisioning only works with Pageant, not with `ssh-agent` from Cygwin / MSYS due to net-ssh/net-ssh#192.

**Comment by bravo-kernel** [comment]
@sschuberth correct

**Comment by rihardsk** [comment]
Shouldn't this be reopened and remain open until https://github.com/net-ssh/net-ssh/issues/192 is resolved or another solution is found?

It was quite confusing to see all of the bugs related to ssh-agent forwarding being closed and yet not being able to get ssh-agent forwarding working on a Windows host. Can't see why @mitchellh closed this bug https://github.com/mitchellh/vagrant/issues/1735#event-57284089 just after reopening it https://github.com/mitchellh/vagrant/issues/1735#event-57284083.

**Comment by sschuberth** [comment]
I agree it's confusing why @mitchellh first reopened and then immediately closed the issue again. 

However, there's a solution that works quite well for me (and hasn't been mentioned before): On a Windows host, start by using only Pageant (not `ssh-agent`). This will ensure agent forwarding works with provisioning. To make agent forwarding also work with `vagrant ssh`, additionally use [ssh-pagent](https://github.com/cuviper/ssh-pageant). This will make OpenSSH as spawned by `vagrant ssh` use the identities from Pageant so that you do not have to deal with `ssh-agent` at all.

**Comment by sethvargo** [comment]
I think Mitchell just clicked the wrong button :smile: 

If you are continuing to have issues with this, please open a new issue. This issue is almost 2 years old and a lot has changed in Vagrant since. I think this may be a bug in the net-ssh library (which comes from Ruby). The next major release of Vagrant (1.8) will upgrade the Ruby version, so hopefully that will make this issue go away.
