### ISSUE TITLE
Port-forwarding collision when bringing up suspended instances

### ISSUE THREAD

**Issue by markjaquith** [hashicorp/vagrant#1740]
I'm still experiencing the #1472 issue when bringing up machines with saved state. The SSH forwarding ports collide and Vagrant bails. `vagrant reload` (or `vagrant halt && vagrant up`) gets it to detect and fix the port collision.

---

Environment:
- OS X 10.8.3
- Vagrant 1.2.2
- VirtualBox 4.2.12 r84980.

---

Reproduction:
1. Bring up A.
2. Suspend A.
3. Bring up B.
4. Attempt to bring up A.

---

Result:

> Vagrant cannot forward the specified ports on this VM, since they
> would collide with some other application that is already listening
> on these ports. The forwarded port to 2222 is already in use
> on the host machine.

---

Expected:

Vagrant notices the port collision and switches the port forwarding, allowing vm A to be brought up.

**Comment by beporter** [comment]
I'm not sure I understand why vagrant can't change the port forwards for a suspended VirtualBox machine if the `VBoxManage` commands that @rwstauner lists above work. (Contrary to @mitchellh's report on July 23, 2013 before closing this thread, that is.)

**Comment by jeremyltn** [comment]
Same issue on OSX. After you set the host port to something else in the Vagrantfile, it seems you need to run `vagrant reload` for it to take effect. Works for me now.
