### ISSUE TITLE
NFS mount error: v1.2.2

### ISSUE THREAD

**Issue by chakming** [hashicorp/vagrant#1744]
I've tried:
1. fix sudoers issue by setting: vagrant no password + Default !requiretty in VM
2. install nfs-common in VM
3. install virtual box guest addition (using vagrant-vbguest) in VM
4. ensure localMachine having installed nfsd
5. check /etc/exports and it shows correct settings

but the nfs issue still comes:

```
mount -o vers=3 192.168.62.1:'/Users/example/Documents/example/example.lamp/example.com' /var/www
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3 192.168.62.1:'/Users/example/Documents/example/example.lamp/example.com' /var/www
```

Environment:
OS X 10.8.3
vagrant 1.2.2
Virtualbox: 4.2.12 r84980

Vagrantfile + /etc/sudoers in guest  + /etc/exports in my mac + vagrant DEBUG log:
https://gist.github.com/chakming/0d955ee0ef698f1b2a48

**Comment by benjifisher** [comment]
@parfienczyk :  Your solution worked for me.  I halted all running VM's, ran "sudo ifconfig ... down" for all the vboxnet networks, and "vagrant up" worked.  Previously, I rebooted my host machine, as suggested by @sentience , but I did not like that solution.

**Comment by timhtheos** [comment]
Been to https://github.com/mikebell/drupaldev-nginx/issues/18 and here.  Yep, my host file has been jacked up. Fixing it up solves the problem. Thanks.

**Comment by leoj3n** [comment]
Note to self: Disable PF firewall (IceFloor.app)!

**Comment by jamime** [comment]
As this is a popular issue for nfs mounts, when receiving the error: `mount.nfs: requested NFS version or transport protocol is not supported`. It can also be caused by having duplicate network mounts within VirtualBox. For example if a machine has been destroyed incorrectly.

**Comment by tgroff** [comment]
Ubuntu 14.04, being from the land of Linux I don't often think of rebooting, but that's exactly what fixed it - NFS mount worked fine after rebooting! oy!

**Comment by ethier** [comment]
Tried everything here, but going back to:

    config.vm.network :private_network, type: :dhcp

From a static IP assignment:

    config.vm.network :private_network, ip: '172.16.231.130'

Is what did the trick for me.

**Comment by jasongabler** [comment]
Thank you @thgrendel !  I edit my hosts file many times a day while testing various deployments behind load balancers. It looks like at some point I fouled up the localhost entry from 127.0.0.1 to 27.0.0.1.  Fixed that and NFS came back for vagrant.

**Comment by mtoigo** [comment]
Can't believe it either, but fixing my /etc/hosts file on my mac fixed this for me too. I had temporarily pointed localhost to somewhere other than 127.0.0.1 and switch it back resolved this.

**Comment by setaloro** [comment]
My problem was, that IP adress was 192.168.100.1
The VM need the end "xxx.xxx.xxx.1"
Changed End IP to another and now works

**Comment by jeremy-bruns** [comment]
restarting my machine helped ...

**Comment by tonystar** [comment]
Confirming: switching localhost back to 127.0.0.1 in `/etc/hosts` resolved this.

**Comment by dadasoz-cuelogic** [comment]
Try -

VAGRANT_USE_VBOXFS=true vagrant up

**Comment by ducnguyenhuy** [comment]
Adding `private_network` IP into /ect/hosts worked for me. (Mac OSX + Vagrant box running below Ubuntu 14.04)

**Comment by dgpro** [comment]
Similar issue on Windows 7
`mount -o 'vers=3,udp,nolock' [removed]:'/C/<removed>' /var/www

Stderr from the command:
mount.nfs: access denied by server while mounting [removed]`

Fixed by... restarting PC...

**Comment by ronilaukkarinen** [comment]
Emptying /etc/exports fixed this for me, thanks @gnutix. It seems if you have multiple vagrant boxes, there can be conflicts.

**Comment by ianoshorty** [comment]
Just chipping in to say @gnutix and @ronilaukkarinen solution worked for me with Roots/Trellis.

**Comment by erikaheidi** [comment]
Confirming that this error happens also if you are working on an encrypted home directory on Ubuntu. I moved the project to outside the encrypted home and it worked just fine.

**Comment by n0impossible** [comment]
I have the same error when running vagrant up

`==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'actimeo=1' 192.168.2.1:'/Users/n0impossible/Documents/htdocs' /home/vagrant/htdocs

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported`

i checked my /etc/hosts file
`##
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
i127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost`

see? `i127.0.0.1	localhost`

my bad, typo when i edit this file using vi editor

i fixed my /etc/hosts file, do vagrant up and work fine.

--Cheers--

**Comment by bartmcleod** [comment]
Today, I finally realized I had to fix the hosts file on the **host** machine. Indeed, there was no entry `127.0.0.1 locahost` After I added it, nfs worked for me too, however, I am still a bit sceptical, since this error just comes and goes as it pleases.

**Comment by vrwired** [comment]
My issue resolved by changing IP to end in 3 and not 1. I'm not sure if was necessary to empty /etc/exports, but I did that first and then edited the Vagrantfile like so: `config.vm.network :private_network, ip: "10.11.12.3"` . `vagrant reload --provision` then brought mount up

**Comment by Beerusm** [comment]
Changing vagrant app directory from home to other directory solved the problem. thanks for the Tip!

**Comment by lightster** [comment]
Yet another possibility: If you use an encrypted sparsebundle on macOS as a mounted directory in your Vagrant VM, you may get permission denied errors when writing to the mounted directory (even with root/sudo). I switched to an unencrypted sparsebundle (since my drive is encrypted anyhow).

**Comment by tecnocat** [comment]
For Mac OS Sierra this solve my day! (Vagrant 1.9.1)

https://github.com/mitchellh/vagrant/issues/5424#issuecomment-284816293

**Comment by chadfurman** [comment]
I had a similar problem in Ubuntu, Vagrant version 1.9.3, VB version 5.1.22

The problem was that my host's OS has changed the `ifconfig` to the `ip` command, and `vboxnet0` did not have an ip address. 

I had to run:

`ip a add 192.168.33.1/255.255.255.0 dev vboxnet0` before Vagrant could start the NFS share

There were many other things I tried: starting/stopping the firewall (ufw, iptables, both, neither); adding specific rules to the firewall to allow all traffic to this IP; `service start` for each of nfs-common, nfs-kernel-server, nfs-server, nfs-client; and clearing out my /etc/exports

It wasn't until I made sure my vboxnet0 had an IP on the host machine that everything worked.

**Comment by therobyouknow** [comment]
Thank you to @gitis and @erikaheidi regarding moving it out of encrypted home folder - I also found that I was able to move beyond this issue once I did that.

 gitis commented on 4 Sep 2014
> I moved the project out of the encrypted home folder and it worked. Thank you, @wellingtonlorindo!

erikaheidi commented on 1 Apr 2016
> Confirming that this error happens also if you are working on an encrypted home directory on Ubuntu. I moved the project to outside  the encrypted home and it worked just fine.
