### ISSUE TITLE
Support CIFS (beside NFS)

### ISSUE THREAD

**Issue by thasmo** [hashicorp/vagrant#1749]
If I'm not totally wrong CIFS is similar to NFS. CIFS is supported on Windows better than NFS. Any idea if this can be implemented?

**Comment by odigity** [comment]
Looks like support was added, but only for Windows hosts:

https://docs.vagrantup.com/v2/synced-folders/smb.html

"Windows only! SMB is currently only supported when the host machine is Windows."
