### ISSUE TITLE
provision as different user than config.ssh.username

### ISSUE THREAD

**Issue by lexinator** [hashicorp/vagrant#1753]
My goal is to 'vagrant ssh' as my login name and mount my home directory over nfs.

nfs-kernel-server does not support uid mapping so /etc/passwd uid must match my home directory ids.  I cannot pre-populate a single vagrant box with all my colleague accounts, as the default uid for the first account on a mac is 501.

I would like to change "config.ssh.username" to my login but I cannot until after the new account is provisioned.

I think the best approach that I've come up with is to be able to provision as the "vagrant" user.

my current work around is in the provision step to modify ~vagrant/.bashrc to ssh mynewlogin@localhost.  It works but is not ideal.

**Comment by ldong** [comment]
@danielfrg Thanks.

`provision` is running **root** by default, this should be written in the doc more clearly.

**Comment by lexinator** [comment]
@ldong For most provisioning backends it defaults to using sudo however some(all?) can be disabled.  For example the shell provisioner has an option ```privileged``` to disable running as root.  https://docs.vagrantup.com/v2/provisioning/shell.html
