### ISSUE TITLE
Re-associate vagrant with vm

### ISSUE THREAD

**Issue by ReeceMarsland** [hashicorp/vagrant#1755]
Vagrant has lost it's association with the already made vm and I need to re-associate it somehow. I found this thread: http://stackoverflow.com/questions/9434313/how-do-i-associate-a-vagrant-project-directory-with-an-existing-virtualbox-vm but the trick described does not work for me. Changing the id files causes 'vagrant status' to report that the machine is yet to be created. I can't even get vagrant to re-associate with the uuid of the vm it just built once I've changed the id file to something different.

I think the issue was caused by running:
vagrant up
vagrant suspend
sudo vagrant up (this created a new box and caused the link to be lost)

I can't see a command or config file setting that would enable me to force the path to the vm.

Running Vagrant version 1.2.2
Thanks

**Comment by rominf** [comment]
@webconsult, thank you for howto. It worked for me. Just to add my two cents:
1. It causes to run provisioning one more time (for a dummy machine, or for the old one if you killed dummy machine before provisioning).
2. I skipped moving VM data and it worked just fine.

**Comment by goliney** [comment]
@mobmad , you saved my day!

**Comment by mdular** [comment]
+1

**Comment by robe01** [comment]
I had the same problem. I solved it by going back to an older version of my ".vagrant" folder by using Windows 8.1's 'FileHistory' programme. 

It seems that virtualbox deleted all of the files in ".vagrant\machines\default\virtualbox" for some reason, so when I went to 'vagrant up' again, new files were put in place for a new vagrant machine. Thank god I back-up my work.

**Comment by paulschreiber** [comment]
I hit this bug with VIP Quickstart. @mobmad's solution worked for me.
```
$ VBoxManage list vms|grep quickstart
"vip-quickstart_default_1431365185830_12124" {50feafd3-74cd-40b5-a170-3c976348de27}
$ echo -n "50feafd3-74cd-40b5-a170-3c976348de27" > .vagrant/machines/default/virtualbox/id
```

**Comment by catalyze** [comment]
I'm having some trouble finding my .vagrant file. I've checked the directory with vagrantfile in it. Any suggestions?

**Comment by jasonm23** [comment]
@catalyze it will be hidden by default, if on OSX or Linux you can do 

    ls -a

From a terminal/shell, to include hidden files.

**Comment by Umojivity1** [comment]
Thank y'all :+1:

**Comment by jpSimkins** [comment]
+1
Thanks @mobmad . Nice job :+1:

**Comment by catalyze** [comment]
@jasonm23 Bingo, that was it. Thanks!

**Comment by janzenz** [comment]
Question: Why does `vagrant` disassociate itself? I have ignored `.vagrant` in my `.gitignore` file. This happens randomly or when I do `git checkout`. `Vagrantfile` is part of my git.

**Comment by rlam3** [comment]
but why does global-status not see it?

**Comment by benlk** [comment]
If the key-based ssh authentication no longer works after following @mobmad's instructions, you can get in with the user:pass combo `vagrant:vagrant` (usually).

To regain key-based ssh authentication, follow these instructions: https://gist.github.com/benlk/d0cf2b3251e6c09758f36ccd14d6894e

**Comment by meitar** [comment]
> but why does the command vagrant global-status not see it? 

@rlam3 Vagrant's `global-status` uses a different index file, stored somewhere in `$HOME`. On a Mac OS X install, it will be in your `~/.vagrant.d/data/machine-index/index` file. This is a JSON file, with the individual `machines` keyed by Vagrant's UUID. The UUID here is different than the VM provider's UUID. You can find it in the specific Vagrant environment's hidden directory, something like `.vagrant/machines/default/virtualbox/index_uuid` (for a VirtualBox-backed VM).

**Comment by varun50** [comment]
@mobmad Great thanks. Was wondering what's going wrong and couldn't figure out the problem until I saw this. Another abnormal feature I observed is my `./vagrant/machines/dev/virtualbox/` was completely wiped off, luckily mine is a three node VM so I copied the config files from other node and changed the ID and it worked. Able to get my old vm back. Thanks a lot.

**Comment by krcrawford** [comment]
@mobmad and @benlk:

After copying the id back to the empty machine folder, you will find that the ssh access if non-existent.

The quicker fix for regaining your ssh access for <your-guest-machine-name> is:
```
cp .vagrant/machines/default/virtualbox/private_key .vagrant/machines/<your-guest-machine-name>/virtualbox
```

Of course, this only works in cases where there are no specialized private key additions.

**Comment by inoas** [comment]
For me the whole folder became empty in .vagrant/machines/default/virtualbox/

It became empty when OS X decided to kill processes on 5% battery and then I vagrant up'ed (while it probably shut down).

used VBoxManage list vms to pick up the uuid, copied all the files that where missing from some other box, adapted the uuid, vagrant status said ok, vagrant up worked again.
