### ISSUE TITLE
Provide 'IdentitiesOnly no' option for ssh config to get agent forwarding working

### ISSUE THREAD

**Issue by stattrak-dragonlore** [hashicorp/vagrant#1764]
Currently a user cannot set this option to no.

I run a vagrant box on a shared server and I don't want to put my ssh private key there.
So I want to use ssh agent to read my key. 

Below is working well:

```
ssh -p 2222 someuser@localhost
```

But `vagrant ssh` is not.

I find vagrant hardcodes `"IdentitiesOnly=yes"]` in the code. After changing this to no, I get 
`vagrant ssh` working.

Reference: http://www.benjaminoakes.com/2013/04/10/ssh-agent-forwarding-with-vagrant-aws/

**Comment by equick** [comment]
Hi, I also hit this issue and can get past it by running `vagrant ssh --plain -- -o User=ec2-user` but I don't understand why I need to do that when I have `override.ssh.username = "ec2-user"` and `override.ssh.private_key_path = "/home/quick/.ssh/id_dsa"` set up in my Vagrantfile?
