### ISSUE TITLE
/sbin/ifup eth1 2> /dev/null

### ISSUE THREAD

**Issue by 84564221** [hashicorp/vagrant#1777]
```
vagrant up node1
```

Error

```
[node1] Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup eth1 2> /dev/null
```

I've tried the following

```
vagrant ssh -c "sudo /sbin/ifup eth1 2> /dev/null"
Device eth1 does not seem to be present, delaying initialization.
```

**Comment by lattera** [comment]
I have a VirtualBox VM that is set up as a DHCP, DNS, and firewall that has an IP of 192.168.1.1. This VM serves Internet access to the rest of my VMs. Vagrant not allowing me to use a .1 address for that VM is really going to cause headaches going forward. Is there any way to force Vagrant to allow me to use 192.168.1.1?

**Comment by GabLeRoux** [comment]
I had a similar problem on a slow network, I commented `config.vm.network :public_network` from my `Vagrantfile` as I don't need that feature atm. In my case, I think my vm didn't close properly last time, anyway, if this can help someone.

Here's what I had before:

    vagrant up
    1
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Clearing any previously set forwarded ports...
    ==> default: Couldn't find Cheffile at ./Cheffile.
    ==> default: Clearing any previously set network interfaces...
    ==> default: Available bridged network interfaces:
    1) en1: Wi-Fi (AirPort)
    2) en0: Ethernet
    3) p2p0
    ==> default: When choosing an interface, it is usually the one that is
    ==> default: being used to connect to the internet.
        default: Which interface should the network bridge to? ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
        default: Adapter 2: hostonly
        default: Adapter 3: bridged
    ==> default: Forwarding ports...
        default: 3306 => 3333 (adapter 1)
        default: 22 => 2222 (adapter 1)
    ==> default: Running 'pre-boot' VM customizations...
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 127.0.0.1:2222
        default: SSH username: vagrant
        default: SSH auth method: private key
        default: Warning: Connection timeout. Retrying...
        default: Warning: Connection timeout. Retrying...
        default: Warning: Remote connection disconnect. Retrying...
        default: Warning: Remote connection disconnect. Retrying...
        default: Warning: Remote connection disconnect. Retrying...
        default: Warning: Remote connection disconnect. Retrying...
        default: Warning: Remote connection disconnect. Retrying...
        default: Warning: Remote connection disconnect. Retrying...


        default: Warning: Remote connection disconnect. Retrying...
        default: Warning: Remote connection disconnect. Retrying...
        default: Warning: Remote connection disconnect. Retrying...
    ==> default: Machine booted and ready!
    ==> default: Checking for guest additions in VM...
    ==> default: Setting hostname...
    ==> default: Configuring and enabling network interfaces...

     The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!

    ARPCHECK=no /sbin/ifup eth2 2> /dev/null

    Stdout from the command:


    Determining IP information for eth2...PING 10.0.2.1 (10.0.2.1) from 10.0.2.53 eth2: 56(84) bytes of data.

    --- 10.0.2.1 ping statistics ---
    4 packets transmitted, 0 received, +3 errors, 100% packet loss, time 3006ms
    pipe 3
     failed.


    Stderr from the command:

**Comment by nckrse** [comment]
I added a second network:
config.vm.network "private_network", ip: "192.168.33.10"

And got the same error but for some reason, it was because eth2 was the created interface and not eth1... Fixed with:
~ $ sudo sed -i 's/eth1/eth2/' /etc/sysconfig/network-scripts/ifcfg-eth1
~ $ sudo /sbin/ifup eth1
Determining if ip address 192.168.33.10 is already in use for device eth2...
~ $

**Comment by holms** [comment]
CentOS 7:
```
Deleting /etc/udev/rules.d/70-persistent-net.rule
vagrant reload box
```
Helped for current machine, but when bulding whole box, this doesn't help at all

**Comment by holms** [comment]
I've sold this like this: holms/vagrant-centos7-box#030375653a 
Also you need to set only second adapter ip, not the first one: `config.vm.network "private_network", ip: "10.1.1.5", :adapter => 2`

**Comment by svpernova09** [comment]
I gave up on this long ago, (not long after my previous comment) and I ran into this again tonight where CentOS 7 wasn't getting the private_network interface, wanted to mention that @holms comment of adding `, :adapter => 2` seems to have solved this for me. Thanks!

**Comment by iyoung** [comment]
Just running vagrant up, seeing the issue described above, I was able to resolve this by just running vagrant ssh, then removing /etc/udev/rules.d/70-persistent-net.rules, exiting, running vagrant halt; vagrant up and all was fine.

**Comment by rodolfovillaruz** [comment]
I uninstalled vagrant and virtualbox and reinstalled, there was no problem again.

**Comment by taylorotwell** [comment]
Getting this on bento/ubuntu-16-04 box. :(

**Comment by balous** [comment]
I am getting this error on ubutnu 16.04. I guess the cause is that ubuntu now uses different names for ethernet interfaces:

vagrant@base-ubuntu-xenial:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:63:c5:ab brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe63:c5ab/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 08:00:27:af:e3:8b brd ff:ff:ff:ff:ff:ff


vagrant@base-ubuntu-xenial:~$ dmesg | grep eth
[    1.317883] e1000 0000:00:03.0 eth0: (PCI:33MHz:32-bit) 08:00:27:63:c5:ab
[    1.317889] e1000 0000:00:03.0 eth0: Intel(R) PRO/1000 Network Connection
[    1.797896] e1000 0000:00:08.0 eth1: (PCI:33MHz:32-bit) 08:00:27:af:e3:8b
[    1.797900] e1000 0000:00:08.0 eth1: Intel(R) PRO/1000 Network Connection
[    1.799479] e1000 0000:00:03.0 enp0s3: renamed from eth0
[    1.815309] e1000 0000:00:08.0 enp0s8: renamed from eth1

**Comment by xwdeng** [comment]
I agree with balous and I have the same problem. what should I do next?

**Comment by HeathNaylor** [comment]
Getting this on `ubuntu/xenial64` when using private network.

**Comment by masonfox** [comment]
Was able to fix this with a complete uninstall of vagrant and adding the box again. Followed the uninstallation directions [here](https://www.vagrantup.com/docs/installation/uninstallation.html).

**Comment by dylanninin** [comment]
Thanks for @masonfox

**Comment by pgporada** [comment]
I have something similarly related in https://github.com/mitchellh/vagrant/issues/8373 on Centos7. I did the following
```
vagrant up # fails
vagrant ssh
sudo su -
mv /etc/sysconfig/network-scripts/ifcfg-enp0s3 /etc/sysconfig/network-scripts/OFF_ifcfg-enp0s3
exit
exit
vagrant reload
```

**Comment by crazytan** [comment]
@pgporada you are a hero!!!!!

**Comment by CeuxDruman** [comment]
**I fixed it!**

SO: Ubuntu 16.04.2
MV for vagrant: virtualbox

**I had vagrant installed via apt-get**, but it seems to be broken/downgraded/bugged.
My solution was to uninstall and **reinstall it from the official website package**:

1. Unsinstall vagrant
`sudo apt-get remove --purge vagrant`
2. Delete ".vagrant" directory from your MV (Don't need to delete it or change Vagrantfile)
`sudo rm -rf <your_mv_directory>/.vagrant/`
3. Install Vagrant package from the official website: https://www.vagrantup.com/downloads.html (In my case: https://releases.hashicorp.com/vagrant/2.0.0/vagrant_2.0.0_x86_64.deb?_ga=2.157298489.244283658.1505144298-1807825711.1505144298)
4. Run it!
`vagrant up`

**Comment by metamaker** [comment]
I use Mint 18.2 and apt version of vagrant was failing with same error. Installation of newer release from Vagrant's official website solved the problem (see explanation at https://askubuntu.com/questions/760871/network-settings-fail-for-ubuntu-xenial64-vagrant-box).
