### ISSUE TITLE
When I run vagrant up

### ISSUE THREAD

**Issue by qinfanpeng** [hashicorp/vagrant#1778]
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/home/qfp/.vagrant.d/boxes/precise32_with_ruby1.9.3/virtualbox/box.ovf"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /home/qfp/.vagrant.d/boxes/precise32_with_ruby1.9.3/virtualbox/box.ovf...
OK.
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Could not create the clone medium '/home/qfp/VirtualBox VMs/deployingrails_1369389985/box-disk1.vmdk'.
VBoxManage: error: VMDK: cannot write allocated data block in '/home/qfp/VirtualBox VMs/deployingrails_1369389985/box-disk1.vmdk' (VERR_DISK_FULL)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Appliance, interface IAppliance, callee 
Context: "ImportAppliance" at line 793 of file VBoxManageAppliance.cpp

**Comment by borpglass** [comment]
I'm getting this same error -- VERR_DISK_FULL -- but with an added twist on my stock ubuntu box. Running df -h shows this:

Filesystem      Size  Used Avail Use% Mounted on
/dev/sda5        77G   27G   47G  36% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
udev            973M   12K  973M   1% /dev
tmpfs           197M  1.1M  196M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            983M   84K  982M   1% /run/shm
none            100M   56K  100M   1% /run/user
/dev/sda1        69G   28G   42G  41% /media/data-desk-ubuntu/Default

(VMs appear to be stored in /home/data-desk-ubuntu/VirtualBox VMs )

Any ideas on where I could move that VMs folder to make Vagrant happy? It appears to already be in a place with 47G free (and only about 25G is required for the machine image I'm trying to run.)

I'd love to use ftdysa's helpful suggestion -- I just don't know where to relocate things. Any tips would be met with shouts of praise.

**Comment by borpglass** [comment]
For anyone following this thread in the future: I have moved this question to a new issue. 

https://github.com/mitchellh/vagrant/issues/5223
