### ISSUE TITLE
Is there Gemfile Equivalent for Vagrant Plugins?

### ISSUE THREAD

**Issue by tknerr** [hashicorp/vagrant#1789]
My `Vagrantfile`s start relying on more and more plugins, probably in a specific version each. How can I make sure that it loads the correct plugins in the correct version?

My first thought was that there must be something like a `Gemfile` equivalent for Vagrant plugins, but I couldn't find it in the docs. Is there?

**Comment by guilhem** [comment]
@mitchellh as many Vagrantfile options are specific to a plugin, and many time to a specific version of a plugin, it will be really good to being able to have something like "Gemfile" for Vagrant.

For the moment, to being able to share our project between developers, we have to put command lines in documentation...

**Comment by modius** [comment]
Vagrant 1.5+ offers Bundler support via a Gemfile: https://www.vagrantup.com/blog/vagrant-1-5-plugin-improvements.html#toc_1

**Comment by tknerr** [comment]
...but that's only used for plugin development, it will not help for
installing plugins into a "productive" vagrant environment :-/
Am 24.02.2015 06:09 schrieb "Geoff Bowers" <notifications@github.com>:

**Comment by aholtventuretech** [comment]
looking for this exact support.  currently, am working on creating a cohesive development environment solution for us, and am running into a plugin requirement that I would rather have automatically installed when "vagrant up" is called, rather than having it be an extra command.

looked at bindler, but it seems it is no longer supported.  

I am echoing the above comment in that the gemfile support does not work for anything other than plugin development.

**Comment by cwc** [comment]
:+1:

**Comment by ut-adamc** [comment]
+1. Sometimes particular vagrantfiles need a gem and you really don't want to install it globally, even for Vagrant.

**Comment by tnguyen14** [comment]
Running into this question as well. +1 on opening this issue.

**Comment by darkn3rd** [comment]
Highly interested, this would make it simple to install plug-ins for the project.  As a suggestion, there this could be part of the **Vagrantfile**, maybe have a plug-in preprocessor something like this:

```ruby
plugin 'vagrant-aws', '>=0.7.0'
plugin 'vagrant-berkshelf', '>=4.0.3'
```

This would install such plug-ins if they did not exist already.  There could also be a `Pluginfile` as well to install these outside of a `vagrant up`.  You could then just do a `vagrant plugin install` without listing any particular plugin, and it will search $PWD for `Pluginfile`, and install the plugins from that file.
