### ISSUE TITLE
Very slow network connection

### ISSUE THREAD

**Issue by julesbl** [hashicorp/vagrant#1807]
Hi

Been using a vagrant 2 installation of ubuntu 12.04 on a Linuxmint host.

Getting very slow internet connection on all connections.

Vagrant file has this

Vagrant.configure("2") do |config|
  # This Vagrantfile is auto-generated by `vagrant package` to contain
  # the MAC address of the box. Custom configuration should be placed in
  # the actual `Vagrantfile` in this box.
  config.vm.base_mac = "080027129698"
  config.vm.network :public_network
  config.vm.synced_folder "/home/julianb/MyDocuments/WebSites/JamesGrey/ContentCapsule/working", "/var/ContentCapsule"
  config.vm.network :forwarded_port, guest: 80, host: 8080
end

When I look at the config using virtualbox admin there are two adapters configured, a NAT with the ports forwarded and a bridge without any ports forwarded. which is, presumably why the problems are occurring.

Anybody got any ideas how to fix this?

Jules

**Comment by Thinkscape** [comment]
Test case: a wget of an url from a public cdn:
1. Run on guest machine (debian jessie) = crawl at ~30kB/s
2. Run on host machine = around 27MB/s. 

I was able to fix it (for the most part) using this: http://superuser.com/a/850389/174755

**Comment by wweiradio** [comment]
it works thanks

**Comment by ianregister** [comment]
I had success with the `localhost:3000` responding-painfully-slow issue using Vagrant. On OS X I changed my hostname from `local` to `vm` (or whatever you want) and then both VirtualBox and Fusion started responding in under 200ms down from 5000ms.
