### ISSUE TITLE
Vagrant up: There was an error while executing `VBoxManage`, a CLI used by Vagrant

### ISSUE THREAD

**Issue by starrychloe** [hashicorp/vagrant#1809]
```
$ /cygdrive/c/Program\ Files/Oracle/VirtualBox/VBoxManage.exe list vms
"AIDC_1367972500" {16d4bcdc-a907-42eb-962f-faef2c68f13c}
"Ubuntu Box" {83f7549d-0ef3-453c-a014-77732d7ba775}


$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Setting the name of the VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "16d4bcdc-a907-42eb-962f-faef2c68f13c", "--name", "AIDC_1370628358"]

Stderr: VBoxManage.exe: error: Could not rename the directory 'C:\Users\Chloe\VirtualBox VMs\AIDC_1367972500' to 'C:\Users\Chloe\VirtualBox VMs\AIDC_1370628358' to save the settings file (VERR_ACCESS_DENIED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 2527 of file VBoxManageModifyVM.cpp

```

However, I am able to start the VM directly from Oracle VirtualBox manager GUI, and I am able to log in with root/vagrant.

**Comment by LadyDascalie** [comment]
I have this same issue on Ubuntu.
The only way I've found to be able to access the VM without having to `destroy` it was to do the following:

in my vagrant file, I was using the following
```ruby
config.vm.provider :virtualbox do |v|
v.customize ["modifyvm", :id, "--name", "nameofmyvm"]
end
```

Commenting the `v.customize ["modifyvm", :id, "--name", "nameofmyvm"]` is what allowed me to boot the machine.

This is in no way a fix however, just a band-aid.

**Comment by cannect** [comment]
Had the same error. I fixed it by resetting the default VM location in Virtual Box. 

Just open the Virtual Box GUI and go to settings.

**Comment by perfecto25** [comment]
hi all, I ran into this error when trying to 'vagrant up' a win2012 box that I built on VBox. 
Running vagrant 1.7.2 (latest as of 6/25/2015) running on ubuntu 14.04
--------------------------------------------------------------------------------------------------
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "47a2582f-a1e2-49b7-bff8-ebd0a71d9149", "--nic2", "none", "--nic3", "none", "--nic4", "none", "--nic5", "none", "--nic6", "none", "--nic7", "none", "--nic8", "none"]

Stderr: VBoxManage: error: Runtime error opening '/home/mreider/VirtualBox VMs/win2012_default_1435261495327_14037/win2012_default_1435261495327_14037.vbox-tmp' for reading: -102(File not found.).
VBoxManage: error: /build/buildd/virtualbox-4.3.10-dfsg/src/VBox/Main/src-server/MachineImpl.cpp[10362] (nsresult Machine::saveSettings(bool*, int))
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "SaveSettings()" at line 2716 of file VBoxManageModifyVM.cpp

My resolution was to delete the .box file, rerunning "vagrant package --base xxx --output xxxx.box" and "vagrant box add"

**Comment by nilyang** [comment]
my option is restart the vm ,don't kown the reason why ,but it works.
when I stop vagrant use `vagrant halt` and later run `vagrant up` ,the error occured!
I sove this problem by:

1.start from virtualbox when the error occurs
2.vagrant up

**Comment by XedinUnknown** [comment]
+1 for powering off with VBox. This fixed it for me.

**Comment by bahrmichael** [comment]
I had a similar issue with a namend instance. Removing the name fixed it for me.

       vb.customize ["modifyvm", :id,
                "--name", "oracle",
                "--memory", "512",
                "--natdnshostresolver1", "on"]

Change to 

       vb.customize ["modifyvm", :id,
                "--memory", "512",
                "--natdnshostresolver1", "on"]

**Comment by Souliloquy** [comment]
I had this issue and couldn't see the ghost VM until I typed "virtualbox restart" in the CLI, this made it visible in the VirtualBox app so I could delete it. Running on Mac Mountain Lion 10.8.5

**Comment by bp323** [comment]
Had this issue on windows after choosing to ignore all warnings that a VB process is still running. Uninstalling and reinstalling fixed the issue without any more problems.

**Comment by andreibenhur** [comment]
Solved this issue just upgrading virtualbox from 4 to 5.

**Comment by St33lMagnolia** [comment]
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'scotch/box' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "dc937c6c-6b0c-45f1-98bc-5d7b0cbfef84", "--type", "headless                     "]

Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (V                     ERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,                      interface IConsole





I am having this issue with vagrant up on windows 7
Vagrant 1.8.1
VirtualBox-5.0.20-106931-Win

Please , I need help. I am a newbie

**Comment by rrzaripov** [comment]
@St33lMagnolia, in your case this is not Vagrant issue. VirtualBox reports that in your hardware disabled VT-x. More about how check availability and possibly enable VT-x you can see [here](https://www.grc.com/securable.htm).

**Comment by tusar-nill** [comment]
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'laravel/homestead'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'laravel/homestead' is up to date...
==> default: Setting the name of the VM: homestead-7
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "3edf52a7-f514-4d17-a014-d07afa80047f", "--nic2", "none", "--nic3", "none", "--nic4", "none", "--nic5", "none", "--nic6", "none", "--nic7", "none", "--nic8", "none", "--nic9", "none", "--nic10", "none", "--nic11", "none", "--nic12", "none", "--nic13", "none", "--nic14", "none", "--nic15", "none", "--nic16", "none", "--nic17", "none", "--nic18", "none", "--nic19", "none", "--nic20", "none", "--nic21", "none", "--nic22", "none", "--nic23", "none", "--nic24", "none", "--nic25", "none", "--nic26", "none", "--nic27", "none", "--nic28", "none", "--nic29", "none", "--nic30", "none", "--nic31", "none", "--nic32", "none", "--nic33", "none", "--nic34", "none", "--nic35", "none", "--nic36", "none"]

Stderr: VBoxManage.exe: error: Invalid NIC number 9
VBoxManage.exe: error: Invalid NIC number 10
VBoxManage.exe: error: Invalid NIC number 11
VBoxManage.exe: error: Invalid NIC number 12
VBoxManage.exe: error: Invalid NIC number 13
VBoxManage.exe: error: Invalid NIC number 14
VBoxManage.exe: error: Invalid NIC number 15
VBoxManage.exe: error: Invalid NIC number 16
VBoxManage.exe: error: Invalid NIC number 17
VBoxManage.exe: error: Invalid NIC number 18
VBoxManage.exe: error: Invalid NIC number 19
VBoxManage.exe: error: Invalid NIC number 20
VBoxManage.exe: error: Invalid NIC number 21
VBoxManage.exe: error: Invalid NIC number 22
VBoxManage.exe: error: Invalid NIC number 23
VBoxManage.exe: error: Invalid NIC number 24
VBoxManage.exe: error: Invalid NIC number 25
VBoxManage.exe: error: Invalid NIC number 26
VBoxManage.exe: error: Invalid NIC number 27
VBoxManage.exe: error: Invalid NIC number 28
VBoxManage.exe: error: Invalid NIC number 29
VBoxManage.exe: error: Invalid NIC number 30
VBoxManage.exe: error: Invalid NIC number 31
VBoxManage.exe: error: Invalid NIC number 32
VBoxManage.exe: error: Invalid NIC number 33
VBoxManage.exe: error: Invalid NIC number 34
VBoxManage.exe: error: Invalid NIC number 35
VBoxManage.exe: error: Invalid NIC number 36

How to fix vagrant up problem?
I'm using 
*windows 10 64bit
*virtualbox 5.0.21.7994-win
*vagrant 1.8.3
Please, I need help. I'm a newbie.

**Comment by yethee** [comment]
@tusar-nill you can look at [this workaround](https://github.com/mitchellh/vagrant/issues/7417#issuecomment-225316022).

**Comment by larskendall** [comment]
I was only able to fix this by running the following: 

`sudo VBoxManage list vms`
Then for each vm listed: 
`sudo VBoxManage unregistervm <vmname> --delete`

**Comment by tusar-nill** [comment]
@larskendall 
Hey, I'm using windows 10 OS. So, Does sudo command works for windows?

**Comment by larskendall** [comment]
@tusar-nill I think in Windows you can right click on the CMD executable and run it as administrator. Then you can run those commands without the `sudo` and they should hopefully work. If that doesn't work, then maybe `runas` would help. Here's a thread about that particular issue that might help:

http://superuser.com/questions/42537/is-there-any-sudo-command-for-windows

**Comment by s2925534** [comment]
I found a hot fix in my case. I just change the Virtual Box VMs path in the configuration. It was somehow setup to my old username but after I've changed its working nicely.
See pics.
![vb vm error](https://cloud.githubusercontent.com/assets/7779985/16115833/dcb0b35a-340c-11e6-9631-f76f7787b156.png)

**Comment by magedmakled** [comment]
Was getting that error but `vagrant reload` seems to fix it. I'm on `mac El Capitan`, `Vagrant 1.8.4` and `VB 5.0.24`

**Comment by mrreubenjones** [comment]
Thanks s2925534, that solved my problem. Was pulling my hair out for a few minutes there. :)

**Comment by aprilpur** [comment]
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "0bc57779-876b-4756-8253-5990e9447e38", "--type", "headless"]

Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

I am using windows 10 and I was enable virtualization but it's not work.
help me please :sob:

**Comment by Mohamed-Saleem** [comment]
@borantula fix worked for me on OpenSuse Tumbleweed, Thanks.

**Comment by shrmrf** [comment]
In my case, this is how I encountered the problem:-

I was using `hyper-V` with Visual Studio and then forgot to turn it off before starting the `vagrant up` command. This showed a BSOD (blue screen...) and restarted the computer. I turned off `hyper-V` and tried to run `vagrant up` in the same folder as before... Got an error that the index had been corrupted. I went on to delete the index file (pointed to by the error message).

I did `vagrant up` again and got the dreaded 
```
`There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"]

Stderr:

```

Then I went ahead and deleted the `.vagrant` directory in the same folder and that, folks, fixed it for me!!

I hope someone benefits!!

**Comment by weidongliangadelaide** [comment]
Dear all, 
I am a newer in vagrant and virtual box. As i run vagrant up, i got a problem as below: 
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\a1639371>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "e17b2f74-98c6-45f0-8441-f2fdd326978a", "--type", "headless
"]

Stderr: VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (V
ERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,
 interface IConsole

C:\Users\a1639371>



It seems like there is a problem from VBoxManage. Can you please help? 

Thank you so much for your time 


Regards
Weidong

**Comment by caseyfw** [comment]
@weidongliangadelaide this is NOT the place to ask this question because it is completely unrelated to this issue. It looks like the issue you are having is that your computer's processor either does not support VT-x, or it is disabled in BIOS. Try [googling your actual issue](https://www.google.com.au/#q=enable+vt-x+in+bios).

**Comment by aphofstede** [comment]
I had to set `hostname: ''` in my puphpet `config.yaml` to get around this

**Comment by GeeWee** [comment]
What @shrmrf did also worked for me.

**Comment by vmorate** [comment]
Just removing the .vagrant folder worked for me too, thanks

**Comment by dkw789** [comment]
reinstalling a newer version of virtualbox fixes it too.

https://www.virtualbox.org/wiki/Downloads

**Comment by williamgomes** [comment]
I got the same error. Below was the error message:

```
A customization command failed:

["modifyvm", :id, "--name", "dev.vagrant.local"]

The following error was experienced:

#<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "d1050ee5-6c69-45a9-9842-647c0919db44", "--name", "dev.vagrant.local"]

Stderr: VBoxManage: error: Could not rename the directory '/var/root/VirtualBox VMs/medidatevagrantlocal_medidatevagrantlocal_1485168669703_99607' to '/var/root/VirtualBox VMs/dev.vagrant.local' to save the settings file (VERR_ALREADY_EXISTS)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "SaveSettings()" at line 3052 of file VBoxManageModifyVM.cpp
>

Please fix this customization and try again.
```

From the error message, it seems kinda clear to me about the error message. I focused on the below line:

`Stderr: VBoxManage: error: Could not rename the directory '/var/root/VirtualBox VMs/medidatevagrantlocal_medidatevagrantlocal_1485168669703_99607' to '/var/root/VirtualBox VMs/dev.vagrant.local' to save the settings file (VERR_ALREADY_EXISTS)`

It seems like somehow the **hostname** of my newly created machine got conflicted with one of my old machine's **hostname**. Thats why it couldn't create the settings file as it already exists from my old machine. Even destroying that existing machine won't solve the problem. So what i did was, gave a new **hostname** for my new vagrant box and it worked perfectly. :)

**Comment by TheoJL** [comment]
```Stderr: VBoxManage: error: Could not rename the directory '/Users/theo/VirtualBox VMs/airship_machine1_1485426682714_97042' to '/Users/theo/VirtualBox VMs/airship.puphpet' to save the settings file (VERR_ALREADY_EXISTS)```

In my case I just deleted the folder ```/Users/theo/VirtualBox VMs/airship.puphpet```. After typing ```vagrant up``` vagrant added it back, but this time without the error message.

**Comment by williamgomes** [comment]
@TheoJL does your time out message looks like below:

```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

If so, first try to restarting your VirtualBox application. If that doesn't help either, try to restart your whole pc/laptop. This will definitely solve the problem.

**Comment by williamgomes** [comment]
@TheoJL yes thats also helpful. But, as mine got conflicted with an existing one, i had to rename the hostname. :)

**Comment by zzzanderw** [comment]
I'm getting a VBoxManage error `VERR_PATH_NOT_FOUND`:
```
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: MagicDB_default_1486432349616_2036
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 3306 (guest) => 3306 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "cf80d5a9-a152-4e1b-b1bd-7009705e960d", "--type", "headless"]

Stderr: VBoxManage.exe: error: Path not found. (VERR_PATH_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Process finished with exit code 1
```
Any ideas as to what the issue may be?

**Comment by uchagani** [comment]
Make sure VBoxManage.exe is on your path.

**Comment by zzzanderw** [comment]
@uchagani It is.
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Zander Work>vboxmanage
Oracle VM VirtualBox Command Line Management Interface Version 5.1.4
(C) 2005-2016 Oracle Corporation
All rights reserved.

Usage:

  VBoxManage [<general option>] <command>


General Options:

  [-v|--version]            print version number and exit
  [-q|--nologo]             suppress the logo
  [--settingspw <pw>]       provide the settings password
  [--settingspwfile <file>] provide a file containing the settings password
```...

**Comment by erikseulean** [comment]
For windows users, run the git bash or the terminal that you're using with admin rights.

**Comment by Adongojustice** [comment]
**SOLVED! ON WINDOWS**

first of all destroy the virtual box with _vagrant destroy_

navigate to `C:\Users\Justice` replace justice by username
delete the _.vagrant.d_ folder
go into _VirtualBox VMs_ folder and delete everything inside it.
execute  _vagrant up_

it should work fine

**Comment by amol-c** [comment]
had to reinstall virtualbox.

**Comment by rkarthik63** [comment]
I was missing libcurl3 package. Installed libcurl3 and re-installed virtual box to fix the issue

**Comment by portal7** [comment]
I solved killing process "VBoxHeadless"  in Task Manager (Windows 10), running "vagrant up" and works like a charm!!

**Comment by mualle** [comment]
Check that the VM is not running on VirtualBox Manager.

**Comment by helturkey** [comment]
@Adongojustice thank u very much, your response solved my problem.

**Comment by rasheedsaidi** [comment]
I had the same issue of "There was an error while executing `VBoxManage`, a CLI used by Vagrant ..." on my Windows 10 machine. I got that fixed by running the CLI window as an 'administrator' and running vagrant up again.

**Comment by lambasahil** [comment]
Can anyone help?
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8080 (guest) => 8001 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "320c29c0-32f1-4134-9f39-1340f5aebaac", "--type", "headless
"]

Stderr: VBoxManage.exe: error: The virtual machine 'Catalogue_default_1506252938
237_96481' has terminated unexpectedly during startup with exit code 1 (0x1).  M
ore details may be available in 'C:\Users\sahil\VirtualBox VMs\Catalogue_default
_1506252938237_96481\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap,
 interface IMachine
```

**Comment by rafaelrozon** [comment]
@lambasahil I had the same problem. I fixed it by updating Virtualbox to 5.2.4.

**Comment by ito2307** [comment]
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/home/eduardoh/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-xenial64/20180213.2.0/virtualbox/box.ovf", "--vsys", "0", "--vmname", "ubuntu-xenial-16.04-cloudimg-20180213_1518618539483_25179", "--vsys", "0", "--unit", "10", "--disk", "/home/eduardoh/VirtualBox VMs/ubuntu-xenial-16.04-cloudimg-20180213_1518618539483_25179/ubuntu-xenial-16.04-cloudimg.vmdk", "--vsys", "0", "--unit", "11", "--disk", "/home/eduardoh/VirtualBox VMs/ubuntu-xenial-16.04-cloudimg-20180213_1518618539483_25179/ubuntu-xenial-16.04-cloudimg-configdrive.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /home/eduardoh/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-xenial64/20180213.2.0/virtualbox/box.ovf...
OK.
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not create the imported medium '/home/eduardoh/VirtualBox VMs/ubuntu-xenial-16.04-cloudimg-20180213_1518618539483_25179/ubuntu-xenial-16.04-cloudimg.vmdk' (VERR_VD_VMDK_INVALID_FORMAT)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 886 of file VBoxManageAppliance.cpp


i got this error

**Comment by tgaertner** [comment]
Make sure you have installed the VirtualBox-ExtensionPack
Debian/Ubuntu: sudo apt-get install virtualbox-ext-pack

**Comment by tgaertner** [comment]
Make sure you have installed the VirtualBox-ExtensionPack
Debian/Ubuntu: sudo apt-get install virtualbox-ext-pack

**Comment by eleijonmarck** [comment]
Vagrant Reload fixed the issue `vagrant reload`

**Comment by samomar** [comment]
This thread is gold, **I don't know what exactly worked for me but this thread along side this link helped** https://stackoverflow.com/questions/50053255/virtualbox-raw-mode-is-unavailable-courtesy-of-hyper-v-windows-10

**Comment by dinbrca** [comment]
Had it on Mac after updating to Mac OS Mojave with following error:
```
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp
```

After a couple of minutes I tried loading VirtualBox directly instead of using Vagrant throught the CLI - I got the following message:
<img width="446" alt="screen shot 2018-10-02 at 10 00 01 am" src="https://user-images.githubusercontent.com/2164032/46333753-367eb600-c62a-11e8-83cb-3220d5cef2b7.png">

turns out I just needed to update the VirtualBox.

**Comment by xlcrr** [comment]
Restarting laptop worked for me

**Comment by Elite40** [comment]
You have to check if you've the newest version of Virtualbox, because the version might not be compatible with the new Mac OS Mojave. As @dinbrca suggested above, i updated the virtualbox and it worked again!!

**Comment by thanhbkhn** [comment]
Use 
`vagrant reload`

to solve it

**Comment by dvetal** [comment]
vagrant reload did not work for me.  When I  updated to mohave i had to basically download the latest vagrant and the latest VirtualBox. Then it worked.

**Comment by Xerotherm1c** [comment]
I too received this error, but it was not because of permissions like I had presumed. I'm using vagrant box with Laravel and I attempted to create a new symbolic link for storage using the artisan command. But that command failed, and upon Googling I found that you need to have administrative permissions when launching vagrant to be able to create symbolic links. No sweat, so I closed Git CMD and reopened it as an administrator. I then ran `vagrant halt` followed by `vagrant up`, but I didn't realize that the halt didn't actually shut down the vagrant box because the elevated instance seems to not be able to talk to the vagrant box that the non-elevated instance spawned? Not entirely sure, but once I halted the box from non-admin and restarted the vagrant box inside the elevated instance, my problem was solved and everything is back to normal. Hopefully this helps someone.

**Comment by ne018** [comment]
remove saved state on your vbox using:
vagrant halt

then vagrant up again.

**Comment by AFKD98** [comment]
I am facing the same issue on Ubuntu 16.04. I tried everything above. I am using latest versions.
virtualbox version 6.0.8
vagrant version 2.2.5
I think I need to downgrade my versions ?
Help ??

**Comment by jakelacey2012** [comment]
I also had this error because "Oracle America, inc", was blocked from installing software on my mac. This can be fixed by following this https://matthewpalmer.net/blog/2017/12/10/install-virtualbox-mac-high-sierra/index.html

**Comment by 0e318236-1680-41a8-a989-3c9227637cdf** [comment]
My VirtualBox VMs folder was missing. Adding it fixed.

**Comment by srikanta72** [comment]
I found the solution at below link: 
1. Grant permission to VirtualBox under System Preferences > Security & Privacy > General (this request is new to macOS High Sierra)
2. Open Terminal and run: sudo "/Library/Application Support/VirtualBox/LaunchDaemons/VirtualBoxStartup.sh" restart
Like the guy who answered in below link: 
https://stackoverflow.com/questions/18149546/vagrant-up-failed-dev-vboxnetctl-no-such-file-or-directory

**Comment by prbhr007** [comment]
> I was able to get around this error by going into virtual box preferences and changing the vm directory to c:\1\vagrant\vm

same solution works for OSX as well.

**Comment by sengfai** [comment]
Go to virtualbox and remove and delete it manually, then run "vagrant up again".

**Comment by jggj21** [comment]
I opened Virtual Box and when I started the machine from there I showed an error that I had virtualization disabled in the BIOS, I enabled the option from the bios and vagrant up it worked again.
