### ISSUE TITLE
Vagrant up renames virtual machine directory

### ISSUE THREAD

**Issue by clebio** [hashicorp/vagrant#1817]
In Windows (8 64-bit), using 'vagrant up' sometimes causes the VirtualBox VM to get renamed, including the directory the VM resides in. This is different from the normal behavior of VirtualBox GUI and VBoxManage.

Steps to reproduce:
`vagrant init`
`vagrant up`
`vagrant halt`

Open Windows file explorer and identify the folder for this vagrant box (the VirtualBox VM). From VirtualBox GUI, you can right-click the instance and select 'Show in Explorer').

Using the following, identify the correct `vm_id` for the current vagrant box:
`"\Program Files\Oracle\VirtualBox\VBoxManage.exe" list vms`

Use VBoxManage to control the vagrant box:
`\Program Files\Oracle\VirtualBox\VBoxManage.exe" startvm <vm_id>`
`\Program Files\Oracle\VirtualBox\VBoxManage.exe" controlvm <vm_id> poweroff`

At this point, the VM _has not changed names_, nor has the VM folder name changed.

`vagrant up`
This will either issue an error (for instance, if File Explorer has the folder open):
_There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
Command: ["modifyvm", "d471d855-b779-4f9f-8efd-3d6e5a829fa5", "--name", "<vm_id>"]
Stderr: VBoxManage.exe: error: Could not rename the directory 'C:\Users\user\VirtualBox VMs<vm_id>' to 'C:\Users\user\VirtualBox VMs<vm_id>' to save the settings file (VERR
_ACCESS_DENIED)_

**Or, this will _rename_ the VM and host folder**.

It may be that anything else that is using that folder (Windows file explorer, for example), will inhibit renaming. But it's noteworthy that **VBoxManage does not rename the VM instance**.

**Comment by naumoff** [comment]
5 years passed and still problem exists

**Comment by chrisroberts** [comment]
@naumoff I do not see this behavior exhibited in the current version of Vagrant. If you are currently experiencing this problem with the latest version of Vagrant, please create a new issue and provide the details requested.

Cheers!
