### ISSUE TITLE
Allow traditional Windows backslash "\" in synced_folder definition

### ISSUE THREAD

**Issue by GiraffeSlacks** [hashicorp/vagrant#1827]
Vagrantfile does not seem to understand traditional Windows' paths with backslashes. Instead it (seems) to just strip them and then complain of the invalid path.

The following

```
config.vm.synced_folder "C:\Users\Giraffeslacks\Documents\Vagrant Shares", "/vagrant"
```

results in

```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: C:UsersGiraffeslacksDocumentsVagrant Shares
```

With forward slashes the result is as expected: success.

As an alternative to making backslashes compatible I would suggest that Vagrant detect the problem and complain appropriately. Something like: Please use a forward slash "/" in all paths.

**Comment by aspiringguru** [comment]
Having a similar problem here.
Where do I find "config.vm.synced_folder" ?
Vagrant installed to default directory C:\HashiCorp\Vagrant\bin
file 'vagrant' appears to be the only configuration file, it does not set config.vm.synced_folder to a value. I tried setting config.vm.synced_folder  in this config file. ie

config.vm.synced_folder "C:\\Users\\myusername\\Documents\\myDirPath", "/vagrant"
in the 2nd line immediately after  #!/usr/bin/env bash

vm:
* The host path of the shared folder is missing: ../vodm_data
