### ISSUE TITLE
VMware provider isn't setting the MAC address as expected.

### ISSUE THREAD

**Issue by skoblenick** [hashicorp/vagrant#1841]
I am attempting to create a VM with two NICs using VMware Fusion 5.04, Vagrant 1.2.2 and the VMware provider 0.6.3. VMware shows the two network interfaces when 'vagrant up' is ran, but the vmx setting for generatedAddress isn't being set to the VM's MAC address specified in my Vagrantfile.

The below is the Vagrantfile being used:

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "centos64"
    config.vm.box_url = "centos64.box"
    config.vm.hostname = "centos64"

    config.vm.provider :vmware_fusion do |v, override|

        v.gui = true

        v.vmx["memsize"] = "2048"

        v.vmx["ethernet0.present"] = "TRUE"
        v.vmx["ethernet0.connectionType"] = "nat"
        v.vmx["ethernet0.virtualDev"] = "e1000"
        v.vmx["ethernet0.wakeOnPcktRcv"] = "FALSE"
        v.vmx["ethernet0.addressType"] = "generated"
        v.vmx["ethernet0.linkStatePropagation.enable"] = "TRUE"
        v.vmx["ethernet0.generatedAddress"] = "00:0c:29:ac:f3:50"
        v.vmx["ethernet0.pciSlotNumber"] = "33"
        v.vmx["ethernet0.generatedAddressOffset"] = "0"

        v.vmx["ethernet1.present"] = "TRUE"
        v.vmx["ethernet1.connectionType"] = "nat"
        v.vmx["ethernet1.virtualDev"] = "e1000"
        v.vmx["ethernet1.wakeOnPcktRcv"] = "FALSE"
        v.vmx["ethernet1.addressType"] = "generated"
        v.vmx["ethernet1.generatedAddress"] = "00:0c:29:ac:f3:5a"
        v.vmx["ethernet1.pciSlotNumber"] = "34"
        v.vmx["ethernet1.generatedAddressOffset"] = "10"

    end

end
```

The 2 lines from the vm.vmwarevm (centos64.vmx) being generated from vagrant up (in the local workspace) that I expected to be changed are:

ethernet0.generatedAddress = "00:0c:29:65:08:9e"
ethernet1.generatedAddress = "00:0c:29:65:08:a8"

I have attempted to hack the values within the generated vmx file. The values are always reset thou, even after a halt and up, which makes it evident that Vagrant is resetting these values.

If I shutdown -h the machine then modify the MAC address' from the GUI, I can force the MAC address to what I need them to be.

I can understand the l the likely reason for this is to prevent MAC address collisions but in a case where the user is explicitly trying to change the MAC address it should be expected that they know what they are doing. Also in the case where the NICs are set to NAT, the only way I can see a collision occurring is two VM's, or interfaces on the same box are attempting to use the same MAC. For this reason I think this is a bug, if it's a setting I should be allowed to override even if it causes negative but expected behaviour.

**Comment by ryanerwin** [comment]
Why doesn't the host.vm.network "private_network", ip: "192.168.5.111", mac: 00:XX:XX:XX:XX:XX syntax work on Vagrant when using the VMware plugin, instead requring changes that required editing the vmware VMX file?

There isn't even a CentOS 7 VMware box that works on the Vagrant site, you have to build your own...

Why bother selling licenses if the licensed software is inferior to the open source version?
