### ISSUE TITLE
'vagrant up' insists on a previously installed provider

### ISSUE THREAD

**Issue by thasmo** [hashicorp/vagrant#1844]
Used the provider 'vmware_workstation' before but reinstalled Vagrant 1.2.2 without the provider. Now when I want to 'vagrant up' an existing machine, which was previously created using the 'vmware_workstation' provider, does not boot and Vagrant throws this error:

```
The provider 'vmware_workstation' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
```

VAGRANT_DEFAULT_PROVIDER is not set, but there are files inside the directory ".vagrant\machines\default\vmware_workstation", while "..vagrant\machines\default\virtualbox" is empty.

After deleting the ".vagrant" directory it worked again to 'vagrant up' with the virtualbox provider.

**Comment by djkwagala** [comment]
@mitchellh  thanks. this helped!
