### ISSUE TITLE
Vagrant fails to recover if virtual machine is deleted on disk

### ISSUE THREAD

**Issue by thasmo** [hashicorp/vagrant#1848]
When deleting the VM files on the disk directly (e.g. in the Windows explorer) Vagrant prints this error:

```
Your VM has become "inaccessible." Unfortunately, this is a critical error with VirtualBox that Vagrant can not cleanly recover from. Please open VirtualBox and clear out your inaccessible virtual machines or find a way to fix them.
```

VirtualBox itself doesn't show the VMs either, so I can not delete the VM anywhere and Vagrant gives this error on every command given - even on "vagrant destroy".

The only way to get this fixed was to delete the ".vagrant" directory.

**Comment by idreesandroid** [comment]
for window 
C:\Users\Lenovo\VirtualBox VMs\vagrant_default_1558438543686_34399

 go there and just remove the temp at the extension and it will start working
