### ISSUE TITLE
"Guru meditation" on boot, every version of VirtualBox and Vagrant and Ubuntu on OS X 10.8.4

### ISSUE THREAD

**Issue by MaciekBaron** [hashicorp/vagrant#1871]
Hi there,

I cannot seem to be able to run Vagrant on OS X (Mountain Lion, 10.8.4).

Every time I try to boot a simple Vagrant instance by using:

```
vagrant init
vagrant up
```

my VirtualBox instance "crashes", or enters the "guru meditation" state to be more precise.

This happens after freshly installing Vagrant on a new computer and downloading _lucid32_ or any other OS version. I've uploaded [the log](https://gist.github.com/MaciekBaron/bd50936ba37ed1d9eef7) to gist for reference.

I've tried the following versions of VirtualBox:
- 4.1.23
- 4.2.12
- 4.2.14 (I haven't tried the latest version due to a [different issue](https://github.com/mitchellh/vagrant/issues/1847))

...and the following versions of Vagrant:
- 1.2.0
- 1.2.2

...and the following boxes:
- http://files.vagrantup.com/precise32.box
- http://files.vagrantup.com/lucid32.box

Is it possible that Vagrant does not work for some reason with OS X 10.8.4? I can't think of another explanation.

**Comment by mikeweilgart** [comment]
The following link may also be helpful.  https://forums.virtualbox.org/viewtopic.php?f=3&t=78983&p=376018#p376018

(Summary: Others have had this issue on other specified versions of VirtualBox.  By downgrading from VirtualBox 5.1 to 5.0.28 (the latest 5.0 version available at this writing) I no longer got "Guru Meditation.")
