### ISSUE TITLE
Install plugin dependencies from within Vagrantfile

### ISSUE THREAD

**Issue by erran-r7** [hashicorp/vagrant#1874]
The ability to install plugins programmatically would be beneficial in Vagrantfiles. My idea of how this would work is placing plugin dependencies outside of the Vagrant configure blocks like so:

``` ruby
plugin 'vagrant-berkshelf', '1.3.2'

Vagrant.configure('2') do |config|
  # Normal configuration here
end
```

Related issues:
- #1700 
- #1736  
- #1789 
- I started this due to having a similar issue to: https://github.com/cityindex/wordpress-development-flow/issues/29

I started to create a work around at the top of my Vagrantfile, in accordance with [my comment on #1736 ](https://github.com/mitchellh/vagrant/issues/1736#issuecomment-20086447), but I only gotten this far (by shelling out and grepping through the vagrant.d directory):

``` ruby
def plugin(name, version = nil, opts = {})
  @vagrant_home ||= opts[:home_path] || ENV['VAGRANT_HOME'] || "#{ENV['HOME']}/.vagrant.d"
  plugins = JSON.parse(File.read("#@vagrant_home/plugins.json"))

  if !plugins['installed'].include?(name) || (version && !version_matches(name, version))
    cmd = "vagrant plugin install"
    cmd << " --entry-point #{opts[:entry_point]}" if opts[:entry_point]
    cmd << " --plugin-source #{opts[:source]}" if opts[:source]
    cmd << " --plugin-version #{version}" if version
    cmd << " #{name}"

    result = %x(#{cmd})
  end
end

def version_matches(name, version)
  gems = Dir["#@vagrant_home/gems/specifications/*"].map { |spec| spec.split('/').last.sub(/\.gemspec$/,'').split(/-(?=[\d]+\.?){1,}/) }
  gem_hash = {}
  gems.each { |gem, v| gem_hash[gem] = v }
  gem_hash[name] == version
end

# With version/source: plugin 'vagrant-berkshelf', '1.3.2', source: 'https://rubygems.org'
plugin 'vagrant-berkshelf'
plugin 'vagrant-omnibus'
```

To me it looks like the solution would be to expose a similar method while Vagrantfile's are being parsed. [This code in `VagrantPlugins::CommandPlugin::Command::Install`](https://github.com/mitchellh/vagrant/blob/master/plugins/commands/plugin/command/install.rb#L43-L50) is probably how the plugin method would handle install. I'm not sure how to handle the versioning though.

**Comment by bdw429s** [comment]
After reading all these comments, I'm a little unclear on what the outcome was of this discussion.  This ticket was closed with a reference to "vundle" which appears to be a vim bundler which is a little confusing.  Another comment says "eventually this will come in to core" but links to a dead ticket of +1's  and comments about how the suggested libraries are all unmaintained.

I using vagrant with teams of developers who don't really know or care what Vagrant is, they just need it to work with as little manual steps as possible.  `vagrant up` is pretty straightforward, but requirement them to also install a collection of other plugins is a lot harder than you would think.  I would LOVE vagrant to take care of installing in the necessary plugins the first time they "up".  I need a solution that is as easy as possible without extra manual steps to get screwed up or missed.

**Comment by miroswan** [comment]
So far I got this to install the plugin, but vagrant isn't aware of the new config options introduced:

```
def ensure_plugin(plugin)
  pm = Vagrant::Plugin::Manager.new(
    Vagrant::Plugin::Manager.user_plugins_file
  )
  plugin_hash = pm.installed_plugins
  return if plugin_hash.has_key?(plugin)

  puts "Installing plugin #{plugin}"
  pm.install_plugin(plugin)
end
```

If there is a way to reload the config to recognize the  new plugin, I think I might be on my way.

**Comment by miroswan** [comment]
I ended up just settling for this. Not single command, but better than nothing:

```
# Install vagrant plugin
#
# @param: plugin type: Array[String] desc: The desired plugin to install
def ensure_plugins(plugins)
  logger = Vagrant::UI::Colored.new
  result = false
  plugins.each do |p|
    pm = Vagrant::Plugin::Manager.new(
      Vagrant::Plugin::Manager.user_plugins_file
    )
    plugin_hash = pm.installed_plugins
    next if plugin_hash.has_key?(p)
    result = true
    logger.warn("Installing plugin #{p}")
    pm.install_plugin(p)
  end
  if result
    logger.warn('Re-run vagrant up now that plugins are installed')
    exit
  end
end
```

**Comment by sshrestha-navarts** [comment]
@miroswan how do I use this in my Vagrant file? I've been looking for this solution as well. 

I need to ensure some plugins are installed before running `vagrant up`

**Comment by jaequery** [comment]
hi everyone, are there any update on this? honestly having another command to run defeats the whole purpose of Vagrant for me and i'm sure a lot of others. this is just begging for another "higher abstraction" tool that fully automates deployments to come into market, something like "magic up" maybe, someday...

**Comment by jbq** [comment]
FWIW I'm using @miroswan's solution and I'm happy with it.  Native support in Vagrant would be nice though.

**Comment by DevNIX** [comment]
Hi guys, I've started a little plugin manager for my own. If you think it is useful for you, I will be glad to hear things that could be improved.

I'm maintaining this project as bugs appears at my daily job on different environments. If you have some issue or pull request, I will be constantly improving this.

Cheers!

http://devnix.github.io/Vagrant-dependency-manager/
https://github.com/DevNIX/Vagrant-dependency-manager

**Comment by jolohaga** [comment]
I find my users don't mind doing an init step before doing `vagrant up`.  In developing init scripts, I wish Vagrant provided command line tools to query what plugins are installed.

**Comment by DevNIX** [comment]
@jolohaga Do you mean a command like `vagrant plugin list`?

**Comment by jolohaga** [comment]
@DevNIX Yes, that works for me.  Obviously, I need to learn the command line features better.  Thank you for pointing this out.

**Comment by nitrocode** [comment]
@DevNIX cool script (minus the tabs lol). Would you possibly turn that into a PR to merge it into vagrant core?

**Comment by DevNIX** [comment]
@nitrocode I don't know if my code would be the correct approach to do this job inside the core project. Maybe I could try to hack it some day, but I am not an experienced Ruby developer. Will fix the tabs ASAP!
