### ISSUE TITLE
Cannot get vmware fusion box to work after upgrading to vagrant 1.2.2

### ISSUE THREAD

**Issue by rrichards** [hashicorp/vagrant#1894]
I have a gist where i worked on troubleshooting this with some other folks on freenode. https://gist.github.com/rrichards/5ab285cf5fe02a9b6b03

basically no matter what i try it doesnt want to recognize or load the vmware fusion box. Im fine with deleting all vagrant directories and starting from scratch if necessary.

thanks!
Ryan

**Comment by kenorb** [comment]
Related: [Multiple providers in a single vagrant file](http://stackoverflow.com/q/17059982/55075) at stackoverflow.
