### ISSUE TITLE
give a chance to disable default ssh port forwarding

### ISSUE THREAD

**Issue by pniederlag** [hashicorp/vagrant#1922]
from config/default.rb

```
# Share SSH locally by default
config.vm.network :forwarded_port,
  guest: 22,
  host: 2222,
  host_ip: "127.0.0.1",
  id: "ssh",
  auto_correct: true
```

it seems impossible to disable this port_forwarding which in turn really requires the first interface to be a NAT interface.

**Comment by qasimzee** [comment]
Also getting the same issue as 8080 port setting is available on packaged vagrant file. Following line helped me.

```config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true```

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://tubemulticouche.fr/seat.php?hu>

 

info@whywouldwe.com
