### ISSUE TITLE
`vagrant ssh` cannot connect to remote host

### ISSUE THREAD

**Issue by hkdobrev** [hashicorp/vagrant#1936]
Here is my debug log:

https://gist.github.com/hkdobrev/6012545

The relevant part:

```
DEBUG virtualbox_4_2:   - [1, "ssh", 2222, 22]
DEBUG ssh: Checking key permissions: /home/hkdobrev/.vagrant.d/insecure_private_key
 INFO ssh: Invoking SSH: ["vagrant@127.0.0.1", "-p", "2222", "-o", "LogLevel=FATAL", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-o", "IdentitiesOnly=yes", "-i", "/home/hkdobrev/.vagrant.d/insecure_private_key", "-o", "ForwardAgent=yes"]
ssh_exchange_identification: Connection closed by remote host
```

The problem occurs on both `vagrant up` and `vagrant ssh`.

When running `vagrant up` everything hangs and if I interupt it `vagrant status` shows _`running`_.

Then `vagrant ssh` produces the given output.

---

**Things I have tried**:
- Uninstalled vagrant.
- Removed `~/.vagrant.d/` (had some old files there from perviously installed vagrant 1.0.x).
- Installed vagrant again.

---

Vagrant version: **1.2.3**

**Comment by alberto56** [comment]
I'm using a CoreOS box, and I often log into my clients' or my own VPN ([virtual private network](http://lifehacker.com/5940565/why-you-should-start-using-a-vpn-and-how-to-choose-the-best-one-for-your-needs)). This generally does not cause any issues, but once in awhile it will cause SSH to stop working. My solution is to halt and restart the machine. See below for my output:

    $ vagrant ssh
    ssh_exchange_identification: Connection closed by remote host
    $ vagrant halt
    ==> core-01: Attempting graceful shutdown of VM...
        core-01: Guest communication could not be established! This is usually because
        core-01: SSH is not running, the authentication information was changed,
        core-01: or some other networking issue. Vagrant will force halt, if
        core-01: capable.
    ==> core-01: Forcing shutdown of VM...
    $ vagrant up
    Bringing machine 'core-01' up with 'virtualbox' provider...
    ==> core-01: Checking if box 'coreos-alpha' is up to date...
    ==> core-01: Clearing any previously set forwarded ports...
    ==> core-01: Fixed port collision for 22 => 2222. Now on port 2200.
    ==> core-01: Clearing any previously set network interfaces...
    ==> core-01: Preparing network interfaces based on configuration...
        core-01: Adapter 1: nat
        core-01: Adapter 2: hostonly
    ==> core-01: Forwarding ports...
        core-01: 22 => 2200 (adapter 1)
    ==> core-01: Running 'pre-boot' VM customizations...
    ==> core-01: Booting VM...
    ==> core-01: Waiting for machine to boot. This may take a few minutes...
        core-01: SSH address: 127.0.0.1:2200
        core-01: SSH username: core
        core-01: SSH auth method: private key
        core-01: Warning: Connection timeout. Retrying...
    ==> core-01: Machine booted and ready!
    ==> core-01: Setting hostname...
    ==> core-01: Configuring and enabling network interfaces...
    ==> core-01: Exporting NFS shared folders...
    ==> core-01: Preparing to edit /etc/exports. Administrator privileges will be required...
    Password:
    ==> core-01: Mounting NFS shared folders...
    ==> core-01: Machine already provisioned. Run `vagrant provision` or use the `--provision`
    ==> core-01: flag to force provisioning. Provisioners marked to run always will still run.
    $ vagrant ssh
    Last login: Wed Jul 29 17:30:06 2015 from 10.0.2.2
    CoreOS alpha (752.1.0)
    core@core-01 ~ $

**Comment by hassanamirkhan** [comment]
I have the same issue.

1) vagrant ssh works with "hashicorp/precise32" box on windows 7
2) vagrant sst gives me "ssh_exchange_identification: Connection closed by remote host" error with "ubuntu/trusty64" box on windows 7

Any solution ?

**Comment by mathsyouth** [comment]
@alberto56 Thanks for your solution. That works for me.

**Comment by obimod** [comment]
If you have a designated ssh port in the Vagrantfile you should compare it to the actual port vagrant is running ssh on. Sometimes with multiple instances running the port-conflict-auto-correction can cause you to mess up your configs (i.e. 2222 vs 2200).
