### ISSUE TITLE
ssh_exchange_identification: Connection closed by remote host when enabling synced folder (works when I uncomment the synced folder line)

### ISSUE THREAD

**Issue by ostollmann** [hashicorp/vagrant#1971]
Please see my configuration here: https://github.com/o1iver/vagrant-problem-1

If I comment this line:

```
config.vm.synced_folder "/Users/ost/Development/", "/dev/", :nfs => false
```

I can ssh into the machine using `vagrant ssh`. As soon as I uncomment that line I get the following error when trying to ssh into the machine:

```
ssh_exchange_identification: Connection closed by remote host
```

I am running OS X 10.8.4 and am using Virtual Box. I have, in fact, just followed the v2 tutorial. If any other information is required just let me know.

Note that I am running `vagrant halt ; vagrant up` between testing with and without the synced folder.

**Comment by silbertmonaphia** [comment]
OMG,I did the same thing...thanks @mitchellh
