### ISSUE TITLE
vagrant stuck at "Setting hostname"

### ISSUE THREAD

**Issue by Adirelle** [hashicorp/vagrant#1974]
Since I upgraded Vagrant to 1.2.4 (from 1.2.2), "vagrant up" gets stuck at "Setting hostname". If I interrupt it and try to run a "vagrant reload", it gets stuck at "Attempting graceful shutdown of VM".

Reverting to 1.2.2 fixes this issue.

Context: 
- Vagrant 1.2.4 without any plugin,
- VirtualBox 4.2.16,
- Custom Debian Squeeze base box, created with Vagrant 1.0,
- Windows 7 64-bits.

See https://gist.github.com/Adirelle/5e5a0ae063e9f02e23c7 for a debug log.

**Comment by haseebeqx** [comment]
same issue happening again with 2.0.4

**Comment by JoannaRMIT** [comment]
Same here

**Comment by haseebeqx** [comment]
for me the problem only happens with `harshicorp/precise32` box, may be something related to that

**Comment by briancain** [comment]
@haseebeqx @JoannaRMIT Please open a new issue if you're encountering a problem, thanks!

**Comment by zackshapiro** [comment]
Glad I'm not alone
