### ISSUE TITLE
VMware Fusion Provider Sets VNC On By Default To Port 5985

### ISSUE THREAD

**Issue by joefitzgerald** [hashicorp/vagrant#1995]
By default, the VMware Fusion provider sets the VNC management option to "on" and sets it to run on port 5985. This is probably not the best port number to run VNC on, as it's also the default port for winrm, which is one of the only other communicator protocols you're likely to use with vagrant other than ssh. 

In the VMX, this translates into the following settings:

```
RemoteDisplay.vnc.enabled = "true"
RemoteDisplay.vnc.port = "5985"
```

If you are trying to set up winrm, the current defaults can lead to a confusing debug session where you ask yourself questions like "if I can ping and telnet on this port, and I can connect, why isn't this working". It's not until you try to actually craft a winrm request manually that you realize it's listening for VNC connections, not winrm - and hiding the guest's winrm services.

By default, the option is off and uses port 5900. Is there a reason we don't just use the default?

**Comment by dragon788** [comment]
This is a pretty easy to fix, if you want to disable VNC via Packer, add this to your template JSON. 

  "vmx_data_post":{
      #....snipped other config....#
      "remotedisplay.vnc.enabled":"FALSE"
  }  

Then you can enable it yourself in a Vagrantfile, do the following.

  config.vm.provider "vmware_workstation" do |vmw|
      #....snipped other config....#
      vmw.vmx["remotedisplay.vnc.enabled"] = "FALSE"
  end
