### ISSUE TITLE
Allow overriding of --no-color option

### ISSUE THREAD

**Issue by joegrasse** [hashicorp/vagrant#2027]
I am using vagrant 1.2.7 along with ConEmu on Windows 7. ConEmu is a command prompt that has support for colors and with the fix for Issue #1344 support for colored text no longer works.

Could you allow for overriding the --no-color option?

**Comment by mbrodala** [comment]
@mitchellh To not have to specify `--color` on each invocation I currently set `ANSICON=dummy` on my windows desktop to [enforce color output](https://github.com/mitchellh/vagrant/blob/d2874064f4f90df13b66debdedddc9866ac24576/lib/vagrant/util/platform.rb#L151) (which actually works pretty fine on the default `cmd` console). Is this reliable or would you add an `VAGRANT_COLOR` environment variable similar to `VAGRANT_NO_COLOR`?
