### ISSUE TITLE
Feature request: vagrant scp

### ISSUE THREAD

**Issue by ksylvan** [hashicorp/vagrant#2034]
It would be great to have the ability to "vagrant scp" to/from a virtual machine.

There's this script: https://gist.github.com/colindean/5213685

```
#!/bin/sh
OPTIONS=`vagrant ssh-config | awk -v ORS=' ' '{print "-o " $1 "=" $2}'`
scp ${OPTIONS} "$@" || echo "Transfer failed. Did you use 'default:' as the target?"
```

But this script only works for a simple single-machine configuration. I'd love to be able to do something like this:

```
$ vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'agent' up with 'virtualbox' provider...
...
$ vagrant scp master:/etc/motd agent:/tmp
```

And the "vagrant scp" command would do the right thing.

**Comment by invernizzi** [comment]
Try [vagrant-scp][1], a Vagrant plugin that I wrote to solve this problem. Install via:

    vagrant plugin install vagrant-scp

Use it like so:

    vagrant scp <some_local_file_or_dir> <somewhere_on_the_vm> [vm_name]


  [1]: https://github.com/invernizzi/vagrant-scp
