### ISSUE TITLE
Permission denied - /home/vagrant/.gem/specs

### ISSUE THREAD

**Issue by drnic** [hashicorp/vagrant#204]
Any thoughts on this access issue?

My Vagrantfile (built on lucid32) using opscode chef recipes:

<pre>
Vagrant::Config.run do |config|
  config.vm.box = "base"

  config.vm.provisioner = :chef_solo
  config.chef.cookbooks_path = "cookbooks"
  config.chef.add_recipe "apt"
  config.chef.add_recipe "java"
  config.chef.add_recipe "git"
  config.chef.add_recipe "ruby"
  config.chef.add_recipe "rubygems"
  config.chef.add_recipe "rails"
end
</pre>

When I ssh in, I cannot install gems:

<pre>
> vagrant ssh
$ gem install rails
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /home/vagrant/.gem/specs
</pre>

<pre>
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 1.3.7
  - RUBY VERSION: 1.8.7 (2010-01-10 patchlevel 249) [i486-linux]
  - INSTALLATION DIRECTORY: /usr/lib/ruby/gems/1.8
  - RUBY EXECUTABLE: /usr/bin/ruby1.8
  - EXECUTABLE DIRECTORY: /usr/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-linux
  - GEM PATHS:
     - /usr/lib/ruby/gems/1.8
     - /home/vagrant/.gem/ruby/1.8
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/
</pre>

The only gems installed came via the `rails` chef recipe.

Sorry if this is more of a recipe/environment issue; I thought it might be something odd with how the `vagrant` user is created. Or someone might have an idea what is going wrong here.

**Comment by jcserracampos** [comment]
Why was this issue closed?
I'm having the same problem in 2017.
