### ISSUE TITLE
'vagrant box add' fail on Windows

### ISSUE THREAD

**Issue by yandod** [hashicorp/vagrant#2056]
When adding box with `vagrant box add path_to_box` is failing on WindowsXP.

```
Downloading or copying the box...
[0KAn error occurred while downloading the remote file. The error--:--)
message, if any, is reproduced below. Please fix this error and try
again.

Failed writing body (0 != 16383)
```

Is there some work around for this?
version of vagrant is 1.2.7

**Comment by mbaev** [comment]
Just example for Windows 7/8:
set VAGRANT_HOME=C:\Program Files (x86)\Vagrant

**Comment by dmasikondo** [comment]
**mbaev** you are a life saver thank you. Had spent sleepless nights failing todownload the Laravel Homestead box on windows 7

**Comment by mbaev** [comment]
@dmasikondo You're welcome)

**Comment by replaysMike** [comment]
Just a note - I received this same error when I was out of drive space on the drive vagrant was installed to. Was confusing.
