### ISSUE TITLE
VMware Workstation provider doesn't add/remove VMs in the VMware GUI

### ISSUE THREAD

**Issue by thasmo** [hashicorp/vagrant#2074]
When using the `vmware_workstation` provider with `up` and `destroy` it does not update the status of the VM in the VMware Workstation GUI. When doing a `vagrant up` the VM doesn't show up in the GUI, it has to be added manually. I've also set VAGRANT_VMWARE_CLONE_DIRECTORY to the directory in which the GUI stores it's VMs, but that didn't help - it's _only_ possible to manually add the VM via the `File -> Open...` option in the GUI. Also doing a `vagrant destroy` doesn't remove the VM from the GUI, but VMware throws an error when clicking on it because it's not available anymore, obviously.

Is this a VMware Workstation "bug", or can the VMware plugin handle this?

**Comment by TraGicCode** [comment]
Shame this is still a problem.  Tad bit annoying and seems like a bug when you start playing around with vmware workstation on windows with vagrant after using virtualbox
