### ISSUE TITLE
Unable to add a box from another drive under Windows

### ISSUE THREAD

**Issue by rgarrigue** [hashicorp/vagrant#2081]
The console below is quite explicit: 

```
        D:\travail\rmanTest>vagrant box add oracle C:\oracle.basebox
        Downloading or copying the box...
        ←[0KAn error occurred while downloading the remote file. The error
        message, if any, is reproduced below. Please fix this error and try
        again.

        Couldn't open file /oracle.basebox
```

Gotta love working with VMs on a 128Gb SSD drive -_- ...

**Comment by nuncanada** [comment]
For some reason in my setup, the syntax file://drive:/whatever only worked if the command prompt was in the drive being used... If it was outside it didn't work... Worse, this behaviour seemed to depend whether curl was download a box or a metadata file

Use file:////fileserver/directories/file, it always works.
