### ISSUE TITLE
config.vm.hostname fails in RHEL 5.9

### ISSUE THREAD

**Issue by Smolations** [hashicorp/vagrant#2097]
I receive a vagrant error telling me it is unable to set the hostname of my RHEL basebox when using `config.vm.hostname`. Host machine is OS X 10.8.4.

To work around it, I have to use an inline shell script (I set the `fqdn` variable before this command runs):

```
config.vm.provision :shell, :inline => "echo '#{fqdn}' > /proc/sys/kernel/hostname && /etc/init.d/network restart"
```

To be safe, I also use a puppet template to modify `/etc/sysconfig/network`, subscribing a command to restart the network to those file changes.

**Comment by timwood0** [comment]
This discussion begs the question, though: What is up with the setting of the hostname in the 'Linux' case?  There does not exist a function to do so in that (well-organized) code path!

**Comment by zhuni** [comment]
my host mechine is win7 ,after update virtualbox`lenovo@lenovo-PC MINGW64 /d/douban/shire-in-vagrant (master)
$ vagrant reload
==> default: Attempting graceful shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 9010 (guest) => 9010 (host) (adapter 1)
    default: 9015 (guest) => 9015 (host) (adapter 1)
    default: 9200 (guest) => 9200 (host) (adapter 1)
    default: 9315 (guest) => 9315 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.1.44
    default: VirtualBox Version: 5.1
==> default: Setting hostname...
Vagrant attempted to execute the capability 'change_host_name'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.

`
