### ISSUE TITLE
Error: sudo helper setuid-wrapper must run as root

### ISSUE THREAD

**Issue by command-tab** [hashicorp/vagrant#2099]
When attempting to bring up a Vagrant machine with the [coreos-vagrant](https://github.com/coreos/coreos-vagrant/) OS under VMware, Vagrant fails with the error:

```
sudo helper setuid-wrapper must run as root
```

It's got to be something on my system and not that particular Vagrantfile, but I'm unsure what to check. Here's my Vagrant log:
https://gist.github.com/commandtab/6383948

**Comment by henkbl** [comment]
@jgrevich Works great, thank you!

**Comment by devekko** [comment]
@nirvdrum couldn't get this workaround on Trusty to fly

any more config needed?

**Comment by nirvdrum** [comment]
@devekko I don't recall. You might be better off just setting up the symlink and installing fresh. It's possible the suid permissions didn't copy over when you moved. But I am running LinuxMint 17 (an Ubuntu 14.04 derivative) with this setup and it's working.

**Comment by devekko** [comment]
thanks @nirvdrum encrypted home drive?

**Comment by Bombdog** [comment]
@nirvdrum workaround works for me. Encrypted home directory (Ubuntu 16.04 LTS) causes this error only with VMWare driver, not a problem with the freely available virtualbox driver. Old issue, but still seems to be a problem
