### ISSUE TITLE
Vagrant 1.3.1 chef-solo environment support not reading environment name

### ISSUE THREAD

**Issue by ekrupnik** [hashicorp/vagrant#2210]
I am using the new Vagrant 1.3.1 for environment support using the chef-solo provisioner. In my `Vagrantfile`, I specify both the `environments_path`, as well as the NAME of the environment to use, which is defined inside the file. It does not appear that Vagrant reads the `name` of the environment set in the environment file, as outlined below.

`Chef::Exceptions::EnvironmentNotFound: Environment 'DEV1' could not be loaded from disk`

My Vagrantfile looks like:

```
  config.vm.provision :chef_solo do |chef|
    chef.log_level = :debug
    chef.data_bags_path = "../../data_bags"
    chef.environments_path = "../../environments"
    chef.roles_path = "../../roles"
    chef.environment = "DEV1"
```

When I set `chef.environment = "dev1"`, this error does not come up. 

Inside my environments/dev1.rb file, it has `name "DEV1"` set, which Opscode/Chef reads and set as the environment name.

**Comment by rojomisin** [comment]
I get this issue a lot, and the way to get around it is to `vagrant destroy --force;rm -rf .vagrant;vagrant up`.  Could this have to do with using upper case environments?  By my own convention I make roles and environments uppercase.  In fact Chef Web UI doesn't allow them to be uppercase, but knife does, so I think there's possibly something to it being a case issue.
