### ISSUE TITLE
No such file or directory - getcwd (Errno::ENOENT) when doing vagrant box add

### ISSUE THREAD

**Issue by wsargent** [hashicorp/vagrant#222]
I can't unpackage the lucid32 box once it is downloaded:
wsargent@pendulum:~/rubygems-1.3.7$ vagrant box add base http://files.vagrantup.com/lucid32.box
[vagrant] Downloading with Vagrant::Downloaders::HTTP...
[vagrant] Copying box to temporary location...
[vagrant] Cleaning up downloaded box...
/usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/action/box/unpackage.rb:47:in `chdir': No such file or directory - getcwd (Errno::ENOENT)
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/action/box/unpackage.rb:47:in`decompress'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/action/box/unpackage.rb:28:in `call'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/action/warden.rb:27:in`call'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/action/box/download.rb:23:in `call'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/action/warden.rb:27:in`call'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/action/builder.rb:120:in `call'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/action.rb:119:in`run'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/util/busy.rb:19:in `busy'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/action.rb:119:in`run'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/box.rb:61:in `add'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/box.rb:30:in`add'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/lib/vagrant/command/box.rb:8:in `add'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in`send'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in `run'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:118:in`invoke_task'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor.rb:263:in `dispatch'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:109:in`send'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:109:in `invoke'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor.rb:205:in`box'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
    from /usr/lib/ruby/gems/1.8/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /usr/lib/ruby/gems/1.8/gems/vagrant-0.6.7/bin/vagrant:15
    from /usr/bin/vagrant:19:in`load'
    from /usr/bin/vagrant:19

**Comment by nmusatti** [comment]
I just stumbled upon an instance of this problem while installing the libvirt plugin. In my case it was due to launching a command from a non-existent current directory.
