### ISSUE TITLE
VMWare clock skew on host machine resume

### ISSUE THREAD

**Issue by dcramer** [hashicorp/vagrant#2248]
If you have a running VM and you suspend/resume your host OS, you'll find that the clock is now out of sync with the host OS.

Note: We've tried setting the following in Vagrantfile:

```
    vp.vmx['tools.syncTime'] = 'TRUE'
    vp.vmx['tools.synchronize.restore'] = 'TRUE'
```

I'm not sure if there's something that Vagrant can do to address this.

**Comment by blopker** [comment]
If anyone stumbles across this, the only way I was able to get it working (kinda) was with:
```
v.vmx["rtc.startTime"] = Time.now.to_i - Time.zone_offset('PST')
```
Replace `PST` with whatever timezone you want.

Cheers!
