### ISSUE TITLE
Parent folders of synced_folder are owned by root

### ISSUE THREAD

**Issue by nathany** [hashicorp/vagrant#2257]
> "The second parameter must be an absolute path of where to share the folder within the guest machine. This folder will be created (recursively, if it must) if it doesn't exist."

When I setup a synced folder like so:

``` ruby
linux.vm.synced_folder src_path, "/home/vagrant/go/src"
```

The src folder is owned by vagrant:vagrant but the go folder is owned by root:root. This prevents the pkg and bin folders from being created later.

```
mkdir /home/vagrant/go/pkg: permission denied
```

Adding `owner: "vagrant", group: "vagrant"` did not remedy the situation.

Vagrant 1.3.3, VirtualBox 4.2.18 r88780, OS X 10.8.5, precise64, inline shell provisioning

**Comment by fd0** [comment]
For the record: I also think that this is unexpected. I got bitten today, too.
