### ISSUE TITLE
Add documentation for mount_options with examples

### ISSUE THREAD

**Issue by gregelin** [hashicorp/vagrant#2274]
I ran into a vagrant file that used the deprecated "extra" flag to set a shared folder options instead of "mount_options." Unfortunately, I could not find clear documentation of how to set up the array for mount_options in issue #1029 or in the documentation. So requesting documentation with examples of using mount_options. Thanks.

**Comment by habitullence** [comment]
I'm completely lost on the mount options, especially nfs. It's marked as resolved but I can't find the docs anywhere :S

**Comment by justechn** [comment]
Mount options are still not very clearly defined or examples given. https://www.vagrantup.com/docs/synced-folders/basic_usage.html says `mount_options (array) - A list of additional mount options to pass to the mount command.` but no where that I can find are those additional mount options defined.

**Comment by adamelliotfields** [comment]
I could be mistaken, but I believe `mount_options` are options passed to the `mount` command on the guest.

See "Mount options for udf": http://man7.org/linux/man-pages/man8/mount.8.html
