### ISSUE TITLE
NFS is broken on Mac OS X 10.8.5 using VirtualBox 4.2.18 and Vagrant 1.3.x 

### ISSUE THREAD

**Issue by ricbra** [hashicorp/vagrant#2319]
I'm experiencing problems when trying to mount a NFS share. I've spent quite a few hours on this issue and I believe mine is different then those already reported in https://github.com/mitchellh/vagrant/issues/1093 and https://github.com/mitchellh/vagrant/issues/1744.

When booting a VM vagrant just stops without any error after the NFS mounting:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Setting hostname...
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /vagrant
[default] -- /home/developer
[default] Exporting NFS shared folders...
Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
[default] Mounting NFS shared folders...
```

I tried changing the guest OS from CentOS 6 to Debian 7, no difference. On my Ubuntu machine with Vagrant 1.3.4 and VirtualBox 4.2.18 all is working fine.

I finally fixed the issue by downgrading to Vagrant 1.2.7. My colleague is experiencing the same issue on his Mac 10.8.5 so this issue shouldn't be that hard to reproduce. 

My debug info: https://gist.github.com/ricbra/6821924

**Comment by etisab** [comment]
+1, using OSX Mavericks and Vagrant 1.7.2

**Comment by JimyRyan** [comment]
+1 using OSX Mavericks (10.9.4) and Vagrant 1.7.2 (with default Ubuntu 14.04 64 Box)

**Comment by andrewroth** [comment]
+1 Does anyone know a command I can manually run from the vagrant box after I ssh in to get the NFS working?

**Comment by WouterSioen** [comment]
+1

**Comment by Gerst20051** [comment]
:+1:

**Comment by eddiejaoude** [comment]
Thanks @bartekn , it was the firewall causing the issue on nfs mount

**Comment by DanielAron** [comment]
Same problem here with Vagrant 1.7.2
Turning of the firewall fix it
Thanks @bartekn

**Comment by dkinzer** [comment]
I think I've just run into this myself.
