### ISSUE TITLE
Add some way to increase disk space from Vagrantfile

### ISSUE THREAD

**Issue by peterbraden** [hashicorp/vagrant#2339]
At the moment you can increase memory in the vagrantfile, but if you want to increase disk space you have to use the VBoxManage tool to enlarge the image. It would be great to be able to specify this in the vagrantfile.

**Comment by xacaxulu** [comment]
Does anyone have the remotest idea about how to put this into a .kitchen.yml format?

**Comment by renan** [comment]
My solution was to resize the base box itself, like follows:

```shell
vagrant box add ubuntu/trusty64 --box-version 20150609.0.9
cd ~/.vagrant.d/boxes/ubuntu-VAGRANTSLASH-trusty64/20150609.0.9/virtualbox/
VBoxManage clonehd box-disk1.vmdk tmp-disk.vdi --format vdi
VBoxManage modifyhd tmp-disk.vdi --resize 61440
VBoxManage clonehd tmp-disk.vdi resized-disk.vmdk --format vmdk
rm tmp-disk.vdi box-disk1.vmdk
mv resized-disk.vmdk box-disk1.vmdk
```

**Comment by hbrls** [comment]
I followed this blog post, and it works well.

http://blog.lenss.nl/2012/09/resize-a-vagrant-vmdk-drive/

**Comment by BenMorganIO** [comment]
@mitchellh Do you know what's supposed to go into those ellipses?

**Comment by dvfabbri** [comment]
@BenMorganIO did you determine what goes in those ellipses to set disk size?

**Comment by BenMorganIO** [comment]
Nope...

**Comment by dvfabbri** [comment]
@mitchellh Can you provide an example of the commands required to create a VM with 500GB disk in the Vagrant file? I have been looking around to set this up, but I currently am just stuck using [Gparted](http://gparted.org/) to resize post creation. 

```
config.vm.customize "virtualbox" do |vb|
  vb.customize "pre-boot", ["..."]
end
```

**Comment by Dimasdanz** [comment]
The command should be something like this

```
config.vm.customize "virtualbox" do |vb|
  vb.customize "pre-boot", ["modifyhd", :id, "--resize", "32678"] #32678 = 32GiB
end
```

But, this would not work because:

1. UUID passed by Vagrant to VBoxManage is not hdd's UUID listed by `VBoxManage list hdds` so modifyhd is not possible. It displays error like this  

    ```
    Stderr: VBoxManage.exe: error: The given path <UUID-here> is not fully qualified 
    ```

2. Even if we can get hdd UUID to execute modifyhd, storage format of boxes downloaded by Vagrant is VMDK. [modifyhd command cannot be performed on VMDK format](https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvdi)

So, as of now, I think the only way to increase disk space is @renan's way  
You can also modify an already created vagrant but you have to remove attached hdd and reattach the new one.

**Comment by jhgorse** [comment]
so this what we need?
```
config.vm.provider "virtualbox" do |v|
  vmdk_path = get_vagrant_box_path()
  tmp1 = vmdk_path."tmp1"
  tmp2 = vmdk_path."tmp2"

  v.customize "pre-boot", ["clonehd",  vmdk_path,  tmp1, "--format vdi"]
  v.customize "pre-boot", ["modifyhd", tmp1, "--resize", "32678"]
  v.customize "pre-boot", ["clonehd",  tmp1,       tmp2, "--format vmdk"]

  rm vmdk_path tmp1
  mv tmp2 vmdk_path
end
```

**Comment by mleopold** [comment]
Hi,
@mitchellh The issue was closed in 2013, is there any chance of reopening it? it seems this issue is still around and the suggestions are inconvenient at best. A option for the disk-size at the first creation or more guided resize later sounds like it would be appreciated.

Br,
Martin

**Comment by Shuliyey** [comment]
@jhgorse thanks for the script.

Just a question I got the below error around the below two lines

```vagrantfile
  tmp1 = vmdk_path."tmp1"
  tmp2 = vmdk_path."tmp2"
```
There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/mnt/sdb/VirtualBox/dye/Vagrantfile:55: syntax error, unexpected tSTRING_BEG, expecting '('
    tmp1 = vmdk_path."tmp1"
                      ^
/mnt/sdb/VirtualBox/dye/Vagrantfile:56: syntax error, unexpected tSTRING_BEG, expecting '('
    tmp2 = vmdk_path."tmp2"
```

**Comment by skortchmark9** [comment]
@renan's solution seems to be working for me - However, I also needed to edit the box.ovf file, where it says `ovf:capacity`

**Comment by snowiow** [comment]
I had the same problem and thanks to @renan 's solution I got started. But it wasn't the complete solution for me, because I had an UUID conflict. I have written up my complete solution path [here](http://snow-dev.com/increase-disk-space-of-a-vagrant-machine/). I hope it is of any help for anybody.

**Comment by BenMorganIO** [comment]
@snowiow Thankyou :heart:

**Comment by ogero** [comment]
I've just made a Python script that does the VMDK resize and deal with UUID all the way..
But regrettably, it can't be automatically used inside Vagrantfile.. the steps are something like this:
```
>vagrant up --no-provision
>vagrant halt
>wget https://gist.githubusercontent.com/ogero/14692edf0702bfefe0455d6e7a9dc6de/raw/849c39404b649abaf6985901505170cc2f366c46/expand_disk.py
>chmod +x expand_disk.py
>python expand_disk.py
>vagrant up --no-provision
>vagrant ssh --command "sudo resize2fs /dev/sda1"
>vagrant provision
```

**Comment by Doume3** [comment]
Hi, I saw this contribution which help me a lot :+1: https://github.com/sprotheroe/vagrant-disksize

**Comment by steveswinsburg** [comment]
With the vagrant-disksize plugin I get a resized disk but the partition underneath is still the original so has to be resized within the guest. This makes it hard to automate.

**Comment by afturner** [comment]
If you'd like an automated solution, I did this:

    config.disksize.size = '10GB'
    config.vm.provision "shell", inline: <<-SHELL
        sudo resize2fs /dev/sda1
    SHELL

And install vagrant-disksize:

    vagrant plugin install vagrant-disksize

YMMV. sda1 was the right one for me, but you may need to ssh and double check.

**Comment by CristianCantoro** [comment]
@Doume3 said:
> Hi, I saw this contribution which help me a lot +1 https://github.com/sprotheroe/vagrant-disksize

I confirm that using the [`vagrant-disksize`](https://github.com/sprotheroe/vagrant-disksize) plugin with a Ubuntu base box solved the issue for me. It also seems that I had nothing else to do (no `resize2fs`, no `lvextend`, etc.) and it work "automagically".
