### ISSUE TITLE
The provider 'vmware_workstation' could not be found, but was requested to back the machine 'devmachine2'. Please use a provider that exists.

### ISSUE THREAD

**Issue by hyperfocus1338** [hashicorp/vagrant#2342]
Hello,

Vagrant can't find my VMware workstation 10 installation on Ubuntu. It's installed perfectly fine and is able to create VM's.

I have set the environment variable with:

export VAGRANT_DEFAULT_PROVIDER=vmware_workstation

Trying to start Vagrant with vagrant up --provider vmware_workstation gave the same error.

I'm running Ubuntu desktop 13.04 with VMware workstation 10.

**Comment by weaming** [comment]
What plugin show be installed?

**Comment by carltondickson** [comment]
https://www.vagrantup.com/docs/vmware/installation.html covers how to install the VMWare provider
Once installed I get this
`
$ vagrant plugin list
vagrant-vmware-workstation (4.0.18)
`

Note you'll need to buy a licence for this provider first, all covered on the link above
