### ISSUE TITLE
Default gateway for guest

### ISSUE THREAD

**Issue by flaccid** [hashicorp/vagrant#2389]
Requesting to re-open https://github.com/mitchellh/vagrant/issues/436
Happy to provide more information or simply use this new issue.

**Comment by jonancm** [comment]
I feel that this doesn't solve the problem yet if you use DHCP, as @atrauzzi [mentioned before](#issuecomment-67455884).

I'm testing this on a [trusty64](https://vagrantcloud.com/ubuntu/boxes/trusty64) (Ubuntu Server) VM where I have the NAT interface with port forwarding for SSH (`eth0`) that Vagrant creates by default, plus a bridged interface to access my LAN (`eth1`), which I add like this:

```ruby
config.vm.network "public_network"
```

I've noticed that Vagrant appends the following lines to `/etc/network/interfaces`:

```
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet dhcp
    post-up route del default dev $IFACE
#VAGRANT-END
```

whereas the NAT interface (`eth0`) is set up in `/etc/network/interfaces.d/eth0.cfg`:

```
# The primary network interface
auto eth0
iface eth0 inet dhcp
```

I have the impression that the source of the problem is the post-up hook that removes the default gateway from `eth1`.

Wouldn't it be most convenient to have a way of telling Vagrant in the Vagrantfile not to add this post-up hook to `eth1` and have the issue solved in that way?

**Comment by flaccid** [comment]
@mitchellh I think we have enough evidence here for vagrant to solve this in a proper way instead of Vagrantfile messyness :+1:

**Comment by gregtampa** [comment]
need to add a gateway NOT using DHCP as it is a static IP at a datacenter.. 
will try to get those scripts working in one of the answers.  Making my life harder.. might change over to LXC

**Comment by niccolox** [comment]
I've been adding a second public gateway on reload and it bypasses all
these hacks

  config.vm.network "public_network", bridge: "eth0"

end
end

On Wed, May 20, 2015 at 2:00 PM, Gregory Hanis <notifications@github.com>
wrote:

> need to add a gateway NOT using DHCP as it is a static IP at a
> datacenter..
> will try to get those scripts working in one of the answers. Making my
> life harder.. might change over to LXC
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/2389#issuecomment-104036706>.
>



-- 

-- 
Nicholas Roberts
www.niccolox.org

**Comment by clay584** [comment]
Virtualbox, etc will assign a default gateway because that is the default behavior to give clients a default route so they can access the internet.  This is not needed if you are bridging, so you can just add this to your vagrantfile in order to not install the NAT default gateway into the guest route table.

This will fix the issue for DHCP, bridged interfaces.

    config.vm.provision "shell", inline: <<-SHELL
        sudo sed -i s/DEFROUTE=yes/DEFROUTE=no/g /etc/sysconfig/network-scripts/ifcfg-<NAT_INTERFACE>
        sudo systemctl restart network
    SHELL

**Comment by gregtampa** [comment]
don't know why you closed this issue, I will not be using vagrant till it has full network routing configurable

**Comment by anthonymanzo** [comment]
I've been trying to set as static as well (like gregtampa).  I'm new to Vagrant and Chef so this may not be the right way.  So far, I've only gotten partial success using the https://github.com/target/network_interfaces_v2-cookbook cookbook.  It assigns the ip and gw but after that it hangs the 'vagrant up ' process becuase the ip has changed.  I need to figure out how to overcome this in a best practices sort of way.  Any suggestions ??

**Comment by anthonymanzo** [comment]
By the way, here's my recipe I'm executing for the static:

```
network_interface 'eth0' do
  bootproto 'static'
  address node['network_interfaces_v2']['address'] 
  netmask node['network_interfaces_v2']['netmask']
  gateway node['network_interfaces_v2']['gateway']
end
```

**Comment by EvanPurkhiser** [comment]
Using @clay584's shell provisioning I've had better luck on Centos 7 with

```
sudo systemctl restart NetworkManager
```

**Comment by JavyZheng** [comment]
@stanleygu 

After changing the default gateway, I am able to reach the VM from an external IP(from another subnet).

However, the VM now cannot access the internet.

Did you encounter the same problem with me or could you give some advice on this situation?

**Comment by neyfrota** [comment]
My vagrant file looks like this
```
...
config.vm.network "private_network", ip: "192.168.10.15"
config.vm.network "public_network"
config.vm.provision "shell", run: "always", inline: "/sbin/dhclient -r eth2; /sbin/route del default; /sbin/dhclient eth2"
...
```

**lines 1 and 2** make sure i have this adapter setup

- Adapter 1: eth0 nat (for vagrant use) 
- Adapter 2: eth1 hostonly (internal network to talk with other vms)
- Adapter 3: eth2 bridged (that we answer bridge adapter and guest dhcp a ip at same network as host)

At this point, guest default gw still point to network at eth0

**Line 3** is the best way to modify default gw without know router ip. we release eth2 ip, remove default router, renew eth2 ip and by consequence fill default gw with host router ip 

Done. guest default gw point to host router

**Comment by belonesox** [comment]
My workaround without hardcoding to IP/interface names, etc:
http://wiki.4intra.net/Blog:StasFomin/Easy_Networking_with_Vagrant_and_VirtualBox

**Comment by nileshvmware** [comment]
Hi team,
Need to get gateway IP details on VMs from scripts
Pls provide me

**Comment by vioan** [comment]
I have the same issue with vagrant on a FreeBSD host

**Comment by pedroarthur** [comment]
In my case, it happens the default route via NAT has the same metric as the default route via the public network. Hence, the requests are received through the public network, but responses go through the NAT interface to get dropped.

For now, I am overriding the configuration by provisioning the following:

```shell
sed s/RouteMetric=100/RouteMetric=200/ \
    /run/systemd/network/10-netplan-enp0s3.network \
    | tee /etc/systemd/network/10-netplan-enp0s3.network \
    ;
```
In a Ubuntu Bionic box, this will change the NAT default route metric to 200. I did this way cause it is easier to change NAT interface parameters than changing DHCP-enabled public networks parameters. However, a proper solution should encompass new configuration item for DHCP. Something like:

```ruby
host.vm.network "public_network",
    use_dhcp_assigned_default_route: true,
    dhcp_route_metric: 50
```
