### ISSUE TITLE
Error while adding new interface: VBoxNetAdpCtl: ioctl failed for /dev/vboxnetctl: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by zippo2021** [hashicorp/vagrant#2429]
Hi. I'm getting this error with 'vagrant up' while using Fedora 19:
<code>There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
Command: ["hostonlyif", "create"]
Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: VBoxNetAdpCtl: ioctl failed for /dev/vboxnetctl: Inappropriate ioctl for devic
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage: error: Context: "int handleCreate(HandlerArg_, int, int_)" at line 68 of file VBoxManageHostonly.cpp
</code>

**Comment by moff** [comment]
Sorry for posting in this old thread! But it's in Google's top so I'm willing to help others that suffer from getting this error (using Ubuntu 16.04, Vagrant, Virtualbox, Homestead):
```
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: VBoxNetAdpCtl: ioctl failed for /dev/vboxnetctl: Inappropriate ioctl for device
```
I tried everything that I could find, but it didn't help. I was using fresh installations of Virtualbox and Vagrant from official websites.

The problem disappeared after with fresh install of Virtualbox via official repo (not a .deb downloaded from official website) using standard command `sudo apt-get install virtualbox`

I hope it'll help someone!
