### ISSUE TITLE
Restarting network (via systemctl):  [FAILED]

### ISSUE THREAD

**Issue by kelbyers** [hashicorp/vagrant#2430]
After upgrading from Vagrant 1.3.3 to 1.3.5 and upgrading vagrant-vmware-fusion from 2.0.5 to 2.0.8, my Fedora 19 guests get errors up starting:

Kels-MacBook-Pro:800 jxb2016$ vagrant reload vpre
[vpre] Attempting graceful shutdown of VM...
Connection to 192.168.254.193 closed by remote host.
[vpre] Verifying vmnet devices are healthy...
[vpre] Preparing network adapters...
[vpre] Starting the VMware VM...
[vpre] Waiting for the VM to finish booting...
[vpre] The machine is booted and ready!
[vpre] Forwarding ports...
[vpre] -- 22 => 2222
[vpre] Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

service network restart

Stdout from the command:

Restarting network (via systemctl):  [FAILED]

Stderr from the command:

Job for network.service failed. See 'systemctl status network.service' and 'journalctl -xn' for details.

Kels-MacBook-Pro:800 jxb2016$ vagrant ssh vpre
Last login: Mon Oct 28 12:30:44 2013 from url-fw03-websensedmz.homedepot.com
[vagrant@pre ~]$ sudo systemctl status network.service
network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network)
   Active: failed (Result: exit-code) since Mon 2013-10-28 14:13:51 EDT; 7min ago
  Process: 2030 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=1/FAILURE)

Oct 28 14:13:51 pre.p2v.vagrantup.com network[2030]: RTNETLINK answers: File exists
Oct 28 14:13:51 pre.p2v.vagrantup.com network[2030]: RTNETLINK answers: File exists
Oct 28 14:13:51 pre.p2v.vagrantup.com network[2030]: RTNETLINK answers: File exists
Oct 28 14:13:51 pre.p2v.vagrantup.com network[2030]: RTNETLINK answers: File exists
Oct 28 14:13:51 pre.p2v.vagrantup.com network[2030]: RTNETLINK answers: File exists
Oct 28 14:13:51 pre.p2v.vagrantup.com network[2030]: RTNETLINK answers: File exists
Oct 28 14:13:51 pre.p2v.vagrantup.com network[2030]: RTNETLINK answers: File exists
Oct 28 14:13:51 pre.p2v.vagrantup.com systemd[1]: network.service: control process exited, code=exited status=1
Oct 28 14:13:51 pre.p2v.vagrantup.com systemd[1]: Failed to start LSB: Bring up/down networking.
Oct 28 14:13:51 pre.p2v.vagrantup.com systemd[1]: Unit network.service entered failed state.
[vagrant@pre ~]$ sudo journalctl -xn
-\- Logs begin at Mon 2013-08-05 17:58:43 EDT, end at Mon 2013-10-28 14:21:09 EDT. --
Oct 28 14:14:12 pre.p2v.vagrantup.com systemd[1]: Starting Stop Read-Ahead Data Collection...
-\- Subject: Unit systemd-readahead-done.service has begun with start-up
-\- Defined-By: systemd
-\- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-\- Unit systemd-readahead-done.service has begun starting up.
Oct 28 14:14:12 pre.p2v.vagrantup.com systemd-journal[170]: Forwarding to syslog missed 22 messages.
-\- Subject: One or more messages could not be forwarded to syslog
-\- Defined-By: systemd
-\- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-\- Documentation: http://www.freedesktop.org/wiki/Software/systemd/catalog/0027229ca0644181a76c4e92458afa2e
--
-\- One or more messages could not be forwarded to the syslog service
-\- running side-by-side with journald. This usually indicates that the
-\- syslog implementation has not been able to keep up with the speed of
-\- messages queued.
Oct 28 14:14:12 pre.p2v.vagrantup.com systemd[1]: Started Stop Read-Ahead Data Collection.
-\- Subject: Unit systemd-readahead-done.service has finished start-up
-\- Defined-By: systemd
-\- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-\- Unit systemd-readahead-done.service has finished starting up.
--
-\- The start-up result is done.
Oct 28 14:16:38 pre.p2v.vagrantup.com avahi-daemon[734]: Invalid response packet from host 192.168.254.1.
Oct 28 14:19:08 pre.p2v.vagrantup.com avahi-daemon[734]: Invalid response packet from host 192.168.254.1.
Oct 28 14:20:54 pre.p2v.vagrantup.com sshd[2178]: Accepted publickey for vagrant from 192.168.254.1 port 51431 ssh2
Oct 28 14:20:54 pre.p2v.vagrantup.com systemd-logind[731]: New session 2 of user vagrant.
-\- Subject: A new session 2 has been created for user vagrant
-\- Defined-By: systemd
-\- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-\- Documentation: http://www.freedesktop.org/wiki/Software/systemd/multiseat
--
-\- A new session with the ID 2 has been created for the user vagrant.
--
-\- The leading process of the session is 2178.
Oct 28 14:20:54 pre.p2v.vagrantup.com sshd[2178]: pam_unix(sshd:session): session opened for user vagrant by (uid=0)
Oct 28 14:21:01 pre.p2v.vagrantup.com sudo[2209]: vagrant : TTY=pts/0 ; PWD=/home/vagrant ; USER=root ; COMMAND=/bin/systemctl
Oct 28 14:21:09 pre.p2v.vagrantup.com sudo[2211]: vagrant : TTY=pts/0 ; PWD=/home/vagrant ; USER=root ; COMMAND=/bin/journalctl

**Comment by lsim** [comment]
+1 in Vagrant 1.8.5 (centos 7 guest):

==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

# Update sysconfig
sed -i 's/\(HOSTNAME=\).*/\1cis-latest/' /etc/sysconfig/network

# Update DNS
sed -i 's/\(DHCP_HOSTNAME=\).*/\1"cis-latest"/' /etc/sysconfig/network-scripts/ifcfg-*

# Set the hostname - use hostnamectl if available
echo 'cis-latest' > /etc/hostname
if command -v hostnamectl; then
  hostnamectl set-hostname --static 'cis-latest'
  hostnamectl set-hostname --transient 'cis-latest'
else
  hostname -F /etc/hostname
fi

# Remove comments and blank lines from /etc/hosts
sed -i'' -e 's/#.*$//' -e '/^$/d' /etc/hosts

# Prepend ourselves to /etc/hosts
grep -w 'cis-latest' /etc/hosts || {
  sed -i'' '1i 127.0.0.1\tcis-latest\tcis-latest' /etc/hosts
}

# Restart network
service network restart


Stdout from the command:

/bin/hostnamectl
Restarting network (via systemctl):  [FAILED]


Stderr from the command:

Job for network.service failed because the control process exited with error code. See "systemctl status network.service" and "journalctl -xe" for details.
