### ISSUE TITLE
Too many open files - getcwd (Errno::EMFILE)

### ISSUE THREAD

**Issue by thbar** [hashicorp/vagrant#2435]
While doing `vagrant up` on a precise64 box with virtualbox 4.2.18 r88780 and vagrant 1.3.5, I'm getting [these errors](https://gist.github.com/thbar/7211993).

It occurs only if I try to use a synced folder using this (if I remove this, the issue disappears):

``` ruby
config.vm.synced_folder "projects", "/projects"
```

I did not include the full verbose log publicly because I'm concerned about leaking some client related data, but I could send it to you privately though.

**Comment by agis-** [comment]
It seems that on OS X Mavericks the default `ulimit -n` was set to 200. Increasing it to 1024 did the trick.

**Comment by bendilley** [comment]
Further to @agis-'s comment, I can confirm that I also found it was the **OS X** host machine's `ulimit -n` that was too small, at 256. Upping it to 1024 (same as the Ubuntu default) did the trick. This can of course be added to `~/.bash_profile` or equivalent.

**Comment by mcandre** [comment]
On my machine, `ulimit` reports `unlimited`, and I still see this "Too many open files" error anyway. Using macOS Sierra.
