### ISSUE TITLE
vagrant ssh works but provision fails on SSH auth and vagrant up cannot ssh

### ISSUE THREAD

**Issue by mjuarezm** [hashicorp/vagrant#2438]
I am using Vagrant version 1.3.5 and I am experiencing exactly the same as in Issue <a href="https://github.com/mitchellh/vagrant/issues/1969" class="issue-link" title="vagrant ssh works but provision fails on SSH auth">#1969</a>. I've found the follow up of this issue (Issue <a href="https://github.com/mitchellh/vagrant/issues/1975" class="issue-link">#1975</a>) which was solved by setting <b>root</b> as the owner of the private key (Issue <a href="https://github.com/mitchellh/vagrant/issues/1921" class="issue-link" title="The private key to connect to the machine via SSH must be owned by the user running Vagrant">#1921</a>). However it does not solve the problem in my case.
I am using a base box using VirtualBox as provider and I've tried with a generated keys and the insecure keys provided by Vagrant. I'll post the logs in the following comment.

**Comment by Helenbj** [comment]
Adding bellow two lines to Vagrantfile I can figure it out.
```
config.ssh.username = "vagrant"
config.ssh.password = "vagrant"
```
