### ISSUE TITLE
Allow global installation of plugins

### ISSUE THREAD

**Issue by sit** [hashicorp/vagrant#2457]
When attempting to use @jtimberman's vagrant-cookbook, it appears that plugins get installed so that they are only available for the user running Chef. That is, `vagrant plugin install` puts the plugins in `~/.vagrant.d`, which is typically `/root/.vagrant.d`.

There doesn't seem to be a `--global` flag or something that would put the plugins available in some location that all users can access.

This would be useful for provisioning end-user workstations with Vagrant pre-installed with all the plugins we want to use in development.

This looks to be the same request as https://groups.google.com/forum/#!topic/vagrant-up/0m03LpREVi8

**Comment by athingisathing** [comment]
This will be really helpfull when in the context of a build server using vagrant...

**Comment by MichaelMackus** [comment]
+1

**Comment by pidgypost** [comment]
+1
