### ISSUE TITLE
`vagrant ssh` is slow, takes 3+ seconds to connect

### ISSUE THREAD

**Issue by markjaquith** [hashicorp/vagrant#2462]
Vagrant is slow in general:

```
$ time vagrant noop | ack 0m

real    0m2.230s
user    0m1.938s
sys 0m0.297s
```

But `vagrant ssh` is slower still:

```
$ time vagrant ssh -c ''

real    0m5.238s
user    0m3.435s
sys 0m1.181s
```

The slowness is not SSH on the vm:

```
$ time expect -c 'spawn ssh vagrant@VAGRANTIP whoami;expect password;send "PASSWORD\n";interact'
spawn ssh vagrant@VAGRANTIP whoami
vagrant@VAGRANTIP's password: 
vagrant

real    0m0.121s
user    0m0.020s
sys 0m0.018s
```

There are about three seconds of lag when making an SSH connection through Vagrant that seem like they shouldn't have to exist.

If this connection delay is unavoidable, couldn't Vagrant open and maintain an SSH connection which it uses when `vagrant ssh -c COMMAND` commands are issued?

**Comment by joelpittet** [comment]
Still getting the same results as the OP and have `UseDNS no` already in the guest.

```
$ time vagrant ssh -c ''
Connection to 127.0.0.1 closed.

real	0m5.254s
user	0m2.541s
sys	0m0.633s
```

**Comment by shkm** [comment]
@joelpittet mitchellh [already explained](https://github.com/mitchellh/vagrant/issues/4214#issuecomment-49551965) why this is going to be slower than plain ssh.

Plug: if it bothers you, you could try [vssh](https://github.com/shkm/vssh), which bypasses the factors which slow down `vagrant ssh`.

**Comment by joelpittet** [comment]
Thanks for the tool @shkm

**Comment by mengdodo** [comment]
when you connect vagrant in homestead box  ,may be very slow and crazy!
this is a simple command  and very fast
ssh vagrant@192.168.10.10 -p 22
