### ISSUE TITLE
Virtualbox private network host-only adapters needlessly being generated

### ISSUE THREAD

**Issue by jameshilliard** [hashicorp/vagrant#2495]
I think adapter detection is being handled wrong still for private networks. If no IP is specified vagrant should first attempt to match the guest static IP to any existing host-only adapters before generating a new one, otherwise multiple adapters end up being generated, at a minimum there should be an option for this. I would say this should ideally be implemented by simply not specifying an IP address for the private_network  configuration option, rather than raising an error(I couldn't figure out how to suppress the error to debug further other than changing the vagrant source itself). Virtualbox seems to add the host IP to a somewhat random subnet on adapter creation so its difficult to create a universal config that doesn't generate unneeded interfaces. If I set an IP and it doesn't happen to match I get a new adapter that I don't want. Matching guest to host also works around the admin requests that changing adapters generates. It should also have the ability to disable/reconfigure dhcp for that network if needed although I don't think that technically would cause issues as the server would simply be ignored by both sides due to using static settings. Generating more than 1 host-only adapter should really be a last resort used if its impossible to use/reconfigure existing ones. I may try and fix this but I'm not all that familiar with ruby syntax and this should be a very simple fix from looking at the code. All the detection components are in place its just the error should be changed to calling for guest auto-detection.

**Comment by OhMeadhbh** [comment]
so we decided we're not going to do this?

i mean, i guess i can launch my vagrant box with the VirtualBox app and configure it to use the correct host only network. but it would be ideal if there were a way to tell vagrant to use an existing host-only network and not to create a second one.
