### ISSUE TITLE
Vagrant VMware provider with Cisco AnyConnect VPN tunneling all

### ISSUE THREAD

**Issue by jmaziarz** [hashicorp/vagrant#2513]
I'm using:
- MacOS 10.8.5
- VMware Fusion 6.0.2 
- Vagrant 1.3.5
- vagrant-vmware-fusion 2.0.12

My company requires all us remote workers to use Cisco AnyConnect that tunnels everything. I have a Windows 7 VM in VMware Fusion that uses vmnet8 (NAT with DHCP), gets and IP address, and can connect to my work network.

From Windows 7: ipconfig /all

Ethernet adapter Local Area Connection:

   Connection-specific DNS Suffix  . : localdomain
   Description . . . . . . . . . . . : Intel(R) PRO/1000 MT Network Connection
   Physical Address. . . . . . . . . : 00-0C-29-76-08-46
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.247.128(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Tuesday, November 19, 2013 1:38:49 PM
   Lease Expires . . . . . . . . . . : Tuesday, November 19, 2013 2:08:53 PM
   Default Gateway . . . . . . . . . : 192.168.247.2
   DHCP Server . . . . . . . . . . . : 192.168.247.254
   DNS Servers . . . . . . . . . . . : 192.168.247.2
   Primary WINS Server . . . . . . . : 192.168.247.2
   NetBIOS over Tcpip. . . . . . . . : Enabled

I'm using Ubuntu 12.04 LTS with Vagrant to build a VM. Here is my Vagrantfile:

 # -_\- mode: ruby -_-
 # vi: set ft=ruby :

 # Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :controller do |c|
    c.vm.box = "ubuntu1204-64"
    c.vm.hostname = "vcontroller"
    c.vm.network :private_network, type: :dhcp 
  end
end

At "vagrant up --provider=vmware_fusion" I would get the error:

dyld: DYLD_ environment variables being ignored because main executable (/Users/jmaziarz/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.0.12/bin/vagrant_vmware_desktop_sudo_helper_wrapper_darwin_amd64) is setuid or setgid
The VMware network device 'vmnet1' can't be started because
its routes collide with another device: 'utun0'. Please
either fix the settings of the VMware network device or stop the
colliding device. Your machine can't be started while VMware
networking is broken.

So I disabled DHCP on vmnet1

$ sudo /Applications/VMware\ Fusion.app/Contents/Library/vmnet-cfgcli vnetcfgadd VNET_1_DHCP no

Now the error is:

dyld: DYLD_ environment variables being ignored because main executable (/Users/jmaziarz/.vagrant.d/gems/gems/vagrant-vmware-fusion-2.0.12/bin/vagrant_vmware_desktop_sudo_helper_wrapper_darwin_amd64) is setuid or setgid
The VMware network device 'vmnet8' can't be started because
its routes collide with another device: 'utun0'. Please
either fix the settings of the VMware network device or stop the
colliding device. Your machine can't be started while VMware
networking is broken.

When I disable VPN it works. I don't understand why my Windows 7 VM is able to use the vmnet8 network but my Vagrant VM cannot. Thoughts?

**Comment by bgronek** [comment]
This is still an issue.

**Comment by jamesmehorter** [comment]
Yep, still an issue

**Comment by rvalente** [comment]
This is still an issue, can we re-open @mitchellh ?

**Comment by sethvargo** [comment]
See https://github.com/mitchellh/vagrant/issues/5740
