### ISSUE TITLE
corruption with shared folders on VMWare 6.02

### ISSUE THREAD

**Issue by bdcravens** [hashicorp/vagrant#2533]
This may be a VMWare issue, but it's crazy frustrating either way.

Using VMWare Fusion provider, and the end of files edited in host (via /vagrant folder and shared folders) are getting randomly truncated. Have been able to repeat consistently on multiple Ubuntu 12.04 instances, both existing and new. 

Possibly related to this VMWare 6.02 issue:
https://communities.vmware.com/thread/462543?start=0&tstart=0

This issue in Sublime Text forum seems to pretty much identify the same issue:
http://www.sublimetext.com/forum/viewtopic.php?f=3&t=14705

**Comment by kung-fu-tzu** [comment]
Still having this issue with VMware Fusion 7.1.2 (2779224).
