### ISSUE TITLE
mount_options creates invalid mount command?

### ISSUE THREAD

**Issue by bitinn** [hashicorp/vagrant#2546]
after upgrading from 1.2 to 1.3, I changed my config to this

`config.vm.synced_folder "www", "/var/www", :mount_options => ["dmode=777","fmode=777"], :nfs => true`

then on `vagrant up` i faced this issue:

```
Preparing to edit /etc/exports. Administrator privileges will be required...
[default] Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'dmode=777,fmode=777' 192.168.10.1:'/Users/teambegin/Desktop/git/leaf-server/www' /var/www

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: an incorrect mount option was specified
```

using vagrant 1.3.5 with virtualbox 4.3.2, not sure which part of the mount command are wrong, and only difference appear to be `-o` doesn't use quote to wrap option string when separating options with comma.

**Comment by feuerbach** [comment]
For the record, the working way to specify the nfs version is

```
config.vm.synced_folder "foo", "/home/vagrant/bar", :nfs => true, :mount_options => ['nfsvers=4']
```
