### ISSUE TITLE
VirtualBox COM server is not running

### ISSUE THREAD

**Issue by rgarrigue** [hashicorp/vagrant#2607]
Hi guys

I'm doing a destroy; up, and there's an issue with VirtualBox, I feel he's unable to follow the pace. I can't be very accurate about when I started having the issue, not so long ago. I just updated both VB and Vagrant to latest (4.3, 1.3.5 over windows 7 + cygwin), it didn't fixed it.

Here is an example: 

```
[garriguer@PCCLT1009 /cygdrive/d/ansible] vagrant destroy -f; vagrant up
[lyr] Forcing shutdown of VM...
[lyr] Destroying VM and associated drives...
[lyr] Running cleanup tasks for 'shell' provisioner...
Bringing machine 'lyr' up with 'virtualbox' provider...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["list", "hostonlyifs"]

Stderr: VBoxManage.exe: error: Failed to create the VirtualBox object!
VBoxManage.exe: error: Code CO_E_SERVER_EXEC_FAILURE (0x80080005) - Server execution failed (extended info not available)
VBoxManage.exe: error: Most likely, the VirtualBox COM server is not running or failed to start.
```

After this one I just tried destroy (wait a sec then separate command) up, it worked.

**Comment by itgou** [comment]
It is the virtual Box  compatibility problem. 
I found the solution finally.

find the file VBoxManage.exe in virtualBox installation menu, right click it and select property, change to maybe compatibility label, and select Windows Server 2008, save, reuse vagrant up, no wrong anymore.

notice: my windows is chinese version, I google translate to get compatibility name , maybe not accurate.
my system is widows 7 x64, use virtual 5.0.24, and not sure the vagrant version
