### ISSUE TITLE
"Configuring and enabling network interfaces" fails with ssh error

### ISSUE THREAD

**Issue by mwhahaha** [hashicorp/vagrant#2614]
I just updated to 1.4.0 and when I attempt to start up I'm getting an error when it attempts to configure eth1.  This was previously working on 1.3.5.  I'm running on OSX using VirtualBox and attempting to start up a centos box.

vagrant up output:

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'centos-min'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Fixed port collision for 22 => 2222. Now on port 2200.
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2200 (adapter 1)
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Setting hostname...
[default] Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown eth1 2> /dev/null

Stdout from the command:



Stderr from the command:
```

Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"
  config.vm.box = "centos-min"
  config.vm.hostname = "puppet-client"
  config.vm.network :private_network, ip: "192.168.101.20"
  config.ssh.forward_agent = "true"
  config.ssh.forward_x11 = "true"
  config.vm.provision :shell, :path => "bootstrap/puppetclient.sh"
end
```

When I log into the box, eth1 exists but doesn't have an ifcfg-eth1 configuration file.

When vagrant up is run with debug, here's the ERROR trace when it quits.

```
ERROR vagrant: /Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/communicators/ssh/communicator.rb:86:in `execute'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/communicators/ssh/communicator.rb:96:in `sudo'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/guests/redhat/cap/configure_networks.rb:26:in `block (2 levels) in configure_networks'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/util/retryable.rb:17:in `retryable'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/guests/redhat/cap/configure_networks.rb:25:in `block in configure_networks'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/guests/redhat/cap/configure_networks.rb:21:in `each'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/guests/redhat/cap/configure_networks.rb:21:in `configure_networks'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/guest.rb:88:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/guest.rb:88:in `capability'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtualbox/action/network.rb:123:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:14:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/synced_folders.rb:68:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:118:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/env_set.rb:19:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/provision.rb:52:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:13:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtualbox/action/set_name.rb:48:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builder.rb:116:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in `block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in `run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/call.rb:51:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builder.rb:116:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in `block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in `run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/call.rb:51:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builder.rb:116:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in `block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in `run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/call.rb:51:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/call.rb:57:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builtin/call.rb:57:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/warden.rb:34:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/builder.rb:116:in `call'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in `block in run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/util/busy.rb:19:in `busy'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/action/runner.rb:69:in `run'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/machine.rb:147:in `action'
/Applications/Vagrant/embedded/gems/gems/vagrant-1.4.0/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
```

**Comment by zeeforgellc** [comment]
I'm pretty sure I'm seeing this on vagrant 1.72, attempting to build a Centos6.4 vm on VirtualBox 4.3.20 from Windows 7.

Here's the log (--info):
C:\Vagrant>vagrant up 
Bringing machine 'gateway' up with 'virtualbox' provider...
Bringing machine 'batch' up with 'virtualbox' provider...
Bringing machine 'database' up with 'virtualbox' provider...
==> gateway: Importing base box 'centos6'...

[KProgress: 10%
[KProgress: 40%
[KProgress: 50%
[KProgress: 60%
[KProgress: 70%
[KProgress: 80%
[KProgress: 90%
[K==> gateway: Matching MAC address for NAT networking...
==> gateway: Setting the name of the VM: Vagrant_gateway_1421861290396_65350
==> gateway: Clearing any previously set network interfaces...
==> gateway: Preparing network interfaces based on configuration...
    gateway: Adapter 1: nat
    gateway: Adapter 2: intnet
==> gateway: Forwarding ports...
    gateway: 22 => 2222 (adapter 1)
==> gateway: Booting VM...
==> gateway: Waiting for machine to boot. This may take a few minutes...
    gateway: SSH address: 127.0.0.1:2222
    gateway: SSH username: vagrant
    gateway: SSH auth method: private key
    gateway: Warning: Connection timeout. Retrying...
    gateway: Warning: Connection timeout. Retrying...
    gateway: 
    gateway: Vagrant insecure key detected. Vagrant will automatically replace
    gateway: this with a newly generated keypair for better security.
    gateway: 
    gateway: Inserting generated public key within guest...
    gateway: Removing insecure key from the guest if its present...
    gateway: Key inserted! Disconnecting and reconnecting using new SSH key...
==> gateway: Machine booted and ready!
==> gateway: Checking for guest additions in VM...
    gateway: The guest additions on this VM do not match the installed version of
    gateway: VirtualBox! In most cases this is fine, but in rare cases it can
    gateway: prevent things such as shared folders from working properly. If you see
    gateway: shared folder errors, please make sure the guest additions within the
    gateway: virtual machine match the version of VirtualBox you have installed on
    gateway: your host and reload your VM.
    gateway: 
    gateway: Guest Additions Version: 4.2.12
    gateway: VirtualBox Version: 4.3
==> gateway: Configuring and enabling network interfaces...

It hangs at the last line.

**Comment by frayedknot** [comment]
I'm also seeing this.

vagrant 1.7.2
virtualbox 4.3.24
osx 10.10.2
guest is centos 7

**Comment by mikelaspina** [comment]
Same here.

vagrant 1.7.2
virtualbox 4.3.24
osx 10.10.2
fedora 21

**Comment by frayedknot** [comment]
@mikelaspina FWIW, As a workaround, I set that network to auto_config: false and I then used shell provisioning to take care of it.

**Comment by quasiben** [comment]
@frayedknot, can you describe the shell provision you do?  I'm getting this error on vagrant 1.7.2 centos 6.6

**Comment by quasiben** [comment]
should this issue be re-opened?  It seems to keep cropping up as far back as 1.4?

**Comment by sidewinder12s** [comment]
I am also getting a hang. 

vagrant 1.7.2
virtualbox 4.3.24
windows 8.1
centos 7

Says that it assumes that this command failed to run: /sbin/ifup enp0s8

I was trying to configure a private network with DHCP and telling virtualbox that it is an internal network.

**Comment by iniweb** [comment]
Same...

Vagrant 1.7.2
VirtualBox 4.3.26r98988
MacOSx 10.10.2
Ubuntu precise64

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
/sbin/ifdown eth1 2> /dev/null
Stdout from the command:
Stderr from the command:
stdin: is not a tty
```

Downgrade to 1.7.0 helped

**Comment by mazjs** [comment]
Having the same problem with Vagrant 1.7.2 (centos 6.6).

Error output:

    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    ==> default: Machine booted and ready!
    GuestAdditions 4.3.24 running --- OK.
    ==> default: Checking for guest additions in VM...
    ==> default: Setting hostname...
    ==> default: Configuring and enabling network interfaces...
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!

     ARPCHECK=no /sbin/ifup eth1 2> /dev/null

    Stdout from the command:

     Device eth1 does not seem to be present, delaying initialization.


    Stderr from the command:

**Comment by istvan-ujjmeszaros** [comment]
I have to fix this issue manualy after every box update, which is really annoying.
These are the steps I make:
```
]$ vagrant ssh
]$ sudo su -

]$ rm -rf /etc/udev/rules.d/70-persistent-net.rules 
]$ rm -rf /etc/sysconfig/network-scripts/ifcfg-eth1

]$ vim /etc/sysconfig/network-scripts/ifcfg-eth1
DEVICE=eth1
ONBOOT=yes

]$ exit
]$ exit

]$ vagrant reload
]$ vagrant ssh

]$ sudo su -
]$ vim /etc/sysconfig/network-scripts/ifcfg-eth1

# you will see the Vagrant generated code
# remove what you put in there; leave the generated stuff

]$ exit
]$ exit

]$ vagrant reload
```

**Comment by mazjs** [comment]
Sorry forgot to update this:

Actually, yah, almost the same thing I did too to make the network connection work. However, I think my case is a bit different. I have used a repackaged box which caused this issue. If I remove `/etc/udev/rules.d/70-persistent-net.rules` before packaging the box; I do not face this issue. I'm trying vagrant/ packaging it from windows 7.

Hope this helps. 

Thanks.

**Comment by skyler** [comment]
@istvan-ujjmeszaros your solution worked for me. Yosemite 10.10.3, Vagrant 1.7.2, VirtualBox 4.3.26, Centos 6.5 final.

**Comment by zeeforgellc** [comment]
FWIW, I worked around this by avoiding the key replacement altogether. I instead used a "config.ssh.private_key_path = File.expand_path()" directive in the Vagrantfile.

With that change, v1.7.2 is working fine.

**Comment by zeeforgellc** [comment]
I should also note that in an earlier provisioning step, I update /etc/sysconfig/network-scripts/ifcfg-eth0 to set "ONBOOT=yes".

I've been fine since making those changes.

**Comment by holms** [comment]
Would be nice if anyone could solve this finally?? Fresh box from veewee template, which I've converted to CentOS 7.1 doesn't work either got the same problem.

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/usr/sbin/biosdevname --policy=all_ethN -i bash: line 3: /usr/sbin/biosdevname: No such file or directory

Stdout from the command:



Stderr from the command:

bash: line 3: /usr/sbin/biosdevname: No such file or directory
```

I've tried to install biodevname package (yes. rpm exists), I've tried to set param for bootloader to stop using biosdevname.. nothing helps.

**Comment by holms** [comment]
Some progress finally:

Taken from here:
http://unix.stackexchange.com/questions/81834/how-can-i-change-the-default-ens33-network-device-to-old-eth0-on-fedora-19

Added two parameters in kickstart, to bootloader section: 

```
bootloader --location=mbr --driveorder=sda --append="net.ifnames=0 biosdevname=0"
```

And here's the next issue:

```
==> otrs: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup eth2

Stdout from the command:

ERROR    : [/etc/sysconfig/network-scripts/ifup-eth] Error, some other host already uses address 10.0.1.100.


Stderr from the command:
```

**Comment by holms** [comment]
Some progress in here... 

```
  config.vm.network "private_network", ip: opts[:private_ip], :adapter => 2
```

This is fully working for me :)

**Comment by yakarij** [comment]
Hi all, I have been banging my head against this for days now, trying all combinations of removing the udev rule 70-persistent-net.rules, adding all kinds of configuration to the network script at ifcfg-eth1, removing it and so on. Whenever I packaged the virtualbox machine and used it as a base box to spawn a new VM, I would be getting this:

```
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

ARPCHECK=no /sbin/ifup eth1 2> /dev/null

Stdout from the command:

Device eth1 does not seem to be present, delaying initialization.

Stderr from the command:
```

All that using VirtualBox 4.3.28, Vagrant 1.7.2 and a CentOS 6.5 image.

The solution that finally worked for me was to remove if cfg-eth1 and linking the udev rules file to `/dev/null` like so:

```
sudo ln -sf /dev/null /etc/udev/rules.d/70-persistent-net.rules
```

**Comment by oknate** [comment]
thanks, yakarij!  Your solution worked for me!

sudo rm /etc/udev/rules.d/70-persistent-net.rules
sudo ln -sf /dev/null /etc/udev/rules.d/70-persistent-net.rules

then rebuild the base box.

**Comment by fehomeh** [comment]
Cheers yakarij, I had the same problem with CentOS-6.7 (2.6.32-573.3.1.el6.x86_64) within Vagrant 1.7.4 and VirtualBox 5.0.2r102096 and problem still was there, your decision helped a lot! Thanks!

**Comment by xrbd** [comment]
+1 for jakarij's solution.  

The 'ln -sf /dev/null /etc/udev/rules.d/70-persistent-net.rules' was the magic for me.

Vagrant 1.8.1 on Win 7 64 bit
Scientific Linux release 6.7 (Carbon) Kernel 2.6.32-431.el6.x86_64 inside Virtualbox Version 5.0.16

**Comment by kzw** [comment]
This problem shows up when I package a ubuntu 16.04 because by default this distribution does not use `ethX` any more.  Altougth there are ways to make it use ethX, is it possible to pass in the parameter from vagrant file so that we can change this pattern to `enp0sX`

**Comment by kzw** [comment]
05057714  might be a fix for this but my version 1.8.1 does not seem to have this fix.  How do I make a new vagrant binary from source?

**Comment by josegreyes** [comment]
i am having the same issue as @kzw does. Is specifying a different O/S a workaround for this issue?

**Comment by mpictor** [comment]
Another variant. Haven't found a solution yet...
```
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

cat /sys/class/net/bonding_masters/address

Stdout from the command:

cat: /sys/class/net/bonding_masters/address: Not a directory


Stderr from the command:


```

**Comment by asifiqbal** [comment]
I am seeing this error too 
<script src="https://gist.github.com/asifiqbal/6f07cc0265689b6316a4415947310156.js"></script>

**Comment by jkobus** [comment]
anyone who is looking for a solution when sitting on ubuntu 16.04 with vagrant 1.8: installing vagrant from deb package (vagrant 1.9.8 for example) fixes this issue.
