### ISSUE TITLE
vagrant ssh -c no longer runs command in login shell

### ISSUE THREAD

**Issue by phinze** [hashicorp/vagrant#2636]
As of f0f8b4e3eeccd325e7ad5a21cd631e8db6f56681 (which provides a host of other benefits to the `vagrant ssh -c` code path!) we introduced an unexpected behavior change.

The commands now no longer run in a login shell. This is Potentially Bad (tm) because non-login shells don't have anything from `.bashrc` or `/etc/profile.d` run, and any assumptions made on state being set by these mechanisms will be broken between vagrant 1.3.5 and vagrant 1.4.0.

Here's a quick command that demonstrates the change:

```
vagrant ssh -c "shopt -q login_shell && echo 'Login shell' || echo 'Not login shell'"
```

That yields 'Login shell' on 1.3.5 and 'Not login shell' on 1.4.0.

My vote would be to restore the prior behavior by doing something like a `/bin/bash -l -c` wrapper around the command.

**Comment by mcandre** [comment]
In the netbsd/NetBSD-7.0 box, `vagrant ssh -c` does not appear to behave as a login shell, does not load /home/vagrant/.profile, /home/vagrant/.shrc, /etc/profile, /etc/shrc, etc. etc. I'm not sure if this represents a bug in Vagrant itself, or perhaps an oddity with respect to how the NetBSD box was packed.

I'm using Vagrant 2.0.0.

Sad panda.

**Comment by briancain** [comment]
Hey @mcandre - if you're experiencing a bug I recommend opening an new issue and include the box you're using, a Vagrantfile, and a debug log saved to a gist. Thanks! 😄

**Comment by mcandre** [comment]
As I said, the **netbsd/NetBSD-7.0** box does not integrate with `vagrant ssh -c` as a login shell.
