### ISSUE TITLE
Vagrant 1.4 embedded openssl lib error

### ISSUE THREAD

**Issue by nunogt** [hashicorp/vagrant#2646]
I'm using Vagrant with Ansible provisioner to run some local tasks. Some of them invoke an external script that depends on openssl, which Vagrant seems to bundle in "/Applications/Vagrant/bin/../embedded/bin/" (prepended to the $PATH variable during runtime).

When openssl is invoked from my script within Vagrant to generate some checksums, it fails and complains with the following error:

dyld: Library not loaded: /vagrant-installer/staging/embedded/lib/libssl.1.0.0.dylib
Referenced from: /Applications/Vagrant/bin/../embedded/bin/openssl
Reason: image not found

This is of course breaking my scripts and no digests are ever computed :)

**Comment by xcoderzach** [comment]
Since this is still an open issue, I thought I'd provide an ansible workaround

```yaml
- name: Do openssl thing
  local_action: shell /bin/bash --login -c 'openssl command here'
```

**Comment by fupelaqu** [comment]
@xcoderzach thanks a lot, you saved my day :)
