### ISSUE TITLE
Can't install vagrant plugin on proxy environment.

### ISSUE THREAD

**Issue by rkyymmt** [hashicorp/vagrant#2671]
Can't install vagrant plugin on proxy environment.

1.4.0 -> NG.
1.3.5 -> OK.

MacOSX Maveriks

**Comment by swansog** [comment]
excellent solution! was stuck on this for last two days....

**Comment by athingisathing** [comment]
We use a .gemrc and are hevy into the development CI with Chef DK and kitchen.  we are also behind a heavy corprate fire wall and for good reason we do not pull anything from the internet. We have a ruby repo but no matter what I do I can not get vagrant to install from an internal repo. 

I have tried all the other points listed above and even using chef exec to no evail. 

Please let me know how do get this to work.

**Comment by iguyking** [comment]
That "evil IT" department likely has a requirement from your business to do inspection of all traffic including SSL.   As such proxy systems such as zScaler, WebProxy and others will then break the SSL by doing a MITM attack most likely.   In doing so they likely have already deployed the root cert for the proxy system to your local boxes.  You can validate that by going to Chrome or Firefox for an https site.  Go into the information for that and look at who issued it.  ie. Facebook.  If it doesn't say it was issued by someone like DigiCert it is likely your proxy helping get in the middle.   

For you to be able to do a vagrant command you will need to get that root cert and make it trusted by vagrant.

Go to <Install Location>\vagrant\embedded\cacert.pem
Paste this cert into the bottom of the file.  Include the ---- BEGIN and the ----- END lines appropriately.  
Try your command again.  That fixed it for me.

**Comment by chatelao** [comment]
This finally worked with my installation:

```
set http_proxy=http://xxx.yyy.zzz.aaa:8080
set https_proxy=%http_proxy%
```
**`vagrant plugin install vagrant-proxyconf --plugin-clean-sources --plugin-source http://rubygems.org`**
