### ISSUE TITLE
Output Results of salt-call

### ISSUE THREAD

**Issue by elithrar** [hashicorp/vagrant#2678]
An option when invoking `vagrant up` or `vagrant provision` should be provided to output the results of `salt-call` whether an error (i.e. syntax error in state files) or success/failure after `salt-call` has finished its run.

Right now I have to ssh into the box and run `salt-call --local state.highstate` again to see which tasks failed. It'd be nice if vagrant could pipe this out after running the salt provisioner (or if it fails mid-run).

I couldn't find any refs to existing functionality along these lines but happy to be corrected.

**Comment by gposton** [comment]
just a note that this still is not documented.... google got me here pretty quickly though :)
