### ISSUE TITLE
Problem Windows 8.1 incompatible character encodings: IBM866 and ASCII-8BIT

### ISSUE THREAD

**Issue by ghost** [hashicorp/vagrant#2763]
D:\Dev\rails-dev-box-master>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Box 'precise32' was not found. Fetching box from specified URL for
the provider 'virtualbox'. Note that if the URL does not have
a box for this provider, you should interrupt Vagrant now and add
the box yourself. Otherwise Vagrant will attempt to download the
full box prior to discovering this error.
Downloading box from URL: http://files.vagrantup.com/precise32.box
C:/HashiCorp/Vagrant/embedded/gems/gems/childprocess-0.3.9/lib/childprocess/wind
ows/process_builder.rb:63:in `join': incompatible character encodings: IBM866 an
d ASCII-8BIT (Encoding::CompatibilityError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/childprocess-0.3.9/lib/chil
dprocess/windows/process_builder.rb:63:in`create_environment_pointer'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/childprocess-0.3.9/lib/chil
dprocess/windows/process_builder.rb:28:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/childprocess-0.3.9/lib/chil
dprocess/windows/process.rb:63:in`launch_process'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/childprocess-0.3.9/lib/chil
dprocess/abstract_process.rb:72:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/subprocess.rb:105:in`block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/safe_chdir.rb:26:in `block (2 levels) in safe_chdir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/safe_chdir.rb:25:in`chdir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/safe_chdir.rb:25:in `block in safe_chdir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/safe_chdir.rb:24:in`synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/safe_chdir.rb:24:in `safe_chdir'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/subprocess.rb:104:in`execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/subprocess.rb:24:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/downloader.rb:133:in`block in download!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/downloader.rb:132:in`download!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builtin/box_add.rb:191:in `download_box_url'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builtin/box_add.rb:74:in`block in call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builtin/box_add.rb:72:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builtin/box_add.rb:72:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builder.rb:116:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/runner.rb:69:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/busy.rb:19:in`busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/runner.rb:69:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builtin/handle_box_url.rb:73:in`block in call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builtin/handle_box_url.rb:56:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builtin/handle_box_url.rb:56:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/warden.rb:95:in`block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/warden.rb:34:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/runner.rb:69:in`block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/runner.rb:69:in`run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builtin/call.rb:51:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/warden.rb:34:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/plugins/provi
ders/virtualbox/action/check_virtualbox.rb:17:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/warden.rb:34:in`call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/runner.rb:69:in`block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/u
til/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/a
ction/runner.rb:69:in`run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/m
achine.rb:147:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.4.2/lib/vagrant/b
atch_action.rb:63:in`block (2 levels) in run'

**Comment by madhead** [comment]
The problem was my `PS1` string (I use Git Bash) with some Unicode swag.. Are there any chances this can be fixed in Vagrant?
