### ISSUE TITLE
Corrupt synced folder cache using Vagrant 1.4.2 and VMWare provider

### ISSUE THREAD

**Issue by danielbachhuber** [hashicorp/vagrant#2768]
Using Vagrant 1.4.2, the VMWare provider (VMWare Version 6.0.2-1398658) and Ubuntu 13.04, I'm regularly experiencing corrupted synced folder caches when editing synced files using Sublime Text on my Mac.

Given [this edit history](https://gist.github.com/danielbachhuber/10532f3a46db17a6259b/revisions) on a sample file, the file consistently ends up as the following inside the VM (notice the incorrect file termination point):

![image](https://f.cloud.github.com/assets/36432/1852357/0bca280c-76f9-11e3-9e19-5db3cf67fd15.png)

Making another edit to the file (even whitespace) will fix the cached representation of the file. The issue can also be resolved by running `echo 1 > /proc/sys/vm/drop_caches` as `sudo` inside the VM.

My co-worker @joehoyle runs a similar setup with Vagrant 1.3.3 and hasn't ever experienced the issue. I haven't yet tested downgrading because I upgraded the VMWare provider which requires 1.4.0

Any suggestions as to what the cause might be, or what additional debugging I can do? I switched to VMWare because of caching issues associated with VirtualBox and NFS, and it's frustrating to say the least that one caching issue has been replaced by another.

**Comment by atombender** [comment]
This issue should be reopened. Experiencing this problem with Virtualbox (latest, 4.3.22 r98236, image is Ubuntu 12.04 with kernel `3.2.0-23-generic`) and ordinary `vboxsf` mounts. @ladyrassilon's manual VM cache drop workaround resolves the problem every time.

**Comment by rvdh** [comment]
I agree with @atombender - I'm experiencing this issue as well. Debian 8 image with latest VirtualBox Version 5.0.14 r105127.
