### ISSUE TITLE
Vagrant 1.4.2 problems with OS X 10.6.8

### ISSUE THREAD

**Issue by straxus** [hashicorp/vagrant#2770]
I installed Vagrant 1.4.2 and was attempting to install a plugin, and I got an unexpected error message:

```
$ vagrant plugin install vagrant-berkshelf
Installing the 'vagrant-berkshelf' plugin. This can take a few minutes...
/Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/ext/builder.rb:62:in `run': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

    /Applications/Vagrant/embedded/bin/ruby extconf.rb
/Applications/Vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `initialize_copy': Bad file descriptor (Errno::EBADF)
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `initialize_dup'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `dup'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `<module:Logging>'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:289:in `<module:MakeMakefile>'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:47:in `<top (required)>'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from extconf.rb:2:in `<main>'
```

I also saw similar errors when I tried to update the gems inside the Vagrant embedded ruby directory. I then came across https://github.com/wayneeseguin/rvm/issues/2511 which implied that this was a problem with the binaries included in the RVM version of ruby, and tried building a new ruby 2.0.0 locally using the same process - I then overwrote the binaries in the embedded Vagrant ruby instance, and install magically worked:

```
$ vagrant plugin install vagrant-berkshelf
Installing the 'vagrant-berkshelf' plugin. This can take a few minutes...
Installed the plugin 'vagrant-berkshelf (1.3.7)'!
$
```

It appears that the embedded Ruby which is provided with Vagrant 1.4.x needs to be rebuilt with a 10.6-compatible version of Ruby, assuming 10.6 is still a supported platform (unclear from the website whether it is)

**Comment by kenny-evitt** [comment]
Just in case anyone else might find it useful, I'm going to provide some details about how I did what was described thus in the description of this issue:

> ... tried building a new ruby 2.0.0 locally using the same process - I then overwrote the binaries in the embedded Vagrant ruby instance, and install magically worked

I installed Ruby 2.0.0 with RVM – `rvm install 2.0.0`

I noted where the binaries were located by running `rvm info 2.0.0`.

I copied those binaries into the Vagrant embedded Ruby directory – `sudo cp /Users/user/.rvm/rubies/ruby-2.0.0-p643/bin/{ruby,irb,gem,rake} /opt/vagrant/embedded/bin/`.

Running `vagrant plugin install vagrant-berkshelf` then seemed to work.
