### ISSUE TITLE
Error on halt and reload

### ISSUE THREAD

**Issue by fgimenez** [hashicorp/vagrant#2775]
Hi, from 1.4.1 I am getting the following error with `vagrant reload` and `vagrant halt` commands:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

shutdown -h now

Stdout from the command:



Stderr from the command:

bash: line 2: shutdown: command not found
```

debian wheezy host and sles11sp3 guest. 

Thanks, cheers

**Comment by chilukuridevbuzz** [comment]
==> default: Attempting graceful shutdown of VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

shutdown -h now

Stdout from the command:



Stderr from the command:

bash: line 4: shutdown: command not found

**Comment by chilukuridevbuzz** [comment]
still facing the same issue
