### ISSUE TITLE
Output buffered incorrectly with Chef 11.8 / Virtualbox

### ISSUE THREAD

**Issue by kevinburke** [hashicorp/vagrant#2782]
It makes it tricky to see that anything is actually happening when you do a provision run.

More information is available at https://tickets.opscode.com/browse/CHEF-4725

**Comment by tknerr** [comment]
I'm getting this again with Vagrant 1.7.4 + Chef 12.4.1

Tried the `log_location STDOUT` workaround mentioned in CHEF-4725 but it did not help either. 

Can anyone confirm this?
