### ISSUE TITLE
Failed to upload a file to the guest VM via SCP due to a permissions

### ISSUE THREAD

**Issue by johntdyer** [hashicorp/vagrant#2804]
I am trying to reprovision a VM and I am getting the following error:

``` logs
Applications/Vagrant/bin/../embedded/gems/bin/vagrant:23:in `<main>'
 INFO interface: error: Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the user running Vagrant doesn't have
read permission on the file. Please set proper permissions on the file:

/var/folders/wb/w7qzyksn56gc8pz5mjczx0kc0000gn/T/vagrant20140110-28495-1q6u63s
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the user running Vagrant doesn't have
read permission on the file. Please set proper permissions on the file:

/var/folders/wb/w7qzyksn56gc8pz5mjczx0kc0000gn/T/vagrant20140110-28495-1q6u63s
```

However this file on the host system does not exist

``` log
# jdyer at retina in ~/Projects/chef/site-cookbooks/tropo-portal on git:12.5.0 x [22:24:22]
$ ls -la /var/folders/wb/w7qzyksn56gc8pz5mjczx0kc0000gn/T/vagrant20140110-28495-1q6u63s
gls: cannot access /var/folders/wb/w7qzyksn56gc8pz5mjczx0kc0000gn/T/vagrant20140110-28495-1q6u63s: No such file or directory
```

Environment Settings:
OSX 10.9
Vagrant 1.4.2
Virtualbox 4.3.6

**Comment by iapilgrim** [comment]
I have the same problem and 
sudo chmod 777 /tmp
works for me.

**Comment by danielrhodeswarp** [comment]
I have the experience of only realistically being able to provision files (or in my case an entire folder with [web.vm.provision :file, source: "../elasticsearch_config", destination: "/some/where/elasticsearch_config"]) into the default /vagrant shared mount OR somwehere on the VM previously created by the vagrant user.

If I try to provision into /tmp (which is 777) or even into /home/vagrant then I get these permission errors we are talking about.

It seems cheesy to me that, before I provision the file upload, I have to provision the creation of an appropriate folder on the VM. My /vagrant mount is version controlled and so I don't want to put these throwaway things in there.

Hmmm...
