### ISSUE TITLE
Specify gateway for public network

### ISSUE THREAD

**Issue by GregDThomas** [hashicorp/vagrant#2832]
This is more for the case where I have a static ip address; I'd like to be able to assign a gateway at the same time. Something like ...

config.vm.network :public_network, :mac => "0800xxxxxxxx", ip: "10.100.1.32", :netmask => "255.255.255.0", gateway: "10.100.1.254"

Currently I'm doing this with a shell script, but it seems odd you can specify address but not gateway in the configuration ...

**Comment by gregtampa** [comment]
how is this a rare request?
I have several IP addresses that have different gateways.
Should allow all parts of the network config in the setup not just the ip address.

**Comment by SaimonL** [comment]
So when is this going to be ready?
I have a server with "dedispec.com" which gives me 5 I.P addresses and I need to set gateway and netmask. Other dedicated server providers also gives more then 1 I.P where you need to set those 2 things.
