### ISSUE TITLE
VAGRANT_DEFAULT_PROVIDER is not respected

### ISSUE THREAD

**Issue by blairham** [hashicorp/vagrant#2839]
set VAGRANT_DEFAULT_PROVIDER to something other that virtual box and it will still use virtualbox as the provider.

> export VAGRANT_DEFAULT_PROVIDER=vmware_fusion
> vagrant up
> bringing machine 'default' up with 'virtualbox' provider...

**Comment by cja-github** [comment]
Please can you explain what "You have to export it in .profile (or alike)" means?
