### ISSUE TITLE
What is the grub-pc?

### ISSUE THREAD

**Issue by millisami** [hashicorp/vagrant#289]
I fired up a new box (vagrant 0.6.8) and I was updating the box with aptitude and I get this visual box asking me where to install it? 

What is this thing and which option do I have to choose?

```
Package configuration                                                                                   
 ┌──────────────────────────────────────────────┤ Configuring grub-pc ├──────────────────────────────────────────────┐  
 │ The GRUB boot loader was previously installed to a disk that is no longer present, or whose normally unique       │  
 │ identifier has changed for some reason. It is important to make sure that the installed GRUB stays in sync with   │  
 │ other components such as grub.cfg or with newer Linux images it will have to load, and so you should check again  │  
 │ to make sure that GRUB is installed to the appropriate boot devices.                                              │  
 │                                                                                                                   │  
 │ If you're unsure which drive is designated as boot drive by your BIOS, it is often a good idea to install GRUB    │  
 │ to all of them.                                                                                                   │  
 │                                                                                                                   │  
 │ Note: It is possible to install GRUB to partition boot records as well, and some appropriate partitions are       │  
 │ offered here.  However, this forces GRUB to use the blocklist mechanism, which makes it less reliable, and        │  
 │ therefore is not recommended.                                                                                     │  
 │                                                                                                                   │  
 │ GRUB install devices:                                                                                             │  
 │                                                                                                                   │  
 │    [ ] /dev/sda (42949 MB, VBOX_HARDDISK)                                                                         │  
 │    [ ] - /dev/sda1 (41420 MB, /)                                                                                  │  
 │                                                                                                                   │  
 │                                                                                                                   │  
 │                                                      <Ok>
```

**Comment by jmmirabile** [comment]
From https://help.ubuntu.com/community/Grub2/Setup, below. Also, It seems that when the grub-pc menu pops up, it indicates the current drive location as "- [drive]", for instance, it will show several options, but the current partition where grub is installed with has a hyphen in front of it. 

[ ] /dev/sda (250059 MB; ST9250410AS
[ ] - /dev/sda1 (510 MB; /boot)
[ ] /dev/sda5 (249546 MB; ST9250410AS)  

Another way to tell is with #> sudo fdisk /dev/sda (if sda is the primary disk)
Once in fdisk, type 'p' and it will print the partition table. The decide marked bootable is where it's installed. I'm not sure I agree with that statement that it's a good idea to mark them all for installation. 

File Structure
GRUB 2 incorporates a totally revised directory and file hierarchy. The menu.lst of GRUB legacy is no longer used.

To find out where GRUB 2 is installed, the user can run the following commands:

Device: sudo grub-probe -t device /boot/grub

UUID: sudo grub-probe -t fs_uuid /boot/grub

From the GRUB 2 menu at boot, the user can also determine which Ubuntu is controlling the boot on a multi-OS system. By default, the first menuentry always lists an option from the installation which is in charge of GRUB 2. For example, if the first menuentry contains "on sda5, then the GRUB installed on sda5 OS is controlling the menu/boot.

**Comment by MatheusRV** [comment]
echo "grub-pc grub-pc/install_devices multiselect     /dev/sda" | sudo debconf-set-selections

Giving a stranger error on techempower/tfb

**Comment by KingWaffleIII** [comment]
It does say to install to all devices if you're unsure which is what I did.
