### ISSUE TITLE
Change the eth0 ip because oft IP conflict

### ISSUE THREAD

**Issue by benboit** [hashicorp/vagrant#2915]
Hi, we are using the 10.0.0.0 net at work for our Servers. Server within that net are not reachable from a vagrant virtualbox. Even adding a public_network interface using DHCP only works if i explicitly set the interface eth1 in the ping Command. My solution now was to add a Route for the destination IP, but this is a annoying workaround. Is it possible to set a different eth0 IP in the vagrantfile or could this be implemented?

**Comment by killerwolf** [comment]
on a multi-vm vagrant env, this ip is always the same

**Comment by mckelvin** [comment]
According to https://www.virtualbox.org/manual/ch09.html#changenat ,

> If, for any reason, the NAT network needs to be changed, this can be achieved with the following command:
>    VBoxManage modifyvm "VM name" --natnet1 "192.168/16"

This can be fixed in `Vagrantfile`:

```ruby
  config.vm.provider "virtualbox" do |vb|
    [...]
    vb.customize ['modifyvm', :id, '--natnet1', '192.168.222.0/24']
    [...]
  end

```

ALSO SEE:

- https://github.com/mitchellh/vagrant/issues/5293

**Comment by mirzawaqasahmed** [comment]
All,
I am getting a similar problem as "killerwolf" on a multi-vm vagrant env where eth0 of all VMs are getting the same ip. How can this be fixed.

**Comment by oliver-dungey** [comment]
+1, I've got 7 VM's being created from 1 Vagrantfile with unique IP/MAC for eth1, but all the eth0 NAT interfaces have the same IP/MAC. The effect is that the Salt minions all fail to talk to the server when they come up, I assume due to IP/MAC clashes. The only workaround seems to be manually changing the NAT MAC addresses in VirtualBox.

**Comment by oliver-dungey** [comment]
Thanks @mckelvin - my Vagrantfile was booting 7 VM's that refused to talk to each other and your snippit allowed me to move off the 10.0.2 subnet. This in turn avoided some IP clash somewhere on my work network somehow. The clue was running a port scan on my vagrant provisioned salt-master - the results came back with a load of listening ports not appropriate to the VM i.e. some other machine somehwere. For reference on CentOS you can do this as follows:

```
sudo yum install nmap
sudo nmap -sT -O 192.168.0.100
```
In the above example my salt-master is 192.168.0.100 so I called nmap from a minion to see what ports it was exposing and couldn't see a listener on 4506 or any familiar services.

**Comment by ThorstenS-linux** [comment]
thanks @mckelvin - nice trick 
I defined a NAT network for every single VM in my multi-machine Vagrantfile. works now. :+1: 
```
vb.customize ['modifyvm', :id, '--natnet1', '192.168.222.0/24']
…
vb.customize ['modifyvm', :id, '--natnet1', '192.168.n.0/24']
```
