### ISSUE TITLE
Mac OSX: Incorrect mount option specified: dmode, fmode

### ISSUE THREAD

**Issue by cryptiklemur** [hashicorp/vagrant#2928]
Whenever i try and specify folder or directory permissions on the synced_folder parameter, get the following error:

``` sh
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'dmode=775' 192.168.56.1:'/Users/ascherer/Projects/neokeo-project' /var/www

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: an incorrect mount option was specified
```

Here's my config: 

``` ruby
config.vm.synced_folder "./" "/var/www",
    id: "vagrant-root",
    type: nfs,
    :mount_options => ['dmode=775', 'fmode=775']
```

**Comment by IvoPereira** [comment]
Facing the same problem with Yii2 Framework not being able to write to cache folders (assets / runtime / web/assets).

Having Apache running as www-data:www-data; all the project folders in www-data:www-data; the folders I've specified above being 775 - chmoding them to 777 reverts always to 775, but no error given.

I've already tried to set permissions in host machine, however no effect at all.

Any ideas how to workaround this?
