### ISSUE TITLE
Private network comes up with wrong IP address

### ISSUE THREAD

**Issue by ahodgkinson** [hashicorp/vagrant#2968]
My VM comes up with the wrong IP address, the very first time it is started.

I have the following in my Vagrantfile:

```
  config.vm.network :private_network, ip: "172.16.2.3", netmask: "255.240.0.0"
```
1. When I 'vagrant up' the system for the very first time, the VM comes up with the IP address 172.16.2.2, instead of 172.16.2.3. 
2. I subsequently do a 'vagrant halt' and 'vagrant up', then the correct IP address is assigned.
3. If I then do a 'vagrant destroy' and 'vagrant up' the incorrect IP address 172.16.2.2 is assigned to the VM. 

This behavior appears to be repeatable.

Curiously, when the incorrect IP address 172.16.2.2 is assigned, it appears that if I ssh to 172.16.2.3, it actually connects to my VM! (and ssh to 172.16.2.2 also works). 

Perhaps the IP 172.16.2.3 is somehow not release by the host system when the VM is destroyed?

This issue may be related to https://github.com/mitchellh/vagrant/issues/1014

Software versions:

Host machine: Ubuntu 12.04.3 LTS
VMS: Ubuntu 12.04.3 LTS
Vagrant 1.3.5
VirtualBox 4.3.0r89960

**Comment by brianm** [comment]
I have this happen to me in 1.7.2 still when using fedora-21. Bouncing the interface still works around it.

**Comment by pwm** [comment]
Same problem here with, using 1.7.2 with vmware_fusion and centos 7.1.

**Comment by cgbaker** [comment]
I've also been struggling with this with 1.7.2 with virtualbox and centos 7.1

**Comment by mgiaccone** [comment]
I had the same issue, the problem seems to be related to the VirtualBox DHCP.
I solved it with by disabling the DHCP server for the hostonly interface:

VBoxManage dhcpserver remove --ifname vboxnet1
