### ISSUE TITLE
Invalid NFS (v4) mount options for Arch Linux

### ISSUE THREAD

**Issue by tina-junold** [hashicorp/vagrant#2989]
for arch with nfs4 vagrant use invalid mount options:
Vagrant assumes that this means the command failed!

```
mount -o 'vers=4,udp' 192.168.101.1:'/home/torsten/projects/my-project' /srv/http/www

Stdout from the command:



Stderr from the command:

mount.nfs: an incorrect mount option was specified
```

the correct syntax should be something like that

```
mount -t nfs4 192.168.101.1:/home/torsten/projects/my-project /srv/http/www
```

**Comment by ikari7789** [comment]
I'm facing this same issue on CentOS 5... Is there any workaround to fix this?

**Comment by JKobyP** [comment]
FYI to those like @ikari7789 struggling with issues like these (although not specifically OP's problem), please note that Archlinux doesn't appear to support NFSv2 by default (there's a section on configuring that [on the wiki](https://wiki.archlinux.org/index.php/NFS#NFSv2_compatibility), but it's out of date.)

Changing the Vagrantfile to use `nfs_version: 3` or higher could prevent some problems if that's something you encounter. (v2 is the default for Trellis.)

**Comment by ikari7789** [comment]
I was able to get past this by hackily patching Vagrant myself to check if `nfs_version: 4` fails with the message as shown above and changing the command.

Unfortunately it seems that Vagrant doesn’t obtain OS version by default, so I implemented a rather general solution. I’d be happy to make a PR though if anyone is interested.
