### ISSUE TITLE
vmware provider expects vmware_fusion box type but current shows vmware_desktop

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/vagrant#2993]
I am using vmware 6.x and just created a new vmware box machine using packer. after adding the box to the vagrant catalog it shows a different provider.

`vagrant box list`

**ubuntu_vmware (vmware_desktop)**

The documentation expects a **vmware_fusion** provider type. 

Am i missing something.

**Comment by mark-r-stevens** [comment]
I just updated to vagrant 1.8.6. All my plugins are up to date. When I try to load a box I created with packer, I get the error below. I solved the problem by manually editing the metadata.json from packer to specify the provider as vmware_fusion.

The box you attempted to add doesn't match the provider you specified.

Provider expected: vmware_fusion
Provider of box: vmware_desktop
