### ISSUE TITLE
VMware provider hangs on starting VM

### ISSUE THREAD

**Issue by goloroden** [hashicorp/vagrant#3053]
I'm using Vagrant 1.4.3 with VMware Fusion provider on OS X. When I try to start a virtual machine with quite a usual `Vagrantfile`, Vagrant freezes while waiting for the machine to boot.

My `Vagrantfile` looks like this:

``` ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64_vmware.box"

  # MongoDB ports
  config.vm.network "forwarded_port", guest: 27017, host: 27017

  # RabbitMQ ports
  config.vm.network "forwarded_port", guest: 5672, host: 5672
  config.vm.network "forwarded_port", guest: 15672, host: 15672

  config.vm.provision "docker" do |d|
    d.run "networld/rabbitmq", args: "-p 5672:5672 -p 15672:15672"
    d.run "networld/mongodb", args: "-p 27017:27017"
  end
end
```

When I run Vagrant with `VAGRANT_LOG=info` I can see that it hangs while waiting for SSH, with the following message which is repeated over and over again:

```
INFO subprocess: Starting process: ["/Applications/VMware Fusion.app/Contents/Library/vmrun", "list"]
INFO vmware_driver: Reading an accessible IP for machine...
INFO vmware_driver: Reading VMX data...
INFO vmware_driver: Reading DHCP lease for '00:0c:29:12:08:b3' on 'vmnet8'
INFO vmware_driver: DHCP leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
INFO dhcp_lease_file: Initialized DHCP helper: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
INFO dhcp_lease_file: Looking for IP for MAC: 00:0c:29:12:08:b3
INFO dhcp_lease_file:   - IP: 
INFO ssh: SSH not up: #<Vagrant::Errors::SSHNotReady: The provider for this Vagrant-managed machine is reporting that it
is not yet ready for SSH. Depending on your provider this can carry
different meanings. Make sure your machine is created and running and
try again. Additionally, check the output of `vagrant status` to verify
that the machine is in the state that you expect. If you continue to
get this error message, please view the documentation for the provider
you're using.>
```

Any idea of what might cause this issue and how to resolve it? A restart of the host machine didn't change anything.

PS: I found the exact same issue on [Google Groups](https://groups.google.com/d/msg/vagrant-up/DaWrJjr_eDg/mNKwOhCdzVkJ), unfortunately without an answer there…

**Comment by antonsmyk** [comment]
Removing VMware state files helps:
```
sudo rm /var/db/vmware/vmnet-dhcpd-vmne*
```

**Comment by nlundquist** [comment]
This is still a serious issue. I've had this case arise, and no fix mentioned in this or or other threads related to the VM provisioner have had an effect. The VMWare provider still loops at acquiring an ip address during "Waiting for machine to boot. This may take a few minutes..."

**Comment by geerlingguy** [comment]
I was having similar issues today, and simply doing a `vagrant destroy -f` then recreating the VM again with `vagrant up` resolved the problems. In my case, I previously had the VM running in VirtualBox with the same IP address as the VMware VM that wouldn't allow me to connect (I couldn't even connect to port 22 via telnet), so maybe that was the problem.

But simply doing the below fixed it for me, and I can connect normally:

```
vagrant destroy -f
vagrant up
```

**Comment by Zowie** [comment]
Just to potentially help anyone, before you `vagrant destroy` and `vagrant up`, Reboot your computer! I know, oldest trick in the book but it has worked for me a couple of times! 

I think it's a confusion that's caused by moving your laptop between Wi-Fi spots, I've also found the issue doesn't arise when I connect to a network by cable. Might be a coincidence, but definitely worth the try :)
