### ISSUE TITLE
provisioners/docker: Ability to skip lxc / aufs dependencies from Vagrantfile

### ISSUE THREAD

**Issue by fgrehm** [hashicorp/vagrant#3103]
Docker 0.9+ no longer depends on having the userland `lxc` package around neither it requires AUFS to work (since 0.8 I think).

This basically means changing [this check](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/docker/cap/debian/docker_install.rb#L11-L14) to use some new configuration option that toggles AUFS installation and skipping [this line](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/docker/cap/debian/docker_install.rb#L19) in case the (new) execution driver config option is != `lxc`

Thoughts?

**Comment by devinrsmith** [comment]
Any thoughts on this ticket? I would be great if the dependency on AUFS was removed so I could install it on linode.

https://github.com/displague/vagrant-linode/issues/27
