### ISSUE TITLE
rsync-auto not working on Mac OS X

### ISSUE THREAD

**Issue by havvg** [hashicorp/vagrant#3108]
Hi there, I just updated to 1.5 and would like to switch from NFS share to rsync.

When running `$ vagrant rsync` everything is fine and gets updated, however running `$ vagrant rsync-auto` only outputs the following and does nothing upon file changes.

```
==> default: Watching: /Users/toni.uebernickel/Development/trnd/repository/trndSphere2
 INFO rsync-auto: Listening to paths: ["/Users/toni.uebernickel/Development/trnd/repository/trndSphere2"]
 INFO rsync-auto: Listening via: Listen::Adapter::Darwin
```

Running a manual `$ vagrant rsync` synchronises the changes correctly again.

Some debug information:

```
 INFO global: Vagrant version: 1.5.0
 INFO global: Ruby version: 2.0.0
 INFO global: RubyGems version: 2.0.14
 INFO global: VAGRANT_EXECUTABLE="/Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.5.0/bin/vagrant"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/Applications/Vagrant/bin/../embedded"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_DETECTED_OS="Darwin"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: VAGRANT_LOG="debug"
 INFO global: Plugins:
 INFO global:   - bundler = 1.5.3
 INFO global:   - i18n = 0.6.9
 INFO global:   - log4r = 1.1.10
 INFO global:   - micromachine = 1.1.0
 INFO global:   - mime-types = 2.1
 INFO global:   - rest-client = 1.6.7
 INFO global:   - vagrant-login = 1.0.0
 INFO global:   - vagrant-share = 1.0.0
 INFO global:   - vagrant-vbguest = 0.10.0
...
 INFO vagrant: `vagrant` invoked: ["rsync-auto", "--debug"
...
DEBUG host: Trying: bsd
 INFO host: Detected: bsd!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: #<Vagrant::Action::Builder:0x000001014a0180>
 INFO cli: CLI: [] "rsync-auto" ["--"]
DEBUG cli: Invoking command class: VagrantPlugins::SyncedFolderRSync::Command::RsyncAuto ["--"]
DEBUG rsync-auto: Getting target VMs for command. Arguments:
DEBUG rsync-auto:  -- names: []
DEBUG rsync-auto:  -- options: nil
DEBUG rsync-auto: Loading all machines...
 INFO rsync-auto: Active machine found with name default. Using provider: virtualbox
 INFO environment: Getting machine: default (virtualbox)
 INFO environment: Uncached load of machine.
...
==> default: Watching: /Users/toni.uebernickel/Development/trnd/repository/trndSphere2
 INFO rsync-auto: Listening to paths: ["/Users/toni.uebernickel/Development/trnd/repository/trndSphere2"]
 INFO rsync-auto: Listening via: Listen::Adapter::Darwin
```

```
$ vagrant plugin update
Updating installed plugins...
All plugins are up to date.
```

```
$ vagrant plugin list
vagrant-login (1.0.0, system)
vagrant-share (1.0.0, system)
vagrant-vbguest (0.10.0)
```

**Comment by erez-rabih** [comment]
Hi,
I am also suffering from this problem.
When I run rsync-auto and change some file under the synced folder no rsync operation is being fired.
When I run vagrant rsync I can see the changes on the VM.
The same happens when I am trying to use the vagrant-gatling-rsync plugin.
It seems that the problem is where the OS should notify the rsync listener on file changes.

I am on Mac OSX 1.9.5 and Vagrant 1.7.2

Any advice which can help me?

**Comment by tuguilucian** [comment]
same here

**Comment by erez-rabih** [comment]
I found a solution to my problem. Apparently, rsync-auto on mac doesn't work well when there are uppercase and lowercase letters in the directory name.
My directory was myAPP and rsync-auto didn't catch file changes. I then changed the directory to be myapp (all lowercase letters), fired rsync-auto again and it worked well.

Hope this will help other people who go frustrated as me :)

**Comment by danshumaker** [comment]
To help other googlers, I just found the solution to my rsync-auto problem by adding the --poll arguement to the command. mentioned [here](https://laracasts.com/discuss/channels/tips/speed-up-vagrant-file-syncing-using-rsync#reply-185212)

**Comment by SeanRoberts** [comment]
I am experiencing this issue on MacOS 10.12 and Vagrant 1.8.6.  Initial rsync works as expected but rsync-auto takes upwards of 30 seconds to catch and write a change.

**Comment by SeanRoberts** [comment]
Reinstalling rsync via homebrew seems to have solved this for me.  Adding the --poll option as @danshumaker said worked as well but it also seemed to stress my CPU and battery a fair amount.
