### ISSUE TITLE
`vagrant share` can't detect HTTP port

### ISSUE THREAD

**Issue by thasmo** [hashicorp/vagrant#3118]
Although I have forwarded port 80 and Apache is running on the VM, `vagrant share` is not able to detected the port:

```
vagrant share
==> default: Detecting network information for machine...
    default: Local machine address: 127.0.0.1
    default:
    default: Note: With the local address (127.0.0.1), Vagrant Share can only
    default: share any ports you have forwarded. Assign an IP or addres to your
    default: machine to expose all TCP ports. Consult the documentation
    default: for your provider ('virtualbox') for more information.
    default:
Vagrant was unable to detect an HTTP port for your machine.

Because your machine appears to have no static IP associated with
it, Vagrant scans through your forwarded ports, looking for one
that responds to an HTTP request. Vagrant couldn't find any
functioning HTTP port!

There are a few options to fix this error:

  1. Create a forwarded port pointing to your HTTP server inside
     your Vagrant machine.

  2. Specify an HTTP port manually with `--http-port` to this
     command.

  3. Assign a non-local address to your machine. This may or may
     not be possible depending on what provider you're using.

  4. Make sure that the HTTP server is up and running within
     your machine. Vagrant share won't start until it is
     reachable.
```

Did I miss something?

**Comment by kmark** [comment]
@IljaN had to do the same on OS X. There was no need to forward any ports via `config.vm.network`

@mitchellh Can we have this reopened or should I create a new issue?

**Comment by swreeser** [comment]
@IljaN thanks! I had the same issue and this fixed it for me.

**Comment by kmark** [comment]
@swreeser @mitchellh Not that I know of.

**Comment by icedstitch** [comment]
I've been having the same problem.  Then I found something interesting.

The web vm port forwarding was
```
Name    | Protocol | Host IP | Host Port | Guest IP | Guest Port 
tcp8080 | TCP       |             | 8080        |                | 80 
```
I wondered why it didn't have Host IP in place
```
Name    | Protocol | Host IP     | Host Port | Guest IP | Guest Port 
tcp8080 | TCP       | 127.0.0.1 | 8080        |                | 80 
```
It worked with autodiscovery!

**Comment by mcallari** [comment]
I am on OSX 10.11.1 and using vagrant 1.7.4 

vagrant share --http 80 worked for me as well.

Thanks @IljaN

**Comment by elasticsteve** [comment]
Did a new install of vagrant yesterday and from then on "vagrant share" stopped working with the same errors as original poster.

When I type "vagrant share --http 80" it works. What the hell is causing this? This is bad, because PHPstorm only has "Vagrant share" built in and I have to open the terminal now and cd into the right folder first, which takes some time.

What's really puzzling is: why did it work before? I did a clean install (removed virtualbox + vagrant first).

**Comment by mylonasg88** [comment]
Installed new Vagrant box through bash file. Can access it through ip and vhost url.

Running "vagrant share" does not work, vagrant can not find the http port.
Running "vagrant share --http 80" generates a URL. Accessing that url on the browser does not work.

Any ideas why?

```==> default: Detecting network information for machine...
    default: Local machine address: 127.0.0.1
    default:  
    default: Note: With the local address (127.0.0.1), Vagrant Share can only
    default: share any ports you have forwarded. Assign an IP or address to your
    default: machine to expose all TCP ports. Consult the documentation
    default: for your provider ('virtualbox') for more information.
    default:  
Vagrant was unable to detect an HTTP port for your machine.

Because your machine appears to have no static IP associated with
it, Vagrant scans through your forwarded ports, looking for one
that responds to an HTTP request. Vagrant couldn't find any
functioning HTTP port!

There are a few options to fix this error:

  1. Create a forwarded port pointing to your HTTP server inside
     your Vagrant machine.

  2. Specify an HTTP port manually with `--http` to this command.

  3. Assign a non-local address to your machine. This may or may
     not be possible depending on what provider you're using.

  4. Make sure that the HTTP server is up and running within
     your machine. Vagrant share won't start until it is
     reachable.
```

```vagrant share --http 80 
==> default: Detecting network information for machine...
    default: Local machine address: 127.0.0.1
    default:  
    default: Note: With the local address (127.0.0.1), Vagrant Share can only
    default: share any ports you have forwarded. Assign an IP or address to your
    default: machine to expose all TCP ports. Consult the documentation
    default: for your provider ('virtualbox') for more information.
    default:  
    default: Local HTTP port: 80
    default: Local HTTPS port: disabled
    default: Port: 2222
    default: Port: 3306
==> default: Checking authentication and authorization...
==> default: Creating Vagrant Share session...
    default: Share will be at: antsy-musk-7827
==> default: Your Vagrant Share is running! Name: antsy-musk-7827
==> default: URL: http://antsy-musk-7827.vagrantshare.com
==> default:  
==> default: You're sharing your Vagrant machine in "restricted" mode. This
==> default: means that only the ports listed above will be accessible by
==> default: other users (either via the web URL or using `vagrant connect`).```

**Comment by elasticsteve** [comment]
I have the same problem. Since yesterday not even vagrant share --http 80 works.

I have the same messages like you posted above.

When trying to access the vagrant link I get:
```
The cold-bear-7253.vagrantshare.com page isn’t working

cold-bear-7253.vagrantshare.com is currently unable to handle this request.
HTTP ERROR 500
```

**Comment by adrianmak** [comment]
After upgraded vagrant to the latest 1.9.1 (prior was running 1.8.x)
Vargant share didn't work anymore
Even though I could use --http 80 to eliminate the error message, but the web url is not accessible.

**Comment by elasticsteve** [comment]
In my case I could make it work with:
`vagrant share --http 8000`

**Comment by adrianmak** [comment]
After I fallback to version 1.8.7
The problem gone.

**Comment by elasticsteve** [comment]
Went back to 1.8.6 and `vagrant share --http 80` worked again.

Then I went back to 1.8.5 and I could even use plain `vagrant share` (which is built into PHPstorm and great to use!).

**Comment by adrianmak** [comment]
@elasticsteve 

I could use vagrant share (without specific http port 80 ) on 1.8.7

**Comment by mylonasg88** [comment]
I fixed it by adding these lines in the end of Vagrantfile:
```Vagrant.configure("2") do |config|
    config.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true
end```

It could not find where to forward ports. Now it works but very slow.

**Comment by Chashkin** [comment]
@mylonasg88 Added but still does not work, it freezes and creates a link is nothing
![image](https://cloud.githubusercontent.com/assets/24776952/21525409/2a69c450-cd2e-11e6-8353-5c7d688b30ec.png)

**Comment by martinlanglois** [comment]
@mylonasg88 that solution worked for me too, but like you said, it is painfully slow... I mean it won't work after hitting 3 pages...

**Comment by martinlanglois** [comment]
@mylonasg88  I reverted to 1.8.7 and it seems to have fixed it . 
( using vBox 5.1.10 ) on mac OSX serria

**Comment by gwtomlinson** [comment]
I'm adding my +1 to this.

1.8.7 worked fine, 1.9.1 no longer works. Reverting back to 1.8.7 and it works again.

I do this:
   vagrant share --domain a.b.c.d --name myname --http 80

On 1.9.1, accessing through http://name.a.b.c.d share just hangs indefinitely. As soon as I kill vagrant share, I get error in browser so I know it's getting through to my machine.

Revert back to 1.8.7 and domain http://name.a.b.c.d works perfectly again.

OSX El Capitan.

**Comment by ianis58** [comment]
Same problem here, but as I'm new to Vagrant and Laravel Homestead, I've never been able to setup a working vagrant share...

**Comment by Scooch** [comment]
Hey, i can get it to create a share URL but i cant access it outside of my laptop.

**Comment by elasticsteve** [comment]
There are tons of problems with Vagrant Share. This really sucks and doesn't get solved for a long time. I'm stuck at version 1.8.6 and it's slow as hell too! Docker might be the future, but then again, I don't know if you can share your environment with the outside like we do in Vagrant. I guess not very easily.
