### ISSUE TITLE
Share and virtual hosts

### ISSUE THREAD

**Issue by spescina** [hashicorp/vagrant#3152]
I have a bunch of virtual hosts on my linux guest vm.
Now I share my vm through http and I give the link to my teammates.
They can see apache responding at that url. Ok...
But I'd like to share with them my virtual hosts too. Can I?

I've tried with this workflow but it obviously doesn't work:
- dns lookup of the given url searching for the IP
- have my teammates map the vhost on that IP in their host file

**Comment by alibad** [comment]
Try http://stackoverflow.com/questions/23752968/vagrant-share-accessing-virtual-hosts-and-accessing-those-that-are-not-in-the
