### ISSUE TITLE
rsync auto command should not watch excluded folders

### ISSUE THREAD

**Issue by arnaudbreton** [hashicorp/vagrant#3159]
As far as I understand the Vagrant rsync auto command code, it watches the shared folder and subfolders.

The `rsync__exclude` parameter seems not to be used by this command, it is only used when launching the rsync command.

**Comment by whitepaperclip** [comment]
Did this stop working? My excluded folders are definitely triggering rsync calls, and I get a ton of duplicate directory warnings from Guard.
