### ISSUE TITLE
rsync selective folder sync for bidirectional syncing

### ISSUE THREAD

**Issue by tomgud** [hashicorp/vagrant#3188]
The 1.5 rsync is amazing but for production I feel there is something missing. As mentioned in #3062 rsync-pull would solve some of the problems but I feel it can be solved more completely.

I believe many users of vagrant, work on source files in the host machine, then synchronize that with the guest machine. The output is then for viewing on the host machine.

What I am suggesting is that there is a folder list that can be configured such as
- host_to_guest_folders: ["src", "lib", ...] 
- guest_to_host_folders: ["bin", "web", ...]
- ignored_folders: [".git", ...]

This would allow users to have bidirectional rsync on selective folders when users know what should be overwritten by the guest machine, and what should be overwritten by the host machine.

I imagine this could have other benefits for those who want to use rsync.

**Comment by dmatora** [comment]
consider using https://github.com/dmatora/vagrant-unison
it delivers realtime bidirectional folder sync

**Comment by ehernandez-xk** [comment]
Hi all, I'm trying to get sync my files in bidirectional way. 
After a lot of research I did not find an standard solution or is not documented.

Any suggestion about how to do rsync from host to guess and vice verse?

additional:
Where the -rz flag is used?

Thaks

**Comment by ehernandez-xk** [comment]
After a long time I decided to use **nfs** instead of **rsync** by the moment everything works.
