### ISSUE TITLE
can't start my VM on Vagrant 1.5.1

### ISSUE THREAD

**Issue by alexeyOnGitHub** [hashicorp/vagrant#3195]
Windows 7 64bit.

I have a VM created with Vagrant 1.4. I downloaded Vagrant 1.5.1 today and tried bringing the machine up with it (tried up/halt/reload) :

$~/vagrant (master)
$ vagrant reload
c:/Vagrant/embedded/lib/ruby/2.0.0/rubygems/version.rb:191:in `initialize': Malformed version number string virtualbox (ArgumentError)
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:273:in`new'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:273:in `block (2 levels) in find'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:270:in`map'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:270:in `block in find'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:416:in`block in with_collection_lock'
        from c:/Vagrant/embedded/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:415:in`with_collection_lock'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:263:in `find'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/vagrantfile.rb:147:in`block in machine_config'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/vagrantfile.rb:180:in `call'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/vagrantfile.rb:180:in`machine_config'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/vagrantfile.rb:45:in `machine'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:416:in`machine'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/command.rb:142:in `block in with_target_vms'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/command.rb:175:in`call'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/command.rb:175:in `block in with_target_vms'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/command.rb:174:in`map'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/reload/command.rb:36:in`execute'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/cli.rb:42:in `execute'
        from c:/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:248:in`cli'
        from c:/Vagrant/bin/../embedded/gems/gems/vagrant-1.5.1/bin/vagrant:158:in `<main>'

**Comment by emimarz** [comment]
+1 rm -rf ~/.vagrant.d

**Comment by lvillasica** [comment]
:100: :+1: rm -rf ~/.vagrant.d

**Comment by tbfed** [comment]
This is not a solution. I have 22 vagrant boxes built and defined, and (re)building 340gb of boxes I have spent months and months building and refining because some install/upgrade error cannot be fixed is totally uncalled for. Even the thought of having to export/reinstall/import them is seriously out of line!

**Comment by kwilczynski** [comment]
I have the same problem and nothing seem to be able to resolve it. The box is built with Packer (which should be irrelevant). I can list boxes with `vagrant box list` but any other command like e.g., `vagrant up` or `vagrant status` would fail with the aforementioned version. Prior to upgrading to latest release of Vagrant everything was working fine.

**Comment by adioe3** [comment]
What worked for me was making sure the `Vagrantfile` has the box name instead od `.`, try changing this line:

```
  config.vm.box = "."
```

to your box name, for example:

```
  config.vm.box = "centos/7"
```

You can find out the box name with `vagrant box list`:

```
$ vagrant box list
centos/7 (virtualbox, 1804.02)
```
