### ISSUE TITLE
auto setting -name in docker run command fails in vagrant 1.5

### ISSUE THREAD

**Issue by jitakirin** [hashicorp/vagrant#3216]
Error output from vagrant up/provision:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!


      rm -f /var/lib/vagrant/cids/267822e8fda447fc21978922f29abec572d85032
      docker run -cidfile=/var/lib/vagrant/cids/267822e8fda447fc21978922f29abec572d85032 -d -name pblittle/docker-logstash pblittle/docker-logstash

Stderr from the command:

2014/03/14 15:04:40 Error: Invalid container name (pblittle/docker-logstash), only [a-zA-Z0-9_.-] are allowed
```

So it looks like it doesn't like the '/'.  Could maybe use just the image name (docker-logstash in the above example) or replace the '/' with a '-' or '.'?

**Comment by alienth** [comment]
This still fails in latest vagrant if you pass a container having a hyphen in it. I believe hyphens may need to be replaced with slashes, as well.

For example, here is the result I get when running a container from a local registry using vagrant:

    Error response from daemon: Invalid container name (blah.foo.local:5000-alienth-centos-systemd), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
