### ISSUE TITLE
Boxes should be OVA compatible

### ISSUE THREAD

**Issue by josephholsten** [hashicorp/vagrant#322]
An OVA is POSIX `tar` file with the `.ovf` file first, the `.mf` file next, and everything else in the same order as listed in the `.ovf` file. It's pretty much the same thing you have now, but with an extra `//References/File[@href="Vagrantfile"]` element in the OVF and concern for ordering.

It's said more formally around line 377 in the [Open Virtualization Format Specification][http://www.dmtf.org/sites/default/files/standards/documents/DSP0243_1.1.0.pdf]

With boxes that are valid OVA files, I can convert to a VMX with a single call to `ovftool`. My continuous integration server would love you.

**Comment by bjtucker** [comment]
I was disappointed to realize after purchasing the VMware Fusion provider for vagrant that the standard vagrant boxes out there are still incompatible. After finding this thread, it's doubly frustrating to realize that they are *almost* compatible. So I'd like to voice a big +1 for another look at this, please. I can say for sure that the incompatible box format is limiting vagrant adoption in my shop.

**Comment by logicminds** [comment]
+1 for having a better way of doing this.  They should be compatible.  Does Hashicorp not have big influence on virtual box now?
