### ISSUE TITLE
rsync not included in msysgit

### ISSUE THREAD

**Issue by bryanlarsen** [hashicorp/vagrant#3236]
Your blog post claims that rsync is included in msysgit.  Unfortunately, that's not the case.

If we do switch to rsync synchronization, our getting started guide is going to increase in length substantially -- I haven't found an easy installer for rsync yet.

Perhaps you can include rsync in your Windows installer?

**Comment by ryanmc2033** [comment]
is there an update for this issue?

**Comment by cromulus** [comment]
Agreed, this would be fantastic for windows users.

**Comment by strarsis** [comment]
+1
I tried cwRsync but unix-style paths (/d/ instead D:) are passed to rsync, 
so vagrant fails when transferring the ssh key after booting the guest.
