### ISSUE TITLE
Malformed version number string virtualbox (ArgumentError) (Win8.1/64 w/Virtualbox & Vagrant 1.5.1)

### ISSUE THREAD

**Issue by YitzchokWillroth** [hashicorp/vagrant#3270]
vagrant up --debug
 INFO global: Vagrant version: 1.5.1
 INFO global: Ruby version: 2.0.0
 INFO global: RubyGems version: 2.0.14
 INFO global: VAGRANT_DETECTED_OS="CYGWIN_NT-6.3"
 INFO global: VAGRANT_EXECUTABLE="C:\Bin\Vagrant\embedded\gems\gems\vagrant-1.5.1\bin\vagrant"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="C:\Bin\Vagrant\embedded"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: VAGRANT_LOG="debug"
 INFO global: Plugins:
 INFO global:   - bundler = 1.5.3
 INFO global:   - mime-types = 2.1
 INFO global:   - rest-client = 1.6.7
 INFO global:   - vagrant-login = 1.0.1
 INFO global:   - vagrant-share = 1.0.1
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/box/plugin.rb
 INFO manager: Registered plugin: box command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/destroy/plugin.rb
 INFO manager: Registered plugin: destroy command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/halt/plugin.rb
 INFO manager: Registered plugin: halt command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/help/plugin.rb
 INFO manager: Registered plugin: help command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/init/plugin.rb
 INFO manager: Registered plugin: init command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/list-commands/plugin.rb
 INFO manager: Registered plugin: list-commands command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/package/plugin.rb
 INFO manager: Registered plugin: package command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/plugin/plugin.rb
 INFO manager: Registered plugin: plugin command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/provision/plugin.rb
 INFO manager: Registered plugin: provision command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/reload/plugin.rb
 INFO manager: Registered plugin: reload command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/resume/plugin.rb
 INFO manager: Registered plugin: resume command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/ssh/plugin.rb
 INFO manager: Registered plugin: ssh command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/ssh_config/plugin.rb
 INFO manager: Registered plugin: ssh-config command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/status/plugin.rb
 INFO manager: Registered plugin: status command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/suspend/plugin.rb
 INFO manager: Registered plugin: suspend command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/up/plugin.rb
 INFO manager: Registered plugin: up command
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/communicators/ssh/plugin.rb
 INFO manager: Registered plugin: ssh communicator
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/arch/plugin.rb
 INFO manager: Registered plugin: Arch guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/coreos/plugin.rb
 INFO manager: Registered plugin: CoreOS guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/darwin/plugin.rb
 INFO manager: Registered plugin: Darwin guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/debian/plugin.rb
 INFO manager: Registered plugin: Debian guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/esxi/plugin.rb
 INFO manager: Registered plugin: ESXi guest.
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/fedora/plugin.rb
 INFO manager: Registered plugin: Fedora guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/funtoo/plugin.rb
 INFO manager: Registered plugin: Funtoo guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/linux/plugin.rb
 INFO manager: Registered plugin: Linux guest.
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/netbsd/plugin.rb
 INFO manager: Registered plugin: NetBSD guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/omnios/plugin.rb
 INFO manager: Registered plugin: OmniOS guest.
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/openbsd/plugin.rb
 INFO manager: Registered plugin: OpenBSD guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/pld/plugin.rb
 INFO manager: Registered plugin: PLD Linux guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/redhat/plugin.rb
 INFO manager: Registered plugin: RedHat guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/solaris/plugin.rb
 INFO manager: Registered plugin: Solaris guest.
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/solaris11/plugin.rb
 INFO manager: Registered plugin: Solaris 11 guest.
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/suse/plugin.rb
 INFO manager: Registered plugin: SUSE guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/tinycore/plugin.rb
 INFO manager: Registered plugin: TinyCore Linux guest.
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/guests/ubuntu/plugin.rb
 INFO manager: Registered plugin: Ubuntu guest
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/hosts/arch/plugin.rb
 INFO manager: Registered plugin: Arch host
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/hosts/bsd/plugin.rb
 INFO manager: Registered plugin: BSD host
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/hosts/freebsd/plugin.rb
 INFO manager: Registered plugin: FreeBSD host
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/hosts/gentoo/plugin.rb
 INFO manager: Registered plugin: Gentoo host
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/hosts/linux/plugin.rb
 INFO manager: Registered plugin: Linux host
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/hosts/null/plugin.rb
 INFO manager: Registered plugin: null host
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/hosts/opensuse/plugin.rb
 INFO manager: Registered plugin: OpenSUSE host
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/hosts/redhat/plugin.rb
 INFO manager: Registered plugin: Red Hat host
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/hosts/slackware/plugin.rb
 INFO manager: Registered plugin: Slackware host
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/hosts/windows/plugin.rb
 INFO manager: Registered plugin: Windows host
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/kernel_v1/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/kernel_v2/plugin.rb
 INFO manager: Registered plugin: kernel
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/providers/hyperv/plugin.rb
 INFO manager: Registered plugin: Hyper-V provider
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/providers/virtualbox/plugin.rb
 INFO manager: Registered plugin: VirtualBox provider
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/provisioners/ansible/plugin.rb
 INFO manager: Registered plugin: ansible
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/provisioners/cfengine/plugin.rb
 INFO manager: Registered plugin: CFEngine Provisioner
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/provisioners/chef/plugin.rb
 INFO manager: Registered plugin: chef
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/provisioners/docker/plugin.rb
 INFO manager: Registered plugin: docker
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/provisioners/file/plugin.rb
 INFO manager: Registered plugin: file
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/provisioners/puppet/plugin.rb
 INFO manager: Registered plugin: puppet
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/provisioners/salt/plugin.rb
 INFO manager: Registered plugin: salt
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/provisioners/shell/plugin.rb
 INFO manager: Registered plugin: shell
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/synced_folders/nfs/plugin.rb
 INFO manager: Registered plugin: NFS synced folders
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/synced_folders/rsync/plugin.rb
 INFO manager: Registered plugin: RSync synced folders
DEBUG global: Loading core plugin: C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/synced_folders/smb/plugin.rb
 INFO manager: Registered plugin: SMB synced folders
 INFO global: Loading plugins!
 INFO manager: Registered plugin: vagrant-login
 INFO manager: Registered plugin: vagrant-share
 INFO vagrant: `vagrant` invoked: ["up", "--debug"]
DEBUG vagrant: Creating Vagrant environment
 INFO environment: Environment initialized (#Vagrant::Environment:0x3309bd0)
 INFO environment:   - cwd: D:/Projects/SevenRandolph/Playground
 INFO environment: Home path: C:/Users/yitzchokw/.vagrant.d
 INFO environment: Local data path: D:/Projects/SevenRandolph/Playground/.vagrant
DEBUG environment: Creating: D:/Projects/SevenRandolph/Playground/.vagrant
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #Vagrant::Action::Builder:0x27c8490
 INFO environment: Running hook: environment_load
 INFO loader: Set :root = #Pathname:D:/Projects/SevenRandolph/Playground/Vagrantfile
DEBUG loader: Populating proc cache for #Pathname:D:/Projects/SevenRandolph/Playground/Vagrantfile
DEBUG loader: Load procs for pathname: D:/Projects/SevenRandolph/Playground/Vagrantfile
 INFO loader: Loading configuration in order: [:home, :root]
DEBUG loader: Loading from: root (evaluating)
DEBUG loader: Configuration loaded successfully, finalizing and returning
 INFO host: Autodetecting host type for [#<Vagrant::Environment: D:/Projects/SevenRandolph/Playground>]
DEBUG host: Trying: arch
DEBUG host: Trying: freebsd
DEBUG host: Trying: gentoo
DEBUG host: Trying: opensuse
DEBUG host: Trying: redhat
DEBUG host: Trying: slackware
DEBUG host: Trying: bsd
DEBUG host: Trying: linux
DEBUG host: Trying: null
DEBUG host: Trying: windows
 INFO host: Detected: windows!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #Vagrant::Action::Builder:0x284e6c8
 INFO cli: CLI: [] "up" ["--"]
DEBUG cli: Invoking command class: VagrantPlugins::CommandUp::Command ["--"]
DEBUG command: 'Up' each target VM...
DEBUG command: Getting target VMs for command. Arguments:
DEBUG command:  -- names: []
DEBUG command:  -- options: {:provider=>nil}
DEBUG command: Loading all machines...
 INFO environment: Getting machine: default (virtualbox)
 INFO environment: Uncached load of machine.
 INFO loader: Set "21473532_machine_default" = []
 INFO loader: Loading configuration in order: [:home, :root, "21473532_machine_default"]
DEBUG loader: Loading from: root (cache)
DEBUG loader: Configuration loaded successfully, finalizing and returning
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: #Vagrant::Action::Builder:0x33f6c90
C:/Bin/Vagrant/embedded/lib/ruby/2.0.0/rubygems/version.rb:191:in `initialize': Malformed version number string virtualbox (ArgumentError)
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:273:in`new'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:273:in `block (2 levels) in find'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:270:in`map'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:270:in `block in find'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:416:in`block in with_collection_lock'
        from C:/Bin/Vagrant/embedded/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:415:in`with_collection_lock'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:263:in `find'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/vagrantfile.rb:147:in`block in machine_config'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/vagrantfile.rb:180:in `call'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/vagrantfile.rb:180:in`machine_config'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/vagrantfile.rb:45:in `machine'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:416:in`machine'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/command.rb:142:in `block in with_target_vms'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/command.rb:175:in`call'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/command.rb:175:in `block in with_target_vms'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/command.rb:174:in`map'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/up/command.rb:58:in`block in execute'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:234:in `block (2 levels) in batch'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:232:in`tap'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:232:in `block in batch'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:231:in`synchronize'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:231:in `batch'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/plugins/commands/up/command.rb:57:in`execute'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/cli.rb:42:in `execute'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/environment.rb:248:in`cli'
        from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/bin/vagrant:158:in `<main>'

**Comment by rubo77** [comment]
I think here the main problem is 

    C:/Bin/Vagrant/embedded/lib/ruby/2.0.0/rubygems/version.rb:191:in initialize': 
    Malformed version number string virtualbox (ArgumentError) 
    from C:/Bin/Vagrant/embedded/gems/gems/vagrant-1.5.1/lib/vagrant/box_collection.rb:273:innew'

I had the same issue and the reason was a `.git` folder I added inside my folder

    ~/.vagrant.d/boxes/some-mashine/.git

there should be only version numbers as folders so I guess you had a folder called `virtualbox` there.

see http://stackoverflow.com/a/28054325/1069083
