### ISSUE TITLE
Rename 'Permission Denied' Vagrant / Fileutils.rb

### ISSUE THREAD

**Issue by Zaylril** [hashicorp/vagrant#3278]
Hey,

Not sure if anyone can shed any light on this but having an intermittent issue with permissions when running librarian chef both manually and with the vagrant plugin on Win 8.1 

I get the following error:

c:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:519:in `rename': Permi
ssion denied - (c:/sites/techt/tools/vagrant/../chef/tmp/librarian/scratch/1401
0fb73a3495524c19a693de311356/windows, c:/sites/techt/tools/vagrant/../chef/tmp/
librarian/cache/source/chef/site/877777683730772c/windows/version-uri/094423e7e1
f88e74/package) (Errno::EACCES)

The odd thing is that the cookbook where it breaks varies. Sometimes it the Apache one other times aws etc. I just wondered if anyone had come across a similar issue and fixed it?

**Comment by rpEK007** [comment]
I had the same issue Win 8.1. Running cmd as an administrator helped me.
