### ISSUE TITLE
REVERT: How do I add a box from a network share?

### ISSUE THREAD

**Issue by AnthonyMastrean** [hashicorp/vagrant#3279]
I have Vagrant boxes on a NAS that I can address with a UNC path (I have full read/write privileges to this path).

``` text
//server/share/box/foo.box
```

But, I can't figure out the correct url parameter to satisfy `vagrant box add <name> <url>`. I've tried with and without the `file://` scheme. Both result in the same error.

``` bash
$ vagrant box add foo //server/share/box/foo.box

Downloading box from URL: file://server/share/box/foo.box
Download failed. Will try another box URL if there is one.
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /share/box/foo.box
```

Is this not supported or am I doing something wrong?

---

I tried to `pushd` to the share and reference the relative path, but I get the same error because vagrant resolves the full path.

``` bash
$ pushd //server/share
$ vagrant add box foo box/foo.box
```

---

I mounted the share in Windows Explorer just to get it done. There are a few goofy ways to mount in Windows and sometimes the shell treats them differently, this option seems to be the safest. 

Vagrant seems to create a bad `file://` URL.

``` bash
$ vagrant box add foo /m/box/foo.box

Downloading box from URL: file:m:/box/foo.box
Download failed. Will try another box URL if there is one.
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /box/foo.box
```

So, I wrote out the `file://` URL by hand, but it's still messing with the path

``` bash
$ vagrant box add foo file://m/box/foo.box

Downloading box from URL: file://m/box/foo.box
Download failed. Will try another box URL if there is one.
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /box/foo.box
```

**Comment by nuncanada** [comment]
Just for those looking how this works... For me, if you are inside the network drive in the Command Prompt then file://X://whatever works... But outside it doesnt...

file:////fileserver/directories/metadata.json worked fine.
