### ISSUE TITLE
An unexpected error occurred while loading the Vagrant VMware provider

### ISSUE THREAD

**Issue by ubermuda** [hashicorp/vagrant#3299]
I just upgraded to Vagrant 1.5.1, and first command I run (`vagrant destroy`) gives me this:

```
An unexpected error occurred while loading the Vagrant VMware
provider. Please contact support with the following
error code: '7'.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit
```

Here's a gist of the run with `VAGRANT_LOG=debug`: https://gist.github.com/ubermuda/d0e8944390614d212ed4

**Comment by PortNumber53** [comment]
`rm ~/.vagrant.d/plugins.json` worked for me too, didn't have to do any plugin install
