### ISSUE TITLE
Error: Connection refused. Retrying... 

### ISSUE THREAD

**Issue by shacharc** [hashicorp/vagrant#3329]
Hi , 
experiencing the following 
Vagrant 1.5.1
Vbox 4.3.6r91406
Fedora release 19 (Schrödinger’s Cat)
kernel 3.13.6-100.fc19.x86_64
box : Ubuntu Server 12.04 amd64 (with Puppet, Chef and VirtualBox 4.2.1)

always happening after resuming a suspended machine

INFO ssh: Attempting SSH connnection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 127.0.0.1
 INFO ssh:   - Port: 2222
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/home/shachar/.vagrant.d/insecure_private_key"]
 INFO ssh: SSH not ready: #<Vagrant::Errors::SSHConnectionRefused: SSH connection was refused! This usually happens if the VM failed to
boot properly. Some steps to try to fix this: First, try reloading your
VM with `vagrant reload`, since a simple restart sometimes fixes things.
If that doesn't work, destroy your VM and recreate it with a `vagrant destroy`
followed by a `vagrant up`. If that doesn't work, contact a Vagrant
maintainer (support channels listed on the website) for more assistance.>
 INFO interface: detail: Error: Connection refused. Retrying...
 INFO interface: detail:     ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...

and without debugging
Bringing machine 'ubuntuc' up with 'virtualbox' provider...
==> ubuntuc: Resuming suspended VM...
==> ubuntuc: Booting VM...
==> ubuntuc: Waiting for machine to boot. This may take a few minutes...
    ubuntuc: SSH address: 127.0.0.1:2222
    ubuntuc: SSH username: vagrant
    ubuntuc: SSH auth method: private key
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
    ubuntuc: Error: Connection refused. Retrying...
==> ubuntuc: Machine booted and ready!

**Comment by DealerUplift-DavidJohnston** [comment]
Windows 7 Host / GitHub for Windows Bash Shell

There is a good chance this can be blamed on VirtualBox but I just when through the following scenario in which this situation occurred:
[rebooting as necessary...]
* Started with VirtualBox 4.2.16 and using ubuntu/trusty64 unaltered.
* vagrant up //all good
* Ran into a dual-monitor issue while doing some work (hence the desire to upgrade...)
* Installed VirtualBox 4.3.24
* vagrant up // **immediately (timewise)** after `default: SSH auth method: private key` I see `default: Warning: Connection timeout. Retrying`.  This continues even after the login prompt appears on the VirtualBox GUI screen
* Installed VirtualBox 4.2.16 again
* vagrant up // **all good again** - the connection timeout occurs once but there is a noticeable delay  between the SSH auth method message and the first timeout.
* Installed VirtualBox 4.3.24 and then 4.3.22 in succession and get the connection timeout both times.

After ctl-c to stop the error messages I issued `vagrant ssh` and after a delay the command line reappeared; i was neither provided a shell nor was I shown any error messages.  "Command" forms did not work either.  Attempting to directly ssh using `ssh -p 2222 vagrant@localhost` resulted in a `Bad file number` exception.  Both commands were tried with 4.2.16 and work as expected.

From the VirtualBox GUI I am able to `ssh vagrant@localhost` just fine.  It is not a guest `sshd` issue that I can tell.

I'm not sure how to diagnose the issue further but my best guess right now is that binding/port-forwarding from 2222 to 22 doesn't actually take.  I do see the message `22 => 2222 (adapter 1)` even in the failing scenarios but I'm not sure how to go about proving or disproving the bindind/forwarding in Windows 7.

NB: a VirtualBox upgrade should not have any bearing on SSH keypairs; tried to figure out how to disable key authentication and use passwords but the documentation was not clear how to force that and, besides, given the symptoms above it is improbable that the keys have anything to do with this.

**Comment by DealerUplift-DavidJohnston** [comment]
Following up on this I do believe their is definite improvement to be had in the behavior of vagrant in the face of VirtualBox networking, specifically NAT port forwarding, being un-established.  The non-response from `vagrant ssh` is a prime example.

For this specific issue, though, I suspect, after reading the VirtualBox forums, that recently introduced security enhancements to the 4.3.x line and what like probably going to turn out to be a network card driver issue on my machine, are combining to cause the behavior exhibited.
