### ISSUE TITLE
speed up compression of boxes using parallel compression

### ISSUE THREAD

**Issue by berendt** [hashicorp/vagrant#3334]
The compression of large boxes takes a lot of time at the moment because the used compression tool bsdtar only runs on one core. Is it not possible to use parallel compression by using some other tool? For example http://zlib.net/pigz/.

**Comment by chrissound** [comment]
Has anyone tried just using something like http://zlib.net/pigz/? Surely if it's dramatically faster and produces the exact same tar file?

I might give this a go myself. I'm guessing I'll just need to modify this file: /lib/vagrant/action/general/package.rb (https://github.com/mitchellh/vagrant/blob/1f88a9737369eda3dede0d3aeb30928adf82a9f7/lib/vagrant/action/general/package.rb)

Hopefully my Ruby lingo is sufficient.
