### ISSUE TITLE
rsync__auto option not syncing

### ISSUE THREAD

**Issue by mirzap** [hashicorp/vagrant#3350]
I read in the documentation that there is an option for auto sync:

```
rsync__auto (boolean) - If false, then rsync-auto will not watch and automatically sync this folder. By default, this is true.
```

And I've configured synced folder like this:

```
config.vm.synced_folder "www", "/var/www",
            type: "rsync",
            rsync__auto: true,
            owner: "www-data"
```

But  it doesn't work. 

No sync is done until I run Vagrant command

`vagrant rsync-auto`

Any suggestions ?
I use Vagrant 1.5.1

**Comment by mirozoolab** [comment]
+1 for this feature.

Also, if I understood well, the option's goal is to enable auto-syncing when the 'vagrant rsync-auto' is ran, right? In this case, mentionning the cli command in the rsync__auto option may be useful, until the feature may be added. As it is written now it seems that enabling rsync__auto suffices to turn auto sync on.

**Comment by BHSPitMonkey** [comment]
I was burned by misunderstanding this, as well. I'm not sure what `rsync__auto` is even useful for in its current form; It seems intuitive that its purpose would be to instruct vagrant to run `rsync-auto` in the background for you while the box is running.

**Comment by edvinasme** [comment]
Good luck, it's not the first issue like this which I see closed without a proper fix/solution offered. I would suggest revising issue review/closing process.

**Comment by raupie** [comment]
I must have misunderstood the purpose of rsync_auto in the synced folder configuration option in the vagrant file. If this has no purpose and the only option is vagrant rsync-auto then what is the difference/purpose of it in the config?
