### ISSUE TITLE
Make .vagrant tree host-specific

### ISSUE THREAD

**Issue by odigity** [hashicorp/vagrant#3362]
I keep my local repos in a Dropbox folder so I can switch between my desktop and laptop seamlessly and still have the current state of everything be synced, including changes that haven't been committed yet.  The problem is the .vagrant tree is not host-specific, so when I've brought vagrant up on one host, then do the same on a second host, the second host overwrites the .vagrant/machines/[name]/virtualbox/id file which breaks the original host.

I did find a blog post describing the problem and a solution:

http://www.binaryphile.com/vagrant/sharing-vagrant-project-files-over-dropbox/

It's a little outdated (there's no more Virtualbox.xml anymore), but was still useful enough to help me understand the problem.  However, the described solution (manually changing the UUID on the second host to match the first) is very brittle.

I propose adding an additional directory layer to the .vagrant tree to include the host name, so the same tree can support different VM UUIDs on different hosts off the same Vagrantfile.  In order words, this:

.vagrant/machines/[name]/virtualbox/id

Would instead become one of the following (take your pick):
- .vagrant/[host]/machines/[name]/virtualbox/id
- .vagrant/machines/[host]/[name]/virtualbox/id
- .vagrant/machines/[name]/[host]/virtualbox/id
- .vagrant/machines/[name]/virtualbox/[host]/id
- .vagrant/machines/[name]/virtualbox/[host]-id

The last option has the merit of not adding another level of directory structure.

**Comment by simspace-dev** [comment]
Thank you!  Thank you!  Thank you!

**Comment by simkessy** [comment]
I don't understand what this step means

4. move .vagrant to .vagrant-laptop

**Comment by simkessy** [comment]
How do you set this for Windows?

**Comment by golfhotel** [comment]
Can you explain how to manage and configure VAGRANT_DOTFILE_PATH on Windows host?
Best regards.

**Comment by NeMO84** [comment]
Glad I read this issue. I have been developing with vagrant on my desktop and laptop separately over the last few weeks, and it became a headache trying to keep files synced.
