### ISSUE TITLE
Package Vagrant in a PPA (Personal Package Archive)

### ISSUE THREAD

**Issue by naftulikay** [hashicorp/vagrant#3366]
It's difficult to keep up to date with the latest versions of Vagrant. 

By packaging Vagrant in a Launchpad PPA, installation of the latest and greatest of Vagrant could be possible in three short commands:

```
sudo add-apt-repository ppa:vagrant/stable
sudo apt-get update
sudo apt-get install vagrant
```

**Comment by nitrocode** [comment]
Any update on this? I'd love to see an official ppa because Ubuntu still has the ancient version `1.8.1`.
