### ISSUE TITLE
color on Windows command line

### ISSUE THREAD

**Issue by mosesonline** [hashicorp/vagrant#3375]
_puppet.options = "--color=true"_
does not work, but _"puppet apply --color..."_ looks very nice :)
On Windows 7 command line interface. I looked into the code but don't know where i could set Windows 7 cli to allow color.
when I delete

``` ruby
if !@machine.env.ui.is_a?(Vagrant::UI::Colored)
       options << "--color=false"
end
```

in 
https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/puppet/provisioner/puppet.rb
my option setting obviously works.
A good solution would be for me, if vagrant wouldn't overwrite the users options.

**Comment by mbrodala** [comment]
Another option is adding the environment variable `ANSICON` with an arbitrary value. This way you don't have to append `--color` to each and every `vagrant` execution.
