### ISSUE TITLE
Automatic update checking is enabled by default.

### ISSUE THREAD

**Issue by glucas** [hashicorp/vagrant#3391]
According to the [documentation](http://docs.vagrantup.com/v2/boxes/versioning.html), automatic update checking is disabled by default and must be enabled in the Vagrantfile. 

Testing Vagrant 1.5, I see the opposite: I cannot start an existing machine without a network connection, unless I explicitly disable update checking in the Vagrantfile: 

```
> vagrant up compute1
Bringing machine 'compute1' up with 'vmware_workstation' provider...
==> compute1: Checking if box 'glucas/precise64' is up to date...
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Could not resolve host: (nil); Host not found
```

Modifying the Vagrantfile to add `config.vm.box_check_update = false` fixes this and things work fine. 

Ideally even if automatic checking _were_ enabled, the failure to connect would cause a warning rather than a fatal error.

**Comment by prajnanayak24** [comment]
Hello, 

I uncommented the  config.vm.box_check_update = false  but still facing the same error. Given the details below. All the help highly appreciated. 

**************************************************************************************************
C:\HashiCorp>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'precise32' could not be found. Attempting to find and install.
..
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'precise32' (v0) for provider: virtualbox
    default: Downloading: http://files.vagrantup.com/precise64.box
    default: Progress: 0% (Rate: 0curl:/s, Estimated time remaining: --:--:--)
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Could not resolve host: (nil); Host not found
**************************************************************************************************

This is my vagrantup file:

**************************************************************************************************
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"
    config.vm.network :private_network, ip: "192.168.33.101"
    config.vm.synced_folder "./", "/vagrant"
end
**************************************************************************************************
