### ISSUE TITLE
vagrant up - progress 90% then error - VBOX_E_FILE_ERROR

### ISSUE THREAD

**Issue by leeDav** [hashicorp/vagrant#3401]
For all my Vagrant projects, each time I `vagrant up` I see the below error.

I've tried restarting VirtualBox service, removing the precise32 box (with `vagrant box remove precise32`), restarting my Mac, updating VirtualBox and I'm stumped as this is preventing me from working.

Any help would be appreciated!

OS X: 10.9
RAM: 12 GB

``` bash
[default] Importing base box 'precise32'...
Progress: 90%There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/Users/leedavies/.vagrant.d/boxes/precise32/virtualbox/box.ovf"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /Users/leedavies/.vagrant.d/boxes/precise32/virtualbox/box.ovf...
OK.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Machine settings file '/Users/leedavies/VirtualBox VMs/precise32/precise32.vbox' already exists
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component Machine, interface IMachine
VBoxManage: error: Context: "int handleImportAppliance(HandlerArg*)" at line 779 of file VBoxManageAppliance.cpp
```

**Comment by eric-yoo** [comment]
To help those who might be struggling with the same issue, I ran into the same error today (vagrant up stopping at 90%). I found out the problem was lack of storage in my case (it was mentioned at the end of my error message). I guess if you go through the error message real carefully, the solution might be right there for you!
