### ISSUE TITLE
Making smaller base boxes

### ISSUE THREAD

**Issue by johnf** [hashicorp/vagrant#343]
Using the following procedure when creating the base box can greatly reduce it's size.

I tested by using the lucid32 base. This box is 479MB from the website.

```
vagrant up
vagrant ssh
aptitude clean
cat /dev/zero > zero.fill;sync;sleep 1;sync;rm -f zero.fill
exit
vagrant package
```

This cuts the box down to 390MB

If you go further and remove packages that won't be needed by most ie

```
sudo aptitude purge ri
sudo aptitude purge installation-report landscape-common wireless-tools wpasupplicant ubuntu-serverguide
sudo aptitude purge python-dbus libnl1 python-smartpm linux-headers-2.6.32-21-generic python-twisted-core libiw30
sudo aptitude purge python-twisted-bin libdbus-glib-1-2 python-pexpect python-pycurl python-serial python-gobject python-pam python-openssl libffi5
```

You can bring the box size down to 360MB. This one might not be worth doing but the first is probably a good idea.

**Comment by cybertk** [comment]
+1

**Comment by lferro9000** [comment]
Another area that could also be cleaned is the /var/log and the /tmp folders (if at all possible).

**Comment by acefei** [comment]
It did not work for me.
`[vagrant@localhost ~]$ cat /dev/zero > zero.fill;sync;sleep 1;sync;rm -f zero.fill
cat: write error: No space left on device`
