### ISSUE TITLE
[NFS] Administrator privileges will be required: Ask password upfront

### ISSUE THREAD

**Issue by ruudk** [hashicorp/vagrant#3439]
I have a Vagrantfile with a lot of VM's and some have NFS. When I run `vagrant up` it starts the process of bringing all the VM's up. But then after a while it asks me for the password:

```
==> web1: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
```

Most of the time I forget that I have to enter the password and thus the VM's don't come up.

Would be great if you could detect the password requirement when I start the command. Then I can type the password immediately.

**Comment by bsingarayan** [comment]
https://github.com/cogitatio/vagrant-hostsupdater/issues/50
