### ISSUE TITLE
Vagrant temp files being saved to code directory instead of ~/.vagrant.d/tmp

### ISSUE THREAD

**Issue by gauravspatel** [hashicorp/vagrant#3493]
I'm using Vagrant 1.5.3 on CentOS 6.5. When I run vagrant up, vagrant provision, etc, temp files end up saved in my code's directory.

Below is a small snippet of the ls of my code's directory.

```
vagrant20140329-1996-1bzouma         vagrant20140329-5163-c4lpx0
vagrant20140329-1996-1bzouma2        vagrant20140329-5163-c4lpx02
vagrant20140329-1996-1bzouma2.lock   vagrant20140329-5163-c4lpx02.lock
vagrant20140329-1996-fz5f8y          vagrant20140329-5488-1kjj4hq
vagrant20140329-1996-fz5f8y1         vagrant20140329-5488-1kjj4hq2
vagrant20140329-21161-1o2ucmy        vagrant20140329-5488-1kjj4hq2.lock
```

Setting VAGRANT_HOME or TMPDIR does not help the location of the cache files. I was expecting (based on the documentation) that the files be saved to ~/.vagrant.d/tmp or /tmp.  I uninstalled Vagrant, deleted ~/.vagrant.d/ and reinstalled to make sure their were no weird permissions issues on my VAGRANT_HOME.

I've set VAGRANT_LOG to debug and checked for any of the filenames or portions of the filename but they are never recorded in the debug output. 

Any ideas on which setting I could set or what is going on? Having vagrant\* files litter my code directory seems like odd behavior.

**Comment by valterhenrique** [comment]
@stumbata suggestion has worked for me! Just run `chmod +t /tmp` and you should be good to go!
