### ISSUE TITLE
vagrant 1.5.4 creates lots of files

### ISSUE THREAD

**Issue by idar** [hashicorp/vagrant#3514]
After upgrading to vagrant 1.5.4 from 1.3.5 and upgrading ubuntu to trusty, i now get lots of tmp files in my working directory:
vagrant20140422-26517-1keii7p
vagrant20140422-26517-1keii7p1
vagrant20140422-26517-5vi4pc
vagrant20140422-26517-5vi4pc2
vagrant20140422-26517-5vi4pc2.lock
vagrant20140422-2769-n0lxha
vagrant20140422-2769-n0lxha1
vagrant20140422-2769-v7ccim
vagrant20140422-2769-v7ccim2
vagrant20140422-2769-v7ccim2.lock
vagrant20140422-2806-12ecgt9
vagrant20140422-2806-12ecgt91
vagrant20140422-2806-xc87t8
vagrant20140422-2806-xc87t82
vagrant20140422-2806-xc87t82.lock
vagrant20140422-3332-7ghq7a
vagrant20140422-3332-7ghq7a1
vagrant20140422-3332-87ihle
vagrant20140422-3332-87ihle2
vagrant20140422-3332-87ihle2.lock
vagrant20140422-3355-1l70ry5
vagrant20140422-3355-1l70ry52

and folder named:
d20140422-26517-t8lbbf
d20140422-2769-cuanw3
d20140422-2806-r22le
d20140422-3332-z9a40y
d20140422-3355-8029g9

**Comment by Eugeny** [comment]
@jnankin :beer: helped me too

**Comment by codeofsumit** [comment]
I have the same issue. A lot of files are created from vagrant in the folder where my vagrant file is.
I've tried `chmod -R 1777 /tmp` without success.
Is there another possible problem?
