### ISSUE TITLE
Prompt for basic HTTP Auth credentials

### ISSUE THREAD

**Issue by martinssipenko** [hashicorp/vagrant#3531]
When trying to use a `box` that is being behind basic http auth I get following error.

```
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 401 Unauthorized
```

It would be very nice if vagrant could prompt for credentials.

**Comment by webarchitect609** [comment]
Problem still exists and putting login/password in uri is not a good idea. If vagrant uses curl why don't you use it with `--anyauth` option to let it ask if any autenthication is needed? 

Why do you leave problem without any proper solution?

**Comment by alexbowers** [comment]
We're having a similar problem too. Any chance of a revisit @mitchellh ?

**Comment by mvyletel** [comment]
I know this issue is closed but it's one of the first hits on google so here's my solution. Note that this is inspired by S3Auth plugin but works for basic auth by prompting for user/pass and passing http header to curl so the credentials are not visible on console. simply add this to Vagrantfile and it should work

```
require 'base64'
require 'vagrant/util/downloader'

#
# Extend vagrant's Downloader class to ask for basic auth credentials
module Vagrant
  module Util
    class Downloader
      @@token = ""

      def basicauth_downloader(options, subprocess_options, &data_proc)
        if @@token.empty?
          print "Username: "
          username = STDIN.gets.chomp
          print "Password: "
          password = STDIN.noecho(&:gets).chomp
          @@token = Base64.encode64("#{username}:#{password}")
        end

        options = [ "-H", "Authorization: Basic #{@@token}" ] + options
        orig_execute_curl(options, subprocess_options, &data_proc)
      end

      def execute_curl_with_basicauth(options, subprocess_options, &data_proc)
        orig_execute_curl(options, subprocess_options, &data_proc)
      rescue Errors::DownloaderError => e
        @ui.clear_line if @ui
        if e.message =~ /401 Unauthorized/
          basicauth_downloader(options, subprocess_options, &data_proc) || (raise e)
        else
          raise e
        end
      end

      alias orig_execute_curl execute_curl
      alias execute_curl execute_curl_with_basicauth
    end
  end
end
```

**Comment by webarchitect609** [comment]
@mvyletel , curl cli tool itself has mode when it could recognize resource requires basic auth and promt for password itself. Is it possible to use it in your code? 

And maybe you could try to write your own vagrant plugin? It could be very desired for lots of people :)

**Comment by mvyletel** [comment]
@webarchitect609 I've tried to let curl get it itself but it was not working. possibly because curl is run in subprocess. dunno...did not dig any further.

regarding the plugin I have some alpha version ready. will try to  polish it a little bit before pushing it to github

**Comment by webarchitect609** [comment]
@mvyletel , sounds great! Good luck! :)
