### ISSUE TITLE
make it possible to define the folder for storing the virtual maschines / harddrives

### ISSUE THREAD

**Issue by kaystrobach** [hashicorp/vagrant#3532]
it would be nice, if there would be an option to move the virtualbox/vmware config/ disks which are currently stored in `~/Virtualbox VMs` into the .vagrant folder of the VM.

This way it would be easier to move / copy the VM from one harddrive/pc/mac to another
And it would also be easier to control where the VM Data is stored.

PS: I know #1247, but that does not fix that with Multiplattform in mind :angry:

**Comment by vmmello** [comment]
This is a bit an unrelated question, but it's not very far from what is being asked here...

Is it safe for directory `$VAGRANT_HOME/boxes/` to be a symlink to an external directory, e.g. `/mount_point_with_more_space/vagrant/boxes`?

**Comment by aateeque** [comment]
Did this ever get picked up?
