### ISSUE TITLE
Windows 8.1 eat CPU if Vagrant installed

### ISSUE THREAD

**Issue by guilliman** [hashicorp/vagrant#3534]
After upgrade my PC to Windows 8.1 i have strange bug with Vagrant and i can reproduce it on clean system or even on Virtualbox Windows 8.1. I also try it on another computer and have same bug.
Installing Vagrant 1.5.4(i also try it with 1, 2 and 3 versions) and if i install any program after this my process aeinv.dll (Application Experience Program Inventory Component) (wich starting by svhost) eat 50% of my CPU :(

**Comment by jmbrinkman** [comment]
It is related to chefdk, please see https://github.com/chef/chef-dk/issues/144 for what solved it for me.

**Comment by antitoxic** [comment]
Is there any definitive answer on how to fix this. Even if I disable the tasks I still get the problem after installing some new software. 

It's not a problem for me but if `vagrant` is to be an easy way to setup environment across a distributed team, what do I advise the developers to do so they are not caught in this 100% CPU loop?
