### ISSUE TITLE
Vagrant does not display pv (pipe viewer) command output when provisioning

### ISSUE THREAD

**Issue by aaronjwood** [hashicorp/vagrant#3543]
I have very large data sets that I need to do an import of as part of my provisioning process. It's incredibly helpful to see the progress of them in realtime using pv. For some reason Vagrant doesn't display anything from pv like it should. It all still works as intended so it's really just a visual thing. Is this due to the way Vagrant internally handles output?

Here is an example of how I'm using the pv command in my provisioning script:
pv -i 1 -p -t -e /path/to/sql/file.sql | mysql -u username -ppassword

**Comment by konstantinast** [comment]
Using 1.8.1 Vagrant version and still experience'ing the same problem with pv (pipe viewer). 

As I was not able to get better solution to this problem my workaround is to use --force parameter with pipe viewer, but that result in a "spammed" vagrant up log (every second pipe viewer prints a new line with current progress and when a file is very big, then the log can get extra of hundreds or even thousands ofnot very necessary lines). To fight this unnecessary verbosity I add extra pipe viewer parameter --interval. 

To wrap it up my currently used pipe viewer and mysql dump import command combo is:

```
pv --interval 5 --force /tmp/dump.sql | mysql
``` 

If there is a more elegant solution to this problem, I would be very glad to hear it.

**Comment by RustyD** [comment]
Is this issue going to be re-opened?

**Comment by keshavkaul** [comment]
Why is this still closed?

**Comment by Kamilius** [comment]
Any progress on this one?

**Comment by PatchRanger** [comment]
+1 for re-opening this issue, it is still valid. Workaround https://github.com/hashicorp/vagrant/issues/3543#issuecomment-185430702 works - but nevertheless it is a workaround, temporal solution, not resolution.

**Comment by Zoltanpetrik** [comment]
@mitchellh This is still an issue, I've put together a Vagrantfile which demonstrates it without any external dependencies like mysql dumps..

**My environment where the issue exists:**
- Microsoft Windows [Version 10.0.17763.678]
- Using built-in Windows cmd to execute the `vagrant up` command
- Vagrant 2.2.5
- VirtualBox 6.0.6 r130049

**Vagrantfile:**
```
$script = <<-SCRIPT
#!/usr/bin/env bash

sudo su
apt-get update
apt-get install pv -y

SIZE=200000000

echo === Starting pv with workaround
head -c $SIZE </dev/urandom | pv -s $SIZE --interval 1 --force | gzip -c > /dev/null 2>&1
echo === pv with workaround finished

echo === Starting pv normally, it takes the same amount of time but the shell hangs
head -c $SIZE </dev/urandom | pv -s $SIZE | gzip -c > /dev/null 2>&1
echo === pv finished
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "pv-bug"
  config.vm.provision "shell", inline: $script
end
```
