### ISSUE TITLE
shared folder not mounting

### ISSUE THREAD

**Issue by auxbuss** [hashicorp/vagrant#355]
Hi,

The vm appears to mount v-root okay:

<pre>
$ vagrant reload
[default] Attempting graceful shutdown of linux...
[default] Running any VM customizations...
[default] Clearing any previously set forwarded ports...
[default] Forwarding ports...
[default] -- ssh: 22 => 2222 (adapter 1)
[default] Cleaning previously set shared folders...
[default] Creating shared folders metadata...
[default] Booting VM...
[default] Waiting for VM to boot. This can take a few minutes.
[default] VM booted and ready for use!
[default] Mounting shared folders...
[default] -- v-root: /vagrant
$ 
</pre>

But `/vagrant` is empty on the guest. The shared folder contents were available prior to upgrading the OS, which was created via:

<pre>
$ vagrant box add lucid32 http://files.vagrantup.com/lucid32.box
$ vagrant init lucid32
$ vagrant up
</pre>

I'm new to vagrant, so not clear how to start debugging.

**Comment by yoshiwaan** [comment]
Having dkms installed when the Virtualbox guest additions are installed is supposed to fix this I believe, but that would need fixing at the box level.

The vagrant-vbguest plugin helped fix this for me, it automatically recompiles guest additions if they're old.

**Comment by cortopy** [comment]
Thanks @yoshiwaan . The plugin worked smoothly and fixed this issue for me
