### ISSUE TITLE
rsync-auto fails when `synced_folders` data file is missing

### ISSUE THREAD

**Issue by benesch** [hashicorp/vagrant#3550]
Steps to reproduce:
1. Create a Vagrant environment with v1.5.4, and configure an rsync shared folder.
2. `vagrant up`
3. Verify that `vagrant rsync-auto` works as expected.
4. Upgrade to v1.6.x.
5. Run `vagrant rsync-auto` in the same environment. It'll crash with the following error:

```
/usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-1.6.0.dev/lib/vagrant/action/builtin/mixin_synced_folders.rb:167:in `synced_folders_diff': undefined method `each' for nil:NilClass (NoMethodError)
    from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-1.6.0.dev/plugins/synced_folders/rsync/command/rsync_auto.rb:47:in `block in execute'
    from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-1.6.0.dev/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
    from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-1.6.0.dev/lib/vagrant/plugin/v2/command.rb:220:in `each'
    from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-1.6.0.dev/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
    from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-1.6.0.dev/plugins/synced_folders/rsync/command/rsync_auto.rb:44:in `execute'
    from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-1.6.0.dev/lib/vagrant/cli.rb:42:in `execute'
    from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-1.6.0.dev/lib/vagrant/environment.rb:248:in `cli'
    from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/vagrant-1.6.0.dev/bin/vagrant:166:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.0.0-p353/bin/vagrant:23:in `load'
    from /usr/local/var/rbenv/versions/2.0.0-p353/bin/vagrant:23:in `<main>'
```

Or, with v1.6.x, remove the `synced_folders` file but leave the rest of the `.vagrant` dir intact:

```
$ rm vagrant/machines/<machine>/virtualbox/synced_folders 
```

But, obviously, this is much less likely to occur.

The problem is that `cached_synced_folders` [returns `nil` if the `synced_folders` file is missing](https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/action/builtin/mixin_synced_folders.rb#L217), but that case isn't handled by its caller: [`rsync_auto.rb:47`](https://github.com/mitchellh/vagrant/blob/master/plugins/synced_folders/rsync/command/rsync_auto.rb#L47).

**Comment by paravz** [comment]
This fix must be a reason for edge case error i experience:
- issue vagrant up
- rsync fails (VM issues with rsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]): vm is up, but synced_folders cache is not created
- manual "vagrant rsync" does not work anymore, since there is no cache file and cache returns empty set

The fix for my issue was to disable cache for rsync in plugins/synced_folders/rsync/command/rsync.rb
      folders = synced_folders(machine, cached: false)[:rsync]
and use (vagrant up; sleep 20; vagrant rsync)
