### ISSUE TITLE
The command 'vagrant up' creates a VMDK disk instead of VDI

### ISSUE THREAD

**Issue by coolguydork** [hashicorp/vagrant#3567]
When I issue the command 'vagrant up', the disk created is a vmdk file. The base image is a VDI. I want to be able to use modifyhd in the Vagrantfile, but it does not work with VMDK; the disk needs to be in VDI format.

Can we make the command create a VDI file instead of VMDK?

**Comment by gavenkoa** [comment]
What about http://crysol.github.io/recipe/2015-11-17/vagrant-vdi-virtual-disk-for-virtualbox.html

    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
      config.vm.box = "deb/jessie-i386"

      config.vm.provider :virtualbox do |vb|
        if ARGV[0] == "up" && ! File.exist?(HOME_DISK)
          vb.customize ['createhd',
                        '--filename', HOME_DISK,
                        '--format', 'VDI',
                        '--size', 50000]

          vb.customize ['storageattach', :id,
                        '--storagectl', 'SATA Controller',
                        '--port', 0,
                        '--device', 0,
                        '--type', 'hdd',
                        '--medium', HOME_DISK]
        end
      end
    end
