### ISSUE TITLE
Windows 7 machines cannot download hashicorp/precise64 box

### ISSUE THREAD

**Issue by pidah** [hashicorp/vagrant#3586]
Attempts to download the hashicorp/precise64 box fails on windows 7 running vagrant 1.5.4 with the following error:

C:\Users\xxxx\Documents\GitHub\opg-backoffice-deploy>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'hashicorp/precise64' could not be found. Attempting to find an
d install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/hashicorp/precise64"]
Error: Failed connect to vagrantcloud.com:443; No error

This works fine on on Ubuntu 12.04 and Mac OSX 10.9.2

To reproduce on a windows system, run the following 2 commands in an empty directory:

vagrant init hashicorp/precise64

vagrant up

Thanks

**Comment by stevebutler-hsdg** [comment]
Running vagrant in a CMD terminal on Windows 7, I had the same problem with a corporate proxy.  I set both HTTP_PROXY and HTTPS_PROXY, and then "vagrant box add ubuntu/trusty64" was successful.

**Comment by kaushalsingh861** [comment]
i had also this error
Error: Failed connect to atlas.hashicorp.com:443; No error
I just ran the CMD as administrator after setting HTTP proxy and it worked for me

**Comment by sundarsrd** [comment]
Had the same issue;
figured out the exact issue (in correct proxy) by using --debug option.

in my case adding the port explicitly to the HTTP_PROXY/HTTPS_PROXY worked.
ex: set http_proxy=http://192.168.x.x:80

**Comment by rajagopalan** [comment]
i am having the same issue. I was able to download the precise64,box from my corporate desktop, but my vagrant comand fails. i had setup the http_proxy as HTTP_PROXY'"http://hproxy.hh.local:3128" in system variables in a windows 7 machine.

**Comment by tanmoypal** [comment]
I was facing the same issue in Windows 8. 

C:\Users\workspace\bosh-lite>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'cloudfoundry/bosh-lite' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 9000.69.0
The box 'cloudfoundry/bosh-lite' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/cloudfoundry/bosh-lite"]
Error: Failed connect to atlas.hashicorp.com:443; No error

setting the http_proxy and https_proxy from command line fixed the issue. 

C:\Users\workspace\bosh-lite>set http_proxy=http://<corporate proxy>:8080

C:\Users\workspace\bosh-lite>set https_proxy=http://<corporate proxy>:8080

**Comment by pssayi** [comment]
Same case for me , the HTTP / HTTPS proxy setting worked.

**Comment by MartinGacheru** [comment]
how do you set port? via command git

**Comment by thesamarkand** [comment]
SOLUTION FOR USERS WITH DIRECT CONNECTION TO INTERNET:

Go to Mu$tdie firewall settings, add allowing rules for:
C:\HashiCorp\Vagrant\embedded\bin\curl.exe
C:\HashiCorp\Vagrant\bin\vagrant.exe

**Comment by srinivasreddy** [comment]
You can download the box file and add it locally . That also works.

**Comment by sanjeevlsg** [comment]
hello reddy can you send me details on local download and get vagrant up. Thanks

**Comment by sanjeevlsg** [comment]
error message Bringing machine 'oob-mgmt-server' up with 'virtualbox' provider...
==> oob-mgmt-server: Box 'CumulusCommunity/vx_oob_server' could not be found. Attempting to find and install...
    oob-mgmt-server: Box Provider: virtualbox
    oob-mgmt-server: Box Version: 1.0.4
The box 'CumulusCommunity/vx_oob_server' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/CumulusCommunity/vx_oob_server"]

**Comment by fide1** [comment]
install 
https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555

**Comment by ByteJuggler** [comment]
For reference and what it's worth: 

I've today run into this same issue.  The issue basically that that there seems to be some inconsistency in respect of the environment variables used by different vagrant sub-commands.  Some support lower case while some require upper case only. 

To reiterate, some vagrant commands/subcommands require the capitalized HTTP_PROXY variables to be set while others work with the lower case versions.   This seems at the very least surprising and arguably less than friendly behaviour.

Background: I'm reinstalling vagrant today on my PC.  During the setup I set the http_proxy and https_proxy variables in order to enable me to successfully run "vagrant plugin repair" and "vagrant login".  

However following this, running "vagrant box add ...." still failed with:

> Error: Failed to connect to vagrantcloud.com port 443: Timed out

I then searched and found this issue, from which I got the idea to _also_ set the capitalized environment varaibles e.g. HTTP_PROXY and HTTPS_PROXY.  After doing so the "vagrant box add ..." command started working as expected.

Obviously it would be better if all the vagrant command supported both lower and uppercase environment variables.

**Comment by himagarg** [comment]
Facing same issue, ran below command and its working fine
set https_proxy=http://username:password@URL

**Comment by khayapro** [comment]
Make sure that your corporate proxy is set as follows:
set HTTP_PROXY=http://username:password@proxy:8080
set HTTPS_PROXY=http://username:password@proxy:8080

Note: Dont put 's' in your HTTPS_PROXY variable value 
The above worked for me.
