### ISSUE TITLE
VirtualBox/Ubuntu: ":mac" option for "private_network" configurations does not successfully set the mac address.

### ISSUE THREAD

**Issue by philgebhardt** [hashicorp/vagrant#3588]
Using Vagrant, I am currently trying to set up a private_network interface on my hashicorp/precise32 box (with VirtualBox) and configure this interface with a MAC address of "5C:A1:AB:1E:00:01". I have not seen an explicit example of this use anywhere as all of the examples use public network (bridged) interfaces. However the documentation shows that the :mac option is available for private network interfaces. I have tried the following combinations so far: 

Syntax v1 

``` ruby
config.vm.network :hostonly, "192.168.33.10", :mac => "5CA1AB1E0001" 
```

Syntax v2 

``` ruby
config.vm.network "private_network", ip: "192.168.33.11", :mac => "5CA1AB1E0001" 
```

``` ruby
config.vm.network :private_network, ip: "192.168.33.11", :mac => "5CA1AB1E0001"
```

All three of the above lines successfully passes the Vagrant ruby parser, however none of these lines successfully change the mac address of the network adapter.

Solutions for setting mac address (syntax v1 and v2) for public (bridged) networks.

I have seen examples of the :mac option, but I can only apply it to public network setups. Specifying "private_network" in place of public network successfully launched the VM, but fails to change the mac address of the public interface (eth1).

EDIT (04/30/2014 1:45 PST):
I have further determined that the above syntax for setting mac addresses on private network adapters is being ignored. I compared the results of configuring a public network versus a private network when intentionally trying to break the setup of this VM (by passing an invalid MAC address).

Private Network (Produces no VBoxManager error)

``` ruby
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.network "private_network", ip: "192.168.33.11", :mac => "THISSHOULDBREAK"
end
```

Public Network (Produces error as expected)

``` ruby
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
   config.vm.network "public_network", :mac => "THISSHOULDBREAK"
end
```

Error:

``` bash
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'hashicorp/precise32'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'hashicorp/precise32' is up to date...
==> default: Setting the name of the VM: vagrant-test_default_1398890403706_81416
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "8882b4c9-2848-467a-909f-2fd156c9f5c6", "--nic1", "nat", "--nic2", "bridged", "--bridgeadapter2", "Intel(R) 82579LM Gigabit Network Connection", "--cableconnected2", "on", "--macaddress2", "THISSHOULDBREAK"]

Stderr: VBoxManage.exe: error: Invalid MAC address format
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component NetworkAdapter, interface INetworkAdapter, callee IUnknown
VBoxManage.exe: error: Context: "COMSETTER(MACAddress)(Bstr(ValueUnion.psz).raw())" at line 1789 of file VBoxManageModifyVM.cpp
```

**Comment by v6** [comment]
Can Vagrant VMs only be changed to a specific MAC address?

**Comment by kikitux** [comment]
Hello, You are commenting on a issue that is closed, it may never get a reply.

mac are auto generated on first boot on virtualbox/vmware

if you send an email to the mailing list, probably you will get an answer

Alvaro.
