### ISSUE TITLE
upgrading to 1.5.4 problem: vagrant up gives error downloading file

### ISSUE THREAD

**Issue by lmcardle** [hashicorp/vagrant#3589]
I have been using vagrant with no issues for a long time.  All of a sudden though, I am not able to run vagrant up, right after running vagrant init <some file path>.  When I run vagrant up I get the error:

"An error occurred while downloading the remote file. The error message, if any, is reproduced below. Please fix this error and try again."  

No other error message is given.

Everything works fine with boxes that are already added to vagrant.  however, even that, I get the same error when I try to add new boxes to vagrant: i.e vagrant box add <path to box file> --name someName

Any thoughts on what might have gone wrong?  The only change I made was upgrading to the latest version of vagrant, 1.5.4.  I tried uninstalling and re-installing an earlier version, but I still have the same issue.  I never had this issue prior to installing 1.5.4.

**Comment by brandocorp** [comment]
I just got a new laptop and I was experiencing this same issue with OSX 10.10.3, and Vagrant 1.7.2. I did some digging and found a couple of LD [environment variables](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/dyld.1.html) that can be set to get some extra info.

So I ran the following:

```bash
export DYLD_PRINT_LIBRARIES_POST_LAUNCH=true
export DYLD_PRINT_ENV=true
export VAGRANT_LOG=debug
```

Then I ran a vagrant up, and saw this in the logs
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'opscode-ubuntu-14.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Adding box 'opscode-ubuntu-14.04' (v0) for provider: virtualbox
    default: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box

...

 INFO subprocess: Starting process: ["/opt/vagrant/bin/../embedded/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.7.2", "--continue-at", "-", "--output", "/Users/502432254/.vagrant.d/tmp/boxeba23a130f268f1259a10662301d0f8723c26517", "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box"]
 INFO subprocess: Command in the installer. Specifying DYLD_LIBRARY_PATH...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: DYLD_INSERT_LIBRARIES=/usr/lib/dgagent/libpreload.dylib

...

dyld: loaded: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
dyld: loaded: /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
DEBUG subprocess: stderr: dyld: unloaded: /usr/lib/dgagent/libpreload.dylib
dyld: Symbol not found: _iconv
  Referenced from: /usr/lib/libcups.2.dylib
  Expected in: /opt/vagrant/bin/../embedded/lib/libiconv.2.dylib
 in /usr/lib/libcups.2.dylib
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 5
 WARN downloader: Downloader exit code: 5
```

The important bits seems to be this:

```
DEBUG subprocess: stderr: DYLD_INSERT_LIBRARIES=/usr/lib/dgagent/libpreload.dylib
DEBUG subprocess: stderr: dyld: unloaded: /usr/lib/dgagent/libpreload.dylib
```

I did some quick google searching but I couldn't find much about that file or what it is. However, after running the following command, I was able to successfully start a box download:

```
export DYLD_INSERT_LIBRARIES=
```

I tried just unsetting the environment variable, but that did not work.

This seems to be a better compromise than commenting out the line from `subprocess.rb`. Anyone have any thoughts?

**Comment by saurabh-agrawal83** [comment]
Following command did the trick with Vagrant 1.7.2

`export DYLD_INSERT_LIBRARIES=`
