### ISSUE TITLE
base_mac is totally undocumented

### ISSUE THREAD

**Issue by aspiers** [hashicorp/vagrant#3609]
Both manual and [Google search for `base_mac` on vagrantup.com](https://www.google.co.uk/search?q=base_mac+site%3Avagrantup.com&oq=base_mac+site%3Avagrantup.com&aqs=chrome..69i57.3734j0j4&sourceid=chrome&es_sm=121&ie=UTF-8#q=%22base_mac%22+site:vagrantup.com+) come up empty, and yet there are oblique references to it in several places, e.g.
- http://friendsofvagrant.github.io/v1/docs/config/vm/base_mac.html
- https://github.com/mitchellh/vagrant/issues/48#issuecomment-179850
- the end of https://docs.vagrantup.com/v2/virtualbox/boxes.html

Also `vagrant package` creates fresh boxes whose `Vagrantfile` has a `base_mac` line built-in.  Maybe the assumption is that because `vagrant package` automatically takes care of it, noone needs to understand it.  But isn't it reasonable to expect some people to be building boxes manually?  Even when editing boxes generated by `vagrant package`, it's good to not have to guess what `base_mac` is there for.

**Comment by jkugler** [comment]
The FreeBSD 10.4 box fails without it as well (found this issue trying to figure out how to set this via kitchen). For reference: freebsd/FreeBSD-10.4-RELEASE
