### ISSUE TITLE
Regular VBoxManage error on vagrant destroy

### ISSUE THREAD

**Issue by davebirch** [hashicorp/vagrant#3612]
I've seen this issue intermittently since I started using vagrant, but I'm pretty convinced that it's appearing more regularly in recent weeks. The error displayed is always very similar to:

``` text
==> centosminion3: Forcing shutdown of VM...
==> centosminion3: Destroying VM and associated drives...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["unregistervm", "4eff2be3-ea34-4c3b-b4fc-54783ad7be2f", "--delete"]

Stderr: 0%...10%...20%...30%...
Progress state: VBOX_E_INVALID_OBJECT_STATE
VBoxManage.exe: error: Machine delete failed
VBoxManage.exe: error: Medium 'C:\Users\username\VirtualBox VMs\centos-64-x64-vbox4210\box-disk1_5.vmdk' is locked for reading by another task
VBoxManage.exe: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component Medium, interface IMedium
VBoxManage.exe: error: Context: "int __cdecl handleUnregisterVM(struct HandlerArg *)" at line 166 of file VBoxManageMisc.cpp
```

Retrying the vagrant destroy command after seeing the error shows a ""VM not created. Moving on.." message for that VM, so it seems that despite the failure, the destroy command is successfully completing in the background.

Currently using:
vagrant 1.5.4
VirtualBox 4.3.10 r93012
Windows 7

No real idea of specific steps to reproduce this one, but I've seen it very regularly recently when shutting down multi-machine vagrant instances (every couple of attempts to destroy a 2-3 machine

I had assumed that it was just some process on the VM accessing the disk that was causing the issue, although strangely, I've even seen the error once or twice when destroying suspended VMs, which I would have thought would have precluded any disk access.

Sorry for the rather vague bug report, please let me know if there's anything else I can do to give you more info on the problem.

**Comment by matt-richardson** [comment]
We are also finding this happening frequently now. 
Using vagrant 1.7.2, Virtualbox 4.3.20 r96997.

We've only just started seeing it, and it happened just after we upgraded to the latest versions.

Its not consistent though - if we re-run the job (its only happening on our CI agents) it usually passes.
