### ISSUE TITLE
SMB share freezes

### ISSUE THREAD

**Issue by jyggen** [hashicorp/vagrant#3635]
Me and a co-worker are having an issue with shared folders using SMB. For some reason the SMB share seems to freeze everything on the server that tries to access it. This is not always the case, and a simple `vagrant reload` will fix the issue, but it reappears after a while again. 

When this issue starts to appear, trying to `cd` into the share (in this case /var/www) will freeze the SSH session:
![vagrant issue](http://i.imgur.com/Ro8L9De.jpg)

Just writing /var/w and autocomplete with tab will do the same thing. According to my co-woker `cd /var` will freeze as well.

Nginx also stops working, the connection will eventually time out when trying to access any of the sites. If I try to reload nginx (`sudo service nginx reload`) I end up with an empty prompt similar to the one in the screenshot above. I've tried to remove every site that is located on the SMB share from the nginx config and (if I remember correctly) nginx started to work again.

This is the SMB config:

``` ruby
config.vm.synced_folder "www/", "/var/www", type: "smb"
```

Not really sure how to debug this further, so any advice is appreciated.

Edit: After writing this it appeared again. Maybe it's related to letting the box/share idle for a while?

**Comment by cbrunnkvist** [comment]
Ran into this issue now. Indeed it seems like the mount client-or-server end will timeout after a certain period: at that point, the cifs client will wait seemingly forever for a reply and then you get the same exact situation as with an nfs mount -o=hard waiting forever for a reply. Cron job...oh well, that is one workaround. 
:fearful:

**Comment by cbrunnkvist** [comment]
The server IP address being used for the mount is the main one on the first interface of the host, but I think it should be using the "closest" address i.e. `10.0.2.2` in the default case. 

I realized this while looking at the "has not responded in 120 seconds" syslog message: _of course_ it will not respond as the host main interface had received a new DHCP assignment (and how is the client supposed to know that)

**Comment by cbrunnkvist** [comment]
Changed it to     

    config.vm.network "private_network", ip: "192.168.50.4"
    config.vm.synced_folder "./", "/vagrant", type: "smb", mount_options: ['ip=192.168.50.1'] #host side of that :private_network

but still have not been able to verify to a 100% that this actually alleviates the share-stops-working situation..
