### ISSUE TITLE
rsync change the owner and group of excluded directories

### ISSUE THREAD

**Issue by jderusse** [hashicorp/vagrant#3645]
The patterns specified in `rsync__exclude` are exclude from synchronisation, but the method `rsync_post` change the owner and the group of everything under `guestpath`.

This is a problem, when the application store local data (like logs) into a `%app_dir%/logs` : I specify `["logs/"]` in `rsync__exclude` to prevent my host to erase the guest content.  But after a sync, the guest can't write into his logs directory (no more the owner).

NB: For other reasons,  the owner of the `%app_dir%` can not be the same that the owner of the `%app_dir%/logs`.

**Comment by schkovich** [comment]
I am jumping in kind of late but filter with [hide](http://linuxcommand.org/man_pages/rsync1.html) option did the trick.
```
  sync_paths.each do |key, folder|
    unless folder['source'].empty? || folder['target'].empty?
      sync_owner = !folder['sync_owner'].nil? ? folder['sync_owner'] : 'vagrant'
      sync_group = !folder['sync_group'].nil? ? folder['sync_group'] : 'vagrant'
      config.vm.synced_folder "#{folder['source']}", "#{iac_path}/#{folder['target']}",
      group: "#{sync_group}", owner: "#{sync_owner}", mount_options: folder['mount_options'],
      type: "#{provider['sync_type']}",
      rsync__args: ["--verbose", "--archive", "--delete", "--filter=H app/tmp", "-z", "--links"],
      rsync__exclude: folder['rsync__exclude']
    end
  end
```
`app/tmp` does not exist in source. Ownership is not changed when rsync runs.
