### ISSUE TITLE
ansible can't provision two machines at once

### ISSUE THREAD

**Issue by khadrin** [hashicorp/vagrant#3691]
After upgrading to 1.6, I'm getting the following error when provisioning two separate machines at the same time with Ansible:

```
==> javaplay: Running provisioner: ansible...
An action 'read_ssh_info' was attempted on the machine 'autocomplete',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.
```

It looks like [ansible/provisioner.rb](https://github.com/mitchellh/vagrant/blob/925eb47cb75892e5b38db181061deb73f87394af/plugins/provisioners/ansible/provisioner.rb) iterates all active machines to generate a single inventory file for Ansible. Could the inventory file be per-machine?

**Comment by kenorb** [comment]
You can provision two machines at the same time by changing dynamically `config.vm.define` value, e.g.

    config.vm.define "default-#{variable}"

See: [Multiple providers in a single vagrant file?](http://stackoverflow.com/q/17059982/55075)
