### ISSUE TITLE
1.6 - “Vagrant locks each machine for access by only one process at a time.”

### ISSUE THREAD

**Issue by jeffreylo** [hashicorp/vagrant#3693]
[The changelog for Vagrant 1.6](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#160-may-6-2014) introduced this core change to prevent multiple vagrant `up` actions, but there are use cases where multiple processes ought to be allowed, e.g., simultaneous `logs` processes against a single machine.

It may be ideal to blacklist actions that ought to lock a machine (such as `vagrant up`).

**Comment by kenorb** [comment]
Similar issue for AWS plugin: #428, #457
