### ISSUE TITLE
Please change the VAGRANT_DOTFILE_PATH from env variable to config option

### ISSUE THREAD

**Issue by leomeih** [hashicorp/vagrant#3705]
Vagrant is really amazing and thank you for your great work!  
But the exported env variable VAGRANT_DOTFILE_PATH is sometimes flushed by other shell scripts.  
It's very annoying to export it every time before running 'vagrant status' or 'vagrant ssh'.  
Now I have to use 'vagrant global-status' to find the active vm id from time to time on a Win7 cygwin environment.  
Unlike VAGRANT_HOME which is a permanent setting, VAGRANT_DOTFILE_PATH needs more flexibility especially with the vagrant-cachier plugin.  

Could you please make a 'config.vagrant.dotfile_path' as default config in Vagrantfile and let the env variable VAGRANT_DOTFILE_PATH serve as an optional config?

Thanks.

**Comment by chrisinajar** [comment]
@adrouare I improved your code slightly. It now properly respects "quoted arguments" and success/failure return values.

```ruby
VAGRANT_DOTFILE_PATH = 'custom/dotfile/path';
currpath = ENV['VAGRANT_DOTFILE_PATH'];
if(currpath.nil?)
    currpath = '.vagrant';
end
puts currpath #debugging
if(currpath != VAGRANT_DOTFILE_PATH)
    ENV['VAGRANT_DOTFILE_PATH'] = VAGRANT_DOTFILE_PATH
    ret = system "vagrant",*ARGV
    FileUtils.rm_r(currpath)
    if(ret)
      exit
    else
      abort "Finished"
    end
end
```

**Comment by Yivan** [comment]
Thanks for providing some solutions.
It works, but has some side effects:
- Vagrantfile is parsed 2 times, making commands longer (particularly `vagrant ssh`)
- It don't work on GitBash on Windows as it need tty shell. Making `vagrant ssh` will bring no ssh prompt. It is possible to use Cmder instead (which use cmd console behind). PowerShell and cmd.exe bring well the ssh prompt.

For those interested, we ended up with another solution, see at the end of this issue comment (the first one): https://github.com/hashicorp/vagrant/issues/11246#issue-535987893

**Comment by Yivan** [comment]
I would just share here another solution, using direnv could resolve this for people interrested please see: https://github.com/hashicorp/vagrant/issues/11110#issuecomment-540033452
