### ISSUE TITLE
Docker provider with host vm fails when symlink is present

### ISSUE THREAD

**Issue by kubilus1** [hashicorp/vagrant#3734]
When running a Vagrantfile with the docker provider fails to start if I use a host vm and there is a symlink present in the directory that the Vagrantfile lives in.

To test, drop this vagrantfile in a directory:

```
Vagrant.configure("2") do |config|
    config.vm.define "client" do |client|
      client.vm.provider "docker" do |d|
        d.image = "blalor/centos"
        d.force_host_vm = true
        #d.remains_running = false
        d.cmd = ["sleep", "100"]
      end
    end
end
```

From this directory create a symlink to another location outside of this directory.  For instance:

$ ln -sf ../Makefile Makefile

Then start it:

$ vagrant up --provider=docker

Results in the following error:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

find '/var/lib/docker/docker_1399649530_12763' '(' ! -user docker -or ! -group docker ')' -print0 | xargs -0 -r chown -v docker:docker

Stdout from the command:

boot2docker: 0.8.0
changed ownership of '/var/lib/docker/docker_1399649530_12763' to 1000:100
changed ownership of '/var/lib/docker/docker_1399649530_12763/Dockerfile' to 1000:100
changed ownership of '/var/lib/docker/docker_1399649530_12763/Vagrantfile' to 1000:100


Stderr from the command:

chown: /var/lib/docker/docker_1399649530_12763/Makefile: No such file or directory
```

**Comment by deivid-rodriguez** [comment]
I agree this is not a good default. Another reason: `git status` gives different results in the guest (resolved links) and host machines (symlinks) if you keep symlinks in your repository. That is confusing.

**Comment by avdd** [comment]
I just discovered this unusual default while exploring options for keeping junk out of my source tree.

If I have a link to a directory outside my tree, then all that directory's contents gets copied to the guest.  This is highly unusual and undesirable default behaviour.
