### ISSUE TITLE
Unable to install plugins that depend on nokogiri in Vagrant 1.6+ 

### ISSUE THREAD

**Issue by lox** [hashicorp/vagrant#3769]
Since installing Vagrant 1.6.0, I'm unable to install landrush, or other plugins that depend on nokogiri:

I initially thought this was a landrush issue, but have reproduced with other vagrant plugins:

https://github.com/phinze/landrush/issues/69

I tested 1.6.1 and 1.6.2, both of which fail the same way. Reverting to 1.5.4 fixes the problem.

**Comment by 7stud** [comment]
> josegonzalez said,
> as an aside, people should maybe not use xml and start using json ;)

~/vagrant_getting_started$ vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing json (1.8.2), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.2'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb 
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `initialize_copy': Bad file descriptor (Errno::EBADF)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `initialize_dup'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `dup'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `<module:Logging>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:289:in `<module:MakeMakefile>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:47:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /Users/7stud/.vagrant.d/gems/gems/json-1.8.2 for inspection.
Results logged to /Users/7stud/.vagrant.d/gems/gems/json-1.8.2/ext/json/ext/generator/gem_make.out

~/vagrant_getting_started$ gem install json -v '1.8.2'
Fetching: json-1.8.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-1.8.2
1 gem installed

~/vagrant_getting_started$ vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing json (1.8.2), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.2'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb 
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `initialize_copy': Bad file descriptor (Errno::EBADF)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `initialize_dup'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `dup'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:292:in `<module:Logging>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:289:in `<module:MakeMakefile>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:47:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /Users/7stud/.vagrant.d/gems/gems/json-1.8.2 for inspection.
Results logged to /Users/7stud/.vagrant.d/gems/gems/json-1.8.2/ext/json/ext/generator/gem_make.out

**Comment by benjohnson77** [comment]
I came into this issue yesterday, a bit late to the party. For me updating vagrant to 1.7.2 solved the issue.

**Comment by obfuscurity** [comment]
Same. Weird how boxes suddenly stopped working correctly under 1.6.3 for no apparent reason, but upgrading to 1.7.2 fixed it for me.

**Comment by tomav** [comment]
Same here, upgrading to `1.7.2` fixed the problem. Thank you @benjohnson77 & @obfuscurity

**Comment by arnlaugsson** [comment]
Updating to Vagrant 1.7.2 fixed it for me too.

```
~  ᐅ vagrant version
Installed Version: 1.7.2
Latest Version: 1.7.2

You're running an up-to-date version of Vagrant!
~  ᐅ vagrant plugin install vagrant-cachier
Installing the 'vagrant-cachier' plugin. This can take a few minutes...
Installed the plugin 'vagrant-cachier (1.2.0)'!
```

**Comment by hadifarnoud** [comment]
i still have this issue with vagrant 1.6.3 OSX 10.10.3 gem 2.4.6

I have tried ALL the above solutions. At last I edited nokogiri 1.6.2.1 gemspec in /Vagrant folder and modified the version to  s.version = "1.6.6.2"

not sure this is going to mess up some things or not.

**Comment by fireproofsocks** [comment]
Having this problem with Vagrant 1.6.3 on Mac OS X 10.9.5

**Comment by johnleetran** [comment]
upgrade to a newer version of vagrant OR

gem install --install-dir ~/.vagrant.d/gems nokogiri -v '1.6.3.1'

if you get another error like before run the same command on that package, for example

gem install --install-dir ~/.vagrant.d/gems dep_selector -v '1.0.3'

**Comment by jokeyrhyme** [comment]
I've had a great run with Vagrant, but I'm transitioning my projects to Docker now. Docker gets easier and easier to use each day, and it doesn't have any of the Ruby-to-C++ interface problems that Vagrant has. If you are having problems with Vagrant, give Docker a try.

**Comment by af7** [comment]
@jokeyrhyme Is there a "VVV" equivalent in Docker?

**Comment by jokeyrhyme** [comment]
@af7 if you mean http://varyingvagrantvagrants.org/ , then I'm not sure. I did find this (but it seems incomplete): https://github.com/Varying-Vagrant-Vagrants/vvv-docker/tree/lkwdwrd

**Comment by johnleetran** [comment]
i still prefer vagrant because vagrant boxes are easier to destroy than docker containers/images.  i am tired of doing a 

`docker rmi -f $(docker images -q)`
`docker rm -f $(docker ps -aq)`

Boot2docker, pushing to a privately hosted docker repository is a pain in the butt.

Another pain point, docker caching for building new docker images is a subtle trap.  We've been bitten by this several times in development.

**Comment by theninthnode** [comment]
Solution for me with Vagrant 1.6.3 on Mac was adding this to vagrant-1.6.3.gemspec like suggested above:

  s.add_dependency(%q<nokogiri>, ["< 1.6.3"])

**Comment by ryancastle** [comment]
I just had this error on vagrant 1.6.3 for nokogiri 1.6.6.2 when installing vagrant-cachier. But installing that version of nokogiri into `~/.vagrant.d/gems` as per @johnleetran's suggestion solved it.

**Comment by damienalexandre** [comment]
On Ubuntu 15.10, I just had to install `zlib1g-dev`:

```
$ sudo apt install zlib1g-dev
$ vagrant plugin install vagrant-cachier
    Installing the 'vagrant-cachier' plugin. This can take a few minutes...
    Installed the plugin 'vagrant-cachier (1.2.1)'!
```

This is cleaner than installing an old version of nokogiri manually :wink:

**Comment by Tyrael** [comment]
not everybody was having problem of building nokogiri because of the missing zlib1g-dev package ;)

**Comment by Donal-Flanagan** [comment]
I had the exact same issue on ubuntu 15.10, with vagrant 1.7.4. Installing the zlib1g-dev package worked perfectly. Thanks for the fix @damienalexandre

**Comment by tartley** [comment]
I also had the exact same issue on Ubuntu 15.10, with vagrant 1.7.4, but installing zlib1g-dev did not fix it. I then did a `gem install nokogiri -v '1.6.7.2'` (not with the intent of installing it, but I was following the instructions in the error message `Make sure that "gem install nokogiri -v '1.6.7.2'" succeeds...`) and after that, my `vagrant plugin install...` started working.

**Comment by Mathyn** [comment]
I had this issue today when trying to install the vagrant-triggers plugin with Ubuntu 14.04. When I tried to manually run `gem install nokogiri -v '1.6.7.2'` as suggested by the error output this also failed to install but did provide the helpful error message `zlib is missing; necessary for building libxml2`. 

After installing zlib (`sudo apt-get install zlib1g-dev`) I could install nokogiri and with that install vagrant-triggers.

**Comment by avishnyakov** [comment]
Getting this while using vagrant-azure (https://github.com/Azure/vagrant-azure) on win10. Not sure what the resolution might be yet.

**Comment by akeif** [comment]
I had the same problem on Ubuntu 16.04. Installing the latest version of Vagrant from [their website](https://www.vagrantup.com/downloads.html) fixed it for me.

**Comment by bhouston** [comment]
@Mathyn thanks for the suggestion:
> After installing zlib (sudo apt-get install zlib1g-dev) I could install nokogiri and with that install vagrant-triggers.

On a fresh install of Ubuntu 16.04, running ```sudo apt-get install zlib1g-dev``` got lxc running for me.  Sweet.

**Comment by andela-mallan** [comment]
Quick fix!
I run `VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant plugin install vagrant-<name_of_plugin>` and worked for me as a temporary solution. 
Let me know if it helps.

**Comment by lostiniceland** [comment]
I am having this issue on OpenSuse Leap 15 and Vagrant 2.1.2

The proposed environment-vars did not work for me and I've checked that zlib-devel is installed.

**Comment by lostiniceland** [comment]
Still having this error on a fresh Opensuse Leap 15 with Vagrant 2.1.2 and nokogiri 1.8.4
```
> vagrant plugin install vagrant-libvirt 
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Fetching: excon-0.62.0.gem (100%)
Fetching: formatador-0.2.5.gem (100%)
Fetching: fog-core-1.43.0.gem (100%)
Fetching: fog-json-1.2.0.gem (100%)
Fetching: mini_portile2-2.3.0.gem (100%)
Fetching: nokogiri-1.8.4.gem (100%)
Building native extensions.  This could take a while...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually                                                                                           
caused by misconfigured plugin installations or transient network                                                                                               
issues. The error from Bundler is:                                                                                                                              

ERROR: Failed to build gem native extension.

    current directory: /home/marc/.vagrant.d/gems/2.4.4/gems/nokogiri-1.8.4/ext/nokogiri
/opt/vagrant/embedded/bin/ruby -r ./siteconf20180714-7439-1nlz3j6.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)
        --help
        --clean
/opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:523:in `with_werror'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
        from extconf.rb:138:in `nokogiri_try_compile'
        from extconf.rb:162:in `block in add_cflags'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/mkmf.rb:630:in `with_cflags'
        from extconf.rb:161:in `add_cflags'
        from extconf.rb:410:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/marc/.vagrant.d/gems/2.4.4/extensions/x86_64-linux/2.4.0/nokogiri-1.8.4/mkmf.log

extconf failed, exit code 1
```
