### ISSUE TITLE
Commands defined in Vagrantfiles not working since 1.6.0

### ISSUE THREAD

**Issue by jsoriano** [hashicorp/vagrant#3775]
Commands defined in Vagrantfiles stop working in 1.6.0, as a minimal example, consider this Vagrantfile:

``` ruby
VAGRANTFILE_API_VERSION = "2"

class MyCommand < Vagrant.plugin(VAGRANTFILE_API_VERSION, :command)
  def self.synopsis
    "Says Hello"
  end

  def execute
    puts "Hello"
    0
  end
end

class MyPlugin < Vagrant.plugin(VAGRANTFILE_API_VERSION)
  name "My Plugin"

  command "mycommand" do
    MyCommand
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "base"
end
```

Till 1.5.4 this code provides a command called `mycommand` that appears in `vagrant list-commands` and that can be called as `vagrant mycommand`, but from 1.6.0 the command disappears.

Is this using some deprecated code? In principle vagrant 1.6 is supposed to be backwards compatible.

**Comment by jglick** [comment]
Since 1.7.0 according to the GitHub commit. Seems to work in 1.7.2.
