### ISSUE TITLE
VirtualBox read_guest_ip fails to get Guest IP

### ISSUE THREAD

**Issue by ifnull** [hashicorp/vagrant#3792]
VBoxManage appears to not be returning an IP at the time it is requested. `["/usr/bin/VBoxManage", "guestproperty", "get", "a7b38e5f-3541-4359-a6b8-118eb4a11729", "/VirtualBox/GuestInfo/Net/1/V4/IP"]` returns `No value set!` but if I call it manually it does correctly return the IP. This leads me to believe it may be a race condition issue.

When called after `vagrant up` fails, this command returns successfully.

```
(default)[danielsmith-laptop ~/workspace/foobar (master)]
11:26 $ /usr/bin/VBoxManage "guestproperty" "get" "a7b38e5f-3541-4359-a6b8-118eb4a11729" "/VirtualBox/GuestInfo/Net/1/V4/IP"
Value: 172.28.128.12
```

Ultimately I get the error message: 

```
#<Vagrant::Errors::NFSNoGuestIP: No guest IP was given to the Vagrant core NFS helper. This is an internal error that should be reported as a bug.>
```
### Vagrantfile

https://gist.github.com/ifnull/514fe3212990ce78e81a#file-vagrantfile-rb
### Debug Log

https://gist.github.com/ifnull/514fe3212990ce78e81a#file-debug-log
### Additional Information

```
Vagrant 1.6.2
VBox 4.3.10r93012
VBoxGuestAdditions 4.3.10 r93012
```

```
(default)[danielsmith-laptop ~/workspace/foobar (master)]
11:26 $ vagrant plugin list
vagrant-login (1.0.1, system)
vagrant-share (1.0.1, system)
vagrant-vbguest (0.10.0)
```

**Comment by blech75** [comment]
I, too, was running into this issue with vagrant 2.0 and virtualbox 5.1.28. It was a doozy to figure out, but i finally got it. See the [notes I made in a gist](https://gist.github.com/blech75/8e0808e1982b6c605be5cad35fc13350). (FWIW, this was with the `yk0/ubuntu-xenial (virtualbox, 201606082)` box version.)

Funny thing is, I've always made it a point to ensure the guest additions are up-to-date by using the [vagrant-vbguest](https://github.com/dotless-de/vagrant-vbguest/) plugin. But when testing out a new dev env build, I decided to remove all vagrant plugins to see how it works (to find errors that other users might run into), upgrade everything to the latest versions, and sure enough, it failed!

Is there any more guidance we could provide users when this condition occurs? I did not expect the (apparent) incompatibility between different versions of the `VBoxManage` tool and the guest additions.
