### ISSUE TITLE
undefined method `to_sym' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by schmunk42** [hashicorp/vagrant#3806]

**Comment by cjbush** [comment]
I can verify that I also have this problem in 1.7.2

**Comment by cjbush** [comment]
When I change my metadata.json to simply:

{ "provider": "hyperv" } 

This error goes away. This might be more an issue with documentation than anything.

**Comment by frizop** [comment]
Similar issue: https://gist.github.com/fecf9f6cf6bce9461088

Appears like it could be related to the the box file, but I can't really beg it down.

**Comment by pankaj1jul** [comment]
And issues continues to 1.9.3 :
Please fix the issue. or provide proper documentation on Metadata File. We got license from vagrant, but still see it is not mature enough tool to take the infrastructure problems.

==> box: Loading metadata for box 'metadata.json'
    box: URL: file:///home/psaraf/images/bpsim2/metadata.json
==> box: Adding box 'camstore/bpsim' (v1) for provider: vmware_workstation
    box: Unpacking necessary files from: file://bpsim-vm-worstation.box
/opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:144:in `block (4 levels) in add': undefined method `to_sym' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:144:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:144:in `find'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:144:in `block (3 levels) in add'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:461:in `with_temp_dir'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:134:in `block (2 levels) in add'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:461:in `with_temp_dir'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:115:in `block in add'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:448:in `block in with_collection_lock'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:447:in `with_collection_lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/box_collection.rb:104:in `add'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/box_add.rb:347:in `box_add'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/box_add.rb:273:in `add_from_metadata'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/box_add.rb:108:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/box/command/add.rb:78:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/commands/box/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/bin/vagrant:127:in `<main>'
