### ISSUE TITLE
Vagrant could be smarter about the default provider

### ISSUE THREAD

**Issue by jordansissel** [hashicorp/vagrant#3812]
When configuring a box to use a given provider that isn't the system's default, I would love Vagrant to recognize this and use the provider I asked it to use from the Vagrantfile.

It is possible I am simply misconfiguring something. If so, let me know :)

I have some vagrant boxes using docker as the provider, configured thusly:

```
    config.vm.define "ubuntu-12.04" do |c|
      c.vm.box = "dummy"
      c.vm.box_url = "http://bit.ly/vagrant-docker-dummy"
      c.vm.provider :docker do |docker|
        docker.image = "jordansissel/system:ubuntu-12.04"
      end
    end
```

Yet, doing `vagrant up ubuntu-12.04` results in:

```
The provider 'virtualbox' that was requested to back the machine
'ubuntu-12.04' is reporting that it isn't usable on this system. The
reason is shown below:
```

However, doing `vagrant up --provider docker ubuntu=12.04` works as expected.

**Comment by tknerr** [comment]
Is it just me, or is this not working anymore in 1.7.4?

I was so sure it had worked, but now it doesn't anymore...
