### ISSUE TITLE
chmod, chown throws error on SMB shared folders

### ISSUE THREAD

**Issue by schmunk42** [hashicorp/vagrant#3813]
I created an ubuntu base box for hyperv. Now I want to run some puppet scripts to build up some servers, etc...

Some of my existing puppet modules are checking permissions and trying to change them if needed within the SMB share.

But the `chmod` fails with `operation not permitted` - how can I work around this issue?

Vagrant 1.6.2

**Comment by santhoshscs** [comment]
I had the same issue  - 
Vagrant - version 2.0.4 
Virtualbox version  5.2.8 r121009 (Qt5.6.2)
Host : Windows 10 
Guest: Centos 7

When I checked the mount inside the VM - It seems it used old smb version 1.0 
`
[vagrant@local ~]$ mount   

//192.168.3.36/vgt-0f26c47ff64839d33e5094c0c0289868-6924173fbf589baf00543690b44caea2 on /vagrant type cifs (rw,relatime,vers=1.0,sec=ntlmssp,cache=strict,username=scs,domain=WS18,uid=1000,forceuid,gid=1000,forcegid,addr=192.168.3.36,file_mode=0664,dir_mode=0775,nounix,serverino,mapposix,mfsymlinks,rsize=61440,wsize=65536,echo_interval=60,actimeo=1)
`
I changed the SMB version to 3.0 with mount_options `"vers=3.0"` - fixed my issue
