### ISSUE TITLE
rsync-auto don't stop on Windows when pressing Ctrl + C (in a Cygwin shell)

### ISSUE THREAD

**Issue by ghost** [hashicorp/vagrant#3824]
I use Windows 8.1 and the latest Cygwin (64-bit).

**Reproduction:**
1. Start a Vagrant VM with a rsync shared folder
2. Start vagrant rsync-auto in a Cygwin shell
3. Press Ctrl + C. In the shell it seems that rsync-auto stopped. But when you look in the Task Manager for Ruby processes there will still be a Ruby process of rsync-auto. When you make changes to a file that is synchronised with rsync, the shell will output the log of rsync-auto again.

I used [this Vagrant config](https://github.com/Sanjo/vagrant-meteor).

**Comment by Arxisos** [comment]
Inspired by https://www.cygwin.com/ml/cygwin/2010-05/msg00524.html I modified [`/bin/vagrant`](https://github.com/mitchellh/vagrant-installers/blob/master/substrate/modules/vagrant_installer/templates/vagrant.erb) (the bash file distributed by the installer) to kill all child processes if the CTRL + C signal handler is triggered. The solution is using `pskill` from [Windows Sysinternals](http://technet.microsoft.com/en-us/sysinternals/bb896683.aspx). You will need to change `PSKILL` to the correct path for your system (the following code is assuming that `pskill` sits at `/d/bin/cmdwrapper/pskill`.

```patch
--- vagrant     2014-05-06 05:27:30.000000000 +0200
+++ vagrant.custom      2015-01-04 18:39:26.555633800 +0100
@@ -113,4 +113,33 @@
 export VAGRANT_EXECUTABLE

 # Call the actual Vagrant bin with our arguments
-"${RUBY_EXECUTABLE}" "${VAGRANT_LAUNCHER}" "$@"
+"${RUBY_EXECUTABLE}" "${VAGRANT_LAUNCHER}" "$@" &
+
+# Custom signal handler
+PSKILL="/d/bin/cmdwrapper/pskill"
+
+# A simple signal handler that kills the child process if we've started one
+killChildProcess() {
+    if [ -n "${CHILDPIDW}" ] ; then
+        # Use pskill to kill the entire family
+        # TODO: See if there's way to do this purely with cygwin
+        ${PSKILL} -t ${CHILDPIDW} &> /dev/null
+    fi
+}
+
+# Get the child PID
+CHILDPID=$!
+CHILDPIDW=`/usr/bin/ps -p ${CHILDPID} | /usr/bin/awk -e '/^[[:space:]]+[[:digit:]+]/{print $4}'`
+
+# Register the signal handler for CTRL-C/interrupt
+trap 'killChildProcess' INT
+
+# Wait for the child to finish normally and store the exit code
+wait ${CHILDPID}
+RESULT=$?
+
+# Remove the signal handler (probably unnecessary since we're exiting anyway)
+trap - INT
+
+# Propagate the requested process' exit code to the caller
+exit ${RESULT}
```

Maybe we can merge a more polished version of the code into the vagrant project.

**Comment by wesruv** [comment]
Also getting this @fongandrew 's one liner worked for me, thanks!

Wish I didn't have to do that though, `cygwin--`

**Comment by mreichenbach-igniti** [comment]
@Arxisos : Thanks, your changes work fine for me (using Vagrant 1.7.2) :+1:

**Comment by mreichenbach-igniti** [comment]
@Arxisos : I just realised that with your changes, I cannot use "vagrant ssh" any more. It seems to log into the VM but then terminates all processes. :cry:

**Comment by Arxisos** [comment]
@mreichenbach-igniti Yes, I noticed that, too. Now, I've simply switched to run `vagrant auto-rsync` with Powershell. I added cygwin's `rsync` and `ssh` to my path.

**Comment by mreichenbach-igniti** [comment]
@Arxisos : I'm using putty now for ssh (and cygwin for `vagrant rsync-auto`) which works fine too.

**Comment by ponsea** [comment]
`cmd /C vagrant rsync-auto`!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
