### ISSUE TITLE
Multi-machine provisioner order not intuitive

### ISSUE THREAD

**Issue by robkinyon** [hashicorp/vagrant#3833]
Whenever provisioners are defined, they are run in the order they are defined. However, when you define provisioners with multiple machines, they are not run in the order I define them. For example:

``` ruby
Vagrant.configure(2) do |config|
    config.vm.provision :shell, :inline => 'echo A'
    config.vm.define :testing do |test|
        test.vm.provision :shell, :inline => 'echo B1'
        config.vm.provision :shell, :inline => 'echo B2'
    end
    config.vm.provision :shell, :inline => 'echo C'
end
```

The output of a `vagrant provision` is:

```
A
B2
C
B1
```

So, either:
1. Update the documentation to make it clear that global provisioners are executed before local provisioners
2. Update the code to ensure that the order provisioners are defined in the Vagrantfile is the order they are executed
3. Allow me to specify an ordering between provisioners, similar to how Chef and Puppet function.

Note that the third option assumes the first option as well. :)

**Comment by thpham** [comment]
Is there a workaround to change this 'outside-in' behaviour ? for example, I've a provisioner specific (vagrant-aws) declaration within the node definition that needs to be executed at first!  (->  set the hostname, because nodeX.vm.hostname doesn't work with this plugin)

**Comment by robkinyon** [comment]
@thpham I've answered the linked SO question with the right answer. Basically, a Vagrantfile is just a Ruby program and, when run, it generates a huge data structure that the CLI subcommands traverse for their own ends. Therefore, create functions that attach provisioners at the 'right' level. This way, you're still reusing code, but it's being attached at the right places.
