### ISSUE TITLE
Disable rsync-auto notifications

### ISSUE THREAD

**Issue by thasmo** [hashicorp/vagrant#3834]
Vagrant is constantly printing messages like this to the console:

```
==> default: Rsyncing folder: /cygdrive/s/Project/box/host/ => /var/www/host
==> default:   - Exclude: [".vagrant/", ".git/", "bower_components/", "node_modules/"]
```

Is there a way to hide them? Even `ctrl+c` doesn't help in hiding.
I'd like to have rsync-auto sync the files in the background without notifications.

Is it possible somehow? Thanks a lot! :)

**Comment by vhosakot** [comment]
When I did `vagrant up` with the box `centos/7 (virtualbox, 1703.01)`, `==> default: Rsyncing folder: /root/ => /vagrant` was stuck for me too, and adding
`config.vm.synced_folder '.', '/vagrant', disabled: true`
in Vagrantfile resolved the issue for me and rsync did not happen.
