### ISSUE TITLE
Integrate triggers into core?

### ISSUE THREAD

**Issue by russroy** [hashicorp/vagrant#3849]
I think one way to view Vagrant is as a programmable state-machine for VM environments.   Viewed as such the ability to attach custom actions triggered to a state transition before, after, or in place of the existing canned vagrant actions is crucial to full programmability.

We do have the vagrant-triggers plugin which seeks fill this hole.  It's a nice addition but I see some shortcomings to its embodiment as a plugin:

1)  triggers is a pretty generic concept and central to the state-machine conceptualization - it belongs in the core

2)  People don't alway think to look for a plugin to augment vagrant functionality.   Instead they'll glom on some ad hoc solution.   Putting functionality in the core gives it more "visibility".

3)  Putting the functionality in the core might help to mitigate the occurrence of inter-plugin compatibility issues such as this https://github.com/mitchellh/vagrant-aws/issues/233

**Comment by trajano** [comment]
My use case would be to run `docker swarm leave` before it gets destroyed rather than doing it manually.
