### ISSUE TITLE
Virtualbox 4.3.12 not detected on Windows 7 - VBOX_INSTALL_PATH changed

### ISSUE THREAD

**Issue by dsjgordon** [hashicorp/vagrant#3852]
Got the "Vagrant could not detect VirtualBox!" after upgrading Virtualbox to 4.3.12.

Vagrant: 1.6.2
Virtualbox: 4.3.12

Digging around I found that embedded\gems\gems\vagrant-1.6.2\plugins\providers\virtualbox\driver\base.rb tries the env var VBOX_INSTALL_PATH to locate VBoxManage.  It appears Oracle have changed it to VBOX_MSI_INSTALL_PATH as of 4.3.12.

Manually restoring the VBOX_INSTALL_PATH env var resolved the issue, so probably need to update base.rb to include the new one.

**Comment by master12** [comment]
this worked for me. just needed to restart the command prompt window when I was finished editing the env var
