### ISSUE TITLE
Error while adding Vagrant box in windows xp

### ISSUE THREAD

**Issue by lkrenaga** [hashicorp/vagrant#3869]
I installed latest vagrant and virtual box. When i run 

 vagrant box add precise32 http://files.vagrantup.com/precise32.box

Getting below error. 

The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

**Comment by mark-juwai** [comment]
@BakerCo It works!
Thanks

**Comment by yanliqing** [comment]
The solution provided by @BakerCo worked for me :)

**Comment by manueljaguilera** [comment]
Thanks to @BakerCo and @vweevers

**Comment by appsbits** [comment]
Thanks @BakerCo. it works. Vagrant 1.7.2 btw

**Comment by Acekid88** [comment]
Yes, second attempt of a 5 hour download was successful!
Thank you ( @BakerCo and @vweevers)

**Comment by danielrhodeswarp** [comment]
Have been experiencing this with Vagrant 1.7.4 on Windows XP. Fixed by using the solution from @BakerCo - thanks for that.

Surprised to see that this quite old bug is still in Vagrant. Though to be honest, for the sake of crappy Windows XP, I also probably wouldn't bother!

**Comment by pickupman** [comment]
Thanks to @BakerCo  for the solution. Still need this for Windows XP installs of vagrant.
