### ISSUE TITLE
keep_color doesn't work with ansible script on guest

### ISSUE THREAD

**Issue by melck** [hashicorp/vagrant#3891]
Hi, first sorry for my english !

I want to report a little issue, i'm on windows 7 and i launch ansible provisionning from shell script on guest. I want to keep color like ansible handle it but when i put keep_color, the colors are white and all red if script fails. Do you have a way to workaround this color issue without install plugin?

**Comment by gildegoma** [comment]
@melck in case you're still interested in this kind of things, please have a look at #5340.
