### ISSUE TITLE
Vagrant 1.6.2 tries to use HyperV instead of Virtualbox as before

### ISSUE THREAD

**Issue by alexeyOnGitHub** [hashicorp/vagrant#3896]
I have a Vagrant setup created couple months ago. it uses Virtualbox provider.
now I installed Vagrant 1.6.2 on a new computer and started it for the first time in the folder where I keep my Vagrant configuration files (provisioning and Vagrantfile): "vagrant up". 
for some reason it's trying to use HyperV instead of Virtualbox:

```
$ vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
```
## 

had to stop it using CTRL_C because it seems to be frozen.

I'm using Virtualbox 4.3.12

**Comment by UltCombo** [comment]
> the original advice sounded a bit ambiguous to me, sorry

The usual grammar is `SET <var name> TO <value>`, so I also understood it the other way around.

Anyway, thanks for help! Setting the `VBOX_INSTALL_PATH` env var solved the issue for me as well.

**Comment by UltCombo** [comment]
By the way, I'm using Vagrant 1.7.2 with VirtualBox 4.3.20 and still experienced this issue.
Was this issue actually fixed in Vagrant?

**Comment by UltCombo** [comment]
Oh, looks like the issue is only reproducible when running `vagrant up` from msysGit Bash.

**Comment by angrychimp** [comment]
I'm still seeing this same behavior with a fresh install of Vagrant 1.7.2 and VirtualBox 4.3.22 on Windows 7. I've tried using the standard Windows command prompt, and Cygwin. As with the others above, I'm able to work around the issue using the adjusted environment variable.

Is this expected to be fixed at this point? Or is it possible this is a new bug?

**Comment by possibly** [comment]
@angrychimp me too. 

VirtualBox 4.3.24 for Windows hosts x86/amd64 and Vagrant 1.7.2 for Windows 7. I'm using standard Windows cmd.exe. Deleting `VBOX_MSI_INSTALL_PATH` system variable and setting `VBOX_INSTALL_PATH` to `C:\Program Files\Oracle\VirtualBox` solved this issue, as it has with everyone else.

**Comment by angrychimp** [comment]
@mitchellh - can you please review this issue again and confirm if it should be reopened? Or should a new issue be created?

**Comment by jchristman** [comment]
@angrychimp, I had this same problem after:
 1. Installed vagrant for the first time on Windows 7
 2. Installed VirtualBox for the first time (on this machine)

I confirm that VirtualBox still installs with the ```VBOX_MSI_INSTALL_PATH``` as of 4.3.26 (released 16 March, 2015). Using the steps provided by @possibly, I renamed the system variable to ```VBOX_INSTALL_PATH``` and had no issues thereafter.

**Comment by braneof** [comment]
Just ran into this issue with the latest versions: VirtualBox 5.0.10 and Vagrant 1.8.1. Changing `VBOX_MSI_INSTALL_PATH` to `VBOX_INSTALL_PATH` worked, but this is an annoying issue and it's still not fixed.

**Comment by uttamanand** [comment]
you can give command as -:

vagrant up --provider virtualbox

**Comment by apournaras** [comment]
I did delete `VBOX_MSI_INSTALL_PATH` and created `VBOX_INSTALL_PATH` and set it to `C:\Program Files\Oracle\VirtualBox` but I vagrant still tries to use Hyper-v instead of Virtualbox on Windows 8.1. I use vagrant 2.0.0 and virtualbox 5.2.0

**Comment by uttamanand** [comment]
I guess you are trying to do vagrant up. 

Instead try vagrant up —provider virtualbox

Note-: — is double hyphen .

**Comment by uttamanand** [comment]
Cool.
