### ISSUE TITLE
Vagrant RDP

### ISSUE THREAD

**Issue by 3goats** [hashicorp/vagrant#3917]
When I run `vagrant rdp` my RDP session always opens in full screen mode. I've tried this:

`vagrant rdp -- /h:900 /w:1100` as per the documentation but the parameters get ignored!

**Comment by TaylorMonacelli** [comment]
vagrant rdp -- "screen mode id:i:1" "desktopwidth:i:1024" "desktopheight:i:768"
works for me on OS X.  Microsoft RDP Version 8.0.29 (Build 27077), Vagrant 1.9.1
