### ISSUE TITLE
incompatible character encodings: CP850 and Windows-1252

### ISSUE THREAD

**Issue by heliobarbosa** [hashicorp/vagrant#3937]
When the user profile directory has accent, vagrant opens its beak, he can not read environment variables, because some of them are pulling something from the user profile directory it can not convert the charset

C:\Users\Hélio\Downloads>vagrant box add sonbox.box
C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.6.2/lib/bundler/runtime.rb:224:in `
join': incompatible character encodings: CP850 and Windows-1252 (Encoding::Compatibil
ityError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.6.2/lib/bundler/runtim
e.rb:224:in`setup_environment'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.6.2/lib/bundler/runtim
e.rb:15:in `setup'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.6.2/lib/bundler.rb:127
:in`setup'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.6.2/bin/vagrant:71:in
`<main>'

**Comment by andrey-borgoyakov** [comment]
Solved this bug, just set VAGRANT_HOME variable in CMD like this:
set VAGRANT_HOME=C:\HashiCorp\Vagrant

This patch C:\HashiCorp\Vagrant  by default install vagrant. Worked for me (OS Windows 8.1 x64)

**Comment by andreroggeri** [comment]
I fixed this issue by using the command above

**set VAGRANT_HOME=C:\HashiCorp\Vagrant**

AND

Changing the default VM folder on VirtualBox preferences

**Comment by DeadRamza** [comment]
@andreroggeri this fixed for me too, my user name has an "é" character in it as well, so vagrant was probably bugging when checking the default vm folder wich was located under the "users/myusérname" folder, i just changed it to a generic folder "C:\VMs"  and it worked.

**Comment by jhessamanda** [comment]
Please!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! someone help me with this error? JESSICA-PC@JESSICA MINGW64 ~/desktop/blog/projeto (master)
$ git add --all

JESSICA-PC@JESSICA MINGW64 ~/desktop/blog/projeto (master)
$ git commit -m "ajustes no bootstrap"
[master af559d8] ajustes no bootstrap
 2 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 index.html
 create mode 100644 scss/vendors/plugins.scss

JESSICA-PC@JESSICA MINGW64 ~/desktop/blog/projeto (master)
$ sass --no-cache --watch scss:css --style compressed
>>> Sass is watching for changes. Press Ctrl-C to stop.
  directory css/vendors
      write css/vendors/plugins.css
      write css/vendors/plugins.css.map
Encoding::CompatibilityError: incompatible character encodings: Windows-1252 and CP850
  Use --trace for backtrace.

**Comment by rvanmil** [comment]
@andreroggeri 👍

**Comment by diezcode** [comment]
amazing that this command fixed my vagrant bug with my name = Stéphane "é"
with this on my folder = set VAGRANT_HOME=C:\HashiCorp\Vagrant 
The issue is gone. Is vagrant making an update for the new updates?

**Comment by istvan-ujjmeszaros** [comment]
I had to revert to 1.8.7 as 1.9 seems to have issues on Windows with curl and I couldn't fix that.
The `set VAGRANT_HOME=C:\HashiCorp\Vagrant` fix works, but I had to run `vagrant up` from a command prompt with admin rights.
Guys, it would be really great if you could test vagrant on Windows before publishing it.

**Comment by Traxpoint** [comment]
Got this issue with version 2.0.4, could get it running with the solutions from this forum.

set VAGRANT_HOME=C:\HashiCorp
and
have moved VirtualBox path from users directory to c:\
