### ISSUE TITLE
Add way to change memory of Hyper-V

### ISSUE THREAD

**Issue by LarryEitel** [hashicorp/vagrant#3947]
I use:

```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "hyperv" do |hv|
    hv.customize ["modifyvm", :id, "--memory", 2048]
  end
```

I only get 512MB

**Comment by adamralph** [comment]
ping

**Comment by vvchik** [comment]
hi, I just create PR #5183 that realize that functionality.
It is very simple change, and you can just replace three files in
c:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.1\plugins\providers\hyperv\
until this PR will be accepted.

**Comment by adamralph** [comment]
@vvchik fantastic!

**Comment by alexsandro-xpt** [comment]
It's work?

**Comment by PhilKershaw** [comment]
@alexsandro-xpt Judging by the conversation in the PR it would seem so. I'm looking forward to getting this up and running. Thank you @vvchik for making this possible!
