### ISSUE TITLE
Guru meditation

### ISSUE THREAD

**Issue by ku1ik** [hashicorp/vagrant#396]
Hi,

I've installed vagrant 0.7.5 on Fedora 15. I have VirtualBox 4.0.4.
I've tried to follow tutorial, fetched base box lucid32 and issued vagrant up. I got

```
...
[default] Waiting for VM to boot. This can take a few minutes.
[default] Failed to connect to VM!
Failed to connect to VM via SSH. Please verify the VM successfully booted
by looking at the VirtualBox GUI.
```

I started GUI and noticed that virtual machine is in "guru meditation" state.

I started the machine manually from GUI and it booted correctly.
Downgrading to 0.7.4 fixes the problem.

I've checked 0.7.5 on ruby 1.8.7 and 1.9.2 and on both it doesn't work. I've also tried other box (maverick32) and the same problem with 0.7.5.

**Comment by enriquezrene** [comment]
I solved the problem using my latest OS version:
http://enriquezrene.com/home/index.php/devops/vagrant

**Comment by ssundarraj** [comment]
@enriquezrene The link isn't working. Can you update this thread with the contents of that please?

**Comment by enriquezrene** [comment]
@ssusundarraj sorry it's here http://enriquezrene.com/home/index.php/en/devops-english/vagrant
