### ISSUE TITLE
The box you attempted to add doesn't match the provider you specified.

### ISSUE THREAD

**Issue by medyagh** [hashicorp/vagrant#3967]
I keep getting this error when I do vagrant up,

"The box you attempted to add doesn't match the provider you specified.
Provider expected: virtualbox
Provider of box: aws"

my Vagrantfile looks like this:
   config.vm.box = "dummy"
 14   config.vm.box_url="https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
 15   config.vm.provider :aws do |aws,override|
and so on ..

**Comment by gustawdaniel** [comment]
In my case helped

    sudo apt-get install virtualbox
