### ISSUE TITLE
Vagrant > v1.62 WinRM conflicts with HTTP_PROXY environment variable

### ISSUE THREAD

**Issue by ghost** [hashicorp/vagrant#3968]
Vagrant > v1.62 <b>WinRM</b> conflicts with <b>HTTP_PROXY</b> environment variable. Cannot mount directory nor run provisioning script.
Removing <b>HTTP_PROXY, HTTPS_PROXY</b>  environment variables resolves the issue.
Behind a very secure and restricted financial organization corporate firewall.
Host: Win7 x64; Guest: Win2012R2; Provider: VirtualBox

**Comment by rlaveycal** [comment]
Just to mention that setting the NO_PROXY environment variable to a COMMA separated list ```"localhost,127.0.0.1"``` will bypass the proxy and allow WinRM to connect to the guest
