### ISSUE TITLE
Cannot destroy a zombie box

### ISSUE THREAD

**Issue by vitaut** [hashicorp/vagrant#3975]
I can't destroy the box after deleting the content of a (test) project including Vagrantfile. `vagrant global-status` reports the box as running:

<pre>
$ vagrant global-status
id       name    provider   state   directory                           
------------------------------------------------------------------------
3898812  default virtualbox running /home/viz/test  
</pre>

but `vagrant destroy` has no effect:

<pre>
$ vagrant destroy 3898812
==> default: VM not created. Moving on...
</pre>

I've tried using `VBoxManage` to poweroff and unregister the VM as suggested in http://stackoverflow.com/a/15410190/471164, but vagrant still reports it as running.

I'm using Vagrant 1.6.3.dev.

**Comment by tschet** [comment]
Thanks, that was helpful. I realized I had a box on the global-status list that no longer existed, but couldn't figure out how to remove it.

**Comment by eMPee584** [comment]
Mh.. Why exactly is global-status showing a cached view?
