### ISSUE TITLE
Cannot salt docker box

### ISSUE THREAD

**Issue by davidkarlsen** [hashicorp/vagrant#3984]
Configuration file '/etc/salt/minion'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using current old file as you requested.
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.19-0ubuntu6) ...
Processing triggers for ureadahead (0.100.0-16) ...
-  INFO: Running install_ubuntu_check_services()
- ERROR: Failed to run install_ubuntu_check_services()!!!
  ESC]0;root@cd15776da97e: ~^Groot@cd15776da97e:~# exit

Dockerfile:

```
et2448@ubuntu:~/projects/tac/jfr/tac-jfr-server/jfr-srv-docker$ cat Dockerfile 
FROM ubuntu:14.04
MAINTAINER David J. M. Karlsen <david.karlsen@evry.com>

# Update the system
RUN echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get upgrade -y

# Install OpenSSH Server and set credentials to root/root
RUN apt-get install -y openssh-server
RUN mkdir -p /var/run/sshd
RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN sed -ri 's/#UsePAM no/UsePAM no/g' /etc/ssh/sshd_config
RUN sed -ri 's/PermitRootLogin without-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
RUN echo 'root:root' | chpasswd
RUN useradd -m vagrant -U -G sudo
RUN echo 'vagrant:vagrant' | chpasswd

# Setup basic aliases
RUN echo "\nalias ..='cd ..'" >> /root/.bashrc

# Expose port 22 for ssh
EXPOSE 22

#this should rather go into a salt-forumla:
RUN apt-get install aptitude software-properties-common -y && aptitude update && aptitude dist-upgrade -y
#oracle java:
#RUN add-apt-repository -y ppa:webupd8team/java && apt-get update && echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections && aptitude install -y oracle-java7-installer
#RUN java -version

CMD /usr/sbin/sshd -D


```

Vagrantfile:

  #config.ssh.password = "vagrant"
  config.ssh.password = "root"
  config.ssh.username = "root"
  #config.ssh.insert_key = "true"
  config.ssh.pty = "true"

  config.vm.synced_folder ".", "/srv/salt/"
  config.vm.synced_folder "vagrant/pillar", "/srv/pillar/"

  config.vm.define "app" do |app|
    app.vm.provider "docker" do |d|
      d.has_ssh = true 
      d.build_dir = "."
      d.name = "tacjfrsrv"
    end
  end

  #need curl for salt bootstrap
  #config.vm.provision :shell, :inline => "aptitude -y install curl"

  #config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  ## Use all the defaults:
  config.vm.provision :salt do |salt|
    salt.verbose = true
    salt.minion_config = "vagrant/minion"
    # pillar data is in vagrant/pillar/top.sls|wxs.sls
    salt.run_highstate = true

```
#salt.install_type = 'git'
#salt.install_args = 'develop'
```

  end

end

minion and pillar config not included in issue

**Comment by nha** [comment]
I am running into this as well. It would be really nice to have Vagrant help bootstrap salt. Unless I am doing something wrong, it is easy to use Vagrant and (Docker or Salt), but not Vagrant and (Docker and Salt). Mostly, it seems due to Docker. It also means that right now I am forced to make my own Dockerfile instead of doing everything in Vagrant if I want to use both.
