### ISSUE TITLE
Windows hosts should be rebooted after changing hostname

### ISSUE THREAD

**Issue by benh57** [hashicorp/vagrant#3987]
Currently, if i spin up a windows basebox which has hostname 'A' and i have vagrant set to give it hostname 'B' (using vm.hostname)  the provisioner (say, puppet) gets the wrong hostname - "A".

This is because Windows needs to be rebooted to activate the new hostname.

To fix this, Vagrant should reboot windows instances if the hostname needs to be changed, after setting it.

**Comment by rgl** [comment]
This is not working with Windows 2012 R2, the machine does not really reboot after setting the hostname.

**Comment by benh57** [comment]
1.7.2 no longer reboots because they attempted a non-reboot solution for setting the hostname. 

1.7.3, yet to be released git master, should reboot again.
