### ISSUE TITLE
Allow lower case Vagrantfile files

### ISSUE THREAD

**Issue by dol** [hashicorp/vagrant#399]
On Linux systems file names are seldom upper case.

vagrant init should generate a file with a lower case name. 'vagrant up' only looks for an upper case file name. On Mac OS X it's most time no problem, due the case insensitive file system.

**Comment by jxmallett** [comment]
A heads up if you're using a case-sensitive environment like Linux - Some tools that integrate with vagrant, like phpstorm, won't recognise the vagrantfile with a lowercase V, so Vagrantfile with an uppercase V is probably still the safer option.
