### ISSUE TITLE
Add "vagrant remote" feature.

### ISSUE THREAD

**Issue by espennilsen** [hashicorp/vagrant#401]
It would be very nice if I could spawn the virtualbox VM's on other machines. I do my coding on my macbook but I would like to spawn the VM's on my desktop computer.

**Comment by user-friendly** [comment]
+1

**Comment by cloutierjo** [comment]
+1

**Comment by erossetto** [comment]
+1

**Comment by shafqatevo** [comment]
+1
Our need is to spin VMs by driving a VirtualBox that is in a remote Solaris host. Not finding any Solaris port of Vagrant (am I missing anything?).

**Comment by mwthink** [comment]
+1 
I do my development on 1 machine, but have a multitude of in-home servers. This feature would be killer.

**Comment by giacmir** [comment]
+1

**Comment by mlongob** [comment]
+1

**Comment by HeWhoWas** [comment]
2 months until the two year anniversary of this tickets closure, and 18 months since 2.0 was released..... +1

**Comment by silviuvulcan** [comment]
The most compelling reason for me is ansible on a windows host. Running ansible is cumbersome to say the least on cygwin together with windows vagrant. This would allow to keep vagrant and ansible inside a Linux VM which would call actually the host when deploying boxes.

**Comment by wei-ding** [comment]
This feature will be a killer feature.
