### ISSUE TITLE
Vagrant creating random files and folders

### ISSUE THREAD

**Issue by serpro** [hashicorp/vagrant#4020]
Recently I updated Vagrant (v 1.6.3) and I noticed that in the folder of my project there are some new folders and files like:

d20140610-11944-1j6n1cz/
d20140610-15421-1pkz3t8/
vagrant20140610-11944-p76ezc
vagrant20140610-11944-p76ezc2
vagrant20140610-11944-yt3bhz
vagrant20140610-11944-yt3bhz1
vagrant20140610-15421-mfqrig
vagrant20140610-15421-mfqrig1
vagrant20140610-15421-y3r71a
vagrant20140610-15421-y3r71a2
vagrant20140610-15421-y3r71a2.lock

most of the files are empty, others have text like this:

source "https://rubygems.org"
source "http://gems.hashicorp.com"
gem "vagrant", "= 1.6.3"
group :plugins do
gem "vagrant-login", nil, {}
gem "vagrant-share", nil, {}
end

The directories have a file named config with this this info:

BUNDLE_PATH: "/home/user/.vagrant.d/gems"

Is this some kind of debug option? how can I disable it?

**Comment by rafaelcneves** [comment]
Change permission for /tmp resolved to me, for me this make no sense, but works:
`sudo chmod 1777 /tmp`
