### ISSUE TITLE
rysnc-auto fails with undefined method

### ISSUE THREAD

**Issue by trevorwh** [hashicorp/vagrant#4031]
Hi All,

Tried searching for this but wasn't able to find anything. Rsync-auto was working correctly until a bit ago, all of a sudden get this on any changes:

[Listen warning]: Change block raised an exception: undefined method `[]' for nil:NilClass
Backtrace:
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/synced_folders/rsync/helper.rb:57:in`rsync_single'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/synced_folders/rsync/command/rsync_auto.rb:161:in `block (2 levels) in callback'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/synced_folders/rsync/command/rsync_auto.rb:158:in`each'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/synced_folders/rsync/command/rsync_auto.rb:158:in `block in callback'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/synced_folders/rsync/command/rsync_auto.rb:157:in`each'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.2/plugins/synced_folders/rsync/command/rsync_auto.rb:157:in `callback'
    /Applications/Vagrant/embedded/gems/gems/listen-2.7.4/lib/listen/listener.rb:149:in`call'
    /Applications/Vagrant/embedded/gems/gems/listen-2.7.4/lib/listen/listener.rb:149:in `block in _wait_for_changes'
    /Applications/Vagrant/embedded/gems/gems/listen-2.7.4/lib/listen/listener.rb:138:in`loop'
    /Applications/Vagrant/embedded/gems/gems/listen-2.7.4/lib/listen/listener.rb:138:in `_wait_for_changes'
    /Applications/Vagrant/embedded/gems/gems/listen-2.7.4/lib/listen/listener.rb:42:in`block in start'

Can this be confirmed as bug?

Thanks!

**Comment by JbalTero** [comment]
Encountered this

> E, [2019-05-23T15:29:58.905907 #10408] ERROR -- : exception while processing events: undefined method `[]' for nil:NilClass Backtrace:
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/synced_folders/rsync/helper.rb:73:in `rsync_single'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/synced_folders/rsync/command/rsync_auto.rb:214:in `block (2 levels) in callback'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/synced_folders/rsync/command/rsync_auto.rb:203:in `each'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/synced_folders/rsync/command/rsync_auto.rb:203:in `block in callback'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/synced_folders/rsync/command/rsync_auto.rb:202:in `each'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/plugins/synced_folders/rsync/command/rsync_auto.rb:202:in `callback'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
 -- C:/HashiCorp/Vagrant/embedded/gems/2.2.4/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'

**Comment by anjia0532** [comment]
I get the same thing
```
    default: E, [2019-08-08T15:18:13.391379 #5604] ERROR -- : exception while processing events: undefined method `[]' for nil:NilClass Backtrace:
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/synced_folders/rsync/helper.rb:74:in `rsync_single'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/synced_folders/rsync/command/rsync_auto.rb:218:in `block (2 levels) in callback'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/synced_folders/rsync/command/rsync_auto.rb:207:in `each'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/synced_folders/rsync/command/rsync_auto.rb:207:in `block in callback'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/synced_folders/rsync/command/rsync_auto.rb:206:in `each'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/vagrant-2.2.5/plugins/synced_folders/rsync/command/rsync_auto.rb:206:in `callback'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
    default:  -- D:/Vagrant/embedded/gems/2.2.5/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
Exiting due to interrupt.

```
