### ISSUE TITLE
Ability to run file provisioner in sudo mode

### ISSUE THREAD

**Issue by anandsuresh** [hashicorp/vagrant#4032]
Would be great to have a sudo mode for the file provisioner to copy files to certain locations that are owned by root. E.g. The /vagrant folder is owned by root on CentOS 6.5. Attempting to copy a file into that folder fails with the following:

```
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the SSH user doesn't have permission
to write to the destination location. Alternately, the user running
Vagrant on the host machine may not have permission to read the file.
```

**Comment by leaveye** [comment]
Being bite by this, provision job has not enough permission *feature*, I really think the solution above is ugly. Anyone agree with me?
