### ISSUE TITLE
`docker commit` through vagrant

### ISSUE THREAD

**Issue by ivotron** [hashicorp/vagrant#4035]
What makes Docker so awesome is the fact that you can mess around with a container and commit the changes to an image. AFAIK, it is not possible to do this through vagrant's docker provider, right? In other words, if we do `docker commit` directly through docker, vagrant won't see this change and will keep pointing to the old image ID

**Comment by aquaglia** [comment]
I know this thread is very old, but suppose that I use ansible_local to provision. In that case I do not have the chance to commit from the Dockerfile.
