### ISSUE TITLE
vagrant does not honor proxy settings for vagrant cloud boxes

### ISSUE THREAD

**Issue by davidkarlsen** [hashicorp/vagrant#4051]
When using vagrantcloud boxes like:
vm.box = "user/boxname"

vagrant does not use the http_proxy settings (but it does when installing plugins!).

Thus vagrantcloud boxes are not usable from enterprisey networks that require you to configure a proxy server for http(s) traffic.

**Comment by jclagache** [comment]
I don't know if this issue should be re-opened or a new one should be created : downloading a box on vagrantcloud through a proxy works but not login.
Download is subprocessed to cURL, so the http_proxy environnent variable is used as expected. However, login is managed by [rest-client](https://github.com/rest-client/rest-client) but the login client does not deal with such environnent variable.
My workaround is to modify the login client constructor : 
```
module VagrantPlugins
  module LoginCommand
    class Client
      # Initializes a login client with the given Vagrant::Environment.
      #
      # @param [Vagrant::Environment] env
      def initialize(env)
        @logger = Log4r::Logger.new("vagrant::login::client")
        @env    = env
        RestClient.proxy = ENV['http_proxy']
      end
....
    end
  end
end
```
Do you think that Vagrant has to deal with environnent proxy settings or leave this to the vagrant-proxyconf plugin (tmatilai/vagrant-proxyconf#53) ?
