### ISSUE TITLE
Vagrant rsync 255 error (possibly Vagrant not picking up right IP from Vagrantfile)

### ISSUE THREAD

**Issue by nomasprime** [hashicorp/vagrant#4139]
Tried everything I can think of to get Vagrant synced folders working with a Windows guest. Furthest I've got is with rsync. I can ssh between the two machines but rsync still throws up this vague error:

```
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /somepath
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --no-owner --no-group -e ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/Users/rick/.vagrant.d/insecure_private_key' --exclude .vagrant/ --exclude .git/ /somepath vagrant@127.0.0.1:/vagrant
Error: ssh: connect to host 127.0.0.1 port 22: Connection refused
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at /SourceCache/rsync/rsync-42/rsync/io.c(452) [sender=2.6.9]
```

A curiosity is if I turn on OS X Remote Login then I'm asked for a password but I thought this connection would be one way, looks like it could be trying to connect to host and never reaching guest. 

A couple of lines from my Vagrantfile that could be relevant:

```
config.vm.network "private_network", ip: "192.168.50.4"
config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
```

Think this could be a problem with Vagrant not picking up right IP address and therefore trying to connect back to itself.

**Comment by n8green** [comment]
Hitting this issue with a windows 2008 guest, running SSHd. I can manually SSH from the host to the IP I defined in the Vagrantfile, however when trying to spin up the box with an rsync file sharing configuration Vagrant assumes the IP to connect to is 127.0.0.1 - which from the host will obviously not work. 

Is there a way I can override this?
