### ISSUE TITLE
Grouping Provision Commands

### ISSUE THREAD

**Issue by 3goats** [hashicorp/vagrant#4140]
I've read through the Vagrant docs but can't seem to work out if its possible to create  groups of provision commands, or something that provides a similar capability. e.g.

``` ruby
def group1()
   config.vm.provision "shell", :path=> "echo 'hello group 1'"
   config.vm.provision "shell", :path=> "echo 'hello I'm group 1'"
end
def group2()
   config.vm.provision "shell", :path=> "echo 'hello group 2'"
   config.vm.provision "shell", :path=> "echo 'hello I'm group 2'"
end
```

Then specify the provisioning group as part of the vagrant up or provision commands. e.g.

`vagrant up group1` or `vagrant provision group2`

**Comment by johanwasserman** [comment]
upvote
