### ISSUE TITLE
Please make number of ssh connect retries configurable

### ISSUE THREAD

**Issue by lsimons** [hashicorp/vagrant#4172]
I'm spinning up nested xen server instances in a cloudstack environment controlled using vagrant-cloudstack. These instances take a while to boot and then have to reboot before SSH becomes available. During a lot of this time it is refusing connections rather than timing out:

```
 INFO ssh: Attempting SSH connnection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 178.237.34.118
 INFO ssh:   - Port: 3031
 INFO ssh:   - Username: root
 INFO ssh:   - Password? true
 INFO ssh:   - Key Path: []
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2014-07-09T17:23:05.832659 #98571] DEBUG -- net.ssh.transport.session[807710fc]: establishing connection to 178.237.34.118:3031

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO retryable: Retryable exception raised: #<Errno::ENETUNREACH: Network is unreachable - connect(2)>
```

Vagrant runs out of retries before the host is up. My manual hack to plugins/communicators/ssh/communicator.rb works:

```
        ### start monkey-patch
        # opts[:retries] = 5 if !opts.has_key?(:retries)
        opts[:retries] = 500 if !opts.has_key?(:retries)
        ### end monkey-patch
```

Unfortunately, vagrant-cloudstack calls `ready?` which does not allow passing the :retries option through to `connect`. I think the nice approach is for the retries option to be configurable from the Vagrantfile, i.e. as a config.ssh.retries setting or similar.

(I don't have a patch as it is taking me far too long trying to figure out how the vagrant plugin and config merging magic works.)

(And thanks for vagrant! It's awesome!)

**Comment by FlorianHeigl** [comment]
@mitchellh that doesn't work. it doesn't wait for 30s and then time out. can you have a long look at the original error please... it tries to connect, finds the remote host down and aborts immediately. no timeout is involved. I'm afraid this needs to be solved with either just retries or a sep. error path for "host is not doing IP yet" not a tcp timeout.
Retries sound nice.

**Comment by FlorianHeigl** [comment]
this might be a wrapper around the problem:
http://www.rubydoc.info/gems/vagrant-skytap/0.1.8/VagrantPlugins/Skytap/Action/WaitForCommunicator

**Comment by FlorianHeigl** [comment]
Is it possible that this returns because ssh_info is true (but contains the exception only)?

(/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/communicators/ssh/communicator.rb)
`      def wait_for_ready(timeout)
        Timeout.timeout(timeout) do
          # Wait for ssh_info to be ready
          ssh_info = nil
          while true
            ssh_info = @machine.ssh_info
            break if ssh_info
            sleep 0.5
          end`

**Comment by FlorianHeigl** [comment]
For whoever runs into this:

I've managed to overload the WaitForCommunicator lib with the one from Skytap.

`utopia:opennebula-provider-1.1.2 floh$ grep -R -A2 -B2 Sky *
lib/opennebula-provider/action.rb-    module Action
lib/opennebula-provider/action.rb-      include Vagrant::Action::Builtin
lib/opennebula-provider/action.rb:      include VagrantPlugins::Skytap::Action
lib/opennebula-provider/action.rb-
lib/opennebula-provider/action.rb-      def self.destroy`

That now gives a retry loop that doesn't look 100% beautiful but _far_ better than aborting.
