### ISSUE TITLE
`vagrant ssh` is noticeably slower than plain `ssh`

### ISSUE THREAD

**Issue by makeamark1** [hashicorp/vagrant#4214]
Logging into a Vagrant machine using `vagrant ssh` takes several seconds, while logging in using a direct invocation of `ssh` only takes tenths of milliseconds (see below for details). The slowness of `vagrant ssh` is especially annoying in interactive use with repeated logins/logouts, where it is immediately noticeable (and reflects badly on Vagrant as looking slow). Is there any way of getting the `vagrant ssh` execution time on par with plain `ssh`?

```
$ time vagrant ssh -c :
Connection to 127.0.0.1 closed.
Time: 1.72s real 1.38s user 0.23s system 93.87 cpu
$ vagrant ssh-config > config && time ssh -F config default :
Time: 0.04s real 0.01s user 0.00s system 35.31 cpu
$ vagrant version
Installed Version: 1.6.3
Latest Version: 1.6.3
```

**Comment by filex** [comment]
A while ago, I've written a simple shell-wrapper that boils everything that `vagrant ssh` can do (with multiple boxes and providers and ..) down to a stupid _ssh-into-default-virtualbox_: https://github.com/filex/vagrant-ssh.

It's by no means a general replacement for `vagrant ssh`. But it can handle direct commands like `vagrant-ssh -- whoami`.
