### ISSUE TITLE
Image download progress for docker provider

### ISSUE THREAD

**Issue by lzlarryli** [hashicorp/vagrant#4243]
When `vagrant up` pulls an image from Dockerhub, there is no download progress information. It does not even say it is pulling an image. For larger images or users with slower internet, there is no feedback or indication of anything happening, creating a "it just hangs" user experience.

With `VAGRANT_LOG=info vagrant up`, we can see the line saying it is pulling an image without download progress. With `VAGRANT_LOG=debug vagrant up`, we finally see 

```
DEBUG subprocess: stderr: Unable to find image 'xxx' locally
DEBUG subprocess: stderr: Pulling repository xxx
DEBUG subprocess: stderr: 
DEBUG subprocess: stderr: 
```

where each line `DEBUG subprocess: stderr:` corresponds to one line of docker's download progress output, but parsed to empty space.

It would be nicer if it says it is pulling an image and show the progress when `vagrant up` is executed without any log settings.

Possibly related issue:
https://github.com/mitchellh/vagrant/issues/3739

**Comment by gcaracuel** [comment]
@duro then, have you tested it? is it working? I cannottt test right now

Thanks!

**Comment by gcaracuel** [comment]
I have tested, "-i" flag is only for Docker run not for pull so ticket docker/docker#7658 is not solving this. Anyway I think this should be re-open.

**Comment by marzolfb** [comment]
Agreed on reopening - it feels like a "hang" to me when downloading a large container just like @roychoo  said.
