### ISSUE TITLE
Rsync not respecting rsync__exclude on *initial* sync

### ISSUE THREAD

**Issue by sursh** [hashicorp/vagrant#4248]
I'm trying to get Vagrant to sync `.` to `/vagrant`, as is the default behavior, _except_ for a few folders that I'd like to exclude. I'm finding that rsync is NOT respecting rsync__exclude on first sync when the VM is created, but seems to be working on subsequent rsyncs. 

I'm following along with [this documentation](http://docs.vagrantup.com/v2/synced-folders/rsync.html). I added an exclude line to my `Vagrantfile`:

``` ruby
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "aws"

  # Relevant bit:
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: [".git/", "data/"]

  config.vm.provider :aws do |aws, override|
    # etc ..... 
```

I know that rsync sees this, since running `vagrant rsync` gives the following output: 

```
$ vagrant rsync
==> default: Rsyncing folder: /Users/sasha/code/client-name/ => /vagrant
==> default:   - Exclude: [".vagrant/", ".git/", "data/"]
```

and when I blow away the contents of `/vagrant` and re-rsync with `vagrant rsync`, those files & folders are _not_ recreated, as expected. 

However, when the machine is initially created, the exclude is NOT respected and .git/ and data/ are copied over. Here is the relevant output from that process. 

```
==> default: Waiting for instance to become "ready"...
==> default: Waiting for SSH to become available...
==> default: Machine is booted and ready for use!
==> default: Rsyncing folder: /Users/sasha/code/LTV/ => /vagrant
==> default: Running provisioner: shell...
```

and when I ssh into the box:

```
ubuntu@ip-x-x-x-x:/vagrant$ ls d
data/    
ubuntu@ip-x-x-x-x:/vagrant$ ls .git
.git/       .gitignore  
```

What's going on here? Why the different behavior? And can I get the initial rsync to exclude certain folders?

**Comment by trompx** [comment]
I have the same problem : Vagrant 1.7.2
My Vagrantfile is in a websites folder : 
- websites
   - project_1
   - project_2

When for example I work on project_1, I rsync websites, exlcude project_2 and exclude project_1/node_modules.

I want to only install node modules on the VM, it works when I vagrant up on initial rsync, but as soon as I "vagrant rsync-auto" the exclude project_1/node_modules is not respected and my VM node_modules folder is removed (as not present on the host).

If I then "mkdir node_modules" in project_1, it is not removed in the VM as expected.

Any update or solution for respecting the exclude on initial vagrant rsync-auto ?

Thank you
