### ISSUE TITLE
Feature Request: RDP auto login with password

### ISSUE THREAD

**Issue by xWayfinder** [hashicorp/vagrant#4300]
It would be very useful to be automatically logged into a Windows machine when I provide a password for rdp in the Vagrantfile and run the command 'vagrant rdp'. 

Use Case: currently I do a lot of configuration on Windows machines which requires me to rdp into the boxes repetitively, it seems quite arbitrary for me to log in each time as I will be doing this maybe 20 times or so during the day.

**Comment by retrogradeorbit** [comment]
If you are using rdesktop on linux for the rdp calls, then

```
vagrant rdp machinename -- -p password
```

works. Would be nice if it was built in to vagrant so you don't have to keep issuing it on the commandline.

**Comment by majkinetor** [comment]
This is not correct info. With `mtsc` you can achieve this thing easily. Given that vagrant machine ip is `192.168.0.10`:

    cmdkey /generic:TERMSRV/192.168.0.10 /user:vagrant /pass:vagrant
    mstsc /v 192.168.0.10
