### ISSUE TITLE
setting the hostname on CentOS 7

### ISSUE THREAD

**Issue by pazooki** [hashicorp/vagrant#4352]
Apparently the right way to set the hostname in el7 is by using hostnamectl.
hostnamectl set-hostname {{ your_hostname }}

right now vagrant can't set hostname for Centos 7 ...

**Comment by dmacvicar** [comment]
So this has to be fixed duplicating the hostnamectl call in all every distro that uses systemd?. I noticed arch also has this code and SLES-12 still fails.

Is copy-paste the call to a guest plugin the right approach?

**Comment by jdiez17** [comment]
+1, all distros that use systemd set the hostname via hostnamectl. I just ran into this issue on a Fedora 23 Server box, where Vagrant sets the hostname by writing to `/etc/hostname` (see [here](https://github.com/mitchellh/vagrant/blob/master/plugins/guests/fedora/cap/change_host_name.rb#L41)). This is interpreted as a "transient hostname" and does not persist across reboots.
