### ISSUE TITLE
disable virtualbox provider

### ISSUE THREAD

**Issue by brettlangdon** [hashicorp/vagrant#4375]
I am using virtualbox with `vagrant-libvirt` and do not have virtualbox installed on my machine and when I try to `vagrant up` I am getting the following warning, even though I have `VAGRANT_DEFAULT_PRODIVER=libvirt`, is there a way for me to tell vagrant not to consider virtualbox provider at all? I am thinking something similar to `devbox.vm.synced_folder '.', '/vagrant', disabled: true` for the default shared folder.

```
The provider 'virtualbox' that was requested to back the machine
'devbox' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
```

If it helps at all, I am on 1.6.3, and I can provide more config information if necessary.

**Comment by spyderdyne** [comment]
This isnt working for me.  I have tried multiple ways of doing this and cannot seem to make it use the libvirt provisioner.  I was originally using Virtualbox and ran into some issues with it.  I then removed it, removed and reinstalled Vagrant (after deleting the ~/.vagrant.d folder and its contents,) and installed the libvirt components.  I am getting this erorr now:

Creating Medusa Gorgon (server) Image
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

Creating Medusa Serpent (slave) Image
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

Medusa Image Creation Completed...

From the docs: https://docs.vagrantup.com/v2/providers/basic_usage.html

1.  I am setting the VAGRANT_DEFAULT_PROVIDER (2) in my image creation script here:

http://bazaar.launchpad.net/~openstack-tailgate/openstack-tailgate/trunk/view/head:/mythos/images/create-images.sh

It is ignored...

I am setting the provider in the Vagrantfile with config.vm.provider (3) here:

http://bazaar.launchpad.net/~openstack-tailgate/openstack-tailgate/trunk/view/head:/mythos/images/server/Vagrantfile

It is also ignored...

The only thing I have not tried is using the --provisioner (1) flag, but I shouldnt have to.  Am I using the wrong style of Vagrantfile or something?

Thanks.

**Comment by spyderdyne** [comment]
Created new topic since this one is closed:

https://github.com/mitchellh/vagrant/issues/6397
