### ISSUE TITLE
Connection refused,vm ssh is not a available

### ISSUE THREAD

**Issue by HouCoder** [hashicorp/vagrant#4470]
OS: Windows 8.1 X64
Virtualbox version: 4.3.14 r95030
Vagrant version: 1.6.5
Log:

```
C:\Users\Tonni\Vagrant\Ubuntu>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minut
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
    default: Warning: Connection refused. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

booting vm stuck at SSH auth, i use telnet to detect vm ssh status ,but it seems vm ssh is not working at all.
![unnamed qq screenshot20140907094839](https://cloud.githubusercontent.com/assets/5292143/4177278/2bfea22c-3631-11e4-86fc-3717111225a5.png)

**Comment by nalybuites** [comment]
@micanzhang, I don't believe this is the case. The people above have experienced this issue with precise32. I'm seeing it with hashicorp/precise32, hashicorp/precise64, and ubuntu/trusty64. Those are the only VMs I've tried.

**Comment by cfarrell81** [comment]
Possibly unrelated but when I was having trouble getting going with Vagrant & virtual box, installing the VM VirtualBox Extension Pack for my particular version of virtualbox sorted me out https://www.virtualbox.org/wiki/Downloads

**Comment by jjshoe** [comment]
One possible solution on linux is that the known_hosts entry has changed on you, this will prevent you from being able to `vagrant ssh`

**Comment by nalybuites** [comment]
It has not. On a Mac with a static known_hosts file. There should be no
reason that it would change without warning. That would be a serious
security issue with SSH, otherwise.

[ mobile ]

**Comment by jjshoe** [comment]
Your reply doesn't compute.

**Comment by nalybuites** [comment]
Why not? SSH always asks before modifying known_hosts. Unless you're
talking about the allowed hosts list on the server, which is something
completely different.

[ mobile ]

**Comment by jjshoe** [comment]
Right, it asks, which is exactly why vagrant ssh couldn't connect, because I couldn't be warned about a changed identity...

**Comment by nalybuites** [comment]
Local host is in the known hosts file.

[ mobile ]

**Comment by jjshoe** [comment]
You don't have to use localhost to connect to a vagrant instance.

**Comment by nalybuites** [comment]
I'm connecting from localhost to a vagrant VM on that machine.

[ mobile ]

**Comment by jjshoe** [comment]
@nalybuites - Ah, that's where the confusion is. @HouCoder opened this ticket, I merely replied with one possible thing to look at. Then there is you, who has never posted a question in this entire thread, so I'm not sure what you're talking about.

**Comment by nalybuites** [comment]
My bad, I thought this was the ticket I posted. Very similar issue though,
unable to SSH into a completely fresh VM.

[ mobile ]
