### ISSUE TITLE
FR: PXE-booting "blank" VMs

### ISSUE THREAD

**Issue by aspiers** [hashicorp/vagrant#4487]
AFAICS it is not currently possible to write a `Vagrantfile` which persuades Vagrant to boot a "blank" VM, i.e. one with a fresh, uninitialized virtual disk suitable for PXE-booting, without involving any Vagrant box:

```
vagrant up controller1
Bringing machine 'controller1' up with 'libvirt' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* A box must be specified.
```

If that is true, please consider this a feature request, and if not, please consider it a documentation bug that it is not more obvious how to do it ;-)

The use case I need it for is a multi-machine `Vagrantfile` where the first machine boots from a box and sets up a DHCP/TFTP server which subsequent machines can PXE-boot from.  In this way you could set up an entire environment of multiple machines from a single suitably-crafted box.

**Comment by infernix** [comment]
@aspiers I've gotten proper PXE boot order merged in https://github.com/pradels/vagrant-libvirt/pull/425 and I'm looking at the docker example, but don't see a trivial way to add the remaining ```:no_box``` functionality to ```vagrant-libvirt``` just yet. 

I think there are at least three use cases here:
* PXE booting VMs with no disk whatsoever (yours) 
* PXE booting VMs with no box but with an extra disk on which the OS gets installed over the network (mine)
* PXE booting VMs with a blank box and no extra disk on which the OS gets installed over the network (mine)

In all cases I think the behaviour should be such that Vagrant builds the VM (and optionally attaches a blank box) but then does nothing more than start it; it shouldn't even care to see what DHCP IP it was given. Not sure if the libvirt plugin can really handle that case well.

**Comment by aspiers** [comment]
Thanks!  Actually my use case is the second not the first :)  But there's probably someone out there who might appreciate the first (e.g. testing root over NFS environments).  I agree with your assessment of the desired behaviour.

**Comment by infernix** [comment]
@aspiers if able, please test my PR @ https://github.com/pradels/vagrant-libvirt/pull/442. Thanks!

**Comment by aspiers** [comment]
I will try to find time but unfortunately it's very unlikely to happen in the next month or so, sorry!

**Comment by darksheer** [comment]
I would like to see this capability as well. We're using the product mentioned, but have a number of use cases for allowing the provisioning of systems via vagrant straight into pxe.

**Comment by infernix** [comment]
@darksheer this is merged already in https://github.com/pradels/vagrant-libvirt, just not released yet as a new version.

**Comment by darksheer** [comment]
Great, thank you for the update. Will the same change be allowed for other providers than libvirt? VMware, VirtualBox, fusion, etc?

**Comment by infernix** [comment]
It is possible from Vagrants point of view but each provider plugin needs to implement it individually. I personally only need libvirt so you'd need to check with the plugin authors.

**Comment by darksheer** [comment]
Thanks, I'll pass along your PR as reference to the other provider plugin groups.

**Comment by marcindulak** [comment]
I have two questions about the status of pxe booting of boxes.

At https://github.com/pradels/vagrant-libvirt#no-box-and-pxe-boot I'm reading:
"In short, VMs without a box can be created, halted and destroyed but all other functionality cannot be used.". Specifically:
...
- No provisioning scripts are ran
- No network configuration is being applied to the VM
- No SSH connection can be made
...
What is the source of these limitations: vagrant, libvirt, the vagrant-libvirt plugin itself?

Second question, related to the first one:

I'm taking a different approach to pxe boot in Vagrant with Virtualbox provider: I take a standard box (e.g. puppetlabs/centos-6.6-64-nocm), perform a pxe installation ontop of it (using the old systemimager software), and use kexec to boot into the installed kernel. The installed system is functional, I can ssh to it, network settings and provisioning are applied, etc., but such VM hangs after rebooting (VBox's GUI shows black screen with a "dead" cursor). The Vagrantfile is available at https://github.com/marcindulak/vagrant-systemimager-tutorial-centos6/ . Is this hang related to some limitations of this approach?

**Comment by infernix** [comment]
@marcindulak SSH connections cannot be made because Vagrant does not do any provisioning. When a PXE box is started with no disks for example, Vagrant does not know if there is even a vagrant user or what the IP of the PXE booted box would be. So any vagrant actions that rely on ssh (provisioning) are not supported because we can't guarantee that they will work in such cases. Once the PXE node is booted and an OS is running on it, ssh *outside of vagrant* will work fine of course. 

Can't say much about your VBox problem unfortunately.

**Comment by jamesalbert** [comment]
Late to the party here. @infernix does that mean when vagrant is "Waiting for machine to boot", that it's normal for it to fail? If so, is there any way of confirming that it actually pxe booted?

**Comment by eoli3n** [comment]
Need it too with virtualbox provider.

**Comment by benh57** [comment]
I got this partially working with Vagrant. I'll turn it into a PR at some point.

**Comment by benh57** [comment]
(correction -- partially working with virtualbox)
