### ISSUE TITLE
Sometimes hangs on "Waiting for VM to boot. This can take a few minutes."

### ISSUE THREAD

**Issue by jonleighton** [hashicorp/vagrant#455]
HI there,

Sometimes (I mean, fairly often, maybe 30-50% of the time for me) vagrant seems to hang on:

```
Waiting for VM to boot. This can take a few minutes.
```

I mean possibly it would finish eventually, but I have never waited to potentially infinite length of time to see. It certainly seems to take longer than 'usual', when I do manage to successfully boot.

When this happens, the only thing I can do is poweroff the VM through VBoxManage and try again.

Is there any way I can get more output about what it's doing in order to help debug this?

Cheers

**Comment by xacaxulu** [comment]
I have this problem too. It seems like the issue isn't actually 'closed' given how many people are reporting similar issues on mainstream OS's.
