### ISSUE TITLE
Vagrant says VirtualBox Version is Not Supported

### ISSUE THREAD

**Issue by ishansharma** [hashicorp/vagrant#4563]
I have Vagrant 1.6.3 and VirtualBox 4.3.12 on Windows 8.1 Pro(64 bit). Since yesterday, Vagrant started giving this error:

```
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
```

I have tried installing different versions of Vagrant and VirtualBox but same result. How can I resolve this?

**Comment by rtancman** [comment]
Try update to version 1.7.4 because I have same problem but new version fix it
