### ISSUE TITLE
The 'provision "docker"' command no longer work

### ISSUE THREAD

**Issue by svlasov** [hashicorp/vagrant#4569]
When I'm trying to run "vagrant provision" command with  
    provision "docker"
in my Vagrantfile, I receive

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

curl http://get.docker.io/gpg | apt-key add -

Stdout from the command:

Stderr from the command:

stdin: is not a tty
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0     31      0  0:00:05  0:00:05 --:--:--    41
gpg: no valid OpenPGP data found.

**Comment by dragonfax** [comment]
I'm seeing this again.

```
little-boobop:docker-images dragonfax$ vagrant provision
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Running provisioner: docker...
    default: Installing Docker (latest) onto machine...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

curl http://get.docker.io/gpg | apt-key add -

Stdout from the command:



Stderr from the command:

stdin: is not a tty
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
gpg: no valid OpenPGP data found.

```

**Comment by dragonfax** [comment]
My mistake. Fixed in latest version.

**Comment by pykiss** [comment]
Same error today

    ==> default: Running provisioner: docker...
        default: Installing Docker (latest) onto machine...
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!

    curl http://get.docker.io/gpg | apt-key add -

    Stdout from the command:



    Stderr from the command:

    stdin: is not a tty
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    gpg: no valid OpenPGP data found.

**Comment by alexbeletsky** [comment]
I'm still having that issue, 

```
› vagrant --version
Vagrant 1.7.4
```

What update am I missing?
