### ISSUE TITLE
VMWare provider won't install

### ISSUE THREAD

**Issue by ghost** [hashicorp/vagrant#4575]
The VMWare provider won't install as the installation depends on the gem ffi-1.9.5, but version 1.9.3 is what is available with the latest version of Vagrant.

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.5), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.5'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
/Applications/Vagrant/embedded/bin/ruby extconf.rb
```

/Applications/Vagrant/embedded/bin/ruby: invalid option -H  (-h will show valid options) (RuntimeError)

Gem files will remain installed in /Volumes/Macintosh HDD/Imac-1/.vagrant.d/gems/gems/ffi-1.9.5 for inspection.
Results logged to /Volumes/Macintosh HDD/Imac-1/.vagrant.d/gems/gems/ffi-1.9.5/ext/ffi_c/gem_make.out

**Comment by brennovich** [comment]
I would like to install it without any developer tools on my machine (as I currently do with VirtualBox) :/
