### ISSUE TITLE
Cannot set a private IP on a windows guest with Parallels provider

### ISSUE THREAD

**Issue by carcus88** [hashicorp/vagrant#4581]
I am using the Vagrant 1.6.5 and the vagrant-parallels plugin 1.2.2 on OS X 10.9.5 
All the latest stuff so far as I can tell.

I've been using Vagrant with Parallels for about a year now and I'm pretty sure I don't have anything wrong with my configs. The problem is that I need to set a static IP on a Windows guest and it never takes. It always falls back to using DHCP. I have a ton of Linux guests this setup works for without an issue.

```
config.vm.network "private_network", ip: "192.168.56.139"
```

I've tried two boxes so far from vagrantcloud both with the same results

https://vagrantcloud.com/lmayorga1980/boxes/windows7-sp1
https://vagrantcloud.com/scorebig/boxes/windows-2012R2-SC

When vagrant starts up it never finds the adapter and leaves it with the default DHCP configuration. Nothing is shown however in the normal vagrant up output but enabling debug shows this

```
 WARN configure_networks: Could not find interface for network {:type=>:static, :adapter_ip=>"192.168.56.1", :ip=>"192.168.56.139", :netmask=>"255.255.255.0", :auto_config=>true, :interface=>1}
```

[Full Log](https://gist.github.com/carcus88/8913a5bf70801020b1a3)

I've tried just about everything I can think of and nothing will set the adapter IP to a static value. I tried to create multiple networks in the vagrant file and they all end up the same way with DHCP. If I set the adapter IP manually inside it will persist through halts and ups but thats not a solution, just an observation.

**Comment by mewm** [comment]
@carcus88 did you ever manage to find the reason for this? I'm experiencing the exact same problem. Thanks for the hack though :)

**Comment by carcus88** [comment]
@mewm No I haven't found the problem but I was getting back into working on my Windows box today so I'll poke around again and see if anything has changed. Are you using parallels 8,9, or 10?

**Comment by mewm** [comment]
@carcus88 Alright... I'm using Parallels v10

**Comment by legal90** [comment]
The reason is a type error here:
[plugins/guests/windows/cap/configure_networks.rb#L26](https://github.com/mitchellh/vagrant/blob/bb052366f7f9616666299a97edcceadae007394a/plugins/guests/windows/cap/configure_networks.rb#L26)

```ruby
...
            vm_interface_map = create_vm_interface_map(machine, guest_network)
            networks.each do |network|
              interface = vm_interface_map[network[:interface]+1]
              if interface.nil?
                @@logger.warn("Could not find interface for network #{network.inspect}")
                next
              end
...
```
Keys in the `vm_interface_map` hash are strings, but `interface` is fetching the value by integer key. In the result, all secondary adapters are not configured regardless of the provider.

I'll try to fix it and send a pull-request soon

cc:\ @mitchellh

**Comment by legal90** [comment]
Ah, sorry, I found the root cause: `nic_mac_addresses` should return a hash with integer keys.
I've fixed it in the Parallels provider.

P.s. Anyway, it might be useful to apply `.to_i` or `.to_s` in the hunk I've mentioned above. It will help to avoid such "hidden" errors.
