### ISSUE TITLE
Multiple 'ERROR loader: Unknown config sources: ...' messages showing up when deploying multi VM projects

### ISSUE THREAD

**Issue by marnovdm** [hashicorp/vagrant#4585]
When deploying a multi VM project with 'VAGRANT_LOG=warn vagrant up' I get multiple of these errors. An example of such output from a project with 17 VMs:

ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev", "27046540_machine_sql001.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev", "27046540_machine_sql001.apm.dev", "27046540_machine_php001.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev", "27046540_machine_sql001.apm.dev", "27046540_machine_php001.apm.dev", "27046540_machine_php002.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev", "27046540_machine_sql001.apm.dev", "27046540_machine_php001.apm.dev", "27046540_machine_php002.apm.dev", "27046540_machine_php003.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev", "27046540_machine_sql001.apm.dev", "27046540_machine_php001.apm.dev", "27046540_machine_php002.apm.dev", "27046540_machine_php003.apm.dev", "27046540_machine_mem001.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev", "27046540_machine_sql001.apm.dev", "27046540_machine_php001.apm.dev", "27046540_machine_php002.apm.dev", "27046540_machine_php003.apm.dev", "27046540_machine_mem001.apm.dev", "27046540_machine_mem002.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev", "27046540_machine_sql001.apm.dev", "27046540_machine_php001.apm.dev", "27046540_machine_php002.apm.dev", "27046540_machine_php003.apm.dev", "27046540_machine_mem001.apm.dev", "27046540_machine_mem002.apm.dev", "27046540_machine_wrk101.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev", "27046540_machine_sql001.apm.dev", "27046540_machine_php001.apm.dev", "27046540_machine_php002.apm.dev", "27046540_machine_php003.apm.dev", "27046540_machine_mem001.apm.dev", "27046540_machine_mem002.apm.dev", "27046540_machine_wrk101.apm.dev", "27046540_machine_wrk102.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev", "27046540_machine_sql001.apm.dev", "27046540_machine_php001.apm.dev", "27046540_machine_php002.apm.dev", "27046540_machine_php003.apm.dev", "27046540_machine_mem001.apm.dev", "27046540_machine_mem002.apm.dev", "27046540_machine_wrk101.apm.dev", "27046540_machine_wrk102.apm.dev", "27046540_machine_wrk103.apm.dev"]
ERROR loader: Unknown config sources: ["27046540_machine_gear001.apm.dev", "27046540_machine_gear002.apm.dev", "27046540_machine_mon001.apm.dev", "27046540_machine_mon002.apm.dev", "27046540_machine_log001.apm.dev", "27046540_machine_cfg001.apm.dev", "27046540_machine_sql001.apm.dev", "27046540_machine_php001.apm.dev", "27046540_machine_php002.apm.dev", "27046540_machine_php003.apm.dev", "27046540_machine_mem001.apm.dev", "27046540_machine_mem002.apm.dev", "27046540_machine_wrk101.apm.dev", "27046540_machine_wrk102.apm.dev", "27046540_machine_wrk103.apm.dev", "27046540_machine_wlb001.apm.dev"]

This does not prevent deployment of the machines but the output seems to suggest something is wrong. Is this something I can fix locally (perhaps old cache or something, somewhere)?

Obviously this is not a big issue as the deployment works, but it does clutter the terminal output which can make it harder to troubleshoot real issues. If I can provide any more information to help troubleshoot this please let me know. Thanks!

**Comment by jdwelch** [comment]
So, if it's just a warning, why isn't it marked as such, and more importantly, able to be silenced. It's really annoying to see this noise many times a day.

**Comment by invernizzie** [comment]
Completely agree with @jdwelch above. I'm getting these errors when trying to start a kubernetes cluster using the vagrant provider. The machines don't seem to finish Salt provisioning, but I'm not sure if this error is related or not as it might only be a "warning". ¬¬
