### ISSUE TITLE
Box doesn't support requested provider

### ISSUE THREAD

**Issue by ghost** [hashicorp/vagrant#4599]
I've uploaded a box to Vagrant Cloud. It was built using Packer, and I'm able to add it locally using `vagrant box add` and use it just fine in my Vagrantfile. I'm now trying to pull this image down automatically from the cloud, and am getting the following error:

```
==> default: Box '(my_organization)/lamp' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box '(my_organization)/lamp'
    default: URL: https://vagrantcloud.com/(my_organization)/lamp

The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

Name: (my_organization)/lamp
Address: https://vagrantcloud.com/(my_organization)/lamp
Requested provider: [:virtualbox]
```

I've set the provider on the cloud to virtualbox, and used the virtualbox-iso builder. I've tried running this straight from a fresh 'vagrant init' and get the same error. What am I missing?

Vagrant version 1.6.5
VirtualBox version 4.3.14
Packer version 0.7.1

**Comment by alaindomissy** [comment]
This message is still confusing:

> The box you're attempting to add doesn't support the provider
> you requested. Please find an alternate box or use an alternate
> provider. Double-check your requested provider to verify you didn't
> simply misspell it.

It seems to imply that the box was found but is missing support for a particular provider.
Could we instead say :
> The box you're attempting **was not found or** it doesn't support the provider
> you requested. Please find an alternate box or use an alternate
> provider. Double-check your requested provider to verify you didn't
> simply misspell it.

Thanks
