### ISSUE TITLE
Shell provisioner doesnt run sed properly

### ISSUE THREAD

**Issue by armando-fandango** [hashicorp/vagrant#4611]
Vagrant 1.6.x on Mac OSX with VirtualBox latest and Ubuntu 14.04.1 machine
I have this line in shell provisioner: 
sudo sed -i 's/(.config..map_path..).*/\1/' /var/www/html/simiangrid/Grid/config/config.php.tpl

The same line works well when run in same Vm by logging in through vagrant ssh

It should look for this line and remove = "" : $config["map_path"] = "";

Why this doesnt work in shell provisoner ?

Thanks

**Comment by khessels** [comment]
I encountered problems when using a newline in the replace text
The first statement with new line character

Works (but would break apache):
sed -i "s^#LogLevel info ssl:warn^<Directory /home/vagrant/ability/v1/web>   Options Indexes FollowSymLinks   AllowOverride All   Require all granted</Directory>^" /etc/apache2/sites-available/000-default.conf

Does not work and produces an error:
sed -i "s^#LogLevel info ssl:warn^\n<Directory /home/vagrant/ability/v1/web>\n   Options Indexes FollowSymLinks\n   AllowOverride All\n   Require all granted\n</Directory>^" /etc/apache2/sites-available/000-default.conf
