### ISSUE TITLE
provider-agnostic mechanism for configuring additional disks

### ISSUE THREAD

**Issue by aspiers** [hashicorp/vagrant#4630]
It is currently possible to tell some providers to add additional disks to the VM, e.g. via [`provider.customize` for VirtualBox](http://docs.vagrantup.com/v2/virtualbox/configuration.html) or [`provider.storage` for the `vagrant-libvirt` plugin](https://github.com/pradels/vagrant-libvirt/blob/master/README.md#additional-disks).  But it would make a lot of sense if this API was standardized across all providers, in the same way that `vm.network` already provides a standardized interface for setting up vNICs.  And actually the API which `vagrant-libvirt` already chose seems like a logical one to adopt for this.  

Of course, there would still be provider-specific storage options occasionally required, but that could be handled using the existing double-underscore convention.

**Comment by remilapeyre** [comment]
Has there been work on this feature? I need it as well and will try to do it if nobody is working on it.

**Comment by briancain** [comment]
Hey all! Sorry this wasn't closed earlier, but this has been implemented via https://github.com/hashicorp/vagrant/pull/11165, and currently Vagrant has a VirtualBox implementation already merged into master via https://github.com/hashicorp/vagrant/pull/11349. Hyper-V and VMWare are soon to follow. Thanks!
