### ISSUE TITLE
Issue downloading json file from box_url

### ISSUE THREAD

**Issue by bhundven** [hashicorp/vagrant#4647]
In issue: https://github.com/coreos/coreos-vagrant/issues/165
the issue is that a url that is able to be fetched from the command-line, but not able to be fetched from config.vm.box_url from within vagrant.

The issue linked to above has all of the detail and debug output.

**Comment by ineu** [comment]
@mitchellh 
I agree that this is very hard to understand real issue here, especially with `--debug` option being undocumented. If it cannot fetch box or metadata, it should give proper error message. Please consider fixing this.
