### ISSUE TITLE
"Renaming the Windows guest failed."

### ISSUE THREAD

**Issue by romu70** [hashicorp/vagrant#4683]
Hi,
I'm pretty new to Vagrant. My final goal is to be able to drive a remote KVM server to control Windows and Linux boxes. As I'm having a lot of issues, I'm trying to isolate the problems into small ones.

So first one issue: driving a Windows VirtualBox VM from a Linux host.
1. I created the Windows VM
2. Added a vagrant/vagrant administrator account
3. installed Cygwin to get SSH connectivity
4. Packaged the VM as a base box.

The, I created the following Vagrantfile:

```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.windows.set_work_network = true

  config.vm.box = "v7" 
  config.vm.define "v7" do |the|

    the.vm.boot_timeout = 180
    the.vm.box = "v7"
    the.vm.hostname = "v7"
    the.vm.communicator = "ssh"
    the.ssh.username = "vagrant"
    the.ssh.password = "vagrant"
    the.vm.guest = :windows
    the.vm.network "public_network"

    config.vm.provider "virtualbox" do |v|
      v.name = config.vm.box
      v.gui = true
      v.memory = 4096
    end
  end
end
```

And I get the output:

```
==> v7: Inserting Vagrant public key within guest...
==> v7: Machine booted and ready!
==> v7: Checking for guest additions in VM...
==> v7: Setting hostname...
Renaming the Windows guest failed. Most often this is because you've
specified a FQDN instead of just a host name.
```

And here, I'm stuck, because I don't understand this message. Any help? Thanks.

**Comment by albertorugnone** [comment]
@romu70 hi have you solved? I have the same problem and I am in stuck too

**Comment by romu70** [comment]
@albertorugnone didn't try since.

**Comment by softilium** [comment]
try to append :

config.vm.communicator = "winrm"
