### ISSUE TITLE
vagrant ssh --command logs in instead of execute command

### ISSUE THREAD

**Issue by doerler** [hashicorp/vagrant#4757]
If I try to execute a command from the host directly inside the guest with

```
vagrant ssh -c 'cat /proc/cpuinfo'
```

I get logged into the virtual machine instead of executing the command from 'remote'

```
Host:myvagrantboxfolder user$ vagrant ssh -c 'cat /proc/cpuinfo'
vagrant@guest:~$ 
```

My Host is OS X Yosemite and the guest is a Debian Wheezy 64 Bit. Vagrant is running in version 1.6.5

Markus

**Comment by raiyuza** [comment]
I have this issue. How exactly did you resolve this ? I re-installed vagrant and my homestead box several times. Also removed the .vagrant.d folder from my home directory.

Any help whould be greatly appreciated as not having this functionality breaks alot of my install scripts.
