### ISSUE TITLE
Puppet agent provisioner should support structured facts

### ISSUE THREAD

**Issue by purpleidea** [hashicorp/vagrant#4762]
Puppet now supports structured facts [1]. In fact, facts don't always have to be strings anymore!

Since the puppet agent provisioner [2] passes in facts as strings via the FACTER_varname environment variables, only strings are supported. You can work around this for simple cases, but it requires custom code, and would be nicer to have as a built in. [3]

How to do this:
If you need structured facts from vagrant, then you first set a flag to true:

<pre>
config.vm.provision "puppet_server" do |puppet|
    puppet.structured_facts = true
    puppet.facter = {...}
end
</pre>

Then, the only difference is that when you run a 'vagrant provision', or a 'vagrant up', the vagrant command should first generate a vagrant.yaml file in /etc/facter/facts.d/ that contains all of the facts.

Advantages:
1) You don't need to pass in a huge mess of environment variables
2) If you don't run with 'vagrant provision', and instead you run manually from the vm host, then the facts will still work :)

I'm not working to implement this at the moment, so it would be good if someone else would stand up to do it, but I figured I'd offer the design since it will solve two problems people have.

Cheers,
James

[1] https://docs.puppetlabs.com/facter/latest/custom_facts.html#external-facts
[2] http://docs.vagrantup.com/v2/provisioning/puppet_agent.html
[3] https://github.com/purpleidea/oh-my-vagrant/commit/ad5afa66be608b31055f4ad1338d082de0ba401d

**Comment by benh57** [comment]
I'll take a look at this since this is breaking for me.

**Comment by benh57** [comment]
I implemented this at https://github.com/benh57/vagrant/tree/puppet_structuredfacts 

I'm assuming that any structured facts are yaml data.

It can be used like so:

in vagrantfile:

require 'yaml'
    windows_facter_settings = {
            'foo' => 'bar',
  }

Then in the provisioner:

win.vm.provision "puppet", run: "always" do |puppet|
....
          puppet.structured_facts = true
          puppet.facter = windows_facter_settings.to_yaml
      end


This will also fix https://github.com/mitchellh/vagrant/issues/5660

**Comment by benh57** [comment]
I'll submit a PR for this soon.

**Comment by aloyr** [comment]
Hi @benh57, I got your structured_facts branch, rebased on top of @mitchellh vagrant/master and while that worked, I had to convert the facter to yaml on the VagrantFile, which could break existing setups, so instead I changed line 132 of your *plugins/provisioners/puppet/provisioner/puppet.rb* to this:
```
t.write(config.facter.to_yaml)
```
And that worked for me without having to change the VagrantFile. I would imagine this way would be preferable over the alternative, but I could be wrong... :)

My problem now is that I can't easily distribute my vagrant setup with other developers & designers on the team... So, my questions to you are:
- is there any disadvantage to convert the facter hash to yaml on the provisioner file like I did?
- is it OK to create a PR for this fix?

Thanks in advance,
-Peter

**Comment by aloyr** [comment]
Hi, just a quick update: while the solution on my PR works, not having native support for bundler vagrant plugins, and not having the ability to easily distribute our dev boxes to other devs that are not Ruby developers are deal breakers, so I found a workaround until this gets merged...

In vagrant, all we need to do is convert the structured facts to JSON, then inside puppet, use the *parsejson($::<factname>)* function to restore the structure of the fact. [In this example](https://github.com/aloyr/vp4p/blob/master/environments/dev/modules/drupal/manifests/web_stanza.pp#L3), all I did was wrap the previously structured fact with the parsejson function call and it all worked just fine.

**Comment by benh57** [comment]
Thanks @aloyr  ! I'll make that change -- but feel free to make a PR for my changes if you get to it before I do :) I'd also like to get this into the upstream vagrant soon, just been busy.

**Comment by aloyr** [comment]
Hi @benh57,

I have a [PR made already](https://github.com/mitchellh/vagrant/pull/7233)... I'd love to see the change upstream too. Right now I had to fallback to the stock build and use the JSON workaround to be able to share a Dev box with other developers and designers, but it would be awesome if the structured facts just worked. :)

-Peter

**Comment by goutham27** [comment]
Hi,

We are waiting for this feature, any update on when this will be released ?

Thanks

**Comment by m4ce** [comment]
Any news on this? We are also hitting this limitation.

**Comment by cdoublev** [comment]
It could probably help people to know by reading [Vagrant Documentation](https://www.vagrantup.com/docs/provisioning/puppet_apply.html#custom-facts), that Vagrant provided facts currently only accept string values. I was hitting a "Substring operation not permitted", and only this issue is what has allowed me to understand why.
