### ISSUE TITLE
VAGRANT_NO_PARALLEL doesn't work if defined in Vagrantfile

### ISSUE THREAD

**Issue by thomascramer** [hashicorp/vagrant#4843]
If you run "VAGRANT_NO_PARALLEL=true vagrant up" it works just fine.  But if you define "ENV['VAGRANT_NO_PARALLEL'] = 'true'" in the Vagrantfile, it doesn't.  However, other options like "VAGRANT_DEFAULT_PROVIDER" seems ok.  It would be good if we could make this configurable by ENV or some other means in the Vagrantfile to simplify the startup process..

**Comment by urquilla** [comment]
I agree with @thomascramer It would definitely be great if configurable in the vagrantfile like "VAGRANT_DEFAULT_PROVIDER'
