### ISSUE TITLE
Vagrant Share suddenly stopped working.

### ISSUE THREAD

**Issue by tbergeron** [hashicorp/vagrant#4848]
Hi,

I was using Vagrant Share and everything has been fine for the last days. I was using `vagrant share` whenever I needed to test something coming from the outside and it's been a breeze.

But suddenly it stopped working, told me that my 3 hours old share was expired so that's when I noticed it was weird since I thought the timeout was 7 hours. I tried to run share again, it created shares but always came back with the same error. So now my shares look like this:

![](http://f.cl.ly/items/1E2R3p241y3M081S1L1r/Screen%20Shot%202014-11-19%20at%202.53.37%20PM.png)

I noticed this when starting my box:

```
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.1.12
    default: VirtualBox Version: 4.3
```

Also here's the error I'm getting right now:

```
02:51:05 {master} ~/path/$ vagrant share
==> default: Detecting network information for machine...
    default: Local machine address: 192.168.33.10
    default: Local HTTP port: 80
    default: Local HTTPS port: disabled
==> default: Checking authentication and authorization...
==> default: Creating Vagrant Share session...
    default: Share will be at: gentle-musk-ox-9937
The sharing proxy exited with a non-zero exit status! This represents
an erroneous exit and likely a bug. Please report this issue.
```

At first I thought Vagrant Share was down since www.vagrantshare.com was blank but I think this is normal so I really wonder what happened because I swear I did not change anything except my PHP code I was testing on the box lol

Any ideas of what's going on?

Thanks and have a nice day!

**Comment by lavhal** [comment]
Hi,

I have the same issue. It was working ok, but since three days I'm receiving the same error. I executed vagrant share --debug, and the log is the same as with above user.

I tried to install complete fresh copy of linux, and then tried in windows, but the error is the same.

Could you please give me some hint, how can I solve this issue.

Thanks in advance.

**Comment by vinayr** [comment]
+1

**Comment by marcobax** [comment]
I'm getting the same error as well!

**Comment by lucaDgt** [comment]
same here too, same log as above, something happened this weekend i think on mux servers.

**Comment by Alex-proffesor** [comment]
I also get the same error

**Comment by Cerzus** [comment]
I'm getting the same error

**Comment by brablc** [comment]
I have reported the problem to https://twitter.com/hashicorpstatus and they fixed it. At least it works for me now.

**Comment by lavhal** [comment]
thanks for info @brablc , I tried and it works.

**Comment by Alex-proffesor** [comment]
thanks @brablc ,working.

**Comment by marcobax** [comment]
Awesome, thanks for fixing!

**Comment by Deborah-Digges** [comment]
I'm facing this issue still. Is it intermittent?

**Comment by dsbgithub** [comment]
what is the fix?? the page is not displaying any solution

**Comment by dsbgithub** [comment]
I can't RDP to windows 2012 machine. I really need to bring vagrant to my team environment but I am soo stuck

**Comment by briancain** [comment]
Hey @dsbgithub - please email the vagrant up mailing list if you are stuck and need help. There are people on there who will be able to answer any questions you have...thanks!
