### ISSUE TITLE
`vagrant box add` should warn *before* downloading that the box already exists

### ISSUE THREAD

**Issue by doxxx** [hashicorp/vagrant#4852]
When running `vagrant box add --name <NAME> <URL>` with a name of a box that already exists, Vagrant does all the work of downloading the box file first before checking if a box by that name already exists. It should check before downloading so as to avoid having to download the box file twice.

**Comment by doxxx** [comment]
I'm still seeing this behavior but I think I know what the problem is: If the `--provider` option is not on the command-line, that check is skipped. So, for example, the following command downloads the box before checking that the box doesn't already exist:

    vagrant box add --name existing-name http://host/path/to/vm.box

I'm guessing this is because it has to inspect the box file to know which provider to use.

**Comment by pesetskyps** [comment]
Yes, as doxxx says without the provider specified it doesn't check the existance of the box before download. Why this shouldn't be a bug. Seems like it is?
