### ISSUE TITLE
Vagrant 1.7.0 - Bundler error

### ISSUE THREAD

**Issue by maspwr** [hashicorp/vagrant#4918]
I just upgraded to Vagrant `1.7.0` and got the following error.

```
% vagrant status
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
/opt/vagrant/embedded/gems/gems/bundler-1.7.8/lib/bundler/resolver.rb:357:in `resolve': Could not find gem 'vagrant-login (>= 0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.8/lib/bundler/resolver.rb:164:in `start'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.8/lib/bundler/resolver.rb:129:in `resolve'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.8/lib/bundler/definition.rb:193:in `resolve'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.8/lib/bundler/definition.rb:132:in `specs'
    from /opt/vagrant/embedded/gems/gems/bundler-1.7.8/lib/bundler/definition.rb:177:in `specs_for'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant.rb:76:in `<top (required)>'
    from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:118:in `require'
    from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:118:in `rescue in require'
    from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:124:in `require'
    from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.0/bin/vagrant:105:in `<main>'
```

The contents of `plugins.json`:

```
% cat ~/.vagrant.d/plugins.json
{"installed":{"vagrant-vmware-fusion":{"ruby_version":"2.0.0","vagrant_version":"1.6.5","gem_version":"","require":"","sources":[]}},"version":"1"}%
```

**Comment by wballard** [comment]
I'm getting this error right now with Vagrant 1.7.2. Stuck dead.

**Comment by welly** [comment]
I'm getting similar ruby gem errors with Vagrant 1.7.2. It seems to be working but every time I run a vagrant command, screen full of errors:

```
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find net-ssh-2.9.2 in any of the sources (Bundler::GemNotFound)
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/spec_set.rb:85:in `map!'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/spec_set.rb:85:in `materialize'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:132:in `specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:177:in `specs_for'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:166:in `requested_specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/environment.rb:18:in `requested_specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:13:in `setup'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler.rb:122:in `setup'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/setup.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

I'm not sure if it's anything to do with rvm? It appears to be trying to using the system ruby libraries instead.

**Comment by reinh** [comment]
Also still getting this with 1.7.2

```
❯ vagrant plugin install vagrant-login
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:368:in `resolve': Could not find gem 'vagrant-login (>= 0) ruby' in the gems available on this machine. (Bundler::GemNotFound)
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:166:in `start'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/resolver.rb:129:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:193:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:132:in `specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/definition.rb:177:in `specs_for'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant.rb:76:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:105:in `<main>'
```

If I knew how, I would just nuke the whole installation from space and start over.

**Comment by marblegravy** [comment]
@reinh - Try installing vagrant from the newest installers, then `rm -rf ~/.vagrant.d`
That worked for me.

**Comment by murdoc-mos** [comment]
Thanks @marblegravy, over a year later this answer is still relevant on 1.8.7

**Comment by GautamProtegrity** [comment]
$ vagrant up
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/resolver.rb:347:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'vagrant-vbguest (>= 0) x86-mingw32' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/resolver.rb:325:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/resolver.rb:325:in `verify_gemfile_dependencies_are_found!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/resolver.rb:198:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/resolver.rb:182:in `resolve'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:200:in `resolve'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:140:in `specs'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:185:in `specs_for'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant.rb:76:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:105:in `<main>'

Can anyone please help. I had already did this set up in windows 7 host that ran perfectly without any issues with virtual box 5.0. Used the same installer same,  vbox version, same everything but it still soesn't work  unable to figure out exactly whats wrong. Any command I type like 'vagrant up' / 'vagrant plugin install' or any such command starting with vagrant it gives this error. I have had no sleep, so please help

**Comment by Alphius1987** [comment]
I'm also stuck on this:
$ vagrant plugin install vagrant-proxyconf
Bundler, the underlying system used to manage Vagrant plugins,
is reporting that a plugin or its dependency can't be found.
This is usually caused by manual tampering with the 'plugins.json'
file in the Vagrant home directory. To fix this error, please
remove that file and reinstall all your plugins using `vagrant
plugin install`.
C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:347:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'vagrant-proxyconf (>= 0) x86-mingw32' in any of the gem sources listed in your Gemfile or available on this machine. (Bundler::GemNotFound)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:325:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:325:in `verify_gemfile_dependencies_are_found!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:198:in `start'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/resolver.rb:182:in `resolve'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant.rb:76:in `<top (required)>'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:105:in `<main>'

Any help is highly appreciated, thanks in advance

**Comment by SKempin** [comment]
`rm -rf ~/.vagrant.d` fixed this for me, on Windows 7.

**Comment by e-oloughlin** [comment]
On OSX 10.11.6 running vagrant 1.87, `rm -rf ~/.vagrant.d` worked for me... or in reality `mv ~/.vagrant.d ~/.vagrant.d.backup` ;)

**Comment by webfacer** [comment]
still not working for me on windows, i also deleted it and run new installtion with fresh vagrant install exe but still getting this errors
