### ISSUE TITLE
Linux VMware Workstation and Windows guest shared folder symlink bug

### ISSUE THREAD

**Issue by nanliu** [hashicorp/vagrant#4956]
This issue occurs with VMware Workstation 10.0.4 and 11.0.0 on Linux (Tested on Ubuntu 14.04 and RHEL 6.5), and Windows guest.

The shared folder is mounted correctly in `\\vmware-host\Shared Folders\`, but the symlink folder (created via mklink) in c:\vagrant -> `\\vmware-host\Shared Folders\-vagrant` does not see anything more than one folder deep. For example if there's a file in lib/test.rb, it is visible in  `\\vmware-host\Shared Folder\vagrant\lib\test.rb`, but C:/vagrant/lib would be an empty directory.

This is not a problem with VMware Workstation on Windows, or VMware Fusion on MacOS. I'm not sure this is a vagrant bug, but it severely affects vagrant functionality (such as puppet provisioning). This matches a community bug on VMware forum: https://communities.vmware.com/message/2434315

**Comment by nanliu** [comment]
@databus23, we finally got some feedback and this appears to be related to Linux filesystem case sensitivity and require an additional VMX configuration in Linux VMware workstation (Where X is the number of shared folders):

```
sharedFolderX.hostDefaultCase = "FALSE"
```

I haven't had a chance to verify since I destroyed my testing VM, and currently working on a different project. If you or anyone else tracking this issue can verify, please post a comment. If this option works, it should be a small patch to the workstation provider.

**Comment by nanliu** [comment]
Last note, VMware has addressed this issue, they will include the fix in the next release, but have no ETA on the dates.

**Comment by Moonlighter** [comment]
Hi,

Yesterday i try to install angularjs-cli on SharFolder between a host (Windows10) and à VM on VMware 12(Workstation, with Ubuntu 14.04 LTS)

[In my Ubuntu.vmx]

sharedFolder0.present = "TRUE"
sharedFolder0.enabled = "TRUE"
sharedFolder0.readAccess = "TRUE"
sharedFolder0.writeAccess = "TRUE"
sharedFolder0.hostPath = "C:\wamp\www"
sharedFolder0.guestName = "www"
sharedFolder0.expiration = "session"
sharedFolder0.followSymlinks = "TRUE"

I access to my ShareFolder on my VM here /mnt/hgfs/www/

So after i try to install i receive this issues:

EACCES: permission denied, symlink '../semver/bin/semver' -> '/mnt/hgfs/www/ang20/my-demo/node_modules/agent-base/node_modules/.bin/semver'
Error: EACCES: permission denied, symlink '../semver/bin/semver' -> '/mnt/hgfs/www/ang20/my-demo/node_modules/agent-base/node_modules/.bin/semver'
    at Error (native)

Somebody have an idea? Thank's!
