### ISSUE TITLE
1.7.1 OSX 10.10 ArgumentError

### ISSUE THREAD

**Issue by Spechal** [hashicorp/vagrant#4962]
OSX Yosemite
VirtualBox 4.3.20
Guest OS Ubuntu 14.10.1
Guest Additions installed 

```
$ vagrant package --base ubuntu-vagrant
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:153:in `action': wrong number of arguments (2 for 1) (ArgumentError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:83:in `package_vm'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:66:in `package_base'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/cli.rb:42:in `execute'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:301:in `cli'
    from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.1/bin/vagrant:174:in `<main>'
```

**Comment by symgryph** [comment]
I tried the fix still get the following:

 vagrant package --base CentosBase6.6 --output centostest.box

/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:83:in
`core#hash_merge_kwd': wrong argument type String (expected Symbol)
(TypeError)

from
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:83:in
`package_vm'

from
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:66:in
`package_base'

from
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:42:in
`execute'

from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/cli.rb:42:in
`execute'

from
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:301:in
`cli'

from
/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.1/bin/vagrant:174:in
`<main>'


Reverting back to 'working' dangerous fix.....sadness'

On Wed, Dec 31, 2014 at 5:53 PM, Seth Vargo <notifications@github.com>
wrote:

> Hi, please do not *remove* the ** as it could damage your Vagrant
> installation and make the upgrade process difficult in the future. Here is
> the actual fix: f9eff24
> <https://github.com/mitchellh/vagrant/commit/f9eff24fa9de28309ed9b96560803e055a5bdd03>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellh/vagrant/issues/4962#issuecomment-68473647>.
>



-- 
-----------------------
Two Wheels Good, Four Wheels Bad

**Comment by symgryph** [comment]
I just went back to 1.6.5, since it works. I did check out the github
version, and got the same error.

On Thu, Jan 1, 2015 at 4:15 PM, Thomas Munn <symgryph@gmail.com> wrote:

> I tried the fix still get the following:
>
>  vagrant package --base CentosBase6.6 --output centostest.box
>
> /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:83:in
> `core#hash_merge_kwd': wrong argument type String (expected Symbol)
> (TypeError)
>
> from
> /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:83:in
> `package_vm'
>
> from
> /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:66:in
> `package_base'
>
> from
> /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:42:in
> `execute'
>
> from
> /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/cli.rb:42:in
> `execute'
>
> from
> /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:301:in
> `cli'
>
> from
> /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.1/bin/vagrant:174:in
> `<main>'
>
>
> Reverting back to 'working' dangerous fix.....sadness'
>
> On Wed, Dec 31, 2014 at 5:53 PM, Seth Vargo <notifications@github.com>
> wrote:
>
>> Hi, please do not *remove* the ** as it could damage your Vagrant
>> installation and make the upgrade process difficult in the future. Here is
>> the actual fix: f9eff24
>> <https://github.com/mitchellh/vagrant/commit/f9eff24fa9de28309ed9b96560803e055a5bdd03>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mitchellh/vagrant/issues/4962#issuecomment-68473647>.
>>
>
>
>
> --
> -----------------------
> Two Wheels Good, Four Wheels Bad
>



-- 
-----------------------
Two Wheels Good, Four Wheels Bad

**Comment by AntonioMeireles** [comment]
fwiw exact same issue as @symgryph  here (10.10.1 &&  vagrant 1.7.1 &&  f9eff24 applied) 
```
cd box; \
	vagrant package --base "CoreOS Box" --output ../coreos.box --include change_host_name.rb,configure_networks.rb --vagrantfile vagrantfile.tpl
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:83:in `core#hash_merge_kwd': wrong argument type String (expected Symbol) (TypeError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:83:in `package_vm'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:66:in `package_base'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/plugins/commands/package/command.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.1/bin/vagrant:174:in `<main>'
make: *** [coreos.box] Error 1
```

**Comment by alu** [comment]
I think need symbol in hash.

```ruby
      def package_vm(vm, options)
        opts = options.inject({}) do |acc, data|
          k,v = data
          acc["package.#{k}".to_sym] = v
          acc
        end

        vm.action(:package, **opts)
      end
```

**Comment by AntonioMeireles** [comment]
fwiw i can confirm that, here,  @alu 's fix above (appending **.to_sym** to **"package.#{k}"**) actually seems to _really_ fix f9eff24 / #4972

**Comment by AntonioMeireles** [comment]
humm. issue seems to be https://bugs.ruby-lang.org/issues/10118 if i'm understanding things correctly

**Comment by sramazzina** [comment]
Worked for me thanks!!

**Comment by AntonioMeireles** [comment]
@sramazzina fwiw it doesn't seem to work that well here. it **stops** failing but custom args to _vagrant package_ are silently ignored...

**Comment by sramazzina** [comment]
I was trying to simply package my ubuntu vm and it worked.... but I was so excited that I made the changes before coming to post's end :-( .... That's my mistake! I reverted the change to the original version. Someone can tell me if the packaged box can be considered as good or do I have to throw it away?

**Comment by alu** [comment]
@AntonioMeireles Sorry, my comment was not perfectly.

**Comment by tian-xiaobo** [comment]
/opt/vagrant/embedded/gems/gems/vagrant-1.7.1/lib/vagrant/machine.rb:153

-     def action(name, **opts)
+     def action(name, opts)

**Comment by AntonioMeireles** [comment]
fwiw 1.7.2, released in last few hours, seems to have fixed this once and for all out of the box :smile:

**Comment by rsvalerio** [comment]
Same problem here. 

Environment: vagrant 1.7.2, ruby 2.0.0p481,  OSX Yosemite - 10.10.3

Changed file: vi vagrant-1.7.2/lib/vagrant/machine.rb:153

before: def action(name, opts=nil) 

after: def action(name, opts)

Done.
