### ISSUE TITLE
[Doc] .vagrantplugins documentation missing

### ISSUE THREAD

**Issue by gimler** [hashicorp/vagrant#5035]
Where can i find the documentation for the `.vagrantplugins` file?

**Comment by fh** [comment]
@mitchellh Sorry to chime in on an old closed issue: But do you have any pointer to the doc in regards to what should be used instead? I failed to come up with something similar.

Our use case is here that we do have some project specific commands (stuff like `vagrant logs tail` to `tail` the random logfiles a specific application has and other app-specific tedious tasks we would like to make available to developers outside the vagrantbox).
