### ISSUE TITLE
Vagrant Machine "Already Exists"

### ISSUE THREAD

**Issue by amilajack** [hashicorp/vagrant#5038]
I've looked into this issue for a long time and I can't seem to find the solution. After deleting all VM's with the vagrant destroy command, vagrant still says that "homestead" is still running.

First I ran this:

```
Amilas-MacBook-Pro:scripts amila$ vagrant global-status
id       name   provider state  directory
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.
```

and then this

```
Amilas-MacBook-Pro:scripts amila$ sudo ~/.composer/vendor/bin/homestead up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'laravel/homestead'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'laravel/homestead' is up to date...
A VirtualBox machine with the name 'homestead' already exists.
Please use another name or delete the machine with the existing
name, and try again.
```

**Comment by CaddyDz** [comment]
@amilajack Can you please mention what version of vagrant you had and to which one you downgraded?  
I'm having the same issue but Homestead requires version **1.9** of Vagrant anyways

**Comment by amilajack** [comment]
It's been years since I've used homestead :( I used docker now. Try reinstalling vagrant and removing all related caches/built files. Also if i recall correctly, you may have to remove some kind of temporary hidden vm data. Forgot what exactly bc it's been years. Hope this helps

**Comment by bhanu-prakashl** [comment]
i have the issure like this below and vagrant up doesn't work
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.

is there any version compatibility issues

**Comment by willgittoes-dd** [comment]
Similar issue. No vagrant files (eg.  `ls -lah ./ | grep agra` returns nothing for current dir and every parent as far as /). When I try to run `vagrant init` I get told there's already a vagrantfile. It CREATES a vagrantfile in my home dir, then complains there's already a vagrantfile.

**Comment by kikitux** [comment]
@willgittoes-dd you are commenting on a close issue.

If you can reproduce this, and share instructions, please open a new issue and fill the template.
