### ISSUE TITLE
Cannot configure network interfaces in Arch Linux

### ISSUE THREAD

**Issue by ogarcia** [hashicorp/vagrant#5054]
When you configure an Arch Linux Vagrant for use a bridged/public network it gives the following error:

```
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mv /tmp/vagrant_network
                                     /etc/netctl/

Stdout from the command:



Stderr from the command:

mv: missing destination file operand after ‘/tmp/vagrant_network’
Try 'mv --help' for more information.
bash: line 3: /etc/netctl/: Is a directory
```

Steps to reproduce:
1. vagrant init ogarcia/archlinux-201412-x64
2. Uncomment the network line: config.vm.network "public_network"
3. vagrant up

I think that the bug is that the `mv /tmp/vagrant_network` and `/etc/netctl/` are in different lines, then the script executes `mv /tmp/vagrant_network` giving the `mv: missing destination file.. blah blah` error and later `/etc/netctl/` giving `bash: line 3: /etc/netctl/: Is a directory`.

**Comment by ogarcia** [comment]
Ok. Thanks all to "Seek and destroy" this issue!

**Comment by cupen** [comment]
I solved this problem according to what @x-yuri said. 
My operate system was Windows7, I just replaced `D:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.7.1\plugins\guests\arch\ca\configure_networks.rb` with https://github.com/mitchellh/vagrant/commit/9d1834a3c98fcc5f413878bb1f3acd055b6fe90e , It works fine.

Thank you very much!
