### ISSUE TITLE
could not find recipe server for cookbook mysql

### ISSUE THREAD

**Issue by kartikdanidhariya** [hashicorp/vagrant#5061]
i am using ubuntu 12.04 
vagrant version is 1.7.1
i want to use vagrant for Ruby on rail
i follow this blog 
https://gorails.com/guides/using-vagrant-for-rails-development
when i run vagrant up so it give following error

 ==> default: Installing Chef cookbooks with Librarian-Chef...
==> default: The cookbook path '/home/keyur/ruby/site-cookbooks' doesn't exist. Ignoring...
==> default: Running provisioner: chef_solo...
==> default: Detected Chef (latest) is already installed
Generating chef JSON and uploading...
==> default: Running chef-solo...
==> default: stdin: is not a tty
==> default: [2014-12-24T12:35:20+00:00] INFO: Forking chef instance to converge...
==> default: [2014-12-24T12:35:20+00:00] INFO: **\* Chef 12.0.3 ***
==> default: [2014-12-24T12:35:20+00:00] INFO: Chef-client pid: 2731
==> default: [2014-12-24T12:35:24+00:00] INFO: Setting the run_list to ["recipe[apt]", "recipe[nodejs]", "recipe[ruby_build]", "recipe[rbenv::user]", "recipe[rbenv::vagrant]", "recipe[vim]", "recipe[mysql::server]", "recipe[mysql::client]"] from CLI options
==> default: [2014-12-24T12:35:24+00:00] INFO: Run List is [recipe[apt], recipe[nodejs], recipe[ruby_build], recipe[rbenv::user], recipe[rbenv::vagrant], recipe[vim], recipe[mysql::server], recipe[mysql::client]]
==> default: [2014-12-24T12:35:24+00:00] INFO: Run List expands to [apt, nodejs, ruby_build, rbenv::user, rbenv::vagrant, vim, mysql::server, mysql::client]
==> default: [2014-12-24T12:35:24+00:00] INFO: Starting Chef Run for vagrant-ubuntu-trusty-64
==> default: [2014-12-24T12:35:24+00:00] INFO: Running start handlers
==> default: [2014-12-24T12:35:24+00:00] INFO: Start handlers complete.
==> default: 
==> default: 
==> default: ================================================================================
==> default: Recipe Compile Error
==> default: ================================================================================
==> default: 
==> default: Chef::Exceptions::RecipeNotFound
==> default: --------------------------------
==> default: could not find recipe server for cookbook mysql
==> default: 
==> default: [2014-12-24T12:35:25+00:00] ERROR: Running exception handlers
==> default: [2014-12-24T12:35:25+00:00] ERROR: Exception handlers complete
==> default: [2014-12-24T12:35:25+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2014-12-24T12:35:25+00:00] ERROR: could not find recipe server for cookbook mysql
==> default: [2014-12-24T12:35:25+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

so how can i solve this error, i am totally new for vagrant and ROR
pls help!!,Thanks in advance!!!!

**Comment by michael-franz** [comment]
> chef.add_recipe "mysql::server"
> chef.add_recipe "mysql::client"

The mysql-Cookbook doesn't contain recipes any more (since version 6.0). See the Usage-section for further information: https://supermarket.chef.io/cookbooks/mysql
