### ISSUE TITLE
Add timestamp to debug log

### ISSUE THREAD

**Issue by uchagani** [hashicorp/vagrant#5203]
I've requested a similar feature before but now I'm asking for timestamps to be added to at least the debug logs.

I've trying to isolate a problem with bringing up machines and have isolated a port forwarding issue.  However I can't isolate to a single place in the log file because it everything is going by so fast.  I'd like to be able to compare timestamps from when I see the error and what is happening in the logs.

**Comment by sethvargo** [comment]
@uchagani how would having timestamps help solve this issue? Maybe I am misunderstanding, but the logs should be sequential.

**Comment by uchagani** [comment]
I'm using vagrant as part of a CI Build/Test/Deploy cycle.  I am noticing a strange behavior in one of the apps I am testing where, when another vagrant box is spun up, the port-forwarding of the new box, causes a network glitch in boxes that are already spun up.

I'm trying to narrow down where in the vagrant log this is happening.  I already have timestamps from my app regarding the crash and i wanted to line that up with the vagrant log to see what exactly in vagrant is causing the problem.

**Comment by phgr100x** [comment]
Add this at start of your Vagrantfile, it helps me:
```
$out_file = File.new('debug.log', 'w')
def $stdout.write string
	log_datas=string
	if log_datas.gsub(/\r?\n/, "") != ''
		log_datas=::Time.now.strftime("%d/%m/%Y %T")+" "+log_datas.gsub(/\r\n/, "\n")
	end
	super log_datas
	$out_file.write log_datas
	$out_file.flush
end
def $stderr.write string
	log_datas=string
	if log_datas.gsub(/\r?\n/, "") != ''
		log_datas=::Time.now.strftime("%d/%m/%Y %T")+" "+log_datas.gsub(/\r\n/, "\n")
	end
	super log_datas
	$out_file.write log_datas
	$out_file.flush
end
```

**Comment by mcandre** [comment]
Solid feature idea, maybe submit a PR?

**Comment by philippe-granet** [comment]
See PR https://github.com/hashicorp/vagrant/pull/9175

**Comment by gustavomcarmo** [comment]
Great @philippe-granet !!!

I've just improved your solution placing the code in a different file called timestamp-logger.rb and adding just one line of code at the start of my Vagrantfile: load 'timestamp-logger.rb'

**Comment by philippe-granet** [comment]
A PR has been merged : https://github.com/hashicorp/vagrant/pull/9269

**Comment by briancain** [comment]
I'm going to go ahead and close this now that #9269 has been merged. Thanks!
