### ISSUE TITLE
Vagrant could not detect virtualbox windows 7 32 bit

### ISSUE THREAD

**Issue by jeremymichel** [hashicorp/vagrant#549]
Hello,
I'm using a windows 7 32 bit french, I've installed vagrant, everything went fine, but when I try to add a box I get the following message.
"Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.

If VirtualBox is installed, it may be an incorrect version. Vagrant currently
requires VirtualBox 4.1.x. Please install the proper version to continue.

If you have an older or newer version of VirtualBox, please make sure you're
using the proper version of Vagrant. Ask the mailing list if you have questions."

I have virtualbox 4.1.6 installed I checked my system path, but nothing seems to work, I've tried with the virtualbox gem 0.9.1 and 0.9.2, still not working.

Is there a solution to my problem, or is vagrant unable to work on windows 7 32 bit?

**Comment by satish534** [comment]
Is anybody tried to install virtual box 2.0.2 and Vagrant 5.1.6 ?
