### ISSUE TITLE
Add resume ability to vagrant box add command

### ISSUE THREAD

**Issue by jasherai** [hashicorp/vagrant#57]
Although this is just an irritant, it would be nice to have resume support (and option for fresh download) of the remote box download. 

Pretty self-explanatory i guess :)

jasherai

**Comment by jean** [comment]
Good to see this made it in :-) However the current implementation nukes the incomplete download if it's older than 6 hours. Boxes really need to be validated using a checksum anyway, to enable verification of their integrity. So I'd like to log a feature request: store the checksum when starting download, and don't nuke incomplete downloads unless the checksum changed.

**Comment by GoranSoce** [comment]
Who needs resuming of 2Gb files. It's always a pleasure to find my box download failed at 96%, especially if the max download speed is 300Kb. Have to switch to docker. This happens to often.
