### ISSUE TITLE
`vagrant ssh NAME` on JRuby causes "Pseudo-terminal will not be allocated because stdin is not a terminal." error

### ISSUE THREAD

**Issue by mbbx6spp** [hashicorp/vagrant#594]
See this gist for all the commands needed to reproduce:
https://gist.github.com/4be48502cc7767684139

The issue only shows up on JRuby (though I have only tried MRI 1.9.2p290 as an alternative). This issue makes the SSH session useless, because I am not able to get any output when typing commands at the non-existent shell prompt.

Suspicions: my gut feeling is this is specific to SSH gem in `net-ssh` gem when it run on JRuby, but wanted to alert you to this anyway just in case this is in vagrant somewhere.

Versions I am using:
- `gem list vagrant` # => vagrant (0.8.8) (for both JRuby and MRI)
- `VBoxManage -v` # => 4.1.2r73507
- `ruby -v` # => ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-darwin11.1.0]
- `jruby -v` # => jruby 1.6.4 (ruby-1.9.2-p136) (2011-08-23 17ea768) (OpenJDK 64-Bit Server VM 1.7.0-ea) [darwin-x86_64-java]
- `java -version` # => openjdk version "1.7.0-ea"
- `uname -a` # => Darwin winston 11.2.0 Darwin Kernel Version 11.2.0: Tue Aug  9 20:54:00 PDT 2011; root:xnu-1699.24.8~1/RELEASE_X86_64 x86_64

**Comment by lolotux** [comment]
The solution is : 
```
vagrant ssh -c "the command" $vagrantbox -- -T
```
