### ISSUE TITLE
problem with vagrant on osx - kernel_task > 100%

### ISSUE THREAD

**Issue by ghost** [hashicorp/vagrant#632]
vagrant (0.8.10)
virtualbox (4.1.8)
osx (10.7.2)

Following the guide http://vagrantup.com/docs/getting-started/index.html I get the kernel_task issue while Configuring Chef and the Vagrant fro mthe provisioning section.  I read multiples posts about this issue.  Am I doing something wrong? or is this "normal"? 

Thanks.
Alex

**Comment by Jaspur** [comment]
Still exists
