### ISSUE TITLE
Is it possible to define multiple network interfaces for a box?

### ISSUE THREAD

**Issue by blt** [hashicorp/vagrant#641]
I note in the [host-only networking](http://vagrantup.com/docs/host_only_networking.html) documentation that a static IP is set for a single interface. Is is possible to define multiple interfaces, possibly with different strategies? (Say, eth0 is DHCP/NAT and eth1 static for host-only?)

**Comment by v6** [comment]
Is there any more documentation for :adapter or :interface? 

I want to do everything possible using Vagrant without needing vboxmanage or saltstack or whatever.

**Comment by boriel** [comment]
I also need this feature. To specify which adapter will vagrant use for vagrant ssh. :) Would be very useful! :+1:

**Comment by openface** [comment]
+1

For our project needs, we need to have Vagrant use eth2 always, because eth0 and eth1 are reserved for the web application user to configure.  (it's a network appliance)
