### ISSUE TITLE
Automating bridged networking

### ISSUE THREAD

**Issue by fjl82** [hashicorp/vagrant#655]
First off, thanks for implementing bridged networking. I've been using this for a while with a workaround in the box I'm using, but now that 0.9 is out, I want to move to the "official" way (because it's cleaner and also, because the old "cheat" no longer works).
However, I have one issue with this, or maybe 2, depending on how you look at it.
When using bridged networking, I get asked during "vagrant up" what device I want to use. Not only is this pointless on my machine, since it only lists one option (i only have 1 network interface), but even worse, this breaks my automated setup with hudson, since it relies on a fully automated process.
I can work around this by simply hacking the ruby source to change line 329 in lib/vagrant/action/vm/network.rb from
choice = nil
to
choice = 1
but ofcourse there is a better solution. I suggest the following enhancements:
1) Don't prompt the user when only 1 network interface is available (giving the user a choice from 1 option is no choice anyway).
2) Allow specifying the network interface in the vagrantfile.

**Comment by sej7278** [comment]
sorry to comment on such and old issue, but i'd really like an option like @ipartola says for switching between laptop and desktop. 

use wlan0 if its there and has an ip (laptop) or use eth0 if its not (desktop or laptop with cable unplugged).

rather than autodetection it would be easier/nicer/portable to just have a setting in ~/.vagrant

i can't even think of a horrible hack to put in Vagrantfile to detect the host (name/ip?) and change network settings based on that.

**Comment by sethvargo** [comment]
Hi @sej7278 

This issue is almost 3 years old and Vagrant has changed significantly since the original report. Please open a new issue and include your Vagrantfile as well as any debug output as a GitHub gist. Thanks! :smile:

**Comment by sej7278** [comment]
well i'm using the latest version of vagrant and no debug output or Vagrantfile is going to help, i guess this is a feature request or question as to whether there is an undocumented setting that solves the issue.

**Comment by rbreaves** [comment]
This is what works for me. I've added this to my own Vagrantfile and it lets the native options pass through while also giving me the ability to add whatever custom parameters I want. Ex. "vagrant -b up" or "vagrant --bridge='eth0: Wlan' up". If you do not specify the bridge adapter then it will just prompt you like normal to select one. I have more custom options, but for this example I only left bridge.

```
require 'getoptlong'

opts = GetoptLong.new(
   ##
   # Native Vagrant options
   [ '--force', '-f', GetoptLong::NO_ARGUMENT ],
   [ '--provision', '-p', GetoptLong::NO_ARGUMENT ],
   [ '--provision-with', GetoptLong::NO_ARGUMENT ],
   [ '--provider', GetoptLong::NO_ARGUMENT ],
   [ '--help', '-h', GetoptLong::NO_ARGUMENT ],
   [ '--check', GetoptLong::NO_ARGUMENT ],
   [ '--logout', GetoptLong::NO_ARGUMENT ],
   [ '--token', GetoptLong::NO_ARGUMENT ],
   [ '--disable-http', GetoptLong::NO_ARGUMENT ],
   [ '--http', GetoptLong::NO_ARGUMENT ],
   [ '--https', GetoptLong::NO_ARGUMENT ],
   [ '--ssh-no-password', GetoptLong::NO_ARGUMENT ],
   [ '--ssh', GetoptLong::NO_ARGUMENT ],
   [ '--ssh-port', GetoptLong::NO_ARGUMENT ],
   [ '--ssh-once', GetoptLong::NO_ARGUMENT ],
   [ '--host', GetoptLong::NO_ARGUMENT ],
   [ '--entry-point', GetoptLong::NO_ARGUMENT ],
   [ '--plugin-source', GetoptLong::NO_ARGUMENT ],
   [ '--plugin-version', GetoptLong::NO_ARGUMENT ],

   # custom options
   [ '--bridge', '-b', GetoptLong::OPTIONAL_ARGUMENT ]
)

bridge='false'

opts.each do |opt, arg|
  case opt
    when '--bridge'
      if arg == ''
        bridge='public'
      elsif arg == 'up'
        bridge='public'
      else
        bridge = arg
        #Removes equal sign from string
        bridge[0] = ''
      end
  end
end

if bridge != 'false'
    if bridge == 'public'
      config.vm.network "public_network"
    else
      config.vm.network "public_network", bridge: bridge
    end
  else
    config.vm.network "private_network", ip: "192.168.33.10"
end

```
