### ISSUE TITLE
Docker container can't RUN apt-get update but PING seems to works

### ISSUE THREAD

**Issue by cfrancois7** [hashicorp/vagrant#6857]
Dear everyone,

I installed a Ubuntu 14.04 box and I want to run several docker containers on it.

```
$ vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.1
```

I created my vagrantfile which uses one another which creates the box:

```
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.define "nginx-ontowiki" do |a|
    a.vm.provider "docker" do |d|
      d.build_dir = "./docker/dockerfile/mywiki/"
      #d.build_args = ["-t=mywiki"]
      d.name = "mywiki"
      #d.create_args = ["-t -i"]
      d.remains_running = true
      d.vagrant_machine = "dockerhost"
      d.vagrant_vagrantfile = "./host/Vagrantfile"
      #d.has_ssh = true
      d.ports = ["80:80"]
    end
  end
end
```

I run `vagrant up`:
see [see vagrant up](https://gist.github.com/cfrancois7/22eb255460dd808811a2)

I decided to copy the path in the host VM:

```
$ vagrant ssh
$ sudo cp -r /var/lib/docker/docker_build_aa2da7fb452e4641c0b5a5b4e2634d39/ /mnt
$ sudo clown -R `whoami` /mnt/docker/*
```

But when I run my container, it seems there is no internet connection because the script blocks on the STEP 2  without errors. If I cut my internet connection an error message is raised immediately also whereas in Vagrant internet works fine:

```
$ docker build /mnt/docker_build_aa2da7fb452e4641c0b5a5b4e2634d39/
Sending build context to Docker daemon 6.144 kB
Sending build context to Docker daemon 
Step 0 : FROM ubuntu:14.04
 ---> Using cache
 ---> a06818ddab5f
Step 1 : RUN echo "deb http://archive.ubuntu.com/ubuntu trusty main universe" > /etc/apt/sources.list
 ---> Using cache
 ---> a0a8fced5f2e
Step 2 : RUN apt-get update -y
 ---> Running in 18bcf130bfb2
```

If I run ping in the docker file I get:

```
RUN ping -c 1 google.com
 ---> Running in 4d7d249db6c2
PING google.com (77.95.65.109) 56(84) bytes of data.
64 bytes from 77.95.65.109: icmp_seq=1 ttl=61 time=4.28 ms

--- google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 4.289/4.289/4.289/0.000 ms
 ---> 702432e2fb9e
Removing intermediate container 4d7d249db6c2
```

```
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

I'm behind a proxy which is well define in my vagrantfile and the proxy configuration are good:

```
$ cat /etc/default/docker | grep proxy
export http_proxy=http://www-cache.ujf-grenoble.fr:3128
export no_proxy=/var/run/docker.sock,localhost,127.0.0.1
```

Have you an idea to resolve my mystery? Because I've not error message in docker container and that I can't wait for 2 hours long to just `$ run apt-get update -y` (it's too long to be normal).

**Comment by sethvargo** [comment]
Hi @cfrancois7 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant and Docker. Unfortunately I am having a very tough time understanding the issue(s) you are facing. Please keep in mind that our reviewers are not in your head :smile:.

The first issue seems to be that the Docker process is unable to find your Dockerfile. The error Vagrant is reporting is coming from Docker, not Vagrant. Do you have a Dockerfile at the proper location?

As for the second issue related to networking, unfortunately I think that is outside of what support we can offer you in Vagrant. All those commands you are executing are happening within Docker, so you might be able to get a better response from the Docker team. 

With respect to the proxy, you may need to tell _Docker_ that you are behind a proxy as well.

**Comment by cfrancois7** [comment]
Thank you for your reply.

I resolved the problem. It was the proxy conf was correct in my vagrant box, but in the docker container within the vagrant box, the proxy conf hasn't been propagated. Indeed neither `apt` or sudo were configured with my proxy settings.

Maybe my question is not a problem anymore but I would be very interested by knowing how to propagate proxy settings through the `docker provider`.

Best regards, thank you for your quick reply.

**Comment by sethvargo** [comment]
Hi @cfrancois7 

Thank you - I'm glad it's working for you. I don't know if we should propagate proxy settings to the Docker container, since you may want a different proxy and then the configuration matrix becomes confusing. Instead, I think we should document how to configure the Docker proxy and explain how you can do that easily in the Vagrantfile. Tagging as docs.
