### ISSUE TITLE
Read-only file system. What's wrong?

### ISSUE THREAD

**Issue by itsNikolay** [hashicorp/vagrant#713]
If you are not agains I continue after this discussion:
http://stackoverflow.com/questions/9150732/capistrano-deploy-in-virtual-machne

**\* [err :: 33.33.33.10] creating symbolic link `/vagrant/demoapp/current/log'
*** [err :: 33.33.33.10] : Read-only file system
and
itsnikolay@itsnikolay-VirtualBox:~/vagrant/1vagrant/projects/demoapp$ ssh vagrant@33.33.33.10 'ln -s /vagrant/demoapp/shared/log /vagrant/demoapp/current/log'
vagrant@33.33.33.10's password: 
ln: creating symbolic link`/vagrant/demoapp/current/log': Read-only file system
The same error

Anybody has thoughts about the error, probably you met it before?

**Comment by iwanwan** [comment]
Not  work, I try like this on my Vagrantfile
```
  config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
```

it return 
```
vm:
* The following settings shouldn't exist: customize
```

**Comment by curtisblackwell** [comment]
I have the same problem as @iwanwan. @trex005's solution doesn't work for me either.

Running Vagrant 1.6.5 on Mac OS X Yosemite.

**Comment by PrakashThapa** [comment]
Same Problem for me. 
```
vm:
* The following settings shouldn't exist: customize```

**Comment by marcofranssen** [comment]
Can't get this to work. Is anyone able to help me out?

I have following setup:

Windows 8.1
Vagrant 1.7.4
VirtualBox 5

I have multiple shared folders like this:

``` ruby
config.vm.synced_folder "../webapp", "/srv/webapp", type: "smb"
config.vm.synced_folder "../backend", "/srv/backend", type: "smb"
...
....
...
```

For the webapp I use nodejs, when I install node packages using npm it tries to create symlinks and fails with the following error.

``` bash
vagrant@devenvbk:/srv/webapp$ npm install --save-dev gulp
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev" "gulp"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path ../user-home/cli.js
npm ERR! code ENOTSUP
npm ERR! errno -95

npm ERR! nospc ENOTSUP, symlink '../user-home/cli.js'
npm ERR! nospc This is most likely not a problem with npm itself
npm ERR! nospc and is related to insufficient space on your system.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/webapp/npm-debug.log
```

Also tried to manually create a symlink using `ln -s` but that also fails with following output.

``` bash
ln: failed to create symbolic link `test': Operation not supported
```

So it seems the symlinks are not working for me out of the box. Any ideas on what I can try to solve this?

**Comment by jesalg** [comment]
@marcofranssen Try adding this to your Vagrantfile:

    config.vm.provider "virtualbox" do |v|
      v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    end

**Comment by wangpin34** [comment]
Following command works on VirtualBox 4.3.28
```
VBoxManage setextradata centos-mp_1 VBoxInternal2/SharedFoldersEnableSymlinksCreate/git 1
```
centos-mp_1 is my vm name, git is my share folder name. After restart the Virtalbox, it works.

**Comment by marcofranssen** [comment]
So based on this

```
config.vm.synced_folder "../webapp", "/srv/webapp", type: "smb"
``` 

What is the name of the shared folder?

**Comment by wangpin34** [comment]
@marcofranssen  I don't know your share folder but these ../webapp, /srv/webapp are not like names of share folder.  Follow is my share folder setting.
![myvm](https://cloud.githubusercontent.com/assets/12655367/9253461/78911b2e-4210-11e5-8c6f-9eaa3b2bc343.png)
 'E:/work/git' is the real dir, and the 'git' is the share folder name. I have executed the command and it works as expected. Don't forget to restart your Virtualbox finally.
```
VBoxManage setextradata centos-mp_1 VBoxInternal2/SharedFoldersEnableSymlinksCreate/git 1
```

**Comment by marcofranssen** [comment]
Somehow the shared folders created with vagrant don't show up in the Virtualbox UI. Any ideas on how I can get my hands on the shared folder names created using Vagrant?

**Comment by psychok7** [comment]
I can't get it to work using:

```
  config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
  end
``` 

on
```
Ubuntu 14.04
Vagrant 1.7.4
VirtualBox 4.3.16
```

I try doing creating the symlink with `python 2.7.6` and `os.link()` but i get a `OSError: [Errno 1] Operation not permitted`.

Any ideas?

**Comment by jskrepnek** [comment]
Note that symbolic links appear to have been broken in VirtualBox 5 on Windows.  See [this vagrant issue](https://github.com/mitchellh/vagrant/issues/6024).

In addition to some combination of the solutions mentioned above, downgrading to VirtualBox 4.3.3 was also required for me to get symbolic links working in shared folders.

**Comment by Perni1984** [comment]
I can confirm being able to create and browse symlinks inside the /vagrant shared folder using @trex005 method above on the following configuration:

Host OS: Windows 10
VirtualBox: 5.0.10 r104061
Vagrant: 1.7.4 (self-patched #6493 to re-enable UNC filepath on windows -> this may not be necessary!)

Guest OS: Ubuntu/trusty64

What is not working is creating symlinks inside synced_folders that are synced via smb!

@marcofranssen: you can get the names of the shares via 'net share' on the windows command prompt (as you mentioned correctly they are not shown within virtualbox manager).

Nevertheless using the sharename of an smb share together with  
```
v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/<SMBShareName>", "1"]
``` 
does not work as those shares are mounted as cifs shares instead of vboxsf shares (like /vagrant is) inside the guest OS.

Summarizing:
Symlinks for synced_folders that are using vboxsf in the guest OS are working on my system
Symlinks for synced_folders that are using cifs in the guest OS are not working on my system

**Comment by Perni1984** [comment]
ok, finally got this working on a windows 10 host, without having to enable symlinks outside the vagrant box.

use type "smb" for the synced folder, force smb3 and mfsymlinks as mount options and everything works fast and like a breeze on windows 10:

```
config.vm.synced_folder "../.", "/var/www", type: "smb", mount_options: ["vers=3.02","mfsymlinks"]
```

Important: the linux guest must have a kernel version >= 3.18, otherwise mfsymlinks does not work.

**Comment by pYr0x** [comment]
@Perni1984 i tried your solution. unfortunately it is not working for me.
```
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:
```
and
```
The error output from the last command was:

stdin: is not a tty
mount error(13): Permission denied
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```

i have no passwort for my windows user. so i skip the prompt when i was asking:
```
default: You will be asked for the username and password to use for the SMB
default: folders shortly. Please use the proper username/password of your
default: Windows account.
default:
default: Username: MYUSERNAME
default: Password (will be hidden):
```

**Comment by Perni1984** [comment]
@pYr0x: reading mount permission denied means for me that mount.cifs cannot connect to the host System.

I suppose you have Windows 10, and I read here on Github that Microsoft made Windows 10 more "secure" by disabling insecure guest Access per default. On the following links you can find an Explanation: 
https://techjourney.net/cannot-connect-to-cifs-smb-samba-network-shares-shared-folders-in-windows-10/

I guess there are two ways to solve this Problem: 
1. put a Password to your Default user (I would prefer this one)
2. allow insecure guest Access as described in the link above.

**Comment by jaywhy13** [comment]
:( I still can't get it to work for me. I'm trying to share a folder from the VM to my host OS. I'm running Mac OS X It shows up as invalid in Mac OS 10.11.1 with a Ubuntu 14.04 VM. 
I have the following in my configuration:
```
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    vb.memory = "768"
  end
```

I've tried both vagrant and v-root. Nothing works. Help!

**Comment by maoizm** [comment]
@Perni1984 Seems that your solution works only if I run vagrant as Administrator, otherwise I get error message from Vagrant.

Host: Windows 10 x64, Vagrant 1.8.1, Virtualbox 5.0.10
Guest: ubuntu/trusty32

**Comment by Perni1984** [comment]
@maoizm: you are right, to use smb for the synced Folders, vagrant has to be run as Administrator.
see: https://www.vagrantup.com/docs/synced-folders/smb.html

**Comment by menasheh** [comment]
I can't believe this issue still persists!

**Comment by juniway** [comment]
not work

**Comment by juniway** [comment]
Virtualbox 5.1.22-win.exe
VBoxGuestAdditions_5.1.22.iso

Host: Windows 7
Guest: Arch Linux

On Windows Host, run VirtualBox as Administrator, and then login to the vm Guest OS, and create a symblic link in shared folder in /media/sf_tmp, pops out errors "Failed to create  symbolic link 'xxx': Read-only file system"

**Comment by joshco** [comment]
I found a workaround by using bind mounts in Linux.  I'm running into this issue with a node project where npm wants to use symlinks when it installs modules. (and the no-bin-links setting doesnt catch everything)

So I create a node_modules directory in the vagrant user home dir (an actual VM filesystem).  Then I mount it on top of the node_modules on the vagrant shared fs.

```
mount --bind /home/vagrant/spoke_node_modules /vagrant/Spoke/node_modules
```
I put this in a provision always shell script in my vagrant file

This has a similar effect as if I had symlinked it to the local filesystem.  The main drawback is that

**Comment by jcrben** [comment]
I got this message running macOS host with a Linux guest when I was trying to symlink to another file in the in the shared folder from the guest. Thinking it over, it makes sense that would never really work.

I used a relative path symlink inside the host instead to address it.

**Comment by msutar** [comment]
Worked for me:
https://www.virtualbox.org/ticket/10085#comment:14
with restarting the virtualbox manager

My config :
VirtualBox : 5.1.20
Windows : 7 x64

**Comment by sarbull** [comment]
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 4200, host: 4200
  config.vm.synced_folder "./projects", "/home/vagrant/projects", type: "virtualbox"
  
  config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
  
  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://10.0.0.1:8080/"
    config.proxy.https    = "http://10.0.0.1:8080"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end
end
```
