### ISSUE TITLE
/etc/init.d/nfs-kernel-server: command not found

### ISSUE THREAD

**Issue by richard-scott** [hashicorp/vagrant#7173]
### Vagrant version

$ vagrant -v
Vagrant 1.8.1
### Host operating system

$ cat /etc/redhat-release
Scientific Linux release 7.2 (Nitrogen)
### Guest operating system

Any Linux variant... doesn't matter as its a problem with the host.
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.provider :virtualbox do |vb|
    vb.name = "Debian-01"
    vb.memory = "768"
    vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "0", "--type", "dvddrive", "--medium", "/usr/share/virtualbox/VBoxGuestAdditions.iso"]
    vb.customize ["modifyvm", :id, "--cpus", 1]
  end
  config.vm.hostname="debian-01"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/ansible/playbook.yml"
  end
end
```
### Debug output

Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. Do NOT paste the debug
output in the issue, just paste the link to the Gist.
### Expected behavior

Vagrant adds a share to /etc/exportfs (as expected) and should then start/restart the NFS daemon.
(This works just fine on Debian 8.x system, but not on the RHEL based one as the NFS server service has a different name.)
### Actual behavior

```
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
sudo: /etc/init.d/nfs-kernel-server: command not found
```
### Steps to reproduce
1. Install Scientific Linux
2. Add: vagrant, virtualbox-5, nfs-utils
3. Attempt to start a Vagrant managed VM that uses NFS for /vagrant syncing
### Possible fix:

From looking in here: hosts/redhat/cap/nfs.rb I think this code needs:

```
            release_file.open("r:ISO-8859-1:UTF-8") do |f|
              match = /(Red Hat|CentOS|Fedora).* release ([0-9]+)/.match(f.gets)
              if match
                distribution = match[1]
                version_number = match[2].to_i
                if (distribution =~ /Fedora/ && version_number >= 16) ||
                   (distribution =~ /Red Hat|CentOS/ && version_number >= 7)
                  # "service nfs-server" will redirect properly to systemctl
                  # when "service nfs-server restart" is called.
                  nfs_server_binary = "/usr/sbin/service nfs-server"
                end
              end
            end

```

needs updating to this:

```
            release_file.open("r:ISO-8859-1:UTF-8") do |f|
              match = /(Red Hat|CentOS|Scientific|Fedora).* release ([0-9]+)/.match(f.gets)
              if match
                distribution = match[1]
                version_number = match[2].to_i
                if (distribution =~ /Fedora/ && version_number >= 16) ||
                   (distribution =~ /Red Hat|CentOS|Scientific/ && version_number >= 7)
                  # "service nfs-server" will redirect properly to systemctl
                  # when "service nfs-server restart" is called.
                  nfs_server_binary = "/usr/sbin/service nfs-server"
                end
              end
            end
```

oh and this file also needs updating too: hosts/redhat/host.rb

```
          release_file.open("r:ISO-8859-1:UTF-8") do |f|
            contents = f.gets
            return true if contents =~ /^CentOS/ #  CentOS
            return true if contents =~ /^Fedora/ # Fedora
```

```
          release_file.open("r:ISO-8859-1:UTF-8") do |f|
            contents = f.gets
            return true if contents =~ /^CentOS/ # CentOS
            return true if contents =~ /^Scientific/ #  Scientific Linux
            return true if contents =~ /^Fedora/ # Fedora
```

This addition of "Scientific" into these files has fixed my issue.

**Comment by sethvargo** [comment]
Hi @richard-scott 

I'm going to tag this as an enhancement to core, because I don't think Vagrant currently claims to support Scientific Linux as a guest, but we can definitely add that. Thanks!

**Comment by richard-scott** [comment]
@sethvargo Scientific Linux is the Host OS Running Virtual Box & Vagrant etc. not the Guest OS in the VM :smile:

**Comment by richard-scott** [comment]
Maybe supporting individual operating systems is not the way forward, but supporting the different ways that NFS is started could be easier to manage? There must be far less of those to cater for.

For me, i have just upgraded to Vagrant v1.8.3 and had to re-visit this, but came up with this work around:

```
[root@recon ~]# cat << 'EOF' > /etc/init.d/nfs-kernel-server
#!/bin/bash
systemctl ${1} nfs-server
EOF
[root@recon ~]# chmod +x /etc/init.d/nfs-kernel-server
```

I have created a nfs-kernel-server init.d wrapper script to redirect the commands to the correct service.

**Comment by a-bashtannik** [comment]
Host machine: Ubuntu 16.04, Vagrant 1.9.3, VirtualBox 5.1
Error message: 
```
sudo: /usr/sbin/systemctl: command not found
```
quickfix: `ln -s /bin/systemctl /usr/sbin/systemctl` on host machine.

**Comment by chrisroberts** [comment]
NFS capability has been updated to detect service name as well as style in recent releases so this should now be resolved. Cheers!
