### ISSUE TITLE
vagrant destroy docker error because it cannot delete image

### ISSUE THREAD

**Issue by iondulgheru** [hashicorp/vagrant#7245]
### Vagrant version

[root@centos-play ~]# vagrant -v
Vagrant 1.8.1
### Host operating system

[root@centos-play ~]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
### Debug output

[root@centos-play icinga_monitoring]# vagrant destroy piper
    piper: Are you sure you want to destroy the 'piper' VM? [y/N] y
==> piper: Stopping container...
==> piper: Deleting the container...
==> piper: Removing built image...
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "rmi", "55a589d98865", {:notify=>[:stdout, :stderr]}]

Stderr: Failed to remove image (55a589d98865): Error response from daemon: conflict: unable to delete 55a589d98865 (cannot be forced) - image is being used by running container 9e12171e549d

Stdout:
### Expected behavior

Delete the machine without error.
If the image is used by another container return success if the current container was deleted, and throw an warning about not being able to also delete the image . The image will be deleted anyway when you delete the last container that uses this image.
### Actual behavior

An error is thrown about not being able to delete the image. This is misleading for less experienced users

**Comment by ascotan** [comment]
+1 if you're using more than one docker container this is pretty annoying

**Comment by chrisroberts** [comment]
One workaround in the latest release is to enable the compose option to use the `docker-compose` driver which can properly handle destroying images when used by multiple containers.

**Comment by ZhixiongCai** [comment]
There are errors in the configuration of this machine. Please fix
the following errors and try again:

docker provider:
* Docker compose is not currently supported from within proxy VM.

Seems that this workaround can not serve my purpose 😞

**Comment by nmaludy** [comment]
+1 this just bit me...
