### ISSUE TITLE
SMB credentials drops sequences around the "$" character resulting in invalid mounts.

### ISSUE THREAD

**Issue by virgofx** [hashicorp/vagrant#7246]
SMB credentials drop sequences because of "$" character sequences in password resulting in invalid mounts.
### Vagrant version

Vagrant 1.8.1
### Host operating system

Windows 10 x64
### Guest operating system

CentOS 7
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|

    config.vm.define "default", primary: "true" do |box|
        box.vm.box = "centos/7"
        box.vm.network "private_network", ip: "192.168.56.10"
        box.vm.synced_folder ".", "/vagrant", disabled: true
        box.vm.synced_folder ".", "/vagrant", type: "smb"
    end
end
```
### Expected behavior

Temporary SMB credentials inside guest should be accurate
### Actual behavior

Password drops "$@" characters.
### Steps to reproduce
1. vagrant up
2. Enter username for SMB
3. Enter password `hello$@world`  (It's ok that it's not valid)
   
   SMB mount fails with permission denied.
4. Check stored password 
   
   ```
   vagrant ssh
   cat /etc/smb_*
   ```
   ---
   
   ```
   username=****
   password=helloworld
   ```

**Comment by virgofx** [comment]
Some observations

**Working**
`hello@world`  ->  `hello@world`

**Not Working**
`hello@$world`  ->  `hello@`
`hello$@world`  ->  `helloworld`
`a$b@c$d@e$f`  ->  `a@c@e`
`a$b$c$d$e`  ->  `a`

**Comment by world** [comment]
Why u writing to me?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
