### ISSUE TITLE
cfengine provisioner fails if redhat-like base box does not contain wget

### ISSUE THREAD

**Issue by norcnorc** [hashicorp/vagrant#7265]
When installing CFengine into a Redhat-like guest operating system, the cfengine provisioner assumes that wget(1) is available. I at least [one case](https://atlas.hashicorp.com/centos/boxes/7/versions/1603.01), that is not so. When wget is not available, provisioning fails with an unhelpful error message.
### Vagrant version

Vagrant 1.8.1
### Host operating system

OSX
### Guest operating system

CentOS
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version =  "1603.01"
  config.vm.provision "cfengine" do |cfengine|
    cfengine.am_policy_hub = true
  end
end
```
### Debug output

https://gist.github.com/norcnorc/1ea514d23ed136fad89a4854cc77774e#file-cfengine-fail-log-L10161
### Expected behavior

The latest version of the "cfengine-community" package is installed into the VM.
### Actual behavior

Installation of the "cfengine-community" package fails with an error message about GPG keys.

```
==> default: Installing CFEngine onto machine...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum -y install cfengine-community

Stdout from the command:

Loaded plugins: fastestmirror


Stderr from the command:


You have enabled checking of packages via GPG keys. This is a good thing. 
However, you do not have any GPG public keys installed. You need to download
the keys for packages you wish to install and install them.
You can do that by running the command:
    rpm --import public.gpg.key


Alternatively you can specify the url to the key you would like to use
for a repository in the 'gpgkey' option in a repository section and yum 
will install it for you.

For more information contact your distribution or package provider.

Problem repository: cfengine-repository
```
### Steps to reproduce
1. Run `vagrant up`
### Workaround

Add the line

``` ruby
config.vm.provision "shell", inline: "yum install -y wget"
```

to the Vagrantfile, _before_ the `config.vm.provision "cfengine"` line.

**Comment by briancain** [comment]
Because we can't address this for every dependency for each provider and provisioner, in this case it makes sense for the box maintainers to include `wget` on the box itself. Thanks!
