### ISSUE TITLE
rsync-auto does not watch symlinked directories, even with polling

### ISSUE THREAD

**Issue by tnguyen14** [hashicorp/vagrant#7267]
In my vagrant setup, I have a synced folder using rsync as such

```
.
|-- Vagrantfile
|-- shared
    |-- linktofolder -> /Users/tnguyen/myproject
```

``` ruby
config.vm.synced_folder "shared", "/home/vagrant/shared", type: "rsync"
```

I have `vagrant rsync-auto` running. When I make changes in `myproject`, the changes are not picked up. I have also tried `vagrant rsync-auto --poll`, but the behavior is still the same.

Is this the expected behavior, or is this a bug? If the former, is there a way to watch for changes through the symlinked folder?
### Vagrant version

1.8.1
### Host operating system

OS X 
### Guest operating system

CentOS 6.7

**Comment by tnguyen14** [comment]
It seems like polling should have worked, from what I can read in guard/listen#25, and I am under the impression that vagrant uses listen?

**Comment by chrisroberts** [comment]
Closing as this is an issue with the upstream library. Cheers!
