### ISSUE TITLE
Under Cygwin, global-status should give directory paths usable in Cygwin

### ISSUE THREAD

**Issue by rct** [hashicorp/vagrant#7268]
`vagrant global-status` gives Windows style paths even though Cygwin is being used and detected.  If `VAGRANT_DETECTED_OS == cygwin` it should give path names that can be used (copy and pasted) within the Cygwin environment without having to translate paths by hand.
### Vagrant version

$ vagrant -v
Vagrant 1.8.1
### Host operating system

Windows 7/64 bit with Cygwin 
$ uname -a
CYGWIN_NT-6.1 t500 2.5.1(0.297/5/3) 2016-04-21 22:14 x86_64 Cygwin
### Guest operating system

n/a
### Vagrantfile

n/a
### Expected behavior

When `VAGRANT_DETECTED_OS == cygwin` expect to see paths that can be copied and pasted into Cygwin's bash `/cygdrive/c/Users/foo/..` without needing to translated and escaped.

When `VAGRANT_DETECTED_OS != cygwin`  expect to see Windows paths on Windows. `C:\Users\foo\...`
### Steps to reproduce
1.  Start Cygwin terminal 
2.  have at least 1 box configured
3.  run `vagrant global-status`,
4.  Look at the path names in the directory column.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
