### ISSUE TITLE
[enhancement] could you pls provide an alternative configuration to set adapter 1 as host-only, not NAT?

### ISSUE THREAD

**Issue by naijim** [hashicorp/vagrant#7279]
I have a Whonix Gateway providing Tor service. And I want to forward all traffic from another guest(Debian) machine to Whonix. I have been kept trying in several days, so much pain.

[this](https://github.com/mitchellh/vagrant/issues/5708) points out that NAT on adapter 1 is a hard requirement.
[this](http://superuser.com/questions/752954/need-to-do-bridged-adapter-only-in-vagrant-no-nat) provides an alternative way to do that. I tried to follow the guide, but never succeeded...

It looks like the NAT configuration of Virtualbox has connection to the global Internet by default. But in some scenarios a connection to Internet is not suitable.

**Comment by conorsch** [comment]
Folks have been asking for more flexible interface configuration in Vagrant for years. While I don't expect the maintainers to view the enhancement as trivially implementable, I'll say that greater control over network devices would be extremely welcome, and greatly ease rapid prototyping of multi-machine environments.

Perhaps this would be a good excuse to iterate the vagrant API version? I've been diligently wrapping all my Vagrantfiles with API blocks:

```
Vagrant.configure("2") do |config|
# ...
end
```

in anticipation of such a change.

**Comment by akarasulu** [comment]
2.0 is out and so I was wondering if there was any progress on this issue scheduled for 1.9. I need to run a bridged interface on eth0 and NAT on eth1. If not does anyone know of a reliable workaround?

Thanks much!

**Comment by belonesox** [comment]
I use my workaround that leaves NAT-adapter first but always fixes routing and makes default routing through public network:

http://wiki.4intra.net/Blog:StasFomin/Easy_Networking_with_Vagrant_and_VirtualBox

**Comment by chrisroberts** [comment]
Hi there,

The default NAT interface is core to the internal implementation of Vagrant and expected for many operations. While it may be possible to modify this interface via direct provider manipulation, it's not something currently supported from within Vagrant.

Cheers!
