### ISSUE TITLE
Vagrant rsync really slow because of calls to `machine.guest.capability`

### ISSUE THREAD

**Issue by wk8** [hashicorp/vagrant#7329]
### Vagrant version

Latest master (b384ff98a54fd632e1f2d67b7fcafd603f30e620)
### Host operating system

Mac OS X
### Guest operating system

This is the operating system you run in the virtual machine.

Ubuntu 14.04
### Expected behavior

rsync (and especially rsync-auto) should be fast, and in any case most of time it takes should be spent in the actual rsync command, not in Vagrant internals
### Actual behavior

The vast majority of the time is spent in Vagrant internals
### Steps to reproduce

My branch https://github.com/mitchellh/vagrant/compare/master...wk8:wk_temp2 is obviously extremely ghetto and won't be considered as is, but it so happens that using that patch, my `vagrant rsync-auto` is down from ~5-6 secs per iteration to ~0.3 secs (which is pretty much the time running the same rsync command manually takes)

@sethvargo : this issue is mainly to ask for guidance to turn my patch above in something you would consider merging. Right now I see two ways to address this:
1. turn the `RsyncHelper` into a class that gets instantiated with the options once and for all, which makes the caching a little less ghetto. Could break a number of plugins though, so I guess you won't want that
2. haven't had time to properly dive into that capability chain system, but it seems wrong that it takes so long and has no caching?

**Comment by snfnwgi** [comment]
Who can answer my question
https://github.com/hashicorp/vagrant/issues/9010
