### ISSUE TITLE
request to use existing SMB mount to avoid admin privileges requirement

### ISSUE THREAD

**Issue by joshco** [hashicorp/vagrant#7371]
Could you add a configuration option to have the guest mount a specified existing SMB share/mount point from the host?

The current approach (vagrant exposes the share) seems to be what requires admin privileges.  
Admin privileges means that any calling app must also be run as administrator, in my case that's RubyMine.  I can't run the app via it's vagrant unless it is also running as admin.  Of course since running something like vagrant as admin means that that VMs and settings don't show up under my user account.

Another configuration parameter such as "smb_share" alongside "smb_host" would allow this.

My setup
### Vagrant version

Vagrant 1.8.1
### Host operating system

Windows 10 x64, mingw
### Guest operating system

Linux Ubuntu Trusty64

**Comment by cyberis** [comment]
+1 Vagrant is most annoying to run on Windows when it requires admin privs during vagrant up. I am limited to cmd.exe when usually I run vagrant from git or cygwin bash when on Windows but can't because of priv elevation.

**Comment by Perni1984** [comment]
+1 for the idea.

@cyberis: slightly off-topic, but you can start git cmd with Administrator privileges (Ctrl + Shift + Click on Launch Icon) to circumvent the priv. escalation. You still have to put in your admin password when you connect over smb inside a shared folder though.

**Comment by joshco** [comment]
@Perni1984 your OT is true, but the challenge is that with the requirement for admin priv, one can no longer call vagrant from the growing set of applications that support it.  For me, that includes RubyMine.  Running that as admin just to be able to debug through a vagrant is a major pita. 

I've started just executing an SMB mount command inside the vagrant such as:::
````
mount -t cifs -o uid=1000, **credential info**,vers=3.02 //192.168.10.1/vb2 /vagrant
````
This mounts the SMB mount over the top of the original vbox file share, which seems to make things faster without breaking things. (so far)

**Comment by dhandeo** [comment]
The windows share already exists for the host machine, or can be over network. It would be convenient to define the mounting in the Vagrantfile

**Comment by krystan** [comment]
Still and issue and for us a very annoying one we cannot use vb shared drives as they do not support symlinks which breaks npm when installing back to a mapped drive, we need the node_modules on the host so people can use them to view source in editors or we could just let them reside on the Linux host. Would be good to be able to auto mount in this fashion as described in  this issue

**Comment by chrisroberts** [comment]
Hi there,

This behavior was enabled via the SMB updates in #9294 so I'm going to close this up. 

Cheers!
