### ISSUE TITLE
Salt provisioner does not work if ca-certificates and Python are missing from base box

### ISSUE THREAD

**Issue by babilen** [hashicorp/vagrant#7392]
### Vagrant version

```
$ vagrant --version
Vagrant 1.8.1
```
### Host operating system

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux stretch/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
### Vagrantfile

``` ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "debian/jessie64"
  config.vm.define :salttest do |salttest|
    salttest.vm.hostname = "salttest-debian-jessie.test"

    salttest.vm.provision :salt do |salt|
      salt.install_type = "stable"
      salt.install_master = true
     end
  end
end
```

If you test this, please use the `libvirt` provider as the `debian/jessie64` base box for virtualbox contains both `python` and `ca-certificates`.
### Expected behavior

I expected the `salt-minion` and `salt-master` packages to be installed.
### Actual behavior

They were not installed. If you copy the bootstrap script that comes with vagrant into the basebox the following happens:
### Steps to reproduce
1. Install https://github.com/vagrant-libvirt/vagrant-libvirt with `vagrant plugin install vagrant-libvirt`
2. Use aforementioned Vagrantfile and run `vagrant up --provider=libvirt`
3. Run `vagrant ssh` and `sudo -i`
4. See output of `dpkg -l salt-master salt-minion`
5. Run `apt-get update ; apt-get install python`
6. Run `/tmp/bootstrap_salt.sh -M stable` and observe:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```
1. Run `apt-get install ca-certificates`
2. Run `/tmp/bootstrap_salt.sh -M stable`
### Notes

Vagrant obviously expects base boxes to have both `python` and `ca-certificates` installed, but that is not documented on https://www.vagrantup.com/docs/boxes/base.html nor are those packages installed by the salt provisioner during provisioning.

**Comment by babilen** [comment]
Unfortunately salt still doesn't install if ca-certificates aren't installed and one has to include something like `config.vm.provision "shell", inline: "apt-get update; apt-get -qq install ca-certificates curl"`  in the `Vagrantfile`.

**Comment by reillysiemens** [comment]
I ran into this issue while making a custom FreeBSD 11.0-RELEASE-p1 box. One approach to "solving" this for FreeBSD would be to use `fetch`'s `--no-verify-peer` flag
```shell
if [ -x /usr/bin/fetch ]; then
    /usr/bin/fetch --no-verify-peer -o - https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh | sh -s -- "$@"
# the rest...
```
This will ensure the script is downloaded, but has security implications.

For whatever it's worth the relevant missing CA package in FreeBSD is `ca_root_nss`.

**Comment by briancain** [comment]
Hi all,

Sorry to leave this issue open for so long, but this is a problem with the box and the maintainers rather than something Vagrant should be handling. If a Vagrant box does not contain the `ca-certificates` package, the maintainer should update that box to include it. Thanks!
