### ISSUE TITLE
RSync picks incorrect SSH connection when multiple machines are started in parallel

### ISSUE THREAD

**Issue by p0deje** [hashicorp/vagrant#7531]
Since 45a8a5907fe58de57ed1bac45587a5609bae0454, Vagrant started to share SSH connections. It's currently done with creating `ControlPath` socket like this:

``` ruby
controlpath = File.join(Dir.tmpdir, "ssh.#{rand(1000)}")
```

However, `rand(1000)` is not very random when there are hundreds of machines being synced in parallel, that's why sometimes we can see strange behavior when one machine syncs folder to a completely different machine. This happens when the `controlpath` is already created by another machine performing sync.

We constantly see this issue on CI server and it's fixed by disabling `ControlMaster` from `RsyncHelper`. There is no easy way to reproduce the behavior, but it's pretty easy to follow the issue assuming `random(1000)` returns the same number for multiple machines.

I'm also not sure what's the best way to fix the behavior.
### Vagrant version

```
$  vagrant -v
Vagrant 1.8.4
```
### Expected behavior

Vagrant correctly syncs folder.
### Actual behavior

Vagrant syncs folder to a different machine.

**Comment by conf** [comment]
From `man 5 ssh_config` (I reformatted text a little for readability):
```
ControlPath
  Specify the path to the control socket used for connection sharing as described
  in the ControlMaster section above or the string ``none'' to disable connection
  sharing. In the path,
  - `%L' will be substituted by the first component of the local host name,
  - `%l' will be substituted by the local host name (including any domain name),
  - `%h' will be substituted by the target host name,
  - `%n' will be substituted by the original target host name specified on the command line,
  - `%p' the destination port,
  - `%r' by the remote login username,
  - `%u' by the username of the user running ssh(1),
  and `%C' by a hash of the concatenation: %l%h%p%r.

  It is recommended that any ControlPath used for opportunistic connection sharing
  include at least %h, %p, and %r (or alternatively %C) and be placed in a
  directory that is not writable by other users.
  This ensures that shared connections are uniquely identified.
```
Opportunistic connection sharing is exact mode that is enabled by `ControlMaster=auto`.
So, maybe we can just use `Controlpath='%C'` and it will be unique enough?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

ref: https://github.com/hashicorp/vagrant/commit/cb0bd89ae14f56bccab3e03249607b13a52c8009#diff-9e332e84f310f01ef491b96b33da75b8
