### ISSUE TITLE
Vagrant should show an error when user configures an empty password for a SMB synced folder

### ISSUE THREAD

**Issue by raphinesse** [hashicorp/vagrant#7560]
### Vagrant version

Vagrant 1.8.4
### Host operating system

Windows 7 Professional 64 Bit @ SP1
### Guest operating system

Ubuntu 14.04/16.04 64 Bit
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/vagrant", type: "smb", mount_options: ["vers=2.1"]
end
```
### Expected behavior

Show an error that informs the user that, by default network access is denied to accounts which don't have a password. (Information from [this unix.stackexchange answer](http://unix.stackexchange.com/a/65519/107893))
### Actual behavior

Vagrant continues and then fails with error `mount error(5): Input/output error` when trying to mount the SMB share.
### Steps to reproduce
1. Run `vagrant up` with above Vagrantfile
### References

The mount options that are given in the `Vagrantfile` are necessary to come past the error described in GH-7559.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
