### ISSUE TITLE
vmware_desktop can't change hostname on guests running systemd

### ISSUE THREAD

**Issue by dgvigil** [hashicorp/vagrant#7750]
This appears to be an issue with vmware_$desktop provider. I'm getting the same as @lsim in #2430  when using the 'vmware_workstation' provider.
### Vagrant version

Vagrant 1.8.5
vagrant-vmware-workstation (4.0.10)
### Host operating system

Windows 10 Version 1511
VMware Workstation 12 Pro
### Guest operating system

CentOS 7
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "puppetlabs/centos-7.0-64-puppet"

  config.vm.hostname = "jenkins-master-test.novalocal"

  config.vm.provider "vmware_workstation" do |v|
    v.gui = false
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "2"
  end
end
```
### Debug output

https://gist.github.com/dgvigil/5d9099acdc7db35696a285527215969b
### Expected behavior

vagrant should be able to modify the hostname 
### Actual behavior

hostname doesn't change and `vagrant up` fails.

This Vagrant file works if I use CentOS6 or if I use " --provider virtualbox"

**Comment by tercenya** [comment]
same failure on the Mac side. Tested using:

Vagrant 1.8.5
vagrant-vmware-fusion 4.0.11

MacOS 10.11.6
VMWare Fusion 8.1.1

GuestOS Centos7

**Comment by chrisroberts** [comment]
Vagrant guest support has been overhauled for many guests around hostname modification which should make this issue resolved. Running tests locally I see no issues with setting hostnames on the guests described using the latest version of Vagrant.

Cheers!
