### ISSUE TITLE
Installing plugin doesn't respect ssl_verify_mode

### ISSUE THREAD

**Issue by kenorb** [hashicorp/vagrant#7787]
I'm using corporate network which has its own root certificates and I've problem with installing Vagrant plugins.

I've setup `C:\ProgramData\gemrc` with:

```
:ssl_verify_mode: 0
```

and the setting is loaded fine:

```
C:\HashiCorp\Vagrant\embedded\bin>gem.bat env
RubyGems Environment:
  - GEM CONFIGURATION:
     - :ssl_verify_mode => 0
```

however the plugin installation still fails as shown below.

Vagrant version: 1.8.5 on Windows
### Steps to reproduce

I'm on corporate network where company is using its own certificate chain (via Blue Coat). The certificates are installed properly in the system (web-browsers and curl works fine).

Now I'm trying to install any Vagrant plugin, but it fails.

```
$ vagrant plugin install vagrant-timezone --plugin-source http://rubygems.org
Installing the 'vagrant-timezone' plugin. This can take a few minutes...
...
Could not verify the SSL certificate for https://gems.hashicorp.com/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
...
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://gems.hashicorp.com/.
```
### Expected behaviour

Either:
- The ssl_verify_mode should be respected and SSL certificate ignored.
- System certificates should be accepted (curl command works fine).
- The `--plugin-source http://rubygems.org` or similar parameter should override `build_install_opts`.
### Workaround

Replacing `https` to `http` in `C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.8.5\plugins\commands\plugin\command\mixin_install_opts.rb` manually works fine.

Related: [Installing vagrant plugin on the corporate network](http://superuser.com/q/1122599/87805)
### References
- GH-3160
- GH-7780

**Comment by chrisroberts** [comment]
Related: #7793

**Comment by beenje** [comment]
I also have an SSL error when trying to install a plugin:
```
$ vagrant plugin install vagrant-vbguest
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

Source: https://rubygems.org/
```

As #7780 is linked to this issue, I'll put my comment here.

This Dockerfile allows to easily reproduce the problem:
```
FROM centos:7

RUN yum update -y \
  && yum install -y https://releases.hashicorp.com/vagrant/1.9.4/vagrant_1.9.4_x86_64.rpm \
  && yum clean all

RUN vagrant plugin install --debug vagrant-vbguest
```

Vagrant 1.9.4 on CentOS 7.3

**Comment by beenje** [comment]
My problem might be linked to docker.
I'm testing an Ansible role using [molecule](https://molecule.readthedocs.io). That's the only reason I'm installing vagrant in a Docker container.

The same command works fine in a virtual machine.
But I don't get why this would fail in a docker container. Missing dependencies?
Do you have any idea?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
