### ISSUE TITLE
Resuming donwloads doesn't work on atlas.hashicorp.com

### ISSUE THREAD

**Issue by olivierdalang** [hashicorp/vagrant#7809]
Vagrant is an awesome tool, but currently completely unusable with a slow and/or unreliable connection, because atlas.hashicorp.com doesn't support resuming downloads. Neither downloading through vagrant CLT nor using a download manager works.

After resuming an interrupted download, the CLT says "Box download is resuming from prior download progress", but it actually seems to start over.

From here (Senegal), getting a 1gb+ file in one shot requires a great amount of luck. Please think of people that have slow and unreliable internet connection.
### Vagrant version

1.8.1
### Expected behavior

atlas.hashicorp.com should support resuming download, both when downloading from vagrant CLT or from any other download manager.
### Actual behavior

atlas.hashicorp.com does not support resuming download, both when downloading from vagrant CLT or from any other download manager.

**Comment by cwt137** [comment]
I've seen this behavior when downloading boxes here in the US, using v1.8.4.

**Comment by PierrickI3** [comment]
+1

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
