### ISSUE TITLE
Rsync change_dir error while executing vagrant up

### ISSUE THREAD

**Issue by Jerobie1** [hashicorp/vagrant#7822]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!
### Guest operating system -- debian/jessie64  on Oracle VM Virtualbox 5.1.6

This is the operating system you run in the virtual machine.
### Vagrantfile

``` ruby
# Copy-paste your Vagrantfile here
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", type: "dhcp"
  #config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.network "forwarded_port", guest: 80, host: 9032
  config.vm.provision :shell, :path => "install.sh"
  config.vm.synced_folder ".", "/vagrant", disable: true
  config.vm.synced_folder ".", "/var/www", type: "nfs"
end
```
### Debug output

link  
INFO  & DEBUG created the same info
https://gist.github.com/Jerobie1/fe36be47ca8b963fa380f42dc9b0c076
### Expected behavior

directory /home/JerryO/Downloads synced to /vagrant
### Actual behavior

failed on change_dir as per output
### Steps to reproduce
1.  Start cygwin64 terminal window
   2.cd to Downloads
   3.vagrant up
### References

Are there any other GitHub issues (open or closed) that should be linked here?
I have reviewed all "rsync" issues and did not find any that applied..

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
