### ISSUE TITLE
Vagrant (re-)uses 127.0.0.1 (localhost) on Debian/Ubuntu when config.vm.hostname ist set 

### ISSUE THREAD

**Issue by dhs-rec** [hashicorp/vagrant#7834]
When managing the hostname of a Debian or Ubuntu VM via config.vm.hostname, vagrant writes an additional line with address 127.0.0.1 into /etc/hosts, so that it looks like this afterwards:

```
127.0.0.1       myhost.virtual.box   myhost
127.0.0.1       localhost
127.0.1.1       packer-Ubuntu1604-1471511555
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

Debian and Ubuntu use an address of 127.0.1.1 for this, so that the 127.0.0.1 entry can be left untouched. So instead of adding another line with 127.0.0.1, Vagrant should instead replace the line that starts with 127.0.1.1 on Debian or Ubuntu VMs.
### Vagrant version

% vagrant -v
Vagrant 1.8.5
### Host operating system

Windows Server 2012 R2
### Guest operating system

Ubuntu 16.04
### Expected behavior

The line starting with 127.0.1.1 should have been replaced in /etc/hosts (or added if it didn't exist).
### Actual behavior

An additional line starting with 127.0.0.1 has been added to /etc/hosts.
### Steps to reproduce
1. vagrant init <a Debian or Ubuntu box>
2. Edit Vagrantfile and add a config.vm.hostname entry
3. vagrant up
4. Check /etc/hosts on the VM

**Comment by meshy** [comment]
Related to https://github.com/hashicorp/vagrant/issues/7263

**Comment by chrisroberts** [comment]
Closing this as the updates which will be provided to resolve #11508 will fix this issue. Cheers!
