### ISSUE TITLE
Vagrant does not automatically install cifs-utils if missing on a CentOS 7 box

### ISSUE THREAD

**Issue by oniric85** [hashicorp/vagrant#7850]
I'm using Vagrant 1.8.5 on Windows 10. My guest is running a CentOS 7.1 VM.

I'm trying to setup an SMB shared folder between host and guest but the machine I'm using does not come with cifs-utils package. I've read in the documentation that Vagrant should be able to auto-install it but it does not happen.

**Comment by stefanotorresi** [comment]
@chrisroberts ping

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
