### ISSUE TITLE
OSX uninstall instructions missing directory

### ISSUE THREAD

**Issue by dwsteele** [hashicorp/vagrant#7860]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!
### Vagrant version

1.8.6
### Host operating system

MacOS Sierra
### Expected behavior

Vagrant should be uninstalled.
### Actual behavior

Files were left behind.
### Steps to reproduce

Follow uninstall directions at for OSX: https://www.vagrantup.com/docs/installation/uninstallation.html

This directory is left behind: /opt/vagrant

**Comment by briancain** [comment]
Hi, it looks like this was fixed already in the docs. I'm going to go ahead and close this issue. Thanks!

**Comment by dwsteele** [comment]
Agreed, this has been fixed in the docs.  Thanks!
