### ISSUE TITLE
credential lost in some curl command with artifactory (ends up with a "401 Unauthorized")

### ISSUE THREAD

**Issue by bionoone** [hashicorp/vagrant#7864]
when doing a 

> vagrant box add https://user:password@artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo

the curl command does not get the password consistently : (executed curl commands)

> INFO subprocess: Starting process: ["/usr/bin/curl", "-I", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.8.1 (+https://www.vagrantup.com; ruby2.3.1)", "--continue-at", "-", "-u", "user:password", "-H", "Accept: application/json", "https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo"]
> INFO subprocess: Starting process: ["/usr/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.8.1 (+https://www.vagrantup.com; ruby2.3.1)", "--continue-at", "-", "-u", "user:password", "-H", "Accept: application/json", "--output", "/home/vagrant/.vagrant.d/tmp/box7e56a29315bd5f88e1dc2bc65dee6d9276daf587", "https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo"]
> INFO subprocess: Starting process: ["/usr/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.8.1 (+https://www.vagrantup.com; ruby2.3.1)", "--continue-at", "-", "--output", "/home/vagrant/.vagrant.d/tmp/box70dd17271a3e5fbd5cc2faae9be58a1d42748509", "https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo-virtualbox-1.0.0.box"]

this leads to a 

> The requested URL returned error: 401 Unauthorized
### Vagrant version

1.8.1
### Host operating system

any (Windows + linux)
### Debug output

 INFO global: Vagrant version: 1.8.1
 INFO global: Ruby version: 2.3.1
 INFO global: RubyGems version: 2.5.1
 INFO global: VAGRANT_DEFAULT_PROVIDER="libvirt"
 INFO global: VAGRANT_EXECUTABLE="/usr/share/vagrant/bin/vagrant"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/var/lib/vagrant"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_INTERNAL_BUNDLERIZED="1"
 INFO global: VAGRANT_DETECTED_OS="Linux"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_LOG="debug"
 INFO global: Plugins:
 INFO global:   - bundler = 1.10.6
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: kernel
 INFO manager: Registered plugin: VirtualBox provider
 INFO manager: Registered plugin: Hyper-V provider
 INFO manager: Registered plugin: docker-provider
 INFO manager: Registered plugin: winrm communicator
 INFO manager: Registered plugin: ssh communicator
 INFO manager: Registered plugin: ssh-config command
 INFO manager: Registered plugin: help command
 INFO manager: Registered plugin: package command
 INFO manager: Registered plugin: up command
 INFO manager: Registered plugin: global-status command
 INFO manager: Registered plugin: suspend command
 INFO manager: Registered plugin: push command
 INFO manager: Registered plugin: plugin command
 INFO manager: Registered plugin: vagrant-login
 INFO manager: Registered plugin: halt command
 INFO manager: Registered plugin: init command
 INFO manager: Registered plugin: cap command
 INFO manager: Registered plugin: status command
 INFO manager: Registered plugin: box command
 INFO manager: Registered plugin: ssh command
 INFO manager: Registered plugin: snapshot command
 INFO manager: Registered plugin: reload command
 INFO manager: Registered plugin: provision command
 INFO manager: Registered plugin: port command
 INFO manager: Registered plugin: rdp command
 INFO manager: Registered plugin: resume command
 INFO manager: Registered plugin: version command
 INFO manager: Registered plugin: provider command
 INFO manager: Registered plugin: list-commands command
 INFO manager: Registered plugin: destroy command
 INFO manager: Registered plugin: powershell command
 INFO manager: Registered plugin: Gentoo host
 INFO manager: Registered plugin: FreeBSD host
 INFO manager: Registered plugin: Linux host
 INFO manager: Registered plugin: Red Hat Enterprise Linux host
 INFO manager: Registered plugin: Windows host
 INFO manager: Registered plugin: Slackware host
 INFO manager: Registered plugin: null host
 INFO manager: Registered plugin: Arch host
 INFO manager: Registered plugin: Mac OS X host
 INFO manager: Registered plugin: SUSE host
 INFO manager: Registered plugin: BSD host
 INFO manager: Registered plugin: heroku
 INFO manager: Registered plugin: atlas
 INFO manager: Registered plugin: local-exec
 INFO manager: Registered plugin: ftp
 INFO manager: Registered plugin: noop
 INFO manager: Registered plugin: Gentoo guest
 INFO manager: Registered plugin: FreeBSD guest
 INFO manager: Registered plugin: NixOS guest
 INFO manager: Registered plugin: Linux guest.
 INFO manager: Registered plugin: Red Hat Enterprise Linux guest
 INFO manager: Registered plugin: OmniOS guest.
 INFO manager: Registered plugin: Windows guest.
 INFO manager: Registered plugin: OpenBSD guest
 INFO manager: Registered plugin: ESXi guest.
 INFO manager: Registered plugin: Slackware guest
 INFO manager: Registered plugin: PLD Linux guest
 INFO manager: Registered plugin: Solaris 11 guest.
 INFO manager: Registered plugin: CoreOS guest
 INFO manager: Registered plugin: Solaris guest.
 INFO manager: Registered plugin: Funtoo guest
 INFO manager: Registered plugin: Atomic Host guest
 INFO manager: Registered plugin: TinyCore Linux guest.
 INFO manager: Registered plugin: NetBSD guest
 INFO manager: Registered plugin: SmartOS guest.
 INFO manager: Registered plugin: VMware Photon guest
 INFO manager: Registered plugin: Arch guest
 INFO manager: Registered plugin: Darwin guest
 INFO manager: Registered plugin: Mint guest
 INFO manager: Registered plugin: Ubuntu guest
 INFO manager: Registered plugin: Debian guest
 INFO manager: Registered plugin: SUSE guest
 INFO manager: Registered plugin: Fedora guest
 INFO manager: Registered plugin: puppet
 INFO manager: Registered plugin: chef
 INFO manager: Registered plugin: file
 INFO manager: Registered plugin: ansible
 INFO manager: Registered plugin: salt
 INFO manager: Registered plugin: shell
 INFO manager: Registered plugin: docker
 INFO manager: Registered plugin: CFEngine Provisioner
 INFO manager: Registered plugin: SMB synced folders
 INFO manager: Registered plugin: NFS synced folders
 INFO manager: Registered plugin: RSync synced folders
 INFO global: Loading plugins!
 INFO vagrant: `vagrant` invoked: ["box", "add", "https://user:password@artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo", "--debug"]
 INFO environment: Environment initialized (#Vagrant::Environment:0x00560bca54fae8)
 INFO environment:   - cwd: /home/vagrant/workspace/vagrant
 INFO environment: Home path: /home/vagrant/.vagrant.d
 INFO environment: Local data path: /home/vagrant/workspace/vagrant/.vagrant
 INFO environment: Running hook: environment_plugins_loaded
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_plugins_loaded #Vagrant::Action::Builder:0x00560bca5889d8
 INFO environment: Running hook: environment_load
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_load #Vagrant::Action::Builder:0x00560bca27fcc8
 INFO cli: CLI: [] "box" ["add", "https://user:password@artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo"] 
 INFO loader: Set :root = ["#Pathname:/home/vagrant/workspace/vagrant/Vagrantfile"] 
 INFO loader: Loading configuration in order: [:home, :root] 
 INFO host: Autodetecting host type for [#<Vagrant::Environment: /home/vagrant/workspace/vagrant>] 
 INFO host: Detected: redhat!
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action:  #Vagrant::Action::Builder:0x00560bc9eb2938
 INFO warden: Calling IN action: #Vagrant::Action::Builtin::BoxAdd:0x00560bca615090
 INFO environment: Running hook: authenticate_box_url
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: authenticate_box_url #Vagrant::Action::Builder:0x00560bca42ccb0
 INFO warden: Calling IN action: #VagrantPlugins::LoginCommand::AddAuthentication:0x00560bc9df3948
 INFO warden: Calling OUT action: #VagrantPlugins::LoginCommand::AddAuthentication:0x00560bc9df3948
 INFO box_add: Downloading box: https://user:password@artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo => /home/vagrant/.vagrant.d/tmp/box7e56a29315bd5f88e1dc2bc65dee6d9276daf587
 INFO downloader: HEAD: https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo
 INFO subprocess: Starting process: ["/usr/bin/curl", "-I", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.8.1 (+https://www.vagrantup.com; ruby2.3.1)", "--continue-at", "-", "-u", "user:password", "-H", "Accept: application/json", "https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo"]
 INFO subprocess: Command not in installer, restoring original environment...
  Server: nginx/1.6.2
Date: Tue, 04 Oct 2016 14:10:44 GMT
Content-Type: application/json
Content-Length: 0
Connection: keep-alive
X-Artifactory-Id: 395de8333de4ef78:-345c33e9:15777b20ad6:-8000
 INFO interface: output: Loading metadata for box 'https://user:password@artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo'
 INFO interface: output: ==> box: Loading metadata for box 'https://user:password@artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo'
==> box: Loading metadata for box 'https://user:password@artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo'
 INFO box_add: Downloading box: https://user:password@artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo => /home/vagrant/.vagrant.d/tmp/box7e56a29315bd5f88e1dc2bc65dee6d9276daf587
 INFO downloader: Downloader starting download: 
 INFO downloader:   -- Source: https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo
 INFO downloader:   -- Destination: /home/vagrant/.vagrant.d/tmp/box7e56a29315bd5f88e1dc2bc65dee6d9276daf587
 INFO subprocess: Starting process: ["/usr/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.8.1 (+https://www.vagrantup.com; ruby2.3.1)", "--continue-at", "-", "-u", "user:password", "-H", "Accept: application/json", "--output", "/home/vagrant/.vagrant.d/tmp/box7e56a29315bd5f88e1dc2bc65dee6d9276daf587", "https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo"]
 INFO subprocess: Command not in installer, restoring original environment...
 INFO interface: output: Adding box 'fedora24-algo' (v1.0.0) for provider: virtualbox
 INFO interface: output: ==> box: Adding box 'fedora24-algo' (v1.0.0) for provider: virtualbox
==> box: Adding box 'fedora24-algo' (v1.0.0) for provider: virtualbox
 INFO box_collection: Box not found: fedora24-algo (virtualbox)
 INFO box_add: Downloading box: https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo-virtualbox-1.0.0.box => /home/vagrant/.vagrant.d/tmp/box70dd17271a3e5fbd5cc2faae9be58a1d42748509
 INFO interface: detail: Downloading: https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo-virtualbox-1.0.0.box
 INFO interface: detail:     box: Downloading: https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo-virtualbox-1.0.0.box
    box: Downloading: https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo-virtualbox-1.0.0.box
 INFO downloader: Downloader starting download: 
 INFO downloader:   -- Source: https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo-virtualbox-1.0.0.box
 INFO downloader:   -- Destination: /home/vagrant/.vagrant.d/tmp/box70dd17271a3e5fbd5cc2faae9be58a1d42748509
 INFO subprocess: Starting process: ["/usr/bin/curl", "-q", "--fail", "--location", "--max-redirs", "10", "--user-agent", "Vagrant/1.8.1 (+https://www.vagrantup.com; ruby2.3.1)", "--continue-at", "-", "--output", "/home/vagrant/.vagrant.d/tmp/box70dd17271a3e5fbd5cc2faae9be58a1d42748509", "https://artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo-virtualbox-1.0.0.box"]
 INFO subprocess: Command not in installer, restoring original environment...
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 INFO interface: info: 
[K
[K INFO interface: detail: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
 INFO interface: detail:     box: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)
    box: Progress: 0% (Rate: 0/s, Estimated time remaining: --:--:--)DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999

curl: (22) The requested URL returned error: 401 Unauthorized
 WARN downloader: Downloader exit code: 22
ERROR downloader: Exit code: 22
 INFO interface: info: 
[K
[KDEBUG box_add: Deleting temporary box: 
ERROR warden: Error occurred: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
The requested URL returned error: 401 Unauthorized
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 1 hooks defined.
 INFO runner: Running action: environment_unload #Vagrant::Action::Builder:0x00560bcb136dc0
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<Vagrant::Errors::DownloaderError: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
The requested URL returned error: 401 Unauthorized>
ERROR vagrant: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
The requested URL returned error: 401 Unauthorized
ERROR vagrant: /usr/share/vagrant/lib/vagrant/util/downloader.rb:206:in `execute_curl'
/usr/share/vagrant/lib/vagrant/util/downloader.rb:136:in`download!'
/usr/share/vagrant/lib/vagrant/action/builtin/box_add.rb:445:in `download'
/usr/share/vagrant/lib/vagrant/action/builtin/box_add.rb:321:in`block in box_add'
/usr/share/vagrant/lib/vagrant/action/builtin/box_add.rb:313:in `each'
/usr/share/vagrant/lib/vagrant/action/builtin/box_add.rb:313:in`box_add'
/usr/share/vagrant/lib/vagrant/action/builtin/box_add.rb:266:in `add_from_metadata'
/usr/share/vagrant/lib/vagrant/action/builtin/box_add.rb:104:in`call'
/usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
/usr/share/vagrant/lib/vagrant/action/builder.rb:116:in`call'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
/usr/share/vagrant/lib/vagrant/util/busy.rb:19:in`busy'
/usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
/usr/share/vagrant/plugins/commands/box/command/add.rb:78:in`execute'
/usr/share/vagrant/plugins/commands/box/command/root.rb:61:in `execute'
/usr/share/vagrant/lib/vagrant/cli.rb:42:in`execute'
/usr/share/vagrant/lib/vagrant/environment.rb:302:in `cli'
/usr/share/vagrant/bin/vagrant:174:in`<main>'
 INFO interface: error: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
The requested URL returned error: 401 Unauthorized
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
The requested URL returned error: 401 Unauthorized
 INFO interface: Machine: error-exit ["Vagrant::Errors::DownloaderError", "An error occurred while downloading the remote file. The error\nmessage, if any, is reproduced below. Please fix this error and try\nagain.\n\nThe requested URL returned error: 401 Unauthorized"]

**Comment by chrisroberts** [comment]
Is this an intermittent problem or is it reliably reproducible?

**Comment by bionoone** [comment]
reliably reproductible. it has been verified on Windows 8.1 and fedora 24.

note: there is trivial workaround - use the fully version qualified url (https://user:password@artifactory.mysite.com/artifactory/api/vagrant/vagrant-local/fedora24-algo-virtualbox-1.0.0.box). so the priority is quite low.

**Comment by chrisroberts** [comment]
Okay, great. Thanks for the follow up!

**Comment by chrisroberts** [comment]
Closing as creds can be provided within target URL.
