### ISSUE TITLE
Provide private ip in global-status

### ISSUE THREAD

**Issue by Yuki-Inoue** [hashicorp/vagrant#7869]
This is an enhancement idea: I thought it would be useful if we could obtain the private ips, defined by the `private_network` configuration, in the `vagrant global-status` command.

Any opinion?

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
