### ISSUE TITLE
Error: dup() in/out/err failed

### ISSUE THREAD

**Issue by Hassnain-Raza-Alvi** [hashicorp/vagrant#7899]
I am getting the rsync error in vagrant up. I am using Git Bash in Windows 10. here is the detailed error 

```
==> web: Rsyncing folder: /c/Users/Hassnain/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /c/Users/Hassnain/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL   -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'C:/Users/Hassnain/.vagrant/machines/web/virtualbox/private_key'" "--exclude" ".vagrant/" "/c/Users/Hassnain/" "vagrant@127.0.0.1:/vagrant"
Error: dup() in/out/err failed
rsync: read error: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at /usr/src/rsync/rsync-3.0.8/io.c(760) [sender=3.0.8]

```

All the rules for rsync vagrant are added in firewall and everything is allowed. I tried removing line  84 in helper.rb in rsync gem folder but it did not worked as well 

Please guide me how to solve it 
### Vagrant version

v1.8.6
### Host operating system

Windows 10 Pro Latest
### Guest operating system

CentOS/7 VBox

**Comment by chrisroberts** [comment]
@Hassnain-Raza-Alvi Can you confirm if this is still an issue with the latest Vagrant release? Thanks!

**Comment by lordgordon** [comment]
Hi there, 

I have the same issue with a Windows 10 Home (latest) host and Vagrant 1.9.1.

As a workaround I use powershell with cwRsync, but I had to manually fix a Vagrant ruby file to have it working. And it seems this solution is not perfect as I have another issue as described in GH-8333.

**Comment by chestercharles** [comment]
Howdy all,

I am having the same issue but with a Windows 8.1 host

### Host
Windows 8.1 Enterprise 

### Guest
 ubunut/trusty64

### Box
Vagrant 1.9.4.

```
Host path: /c/HashiCorp/Vagrant/Projects/vm_mitts/shared/
Guest path: /srv/apps
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL   -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'C:/HashiCorp/Vagrant/Projects/vm_mitts/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "/c/HashiCorp/Vagrant/Projects/vm_mitts/shared/" "vagrant@127.0.0.1:/srv/apps"
Error: dup() in/out/err failed
rsync: read error: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at /usr/src/rsync/rsync-3.0.8/io.c(760) [sender=3.0.8]
```

**Comment by chestercharles** [comment]
I was actually able to resolve this issue by reinstalling rsync using cygwin.

I had initially installed rsync using mingw. 

Per the solution by kwakwaversal in #6677 (near the bottom), I downloaded cygwin and installed rsync and the cygwin ssh client. Now it seems to be working fine.

**Comment by snfnwgi** [comment]
Who can answer my question
https://github.com/hashicorp/vagrant/issues/9010

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Comment by TYOFFE718** [comment]
still getting this error

Enter your choice: 3
==> box: Adding box 'laravel/homestead' (v5.1.0) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/laravel/boxes/homestead/versions/5.1.0/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
