### ISSUE TITLE
Vagrant failing using rsync/ssh on Windoze guest

### ISSUE THREAD

**Issue by bgblanch** [hashicorp/vagrant#7904]
### Vagrant version

Vagrant 1.8.6 & vSphere
### Host operating system

Ubuntu 16.04.1
### Guest operating system

Windows Server 2012R2
### Vagrantfile

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "dummy"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600
  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true

  config.vm.provider :vsphere do |vsphere|
    vsphere.host = '<removed>'
    vsphere.name = 'Windows_Build_Server_2012R2'
    vsphere.data_center_name = '<removed>'
    vsphere.vm_base_path = '<removed>'
    vsphere.template_name = '<removed>'
    vsphere.clone_from_vm = 'true'

    vsphere.memory_mb = '4096'
    vsphere.cpu_count = '2'

    vsphere.user = 'william'
    vsphere.password = :ask
    vsphere.insecure = 'true'
  end

  config.vm.provision "shell", path: "provisioner/prereqs.ps1"
  config.vm.provision :reload
  config.vm.provision "shell", path: "provisioner/vs_install.ps1"
  config.vm.provision :reload
  config.vm.provision "shell", path: "provisioner/install.ps1"
end
```
### Debug output

[ssh_issue.log gist](https://gist.github.com/bgblanch/6f48a37e949f935c7805aeb9fbb1265f)

```
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /home/william/Git/Windows_Build_vSphere/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--no-owner" "--no-group" "-e" "ssh -p 22 -o LogLevel=FATAL  -o ControlMaster=auto -o ControlPath=/tmp/ssh.132 -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/home/william/.vagrant.d/insecure_private_key'" "--exclude" ".vagrant/" "/home/william/Git/Windows_Build_vSphere/" "vagrant@192.168.1.134:/vagrant"
Error: rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]
```
### Expected behavior

local project folder is "sync'd" with vSphere /vagrant folder
### Steps to reproduce

```
`vagrant up --provider=vsphere `
```

**Comment by bgblanch** [comment]
I moved this issue from the provider to vagrant proper because it appears, to my noob eyes, that the provider is relying on the SyncedFolders within vagrant.  For Windoze guests, I believe it should be using winrm rather than ssh.  I've tried using OpenSSH and Cygwin ssh within the Windoze guest with no luck.

**Comment by matthewvalimaki** [comment]
I am experiencing this same issue with same guest (Windows Server 2008 R2) on AWS (https://github.com/mitchellh/vagrant-aws) with zero provisions. I have not tried using SSH server on the guest but that would be an unacceptable workaround for me as well.

**Comment by rayterrill** [comment]
Looks like this is still an issue. I'm working around this with:
`
config.vm.synced_folder '.', '/vagrant', disabled: true
`

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
