### ISSUE TITLE
rsync` failed on Vagrant 1.8.6

### ISSUE THREAD

**Issue by omps** [hashicorp/vagrant#7908]
### Vagrant version

~$ vagrant --version
Vagrant 1.8.6
### Host operating system

~$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.5 (Santiago)
### Guest operating system

Centos 7
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.define "devopsmain" do |devopsmain|
    devopsmain.vm.box  = "centos/7"
    devopsmain.vm.hostname = "devopsmain"
    devopsmain.vm.network :private_network, ip: "192.168.250.100"
    devopsmain.hostmanager.alias = %w(devopsmain)
    devopsmain.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    devopsmain.vm.provision "shell", inline: <<-SHELL
       sudo yum update -y
       sudo rpm -ivh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
       sudo yum install puppetserver -y
       sudo sed -i 's/2g/512m/g' /etc/sysconfig/puppetserver
    SHELL
  end

```
### Actual behavior

==> devopsmain: Rsyncing folder: /home/singho/devopsenv/ => /home/vagrant/sync
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /home/singho/devopsenv/
Guest path: /home/vagrant/sync
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2200 -o LogLevel=FATAL  -o ControlMaster=auto -o ControlPath=/tmp/ssh.849 -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/home/singho/devopsenv/.vagrant/machines/devopsmain/virtualbox/private_key'" "--exclude" ".vagrant/" "/home/singho/devopsenv/" "vagrant@127.0.0.1:/home/vagrant/sync"
Error: command-line: line 0: Bad configuration option: ControlPersist
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]
### References
#6702
### Issue 1:

As per the issue #6702 I removed the following lines

``` ruby
         unless Vagrant::Util::Platform.windows?
           controlpath = File.join(Dir.tmpdir, "ssh.#{rand(1000)}")
           control_options = "-o ControlMaster=auto -o ControlPath=#{controlpath} -o ControlPersist=10m "
         end
```

which solves the issue.

I am wondering why my system is being detected as a windows machine by vagrant?

**Comment by snfnwgi** [comment]
Who can answer my question
https://github.com/hashicorp/vagrant/issues/9010

**Comment by vhosakot** [comment]
When I did `vagrant up` with the box `centos/7 (virtualbox, 1703.01)`, `==> default: Rsyncing folder: /root/ => /vagrant` was stuck for me too, and adding
`config.vm.synced_folder '.', '/vagrant', disabled: true`
in Vagrantfile resolved the issue for me and rsync did not happen.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
