### ISSUE TITLE
Setting hostname on debian8 with systemd / without dbus

### ISSUE THREAD

**Issue by beatchristen** [hashicorp/vagrant#7973]
### Vagrant version
1.8.6

### Host operating system
 Darwin Kernel Version 16.1.0
VirtualBox Version: 5.1

### Guest operating system
Guest Additions Version: 5.0.12
Debian 8.5 with systemd *without* dbus

### Vagrantfile
```ruby
  config.vm.define 'debian8-without-dbus' do |node|
    node.vm.guest = :debian
    hostname node, 'debian8-without-dbus'
    size node, cpu=2, mem=1024
  end
```

### Debug output
https://gist.github.com/beatchristen/7a22ffe46d4a6569a2397e5e6dcc7469

### Expected behavior
the hostname should be set to debian8-without-dbus.loc.serv.development

### Actual behavior
vagrant terminated with an error

### Steps to reproduce
1. Use a debian base box with systemd and without dbus (apt-get purge dbus if necessary)
2. vagrant up

### References
https://wiki.debian.org/HowTo/ChangeHostname
> Versions of Debian with systemd installed can use "hostnamectl set-hostname mymachine". 
> This tool depends on dbus so be sure to install that first. 

I'm not sure why systemd would install /usr/bin/hostnamectl without depending on dbus

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Comment by abbbi** [comment]
hi,

im stumbling about this with the recently released version. 
I downgraded to v2.1.5 , the version i used before to make it work again.
