### ISSUE TITLE
No warning if using custom ssh key path and unable to save newly generated key

### ISSUE THREAD

**Issue by dragon788** [hashicorp/vagrant#8037]
Similar issue to #7610 but occurring after I used a custom path for the insecure_vagrant_key. After it installs the insecure key it is unable to find and use the newly generated key, but it doesn't report any errors. I'm fairly certain the issue is that I have the VM on a "shared" NTFS partition where Vagrant is unable to put the correct permissions on the SSH key, but it should provide a warning about that, not just silently fail to connect.

To work around this I simply used the `config.ssh.insert_key = false` as well as supplying the alternate path to the insecure key.

### Vagrant version
1.8.7

### Host operating system
Ubuntu 16.04

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.private_key_path = '/home/username/.ssh/insecure_private_key'
  #config.ssh.insert_key = false
  config.vm.box = "boxcutter/ubuntu1604-desktop"
end
```

### Debug output
https://gist.github.com/anonymous/3006bc841caaf97cd3965443fccf7931

Lowercase 'username' is a Linux user, uppercase 'Username' is the shared Windows path to .vagrant.d and my projects folder.

### Expected behavior
Should have received a warning around setting permissions on the newly generated SSH key that was inserted to the VM to replace the insecure key rather than a generic timeout message.

### Actual behavior
Didn't receive a warning. The VM booted and I got the generic error about being unable to communicate with it after the secondary SSH connection finally timed out.

### Steps to reproduce
1. Put .vagrant.d and a project folder with Vagrantfile on a FAT32 or NTFS drive, export VAGRANT_HOME to point to .vagrant.d.
2. Copy insecure private key to ~/.ssh that has valid permissions (600 or 644).
2. vagrant up with above example file and watch the failure.
3. Uncomment the insert_key line and vagrant destroy then vagrant up and enjoy the success/silence.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- #7610

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
