### ISSUE TITLE
vagrant 1.8.7  Windows 10 doesn't installs correctly

### ISSUE THREAD

**Issue by MikhailRoot** [hashicorp/vagrant#8038]
I used 1.8.0 version with virtualbox  but as  recent windows 10 updates installed when I tried to vagrant up it gave me an error with virtualbox. So i've updated virtualbox to 5.1 but vagrant 1.8.0 doesn't work with VirtualBox 5.1 so I've decided to update Vagrant to latest 1.8.7 too.
The problem is: after installation bin directory with vagrant.exe is not accessible even to be listed even under administrator account, it says you have no priviliges to access. Also it doesn't sets up correct $PATH  variable for vagrant to work. My current sollution is to install 1.8.5 which installs correctly. 
Please check and fix windows msi installer for 1.8.7.

**Comment by cyclobster** [comment]
I'm getting the same issue. vagrant.exe is not accessable even for administrator account after upgrading from 1.8.5 to 1.8.7 on Windows 7. The difference for me is I uninstalled 1.8.7, reinstalled 1.8.5 but 1.8.5 no longer works.

**Comment by chrisroberts** [comment]
Hi! Can you show what the permissions are for the `C:\HashiCorp\Vagrant` and the `C:\HashiCorp\Vagrant\bin` directories. I am successfully installing Vagrant 1.8.7 on a fresh Windows 10 with no problems. Need some more context to attempt to reproduce this issues. Thanks!

**Comment by MikhailRoot** [comment]
I've tried to upgrade Vagrant to 1.8.7 in non standard directory C:\DEV\Vagrant my user was owner and has full access to it. 1.8.7 msi package on installation asks for administrator priviliges to continue.  Sorry i've deleted directory  C:\DEV\Vagrant\bin booting under Ubuntu because it became completely unaccessible under windows after installation, when I opened access rights tab for it it showed me empty permissions list and when I've tried to add permissions for my user it throws me an error, so I couldn't even close adding this dialog. Then after removal I've tried to install Vagrant 1.8.7 wit default path C:\HashiCorp\Vagrant but experienced same issue with ./bin subdirectory as before. It showed me empty list of permissions for Vagrant/bin directory and I still couldn't open it and even change permissions.

**Comment by cyclobster** [comment]
On C:\HashiCorp\Vagrant I'm getting:
```
Vagrant BUILTIN\Users:(OI)(CI)(RX)
        BUILTIN\Administrators:(OI)(CI)(F)
        NT AUTHORITY\SYSTEM:(OI)(CI)(F)

Successfully processed 1 files; Failed processing 0 files
```

On C:\HashiCorp\Vagrant\bin I'm getting:
```
C:\HashiCorp\Vagrant>icacls bin
bin BUILTIN\Users:(I)(OI)(CI)(RX)
    BUILTIN\Administrators:(I)(OI)(CI)(F)
    NT AUTHORITY\SYSTEM:(I)(OI)(CI)(F)

Successfully processed 1 files; Failed processing 0 files
```

**Comment by chrisroberts** [comment]
@cyclobster and the vagrant executable is not accessible?

**Comment by cyclobster** [comment]
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved

C:\HashiCorp\Vagrant\bin>icacls vagrant.exe
vagrant.exe BUILTIN\Administrators:(I)(F)
            NT AUTHORITY\SYSTEM:(I)(F)
            BUILTIN\Users:(I)(RX)
            NT AUTHORITY\Authenticated Users:(I)(M)

Successfully processed 1 files; Failed processing 0 files

C:\HashiCorp\Vagrant\bin>vagrant
Access is denied.

C:\HashiCorp\Vagrant\bin>vagrant.exe
Access is denied.

C:\HashiCorp\Vagrant\bin>icacls vagrant.exe
vagrant.exe: The system cannot find the file specified.
Successfully processed 0 files; Failed processing 1 files
```

**Comment by MikhailRoot** [comment]
> C:\HashiCorp\Vagrant\bin>vagrant
Access is denied.

> C:\HashiCorp\Vagrant\bin>vagrant.exe
Access is denied.
@cyclobster 


This is exactly the root of problem I've experienced. Currently solved only by installing Vagrant 1.8.5 .

**Comment by MikhailRoot** [comment]
Sorry i've accidantially closed issue. it's still opened.

**Comment by briancain** [comment]
Hi @MikhailRoot - I recommend downloading the latest vagrant and seeing if this is still an issue. If so please re-open. Thanks1
