### ISSUE TITLE
Drop requirement for environments with puppet4& puppet apply provisioner

### ISSUE THREAD

**Issue by nicobrevin** [hashicorp/vagrant#8072]
This is a feature request to allow the puppet apply provisioner to operate without a manifests dir options, so you can just point to something under `/vagrant` without needing extra folder boilerplate if you don't want it.

The puppet apply provisioner forces you to use a manifest dir, which wasn't a big deal with puppet < 4, but with the more complex layout in puppet 4 it's a bit of a pain.  Afaics, there's no need for this for local applies, because it can be done as simply as `puppet apply --modulepath /vagrant/modules /vagrant/site.pp
`

Thoughts?  Worth me submitting a PR?

**Comment by chrisroberts** [comment]
@nicobrevin If you would like to put together a PR for this I would be happy to review it!

**Comment by ekohl** [comment]
It looks like ```@manifest_file``` is already an absolute path so ```--manifestdir``` is redundant unless you use includes inside your manifest.

**Comment by briancain** [comment]
I believe this was already fixed in #8797. I'm going to go ahead and close this issue.
