### ISSUE TITLE
Extra SSH options in Vagrantfile

### ISSUE THREAD

**Issue by zaufi** [hashicorp/vagrant#8077]
Reading sources of `/usr/lib64/ruby/gems/2.3.0/gems/vagrant-1.8.7/lib/vagrant/util/ssh.rb` (line 105) I see that there is an option to control log level could be set:
```ruby
        log_level = ssh_info[:log_level] || "FATAL"

        # Command line options
        command_options = [
          "-p", options[:port].to_s,
          "-o", "Compression=yes",
          "-o", "DSAAuthentication=yes",
          "-o", "LogLevel=#{log_level}"]
```
but adding `config.ssh.log_level = "DEBUG"` to my `Vagrantfile` gives me an error:

```
SSH:
* The following settings shouldn't exist: log_level
```

It looks like this option has missed in `/usr/lib64/ruby/gems/2.3.0/gems/vagrant-1.8.7/lib/vagrant/machine.rb` in function `ssh_info` at line 422...

Another missed option, used by `ssh.rb` and missed is `extra_args`...

**Comment by pachonk** [comment]
Try `config.env[:ssh_info][:log_level] = 'DEBUG'` perhaps.

**Comment by pachonk** [comment]
Here is the full docs for config.ssh: https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
