### ISSUE TITLE
Default installer path for windows is set to C:\HashiCorp

### ISSUE THREAD

**Issue by dorinlazar** [hashicorp/vagrant#8082]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.9.0

### Host operating system
Windows 10

### Guest operating system
n/a

### Vagrantfile
n/a

### Debug output
n/a

### Expected behavior
The default installation path should be C:\Program Files\HashiCorp\Vagrant or C:\Program Files (x86)\HashiCorp\Vagrant

### Actual behavior
The default installation path is C:\HashiCorp\Vagrant

### Steps to reproduce
1. Run installer

### References
n/a

**Comment by chrisroberts** [comment]
There are historical compatibility issues for why the installation is at `C:\HashiCorp\Vagrant` by default. Moving the installation to the system defined program files destination is planned for a currently undefined future release. Cheers!

**Comment by kikitux** [comment]
@dorinlazar to explain a bit more, the issues relies on the Spaces in `Program Files` basically.

**Comment by chrisroberts** [comment]
Closing this as the installer will continue to use the current default path for the foreseeable future.
