### ISSUE TITLE
Hyper-V disk file not deleted by Test-Kitchen

### ISSUE THREAD

**Issue by rlaveycal** [hashicorp/vagrant#8128]
### Vagrant version
1.9.1

### Host operating system
Windows 10 1607

### Guest operating system
N/A

### Expected behavior

Using Chef's Test-Kitchen with the vagrant provider to create a Hyper-V machine, `kitchen destroy` doesn't delete the virtual disk file.

When using vagrant directly `vagrant destroy` does delete the entire hyper-v folder

This could be related to the `delete_vm.ps1` script which only calls `Remove-VM`. This doesn't delete the disks. `Get-VHD $VmId | Remove-Item -Force` would be required to delete the disks

### Background

I'm currently trying to work around a path-to-long issue (> 260 chars) with Test-Kitchen. As part of that I've hacked the `import_vm_vmcx.ps1` script to create the data files outside of the vagrant folder. Hence they were left behind on destroy. I still think it would be better for vagrant to delete the disks by querying Hyper-V rather than assume they are in a child directory.

**Comment by chrisroberts** [comment]
Closing as this is working correctly from Vagrant.

Cheers!
