### ISSUE TITLE
Problem to mount NFS synced folder in any provider

### ISSUE THREAD

**Issue by francisrod01** [hashicorp/vagrant#8140]
Hi guys!

I have the same problem of synced folders, but in all providers.
**My OS:** Debian Jessie AMD 64 bits.
This question is distinct to issue #6769 

For example, to using `debian/jessie64`:

output here:

```bash
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
● nfs-kernel-server.service - LSB: Kernel NFS server support
   Loaded: loaded (/etc/init.d/nfs-kernel-server)
   Active: active (exited) since Sun 2016-12-18 20:21:10 BRST; 1 day 13h ago
==> default: Mounting NFS shared folders...



The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp,rw,vers=4,tcp,nolock 192.168.33.1:/home/tosystems /vagrant
result=$?
if test $result -eq 0; then
if test -x /sbin/initctl && command -v /sbin/init && /sbin/init 2>/dev/null --version | grep upstart; then
/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/vagrant
fi
else
exit $result
fi


Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: Connection timed out
```

Now, to using `debian/contrib-jessie64`:

```bash
$ vagrant up --provider kvm
Ignoring ruby-libvirt-0.6.0 because its extensions are not built.  Try: gem pristine ruby-libvirt --version 0.6.0
Bringing machine 'default' up with 'kvm' provider...
==> default: Box 'debian/contrib-jessie64' could not be found. Attempting to find and install...
    default: Box Provider: kvm
    default: Box Version: >= 0
==> default: Loading metadata for box 'debian/contrib-jessie64'
    default: URL: https://atlas.hashicorp.com/debian/contrib-jessie64
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: debian/contrib-jessie64
Address: https://atlas.hashicorp.com/debian/contrib-jessie64
Requested provider: [:kvm]
```

And so, using my box of work (also not run), `ubuntu xenial 64 bits`

```bash
==> default: Waiting for machine to boot. This may take a few minutes...
 
```

And I have already entered the public key of my machine in the VM `authorization_keys` file.
I'm pretty sure I'll have trouble mounting the disk with this VM too.

What's happening?

**Comment by mauricioabreu** [comment]
@devtosystems I think this problem is related to Vagrant 1.9.1. 
Try to downgrade to 1.9.0 and check if it works.

**Comment by devtosystems** [comment]
Thanks @mauricioabreu I'll try this now.

**Comment by davecb** [comment]
I have much the same symptoms, encountered when "up" ing a KVM VM containing ubuntu on my Fedora 25 machine.  A test run using the Vagrantfile below produced the attached log. 
 
[vagrant_ubuntu_kvm.txt](https://github.com/mitchellh/vagrant/files/706207/vagrant_ubuntu_kvm.txt)

Feel free to contact me at davecb@spamcop.net if there is anyting I can do to help, like log a run with different settings 

--dave

```
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.10"
end
```

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
