### ISSUE TITLE
Rsync blocked sending incremental file list on VM boot

### ISSUE THREAD

**Issue by daks** [hashicorp/vagrant#8168]
### Vagrant version
1.9.1

### Host operating system
Debian testing/stretch

### Guest operating system
debian/wheezy64, or debian/jessie64 or ubuntu/trusty64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  # needed to force use of rsync
  config.vm.synced_folder ".", "/vagrant", type: "rsync"    
end
```

### Debug output
https://gist.github.com/daks/d60c30eb1b17e6f593f8a7d13f000a4a
I removed all information about other VM available on this machine

### Expected behavior
I expect vagrant to sync current host directory to /vagrant on the guest. But rsync keeps failing, whatever image I use (tested with 2 Debian, 1 Ubuntu) and provider (tested with Virtualbox and Libvirt)

### Actual behavior
Boot is stucked at 'send incremental file list' and ends with an error message.

### Steps to reproduce
1. vagrant init debian/jessie64
2. edit Vagrantfile to force use of rsync for sync folder
3. vagrant up

**Comment by daks** [comment]
I tried vagrant 1.8.7 and got the same problem

**Comment by predatorian3** [comment]
This seems to also be a problem with Vagrant 1.9.2 and Virtualbox 5.1.18

```
C:\Users\user01\Desktop\jenkins_test
λ vagrant up --provider=virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'centos/7' is up to date...
"rsync" could not be found on your PATH. Make sure that rsync
is properly installed on your system and available on the PATH.

C:\Users\user01\Desktop\jenkins_test
λ vagrant version
Installed Version: 1.9.2
Latest Version: 1.9.2

You're running an up-to-date version of Vagrant!

C:\Users\user01\Desktop\jenkins_test
λ VBoxManage.exe --version
5.1.18r114002

```

**Comment by chrisroberts** [comment]
@predatorian3  The error you are encountering is the lack of an `rsync` executable on your host system. The Windows Vagrant package does not currently include `rsync` and as such you'll need to install one for that type of synced folder to work. More information here: https://www.vagrantup.com/docs/synced-folders/rsync.html#prerequisites

**Comment by daks** [comment]
It seems that my issue with rsync is now resolved. I have no idea what happens in between, except distro and Vagrant upgrades.
My box image has not changed, and it was not an issue with rsync non available.

**Comment by chrisroberts** [comment]
Closing as issue is resolved.
