### ISSUE TITLE
Vagrant does not URLEncode credentials when prompting for password using SMB synced_folder

### ISSUE THREAD

**Issue by bender-the-greatest** [hashicorp/vagrant#8169]
### Vagrant version
Vagrant 1.9.1

### Host operating system
Windows 10

### Guest operating system
OSX El Capitan, though since the error was a URL encoding error I'd imagine it also affects Linux or other BSD guests.

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "osx_el_capitan" # This box was built locally, but can likely be reproduced using a Linux/BSD box w/ SMB type `synced_folder`
  config.vm.synced_folder '.', "/vagrant", type: :smb

  config.vm.provider :virtualbox do |v|
    v.gui = true
  end
end
```

### Expected behavior
Mount the SMB share and continue with provisioning steps.

### Actual behavior
Received an error with the `smb://` URL that was generated after inputting my credentials stating that the URL was invalid. My password has special characters in it that would need to be URL encoded or it would confuse the URL parser. Changing my host password to something alphanumeric allowed the shared mount to continue as expected.

### Steps to reproduce
1. SMB server with password containing non-alphanumeric characters (e.g. @, *, ?, etc.)
2. `vagrant up`, inputting username and password 
3. You should receive the error shortly after it attempts to mount the SMB type `synced_folder`

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
