### ISSUE TITLE
SMB credential are not used.

### ISSUE THREAD

**Issue by SaschaMzH** [hashicorp/vagrant#8214]
### Vagrant version
Vagrant 1.9.1

### Host operating system
Windows 7

### Guest operating system
Ubuntu 

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "kaorimatz/ubuntu-16.04-amd64"

  config.vm.synced_folder "c:\\projects\\", "/c/projects", type: "smb"
end
```

### Expected behavior
Use the credential which are typed into the console during the `vagrant up`.

### Actual behavior
The credentials which are type into the console are not used. Furthermore the local smb share is read and writeable for everyone.

### Steps to reproduce
1. `vagrant up`
2. Look into the newtork settings from the created smb share.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
