### ISSUE TITLE
translation missing: en.vagrant.commands.status.deletingsnapshotlive

### ISSUE THREAD

**Issue by danielcompton** [hashicorp/vagrant#8216]
### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

$ vagrant -v
Vagrant 1.9.1

### Host operating system

macOS Sierra 10.12.2

### Guest operating system

`ubuntu/trusty64`

### Steps to reproduce

In one console tab I ran

```sh
vagrant snapshot delete java-installed
```

in another I ran

```sh
vagrant status
```

### Expected behavior

Translations exist for deleting a snapshot.

### Actual behavior

```sh
$ vagrant status
Current machine states:

default                   deletingsnapshotlive (virtualbox)

translation missing: en.vagrant.commands.status.deletingsnapshotlive
```

### References

#1110 is one similar issue.

**Comment by briancain** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
