### ISSUE TITLE
Supporting stronger hashes (SHA256,SHA384,SHA512) in the downloader integrity checker

### ISSUE THREAD

**Issue by BabakMN** [hashicorp/vagrant#8232]
Thanks to @chrisroberts and @sethvargo in #7985 currently we have support for MD5 and SHA1. I'd like to propose that we also add support for SHA256, SHA384 and SHA512.

**Comment by briancain** [comment]
Hi, this has been added in the most recent release of Vagrant. Closing this issue now! :tada:
