### ISSUE TITLE
Vagrant 1.9.1 - A parameter cannot be found that matches parameter name 'BootDevice'

### ISSUE THREAD

**Issue by czuk** [hashicorp/vagrant#8240]
**Vagrant version**
1.9.1

**Host operating system**
Windows Server 2008R2 SP1

**Powershell**
PS C:\Users\ServerAdmin> $PSVersionTable.PSVersion
Major  Minor  Build  Revision
5      0      10586  117

**PowerShell Management Library for Hyper-V**
There does not appear to be native Hyper-V cmdlets in Server 2008 R2.  
I installed Hyper-V cmdlets from http://pshyperv.codeplex.com/releases specifically http://pshyperv.codeplex.com/downloads/get/219013 for Server 2008 R2 SP1.  
I guess they might not be supported which is fair - I inherited the server and an upgrade to 2012 or later isn't on the cards at the moment so it would be great if 2008 R2 with these cmdlets could be supported.

**Guest operating system**
ubuntu 16.04 server

**Provider**
hyperv

**Vagrantfile**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.network "public_network", auto_config: true
  config.vm.network :forwarded_port, guest: 3000, host: 3000, auto_correct: true
  config.vm.network :forwarded_port, guest: 3001, host: 3001, auto_correct: true
  config.vm.provision :shell, inline: <<-SHELL
    # Create Swap Filesystem
	echo "Creating Swap Filesystem"
	sudo fallocate -l 1G /swapfile > /dev/null
	sudo chmod 600 /swapfile > /dev/null
	sudo mkswap /swapfile > /dev/null
	sudo swapon /swapfile > /dev/null
	sudo cp /etc/fstab /etc/fstab.bak > /dev/null
	echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null
        SHELL
end
```

**Debug output**
https://gist.github.com/czuk/bd0d1f8e6252346fd075b291ec220a24

### Expected behavior
A new hyperv machine should have been created and started a la vagrant way.

### Actual behavior
vagrant up fails:
```
C:\gitclones\test>vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_xml.ps1
Error:

C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.9.1\plugins\providers\hyperv\
scripts\import_vm_xml.ps1 : A parameter cannot be found that matches parameter
name 'BootDevice'.At line:1 char:1
+ &('C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.9.1\plugins\prov ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [import_vm_xml.ps1], Parame
   terBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,import_vm_xml.ps1
```

**Steps to reproduce**
run vagrant up

**References**
- [here](https://github.com/mitchellh/vagrant/issues/7098)
- [here](https://github.com/paulshir/coreos-hyperv/issues/1)

**Comment by kikitux** [comment]
Hello @czuk 

Did you saw this?
https://www.vagrantup.com/docs/hyperv/

Vagrant hyperv works with Win8 , also with Win10.

Any chance you can test on Win8/10 ?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
