### ISSUE TITLE
Headless vagrant fails silently with a guru meditation on machines with VT-x disabled (or no VT-x support)

### ISSUE THREAD

**Issue by kg** [hashicorp/vagrant#825]
I installed the latest version of Vagrant for Windows on a Windows 7 machine with a 64-bit CPU that has VT-x (but I was unaware that VT-x was disabled in my BIOS). Every time I attempted to boot the VM with 'vagrant up', it would hang during the 'waiting for VM to start' stage. If I opened VirtualBox's GUI the VM would either appear hung or in a 'guru meditation' state. There wasn't any way for me to manually manage or fix the VM without killing all the virtualbox processes.

If I changed the vagrant config to run in GUI mode instead of headless, VirtualBox then opened up a dialog warning me about the lack of VT-x.

It would be ideal to detect the lack of VT-x and work around it, but a warning would be adequate too.

**Comment by enriquezrene** [comment]
For me this error was present when I upgraded my OS version
http://enriquezrene.com/home/index.php/devops/vagrant
