### ISSUE TITLE
Attempting to destroy a box with an always running file provisioner fails if the source file on the host does not exist

### ISSUE THREAD

**Issue by rtkaheller** [hashicorp/vagrant#8258]
When attempting to destroy a box that uses a file provisioner that is set to always run, it fails if the source file on the host does not exist. However, since the file is being copied from the host to the VM (which is about to be destroy) it should not be a fatal error that the file does not exist.

### Vagrant version
Vagrant 1.8.7
I wasn't able to try on Vagrant 1.9.1 due to some dependency issues in my environment. I don't see anything in the changelog that suggests this issue was fixed, but it's possible I missed it.

### Host operating system
macOS Sierra 10.12.3
Ubuntu 12.04

### Guest operating system
Ubuntu 12.04

### Vagrantfile
```ruby
require "vagrant"

Vagrant.configure("2") do |config|

  config.vm.define :test_box do |cfg|
    cfg.vm.box = "hashicorp/precise64"
    cfg.vm.provision :file, run: "always" do |provisioner|
      provisioner.source = "/tmp/origin_test_file"
      provisioner.destination = "/tmp/dest_test_file"
    end
  end
end
```

### Debug output
https://gist.github.com/rtkaheller/af00ad7f3e9d812706b9da888f97f884

### Expected behavior
The vagrant box is destroy as expected.

### Actual behavior
The destroy command fails with:
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

File provisioner:
* File upload source file /tmp/origin_test_file must exist
```

### Steps to reproduce
1. Make sure the file `/tmp/origin_test_file` is present on the host
2. Using the above Vagrantfile, run `vagrant up test_box`
2. Delete `/tmp/origin_test_file` from the host
3. Run `vagrant destroy -f test_box`

**Comment by chrisroberts** [comment]
This is due to the Vagrantfile validation. If the validation fails, then commenting out or removing the provision line will resolve the issue. Cheers!
