### ISSUE TITLE
Please consider code-signing Vagrant and related executables on macOS

### ISSUE THREAD

**Issue by noahwilliamsson** [hashicorp/vagrant#8278]
### Vagrant version

```
$ vagrant -v
Vagrant 1.9.1
```

### Host operating system

```
$ sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1217
```

### Guest operating system

Not relevant.

### Vagrantfile

Not relevant.

### Debug output

```
$ for i in /opt/vagrant/bin/* /opt/vagrant/embedded/bin/*; do codesign -d $i; done
/opt/vagrant/bin/vagrant: code object is not signed at all
/opt/vagrant/embedded/bin/atlas-upload: code object is not signed at all
/opt/vagrant/embedded/bin/bsdcpio: code object is not signed at all
/opt/vagrant/embedded/bin/bsdtar: code object is not signed at all
/opt/vagrant/embedded/bin/c_rehash: code object is not signed at all
/opt/vagrant/embedded/bin/curl: code object is not signed at all
/opt/vagrant/embedded/bin/curl-config: code object is not signed at all
/opt/vagrant/embedded/bin/erb: code object is not signed at all
/opt/vagrant/embedded/bin/gem: code object is not signed at all
/opt/vagrant/embedded/bin/iconv: code object is not signed at all
/opt/vagrant/embedded/bin/irb: code object is not signed at all
/opt/vagrant/embedded/bin/openssl: code object is not signed at all
/opt/vagrant/embedded/bin/rake: code object is not signed at all
/opt/vagrant/embedded/bin/rdoc: code object is not signed at all
/opt/vagrant/embedded/bin/ri: code object is not signed at all
/opt/vagrant/embedded/bin/ruby: code object is not signed at all
/opt/vagrant/embedded/bin/xml2-config: code object is not signed at all
/opt/vagrant/embedded/bin/xmlcatalog: code object is not signed at all
/opt/vagrant/embedded/bin/xmllint: code object is not signed at all
/opt/vagrant/embedded/bin/xslt-config: code object is not signed at all
/opt/vagrant/embedded/bin/xsltproc: code object is not signed at all
```

### Expected behavior

Vagrant executable should be code-signed on macOS.  This would allow users to whitelist the code-signing certificate once and then enjoy upgrades without having to whitelist every executable once again.

### Actual behavior

Vagrant executable are not code-signed at all.  On a system where a binary whitelisting/blacklisting system (e.g. [Google Santa](https://github.com/google/santa)) is running this requires every version of every binary to be whitelisted before it can run.

Here's a screenshot of what happens when attempting to run an executable that has not been whitelisted.

![1-vagrant-google-santa](https://cloud.githubusercontent.com/assets/91926/22863699/9ab34688-f145-11e6-82f2-a180ddea8383.png)

### Steps to reproduce

  1. Install a [recent release](https://github.com/google/santa/releases) of Google Santa.
  2. Switch Santa into [LOCKDOWN mode](https://github.com/google/santa/wiki/Configuration#clientmode) by issuing:

          $ sudo defaults write /var/db/santa/config.plist ClientMode -int 2  # To switch back to MONITOR mode, use '-int 1'

  3. [Download](https://www.vagrantup.com/downloads.html) and install Vagrant.
  4. With Google Santa in LOCKDOWN mode, run Vagrant in the terminal:

          $ vagrant
          -bash: /usr/local/bin/vagrant: Operation not permitted
          
          Santa

          The following application has been blocked from executing
          because its trustworthiness cannot be determined.

          Path:       /opt/vagrant/bin/vagrant
          Identifier: d991f520d014ca48b5e904b7005714cfc1adff75af66ae9d41b64ca2428a3a3a
          Parent:     bash (74394)

  5. Google Santa has blocked the execution of the Vagrant binary.  A quick look with `santactl fileinfo` gives:

          $ santactl fileinfo /opt/vagrant/bin/vagrant
          Path                 : /opt/vagrant/bin/vagrant
          SHA-256              : d991f520d014ca48b5e904b7005714cfc1adff75af66ae9d41b64ca2428a3a3a
          SHA-1                : 0c01693fd05ba5fb1da45d2d4a612e784d0d7059
          Type                 : Executable (x86-64)
          Code-signed          : No
          Rule                 : Blacklisted (Unknown)

  6. Whitelist the Vagrant executable manually.

          $ sudo santactl rule --whitelist --path /opt/vagrant/bin/vagrant
          Added rule for SHA-256: d991f520d014ca48b5e904b7005714cfc1adff75af66ae9d41b64ca2428a3a3a.
          $ santactl fileinfo /opt/vagrant/bin/vagrant
          Path                 : /opt/vagrant/bin/vagrant
          SHA-256              : d991f520d014ca48b5e904b7005714cfc1adff75af66ae9d41b64ca2428a3a3a
          SHA-1                : 0c01693fd05ba5fb1da45d2d4a612e784d0d7059
          Type                 : Executable (x86-64)
          Code-signed          : No
          Rule                 : Whitelisted (Binary)

  7. An attempt to run Vagrant again now makes Santa complain about more executables.

          $ vagrant
          Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: operation not permitted
          
          Santa
 
          The following application has been blocked from executing
          because its trustworthiness cannot be determined.
 
          Path:       /opt/vagrant/embedded/bin/ruby
          Identifier: a5a437ac778fe6162c51805f80d534618ea96e3bb135e6d3a5359fdb53ab6e04
          Parent:     vagrant (74453)

  8. Workaround this issue by whitelisting all binaries below `/opt/vagrant/embedded/bin/`
  9. When a new version of Vagrant is released you'll have to repeat all the whitelistning again (because they are not code-signed with a certificate that could have been whitelisted just once)
  10. Undo step 2 to reset your environment.

          $ sudo defaults delete /var/db/santa/config.plist ClientMode

### References

- https://github.com/google/santa
- https://github.com/google/santa/wiki
- https://github.com/drduh/macOS-Security-and-Privacy-Guide#binary-whitelisting

**Comment by arubdesu** [comment]
This is unrelated to the recent build system issue where an install package was posted without being signed, we understand that was a hiccup.
I know Vagrant is vendor'ing dependencies that carry various open source licenses, but once you ship the whole bundle all executable components, you 'own' it according to customers - it really should be code signed by Hashicorp. I've opened tickets with [Puppet](https://tickets.puppetlabs.com/browse/PA-519) along the same lines. 
Apple is showing their hand with System Integrity Protection, which means it could be MORE reliable to target interpreters in protected/restricted directories, but I understand the cross-platform nature of Vagrant would make tracking/supporting a specific interpreter across multiple releases of one OS a pain. The plus side of this is you're already vendoring most things and therefore don't need to rely on whatever ancient/obscure Apple-patched version of openssl they're building Ruby with... 😅 
You'd therefore need to get the specific DeveloperID designation for Mac Apps with Apple and the associated code signing cert, and make it available to your build system.

**Comment by briancain** [comment]
Hey all! It looks like this issue was missed when we implemented it, but Vagrant now follows the release process required for the latest macOS Catalina. Thanks again for your report!
