### ISSUE TITLE
There was an error while executing 'VBoxManage'

### ISSUE THREAD

**Issue by cducrest** [hashicorp/vagrant#8293]
Hello, I have just installed the latest versions of VirtualBox and Vagrant for a univeristy exercise, I had to download some "provisionning.yml" and "Vagrantfile" from my univsersity. Then when I do Vagrant up, I have this error: "Stderr: VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole". I have tried switching versions of VirtualBox, using the command prompt as an admin, different things I found on the internet, and even switching laptop but the error seems to persist. If you have any idea on how to help that would be really appreciated. I hope I provide enough information below.

Thank you very much.

### Vagrant version
Vagrant 1.9.1

### Host operating system
Windows 10

### Guest operating system
Ubuntu

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "box-cutter/ubuntu1404-desktop"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end

  # Shared folder
  config.vm.synced_folder "Assignments", "/home/vagrant/assignments", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=664"]

  # Prepare for ansible 
  config.vm.provision "shell", inline: "sudo sed -i.old s#us\.archive\.ubuntu\.com#ftp.snt.utwente.nl/pub/os/linux#g /etc/apt/sources.list"
  config.vm.provision "shell", inline: "sudo apt-add-repository -y ppa:ansible/ansible"
  config.vm.provision "shell", inline: "sudo apt-get update"
 
  config.vm.provision "shell", inline: "sudo apt-get install -y python-pip python-dev ansible" 
  config.vm.provision :shell, inline: <<-SCRIPT
  GALAXY=/usr/local/bin/ansible-galaxy
  echo '#!/usr/bin/env bash
  /usr/bin/ansible-galaxy "$@"
  exit 0
  ' | sudo tee $GALAXY
  sudo chmod 0755 $GALAXY
  SCRIPT

  # Run ansible provisioning script
  config.vm.provision "ansible_local" do |ansible|
    ansible.install = false
    ansible.playbook = "provisioning.yml"
  end
end
```

### Debug output
https://gist.github.com/cducrest/8fc9cd922aa81f0f7fa15792140cb3c1

**Comment by chrisroberts** [comment]
Hi! I have been unable to reproduce this error. Using a fresh windows 10 installation with virtualbox 5.1.14 I have not had any issues bringing the VM up. Does your host machine have virtualization enabled? Can you create a virtual machine manually via the virtualbox GUI?

**Comment by cducrest** [comment]
Yes virtualization is enabled and I can create a virtual machine via the virtualbox GUI.

**Comment by chrisroberts** [comment]
I have attempted to reproduce this locally with a couple different versions of virtualbox and have been unsuccessful. Are you still experiencing this issue? If so, can you remove the installed box and try again:

```
$ vagrant box remove box-cutter/ubuntu1404-desktop
$ vagrant up
```

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
