### ISSUE TITLE
Admin requirements for VMWare on Windows are too strict

### ISSUE THREAD

**Issue by kylemacfarlane** [hashicorp/vagrant#8305]
I can understand why vagrant needs admin to up/reload/etc but why to ssh in? This makes it more difficult to use `vagrant ssh` from other places (e.g. a terminal inside Vim).

It's perfectly possible to login without admin using `ssh -i ./vagrant/... 192...` so why does Vagrant block `vagrant ssh`?

I also wonder if admin is needed for any commands if `vmnetnat.conf` has the proper permissions?

**Comment by lqbweb** [comment]
agree, in our scenario, we are running vagrant from a build server, and obviously not from an admin account. There should be some sort of vagrant server running on the admin account that performs the changes needed. I think I will have to do this myself now.

**Comment by chrisroberts** [comment]
Hi there,

This has been resolved with the new Vagrant VMware Desktop plugin. More information can be found here:

https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

Cheers!
