### ISSUE TITLE
Change name of network interface with `private_network`

### ISSUE THREAD

**Issue by arvenil** [hashicorp/vagrant#8322]
How to assign custom name for network interface while using `private_network` with `dhcp`?

I'm trying to build multi-machine Vagrantfile with docker swarm without using static IPs in Vagrantfile.

It is done by creating docker manager (1 machine) and later connecting to it docker workers (n machines) by using IP address. So I need to get IP address of the manager box and pass it to worker boxes.

One way to achieve that would be to query ifconfig for IP address ([like docs suggest](https://www.vagrantup.com/docs/networking/private_network.html#dhcp)) and store it for later use. This could be done with hacky command `ifconfig #{$interface} | awk '/(cast)/ {print $2}' | cut -d: -f2 > /vagrant/manager_ip` (or maybe there is better way to get IP address?).

The problem is that network interface name doesn't seem to be predictable. Currently it's name is `enp0s8` but I would like to know how to change it within Vagrantfile to something constant?

### Vagrant version
Vagrant 1.9.1

### Host operating system
macOS

### Guest operating system
minimal/xenial64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

$nodes = 2

# How to make below a constant?
$interface = "enp0s8"

Vagrant.configure("2") do |config|
  config.vm.box = "minimal/xenial64"
  config.vm.provision :docker

  config.vm.network "private_network",
    type: "dhcp"

  config.vm.define "manager" do |config|
    config.vm.hostname = "manager"
    config.vm.provision "shell", inline: <<-SHELL
        ifconfig #{$interface} | awk '/(cast)/ {print $2}' | cut -d: -f2 > /vagrant/manager_ip
        docker swarm init --advertise-addr $(cat /vagrant/manager_ip)
        docker swarm join-token -q worker > /vagrant/worker_token
    SHELL
  end

  $nodes.times do |n|
    config.vm.define "node-#{n}" do |config|
      config.vm.hostname = "node-#{n}"
      config.vm.provision "shell", inline: <<-SHELL
          docker swarm join --token=$(cat /vagrant/worker_token) $(cat /vagrant/manager_ip):2377
      SHELL
    end
  end
end
```

ifconfig
```
$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:9d:98:6f:62
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

enp0s3    Link encap:Ethernet  HWaddr 08:00:27:42:0e:40
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe42:e40/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:127092 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11417 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:173521866 (173.5 MB)  TX bytes:817766 (817.7 KB)

enp0s8    Link encap:Ethernet  HWaddr 08:00:27:2d:da:c4
          inet6 addr: fe80::a00:27ff:fe2d:dac4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:35 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:9882 (9.8 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Comment by ahammond** [comment]
I have a similar challenge around using Vagrant to test a dnsmasq dhcp server setup. I need to know what interface is hosting what networks. Ideally, I just want to configure the interface name statically.

**Comment by GregJPreece** [comment]
While it's still pretty hacky, this works on Ubuntu as a workaround:

`INTERFACE="$(ls --ignore='lo' /sys/class/net)"`
`IP_ADDR="$(ifconfig ${INTERFACE} | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')"`

I'm using this to auto-generate SSL certs on provision, might work OK for you until Vagrant has something better.

**Comment by ahammond** [comment]
`ifconfig` is oldschool. `IP_ADDR=$(ip -oneline addr list $INTERFACE |  ...`

**Comment by chrisroberts** [comment]
Old style device naming can be done via configuration settings, usually when building the guest box. You can find more information about using the old style naming here: https://access.redhat.com/discussions/916973

Cheers!
