### ISSUE TITLE
Vagrant docker-exec output improvement

### ISSUE THREAD

**Issue by kamilszewczyk** [hashicorp/vagrant#8361]
This is a improvement to the way of docker-exec command output.
Running standard docker exec command on exisiting container on long running script produces a nice output while the command is running giving a way to follow the progress of command.
Running the same script using vagrant docker-exec is showing the whole output at the end of script run giving really bad user experience.
Is it possible to show the output from long running script while they're executing?

### Guest operating system
boot2docker

### Test script
```bash
#!/bin/bash

sleep 1
echo "1"
sleep 1
echo "2"
sleep 1
echo "3"
sleep 1
echo "4"
sleep 1
echo "5"
```

### Expected behavior
Running test script, numbers from 1 to 5 should appear in output in 1 seconds interval

### Actual behavior
The script is run on docker, and then the whole output is presented

### Steps to reproduce
1. Put a test script on docker container
2. Run vagrant docker-exec [name] -- /path/to/test/script.sh

**Comment by kikitux** [comment]
@kamilszewczyk 

Added the labels for this.

The code is here:

https://github.com/mitchellh/vagrant/blob/9c299a2a357fcf87f356bb9d56e18a037a53d138/plugins/providers/docker/command/exec.rb#L98

Pull Request are very welcome as may take some time to get to this enhancement.

Alvaro

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
