### ISSUE TITLE
Documentation lists incorrect values for config.winrm.transport

### ISSUE THREAD

**Issue by dummptyhummpty** [hashicorp/vagrant#8365]
### Vagrant version
1.9.2

### Host operating system
Windows 10

### Guest operating system
Windows 2012 R2

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.vm.box = "win2012r2"
  config.vm.box_url = "win2012r2.box"
  config.vm.communicator = "winrm"
  config.vm.guest = :windows
  config.winrm.transport = ssl
  end

end
```

### Expected behavior
The documentation for config.winrm.transport lists valid settings as ":negotiate, ssl and :plaintext". I'd expect "ssl" to use SSL to connect to WinRM over host port 55986 (mapped to guest port 5986).

### Actual behavior
Vagrant attempts to use SSL to connect to WinRM, but uses host port 55985 (mapped to guest port 5985). It appears that the correct value is actually ":ssl" and not "ssl" as stated in the documentation. Using ":ssl", Vagrant uses SSL on the correct port (55986).

### Steps to reproduce
1. Set config.winrm.transport to ssl in Vagrantfile

**Comment by kikitux** [comment]
@ummptyhummpty 

So how a good Vagrantfile looks like?

**Comment by dummptyhummpty** [comment]
@kikitux This works:

`Vagrant.configure("2") do |config|

  config.vm.box = "win2012r2"
  config.vm.box_url = "win2012r2.box"
  config.vm.communicator = "winrm"
  config.vm.guest = :windows
  config.winrm.transport = :ssl
  end

end`
