### ISSUE TITLE
vagrant-nfs tries to use init.d on NixOS

### ISSUE THREAD

**Issue by ghost** [hashicorp/vagrant#8430]
### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
NixOS

### Guest operating system
CentOS

### Vagrantfile
```ruby
begin
	gem "puppet"
	gem "vagrant-r10k"
rescue Gem::LoadError
	raise "Some plugins are missing. Check the Vagrantfile for a list of "\
		"requirements."
end

Vagrant.configure("2") do |config|
	config.vm.box = "puppetlabs/centos-6.6-64-puppet"
	config.vm.network "private_network", type: "dhcp"
	config.vm.synced_folder "~/usr/devel/********", "/home/vagrant/usr/devel",
		nfs: true
	config.vm.provider "virtualbox" do |vb|
		# TODO: Add virtual machine optimisations here
	end

	config.r10k.puppet_dir = "environments/default"
	config.r10k.puppetfile_path = "environments/default/Puppetfile"
	config.r10k.module_path = "environments/default/modules"

	config.ssh.forward_agent = true

	config.vm.provision "puppet" do |puppet|
		puppet.environment_path = "environments"
		puppet.environment = "default"
	end
end

# vim: set ft=ruby ts=4 sw=4:
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Debug output to come.

### Expected behavior
NFS server interface is systemctl

### Actual behavior
NFS fails looking for /etc/init.d/nfs-kernel-server

### Steps to reproduce
1. Run NixOS (can provide `configuration.nix` if needed)
2. Try to use NFS shares on Vagrant

**Comment by sphaugh** [comment]
https://gist.github.com/cc07686cf07e142f1f8927b75931e3be

**Comment by sphaugh** [comment]
I think there may be a helper script that isn't running, since doing 

```
exportfs -a
vagrant reload
vagrant provision
```
fixes my problem.

**Comment by chrisroberts** [comment]
This should be resolved in current versions of Vagrant as the nfs guest and host support has received multiple related updates. If you still encounter this issue after upgrading to the latest version, please open a new issue and I will investigate further.

Cheers!
