### ISSUE TITLE
vagrant port <id> throws error but Vagrantfile successfully mapped ports using ENV["var"]

### ISSUE THREAD

**Issue by Jovonni** [hashicorp/vagrant#8431]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.9.3

### Host operating system
Mac 10.11.6 El Captain

### Guest operating system
cbumgard/nodejs

### Vagrantfile
```ruby
#!/usr/bin/ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  puts "Vagrantfile Unit 1"
  puts ENV["PORTENV1"]
  config.vm.box = "cbumgard/nodejs"
  config.vm.provider :virtualbox do |vb|
        vb.name = "unit_1"
  end

  config.vm.provision "shell", inline: "touch /$1", args: ENV['PORTENV1']
  config.vm.network :forwarded_port, guest: 22, host: 2222, host_ip: "0.0.0.0", id: "ssh", auto_correct: true
  config.ssh.forward_agent = true
  config.vm.network :forwarded_port, guest: ENV['PORTENV1'], host: ENV['PORTENV1'], auto_correct: true

end



```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Expected behavior
What should have happened?
vagrant port <id> should return the port, and relevant information.

### Actual behavior
What actually happened?
Vagrantfile Unit 1

There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* Forwarded port definitions require a "host" and "guest" value
* Ports to forward must be 1 to 65535

### Steps to reproduce
export PORTENV1='3001'
PORTENV1='3001' vagrant provision
vagrant up
vagrant global-status ## get relevant id
vagrant port <vmid>

### References
No references

### Extra information
So, I can validate that the PORTENV1 is actually set, however vagrant is NOT registering the port information, and throws the error. However, I see many people accomplishing it this way. I don't want to have to hardcode the port to forward. 

Even more interestingly, I notice that the ports are SUCCESSFULLY FORWARDED & REGISTERED....

However the vagrant port <id> command throws that command.... any ideas?

**Comment by chrisroberts** [comment]
This appears to be an issue where, when running the `vagrant port` the environment variable is not set. When Vagrant attempts to read the project Vagrantfile, the error is generated due to the value being empty. Having the port value properly set within the environment will resolve this issue. 

Cheers!
