### ISSUE TITLE
WinRMShell not using IP address output to console. Failing to connect.

### ISSUE THREAD

**Issue by kmacphee** [hashicorp/vagrant#8435]
### Vagrant version
1.9.2

### Host operating system
Windows 10 (Anniversary Update)

### Guest operating system
Windows Server 2016 (Hyper-V provider)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "WindowsServer2016"
  config.vm.communicator = "winrm"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.winrm.username = "Administrator"
  config.winrm.password = "vagrant"
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true
  
  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "windows_file_server"
	chef.cookbooks_path = "vendor"
  end
end
```

### Debug output
https://gist.github.com/kmacphee/43454d91362bcadf5ad1a9f9dbb80761

### Expected behavior
The first valid IP address Vagrant finds in the debug log is actually the correct one:

DEBUG subprocess: stdout: ===Begin-Output===
{
    "ip":  "fe80::f426:3626:b5fb:679c"
}

If WinRMShell connected to that address it should work. I've run Test-WSMan on it once the machine boots. 

### Actual behavior
Unfortunately, for some reason Vagrant retries obtaining the IP address and picks up an address in the "limited or no connectivity" range.

DEBUG subprocess: stdout: ===Begin-Output===
{
    "ip":  "169.254.103.156"
}

I assume the Windows guest VM is messing about with the network configuration on boot, maybe something DHCP related. By the time I can check 'ipconfig' on the guest it has the IPv6 address that Vagrant reports the first time. Unfortunately Vagrant never retries reading the IP address after picking up the 169.* one. It gets stuck in a loop trying to connect to that. It times out after a couple of minutes.

The original "WinRM address:" that gets output to the shell is the correct one ("fe80::f426:3626:b5fb:679c"), so it picking up a completely different (invalid) address under the hood makes it a little difficult to troubleshoot.

### Steps to reproduce
For me, I only need to 'vagrant up' to reproduce it.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
