### ISSUE TITLE
Permission denied issue after setup

### ISSUE THREAD

**Issue by aswinfrancis91** [hashicorp/vagrant#8459]
I am not able to run vagrant from cmd or git bash. The issue is really weird. I installed 1.9.3 and after the restart, i would always get access denied issue from cmd even when I run it as admin. I search online and found one post asking me to use 1.8.5. That also initially didn't work. I did an uninstall clean temp files and clean registry and did do the required restart. I went ahead and installed 1.8.5. Didn't restart when it asked me to. Then I open cmd and type vagrant -h, I get the help text. Then I go to my directory and enter vagrant add box it shows permission denied and the exe itself gets removed from the vagrant's bin folder :|

I tried to enable debug but the same thing happens. I get access denied and the exe files gets removed from the bin folder

### Vagrant version
1.8.5 and 1.9.3

### Host operating system
Windows 10 Pro

### Guest operating system
Windows 10 Pro

### Debug output
Cannot debug

### Expected behavior
After installation system asks for restart, after restart if I try any vagrant command, for eg: vagrant -h, it will show command details

### Actual behavior
After installation system asks for restart, after restart if I try any vagrant command, for eg: vagrant -h, it will show access denied in cmd or permission denied in git bash

### Steps to reproduce
1. Mentioned at first

### References
https://stackoverflow.com/questions/29253578/vagrant-access-is-denied

**Comment by aswinfrancis91** [comment]
I got the below error after following the steps mentioned in the stackover flow page:
C:/Users/afrancis/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': File exists @ dir_s_mkdir - C:/Users/afrancis/Vagrant/bin/vagrant.exe (Errno::EEXIST)
        from C:/Users/afrancis/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
        from C:/Users/afrancis/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
        from C:/Users/afrancis/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
        from C:/Users/afrancis/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
        from C:/Users/afrancis/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:210:in `each'
        from C:/Users/afrancis/Vagrant/embedded/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
        from C:/Users/afrancis/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:771:in `block in setup_home_path'
        from C:/Users/afrancis/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:766:in `each'
        from C:/Users/afrancis/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:766:in `setup_home_path'
        from C:/Users/afrancis/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:129:in `initialize'
        from C:/Users/afrancis/Vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:165:in `new'
        from C:/Users/afrancis/Vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:165:in `<main>'

**Comment by chrisroberts** [comment]
Hi there,

If this is the command that you ran:

```
setx VAGRANT_HOME "D:\your\path\vagrant.exe"
```

it will cause the error you experienced above. The `VAGRANT_HOME` environment variable provides the path to a directory for Vagrant to store information. From the error above, it looks like you used `C:/Users/afrancis/Vagrant/bin/vagrant.exe` which may be an actual file. Change the value used to a valid directory path. For example:

```
setx VAGRANT_HOME "C:\Users\afrancis\.vagrant.d"
```

and see if that fixes the issue for you. Cheers!

**Comment by aswinfrancis91** [comment]
![image](https://cloud.githubusercontent.com/assets/1233653/24901276/30b4aa4a-1ec4-11e7-909d-ba2772276de0.png)

**Comment by chrisroberts** [comment]
@aswinfrancis91 In your last comment, which version of Vagrant did you have installed?

**Comment by aswinfrancis91** [comment]
1.8.5. That is the only version where vagrant command at least runs. 

⁣Sent from BlueMail ​

**Comment by briancain** [comment]
@aswinfrancis91 do you still encounter this problem if you install the latest version of Vagrant?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
