### ISSUE TITLE
Win10 Vmware Workstation 12 fails on enableSharedFolders command

### ISSUE THREAD

**Issue by fritz-gerneth** [hashicorp/vagrant#8461]
### Vagrant version
Vagrant 1.9.3
vagrant-berkshelf (5.1.1)
  - Version Constraint: > 0
vagrant-omnibus (1.5.0)
  - Version Constraint: > 0
vagrant-share (1.1.7)
  - Version Constraint: > 0
vagrant-vmware-workstation (4.0.18)

### Host operating system
Win10, VMware Workstation 12.5.5 build-5234757

### Guest operating system
Tried with quite a few boxes:
- Centos/7
-  bento/centos-7.3 
- puphpet/ubuntu1404-x64 (v20151128 and current)
-  puphpet/centos65-x64 
-  puphpet/centos7-x64
-  puphpet/ubuntu1604-x64

### Debug output
- VMWare log / Vagrant file: https://gist.github.com/fritz-gerneth/d142c38857a5ec087a8ef49b07a8ab12

### Expected behavior
- No error, shared folders mounted

### Actual behavior
- Vagrant up fails with error:
```
==> public: Waiting for HGFS to become available...
==> public: Enabling and configuring shared folders...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "C:/Users/Fritz Gerneth/Documents/Projects/puphpet/.vagrant/machines/public/vmware_workstation/85663c32-fc1d-4311-9741-0304e42b6132/ubuntu-14.04-amd64.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

Stderr:
```

This happens consistently with all boxes tried with the same error message after an upgrade of vagrant and VMware workstation (same error, same log). 
For the outdated box puphpet/ubuntu1404-x64 (v20151128) everything works fine.  Prior to upgrade I've been using VMware v11.x and vagrant v1.18.5 without any issues (with the old box).

**Comment by chrisroberts** [comment]
@fritz-gerneth Hi there. My guess is that it may be due to the space in the path. I'm going to be reproducing the behavior locally to confirm and will get a fix applied shortly if that is the case. Cheers!

**Comment by fritz-gerneth** [comment]
To keep this updated with my current progress:
- I'm now in a state where the initial `up` succeeds about 20% of the time ( [recent log](https://gist.github.com/fritz-gerneth/39269f91c710f2d5eb761afeb4863d90)
- Later `up`s seem to work with no issue
- Same config for virtualbox is working without any issue

**Comment by fritz-gerneth** [comment]
This still happens for me with the most recent version of Vagrant (1.9.5) & VMware (12.5.6). Also happening with no spaces in the path.

**Comment by chrisroberts** [comment]
I believe this happens when vmware is attempting to automatically upgrade the vmtools on the guest when first booted. Adding the following configuration to my Vagrantfile (and in turn including in my packer templates) has stopped it from occurring:

```ruby
Vagrant.configure("2") do |config|
  config.vm.provider "vmware_fusion" do |vmware|
    vmware.vmx["tools.upgrade.policy"] = "manual"
  end
end
```

Cheers!
