### ISSUE TITLE
VMware machines are not listed in VMware Fusion library (mac)

### ISSUE THREAD

**Issue by terion-name** [hashicorp/vagrant#8466]
I was previously using vagrant with virtualbox. With it all provisioned vagrant VMs were added to list in virtualbox app — it was convenient to see them all in one place and see what machines are running.
Now I've switched to VMware — and this behaviour is not repeating: when I open vm library (the vmware app) I see only machines that were imported explicity, and no vagrant machines, even that are running now.
Is there a way to bring that virtualbox behaviour to vmware provider?

**Comment by fsvehla** [comment]
Any update here?

**Comment by chrisroberts** [comment]
Enabling the `gui` option will add it to the library list, but it is currently not removed when the guest is destroyed via Vagrant.

https://www.vagrantup.com/docs/vmware/configuration.html#gui

**Comment by chrisroberts** [comment]
There is no way for us currently to affect the display within the VMware GUI with regards to the existence or removal of virtual machines. If the support gets introduced we will revisit this issue and include support for automatic addition and removal.

Cheers
