### ISSUE TITLE
Stale file handle after sleep with NFS on macOS

### ISSUE THREAD

**Issue by plowman** [hashicorp/vagrant#8496]
### Vagrant version
1.9.3

### Host operating system
macOS Sierra 10.12.4

### Guest operating system
Ubuntu 16.04.1 LTS
Running via VirtualBox 5.1.18

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mybox"
  config.vm.box_url = "https://storage.googleapis.com/fake_path/images/vagrant/mybox.json"

  # Allow us to see the local project instance
  config.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true

  # Surface the index server
  config.vm.network :forwarded_port, guest: 8081, host: 8081, auto_correct: true

  # Configure virtualbox
  config.vm.provider "virtualbox" do |v|
    config.vm.network "private_network", type: "dhcp"

    v.memory = 4096
    v.cpus = 7
    v.name = "mybox"
  end

  # Configure vmware_fusion
  config.vm.provider "vmware_fusion" do |v|
    v.memory = 4096
    v.cpus = 7
    v.name = "mybox"
  end

  config.vm.hostname = "mybox"

  # copy mybox clone of project3 into the vagrant instance
  config.vm.synced_folder ".", "/project/project3", type: "nfs"

  # make ssh keys work
  config.vm.synced_folder "~/.ssh", "/home/vagrant/.ssh_host", type: "nfs"

end

if not Vagrant.has_plugin?("vagrant-bindfs")
    puts "Install vagrant-bindfs to avoid permissions issues with the host OS:\n\n\tvagrant plugin install vagrant-bindfs\n\n"
    exit 1
end
```

### Debug output
**Output when it works properly:**
https://gist.github.com/plowman/1ffb1acfe8568609d475bdcd1ed57aef
**Output when it fails to work:**
https://gist.github.com/plowman/5a5b7e16b0131c2b8f5050363a0c06b7

### Expected behavior
After running `vagrant ssh` the files in the /project/project3 directory should be mounted via NFS and should be fully accessible.

### Actual behavior
Trying to access any of the files in /project/project3 directory results in the error: `Stale file handle`

The juicy bit in the logs appears to be this:
```
INFO interface: error: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 172.28.128.1:/project/project3 /project/project3

Stdout from the command:

Stderr from the command:

mount.nfs: access denied by server while mounting 172.28.128.1:/project/project3
```

### Steps to reproduce
1. Run `vagrant up`
2. `vagrant ssh` into the machine
3. Let my computer go to sleep for a few minutes.
4. When the computer resumes, any command which interacts with the hosted files will fail. For example, `ls -al /project/project3` will return `ls: cannot open directory '/project/project3': Input/output error`.
5. `cd /project/project3` will return `cd: /project/project3: Stale file handle`.

**Comment by plowman** [comment]
Fyi, just added a second vagrant.log file to the description above for when `vagrant up` happens and the mount fails, along with the part of the log that seems to describe this issue:
```
mount -o vers=3,udp 172.28.128.1:/project/project3 /project/project3

Stdout from the command:

Stderr from the command:

mount.nfs: access denied by server while mounting 172.28.128.1:/project/project3
```

**Comment by plowman** [comment]
I now have a theory on why this is happening. My coworker ran into the same problem with this error:
```
mesg: ttyname failed: Inappropriate ioctl for device
mount.nfs: access denied by server while mounting 172.28.128.1:/Users/username/src/project3
```

Output of `VBoxManage guestproperty enumerate gbox | grep IP`, i.e. the IP addresses being used by this VirtualBox:
```
Name: /VirtualBox/GuestInfo/Net/0/V4/IP, value: 10.0.2.15, timestamp: 1493410155031275000, flags:
Name: /VirtualBox/GuestInfo/Net/2/V4/IP, value: 172.28.128.4, timestamp: 1493410160032158000, flags:
Name: /VirtualBox/GuestInfo/Net/1/V4/IP, value: 172.28.128.3, timestamp: 1493410160031425000, flags:
```

Output of `cat /etc/exports`, i.e. where the nfs mounts are currently located:
```
# VAGRANT-BEGIN: 501 4e8ab904-c376-4607-a4d7-c14ce24bfa8c
"/Users/username/.ssh" 172.28.128.4 -alldirs -mapall=501:20
"/Users/username/src/project3" 172.28.128.4 -alldirs -mapall=501:20
# VAGRANT-END: 501 4e8ab904-c376-4607-a4d7-c14ce24bfa8c
```

## Possible problem
* The initial error references the IP `172.28.128.1`. However, that IP is not exposed by VirtualBox, nor does /etc/exports show that IP as one of the places where the files are exported.
* Since the network is setup using DHCP, i.e. `config.vm.network "private_network", type: "dhcp"`, it appears that when the IP changes, mount.nfs tries an IP that neither virtualbox or the host machine is expecting.

## Workaround
* Hardcoding the IP address appears to fix this issue. So in the above example, replacing this line:
    > config.vm.network "private_network", type: "dhcp"

  With this one:
    > config.vm.network "private_network", ip: "172.28.128.5"

**Comment by medmek** [comment]
> I now have a theory on why this is happening. My coworker ran into the same problem with this error:
> 
> ```
> mesg: ttyname failed: Inappropriate ioctl for device
> mount.nfs: access denied by server while mounting 172.28.128.1:/Users/username/src/project3
> ```
> Output of `VBoxManage guestproperty enumerate gbox | grep IP`, i.e. the IP addresses being used by this VirtualBox:
> 
> ```
> Name: /VirtualBox/GuestInfo/Net/0/V4/IP, value: 10.0.2.15, timestamp: 1493410155031275000, flags:
> Name: /VirtualBox/GuestInfo/Net/2/V4/IP, value: 172.28.128.4, timestamp: 1493410160032158000, flags:
> Name: /VirtualBox/GuestInfo/Net/1/V4/IP, value: 172.28.128.3, timestamp: 1493410160031425000, flags:
> ```
> Output of `cat /etc/exports`, i.e. where the nfs mounts are currently located:
> 
> ```
> # VAGRANT-BEGIN: 501 4e8ab904-c376-4607-a4d7-c14ce24bfa8c
> "/Users/username/.ssh" 172.28.128.4 -alldirs -mapall=501:20
> "/Users/username/src/project3" 172.28.128.4 -alldirs -mapall=501:20
> # VAGRANT-END: 501 4e8ab904-c376-4607-a4d7-c14ce24bfa8c
> ```
> ## Possible problem
> * The initial error references the IP `172.28.128.1`. However, that IP is not exposed by VirtualBox, nor does /etc/exports show that IP as one of the places where the files are exported.
> * Since the network is setup using DHCP, i.e. `config.vm.network "private_network", type: "dhcp"`, it appears that when the IP changes, mount.nfs tries an IP that neither virtualbox or the host machine is expecting.
> 
> ## Workaround
> * Hardcoding the IP address appears to fix this issue. So in the above example, replacing this line:
>   > config.vm.network "private_network", type: "dhcp"
>   
>   
>   With this one:
>   > config.vm.network "private_network", ip: "172.28.128.5"

Hello and thanks for the solution. In my case this was already done, and i still got it from time to time, and especially while using Gitkraken, I don't really know if he's the culprit though 

Cheers
(using Windows 10, NFS, winnfsd & bindfs plugin)

**Comment by chrisroberts** [comment]
Hi there. This appears to be an issue with the network resetting on the guest and requesting a new IP address. A private network with a static IP should resolve the issue.

Cheers.
