### ISSUE TITLE
Vagrant smb sets permission of everyone to full control

### ISSUE THREAD

**Issue by DrowningElysium** [hashicorp/vagrant#8522]
Vagrant: 1.9.3

I have just installed homestead on Hyper-V and set it up to use smb to set the share for the site.
The problem is I have to work on public WIFI as there is no private network.
In my opinion the network shares should be set up so that only the user account that sets up the share should be able to have any permissions to that share.

If there is any additional information needed, please request it as I am not able to see what information I should provide for this.

Edit:
I tried changing the permissions to my computer user only and vagrant just returns them to Everyone has Full control

**Comment by gitttt** [comment]
Same for me. I have a Windows 7 host and a Windows 2016 Server guest. The share on the Windows 7 host is accessible to everyone. As @DrowningElysium  I manually removed this and restricted the permissions to my user account (the same that I provide user name and password for when doing a vagrant up). The configuration seems to work until I do another vagrant up. Then everything is reset and "everyone" as access again to the shared folder on my host. 

This is a severe security concern.

**Comment by fsackur** [comment]
Hi,

Setting SMB share permissions to "Full" for "Everyone": this is best practice for fileshares on WIndows on NTFS volumes (and likely for any OS on any modern filesystem). NTFS is a much better option for permissioning than SMB.

SMB permissions and underlying filesystem permissions are cumulative. A share with Everyone,Full does not grant access unless the connecting user also has permissions at the NTFS level. If your folder on disk has wide-open permissions, then fix that problem. (This is unlikely unless you have explictly set it as so.) 

You can check with Get-Acl or ICACLS. Look for permissions granted to "Everyone" at that level. If you don't see them, you don't have a problem.

As a question, do you have a firewall on when you're on wifi? Just a thought.

This is a non-issue, AFAICS.

**Comment by chrisroberts** [comment]
After digging into this some more I'm going to agree with @fsackur assessment above (https://github.com/hashicorp/vagrant/issues/8522#issuecomment-458568014) and close this up. Cheers!
