### ISSUE TITLE
VirtualBox internal networks do not respect :use_dhcp_assigned_default_route

### ISSUE THREAD

**Issue by csfeathers** [hashicorp/vagrant#8591]
The VirtualBox provider in `intnet` mode doesn't pass through `:use_dhcp_assigned_default_route` to the template renderer. It therefore always renders the corresponding `false` branch in the template. The option is however documented for `private_networks` too.

We hit this issue after trying to take advantage of the bugfix in GH-8575.

The function `bridged_network_config` has special cased handling of this option in its `type: :dhcp` branch that is missing in `intnet_network_config` and `hostonly_network_config`.

After reading through https://github.com/mitchellh/vagrant/blob/master/plugins/providers/virtualbox/action/network.rb I'm generally a little concerned about some of those functions silently dropping settings from the config hash. For example, `:gateway` is templated in `network_static.erb` but is not consistently passed through to the template renderer either. But maybe that's a separate issue?

### Vagrant version
Vagrant 1.9.5

### Host operating system
Windows 7

### Guest operating system
Ubuntu 16.04 Server x64

### Steps to reproduce
1. Set up a VirtualBox internal network (preferably with a DHCP server and a gateway)
2. Configure a `private_network` with `:type = 'dhcp'` on an Ubuntu box
3. `vagrant up && vagrant ssh`
4. `cat /etc/network/interfaces`

### References
- GH-8575

**Comment by kikitux** [comment]
@csfeathers 

please update to latest vagrant and try again

if fail, please share a minimal Vagrantfile to reproduce the issue

Thanks
