### ISSUE TITLE
vagrant up hangs at `Acquired process lock: machine-action...`

### ISSUE THREAD

**Issue by hcguersoy** [hashicorp/vagrant#8592]
### Vagrant version
```$ vagrant -v
Vagrant 1.9.5
```

Update 2: Downgrading Vagrant to 1.8.7 everything works fine together with VBox 5.1.22r115126

### Host operating system
MacOS 10.12.5

VirtualBox:
```
$ VBoxManage --version
5.1.22r115126
```
Update: Downgraded to VirtualBox `5.0.38r114633` but same behaviour.

### Guest operating system
Tried with `centos/7`, `hashicorp/precise32` and `ubuntu/trusty64`

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
end
```

### Debug output
see [https://gist.github.com/hcguersoy/678d6a1df8a7aab6adb1ec661532a884](https://gist.github.com/hcguersoy/678d6a1df8a7aab6adb1ec661532a884)

### Expected behaviour
A VM should be created in Virtualbox and started up.

### Actual behaviour
`vagrant up` hangs simply at the step
```
DEBUG environment: Attempting to acquire process-lock: machine-action-60dbf4371ca883950272eca45903fc1a
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-60dbf4371ca883950272eca45903fc1a
```

until I stop the vagrant process (CMD & C).

### Steps to reproduce
1. vagrant init ubuntu/trusty64
2. vagrant up

### References
none

**Comment by casperWWW** [comment]
Have the same problem. Does anybody know how to fix this?

**Comment by tocas** [comment]
I had same problem. Downgrade to 1.9.4 help. So looks like it's broken by latest release 1.9.5.

**Comment by JPrevost** [comment]
I ran the uninstall tool and then reinstalled after having this issue and it seems okay on 1.9.5 now.

**Comment by attluh** [comment]
I experienced this today with a fresh install of 1.9.5 and had to downgrade to 1.9.4.

**Comment by naikajah** [comment]
I had the same issue with vagrant 1.9.7.
I then installed 1.8.7 version and then I encountered a different error related to 
https://github.com/mitchellh/vagrant/issues/5782

and the workaround suggested in 
https://github.com/mitchellh/vagrant/issues/7970
worked for me.

**Comment by dbrown428** [comment]
I had this same issue when upgrading from 1.8.7 to 1.9.7. I tried downgrading to 1.9.4, and still got stuck at "Acquired Access Lock". I then completely uninstalled vagrant and the user data (https://www.vagrantup.com/docs/installation/uninstallation.html), and reinstalled 1.9.7 - everything seams to be working properly now.

**Comment by gdubicki** [comment]
Ok, I got this resolved. What helped was to UNINSTALL Vagrant 2.0.0 and reinstall it from scratch. DON'T just upgrade it from the previous version - use install script first, remove user data and then install again.

**Comment by fatalmind** [comment]
Same here: Installed Vagrant 2.0.1 on top of 1.8.x. `Vagrant up` got stuck. Uninstalled Vagrant (using the uninstall.tool contained in the 2.0.1 distribution), reinstalled. All fine.

OS X, VirtualBox 5.2.6 (My first thought was that the new VirtualBox was the problem—not so).

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
