### ISSUE TITLE
stderr: /bin/chown: changing ownership : Operation not permitted

### ISSUE THREAD

**Issue by miiimooo** [hashicorp/vagrant#8610]
I followed the guidelines for sudo in https://www.vagrantup.com/docs/synced-folders/nfs.html#root-privilege-requirement

Nevertheless, I get

```
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Vagrant failed to install an updated NFS exports file. This may be
due to overly restrictive permissions on your NFS exports file. Please
validate them and try again.

command: chown 0:4 /tmp/vagrant20170523-25696-1r766rd
stdout: 
stderr: /bin/chown: changing ownership of '/tmp/vagrant20170523-25696-1r766rd': Operation not permitted
```

Not sure this is relevant but the sudo itself seems to work:
```
$ touch /tmp/vagrant20170523-4158-s8y0cg
$ chown 0:4 /tmp/vagrant20170523-4158-s8y0cg
chown: changing ownership of '/tmp/vagrant20170523-4158-s8y0cg': Operation not permitted
$ sudo chown 0:4 /tmp/vagrant20170523-4158-s8y0cg
```

### Vagrant version
Vagrant 1.9.5

### Host operating system
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

### Guest operating system
box 'ubuntu/trusty64'

### Vagrantfile
```ruby
box_name = "tapwell.se"
box_host = "tapwell.dev"
box_mem = 3096
box_ip =  "192.168.50.131"

###
vagrant_root = File.dirname(__FILE__)
share_root = "/srv/www/"  + vagrant_root.split('/').last

Vagrant.configure("2")  do |config|
    config.vm.box = "ubuntu/trusty64"

    # Disable totally unnecessary default shared folder
    config.vm.synced_folder '.', '/vagrant', :id => 'vagrant-root', :disabled => true


    # Assign this VM to a host only network IP, allowing you to access it
    # via the IP.
    config.vm.network :private_network, ip: box_ip
    ## Use for windows testing
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.hostname = box_host
    config.vm.provider "virtualbox" do |v|
        v.name = box_name
        v.customize ["modifyvm", :id, "--memory", box_mem]
        v.customize ["modifyvm", :id, "--cpus", "1"]
    end

    # Provisioning settings.
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision/site.yml"
        ansible.sudo = true
        # Vhost and PHP settings - change if needed
        ansible.extra_vars = {
          ansible_os_family: 'Debian',
          server_hostname: config.vm.hostname,
          share_root: share_root,
          drupal_root: share_root + "/web",
          mysql_root_password: "password",
          php_memory_limit: "256M",
          composer_user: "vagrant",
          composer_user_home: "/home/vagrant",
          box_mem: box_mem,
          drupal_db: 'drupal',
          varnish_default_backend_port: '8081',
          varnish_default_backend_host: '127.0.0.1',
          varnish_secret: '5b096b19-8d12-4a8e-9075-50d6b0c7ebf8',
        }
    end

    config.hostsupdater.aliases = ["dev.tapwell.com", "dev.tapwell.se", "dev.tapwell.no", "dev.tapwell.fi"]

    # The path to the platform
    config.vm.synced_folder vagrant_root, share_root, :nfs => true, :nfs_udp => true

end
```

### Debug output
https://gist.github.com/miiimooo/4365441ee909b6a5b1d432b12c58a0ba

### Expected behavior
Should have mounted the shared folder

### Actual behavior
Did not mount the folder

### Steps to reproduce
1. vagrant up
2.
3.

### References
https://www.vagrantup.com/docs/synced-folders/nfs.html#root-privilege-requirement

- GH-8238

**Comment by miiimooo** [comment]
Looking at the source I have realised what the problem is:

My /etc/exports is owned by root:adm, my user is member of the adm group

vagrant-1.9.5/plugins/hosts/linux/cap/nfs.rb: 110
```
              # Only use "sudo" if we can't write to /etc/exports directly
              sudo_command = ""
              sudo_command = "sudo " if !File.writable?(NFS_EXPORTS_PATH)
```

So the bug here is that directly writing to /etc/exports isn't used but still tries to do the tmp file move.

As a workaround I've changed the group on my /etc/exports and that solved it for me.

**Comment by psihius** [comment]
This is still an issue on Vagrant 2.0.0

In my case changing the group does not help at all. I have followed the current documentation, added lines to the sudoers files and I get an error when trying to chown the file. If I change the file user and group to `myuser:adm` - I get an mv error with `permission denied`.

**Comment by psihius** [comment]
So I reverted the exports file to root:root @ 664 permissions and dropped to NFSv3 and oh god - it works!

Basically what I think is NFSv4 setup requires it's own section to explain how you set up that monster. NFSv3 is basically enable and forget, v4 needs a god damn detailed step by step manual...

**Comment by towo** [comment]
It's also an issue when you have ACL permissions for `/etc/exports`; it will then try to do a `chown 0:0/tmp/$filename` without sudo and fail at that. Workaround is remove the ACL, but this shouldn't be an issue in the first place.
