### ISSUE TITLE
[Windows] "Vagrant::Util::Platform.windows_admin" hangs forever

### ISSUE THREAD

**Issue by BR0kEN-** [hashicorp/vagrant#8611]
### Vagrant version
1.9.5

### Host operating system
Windows 7 Enterprise N, Service Pack 1, x64

### Guest operating system
Doesn't matter, but Ubuntu Xenial x64

### Vagrantfile
```ruby
Vagrant::Util::Platform.windows_admin?

# Never reach this point.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
end
```

### Debug output
https://gist.github.com/BR0kEN-/ff4782cd7a8164b099d6ca44643da328

Please note that output of command is correct - `True` (https://gist.github.com/BR0kEN-/ff4782cd7a8164b099d6ca44643da328#file-vagrant-log-L292), but it continues hanging, and the next line (`ERROR loader: Vagrantfile load error:`) caused by clicking `CTRL+C` because, otherwise, execution never ends.

### Expected behavior
It shouldn't hang.

### Actual behavior
It hangs forever.

### Steps to reproduce
1. `cd test`
2. `vagrant init ubuntu/xenial64` (doesn't matter which one, the problem is in utilities)
3. Add the `Vagrant::Util::Platform.windows_admin?` as very first line to `Vagrantfile`.

**Comment by BR0kEN-** [comment]
Actually, any execution of `Vagrant::Util::PowerShell.execute_cmd` leads to hanging out.

**Comment by BR0kEN-** [comment]
After debugging I found out that this isn't Vagrant bug, but https://github.com/enkessler/childprocess. The `break if process.exited?` in `Vagrant::Util::Subprocess.execute` is never returns `true`, so commands are permanently running.

**Comment by BR0kEN-** [comment]
Strange, but the problem happens only with PowerShell. Others also have experienced this, but running commands from C# (https://stackoverflow.com/a/27922916).

Might be we have consider usage of PowerShell commands in Vagrant?

**Comment by BR0kEN-** [comment]
Also, I run Cygwin as administrator (right click, `Run as administrator`) and `Vagrant::Util::Platform.windows_admin?` just returns `false`. 👎

**Comment by BR0kEN-** [comment]
Damn, PR isn't fix the problem due to exit code. Process successfully terminates, but exit code ain't `0`.

Note: this is actual for PowerShell 2. After update to PowerShell 3 the problem is gone.

**Comment by briancain** [comment]
Hi @BR0kEN- - if you upgrade to the latest Vagrant do you still encounter this issue? Thanks!

**Comment by BR0kEN-** [comment]
@briancain I'm not able to test, sorry. It needs an effort booting a VM with Win7 and PowerShell 2 and I don't want to experiment.

**Comment by chrisroberts** [comment]
The underlying cause of this was powershell 2 hanging. Recent releases of Vagrant have a powershell 2 check to prevent this from happening. Cheers!
