### ISSUE TITLE
ssh-agent forwarding not working correctly while provisioning on Windows

### ISSUE THREAD

**Issue by Igetin** [hashicorp/vagrant#8615]
### Vagrant version
1.9.4 & 1.9.5

### Host operating system
Windows 7 Enterprise (64-bit)

### Guest operating system
Ubuntu 14.04.5 LTS (Trusty Tahr) (64-bit)

### Vagrantfile
```ruby
...
config.ssh.forward_agent = true
...
```
And relevant lines from provisioner script:

```
ssh-keyscan github.com >> ~/.ssh/known_hosts
git clone git@github.com:myaccount/myprivaterepo.git
```

### Debug output

[Gist](https://gist.github.com/Igetin/2a3c02d72b4156221d3bce122bcbcea2)

### Expected behavior

Works when `vagrant ssh`'d into the guest machine and cloning the repo manually:

```
Cloning into 'laundry'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
remote: Counting objects: 4245, done.
remote: Total 4245 (delta 0), reused 0 (delta 0), pack-reused 4245
Receiving objects: 100% (4245/4245), 7.60 MiB | 6.34 MiB/s, done.
Resolving deltas: 100% (2956/2956), done.
Checking connectivity... done.
```

### Actual behavior
```
==> default: # github.com SSH-2.0-libssh-0.7.0
==> default: # github.com SSH-2.0-libssh-0.7.0
==> default: no hostkey alg
==> default: Cloning into 'laundry'...
==> default: Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
==> default: Error reading response length from authentication socket.
==> default: Permission denied (publickey).
==> default: fatal: Could not read from remote repository.
==> default:
==> default: Please make sure you have the correct access rights
==> default: and the repository exists.
```

### Steps to reproduce
1. Run Windows
2. Ensure ssh-agent is running with the proper identity (`eval $(ssh-agent) && ssh-add`)
3. Run the provisioner via `vagrant up` or `vagrant provision`

### References
https://github.com/mitchellh/vagrant/issues/8415
https://github.com/mitchellh/vagrant/issues/1735

**Comment by gmanfunky** [comment]
Are you running the `ssh-agent` and `ssh` provided with git for windows (msys2)?

I just spent a few hours researching a similar case for myself. It seems that the `ssh.exe` and partnered `ssh-agent.exe` packaged with git for windows uses yet-another-method of fake unix-sockets, which the ruby gem `net-ssh` is unaware of. It is a separate case from the "cygwin+ruby+ssh-agent". 

A work-around I've found is to load up putty's pageant, which `net-ssh` gem is aware of. You have to do a little dance to load your key in `.ppk` format.

**Comment by Igetin** [comment]
Yes, I'm running Git for Windows. Tried on versions 2.11.0.3 and 2.13.1, agent forwarding fails on both.

Pageant is a workaround indeed, and it's been mentioned before on the issues I referenced. I've been currently just doing the repo cloning via `vagrant up && vagrant ssh -c 'bash /vagrant/clone_repo.sh' `.

**Comment by gmanfunky** [comment]
From my understanding `vagrant ssh` is an alias for ssh in your path. So the git package provided `ssh` knows how to work with `ssh-agent`. It jumps through some hoop to pretend to be a socket file on windows. 

But `vagrant provision` uses the Ruby [net-ssh](https://github.com/net-ssh/net-ssh) gem. Some work has gone into that project to make it work with ssh-agent under cygwin. But it still isn't aware of git's msys2 world, which doesn't have provide file capability that ruby standard library can recognize. 

I haven't been able to track down where the code is that the git/msys2 provided `ssh-agent` and `ssh` uses. If it is upstream and common enough, we might be able to lobby `net-ssh` to support it's "fake-file-socket" method and then vagrant can inherit such support.

**Comment by aymericDD** [comment]
I have the same problem on Windows 10 with Vagrant 2.0.4

**Comment by func0der** [comment]
@gmanfunky Since you seem to have the biggest insight in this particular manner, could you open up an issue over at net-ssh, pls?
That is, if we really think, that net-ssh should be fixed here and not git/msys2 which somehow does not work in a standard manner.

**Comment by mhall** [comment]
Unfortunately, this also does not work with the built-in OpenSSH that is now natively provided in recent builds of Windows 10. Running `ssh-add -L` in PowerShell shows my identity loaded properly, but `vagrant provision` is unable to make use of the key.

**Comment by hopefulwalker** [comment]
I have the same problem on Windows 10 with Vagrant 2.2.4 & Git: 2.21.0A.
ssh-agent forwarding doesn't work.

**Comment by func0der** [comment]
Windows 10 and native ssh-agent: https://github.com/net-ssh/net-ssh/issues/628

**Comment by axos88** [comment]
This is not restricted to Windows. I'm having the same issue on linux

**Comment by axos88** [comment]
Disregard, my issue is actually: https://github.com/hashicorp/vagrant/issues/1303

**Comment by felipecassiors** [comment]
I still have the same problem. 

Windows 10 1909
Vagrant 2.2.6
Git for Windows 2.25.0

I setted up my ssh-agent with this guide: 
https://help.github.com/en/github/authenticating-to-github/working-with-ssh-key-passphrases

**Comment by chrisroberts** [comment]
Closing this issue as support for ssh-agent forwarding via cygwin/msys2 has been fixed. For the windows port of openssh, we are waiting for implementation within the net-ssh library.

Cheers!
