### ISSUE TITLE
Allow bridged networking without removing it's default route

### ISSUE THREAD

**Issue by halcyonCorsair** [hashicorp/vagrant#862]
I need the bridged network's default route to stay in place, so I need a way I can tell vagrant to not add the following to the VM's /etc/network/interfaces:

```
post-up route del default dev $IFACE
```

**Comment by mckelvin** [comment]
:+1:

**Comment by mckelvin** [comment]
@justinlynn  I would appreciate it if you add `use_dhcp_assigned_default_route` to https://docs.vagrantup.com/v2/networking/public_network.html

**Comment by justinlynn** [comment]
@mckelvin I will put it on my todo list. I'm travelling extensively at the moment so it may be some time until I am able to do so.

**Comment by justinlynn** [comment]
@mckelvin Would you mind creating a new issue for this request and mentioning me on it please? That way it may be fixed more quickly and is less likely to be missed.
