### ISSUE TITLE
vagrant esxi plugin's guest capability does not work correctly

### ISSUE THREAD

**Issue by shawnho1018** [hashicorp/vagrant#8637]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
vagrant 1.9.5
### Host operating system

Mac OS 10.12
### Guest operating system
ESXi 6.5
Box file can be downloaded from: 
https://www.dropbox.com/s/sgokojt6xr3bfn0/vmware-iso-vmware-0.1.2.box?dl=0

### Vagrantfile

```ruby
# Copy-paste your Vagrantfile here
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "esxi65"
  config.vm.guest=:vyos
  config.vm.provider "vmware_fusion" do |vb|
    config.vm.hostname = "my123"
    config.ssh.username="root"
    config.ssh.private_key_path=File.expand_path("../id_rsa", __FILE__)
    config.vm.network "private_network", ip: "192.168.62.20"
    vb.gui=true
  end
end
```

### Debug output
Debug file can be downloaded from: 
https://www.dropbox.com/s/kkpscwqwycenzn7/vagrant.log?dl=0

The debug log suggests the following: 
『 INFO interface: error: The configured shell (config.ssh.shell) is invalid and unable
to properly execute commands. The most common cause for this is
using a shell that is unavailable on the system. Please verify
you're using the full path to the shell and that the shell is
executable by the SSH user.』
I think this may prevent the vagrant to further execute guest_capability. 

### Expected behavior
What should have happened?
Guest Capability for ESXi plugin {change_host_name} should work. I use another guest to test. If I deliberately set config.vm.guest=:esxi, I can see:
DEBUG ssh: Exit status: 0
DEBUG guest: Searching for cap: change_host_name
DEBUG guest: Checking in: esxi
DEBUG guest: Found cap: change_host_name in esxi
 INFO guest: Execute capability: change_host_name [#<Vagrant::Machine: default (HashiCorp::VagrantVMwarefusion::Provider)>, "vyos-2"] (esxi)

### Actual behavior
What actually happened?
change_host_name capability does not work on my esxi box. 
### Steps to reproduce
1. Use the box image I produce in the following link: 
https://www.dropbox.com/s/sgokojt6xr3bfn0/vmware-iso-vmware-0.1.2.box?dl=0
2. Vagrant up --provider=vmware_fusion

**Comment by kikitux** [comment]
Hello

This was added in 2013 and the code is here:
https://github.com/mitchellh/vagrant/blob/9c299a2a357fcf87f356bb9d56e18a037a53d138/plugins/guests/esxi/cap/change_host_name.rb

Could you please share a command to check the version of esxi and the command to change the hostname in the version you are using?

with that we can update the logic of this.

thanks

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
