### ISSUE TITLE
I cannot up a vm on windows 10 with hyper-v enabled

### ISSUE THREAD

**Issue by HenrikBach1** [hashicorp/vagrant#8644]
If I issue these commands, in an elevated shell, I get below error:

$ vagrant init wkerkeni/xenialdesk64; vagrant up --provider hyperv
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) Wi-Fi-Hyper-V-Swithch
    default: 2) Ethernet-Hyper-V-Switch
    default: 3) packer-hyperv-iso
    default:
    default: What switch would you like to use? 1
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Import-VM : 'xenialdesk64' failed to realize. (Virtual machine ID 0E9E7C44-1D07-417A-AD29-40D948E6A9AF)
Failed to access configuration store: General access denied error (0x80070005).
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.9.5\plugins\providers\hyperv\scripts\import_vm_vmcx.ps1:154 char:1
+ Import-VM -CompatibilityReport $vmConfig
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Import-VM], VirtualizationException
    + FullyQualifiedErrorId : AccessDenied,Microsoft.HyperV.PowerShell.Commands.ImportVM

### Vagrant version
$ vagrant -v
Vagrant 1.9.5

### Host operating system
This is the operating system that you run locally.
$ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Enterprise N
OS Version:                10.0.14393 N/A Build 14393

and (later today after a major windows update I tried again)

$ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Enterprise N
OS Version:                10.0.15063 N/A Build 15063

### Guest operating system
This is the operating system you run in the virtual machine.
Ubuntu Xenial Desktop 16.04 LTS 64 bit

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "wkerkeni/xenialdesk64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

### Debug output
https://gist.github.com/HenrikBach1/d223dc20c2fa4b25b745dbd7729987db.js

### Expected behavior
What should have happened?
The VM should be started

### Actual behavior
What actually happened?
The above error message

### Steps to reproduce
1. vagrant init wkerkeni/xenialdesk64
2. vagrant up --provider hyperv

### References
Are there any other GitHub issues (open or closed) that should be linked here?
None of my knowledge

**Comment by mikehans** [comment]
Line 803 and 804 of your debug gist looks to be the start of the problem.:
```
DEBUG subprocess: stderr: Import-VM : 'xenialdesk64' failed to realize. (Virtual machine ID BE4C94D0-A83E-4C3D-BE2E-D85460C53A5F)
Failed to access configuration store: General access denied error (0x80070005).
```

When using Hyper-V I think I read somewhere that using the Ethernet Hyper-V switch is better than the Wifi Hyper-V switch. I'm not sure where I read it now or if it's even still current (or even if it was good advice to begin with). 

I'm not sure what the configuration store is that is referred to in line 804. There may be a problem with the box. Not sure that it's Hyper-V related - you are running with an elevated command prompt otherwise vagrant would have failed with a different error.

A couple of things to try: 
1) Try using the Ethernet Hyper-V switch instead of the WiFi Hyper-V switch
2) Try a different box - perhaps centos/7

**Comment by HenrikBach1** [comment]
Ok. I'll look into your suggestions...

**Comment by HenrikBach1** [comment]
Hi,

Now, I've tried:
Item 1: No effect with all possible network choices,
Item 4: It seems that it is a general hyper-v permission problem that other people reports back, too: https://github.com/hashicorp/vagrant/issues/8906.

/Henrik

**Comment by HenrikBach1** [comment]
Now, it seems to work in vagrant 2.0.3.

Case closed.

/Henrik
