### ISSUE TITLE
Feature request: attach secondary disk on Hyper-V

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/vagrant#8648]
Reading the available options, I notice a lack of any capability to add a secondary disk. This would be very useful in order to create a separation between persistent data (stored on the secondary disk) and app code (stored on the main image, which is re-created on demand).

While synced folders are a possible road toward a solution here, not all scenarios can cope with the "shared folder" mechanism employed there (e.g. SQL Server wants a real disk to write on).

Please correct me if I somehow just missed this feature in the documentation.

**Comment by JohnEricson** [comment]
There is a pendingt request on this here https://github.com/hashicorp/vagrant/pull/6321
I think it's not merged yet because the format of configuring it in the Vagrantfile needs to change.
