### ISSUE TITLE
Feature request: local shell provisioner

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/vagrant#8649]
Packer has a useful "local shell" provisioner that can be used to perform operations on the host that support setting up the guest. I request the same feature be added to Vagrant - I want to execute shell (and PowerShell) scripts on the host at certain steps in the provisioning process.

**Comment by avoidik** [comment]
https://superuser.com/a/992220

**Comment by chrisroberts** [comment]
This can now be accomplished with vagrant triggers: https://www.vagrantup.com/docs/triggers/

Cheers!

**Comment by sandersaares** [comment]
Vagrant triggers only appear to support executing commands on the host before or after provisioning, not at certain steps. Or do I misunderstand it somehow?

What I need is to execute a command on the host between two provisioning commands executed on the guest.
