### ISSUE TITLE
setting hostname in vagrant races with systemctl restart network

### ISSUE THREAD

**Issue by tomaskrizek** [hashicorp/vagrant#8650]
### Vagrant version
1.9.5

### Host operating system
Fedora 25

### Guest operating system
Fedora 25

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
    config.vm.box = "freeipa/ci-master-f25"
    config.vm.box_version = "0.2.5"

    config.vm.network "private_network",
        ip: "192.168.101.100"

    config.vm.hostname = "controller.ipa.test"
end
```

### Debug output
- `vagrant up`: https://gist.github.com/tomaskrizek/30085a696a9e5807a9711e47ca900f4e
- `journalctl -u network` on VM: https://gist.github.com/tomaskrizek/28ee03e81c306df4ad50a0644226654d

### Expected behavior
VM successfully starts with the specified IP and hostname.

### Actual behavior
VM starts, but setting the hostname fails.
When vagrant attempts to restart network after it sets the hostname, this probably races with some other restart of the network service and it fails with `dhclient(651) is already running - exiting`.

### Steps to reproduce
1. use Vagrantfile above
2. `vagrant up`

### References
- At first I though this may be an issue with `vagrant-libvirt`: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/785 
- Similar issue in `vagrant-parallels`:  https://github.com/Parallels/vagrant-parallels/issues/83
- Simillar issue in vagrant with different box: https://github.com/mitchellh/vagrant/issues/5852

### Additional info
- I'm not able to reproduce this with `fedora/25-cloud-base`, so it may be a box issue, but I have no idea what could possibly be causing it. 

### Workaround
Do not use vagrant to set the hostname.

**Comment by bendikro** [comment]
No fixes for this in the works?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
