### ISSUE TITLE
Shell provisioner occasionally instantly fails with "The box is not able to report an address for WinRM to connect to yet."

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/vagrant#8681]
### Vagrant version
Vagrant 1.9.5

### Host operating system
Windows 10 Creators Update.

### Guest operating system
Windows Server 2016.

### Vagrantfile
No correlation with a specific vagrantfile detected so far - seems to randomly happen with "shell" provisioners when operating over WinRM.

### Debug output
https://gist.github.com/sandersaares/f97798ca3dd647f4d28ad757b43280e1

### Expected behavior
The "shell" provisioner executes commands without fault.

### Actual behavior
Sometimes a "shell" provisioner will instantly fail with the error "The box is not able to report an address for WinRM to connect to yet.".

This may happen even right after finishing another shell provisioner that performed its job just fine via WinRM. For example:

```
c:\Source\xxx\xxx>vagrant destroy -f && vagrant up
==> default: Running cleanup tasks for 'trigger' provisioner...
==> default: Stopping the machine...
==> default: Deleting the machine...
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Configured vmname is xxx
==> default: Importing a Hyper-V instance
Looking for switch with name: xxx
Found switch: xxx
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
    default: Setting VM Integration Services
    default: Successfully imported a VM with name: xxx
==> default: Starting the machine...
==> default: Waiting for the machine to report its IP address...
    default: Timeout: 300 seconds
    default: IP: fe80::f9d3:8f08:2072:1b6e
==> default: Waiting for machine to boot. This may take a few minutes...
    default: WinRM address: 10.0.5.125:5986
    default: WinRM username: xxx
    default: WinRM execution_time_limit: PT2H
    default: WinRM transport: ssl
==> default: Machine booted and ready!
==> default: Running provisioner: Copy setup files to guest (file)...
==> default: Running provisioner: Attach data disk (trigger)...
==> default: Executing command "PowerShell.exe -File ../Scripts/Attach-DataDisk.ps1 -vmName my-windows-asdp-host -diskPath c:/VM/Virtual Hard Disks/Test2.vhdx"...
==> default: Adding disk c:/VM/Virtual Hard Disks/Test2.vhdx
==> default: Command execution finished.
==> default: Running provisioner: Connect data disk (shell)...
    default: Running: inline PowerShell script
==> default: Data disk appears to already have a filesystem, which is nice and well.
==> default: Mounting data disk as drive D.
==> default: Running provisioner: Customize the VM (shell)...
    default: Running: inline PowerShell script
==> default: WARNING: Waiting for service 'Docker Engine (docker)' to stop...
==> default: Running provisioner: Replace default credentials (shell)...
The box is not able to report an address for WinRM to connect to yet.
WinRM cannot access this Vagrant environment. Please wait for the
Vagrant environment to be running and try again.
```

When it occurs, the error is instant. There is no waiting for IP address - the "executing provisioner" line appears together with this error.

I note that the "default IP" and "WinRM address" lines in the above snippet are different. It seems to take the link-local IPv6 address as "default IP" for some reason (gets it before DHCP assigns IPv4?). Not sure if relevant, as the WinRM IP address is the correct one and worked for the first "shell" provisioners.

### Steps to reproduce
1. `vagrant up`

**Comment by sandersaares** [comment]
Added gist with debug log. Nothing useful to my eyes but I imagine others know better what to look for.

**Comment by sandersaares** [comment]
This happens if `get_network_config.ps1` returns an empty string for the IP address.

Why does it do that? Unknown - the machine is up and running and previous commands are executing just fine. I have also noticed that sometimes Hyper-V manager does not show an IP address. Possibly this information is not 100% reliable.

**Comment by jbonhag** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
