### ISSUE TITLE
Hyper-V from within WSL

### ISSUE THREAD

**Issue by davidtwco** [hashicorp/vagrant#8700]
### Vagrant version
Vagrant 1.9.5 inside and outside WSL.

### Host operating system
Windows/Bash for Windows

### Guest operating system
Any

### Vagrantfile
N/A

### Debug output
`vagrant status --debug`
https://gist.github.com/davidtwco/ac7c05a315f594c91bc0a4b9bcc671d9

### Expected behavior
Listed status of Hyper-V VMs.

### Actual behavior
Hyper-V was said to be unavailable.

### Steps to reproduce
1. Install Vagrant within WSL and follow [Vagrant documentation on WSL](https://www.vagrantup.com/docs/other/wsl.html).
2. Use the Hyper-V provider in a Vagrantfile.
3. Try to use Vagrant from within WSL.

### References
N/A

**Comment by nigh8w0lf** [comment]
It's the same on the latest  Version: 1.9.6
running `vagrant up --provider=hyperv` from within WSL, you get the below message.

_The provider 'hyperv' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

The Hyper-V provider only works on Windows. Please try to
use another provider._

**Comment by chrisroberts** [comment]
Hi there,

The WSL support in Vagrant is still very new and currently only the VirtualBox and Docker providers are supported. Other providers will gain support over time and I have labeled this issue as an enhancement.

Cheers!

**Comment by pierrebeaucamp** [comment]
Thanks for looking into this.
I just wanted to add that Docker on Windows is also using Hyper-V under the hood. Unfortunately that means that you can't run Virtualbox and Docker side-by-side. Vagrant integration with Hyper-V would be a real life-saver for anyone who needs Docker in their workflow.

**Comment by ironland** [comment]
Hi,

has there been any progress on this? I was thinking of setting up my environment using vagrant within WSL and Hyper-V as the provider. Is this still possible?

**Comment by davidtwco** [comment]
@ironland You'll need to have a separate Command Prompt or PowerShell window open for running Vagrant commands. This means that your project will need to be in the Windows filesystem rather than the WSL filesystem.

**Comment by itopiacloud** [comment]
I've also got this issue with Windows10 CU - I've aliased vagrant to the Windows exe but getting same issue.

**Comment by wilmardo** [comment]
Is there any progress on this? 
Came accross this issue today for exact the reaseon @pierrebeaucamp states above, I would like to use Docker and Vagrant on the same host. To bad this isn't possible at the moment :/

**Comment by nocsigroup** [comment]
The vagrant hyper-v provider needs access to Hyper-V powershell module -- which isn't exposed directly from WSL. Easiest thing to do is just to open a powershell prompt from WSL (/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe) and use vagrant in that manner.

**Comment by strarsis** [comment]
@nocsi: I need to run other *nix based tools like ansible. Although ansible can be installed on Windows (cmd), it won't work without adjustments because it expects different paths (like user home paths).
