### ISSUE TITLE
Centos 7 guest cannot create SMB synced_folder (Hyper-V on Windows 10 host)

### ISSUE THREAD

**Issue by mikehans** [hashicorp/vagrant#8703]
### Vagrant version
1.9.5

### Host operating system
Windows 10 (Hyper-V)

### Guest operating system
Centos 7 from https://atlas.hashicorp.com/centos/boxes/7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "centos7aa"
  
  config.vm.provider "hyperv" do |h|
    h.vmname = "centos7-test1"
    h.cpus = 2
    h.memory = 1024
    h.maxmemory = 2048
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "./shared", "/vagranttest", type: "smb"

  # The following shell script does work (add username & password)
  # Note that tested password has spaces in it. 
  # username in the example (not working) is myuser
  # password in the example is "Hello world"
  # config.vm.provision "shell", inline: <<-SHELL
  #     mkdir -p /vagranttest
  #     sudo mount -t cifs -o username=myuser,password="Hello world" //192.168.43.218/3cd78a30c6e97f96c5e3d321213469ac /vagranttest
  # SHELL

  config.vm.provision "shell", path: "provision.sh"
  
end

```

### Expected behaviour and additional testing
The SMB share failed to mount.

The error message notes that the following was attempted
```bash
mount -t cifs -o uid=1000,gid=1000,sec=ntlm,credentials=/etc/smb_creds_f848db941825c6a437a5d7bc7e399ca4 //192.168.0.11/f848db941825c6a437a5d7bc7e399ca4 /vagranttest
```

I copied and pasted this into the Centos console (vagrant ssh'd in) and it failed there too. 

I modified the mount command to the following which also failed (the credential file exists)
```bash
sudo mount -t cifs -o credentials=/etc/smb_creds_f848db941825c6a437a5d7bc7e399ca4 //192.168.43.218/3cd78a30c6e97f96c5e3d321213469ac /vagranttest
```

Putting the credentials directly into the mount command as username and password worked (I can read and write from both host and guest).
```bash
sudo mount -t cifs -o username=myuser,password="Hello world" //192.168.43.218/3cd78a30c6e97f96c5e3d321213469ac /vagranttest
```

### Steps to reproduce
1. Windows 10 host (fully updated) with Hyper-V required
2. create an SMB mount using the synced_folder command
3. ```vagrant up --provider hyperv``` with the centos/7 box
4. observe that the share fails to mount

**Comment by bbrala** [comment]
Could this be related to #8620? Can you try with that sec option?

**Comment by tapuzzo-fsi** [comment]
I got bit by this bug today.  I had to manually add sec=ntlmssp to my mount options which luckily seems to override the version that is automatically placed by vagrant.  Seems like this happens in newer linux kernels.    Should be a config to set the preferred "sec" or better yet a flag to not set it (allowing default or manual set via mount_options.)

**Comment by jbonhag** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
