### ISSUE TITLE
Official hashicorp box in documentation and in Atlas is VERY old (Ubu 12.04)

### ISSUE THREAD

**Issue by marco-m** [hashicorp/vagrant#8713]
I noticed that the Vagrant documentation for Boxes (https://www.vagrantup.com/docs/boxes.html) still suggests Ubuntu 12.04, which has been superseded by 14.04, which has been superseded by 16.04 :-)

At the beginning I wanted to provide a PR editing the documentation to point to `vagrant init hashicorp/xenial64`, but then I realized that the only Ubuntu box from Hashicorp is still 14.04 (https://atlas.hashicorp.com/hashicorp/).

As a user, it gives the impression that the documentation is very stale. Even worse, if a user is not following Ubuntu, will actually use 12.04 which is way too old and EOL.

Maybe the simplest approach is to remove the section about "Official Boxes" and just suggest to use the Bento boxes?

**Comment by marco-m** [comment]
hello ?

**Comment by briancain** [comment]
This has been fixed already, so I'm going to go ahead and close this.
