### ISSUE TITLE
Verify License behind a proxy

### ISSUE THREAD

**Issue by iguyking** [hashicorp/vagrant#8734]
### Vagrant version
Vagrant 1.9.5

### Host operating system
Windows 10

[environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0

Environment Variables of http_proxy & https_proxy are configured properly and cacert.pem updated due to zScaler intercept.    System is able to do a vagrant plugin install/uninstall etc commands successfully.   

### Expected behavior
vagrant does its plugin checkin behind a proxy.  

### Actual behavior
Vagrant hasn't been able to verify your usage of 'vagrant-vmware-workstation' in
over two weeks. Please connect to the internet to allow Vagrant to verify
your license. If you don't verify the license within 4 to 6 weeks, you will
be locked out.

### Steps to reproduce
1.  Install plugin for 'vmware_workstation' and be behind Proxy environment
2.  Wait a 2 weeks since installing

**Comment by sacerro** [comment]
+1
Same issue. I'm behind proxy

**Comment by geckoseo** [comment]
Same, behind a proxy. How to resolve?

**Comment by geckoseo** [comment]
Well, for any other hapless person stumbling on this thread, I found a solution that seems to work:

There is a file that contains a date of last ping..

~/.vagrant.d/data/last-ping-vagrant-vmware-fusion 

or in Windows:

~/.vagrant.d/data/last-ping-vagrant-vmware-workstation

The date stamp in the file was 1518199687

The date format is [yyddmmssss]

I changed that to the year 2022, so now it looks like this:

2218199687

..and the problem went away. I did not even need to restart the machine or remove/reinstall anything, simply ran `vagrant status` to confirm the warning was gone.

**Comment by chrisroberts** [comment]
Hi there. Re-installing the problem will resolve the issue correctly. You can read more about it here: https://www.hashicorp.com/blog/updating-vagrant-vmware-plugin

Cheers!
