### ISSUE TITLE
Docker provider (through docker-machine) binds ssh port to 127.0.0.1 instead of 0.0.0.0

### ISSUE THREAD

**Issue by zatarus** [hashicorp/vagrant#8752]
### Vagrant version
Vagrant 1.9.5

### Host operating system
Mac OSX 10.11.6

### Guest operating system (container in a debian server)
phusion/baseimage-custom

Source Dockerfile:

```
FROM phusion/baseimage
RUN rm -f /etc/service/sshd/down 
RUN /usr/sbin/enable_insecure_key
```

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.define "phusion" do |v|
        v.vm.provider "docker" do |d|
          d.cmd = ["/sbin/my_init", "--enable-insecure-key"]
          d.image = "phusion/baseimage-custom"
          d.name = 'dockerizedvm'
          d.has_ssh = true
        end
        v.ssh.host = 'my-remote-machine'
        v.ssh.private_key_path = "insecure_key"
        v.vm.provision "shell", inline: "echo hello"
    end
end
```

### Debug output
```
$ vagrant up
Bringing machine 'phusion' up with 'docker' provider...
==> phusion: Creating the container...
    phusion:   Name: dockerizedvm
    phusion:  Image: phusion/baseimage-custom
    phusion:    Cmd: /sbin/my_init --enable-insecure-key
    phusion:   Port: 127.0.0.1:2222:22
    phusion:  
    phusion: Container created: e9a5c40c83e0b14e
==> phusion: Starting container...
==> phusion: Waiting for machine to boot. This may take a few minutes...
    phusion: SSH address: my-remote-machine:2222
    phusion: SSH username: vagrant
    phusion: SSH auth method: private key
    phusion: Warning: Connection refused. Retrying...
    phusion: Warning: Connection refused. Retrying...
    phusion: Warning: Connection refused. Retrying...
```
and guest machine:
```
$ docker ps
phusion/baseimage-custom  ...  Up 9 minutes   127.0.0.1:2222->22/tcp  dockerizedvm
```
### Expected behavior
SSH should work, **I can ssh** to the image using `insecure_key` on the server itself, that proves it is ssh enabled.

```
$ ssh -i insecure_key root@localhost -p 2222
Last login: Tue Jul  4 11:36:58 2017 from 172.17.0.1
root@441464bbaf83:~# 
```

### Actual behavior
SSH doesn't work, I think it is a binding issue because vagrant isn't aware docker is remote. I'm looking a way of making `docker run` command to bind to interface I specify (0.0.0.0), do such option exist?

### Steps to reproduce
1. Have a remote machine with docker installed and root access, build the ssh enabled phusion image
2. Add that machine to docker-machine, enabled its environment
3. Vagrant up with above configuration

**Comment by zatarus** [comment]
Temporary solution I've found is adding ports manually 2222:22 and changing vagrant username to 'root' (I will fix that later) but I've lost auto correct feature here.

**Comment by jbonhag** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier 🙁 

Cheers!
