### ISSUE TITLE
Chef-zero provisioning crash on Windows Server 2008 host

### ISSUE THREAD

**Issue by Bedotech** [hashicorp/vagrant#8755]
### Vagrant version
`Vagrant 1.9.6`

### Host operating system
`Windows 7`

### Guest operating system
`Windows Server 2008 r2 x64`
With .NET 4.5 and Powershell 5

### Vagrantfile
```ruby
# Required plugins
plugins = [
  "vagrant-berkshelf",
  "vagrant-omnibus",
  "vagrant-share"
]
plugins.each do |plugin|
  unless Vagrant.has_plugin?(plugin)
    raise "The vagrant plugin '#{plugin}'' is not installed! use vagrant plugin install {#plugin}"
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "charris/windows-2008-r2-x64"
  # https://www.vagrantup.com/docs/vagrantfile/winrm_settings.html
  config.winrm.codepage = 437
  config.winrm.retry_limit = 12
  config.winrm.retry_delay = 3

  hostname = "softsolution_vagrant_machine"
  config.vm.define hostname do |host|
  end

  config.vm.provider :virtualbox do |vb|
      vb.name = hostname
  end

  # Install Chocolatey
  config.vm.provision "shell", path: "install_chocolatey.bat"

  # Install latest chef
  config.omnibus.chef_version = :latest

  # Define Berkshelf
  # https://github.com/berkshelf/vagrant-berkshelf
  config.berkshelf.berksfile_path = "cookbooks/utilities/Berksfile"
  config.berkshelf.enabled = true

  # Install chef-solo
  config.vm.provision "chef_zero" do |chef|
    # Use a fixed provisioner version.
    # chef.version = "13.2.21"
    # Specify the local paths where Chef data is stored
    chef.cookbooks_path = "cookbooks"
    chef.nodes_path = "nodes"
    chef.roles_path = "roles"

    # Add recipes
    chef.add_recipe "utilities::chrome"

    chef.verbose_logging = true
  end
end
```

### Debug output
[debug.log](https://gist.github.com/Bedotech/2fc1841a3f606965a8bb68c91a7eb066)

### Expected behavior
The provisionig process must be ok or fail for error in cookbooks

### Actual behavior
Chef-zero can't find node and fail: ` Caused by Net::HTTPServerException: 404 "Not Found"` you can see the error in debug.log

This happen only on the first `vagrant up` if after fail i run `vagrant provision` all works correctly!

I think the problem is the sharing with `/nodes` folder every time i destroy a VM and create a new one Vagrant or chef create a new node file.

Thanks you for the support!

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
