### ISSUE TITLE
Vagrant 1.9.7 fails to install 'vagrant vb-guest'

### ISSUE THREAD

**Issue by 128keaton** [hashicorp/vagrant#8785]
### Vagrant version
1.9.7

### Host operating system
10.12.4

### Guest operating system
Ubuntu 16.04

### Vagrantfile
https://gist.github.com/128keaton/f725236ac6dad108e5b3741504f18a20

(put in a gist because its long)

### Debug output
https://gist.github.com/128keaton/230b0646f8df7b98ea8e8333acce51e8

### Expected behavior
The plugin should have installed.

### Actual behavior
The plugin didn't install

### Steps to reproduce
1. Download the latest version of Vagrant
2. Try to install [vagrant vb-guest](https://github.com/dotless-de/vagrant-vbguest)

**Comment by daffy1234** [comment]
1.9.5 is not the latest version.

**Comment by 128keaton** [comment]
@daffy1234 my bad, I wrote 1.9.5 in my report. Editing that. It was 1.9.7 that I was using. Using 1.9.5 is the workaround I used.

**Comment by chrisroberts** [comment]
Hi there,

Would you please you try doing a `vagrant plugin expunge` and re-installing the plugins to see if it resolves the loading issue.

Thanks!

**Comment by 128keaton** [comment]
@chrisroberts I tried a couple of times, and removed all of my ruby gems, but it did not help

**Comment by kikitux** [comment]
can't repo

```
vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Fetching: micromachine-2.0.0.gem (100%)
Fetching: vagrant-vbguest-0.14.2.gem (100%)
Installed the plugin 'vagrant-vbguest (0.14.2)'!
```

please check if you are using ipv6 and your machine can resolv ipv6 hosts (dns)

does your network have/use proxy of any sort?

**Comment by 128keaton** [comment]
@kikitux no I am not using ipv6. I just tried on another network, same issue.

**Comment by benje** [comment]
Also getting this issue when trying to install vagrant-vbguest plugin, or when running `vagrant plugin update`. Tried @chrisroberts suggestion but it didn't help.

Vagrant version: 1.9.7

Error:
```
vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies gssapi (= 1.0.3) and gssapi (= 1.2.0)
  Activated gssapi-1.2.0
  which does not match conflicting dependency (= 1.0.3)

  Conflicting dependency chains:
    gssapi (= 1.2.0), 1.2.0 activated

  versus:
    gssapi (= 1.0.3)

  Gems matching gssapi (= 1.0.3):
    gssapi-1.0.3
```

Any solutions would be appreciated!

**Comment by guimaluf** [comment]
I was getting the same error as @benje on Vagrant version 1.9.6 on Gentoo 
After downgrade to 1.9.5 plugins were install as always

**Comment by chrisroberts** [comment]
I have been unable to reproduce this behavior. It seems like there are artifacts from previous vagrant installations which still exist and are being loaded when the Vagrant is determining its internal library list. If you fully uninstall vagrant (ensuring the installation directory is fully removed) and re-install do you still encounter the errors?

One workaround available using an environment variable to disable strict dependency enforcement:

```
$ VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant ...
```

Let me know if a full re-install does not resolve the issue.

Cheers!

**Comment by guimaluf** [comment]
@chrisbaldauf 
I completely removed vagrant on gentoo `emerge -C vagrant` after reinstall I got the same error.
The plugin was successfully installed using `VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT` but I'm getting boot timeout on vms.

I'm downgrading to 1.9.5 again

**Comment by chrisbaldauf** [comment]
I think you mean @chrisroberts

**Comment by mwdiers** [comment]
I ran into this problem on macOS 10.12.6 after upgrading to 1.9.7.

Running the uninstall.tool and reinstalling Vagrant resolved this for me.

**Comment by Gemfruit** [comment]
I encountered this error today, and was unable to install other plugins relying on vagrant-vbguest. Unfortunately, my limited understanding of the tools resulted in a complete wipe of everything (virtual box, vagrant, VVV), and a fresh slate. Manually installing vagrant-vbguest did the trick, but it took me quite awhile to come to that conclusion, as I wasn't aware that it itself, was a plugin.

My guess is as stated above, fragments from a previous installation. While I did uninstall everything, I did not confirm the directories were empty, and I was unaware of the expunge command. Either way, figured I'd chime in that this plagued me as well.

**Comment by sergiokas** [comment]
@chrisroberts `VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1` workaround temporarily solved the issue for me (without uninstalling / reinstalling everything).

**Comment by DougBeney** [comment]
Huh, thanks for the fix. Running the command `VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant plugin install vagrant-hostsupdater` worked for me. (I needed the hostsupdater plugin.)

I was running Solus Linux with `Vagrant 1.9.6`, `ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]`, `gem 2.4.5.2`, and `Bundler version 1.15.4`.

**Comment by chrisroberts** [comment]
The 2.0.3 release of vagrant included vendored isolation based on version to prevent any overlap of items which may not be cleaned out on upgrade. This prevents unexpected library version collisions and resolves the underlying issue encountered here. Cheers!
