### ISSUE TITLE
Vagrant deleted downloaded box when failed to extract due to low disk space

### ISSUE THREAD

**Issue by sajjadG** [hashicorp/vagrant#8843]
I had 21G free space on my disk and I tried to setup `vagrant-box-osx` with this commands:

```
vagrant init http://files.dryga.com/boxes/osx-sierra-0.3.1.box
vagrant up
```
as its [github page setup section](https://github.com/AndrewDryga/vagrant-box-osx#setting-up) said. and after downloading 13GB box **it started to extract the box and it failed then it deleted the downloaded box!!! why?????**

```
$ vagrant up 
/usr/share/rubygems-integration/all/gems/vagrant-1.9.1/lib/vagrant/util/platform.rb:24: warning: Insecure world writable dir /home/sajjad/Programs in PATH, mode 040777
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'http://files.dryga.com/boxes/osx-sierra-0.3.1.box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'http://files.dryga.com/boxes/osx-sierra-0.3.1.box' (v0) for provider: virtualbox
    default: Downloading: http://files.dryga.com/boxes/osx-sierra-0.3.1.box
    default: Progress: 1% (Rate: 261k/s, Estimated time remaining: 15:35:32)^C==> default: Waiting for cleanup before exiting...
==> default: Box download was interrupted. Exiting.
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x ./box-disk1.vmdk: truncated gzip input
bsdtar: Error exit delayed from previous errors.
```

### Vagrant version
Vagrant 1.9.1

### Host operating system
Debian testing (10)

### Guest operating system
default

### Vagrantfile
I did not change it. it's what I got after running `vagrant init http://files.dryga.com/boxes/osx-sierra-0.3.1.box`
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
config.vm.box = "http://files.dryga.com/boxes/osx-sierra-0.3.1.box"
end
```

### Expected behavior
Keep the downloaded box in case of any error

### Actual behavior
Full cleanup!!! delete the downloaded box!!!

### Steps to reproduce
Vagrant up on a system with low disk space. disk space more than the box but less than x2 of box size.

**Comment by briancain** [comment]
Hello @sajjadG - do you have output showing the box got deleted after downloading? It looks like the output you shared is showing that a signal interrupt was sent to vagrant while downloading the box at 1% downloaded, and then vagrant attempted to untar that partially downloaded file.

**Comment by sajjadG** [comment]
Hi @briancain - You are right. I think i mis-interpreted the error! and it about download interruption. But I tried resume feature for downloading before downloading and it was working and I had a file in `~/.vagrant.d/tmp/box419204330a15f9c4b72ce94f70b05baec0c69e85` and its size was increasing while downloading and when I interrupted the download with `ctrl+c` vagrant kept the file there and when I `vagrant up`ed again it resumed the downloading. But this time I checked the path and all the possible places and I couldn't find a tmp file anywhere. and I `df`ed and checked my free space and it seemed there's no tmp file there! and it was not the expected behavior. That's why I thought it's because I didn't have enough free space for extracting!
I'll try to download it again and reproduce and report what happens.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
