### ISSUE TITLE
Time out issue for vagrant up on windows 10

### ISSUE THREAD

**Issue by ShafiqAhmed89** [hashicorp/vagrant#8846]
I am trying to configure this project on my local machine. I followed the steps given in readme. When I execute "vagrant up" command, it's giving time out issue. To see what's happening in background, I added following to VagrantFile : 
config.vm.provider "virtualbox" do |vb|
   vb.gui = true
end
After adding above lines and execute the vagrant up command, it's asking for login credentials of  "rhel73minimal". I used vagrant/vagrant for login/password, but the issue remains same, after sometime it is giving timeout. Please check the screenshot for more details: 

![image](https://user-images.githubusercontent.com/30666643/28888255-8af3f3b6-7785-11e7-9f45-45c92e18463b.png)

versions used initially:
vagrant : 1.9.4
virtual box : 5.0.20

works fine in windows 7.
Do I need to do anything else ?

I tried with config.vm_.boot_timeout value as 600, issue remains the same.
I tried with vagrant version 1.9.7 & virtual box version 5.0.26 combination, issue remains the same.
I tried with vagrant version 1.8.4 & virtual box version 5.0.26 combination, issue was different i.e vagrant didn't support latest virtual box version.

I am on windows 10. Is it causing any issues ?

Settings on VM:
- Port 22->2222 is enabled.
- Unable to vagrant ssh after failure.
- Network mode is "host only".
- Didn't have access to outside network from inside guest.

**Comment by emersonmellado** [comment]
Can you post your complete .Vagrantfile? I had the same issue a few weeks ago, but it is working now here.

**Comment by ShafiqAhmed89** [comment]
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rhel73-1.0.0"
  config.vm.box_url = "http://repo.release.xxxxx.yyy/nexus/content/repositories/vagrant/com/xxxxx/vagrant/rhel73/1.0.0/rhel73-1.0.0.box"
  config.vm.hostname = "master0"
  config.vm.boot_timeout = 600

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    end

  config.vm.define :master0 do |master0|
    master0.vm.box = "rhel73-1.0.0"
    master0.vm.box_url = "http://repo.release.xxxxx.yyy/nexus/content/repositories/vagrant/com/xxxxx/vagrant/rhel73/1.0.0/rhel73-1.0.0.box"
    master0.vm.hostname = "master0"
    master0.vm.network "private_network", ip: "192.168.100.10"
    master0.vm.network "forwarded_port", guest: 8080, host: 8080
    if Vagrant::Util::Platform.windows? then
      master0.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    end
    master0.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    master0.vm.provision "file", source: "yum.conf", destination: "/tmp/yum.conf"
    master0.vm.provision "file", source: "jenkins.cfg", destination: "/tmp/jenkins.cfg"
    master0.vm.provision "file", source: "plugins.csv", destination: "/tmp/plugins.csv"
    master0.vm.provision "shell", path: "master.sh"
    master0.vm.provision "shell", inline: "echo -e '192.168.100.20\tslave0' >> /etc/hosts"
  end

  config.vm.define :slave0 do |slave0|
    slave0.vm.box = "rhel73-1.0.0"
    slave0.vm.box_url = "http://repo.release.xxxxx.yyy/nexus/content/repositories/vagrant/com/xxxxx/vagrant/rhel73/1.0.0/rhel73-1.0.0.box"
    slave0.vm.hostname = "slave0"
    slave0.vm.network "private_network", ip: "192.168.100.20"
    slave0.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--memory", "1024"]
    end
    slave0.vm.provision "file", source: "yum.conf", destination: "/tmp/yum.conf"
    slave0.vm.provision "shell", path: "slave.sh"
  end
end

**Comment by ShafiqAhmed89** [comment]
@emersonmellado how did your issue get resolve ? Did you have any different settings. 
I am unable to ssh to my vm and also unable to ping/access outside network from vm (guest).

**Comment by emersonmellado** [comment]
@ShafiqAhmed89 I am not exactly sure, I was trying to use a CentOs and flipped to ubuntu. Can you try a very simple ubuntu machine? then it maybe a good idea to go isolating you vagrantfile piece by piece, it may be a configuration issue or something in the host.

I am sorry to not be so helpful in thie one. :(

**Comment by xiaotuanyu120** [comment]
open your git bash, and try this command
`netsh winsock reset`

**Comment by sea129** [comment]
Having the same issue with win 10 on home PC, vagrant 2 and vb 5.1.28.
Vagrant file just has box = ubuntu/trusty64

However, with vagrant 1.9.2, vb 5.1.18 and win 10 on another PC at work, it works.

**Comment by briancain** [comment]
Hi @ShafiqAhmed89 - Does this issue still persist if you use a different box?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
