### ISSUE TITLE
VBOX_INSTALL_PATH may contain multiple paths

### ISSUE THREAD

**Issue by snoblucha** [hashicorp/vagrant#885]
Command:

vagrant box add lucid32 http://files.vagrantup.com/lucid32.box

Symptoms: 

Command failed with message
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.

Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

Cause:

Bad value of VBOX_INSTALL_PATH for me it was
VBOX_INSTALL_PATH=C:\Program Files\Sun\xVM VirtualBox\;C:\Program Files\Oracle\VirtualBox\

Fix for me: 

set VBOX_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
and edit the environment properties for windows

Explanantion:

I have been using VirtualBox for a long time and through updating process somehow the VBOX_INSTALL_PATH property ends up in state described above. Note that SUN directory does not exist anymore and was properly uninstalled. I have been playing with PATH and points it to Oracle directory with no success, the command from command line ran OK, but vagrant still complained.

I suppose, that if more versions of virtualBox is installed(no matter for the reason) the VBOX_INSTALL_PATH may contain the list of path to the installations. And it will cause strange problems with Vagrant.

**Comment by KingMeet** [comment]
S
