### ISSUE TITLE
Specified :bridge => 'en1' not matched when it is in the interactive list

### ISSUE THREAD

**Issue by kennknowles** [hashicorp/vagrant#886]
Hi all,

I'm running vagrant 1.0.2 on ruby 1.9.3 in an RVM on OSX 10.7.3 and cannot get bridged networking working non-interactively. I dove into the code a bit, but nothing jumps out at me.

This is the Vagrantfile I am using to repro:

```
Vagrant::Config.run do |config|
  config.vm.box = "lucid64"
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"
  config.vm.network :bridged, :bridge => 'en1'
end
```

Steps to repro (assuming you have rvm set up)

```
rvm use --create 1.9.3@vagrant-repro
gem install vagrant
VAGRANT_LOG=DEBUG vagrant up
```

Output will be the following, which seems self-contradictory.

```
DEBUG network: Bridge was directly specified in config, searching for: en1
INFO interface: info: Specific bridge 'en1' not found. You may be asked to specify which network to bridge to.
[default] Specific bridge 'en1' not found. You may be asked to specify which network to bridge to.
INFO interface: info: Available bridged network interfaces:
[default] Available bridged network interfaces:
INFO interface: info: 1) en1: Wi-Fi (AirPort)
1) en1: Wi-Fi (AirPort)
 INFO interface: info: 2) en0: Ethernet
2) en0: Ethernet
INFO interface: info: 3) p2p0
3) p2p0
INFO interface: ask: What interface should the network bridge to? 
```

Thanks for any help resolving this,
- Kenn

**Comment by zilan920** [comment]
贼 血呼啦慢

**Comment by btylke** [comment]
I have had success with the following:
`
INTERNET_INTERFACE = %x(vboxmanage list bridgedifs | grep `route get 8.8.8.8 | grep interface | head -1 | awk -F' '  '{print $2}'` | grep -v VBoxNetworkName | awk -F 'Name: *' '{print $2}').strip
config.vm.network "public_network", bridge: "#{INTERNET_INTERFACE}"
`
