### ISSUE TITLE
Hyper-V Provider Fails when PowerCLI is Installed

### ISSUE THREAD

**Issue by michaeltlombardi** [hashicorp/vagrant#8862]
### Vagrant version
`1.9.7`

### Host operating system
Windows `10.0.14393`

### Guest operating system
CentOS 7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "hyperv"
  config.vm.network "public_network", bridge: "Guest"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "hyperv" do |h|
    h.enable_virtualization_extensions = true
    h.differencing_disk = true
  end
end
```

### Debug output
The full [debug output can be found in this gist](https://gist.github.com/michaeltlombardi/439dea9a254093799b811ea60658818c), but the relevant part is below:

```
DEBUG subprocess: stderr: Get-VM : 8/8/2017 11:28:54 AM	Get-VM		You are not currently connected to any servers. Please connect first using a 
Connect cmdlet.	
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-1.9.7\plugins\providers\hyperv\scripts\import_vm_xml.ps1:40 char:5
+     Get-VM | ForEach-Object -Process {
+     ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-VM], ViServerConnectionException
    + FullyQualifiedErrorId : Core_BaseCmdlet_NotConnectedError,VMware.VimAutomation.ViCore.Cmdlets.Commands.GetVM
```

Notice in this case that the cmdlet that failed is a VMware cmdlet, not from the Hyper-V module.

### Expected behavior
The VM should have launched as expected.

### Actual behavior
A failure occurred because the command `Get-VM` is ambiguous when both the PowerCLI and Hyper-V modules are available on a system.

### Steps to reproduce
1. Ensure Hyper-V is installed
2. Install the PowerCLI module (`Install-Module PowerCLI`)
3. Launch a vagrant box using the Hyper-V provider.

### Possible Fix
Fully qualify the Hyper-V commands in the script files to disambiguate the calls. I can submit a PR for this. for example instead of:

```powershell
Get-VM | ForEach-Object -Process {
    ...
}
```

We would include the Module name prior to the the function or cmdlet call:

```powershell
Hyper-V\Get-VM | ForEach-Object -Process {
    ...
}
```

**Comment by wiltaylor** [comment]
I recently sent a pull request for #8849 which adds a new ps1 file. I will update my pull request to add fully qualified also.
