### ISSUE TITLE
Unable to access guest VM synced folder(smb) 

### ISSUE THREAD

**Issue by ashokvaddevalli** [hashicorp/vagrant#8867]
Vagrant Version:1.9.6

Host OS; Windows 7

Guest OS: Windows 7

Vagrant provider vsphere

Vagrant file for smb:

config.vm.synced_folder ".", "/vagrant", type: "smb", smb_username: "hostmachineusername", smb_password: "hostmachinepassword"

Issue:

I am unable to access c:/vagrant folder on Guest VM, I am getting below error.

Pop up window: Location is not available
C:\vagrant is not accessible
Logon failure: unknown username or bad password.

Debug issue:

I have added domain name on vagrant file below 

config.vm.synced_folder ".", "/vagrant", type: "smb", smb_username: "domain/hostmachineusername", smb_password: "hostmachinepassword"

I am getting cmdkey issue after added domain name

**Comment by wiltaylor** [comment]
When you are entering the username you need to put the slash like \\ not /

**Comment by ashokvaddevalli** [comment]
Thanks @wiltaylor 

It is working, I am able to access synced folder.

**Comment by ashokvaddevalli** [comment]
@wiltaylor 

I don't like it to mention host machine username and password on Vagrant file, because it is not secured and also my guest VM is running on Esxi server, it is easy to see cred's to others.

How to pass the username and password in Vagrant file?

**Comment by briancain** [comment]
I'm going to go ahead and close this issue since you said it's working! If it's still an issue please let us know and I can re-open the issue.
