### ISSUE TITLE
Hyper-V Admin membership check is too simple, doesn't detect indirect membership

### ISSUE THREAD

**Issue by henriklynggaard** [hashicorp/vagrant#8868]
Hyper-V access is not detected if the membership is granted indirectly, because the code only checks direct membership

@_windows_hyperv_admin = -> {
      ps_cmd = "[System.Security.Principal.WindowsIdentity]::GetCurrent().Groups | ForEach-Object { if 
   ($_.Value -eq 'S-1-5-32-578'){ Write-Host 'true'; break }}"
   output = Vagrant::Util::PowerShell.execute_cmd(ps_cmd)
   return output == 'true'
}.call

As evident from above code loops the groups that the current user is member of. This will not detect if the access granted is indirect i.e. User (Memeber of)> group A (Memeber of)> "HyperV Admins" since the loop will only find "Group A"

### Vagrant version
Vagrant 1.8.7 (The code is the same in the master branch, so upgrading doesn't fix it)

### Host operating system
Windows 10

### Guest operating system
Fedora 26

### Vagrantfile
N/A

### Expected behaviour
Hyper-V access is detected despite indirect membership

### Actual behaviour
Hyper-V access is not detected

### Steps to reproduce
1. Add the user to a local or AD group of your choice
2. Add the group to "HyperV Administrator"
3. User has now got Hyper-V access through the indirect membership. This can be seen in the Hyper-V Manager console

### References
https://github.com/mitchellh/vagrant/blob/8dbb5d55a48f94951c9bc9866907f6c2b2ba9bd5/lib/vagrant/util/platform.rb#L81
- ...

**Comment by wiltaylor** [comment]
With this problem I recommend you don't try checking members of nested AD groups as this can fail on some high security multiple domain environments (inside the .net framework too so its hard to fix).

Possible solutions are to check the users access token to see if it has the correct rights or test something that only an admin could do.
