### ISSUE TITLE
file 'plugins/guests/redhat/cap/configure_networks.rb' should have 'extra_opts.merge(network)' instead of 'network.merge(extra_opts)'

### ISSUE THREAD

**Issue by fventuri-availity** [hashicorp/vagrant#8885]
When creating the template for a RedHat, guest, the code in  'plugins/guests/redhat/cap/configure_networks.rb' initializes the 'extra_opts' hash with the values from the previous network configuration (line 24):

extra_opts = machine.config.vm.networks[i].last.dup

These properties might include say the static IP address of the previous interface (in [:ip]).

The current interface properties are stored in the 'network' hash (including say its static IP address in network[:ip]).

When in lines 50-52 the 'TemplateRenderer.render()' method is invoked, the 'options' argument is generated by merging 'extra_opts' into 'network' as follows:

options: network.merge(extra_opts)

In the example above with the [:ip] item, this means that the value from extra_opts (which is the value of the static IP address from the previous interface) overwrites the correct value from network[:ip].

I think that merge should be done in the opposite order, i.e.:

options: extra_opts.merge(network)

This way in case of a conflict, the value from the 'network' hash wins over the value from 'extra_opts'.

Regards,
Franco Venturi

**Comment by chrisroberts** [comment]
Fixed via #10527 

Cheers!
