### ISSUE TITLE
vagrant-vmware-workstation plugin provider change?

### ISSUE THREAD

**Issue by cdenneen** [hashicorp/vagrant#8898]
Can someone confirm in the latest release of `vmware-workstation-plugin` the provider required in the `Vagrantfile` is now supposed to be `vmware_desktop` from `vmware_workstation`?

If this is so the vagrant binary itself still only takes `--provider vmware_workstation` and wasn't updated to accommodate the change. 

If this is true then I would think the `--provider` switch should match the `config.vm.provider = 'vmware_desktop'` required for `Vagrantfile`.

**Comment by chrisroberts** [comment]
Hi there, 

This is now available in the vagrant-vmware-desktop plugin. Please see this post for more information:

https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

Cheers!
