### ISSUE TITLE
Vagrant download using wrong $ATLAS_TOKEN after Vagrant Cloud Migration

### ISSUE THREAD

**Issue by Cbeck527** [hashicorp/vagrant#8929]
After migrating our organization to Vagrant Cloud, all of our developer accounts are getting a 404 when running `vagrant box update` with the new tokens. As far as I can tell, it's using an old Atlas URL and token value to hit the new API.

A temporary fix that we've found is destroying the box, deleting the downloaded box, and then re-running `vagrant up`, but that is a little heavy handed and you lose all of the data on the box.

### Vagrant version
```shell
$ vagrant --version
Vagrant 1.9.8
```

### Host operating system
macOS 10.11.5

### Guest operating system
Ubuntu 14.04LTS

### Vagrantfile
```ruby
...
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "dev"
  config.vm.box = "warbyparker/REDACTED_PRIVATE_BOX"
  config.vm.network :private_network, ip: "192.168.250.10"
  config.ssh.insert_key = false
end
...
```

### Debug output
_I've cleaned up some sensitive info, but you can see that_ `OLD_ATLAS_TOKEN` _and_ `NEW_ATLAS_TOKEN` _are both present in the debug output.

https://gist.github.com/Cbeck527/84cdaea3b90b176a295a40d321a02402

### Expected behavior
Vagrant uses the (brand new) `ATLAS_TOKEN` to query vagrant cloud API and ask for new box version

### Actual behavior
Vagrant uses the old `ATLAS_TOKEN` (cached somewhere?) to query vagrant cloud API and ask for new box version...

### Steps to reproduce
1. Migrate atlas account to Vagrant Cloud
2. Generate new token and `export ATLAS_TOKEN` in shell init file
3. `vagrant box update`

**Comment by akellehe** [comment]
@chrisroberts is there a known workaround for this?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
