### ISSUE TITLE
Vagrant on Docker provider cannot start on Fedora due to SELinux

### ISSUE THREAD

**Issue by amtlib-dot-dll** [hashicorp/vagrant#8943]
### Vagrant version
`Vagrant 1.9.1` from Fedora repo. No official binary is provided by Vagrant either, only a Centos one

### Host operating system
Fedora 26

### Guest operating system
Alpine

### Vagrantfile
```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "alpine"
  end
end
```

```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "alpine"
    d.volumes = ["/home/***/vagrant:/vagrant:Z"]
  end
end
```

### Debug output
Key output when using the first Vagrantfile
```
INFO subprocess: Starting process: ["/bin/docker", "run", "--name", "vagrant_default_***", "-d", "-v", "/home/***/vagrant:/vagrant", "alpine"]
```

Key output when using the second one
```
 INFO subprocess: Starting process: ["/bin/docker", "run", "--name", "vagrant_default_***", "-d", "-v", "/home/***/vagrant:/vagrant:Z", "-v", "/home/***/vagrant:/vagrant", "alpine"]
```

### Expected behavior
The container starts normally

### Actual behavior
The container fails to start

### Reason
In distributions made by RedHat, SELinux are enforced and processes spawned by docker are under a SELinux label unable to access the home path. There is a flag in docker as a workaround, that when `:Z` is appended to the `-v` parameter the host path will be relabeled and accessible from the container. However, the default volume `/vagrant` does not do so, and this behaviour cannot be overridden, rendering the Docker unusable in Fedora.

### Steps to reproduce
1. Create the Vagrantfile as above, under somewhere in `/home`
2. sudo vagrant up --debug

**Comment by soapy1** [comment]
Hi there,
Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!)  but fedora 26 is now at EOL https://fedoraproject.org/wiki/End_of_life. Testing with a more recent version of fedora and Vagrant revealed that this is not longer an issue. 

Cheers!
