### ISSUE TITLE
Vagrant up with ethereum-dev-env/vagrantfile fails

### ISSUE THREAD

**Issue by jamesray1** [hashicorp/vagrant#8956]
Note sure if this is this is a bug with vagrant itself, it seems like it could be with the vagrant file or Homestead, so I posted here as well: https://groups.google.com/forum/#!topic/vagrant-up/6YCXpBJmhsM

### Vagrant version
Vagrant 1.9.1

### Host operating system
Ubuntu 17.04 x64

### Guest operating system
Ubuntu 17.04 x64

### Vagrantfile
```ruby
$installScript = <<SCRIPT
sudo apt update && \
sudo apt install -y  git g++ make python-minimal silversearcher-ag && \
wget https://nodejs.org/dist/v8.3.0/node-v8.3.0-linux-x64.tar.xz && \
tar -xvf node-v8.3.0-linux-x64.tar.xz && \
sudo mv node-v8.3.0-linux-x64/bin/* /usr/bin/ && \
sudo mv node-v8.3.0-linux-x64/lib/* /usr/lib/ && \
cp /vagrant/.tmux.conf /home/vagrant/.tmux.conf
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/zesty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 1
  end

  config.vm.provision "shell", "inline": $installScript
end
```
The command completes successfully with a vanilla Vagrantfile (deleting any vagrant file in the current directory, running `vagrant init` then `vagrant up`—using an unmodified vagrantfile from vagrant)

### Debug output
https://gist.github.com/jamesray1/25e36c9be5fd9668ac7f9a099d2f9914

### Expected behavior
The `vagrant up` command is probably successful, completing with a zero exit status.

### Actual behavior
The `vagrant up` command is not successful, completing with a non-zero exit status.

### Steps to reproduce
1. Install VirtualBox: Zesty 64 virtualbox-5.1_5.1.26-117224-Ubuntu-zesty_amd64.deb. Direct download link [here](http://download.virtualbox.org/virtualbox/5.1.26/virtualbox-5.1_5.1.26-117224~Ubuntu~zesty_amd64.deb).
2. Install Vagrant, debian 64 bit: direct download [here](https://releases.hashicorp.com/vagrant/2.0.0/vagrant_2.0.0_x86_64.deb).
3. Open a terminal and run `vagrant init`.
4. Modify the vagrantfile, changing it to the one [here](https://github.com/jwasinger/ethereum-dev-env/blob/master/ethereumjs/Vagrantfile). Otherwise, running `vagrant up` with the unmodified vagrantfile works.
5. Run `vagrant up`.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
None that I have found.

**Comment by jamesray1** [comment]
On Gitter chat with @jwasinger.

**Comment by chrisroberts** [comment]
Can you please provide a gist with debug output enable:

```
vagrant up --debug
```

Thanks.

**Comment by jamesray1** [comment]
It's OK I've sorted it out. The gateway of my router doesn't have SSH enabled.
