### ISSUE TITLE
A VirtualBox machine with the name 'test-xenial-64' already exists.

### ISSUE THREAD

**Issue by jarrettj** [hashicorp/vagrant#8961]
Hi,

At least once a week, I have to recreate my dev environment because virtualbox does not know it has setup one already. I've searched the issue list and don't se anyone else with a similar issue. The folder is versioned controlled by git, but I ignore the .vagrant folder. 

Weird that vagrant up cannot boot the VM but vagrant destroy can delete it. 

### Vagrant version
Vagrant 1.9.1

### Host operating system
MacOS Sierra V10 

### Guest operating system
Ubuntu Xenial

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.vm.synced_folder "./", "/var/www/test", :id => "vagrant-root", nfs: true
    config.vm.provision :shell, path: "vagrant/setup.sh"

    config.vm.define 'test' do |node|
      node.vm.hostname = 'test.local'
      node.vm.network :private_network, ip: '196.168.22.22'
      node.hostmanager.aliases = %w(www.test.local)
    end

    config.vm.provider :virtualbox do |vb|
      vb.name = "test-xenial-64"
      host = RbConfig::CONFIG['host_os']
      if host =~ /darwin/
        mem = `sysctl -n hw.memsize`.to_i / 1024
      elsif host =~ /linux/
        mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i
      elsif host =~ /mswin|mingw|cygwin/
        mem = `wmic computersystem Get TotalPhysicalMemory`.split[1].to_i / 1024
      end

      mem = mem / 1024 / 4
      vb.customize ["modifyvm", :id, "--memory", mem]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--vram", "9"]
      vb.customize ["modifyvm", :id, "--usb", "on"]
      vb.customize ["usbfilter", "add", "0", "--target", :id, "--name", "android", "--vendorid", "0x18d1"]
    end

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.vm.provision :hostmanager
    config.vm.hostname = 'test.local'
    config.vm.network :forwarded_port, guest: 22, host: 32222
end
```

### Expected behavior
What should have happened?
A running vagrant vm

### Actual behavior
What actually happened?
A VirtualBox machine with the name 'test-xenial-64' already exists.
Please use another name or delete the machine with the existing
name, and try again.

### Steps to reproduce
1. vagrant reload

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
