### ISSUE TITLE
Vagrant 1.9.5 to 2.0.0 on WSL Creators Update version (4.4.0-43-Microsoft) asking for vagrant.exe

### ISSUE THREAD

**Issue by jkeslin-argonne** [hashicorp/vagrant#8962]
### Vagrant version
vagrant versions 1.9.5 to 2.0.0 show this behavior

### Host operating system
Windows 10 Enterprise 1703 (OS Build 15063.540)

### Guest operating system
Linux <HOSTNAME> 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a: 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

### Vagrantfile
```ruby

```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
[Gist Debug Output](https://gist.github.com/jkeslin-argonne/f7aacbf82000eb77ba2f8a02455e379a)

### Expected behavior

```
[jkeslin@HOSTNAME ~/tmp]$ vagrant global-status
id       name   provider state  directory
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.
```

### Actual behavior

```
[jkeslin@HOSTNAME ~/tmp]$ vagrant global-status
The executable 'vagrant.exe' Vagrant is trying to run was not
found in the PATH variable. This is an error. Please verify
this software is installed and on the path.
```

### Steps to reproduce
1. Update windows 10 to 1703
2. Install WSL 16.04 
3. Follow directions on wsl install page and install 1.9.5 or higher
4. run vagrant global-status or any vagrant command

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by jkeslin-argonne** [comment]
Discussion on vagrant google groups here: 

[](https://groups.google.com/forum/#!searchin/vagrant-up/WSL%7Csort:relevance/vagrant-up/NrC27OB5Pos/Q54UC2MIDAAJ)

**Comment by dezza** [comment]
https://github.com/hashicorp/vagrant/blob/acd8eb628402bc1684c3fb07193a8180769c28f0/lib/vagrant/util/platform.rb#L446-L447

Does this mean it is actually required to install both Windows and Linux versions of Vagrant?

I'm asking because elsewhere I see people mentioning it should work entirely as standalone in WSL and this comment and code seems to be the opposite?

**Comment by jkeslin-argonne** [comment]
Now try to run an ansible provisioning step in WSL now... does it allow you to run ansible?  If you only install windows vagrant, with a windows virtualbox, and then run from wsl, then once it gets to ansible provisioning step for me it complains about not being able to run ansible as a windows host control machine.  Ansible has to be run from vagrant on the wsl side which my guess is probably why the code wants it installed in both places.  

That was my experience anyways.

**Comment by chrisroberts** [comment]
@dezza That is only relevant if you have Vagrant installed within the Windows system _and_ within the WSL. If it is installed in both places it will require the same version be in use.

**Comment by dezza** [comment]
@chrisroberts please explain. I only ever installed the Windows version after numerous attempts at getting Linux-only to work and it ended up asking for vagrant.exe everytime. I never thought you should have both nor did I have before. When it should be asking for “vagrant” it was asking for “vagrant.exe” that is when only `vagrant` was installed in WSL.

**Comment by chrisroberts** [comment]
@dezza There was a missing check when validating versions that's fixed in PR #9107. Fix will be included in the next release.

**Comment by jkeslin-argonne** [comment]
So, for windows 10 with WSL, is it required to have both vagrant for linux and vagrant for windows installed now?  What is the correct way of running vagrant in windows 10 in WSL and is the documentation updated also?

**Comment by chrisroberts** [comment]
@jkeslin-argonne Having the `vagrant.exe` installed within Windows _should not_ be a prerequisite for installing and running Vagrant within the WSL. The missing path check is what is currently requiring it to be installed, and that is only the case when windows access from the WSL is enabled (`VAGRANT_WSL_ENABLE_WINDOWS_ACCESS` is set). The next release will correct the behavior.
