### ISSUE TITLE
Problem with Vagrant 2.0 and the vagrant-berkshelf plugin

### ISSUE THREAD

**Issue by gforghetti** [hashicorp/vagrant#8969]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
version 2.0

### Host operating system
MacOS Sierra 10.12.6

-------------------------------------------------------------------

I had Vagrant 1.9.8 installed, no problems.
Then installed Vagrant 2.0.
All Vagrant commands fail with the following error (including vagrant version):

**$ vagrant version
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

This Vagrant environment has specified that it requires the Vagrant
version to satisfy the following version requirements:

  ~> 1.5

You are running Vagrant 2.0.0, which does not satisfy
these requirements. Please change your Vagrant version or update
the Vagrantfile to allow this Vagrant version. However, be warned
that if the Vagrantfile has specified another version, it probably has
good reason to do so, and changing that may cause the environment to
not function properly.**

-------------------------------------------------------------------

I re-installed all plugins with vagrant plugin expunge --reinstall
Same error.
I removed all plugins, no error.
I narrowed down the problem to the vagrant-berkshelf plugin

If I uninstall the vagrant-berkshelf plugin, all is good.

**$ vagrant plugin uninstall vagrant-berkshelf
Uninstalling the 'vagrant-berkshelf' plugin...
Successfully uninstalled vagrant-berkshelf-5.1.1
🐳  gforghetti:~:$ vagrant version
Installed Version: 2.0.0
Latest Version: 2.0.0

You're running an up-to-date version of Vagrant!**

-------------------------------------------------------------------

If I reinstall the vagrant-berkshelf plugin, the error returns:

**$ vagrant plugin install vagrant-berkshelf
Installing the 'vagrant-berkshelf' plugin. This can take a few minutes...
Fetching: vagrant-berkshelf-5.1.1.gem (100%)
The Vagrant Berkshelf plugin requires Berkshelf from the Chef Development Kit.
You can download the latest version of the Chef Development Kit from:

    https://downloads.chef.io/chef-dk/

Installing Berkshelf via other methods is not officially supported.
Installed the plugin 'vagrant-berkshelf (5.1.1)'!
Post install message from the 'vagrant-berkshelf' plugin:

The Vagrant Berkshelf plugin requires Berkshelf from the Chef Development Kit.
You can download the latest version of the Chef Development Kit from:

    https://downloads.chef.io/chef-dk/

Installing Berkshelf via other methods is not officially supported.

🐳  gforghetti:~:$ vagrant version
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

This Vagrant environment has specified that it requires the Vagrant
version to satisfy the following version requirements:

  ~> 1.5

You are running Vagrant 2.0.0, which does not satisfy
these requirements. Please change your Vagrant version or update
the Vagrantfile to allow this Vagrant version. However, be warned
that if the Vagrantfile has specified another version, it probably has
good reason to do so, and changing that may cause the environment to
not function properly.**

-------------------------------------------------------------------
I go back and install vagrant 1.9.8 all is good.

So there is some issue with Vagrant 2.0 and the vagrant-berkshelf plugin.

**Comment by kikitux** [comment]
Hello

Seems is not Vagrant issue but a plugin issue

can you please monitor this:
https://github.com/berkshelf/vagrant-berkshelf/issues/319

Thanks
Alvaro.
