### ISSUE TITLE
Changing shared folder permissions from within virtual machine

### ISSUE THREAD

**Issue by axsuul** [hashicorp/vagrant#897]
I would like to change the shared folder permissions from within the virtual machine. So something like

```
chown some-random-user /vagrant
```

Doing this has no effect as the folder's owner as it remains to be `vagrant`. Is it possible?

**Comment by widoz** [comment]
Sorry to open this again, but I encountered the same problem within WordPress installation.

Apache run with `www-data:www-data` perms, but within the `Vagrantfile` I'm not able to set the properly perms for directories.

These doesn't help.
I running Vagrant 2, you can see configuration and provisioners here https://github.com/widoz/vagrant-lamp

```
config.vm.synced_folder "/var/www/html/wp",
    owner: "www-data", group: "www-data",
    mount_options: ["dmode=755","fmode=644"]

config.vm.provision "shell" do |s|
    s.inline = "mount -t vboxsf -o uid=`id -u www-data`,gid=`id -g www-data`,dmode=755,fmode=644 /var/www/html/wp"
end
