### ISSUE TITLE
Any significant disk usage try will throw an "nfs server <ip address>:<path> not responding" error

### ISSUE THREAD

**Issue by chrisvel** [hashicorp/vagrant#8975]
### Vagrant version
v2.0

### Host operating system
Ubuntu 17.10, kernel 4.12.6

### Guest operating system
openBSD 5.9, 6.0, 6.1

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  # Requires
  require "./paths"

  config.vm.define "bsdguest" do |worker|
    worker.vm.box = "kaorimatz/openbsd-5.9-amd64"
    worker.vm.network "private_network", ip: "192.168.1.42", netmask: '255.255.255.0'

    worker.vm.synced_folder HOST_DIR, QUEST_DIR, type: "nfs"

    worker.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    end

  end
end
```

### Debug output
```
nfs server 192.168.1.42:...... not responding
```

### Actual behavior
I am having a very disturbing issue with my Ubuntu host and openBSD guest - after some significant disk usage from the guest side, I get a message in Ubuntu: nfs server ...... not responding. Only way to revive from this is to restart the box. I have tried to restart the nfs-server in Ubuntu and also just upgraded from 17.04 but the issue persists. 

### Steps to reproduce
1. vagrant ssh boxname
2. Any demanding disk usage process - even trying to type "cd" and hit tab after a letter for autocompletion

**Comment by kikitux** [comment]
Is the network 192.168.1.x used anywhere?

What happens if you set the nfs manually without Vagrant, do you see same
pattern ?

**Comment by chrisvel** [comment]
No it doesn't and I haven't tried with setting up manually. Only thing I've tried is the opposite way - the guest as a server and the host as a client which I know that 100% works great.

**Comment by chrisvel** [comment]
Just to mention the same thing happens to other distros too. I've tried Ubuntu, Debian, Manjaro and Antergos. It seems like an issue of BSD with the host.

**Comment by briancain** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier 

Cheers!
