### ISSUE TITLE
[Enhancement] Please integrate the check for box updates earlier in the "vagrant destroy + vagrant up" flow.

### ISSUE THREAD

**Issue by MaxTranced** [hashicorp/vagrant#8976]
### Vagrant version
    vagrant --version
    Vagrant 1.9.1

### Host operating system
Ubuntu 16.04.1

### Expected behavior

    $ vagrant destroy
        dev-vm: Are you sure you want to destroy the 'dev-vm' VM? [y/N] y
    ==> dev-vm: Destroying VM and associated drives...
    ==> dev-vm: [vagrant-hostsupdater] Removing hosts
    ==> dev-vm: Checking if box 'ubuntu/trusty64' is up to date...
    ==> dev-vm: A newer version of the box 'ubuntu/trusty64' is available! You currently
    ==> dev-vm: have version '20170818.0.0'. The latest is version '20170831.0.0'. Run
    ==> dev-vm: `vagrant box update` to update.

### Actual behavior
    $ vagrant destroy
        dev-vm: Are you sure you want to destroy the 'dev-vm' VM? [y/N] y
    ==> dev-vm: Destroying VM and associated drives...
    ==> dev-vm: [vagrant-hostsupdater] Removing hosts
    
    $ vagrant up
    Bringing machine 'dev-vm' up with 'virtualbox' provider...
    ==> dev-vm: Importing base box 'ubuntu/trusty64'...
    ==> dev-vm: Matching MAC address for NAT networking...
    ==> dev-vm: Checking if box 'ubuntu/trusty64' is up to date...
    ==> dev-vm: A newer version of the box 'ubuntu/trusty64' is available! You currently
    ==> dev-vm: have version '20170818.0.0'. The latest is version '20170831.0.0'. Run
    ==> dev-vm: `vagrant box update` to update.
    ==> dev-vm: Setting the name of the VM: dev-vm
    ==> dev-vm: Clearing any previously set forwarded ports...
    ==> dev-vm: Clearing any previously set network interfaces...

It would be nice if `vagrant destroy` also checked for box updates. When a user wants to run a destroy/update cycle due to other reasons, this would give the user a chance to also update the box in the process.

Thank you!

**Comment by briancain** [comment]
Hey there! Thanks for opening an issue with Vagrant. I think ideally it might make more sense for you to run `vagrant box update` before the destroy command. I think for a lot of users it might find this behavior surprising when trying to destroy a box and having to wait for the box update to download. Again, thanks for the enhancement request, and sorry it took so long for us to take a look and respond! :pray:
