### ISSUE TITLE
Vagrant rsync gives timeout error during vagrant up

### ISSUE THREAD

**Issue by uarunach** [hashicorp/vagrant#8980]
Error facing during Vagrnat UP

52:03 [0mBringing machine 'alpha_cspersonbrief' up with 'aws' provider...[0m
06:52:06 [1;33m==> alpha_cspersonbrief: Warning! The AWS provider doesn't support any of the Vagrant
06:52:06 ==> alpha_cspersonbrief: high-level network configurations (`config.vm.network`). They
06:52:06 ==> alpha_cspersonbrief: will be silently ignored.[0m
06:52:06 [1m==> alpha_cspersonbrief: Starting the instance...[0m
06:52:07 [1m==> alpha_cspersonbrief: Waiting for instance to become "ready"...[0m
06:52:24 [1m==> alpha_cspersonbrief: Waiting for SSH to become available...[0m
06:52:35 [1m==> alpha_cspersonbrief: Machine is booted and ready for use![0m
06:52:41 [1m==> alpha_cspersonbrief: Rsyncing folder: /cygdrive/c/jenkins/workspace/MFWKFT-CSAPITEST/personbrief/ => /vagrant[0m
06:52:41 [1m==> alpha_cspersonbrief:   - Exclude: [".vagrant/", ".hg/", "tools/", "chef-server_11.1.6-1_amd64.deb", "stage-mfwk.pem", "init.bat", "run.bat", "setup.bat", "download_results.sh", "boot_awshost.sh", "start_vagrant.sh", ".vagrant", "boxes", "mfwkft_boxes", "results"][0m
06:53:06 ERROR warden: Error occurred: There was an error when attempting to rsync a synced folder.
06:53:06 Please inspect the error message below for more info.
06:53:06 
06:53:06 Host path: /cygdrive/c/jenkins/workspace/MFWKFT-CSAPITEST/personbrief/
06:53:06 Guest path: /vagrant
06:53:06 Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'c:/jenkins/workspace/MFWKFT-CSAPITEST/personbrief/stage-mfwk.pem' --exclude .vagrant/ --exclude .hg/ --exclude tools/ --exclude chef-server_11.1.6-1_amd64.deb --exclude stage-mfwk.pem --exclude init.bat --exclude run.bat --exclude setup.bat --exclude download_results.sh --exclude boot_awshost.sh --exclude start_vagrant.sh --exclude .vagrant --exclude boxes --exclude mfwkft_boxes --exclude results /cygdrive/c/jenkins/workspace/MFWKFT-CSAPITEST/personbrief/ ubuntu@10.52.140.93:/vagrant
06:53:06 Error: ssh: connect to host 10.52.140.93 port 22: Connection timed out

06:53:06 rsync: connection unexpectedly closed (0 bytes received so far) [sender]
06:53:06 rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1

**Comment by briancain** [comment]
Hi @uarunach - it looks like you're trying to bring up a vagrant machine in aws and the error you received was an ssh connection time out. Make sure you can reach your AWS host with the ip you provided vagrant.

Also please fill out the issue template provided so that we can get an idea of what version of vagrant, host, guest, etc that you are using. Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
