### ISSUE TITLE
Kernel panic when running angularjs with vagrant.

### ISSUE THREAD

**Issue by geolgau** [hashicorp/vagrant#8981]
Kernel panic in the VM (which runs on CentOS 7) appears after a random period of time (a couple of minutes, usually). 

Tested on multiple Linux and MacOS distributions (Ubuntu 16, CentOS 7 and MacOS Sierra).
This does not reproduce on Windows.

I am trying to run an angular js app which resides on my local CentOS 7 PC using vagrant. 
The VM that i create is also CentOS7, and i run the app using vagrant synchronization. The whole project folder is synchronized then built and ran on the VM.

To be noted that the node_modules folder which should be created in the project folder after we run npm install is being symlinked beforehand for improved performance. 

If i run npm install in the /project folder without symlinks it will take a very long time, angular is known to have very poor performance with vagrant synced folders.

###**Vagrantfile:**

```ruby
Vagrant.configure("2") do |config|

  config.vm.boot_timeout = 500
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true
  config.vm.network "forwarded_port", guest: 8000, host: 8000, auto_correct: true
  config.vm.network "forwarded_port", guest: 4200, host: 4200, auto_correct: true
  config.vm.network "private_network", ip: "10.1.1.100"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = 8000
     vb.cpus = 4
     vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
     vb.name = 'ConsoleVM'
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
 
  config.vm.synced_folder ".", "/project"

  #Build the angular UI
  config.vm.provision :shell,
    inline: "mkdir -p /node_modules &&  cd /project/ && sudo ln -s /node_modules node_modules && sudo npm install"

end
  #Bring up the angular UI
  config.vm.provision :shell,
    inline: "cd /project && sudo ng serve --host 0.0.0.0 --poll=2000"

end
```

Encountered behavior:

The vagrant up --provision runs fine, the UI comes up and running but after a couple of minutes I get this in the VM (virtualbox) console:

https://i.imgur.com/3hnPNr9.png

This happens all the time and randomly, and on multiple platform hosts, except on Windows.

Expected behavior:

Angular UI should run forever.

vagrant version: 1.9.7

VirtualBox Graphical User Interface
Version 5.1.22 r115126 (Qt5.6.1)
Host OS: CentOS 7 - also tested with MacOS and Ubuntu
Guest OS: CentOS 7

**Comment by cheeseplus** [comment]
VirtualBox 5.1.22 had a slew of regressions that were fixed - I'd upgrade to at least 5.1.26 if not the latest 5.1.28.

**Comment by briancain** [comment]
Hey @geolgau - if you could please upgrade your virtualbox installation and let us know if you still are encountering this issue. Thanks!

**Comment by geolgau** [comment]
This is not happening in 5.1.28 so far. 
In the meantime, I've found a better solution for my app, and that is using rsync synchronization. Way faster and more reliable.

Here is the line that uses it, if anyone wants it:

`  # Synced project files.
  config.vm.synced_folder ".", "/project", type: "rsync",
    exclude: ["setup/", ".git/",  node_modules/"],
    args: ["--verbose", "--archive", "-z"]`
