### ISSUE TITLE
Automatically install the Bash completion script

### ISSUE THREAD

**Issue by alb-i986** [hashicorp/vagrant#8987]
Would it be possible for the Debian package (and possibly the others too) to have the [Bash completion script](https://github.com/hashicorp/vagrant/blob/master/contrib/bash/completion.sh) automatically installed in the system, i.e. copied into `/etc/bash_completion.d/`?

AFAIU one needs to manually copy it him/herself, isn't it?

Thanks

References:
- #400

**Comment by rfults** [comment]
Terraform includes ```-install-autocomplete``` option. Maybe that can happen with all the Hashicorp tools?

**Comment by patr00n** [comment]
macos user has homebrew package `$ brew install vagrant-completion`

**Comment by Jeansen** [comment]
I'd also be happy to have this one installed automatically or at least have it mentioned in the official documentation. Some automation or option would be nice, especially with respect to the official installation guide that recommends NOT to use any package provided by different Linux distributions.
