### ISSUE TITLE
Hyper-V automatic checkpoints should default to disabled

### ISSUE THREAD

**Issue by PatrickLang** [hashicorp/vagrant#8988]
Hyper-V added a new feature that automatically takes checkpoints of VMs when they're started. When you stop the VM, it's deleted. [Link](https://blogs.technet.microsoft.com/virtualization/2017/04/20/making-it-easier-to-revert/)

However - if you're trying to manage state with Vagrant this could get in the way. Personally I'd prefer to rely on `vagrant destroy` or `vagrant provision -force` to get back to a known-good state. What do you think?

I confirmed that it conflicts with Packer's post-processor for Vagrant https://github.com/hashicorp/packer/issues/5371 and can give errors like this

### Vagrant version
Vagrant 2.0.0

### Host operating system
`gin *BuildLabEx*` returns 16291.0.amd64fre.rs3_release.170912-1708
This would apply to any Windows 10 insider build since around May

### Guest operating system
Windows Server Insider, build 16278
[Packerfile](https://github.com/StefanScherer/packer-windows/blob/my/windows_2016_insider.json)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "rs3_release_16296_insider_hyperv"
end
```

### Expected behavior
VM should have started

### Actual behavior
```none
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Importing a Hyper-V instance
    default: Please choose a switch to attach to your Hyper-V instance.
    default: If none of these are appropriate, please open the Hyper-V manager
    default: to create a new virtual switch.
    default:
    default: 1) HvsiIcs
    default: 2) DockerNAT
    default: 3) nat
    default: 4) Ethernet
    default: 5) Default Switch
    default:
    default: What switch would you like to use? 4
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

"Missing Checkpoint present."
```

### Steps to reproduce

1. Build [Packerfile](https://github.com/StefanScherer/packer-windows/blob/my/windows_2016_insider.json)
1. `vagrant box add --name windows_2016_insider windows_2016_insider_hyperv.box`
1. `vagrant init windows_2016_insider`
1. `vagrant up`

### References

https://github.com/hashicorp/packer/issues/5371

**Comment by PatrickLang** [comment]
I have a PR out for the Packer change. If auto checkpoint is disabled in Packer, that setting is preserved when it's imported from the box. With that in mind, maybe the enhancement should be "support enabling auto checkpoint" instead.

**Comment by zoredache** [comment]
Not certain if my comment on the closed PR gets seen.  The patch PatrickLang provided is incomplete and the only seems to function for Generation 1 VMs, and not Generation 2 VMs.  The DisableAutomaticCheckpoints only gets called in the generation 1 VM creation block.

**Comment by PatrickLang** [comment]
I have been working more with the [centos/7](https://app.vagrantup.com/centos/boxes/7) box recently which wasn't built with Packer. It still enables the automatic checkpoints. I should go ahead and fix this with an option in the hyperv provider.

Any thoughts on whether automatic checkpoints should default to on vs off? I'm in favor of off for consistency with the other providers.

**Comment by Deracination** [comment]
The same problem exists with 'vagrant package' CLI

I manually removed checkpoints from the VM using the Hyper-V manager in order to package it.
