### ISSUE TITLE
vmware_workstation provider fails to start VMs - bad path?

### ISSUE THREAD

**Issue by tuftedocelot** [hashicorp/vagrant#8993]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.0

### Host operating system
Arch

### Guest operating system
CentOS 7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  
  config.vm.provider "vmware_workstation" do |v|
      v.gui = true
      v.vmx["memsize"] = "1024"
  end

  config.vm.define "task01" do |host|
    host.vm.hostname = "task01"
  end

  config.vm.define "task02" do |host|
    host.vm.hostname = "task02"
  end

  config.vm.define "sql" do |host|
    host.vm.hostname = "sql"
  end

  config.vm.define "ui01" do |host|
    host.vm.hostname = "ui01"

    host.vm.provision "ansible" do |ansible|
      ansible.limit = "all"
      ansible.playbook = "playbook.yml"
      ansible.groups = {
        "task": ["task01", "task02"],
        "ui": ["ui01"],
        "database": ["sql"]
      }
    end
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/tuftedocelot/d8cdf98f3bd9fe0e70a58328942db353

### Expected behavior
The VMs specified in the Vagrantfile would start

### Actual behavior
vagrant fails to start any of the VMs with the following error:
```
/home/user/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-workstation-4.0.24/bin/vagrant_vmware_desktop_sudo_helper:20:in `stat': No such file or directory @ rb_file_s_stat - /opt/vagrant/embedded/lib/ruby/site_ruby/2.3.0 (Errno::ENOENT)
	from /home/user/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-workstation-4.0.24/bin/vagrant_vmware_desktop_sudo_helper:20:in `block in <encoded>'
	from /home/user/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-workstation-4.0.24/bin/vagrant_vmware_desktop_sudo_helper:19:in `delete_if'
	from /home/user/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-workstation-4.0.24/bin/vagrant_vmware_desktop_sudo_helper:19:in `<encoded>'
	from /home/user/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-workstation-4.0.24/bin/vagrant_vmware_desktop_sudo_helper:44:in `RGLoader_load'
	from /home/user/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-workstation-4.0.24/bin/vagrant_vmware_desktop_sudo_helper:44:in `<main>'
```

### Steps to reproduce
1. Run `vagrant up`

### References
N/A

**Comment by chrisroberts** [comment]
Hi @tuftedocelot. Thanks for reporting this issue! It will be fixed in the next release of the plugin. As a temporary workaround, creating the missing directory (`/opt/vagrant/embedded/lib/ruby/site_ruby/2.3.0`) should resolve the error.

Cheers!

**Comment by tuftedocelot** [comment]
Hey @chrisroberts, thanks for the reply. Looks like there are a series of dirs to create:

- `/opt/vagrant/embedded/lib/ruby/site_ruby/2.3.0/x86_64-linux`
- `/opt/vagrant/embedded/lib/ruby/vendor_ruby/2.3.0`
- `/opt/vagrant/embedded/lib/ruby/vendor_ruby/2.3.0/x86_64-linux`

**Comment by tuftedocelot** [comment]
To clarify, creating those dirs did let vagrant create the VMs. Thanks for looking into that!

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
