### ISSUE TITLE
Prevent modifications to /etc/network/interfaces

### ISSUE THREAD

**Issue by akarasulu** [hashicorp/vagrant#8998]
This is **NOT** a bug but rather an enhancement request. I would like to be able to disable vagrant from deleting default routes when making modifications to the /etc/network/interfaces file. For example, the following fragments are being added to the interfaces file:

```bash
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth2
iface eth2 inet dhcp
    post-up route del default dev $IFACE || true
#VAGRANT-END
```

Is there a workaround to prevent this behavior? It is wreaking havoc on my configuration. Thanks much.

**Comment by chrisroberts** [comment]
Vagrant must update this file to configure networks. You can set the `auto_config` option to `false` which might get you the behavior you are after. Cheers!
