### ISSUE TITLE
Failed to install any plugin

### ISSUE THREAD

**Issue by asif-alam** [hashicorp/vagrant#8999]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### 2.0.0
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Windows 10
This is the operating system that you run locally.

Error when trying to install any plugin:

conflicting dependencies childprocess (= 0.5.6) and childprocess (= 0.6.3)
  Activated childprocess-0.6.3
  which does not match conflicting dependency (= 0.5.6)

  Conflicting dependency chains:
    childprocess (= 0.6.3), 0.6.3 activated

  versus:
    childprocess (= 0.5.6)

  Gems matching childprocess (= 0.5.6):
    childprocess-0.5.6

**Comment by briancain** [comment]
Hi @asif-alam - Are you trying to install a vagrant plugin? Also if you could please provide us with the full command you're running, and share the output with the `--debug` flag used that would be very helpful, thank you!

**Comment by asif-alam** [comment]
hi @briancain,

I was trying to to install "vagrant plugin update vagrant-winrm"
I was successful when I used 1.8.1 but was failing when i was using 2.0.0

I will provide you debug details if it does not help you.

Thanks

**Comment by briancain** [comment]
Hi @asif-alam : Vagrant now does not require a plugin to use winrm. You should be able to communicate over winrm with just core vagrant. I believe this is likely why you are running into these dependency issues. Please give it a shot and let me know if you can use winrm without the plugin! Thanks.

**Comment by asif-alam** [comment]
I was trying check sample example for chef and tried to use kitchen list, may be related to kitchen-vagrant. Have you any idea? Please have a look below kitchen diagnose command:

PS C:\chef\learn-chef-2\cookbooks\learn_chef_iis> kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: WinRM Transport requires the vagrant-winrm Vagrant plugin to properly communicate with this Vagrant VM. Please install this plugin with: `vagrant plugin install vagrant-winrm' and try again.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

PS C:\chef\learn-chef-2\cookbooks\learn_chef_iis> kitchen diagnose
---
timestamp: 2017-09-28 04:03:48 UTC
kitchen_version: 1.17.0
instances:
  error:
    exception: "#<Kitchen::UserError: WinRM Transport requires the vagrant-winrm Vagrant
      plugin to properly communicate with this Vagrant VM. Please install this plugin
      with: `vagrant plugin install vagrant-winrm' and try again.>"
    message: 'WinRM Transport requires the vagrant-winrm Vagrant plugin to properly
      communicate with this Vagrant VM. Please install this plugin with: `vagrant
      plugin install vagrant-winrm'' and try again.'
    backtrace:
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:543:in
      `verify_winrm_plugin'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:355:in
      `load_needed_dependencies!'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/configurable.rb:52:in
      `finalize_config!'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/kitchen-vagrant-1.2.1/lib/kitchen/driver/vagrant.rb:167:in
      `finalize_config!'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:317:in
      `setup_driver'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/instance.rb:103:in
      `initialize'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/config.rb:240:in
      `new'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/config.rb:240:in
      `new_instance'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/config.rb:137:in
      `block in build_instances'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/config.rb:136:in
      `map'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/config.rb:136:in
      `with_index'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/config.rb:136:in
      `build_instances'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/config.rb:112:in
      `instances'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:112:in
      `filtered_instances'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command.rb:142:in
      `parse_subcommand'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command/diagnose.rb:53:in
      `load_instances'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command/diagnose.rb:32:in
      `block in call'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command/diagnose.rb:73:in
      `record_failure'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/command/diagnose.rb:32:in
      `call'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/cli.rb:53:in
      `perform'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/cli.rb:143:in
      `diagnose'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in
      `run'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in
      `invoke_command'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/cli.rb:334:in
      `invoke_task'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in
      `dispatch'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in
      `start'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/bin/kitchen:13:in
      `block in <top (required)>'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/lib/kitchen/errors.rb:171:in
      `with_friendly_errors'
    - C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.17.0/bin/kitchen:13:in
      `<top (required)>'
    - C:/opscode/chefdk/bin/kitchen:279:in `load'
    - C:/opscode/chefdk/bin/kitchen:279:in `<main>'
PS C:\chef\learn-chef-2\cookbooks\learn_chef_iis>

**Comment by asif-alam** [comment]
Hi @briancain I am creating a new virtual box which is taking time for updates, will let you know once finished

**Comment by asif-alam** [comment]
Hi @briancain, 

Thanks a lot for your cooperation. Actually I was trying to do some test on chef test-kitchen with vagrant and as part of that I was trying to create a new virtual box using following command but fails for WinRM (timeout)

PS C:\chef\packer-box\packer-templates>  packer build -force -only virtualbox-iso vbox-2012r2.json
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying Guest additions
    virtualbox-iso: Downloading or copying: file:///C:/Program%20Files/Oracle/VirtualBox/VBoxGuestAdditions.iso
==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://care.dlservice.microsoft.com/dl/download/6/2/A/62A76ABB-9990-4EFC-A4FE-C7D698DAEB96/9600.17
050.WINBLUE_REFRESH.140317-1640_X64FRE_SERVER_EVAL_EN-US-IR3_SSS_X64FREE_EN-US_DV9.ISO
==> virtualbox-iso: Deleting previous output directory...
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying files flatly from floppy_files
    virtualbox-iso: Copying file: answer_files/2012_r2/Autounattend.xml
    virtualbox-iso: Copying file: scripts/postunattend.xml
    virtualbox-iso: Copying file: scripts/boxstarter.ps1
    virtualbox-iso: Copying file: scripts/PackerShutdown.bat
    virtualbox-iso: Copying file: scripts/package.ps1
    virtualbox-iso: Copying file: scripts/SetupComplete-2012.cmd
    virtualbox-iso: Copying file: scripts/Test-Command.ps1
    virtualbox-iso: Done copying files from floppy_files
    virtualbox-iso: Collecting paths from floppy_dirs
    virtualbox-iso: Resulting paths from floppy_dirs : []
    virtualbox-iso: Done copying paths from floppy_dirs
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 4050)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1506635525 --memory 2048
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1506635525 --vram 48
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1506635525 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 10s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for WinRM to become available...

**Comment by asif-alam** [comment]
Hi @briancain,

I was able to create the virtual box using packer properly and which use winrm and I think test-kitchen has some dependency with winrm plugin because I was getting following error:

PS C:\chef\packer-box\learn-chef\cookbooks\learn_chef_iis> kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: WinRM Transport requires the vagrant-winrm Vagrant plugin to properly communicate with this Vagrant VM.
Please install this plugin with: `vagrant plugin install vagrant-winrm' and try again.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

Thanks
Asif

**Comment by chrisroberts** [comment]
@asif-alam Would you please try uninstalling Vagrant and then re-installing it. It looks like there are some old dependency versions still installed that are causing a conflict. The uninstall process should properly delete the related directory and the fresh install should then stop generating this error.

**Comment by asif-alam** [comment]
@chrisroberts I think this is not related to vigrant, the issue with chef test kitchen

Thanks
Asif
