### ISSUE TITLE
vagrant up not working while git bash is in admin mode, works well in normal mode

### ISSUE THREAD

**Issue by barunTayenjam** [hashicorp/vagrant#9001]
### Vagrant version
2.0

### Host operating system
Windows 10

### Guest operating system
Ubuntu 16.04 LTS

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.9.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON.parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false
    end

    if defined? VagrantPlugins::HostsUpdater
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    end
end
```

### Debug output
https://gist.github.com/barunTayenjam/a61eaa2b1fe9f544067c0418271b06ad

### Expected behavior
Running vagrant up in Git Bash from administration mode giving error

### Actual behavior
Running vagrant up in Git Bash from administration mode giving error

### Steps to reproduce
1. Run Git Bash as Admin mode in windows 10
2. Run Vagrant up

I am basically trying to solve this issue https://stackoverflow.com/questions/46409402/symlink-protocol-error-in-vagrant-2-0

**Comment by briancain** [comment]
Hi @barunTayenjam - if you could, please provide the minimal vagrantfile that reliably reproduces this error and we can try to reproduce it on our end. Thank you!

**Comment by barunTayenjam** [comment]
Hi @briancain, thanks for looking up on this, below is the minimal vagrantfile, I got it by deleting the old vagrant file and running vagrant init --minimal

====
Vagrant.configure("2") do |config|
  config.vm.box = "base"
end
====

I am seeing this error now 

===

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/HP/Homestead/base

**Comment by briancain** [comment]
@barunTayenjam - The error you received there was because you didn't give the `init` command a vagrant box to use. I recommend either just trying with `config.vm.box = "hashicorp/precise64"` or trying to trim down your original vagrantfile. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
