### ISSUE TITLE
vmware fusion 10.0.0 support

### ISSUE THREAD

**Issue by tcataldo** [hashicorp/vagrant#9007]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
$ vagrant -v
Vagrant 2.0.0
$ vagrant plugin list
vagrant-hostmanager (1.8.7)
vagrant-share (1.1.9, system)
vagrant-vmware-fusion (4.0.24)

### Host operating system
osx 10.13 high sierra 

### Guest operating system
ubuntu xenial, but it is not relevant

### Expected behavior
The VM starts in vmware fusion 10.

### Actual behavior
Bringing machine 'mapi' up with 'vmware_fusion' provider...
This provider only works with VMware Fusion 8 or lower. You have
Fusion '10.0.0'. Please install the proper version of VMware
Fusion and try again.

### Steps to reproduce
1. upgrade vmware fusion to 10
2. vagrant up

**Comment by ndobbs** [comment]
I too like to stay on the latest edge of software - purchased and upgraded both VMware Fusion, also upgraded to Vagrant 2.0 today. Can't run my dev environment without downgrading now.

**Comment by chrisroberts** [comment]
Release with Fusion 10 and Workstation 14 support will be coming next week.

**Comment by japecci** [comment]
any update as to when the plugin update will be coming out?

**Comment by tmpkn** [comment]
Any update re Fusion 10 support?

**Comment by LewisTheobald** [comment]
Hi @chrisroberts - you said 10 days ago it'll be 'coming next week', do you have an update on this? Eager to actually be able to fire up and use our boxes again.

**Comment by tmpkn** [comment]
We're in the same boat here.

**Comment by daniel-chris-lucas** [comment]
Same here, keep refreshing the VMWare integration page but still no update.

**Comment by punkrokk** [comment]
Yea - I could be in this boat, but I'm waiting for the plugin update to upgrade. Keep up the good work guys.

**Comment by yakovzaytsev** [comment]
@chrisroberts when will you release ?

**Comment by terion-name** [comment]
@chrisroberts any updates on this? work had stopped :(

**Comment by ndobbs** [comment]
@chrisroberts Looking for an update even if the timeline is out further than originally anticipated. I read Fusion 10 has a new API so I'm assuming development is more complex than originally anticipated. 

Appreciate all the hard work you all put into this.

**Comment by tmpkn** [comment]
I second that - a realistic ETA would be much appreciated.

**Comment by embusalacchi** [comment]
Any ETA?

**Comment by jsco2t** [comment]
Is there anything that you need help with to close this issue out? Beta testers? Bug fixes?

**Comment by m4rkw** [comment]
Hey guys, I figured out how to hack 4.0.24 into working with Fusion 10.

```
$ cd ~/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-fusion-4.0.24/lib/vagrant-vmware-fusion
$ mv -f driver.rb driver.rb.orig
$ cat > driver.rb <<EOF
load File.dirname(__FILE__) + "/driver.rb.orig"

module DriverVersionHack
  def verify!
  end
end

class HashiCorp::VagrantVMwarefusion::Driver::Fusion
  prepend DriverVersionHack
end
EOF
$ cd "/Applications/VMware Fusion.app/Contents/Library"
$ sudo ln -s services/Open\ VMware\ Fusion\ Services
```

This monkey patches the ruby code for the plugin to skip the version check and creates a symlink to the Services binary which was moved in v10.  After doing this I'm able to vagrant up and vagrant ssh into the running vm.

YMMV, I'm sure there's probably a bunch of stuff that won't work but maybe this will help some people out until Hashicorp release proper v10 support.

**Comment by daniel-chris-lucas** [comment]
@mitchellh thanks for the update. Is there a estimated release date? Keep up the great work

**Comment by tisba** [comment]
Thanks for the clarification, @mitchellh.

**Comment by mitchellh** [comment]
The target currently is October 18, earlier if we can. 

I feel really bad that we've taken longer than usual here and I'm sorry, so I also talked with folks over here and we'll be giving a special discount code on this issue for the people who have been patiently waiting for this so that instead of the normal upgrade price ($19 instead of $39). 

Also, just as we've done in past years, anyone who purchased the plugin in the 60 days leading up to the VMware 10 support will be upgraded for free on release day. They only have to redownload their license. 

I'll post the discount code and any more news as it comes.

**Comment by ndobbs** [comment]
@mitchellh This is great, thanks so much for the updates and the offer on the coupons. Hashicorp rocks!

**Comment by jjl** [comment]
How come this is a paid upgrade if the plugin works apart from the version check?

**Comment by StefanScherer** [comment]
Thanks @mitchellh, I also wait for that update, but I'm lucky and still on Fusion 8.5.8 so I'm operable until the new plugin is available. Keep up the good work!!

**Comment by m4rkw** [comment]
@jjl it probably doesn't work 100%, and the security issue mentioned is real.

**Comment by mitchellh** [comment]
@jjl The upgrade fees enable us to responsibly sustain the ongoing maintenance of not just the plugin but the core of Vagrant itself. We only ever introduce major upgrades for new versions of VMware since that itself also comes with an upgrade cost. In most cases, 90+% of the plugin does work with a version check change. As I haven't been working directly on this release, I'm not sure where any compatibility issues exists. But there hasn't been a new version of VMware that hasn't introduced subtle bugs yet (typically networking) and the maintenance to resolve those is what these fees help sustain.

Additionally, we've continued to release new features into the VMware plugin over time. For example earlier this year we introduced linked clone support. This is a major feature enabled by VMware 8 but we didn't charge an upgrade fee for the feature, only the VMware 8 support 6 months earlier. So these fees also help pay for the team to do work such as that. 

Thanks for helping support Vagrant. 😄

**Comment by barkingfoodog** [comment]
@mitchellh I know Fusion Pro offers some new APIs for administering VMs and various features, including NAT. Will the new plug-in take advantage of any of these? I know there have been periodic issues with the plugin configuring NAT especially ( #7948 #8642 #9047 ). It seems that letting VMWare mange its configuration via an API would be safer than hacking its config files directly.

**Comment by mitchellh** [comment]
@barkingfoodog Yep, those are the sorts of things we will be looking into once we get base compatibility updated and released. Networking (and the lack of a real API) has been a real challenge for the plugin for many years, so if the updates are able to support our usage, we will use them.

**Comment by barkingfoodog** [comment]
@mitchellh Awesome! The vagrant-vmware plugin was the first thing I thought of when I saw those release notes, and it sure seems the API feature had projects just like this in mind. I love seeing compatible technologies move towards each other.

**Comment by satyadeep** [comment]
Thanks for sharing the updates @mitchellh . Have been holding on to Fusion 8.5 and waiting eagerly for the update to the plugin. Keep up the great work!

**Comment by aspraveen** [comment]
Thanks @mitchellh for the comments. I was also regularly checking the vagrantup site for the new release as I am stuck after upgrading to vmware fusion 10. Will wait then..

**Comment by ndobbs** [comment]
Thank you team for honoring your timeline. Really appreciate all of the hard work you put into supporting fusion 10.x!

It was nice to see this: 
`Fetching: vagrant-vmware-fusion-4.0.25.gem (100%)`

**Comment by blopker** [comment]
Looks like there was a `vagrant-vmware-fusion` update today, but I don't think it added Fusion 10 support. Just in case anyone is confused. 😄  

Changelog here: https://github.com/hashicorp/vagrant-plugin-changelog/blob/master/vagrant-vmware-changelog.md

**Comment by signed8bit** [comment]
Why the thumbs down @embusalacchi? Not super helpful without comments.

**Comment by mitchellh** [comment]
The new VMware version support and all supporting requirements were merged just after that release. The primary engineer behind it had to attend to family matters, but we're planning a release tomorrow.

**Comment by terion-name** [comment]
@mitchellh how to upgrade licence?

**Comment by m4rkw** [comment]
@terion-name you can't yet, the version that support for Fusion 10 has not been released yet.

**Comment by m4rkw** [comment]
with 4.0.25 installed if I run:

````
$ vagrant plugin update
````

it asks for authentication every time and seems to reinstall the plugin despite the version not having changed.  anyone else seeing this?

**Comment by ghsolutions** [comment]
i run into problems installing the updated plugin 4.0.25:

https://gist.github.com/ghsolutions/d9cfcbfd1912b387cf189f52ed92afb0

**Comment by m4rkw** [comment]
@ghsolutions the plugin name is "vagrant-vmware-fusion" not "vmware"

**Comment by ghsolutions** [comment]
Ok, mea culpa thank you :)

**Comment by ndobbs** [comment]
Looks like it has been released `Updated 'vagrant-vmware-fusion' to version '5.0.0'!`

@mitchellh any update on the coupon codes so I can upgrade my license? 

```
You're using a license that doesn't allow you to use the installed
version of Fusion. This error message occurs if you upgraded Fusion
without also upgrading your license. Please upgrade your license to
unlock features and support for the latest version of VMware Fusion,
or revert your version of Fusion back to the supported version.
You can upgrade your license by going to the following URL:

http://license.hashicorp.com/upgrade/vmware
```

Thanks for all of your help and support.

**Comment by sergeyklay** [comment]
@mitchellh Could you please create a small release instruction/note about upgrading, license, supported version, etc. Personally I bought VMW 10, then bought plugin license and had to do downgrade VMWare license from 10 to 8. Right now I have no idea is it possible upgrade for free from 8 to 10 and should I do this or plugin is not ready yet

**Comment by ruettimac** [comment]
When buying a new license, the only option is vmware fusion 8 or below (macos).

**Comment by m4rkw** [comment]
this is true DevOps releasing in action :P

**Comment by mitchellh** [comment]
Hey all, the VMware plugin has been updated! There are still other pages being updated but the core supporting infrastructure is all there.

Valid 10/18 to 10/31 (UTC), we've created the coupon code `VMW10-SORRY` (😅 😅) to allow prior Vagrant VMware license owners to upgrade for $19 rather than $39. This is to apologize to those on this thread who have been patiently waiting for this which took longer than usual. 

And as the upgrade page says, anybody who purchased after August 8, 2017 has already been automatically upgraded for free. If you find your confirmation email and redownload then your license is ready to go with the new versions of VMware.

**Comment by m4rkw** [comment]
@mitchellh I just put that discount code in and got charged the full price for a new license

**Comment by terion-name** [comment]
@mitchellh purchase page still says that plugin is for VMware 8 and below. Didn't update yet?

**Comment by terion-name** [comment]
@mitchellh and discount drops immediately after applying

**Comment by mitchellh** [comment]
@m4rkw Email support and you'll be refunded. For anyone else, please verify the checkout price before finalizing the purchase! I'll look into the code, it should work for anyone using an email address that has purchased the license before.

@terion-name Yes that page hasn't been updated yet.

**Comment by tj-anderson** [comment]
I was able to upgrade with the promo code and it worked as expected.

**Comment by terion-name** [comment]
@mitchellh I've entered my email (mail@terion.name) on purchase screen and it set all the info. Then I've applied upgrade coupon from upgrade page. Then I've added second coupon, price changed to 19, but immediately all coupons dropped and price set to full

**Comment by mitchellh** [comment]
@terion-name Ah, only one discount code can be applied. I'll make note of that in my comment above. It appears the behavior when applying multiple is to drop them all and reset the price. That's out of our control unfortunately!

**Comment by terion-name** [comment]
@mitchellh applying only `VMW10-SORRY` changes nothing — it is dropping

**Comment by terion-name** [comment]
https://www.dropbox.com/s/ui4u7oug95rzgxr/screencast%202017-10-18%2019-02-26.mp4?dl=0

**Comment by mitchellh** [comment]
We're looking into it. We're seeing some orders come in successfully so we're not sure yet. We're running through the process now.

**Comment by mitchellh** [comment]
@terion-name Your email doesn't exist as a prior owner in our shopify history. The coupon code is restricted to prior owners for the upgrade. It doesn't affect new owners. Sorry if I didn't make that clear, but I did note in both my comments mentioning the coupon code that its for "upgrades"! When we ran through it with a new email we saw the same behavior as you.

If this isn't correct, please email our support and we'll work with you to look up your email or diagnose why it may not exist in our customer DB.

**Comment by sergeyklay** [comment]
I'm so sorry for annoying questions but... 

> anybody who purchased after August 8, 2017 has already been automatically upgraded for free. If you find your confirmation email and redownload then your license is ready to go with the new versions of VMware.

My invoice is from Oct 5, 2017 and I don't see any email. Is it ok?

**Comment by chrisroberts** [comment]
@sergeyklay Yes, your license was automatically upgraded. You can download the updated license from the link in your original order confirmation email.

**Comment by terion-name** [comment]
@mitchellh I own a licence for previous version and it was bought on mail@terion.name address at April 5 2017

**Comment by shawnho1018** [comment]
After applying the coupon code, I see the price drop but refresh back to the original 79 dollars before I can further make the purchase. Could anyone please check the problem?

**Comment by vdanen** [comment]
Same issue here.  Add the second coupon to get it to the correct price and they both get removed.

**Comment by chrisroberts** [comment]
Hi everyone. The discount code has been updated and should resolve these "Customer information does not meet the requirements" messages being returned.

**Comment by back-2-95** [comment]
I got this question from our employees. Is Fusion 10 Pro needed for Vagrant or is normal version enough?

**Comment by mitchellh** [comment]
@terion-name See what @chrisroberts said above ^ and try again. We've been relaxing some of the constraints on the coupon and we hope it'll work for more now. Its been tricky to diagnose since it has been clearly working for some and not others and there are only so many knobs we have to turn with it, haha.

**Comment by terion-name** [comment]
@mitchellh @chrisroberts worked, thank you!

**Comment by shawnho1018** [comment]
Works for me too. Thanks!

**Comment by chrisroberts** [comment]
@back-2-95 Fusion Pro would be recommended. Fusion lacks some features like linked clones and advanced networking that the Vagrant provider utilizes. You would need to disable those things in your Vagrantfile to get things working as expected.

**Comment by ndobbs** [comment]
I'm having issues with `HGFS`, I can't seem to mount any ShareFolders, should I move this discussion to a new issue? 

```
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "/Users/ndobbs/shspace/projects/infrastructure/dev-testing/.vagrant/machines/security_testing/vmware_fusion/ee48833a-2761-4b25-b376-2d9dfbc8d821/ubuntu-14.04-amd64.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

Stderr:
```

**Comment by onedsc** [comment]
Hitting https://github.com/hashicorp/vagrant/issues/9047 - currently a show stopper for me

**Comment by chrisroberts** [comment]
@ndobbs Yes, please create a new issue. 

and I'm going to close this as the original issue is now resolved. Cheers!

**Comment by ndobbs** [comment]
@onedsc I ran into this too, I deleted the `.vagrant` directory in my projects folder order to get it working again.

**Comment by onedsc** [comment]
@ndobbs I deleted the .vagrant dir in my project file and I get the same isssue:
Bringing machine 'devtest0' up with 'vmware_fusion' provider...
==> devtest0: Cloning VMware VM: 'illumio/centos-7.3'. This can take some time...
==> devtest0: Verifying vmnet devices are healthy...
==> devtest0: Deleting the VM...
/Users/dcook/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-fusion-5.0.0/lib/vagrant-vmware-fusion/helper/nat_conf.rb:169:in `initialize': Permission denied @ rb_sysopen - /Users/dcook/.vagrant.d/data/vmware/vmware-nat.json.lock (Errno::EACCES)

**Comment by chrisroberts** [comment]
See here: https://github.com/hashicorp/vagrant/issues/9047#issuecomment-337672998

**Comment by onedsc** [comment]
@chrisroberts - Thanks that seems to have fixed it

**Comment by eatstoomuchjam** [comment]
Attempting to install the latest version of `vagrant-vmware-fusion` over ssh fails.  Installing while logged in from the GUI works.  It seems to have to do with how you're escalating privileges:

```
bash-3.2$ vagrant plugin install vagrant-vmware-fusion
Installing the 'vagrant-vmware-fusion' plugin. This can take a few minutes...
Building native extensions.  This could take a while...

Vagrant is installing the VMware plugin which requires
root access. You may be prompted for your password to
complete setup.

0:1252: execution error: The administrator user name or password was incorrect. (-60007)
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

    current directory: /Users/danarchy/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-fusion-5.0.0/ext/vagrant-vmware-desktop
/opt/vagrant/embedded/bin/ruby -r ./siteconf20171018-13889-egbfrw.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/vagrant/embedded/bin/$(RUBY_BASE_NAME)

extconf failed, exit code 1

Gem files will remain installed in /Users/danarchy/.vagrant.d/gems/2.3.4/gems/vagrant-vmware-fusion-5.0.0 for inspection.
Results logged to /Users/danarchy/.vagrant.d/gems/2.3.4/extensions/x86_64-darwin-13/2.3.0/vagrant-vmware-fusion-5.0.0/gem_make.out
```

**Comment by mafrosis** [comment]
Thanks Hashicorp guys for continuing to support VMWare and how you've handled all the complaints in this thread!  🎉 ❤️ 

@back-2-95 I've been using Vagrant and Fusion since v4 - I've never used Pro or needed to have special commands in my Vagrantfile to support the normal version. I'd wager the majority of people out there are _not_ running Pro. YMMV, of course.

**Comment by Fred78290** [comment]
Thanks Hashicorp, work fine now :) The coupon have been applied for me with 19USD value. (Need to verify the good charge with my bank :P)

In reponse of eatstoomuchjam , I got the same Issue

to solve it juste change the ownership of /Users/$USERNAME/.vagrant.d/data/vmware/, it's owned by root.

Cheers

**Comment by embusalacchi** [comment]
I was running into a strange issue after getting the new plugin and creating machines with packer.  If you're having an issue installing a new VM w/vagrant, the new plugin, and OSX 10.13 please check out this link - https://communities.vmware.com/thread/573147.  I wasted a ton of time on this so wanted to post here for everyone.

**Comment by Fred78290** [comment]
Got also this issue :P
Solved by doing these
1 - Remove VirtualBox (incompatible with Fusion)
2 - Reboot and hit shit key at boot to force the cache kernel extension to be rebuild, (take a long)
3 - After don't logging, reboot again
4 - Log in account and execute these command
sudo kextcache -system-prelinked-kernel
sudo kextcache -system-caches
