### ISSUE TITLE
The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong.

### ISSUE THREAD

**Issue by ArminBeda** [hashicorp/vagrant#9016]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
$ vagrant -v
Vagrant 1.9.6

### Host operating system
Microsoft Windows 7 Enterprise

### Guest operating system
Ubuntu (64-bit)

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", guest: 80, host: 9080
  config.vm.network "forwarded_port", guest: 8080, host: 8181

  config.vm.network "private_network", ip: "192.168.33.10"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
  end

  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo 'export http_proxy=http://proxy.de.softlab.net:8080' >> .bashrc
    echo 'export https_proxy=http://proxy.de.softlab.net:8080' >> .bashrc
    echo 'export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre' >> .bashrc

    sudo su
    echo 'Acquire::http::Proxy "http://proxy.de.softlab.net:8080";' >> /etc/apt/apt.conf.d/08proxy
    echo 'Acquire::https::Proxy "http://proxy.de.softlab.net:8080";' >> /etc/apt/apt.conf.d/08proxy
    echo 'Acquire::ftp::Proxy "http://proxy.de.softlab.net:8080";' >> /etc/apt/apt.conf.d/08proxy

    mkdir /etc/systemd/system/docker.service.d
    echo '[Service]' >> /etc/systemd/system/docker.service.d/http-proxy.conf
    echo 'Environment="HTTP_PROXY=http://proxy.de.softlab.net:8080/"' >> /etc/systemd/system/docker.service.d/http-proxy.conf

    export http_proxy=http://proxy.de.softlab.net:8080
    export https_proxy=http://proxy.de.softlab.net:8080

    echo 'deb https://apt.dockerproject.org/repo ubuntu-xenial main' | sudo tee /etc/apt/sources.list.d/docker.list

    apt-get update
    apt-get install -y software-properties-common apt-transport-https ca-certificates
    apt-add-repository ppa:ansible/ansible -y
    apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    apt-get update
    apt-get install -y ansible=2.2.1.0-1ppa~xenial openjdk-8-jdk-headless=8u111-b14-2ubuntu0.16.04.2 maven=3.3.9-3
    apt-get -o Dpkg::Options::="--force-confold" install -y docker-engine=1.12.3-0~xenial

    usermod -aG docker ubuntu

    mkdir /home/ubuntu/.m2
    cp /vagrant/settings.xml /home/ubuntu/.m2/
    cp /vagrant/.gitconfig /home/ubuntu/
    chown -R ubuntu:ubuntu /home/ubuntu/.m2 /home/ubuntu/.gitconfig
  SHELL
end
```

### Debug output
https://github.com/ArminBeda/DebugOutpug/blob/master/DebugFile

### Expected behavior
The command `vagrant up` should work without error.

### Actual behavior
At the end (as you see in the DebugFile) I am getting the error 
**

> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

**

and during the process I am getting other errors as well, eg.:

> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 127.0.0.1:2222
>     default: SSH username: ubuntu
>     default: SSH auth method: password
>     default: Warning: Connection aborted. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection aborted. Retrying...
>     default: Warning: Remote connection disconnect. Retrying...
>     default: Warning: Connection aborted. Retrying...
>     default: Warning: Connection reset. Retrying...
>     default: Warning: Connection aborted. Retrying...
>     default: Warning: Authentication failure. Retrying...
>     default:
>     default: Inserting generated public key within guest...
>     default: Removing insecure key from the guest if it's present...
>     default: Key inserted! Disconnecting and reconnecting using new SSH key...

### Steps to reproduce
1. Based on [this ](https://github.com/hashicorp/vagrant/issues/1659)article I tried to change in  /etc/sudoers the following:

vagrant ALL=(ALL) NOPASSWD:ALL
Defaults:vagrant !requiretty

But on Windows I could not find /etc/sudoers

2. Tried vangrant reload --provision.  Getting the same results.

3. Tried simply vagrant reload. Getting the same results.

**Comment by briancain** [comment]
Hi @ArminBeda - the error you are receiving is not a Vagrant bug. There is an issue with one of your provision scripts. There is no file `/vagrant/settings.xml` on your guest machine and thus the command `cp /vagrant/settings.xml /home/ubuntu/.m2/` fails, which is how you received a non-zero exit code in your shell script. This also looks to be true for the other file you're trying to `cp` or `chown`.

```
==> default: cp: cannot stat '/vagrant/settings.xml'
==> default: : No such file or directory
```

I'm going to go ahead and close this since it is not a Vagrant bug. Thanks!

**Comment by ArminBeda** [comment]
Hi @briancain, all right thank you for the insight. Could you give me a tip where should I looking for to find a solution for this bug?

**Comment by briancain** [comment]
@ArminBeda It looks like your Vagrant file expects `settings.xml` and `.gitconfig` to exist on your guest at `/vagrant/settings.xml` and `/vagrant/.gitconfig` so I recommend figuring out where those files should actually exist. If you're still stuck, please send an email to the [vagrant up](https://groups.google.com/forum/#!forum/vagrant-up) mailing list and more people should be able to help you there. Thanks!
