### ISSUE TITLE
Multi-VM public network with same ports not performing as expected

### ISSUE THREAD

**Issue by deepvoice** [hashicorp/vagrant#9018]
### Vagrant version
Vagrant 1.9.7

### Host operating system
Ubuntu 16.04 LTS

### Guest operating system
Ubuntu 16.04 LTS

### Expected behavior
VM #1  (note: eth1:1)

config.vm.network "public_network", bridge: "eth1", ip: "x.x.x.10", netmask: "255.255.255.
128", autoconf: "false"
 config.vm.network "forwarded_port", guest: 25, host: 25, host_ip: "x.x.x.10"
VM #2  (note: eth1:2)
config.vm.network "public_network", bridge: "eth1", ip: "x.x.x.11", netmask: "255.255.255.
128", autoconf: "false"
 config.vm.network "forwarded_port", guest: 25, host: 25, host_ip: "x.x.x.11"

Also tried
VM #1  
config.vm.network "private_network", ip: "10.10.10.10"
config.vm.network "public_network", bridge: "eth1", ip: "x.x.x.10", netmask: "255.255.255.
128", autoconf: "false"
 config.vm.network "forwarded_port", guest: 25, host: 25, host_ip: "x.x.x.10", guest_ip: "10.10.10.10"

VM #2 
config.vm.network "private_network", ip: "10.10.10.10"
config.vm.network "public_network", bridge: "eth1", ip: "x.x.x.11", netmask: "255.255.255.
128", autoconf: "false"
 config.vm.network "forwarded_port", guest: 25, host: 25, host_ip: "x.x.x.11", guest_ip: "10.10.10.10"

x.x.x.10 should be listening on port 25
x.x.x.11 should also be listening on port 25

### Actual behavior
VM #1 starts normally
VM #2 Gives the error
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 25 is already in use
on the host machine.

### References
Multiple host_ip port forwarding issues #7017
#7035
#4608 
#4616
#5587

**Comment by chrisroberts** [comment]
@deepvoice What provider are you using?

**Comment by deepvoice** [comment]
I have my own cold-iron servers

**Comment by chrisroberts** [comment]
@deepvoice Is Vagrant using the VirtualBox provider to run the guests, or is it using a plugin?

**Comment by deepvoice** [comment]
Virtualbox version 5.1.26

**Comment by briancain** [comment]
Hi @deepvoice - I can't seem to reproduce this error. When I setup port forwarding for two vms with the same port but "different" ips I am able to do so without encountering that error message. Do you have any more information that you could provide to help? Maybe the full debug log, and a Vagrantfile?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
