### ISSUE TITLE
file provisioner OpenWRT

### ISSUE THREAD

**Issue by willis7** [hashicorp/vagrant#9021]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
`Vagrant 1.9.6`

### Host operating system
Mac OSX

### Guest operating system
`living42/openwrt-15.05-x86` v0.1.0

### Vagrantfile
```ruby
    config.vm.define 'router' do |router|
        router.vm.box               = 'living42/openwrt-15.05-x86'
        router.vm.box_version       = '0.1.0'
        router.vm.box_check_update  = false
        router.ssh.username         = 'root'
        router.ssh.password         = 'password'

        router.vm.network 'private_network', auto_config: false, ip: router_ip
        router.vm.synced_folder '.', '/vagrant', disabled: true

        router.vm.provision 'file', source: './provision/collectd.conf', destination: '/etc/collectd.conf'
    end
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://gist.github.com/willis7/ff0e5c1a3882796c8f50d91a2c6856ec

### Expected behavior
File copied from Host to Guest. I'm guessing this is expected behavior, but I'm more curious to know if there's an alternative solution.

### Actual behavior
Error as per Gist

### Steps to reproduce
1. `vagrant up`

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- https://github.com/hashicorp/vagrant/issues/6634

**Comment by chrisroberts** [comment]
Hi there,

This requires the implementation of guest support for openwrt. While this sounds like a reasonable idea, it has a low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Thanks!
