### ISSUE TITLE
VBoxManage.exe: error: VT-x is not available

### ISSUE THREAD

**Issue by helderboone** [hashicorp/vagrant#9025]
Hi,
I installed vagrant 2.0 and virtualbox 5.1.26 on my machine. I also enabled VT on BIOS. 
When i write vagrant up shows the error: Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by briancain** [comment]
Hi @helderboone - if you could please provide a vagrantfile, and link to a gist with debug output, that would be great! Thanks.

**Comment by helderboone** [comment]
VagrantFile
```

**Comment by chrisroberts** [comment]
Do you have Hyper-V enabled on the host?

**Comment by helderboone** [comment]
Yes I have. I installed docker so it needs the hyper-v. Then i uninstalled docker e tried to unisnstall hyper-v. However, while the system is uninstalling the hyper-v occur an error and the system is restored and hyper-v comes back. I don't know what to do.

**Comment by helderboone** [comment]
The issue was solved uninstalling hyper-v. I was having trouble with uninstallation.
