### ISSUE TITLE
windows 8.1 vagrant up has limited my internet access

### ISSUE THREAD

**Issue by BowserHowser** [hashicorp/vagrant#9028]
Hey gays i'm totally new in vagrant development environment so i read about the stuff in the documentation website and i followed couple videos on YouTube to how run vagrant with laravel project and i try make the following stuff like the you-tuber instructors but while i'm using it in my PC the wifi connection to the internet has limited access so i try to make 

> ipconfig /renew

  but no result since _i reboot my PC every thing going be OK_ **so i am trying here to get an other solution without reboot the system because in every time we gonna be needs the internet connection** so **Please harry Help me**

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
