### ISSUE TITLE
option to move NAT adapter as 2nd interface (not 1st and default one)

### ISSUE THREAD

**Issue by ReSearchITEng** [hashicorp/vagrant#9030]
### Expected behavior
For bridged (public_network), there should be an option (if not the default one) to make the NAT adaptor 2nd, and bridged adaptor the 1st one, while still being able to connect to the machine.

If we try this now:
```
  config.vm.network "public_network", :adapter=>1 , type: "dhcp", :bridge => "enp3s0"
```
Vagrant is not able to connect to the machine any longer, as it does not 
```
==> ktmp-master: Preparing network interfaces based on configuration...
    ktmp-master: Adapter 1: bridged
[...]
==> ktmp-master: Running 'pre-boot' VM customizations...
==> ktmp-master: Booting VM...
==> ktmp-master: Waiting for machine to boot. This may take a few minutes...
    ktmp-master: SSH address: 127.0.0.1:22
    ktmp-master: SSH username: vagrant
    ktmp-master: SSH auth method: private key
    ktmp-master: Warning: Authentication failure. Retrying...
    ktmp-master: Warning: Authentication failure. Retrying...
[...]
Timed out while waiting for the machine to boot.
```
not interfere with the box's networking definitions

### Actual behavior
No methods for both vagrant and user to connect to the VM.

### Steps to reproduce
 ```
  config.vm.network "public_network", :adapter=>1 , type: "dhcp", :bridge => "enp3s0"
```

### References
There are few issues which were closed as "old", currently no solution for any of them:
- #2779  (the main one, and full of details) 
- #7635

**Comment by chrisroberts** [comment]
Hi there,

Thanks for creating this issue. I'm going to close this as Vagrant's behavior is built to use the first adapter as the NAT adapter for communication. Changing this changes internal behavior of Vagrant, and I'm not sure that such a large modification is worth the gain of being able to rearrange the network adapters within the guest. If there are strong reasons why this should be supported, I'm very happy to consider them. Cheers!

**Comment by ddayan** [comment]
Is it possible to use UPNP without making the bridged network the first adapter?
