### ISSUE TITLE
The ansible provisioner not longer prompts for the vault password when using ansible 2.4.0.0 with ask_vault_pass set to true.

### ISSUE THREAD

**Issue by IanCaunce** [hashicorp/vagrant#9033]
The ansible provisioner not longer prompts for the vault password when using ansible `2.4.0.0` with `ask_vault_pass` set to `true`.

Vagrant exits with the error:
```
ERROR! Attempting to decrypt but no vault secrets found
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

After some googleing I found this [stackoverflow](https://stackoverflow.com/questions/46451737/ansible-called-by-vagrant-does-not-prompt-for-vault-password) post.

Tested using vagrant version `1.9.1`, `1.9.5` and `2.0.0`.
Host OS: `Ubuntu 16.04`
Kernel: `4.10.0-35-generic`
Guest OS: `ubuntu/xenial64`

## Expected Behaviour:
Vagrant should prompt the user for the vault password.

## Actual Behaviour:
Vagrant doesn't prompt the user and exits.

## Vagrant File
```ruby
Vagrant.configure(2) do |config|

    box_name = "my-box-name"

    config.vm.define box_name
    config.vm.hostname = box_name

    config.vm.provider "virtualbox" do |v|
        v.name = box_name
        v.memory = 1024
    end

    config.vm.box = "ubuntu/xenial64"

    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 3306, host: 3306

    config.ssh.forward_agent = true

    config.vm.synced_folder ".", "/vagrant", owner: "ubuntu", group: "www-data", mount_options: ["dmode=775", "fmode=664"]

    config.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
            ansible_python_interpreter: "/usr/bin/python3"
        }
        ansible.ask_vault_pass = true
        ansible.inventory_path = "provisions/hosts"
        ansible.galaxy_role_file = "provisions/requirements.yml"
        ansible.galaxy_roles_path = "provisions/roles/vendor"
        ansible.playbook = "provisions/playbook.yml"
    end
end
```

**Comment by gildegoma** [comment]
@IanCaunce Thank you for reporting this. As you mentioned, this problem is caused by a change in Ansible 2.4, not in Vagrant. 

I am quite unsure that something can be done in Vagrant itself (see similar story in #2924, about the impossibility to handle non-private variable prompts).

This must be reported to Ansible project. I suspect that https://github.com/ansible/ansible/issues/30993 is related to same change (removal of `getpass.getpass` usage for the password interactive prompt).

See also more details here: https://stackoverflow.com/a/46477011

**Comment by IanCaunce** [comment]
After reading that stackoverflow I thought that was the case but wanted to report it here just in case a fix could be applied in vagrant to support ansible's new logic.

Thanks for the feedback!
