### ISSUE TITLE
Rsync problem!!!!

### ISSUE THREAD

**Issue by lisi4ok** [hashicorp/vagrant#9038]
`==> default: Rsyncing folder: /c/Users/user/Documents/dev/vagrant/ => /vagrant
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /c/Users/user/Documents/dev/vagrant/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL   -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i 'C:/Users/user/Documents/dev/vagrant/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "/c/Users/user/Documents/dev/vagrant/" "vagrant@127.0.0.1:/vagrant"
Error: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
Continuing without compression.

rsync: change_dir "/c/Users/user/Documents/dev/vagrant" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
`
Latest ver Vagrant / VirtualBox
Win 10
centos/7.box

PLS HELP

**Comment by briancain** [comment]
Hello @lisi4ok - this was recently fixed via #8972 and should be in the next release of vagrant, so I'm going to go ahead and close this as a duplicate issue. Thanks!

For now, are you able to use something like the default Virtualbox shared folder option?

**Comment by vhosakot** [comment]
When I did `vagrant up` with the box `centos/7 (virtualbox, 1703.01)`, `==> default: Rsyncing folder: /root/ => /vagrant` was stuck for me too, and adding
`config.vm.synced_folder '.', '/vagrant', disabled: true`
in Vagrantfile resolved the issue for me and rsync did not happen.

**Comment by rupamkhaitan** [comment]
In my case i see blank error

There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /cygdrive/d/htdocs/vagrant_project/
Guest path: /home/cambium/workspace/vagrant_project
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--chmod=ugo=rwX" "--no-perms" "--no-owner" "--no-group" "--rsync-pa
th" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL    -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i
 'D:/htdocs/cnMaestro/cnssops/vagrant/.vagrant/machines/devops-box/virtualbox/private_key'" "--exclude" ".vagrant/" "/cygdrive/d/htdocs/vagrant_project/" "vagrant@127.0.0.1:/home/cambium/workspace/vagrant_project"
Error:
