### ISSUE TITLE
Cannot configure shared folders on Windows 10 

### ISSUE THREAD

**Issue by alankritjoshi** [hashicorp/vagrant#9041]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.0

### Host operating system
Windows 10 Home

### Guest operating system
ubuntu/trusty64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder "data/", "/vagrant/vagrant_data"
end
```
### Debug output
https://gist.github.com/alankritjoshi/e0adaa682da9575e2d5c2e1bd9c3aeb6

### Expected behavior
Shared folder and files

### Actual behavior
No sharing possible. VirtualBox has the incorrect path. 

Host: \\?\D:\Computer Science\Computer Systems\data
Guest; vagrant_vagrant_data

### Steps to reproduce
Install virtualbox 5.1.28 and vagrant 2.0.0
1. vagrant up
2. vagrant ssh

**Comment by briancain** [comment]
Hi @alankritjoshi - I don't actually see an error in the gist you provided...it looks like maybe you had run vagrant up on an already provisioned machine? Did you see the error the first time around?

**Comment by alankritjoshi** [comment]
I don't see any error. I am unable to share any folders. I share the log hoping it would help in figuring out what I am doing wrong. 

After I start up a new vagrant box, in the Virtualbox the folders are set as:

Windows 10: 
\?\D:\Computer Science\Computer Systems\data
ubuntu/trusty64: 
vagrant_vagrant_data

The folder that I want to be shared is:
Windows 10: 
D:\Computer Science\Computer Systems\data
ubuntu/trusty64: 
/vagrant/vagrant_data

I am assuming these folder paths are inaccurate. So I am unable to figure out why I cannot share the folders.

**Comment by chrisroberts** [comment]
@alankritjoshi Hi there. When the guest is brought up, are there no contents in the `/vagrant/vagrant_data` folder?

```
$ vagrant ssh -- ls -l /vagrant/vagrant_data
```

**Comment by alankritjoshi** [comment]
The guest works fine as it is when I ssh into it. So yes, there is data in it as wrote code etc. in it. The problem is the data in `vagrant_data` is not shown in my Windows. In the vagrant directory, there is a `data` folder which doesn't have anything that I have in my guest's vagrant_data.

**Comment by chrisroberts** [comment]
@alankritjoshi For a mount to be successful, the target directory must be empty. In this case, the file system on your host computer is being mounted to `/vagrant/vagrant_data` on the guest machine. That means that the `/vagrant/vagrant_data` directory on the guest machine is the target. You must ensure the `/vagrant/vagrant_data` directory is empty on the guest machine. Then you can run `vagrant reload` which will restart the guest and mount the directory.

Once the directory is mounted, you can add files in the guest or on the host and you will see them in both places.

Cheers!

**Comment by alankritjoshi** [comment]
I think I misunderstood what you asked. I am assuming when you said  

> When the guest is brought up, 

you meant when the guest is upped for the first time. I confirm that it is empty when I set up a new vagrant project. Even the Windows 10 directory which is mapped to it is empty. So sharing is not working.

**Comment by triinoxys** [comment]
Vagrant version: 2.1.2
VirtualBox version: 5.2.14

Still having issue, got it fixed by editing line `271` in `C:\HashiCorp\Vagrant\embedded\gems\2.1.2\gems\vagrant-2.1.2\lib\vagrant\util\platform.rb`

Original: `"\\\\?\\" + path.gsub("/", "\\")`
Fixed: `path.gsub("/", "\\")`

PS: the line number may change in older vagrant versions, just search for `path.gsub("/", "\\")`

**Comment by alankritjoshi** [comment]
I do not have a vagrant installation to verify this on my end. Thanks for the fixes.
