### ISSUE TITLE
SSH Private Key Authentication Fails When Using an Imported VirtualBox Box

### ISSUE THREAD

**Issue by maham-nazir-confiz** [hashicorp/vagrant#9050]
### Vagrant version
Vagrant 1.8.1

### Host operating system
Ubuntu 16.04 LTS

### Guest operating system
CentOS 7.0

### Vagrantfile
```
Vagrant.configure(2) do |config|

 config.vm.box = "oneops"

 # Use the vagrant-cachier plugin, if installed, to cache downloaded packages
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.network "forwarded_port", guest: 3001, host: 3003
  config.vm.network "forwarded_port", guest: 3000, host: 9090
  config.vm.network "forwarded_port", guest: 8080, host: 9091
  config.vm.network "forwarded_port", guest: 8161, host: 8166

  config.vm.provider "virtualbox" do |vb|
   vb.gui = false
   vb.memory = 6144
   vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
  end

  config.vm.synced_folder "~/Documents/Share/", "/home/vagrant/Documents/Share/"
end
```
### Debug output
Gist Link to the Output => https://gist.github.com/maham-nazir-confiz/a7832e21deadca647ebfe61feb1ba37f

### Expected behavior
SSH authentication using private key should have worked.

### Actual behavior
SSH Authentication gets stuck on "default: Error: Connection timeout. Retrying..." until it times out. I am still able to ssh into the machine but cannot create sync folders between host and guest machines.

### Steps to reproduce
1. Import a .ova file into Virtual Box.
2. Place its ID in the "id" file in "/home/user/vagrant/.vagrant/machines/default/"
3. Run "vagrant up"

### References
N/A

**Comment by briancain** [comment]
Hi there @maham-nazir-confiz - In general this workflow is not supported in Vagrant. Vagrant expects a machine to have a `vagrant` user, and uses a default private key to authenticate with. Check out the documentation around creating a base box for vagrant: https://www.vagrantup.com/docs/virtualbox/boxes.html

I also recommend checking out the `config.ssh` docs where you can configure which user, password, and private key should be used when authenticating to a machine. https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html

Thanks!
