### ISSUE TITLE
Booting CentOS 7.3 vagrant box on CentOS 7.4 host times out

### ISSUE THREAD

**Issue by vhosakot** [hashicorp/vagrant#9058]
### Vagrant version
```
# vagrant -v
Vagrant 2.0.0
```
### Host operating system
CentOS 7.4
```
# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
```
### Guest operating system
CentOS 7.3 (box version 1707.01)
### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1707.01"
end
```
### Expected behavior
Should not timeout and the vagrant box must boot properly.

### Actual behavior
```
# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'centos/7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'centos/7' is up to date...
==> default: Setting the name of the VM: root_default_1507909053344_41735
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```
Provider is VirtualBox 5.1.28:
```
# virtualbox --help | grep Virtual
Oracle VM VirtualBox Manager 5.1.28

# VBoxManage --version
5.1.28r117968
```
### Steps to reproduce
See "Actual behavior" above.

**Comment by vhosakot** [comment]
I spent the past three days debugging this issue and still not able to resolve this.

A million people are seeing this. Vagrant **MUST** find the root cause, fix it or worst-case print a better, user-friendly, understandable error message why we cannot SSH into the vagrant box.

https://github.com/geerlingguy/drupal-vm/issues/953
https://github.com/hashicorp/vagrant/issues/7176
https://github.com/hashicorp/vagrant/issues/7930
https://github.com/geerlingguy/drupal-vm/issues/824
https://github.com/fideloper/Vaprobash/issues/563
https://github.com/hashicorp/vagrant/issues/7673
https://github.com/hashicorp/vagrant/issues/3951
https://github.com/fgrehm/vagrant-lxc/issues/388
https://github.com/hashicorp/vagrant/issues/5984
https://github.com/hashicorp/vagrant/issues/2321
https://github.com/geerlingguy/drupal-vm/issues/965
https://github.com/chef/bento/issues/682
https://github.com/hashicorp/vagrant/issues/3802
https://github.com/GoSecure/malboxes/issues/65
https://github.com/projectatomic/adb-atomic-developer-bundle/issues/264
https://github.com/cloudfoundry/bosh-lite/issues/238
https://github.com/hashicorp/vagrant/issues/5659
https://github.com/geerlingguy/drupal-vm/issues/1129
https://github.com/geerlingguy/drupal-vm/issues/409
https://github.com/hashicorp/vagrant/issues/2157

**Comment by briancain** [comment]
Hello @vhosakot - have you tried a different vagrant box? We usually recommend people use the `bento` vagrant boxes such as `"bento/centos-7.2"`. Give that a go, and let us know if you still are experiencing the timeout issue. Thanks!

**Comment by x-cubed** [comment]
I had this issue and discovered that VT-x was disabled on the host. Unfortunately, neither vagrant nor VirtualBox seem to expose this as an error message, I only found it out by starting up the full VirtualBox UI, at which point I received a popup error message. Once the host was rebooted with VT-x enabled, the problem went away.

It seems like maybe VirtualBox is doing the wrong thing here, as the logs show that the virtual machine has started, and the VBoxHeadless processes remain running, even though the VM is unable to boot completely. It would make more sense for it to immediately quit with an error message, rather than sit idle.

**Comment by Alpinista** [comment]
I had the same issue but in my case I am working on a RHEL 7.3 virtual machine as my dev box and booting a vagrant box based on RHEL 7.4 within that environment.  Every time I would try to boot the vagrant box I would receive the time out as noted above.  

Software on my dev box  ... 
  $ cat /etc/redhat-release
  Red Hat Enterprise Linux Server release 7.3 (Maipo) 
  $ vboxmanage --version
  5.1.30r118389
  $ vagrant --version
  Vagrant 2.0.0

Resolution: 
Enable hardware virtualization in vSphere for my dev box within Edit Settings > CPU.  This does require a reboot of the vm but it does resolve the issue.  Hope it helps.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
