### ISSUE TITLE
:paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.

### ISSUE THREAD

**Issue by andrewhowdencom** [hashicorp/vagrant#9062]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version

1.9.8, but code still exists

### Host operating system

```
$ sudo lsb_release -da


No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux unstable (sid)
Release:	unstable
Codename:	sid
```

### Guest operating system

Ubuntu 16.04

### Vagrantfile

Irrelevant

Yah so this warning is being output to stderr with newer debian updates. Preeety sure the SSH client got updated.

Heads up.

**Comment by Mte90** [comment]
Yes seems something on https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh.rb so maybe an update of dependence will fix that

**Comment by guysoft** [comment]
Same issue on vagrant 2.0.0 Debian sid
