### ISSUE TITLE
Windows VM reports IP from range 169.254.x.x in case if there is no DHCP server. 

### ISSUE THREAD

**Issue by zelentsovl** [hashicorp/vagrant#9064]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
**2.0.0**

### Host operating system
This is the operating system that you run locally.
**CentOS 7.3**

### Guest operating system
This is the operating system you run in the virtual machine.
**Windows 2012 R2**

### Vagrantfile - All variables are defined in separate file
```ruby
Vagrant.configure("2") do |config|
  # Open variables file for reading
  require 'yaml'
  variables = YAML::load(File.open('variables.yml')) 

  # Define a few local variables
  vm_number_converter = variables['vm_number_converter']
  vm_name_prefix = variables['vm_name_prefix']
  vm_network_prefix = variables['vm_network_prefix']
  vm_start_ip = variables['vm_start_ip']
  
  config.winrm.username = variables['winrm_username']
  config.winrm.password = variables['winrm_password']

  # Configure vsphere provider
  config.vm.provider :vsphere do |vsphere|
    vsphere.host = variables['vsphere_server']
    vsphere.user = variables['vsphere_user']
    vsphere.password = variables['vsphere_password']
    vsphere.data_center_name = variables['vsphere_datacenter']
    vsphere.compute_resource_name = variables['vsphere_resource']
    vsphere.data_store_name = variables['vsphere_datastore']
    vsphere.vm_base_path = variables['vsphere_vm_base_path']
    vsphere.template_name = variables['vsphere_template_master']
    vsphere.insecure = true
  end

 # Create and configure vms
  (1..vm_number_converter).each do |i|
    config.vm.define "#{vm_name_prefix}converter#{i}" do |convertervm|
      convertervm.vm.communicator = "winrm"
      convertervm.vm.guest = :windows
      convertervm.vm.synced_folder ".", "/vagrant", disabled: true
      # convertervm.vm.hostname = "#{vm_name_prefix}converter#{i}"
      j = vm_start_ip - 1 + i
      convertervm.vm.network :private_network, ip: "#{vm_network_prefix}#{j}"
      # Define VMs parameters
      convertervm.vm.provider :vsphere do |vm|
        vm.template_name = variables['vsphere_template']
        vm.customization_spec_name = variables['customization_spec_win_name']
        vm.name = "#{vm_name_prefix}converter#{i}"
        vm.cpu_count = variables['cpu_number']
        vm.memory_mb = variables['memory']
      end
    end
  end

end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

_==> testconverter1: An error occurred. The error will be shown after all tasks complete.
==> testconverter2: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'testconverter1'
machine. Please handle this error then try again:

Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period._

### Expected behavior
What should have happened?
**VM should get specified static IP and report it to vagrant**

### Actual behavior
What actually happened?
**VM reports IP from range 169.254.x.x and vagrant can't connect to the VM. But VM gets correct IP in a few minutes after customized specification is applied to the VM. Second start of vagrant up --provision detects correct ip address** 

### Steps to reproduce
1. vagrant up

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:

**Comment by chrisroberts** [comment]
Fixed by #8997 and will be available in the next release. Cheers!
