### ISSUE TITLE
Vagrant install plugin fails with "Unable to resolve dependency: user requested 'vmware (> 0)"

### ISSUE THREAD

**Issue by ghsolutions** [hashicorp/vagrant#9066]
### Vagrant version
Vagrant 2.0.0

### Host operating system
Mac OS X 10.13 High Sierra

### Debug output
https://gist.github.com/ghsolutions/d9cfcbfd1912b387cf189f52ed92afb0

### Expected behavior
I wanted to install the actual vmware plugin

### Actual behavior
it stops with an error

### Steps to reproduce
vagrant plugin install vmware

**Comment by briancain** [comment]
Hi @ghsolutions - did you give it a local gem file called `vmware`, or are you trying to install the vagrant vmware plugin?

I recommend checking out the installation docs here: https://www.vagrantup.com/docs/vmware/installation.html

**Comment by chrisroberts** [comment]
Hi there. The name you provided is not a valid vagrant plugin name. Please validate the name of the plugin you are attempting to install and try again. 

Cheers!
