### ISSUE TITLE
same files in one directory

### ISSUE THREAD

**Issue by flyer103** [hashicorp/vagrant#9068]
### Vagrant version
<img width="118" alt="image" src="https://user-images.githubusercontent.com/829039/31709973-40f56028-b426-11e7-97c9-04a94d2e58ae.png">

### Host operating system
MacOS

### Guest operating system
Ubuntu16.04

### Vagrantfile
```ruby
# coding: utf-8
# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-16.04" # I have renamed the ubuntu16.04 box

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "flyer" do |dev|
    dev.vm.hostname = "flyer"
    dev.vm.network "private_network", ip: "172.30.70.30"

    dev.vm.synced_folder "~/git", "/home/ubuntu/git", type: "nfs"
  end

  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("/Users/flyer/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
    sed -i 's/^mesg n$/tty -s \&\& mesg n/g' /root/.profile
    echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
SHELL
  end

  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"  
end
```

### Expected behavior
I have found that in the synced_folder, there are same files having the same inode. A rational situation is that files in the same directory couldn't have the same name and inode:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/829039/31710258-0629f7be-b427-11e7-8a9e-3a6f28cbe07c.png">

### Actual behavior
Some files in the synced_folder have duplicates and the inodes are the same.

### Steps to reproduce
1. Use the above Vagrantfile to start an VM instance
2. Visit the synced_folder

**Comment by flyer103** [comment]
After having tried some times, I think it may be a bug related to nfs. 
When using synced_folder without `type: "nfs"`, everything works as expected.

**Comment by briancain** [comment]
Hi @flyer103 - Are you on macOS High Sierra? If so, there's a thread about the current state of NFS on the latest macOS: #8788. If that's the case I'll go ahead and close this as a duplicate.

For now if it works for you, you can use synced folders with virtualbox instead of nfs like you mentioned.

Thanks!

**Comment by flyer103** [comment]
My Host is `Darwin flyer 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64`. It's macOS High Sierra.

The issue is related to https://github.com/hashicorp/vagrant/issues/8788 and it doesn't work adding `[['nolock', 'vers=3', 'tcp', 'fsc', 'noatime', 'rw']]`. Duplicate files occur is random.

I'll close this issue and watch https://github.com/hashicorp/vagrant/issues/8788.
