### ISSUE TITLE
eth Interface Fails to Restart

### ISSUE THREAD

**Issue by MBetters** [hashicorp/vagrant#9069]
Hello, what I'm trying to do is run multiple CentOS VMs in a private network with IP addresses in the 10.0.0.0/24 subnet. I'm simply adding the IP addresses and hostnames of the VMs in the /etc/hosts file of every VM in the network. Whenever a new VM is added, I add its hostname and IP address to every other VMs /etc/hosts file, then verify ping works bidirectionally. So far, everything's working fine. However, I'm running into an output that shows up as an error but doesn't seem to be breaking my little private network setup.

Basically, I'll make some configuration changes on one of the VMs, like downloading software, putting something into bashrc, etc. Then, I'll follow this SO post (https://stackoverflow.com/questions/19094024/is-there-any-way-to-clone-a-vagrant-box-that-is-already-installed) to package up that updated VM. I'll then follow my usual procedure (laid out in the first paragraph) to add the new VM to my private network, except with the Vagrantfile using `config.vm.box = "package.box"`. When I run `vagrant up` for this copied VM, I get some network interface errors.

### Vagrant version
Vagrant 1.9.6

### Host operating system
Windows 10

### Guest operating system
Centos 6

### Vagrantfiles
For a VM that I base from a clean CentOS 6 box, then make changes to, then package into a package.box file:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"
  config.vm.hostname = "host_being_copied"
  config.vm.network "private_network", ip: "10.0.0.10"
end
```
For the new VM being based on the package.box file (I happened to give this VM a hostname of 'web' but it could be anything):
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "package.box"
  config.vm.hostname = "web"
  config.vm.network "private_network", ip: "10.0.0.11"
end
```

### Debug output
https://gist.github.com/MBetters/56e10fe0b47550c7b0103e3592fd6163

### Expected behavior
I expected the new VM ('web', the one basing and spinning up from package.box) to boot up with no errors, like all the other VMs.

### Actual behavior
As seen in the gist, the new VM's booting output shows eth interfaces being restarted, some of them succeeding, others failing. Once I SSH into the new VM, add all the other VMs in the private network to /etc/hosts, and try pinging, it works bidirectionally (from the new VM to the others and from the others to the new VM), so this new VM is indeed being added to the private network. My concern is that the new VM is restarting eth interfaces and failing, as seen in the gist. It seems to be doing some kind of increment, where eth1 fails and then eth2 is used instead. My guess is the original VM (the one that got packaged) is using eth1, while the new VM tries to use eth1, fails, and then uses eth2. Maybe my guess about that is wrong.

Is there something about booting from a packaged box that makes the eth interface restarts necessary? My concern is that if I make too many vagrant boxes, adding them to my private network, and too many of them are booting from package.box files, then will my system eventually run out of eth interfaces? Sorry if that's a dumb question. I'm not a networking expert by any means.

### Steps to reproduce
1. Make the first Vagrantfile, as shown.
2. Boot it up (vagrant up)
3. SSH into it
4. Make any changes you want, or maybe no changes.
5. Package it, following this SO post: https://stackoverflow.com/questions/19094024/is-there-any-way-to-clone-a-vagrant-box-that-is-already-installed
6. Put the package.box file into a new folder.
7. Make the second Vagrantfile, as shown, putting it in the same new folder as the package.box file.
8. Boot up this new VM (vagrant up).

### References
- Maybe https://github.com/jedi4ever/veewee/issues/970
- Maybe also https://github.com/hashicorp/vagrant/issues/8166

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
