### ISSUE TITLE
Can't launch SSH session when syncing "./" folder with "/home/vagrant"

### ISSUE THREAD

**Issue by PiR-P** [hashicorp/vagrant#9071]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
2.0.0

### Host operating system
OS X Sierra

### Guest operating system
Debian Jessie 64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "debian/jessie64"
  config.vm.box_version = "8.9.0"
  config.vm.synced_folder "./", "/home/vagrant"


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Permission denied (public key)

### Expected behavior
Launching the SSH session

### Actual behavior
Can't launch the SSH session

### Steps to reproduce
1. Add the line config.vm.synced_folder "./", "/home/vagrant" (where ./ contains the vagrantfile) 
2. Launch the vagrant machine with vagrant up
3. Launch SSH session with vagrant ssh

**Comment by briancain** [comment]
Hi @PiR-P - Do you still receive this error if you remove the synced_folder option?

**Comment by PiR-P** [comment]
Nope, the error only occurs when the synced_folder option is set up as defined above. Sorry for the late reply.

**Comment by briancain** [comment]
@PiR-P - do you still get this error if you use the bento box `"bento/debian-8.2"`? I had issues bringing up the box you used, however using `"bento/debian-8.2"` I had no issues at all.

**Comment by cydvd** [comment]
Perhaps this is related to ssh key checking. 
Have you tried to log in into your vagrant box directly trough ssh using the correct private key?

If you configure a `synced_folder` within vagrant user home folder, it is not possible for ssh to check the original `/home/vagrant/.ssh/authorized_keys`, because the directory `/home/vagrant` is now mounted with the host synced folder content.

You can solve using `synced_folder` directive with subdirectories of your `/home/vagrant/` folder

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
