### ISSUE TITLE
VirtualBox 5.2.0 is not supported for Vagrant 2.0.0

### ISSUE THREAD

**Issue by vinixavier** [hashicorp/vagrant#9075]
After downloaded VirtualBox 5.20 and installed, i try use vagrant but was not possible.

### Vagrant version
vagrant --version
Vagrant 2.0.0

### Host operating system
Mac OS X Sierra 10.12.6

### Vagrantfile
Vagrantfile default, through ```vagrant init centos/7```
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end
```

### Debug output
```
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.
```

### Steps to reproduce
1. vagrant init centos/7
2. vagrant up

**Comment by briancain** [comment]
Hi @vinixavier ! Thanks for reporting this issue. Support for virtualbox 5.2 has been merged via #8955 and will be in the next release of Vagrant. For now I recommend grabbing the latest virtualbox 5.1.x until we can get the vagrant release out the door.

Thanks!

**Comment by patricknelson** [comment]
When will that release come out? I've just downloaded the latest version of Vagrant which apparently is still at v2.0.0 and unfortunately still no support yet :(

**Comment by franciscop-invast** [comment]
Looks like there's support already for Virtualbox 5.2 on Vagrant 2.0.1, a patch release just after @patricknelson's message. Thanks!
