### ISSUE TITLE
Can't extend erickoegel/dfly48 => The configured shell (config.ssh.shell) is invalid and unable

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9078]
I'm trying to extend the erickoegel/dfly48 box in order to get (rsync) shared folders working. I figure `sudo pkg update && sudo pkg install -y rsync`, export as a new box into my main `vagrant box` list, then try to use that box with vagrant configuration for rsync-based shared folders. However, when I try to `vagrant up`, the exported box with rsync installed somehow fails to be able to ssh compared to the original erickoegel/dfly48 box!

### Vagrant version

```console
$ vagrant -v 
Vagrant 2.0.0
```

### Host operating system

macOS Sierra

### Guest operating system

DragonFly BSD

### Configuration

Vagrantfile for generating "mcandre/dragonfly-rsync" box:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "erickoegel/dfly48"
  config.vm.provision "shell", path: "bootstrap.sh"
end
```

bootstrap.sh:

```sh
#!/bin/sh
sudo pkg update && \
    sudo pkg install -y rsync
```

Vagrantfile for trying to configure rsync-based shared folders:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/dragonfly-rsync"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
end
```

### Expected behavior

I expect `vagrant up` to mostly work, ideally enabling shared folders, or at the very least producing an error message indicating why rsync shared folders cannot be initialized.

### Actual behavior

```console
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'mcandre/dragonfly-rsync'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: vagrant-dragonfly-rust_default_1508385368806_55063
==> default: Fixed port collision for 22 => 2222. Now on port 2202.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2202 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2202
    default: SSH username: vagrant
    default: SSH auth method: private key
The configured shell (config.ssh.shell) is invalid and unable
to properly execute commands. The most common cause for this is
using a shell that is unavailable on the system. Please verify
you're using the full path to the shell and that the shell is
executable by the SSH user.
```

In an attempt to work around this issue, I also tried to install rsync as a provisioning step, and then configure rsync shared folders immediately afterward in the `config` piece of my original Vagrantfile. However, `vagrant up` for that box then complains that it cannot find rsync, even though it is on $PATH. I suspect that the provisioning step doesn't see the latest $PATH, there's an information gap in this area. Oh well :P

**Comment by briancain** [comment]
Hello @mcandre! How exactly are you creating the box `'mcandre/dragonfly-rsync'`?

**Comment by mcandre** [comment]
@briancain `vagrant up` with the Vagrantfile listed above.

**Comment by briancain** [comment]
@mcandre - It looks like the original box `"mcandre/dragonfly-rsync"` has specified a config setting for ssh in its Vagrantfile:

```ruby
config.ssh.shell = 'sh'
```

If you drop that into your vagrant config with your packaged box, it should come up like normal:

```ruby
config.vm.define "dfly2" do |d|
    d.vm.box = "dfly"
    d.ssh.shell = 'sh'
end
```

Let me know if that works for you!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
