### ISSUE TITLE
Vagrant doesn't support VirtualBox-5.2

### ISSUE THREAD

**Issue by richard-scott** [hashicorp/vagrant#9080]
### Vagrant version
$ /usr/bin/vagrant version
Installed Version: 2.0.0
Latest Version: 2.0.0

### Host operating system
 Ubuntu 16.04.3 LTS

### Guest operating system
Any, doesn't matter.

### Vagrantfile
Doesn't matter, failed with Windows Guest VM or Linux Guest VM.

### Expected behavior
It should find a VirtualBox-5.2 Provider.

### Actual behavior#
```
$ /usr/bin/vagrant status
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.
```

**Comment by nschlemm** [comment]
Interesting, I'm seeing a slightly different message (also with virtualbox-5.2 on ubuntu xenial):

```
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.
```

**Comment by pmarques** [comment]
https://github.com/hashicorp/vagrant/pull/8955

**Comment by joernroeder** [comment]
same here! Seems like it was merged after the 2.0.0 release:

[Merge Commit](https://github.com/hashicorp/vagrant/commit/83310f8a56cfea8a543d17f9af4b18caa13ed98a) on 3. Okt and [Release commit](https://github.com/hashicorp/vagrant/commit/d1cf0f77e761289f0cc0b119067ba1903a2891c9) on 7. Sep

**Comment by joernroeder** [comment]
i've reinstalled the old virtualbox version via `brew`
```bash
brew uninstall virtualbox
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/e8816187ae43f52b598f15f45b3453e22727ac99/Casks/virtualbox.rb
```

**Comment by ondrejfuhrer** [comment]
For those, who need alsto the extension pack, here is a brew install command
```sh
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/f738828d2e69bb5f906929b9e54e66655f39bd48/Casks/virtualbox-extension-pack.rb
```

**Comment by hcartiaux** [comment]
I've installed vagrant from the git repository (f99c5d481) using the [PKGBUILD vagrant-git](https://aur.archlinux.org/packages/vagrant-git).

I confirm it works with Virtual Box 5.2 under Arch Linux.

**Comment by GhaziTriki** [comment]
I just copied the updates from 7d73af5637de41f1e53b8f1ef2ea9baf76842dfb and it worked.

**Comment by briancain** [comment]
Hey all! Yes....VirtualBox 5.2 support has already been merged into master. However that code has not been put in a release yet. It should go out in the next release of Vagrant. For now, please use the latest VirtualBox 5.1.x! Thanks.
