### ISSUE TITLE
Mounting NFS shared folders fails - enableSharedFolders, error mounting

### ISSUE THREAD

**Issue by LewisTheobald** [hashicorp/vagrant#9081]
Upgraded this morning to v5, and unable to boot up our CentOS machine on MacOS. Repeatedly fails on NFS shared folders.

### Vagrant version
$ vagrant -v
Vagrant 2.0.0

$ vagrant plugin list
vagrant-bindfs (1.0.9)
vagrant-share (1.1.9, system)
  - Version Constraint: > 0
vagrant-vmware-fusion (5.0.0)
  - Version Constraint: > 0

### Host operating system
MacOS High Sierra 10.13

### Guest operating system
CentOS 7 (puphpet/centos7-x64)

### Debug output
```==> x: Mounting NFS shared folders...
==> x: Waiting for HGFS to become available...
==> x: Enabling and configuring shared folders...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "~/Documents/Projects/.vagrant/machines/x/vmware_fusion/132661c1-2a81-46c8-8a18-f05f33a4ff0d/centos-7.2-x86_64.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system
```

### Expected behavior
Hooked up the shared folders and continue the boot cycle.

### Actual behavior
Vagrant up fails, errors out repeatedly.

### Steps to reproduce
1. Upgrade to Fusion 10 with Vagrant 2 + VM plugin v5
2. Fresh box using NFS sync fails

**Comment by briancain** [comment]
Hey @LewisTheobald - just to confirm, it looks like you're using vmware's shared folders (HGFS), not NFS. Is that the case? Thanks!

**Comment by LewisTheobald** [comment]
Morning @briancain, I just checked my config and it's down as 'sync_type: nfs' - whether that is in fact the issue, that it isn't using NFS? I can't see anywhere that it is being set to use anything other than NFS.

**Comment by briancain** [comment]
@LewisTheobald - You should be setting `nfs` with something like:

```ruby
config.vm.synced_folders ".", "/vagrant", type: "nfs"
```

More information about nfs can be found here... https://www.vagrantup.com/docs/synced-folders/nfs.html#enabling-nfs-synced-folders

But without seeing a Vagrantfile it's difficult to figure out what's going on.

That being said, I recommend *not* using NFS right now on macOS High Sierra due to a bug in NFS (see #8788 for more information).

If you are getting a bug with HGFS in vmware it would be useful to see a debug log...thanks! :)

**Comment by alexwybraniec** [comment]
Hello,

I'm getting the same issue on my new MBP with Sierra (10.12.6). I upgraded to Vagrant 2.0, VMWare Fusion 10.0 and the new vagrant-vmware-fusion as well.

If I disable shared folders, the machine will boot. 
```ruby
config.vm.synced_folder ".", "/vagrant", disabled: true
```
Going to have to switch back to old laptop till this is resolved.

### Vagrant version
Vagrant 2.0.0

### Host operating system
macOS 10.12.6 (16G29)

### Guest operating system
puphpet/ubuntu1404-x64

### Vagrantfile
```ruby

Vagrant.configure(2) do |config|
  config.vm.box = "puphpet/ubuntu1404-x64"

  config.vm.network :private_network, ip: "172.10.0.208", :netmask => "255.255.0.0"

  config.vm.provision "shell", path: "_provision/script.sh", privileged: false

  config.vm.provider "vmware_fusion" do |v|
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "4"
  end

  config.trigger.after [:up, :resume, :reload] do
      info "IP: 172.10.0.208"
  end

end

```

### Debug output
vagrant up --debug
https://gist.github.com/alexwybraniec/0043d2a40c92f4e4c704143bdf2c74b1

**Comment by alexwybraniec** [comment]
@chrisroberts Hi Chris, is there any more info I can provide you? Anything I can help with testing?

**Comment by LewisTheobald** [comment]
@chrisroberts I'm using PuPHPet to generate the Vagrant setup, but in the config file it is set as 'sync_type: nfs'. I'm not sure what changed, but I'm now able to get past this cycle and it correctly prompts:

`==> local.mbm.io: Exporting NFS shared folders...
==> local.mbm.io: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
==> local.mbm.io: Mounting NFS shared folders...
==> local.mbm.io: Waiting for HGFS to become available...
==> local.mbm.io: Enabling and configuring shared folders...`

The only thing I'm running into now is that the machine continues to go into loops whereby I have to do a vagrant reload every hour or so otherwise all the sync'd folders drop off. But I cannot pinpoint any common behaviour to it other than when no requests are made for a given period of time (perhaps the box is going into an inactive state, I really don't know)

**Comment by alexwybraniec** [comment]
My issues here were resolved by switching to the bento boxes
https://app.vagrantup.com/bento/boxes/ubuntu-16.04

**Comment by chrisroberts** [comment]
Hi there,

A new VMware plugin has been released. You can read more about it here:

https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

If you are still encountering this issue after upgrading, please open a new issue and I will investigate further.

Cheers!

**Comment by LewisTheobald** [comment]
Hey @chrisroberts, I'm getting the same error again:

`==> local.mbm.io: Exporting NFS shared folders...
==> local.mbm.io: Preparing to edit /etc/exports. Administrator privileges will be required...
==> local.mbm.io: Mounting NFS shared folders...
==> local.mbm.io: Waiting for HGFS to become available...
==> local.mbm.io: Enabling and configuring shared folders...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["enableSharedFolders", "/Users/lewis/Documents/Projects/.vagrant/machines/local.mbm.io/vmware_fusion/6204e910-409a-44f7-9203-02f71b223f00/centos-7.2-x86_64.vmx", {:notify=>[:stdout, :stderr]}]

Stdout: Error: There was an error mounting the Shared Folders file system inside the guest operating system

Stderr: `

VMWare Fushion v10.1.3 (9472307)

Vagrant 2.1.5

vagrant-bindfs (1.1.0, global)
  - Version Constraint: > 0
vagrant-share (1.1.9, global)
  - Version Constraint: > 0
vagrant-vmware-desktop (1.0.4, global)
  - Version Constraint: > 0
