### ISSUE TITLE
Stop prompting to prune NFS exports

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9082]
In macOS Sierra, the netbsd/NetBSD-7.0 box prompts for the host password on every single `vagrant up` in order to tweak NFS stuff. Please have Vagrant permanently authorize itself for this task, so that the user only needs to enter the password once.

**Comment by briancain** [comment]
Hey @mcandre - I recommend checking out the [Root Privilege Requirement](https://www.vagrantup.com/docs/synced-folders/nfs.html#root-privilege-requirement) docs. It details how you can avoid typing in your password every time when you bring up a guest machine that uses NFS.

Thanks!

**Comment by mcandre** [comment]
Those instructions are helpful, thanks for the link!

I'd really like to see the Vagrant installer manage this configuration, to reduce the likelihood of error by the user, especially on dummy systems like macOS.
