### ISSUE TITLE
Feature request: config way to tweak PATH

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9083]
Some boxes place binaries in strange locations, requiring `$PATH` tweaking. Vagrant could help to make this process easier, by offering a `config.path` attribute. Basically, Vagrant would replace the guest `$PATH` with the value of `config.path`. This works similar to the `ENV` instruction in Docker.

As a workaround, some users can screw with exporting `PATH` from `/root/vagrant/.profile` and similar locations, based on the particular shells involved. This really only works for bash derivatives, as `sh` is usually severely restricted in which configuration files, if any, it loads during non-interactive sessions for `sh -c '...'` / `ssh -c '...'`.

Another workaround is to add an entry in `/etc/login.conf`, and then update the capability database with `cap_mkdb /etc/login.conf`. Though again, many systems like NetBSD fail to load these settings.

Some people suggest using provisioning scripts marked `run: "always"` as a workaround, or even augmenting /etc/profile.d, /etc/profile, /etc/shrc, /home/vagrant/.bashrc, etc. etc., but these are unreliable hacks. For example, `vagrant ssh -c` does not execute commands in a login shell for NetBSD guests, nor when using legacy Vagrant v1.x, nor are environment variables from provisioning scripts safely propagated to other provisioning scripts. So an official `env` attribute on the Vagrant `config` object would dramatically streamline how environment variables are configured for our boxes.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for the suggestion/request but I'm going to close this as the implementation details make this extremely complicated due to the wide variety of supported guests. The option would be very brittle for added guests and prone to breaking. I think that existing approaches for setting PATHs based on specific guest in use is much more applicable and maintainable.

Cheers!
