### ISSUE TITLE
No Provider Found with VirtualBox 5.2.0

### ISSUE THREAD

**Issue by cgatesman** [hashicorp/vagrant#9084]
After upgrading to VirtualBox 5.2.0 on macOS, Vagrant can no longer find it.

### Vagrant version
Vagrant 2.0.0

### Host operating system
macOS 10.13

### Debug output
https://gist.github.com/cgatesman/1152d4c689fb9abad1e28f297d1331ec

**Comment by adriandmitroca** [comment]
Vagrant does not support VirtualBox 5.2 at the moment. You need to downgrade to 5.1 version.

**Comment by briancain** [comment]
Hi @cgatesman! Yep, this work has already been merged into master and will be out in the next release of Vagrant (which should be very soon!). For now please downgrade to VirtualBox 5.1.x. Thanks!
