### ISSUE TITLE
VM destroyed during up

### ISSUE THREAD

**Issue by al35mm** [hashicorp/vagrant#9086]
Using Vagrant 2.0.0, VirtualBox 5.1.30 (just updated from previous version where this issue also occurred) on Windows 10 x64
This is a clean install of Vagrant and VirtualBox.

Problem
Using any vagrant file even the unedited default init file (using ubuntu/trusty64), the up process gets so far i.e. creates and boots the VM, creates vagrant user account and keys then shuts down and destroys the VM. Up then continues and produces errors as though it doesn't realize that it has already (for some reason) destroyed the VM. It seems to destroy the VM after copying the public key to the guest.

Here is the output - relevant lines only;

    vagrant up
    .......
    default: Inserting generated public key within guest...
    ==> default: Forcing shutdown of VM...
    ==> default: Destroying VM and associated drives...
    C:/HashiCorp/Vagrant/embedded/gems/gems/net-scp-1.2.1/lib/net/scp.rb:398:in `await_response_state': scp: /tmp/vagrant-insert-pubkey-1508446645: Read-only file system (RuntimeError)
	from C:/HashiCorp/Vagrant/embedded/gems/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
    .......

    Process finished with exit code 1

**Comment by briancain** [comment]
Hi @al35mm - have you tried using a different vagrant box? Do you still experience this error if you do? Thanks!

**Comment by al35mm** [comment]
Hi @briancain, Thanks for your reply. I just tried ubuntu/xenial64 a few times and I am not getting the issue with that. So there is a problem with ubuntu/trusty64? Unfortunately, it is ubuntu/trusty64 that I need to use at the moment.

**Comment by al35mm** [comment]
OK I may be in business. I haven't used Vagrant for about a year. I just tried removing ubuntu/trusty64 so it would force a new download - I hadn't thought that it could be a fault in the box file. It seems to be spinning up ok at the moment.
