### ISSUE TITLE
curl output displays one character per line (NetBSD guest)

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9087]
### Vagrant version

```console
$ vagrant -v
Vagrant 2.0.0
```

### Host operating system

macOS Sierra

### Guest operating system

netbsd/NetBSD-7.0

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "netbsd/NetBSD-7.0"
  config.vm.provision "shell", path: "bootstrap.sh"
end
```

### bootstrap.sh

```sh
#!/bin/sh
curl -o pkgsrc-2017Q3.tar.gz ftp://ftp.netbsd.org//pub/pkgsrc/pkgsrc-2017Q3/pkgsrc-2017Q3.tar.gz && \
    tar -C /usr -xzf pkgsrc-2017Q3.tar.gz
```

### Expected behavior

curl output maps line-per-line with vagrant output.

### Actual behavior

Vagrant displays one character of curl output per "default" vagrant line.

### Steps to reproduce

1. `vagrant up`

**Comment by nitrocode** [comment]
This also affects other operating systems like CentOS and Ubuntu

**Comment by chrisroberts** [comment]
Hi there,

This is not an issue with Vagrant. The shell provisioner will read data as it becomes available and the output from curl causes issues as it attempts to do in place updates of the download status. This can be avoided by simply adding the `-s` option to the curl command.

Cheers!
