### ISSUE TITLE
vagrant package silently fails when --output path contains a slash

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9088]
### Vagrant version

```console
$ vagrant -v
Vagrant 2.0.0
```

### Host operating system

macOS Sierra

### Guest operating system

erickoegel/dfly48

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "erickoegel/dfly48"
  config.vm.provision "shell", path: "bootstrap.sh"
end
```

### bootstrap.sh

```sh
#!/bin/sh
sudo pkg update && \
    sudo pkg install -y rsync
```

### Expected behavior

Ideally, Vagrant checks to see if a `mcandre` directory exists. If not, Vagrant creates the directory and writes a `dragonfly-rsync.box` file inside the directory.

Or, Vagrant exits with a non-zero status and warns the user that the path would be invalid.

### Actual behavior

Vagrant takes several minutes to produce a box, then I have no idea where the box ends up, because no *.box files are produced.

### Steps to reproduce
1. `vagrant up`
2. `vagrant package --output mcandre/dragonfly-rsync.box`

As a workaround, I am careful to `--output` to `dragonfly-rsync.box`, and then import the box as `mcandre/dragonfly-rsync` to my vagrant box list.

**Comment by bpietraga** [comment]
@mcandre @briancain 
Hello!
I wrote fix in PR.  I found that `package.output` was treated like a string name and not a path. The folder wasn't created. It is my first pull request here. Every suggestion for refactoring and other changes are welcome.
I've marked PR WIP as I did it quickly and It needs test suite.

Thank you for this great library!

**Comment by bpietraga** [comment]
I will have time on weekend to polish code.

**Comment by bpietraga** [comment]
I did refactor and added test for this functionality. More info on PR.
