### ISSUE TITLE
vagrant-vmware-fusion driver.rb NoMethodError

### ISSUE THREAD

**Issue by jsher** [hashicorp/vagrant#9089]
### Vagrant version
2.0.0

### Host operating system
OSX 10.12.6

### VMWare version
Professional Version 10.0.1 (6754183)

### Guest operating system
https://vagrantcloud.com/bento/boxes/centos-7.3/versions/201708.22.0/providers/vmware_desktop.box
https://vagrantcloud.com/hashicorp/boxes/precise64/versions/1.1.0/providers/vmware_fusion.box

### Vagrantfile Centos

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"
  config.vm.hostname = "webade-dev-fusion.vm"

end
```

### Vagrantfile Precise64 (Vanilla)

```ruby
# vagrant init hashicorp/precise64
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/jsher/2221563cd7daed0879e6b6815fd1cf5f
https://gist.github.com/jsher/26a117f791d75754d25bda69c5d91503

### Expected behavior
Vm should have come up

### Actual behavior
Same error, 2 different boxes

### Steps to reproduce
1. Install VMware 10 pro
2. Install VMware Fusion vagrant plugin and license (5.0.0)
3. Create Vagrantfile
4. bring vm up with vmware_fusion provide

**Comment by briancain** [comment]
Hi there @jsher ! It looks like in your gist you are actually running Vagrant 1.9.4. Can you please upgrade to Vagrant 2.0 and let us know if you still experience this? Thanks!

**Comment by jsher** [comment]
Thanks @briancain 
How embarrassing.  I ran vagrant version saw 2.0.0 but didn't read all the other stuff telling me to update to that version.  Sigh. RTFM indeed.

Updated to 2.0.0, updated my plugins, had success bringing up both boxes.
Added in private networking to my Vagrantfile and it's looking good.
Thanks so much, issue was user :(

**Comment by briancain** [comment]
No worries! Glad it all worked out 😄 🎆

**Comment by stantonk** [comment]
@jsher ah i have the exact same issue.

**Comment by stantonk** [comment]
@briancain unfortunately i cannot upgrade to vagrant 2.0.0, other plugins we rely on break.
