### ISSUE TITLE
Stuck while on VPN

### ISSUE THREAD

**Issue by IQ-JYe** [hashicorp/vagrant#9092]
I have a vagrant setup that has been working pretty well for a while now. I decided to update vagrant(from 1.9.something to 2.0.0) and virtualbox(from 5.1.something to 5.1.30, also tried 5.2).
Then the problem started. 

I would not be able to do vagrant up if i were on VPN. I would get stuck at _mounting nfs shared folder_ or _Running provisioner: ansible_local_. And as soon as I get off of VPN the operations would resume and everything would be back to normal.

I had the landrush plugin installed but I uninstalled just in case. It didn't fix anything.

### Vagrant version
Vagrant 2.0.0

### Host operating system
Windows 10
Virtualbox 5.1.18 also tested on Virtualbox 5.1.30

### Guest operating system
Ubuntu 14.04.5

### Vagrantfile
```ruby
Vagrant.require_version '>= 1.8.1'

require 'getoptlong'

opts = GetoptLong.new(
  [ '--env', GetoptLong::OPTIONAL_ARGUMENT ]
)

paramDb=''

opts.each do |opt, arg|
  case opt
    when '--env'
      paramDb=arg
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.boot_timeout = 120
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox", nfs: true
  config.vm.synced_folder ".", "/var/www/html/site", type: "virtualbox", nfs: true
  config.vm.network "private_network", ip: "192.168.50.103"
  config.vm.network :forwarded_port, guest: 22, host: 2223, id: 'ssh'

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision/playbook.yml"
    ansible.extra_vars = {
      env: "#{paramDb}"
    }
  end
end
```

### Debug output
stuck at Mounting NFS shared folders
https://gist.github.com/IQ-JYe/36c806144d8e8ce5a073727bad431d4e
stuck at Running provisioner: ansible_local
https://gist.github.com/IQ-JYe/ed7e42345a88397e9e107bfdb15fa798

### Expected behavior
VM should be up and running fully provisioned.

### Actual behavior
Stuck at various places like Mounting NFS shared folder or Running provisioner: ansible_local

### Steps to reproduce
1. Be on GlobalProtect VPN
2. Vagrant up or Vagrant provision

### References
I have tried suggestions from the following:
https://stackoverflow.com/questions/20339191/vagrant-with-vpn-connection-over-host-computer

**Comment by IQ-JYe** [comment]
Ok. found the problem. If I disable nfs(remove **nfs: true**), everything works. I am afraid this would affect performance though.

So in summary:
In VPN, NFS on - does not work
In VPN, NFS off - does work
No VPN, NFS on - does work

**Comment by IQ-JYe** [comment]
I think the problem comes from that the IP allocated by NFS(vagrant_winnfsd) is already occupied by the VPN.

**Comment by dreadnautxbuddha** [comment]
I encountered something like this. I turned on ExpressVPN then when I 
do a `vagrant up`, I get stuck on **Mounting shared folders...**.

I was able to work around this by setting my private network like so:
`cortez.vm.network "private_network", type: "dhcp"`

Hope this helps.
