### ISSUE TITLE
mac os vagrant halt error . 

### ISSUE THREAD

**Issue by 19940308cai** [hashicorp/vagrant#9094]
![image](https://user-images.githubusercontent.com/20193598/31848394-86e08838-b5f7-11e7-86b5-8294d3a866a3.png)

**Comment by briancain** [comment]
Hello @19940308cai - what version of vagrant are you running?

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄
