### ISSUE TITLE
website download section, SHA256 checksums correspond to different OS files.

### ISSUE THREAD

**Issue by spyros000** [hashicorp/vagrant#9095]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Expected behavior
What should have happened?
The checksum of my downloaded windows file should match the one provided by you.

### Actual behavior
What actually happened?
The checksum of my downloaded windows file matches the mac's provided checksum. Mac's downloaded file checksum matches Debian's.

**Comment by briancain** [comment]
Hey there @spyros000 - I just checked each of the packages for Vagrant 2.0 and they all match the given SHA256 checksums listed [here](https://releases.hashicorp.com/vagrant/2.0.0/vagrant_2.0.0_SHA256SUMS?_ga=2.5136947.186620315.1508774113-2121269785.1508277361). What command were you running to validate the packages?

For example this is how I validated the macOS installer:

```
brian@localghost:Downloads % openssl sha -sha256 vagrant_2.0.0_x86_64.dmg
SHA256(vagrant_2.0.0_x86_64.dmg)= 596fba741f99a083eed9751973b4a3016c99de611165ca561922008d23008494
brian@localghost:Downloads % cat vagrant_2.0.txt | grep -i vagrant_2.0.0_x86_64.dmg
596fba741f99a083eed9751973b4a3016c99de611165ca561922008d23008494  vagrant_2.0.0_x86_64.dmg
```

**Comment by chrisroberts** [comment]
As we have confirmed the checksums are valid, I'm going to close this issue. If you still believe there is an issue, please either respond on this issue or create a new one.

Cheers!
