### ISSUE TITLE
vagrant up error Couldn't open file

### ISSUE THREAD

**Issue by phpapi** [hashicorp/vagrant#9099]
Im using virtualBox 5.2 and vagrant 1.7.4 in win10,then vagrant up output below.
does somebody occurred it?

	PS D:\software> vagrant box add --provider virtualbox CentOS-7.1.1503-x86_64-netboot CentOS-7.1.1503-x86_64-netboot.box
	==> box: Box file was not detected as metadata. Adding it directly...
	==> box: Adding box 'CentOS-7.1.1503-x86_64-netboot' (v0) for provider: virtualbox
	    box: Unpacking necessary files from: file://D:/software/CentOS-7.1.1503-x86_64-netboot.box
	    box: Progress: 100% (Rate: 1024M/s, Estimated time remaining: --:--:--)
	==> box: Successfully added box 'CentOS-7.1.1503-x86_64-netboot' (v0) for 'virtualbox'!
	PS D:\software> vagrant box list
	CentOS-7.1.1503-x86_64-netboot (virtualbox, 0)
	PS D:\software> vagrant up
	Bringing machine 'default' up with 'hyperv' provider...
	==> default: Verifying Hyper-V is enabled...
	==> default: Box 'CentOS-7.1.1503-x86_64-netboot' could not be found. Attempting to find and install...
	    default: Box Provider: hyperv
	    default: Box Version: >= 0
	==> default: Box file was not detected as metadata. Adding it directly...
	==> default: Adding box 'CentOS-7.1.1503-x86_64-netboot' (v0) for provider: hyperv
	    default: Downloading: CentOS-7.1.1503-x86_64-netboot
	    default:
	An error occurred while downloading the remote file. The error
	message, if any, is reproduced below. Please fix this error and try
	again.

	Couldn't open file /software/CentOS-7.1.1503-x86_64-netboot

and i use vagrant init made a vagrantFile and change.

	Vagrant.configure(2) do |config|
	 
	  config.vm.box = "CentOS-7.1.1503-x86_64-netboot"
	  config.vm.network "private_network", ip: "192.168.33.10"
	  config.vm.synced_folder "../www/htdocs", "/opt/htdocs"

	  config.vm.provider "virtualbox" do |vb|
	  #   # Display the VirtualBox GUI when booting the machine
	  #   vb.gui = true
	  #
	  #   # Customize the amount of memory on the VM:
	  #   vb.memory = "1024"
	  end

	end

**Comment by phpapi** [comment]
vagrant up default detect hyperv need to add --provider virtualbox.
vagrant not support virtualbox 5.2.

**Comment by drmaddy736** [comment]
error Couldn't open file /c:/my-bahmni-vagrant/package.box
