### ISSUE TITLE
way to list running VMs

### ISSUE THREAD

**Issue by danielb2** [hashicorp/vagrant#910]
There's no way to list what VMs are currently running through vagrant. I may have three vagrant VMs running but no way to tell me.

Maybe a `vagrant list` ?

**Comment by abhinoc** [comment]
xxxxx-MacBook-Pro:chef-workstation xxxxx$ vagrant global-status
id       name    provider   state   directory                                 
------------------------------------------------------------------------------
a6148c0  default virtualbox running /Users/xxxx/Vagrant/CHEF             
9ec5e50  default virtualbox running /Users/xxxx/Vagrant/chef-workstation

**Comment by AlbertoCastelo** [comment]
I have VM created with `vagrant up` and it is working (I'm able to access a server in the VM). However, with `VBoxManage list vms`, I cannot see any Virtual Machine. Furthermore, it also does not show up in Virtual Box UI.
