### ISSUE TITLE
generic/openbsd6, generic/freebsd11 boxes fail to boot

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9103]
### Vagrant version

2.0.0

### Host operating system

macOS Sierra

### Guest operating system

generic/openbsd6 and generic/freebsd11

### Vagrantfile's

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/openbsd6"
end
```

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/freebsd11"
end
```

### Expected behavior

The boxes successfully `vagrant up`.

### Actual behavior

The boxes produce "provisioning" inline shell script errors, even though no provisioning scripts are configured in the Vagrantfile's.

### Steps to reproduce

1. `vagrant up`

I'd report this to the box owner, but I don't see a link to the box sources, from either the Vagrant Cloud pages, nor from the "generic" bio page.

For now, I'm working around these errors by using the uchida/freebsd and ryanmaclean/openbsd-6.0 boxes.

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the Vagrant mailing list. There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
