### ISSUE TITLE
vagrant up with multiple machines times out. Works with vagrant up <machine-name>

### ISSUE THREAD

**Issue by ferrarimarco** [hashicorp/vagrant#9104]
### Vagrant version
`Vagrant 2.0.0`

### Host operating system
`Ubuntu 17.10`

### Guest operating system
`CentOS 7.4`, `Ubuntu 16.04`

### Vagrantfile
```ruby
scissor = {
  "ubuntu1" => {
    :autostart => true,
    :box => "bento/ubuntu-16.04",
    :cpus => 1,
    :mem => 1024,
    :ip => "10.10.1.55"
  },
  "ubuntu2" => {
    :autostart => true,
    :box => "bento/ubuntu-16.04",
    :cpus => 1,
    :mem => 1024,
    :ip => "10.10.1.53"
  },
  "centos1" => {
    :autostart => true,
    :box => "bento/centos-7.4",
    :cpus => 1,
    :mem => 1024,
    :ip => "10.10.1.51"
  }
}

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  scissor.each do |(hostname, info)|
    config.vm.define hostname, autostart: info[:autostart] do |host|
      host.vm.box = "#{info[:box]}"
      config.vm.network :private_network, ip: "#{info[:ip]}"
    end
  end
end
```
### Debug output
`vagrant up`: https://gist.github.com/ferrarimarco/0d153c33a8ed75a805838f91fef96208
`vagrant up centos1`: https://gist.github.com/ferrarimarco/35d484dbaa33159829241b48134c8c28

### Expected behavior
Three VMs up and running

### Actual behavior
Connection Timeout if running `vagrant up` but works when running `vagrant up <machine-name>` for each machine. Note that the two Ubuntu VMs work in both cases. The CentOS one only with `vagrant up centos1`.

If I don't configure any network in the Vagrantfile (with `config.vm.network :private_network, ip: "#{info[:ip]}"`), I don't see any problem.

I also tried to raise the timeout to 600 seconds, but it did not help.

### Steps to reproduce
1. `vagrant up`

**Comment by ferrarimarco** [comment]
This issue occurs also in Vagrant 2.0.1

**Comment by sly01** [comment]
+1 same on 
MacOS 10.15.2
Vagrant 2.2.6

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
