### ISSUE TITLE
Running ssh-config on Windows with Cygwin is always returning a Cygwin path

### ISSUE THREAD

**Issue by tombazza** [hashicorp/vagrant#9109]
I'm having an issue where the returned value of ```vagrant ssh-config``` from a Windows command prompt is always giving me a Cygwin path to the private key file.

### Vagrant version
```Vagrant 2.0.0```

### Host operating system
Windows 10

### Guest operating system
Ubuntu 14.04.5 LTS

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

#----------------------------------------
# Configuration variables
#----------------------------------------

IP_ADDRESS = "33.33.33.222"
GUEST_SHARE = "/home/vagrant/myproject"
MEMORY = "512"
BASE_BOX = "myproject/myproject-web"
BASE_BOX_VERSION = "2.2.0"
VAGRANTFILE_API_VERSION = "2"

#----------------------------------------

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = BASE_BOX
    config.vm.box_version = BASE_BOX_VERSION
    config.vm.network :private_network, ip: IP_ADDRESS
    config.vm.synced_folder ".", GUEST_SHARE, type: "nfs"
    config.ssh.forward_agent = true

    config.vm.provider "virtualbox" do |my_vm|
        my_vm.customize ["modifyvm", :id, "--memory", MEMORY]
        my_vm.customize [
            "guestproperty", "set", :id,
            "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold",
            10000
        ]
    end

    config.vm.provision :shell do |shell|
        shell.inline = "cd #{GUEST_SHARE} && make install dev test-local"
    end
end
```

### Debug output
https://gist.github.com/tombazza/1e10a618c887ef4d0260ea9ed5f9d43d

### Expected behavior
Running ```vagrant ssh-config``` should return a Windows path to the private key file.

### Actual behavior
The output of ```vagrant ssh-config``` is returning a Cygwin path (e.g. ```/cygdrive/e/[..]/private_key```)

### Steps to reproduce
1. Install Vagrant 2.0.0
2. Install cygwin and add the cygwin binaries to the Windows ```PATH``` environment variable
3. Run ```vagrant ssh-config```

**Comment by tapuzzo-fsi** [comment]
I think the SSH-CONFIG needs to have some configuration ability.  You can't just blanket output one or another.  For example, after painful experimentation, I've settled on using the Git for Windows `ssh` client as my default.  This is compatible with `vagrant ssh-config`.   I think that Vagrant is using the same format that their embedded ssh client needs.  Which is probably fine for most cases.  Maybe Vagrant could add another feature like 'vagrant ssh-embedded' that would return the path to their preferred SSH client so we could use that.  

Honestly the whole situation with ssh clients and Windows is an unmitigated disaster:
* cygwin ssh
* git ssh 
* Linux Subsystem for Windows ssh
* OpenSSH for Windows
* Putty / Kitty / etc.

Horrors...  God help you if you need a particular one to be "first" in your path.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
