### ISSUE TITLE
vagrant init always gives C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:776: [BUG] Segmentation fault EVEN OUTSIDE ONEDRIVE FOLDER

### ISSUE THREAD

**Issue by quantumwebco** [hashicorp/vagrant#9110]
The files are physically on my local system just inside the onedrive folder. There is no possibility of moving all my files and work out of my onedrive folder.

It works fine in some folders so why not others??

**Comment by quantumwebco** [comment]
Also just tested and I get the same error in local folders outside of the onedrive folder

**Comment by chrisroberts** [comment]
Please provide a gist of the debug output when running the command within a folder outside of the OneDrive folder that fails. Thanks.

**Comment by quantumwebco** [comment]
Just the same error. Do you want me to copy in the whole output again?

**Comment by chrisroberts** [comment]
Yes, please provide a gist of the debug output when run from a local system folder. Thanks.

**Comment by quantumwebco** [comment]
OK even weirder now after the first couple of times it not working in any folder even outside of onedrive as well it now works in every folder including where it didn't, inside the onedrive folder. So now it just works everywhere as expected which is nice, but odd.

I think what helped was stopping the onedrive service start on login and so it's not initiated and the folders aren't marked as virtual or whatever.

Apologies, this is clearly something odd happening on my local machine and nothing to do with vagrant.
