### ISSUE TITLE
vagrant plugin update failing with incompatible bundler dependencies

### ISSUE THREAD

**Issue by claytonflesher** [hashicorp/vagrant#9111]
### Vagrant version
2.0.0

### Host operating system
Mac OS Sierra Version 10.12.6

### Expected behavior
`vagrant plugin update` should run without error

I first noticed this when I tried to install the winrm plugin and got the same error.

### Actual behavior
```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies rb-fsevent (= 0.9.8) and rb-fsevent (= 0.10.2)
  Activated rb-fsevent-0.10.2
  which does not match conflicting dependency (= 0.9.8)

  Conflicting dependency chains:
    rb-fsevent (= 0.10.2), 0.10.2 activated

  versus:
    rb-fsevent (= 0.9.8)

  Gems matching rb-fsevent (= 0.9.8):
    rb-fsevent-0.9.8
```
### Steps to reproduce
1. `vagrant plugin update` from a Mac on 2.0.0

**Comment by claytonflesher** [comment]
`vagrant plugin list` returns the following output.

vagrant-share (1.1.9, system)

**Comment by chrisroberts** [comment]
Hi @claytonflesher,

There is a known issue with the installer not properly cleaning up old files during upgrade. Would you please run the uninstall script and then install Vagrant again and see if it resolves the problem. Thanks!

**Comment by claytonflesher** [comment]
That fixed the issue. Thanks!
