### ISSUE TITLE
Enhancement: No way to specifically set ANSIBLE_ROLES_PATH (separate from galaxy roles path)

### ISSUE THREAD

**Issue by james-portman** [hashicorp/vagrant#9114]
### Vagrant version
Current/all

### Host operating system
All

### Guest operating system
All

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "requirements.yml"
    ansible.galaxy_roles_path = "../"
  end
end
```

### Expected behavior
It would be great to have a separate parameter `ansible.roles_path` which was passed to the `ansible-playbook` command as `ANSIBLE_ROLES_PATH`.

### Actual behavior
Currently the single parameter `ansible.galaxy_roles_path` is used for both the `ansible-galaxy` and `ansible-playbook` commands.

**Comment by james-portman** [comment]
The current behaviour is related to/caused by this change:
https://github.com/hashicorp/vagrant/pull/7420/files

I don't know why it was agreed to use a variable specifically for galaxy/ansible-galaxy for the ansible-playbook command

**Comment by james-portman** [comment]
Potential fix:
https://github.com/hashicorp/vagrant/pull/9115

**Comment by gildegoma** [comment]
Most Ansible projects (with or without Vagrant in the game), will store their roles in a `roles/` directory [relative to the playbook file](https://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html#role-search-path). The galaxy roles are often installed in a distinct directory, and the addition #7420 allows this.

If for some reason, you want to use a different roles path, this is easily configured with a `roles_path` entry in an [Ansible configuration file](https://docs.ansible.com/ansible/latest/intro_configuration.html#roles-path) (e.g. a local `ansible.cfg`).

**Comment by james-portman** [comment]
I will test again, but from what I can tell, using roles_path within ansible.cfg also affects ansible-galaxy command.
It is still not logical for you to call the parameter galaxy_roles_path but apply it to both the ansible-galaxy and also the ansible-playbook command.

**Comment by gildegoma** [comment]
> It is still not logical for you to call the parameter galaxy_roles_path but apply it to both the ansible-galaxy and also the ansible-playbook command.

On the contrary, it makes sense to instruct `ansible-playbook` command about where the galaxy roles are, so they can be used. The `ansible-playbook` command will then look for roles in the default paths (e.g. `roles/`) and the galaxy path.

I don't know in your case if you're using galaxy or not, but here are two possible `ansible.cfg` configurations when your roles are not stored in the default paths.

### All the roles in the same place

All roles (installed via galaxy or not) are stored in the same place, but not in a `roles/` directory relative to the ansible playbook file.

```
[defaults]
roles_path = /path/to/my/roles
```

### Galaxy roles are separately installed

```
[defaults]

# The order is important, as the last directory will be used 
# as default target directory by ansible-galaxy
roles_path = /path/to/my/roles:/path/to/galaxy/roles
```

In this case, you'll have to set a custom value for the `galaxy_role_file` option in your Vagrantfile:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.galaxy_role_file = "requirements.yml"
    # override the galaxy command, as the roles path is specified in ansible.cfg,
    # and we don't want Vagrant to install into the 'roles/' directory.
    ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --force"
  end
end
```

I hope it will help you to configure you project as desired...

-----

See also https://groups.google.com/forum/#!topic/ansible-project/vOTvjd6z-iw

**Comment by james-portman** [comment]
Thanks for the response, but it seems some of that is not true.

with:
```
[defaults]
roles_path = ansible-not-galaxy-roles:ansible-galaxy-roles
```
and
```
    ansible.galaxy_role_file = "requirements.yml"
    ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --force"
```
```
    default: Running ansible-galaxy...
- extracting apache_install to /home/jamespo/x/tests/ansible-not-galaxy-roles/apache_install
```

**Comment by gildegoma** [comment]
@james-portman it seems that `ansible-galaxy` is not consistent in this regard (seems to depend if the paths are absolute or relative paths, etc), but I am pretty sure you can adjust the settings to fit your needs (at "worst" you still can specify the exact target directory with Vagrant's `ansible.galaxy_roles_path` option (and keep `galaxy_command` unchanged).

As said, the use cases described here are not "mainstream", and Ansible and Vagrant tools are flexible enough in my opinion to address them. Hence closing... Thank you!

**Comment by james-portman** [comment]
In case it helps anyone, my solution was to use the full path for the role being tested, then any role path is only used for dependecies.
I get the full path using `{{ playbook_dir | dirname }}`

tests/Vagrantfile:
```
ansible.galaxy_roles_path = ".vagrant/roles"
ansible.galaxy_role_file = "requirements.yml"
```

playbook:
```
- hosts: all
  roles:
    - some_dependency_from_requirements_yml
    - "{{ playbook_dir | dirname }}"

```
