### ISSUE TITLE
The package of "PHP"  is not installed from "ppa: ondrej / php"

### ISSUE THREAD

**Issue by Robocop01** [hashicorp/vagrant#9122]
##  The error is as follows:

`TASK [php : add php ppa] *******************************************************
fatal: [joomla]: FAILED! => {"changed": false, "failed": true, "msg": "Invalid repository string: ppa:ondrej/php"}

PLAY RECAP *********************************************************************
joomla                     : ok=4    changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

 ##  Vagrant version
1.8.1+dfsg-1

 ##  ansible        
2.0.0.2-2ubu

 ##  Host operating system
Ubuntu 16.04 LTS

 ##  Guest operating system
debian/jessie64

 ##  tasks/main.yml

`- name: add php ppa
  apt_repository: repo='ppa:ondrej/php' state=present

- name: update apt cache
  apt: update_cache=yes

- name: install php requirements for joomla
  apt: name=php{{ php.version }}-{{ item }} state=present
  with_items:
    - json
    - xml
    - mbstring
    - intl
    - apcache
    - pgsql `

 ##  Steps to reproduce
vagrant up
or 
vagrant provision

  ## my project
[https://github.com/Robocop01/vagrant_joomla](url)

**Comment by gildegoma** [comment]
Closing, as this is an upstream problem (Ansible `apt_repository` module error message: _"Invalid repository string: ppa:ondrej/php"_)

Tip: You can set the verbose option, and get the `ansible-playbook` command running behind the hood (for copy-paste your shell):

```ruby
         # Tell vagrant to run ansible as a provisioner
         joomla.vm.provision :ansible do |ansible|
             # where the playbook is located
             ansible.playbook = "provisioning/playbook.yml"
             # show the ansible-playbook command used by vagrant
             ansible.verbose = true
         end
```

**Comment by Robocop01** [comment]
I did upgrade:
ubuntu (update/upgrade)
vagrant to 2.0.0
ansible to 2.4.1.0
PC restart.
## The error disappeared!

## But, did appear another error
vagrant up
`TASK [php : add php ppa] *******************************************************
fatal: [joomla]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_7iENAO/ansible_module_apt_repository.py\", line 556, in <module>\r\n    main()\r\n  File \"/tmp/ansible_7iENAO/ansible_module_apt_repository.py\", line 544, in main\r\n    cache.update()\r\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 443, in update\r\n    raise FetchFailedException(e)\r\napt.cache.FetchFailedException: W:Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found\r\n, E:Some index files failed to download. They have been ignored, or old ones used instead.\r\n", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/artor/php-joomla-vm/provisioning/playbook.retry`

and (vagrant provision)
`TASK [php : update apt cache] **************************************************
fatal: [joomla]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."}
	to retry, use: --limit @/home/artor/php-joomla-vm/provisioning/playbook.retry
`
