### ISSUE TITLE
The package of "PHP" is not installed from "ppa: ondrej / php (2)

### ISSUE THREAD

**Issue by Robocop01** [hashicorp/vagrant#9124]
## The error is as follows:

`vagrant up
TASK [php : add php ppa] ******************************************************* fatal: [joomla]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n File \"/tmp/ansible_7iENAO/ansible_module_apt_repository.py\", line 556, in <module>\r\n main()\r\n File \"/tmp/ansible_7iENAO/ansible_module_apt_repository.py\", line 544, in main\r\n cache.update()\r\n File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 443, in update\r\n raise FetchFailedException(e)\r\napt.cache.FetchFailedException: W:Failed to fetch http://ppa.launchpad.net/ondrej/php/ubuntu/dists/jessie/main/binary-amd64/Packages 404 Not Found\r\n, E:Some index files failed to download. They have been ignored, or old ones used instead.\r\n", "msg": "MODULE FAILURE", "rc": 0} to retry, use: --limit @/home/artor/php-joomla-vm/provisioning/playbook.retry

and (vagrant provision)
TASK [php : update apt cache] ************************************************** fatal: [joomla]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update apt cache."} to retry, use: --limit @/home/artor/php-joomla-vm/provisioning/playbook.retry`

## I did upgrade:
ubuntu (update/upgrade) Ubuntu 16.04 LTS
vagrant to 2.0.0
ansible to 2.4.1.0
PC restart.

## Guest operating system
debian/jessie64

tasks/main.yml

`- name: add php ppa
apt_repository: repo='ppa:ondrej/php' state=present

    name: update apt cache
    apt: update_cache=yes

    name: install php requirements for joomla
    apt: name=php{{ php.version }}-{{ item }} state=present
    with_items:
        json
        xml
        mbstring
        intl
        apcache
        pgsql `

## Steps to reproduce
vagrant up
or
vagrant provision

my project
https://github.com/Robocop01/vagrant_joomla

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the Vagrant mailing list. There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
