### ISSUE TITLE
How setting two or more "ip" for one interface?

### ISSUE THREAD

**Issue by Robocop01** [hashicorp/vagrant#9125]
How setting two or more "ip" for one interface in Vagrantfile?

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the Vagrant mailing list. There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
