### ISSUE TITLE
Cannot create a private network with an Ubuntu 17.10 VM

### ISSUE THREAD

**Issue by EMegamanu** [hashicorp/vagrant#9134]
### Vagrant version
Vagrant 2.0.0

### Host operating system
Windows 7 Enterprise 64 bits

### Guest operating system
Ubuntu 17.10 Artful Aardvark 64 bits

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/artful64"
  
  config.vm.provision "docker"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  #config.vm.network :forwarded_port, guest: 8888, host: 8888
  config.vm.network "private_network", ip: "192.168.56.2"
  
end
```

### Debug output
https://gist.github.com/EMegamanu/6a5668c4bfa8355d6779abbf1c692fe5

### Expected behavior
Private network should be configured with commands ifdown / ifup

### Actual behavior
Private network setting fails because these commands were removed in Ubuntu 17.10 : https://wiki.ubuntu.com/ArtfulAardvark/ReleaseNotes

### Steps to reproduce
1. vagrant up with the provided Vagrantfile

**Comment by frickenate** [comment]
Yeah, vagrant cannot be used with Ubuntu 17.10 at the moment, due to the removal of the traditional networking configuration tools and files. Ubuntu has decided that `systemd` should completely destroy yet another component of the OS. Vagrant will need to support both the new `netplan` networking config for 17.10+, while maintaining the legacy `/etc/network/interfaces` method.

**Comment by chrisroberts** [comment]
As a workaround until the guest capabilities have been updated, installing the `net-tools` package on the guest should make things work.

**Comment by MartinanderssonDotcom** [comment]
My box `fso/artful64` said that `net-tools` is "already the newest version"; i.e., installed. However, installing `ifupdown` did the trick.

To be perfectly clear, first `vagrant up` will crash. Then `vagrant ssh` into the machine and run:

    sudo apt-get update
    sudo apt-get install -y ifupdown

Ex out and run `vagrant reload`. Boom. Network configured. A bit messy, but I guess it's doable for now.

Does anyone know when Vagrant 2.0.2 is released?

**Comment by mpdude** [comment]
@chrisroberts I suspect `net-tools` might be the wrong package as it does not contain `/sbin/ifup` and friends (see [file list](https://packages.ubuntu.com/artful/amd64/net-tools/filelist)).

`ifupdown` looks like a better choice.

**Comment by domnulnopcea** [comment]
is this issue going to be addressed any time soon?

**Comment by mpdude** [comment]
This problem still persists with the current `v20171220.0.0` box image (dunno if the box update even affects it).

**Comment by martinanderssondotcom** [comment]
Or, if you can handle a more beautiful desktop that according to my experience is even faster than GNOME, use box [`pristine/ubuntu-budgie-17-x64`][vagrant]. It has `net-tools` and `ifupdown` baked in. Plus, you [know exactly how it was built][github].

[vagrant]: https://app.vagrantup.com/pristine/boxes/ubuntu-budgie-17-x64
[github]: https://github.com/martinanderssondotcom/box-ubuntu-budgie-17-x64

**Comment by briancain** [comment]
@domnulnopcea @mpdude - a pull request has been made that includes support netplan in Ubuntu 17.10. You can see that at #9338

**Comment by mpdude** [comment]
Thanks!

**Comment by ljakab** [comment]
I just tested the freshly released Vagrant 2.0.2 with the current version of the `ubuntu/artful64` box (20180126.0.0) and the Vagrantfile mentioned in this issue (after a more complex Vagrant setup failed to bring up the private networks). I was hoping that pull request #9338 solved the issue, it is even mentioned in the [ChangeLog](https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md#202-january-29-2018), but Vagrant still tries to use the old `/sbin/ifup` way of configuring private networks, which fails.

Should I open a new issue, or can someone reopen this one?

**Comment by mpdude** [comment]
Haven't yet checked Vagrant 2.0.2.

But, if you're using the workaround above and are installing `ifupdown`, you might also run into issues on `vagrant reload` when vagrant tries to re-configure network interfaces.

This is due to [this bug](https://bugs.launchpad.net/juju/+bug/1737640). So, you additionally need to download [a fixed version of ubuntu-fan](http://de.archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-fan/ubuntu-fan_0.12.9_all.deb) and `dpkg -i` install it.

**Comment by ljakab** [comment]
@mpdude I'm not using the workaround to install `ifupdown`. Vagrant 2.0.2 added netplan support, and that does work with `bento/ubuntu-17.10` but for whatever reason, it doesn't with `ubuntu/artful64`.

**Comment by NoahO** [comment]
I'm also using Vagrant 2.0.2 and seeing errors like this with bento/ubuntu-17.10

`The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown 'eth1' || true
/sbin/ip addr flush dev 'eth1'
# Remove any previous network modifications from the interfaces file
sed -e '/^#VAGRANT-BEGIN/,$ d' /etc/network/interfaces > /tmp/vagrant-network-interfaces.pre
sed -ne '/^#VAGRANT-END/,$ p' /etc/network/interfaces | tac | sed -e '/^#VAGRANT-END/,$ d' | tac > /tmp/vagrant-network-interfaces.post
cat \
  /tmp/vagrant-network-interfaces.pre \
  /tmp/vagrant-network-entry \
  /tmp/vagrant-network-interfaces.post \
  > /etc/network/interfaces
rm -f /tmp/vagrant-network-interfaces.pre
rm -f /tmp/vagrant-network-entry
rm -f /tmp/vagrant-network-interfaces.post

/sbin/ifup 'eth1'

Stdout from the command:



Stderr from the command:

bash: line 4: /sbin/ifdown: No such file or directory
bash: line 18: /sbin/ifup: No such file or directory`

**Comment by mpdude** [comment]
@NoahO Use `vagrant ssh` to ssh into the box after this error occured. 

Then, try 
```
sudo apt-get update
sudo apt-get install -y ifupdown wget
wget http://de.archive.ubuntu.com/ubuntu/pool/main/u/ubuntu-fan/ubuntu-fan_0.12.9_all.deb
dpkg -i ubuntu-fan_0.12.9_all.deb
```
Exit the SSH session and `vagrant reload`. 

@briancain Could you please re-open this issue? Seems it is not properly resolved.

**Comment by chrisroberts** [comment]
Hi all. I've created a new issue to track this here: #9428

Cheers!

**Comment by mpdude** [comment]
For me, Vagrant 2.0.3 works 👍

**Comment by xikaos** [comment]
Installing ifupdown solved the problem for me.
