### ISSUE TITLE
macOS Vagrant 2.0.1 error /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/specification.rb:17

### ISSUE THREAD

**Issue by fkoji** [hashicorp/vagrant#9136]
### Vagrant version

2.0.1

### Host operating system

macOS Sierra 10.12.6

### Expected behavior

Display version

### Actual behavior

```
% vagrant --version
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/specification.rb:17:in `require': dlopen(/opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle, 9): no suitable image found.  Did find: (LoadError)
	/opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle: malformed mach-o image: load command #17 length (0) too small in /opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle
	/opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle: malformed mach-o image: load command #17 length (0) too small in /opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle - /opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/specification.rb:17:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems.rb:1334:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems.rb:1334:in `<module:Gem>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems.rb:116:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

### Steps to reproduce

Install Vagrant 2.0.1 and exec `vagrant --version`

**Comment by rogeriopradoj** [comment]
same happens when running any vagrant subcommands, ou just vagrant as well

```
vagrant

vagrant version

vagrant --help

# etc.
```

**Comment by kamilgrzegorczyk** [comment]
Same here. Cannot Start or stop machines

**Comment by addnull** [comment]
Same here.

# Vagrant version

2.0.1

# Host operating system

macOS High Sierra 10.13.1

# Steps to reproduce

all vagrant commands including just `vagrant`.

**Comment by paolostivanin** [comment]
+1

**Comment by razvaniacob** [comment]
I have the exact same problem. Any solution to that?

**Comment by memoryleak** [comment]
**vagrant** 
```
/opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/specification.rb:17:in `require': dlopen(/opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle, 9): no suitable image found.  Did find: (LoadError)
	/opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle: malformed mach-o image: load command #17 length (0) too small in /opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle
	/opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle: malformed mach-o image: load command #17 length (0) too small in /opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle - /opt/vagrant/embedded/lib/ruby/2.4.0/x86_64-darwin13/stringio.bundle
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems/specification.rb:17:in `<top (required)>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems.rb:1334:in `require'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems.rb:1334:in `<module:Gem>'
	from /opt/vagrant/embedded/lib/ruby/2.4.0/rubygems.rb:116:in `<top (required)>'
	from <internal:gem_prelude>:4:in `require'
	from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
```

Same here: Mac OS High Sierra with vagrant 2.0.1

**Comment by Superpencil** [comment]
Ditto

**Comment by robertzakrocki** [comment]
Same here :(

**Comment by m4rkw** [comment]
Me too. Sigh.

**Comment by m4rkw** [comment]
this seems like the best solution for now:

````
$ wget https://releases.hashicorp.com/vagrant/2.0.0/vagrant_2.0.0_x86_64.dmg
````

**Comment by MarkParnabyVS** [comment]
Same issue here, as above v2.0.0 works for me, so I'll be using that for now.

**Comment by m4rkw** [comment]
Hmmmmmm: https://www.hashicorp.com/devops-defined#done-right

**Comment by mroest** [comment]
Same here :(

**Comment by prasanna** [comment]
Same issue here.

I'm guessing there's an issue with the ruby that is bundled with Vagrant - is it for the right architecture (x86_64)?

**Comment by rpkoller** [comment]
same error on 10.11.6 :(

**Comment by m4rkw** [comment]
@prasanna seems to be

````
$ file stringio.bundle
stringio.bundle: Mach-O 64-bit bundle x86_64
````

**Comment by m4rkw** [comment]
Oh wait, darwin13 is wrong, it should be 17 for 10.13

**Comment by m4rkw** [comment]
No that's a red herring, 2.0.0 uses darwin13 as well and that works.

**Comment by Autive** [comment]
Same here

**Comment by mark1282** [comment]
same

**Comment by sanditech** [comment]
Same issue on macOS Sierra 10.12.6

**Comment by michaeltrojanek** [comment]
Note that Vagrant 2.0.0 does not support VirtualBox 5.2, so you'll want to keep VirtualBox 5.1.30 until the issue is fixed.

**Comment by freshp** [comment]
+1

**Comment by SinoBoeckmann** [comment]
As mentioned before:

This is a currently working stack (macOS):
- https://www.virtualbox.org/wiki/Download_Old_Builds_5_1
- https://releases.hashicorp.com/vagrant/2.0.0/vagrant_2.0.0_x86_64.dmg

My System: macOS 10.13.1

**Comment by ancascres** [comment]
Same problem here:
- macOS High Sierra 10.13.1
- Vagrant 2.0.1
- VirtualBOX 5.1.30

I fixed it going to Vagrant 2.0.0 again.

**Comment by sdkuck** [comment]
Upgrading to Ruby 2.4.0 as part of a x.0.1 release. Interesting.

**Comment by akopitsa** [comment]
The same error

**Comment by maka-nai** [comment]
same

**Comment by yamil-urbina-tierconnect-com** [comment]
same 😢

**Comment by rpkoller** [comment]
I really hope that an updated and working version of the `2.0.1` installer for OS X could be provided today. Not that we have to wait until the next regular release with version `2.0.2`. :/

**Comment by pengbs** [comment]
same issue

**Comment by luiscpereira** [comment]
Same here

**Comment by queeno** [comment]
Same issue here

**Comment by embusalacchi** [comment]
Same issue MacOS 10.13.1

**Comment by EdwardIII** [comment]
Same on 10.12.5

**Comment by jenhsun** [comment]
It's looked like newest 2.0.1 version use Ruby 2.4.0 version. My guess the file `stringio.bundle` is crashed during packaging...
I look back version 2.0.0 `stringio.bundle` at
`/opt/vagrant/embedded/lib/ruby/2.3.0/x86_64-darwin13`
size is about 44,292. How about the newest one?

My macOS 10.13.1 and use vagrant 2.0.0. Still hasn't upgrade yet!

**Comment by wagenet** [comment]
@jenhsun for 2.4.0 it is 35,812.

**Comment by dhoer** [comment]
@briancain Is it possible to use travis to verify vagrant on macOS platforms in the future? https://docs.travis-ci.com/user/reference/osx/

**Comment by jkrauska** [comment]
+1

**Comment by wagenet** [comment]
If someone can build Ruby 2.4.0 for darwin13, we could probably copy that file over.

**Comment by callahm3** [comment]
+1 here

**Comment by SeanSanker** [comment]
+1

**Comment by chrisroberts** [comment]
Hi everyone,

Fixed package has been built and uploaded. You can download the fixed package here:

https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.dmg

Thank you for the report on this issue and the patience in getting it resolved. I'll leave this issue open for a bit even though it is resolved to provide visibility for anyone that may still have the previous package.

Cheers!

**Comment by austinlparker** [comment]
I'm now seeing issues running Vagrant commands due to plugins; Repair failed, running `vagrant plugin expunge --reinstall` gave this output -

```
This command permanently deletes all currently installed user plugins. It
should only be used when a repair command is unable to properly fix the
system.

Continue? [N]: Y

All user installed plugins have been removed from this Vagrant environment!

Vagrant will now attempt to reinstall user plugins that were removed.
Installing the 'vagrant-chef-zero' plugin. This can take a few minutes...
Fetching: mixlib-log-1.7.1.gem (100%)
Fetching: hashie-2.1.2.gem (100%)
Fetching: libyajl2-1.2.0.gem (100%)
Building native extensions.  This could take a while...
Fetching: ffi-yajl-1.4.0.gem (100%)
Building native extensions.  This could take a while...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

ERROR: Failed to build gem native extension.

    current directory: /Users/aparker/.vagrant.d/gems/2.4.2/gems/ffi-yajl-1.4.0/ext/ffi_yajl/ext/encoder
/opt/vagrant/embedded/bin/ruby -r ./siteconf20171103-93065-1y3ywyz.rb extconf.rb
 -I/Users/aparker/.vagrant.d/gems/2.4.2/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/include -I/opt/vagrant/embedded/include -I/vagrant-substrate/cache/ruby-2.4.2/include -O3 -fno-common -pipe
 -L/Users/aparker/.vagrant.d/gems/2.4.2/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib -L. -L/opt/vagrant/embedded/lib  -Wl,-rpath,@loader_path/../lib -Wl,-rpath,@executable_path/../lib -Wl,-rpath,/opt/vagrant/embedded/lib -fstack-protector -L/usr/local/lib -L/opt/vagrant/embedded/lib
checking for yajl/yajl_tree.h... yes
creating Makefile

current directory: /Users/aparker/.vagrant.d/gems/2.4.2/gems/ffi-yajl-1.4.0/ext/ffi_yajl/ext/encoder
make "DESTDIR=" clean

current directory: /Users/aparker/.vagrant.d/gems/2.4.2/gems/ffi-yajl-1.4.0/ext/ffi_yajl/ext/encoder
make "DESTDIR="
compiling encoder.c
encoder.c:382:20: error: use of undeclared identifier 'rb_cFixnum'
  rb_define_method(rb_cFixnum, "ffi_yajl", rb_cFixnum_ffi_yajl, 2);
                   ^
encoder.c:383:20: error: use of undeclared identifier 'rb_cBignum'
  rb_define_method(rb_cBignum, "ffi_yajl", rb_cBignum_ffi_yajl, 2);
                   ^
2 errors generated.
make: *** [encoder.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/aparker/.vagrant.d/gems/2.4.2/gems/ffi-yajl-1.4.0 for inspection.
Results logged to /Users/aparker/.vagrant.d/gems/2.4.2/extensions/x86_64-darwin-13/2.4.0/ffi-yajl-1.4.0/gem_make.out
```

**Comment by wagenet** [comment]
@austinlparker this is probably related to the 2.4.0 change, but I suspect it's an issue with the plugin itself. Either way, it sounds like a new ticket.

**Comment by wagenet** [comment]
@chrisroberts that fixed things for me. Thanks!

**Comment by m4rkw** [comment]
Hey @chrisroberts I've just noticed here: https://www.hashicorp.com/devops-defined

That the grammar under the Test section is a bit weird.  Eg:

"Test while an application is being written and prior to release, it goes through multiple types of testing."

That reads like the word "test" has been arbitrarily prefixed at the beginning of the sentence and perhaps shouldn't be there, in any case it doesn't read like a proper sentence.

Also:

"The simplest tests, unit testing, is done by developers"

shouldn't "is" be "are" in this sentence?

**Comment by gskerry** [comment]
Patched version fixed for me as well. (10.13.1). 
Thanks.

**Comment by rpkoller** [comment]
thank for the fast fix @chrisroberts ! and also thanks for the somehow better and more descriptive error messages in vagrant 2.x. with those i was able to track down an issue with starting a certain vm ;)

**Comment by mark1282** [comment]
Can confirm all is working good my end. Thanks for the quick fix!

**Comment by chrisroberts** [comment]
Hi @m4rkw, thanks for the feedback on that page. I'll be sure it gets passed along for review :smiley:

**Comment by BillBeal** [comment]
@chrisroberts  I downloaded and installed the fix. It works.  Thanks a lot.

**Comment by fkoji** [comment]
@chrisroberts It works! Thanks a lot!

**Comment by SinoBoeckmann** [comment]
Smooth and clean! Everything is working as expected!
Thank you! :)

**Comment by sanditech** [comment]
Working on my machine now. Thanks!
