### ISSUE TITLE
vagrant destroy exits 1 when no running vm found

### ISSUE THREAD

**Issue by snowman78** [hashicorp/vagrant#9137]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 10

### Guest operating system
Centos/Windows2K12

### Expected behavior
Vagrant should exit 0 if attemting to destroy a vm that is not running.   This was the behaviour of destroy until 2.0.1

### Actual behavior
vagrant now exits 1 of no running vm found

### Steps to reproduce
$ vagrant destroy k8s_node
==> k8s_node: VM not created. Moving on...
$ echo $?
1

**Comment by ColinHebert** [comment]
This issue has been introduced with https://github.com/hashicorp/vagrant/pull/9127

Previously a check was done when counting the "declined instances":
```ruby
declined += 1 if action_env.key?(:force_confirm_destroy_result) && action_env[:force_confirm_destroy_result] == false
```

The behaviour introduced checks whether the state of the machine changed instead: `if m.state.id == init_states[m.name]`

**Comment by briancain** [comment]
@ColinHebert - Yep, it was a regression that I introduced with that commit when I was doing some cleanup of that command. It's planned to be fixed for the next release. Apologies for any problems this might have caused! 😞
