### ISSUE TITLE
On Windows 10 vagrant up kills VM and start new one on vagrant up (sometimes) after windows sleep

### ISSUE THREAD

**Issue by sergionegri** [hashicorp/vagrant#9139]
### Vagrant version
2.0.0

### Host operating system
Win 10 64 bit

### Guest operating system
Ubuntu 16

### Expected behavior
Running a VM.
Keeping it running.
Sleep Windows host.
Wake Windows host from sleep.
Have the VM still running (this happens)
Vagrant detecting that the machine is still running (sometimes does not happen)

### Actual behavior
I halt make windows sleep. Sometimes after sleep the machine is running, but if I do a vagrant halt it says it does not exist. And a vagrant up fires up a new one (if I'm lucky, otherwise it cannot fire because there is a VM running, but global status says it's not)

### Steps to reproduce
See expected behavior

### Additional considerations
As I need smb I need to run as admin via cmd. I also perform on a daily basis at least a "sleep" of the pc. When I wake it up the VM is still up and running. But as sometimes it seems to lose connection with the external world (e.g. I cannot ping from inside to outside). So I perform a vagrant halt and vagrant up. Sometimes all works well. Sometimes it doesn't.

### More experiments
Today I tried not to change the vagrant file. I simply had a running machine (waking up windows after sleep). I did a change of directory in host: it responded (so it was alive). While the machine was running I ran:

```
C:\Users\sergio\PhpstormProjects\main>vagrant global-status
id       name   provider state  directory
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.
```

So I tried a vagrant halt to halt the machine (that is running!!!) but got told no machine was running.

Ok, let's do a vagrant up:

```
C:\Users\sergio\PhpstormProjects\main>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/xenial64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/xenial64' is up to date...
==> default: Setting the name of the VM: main_default_1509782975663_5386
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 3309 is already in use
on the host machine.
```

No way, really? Yes, the port is used by the running VM!

Ok let's see what we have here:

```
C:\Users\sergio\VirtualBox VMs>dir
 Volume in drive C has no label.
 Volume Serial Number is 54DB-2EB9

 Directory of C:\Users\sergio\VirtualBox VMs

04/11/2017  09:09    <DIR>          .
04/11/2017  09:09    <DIR>          ..
29/10/2017  17:36    <DIR>          main_default_1509294377036_35535
02/11/2017  12:08    <DIR>          main_default_1509529683954_97293
03/11/2017  18:10    <DIR>          main_default_1509621032619_66437
03/11/2017  18:12    <DIR>          main_default_1509729098573_69522
04/11/2017  09:09    <DIR>          main_default_1509782975663_5386
```

So machines are there, but Vagrant does not see them!

**Comment by soapy1** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier ☹️

Cheers!
