### ISSUE TITLE
'Global-Status' missing in Bash completion Script 

### ISSUE THREAD

**Issue by arky** [hashicorp/vagrant#9140]
Please kindly add support for global-status subcommand in bash completion script with vagrant package on gnu/Linux. 

### Vagrant version
Vagrant 2.0.0

### Host operating system
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
### Expected behavior
Typing vagrant `globa<tab>` should autocomplete.

### Actual behavior
Typing vagrant `globa<tab>` has no effect,

### Steps to reproduce
1. Open terminal 'vagrant globa
2. Press 'tab' key 
3.The bash doesn't autocomplete the command.

**Comment by n-rodriguez** [comment]
Hi! It looks like a bug : https://github.com/hashicorp/vagrant/blob/master/contrib/bash/completion.sh#L56

**Comment by briancain** [comment]
This seems to have been fixed already, so I'm going to go ahead and close it. Thanks!

```
vagrant@vagrant:~$ source /etc/bash_completion.d/vagrant
vagrant@vagrant:~$ vagrant
box            docker-exec    halt           login          push           rsync          ssh            up
cloud          docker-logs    help           package        rdp            rsync-auto     ssh-config     version
connect        docker-run     init           plugin         reload         share          status
destroy        global-status  list-commands  provision      resume         snapshot       suspend
vagrant@vagrant:~$ vagrant global-status
id       name   provider state  directory
--------------------------------------------------------------------
There are no active Vagrant environments on this computer! Or,
you haven't destroyed and recreated Vagrant environments that were
started with an older version of Vagrant.
```
