### ISSUE TITLE
Vagrant cannot run on windows in a directory that has a subdirectory named C

### ISSUE THREAD

**Issue by uapmous** [hashicorp/vagrant#9148]
After installing Vagrant 2.0.1 on Windows 7, I found that vagrant can't run at all if it is running in a directory that has a subdirectory named "C".  

Here is a trivial reproduction of the issue:

C:\>mkdir vtest

C:\>cd vtest

C:\vtest>vagrant version
Installed Version: 2.0.1
Latest Version: 2.0.1

You're running an up-to-date version of Vagrant!

C:\vtest>mkdir C

C:\vtest>vagrant version
Vagrant failed to initialize at a very early stage:

The plugins failed to initialize correctly. This may be due to manual
modifications made within the Vagrant home directory. Vagrant can
attempt to automatically correct this issue by running:

  vagrant plugin repair

If Vagrant was recently updated, this error may be due to incompatible
versions of dependencies. To fix this problem please remove and re-install
all plugins. Vagrant can attempt to do this automatically by running:

  vagrant plugin expunge --reinstall

Or you may want to try updating the installed plugins to their latest
versions:

  vagrant plugin update

Error message given during initialization: Is a directory @ rb_sysopen - C

 C:\vtest>                                                                                                                                                       

**Comment by jmbejara** [comment]
I'm having the same issue. I can replicate the error using the steps described above. I'm running Vagrant 2.0.2 with VirtualBox 5.2.6 on Windows 10 (Version 1709, OS Build 16299.192).

**Comment by fy0** [comment]
Error message given during initialization: Is a directory @ rb_sysopen - C
Same issue, I used to think "C" means c lang or c lib and a shutdown broke my vm ....
vagrant-2.1.2, win 10 lasted

**Comment by gebailey** [comment]
Glad I found this issue; couldn't figure out why I couldn't run any vagrant commands in my home directory (which has a "c" subdirectory)...  Running vagrant 2.2.3 on Windows 10.
