### ISSUE TITLE
There was an error while executing `VBoxManage`, a CLI used by Vagrant for controlling VirtualBox.

### ISSUE THREAD

**Issue by edherroj** [hashicorp/vagrant#9152]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
$ vagrant --version
Vagrant 2.0.0

### Host operating system
Windows 10 - 64bits

### Guest operating system
/ubuntu1604-x64

### Vagrantfile

```ruby
# -*- mode: ruby -*-
dir = File.dirname(File.expand_path(__FILE__))
require 'yaml'
require "#{dir}/puphpet/ruby/deep_merge.rb"
require "#{dir}/puphpet/ruby/to_bool.rb"
require "#{dir}/puphpet/ruby/puppet.rb"
configValues = YAML.load_file("#{dir}/puphpet/config.yaml")
provider = ENV['VAGRANT_DEFAULT_PROVIDER'] ? ENV['VAGRANT_DEFAULT_PROVIDER'] : 'local'
if File.file?("#{dir}/puphpet/config-#{provider}.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-#{provider}.yaml")
  configValues.deep_merge!(custom)
end
if File.file?("#{dir}/puphpet/config-custom.yaml")
  custom = YAML.load_file("#{dir}/puphpet/config-custom.yaml")
  configValues.deep_merge!(custom)
end
data = configValues['vagrantfile']
Vagrant.require_version '>= 1.8.1'
Vagrant.configure('2') do |config|
  eval File.read("#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}")
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
Expected to reproduce a custom environment using VirtualBox for WordPress theme development.

### Actual behavior

```
Eduardo's PC@LAPTOP-7MVVJUG0 MINGW64 ~/Documents/Root/local-sites
$ vagrant up

Bringing machine 'bradphp' up with 'virtualbox' provider...
==> bradphp: Importing base box 'puphpet/ubuntu1604-x64'...
==> bradphp: Matching MAC address for NAT networking...
==> bradphp: Checking if box 'puphpet/ubuntu1604-x64' is up to date...
==> bradphp: Setting the name of the VM: local-sites_bradphp_1510104058138_3151
==> bradphp: Clearing any previously set network interfaces...
==> bradphp: Preparing network interfaces based on configuration...
    bradphp: Adapter 1: nat
    bradphp: Adapter 2: hostonly
==> bradphp: Forwarding ports...
    bradphp: 22 (guest) => 7537 (host) (adapter 1)
    bradphp: 22 (guest) => 2222 (host) (adapter 1)
==> bradphp: Running 'pre-boot' VM customizations...
==> bradphp: Booting VM...
**There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.**

Command: ["startvm", "94e1293c-f8f0-4492-a7f8-63d10e2b242e", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'bradphp.puphpet' has terminated unexpectedly during startup with exit code -1073741424 (0xc0000190).  More details may be available in 'C:\Users\Eduardo's PC\VirtualBox VMs\bradphp.puphpet\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine
```

### Steps to reproduce
1. Install VirtualBox 5.1.30
2. Install Vagrant 2.0.0
3. Run vagrant file

### References
Are there any other GitHub issues (open or closed) that should be linked here?

**Comment by briancain** [comment]
Hi @edherroj - Can you please provide the following to help us triage your issue....

- A gist link containing the full output of Vagrant with the `--debug` flag
- A gist link containing the contents of that VirtualBox log `'C:\Users\Eduardo's PC\VirtualBox VMs\bradphp.puphpet\Logs\VBoxHardening.log'`
- Your Vagrantfile. It looks like the one you shared is just loading configs, and the actual one is located some where at....`"#{dir}/puphpet/vagrant/Vagrantfile-#{data['target']}"`

Thanks!

**Comment by edherroj** [comment]
@briancain I uninstalled everything, vagrant, virtualbox and gitbash, and after reinstalling all again (using updated version of vagrant 2.0.1) it created the suggested virtual host environment we were told in our online course. I don't understand why this time it worked, but I think it had to do with vagrant version and the command line not being used with admin privileges. 

Thank you for your time! I appreciate.

**Comment by behestee** [comment]
For me the issue was virtual box did not installed or allowed to be run. I followed this instruction and now it worked. The basics is on MacOSX High Siera blocked the application to be installed from DMG packages or from oracle I am not sure, but it blocked virtual box is true.

https://apple.stackexchange.com/questions/301303/virtualbox-5-1-28-fails-to-install-on-macos-10-13-due-to-kext-security
