### ISSUE TITLE
Vagrant attempts to downgrade Virtualbox guest additions without any real need

### ISSUE THREAD

**Issue by gggeek** [hashicorp/vagrant#9153]
### Vagrant version
2.0.1

### Host operating system
win 8.1 64bit

### Guest operating system
Debian 8

### Debug output
https://gist.github.com/gggeek/c6c56d7e0fc714ee058d20e555fe230e

### Expected behavior
Vagrant should not automatically attempt to downgrade existing Guest Additions from A.B.D to A.B.C - at least for minor revision numbers.

### Actual behavior
I recently upgraded Virtualbox to the latest release: 5.2.0. Then downloaded the Guest Additions pack.
I then started manually a VM that I generally manage via Vagrant, and proceeded to upgrade the Guest Additions following the standard Virtualbox procedure (mount the Guest Additions pack as cdrom etc...).
This left me with a VM working fine. The Guest Additions inside the VM were reporting version 5.2.1.
I then shut down the VM, and started it via Vagrant.
Vagrant then duly proceeded to attempt a downgrade of the Guest Additions inside the VM from version 5.2.1 to version 5.2.0.
The funny thing is: since Vagrant uses the same start media for this 'downgrade' as was already used for the installation of the G.A., the whole process ends up being, in this case, just a waste of time - the final version of the G.A. will be 5.2.1.
But I have the suspicion that Vagrant will do the same on every restart of that VM...

I am not sure how to best fix this: how does Vagrant know which versions of the G.A. are available on the host, and which ones are compatible with the current VBox version running on the host?
In my case it seems that VBox 5.2.0 thinks that G.A. 5.2.1 are fine, but Vagrant is not aware of this. It is also not aware that the GAs available on the source media are at version 5.2.1 and not 5.2.0...

I would say that, if there is no better way of determining what are 'compatible' versions, the default should probably be: trust semantic versioning and do not downgrade existing Guest Additions from A.B.D to A.B.C with C < D

**Comment by pauln** [comment]
@gggeek I was experiencing this issue too, but it seems to have been a quirk in VBox's handling of Guest Additions with VBox v5.2.0.  If you're still experiencing this issue, try updating to VBox 5.2.2  - it's stopped the senseless non-downgrading for me.  The first boot after upgrading resulted in the Guest Additions being updated to 5.2.2, and now that everything matches, Vagrant is happy and doesn't mess with Guest Additions on subsequent boots.

**Comment by gggeek** [comment]
I confirm that, having upgraded to VBox 5.2.2, the problem is not happening any more.

However, I am not sure if it "fixed itself" because the way that VBox reports the version numbers to Vagrant was fixed, or simply because at the moment, as you said, version numbers match.

I guess we'll have to wait for when/if Oracles releases VBox Guest Additions 5.2.3 to see if the downgrading starts to happen again...

**Comment by chrisroberts** [comment]
Hi there,

Vagrant won't attempt to upgrade/downgrade guest additions automatically. This upgrade appears to be happening outside of Vagrant, either via plugin or vbox itself.

Cheers!
