### ISSUE TITLE
2.0.1 break nfs detection on debian Jessie

### ISSUE THREAD

**Issue by stevenh** [hashicorp/vagrant#9154]
After updating to vagrant 2.0.1 all our VM's fail to start, complaining about "machine doesn't support NFS"

After debugging the issue the problem was caused by: https://github.com/hashicorp/vagrant/pull/8938

The issue is two fold:
1. The service is nfs-kernel-server and not nfs-server
2. The service doesn't include a unit file so using list-unit-files fails to find the service, list-units is what's needed

### Vagrant version
Vagrant 2.0.1

### Host operating system
Debian Jessie (8.9)

### Guest operating system
ubuntu

### Debug output
 INFO subprocess: Starting process: ["/bin/sh", "-c", "systemctl --no-pager --no-legend --plain list-unit-files --all --type=service | grep nfs-server.service"]
 INFO subprocess: Command not in installer, restoring original environment...

### Expected behavior
vagrant up succeeds

### Actual behavior
It appears your machine doesn't support NFS, or there is not an
adapter to enable NFS on this machine for Vagrant. Please verify
that `nfsd` is installed on your machine, and try again. If you're
on Windows, NFS isn't supported. If the problem persists, please
contact Vagrant support.

### Steps to reproduce
1. vagrant up for a vm which mounts an NFS volume

### References
The following PR caused this breakage: https://github.com/hashicorp/vagrant/pull/8938

**Comment by chrisroberts** [comment]
Fixed via #9274
