### ISSUE TITLE
BSD guest fails to apply provisioning configuration on vagrant up [--provision]

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9157]
I'm trying to configure a base box for MINIX, temporarily leaning on the [Net]BSD guest plugin as a stopgap, when I noticed a strange behavior: BSD and NetBSD guest boxes appear to skip the provisioning step, bombing out instead on a message about shared folders.

### Vagrant version

Vagrant 2.0.0

### Host operating system

macOS Sierra

### Guest operating system

MINIX 3.4.0rc6

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/minix"

  config.vm.provision "file", source: "flag.txt", destination: "/home/vagrant/flag.txt"
  config.vm.provision "shell", path: "bootstrap.sh"
end
```

### flag.txt

```txt
all ur base are belong to us
```

### bootstrap.sh

```sh
#!/bin/sh
su root -c 'yes | pkgin update && yes | pkgin install curl'
```

The mcandre/minix box is a work in progress, built from a packer source in the "minix" feature branch of mcandre/packer-templates: https://github.com/mcandre/packer-templates/tree/minix/minix

### Expected behavior

What should have happened?

Vagrant should attempt to apply both the `file` and `shell` provisioning configuration.

### Actual behavior

What actually happened?

Vagrant exits early with a complaint about how BSD guests do not support shared folders:

```console
$ vagrant up
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'mcandre/minix'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: test_default_1510176773714_56104
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default: 
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Checking if machine supports zones: no
==> default: Mounting shared folders...
    default: /vagrant => /Users/andrew/go/src/github.com/mcandre/packer-templates/minix/test
Vagrant is not able to mount VirtualBox shared folders on BSD-based
guests. BSD-based guests do not support the VirtualBox filesystem at
this time.

To change the type of the default synced folder, specify the type as
rsync or nfs:

    config.vm.synced_folder ".", "/vagrant", type: "nfs" # or "rsync"

Alternatively, if you do not need to mount the default synced folder,
you can also disable it entirely:

    config.vm.synced_folder ".", "/vagrant", disabled: true

You can read more about Vagrant's synced folder types and the various
configuration options on the Vagrant website.

This is not a bug in Vagrant.
```

### Steps to reproduce

1. Build and import the mcandre/minix base box.
2. `cd` to the test directory with the Vagrantfile configured to run file and shel provisioners.
3. Run `vagrant up`.

### Notes

I suspect the [Net]BSD guest plugin is somehow causing Vagrant to exit before the provisioning phase.

I checked whether the problem was that the box was already up, by running `vagrant destroy -f; vagrant up`. Provisioning still failed to execute.

I also tried `vagrant up --provision`. Provisioning still failed to execute.

When I run `vagrant provision`, the file and shell provisioners finally executed! So I think the BSD guest plugin logic is exiting Vagrant during `up`, before `provision` would have run.

The file provisioner worked from `vagrant provision`, and the shell provisioner revealed an error in the base box to do with the fact that sudo is not available in MINIX. I patched the `config.vm.sudo_command` in the base box to use su instead, and then the shell provisioner ran as well. So the BSD guest lack of shared folder support exits provisioning early, hiding an error in the shell script provisioner, which fails quietly, hiding an error with a missing sudo. So many hidden errors, and at the top of them all is the BSD shared folder print-and-die-thingy!

I think it's silly that Vagrant bombs out entirely on BSD shared folders, rather than *implicitly* assuming that shared folders should, therefore, be disabled and then continuing on to provisioning. Oh well, I'm adding `config.vm.synced_folder '.', '/vagrant', disabled: true` to my boxes to force provisioning in the meantime. Whatevs.

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
