### ISSUE TITLE
vagrant rdp does not terminate until rdp session ends

### ISSUE THREAD

**Issue by DDSGooch** [hashicorp/vagrant#9163]
When running _vagrant rdp_, the command hangs until the rdp session is completed or the command is terminated with _CTRL-C_. This means that you cannot do anything else in this command console, which is very annoying and I'm sure it isn't designed to work this way, nor how it used to work.

In the example below (debug log attached), the rdp session started, then was terminated with _CTRL-C_.
```
>vagrant rdp
==> default: Detecting RDP info...
    default: Address: 127.0.0.1:33389
    default: Username: vagrant
==> default: Vagrant will now launch your RDP client with the connection parameters
==> default: above. If the connection fails, verify that the information above is
==> default: correct. Additionally, make sure the RDP server is configured and
==> default: running in the guest machine (it is disabled by default on Windows).
==> default: Also, verify that the firewall is open to allow RDP connections.

>Exiting due to interrupt.
```

More detailed debug log also attached.

### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 7 x64

### Guest operating system
Windows Server 2012

### Vagrantfile
```ruby
Vagrant.require_version ">= 1.8.7"

ip = '192.168.56.3'

Vagrant.configure("2") do |config|
  config.vm.box = "test_box_prereqs"
  config.vm.synced_folder "share", "/vagrant"

  config.vm.network "forwarded_port", guest: 80, host: 8010,
    auto_correct: true

  config.vm.network "private_network", ip: ip, auto_config: false

  config.vm.network "public_network", auto_config: true, bridge: "Intel(R) Dual Band Wireless-AC 8260"

  config.vm.provider "virtualbox" do |vb, override|
    override.vm.provision "shell", inline: "New-NetIPAddress #{ip} -PrefixLength 24 -InterfaceAlias 'Ethernet 2'"
  end

  config.vm.provider "vmware_desktop" do |vmware, override|
    override.vm.provision "shell", inline: "New-NetIPAddress #{ip} -PrefixLength 24 -InterfaceAlias 'Ethernet1'"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
  config.vm.provider "vmware_workstation" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "2"
  end

end
```
### Debug output
[vagrant.log](https://gist.github.com/DDSGooch/3d78cb7335cc6eb2bc488b06143ef255)

### Expected behavior
_vagrant rdp_ should start a remote desktop session, then quit, allowing the user to carry on using that console.

### Actual behavior
_vagrant rdp_ hangs until the session completes or is terminated.

### Steps to reproduce
1. Run vagrant rdp

**Comment by DDSGooch** [comment]
I've since realised it would be a really simple change and have actually patched my local copy of vagrant.

Edit
_C:\HashiCorp\Vagrant\embedded\gems\2.1.1\gems\vagrant-2.1.1\plugins\hosts\windows\cap\rdp.rb_
```
#Vagrant::Util::Subprocess.execute("mstsc", *args)
spawn("mstsc", *args)
```

**Comment by TonyApuzzo** [comment]
Nice!  I have been using a PowerShell alias:

```PowerShell
# Start Vagrant Remote Desktop Session in the background
function vrdp() {
  Start-Process -NoNewWindow vagrant.exe rdp @Args
}
```

**Comment by DDSGooch** [comment]
@TonyApuzzo thanks, it would be nice to get that included in the vagrant repo. I see you've added stuff before, is there any chance you could create a pull request for this?

**Comment by TonyApuzzo** [comment]
I'm just a shlub but I do have a local checkout of Vagrant's develop branch so I can take a crack at it.  Having a pull request does improve the likelyhood of getting a fix into the main.  Might be a while though since usually Vagrant releases are something like every 6 months give-or take.  I'll link the PR to this bug report.

**Comment by janvanveldhuizen** [comment]
I made a similar in change to use spawn() in the linux folder, because Linux has the same behavior. Perfect!  Thanks!
