### ISSUE TITLE
Multiple `vagrant up` executions on different machines create duplicated VMs

### ISSUE THREAD

**Issue by trombik** [hashicorp/vagrant#9164]
### Vagrant version

we are stacked with Vagrant 1.9.x due to a bug introduced in 2.0. but i think the version is not relevant.

### Host operating system

FreeBSD and Ubuntu

### Guest operating system

FreeBSD and OpenBSD

### Summary

When a machine is created by a user in a remote environment, `cloudstack` in our case, and when other user runs `vagrant up` on another machine, two machines are created.

One solution to this problem is managing ID files under `.vagrant/machines` by `git` or something. but this introduces a race condition, and does not prevent the issue from happening. The other would be some kind of lock, which does not look a good idea.

My workaround is syncing machine states before `Vagrant.configure`, which _reduces_ the race, together with operational local rules.

It would be nice for `vagrant` plug-in mechanism to provide plug-ins with something that makes it easier to workaround the issue.

Other workarounds that I am missing are appreciated.

### Vagrantfile

Cannot provide the full `Vagrantfile` because of corporate policy.

Here is the workaround we are currently using.

```ruby
case environment
when "prod"
  system "sh bin/sync.sh #{group_name}"
  unless $CHILD_STATUS.exitstatus.zero?
    $stderr.puts "`bin/sync.sh` failed."
    abort unless $CHILD_STATUS.exitstatus.zero?
  end 
end

Vagrant.configure("2") do |config|
  ...
end
```

`bin/sync.sh` is a script to sync machine states on remote. it fetches API responses and writes ID to state file on local file system if a machine is running on remote.

### Debug output
n/a

### Expected behavior

Multiple `vagrant up` executions on different machines do not create duplicated VMs.

### Actual behavior

Multiple VMs are created.

### Steps to reproduce
1. Create a `Vagrantfile` that creates a machine on remote, say, `aws`, `cloudstack`, etc.
2. Run `vagrant up` on a machine
3. Copy the `Vagrantfile` to another machine
4. Run `vagrant up` on the other machine

### References

None.

**Comment by kikitux** [comment]
Hello

Seems you have some sort of issue using vagrant in a way that is not part of the normal use case.

I can suggest couple of options.

1. Use vagrant-trigger to sync/push the data into a central component before vagrant up.
2. Use other tool like Terraform to create those shared hosts.

Not sure how we can help more, as the out of the box experience is vagrant creating vms per developer.

Alvaro.

**Comment by trombik** [comment]
i think i am doing something wrong to solve the issue, will give Terraform a try. thanks.
