### ISSUE TITLE
Enhancement - Invalid ip address specified in VagrantFile breaks Vagrant

### ISSUE THREAD

**Issue by jeremyquinton** [hashicorp/vagrant#9166]
### Vagrant version
Vagrant 2.0.1

### Host operating system
Mac OSX 

### Guest operating system
Ubuntu 14.04 

### Vagrantfile
```
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.06"
end
```
### Debug output
https://gist.github.com/jeremyquinton/58bbf741ee53bd46c4ffe758e18cb623

### Expected behavior
Vagrant should identify that the ip address is invalid and warn the user and exit instead of a massive strack trace. eg. IP address 192.168.33.06 is not a valid IP address. Please correct before running vagrant up.  

### Actual behavior
Specifying an invalid ip address in the VagrantFile causes a nice ruby stack trace and stops vagrant running. In my instance I did a typo and used the ip address 192.168.33.06 when I meant 192.168.33.6. Not a huge issue but could be a nice little enhancement to Vagrant with some basic validation of the VagrantFile. 

### Steps to reproduce
1. Use the VagrantFile Specified above
2. Run vagrant up
3. User should see ruby stack trace 

### References
This seems to be the same issue as the two below 
- https://github.com/hashicorp/vagrant/issues/7031
- https://github.com/hashicorp/vagrant/issues/6745

**Comment by briancain** [comment]
Closing this now that the pull request has been merged!
