### ISSUE TITLE
Vagrant VMware Fusion plugin update fails if user account is not an admin account

### ISSUE THREAD

**Issue by jmcm1** [hashicorp/vagrant#9167]
### Vagrant version
Vagrant 2.0.0
vagrant-vmware-fusion 5.0.0

### Host operating system
macOS 10.13.1

### Debug output
$ vagrant plugin update
Updating installed plugins...
Fetching: vagrant-share-1.1.9.gem (100%)
Fetching: vagrant-vmware-fusion-5.0.3.gem (100%)
Building native extensions.  This could take a while...

Vagrant is installing the VMware plugin which requires
root access. You may be prompted for your password to
complete setup.

Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 2 incorrect password attempts

### Expected behaviour
Before a dialog would pop that would let me enter the username and password of an admin user on my machine.

### Actual behaviour
Update script just runs sudo which doesn't work as my account is not an admin account. This is a major and very inconvenient change.

### Steps to reproduce
Try to update the vagrant-vmware-fusion plugin on macOS when logged in as a standard account.

**Comment by jmcm1** [comment]
A workaround (if you don't want to make your macOS account into an admin account) is to create a text file in "/etc/sudoers.d/" with the contents "<username> ALL=(ALL) ALL" (where <username> is your non-admin macOS account name). The sudo command will then work. Remove the file afterwards to revert the sudo config to the default.

**Comment by chrisroberts** [comment]
Hi there,

A new Vagrant VMware plugin has been released today. You can read more about it here:

https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

If you still encounter this issue after upgrading, please open a new issue and I will investigate further.

Cheers!
