### ISSUE TITLE
Powershell + rsync: warden: Error occurred: undefined method `gsub!' for nil:NilClass

### ISSUE THREAD

**Issue by daveneeley** [hashicorp/vagrant#9168]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.0

### Host operating system
Windows 10

### Guest operating system
centos/7

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git"
end
```
### Debug output
https://gist.github.com/daveneeley/de0369c2160fafe71a0859824947efc0

### Expected behavior
centos/7 box should have come up

### Actual behavior
error thrown, box not available

### Steps to reproduce
1. open powershell admin prompt
2. install chocolatey
3. choco install rsync
4. vagrant up --provider hyperv
5. wait for error

The error may or may not be only in the hyper-v provider. Since it's rsync I assume not.

**Comment by briancain** [comment]
Hi @daveneeley - this should of been fixed in Vagrant version 2.0.1. Please upgrade and let me know if that solves your issue...thanks!

**Comment by daveneeley** [comment]
Updated to 2.0.1. You are correct, and whoever made that change is completely, totally awesome. Windows rsync finally works!!!

**Comment by briancain** [comment]
Glad I could help, and happy to hear it works! 👍
