### ISSUE TITLE
[Feature request] change vagrant system disk size

### ISSUE THREAD

**Issue by eromoe** [hashicorp/vagrant#9171]
Hi ,

I am using vagrant to test docker images,  system disk eat up soon. (such as centos, ubuntu  only has 8G)

I have tried 

1.  https://github.com/sprotheroe/vagrant-disksize

2. vb.customize https://unix.stackexchange.com/questions/176687/set-storage-size-on-creation-of-vm-virtualbox

Both can't alter system disk size . Why don't provide a built-in way to do this ?

**Comment by whymarrh** [comment]
Refs https://github.com/hashicorp/vagrant/issues/2339

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!

**Comment by Bessonov** [comment]
@soapy1 great! Can you leave a reference to the feature, please? I didn't found anything in [CHANGELOG](https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md)

**Comment by briancain** [comment]
@Bessonov You'll find documentation here: https://www.vagrantup.com/docs/disks/configuration.html It currently only supports VirtualBox, but Hyper-V and VMWare support is on the way soon.
