### ISSUE TITLE
Gem OS not part of Vagrant anymore

### ISSUE THREAD

**Issue by mblaschke** [hashicorp/vagrant#9177]
It seems that gem `OS` is not part of Vagrant anymore. We use it in `Vagrantfile` to detect the running os. Please re-add gem `OS`.

### Vagrant version
Vagrant 2.0.1

### Host operating system
osx high sierra

### Guest operating system
ubuntu 16.04

### Vagrantfile
https://github.com/webdevops/vagrant-docker-vm/blob/ubuntu-16.04/Vagrantfile

### Debug output
```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/mblaschke/VM/devvm-git/Vagrantfile
Line number: 0
Message: LoadError: cannot load such file -- os
```

### Expected behavior
`OS` should be included 😄 

### Actual behavior
`OS` is missing

### Steps to reproduce
1. vagrant up

### References
- https://github.com/webdevops/vagrant-docker-vm/issues/115

**Comment by briancain** [comment]
Hi @mblaschke - `os` is not a gem that we ship with Vagrant. You should be able to just `vagrant plugin install os` to place the rubygem in vagrants environment. Thanks!
