### ISSUE TITLE
Vagrant 2.0.1 - "Vagrant up" hangs on windows 7

### ISSUE THREAD

**Issue by prateekmanocha24** [hashicorp/vagrant#9178]
I have updated vagrant to 2.0.1 & Oracle Virtual box to 5.1.30

**Vagrant version**
Vagrant 2.0.1

**Host operating system**
Window 7 SP1

**Guest operating system**
Ubuntu & Centos

### Vagrantfile
```ruby
**Copy-paste your Vagrantfile here**

Vagrant.configure(2) do |config|

  config.vm.define "acs" do |acs|
    acs.vm.box = "ubuntu/trusty64"
    acs.vm.hostname = "acs"
    acs.vm.network "private_network", ip: "192.168.10.10"
  end

  config.vm.define "web" do |web|
    web.vm.box= "centos/7"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.10.20"
    web.vm.network "forwarded_port", guest: 80, host: 8080
  end

  config.vm.define "db" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = "db"
	db.vm.network "private_network", ip: "192.168.10.30"
  end
  
end
```

**Debug output**
https://gist.github.com/prateekmanocha24/cfec80245b0db12c651f8b94ca4c0065

**Expected behavior**
"vagrant up" should run expectedly

**Actual behavior**
"Vagrant up" hangs

### Steps to reproduce
1. Install vagrant to 2.0.1 & Oracle Virtual box to 5.1.30
2. Use attached Vagrantfile
3. vagrant up
[vagrant.log](https://github.com/hashicorp/vagrant/files/1465037/vagrant.log)

**Comment by ferdinandtjandra** [comment]
i have a same problem here.. how do i solve it?

**Comment by dinhani** [comment]
Same issue here. Tried with 2.0.1 and 2.0.2

**Comment by icalvete** [comment]
Same issue with  2.0.0, 2.0.1 and 2.0.2
