### ISSUE TITLE
Private Network Using the Wrong Nic

### ISSUE THREAD

**Issue by Bowmaster** [hashicorp/vagrant#9179]
### Vagrant version
2.0.1 (Also tested on 2.0.0)

### Host operating system
Mac 10.12.6

### Guest operating system
Server 2016
Centos 7.3

### Hypervisor
VirtualBox 5.2.0 r118431 (Qt5.6.3)

### Vagrantfile
https://gist.github.com/Bowmaster/dcaedca7eb3f721398e7d7344415d207
See lines 15, 42, 66, and 90.  Lines 15, 42, and 66 will recreate the issue, while line 90 is the workaround.
Relevant snippet
```
# Does not create the right NIC
dc1.vm.network 'private_network', ip: '192.168.1.10'

# Creates the right NIC
dc1.vm.network 'private_network', ip: '192.168.1.10', nic_type: '82540EM'
```

### Description
We have a multi-guest vagrantfile that that creates an internal network used for different testing efforts.  Recently this Vagranfile has stopped working and after some digging, what I've found is that when the machine is created in Virtualbox, the first NIC is created with a valid type, but the 2nd one is not.  As a result, the NIC does not present to the OS despite showing as connected.  If I manually specify the NIC type, this error is resolved but this is not overly portable.  I don't recall when this first became an issue but it seems like it was around the 2.0.0 timeframe as I believe 1.9.x did not have this issue.

### Expected behavior
Nic type of private_network should be same as what is created for the primary nic.

### Actual behavior
Nic is created with an invalid type and will not show up in the guest OS

### Steps to reproduce
1. Add a private network to Vagrantfile 

### Workaround

Manually specify the nic_type (not very portable since we have multiple different SKU's for our host workstations)

**Comment by soapy1** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
