### ISSUE TITLE
Vagrant hangs after installing workstation plugin

### ISSUE THREAD

**Issue by masterof0** [hashicorp/vagrant#9181]
After installing the vmware workstation plugin, vagrant ceases to run. Any command (i.e. vagrant --help) fails to return

### Vagrant version
2.0.1

### Host operating system
Windows 10

### Guest operating system
na

### Vagrantfile
na

### Debug output
https://gist.github.com/masterof0/1c33b21d35ac78743573698ecae25abf

### Expected behavior
vagrant should run command and return
(i.e. vagrant -h)

### Actual behavior
vagrant hangs and does not return

### Steps to reproduce
1. install plugin (vagrant plugin install vagrant-vmware-workstation)
2. install license (vagrant plugin license vagrant-vmware-workstation license.lic)
3. run command (vagrant -h)

**Comment by briancain** [comment]
Hi @masterof0 - please upgrade your vmware workstation plugin and let me know if you are still experiencing this issue. Thank you!

**Comment by jschneidereit** [comment]
Can confirm the same behavior on plugin version 5.0.4

**Comment by masterof0** [comment]
Looking good. Thank you for your help

**Comment by chrisroberts** [comment]
Hi there,

A new VMware plugin has been released, you can read about it here:

https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

If you are still encountering issues after upgrading, please create a new issue and I will investigate further.

Cheers!
