### ISSUE TITLE
Vagrant does not have strong hmac ?

### ISSUE THREAD

**Issue by kpiroto** [hashicorp/vagrant#9182]
We have a box with openssh hardening, follows sshd_config relevant part:

ciphers aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com

macs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com

kexalgorithms diffie-hellman-group-exchange-sha256,curve25519-sha256@libssh.org,gss-gex-sha1-,gss-group1-sha1-,gss-group14-sha1-
The only thing we made is to remove all weak ciphers, macs and algorithms, as we need this to be PCI-DSS compliant, and this box will be used to simulate our next production servers.

When I run "vagrant up my-box --provision" againts this box, it hangs trying to connect throuhg ssh.
The curious thing is that if I cancel provisioning I can do "vagrant ssh my-box", and it works just fine.

"An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

could not settle on hmac_client algorithm"

The problem is that we cant use molecule this way, as it hangs when creating instances.

**Comment by briancain** [comment]
Hi @kpiroto - what version of Vagrant are you experiencing this with? Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
