### ISSUE TITLE
/opt/vagrant/embedded/bin/ruby: no such file or directory

### ISSUE THREAD

**Issue by Kelio---** [hashicorp/vagrant#9184]
### Vagrant version
version 2.0.1-1

### Host operating system
Manjaro ( Arch linux ) version 17.06
Vagrant has been installed via pacman

### Debug output
Any "vagrant" command give an error :

**Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: no such file or directory**

I uninstall and reinstall but nothing is working.
Thanks you for your help.

**Comment by spacerIV** [comment]
Same thing!

**Comment by briancain** [comment]
Closing as a dupe of #9185. Thanks for opening an issue!
