### ISSUE TITLE
The vagrant 2.0.1 cannot provisioning the Oracle VM 5.2.1 and doesn't show any error message.

### ISSUE THREAD

**Issue by marodrigues20** [hashicorp/vagrant#9188]
### Vagrant version
$ vagrant -v
Vagrant 2.0.1

### Host operating system
Windows 7

### Guest operating system
hashicorp-VAGRANTSLASH-precise64
Oracle VM VirtualBox 5.2.0
[debug_output.log](https://github.com/hashicorp/vagrant/files/1475652/debug_output.log)

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.box_version = "1.1.0"
end

### Debug output
[debug_output.log](https://github.com/hashicorp/vagrant/files/1475640/debug_output.log)

### Expected behavior
provide the virtual machine

### Actual behavior
the process has been stacked. 
DEBUG subprocess: stdout: 2

### Steps to reproduce
1. $ vagrant init
2.$ vagrant box add hashicorp/precise64
3.$ vagrant up

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...
[debug_output.log](https://github.com/hashicorp/vagrant/files/1475653/debug_output.log)

**Comment by Slach** [comment]
have the same problem with same environment

**Comment by Slach** [comment]
solution is upgrade PowerShell to 5.1 https://www.microsoft.com/en-us/download/confirmation.aspx?id=54616

**Comment by briancain** [comment]
Hi @marodrigues20 - can you please confirm that upgrading to Powershell 5.1 fixes your issue? 
Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
