### ISSUE TITLE
Getting error on running "vagrant up"

### ISSUE THREAD

**Issue by ashutoshinformatica** [hashicorp/vagrant#9189]
### Vagrant version
Vagrant 1.9.6

### Host operating system
Windows 10 64-bit

### Guest operating system
CentOS 6.8

### Vagrantfile

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "infa-axon-vmware"
  config.ssh.insert_key = false
  config.vm.synced_folder "../workspace/axon", "/opt/axon"
  #config.vm.synced_folder "../source/axon5.1/diaku-service", "/opt/axon_data"
  #config.vm.synced_folder "../source/axon5.1/axon_document_upload_microservice", "/opt/axon_document_upload_microservice"
  #config.vm.synced_folder "../source/axon5.1/axon_changerequest_microservice", "/opt/axon_changerequest_microservice"
  #config.vm.synced_folder "../source/axon5.1/axon_notification_microservice", "/opt/axon-notification-microservice"
  config.vm.network "private_network", ip: "192.168.52.100"
  config.vm.hostname = "ms-axon-development.local"
  config.vm.provision "shell", inline: "hostname ms-axon-development.local && hostname > /etc/hostname"
  config.vm.network :forwarded_port, guest: 80, host: 8888,auto_correct: true
  config.vm.network :forwarded_port, guest: 5432, host: 5432, auto_correct: true
  config.vm.network :forwarded_port, guest: 15672, host: 15673, auto_correct: true
  config.vm.network :forwarded_port, guest: 5672, host: 5673, auto_correct: true
  config.vm.network :forwarded_port, guest: 8080, host: 8081, auto_correct: true
  config.vm.network :forwarded_port, guest: 8000, host: 8000, auto_correct: true
  config.vm.network :forwarded_port, guest: 2500, host: 2501, auto_correct: true
  config.vm.network :forwarded_port, guest: 2424, host: 2424, auto_correct: true
  config.vm.network :forwarded_port, guest: 2480, host: 2481, auto_correct: true
  config.vm.network :forwarded_port, guest: 36554, host: 36554, auto_correct: true
  config.vm.network :forwarded_port, guest: 3306, host: 3307, auto_correct: true
  config.vm.network :forwarded_port, guest: 9443, host: 9443, auto_correct: true
  config.vm.network :forwarded_port, guest: 9013, host: 9013, auto_correct: true
  config.vm.network :forwarded_port, guest: 35729, host: 35729, auto_correct: true
  config.vm.network :forwarded_port, guest: 9876, host: 9876, auto_correct: true
  config.vm.network :forwarded_port, guest: 3000, host: 3000, auto_correct: true
  config.vm.network :forwarded_port, guest: 4000, host: 4000, auto_correct: true
  config.vm.network :forwarded_port, guest: 5000, host: 5000, auto_correct: true
  config.vm.network :forwarded_port, guest: 7000, host: 7000, auto_correct: true
  config.vm.network :forwarded_port, guest: 27017, host: 27017, auto_correct: true
  config.vm.provider "vmware_workstation" do |prl|
    prl.memory = 4096
    prl.cpus = 4
  end

end
```

### Debug output
[debug_output.log](https://github.com/hashicorp/vagrant/files/1477554/debug_output.log)

### Expected behavior
vagrant up command should have run successfully. 

### Actual behavior
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["start", "c:/axon-setup/.vagrant/machines/default/vmware_workstation/66790bb3-1ef1-4174-b180-b4fc9a2e2bfc/packer-vmware-vmx-{{timestamp}}.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: Error: The operation was canceled

### Steps to reproduce
1. vagrant plugin install vagrant-vmware-workstation
2. vagrant plugin license vagrant-vmware-workstation ~/license.lic
3. vagrant plugin install vagrant-hostmanager
4. vagrant box add infa-axon-vmware.box --name=infa-axon-vmware
5. vagrant up

**Comment by ashutoshinformatica** [comment]
Below is the out put for vagrant plugin list

vagrant-hostmanager (1.8.7)
vagrant-share (1.1.9, system)
vagrant-vmware-workstation (4.0.24)

**Comment by briancain** [comment]
Hi @ashutoshinformatica - do you still experience this behavior if you upgrade to the latest version of Vagrant? Thanks!

**Comment by ashutoshinformatica** [comment]
Hi @briancain, Even with the latest version I am seeing same error in the logs. However in the end "WARNING: For more information: https://www.vagrantup.com/docs/vmware/boxes.html#vmx-whitelisting
==> default: Starting the VMware VM...
Vagrant timed out while trying to start the VMware machine. This
error is caused by VMware never successfully starting the machine.
This can often be fixed by simply retrying. If the error persists,
please verify that VMware is functional. This is not a Vagrant
issue." This error comes and vagrant is not working as expected.

**Comment by briancain** [comment]
@ashutoshinformatica - what if you try to start a vm through the vmware workstation GUI? Does that work and complete successfully?

**Comment by ashutoshinformatica** [comment]
@briancain  Even with GUI I am seeing the same timeout message. One thing i want to mention is even though this message comes, It is able to bring machine up and running but not able to configure forwarded_port and synced_folder in the guest machine. I will try to summarize the case here.
1. vagrant up runs and exits with this error"Vagrant timed out while trying to start the VMware machine. This
error is caused by VMware never successfully starting the machine.
This can often be fixed by simply retrying. If the error persists,
please verify that VMware is functional. This is not a Vagrant
issue" .
2. vagrant status shows machine up and running.
3. vagrant ssh is not successful in first attempt(After 2 or 3 tries it works). With GUI this is not a problem.
4. forwarded_port and synced_folder are not reflecting in guest machine.
I have compared the logs of vagrant up with my team members and the problem seems while running vagrant up only.

**Comment by briancain** [comment]
Hello @ashutoshinformatica - if vmware itself cannot bring up a VM, then that would be an issue with vmware. One suggestion is to make sure that you have enabled VT-X in your bios and try to bring up a vm with vmware again. If you can't bring up a vm with the GUI, then vagrant likely will not be able to as well so hopefully fixing your computer to work with vmware will then allow you to continue to use vagrant.

**Comment by ashutoshinformatica** [comment]
@briancain Does it mean that this issue is with vmware and not with vagrant? Enabling VT-S in bios, This needs to be done for guest environment or for my home OS? I am able to bring up the VM with the GUI.

**Comment by briancain** [comment]
@ashutoshinformatica - yes exactly! This needs to be done on your host machine inside your bios. Enabling that should allow vmware to bring up vms. If vmware can bring up vms, then vagrant should too.

**Comment by ashutoshinformatica** [comment]
@briancain VT-X is enabled in my machine and I am able to bring up or shutdown the machine by opening .vmx file with vmware. With vagrant also machine is coming up, Issue is with forwarded_ports and synced_folders are not reflecting and commands like vagrant ssh or vagrant halt are very slow and dont work in one try.

**Comment by briancain** [comment]
Can you elaborate a bit more about the vagrant commands not working? Do they fail, and eventually work if you re-run them? Or are they just very slow, and eventually succeed?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
