### ISSUE TITLE
Destroying a VM sometimes fails on Windows

### ISSUE THREAD

**Issue by AndrewSav** [hashicorp/vagrant#9190]
### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 10

### Guest operating system
Windows Server 2016

### Vagrantfile
It does not seem to depend on Vagrantfile

### Debug output
https://gist.github.com/AndrewSav/cce7ba73611d8c1f455fc9a42d374ab3

### Expected behavior
VM deleted

### Actual behavior
A error is generated (see gist linked above)

### Steps to reproduce
Sometimes when you delete a VM with `vagrant destroy` on Windows the deletion fails. Sometimes it succeeds. When you run `vagrant destroy` _second_ time after it failed it usually succeeds too.

**Comment by chrisroberts** [comment]
Hi there,

A new VMware plugin has been released. You can read more about it here:

https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

If you still encounter the same behavior after upgrading, please open a new issue and I will investigate further.

Cheers!
