### ISSUE TITLE
"vagrant up --provider hyperv" locks all other vagrant commands such as "vagrant ssh" from working. With virtualbox it works

### ISSUE THREAD

**Issue by JohnEricson** [hashicorp/vagrant#9194]
I have a problem with a Vagrantfile that supports both the providers virtualbox and hyperv. When I run vagrant up using the virtualbox provider I can vagrant ssh while it's starting up. But when I do the same with the hyperv provider I get this error:

```
PS C:\Virtual_Machines\App-Linux_Docker_Ubuntu_16.04.2> vagrant ssh
An action 'read_state' was attempted on the machine 'default',
but another process is already executing an action on the machine.
Vagrant locks each machine for access by only one process at a time.
Please wait until the other Vagrant process finishes modifying this
machine, then try again.

If you believe this message is in error, please check the process
listing for any "ruby" or "vagrant" processes and kill them. Then
try again.
PS C:\Virtual_Machines\App-Linux_Docker_Ubuntu_16.04.2>
```

The same error happens with the commands status and ssh-config.
This behavior is not the same when I run with virtualbox. Then vagrant ssh works fine.

I have upgraded Vagrant to the latest version.
I can reproduce the error without having any extra plugins installed.

### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 10 Pro 1709 x64

### Guest operating system
root@app:/home/vagrant# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

### Vagrantfile
```ruby
BOX = "kmm/ubuntu-xenial64"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	
	config.vm.box = BOX
	config.vm.provision "shell", inline: "i=0; while true; do let \"i++\"; echo hello $i; sleep 1; done"
end
```

### Debug output
https://gist.github.com/JohnEricson/600ce43e9e877df978cf0fea4bb44a55

### Expected behavior
"vagrant ssh" should work the same, that is work, on both the provider virtualbox and hyperv while running "vagrant up".

### Actual behavior
"vagrant ssh" fails when running "vagrant up --provider hyperv".

### Steps to reproduce
1) vagrant up --provider hyperv
2) Wait until the text _==> default: Machine booted and ready!_ show up in the output.
3) In second PowerShell window in the same directory do: vagrant ssh
4) The error show up.

### References
- GH-4933

**Comment by briancain** [comment]
Hello @JohnEricson - are you able to ssh into the hyper-v guest after `vagrant up` finishes bringing it up?

**Comment by JohnEricson** [comment]
Yes @briancain. When it's finished I can successfully vagrant ssh into it.

**Comment by briancain** [comment]
Hi @JohnEricson - I believe this is expected behavior with the hyper-v plugin. In general you might not be able to ssh into the machine with vagrant due to how certain providers are designed. If you can ssh into the machine after it brings it up, then I believe it's working as expected. Thanks!
