### ISSUE TITLE
Bug: Copying file to a Solaris 11.3 public box home dir doesn't work

### ISSUE THREAD

**Issue by danowar2k** [hashicorp/vagrant#9196]
### Vagrant version
Vagrant 2.0.0

### Host operating system
Windows 7

### Guest operating system
Solaris 11.3

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  ansible_network = "192.168.123"
  pb_test_ip = ansible_network + ".11"
  custom_vagrant_key = '~/.ssh/rsa-private-vagrant.key'

  # A Solaris 11 machine to test playbooks with
  config.vm.define "playbook_test", autostart: false do |playbook_test|
    playbook_test.vm.hostname = "s11-pb-test"
    playbook_test.vm.box = "heavybeans/solaris11-small-server"
    playbook_test.vm.network "private_network", ip: pb_test_ip
    playbook_test.ssh.forward_agent = true
  end
  config.vm.provision "Test",
                      type: "file",
                      source: custom_vagrant_key,
                      destination: '~/.ssh/id_rsa2'
```
### Debug output
https://gist.github.com/danowar2k/19e13fbc4bed04b123fd935fd31cdeba

The error is here:
https://gist.github.com/danowar2k/19e13fbc4bed04b123fd935fd31cdeba#file-gistfile1-txt-L4825
mkdir is called with double quotes, and thus creates the literal ~ directory.

### Expected behavior
The file /export/home/vagrant/.ssh/id_rsa2 should exist.

### Actual behavior
A directory is created with no contents. 
Directory path: **/export/home/vagrant/~**

### Steps to reproduce
1. vagrant up playbook_test --provision-with "Test"

**Comment by soapy1** [comment]
Thanks for the report. Sorry, it took so long to get to this issue. This behavior by Vagrant seems correct. In order to upload to file to the desired location `/export/home/vagrant/.ssh/id_rsa2` the destination for the provisioner should be changed to `.ssh/id_rsa2`.
