### ISSUE TITLE
Windows env var containing path has changed slashes in Vagrantfile

### ISSUE THREAD

**Issue by matthewbeckler** [hashicorp/vagrant#9197]
I am trying to use a cmd.exe environment variable inside a Vagrant file to set the host path for a VM synced folder. I set the env var with the normal Windows-style paths (\ slashes) but the Vagrant output shows that they have been replaced by / slashes, and it cannot find the path from the env var.

### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 10 Pro, 64-bit

### Guest operating system
bento/centos-7.3

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/centos-7.3"

    config.vm.synced_folder ENV['REPO_ROOT'], "/ensemble"
end
```

### Debug output
https://gist.github.com/matthewbeckler/56a4583e345732756c46a91b8315452a

### Expected behavior
I expected vagrant to properly validate my Vagrantfile, indicating that it was able to understand the env var substitution for the VM synced host path.

### Actual behavior
`vagrant validate --debug` reports an error that it cannot find the host path of the shared folder. The missing host path is an odd mix of windows-style and unix-style paths, `c:/work/ensemble_ut`

### Steps to reproduce
1. On a windows 10 machine open a cmd.exe prompt and set the REPO_ROOT env var using a command like `set REPO_ROOT="c:\some\valid\path"`
2. Run `vagrant validate --debug` with the Vagrantfile above.
3. The debug output will contain an error that the host path is missing, but the path has been modified to have the other type of slash. It will report the missing path as "c:/some/valid/path" with incorrect slashes.

### References
- GH-9041 - Possibly not relevant

**Comment by hpaskalev** [comment]
I've stumbled upon this one just yesterday... 
The issue appears to be that the env var value is provided with quotes as these are not needed really.
Lose the quotes and it should work. However, if it's agreed that this is an issue, I'll be more than happy to push a fix for it as I already have one ready. [Here](https://github.com/hpaskalev/vagrant/commit/2f0b3b40137a38b04e975e1aed6e65051934fc16) it is.

**Comment by matthewbeckler** [comment]
This doesn't affect me anymore, as I've changed jobs and we don't use Vagrant at the new job (or Windows either...). I'm certainly not an expert in the best practices for env vars on windows (quotes or not quote), so I will defer any decision making to others.

**Comment by chrisroberts** [comment]
Things here are acting as expected. The use of the double quotes when setting the environment variable initially was the root of the problem. The difference you see in the slashes is just the path handling in Ruby. Going to close this up as it's expected behavior. Cheers!
