### ISSUE TITLE
Add support for the 'automount' option on VirtualBox shared folders

### ISSUE THREAD

**Issue by nebffa** [hashicorp/vagrant#9198]
I would like to be able to configure the 'automount' option for a shared folder for the VirtualBox provider.

See this VBoxManage command for how to add a new shared folder with the setting:

`VBoxManage sharedfolder add Windows-2016-Datacenter --name "Stuff" --hostpath "/Users/ben/stuff/" --automount`

**Comment by briancain** [comment]
Hi @nebffa - I'm not sure I completely understand...is that command doing something different from what already happens when you use the built in vagrant shared folder config option?

```ruby
config.vm.synced_folder "Windows-2016-Datacenter", "/Users/ben/stuff/"
```

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Comment by kevinrook** [comment]
hi im pretty new to Vagrant but i have the same issue.

windows 10 box

my Vagrantfile has this line

config.vm.synced_folder "/Users/kevinrook/gocoedit/vagrant/windows/data", "/vagrant_data"

the shared folder is visible in the VirtualBox Settings for the VM but the option AutoMount is not activated.

i have to Vagrant up the box.   then shut it down.  open VirtualBox settings and edit the the share folder enabling the Auto Mount option.

then the next time i Vagrant up. the share folder is now visible in the Win 10 vm.

is there an option i can add to the Vagrantfile to enable this from the start it would be great.

im running: 
MacOS 10.13.5 (17F77)
Vagrant 2.0.2
Vagrant box "Microsoft/EdgeOnWindows10"
VirtualBox 5.2.8 r121009 (Qt5.6.3)

Regards

Kevin
