### ISSUE TITLE
Unable to license vmware plugin in WSL

### ISSUE THREAD

**Issue by masterof0** [hashicorp/vagrant#9199]
Installed vagrant in WSL, but when I try to install the workstation plugin and license it, I get the following error:
```
[cjohnson@cjoxps: cjohnson]$ vagrant plugin install vagrant-vmware-workstation
Installing the 'vagrant-vmware-workstation' plugin. This can take a few minutes...
Fetching: vagrant-share-1.1.9.gem (100%)
Fetching: vagrant-vmware-workstation-5.0.4.gem (100%)
Building native extensions.  This could take a while...

Vagrant is installing the VMware plugin which requires
root access. You may be prompted for your password to
complete setup.

[sudo] password for cjohnson:
Installed the plugin 'vagrant-vmware-workstation (5.0.4)'!
[cjohnson@cjoxps: cjohnson]$ vagrant plugin license vagrant-vmware-workstation Downloads/license.lic
Installing license for 'vagrant-vmware-workstation'...
The license for 'vagrant-vmware-workstation' was successfully installed!
[cjohnson@cjoxps: cjohnson]$ vagrant plugin list
vagrant-share (1.1.9, system)
vagrant-vmware-workstation (5.0.4)
[cjohnson@cjoxps: cjohnson]$ vagrant -h
A valid license is required to run the Vagrant VMware
provider. Please visit http://www.vagrantup.com to purchase
a license. Once you purchase a license, you can install it
using `vagrant plugin license`.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit
```

### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 10 Pro WSL

### Guest operating system
na

### Vagrantfile
na

### Debug output
https://gist.github.com/masterof0/edae3fbea1c71cef5509d6383ea0e972

### Expected behavior
run vagrant without licensing error

### Actual behavior
any attempt to run vagrant results in licensing error

### Steps to reproduce
1. install vagrant in WSL (dpkg -i)
2. install vmware-workstation plugin
3. install plugin license
4. run vagrant -h

**Comment by StefanScherer** [comment]
Would also love to use Vagrant within WSL to use environment variables for several Vagrant cloud providers as these envs get lost calling the Windows `vagrant.exe`.

But I'm also running VMware Workstation 14 so this would be critical.

**Comment by chrisroberts** [comment]
Hi there,

A new Vagrant VMware plugin has been released today: 

https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

This new plugin may work within WSL at this point, but it has not yet been tested. The next release will include tested support for WSL.

Cheers!

**Comment by mrjester888** [comment]
Fresh install of vagrant in Ubuntu WSL, vagrant-vmware-desktop failed.  

`mrjester@desktop0:/mnt/c/Users/jon/Downloads$ vagrant plugin license vagrant-vmware-desktop license.lic
Installing license for 'vagrant-vmware-desktop'...
The license for 'vagrant-vmware-desktop' was successfully installed!
mrjester@desktop0:/mnt/c/Users/jon/Downloads$ vagrant
A valid license is required to run the Vagrant VMware
provider. Please visit http://www.vagrantup.com to purchase
a license. Once you purchase a license, you can install it
using vagrant plugin license.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit`

**Comment by mrjester888** [comment]
Fresh install of vagrant in Ubuntu WSL, vagrant-vmware-desktop failed.  

`mrjester@desktop0:/mnt/c/Users/jon/Downloads$ vagrant plugin license vagrant-vmware-desktop license.lic
Installing license for 'vagrant-vmware-desktop'...
The license for 'vagrant-vmware-desktop' was successfully installed!
mrjester@desktop0:/mnt/c/Users/jon/Downloads$ vagrant
A valid license is required to run the Vagrant VMware
provider. Please visit http://www.vagrantup.com to purchase
a license. Once you purchase a license, you can install it
using vagrant plugin license.
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

exit`
