### ISSUE TITLE
Vagrant is assigning the same MAC to two different VMs?

### ISSUE THREAD

**Issue by pisymbol** [hashicorp/vagrant#9200]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.0

### Host operating system
$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.9 (Final)
Release:	6.9
Codename:	Final
### Guest operating system
centos/6

### Vagrantfile
```ruby
boxes = [
    {
        :name => "manager",                             # REQUIRED
        :box => "centos/6",                             # OPTIONAL
        :vbox_config => [                               # OPTIONAL
            { "--cpus" => "4" },
            { "--memory" => "8096" }
        ],
    }.
    {
        :name => "member1",
        :vbox_config => [
            { "--cpus" => "2" },
            { "--memory" => "4096" }
        ],
    }
]

# Configure all defined boxes
Vagrant.configure("2") do |config|
    boxes.each do |opts|
        config.vm.define opts[:name] do |config|
            # Use the main Centos EL6 box as the default
            unless opts[:box].nil?
                box = opts[:box]
            else
                box = "centos/6"
            end
            config.vm.box = box

            # Define the provision script
            unless opts[:provision_script].nil?
                pscript = opts[:provision_script]
            else
                pscript = "tools/rpm/provision_vm.sh"
            end

            # Bridged networks make the machine appear as another physical device on
            # your network. We use that as the default.
            unless opts[:networking].nil?
                networking = opts[:networking]
            else
                networking = "public_network"
            end
            config.vm.network networking

            # Box name is hostname
            config.vm.hostname = opts[:name]

            # Always create the default /vagrant folder at the top of the source tree
            config.vm.synced_folder "../", "/vagrant", type: "virtualbox"

            # Sync folders
            unless opts[:synced_folders].nil?
                opts[:synced_folders].each do |hash|
                    hash.each do |folder1, folder2|
                        config.vm.synced_folder folder1, folder2, type: "vritualbox"
                    end
                end
            end

            # Virtualbox configuration
            unless opts[:vbox_config].nil?
                opts[:vbox_config].each do |hash|
                    hash.each do |key, value|
                        config.vm.provider :virtualbox do |vb|
                            vb.customize ["modifyvm", :id, key, value]
                        end
                    end
                end
            end

            # Run the provision script on creation
            host_svn_version=`svn --version | head -n1 | awk '{print $3}'`
            config.vm.provision "shell", path: pscript do |s|
                s.args = [opts[:name], File.basename(Dir.pwd), host_svn_version]
            end
        end
    end
end
```

### Expected behavior
Two VMs with eth0 having two different MAC addresses

### Actual behavior
Two VMs with eth0 both having the same MAC address

### Steps to reproduce
1. vagrant up
2. vagrant ssh manager -t -- 'ifconfig -a'
3. vagrant ssh member1 -t -- 'ifconfig -a'

$ vagrant ssh manager -t -- '/sbin/ifconfig eth0'
eth0      Link encap:Ethernet  HWaddr **52:54:00:B1:3D:B7**
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::5054:ff:feb1:3db7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:81377 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28546 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:107525494 (102.5 MiB)  TX bytes:2438215 (2.3 MiB)

$ vagrant ssh member1 -t -- '/sbin/ifconfig eth0'
eth0      Link encap:Ethernet  HWaddr **52:54:00:B1:3D:B7** 
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::5054:ff:feb1:3db7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:670 errors:0 dropped:0 overruns:0 frame:0
          TX packets:493 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:69357 (67.7 KiB)  TX bytes:70850 (69.1 KiB)

Is this the correct behavior? I would assume Vbox would give me random generated MACs like always, no?

Or is this because in public_networking mode the bridge is shared across ALL VMs on the system? Unfortunately, this is royally screwing up some software.

**Comment by pisymbol** [comment]
So after even more Googling, it seems VBox will use the same MAC if the VMs are defined in the same Vagrant file but use different MACs if the VMs are defined in different Vagrant files.

Is this really true?

**Comment by pisymbol** [comment]
Anyone?

**Comment by pisymbol** [comment]
What's interesting is that I can generate MACs on the fly like so:

```
if boxes.count() > 1
   mac = "525400" + Array.new(6){[*"A".."F", *"0".."9"].sample}.join
   config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--macaddress1", mac]
   end
end
```

But now "vagrant reload <VM>" hangs after setting up ssh (i.e. I think it can't login). WTF!?

**Comment by abbbi** [comment]
hi,

i think i have this problem too. Specially if i using paralell up it seems that vagrant is specifying the same mac address multiple times, i can see this from the VAGRANT_LOG=info output:

abi@cefix:~$ grep mac= up.txt
      mac="02:00:8b:35:e6:00",
      mac="02:00:8b:35:e6:00",
      mac="02:00:8b:35:e6:00",
      mac="02:00:8b:35:e6:00",

deploy of multiple vms then fails with errors all along. I have switched using --no-paralell to workaround this.

**Comment by pisymbol** [comment]
Needs info? C'mon now...

**Comment by briancain** [comment]
@pisymbol I placed this on there because I had yet to do any investigation on the ticket myself. We try to make sure everything is labeled as best we can, but these labels are for us to quickly filter through everything. That specific label is because I don't yet understand how virtualbox or vagrant assigns mac addresses, and since you posed a question about it too, it needs more information before a solution or fix is ready. Thanks.

**Comment by pisymbol** [comment]
@briancain Oh, OK! It seemed like for a second I wasn't providing enough information. I mean suppose I could donate blood or pee in a cup if you really need it.

**Comment by pisymbol** [comment]
Happy New Year! Any update?

**Comment by pisymbol** [comment]
This is still an issue btw.

**Comment by chrisroberts** [comment]
@pisymbol Hi! I dug into this today to see what is going on and it's an issue that's created by the box you are using (the `centos/6` box). In the box's Vagrantfile it is hardcoding the `base_mac` used by the guest. This results in duplicate mac addresses. You can prevent this behavior by adding this to your local Vagrantfile:

```ruby
config.vm.base_mac = nil
```

which will result in them being auto-generated.

Cheers!

**Comment by pisymbol** [comment]
No that is not what happens:

```
$ vagrant destroy -f
==> manager: Forcing shutdown of VM...
vagrant ==> manager: Destroying VM and associated drives...
$ vagrant up --no-provision
Bringing machine 'manager' up with 'virtualbox' provider...
==> manager: Importing base box 'centos/7'...
No base MAC address was specified. This is required for the NAT networking
to work properly (and hence port forwarding, SSH, etc.). Specifying this
MAC address is typically up to the box and box maintainer. Please contact
the relevant person to solve this issue.
```

**Comment by chrisroberts** [comment]
@pisymbol Created a new issue to track this with some specifics on the problem. For now you can prevent the error you are seeing above by replacing:

```ruby
config.vm.box = 'centos/6'
```

with:

```ruby
config.vm.clone = 'centos/6'
```

Cheers!

**Comment by pisymbol** [comment]
$ vagrant up --no-provision
Bringing machine 'manager' up with 'virtualbox' provider...
The working directory for Vagrant doesn't exist! This is the
specified working directory:

/home/pisymbol/Development/src/centos

?

**Comment by rubenk** [comment]
I also bumped into this. The centos boxes are created with https://github.com/redhat-imaging/imagefactory, which hardcodes the mac address. The same happens with fedora/29-cloud-base for instance.

```
~ > grep base_mac .vagrant.d/boxes/centos-VAGRANTSLASH-7/1812.01/virtualbox/Vagrantfile
  config.vm.base_mac = "525400f0e95b"
~ > grep base_mac .vagrant.d/boxes/fedora-VAGRANTSLASH-29-cloud-base/29.20181024.1/virtualbox/Vagrantfile
  config.vm.base_mac = "52540089e2f0"
```

Setting config.vm.base_mac = nil in my Vagrantfile works for me as a workaround.
