### ISSUE TITLE
[#7847 ReOpen] Vagrant SSH fails, port forwarding not working on VBOX

### ISSUE THREAD

**Issue by veemsis** [hashicorp/vagrant#9201]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
vagrant version
Installed Version: 2.0.1
Latest Version: 2.0.1

### Host operating system
Windows 7

### Guest operating system
Ubuntu 16.04

### Vagrantfile

# Copy-paste your Vagrantfile here
https://gist.github.com/veemsis/9ab4dc6db5ef895a5f132db675ba1577

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.
https://gist.github.com/veemsis/fe3ebabbd285dff89b9a3118a2f7bbc2

### Expected behavior
What should have happened?
vagrant ssh should connect into the guest VM via ssh

### Actual behavior
Port forwarding doesn't work in virtualbox, therefore vagrant ssh is not working. Manual putty to the forwarded ssh session also doesn't work. VirtualBox logs: shows the following error:

`00:00:00.987926 NAT: Guest address guess set to 10.0.2.15 by initialization
00:00:00.988046 NAT: Host Resolver conflicts with DNS proxy, the last one was forcely ignored
00:00:01.007618 supR3HardenedErrorV: supR3HardenedScreenImage/LdrLoadDll: rc=VERR_LDRVI_NOT_SIGNED fImage=1 fProtect=0x0 fAccess=0x0 \Device\HarddiskVolume1\Program Files\Open Text\SOCKS Client\HumSOCKS.dll: Not signed.
00:00:01.007964 supR3HardenedErrorV: supR3HardenedMonitor_LdrLoadDll: rejecting 'C:\Program Files\Open Text\SOCKS Client\HumSOCKS.dll' (C:\Program Files\Open Text\SOCKS Client\HumSOCKS.dll): rcNt=0xc0000190
00:00:01.008049 NAT: Failed to redirect TCP 127.0.0.1:2222 -> 0.0.0.0:22 (Unknown error)
00:00:01.009542 IntNet#0: szNetwork={HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2} enmTrunkType=4 szTrunk={VirtualBox Host-Only Ethernet Adapter #2} fFlags=0x14000 cbRecv=325632 cbSend=196608 fIgnoreConnectFailure=false
00:00:01.009880 PGM: The CPU physical address width is 39 bits
00:00:01.009880 PGM: PGMR3InitFinalize: 4 MB PSE mask 0000007fffffffff
00:00:01.009880 TM: TMR3InitFinalize: fTSCModeSwitchAllowed=true 
00:00:01.038280 VMM: Thread-context hooks unavailable
00:00:01.040205 HM: Using VT-x implementation 2.0`

### Steps to reproduce
1. VirtualBox 5.2
2. https://github.com/IBM/deploy-ibm-cloud-private
3. Follow the instructions

### References
#7847 was the same issue. CLosed due to newer versions avalaible.
#https://forums.virtualbox.org/viewtopic.php?f=6&t=79846 - here is the simmiliar thread pointing to different .vbox configuration between vagrant deployments and legacy VirtualBox VM deployment.

**Comment by berenss** [comment]
what version is your windows 7 powershell ?

**Comment by veemsis** [comment]
$PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

**Comment by briancain** [comment]
@veemsis - Do you have a smaller Vagrantfile that reproduces this behavior? Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
