### ISSUE TITLE
Hyper V only getting ipv6 addresses after reboot

### ISSUE THREAD

**Issue by RtypeStudios** [hashicorp/vagrant#9206]
### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 10 

### Guest operating system
Ubuntu 16.04 / CentOs 7

### Hyper V configuration
New-VMSwitch –SwitchName “NATSwitch” –SwitchType Internal
New-NetIPAddress –IPAddress 172.21.21.1 -PrefixLength 24 -InterfaceAlias "vEthernet (NATSwitch)"
New-NetNat –Name MyNATnetwork –InternalIPInterfaceAddressPrefix 172.21.21.0/24

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  
  # Set the provider order.
  config.vm.provider "hyperv"

  # Choose Box
  config.vm.box = "maxx/ubuntu16"
  #config.vm.box = "centos/7"
  
  # Set Network
  config.vm.boot_timeout = 2000
  config.vm.network "private_network", ip: "172.21.21.2"
  
  # Configure ports.
  config.vm.network :forwarded_port, guest: 5000, host: 5000 # Rails Web Server
  config.vm.network :forwarded_port, guest: 5432, host: 5432 # Postgres

  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder ".", "/vagrant", type: "smb", mount_options: ["mfsymlinks"]

  # Setup box details.
  config.vm.provider :hyperv do |hv|
    hv.memory = 2048
    hv.cpus = 2
  end

end
```

### Debug output
https://gist.github.com/RtypeStudios/0014a4295d34187492984211730690de

### Expected behavior
Virtual should have the IP configured from DHCP or allow static IP using configuration 

### Actual behavior
The virtual is always given an ipv6 address and which vagrant cant connect to. I have noticed sometimes when the hyper v switch is the first setup it works. But after a restart of the machine "vagrant up" hits the same issue and gets ipv6 addresses again.

### Steps to reproduce
1. Setup a hyper V switch using the commands above.
2. Reboot
3. Run the above vagrant configuration with vagrant up

### References
None

**Comment by RtypeStudios** [comment]
for DHCP this appears to be an issue with internet connection sharing not work ing after a reboot: https://superuser.com/questions/1110866/internet-connection-sharing-stopped-working-after-windows-10-anniversary-update#

But the static is still not working correctly.

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
