### ISSUE TITLE
vagrant keeps trying to phone home, painfully slow to use with bad DNS server

### ISSUE THREAD

**Issue by giorgian** [hashicorp/vagrant#9208]
I'm working in a network where DNS servers just timeout on requests for external addresses.

Using vagrant here is a nightmare, as vagrant wants to phone home (checkpoint-api.hashicorp.com) all day long (seemingly both before and after doing stuff), and I can't find a way to make it stop.

For instance, if I type:

    vagrant this-command-doesn-t-even-exist

vagrant shows the usage screen, than hangs and waits for a DNS lookup timeout.

Putting in /etc/hosts:

    127.0.0.1	checkpoint-api.hashicorp.com

slightly mitigates the problem, in that it seems to stop DNS requests *AFTER* the command but not before: vagrant ssh still keeps forever.

When I'm using vagrant in a project that doesn't require anything outside my box, disabling Wi-Fi seems the fastest way to make vagrant half usable.

### Vagrant version
Vagrant 2.0.1

### Host operating system
Mac os Sierra

### Guest operating system
Any

### Vagrantfile
Doesn't seem to matter

### Expected behavior
A) `vagrant whatever` should take 0 seconds.
B) `vagrant ssh` should only take a few seconds.

### Actual behavior
A) `vagrant whatever` takes several minutes.
B) `vagrant ssh` takes more than several minutes.

### Steps to reproduce
1. Have a DNS server just timeout for checkpoint-api.hashicorp.com
2. Try using vagrant without suffering.

**Comment by briancain** [comment]
Hello @giorgian - Sorry you are experiencing some frustrating behavior! Fortunately, you can configure vagrant to disable this:

https://www.vagrantup.com/docs/other/environmental-variables.html#vagrant_checkpoint_disable

Hopefully this helps, thanks!
