### ISSUE TITLE
macOS: Not adding vagrant boxes to VirtualBox

### ISSUE THREAD

**Issue by dezza** [hashicorp/vagrant#9209]
### Vagrant version
2.0.1

### Host operating system
MacOS 10.13.1

### Guest operating system
debian/stretch64

### Debug output
https://gist.github.com/dezza/2e709434433d41738b72c7e6754acdfa
raw: https://gist.githubusercontent.com/dezza/2e709434433d41738b72c7e6754acdfa/raw/b922b0ff33fc338ba9277b84593b8b9616d396c2/vagrant_box_add.log

### Expected behavior
Boxes should be visible and imported in VirtualBox and be able to converge without explictly running
`VBoxManage import ~/.vagrant.d/boxes/debian-VAGRANTSLASH-stretch64/9.2.0/virtualbox/box.ovf`

### Actual behavior
No VMs imported.

### Steps to reproduce
1. Install VirtualBox 5.1.30 official dist https://www.virtualbox.org/wiki/Download_Old_Builds_5_1
3. Install vagrant official dist https://www.vagrantup.com/downloads.html
2. Install chefdk 
3. Run `$ vagrant box add debian/stretch64`

Using `VBoxManage import ~/.vagrant.d/boxes/debian-VAGRANTSLASH-stretch64/9.2.0/virtualbox/box.ovf` works. 

And `/usr/local/bin/VBoxManage` contains:
```
exec /Applications/VirtualBox.app/Contents/MacOS/VBoxManage "$@"
```

Which is the correct installed path for VirtualBox.

**Comment by briancain** [comment]
Hi @dezza - Thanks for opening an issue. What you described is correct behavior. `vagrant box add` and `VBoxManage import` are two different operations. Running `vagrant box add` simply downloads a box either locally from a file or from Vagrant Cloud, into your vagrant environment to be used for importing VMs into virtualbox when you actually `vagrant up` that machine later. Hopefully that makes sense...thanks!
