### ISSUE TITLE
"VMware Fusion provider can be purchased" error but license is installed

### ISSUE THREAD

**Issue by thorr18** [hashicorp/vagrant#9210]
Just purchased the Fusion plugin and it doesn't work. No longer able to run `Vagrant`. 

### Vagrant version
> BsMBP:win bem$ vagrant -v
> Vagrant 2.0.1
> BsMBP:win bem$ 

### Host operating system
Darwin
> BsMBP:win bem$ sw_vers
> ProductName:	Mac OS X
> ProductVersion:	10.13.1
> BuildVersion:	17B48
> BsMBP:win bem$ 

### Guest operating system
None

### Vagrantfile
```ruby
# Test was ran in an empty directory with no Vagrantfile at all. 
```

### Debug output

Ran: 
`vagrant plugin install vagrant-vmware-fusion --debug`
`vagrant plugin license vagrant-vmware-fusion ~/license.lic --debug`
`vagrant --debug`

+ [This Gist](https://gist.github.com/thorr18/ab6f1162c88f66ca203e32f16ed58fce) contains three logs:   
  * First, successfully install the vmware plugin and [log it](https://gist.github.com/thorr18/ab6f1162c88f66ca203e32f16ed58fce#file-installplugin-log)
  * Then, successfully install the plugin license and [log it](https://gist.github.com/thorr18/ab6f1162c88f66ca203e32f16ed58fce#file-installlicence-log)
  * Finally, run vagrant with no subcommands, which fails, and [log it](https://gist.github.com/thorr18/ab6f1162c88f66ca203e32f16ed58fce#file-vagrantfails-log)

### Expected behavior
Should be able to run `vagrant --debug` without errors. 
No message about purchasing Fusion plugin are expected after the license installation. 

### Actual behavior
> The Vagrant VMware Fusion provider can be purchased from ...
> ERROR vagrant: The plugins failed to load properly

### Steps to reproduce
As seen in the debug output, it was: 
1. Install vmware plugin. 
2. Install plugin license. 
3. Run `vagrant`

**Comment by briancain** [comment]
Hello @thorr18 - Please run this command to install plugin version 5.0.3, re-license the plugin, and let me know if it solves your issue. Thanks!

```
vagrant plugin install vagrant-vmware-fusion --plugin-version 5.0.4
```

**Comment by thorr18** [comment]
You said 5.0.3 but your command said 5.0.4 so I went with 4. 
> vagrant-vmware-fusion (5.0.4)
>   - Version Constraint: 5.0.4

I am now able to run `vagrant` and get a help menu instead of an error.   
It looks like `vagrant up` is also working with my test Vagrantfile so far. 
```
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_fusion'
Vagrant.configure(2) do |config|
  config.vm.provider "vmware_fusion" do |v|
    v.name = "testpluginVM"
    v.gui = false
    v.linked_clone = true
    v.memory = 2048
    v.cpus = 4
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
  end
    config.vm.provider "vmware_workstation" do |v|
    v.name = "testpluginVM"
    v.gui = false
    v.linked_clone = true
    v.memory = 2048
    v.cpus = 4
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
  end
  config.vm.box = "bento/ubuntu-16.10"
end
```
Thanks

**Comment by briancain** [comment]
@thorr18 ahhhh, sorry about that. I'm glad that worked. Apologies for the typo! :)
