### ISSUE TITLE
Vagrant setting wrong hostname

### ISSUE THREAD

**Issue by mahaag** [hashicorp/vagrant#9211]
### Vagrant version
Vagrant 2.0.1

### Host operating system
Ubuntu 16.04.3 LTS

### Guest operating system
SUSE Linux Enterprise Server 12 SP1

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "mahaag/sles12sp1"
  config.vm.hostname = "client.local"
end
```

### Debug output
Excerpt from debug log:
```
 INFO ssh: Execute: hostname -f | grep '^client.local$' (sudo=false)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: stderr: hostname: Name or service not known

DEBUG ssh: Exit status: 1
DEBUG ssh: Re-using SSH connection.
 INFO ssh: Execute: echo 'client.local' > /etc/HOSTNAME
hostname 'client.local'

# Prepend ourselves to /etc/hosts
grep -w 'client.local' /etc/hosts || {
  sed -i'' '1i 127.0.0.1\tclient.local\tclient' /etc/hosts
}
 (sudo=true)
DEBUG ssh: stderr: 41e57d38-b4f7-4e46-9c38-13873d338b86-vagrant-ssh
DEBUG ssh: Exit status: 0
```
[Complete debug log](https://github.com/hashicorp/vagrant/files/1495467/vagrant_up.log)

### Expected behavior
If setting a qualified hostname in ``config.vm.hostname``, Vagrant should only write the short hostname in ``/etc/HOSTNAME`` and write qualified and short hostname in ``/etc/hosts``.

### Actual behavior
Currently the qualified hostname is written in ``/etc/HOSTNAME`` and qualified and short hostname are written ``/etc/hosts``. This causes the system to show different hostnames after initial ``up`` and ``reload``.

If the box is freshly initialized:

```
$ hostname
client.local
```

Initialize the box, and make a reload afterwards:

```
$ hostname
client
```

### Steps to reproduce
1. Set a qualified hostname in ``config.vm.hostname``
2. Start the Vagrant and retrieve the hostname with ``hostname``
3. Reload the Vagrant and retrieve the hostname with ``hostname`` and see a different value than in step 2

**Comment by mahaag** [comment]
Provided [pull request](https://github.com/hashicorp/vagrant/pull/9212) for this issue.

**Comment by briancain** [comment]
Closing this as it has already been merged!
