### ISSUE TITLE
Failing to download box from artifactory which require authentication

### ISSUE THREAD

**Issue by svl7** [hashicorp/vagrant#9215]
### Vagrant version: 
2.0.1

### Host operating system: 
Windows 10

### Guest operating system: 
Ubuntu 16.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_SERVER_URL'] = "https://artifactory.xyz.com/api/vagrant-repo"

Vagrant.configure("2") do |config|
  config.vm.box = "vmbox"
  config.vm.box_url = "https://artifactory.xyz.com/api/vagrant/vagrat-repo/vmbox"
 (...)
```

### Debug output
https://gist.github.com/svl7/55c9cb21c4445539c367b88486e3d4e6

### Expected behavior
Vagrant should be able to authenticate itself by the artifactory, using the provided ATLAS_TOKEN and the VAGRANT_SERVER_URL, as described in the [artifactory docu](https://www.jfrog.com/confluence/display/RTF/Vagrant+Repositories).

### Actual behavior
Vagrant fails to download the box:

```
$ vagrant up
Bringing machine 'devbox' up with 'virtualbox' provider...
==> devbox: Box 'devbox' could not be found. Attempting to find and install...
    devbox: Box Provider: virtualbox
    devbox: Box Version: >= 0
==> devbox: Box file was not detected as metadata. Adding it directly...
==> devbox: Adding box 'devbox' (v0) for provider: virtualbox
    devbox: Downloading: https://artifactory.swisscom.com/api/vagrant/ttc-vagrant/devbox
    devbox:
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

bsdtar.EXE: Error opening archive: Unrecognized archive format
```
Looking at the debug log, vagrant tries to get the box like this:
_https://artifactory.yxz.com/api/vagrant/vagrant-repo/vmbox?access_token="...Token..."_

I didn't see this possibility in the artifactory repository. But it suggests some other ways, like:
Using a jfrog header and api-key:
`curl -H "X-JFrog-Art-Api:...API-Key" https://artifactory.xyz.com/api/vagrant/vagrant-repo/devbox`

Using the access token (ATLAS_TOKEN) and user name like this:
`curl -u username:ATLAS_TOKEN https://artifactory.yxz.com/api/vagrant/vagrant-repo/vmbox`

Both of which work fine from the command line and lead to the json data describing the box and providing the link.

For me it seems vagrant should do the authentication differently.
Trying it from the command line the way vagrant does it according to the debug log

### Steps to reproduce
- upload a valid, working box to artifactory, including metadata
- set ATLAS_TOKEN and VAGRANT_SERVER_URL environment vars with valid values
- try basic vagrant file with vm.box and vm.box_url pointing to the box in the artifactory fails with a 401 "Failed to decode basic authentication token', though the token is definitely correct and works fine for the authentication methdos artifactory specifies. 

### References
[https://github.com/hashicorp/vagrant/issues/7864](https://github.com/hashicorp/vagrant/issues/7864)
This might be related, but had to do with the vagrant box add command.

**Comment by svl7** [comment]
Solved. 
Issue was that on Artifactory the wrong api got used for the token creation, which resulted in a token that didn't work for vagrant, but still worked when using manually from command line.

**Comment by lifespent** [comment]
What do you mean by "wrong api"? I'm having the same issue.
