### ISSUE TITLE
Vagrant destroy command destroys boxes outside of current directory.

### ISSUE THREAD

**Issue by arthurvanduynhoven** [hashicorp/vagrant#9216]
I am using Jenkins and Vagrant together. In my Jenkins environment I have a multi-branch job. When concurrent builds are run Jenkins creates multiple workspaces.

The first workspace would be `/tmp/workspace/job`
The second workspace would be `/tmp/workspace/job@2`
The third workspace would be `/tmp/workspace/job@3`
etc..

When I run `vagrant destroy` inside the first workspace it will destroy all 3 workspaces.

This was working correctly in Vagrant 1.9.8 and in 2.0.0 this issue started to happen.

### Vagrant version
Vagrant 2.0.1
Vagrant 2.0.0+

### Host operating system
CentOS Linux release 7.4.1708 (Core)

### Expected behavior
Only vagrant boxes in current directory/Vagrantfile should be destroyed

### Actual behavior
All vagrant boxes are destroyed under the base directory.

### Steps to reproduce
1. Create 2 directories
    - /tmp/workspace/job
    - /tmp/workspace/job@2
2. Use same Vagrantfile in both directories and run `vagrant up`
3. Inside the first directory `/tmp/workspace/job` run `vagrant destroy -f`

You will notice all vagrant boxes will be destroyed.

**Comment by briancain** [comment]
Hello @arthurvanduynhoven - I just tried to reproduce this bug following your steps, and I did not encounter this issue.

https://gist.github.com/briancain/ddf2a83894775055439a454f023ae71c

Do you have a debug log where this is happening? Maybe something like what I shared above so that we could follow along? Thanks!

**Comment by arthurvanduynhoven** [comment]
Sorry for the late reply. I reinstalled Vagrant on the effected machine and now I am unable to reproduce.
