### ISSUE TITLE
bsdtar.EXE: Error exit delayed from previous errors.

### ISSUE THREAD

**Issue by phpapi** [hashicorp/vagrant#9217]
### Vagrant version
`Vagrant 2.0.0`

### Host operating system
`Win10` 
VirtualBox 5.0

### Debug output
`
	PS D:\software> vagrant box add .\newbox_name11-24.box --name Centos7php71

	==> box: Box file was not detected as metadata. Adding it directly...
	==> box: Adding box 'Centos7php71' (v0) for provider:
	    box: Unpacking necessary files from: file://D:/software/newbox_name11-24.box
	    box: Progress: 100% (Rate: 194M/s, Estimated time remaining: --:--:--)
	The box failed to unpackage properly. Please verify that the box
	file you're trying to add is not corrupted and that enough disk space
	is available and then try again.
	The output from attempting to unpackage (if any):
	x ./box-disk1.vmdk: Write failed
	x ./box.ovf: Write failed
	x ./Vagrantfile: Can't create '\\\\?\\C:\\Users\\admin\\.vagrant.d\\tmp\\vagrant-box-add-temp-20171124-7316-5b6s6w\\Vagr
	antfile'
	bsdtar.EXE: Error exit delayed from previous errors.
	PS D:\software> vagrant -v
	Vagrant 2.0.0
`

**Comment by phpapi** [comment]
does it means have not enough disk space?

**Comment by briancain** [comment]
@phpapi - how much disk space do you have available, and how large is the box?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
