### ISSUE TITLE
vagrant-share.rb:10: [BUG] Segmentation fault

### ISSUE THREAD

**Issue by traumschule** [hashicorp/vagrant#9220]
### Vagrant version
Vagrant 2.0.1

### Ruby version
2.4.2

### Rubygems version
2.6.13

### Host operating system
debian stretch
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch
$ uname -a
Linux 4.9.0-4-686-pae #1 SMP Debian 4.9.51-1 (2017-09-28) i686 GNU/Linux
```

### Debug output
https://gist.github.com/traumschule/1bd533457439d92c6b3eb9ae1a520607

### Expected behavior
No segflt.

### Actual behavior
Segmentation fault.

### Steps to reproduce
1. slow internet / probably interrupted connection
2. update vagrant to 2.0.1
3. vagrant plugin install vagrant-hostmanager && vagrant up

Removing ~/.vagrant.d/gems/2.4.2/gems/vagrant-share-1.1.9 obviously leads to
```
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/bundler.rb:390:in `write': No such file or directory @ rb_sysopen - /home/user/.vagrant.d/gems/2.4.2/gems/v
agrant-share-1.1.9/vagrant-share.gemspec (Errno::ENOENT)
```

**Comment by briancain** [comment]
Hi @traumschule - Could you please run the following command, and then install the hostmanager plugin?

```
vagrant plugin expunge
```

Thanks!

**Comment by traumschule** [comment]
Thanks for looking into this!

> $ vagrant plugin expunge
> Would you like Vagrant to attempt to reinstall current plugins? [N]: y
> 
> This command permanently deletes all currently installed user plugins.
> It should only be used when a repair command is unable to properly fix
> the system.
> 
> Continue? [N]: y
> 
> All user installed plugins have been removed from this Vagrant
> environment!
> 
> Vagrant will now attempt to reinstall user plugins that were removed.
> Installing the 'vagrant-cachier' plugin. This can take a few
> minutes...Fetching: vagrant-cachier-1.2.1.gem (100%) Fetching:
> vagrant-hostmanager-1.8.7.gem (100%) Fetching: vagrant-share-1.1.9.gem
> (100%) Installed the plugin 'vagrant-cachier (1.2.1)'!
> Installing the 'vagrant-hostmanager' plugin. This can take a few
> minutes... Installed the plugin 'vagrant-hostmanager (1.8.7)'!
> $ ./scripts/vagrant/install.sh
> Checking your system ...
> - vagrant: /usr/bin/vagrant
> Vagrant 2.0.1
> Note: Vagrant prior 1.8.2 will fail.
> - ansible: /usr/bin/ansible
> ansible 2.4.1.0
>   config file = /home/hitchwiki/src/hwt/ansible.cfg
>   configured module search path = [u'/home/hitchwiki/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python2.7/dist-packages/ansible
>   python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]                                                                                           
>                                                                                                                              
> ------------------------------------------------------------                                                       
>                                                                                                                     
> All fine, let's roll ...                                                                                                    
> Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...                                         
> Installed the plugin 'vagrant-hostmanager (1.8.7)'!                                                         
> /home/hitchwiki/.vagrant.d/gems/2.4.2/gems/vagrant-share-1.1.9/lib/vagrant-share.rb:10: [BUG] Segmentation fault at 0x00000008
> ruby 2.4.2p198 (2017-09-14 revision 59899) [i686-linux]

Here is the content of ./scripts/vagrant/install.sh:
```
echo "Checking your system ..."
for app in vagrant ansible; do
  bin=$(which $app)
  if [[ ! $bin ]] ; then
    echo "Please install $app."
  else
    echo "- $app: $bin"
    $bin --version
    if [ $app = "vagrant" ] ; then echo "Note: Vagrant prior 1.8.2 will fail." ; fi
  fi
done
echo -e $sep
echo "All fine, let's roll ..."
vagrant plugin install vagrant-hostmanager
vagrant up
```

Should I try another ruby version?

**Comment by briancain** [comment]
Hi...just from the output you shared it looks like you're installing the plugin twice? After running `vagrant plugin expunge` in the output, I see something that says:

```
Installing the 'vagrant-hostmanager' plugin. This can take a few
minutes... Installed the plugin 'vagrant-hostmanager (1.8.7)'!
```

Right before you run your installation script.

**Comment by traumschule** [comment]
That is correct. The first stems form `vagrant plugin expunge`:
> "Vagrant will now attempt to reinstall user plugins that were removed."

It should cause no issue to run `vagrant plugin install vagrant-hostmanager` multiple times (idempotence)?

**Comment by traumschule** [comment]
Could you reproduce it on debian stretch? What kind of details are you missing? (it's a bit of an effort to down- and upgrade repeatedly for testing?)

**Comment by TomBZombie** [comment]
Will this be fixed in 2.0.2? It seems the only current workaround is downgrading, I'm having the same issue with the vagrant-triggers plugin.

**Comment by Xachman** [comment]
So I ran into this issue when the 32bit version of vagrant 2.0.1 was installed.  After installing the 64bit version this was fixed.

**Comment by maxi7587** [comment]
I had this issue too... Removing Vagrant and using an older version fixed the problem...

**Comment by mitsest** [comment]
Having the same issue, when trying to vagrant up a trellis setup (wordpress)
