### ISSUE TITLE
Vagrant fails to correctly set network interface names in /etc/network/interfaces

### ISSUE THREAD

**Issue by ferrarimarco** [hashicorp/vagrant#9222]
### Vagrant version
```
$ vagrant -v
Vagrant 2.0.1
```

### Host operating system
Windows 10, Deepin 15.5 (it's a Debian based distro)

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  hostname = "gateway"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--cpus", 1]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--memory", 512]
  end
  config.vm.provision "shell", inline: "echo \"ip addr output: $(ip addr)\""
  config.vm.provision "shell", inline: "cat /etc/network/interfaces"
  config.vm.provision "shell", inline: "/etc/init.d/networking restart"  
end
```

### Debug output
https://gist.github.com/ferrarimarco/c83decb8f4c84affe6562328d93c0eeb

### Expected behavior
`/etc/network/interfaces` to be correctly updated considering the network interface names. In this case I expected to see `eth0` instead of `enp0s3`.

### Actual behavior
Vagrant incorrectly sets the name of the first network interface, or fails to update it to the actual name. Therefore the networking service cannot be restarted.

Here are the relevant bits from the log (I execute two simple commands during the provisioning phase):

Output of the `ip addr` command:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:67:d9:b9 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe67:d9b9/64 scope link
       valid_lft forever preferred_lft forever
```

Output of the `cat /etc/network/interfaces` command:
```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto enp0s3
iface enp0s3 inet dhcp
pre-up sleep 2
```

### Steps to reproduce
1. `vagrant up`

### References
Nothing

**Comment by briancain** [comment]
Hi @ferrarimarco - from what I can tell, this is expected behavior with Ubuntu. Vagrant isn't actually setting the name of that interface. Please see this link for more information. Thanks!

https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/
https://askubuntu.com/a/704121

**Comment by ferrarimarco** [comment]
Hi @briancain - there is indeed an issue here because the `/etc/network/interfaces` contents do not match the the names of the network interface.

Is Vagrant populating `/etc/network/interfaces` somehow?

**Comment by briancain** [comment]
Vagrant will only modify that file if you define a private network, which it doesn't look like you have in your Vagrantfile. You would see things like `VAGRANT_BEGIN` and `VAGRANT_END` inside that file.

**Comment by briancain** [comment]
I assume you probably have an interface called `eth0.cfg` inside of `/etc/network/interfaces.d/`? The default `/etc/network/interfaces` file sources that entire dir, which is likely where your eth0 interface is coming from.

**Comment by ferrarimarco** [comment]
nothing in my `/etc/network/interfaces.d/`...

**Comment by briancain** [comment]
I was not....I saw an interface config inside of `/etc/network/interfaces.d` which is where I'm assuming my eth0 interface is coming from.

```
vagrant@vagrant:~$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:10:47:e3 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe10:47e3/64 scope link
       valid_lft forever preferred_lft forever
vagrant@vagrant:/etc/network$ cat interfaces.d/eth0.cfg
auto eth0
iface eth0 inet dhcp
vagrant@vagrant:/etc/network$ cat interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto enp0s3
iface enp0s3 inet dhcp
pre-up sleep 2
```

Perhaps @kikitux has more information here?

**Comment by ferrarimarco** [comment]
I suppose the `eth0 `configuration in `/etc/network/interfaces.d` comes from [the networking setup script](https://github.com/chef/bento/blob/master/ubuntu/scripts/networking.sh) that is invoked on box creation by this [packer template](https://github.com/chef/bento/blob/master/ubuntu/ubuntu-16.04-amd64.json#L283).

Yet I'm still wondering who sets up `enp0s3`...

@briancain can you please reopen this issue while we are looking into it?

Thanks!

**Comment by briancain** [comment]
Vagrant wouldn't be setting up or managing that interface if no private or public networks have been defined in your Vagrantfile. The thing that sets that up is in the template you linked to. Perhaps destroy the machine, bring it up again, and see if you have an `eth0` config in your `/etc/networking/interfaces.d` folder. If not I recommend opening an issue with the bento project. Thanks!

**Comment by queglay** [comment]
@ferrarimarco I also have a mystery interface that I'm not specifying.  this guy -

2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:3e:59:1c:26:9a brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global enp0s3
       valid_lft forever preferred_lft forever
    inet6 fe80::3e:59ff:fe1c:269a/64 scope link 

I have to other interfaces, one public, one private, and they have ip's that are explicitly set. but this one I'd like to eliminate.

I'm using "ubuntu/xenial64"

**Comment by ferrarimarco** [comment]
@queglay consider switching to a bento base box as that bug is fixed there, see https://github.com/chef/bento/issues/1003
