### ISSUE TITLE
Does the "shell provisioner" run bash?

### ISSUE THREAD

**Issue by jameshfisher** [hashicorp/vagrant#9223]
I'm trying to understand [the "Shell Provisioner" documentation](https://www.vagrantup.com/docs/provisioning/shell.html). It keeps describing these scripts as "shell scripts" but does not specify exactly which variant of "shell" they should be. Are they sh, bash, tsch, etc? What is the interpreter for these scripts?

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the Vagrant mailing list. There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄

**Comment by jameshfisher** [comment]
Thanks Brian, I'll try the mailing list.

Also, and I mean this in the most helpful way: the last line of this auto-response sounds very passive-aggressive. I'd consider removing it.

**Comment by briancain** [comment]
@jameshfisher - thanks for the suggestion! It was not intended to be that way, apologies.
