### ISSUE TITLE
Provide support for Solus as a guest

### ISSUE THREAD

**Issue by martinanderssondotcom** [hashicorp/vagrant#9225]
### Vagrant version
`2.0.1`

### Host environment
Windows 10 and VirtualBox 5.2.2

### Guest operating system
[Solus 3.26.2][1]

#### Case 1: Privately packed box with Solus
```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'my-local-solus.box'
  
  config.vm.provider 'virtualbox' do |box|
     box.gui = true
  end
end
```

#### Case 2: Public box with a built-in hack
```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'pristine/solus-3-budgie'
end
```

#### Case 3: Tryna' configure a hostname
```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'pristine/solus-3-budgie'
  config.vm.hostname = 'superman'
end
```

#### Case 4: Swinging a private network
```ruby
Vagrant.configure('2') do |config|
  config.vm.box = 'pristine/solus-3-budgie'
  config.vm.network 'private_network', ip: '192.168.33.10'
end
```

### Expected behavior
Me happy.

### Actual behavior
**Case 1**: Ultra failure, with the following message:

> The guest operating system of the machine could not be detected!
> Vagrant requires this knowledge to perform specific tasks such
> as mounting shared folders and configuring networks. Please add
> the ability to detect this guest operating system to Vagrant
> by creating a plugin or reporting a bug.

Turns out that Solus is not supported.

Vagrant's [docs claim][2] that `config.vm.guest` defaults to `:linux`. This can not be true, cuz set this value explicitly in the Vagrantfile and all of a sudden the Solus box actually works to boot. Which is exactly what the public box used by **case 2** [does][3].

However, **case 3** will still crash. With this message:

> Vagrant attempted to execute the capability 'change_host_name'
> on the detect guest OS 'linux', but the guest doesn't
> support that capability. This capability is required for your
> configuration of Vagrant. Please either reconfigure Vagrant to
> avoid this capability or fix the issue by creating the capability.

Similarly, **case 4** also crashes but whines about a missing "configure_networks" capability.

Please note that I have iterated through every guest plugin [available/supported][4] as `config.vm.guest`. Each one crash lol. So I think we're gonna have to start on a new plugin.

[1]: https://solus-project.com/
[2]: https://www.vagrantup.com/docs/vagrantfile/machine_settings.html
[3]: https://github.com/martinanderssondotcom/box-solus-3-budgie/blob/65bdc897372308ac54870cc0ec51ca12ced22e85/Vagrantfile#L10
[4]: https://github.com/hashicorp/vagrant/tree/bcf3a4b3d1388b168d3892cc56bd309aa3139a6d/plugins/guests

**Comment by briancain** [comment]
Hey @martinanderssondotcom - could you please provide a gist to a debug log with vagrant bringing up one of these vagrantfiles? Thanks!

**Comment by ikeydoherty** [comment]
If there is some kind of file inside Solus that is missing that breaks the Vagrant detection we can add them back (within reason)  :)

**Comment by briancain** [comment]
@martinanderssondotcom - yes, please feel free to email it to me: bcain@hashicorp.com. Thanks!

**Comment by martinanderssondotcom** [comment]
Done!

**Comment by soapy1** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it is a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
