### ISSUE TITLE
Vagrant does not recognize Oracle VM on my Ubuntu 16.04

### ISSUE THREAD

**Issue by MilenkoM** [hashicorp/vagrant#9226]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.9.1

### Host operating system
Ubuntu 16.04

### Guest operating system
Oracle VM
 vboxmanage --version
5.2.2r119230

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
I am learning Puppet, but vagrant does not recognize my VirtualBox.

### Actual behavior
What actually happened?
vagrant up
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

### Steps to reproduce
1.https://github.com/tosmi/packt-learnpuppet
2. Ubuntu 16.04 is mine OS
3. vagrant up,explained in previous step

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by briancain** [comment]
Hello @MilenkoM - Can you please upgrade to the latest version of Vagrant and let me know if that fixes your problem. Thanks!

**Comment by MilenkoM** [comment]
Hi Brian
Actually, the issue was with Oracle VirtualBox,I had to downgrade it to 5.1.Works now!

**Comment by briancain** [comment]
Great! Thanks.
