### ISSUE TITLE
Vagrant 2.0: Problems with starting Centos 7 machine

### ISSUE THREAD

**Issue by ghsolutions** [hashicorp/vagrant#9232]
Hi, i made my own basebox, which worked well on VMWare Fusion 8.5.8 PRO and Vagrant 1.9.8 on macOS 10.13. When i try to bring it up on my newer Enviroment VMWare Fusion 10.0.1 and Vagrant 2.0.1 on macOS 10.13 i don't get it running. It's impossible to get the shared folders runnig. The process stops with timeout error, after setting high the timeout time i get an timeout error a little bit later. Although i get an error message, when i open VMWare the machine has booted but the shared folders does not work. On Vagrant 1.9.8 all worked well and like expected.

I made an test, using the same basebox on both enviroments and here are the infos to this:

### Vagrant version
Vagrant 2.0.1
Vagrant 1.9.8 

### Host operating system
Mac OS 10.13 High Sierra

### Guest operating system
Centos 7

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "testbox"
  config.vm.boot_timeout = 1000
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "./data", "/var/www/html"
end
```

I used the same Vagrantfile on both tests, only the timeout config i added only at the vagrant 2.0.1 test after the error message says i could try this.

### Debug output
Debut Output Vagrant 1.9.8 VMWare 8.5.8
https://gist.github.com/ghsolutions/71eb0d0cc039e4d50f4c49d3e836eeb9

Debug Output Vagrant 2.0.1
https://gist.github.com/ghsolutions/6a41b4916dbac61ad6ac0489f6ecbfc2

### Expected behavior
What should have happened?
The machine should boot.

### Actual behavior
What actually happened?
The machine hangs up while booting

### Steps to reproduce
1. vagrant box add testbox.box --name=testbox
2. vagrant up --no-provision

It's an error i get very often with my enviroments on vagrant 2.0.1 and on vagrant 2.0 too. But i don't want to get back to VMWare Fusion 8.5.8 and Vagrant 1.9.8, i want to use the newest software to develop my software.

**Comment by chrisbalmer** [comment]
Double check that in the `/etc/ssh/sshd_config` file you have `UseDNS` explicitly set to `no`. I was having timeout issues as well until I fixed that in my packer build.

**Comment by ghsolutions** [comment]
Hi, i had not enough time to test it with more than one basebox, but for the tested one it worked very well with setting UseDNS to no. Great tip, thank you very much!

**Comment by beenje** [comment]
Thanks for the tip!
When connecting to a VPN on my Mac, I also had timeout issue with my vagrant box.
Setting UseDNS to no solved it.

**Comment by chrisroberts** [comment]
Looks like Chris' comment https://github.com/hashicorp/vagrant/issues/9232#issuecomment-348502717 fixed this up so I'm going to close this issue. Cheers!
