### ISSUE TITLE
can not download proper box

### ISSUE THREAD

**Issue by alexiusp** [hashicorp/vagrant#9233]
### Short description:
vagrant can not download the proper box for virtual machine. It seems that http://cdn.boxcutter.io does not have it. What should I do?

### Full description:

Vagrant 2.0.1
Host: Windows 10

### Part of Vagrantfile
```ruby
# Vagrant-API version
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "box-cutter/ubuntu1604"

```

### Output
```
default: Downloading: https://vagrantcloud.com/box-cutter/boxes/ubuntu1604/versions/2.0.26/providers/virtualbox.box
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

### Expected behavior
Requested box should be downloaded

### Actual behavior
404 error occurs

### Steps to reproduce
1. vagrant up

**Comment by briancain** [comment]
Hello @alexiusp - the box you are trying to use is no longer on Vagrant Cloud. I recommend trying something like `bento/ubuntu-16.04` instead: https://app.vagrantup.com/bento/boxes/ubuntu-16.04

Thanks!

**Comment by justincampbell** [comment]
Relevant boxcutter issue: https://github.com/boxcutter/ubuntu/issues/133

**Comment by alexiusp** [comment]
thanks for help, guys!
