### ISSUE TITLE
vagrant box update never ends

### ISSUE THREAD

**Issue by jeusdi** [hashicorp/vagrant#9234]
### Vagrant version
2.0.1

### Host operating system
Windows 7

### Guest operating system
centos/7

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
[gist debug output](https://gist.github.com/jeusdi/ad6f0cc5a839c5818d615ad417a341d6)

### Expected behavior
Process ends

### Actual behavior
`vagrant box update` never ends.

**Comment by briancain** [comment]
Hi @jeusdi - if you update your powershell to the latest version, do you still experience this issue?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Comment by jeusdi** [comment]
Sorry. It was solved when I updated powershell.
