### ISSUE TITLE
Invalid token preventing access to public boxes

### ISSUE THREAD

**Issue by tgr** [hashicorp/vagrant#9238]
`vagrant up` / `vagrant box add debian/contrib-stretch64` failed with `curl: (22) The requested URL returned error: 401 Unauthorized` (relevant log snippet here: https://phabricator.wikimedia.org/T181867; don't have the full log unfortunately).  After some trial & error I could fix the problem with `vagrant login --token 'aaa'`. So apparently there are some tokens which prevent access to a public box even though an invalid token does not. That seems like an unnecessary point of failure.

(I'm not sure why vagrant used a token in the first place; `vagrant login --check` told me I'm not logged in. I did log in in the past into some free, unprivileged account to use a tunnel, but that was months if not years ago.)

My setup is Vagrant 1.9.5, Ubuntu 16.04.3.

**Comment by briancain** [comment]
Hello @tgr - I just attempted to reproduce this with an invalid token using Vagrant 2.0.1 and it worked as expected. Could you please update and let me know if you still experience this behavior?

```shell
brian@localghost:~ % vim .vagrant.d/data/vagrant_login_token
# modified my token to be invalid
brian@localghost:~ % vagrant login --check
You are not currently logged in. Please run `vagrant login` and provide
your login information to authenticate.
brian@localghost:~ % vagrant box add "debian/contrib-stretch64"
==> box: Loading metadata for box 'debian/contrib-stretch64'
    box: URL: https://vagrantcloud.com/debian/contrib-stretch64
==> box: Adding box 'debian/contrib-stretch64' (v9.2.0) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/debian/boxes/contrib-stretch64/versions/9.2.0/providers/virtualbox.box
==> box: Successfully added box 'debian/contrib-stretch64' (v9.2.0) for 'virtualbox'!
```

Also, I assume the token in that gist is invalid?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!

**Comment by realiceman** [comment]
Just in case someone ends up here, here is what i have done on my pc (linux ubuntu distro) : 
1) edited the file corresponding to the virtual os i was trying to "vagrant up" : 
   "vim ~/.vagrant.d/boxes/geerlingguy-VAGRANTSLASH-centos7/1.2.9/virtualbox/box.ovf", line 122 added   <Adapter slot="0" enabled="true" MACAddress="08002701AB81" **cable="true"** type="82540EM">
2) in case you have an older version of virtualbox, after the image was downloaded go to vb, right click on the image > setttings > network and click the checkbox 
![selection_102](https://user-images.githubusercontent.com/6204546/43992258-c61af0ac-9d4a-11e8-97c6-872bbb7b497e.png)
3) go to vagrantcloud.com create an account 
4) go to your folder which contains the Vagrantfile and in a terminal write "vagrant login", enter your credentials 
5) vagrant up to start your vm, vagrant ssh hostname ......  
and you're good to go.....at least i was :)
