### ISSUE TITLE
vagrant manage?

### ISSUE THREAD

**Issue by elreydetoda** [hashicorp/vagrant#9239]
I wanted to tell you all before I started how much I love the product it is pretty dang awesome! I am trying to do a lot of things with it. 

So, I wanted to just submit this, and I don't expect anything out of it. I am just tossing the idea out there so you can close it right away if you want to. One thing that you can't do with vagrant is manage an already created vm (at least not from what I have seen, I looked through a lot of the issues/googled to see if anyone had talked about this before but didn't see anything), which makes sense because when you `vagrant init` and download a box or start to manage a box from `vagrant up` you need to record all the information in the local vagrant directory. I feel like there would be a way though that you could still scrape the information from whatever cli tool you are using to add an already created vm to allow vagrant to manage it.

So say for instance a sys admin downloads the esxi plugin and want's to control a remote esxi box (I know this wouldn't be you all, because you don't support plugins I am just giving a scenario) then he could maybe do `vagrant manage remote add $ip` and add the remote esxi box and could manage an already running vm by doing something like `vagrant manage remote list $hostname` or something like that ( I know that is getting long, but you get the idea). 

Or say if it is all local on like virtualbox or something then you could do `vagrant manage local list` that would list all local vms registered to virtualbox and you could do `vagrant manage local add $UUID` from there you could control it with the normal `vagrant up` and such (as long as they configured it already with a vagrant user,etc...) 

Like I said it was an out there idea, that I had while thinking about vagrant. I know that would probably be an extensive amount of work, so shoot it down, ignore it, but I just wanted to post and let you all know about the idea I had so you could use it if you want.

Thank you again for the awesome product!!

Something I just thought of as well, maybe there can be a hashtag on twitter you all use to show off how different people show off how they are using your product. like there is a [unixporn](reddit.com/r/unixporn/) or like [homelab](https://www.reddit.com/r/homelab/) to allow idea sharing and then progressions for the vagrant projects. Just something I though of while writing this

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
