### ISSUE TITLE
Cannot SSH into CentOS 7 VM when using multiple VM env

### ISSUE THREAD

**Issue by dfranciscus** [hashicorp/vagrant#9241]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

Vagrant 2.0.1

### Host operating system
This is the operating system that you run locally.

Mac OS High Sierra

### Guest operating system
This is the operating system you run in the virtual machine.

CentOS 7

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.define :puppet do |puppet|
    puppet.vm.box = "centos/7"
    puppet.vm.network :private_network, ip: "10.0.2.15"
    puppet.vm.hostname = "puppet"
  end

  config.vm.define :puppetagent do |puppetagent|
    puppetagent.vm.box = "centos/7"
    puppetagent.vm.network :private_network, ip: "10.0.2.16"
    puppetagent.vm.hostname = "puppetagent"
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

https://gist.github.com/dfranciscus/8b5ab2ca99d05b1e5e8cc491de59a675

### Expected behavior
What should have happened?

From what I know, VM should come up fine and be able to SSH into it. I cannot for either VM. Oddly, I can if I don't do a multiple VM box.

### Actual behavior
What actually happened?
Cant SSH into VM

### Steps to reproduce
1. mkdir puppet_env
2. cd puppet_env
3. vagrant init centos/7
4. edit Vagrantfile with config above
5. vagrant up puppet

### References
Are there any other GitHub issues (open or closed) that should be linked here?

**Comment by briancain** [comment]
@dfranciscus Can you try again with the `bento/centos-7.2` vagrant box and let me know if that works for you? Thanks!

**Comment by dfranciscus** [comment]
Hi @briancain oddly it seems if I comment out the private IP, ssh works.

' # puppet.vm.network :private_network, ip: "10.0.2.15"'

**Comment by briancain** [comment]
@dfranciscus - I think it's because the box you're using doesn't have guest editions installed? And I believe that's needed to set the private_network setting.

**Comment by dfranciscus** [comment]
@briancain I removed the vagrant-vbguest plugin and that seemed to resolve the issue. I am using  "bento/centos-7.2" as well. Thanks!
