### ISSUE TITLE
vagrant up fail

### ISSUE THREAD

**Issue by forloop163** [hashicorp/vagrant#9242]
vagrant up 

### Vagrant version
Vagrant 2.0.1

MacOsHigh Sierra

### Vagrantfile
config.vm.box = "centos7"
config.vm.network "forwarded_port", guest: 80, host: 8080

### Debug output
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "c9eba581-d472-4e34-aa66-3d3a1c904773", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'centos7_default_1511938481051_60152' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "c9eba581-d472-4e34-aa66-3d3a1c904773", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'centos7_default_1511938481051_60152' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

 INFO interface: Machine: error-exit ["Vagrant::Errors::VBoxManageError", "There was an error while executing `VBoxManage`, a CLI used by Vagrant\nfor controlling VirtualBox. The command and stderr is shown below.\n\nCommand: [\"startvm\", \"c9eba581-d472-4e34-aa66-3d3a1c904773\", \"--type\", \"headless\"]\n\nStderr: VBoxManage: error: The virtual machine 'centos7_default_1511938481051_60152' has terminated unexpectedly during startup with exit code 1 (0x1)\nVBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine\n"]

**Comment by briancain** [comment]
@forloop163 - Could you try using a different centos box (like `bento/centos-7.2`) and see if that solves this? Thanks!

**Comment by forloop163** [comment]
when i re-install the vbox, it can be used, but not sure whether there'll be other problems, because last time when i finish installing it, it's well-run, but it did not work after about 1day later

**Comment by forloop163** [comment]
@briancain when i re-install the vbox, it can be used, but not sure whether there'll be other problems, because last time when i finish installing it, it's well-run, but it did not work after about 1day later.

**Comment by forloop163** [comment]
@briancain I'll keep watching. Thank you.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
