### ISSUE TITLE
Vagrant fails on destroy

### ISSUE THREAD

**Issue by Occams** [hashicorp/vagrant#9244]
### Vagrant version
2.0.1

### Host operating system
Windows Server 2016
Virtualbox 5.1.30

### Guest operating system
Windows 10 Fall Creators Update

### Debug output
https://gist.github.com/Occams/a849f8e10ad413cfdc3e29e6746fe791

This issue popped up on a CI-Build doing automated testing using vagrant. Unfortunately, there's no way for me to reproduce this bug and provide more detailed debug information.

**Comment by briancain** [comment]
@Occams - Does your CI do any cleanup prior to running vagrant destroy? It looks like maybe a folder within a vagrant environment got deleted, and then when vagrant destroy was invoked it tried to read a folder that it expected to exist on disk, but was returned as nil because it was no longer there.

**Comment by Occams** [comment]
@briancain There's no cleanup involved at this stage. All automated tests are conducted in a pristine and temporary vagrant environment. The sequence of vagrant commands is quite simple:

- Dynamically generate Vagrant file

- Do a `vagrant up`

- Create a live snapshot using `vagrant snapshot push`

- Invoke automated tests via a sequences of `vagrant snapshot pop` and `vagrant powershell`

- Cleanup using `vagrant destroy --force`

We run hundreds of successful tests each day, thus this must be some kind of race condition.

**Comment by chrisroberts** [comment]
@Occams Are you still encountering this issue with the latest Vagrant release?

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
