### ISSUE TITLE
Cannot install vmware workstation provider: Unable to resolve dependency: user requested 'vmware-workstation-provider (> 0)'

### ISSUE THREAD

**Issue by bradley-evans** [hashicorp/vagrant#9246]
### General description of issue

I am trying to install the latest version of `vmware_workstation_provider` so it will work with the newest versions of VMWare Workstation (namely, 14). Having a hell of a time with it, though.

### Vagrant version
```
$ vagrant -v
Vagrant 2.0.1
```

### Host operating system
Windows 10

### Guest operating system
Not applicable

### Vagrantfile
Not applicable

### Debug output
https://gist.github.com/bradley-evans/27c729fcdd2a73e4886edf4b3feea7e0
```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vmware-workstation-provider (> 0)'
```

### Expected behavior
I would hope that `vmware-workstation-provider` would be installed.

### Actual behavior
The above bundler error.

### Steps taken to correct the issue

1. Delete / rename `.vagrant.d`
2. Updated `vagrant` to latest version, reinstalled vagrant.
3. Turning it off and then on again.
4. Updating `ruby` with `gem update`. Reinstalling ruby. Ensuring that `gcc` is installed.

Taking this time to verify that I am indeed using an elevated shell. I've tried to run the update command in cygwin, as well.

**Comment by geckoseo** [comment]
updating the vagrant plugins solved this for me

**Comment by briancain** [comment]
Hello @bradley-evans - it looks like you are using the wrong name to install the vagrant vmware provider. Please check out the installation docs which will give you more information on how to install the correct provider. Thanks!

https://www.vagrantup.com/docs/vmware/installation.html
