### ISSUE TITLE
vagrant ssh root密码是什么

### ISSUE THREAD

**Issue by djsxianglei** [hashicorp/vagrant#9247]

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you! 😄

**Comment by djsxianglei** [comment]
thanks,I've solved the problem. Vagrant has no password. I need to set it myself。
