### ISSUE TITLE
sensitive environment variables echoed on failed provision

### ISSUE THREAD

**Issue by DannyMeister** [hashicorp/vagrant#9257]
Today I think a coworker learned my corporate domain password by looking over my shoulder as I did a vagrant up. <goes to change password, restart services, get locked out, grumble, grumble...>

Environment variables are echoed in plain text on provisioning script failure.  Because I need to export a code repository on the guest machine as part of provisioning, I pass my credentials as environment variables.  All has been good until a provisioning script failed and echo'd out my credentials (one down side of pair programming :) )

### Vagrant version
2.0.1

### Host operating system
Windows 10

### Guest operating system
Windows Server 2016 Standard Edition

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  # the following values are read from encrypted file or prompts the user for masked input in my actual vagrantfile
  svnuser = "testuser"
  svnpassword = "testpassword"

  config.vm.box = "gusztavvargadr/w16s-sql14d"
  config.vm.box_version = "0.6.0"
  
  config.vm.network "private_network", type: "dhcp"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end
  config.vm.provision "shell", env: {"SVNUSER"=>svnuser, "SVNPASSWORD"=>svnpassword}, inline: <<'SHELL'
    exit 1
SHELL
end
```

###  output
The following WinRM command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

$env:SVNUSER = "testuser"; $env:SVNPASSWORD = "testpassword"; powershell -ExecutionPolicy Bypass -OutputFormat Text -file "c:\tmp\vagrant-shell.ps1"

### Expected behavior
I believe what happened was intended behavior for vagrant, and quite useful for debugging failed provisioning.  However, as this seems to be the only out-of-box mechanism which I have seen recommended for passing secrets into your guest machine, it seems like there should be an easy way to obscure sensitive settings.

**Comment by chrisroberts** [comment]
Fixed via #9367
