### ISSUE TITLE
There was an error with this Vagrant

### ISSUE THREAD

**Issue by Raghuveer123** [hashicorp/vagrant#9262]
vagrant up
 INFO dcos-vagrant: Validating Plugins...
 INFO dcos-vagrant: Validating User Config...
 INFO dcos-vagrant: Validating Installer Checksum...
 INFO dcos-vagrant: Using DC/OS Installer: installers/dcos/dcos_generate_config-1.10.0.sh
 INFO dcos-vagrant: Using DC/OS Config: etc/config-1.10.yaml
 INFO dcos-vagrant: Validating Machine Config...
 INFO dcos-vagrant: Validating Command...
 INFO dcos-vagrant: Configuring VirtualBox Host-Only Network...
Bringing machine 'm1' up with 'virtualbox' provider...
Bringing machine 'a1' up with 'virtualbox' provider...
Bringing machine 'p1' up with 'virtualbox' provider...
Bringing machine 'boot' up with 'virtualbox' provider...
==> m1: Importing base box 'mesosphere/dcos-centos-virtualbox'...
==> m1: Matching MAC address for NAT networking...
==> m1: Checking if box 'mesosphere/dcos-centos-virtualbox' is up to date...
==> m1: Setting the name of the VM: m1.dcos
==> m1: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: SetupDiCreateDeviceInfo failed (0x00000005)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp

**Comment by Raghuveer123** [comment]
Vagrant Version is 2.0.1
Windows 7 64 bit
VIrtual Box- 5.2.2

**Comment by briancain** [comment]
Hi @Raghuveer123 - Please fill out this [issue template](https://github.com/hashicorp/vagrant/blob/master/.github/ISSUE_TEMPLATE.md) provided. It gives us more information to help triage your issue. Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
