### ISSUE TITLE
some times Vagrant is failed to synching share folders to guest VM

### ISSUE THREAD

**Issue by ashokvaddevalli** [hashicorp/vagrant#9270]
### Vagrant version
2.0.1
### Host operating system
Windows 7

### Guest operating system
Windows 7

### Vagrantfile

```ruby
 -*- mode: ruby -*-
# vi: set ft=ruby :

#Author: Ashok Vaddevalli

Vagrant.configure("2") do |config|
  
config.vm.box = 'dummy'
config.vm.box_url = 'dummy.box'

#config.vm.network "private_network", ip: ENV["ip"]


config.vm.communicator = "winrm"
config.winrm.username = "admin"
config.winrm.password = "admin@123"
config.winrm.timeout = 1800
config.vm.boot_timeout = 600


config.vm.synced_folder "./src", "/src", type: "smb", smb_username: "administrator", smb_password: "admin@123"

config.vm.synced_folder "./Result", "/Result", type: "smb", smb_username: "administrator", smb_password: "admin@123"

config.vm.synced_folder ".", "/vagrant", disabled: true

 
  config.vm.provider :vsphere do |vsphere|
    vsphere.host = 'X.X.X.X'
	#vsphere.customization_spec_name = 'Win7-Custom_template'
    vsphere.compute_resource_name = 'X.X.X.X'
    vsphere.data_center_name = 'Demo'
    vsphere.template_name = 'Templates/InstallerAutomation'
    vsphere.name = 'InstallerAuto'
    vsphere.user = 'administrator@vsphere.local'
    vsphere.password = ENV["vsphere.password"]
	vsphere.insecure = true
  end
  
 
config.vm.provision "shell", inline: "C:/src/setupandrunautomation.bat"
  
  
end

```

### Expected behavior

> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: WinRM address: X.X.X.X:5985
>     default: WinRM username: admin
>     default: WinRM execution_time_limit: PT2H
>     default: WinRM transport: negotiate
> ==> default: Machine booted and ready!
> ==> default: Preparing SMB shared folders...
> ==> default: Mounting SMB shared folders...
>     default: C:/InstallerAutomation/src => /src
>     default: C:/InstallerAutomation/Result => /Result
> ==> default: Running provisioner: shell...
>     default: Running: inline PowerShell script
>     default:         1 file(s) moved.

### Actual behavior

> ==> default: Mounting SMB shared folders...
>     default: C:/InstallerAutomation/src => /src
> The following WinRM command responded with a non-zero exit status.
> Vagrant assumes that this means the command failed!
> 
> cmdkey /add:X.X.X.X /user:administrator /pass:admin@123
> 
> Stdout from the command:
> 
> 
> 
> Stderr from the command:
> 

### Steps to reproduce
1. Re run Vagrant up second time, it was synchronizing share folders, sometimes u can re run vagrant up multiple times for share folders synchronization.

**Comment by ashokvaddevalli** [comment]
Downgrade 2.0 version, share folder synchronizing working fine, but getting the issue on destroy VM.

destroy VM
SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A

**Comment by briancain** [comment]
@ashokvaddevalli - could you please provide a gist link to the full debug log? Thanks!

**Comment by ashokvaddevalli** [comment]
[Vagrant_Vsphere_Debuglog.txt](https://github.com/hashicorp/vagrant/files/1563586/Vagrant_Vsphere_Debuglog.txt)

**Comment by ashokvaddevalli** [comment]
I am wondering mostly this issue comes with every second build(running vagrant up in second time ).

**Comment by ashokvaddevalli** [comment]
I have not seen this issue after done few settings in both host machine and guest machine templates.

The below settings I have done,
1. net config server /autodisconnect:-1
2. Increased SMB timeout time.

**Comment by chrisroberts** [comment]
As setting modification resolved this issue I'm going to close this up.
