### ISSUE TITLE
installation issue on 16.04

### ISSUE THREAD

**Issue by 16116073** [hashicorp/vagrant#9282]
![vagrant](https://user-images.githubusercontent.com/25207205/34073862-c5b79bb0-e2c9-11e7-8459-481a5fbde1f1.png)

**Comment by briancain** [comment]
@16116073 - if you install the latest debian package from https://www.vagrantup.com/downloads.html does it work for you? Thanks!

**Comment by 16116073** [comment]
@briancain ye it did. Thank you. :-)
