### ISSUE TITLE
[$$$] "The "package" command is not supported with VMware"

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9283]
![screen shot 2017-12-17 at 11 48 59 pm](https://user-images.githubusercontent.com/5316/34091754-464d4674-e385-11e7-95dd-986bbedcbf8c.png)

I want to export a Vagrant box that adds additional configuration to a base box built with packer. When I try to export the box, I get an error.

# Source

https://github.com/mcandre/vagrant-macos-homebrew

# Trace

```console
$ vagrant package --output vagrant-macos-homebrew.box
The "package" command is not supported with VMware. We recommend
taking a look at Packer (www.packer.io) as an option for creating
VMware images.
```

It really caught me off guard after I had paid for this plugin to learn that it lacks support for exporting boxes, a reasonably basic feature to expect it to have compared to other Vagrant providers like VirtualBox. I know that VMware is capable of exporting VM's in a way that amenable to constructing Vagrant boxes, because packer can do this.  Although the error message recommends that VMware boxes always be built from scratch using packer, I find this extremely inconvenient. I would prefer to build on top of preexisting boxes using the normal `vagrant package` command. Could this functionality please be added to the VMware Vagrant plugin?

**Comment by chrisroberts** [comment]
The package command is available in the vagrant-vmware-desktop plugin.

Cheers!
