### ISSUE TITLE
Cannot ssh to guest after box update

### ISSUE THREAD

**Issue by gfot** [hashicorp/vagrant#9284]
### Vagrant version
Vagrant 2.0.1

### Host operating system
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

### Guest operating system
Ubuntu 16.04 (box: ubuntu/xenial64)

### Vagrantfile
```ruby
config.vm.define site['name'], autostart: true do |m|
    m.vm.box = BOX_IMAGE
    m.vm.hostname = site['hostname']
    m.vm.network "private_network", ip: site['network']['private']['ip'], netmask: common['network']['mask'], auto_config: true
    (site['network']['port_forward']).each do |pf|
      d = pf['data']
      m.vm.network :forwarded_port, guest: d['guest']['port'], host: d['host']['port'], guest_ip: d['guest']['ip'], host_ip: d['host']['ip'], protocol: d['protocol'], auto_correct: false
    end
    (site['synced_folder']).each do |sf|
      d = sf['data']
      m.vm.synced_folder d['host'], d['guest']
    end
    m.vm.provider "virtualbox" do |vb|
      vb.gui    = if site['provider']['gui'] == 'yes' then true else false end
      vb.cpus   = site['provider']['cpus']
      vb.memory = site['provider']['memory_mb']
    end
    (site['provision']).each do |prv|
      d = prv['data']
      m.vm.provision d['name'], type: "shell", path: d['path'], args: d['args'], privileged: false
    end
    # m.vbguest.auto_update = true
  end
```
When i `vagrant up` and then ssh to vm the system starts with a "System restart required" message.  In vm: `cat /var/run/reboot-required.pkgs` outputs: `linux-image-4.4.0-104-generic, linux-base`. So I logout vm and execute `vagrant reload` to execute restart of vm. After that I can never ssh again to vm. Any ideas?

**Comment by gfot** [comment]
That does not happen with box: "geerlingguy/ubuntu1604". So I assume that is a problem with official "ubuntu/xenial64" box.

**Comment by briancain** [comment]
Hi @gfot - yes that is likely an issue with the vagrant box you are using then. I usually recommend people use the bento boxes...so perhaps `bento/ubuntu-16.04` will work for you? I'll go ahead and close this since it looks to be a box issue. Thanks!
