### ISSUE TITLE
cannot install vagrant-share 1.1.7

### ISSUE THREAD

**Issue by arimourao** [hashicorp/vagrant#9289]
I've been running into some issues lately with my vagrant box. So I ran vagrant plugin expunge --reinstall and then it says that it could not resolve dependency for vagrant-share 1.1.7

### Vagrant version
2.0.1

### Host operating system
Ubuntu 16 64bits

### Guest operating system
Ubuntu

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$serviceup = <<SCRIPT
    echo "Starting service..."
    php -S 0.0.0.0:8000 -t /vagrant/src /vagrant/src/router.php &
    echo "All done! Call http://127.0.0.1:8000 in your browser and be happy."
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Every Vagrant virtual environment requires a box to build off of.
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "forwarded_port", guest: 8000, host: 3132


    # backing providers for Vagrant. These expose provider-specific options.
    config.vm.provider :virtualbox do |vb|

        # Set VM memory size

        vb.customize ["modifyvm", :id, "--memory", "1024"]

        # these 2 commands massively speed up DNS resolution, which means outbound
        # connections don't take forever (eg the WP admin dashboard and update page)
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    end

    config.landrush.enabled = true
    config.landrush.tld = 'fdev'

    config.vm.network "private_network", ip: "192.168.50.5"
    config.vm.hostname = "mapa.fdev"
    config.hostsupdater.remove_on_suspend = true
    #config.vm.boot_timeout = 600

    # config.landrush.host 'mapa.local', '192.168.50.5'




    config.vm.provision "shell", path: "./scripts/install_vagrant.sh"

    config.vm.provision "shell", path: "./scripts/configure_vagrant.sh", args: "/vagrant",
            privileged: false

    # config.vm.provision "shell", inline: $serviceup,
    #         run: "always",
            # privileged: false

    #config.vm.provider :virtualbox do |vb|
    #  vb.gui = true
    #end
end
```

### Debug output
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-share (= 1.1.7)'

### Expected behavior
It should be able to resolve the dependency

### Actual behavior
it is not resolving

**Comment by chrisroberts** [comment]
If you expunge plugins without re-installing and install the plugins individually does that fix the issue?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
