### ISSUE TITLE
Delete the folder that contains my virtual machine

### ISSUE THREAD

**Issue by usuga1931** [hashicorp/vagrant#9296]
Delete the folder that contains my virtual machine, but do not run the "vagrant destroy" the machine can be seen in the virtual box, Is there any way to recover everything I have in that machine?

Thanks.

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the Vagrant mailing list. There are many more people who will be able to get you a faster answer there. Thank you and have a great day!
