### ISSUE TITLE
Vagrant Command Fail on Windows 10 build 1709 - input string invalid 

### ISSUE THREAD

**Issue by chonhan** [hashicorp/vagrant#9299]
Hello, yesterday I had a Windows upgrade to build 1709 Fall Creators Update. However, After system upgraded, I found my vagrant command had broken. Even I uninstall and reinstall both Virtualbox and Vagrant. The result is still the same. 

Since I can turn on my guest VM on Virtualbox, I guess the root cause is something wrong with Vagrant. Does anyone have the same problem as mine?

PS. I can still use `vagrant -v` to get the version info. But when I use `vagrant`, I just get the following error messages.

λ vagrant
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:208:in `downcase': input string invalid (ArgumentError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:208:in `block (2 levels) in fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:207:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:207:in `block in fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:206:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:206:in `fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:121:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/bin/vagrant:118:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/bin/vagrant:118:in `<main>'

### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 10 version 1709
With VirtualBox-5.2.4-119785-Win.exe
And Oracle_VM_VirtualBox_Extension_Pack-5.2.4-119785.vbox-extpack

### Guest operating system
None

### Vagrantfile
None

### Debug output
https://gist.github.com/chonhan/78a59432b199e8ff22f0b6a3e4a0589f

### Expected behavior

$ vagrant
Usage: vagrant [options] <command> [<args>]

    -v, --version                    Print the version and exit.
    -h, --help                       Print this help.

### Actual behavior

λ vagrant
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:208:in `downcase': input string invalid (ArgumentError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:208:in `block (2 levels) in fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:207:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:207:in `block in fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:206:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/platform.rb:206:in `fs_real_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/environment.rb:121:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/bin/vagrant:118:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/bin/vagrant:118:in `<main>'

### Steps to reproduce
1. Upgrade to Windows 10 version 1709
2. Uninstall Vagrant and Virtualbox 
3. Restart
4. Install Virtualbox 5.2.4 and Extension pack
5. Install Vagrant 2.0.1 
6 Restart
7. Execute command

**Comment by briancain** [comment]
@chonhan - What shell program are you using to invoke Vagrant with?

**Comment by chonhan** [comment]
@briancain 
I use `Cmder` as my shell program. It always works fine until this upgrade.

**Comment by akira32chen** [comment]
Do you install the newest git?
