### ISSUE TITLE
SSL Certificate Problem

### ISSUE THREAD

**Issue by chaitanya-ambaselkar** [hashicorp/vagrant#9309]
There is an issue with curl on vagrant version 2.0.1 64 bit on running on windows 7 enterprise. This issue is also seen on versions 1.9.7 and 19.8. 

Below is more information on the issue

c:\chaitanya-data\Personal\vagrantboxes\centos>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/centos-7.2' could not be found. Attempting to find and i
nstall...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'bento/centos-7.2' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/bento/centos-7.2"]
Error: SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Not sure about this. I was able to download it by using config.vm.box_download_insure = true option.

I am connecting to the internet via an enterprise proxy and I am able to visit the vagrantcloud.com via browser fine. 

Thanks
Chaitanya

Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Host operating system
This is the operating system that you run locally.

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by espoelstra** [comment]
This is due to the fact that your company is using an intercepting proxy to decrypt and examine traffic from any computers inside their network. There have been numerous tickets about this in the past, you can either add a copy of your company's certificate to the `cacert.pem` used by the version of `curl` included with Vagrant or you can check out the Vagrant documentation for the `allow-insecure-ssl` or something similar that will ignore the error and basically pass `-k` to `curl` which suppresses this error.

**Comment by espoelstra** [comment]
This is the command, `config.vm.box_download_insecure = true`, and many people on this issue are having the same issue, https://github.com/hashicorp/vagrant/issues/8984 .

**Comment by jesuswasrasta** [comment]
Windows 10, Vagrant 2.1.2, trying to setting up an ubuntu/bionic: I solved using that config 👍

**Comment by philiosi** [comment]
windows 10. Vagrant 2.2.0, also, that config works.

**Comment by chrisroberts** [comment]
Closing as resolved. Cheers.
