### ISSUE TITLE
Can not start machine after vagrant reload

### ISSUE THREAD

**Issue by dragonabv** [hashicorp/vagrant#9312]
agldev@agldev:~/django_vagrant$ vagrant reload
==> djangovm: Attempting graceful shutdown of VM...
==> djangovm: Clearing any previously set forwarded ports...
==> djangovm: Clearing any previously set network interfaces...
==> djangovm: Preparing network interfaces based on configuration...
    djangovm: Adapter 1: nat
==> djangovm: Forwarding ports...
    djangovm: 80 (guest) => 8080 (host) (adapter 1)
    djangovm: 8000 (guest) => 8001 (host) (adapter 1)
    djangovm: 22 (guest) => 2222 (host) (adapter 1)
==> djangovm: Booting VM...
==> djangovm: Waiting for machine to boot. This may take a few minutes...
    djangovm: SSH address: 127.0.0.1:2222
    djangovm: SSH username: vagrant
    djangovm: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

------------------------------------------------------------
agldev@agldev:~/django_vagrant$ vagrant up --provision
Bringing machine 'djangovm' up with 'virtualbox' provider...
==> djangovm: Running provisioner: chef_solo...
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.

**Comment by briancain** [comment]
@dragonabv - Can you please fill out the issue template with the information it asks? Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
