### ISSUE TITLE
vagrant reload - Storage controller already exists

### ISSUE THREAD

**Issue by port22** [hashicorp/vagrant#9313]
Referring to https://github.com/hashicorp/vagrant/issues/5920

```
`Command: ["storagectl", "27a5e0a7-7818-4c2f-baa4-0b6b55a4a033", "--name", "scsi", "--add", "scsi", "--controller", "LSILogic"]`

Stderr: VBoxManage: error: Storage controller named 'scsi' already exists
```

I have the same problem - it is NOT a Virtualbox issue.

This happens on `vagrant reload` and means that the controller which already exists can not be created again (of course, because the virtual machine still exists).

But **how to write the Vagrantfile** so that vagrant will not try to create the Controller again?
Is there a if-condition to test if vagrant does a reload ?

**Comment by briancain** [comment]
@port22 - I think what you really want to do is wrap your controller creation in a conditional that checks if the controller already exists. If you are running `vboxmanage storagectl` yourself with the built in provider custom commands, then you will need to add some logic in your Vagrantfile to ensure it doesn't try to re-create the controller again.

But like the issue you linked to mention, this is not a problem with Vagrant. If you're running a customize command yourself inside a Vagrantfile, it will run every time you bring up the vm. I'm going to go ahead and close this, but if you have further questions please redirect them to the Vagrant up mailing list. More people will be able to help you on there with questions. Thanks!
