### ISSUE TITLE
nfs server export options customization

### ISSUE THREAD

**Issue by port22** [hashicorp/vagrant#9314]
While trying to define nfs synced folder, vagrant refuses to mount it:

```
config.vm.synced_folder "/www", "/www", id: "www", :nfs => true, nfs_udp: false, nfs_version: 3, verify_installed: false, nfs_export: true, mount_options: ["nolock", "rw"]
```

host: /etc/exports
```
# VAGRANT-BEGIN: 1000 27a5e0a7-7818-4c2f-baa4-0b6b55a4a033
"/raid/www" 33.33.33.20(rw,no_subtree_check,all_squash,anonuid=1010,anongid=409,fsid=1011666284)
# VAGRANT-END: 1000 27a5e0a7-7818-4c2f-baa4-0b6b55a4a033
```

First, the guessed ip is wrong. The vm has this private_ip, but outgoing connection from the vm are not being routed via this IP, so nfs-server denies access. Hence I have to modify the IP at time when the /etc/exports file is being modified.

Second, I have to add the **insecure**-option.

Example how I could imagine this:

```
config.vm.synced_folder  "/www", "/www", id: "www", :nfs => true,
nfs_clients: ["33.33.33.1","192.168.56.*"], nfs_server_options: ["insecure","anongid=1000"]
```

**Comment by briancain** [comment]
@port22 - Is the denied access happening when vagrant tries to sync the folder during a `vagrant up`? Do you have a gist link to a debug log and a Vagrantfile that could help us see what's happening? Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
