### ISSUE TITLE
Getting following issue when I run "vagrant" command.

### ISSUE THREAD

**Issue by shakeel2198** [hashicorp/vagrant#9319]
121 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/registry
.rb
  122 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/set.rb
  123 C:/HashiCorp/Vagrant/embedded/gems/gems/i18n-0.8.0/lib/i18n/config.rb
  124 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri/rfc2396_parser.rb

  125 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri/rfc3986_parser.rb

  126 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri/common.rb
  127 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri/generic.rb
  128 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri/ftp.rb
  129 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri/http.rb
  130 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri/https.rb
  131 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri/ldap.rb
  132 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri/ldaps.rb
  133 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri/mailto.rb
  134 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/uri.rb
  135 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/util.rb
  136 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/i386-mingw32/io/conso
le.so
  137 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/user_interac
tion.rb
  138 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/security/pol
icy.rb
  139 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/security/pol
icies.rb
  140 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/security/tru
st_dir.rb
  141 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/security/sig
ner.rb
  142 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/security.rb
  143 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/i386-mingw32/zlib.so
  144 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/package/dige
st_io.rb
  145 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/package/sour
ce.rb
  146 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/package/file
_source.rb
  147 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/package/io_s
ource.rb
  148 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/package/old.
rb
  149 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/package/tar_
header.rb
  150 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/package/tar_
reader/entry.rb
  151 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/package/tar_
reader.rb
  152 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/package/tar_
writer.rb
  153 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/package.rb
  154 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/tsort.rb
  155 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/dependency_l
ist.rb
  156 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/request_set/
gem_dependency_api.rb
  157 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/request_set/
lockfile/parser.rb
  158 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/request_set/
lockfile/tokenizer.rb
  159 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/request_set/
lockfile.rb
  160 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/request_set.
rb
  161 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/gem_metadata.rb
  162 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/errors.rb
  163 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/dependency_graph/action.rb
  164 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/dependency_graph/add_edge_no_circular.rb
  165 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/dependency_graph/add_vertex.rb
  166 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/dependency_graph/delete_edge.rb
  167 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/dependency_graph/detach_vertex_named.rb
  168 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/dependency_graph/set_payload.rb
  169 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/dependency_graph/tag.rb
  170 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/dependency_graph/log.rb
  171 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/dependency_graph/vertex.rb
  172 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/dependency_graph.rb
  173 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/state.rb
  174 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/modules/specification_provider.rb
  175 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/delegates/resolution_state.rb
  176 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/delegates/specification_provider.rb
  177 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/resolution.rb
  178 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/resolver.rb
  179 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo/modules/ui.rb
  180 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo/lib/molinillo.rb
  181 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/mol
inillo.rb
  182 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/act
ivation_request.rb
  183 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/con
flict.rb
  184 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/dep
endency_request.rb
  185 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/req
uirement_list.rb
  186 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/sta
ts.rb
  187 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/set
.rb
  188 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/api
_set.rb
  189 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/com
posed_set.rb
  190 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/bes
t_set.rb
  191 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/cur
rent_set.rb
  192 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/git
_set.rb
  193 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/ind
ex_set.rb
  194 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/ins
taller_set.rb
  195 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/loc
k_set.rb
  196 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/ven
dor_set.rb
  197 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/sou
rce_set.rb
  198 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/spe
cification.rb
  199 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/spe
c_specification.rb
  200 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/api
_specification.rb
  201 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/git
_specification.rb
  202 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/ind
ex_specification.rb
  203 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/ins
talled_specification.rb
  204 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/loc
al_specification.rb
  205 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/loc
k_specification.rb
  206 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver/ven
dor_specification.rb
  207 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/resolver.rb
  208 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/source/git.r
b
  209 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/source/insta
lled.rb
  210 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/source/speci
fic_file.rb
  211 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/source/local
.rb
  212 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/source/lock.
rb
  213 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/source/vendo
r.rb
  214 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/source.rb
  215 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rdoc.rb
  216 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rdoc/rubygems_hook.rb

  217 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/rdoc.rb
  218 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/uninstaller.
rb
  219 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/name_tuple.r
b
  220 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util.rb
  221 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/saf
e_env.rb
  222 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/bundler.
rb
  223 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/s
tate_file.rb
  224 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/m
anager.rb
  225 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/util/dee
p_merge.rb
  226 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/config_file.
rb
  227 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/versions.rb
  228 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/exception.rb
  229 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/syntax_error.rb

  230 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/i386-mingw32/psych.so

  231 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/omap.rb
  232 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/set.rb
  233 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/class_loader.rb

  234 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/i386-mingw32/strscan.
so
  235 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/scalar_scanner.
rb
  236 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/nodes/node.rb
  237 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/nodes/stream.rb

  238 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/nodes/document.
rb
  239 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/nodes/sequence.
rb
  240 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/nodes/scalar.rb

  241 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/nodes/mapping.r
b
  242 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/nodes/alias.rb
  243 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/nodes.rb
  244 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/streaming.rb
  245 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/visitors/visito
r.rb
  246 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/visitors/to_rub
y.rb
  247 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/visitors/emitte
r.rb
  248 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/handler.rb
  249 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/tree_builder.rb

  250 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/visitors/yaml_t
ree.rb
  251 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/json/ruby_event
s.rb
  252 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/visitors/json_t
ree.rb
  253 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/visitors/depth_
first.rb
  254 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/visitors.rb
  255 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/parser.rb
  256 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/coder.rb
  257 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/core_ext.rb
  258 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/i386-mingw32/date_cor
e.so
  259 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/date.rb
  260 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/deprecated.rb
  261 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/stream.rb
  262 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/json/yaml_event
s.rb
  263 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/json/tree_build
er.rb
  264 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/json/stream.rb
  265 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych/handlers/docume
nt_stream.rb
  266 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/psych.rb
  267 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/psych_additi
ons.rb
  268 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/psych_tree.r
b
  269 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/yaml.rb
  270 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/syck_hack.rb

  271 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/i386-mingw32/enc/utf_
16le.so
  272 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/i386-mingw32/enc/utf_
16be.so
  273 C:/HashiCorp/Vagrant/embedded/mingw32/lib/ruby/2.4.0/rubygems/source_list.
rb
  274 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v
2/components.rb
  275 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v
2/errors.rb
  276 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v
2.rb
  277 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v
2/plugin.rb
  278 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v
2/manager.rb
  279 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v
1/errors.rb
  280 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v
1.rb
  281 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v
1/plugin.rb
  282 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/plugin/v
1/manager.rb
  283 C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/provisioners
/chef/command_builder.rb
  284 C:/HashiCorp/Vagrant/embedded/rgloader/rgloader24.mingw.so
  285 C:/HashiCorp/Vagrant/embedded/rgloader/loader.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by shakeel2198** [comment]
I have windows7, 32 bit operating system. Please help me out with this issue.

**Comment by briancain** [comment]
Please fill out the Vagrant issue template with all of the relevant information. Without it, it makes it very difficult for us to help you debug your issue. Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
