### ISSUE TITLE
Automatically --vagrantfile Vagrantfile on vagrant package

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9320]
Vagrant users may be surprised to learn that Vagrant drops important configuration details by default when exporting boxes.

For example, a base box mcandre/netbsd built with packer enables synced folders with rsync. A child box, mcandre/vagrant-netbsd-pkgsrc successfully inherits the `config.ssh.shell`, `config.ssh.sudo_command`, and `config.vm.synced_folder` customizations to successfully `vagrant up`, however a grandchild box mcandre/vagrant-netbsd-rust that extends mcandre/vagrant-netbsd-pkgsrc, fails to `vagrant up`, because the `vagrant package` command used to export the mcandre/vagrant-netbsd-pkgsrc box silently dropped all Vagrantfile customizations, including those of the ancestor mcandre/netbsd box. So mcandre/vagrant-netbsd-rust fails at `vagrant up` due to `config.ssh.shell` reverting back to the Vagrant default bash, not present in NetBSD.

In fact, Vagrant does offer a `--vagrantfile Vagrantfile` option during `vagrant package` exporting, but strangely this is off by default, resulting in even the top-level base box configuration being dropped from downstream boxes. I find this behavior surprising, detrimental, and of low risk to correct by simply applying `--vagrantfile Vagrantfile` by default to future box exports. What do you think?

**Update**

I experimented more with Vagrant flags, and I think that what I actually want, is for `--base`... to be default/implicit when running `vagrant package`. Also would be nice to be able to extend non-VirtualBox-provided boxes as base boxes, like libvirt/qemu and VMware.

**Comment by jbonhag** [comment]
Thanks for the suggestion! I don't think we want to assume that all the configuration of a Vagrantfile is going to applicable to an exported box by default. People may have secrets that they don't want to expose, or a machine may be part of a multi-machine Vagrantfile. We want users to be intentional about what they include with a box.

Again, thank you for the suggestion and have a great day. 😄
