### ISSUE TITLE
Overwrite .box on vagrant package

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9322]
It is helpful that Vagrant presents a message when detecting a previously existing .box file, when the user runs `vagrant package`... However, it would be more helpful to go ahead and overwrite the file, similar to how other command line applications behave.

**Comment by chrisroberts** [comment]
I think that the current behavior of Vagrant returning an error that the destination file already exists is the correct behavior. Automatically overwriting an existing file would be unexpected and likely cause loss when the package command is run and a user is unaware a previously packaged box exists in that location.

Cheers!
