### ISSUE TITLE
--base forgets how to obtain the VM instance name

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9324]
`vagrant halt`, `vagrant destroy`, etc., know how to get a project's VM instance name, but for some reason, when exporting boxes with `--base <name>`, Vagrant then forgets how to obtain this value. I mean, for the vast majority of usage, we're going to want the current working directory's normal Vagrant VM name here.

As a workaround, users can manually examine the contents of `.vagrant/machines/default/virtualbox/id`, lookup the corresponding entry in the `vboxmanage list vms` command output, remove the quotes, and feed *that* value to `vagrant pacakge --base`.

As a workaround, I uploaded a reusable POSIX shell script for accessing this information:

https://github.com/mcandre/garkbit

**Comment by jbonhag** [comment]
Hi there, and thank you for the suggestion.

It seems like if you are changing into the folder where the guest is located, then you can run `vagrant package` without needing the `--base` flag. This also works in a multi-machine environment (for example `vagrant package web`).

Thanks and have a great day! 😄
