### ISSUE TITLE
vagrant up: A flag to disable SSH key generation when preparing to run vagrant package

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9325]
Vagrant features a few hurdles for users attempting to export boxes for reuse. One of those hurdles is SSH configuration, because the Vagrant SSH connector strongly desires to insert a new SSH key during `vagrant up`, causing the box produced by `vagrant package` to fail to `vagrant up` in downstream projects.

One workaround is to ditch Vagrant entirely for producing reusable boxes, and rebuild all extensible boxes from scratch with Packer. This represents an unwieldy workflow.

Another workaround is to manually set `config.ssh.insert_key = false` in the Vagrantfile, then `vagrant destroy -f`, then `rm -rf .vagrant`, and finally `vagrant up && vagrant package`... However, this results in a box whose downstream `vagrant up`s *never* replace the SSH key, which may be undesirable for in certain security environments.

It would be better if `vagrant up` accepted a `-f <Vagrantfile path>`, so that developers could specify one Vagrantfile for building a box, and another sanitized version with corrections like `config.ssh.insert_key = false` for export with `vagrant up -f export.Vagrantfile && vagrant package`...

While a `-f <Vagrantfile path>` would be very useful in its own right, for this particular issue it would suffice if `vagrant up` accepted a flag to override any `config.ssh.insert_key` settings in Vagrantfile's. Perhaps `vagrant up --do-not-insert-key`? `vagrant up --config-extras='config.ssh.insert_key=false'`?

**Update**

For some reason, setting `config.vm.ssh.insert_key = false` in my Vagrantfile actually results in `vagrant up` failing (?)

I also tried `vagrant package --base <VirtualBox live VM name> --vagrantfile export.Vagrantfile`, but strangely the `--base` part seems to override the settings configured in `export.Vagrantfile` :/ So I'm actually using only `--vagrantfile export.Vagrantfile` without the `--base` flag. Ultimately, I was able to successfully `vagrant up` a grandchild Vagrant box by configuring the child with `config.ssh.insert_key = false` in its `Vagrantfile`, and copying the top-level parent's Vagrantfile packer template into `export.Vagrantfile` when packaging.

**Comment by kikitux** [comment]
Hello

Vagrant default behaviour is documented, and the evolution of the tool has been documented in this repo.

Vagrant current default is to replace the known ssh key, this is documented. You can override that if the goal is to keep the known key, however this is not enough to make sure an export box will work in a new import.

Depending of the OS persistency settings will be defined, and those need to be taken care outside of vagrant.

In the historic context, vagrant package did just that, package an existing box, nothing more. 
If the box being packaged is ready to be used, the new box will work just fine.

So any extra step that need to perform is outside the vagrant package command.

Vagrant is a tool that create vms based in a template.
Packer is a tool that createm vms to be consumed, one of those outputs can be vagrant boxes.

If the question is can be vagrant used to package boxes? the answer is yes, however all the manual work required to make the the new box work is outside the scope of the command.

As none of this is an actual bug, i am closing this, please feel free to reach the mailing list if you would like to came with a workflow or guiding on how to build boxes.

As a side note, packer in the context of virtualbox and vagrant can build boxes from an iso, or from an existing box.

Have a look at this repo as an example.
https://github.com/kikitux/virtualbox-ovf

Thanks
Alvaro.
