### ISSUE TITLE
Synced folder misconfiguration / misdocumentation

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9327]
The Vagrant docs claim that synced folders basically work out of the box, as long as either VirtualBox drivers, VMware drivers, or rsync are installed. In practice, DilOS and *BSD boxes fail unless `config.vm.synced_folder ".", "/vagrant", type: "rsync"` is explicitly specified in the right Vagrantfile.

**Comment by briancain** [comment]
Hey there - I'm going to go ahead and close this. I believe that this is still true today. Generally, the majority of Vagrant box guests you could use for VirtualBox and VMWare still work out of the box with the command specified. I couldn't find a place in the docs that claim this though, but if there's a place where we can be better about this statement feel free to open a PR and we can take a look at the improvement. Thanks!
