### ISSUE TITLE
Vagrant running Red Hat OpenShift incorrectly sorts interfaces for adapter assignment

### ISSUE THREAD

**Issue by wicksy** [hashicorp/vagrant#9329]
### Vagrant version

Version: 2.0.1

### Host operating system

OSX Yosemite 10.10.5

### Guest operating system

Centos 7 (vagrant box centos/7 (virtualbox, 1710.01))

### Vagrantfile

https://gist.github.com/wicksy/083ec7419562a6a1d485f3ae690ff59d#file-vagrantfile

### Debug output

https://gist.github.com/wicksy/083ec7419562a6a1d485f3ae690ff59d#file-ocptest-debug-issue-out

### Expected behavior

Adapter 1 should be configured as a NAT interface and Adapter 2 configured on a private (virtualbox hostonly) network with a fixed static IP. This is correctly performed when the box is initially started or when using `--no-provision`. Once the box is provisioned and OpenShift installed (and additional interfaces added) it breaks.

### Actual behavior

Adapter 1 is configured with Adapter 2 private network details (IP, etc) whilst the actual interface in virtualbox is setup as a NAT interface as per the Vagrantfile. Therefore SSH fails and the `up` runs indefinitely.

### Steps to reproduce

1. vagrant up with the Vagrantfile linked above
2. Install OpenShift (version used is latest release of Origin 3.7 but I don't think that matters)
3. vagrant halt
4. vagrant up (at this point the box fails to start completely and hangs configuring the interfaces (incorrectly)) 

### Additional notes

If you `vagrant up --no-provision` using the Vagrantfile to configure the interface files only but not complete the installation of OpenShift, the eth0 interface file is configured correctly (as is eth1):

```
[vagrant@ocptest ~]$ cat /etc/sysconfig/network-scripts/ifcfg-eth0
DEVICE="eth0"
BOOTPROTO="dhcp"
ONBOOT="yes"
TYPE="Ethernet"
PERSISTENT_DHCLIENT="yes"
[vagrant@ocptest ~]$
```

However, once OpenShift is installed and additional interfaces are used (docker0, tun0, br0 etc) when you `vagrant up` the eth0 interface file is configured incorrectly:

```
[vagrant@ocptest ~]$ cat /etc/sysconfig/network-scripts/ifcfg-eth0
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
NM_CONTROLLED=yes
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.10.10
NETMASK=255.255.255.0
DEVICE=eth0
PEERDNS=no
#VAGRANT-END
[vagrant@ocptest ~]$
```

Looking at the DEBUG output (full file available via gist above) it appears to be incorrectly sorting the interfaces so eth0 is handed back as the second adapter (presumably "2") which results in it getting the adapter 2 config in the Vagrantfile but since it's on a NAT network it never works (SSH never works)

```
➜  vagrant git:(master) ✗ grep 'DEBUG.*network_interfaces' ~/tmp/ocptest.debug.issue.out
DEBUG guest: Searching for cap: network_interfaces
DEBUG guest: Found cap: network_interfaces in linux
DEBUG network_interfaces: Unsorted list: ["eth0", "eth1", "docker0", "ovs-system", "tun0", "vxlan_sys_4789", "br0", "", "tun0", "br0", "eth0", "eth1", "lo", "docker0"]
DEBUG network_interfaces: Sorted list: ["", "eth1", "docker0", "eth0", "tun0", "vxlan_sys_4789", "br0"]
DEBUG network_interfaces: Ethernet preferred sorted list: ["eth1", "eth0", "", "docker0", "tun0", "vxlan_sys_4789", "br0"]
➜  vagrant git:(master) ✗
```

If you configure an identical box but do not provision to install OpenShift (just run a simple Ansible playbook to echo hello world) the adapter list whilst much simpler looks like it is sorted correctly and the box starts successfully with both eth0 and eth1 configured correctly:

```
➜  ~ grep 'DEBUG.*network_interfaces:' ~/tmp/wicksytest.debug.new
DEBUG network_interfaces: Unsorted list: ["eth0", "eth1", "", "eth0", "eth1", "lo"]
DEBUG network_interfaces: Sorted list: ["eth0", "eth1", ""]
DEBUG network_interfaces: Ethernet preferred sorted list: ["eth0", "eth1", ""]
➜  ~
```

### References

Could be related to https://github.com/hashicorp/vagrant/issues/7844

**Comment by jbonhag** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
