### ISSUE TITLE
Vagrant doesn't build with ruby 2.5

### ISSUE THREAD

**Issue by jsteel44** [hashicorp/vagrant#9332]
### Vagrant version
2.0.1

### Host operating system
Arch Linux

### Debug output
ERROR:  Error installing vagrant-2.0.1.gem:
	There are no versions of vagrant (= 2.0.1) compatible with your Ruby & RubyGems
	vagrant requires Ruby version < 2.5, ~> 2.2. The current ruby version is 2.5.0.

Please could you add support? Thank you

**Comment by chrisroberts** [comment]
@jsteel44 Looking into validating to hopefully include the constraint update in the next release.

**Comment by germanio** [comment]
It seems that OpenSuse Tumbleweed removed Ruby2.4 from their repos, so Vagrant is also removed or broken after the update.

**Comment by venekamp** [comment]
I have vagrant on openSUSE Tumbleweed, but cannot get vagrant-libvirt compiled as Ruby 2.4 is not present nor installable. Only Ruby 2.5 seems to be available from the default repos.

**Comment by venekamp** [comment]
Ah, the Ruby dependency seems to be fixed in vagrant 2.1.2 and openSUSE Tumbleweed just released 2.1.1. Either wait for 2.1.2 to become available, or find a source that suppliers 2.1.2.

**Comment by venekamp** [comment]
On closer inspections it seems that 2.0.2 already had the patch for relaxing the required Ruby version.
https://github.com/hashicorp/vagrant/commit/4bfb34a2e0f6541c6727651770ea67574248c15d
