### ISSUE TITLE
Currently unusuable on current Win10 set up.

### ISSUE THREAD

**Issue by Johnsonr1** [hashicorp/vagrant#9333]
I don't know if this is a bug or not, but it sure feels like one and I've not been unable to get help from anywhere else.  I have opened a discussion point in the google group - but so far no help.

### Vagrant version
Errog log is based on vagrant 2.0.0 but I have with all versions from 1.9.8 to 2.0.1

### Host operating system
x64 Win10

### Guest operating system
Laravel / Homestead - via Virtual Box - I assume on an Ubuntu VM ?

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.9.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON::parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if Vagrant.has_plugin?('vagrant-hostsupdater')
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    elsif Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.aliases = settings['sites'].map { |site| site['map'] }
    end
end
```

### Debug output
https://gist.github.com/Johnsonr1/801b858ccfb86bbf629e3bc3b00c8dc6

### Expected behavior
I expected a normal response to regular vagrant commands. e.g. vagrant up - spins up virtual machine.

### Actual behavior
No commands can be entered without generating the output seen here: 
 https://gist.github.com/Johnsonr1/93fd69f6155ed3d97e7271ac4232e879. 
I can run a successful command only if I first delete the .vagrant.d file.  However, once the first command has been executed the folder is recreated and the problem resumes.
I've been trying to get laravel / homestead set up but, in fact, I've not been able to start up any box.

### Steps to reproduce
No idea - this is the only behavior I've been able to see on my set up.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
There are a few older references around the web that seem to indicate a similar issue - but none of the suggested fixes have worked for me.
e.g:
https://stackoverflow.com/a/31121287/7390817
GH-5869
- GH-1234
- my own post: https://groups.google.com/forum/#!topic/vagrant-up/I8TbwThopO0
I have uninstalled / reinstalled both vagrant and virtual box multiple times - trying various VB builds post 5.1 and each Vagrant build from 1.9.8.

**Comment by chrisroberts** [comment]
@Johnsonr1 Your debug output truncated all the line endings. Can you upload a new debug gist that provides the full output? Thanks!

**Comment by Johnsonr1** [comment]
Hi, I've updated the same gist with a fresh dump - all lines look complete now.  In the meantime, I'd installed 2.0.1 again.  Exactly the same problem though.

**Comment by Johnsonr1** [comment]
Still flagged as awaiting reply but I don’t think I have the ability to change the flag.  I have replied though and , I’m seeing a few similar issues - any insights therefore ?

**Comment by chrisroberts** [comment]
@Johnsonr1 Thanks for updating the gist. Do you have Windows onedrive enabled on your user directory?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
