### ISSUE TITLE
rsync install step skipped in config.vm.guest :dragonflybsd boxes

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9335]
When I omit the `config.vm.guest` setting for my DragonflyBSD box, or even explicitly set `config.vm.guest = :dragonflybsd`, then `vagrant up` dies on `rsync not found`, completely skipping the rsync_install capability step.

As a workaround, I am setting `config.vm.guest = :freebsd` for my DragonflyBSD boxes.

I trawled through the DragonflyBSD guest plugin code, and at first blush it appears to correctly extend the FreeBSD guest plugin, which invokes the same correct command (sudo) `pkg install -y rsync`. No idea why this step is being skipped for DragonflyBSD guests.

Example boxes:

* b00ga/dragonfly50
* mcandre/dragonflybsd

I'm using Vagrant 2.0.1 from macOS 10.13 High Sierra.

**Comment by kikitux** [comment]
probably copy from freebsd and implement rsync install

https://github.com/hashicorp/vagrant/blob/9c299a2a357fcf87f356bb9d56e18a037a53d138/plugins/guests/freebsd/plugin.rb#L24-L27

**Comment by mcandre** [comment]
@kikitux Yeah, something along those lines.

The weird thing is, I see that the NetBSD guest inherits from the FreeBSD guest. I suppose somehow the inheritance of the `rsync_install` capability is not quite carrying over for some reason.

**Comment by kikitux** [comment]
@briancain can you share some intel on inheritance here? thanks

**Comment by briancain** [comment]
The `:freebsd` guest plugin actually inherits from the `:bsd` plugin.

https://github.com/hashicorp/vagrant/blob/master/plugins/guests/freebsd/plugin.rb#L9-L12

However, it looks like all the usual rsync guest capability functions are in the freebsd plugin. It'd be good to see a debug log where it skips installation to see if it finds the rsync capabilities or not.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
