### ISSUE TITLE
rsync subcommands not listed in vagrant -h

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9336]
`vagrant -h` / `vagrant --help` omits the `rsync` and `rsync-auto` subcommands, making it difficult for users to discover these.

**Comment by kikitux** [comment]
They are hidden by choice:
https://www.vagrantup.com/docs/cli/non-primary.html

**Comment by mcandre** [comment]
That's stupid. Who is to decide what is and is not "useful" for a beginner? Why not hide all commands in such a document? By hiding these commands, you actually make it even MORE difficult for a beginner to reference these commands.

**Comment by kikitux** [comment]
We can review based on positive constructive feedback, but there are better ways to express ideas that go into attack mode.
