### ISSUE TITLE
'vagrant up' fails attempting to forward TCP port(s); VMware Workstation 14, Windows 10 Pro 

### ISSUE THREAD

**Issue by WheelmanK** [hashicorp/vagrant#9337]
### Vagrant version
2.0.1

Installed vagrant plugins:
vagrant-vmware-workstation 5.0.4
vagrant-ignition 0.0.3
vagrant-share 1.1.9

### Host operating system
Windows 10 Pro 1709, build 16299.125 (64 bit)

### VMware Version
Workstation Pro 14.1.0

### Guest operating system
ALL, tested with the following boxes:
hashicorp/precise64 - Ubuntu 12.04 LTS 64-bit
StefanScherer/windows_2016_docker - Windows Server 2016 - 64-bit
symbols/windows_server_1709_docker - Windows Server 2016, version 1709 - 64-bit

### Vagrantfile - This is the Vagrantfile for hashicorp/precise64
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
end
```

### Vagrantfile - This is the Vagrantfile for StefanScherer/windows_2016_docker and symbols/windows_server_1709_docker
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.8.4"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.communicator = "winrm"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  home = ENV['HOME'].gsub('\\', '/')
  config.vm.synced_folder home, home

  config.vm.define "2016" do |cfg|
    cfg.vm.box     = "StefanScherer/windows_2016_docker"
    cfg.vm.box_version = "2017.12.14"
    cfg.vm.provision "shell", path: "scripts/create-machine.ps1", args: "-machineHome #{home} -machineName 2016"
  end

  config.vm.define "1709", autostart: false do |cfg|
    cfg.vm.box     = "symbols/windows_server_1709_docker"
    cfg.vm.provision "shell", path: "scripts/create-machine.ps1", args: "-machineHome #{home} -machineName 1709"
  end
  
  ["vmware_fusion", "vmware_workstation"].each do |provider|
    config.vm.provider provider do |v, override|
      v.gui = false
      v.memory = 2048
      v.cpus = 2
      v.enable_vmrun_ip_lookup = false
      v.linked_clone = true
      v.vmx["vhv.enable"] = "TRUE"
    end
  end
end
```

### Debug output
Gist file containing --debug output produced by vagrant up of hashicorp/precise64
https://gist.github.com/WheelmanK/30d3778c8093f511a963040eb6a59570

### Expected behavior
The VM should spin up 

### Actual behavior
Vagrant attempts to spin up the VM(s) but at the point where host port 2222 is forwarded to guest port 22 (SSH) an access denied error is encountered and the VM is shutdown and deleted.

### Steps to reproduce
vagrant up in any folder on this particular virtualization test machine.

The really strange aspect of this bug is I have 2 essentially identical hardware platforms I use as a virtualization lab.  Both machines are Dell Optiplex 7010s each with 16Gb Ram, 1.5TB drive space, VMware Workstation Pro 14.1.0, Windows 10 Pro 1709 (same update level). 
Vagrant works flawlessly on one and does not work on the other.  
I've reinstalled VMware workstation, the vagrant vmware plugin and vagrant on the machine that doesn't work.  I was able to run the hashicorp/precise64 box once after the VMware workstation reinstall but since then I get the access denied error when vagrant tries to define the port forward of 2222<->22.

I've examined the contents of c:\programdata\vmware\vmnetnat.conf and found left over bits that have not been cleaned up by vagrant.  I deleted the offending cruft to no effect, spin up of the VMs still fails at the point of trying to forward the SSH port.
The c:\programdata\vmware\vmnetnat.conf file on the machine that works also has the cruft in it, which I've deleted and left alone at various times with seemingly no affect. That machine simply keeps working.

Neither of these machines has ever had Hyper-V or VirtualBox installed.
Both have identical versions of docker, docker-compose, docker-machine and docker-machine-vmwareworkstation installed.

### References
Unknown.  I believe I ran across a similar issue specific to using vagrant with VMware Fusion but cannot find it again.

**Comment by dbishop** [comment]
Maybe related to my issue in Fusion: https://github.com/hashicorp/vagrant/issues/9287

**Comment by WheelmanK** [comment]
Interesting theory except that Windows path and file names are case insensitive, at least as far as the OS is concerned.  I'll try and test whether case makes any difference in the behavior of Vagrant and update this post.

**Comment by dbishop** [comment]
Yeah, in my case (no pun intended), the casing mismatch happens in Vagrant's code (well, the vmware plugin).  The macOS filesystem is case-insensitive, case-preserving, but as far as I can tell, the case-handling of the filesystem is irrelevant because the comparison is happening in the vagrant code, not inside filesystem code of the OS.

I'm still not positive they're the same root cause, but it'll be good for the vagrant vmware plugin devs to keep both these bugs in mind, together, as they investigate each.

**Comment by dbishop** [comment]
Another way to look at it is that whatever _generated_ the lowercase path string that failed comparison in the vagrant vmware plugin code on macOS could also generate a lowercase path string on Windows, because the macOS filesystem is case-preserving and any path coming from the filesystem would have been uppercase.  So if there's random case-mangling of paths, it could happen for Windows OS/filesystem too.

**Comment by dbishop** [comment]
@briancain can you also add tags (labels?) to https://github.com/hashicorp/vagrant/issues/9287 ?  It's also networking & provider/vmware.  There's also an associated Zendesk ticket (5883).

Thanks!

**Comment by WheelmanK** [comment]
With input from Stefan in the thread related to issue #9348 I've been able to resolve my problem so am closing this issue.
