### ISSUE TITLE
apt fails with proxyconf and apt proxy pointing to address on additional network interface due to wrong build steps order

### ISSUE THREAD

**Issue by philippkunz** [hashicorp/vagrant#9340]
specifying an (additional) network adapter for a virtualbox internal network and VAGRANT_APT_HTTP_PROXY to use it causes apt-get to fail at an early stage because the network has not been brought up.

the console output without an apt proxy reveals that also there apt-get is run before "Configuring and enabling network interfaces...". So it works only if VAGRANT_APT_HTTP_PROXY points to an address reachable on the first / default network adapter.

it could also relate to the base box, however i suspect it more to relate to some vagrant plugin such as linux / debian / virtualbox guest. The base box debain/stretch64 comes with only one network adapter configured to automatically start up at boot but there are the mentioned vagrant plugins i guess that should take care of starting those additional network adapters created according to the Vagrantfile.

i guess that the plugins seem to be running in a wrong order. installation of virtual guest additions for virtualbox should probably only take place after the network has been fully configured.

### Vagrant version
Vagrant 1.9.3

### Host operating system
Debian 8 Jessie

### Guest operating system
Debian 9 Stretch

### Vagrantfile
```ruby
config.vm.network "private_network", ip: "192.168.1.3", netmask: "24", virtualbox__intnet: "thenetname", nic_type: "Am79C973"
```

### Debug output
https://gist.github.com/philippkunz/4d1c2e514f6f086bce040798ffa194e6

### Expected behavior
the following build steps in the following order
* ==> default: Machine booted and ready!
* ==> default: Configuring proxy for Apt...
* ==> default: Configuring and enabling network interfaces...
* calls to apt-get no earlier than here such as ==> default: Installing rsync to the VM...

### Actual behavior
apt-get fails at an early stage due to the network interface not being up yet.

### Steps to reproduce
1. create another vm with an apt-cacher on the same virtualbox internal network
2. export VAGRANT_APT_HTTP_PROXY="http://192.168.1.2:80/" which is on the virtualbox internal network
3. vagrant up

**Comment by chrisroberts** [comment]
Hi there. The issue you are encountering is not caused by vagrant but by the guest box you are using. It is likely that there is a daily cron job configured which is running an apt-get update on startup. This is not something that vagrant can prevent and would need to be adjusted within the box itself. Cheers!

**Comment by philippkunz** [comment]
hi @chrisroberts, thank you for your answer.

vagrant (including its plugins) interacts with the guest at [==> default: Configuring proxy for Apt...](https://gist.github.com/philippkunz/4d1c2e514f6f086bce040798ffa194e6#file-build-output-wrong-txt-L29) and would therefore in my opinion have a chance to set also up the network interfaces before the first apt-get.

the apt-get output that fails in my reported scenario i guess comes from the vbguest plugin: [debian.rb](https://github.com/dotless-de/vagrant-vbguest/blob/master/lib/vagrant-vbguest/installers/debian.rb#L27).

therefore so far, i don't think the apt-get in question is triggered by the guest box or one of its cron jobs.

the relevant piece of code to configure the networking in the guest vm i guess is probably  [configure_networks.rb](https://github.com/hashicorp/vagrant/blob/master/plugins/guests/debian/cap/configure_networks.rb). also interesting in this case is probably vagrant-proxyconf (e.g. [apt_proxy.rb](https://github.com/tmatilai/vagrant-proxyconf/blob/master/lib/vagrant-proxyconf/config/apt_proxy.rb)).

as of now, i think the vagrant plugins and all their actions within the guest are not executed in a suitable order for the scenario reported. i think that apt-get as is issued by the vbguest plugin should only occur after the debian guest plugin has configured the network interfaces and also after proxyconf.

i wasn't really aware i reported against vagrant core specifically rather than considering also the plugins when i initially created this issue. but now i have no clue where to specifically assign it.
