### ISSUE TITLE
Enhancement: Configurable CLI Aliases

### ISSUE THREAD

**Issue by zachflower** [hashicorp/vagrant#9357]
I wanted to open a discussion around the possibility of adding user-configurable command alias functionality to Vagrant.

While I understand that the concept of _built-in_ aliases have been suggested (and I believe rightly rejected) in the past (i.e. aliasing `start` to `up` and `stop` to `halt`), what I'm proposing is something that is entirely user-configurable and managed in the same vein as functionality found in [Git](https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases), [Bash](http://tldp.org/LDP/abs/html/aliases.html), and even [Vim](http://vimdoc.sourceforge.net/htmldoc/usr_40.html#40.2).

Because this is a new paradigm in terms of command parsing and execution, I thought it prudent to propose the enhancement here rather than opening up a PR without prior discussion.

## Benefit

The benefit to user-configurable aliases within Vagrant (as opposed to shell-based aliases) is that it provides a more contextual outlet for tuning Vagrant in a way that isn't operating system or shell dependent (I personally use Vagrant on both Windows and macOS machines). This mindset carries through from Git aliases, for example, which can generally be considered OS-independent in most basic use-cases.

## Example

The way I would imagine this to work would be an aliases file (for the sake of argument, let's call it `~/.vagrant.d/aliases`, although if I understand correctly that directory may be relatively ephemeral, so it might be a bad choice). For example:

```
# basic command-level aliases
start = up
stop = halt
die = halt -f
restart-nginx = ssh -c "sudo service nginx restart"

# advanced aliases
eradicate = !vagrant destroy && rm -rf .vagrant
```

Using the defined aliases above, a user would then be able to execute `vagrant start`, `vagrant stop`, etc. as they would any other command. The basic command-level aliases would work similarly to Git aliases, with the assumption being that they provide a mechanism for simplifying more complex commands (see the `restart-nginx` alias).

The advanced aliases would also take a cue from Git. When prefixed with a `!`, rather than aliasing one command to another, a shell command would then be executed. As an example, the `vagrant eradicate` command would first destroy the defined box, and then remove the `.vagrant` directory.

**Comment by chrisroberts** [comment]
Hi there. Thank you for this well thought out and thorough feature request. While I can see the value this may add, I'm also looking at the added overhead this will introduce in terms of long term maintenance and testing. My general response for aliasing requests is simply to redirect to existing implementations provided by the shell, as this introduces nothing new within Vagrant itself.

That said, I do see the value in this request, especially as it has been realized in other tools that use it. The priority of this feature is not high enough that we would have any time to commit to it in the near future, however if you are willing to provide the implementation we would be happy to work through the details as they arise. 

Path location that you bring up is a pretty small thing and the `~/.vagrant.d` directory is a good default place. Customizable via environment variable would be ideal with the `VAGRANT_HOME` fallback as the default.

Cheers!

**Comment by zachflower** [comment]
Thanks for the feedback on this @chrisroberts, sorry for the delayed response but I went heads down on it as soon as I had an opportunity.

Any feedback you have on my initial crack (PR #9504) would be hugely appreciated!

**Comment by chrisroberts** [comment]
@zachflower awesome! i'm going to close this issue now and just leave the PR open to track this. cheers!
