### ISSUE TITLE
homestead hangs on booting vm

### ISSUE THREAD

**Issue by iwasherefirst2** [hashicorp/vagrant#9360]
### Vagrant version
2.0.1

### Host operating system
Ubuntu

### Guest operating system
Ubuntu

### Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.9.0'



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON.parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false
    end

    if defined? VagrantPlugins::HostsUpdater
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    end
end
```

### Debug output
>Provide a link to a GitHub Gist containing the complete debug output:
>https://www.vagrantup.com/docs/other/debugging.html. The debug output should
>be very long. Do NOT paste the debug output in the issue, just paste the
>link to the Gist.

I can't copy the debug output from terminal because my PC freezes. (BTW: the mentioned URL is expired)

### Expected behavior
The `vagrant up` command should boot the VM

### Actual behavior
VM is not booted and PC freezes so I have to restart it

### Steps to reproduce
1.  Install new Ubuntu 16.04.3
2.  Install Virtualbox version 5.0.40_Ubuntur115130)
3.  Install Vagrant 2.0.1
4.  Install Homestead v7.0.1
5. Remove SSH Key in .yaml file
6. Enter `vagrant up --debug`

### References
- #7710 This issue was closed because a user comment solved the issue. However I can't find the user comment mentioned in [https://github.com/hashicorp/vagrant/issues/7710#issuecomment-251242778](https://github.com/hashicorp/vagrant/issues/7710#issuecomment-251242778)
- I have asked this question on AskUbuntu as well: https://askubuntu.com/questions/995654/vagrant-up-fails-on-booting-vm

Here is a debug picture that I have taken with my camera, since the computer hangs:
![image](https://user-images.githubusercontent.com/1765602/34869157-5167e680-f786-11e7-85af-e756773a0844.png)

**Comment by iwasherefirst2** [comment]
Whoups... the workaround does not seem to work...

**Comment by iwasherefirst2** [comment]
I was able to get an helpful error message without freezing my PC when entering `vagrant reload`:

```
adam@adam-HP-350-G2:~/Programs/Homestead$ vagrant reload
The provider 'virtualbox' that was requested to back the machine
'homestead-7' is reporting that it isn't usable on this system. The
reason is shown below:

VirtualBox is complaining that the installation is incomplete. Please
run `VBoxManage --version` to see the error message which should contain
instructions on how to fix this error.
adam@adam-HP-350-G2:~/Programs/Homestead$ VBoxManage --version
WARNING: The character device /dev/vboxdrv does not exist.
	 Please install the virtualbox-dkms package and the appropriate
	 headers, most likely linux-headers-generic.

	 You will not be able to start VMs until this problem is fixed.
5.0.40_Ubuntur115130
```
Solved the issue with the following commands

```
sudo apt-get install virtualbox-dkms
sudo apt-get install linux-headers-generic
sudo dpkg-reconfigure virtualbox-dkms
sudo dpkg-reconfigure virtualbox
```

**Comment by iwasherefirst2** [comment]
Okay so the above command make it work again - but I have to do it each time when I restart my computer. Any advice here?

**Comment by eugeniregi** [comment]
Hello!
I have the same Issue, but the above commands not work for me. It still freezes.

I have vagrant 2.0.1
and ubuntu 16.04 as a host

I tried to reinstall virtualbox and homestead but get the same behavior.

Anyone know how to fix this?
Thanks

**Comment by iwasherefirst2** [comment]
I reinstalled my computer, installed Vagrant 2.0.1, virtualbox, virtualbox-dkms and homestead, but it still freezes on "Booting VM".  The trick that I used in my previous comment is also not working for me anymore. I have currently no idea what is happening. 

Buts interesting that I can reproduce the problem on my HP 350 G2 laptop with a fresh Ubuntu installation.

**Comment by tier5** [comment]
Hey @iwasherefirst2  nad @eugeniregi  I am also getting this problem for last 3-4 days in one of my workstation and didn't look for any solution until today when I upgraded second workstation's kernel. I think this problem is causing of new Ubuntu kernel `4.13.0-26-generic`. I have booted to previous kernel `4.10.0-42-generic` and tried `vagrant up` and it worked perfectly for both of my workstations. It is a temporary fix not a permanent solution though.

**Comment by iwasherefirst2** [comment]
@tier5 THANK YOU SO MUCH :D!!!!!!!!!!!!!!!!!!!!!!

Its working with the old kernel. However I had to the following:

1. The GRUB menu did not show up when I was pressing the SHIFT key. Instead I had to change the /etc/default/grub the line `GRUB_TIMEOUT=0` to `GRUB_TIMEOUT=`.

2. After booting with the old kernel, vagrant up created the following error message:

> 
> 
> The VirtualBox VM was created with a user that doesn't match the
> current user running Vagrant. VirtualBox requires that the same user
> be used to manage the VM that was created. Please re-run Vagrant with
> that user. This is not a Vagrant issue.
> 
> The UID used to create the VM was: 
> Your UID is: 1000

So I had to add my UID `1000` to the file 

`Homestead/.vagrant/machines/homestead-7/virtualbox/creator_uid `

I also had to enter in terminal:

> $ vboxmanage list vms
> "my-vm" {c700b8b6-b766-4638-871b-736b44b7db18}

and copy that number `c700b8b6-b766-4638-871b-736b44b7db18` in the file `Homestead/.vagrant/machines/homestead-7/virtualbox/id` after that, vagrant up was working again.

Thank you for that hint! I was just about to buy another laptop..

**Comment by briancain** [comment]
Going to go ahead and close this since it looks resolved! 🎉

**Comment by iwasherefirst2** [comment]
Actually its not solved yet, but the bug has been reported had its related to the Ubuntu Kernel and not to vagrant: https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1736116

**Comment by hmorv** [comment]
Hi,
I've been able to run again homestead after upgrading my Ubuntu kernel to 4.13.0.32 (Ubuntu Xenial) just updating Virtualbox to 5.2.6
This is what I've done:
1.- Add oracle repository :

`sudo add-apt-repository "deb http://download.virtualbox.org/virtualbox/debian xenial contrib"`

2.- Add GPG keys for repository :

```
wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
```
3) Install VirtualBox 5.2

`sudo apt update && sudo apt install virtualbox-5.2`

In my case I had errors while trying to _vagrant up_:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.
Command: ["startvm", "12cec1a1-7453-415b-9467-4db112681a96", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'homestead-7' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```
So I had to remove _virtualbox-dkms_ package and run /sbin/vboxconfig:

```
sudo apt remove --purge virtualbox-dkms
sudo  /sbin/vboxconfig
```
Now VM is up and running again as always did... hope it helps to someone.
