### ISSUE TITLE
vagrant package:  won't fork/clone/duplicate/generate a similar vagrant-up-able box/image.

### ISSUE THREAD

**Issue by ribamar-santarosa** [hashicorp/vagrant#9362]
### Description

`vagrant package`  won't fork/clone/duplicate/generate a similar vagrant-up-able box/image.

### Vagrant version
````
vagrant -v
Vagrant 2.0.1
````

### Host operating system

````
lsb_release  -a
Distributor ID: Debian
Description:    Debian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch
````

### Guest operating system

````
vagrant ssh -c 'cat /etc/debian_version'
9.1
````

### Vagrantfile

fill vagrant image here:
````
Vagrant.configure("2") do |config|
  config.vm.box = "mynewbox"
end
````

### Debug output

````
vagrant package --output mynew.box
# Total bytes written: 1042032640 (994MiB, 26MiB/s)
# ==> default: Box created
# ==> default: You can now add the box:
# ==> default: vagrant box add mynew.box --name any_comfortable_name
````

Full output of `vagrant up` at:
https://gist.github.com/ribamar-santarosa/7b98edacaada8fc1892140a2aabca0e1 

Full output of `ssh` to the virtual machine at: 
https://gist.github.com/ribamar-santarosa/964a8feda145c3ab9602a6dad0aa4888

### Expected behavior

After running:
````
vagrant package --output mynew.box
````
I would expect the command bellow to finish someday: 
````
vagrant init mynewbox  && vagrant up --provider=libvirt 
````

### Actual behavior
````
vagrant init mynewbox  && vagrant up --provider=libvirt 
````
Hangs forever (on `up` part).

### Steps to reproduce
````
# Install vagrant. Check https://github.com/hashicorp/vagrant/issues/9285 / https://github.com/ribamar-santarosa/champselysees/tree/master/vagrant-debian-stretch

# run any image:

vagrant init debian/stretch64 
vagrant up --provider=libvirt
vagrant ssh -c pwd
vagrant ssh -c 'cat /etc/debian_version'
# 9.1

# clone/fork/duplicate that image:

vagrant package --output mynew.box
vagrant box add mynewbox mynew.box
# ==> default: Box created
# ==> default: You can now add the box:
# ==> default: vagrant box add mynew.box --name any_comfortable_name
vagrant box list
# ...
# mynewbox         (libvirt, 0)

vagrant destroy default
rm -rf .vagrant Vagrantfile

# try to use the new image:
vagrant init mynewbox 
VAGRANT_LOG=debug
vagrant up --provider=libvirt # full output at: https://gist.github.com/ribamar-santarosa/7b98edacaada8fc1892140a2aabca0e1 
# ...
# DEBUG wait_till_up: Searching for IP for MAC address: 52:54:00:19:76:79
# ....
# ==> default: Waiting for domain to get an IP address...
# ...
#  INFO wait_till_up: Got IP address 192.168.121.65
# ...
#  INFO wait_till_up: Time for getting IP: 15.072947263717651
# ...
#  INFO ssh: SSH not up: #<Vagrant::Errors::SSHConnectionReset: SSH connection was reset! This usually happens when the machine is
# ...
# DEBUG ssh: == Net-SSH connection debug-level log END ==
#  INFO ssh: SSH not up: #<Vagrant::Errors::SSHConnectionReset: SSH connection was reset! This usually happens when the machine is
# ...
# taking too long to reboot. First, try reloading your machine with
# ...
````

### Further Attempts:

Will update this section as things go on/people comment and I try.

#### 1 - Reload: Failed : Same ssh-forever-waiting error.
````
vagrant reload # ==> leads same error -- wait forever for ssh
````

#### 2 - manual ssh: Failed: Same ssh-forever-waiting error.

While `vagrant up` is running:
````
vagrant ssh -c pwd # no output (not even error output)
````

#### 3  - host-passsthrough: Failed: Same ssh-forever-waiting error.

Added to `Vagrantfile`:
````
  config.vm.provider "libvirt" do |lv|
      lv.cpu_mode = 'host-passthrough'
  end
````

#### 4 - manual non-vagrant ssh: Failed: Connection Reset by peer

While `vagrant up` is running:
````
sudo nmap 192.168.121.65 
# Starting Nmap 7.40 ( https://nmap.org ) at 2018-01-12 11:18 CET
# Nmap scan report for 192.168.121.65
# Host is up (0.000036s latency).
# Not shown: 998 closed ports
# PORT    STATE SERVICE
# 22/tcp  open  ssh
# 111/tcp open  rpcbind
# MAC Address: 52:54:00:19:76:79 (QEMU virtual NIC)


ssh -v -v -v -v root@192.168.121.65 # full output at: https://gist.github.com/ribamar-santarosa/964a8feda145c3ab9602a6dad0aa4888
# ...
# debug2: fd 3 setting O_NONBLOCK
# debug1: Authenticating to 192.168.121.65:22 as 'root'
# debug3: hostkeys_foreach: reading file "/home/ribamar/.ssh/known_hosts"
# debug3: send packet: type 20
# debug1: SSH2_MSG_KEXINIT sent
# Connection reset by 192.168.121.65 port 22
````

### References

These issues look somehow related, but none really matched/led to a solution:
https://github.com/hashicorp/vagrant/issues/8157
https://github.com/hashicorp/vagrant/issues/8204
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/510
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/560
https://bugzilla.redhat.com/show_bug.cgi?id=1283989
https://github.com/cloudfoundry/bosh-lite/issues/355
https://github.com/mitchellh/vagrant-aws/issues/3

I also openend an issue here:
https://github.com/vagrant-libvirt/vagrant-libvirt/issues/851

**Comment by karthikprabhu17** [comment]
I am facing the same issue with libvirt. Unable to ssh into the box

**Comment by chrisroberts** [comment]
Hi there. The `package` command is provider specific. In this case, the provider is a third party plugin (vagrant-libvirt) and not a core Vagrant issue. You can report the issue to the vagrant-libvirt project here: https://github.com/vagrant-libvirt/vagrant-libvirt

Cheers!
