### ISSUE TITLE
SSH failure with password

### ISSUE THREAD

**Issue by ultimateyy** [hashicorp/vagrant#9373]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.0

### Host operating system
ubuntu 16/04 LTS

### Guest operating system
ubuntu/xenial

### Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.username='root'
  config.ssh.password='root'
  config.ssh.insert_key = 'false'
  config.proxy.http = "xxxx"
  config.proxy.https = "xxx"
  config.vm.provision "shell", path:"post-create-base-image.sh"
  config.vm.provider "virtualbox" do |vb|
      vb.customize ['modifyvm', :id, '--uartmode1', 'disconnected']
      vb.customize ['setextradata', :id, 'VBoxInternal/Devices/pcbios/0/Config/DmiBIOSVersion', 'BIOS.VER.B10.MAJORREV.MINORREV']
  end
end
```

### Debug output
[https://gist.github.com/ultimateyy/7571ef8301731a9b4b59835af37f2768](Gist)

### Expected behavior
ssh login with defined username and password

### Actual behavior
Remote connection disconnect
Authentication failure

### Steps to reproduce
1.
    Run vagrant up with the vagrantfile reproduced above.

**Comment by ultimateyy** [comment]
Able to login with username and password defined in Vagrantfile while in GUI mode

**Comment by chrisroberts** [comment]
This is likely due to the configuration of the sshd on that box. Configuration for the ssh daemon generally disables login for the root user, which is why you are able to login via the GUI but not with `ssh`. If you want to be able to login with the root user using ssh, you will need to update the sshd_config file on the guest.

Cheers!
