### ISSUE TITLE
Can't log in to box after setting port forwarding on Windows

### ISSUE THREAD

**Issue by shukriadams** [hashicorp/vagrant#9374]
### Vagrant version
1.9.8

### Host operating system
Windows 10 Pro

### Guest operating system
Ubuntu 16.04

### Vagrantfile
Vagrant.configure("2") do |config|
  
    config.vm.box = "ubuntu/xenial64"
    config.vm.synced_folder "./..", "/vagrant" 
    config.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 2048]
    end

    config.ssh.private_key_path = "~/.ssh/id_rsa"
    #config.ssh.private_key_path = "C:\\Users\\ME\\.ssh\\id_rsa"

    config.ssh.forward_agent = true
end

### Debug output
Host default
  HostName 127.0.0.1
  User ubuntu
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile C:/myproject/vagrant/.vagrant/machines/default/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes

### Expected behavior
I should be able to log into box.

### Actual behavior
Login to box fails

### Steps to reproduce
1. vagrant up
2. vagrant ssh

I'm trying to get port forwarding to work on Window+Ubuntu. I know forwarding works on my Windows host, as I can ssh to a remote machine and "ssh -T git@github.com" works using my local keys.

If I set config.ssh.private_key_path to point to my local id_rsa file, I cannot log into my box, vagrant keeps asking for a password. I'm sure it's finding the key file because if I set the path to something I know doesn't exist, Vagrant up fails and tells me the key path is invalid.

Running vagrant ssh-config with config.ssh.private_key_path set returns

    Host default
      HostName 127.0.0.1
      User ubuntu
      Port 2222
      UserKnownHostsFile /dev/null
      StrictHostKeyChecking no
      PasswordAuthentication no
      IdentitiesOnly yes
      LogLevel FATAL
      ForwardAgent yes    

IdentityFile is gone, is that normal?

If I _don't_ set config.ssh.private_key_path, I can log into my box, but then port-forwarding doesn't work. What should my Vagrantfile look like so, on Windows,  I can both login to and then portforward from my guest? Thanks.

**Comment by chrisroberts** [comment]
Hi there. Would you please provide a gist of the full debug output for starting the Vagrant guest and port forwarding fails to properly setup. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by shukriadams** [comment]
Hi Chris, sorry, lost track of this issue, but it was also a lot of work to set up SSH agent forwarding proper on Windows. Opted for key copying to the guest instead and moved on.
