### ISSUE TITLE
VMware Workstation plugin 5.0 requires /dev/tty during installation

### ISSUE THREAD

**Issue by StefanScherer** [hashicorp/vagrant#9375]
### Vagrant version
Vagrant 2.0.1

### Host operating system
Ubuntu 16.04.2 LTS (Xenial Xerus)
also on 16.04.3

### Guest operating system
Does not apply as vagrant plugin install does not work.

### Vagrantfile

This Vagrantfile helps building a test environment on my Mac to show you the problem within a Linux Ubuntu installation. It installs Vagrant 2.0.1 in Ubuntu, installs VMware Workstation and then tries to install the vagrant-vmware-workstation plugin through the provision script which does not have stdin or /dev/tty.

We are working on a Packer + Vagrant build agent in our CI pipeline and we have to install Vagrant + the VMware plugin with Packer. That's why we want to run the plugin installation without stdin/tty. The problem can also be reproduced with this Vagrantfile.

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "tknerr/ubuntu1604-desktop"

  ["vmware_fusion", "vmware_workstation"].each do |provider|
    config.vm.provider provider do |v, override|
      v.gui = true
      v.memory = 4096
      v.cpus = 2
      v.enable_vmrun_ip_lookup = false
      v.linked_clone = true
      v.vmx["vhv.enable"] = "TRUE"
      v.ssh_info_public = true
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    if [ ! -f .done ]; then
      apt-get update
      wget --no-verbose https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.deb
      sudo dpkg -i vagrant*.deb
      wget --no-verbose http://download3.vmware.com/software/wkst/file/VMware-Workstation-Full-14.1.1-7528167.x86_64.bundle
      sudo sh ./VMware-Workstation-Full*.bundle --console --required --eulas-agreed
      touch .done
    fi
    vagrant plugin install vagrant-vmware-workstation --plugin-version 5.0.4
  SHELL
end
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://gist.github.com/StefanScherer/2a972d6edef90e40916f45a2b0a67864
This is the debug log of the "vagrant plugin install vagrant-vmware-workstation --plugin-version 5.0.4" command inside the Linux VM.

### Expected behavior
Vagrant should install the vagrant-vmware-workstation plugin 5.0.4 even in a packer or vagrant provision script.

### Actual behavior
Installation of the Vagrant plugin aborts as it seems to require /dev/tty

```
Error setting up CLI: open /dev/tty: no such device or address*** extconf.rb failed ***
```

### Steps to reproduce
1. Change the provided `Vagrantfile` to have enable debug log
```
    VAGRANT_LOG=debug vagrant plugin install vagrant-vmware-workstation --plugin-version 5.0.4
```
2. `vagrant up`
3. if plugin could not intalled you can use `vagrant provision` to retry the plugin installation.

### Further information

I've cross checked with an older version of the plugin and the 4.0.24 works very well:

```
$ vagrant provision
==> default: Running provisioner: shell...
    default: Running: inline script
    default: Installing the 'vagrant-vmware-workstation --version '4.0.24'' plugin. This can take a few minutes...
    default: Installed the plugin 'vagrant-vmware-workstation (4.0.24)'!
```

**Comment by chrisroberts** [comment]
Hi there,

The `/dev/tty` requirement has been removed (along with the `sudo` portion entirely) in the new VMware plugin that has been released. You can read more about it here:

https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

Cheers!
