### ISSUE TITLE
VMWare Vagrant Plugin Crashes Host

### ISSUE THREAD

**Issue by jperanson** [hashicorp/vagrant#9376]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
2.0.1
Vagrant VM Ware Plugin (licensed)
PhpStorm 2017.3.2
 

### Host operating system
Windows 7 Pro (powershell 3.0)

### Guest operating system
CentOS 6

### Vagrantfile

```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-6.8"
  config.vm.box_check_update = false

  config.vm.define "Huron-Core" do |node|
    node.vm.provider "vmware" do |vb|
        vb.name = "Huron-Core"
        vb.memory = "1024"
        vb.cpus = 2
    end

    node.vm.network "private_network", ip: "192.168.134.121"
    node.vm.hostname = "huron-core"

    node.vm.network :forwarded_port, guest: 22, host: 1234, auto_correct: true

    node.vm.provision "shell", inline: <<-SHELL
        mkdir -p \
            /var/www/local.natmatch.org \
            /root/db/

        ln -s /vagrant/src/Huron-Core/Huron /var/www/local.natmatch.org/Huron
        ln -s /vagrant/src/Huron-Core/HuronCommon/seed /root/db/seed
        ln -s /vagrant/src/Huron-Core/reconcile /var/www/local.natmatch.org/reconcile
        ln -s /vagrant/src/Huron-Core/configs /var/www/local.natmatch.org/configs
        ln -s /vagrant/src/Huron-Core/api.natmatch.vm.local /var/www/api.natmatch.vm.local

        /bin/sh /vagrant/.setup/Huron-Core/install.sh
    SHELL
  end

  config.vm.define "Huron-Admin" do |node|
    node.vm.network "private_network", ip: "192.168.134.130"
    node.vm.hostname = "huron-admin"

    node.vm.network :forwarded_port, guest: 22, host: 1235, auto_correct: true

    node.vm.provision "shell", inline: <<-SHELL
        mkdir -p /var/www/local.admin.matchprogram.org
        ln -s /vagrant/src/Huron-Admin/AdminHuron /var/www/local.admin.matchprogram.org/AdminHuron
        ln -s /vagrant/src/Huron-Admin/configs /var/www/local.admin.matchprogram.org/configs

        /bin/sh /vagrant/.setup/Huron-Admin/install.sh
    SHELL
  end

end
```

### Debug output
"Starting process: ["C:\\Program Files (x86)\\VMWare\\VM Workstation/vmrun.exe:, "start", ....]
INFO subprocess: Command not in installer, restoring original environment
DEBUG: Selection on IO

### Expected behavior
VM should start up

### Actual behavior
Windows host computer crashes. Mouse cannot move, windows time does not increment. Only a hard reset can restore normal function

### Steps to reproduce
1. Vagrant up

**Comment by chrisroberts** [comment]
Hi there. Would you please provide a gist of the full debug output. Thanks!

**Comment by jperanson** [comment]
Not sure how to do that as the machine fails where the only available remedy is a hard reboot. Can't move the mouse, copy/paste, write a file, etc. Any suggestions for getting you some useful info?

**Comment by chrisroberts** [comment]
@jperanson Even a picture of the terminal with the debug output once it has halted would be helpful. You can email it to me if you'd like :smiley:

**Comment by chrisroberts** [comment]
Hi there,

There is a new VMware plugin now available. You can read more about it here:

https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

If you are still experiencing issues after upgrading, please open a new issue and I will be happy to investigate.

Cheers!
