### ISSUE TITLE
Vagrant freezes in  vagrant up (windows host)

### ISSUE THREAD

**Issue by basos9** [hashicorp/vagrant#9391]
Hello,
I have tried to do the simplest initialization for vagrant on Windows 7
```
> vagrant init
> vagrant up
```
but is stucks there.
Tried with vagrant 2.0.1 and vagrant 1.9.8
Tried with admin cmd prompt.
Tried with disabled Antivirus.
Tried on a second windows 7 machine with the same result.

### Vagrant version
Vagrant 2.0.1 and Vagrant 1.9.8

### Host operating system
HOST: windows 7 x64
OS Version:                6.1.7601 Service Pack 1 Build 7601

### Guest operating system
precise64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
end
```

### Debug output
https://gist.github.com/basos9/fbf996be0ff7a89dada3e8bb374a4eb1

### Expected behavior
Vagrant virtual environment to be up and running.

### Actual behavior
Command prompt freezes at vagrant up. System resources (CPU, Network) are idling. Application is frozen.

### Steps to reproduce
1. Download vagrant 2.0.1 for windows x64. Install on Windows 7 x64
2. Open a command prompt in a working directory. 
3. vagrant init
4. vagrant up

**Comment by mmodler** [comment]
We had the same problem. Upgrading powershell as mentioned here #8783 helped. We upgraded pwershell 2.0 to 4.0.

**Comment by briancain** [comment]
Hi @basos9 - if you could, please confirm that upgrading powershell fixes your issue. thanks!

**Comment by basos9** [comment]
Yes, upgrading Powershell to version 3 solved this issue.
And also the workaround of killing the spawned powershell process, also makes the script to continue, only to split out that the installed powershell version is not supported and version 3 is the minimum requerement.

I suspect that the check for the powershell version produces the freeze, itself.

If this is not considered a bug, which since there is already a check mechanism, it is, maybe, at least, update the readme to state out loud that Powershell v3 is a requrement.

**Comment by briancain** [comment]
It's definitely a bug, however we already have an issue tracking the work (#9056). I'll go ahead and close this as a duplicate. Thanks!
