### ISSUE TITLE
Box not found

### ISSUE THREAD

**Issue by nm926** [hashicorp/vagrant#9392]
Hi Team

Vagrant Version 1.4.3, Ubuntu OS while i run the vagrant i got error "box centos/7" not found

Thanx in advance

**Comment by briancain** [comment]
Hi @nm926 - Please fill out the provided issue template with all of the information it asks. It helps us get more information about what could be going wrong. Thanks!

**Comment by kikitux** [comment]
@nm926 user/box is available since vagrant 1.5. being current versions 1.9 and 2.x

please upgrade.
