### ISSUE TITLE
Validation error info displays odd line/file combo for Ruby errors in loaded files

### ISSUE THREAD

**Issue by mschuchard** [hashicorp/vagrant#9393]
Please note I understand if this is rejected due to poor cost/benefit since this behavior is probably due to Ruby error info capturing and passing upward and this is not a breaking issue, but I still wanted to raise awareness on this issue.

### Vagrant version
Vagrant 1.9.8 (`CHANGELOG.MD` does not note a fix for this since then)

### Vagrantfile
```ruby
require_relative 'other_file'

method # line 3

Vagrant.configure('2') do |config|
  config.vm.box = 'whatever'
end
```

### other_file
```ruby
def method
  invalid # line 2
end
```

### Expected behavior
Either the `Vagrantfile` is specified as the errored file with its corresponding line number, or the `other_file` is specified as the errored file with its corresponding line number. Either change seems good to me.

> Path: Vagrantfile
Line number: 3
Message: NameError: undefined local variable or method `invalid' for main:Object

> Path: other_file
Line number: 2
Message: NameError: undefined local variable or method `invalid' for main:Object

### Actual behavior
The `Vagrantfile` is specified as the errored file and the line number is from `other_file`.
> There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

> Path: Vagrantfile
Line number: 2
Message: NameError: undefined local variable or method `invalid' for main:Object

### Steps to reproduce
Trigger a Vagrant validation on the above code either via `up`, `validate`, etc.

**Comment by briancain** [comment]
Hi @mschuchard - thanks for opening an issue! It looks like this will get magically fixed for us once we have Vagrant using Ruby 2.5:

Vagrant 2.0.2 using Ruby 2.4:

```
vagrant@vagrant:~/temp$ vagrant validate
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /home/vagrant/temp/Vagrantfile
Line number: 2
Message: NameError: undefined local variable or method `invalid' for main:Object
```

Versus Vagrant on Ruby 2.5:

```
brian@localghost:temp % be vagrant validate                                                              ±[●][master]
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /Users/brian/code/vagrant-sandbox/temp/other_file.rb
Line number: 2
Message: undefined local variable or method `invalid'
```

I'll leave this open for now until we can bump the ruby version for Vagrant. Thanks!

**Comment by mschuchard** [comment]
How nice and convenient. Thanks for the followup!

**Comment by briancain** [comment]
Hi, I'm going to go ahead and close this. We're basically just waiting on getting Ruby 2.5 into Vagrant. Thanks for opening an issue!
