### ISSUE TITLE
Vagrant reload from the inside

### ISSUE THREAD

**Issue by unt0xication** [hashicorp/vagrant#9397]
## Vagrant version
1.9.8

## OS
macOS High Sierra

## Description
We are searching a way to "vagrant reload" the Vm from the inside. At my job, we often run a script that clones a wordpress website from our private repo and that initialize it. But the problem is that we need to reload the Vm each time. We'd love to know if our script can reload the Vm itself from a ssh connection. We need the same feature as "vagrant reload", but we need to be able to run that command inside ssh. Is that possible?

**Comment by kikitux** [comment]
hello

doesnt sound like a bug and needs more info for a feature request.

there is lots of things that can be taken from your description, but having a child process that tells parent process what do do is hard.


If you just reboot the VM you will be only missing the share mount points, perhaps you could parse the current mount points and the /Vagrantfile and work around that if needed.

Can you explain better what you need?

Why this can't be triggered from out side the VM ?

Thanks
Alvaro.

**Comment by unt0xication** [comment]
Sorry, i'll try to explain better. If you go into your VM directory and type "vagrant reload" in your terminal your VM will reload, right? 

But imagine if you go into your VM directory and SSH into your running Vagrant machine to get an access to the shell (vagrant ssh command), there's no way i can run a vagrant ssh from there.

That's what we are trying to do here at my job, let me know if u know something we could do :)

**Comment by kikitux** [comment]
not sure why you need that. you can vagrant ssh -c 'sudo reboot' and the VM will be rebooted.

Don't use share folders or mount the shared folder manually and you are done.

If you can explain the use case that will help to sense the feature but as now, we are missing the point.

People use vagrant in all sort of forms, CI/CD, etc.

However there is a point where Vagrant doesnt do what something want to do, and you need to choose:

- trade off and do it in the vagrant way
- move to other tool, say packer with virtualbox-ovf that can start from a VM.

Hope this helps.

**Comment by unt0xication** [comment]
We need that feature because we're using a Command Line Interface inside the Vm. The script can only interact with the current environment and not outside. I cannot run a vagrant ssh -c 'sudo reboot' from there.

**Comment by chrisroberts** [comment]
Hi there. What you are describing is essentially controlling the hypervisor from within the guest VM, and this is not a feature that will be available from Vagrant. Ideally you will want to update how your task is setup so that Vagrant is able to drive the action using provisioners. 

Cheers!

**Comment by unt0xication** [comment]
I'll try to update my task to make it work another way. Thanks for the help!
