### ISSUE TITLE
Configuration of the /etc/network/interfaces and /etc/dhcp/dhcpd.conf  by Vagrantfile?

### ISSUE THREAD

**Issue by ZoranStojsavljevic** [hashicorp/vagrant#9401]
Hello to everyone,

I have an interesting question here: Can I provide by Vagrantfile the configuration of /etc/network/interfaces, namely, can I add in the etc/network/interfaces the following:

```
# The USB-Ethernet interface 2
allow-hotplug eth2
iface eth2 inet dhcp
```

The another question is: can I define by Vagrantfile the following dhcpd.conf file?
/etc/dhcp/dhcpd.conf : /etc/dhcp/dhcpd.conf

I have set it like this:

```
## cat /etc/dhcp/dhcpd.conf
##
## DHCP Server Configuration file.
##   see /usr/share/doc/dhcp-server/dhcpd.conf.example
##   see dhcpd.conf(5) man page
##

default-lease-time 600;
max-lease-time 18000;

subnet 192.168.15.0 netmask 255.255.255.0 {
##   interface enp0s25;
   range dynamic-bootp 192.168.15.100 192.168.15.200;
   option broadcast-address 192.168.15.255;
   next-server 192.168.15.2;
   option subnet-mask 255.255.255.0;
}

host bbb {
   hardware ethernet D0:5F:B8:FF:F8:69;
   fixed-address 192.168.15.20;
   filename "bbb-image";
}

host pdu {
   hardware ethernet 88:b6:27:01:62:43;
   fixed-address 192.168.15.21;
   filename "pdu-image";
}
```
Or I can import the files, written in some other languages (.xml, .json, .jinja2 or something else)?

Any examples of the shelf for these cases?

Thank you,
Zoran

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the Vagrant mailing list. There are many more people who will be able to get you a faster answer there. Thank you and have a great day!
