### ISSUE TITLE
Vagrant Up Hangs after updating to latest version of Ubuntu

### ISSUE THREAD

**Issue by daniel-li95** [hashicorp/vagrant#9406]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
2.01

### Host operating system
Windows 

### Guest operating system
Ubuntu 

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "hashicorp/precise64"
  #config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 4567

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false
  
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  config.vm.boot_timeout = 600

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end

```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/daniel-li95/520d3d6f4ae71f26b9d9d078c269b38c

### Expected behavior
Should have logged and been able to interact with virtual machine from gitbash

### Actual behavior
Hangs on ssh auto 

### Steps to reproduce
1. Follow the basic instructions guide on Vagrantup, using their default settings and box
2. Update and upgrade the machine using apt-get update etc. until it reaches ubuntu 16
3. Run Vagrant reload

**Comment by chrisroberts** [comment]
Can you please try using the `bento/ubuntu-16.04` box and see if this issue persists. Thanks!

**Comment by daniel-li95** [comment]
Hi Chris, 

Just tried changing boxes, doesn't work. When I open the virtual box and interact with it directly, I can still log in. I'm not sure how to check where it tries to log in.

**Comment by chrisroberts** [comment]
Does it work correctly from a cmd.exe or powershell.exe window?

**Comment by daniel-li95** [comment]
No it doesn't. I believe there's an issue when vagrant tries to input login details, but I don't know how to check that.

**Comment by chrisroberts** [comment]
Can you run `vagrant ssh --debug` and provide a gist with the full output

**Comment by daniel-li95** [comment]
Of course.

https://gist.github.com/daniel-li95/0b3af8c63269e785812d067c7033786a

I appreciate your help on this matter so far.

**Comment by chrisroberts** [comment]
@daniel-li95 Can you try upgrading to the 2.0.2 release and see if this behavior continues to persist? Thanks!

**Comment by daniel-li95** [comment]
Hi, it continues to hang at auth method: private key.

How would I check that it's inputting correctly into the virtual machine?

**Comment by daniel-li95** [comment]
Is there any way to view what inputs go from Vagrant into the Virtual Machine?

**Comment by daniel-li95** [comment]
Destroyed box, remade it, seems to work now. Not sure why it didn't work before.
