### ISSUE TITLE
Vagrant Hangs machine at Booting VM

### ISSUE THREAD

**Issue by squeakycheese75** [hashicorp/vagrant#9407]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 1.8.1

### Host operating system
Ubuntu 16.04

### Guest operating system
Same issue with ubuntu/trusty64 and hashicorp/precise64

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
end

or 

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provider :virtualbox
end

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

Sorry it hangs the system every time.  

### Expected behavior
What should have happened?

### Actual behavior
When I run vagrant up (with out without debug) it gets to the Booting VM stage and locks up the machine.  Only way to get around is to reboot.  

==> default: Booting VM...

### Steps to reproduce
1. Vagrant Up

I've tried completely cleaning down vagrant and re-installing.  Same issue every time.  

### References
Are there any other GitHub issues (open or closed) that should be linked here?
https://github.com/hashicorp/vagrant/issues/7710

**Comment by mcrey** [comment]
I have the same situation. Also ubuntu 16.04, also stucking on Booting VM.

Do you have any updates on this issue?

**Comment by bacquy** [comment]
I've got same problem. Someone can try to just start fresh new vm created manually in virtualbox and see if it stuck ?

Thank you

**Comment by mcrey** [comment]
@bacquy the problem is in versions of linux kernel and VBox. It could be solved by upgrading VBox ver. to 5.2 and Vagrant to 2.0.1

**Comment by bacquy** [comment]
I made something very bad and I need to reinstall Ubuntu and I'll try your solution.

**Comment by chrisroberts** [comment]
Please update to the latest version of Vagrant. If the issue persists, please provide a gist of the debug output from a `vagrant up --debug`.

Cheers!

**Comment by bacquy** [comment]
It works for me. Thank you

**Comment by uoo38** [comment]
I've got same situation. I think this issue is related to new Linux kernel 4.13 and it has been reported [here](https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1736116).

**Comment by benplummer** [comment]
I'm experiencing this too although upgrading Vagrant (to 2.0.2) and Virtualbox (to 5.2.6) does not fix it. I was originally on Vagrant 2.0.1 and Virtualbox 5.2.0.

**Comment by sherinkuruvilla** [comment]
I did the following steps to resolve the issue.
1. Upgrade [power shell](https://www.microsoft.com/en-us/download/details.aspx?id=54616)to at-least 3.0
2. Install [Curl](http://www.oracle.com/webfolder/technetwork/tutorials/obe/cloud/objectstorage/restrict_rw_accs_cntainers_REST_API/files/installing_curl_command_line_tool_on_windows.html#summary)
* Add curl.exe path to system path

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by aavrug** [comment]
Hey,
I tried these solutions but still, the same issue is happening to my system the vagrant up freeze my system.
![whatsapp image 2018-03-03 at 23 00 21](https://user-images.githubusercontent.com/1022358/36937504-7e231de4-1f3a-11e8-8ed9-c27444533be4.jpeg)

**Comment by sherinkuruvilla** [comment]
@Gaurav, 
Try vagrant 1.9.6/Virtual Box 4.3.10 combination after uninstalling prior versions. It works for me.

**Comment by MariaFischer** [comment]
I had to do the following to get '$vagrant up' to reliably work on my 16.04 install:
(original solution source: https://askubuntu.com/questions/994926/ubuntu-16-04-freezes-on-vagrant-up)

0) uninstall / purge previous vagrant and virtualbox
1) install vagrant version 2.0.2
2) install virtualbox 5.2.8
3) delete any .../vagrant.d/data/machine-index/index* files

**Comment by karlwilbur** [comment]
I had the same problem. I'm running Ubuntu 16.04 and installed `virtualbox` via `apt`. I have Vagrant version 2.0.3.

Upgrading Virtualbox to 5.2.8 (https://download.virtualbox.org/virtualbox/5.2.8/virtualbox-5.2_5.2.8-121009~Ubuntu~xenial_amd64.deb) fixed it for me. I did have to `apt purge virtualbox` to get rid of the older version and I had to `reboot` to ensure that I was running the right kernel modules.

```
sudo apt purge virtualbox
wget https://download.virtualbox.org/virtualbox/5.2.8/virtualbox-5.2_5.2.8-121009~Ubuntu~xenial_amd64.deb
gdebi virtualbox-5.2_5.2.8-121009~Ubuntu~xenial_amd64.deb
sudo /sbin/vboxconfig
reboot now
```

**Comment by aavrug** [comment]
@karlwilbur Thanks, this almost worked. But now I am facing a different issue. While running `vagrant up` after reaching `homestead-7: Setting hostname...` It is getting stopped like forever. Is there any solution for this. I also tried few solutions from Google but It didn't workout.

**Comment by queglay** [comment]
> I had to do the following to get '$vagrant up' to reliably work on my 16.04 install:
> (original solution source: https://askubuntu.com/questions/994926/ubuntu-16-04-freezes-on-vagrant-up)
> 
>     1. uninstall / purge previous vagrant and virtualbox
> 
>     2. install vagrant version 2.0.2
> 
>     3. install virtualbox 5.2.8
> 
>     4. delete any .../vagrant.d/data/machine-index/index* files

I also have this problem, if that method works it should be part of the installation procedure.
I'm running virtual box 5.2.30 on Mac OS High Sierra.
