### ISSUE TITLE
Vagrant-libvirt [provider is libvirt] does NOT do/perform the port forwarding

### ISSUE THREAD

**Issue by ZoranStojsavljevic** [hashicorp/vagrant#9408]
### Vagrant version
vagrant -v ==>> Vagrant 2.0.1

### Host operating system
uname -a ==>> Linux localhost.localdomain 4.14.14-300.fc27.x86_64 #1 SMP Fri Jan 19 13:19:54 UTC 2018 GNU/Linux

### Guest operating system
KVM (libvirt)

### Vagrantfile
require 'etc'

Vagrant.configure(2) do |config|
  host = Socket.gethostname
  puts "Value of the host name is #{host}"
  user = Etc.getlogin
  puts "Value of the user is #{user}"

  config.ssh.proxy_command = "/usr/bin/ssh -A -t #{host} nc %h %p"
  config.ssh.forward_agent = true

  config.vm.provider :libvirt do |libvirt|
    config.vm.box = "boxName"
    libvirt.memory = 2048
    libvirt.cpus = 2
    libvirt.storage_pool_name = "default"
    libvirt.host = #{host}
    libvirt.username = #{user}

    # libvirt specific plugins installations!

    # implicit call to install plugin vagrant-libvirt
    if !Vagrant.has_plugin?("vagrant-libvirt")
      system('vagrant plugin install vagrant-libvirt')

      raise("vagrant-libvirt installed. Run command again.");
    end
  end

  if !Vagrant.has_plugin?("vagrant-proxyconf")
    system('vagrant plugin install vagrant-proxyconf')

    raise("vagrant-proxyconf installed. Run command again.");
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
=begin
    config.proxy.http     = ...
    config.proxy.https    = ...
    config.proxy.ftp      = ...
    config.proxy.no_proxy = ...
=end
  end

  #### Forward port 2222 for the ssh server
  config.vm.network :forwarded_port, guest: 22, host: 2222
  #### Forward port 8888 for the internal REST server
  config.vm.network :forwarded_port, guest: 8888, host: 8888
  #### Forward port 8010 for the Storage Server
  config.vm.network :forwarded_port, guest: 8010, host: 8010
  #### Forward port 5000 for the KernelCI Frontend Web Server
  config.vm.network :forwarded_port, guest: 5000, host: 5000
  #### Forward port 80 for the http Lava Frontend Web Server
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  #### Forward port 443 for the https Lava Frontend Web Server
  config.vm.network :forwarded_port, guest: 443, host: 4443
  #### Configure network accessibility for tftp server

  config.vm.provision "shell" do |s|
    s.privileged = false
    s.inline = $build
  end

  config.vm.synced_folder ".", "/vagrant", type: "rsync"
end

### Debug output
https://pastebin.com/P3uxGSRb

### Expected behavior
[vuser@localhost cip-b_at_d-generic]$ vagrant ssh-config
Host default
  HostName 127.0.0.1 <<=====================================================
  User vagrant
  Port 2222 <<==============================================================
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/vuser/projects2/vagrant/cip-b_at_d-generic/.vagrant/machines/default/libvirt/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ProxyCommand /usr/bin/ssh -A -t localhost.localdomain nc %h %p
[vuser@localhost cip-b_at_d-generic]]$ 

### Actual behavior
[vuser@localhost cip-b_at_d-generic]$ vagrant ssh-config
Host default
  HostName 192.168.121.157 <<================================================
  User vagrant
  Port 22 <<=================================================================
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/vuser/projects2/vagrant/cip-b_at_d-generic/.vagrant/machines/default/libvirt/private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes
  ProxyCommand /usr/bin/ssh -A -t localhost.localdomain nc %h %p
[vuser@localhost cip-b_at_d-generic]$

### Actual login to libvirt vm

[vuser@localhost stretch64]$ vagrant ssh
Value of the host name is localhost.localdomain
Value of the user is vuser
Pseudo-terminal will not be allocated because stdin is not a terminal.
vuser@localhost.localdomain's password: 
Linux stretch 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent permitted by applicable law.
vagrant@stretch:~$ sudo su
root@stretch:/home/vagrant# ifconfig
ens5: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.121.157  netmask 255.255.255.0  broadcast 192.168.121.255
        inet6 fe80::5054:ff:fe34:6c00  prefixlen 64  scopeid 0x20<link>
        ether 52:54:00:34:6c:00  txqueuelen 1000  (Ethernet)
        RX packets 573  bytes 88745 (86.6 KiB)
        RX errors 0  dropped 53  overruns 0  frame 0
        TX packets 554  bytes 87687 (85.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 1161  bytes 361605 (353.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1161  bytes 361605 (353.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@stretch:/home/vagrant# 

### Steps to reproduce
[command]: vagrant up

### References
None

**Comment by chrisroberts** [comment]
Hi there.

The vagrant-libvirt plugin is a third party plugin and issues/questions should be directed to the plugin author. You can find the GH repository for this plugin here: https://github.com/vagrant-libvirt/vagrant-libvirt

Cheers!
