### ISSUE TITLE
installing vagrant via python code held with errors

### ISSUE THREAD

**Issue by rangarajancr** [hashicorp/vagrant#9410]
Dear Team,

i am trying to install ansible in vagrant environment via python code

where internal os that runs inside ansible environment is centos / 7

procedure i do followed up inorder to install ansible in cetos /7 (vagrant host) via python script is

as follows

yum install gcc
.......................
gcc is required to compile c code
....................................................
yum install python-setuptools
...............................................
easy_install pip
.............................
yum install python-devel
.......................................
pip install ansible
...................

errors i meet up are:

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-RBsaog/pynacl/
/usr/lib/python2.6/site-packages/pip-9.0.1-py2.6.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
[root@web vagrant]# 

i am literally cant understand why i am getting this error.

Thank you

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
