### ISSUE TITLE
Fix NFS for Windows hosts

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9415]
The Vagrant documentation states:

> Windows users: NFS folders do not work on Windows hosts. Vagrant will ignore your request for NFS synced folders on Windows.

https://www.vagrantup.com/docs/synced-folders/nfs.html

Can we get this fixed for Windows hosts, so that more developer boxes can feature bidirectional sync for Windows users?

**Comment by chrisroberts** [comment]
Hi there. Windows does not provide native support for nfsd and as such we won't be adding support for nfs synced folders on Windows hosts. SMB support is available, with support on many guests. There is a third party vagrant plugin available for nfsd on Windows that you may want to investigate, however it is not authored by nor maintained by the Vagrant team: https://github.com/winnfsd/vagrant-winnfsd

Cheers!
