### ISSUE TITLE
Version tag docker provision bug

### ISSUE THREAD

**Issue by imam** [hashicorp/vagrant#9418]
### Vagrant version
Vagrant 1.9.2

### Host operating system
Windows 10

### Guest operating system
Ubuntu 16

### Expected behavior
tag `--name` should replace ':' with something else

### Actual behavior
It's creating a bug when we run `docker.run "rabbitmq:3.6.12"` because `:` is not allowed for `--name`
```
docker: Error response from daemon: Invalid container name (rabbitmq:3.6.12), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed.
```

Currently, to solve this I should set `auto_assign_name` to `false`

**Comment by briancain** [comment]
Please provide the relevant minimum Vagrantfile so that we can try to reproduce your bug. Thanks!

**Comment by briancain** [comment]
Thanks @imam !
