### ISSUE TITLE
Unable to access the Free IPA in web url

### ISSUE THREAD

**Issue by rangarajancr** [hashicorp/vagrant#9419]
Dear Team,

I have successfully installed , Free IPA server with following settings as follows,

Where i am installing Free ipa into centos 7 by vagrant

setup as follows 

Cable modem > pfsense firewall > cisco smart switch > pc > Free IPA
![error1](https://user-images.githubusercontent.com/34336461/35609650-225c1fac-0684-11e8-9688-6b69db35972b.png)
 
----------------------------
[root@localhost vagrant]# cat /etc/*release
CentOS Linux release 7.4.1708 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core) 
CentOS Linux release 7.4.1708 (Core) 

[root@localhost vagrant]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
192.168.2.40 ipa.gworks.mobi ipa
[root@localhost vagrant]# 

[root@localhost vagrant]# cat /etc/hostname 
ipa.gworks.mobi
[root@localhost vagrant]# 

thing is when i try to access it from from my host machine web url i am not able to do it so , i do get following error as "" This site can’t be reached http://ipa.gworks.mobi/ is unreachable".

can any one help me in this please.

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
