### ISSUE TITLE
issue on Mac OS with Vagrant 2.0.2 when I upgrade to HighSierra 10.13.3

### ISSUE THREAD

**Issue by mangkibo** [hashicorp/vagrant#9424]
Hello there,

I have issue on Mac OS with Vagrant 2.0.2 when I upgrade to MacOs HighSierra 10.13.3

### Vagrant version
Vagrant 2.0.2

### Host operating system
Mac OS HighSierra 10.13.3

### Guest operating system
Ubuntu Server Xenial Xerus 16.04.3 64bit

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  
  #config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8888
  config.vm.network :forwarded_port, guest: 3306, host: 3306
  #config.vm.network :forwarded_port, guest: 3000, host: 3000
  #config.vm.synced_folder "shared/", "/var/www/html/projects", owner: "www-data", group: "ubuntu"    
end

```

### Debug output
https://gist.github.com/mangkibo/a14705775760e104662de4ff696d340d

### Expected behavior
1. if I execute "vagrant" it should show vagrant help
2. if I execute "vagrant up/status" it should run / show status of the box 
3. but it work well when I execute "vagrant -v". It show the version

### Actual behavior
What actually happened?
`$ vagrant

/opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/platform.rb:37:in 'downcase': input string invalid (ArgumentError)
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/platform.rb:37:in 'block in wsl?'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/silence_warnings.rb:8:in 'silence!'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/util/platform.rb:35:in 'wsl?'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:136:in '<main>'`

### Steps to reproduce
1. I'm upgrade my Mac OS to HighSierra 10.13.3 
2. execute vagrant
3. it produce "platform.rb:37:in `downcase': input string invalid (ArgumentError)"
4. It work well before i'm doing upgrade

Thanks,

Kibo

**Comment by chrisroberts** [comment]
Hi there. What shell are you using? Do you have any addons/plugins/etc in use on your current shell?

**Comment by mangkibo** [comment]
I'm using macOs Teminal (bash shell i think). Sometime i'm using screen to run my box, but after upgrading the OS, vagrant is not found inside screen. I'm not really sure if i'm using any plugins, and I don't remember installed any of it.

**Comment by mangkibo** [comment]
Hi @chrisroberts,
The problem is on my .bash_profile PATH. I should checked it first. It was point at /usr/bin. When I change to /usr/local/bin it works well.

**Comment by patrickr81** [comment]
Having the same issue on macOS Sierra - changing my PATH didn't help.

I commented out the Windows Subsystem check in /bin/vagrant, bit of a kludge, but it works.

**Comment by patrickr81** [comment]
I had a similar problem. I resolved it by removing an errant '?' from my bash_profile PATH.

(It might have been another character that prints as '?'; it shows as some combination of characters I completely ignored when I deleted it in emacs.)

**Comment by chrisroberts** [comment]
Glad you got it cleared up. Cheers!

**Comment by mangkibo** [comment]
Thanks for all your responses, guys! :)
