### ISSUE TITLE
Assigning private network to ETH2 interface got magically assigned to the ETH1 interface?!

### ISSUE THREAD

**Issue by ZoranStojsavljevic** [hashicorp/vagrant#9426]
### Vagrant version
vagrant -v ==>> Vagrant 2.0.1

### Host operating system
uname -a ==>> Linux localhost.localdomain 4.14.14-300.fc27.x86_64 #1 SMP Fri Jan 19 13:19:54 UTC 2018 GNU/Linux

### Guest operating system
uname -r ==>> 4.9.0-4-amd64

### Vagrantfile (networking part of it)
  config.vm.network :forwarded_port, guest: 8888, host: 8888
  config.vm.network :forwarded_port, guest: 8010, host: 8010
  config.vm.network :forwarded_port, guest: 5000, host: 5000
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 443, host: 4443
  config.vm.network "private_network", bridge: "eth2", ip: "192.168.15.2", type: "static"

### Debug output
root@stretch:~# ip route show
default dev eth0 scope link 
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 
192.168.15.0/24 dev eth1 proto kernel scope link src 192.168.15.2 
root@stretch:~# netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         0.0.0.0         0.0.0.0         U         0 0          0 eth0
10.0.2.0        0.0.0.0         255.255.255.0   U         0 0          0 eth0
192.168.15.0    0.0.0.0         255.255.255.0   U         0 0          0 eth1
root@stretch:~# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fe8d:c04d  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:8d:c0:4d  txqueuelen 1000  (Ethernet)
        RX packets 1774  bytes 186641 (182.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1187  bytes 165406 (161.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.15.2  netmask 255.255.255.0  broadcast 192.168.15.255
        inet6 fe80::a00:27ff:fe57:855c  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:57:85:5c  txqueuelen 1000  (Ethernet)
        RX packets 5  bytes 2420 (2.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24  bytes 3206 (3.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::210:60ff:fe31:d452  prefixlen 64  scopeid 0x20<link>
        ether 00:10:60:31:d4:52  txqueuelen 1000  (Ethernet)
        RX packets 15  bytes 4920 (4.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 2106 (2.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 3662  bytes 1138885 (1.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3662  bytes 1138885 (1.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@stretch:~# dmesg | grep "register 'asix'"
[    6.091255] asix 1-1:1.0 eth2: register 'asix' at usb-0000:00:0b.0-1, ASIX AX88772 USB 2.0 Ethernet, 00:10:60:31:d4:52
root@stretch:~# 

### Expected behavior
ETH2 should take place of ETH1

### Actual behavior
ETH1 popped out of nowhere

### Steps to reproduce
vagrant up (always)

### IMPORTANT!
Please, do note that my filter is on USB ASIX AX88772 device, which, after hijacking from host. got assigned to ETH2!

root@stretch:~# dmesg | grep "register 'asix'"
[    6.091255] asix 1-1:1.0 eth2: register 'asix' at usb-0000:00:0b.0-1, ASIX AX88772 USB 2.0 Ethernet, 00:10:60:31:d4:52
root@stretch:~#

**Comment by chrisroberts** [comment]
Please provide the name of the host distribution, the guest distribution, and a gist of the debug output from a `vagrant up --debug`. Thanks!

**Comment by ZoranStojsavljevic** [comment]
### Host operating system
uname -a ==>> Linux localhost.localdomain 4.14.14-300.fc27.x86_64 -> FEDORA 27

###Guest operating system
uname -r ==>> 4.9.0-4-amd64 -> DEBIAN 9

### vagrant up --debug
https://pastebin.com/2X99QijT

### Virtual Machine Networking
root@stretch: ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.2.15  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::a00:27ff:fe8d:c04d  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:8d:c0:4d  txqueuelen 1000  (Ethernet)
        RX packets 1694  bytes 179767 (175.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1146  bytes 159424 (155.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.15.2  netmask 255.255.255.0  broadcast 192.168.15.255
        inet6 fe80::a00:27ff:fe57:855c  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:57:85:5c  txqueuelen 1000  (Ethernet)
        RX packets 5  bytes 2420 (2.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22  bytes 3066 (2.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::210:60ff:fe31:d452  prefixlen 64  scopeid 0x20<link>
        ether 00:10:60:31:d4:52  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 1760 (1.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 1642  bytes 492647 (481.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1642  bytes 492647 (481.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@stretch: ip route
default dev eth0 scope link 
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 
192.168.15.0/24 dev eth1 proto kernel scope link src 192.168.15.2 
root@stretch:

**Comment by ZoranStojsavljevic** [comment]
I have no idea how managed to close this issue??? :-(

**Comment by ZoranStojsavljevic** [comment]
Any take on this? I kinda have idea that Vagrant does need complete re-design of the networking module!? Very little of networking really does work to the VBox provider specifications.

Zoran
