### ISSUE TITLE
Debian guest capability: configure networks

### ISSUE THREAD

**Issue by chrisroberts** [hashicorp/vagrant#9428]
There still seem to be some remaining issues to be resolved identified in #9134 and initially resolved with #9338.

A mix of ubuntu and debian boxes were used for testing the initial PR, so remaining issues need to be identified with specific boxes that display the error states. Conflicting reports on `bento/ubuntu-17.10` (which is a box I tested locally). Error state reported on `ubuntu/artful64` (https://github.com/hashicorp/vagrant/issues/9134#issuecomment-361584017)

**Comment by haggaie** [comment]
Hi, I'm trying to use the `ubuntu/bionic64` image and it seems to show the same errors as in #9134 (missing ifdown/ifup and /etc/network/interfaces).

**Comment by briancain** [comment]
@haggaie if you are using a version of Vagrant older than `2.0.2` then Vagrant won't have the ability to manage the boxes networking with `systemd-networkd`.

**Comment by haggaie** [comment]
@briancain I'm using version 2.0.2.

**Comment by ljakab** [comment]
@haggaie As the original report says, there are still issues with some Vagrant boxes based on Ubuntu 17.10 and later, even with the latest version of Vagrant.

**Comment by briancain** [comment]
@haggaie yep, I suspect it will also have the same bug in vagrant that`ubuntu/artful64` has. It should be fixed in the next release.

**Comment by haggaie** [comment]
Thanks @briancain, I'll try the next release then.

**Comment by adamskwersky** [comment]
I'm not sure if this is the same issue. I don't see up/down errors. Instead it appears to configure without error, and I can connect using 127.0.0.1/2222 to the ssh, but I can't access services that are running on the guest from my host OS, e.g. a web service on port 8080.
I'm using bento/ubuntu-17.10 and Vagrant 2.0.2 and this is my network config:
	hcldash.vm.network "private_network", type: "dhcp"

vagrant@vagrant:/opt/hcl-dash/logs$ ifconfig eth1
eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.28.128.1  netmask 255.255.255.0  broadcast 172.28.128.255
        inet6 fe80::a00:27ff:fef9:2a7a  prefixlen 64  scopeid 0x20<link>
        ether 08:00:27:f9:2a:7a  txqueuelen 1000  (Ethernet)
        RX packets 35  bytes 5056 (5.0 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 28  bytes 2129 (2.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by mpdude** [comment]
I can confirm that Vagrant 2.0.3 works for `ubuntu/artful64`. 👏
