### ISSUE TITLE
vagrant package with coreos

### ISSUE THREAD

**Issue by nik786** [hashicorp/vagrant#9429]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
vagrant --version
Vagrant 1.9.3

### Host operating system
Windows 10
### Guest operating system
CoreOs

Trying take backup of multi vm environment  of coreos (core-01,core-02,core-03) by vagrant package command

vagrant package core-01 core-02 core-03

But not able to create backup of core-01 core-02 core-03

any help?

**Comment by briancain** [comment]
@nik786 - Please provide a link to a gist containing the full output of the command you're trying to run with the `--debug` flag as well as the Vagrantfile. This will help us triage your issue...thanks!

**Comment by nik786** [comment]
command : vagrant package  core-01 --output core-01.box
Im trying to take backup on below mentioned case :
git clone https://github.com/coreos/coreos-vagrant.git
cd coreos-vagrant
if you will increase the counter in config.rb
$num_instances=3

when vagrant up will be executed then three vms will be created. 

core-01 core-02 and core-03.
after had login in any of vm do some activities
vagrant ssh core-01
cd /home/core
touch a{1..5}.txt

the come out
then execute
vagrant halt
so now how can we take backup of three vms by vagrant pacakge command and use on another machine?

**Comment by briancain** [comment]
@nik786 - you should be able to run `vagrant package core-01` with any relevant options on each guest to "backup" and package each machine into its own box. If you just have general usage questions, direct those to the mailing list. Otherwise if you have found a bug, provide a gist link with the debug output. Thanks!

**Comment by nik786** [comment]
cat Vagrantfile

Vagrant.configure("2") do |config|
 
  config.vm.define "core1" do |core1|
    core1.vm.box = "core-01"
    core1.vm.hostname = 'core1'
    core1.vm.box_url = "file:///c:/core-1/core-01.box"
    #config.ssh.username = "vagrant"
    #config.ssh.password = "vagrant"
    #config.vm.provision "shell",
    #path: "script.sh"
    core1.vm.network :private_network, ip: "192.168.10.101"
    core1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "core1"]
  end
  end
  end

  
vagrant up
core1: Warning: Authentication failure. Retrying...
    
problem : not able to login core1 by vagrant ssh core1

**Comment by briancain** [comment]
@nik786 - if the problem you're facing is just that you can't ssh into the box, please open an issue with the maintainers of the box you are trying to use. https://github.com/coreos/coreos-vagrant

Thanks!
