### ISSUE TITLE
Cannot ignore new Windows 10 built-in SSH client in Vagrant 2.0.2

### ISSUE THREAD

**Issue by jstangroome** [hashicorp/vagrant#9433]
### Vagrant version
Vagrant 2.0.2

### Host operating system
Windows 10 x64 version 1709 (OS Build 16299.214)
also: VirtualBox 5.2.6 r120293
```
C:\Windows\System32\OpenSSH\ssh.exe -V
OpenSSH_7.5p1, without OpenSSL
```

### Guest operating system
Ubuntu 14.04

### Vagrantfile
The result of `vagrant init ubuntu/trusty` is sufficient.

### Expected behavior
`vagrant ssh` should succeed.

### Actual behavior
`vagrant ssh` returned error:
```
vagrant@127.0.0.1: Permission denied (publickey).
```

### Steps to reproduce
1. [Install Windows 10 OpenSSH beta](https://blogs.msdn.microsoft.com/powershell/2017/12/15/using-the-openssh-beta-in-windows-10-fall-creators-update-and-windows-server-1709/)
1. Open default shell (PowerShell) via Win+X, i. Also reproducible with `cmd.exe` shell.
1. `vagrant init ubuntu/trusty`
1. `vagrant up`
1. `vagrant ssh`

### References

With increased verbosity (eg `vagrant ssh -- -vvv`) the output shows:
```
Load key "./.vagrant/machines/section/virtualbox/private_key": invalid format.
```

This `Load key ... invalid format` error is most likely a bug with Windows 10's OpenSSH Beta, possibly related to only ed25519 keys currently being supported: https://github.com/PowerShell/Win32-OpenSSH/issues/973#issuecomment-349065648

However, I cannot easily coerce Vagrant to use its embedded SSH client instead since this change:
https://github.com/hashicorp/vagrant/issues/9143#issuecomment-361635432

I'd hoped `VAGRANT_PREFER_SYSTEM_BIN=0 vagrant ssh` or `VAGRANT_PREFER_SYSTEM_BIN=false vagrant ssh` would work but it didn't.

Modifying the PATH to exclude `C:\Windows\System32\OpenSSH` resolves the issue. Using a Cygwin shell with its own SSH client also resolves the issue.

Uninstalling the Windows 10 SSH beta also resolves the issue.

Would be great if Vagrant 2.0.2 can be forced to use embedded SSH via vargant-specific environment variable command line parameter or even if Vagrant could generate ed25519 SSH keys.

**Comment by besmirzanaj** [comment]
on a bare new W10 system I got this:

```
Permissions for 'D:/Repo/vagrant/.vagrant/machines/default/virtualbox/private_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "D:/Repo/vagrant/.vagrant/machines/default/virtualbox/private_key": bad permissions
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
vagrant@127.0.0.1: Permission denied (publickey).
```

had to explicitly give permissions to the private key removing  'Authenticated users' and 'users' from acl.

**Comment by sibinx7** [comment]
I uninstall Powershell SSH ( System32/openSSH), then restarted the system. Now I can access vagrant via ssh. Run `vagrant ssh --debug`, then you can find the real issue.

**Comment by besmirzanaj** [comment]
Have to try that

**Comment by Raffaello** [comment]
@sibinx7 that is not a real solution. there should no be conflict with powershell

**Comment by Raffaello** [comment]
I have a similar issues and it seems related to `private_key` file permission:
OS: Win10, vagrant 2.0.2
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for '[..]\default\\virtualbox\\private_key' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "[..]\\default\\virtualbox\\private_key": bad permissions
vagrant@127.0.0.1: Permission denied (publickey).

**Comment by sibinx7** [comment]
@Raffaello Yes, It just a workaround. I have this issue after I install Heroku command line and PowerShell openssh. Anyway vagrant is working fine with `Cmder`.

**Comment by oalders** [comment]
I'm having similar issues on macOS 10.13.4.

```
DEBUG ssh: Checking key permissions: /Users/olaf/Documents/github/metacpan-developer/.vagrant/machines/default/virtualbox/private_key
 INFO ssh: Invoking SSH: /usr/bin/ssh ["vagrant@127.0.0.1", "-p", "2222", "-o", "LogLevel=FATAL", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "IdentitiesOnly=yes", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-o", "IdentityFile=\"/Users/olaf/Documents/github/metacpan-developer/.vagrant/machines/default/virtualbox/private_key\""]
vagrant@127.0.0.1: Permission denied (publickey).
```

```
$ vagrant --version
Vagrant 2.1.1
```

I just upgraded `vagrant` today.  That private key file was last updated today.  `VirtualBox` is at `Version 5.2.12 r122591 (Qt5.6.3)`
