### ISSUE TITLE
Install VMware Workstation plugin: Failed to build gem native extension, extconf.rb failed

### ISSUE THREAD

**Issue by AnonymousCat** [hashicorp/vagrant#9435]
When I say `vagrant up` (what I'm ultimately trying to do successfully), it says:

> The provider 'vmware_workstation' could not be found, but was requested to back the machine 'homestead-7'. Please use a provider that exists.

So, I am trying to follow the instructions [here](https://www.vagrantup.com/docs/vmware/installation.html) to install the VMWare provider using the standard plugin installation procedure. Also, when I say `vagrant plugin list`, it says:

> vagrant-share (1.1.7) - Version Constraint: > 0

### Vagrant version
Vagrant 1.9.2 which is the stable release that is recommended in [this](https://learninglaravel.net/books/laravel/installing-laravel) Laravel tutorial. I am using Homestead.

### Host operating system
Windows 10
VMware Workstation 14

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.9.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON::parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if Vagrant.has_plugin?('vagrant-hostsupdater')
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    elsif Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.aliases = settings['sites'].map { |site| site['map'] }
    end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/AnonymousCat/9a14f3c7047f4114a51e6460a8d0f58c

### Expected behavior
The plugin should have been installed.

### Actual behavior

> C:\Users\myname\Homestead> vagrant plugin install vagrant-vmware-workstation
> Installing the 'vagrant-vmware-workstation' plugin. This can take a few minutes...
> Temporarily enhancing PATH to include DevKit...
> Building native extensions.  This could take a while...
> Bundler, the underlying system Vagrant uses to install plugins,
> reported an error. The error is shown below. These errors are usually
> caused by misconfigured plugin installations or transient network
> issues. The error from Bundler is:
> 
> ERROR: Failed to build gem native extension.
> 
>     C:/HashiCorp/Vagrant/embedded/bin/ruby.exe -r ./siteconf20180202-7412-14ttrx9.rb extconf.rb
> *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
>         --with-opt-dir
>         --without-opt-dir
>         --with-opt-include
>         --without-opt-include=${opt-dir}/include
>         --with-opt-lib
>         --without-opt-lib=${opt-dir}/lib
>         --with-make-prog
>         --without-make-prog
>         --srcdir=.
>         --curdir
>         --ruby=C:/HashiCorp/Vagrant/embedded/bin/$(RUBY_BASE_NAME)
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in C:/Users/myname/.vagrant.d/gems/2.2.5/gems/vagrant-vmware-workstation-5.0.4 for inspec
> tion.
> Results logged to C:/Users/myname/.vagrant.d/gems/2.2.5/extensions/x86-mingw32/2.2.0/vagrant-vmware-workstation-5.0.4/gem
> _make.out

### Steps to reproduce
`vagrant plugin install vagrant-vmware-workstation`

**Comment by Enchiridion** [comment]
I was getting the exact same issue after having to [reinstall the plugin](https://www.hashicorp.com/blog/updating-vagrant-vmware-plugin).  Only differences were I'm running VMWare Workstation 12 and vagrant 1.9.4.

However after updating to vagrant 2.0.2 I was able to successfully install the plugin.

**Comment by chrisroberts** [comment]
Hi there. Updating to a more recent version of Vagrant will resolve the problem. Cheers!
