### ISSUE TITLE
vagrant up --provider=softlayer is broken with version 2.02

### ISSUE THREAD

**Issue by cclark64** [hashicorp/vagrant#9436]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

xxxxxxx@oc4286047578: pts/0: 2 files 28Kb -> vagrant -v
Vagrant 2.0.2

### Host operating system
This is the operating system that you run locally.

RHEL 7.4

### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
xxxxxx@oc4286047578: pts/0: 2 files 28Kb -> vagrant up --provider=softlayer
/home/xxxxxx/vagrant-test/sl-ngix/puphpet/ruby/to_bool.rb:9: warning: constant ::Fixnum is deprecated
The provider 'softlayer' could not be found, but was requested to
back the machine 'webtest1'. Please use a provider that exists.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by briancain** [comment]
@cclark64 - is the error you are getting just that the provider can't be found?

```
The provider 'softlayer' could not be found, but was requested to
back the machine 'webtest1'. Please use a provider that exists.
```

**Comment by chrisroberts** [comment]
Hi there,

You need to install the softlayer plugin for the provider to be available:

```
vagrant plugin install vagrant-softlayer
```

Cheers!

**Comment by cclark64** [comment]
Hi

 its installed

activesupport (5.1.4)
  - Version Constraint: > 0
oscar (0.5.3)
  - Version Constraint: > 0
softlayer (0.0.17)
  - Version Constraint: > 0
vagrant-berkshelf (5.1.2)
  - Version Constraint: > 0
vagrant-disksize (0.1.2)
  - Version Constraint: > 0
vagrant-hostmanager (1.8.7)
  - Version Constraint: > 0
vagrant-libvirt (0.0.43)
  - Version Constraint: > 0
vagrant-omnibus (1.5.0)
  - Version Constraint: > 0
vagrant-openstack-provider (0.11.0)
  - Version Constraint: > 0
vagrant-share (1.1.9)
  - Version Constraint: > 0
vagrant-softlayer (0.4.0)
vagrant-vsphere (1.13.2)
  - Version Constraint: > 0
virtualbox (0.8.6)
  - Version Constraint: > 0

regards
