### ISSUE TITLE
Can't download vagrant boxes from the box catalog

### ISSUE THREAD

**Issue by benhsmith** [hashicorp/vagrant#9438]
### Vagrant version
1.9.1

### Host operating system
macOS

### Guest operating system
Centos 7

### Vagrantfile
```
Vagrant.configure(2) do |config|
  config.vm.box = 'hashicorp/precise64'
end
```
### Debug output
https://gist.github.com/benhsmith/3a6f111719ea5760f4a0db70d39e64d4

### Expected behavior
Should have downloaded a box. This is happening with several boxes I've tried and that I've used before.

### Actual behavior
404

### Steps to reproduce
1. Run `vagrant up` or `vagrant box add hashicorp/precise64`

**Comment by chrisroberts** [comment]
Hi there,

The Vagrant Cloud URL in previous versions of Vagrant has been disabled as of today. If you do not want to upgrade your Vagrant installation, you can update the VAGRANT_SERVER_URL environment variable to fix downloads. See the mailing post link below for more information:

https://groups.google.com/d/msg/vagrant-up/H8C68UTkosU/qz4YUmAgBAAJ

Cheers!

**Comment by benhsmith** [comment]
Thanks @chrisroberts !

**Comment by PranjalGohain** [comment]
Is this really resolved.. i tried upgrading to the latest version. But with vagrant up it just does nothing..

![image](https://user-images.githubusercontent.com/23078404/36202048-412d3018-11a8-11e8-8159-c0d1619a5c6b.png)

**Comment by PranjalGohain** [comment]
it was working fine with the older version 1.9.7 where i had to manually change the path name..
