### ISSUE TITLE
Using generice/gentoo box ,Having the error"The following SSH command responded with a non-zero exit status."

### ISSUE THREAD

**Issue by greister** [hashicorp/vagrant#9440]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
```
vagrant -v
Vagrant 2.0.1
```

### Host operating system
This is the operating system that you run locally.
Windows7 64 professional
### Guest operating system
This is the operating system you run in the virtual machine.
gentoo

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "gentoo2"
  config.vm.network "private_network", ip: "192.168.33.13"
  config.vm.network  "public_network", type: "dhcp" , auto_config: true , use_dhcp_assigned_default_route: true
  config.vm.hostname = "gentoo2"
  
  config.vm.provider :virtualbox do |vb|
	vb.name = 'gentoo'
	vb.gui = true
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

https://gist.github.com/greister/0076c188f90d46a70b6ea93ca8e368c4
### Expected behavior
What should have happened?

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by jbonhag** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
