### ISSUE TITLE
vagrant ssh -c ... often stalls for DragonflyBSD guests

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9441]
### Vagrant version

Vagrant 2.0.1

### Host operating system

macOS High Sierra 10.13

### Guest operating system

DragonflyBSD 5.0.1

### Vagrantfile

```ruby
  config.vm.box = "mcandre/dragonflybsd"
```

### Debug output

```console
$ vagrant up
$ vagrant ssh -c "echo 'all ur base are belong to us' >/home/vagrant/flag.txt"
$ vagrant ssh -c "cat /home/vagrant/flag.txt" | grep 'all ur base are belong to us'
```

### Expected behavior

```console
all ur base are belong to us
```

### Actual behavior

The `vagrant ssh -c`... command stalls indefinitely with no output. Even worse, pressing Control+C does not stop the stalled command, so the terminal becomes useless.

As a workaround, I am moving the `grep` pipe into the `vagrant ssh -c`... command, instead of running grep from the host.

**Comment by jbonhag** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
