### ISSUE TITLE
vmware [12.5.8] - vagrant unable to find vmware provider

### ISSUE THREAD

**Issue by pale3** [hashicorp/vagrant#9444]
Started with latest vagrant, if I downgrade to 2.0.1 everything runs as normal. 

Note: I have systemd aware vmware workstation, which brings another issue up where
vagrant is validating vmware service by invoking official /etc/init.d/vmware script. In such env 
there is no vmware script thus vagrant fails with "The init script for managing VMware services could not be found...". Simple fix is just extract vmware init script from bundle and cp it to /etc/init.d/.  <-- I think this also has to be considered in the future vagrant-vmware relation

### Vagrant version
2.0.2

### Host operating system
Arch

### Guest operating system
Windows 7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|

  config.vm.box = "nxm/windows7"

	config.vm.provider :vmware_workstation do |vmware|
		vmware.vmx["memsize"] = "2092"
		vmware.vmx["ethernet1.connectiontype"] = "custom"
		vmware.vmx["ethernet1.vnet"] = "/dev/vmnet0"
		vmware.vmx["ethernet2.connectiontype"] = "custom"
		vmware.vmx["ethernet2.vnet"] = "/dev/vmnet1"
	end

  config.vm.network "public_network", :adapter => 2, :bridge => "eth0"
  config.vm.network "public_network", :adapter => 3, :bridge => "eth1"

end
```

### Debug output
https://gist.github.com/pale3/c84e17010a02a25406ed7042fb79acb9

### Expected behavior
Start up guest system

### Actual behavior
```
The provider 'vmware_workstation' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
```

### Steps to reproduce
1. vagrant up --provider vmware_workstation

**Comment by federkasten** [comment]
I have the same issue. My host OS is also Arch.

**Comment by audibleblink** [comment]
Running into the same issue here.

Host: Arch
VMWare Workstation 14.1.1
Vagrant  2.1.1

Installed the `.xz` from https://www.vagrantup.com/vmware/downloads.html
```
❯❯ vagrant plugin install vagrant-vmware-workstation
❯❯ vagrant plugin license vagrant-vmware-workstation ~/license.lic
❯❯ vagrant plugin list
#> vagrant-vmware-workstation (0.0.1)
```

**Comment by syrm** [comment]
Same problem here, with Archlinux too

**Comment by syrm** [comment]
The problem is here : 
```
/opt/vagrant-vmware-desktop/bin/vagrant-vmware-utility api -port=9922 -log=info

2018-05-22T15:13:59.617+0200 [INFO ] vagrant-vmware-utility.simple: created: vmx=<nil>
2018-05-22T15:13:59.617+0200 [ERROR] vagrant-vmware-utility.simple: vmware services setup failure: error="Failed to locate valid vmware services executable"
Failed to setup Vagrant VMWare API service - failed to setup Vagrant VMware driver - Failed to locate valid vmware services executable```

**Comment by chrisroberts** [comment]
Hi there,

@syrm is correct that the issue is the utility not finding the init script as it is based on the vmware installer not system packages. I'll look into adding some service detection to the utility so it handles systemd setups as well.

**Comment by chrisroberts** [comment]
The vagrant-vmware-utility was updated in version 1.0.1 to prevent the services failure setup when the /etc/init.d/vmware script is not found. Cheers!
