### ISSUE TITLE
Hyper-v launch fails with foreign characters in virtual switch name

### ISSUE THREAD

**Issue by fredrikbaberg** [hashicorp/vagrant#9451]
### Vagrant version
`Vagrant 2.0.2`

### Host operating system
Edition: Windows 10 Pro
Version: 1709
OS Build: 16299.214

Language: Swedish

### Guest operating system
`bento/Ubuntu-16.04`

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
end
```

### Debug output
https://gist.github.com/fredrikbaberg/6192b350f5136fad96a69e2fb5b38552

### Expected behavior
Machine should start.

### Actual behavior
Machine did not start, due to "Hyper-V was unable to find a virtual switch with name ..."

### Steps to reproduce
1. Have Hyper-V virtual switch with foreign character in name. Note: in Swedish the name of the default switch, which can't be changed, is `Standardväxel`, which does not seem to be an allowed name.
2. Create new machine with `vagrant init --box bento/ubuntu-16.04`
3. Run `vagrant up --provider=hyperv`
4. Creating another switch with similar name gives the same result, creating with only "normal" characters works.

**Comment by chrisroberts** [comment]
Fixed by #9747. Cheers!
