### ISSUE TITLE
NFS folders work on Windows hosts

### ISSUE THREAD

**Issue by albrin** [hashicorp/vagrant#9463]
The [site page](https://www.vagrantup.com/docs/synced-folders/nfs.html) says that Windows hosts do not support NFS folders.

But Windows 10 Pro supports NFS folders with standard tools:

![2018-02-13_16-55-52](https://user-images.githubusercontent.com/647103/36143900-01c33fcc-10df-11e8-9f8f-a10ac86d0139.jpg)

And my configuration works great:

```
# ...
  config.vm.synced_folder ".", "/vagrant",
    type: "nfs",
    mount_options: ['dmode=775','fmode=664']
# ...
```

**Comment by varghesejacob** [comment]
is NFS faster than SMB for windows hosts?

**Comment by chrisroberts** [comment]
This will also require some capability updates and some assumption removals on type of mount being performed (remove static failed mount error output).

**Comment by marcharding** [comment]
The "Services for NFS" are only for mounting NFS shares, it's only a nfs client and **not** a nfs server.

See https://support.microsoft.com/en-us/help/2769923/services-for-nfs-availability-in-windows-8-editions

AFAIK a microsoft nfs server is only available in the server editions of windows.

**Comment by chrisroberts** [comment]
After searching through Windows NFSD related things, Windows NFS server is only available in Windows Server editions, so I'm going to close this up. Cheers!
