### ISSUE TITLE
Hyper-V - Unable to use a box created in other computer

### ISSUE THREAD

**Issue by joserman** [hashicorp/vagrant#9464]
Hi all,

The problem is when I try to reuse a box which I create in my local computer, I copy/link the box to other computer and by the time HyperV tries to create and register the VM I got an error from Vagrant..

I´ve been trying with different versions of Vagrant, updating my host.. and nothing was fixed.. 
Also, I try with Windows 10 and 8.1, happen the same error..

### Vagrant version

Vagrant 2.0.1

### Host operating system
Windows 10

### Guest operating system
Windows 10 / 8.1

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "GFT_Ubuntu_Server_16_04"
  config.vm.network "private_network", bridge: "ethHV"

end
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
Create the VM, register it and starting up.

### Actual behavior

The error happen during the following this process.

```
-> 
==> default: Successfully added box 'myubuntu/ubuntu1604' (v0) for 'hyperv'!
==> default: Importing a Hyper-V instance
Looking for switch with name: ethHV
Found switch: ethHV
    default: Cloning virtual hard drive...
    default: Creating and registering the VM...

An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Compare-VM : Failed to import a virtual machine.
At C:\XXXX\vagrant\embedded\gems\gems\vagrant-2.0.1\plugins\providers\hyperv\scripts\import_vm_vmcx.ps1:33 char:14
+ $vmConfig = (Compare-VM -Copy -GenerateNewID @VmProperties)
+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Compare-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.CompareVM
```

### Steps to reproduce
1. Create the box using packer, (This box works fine in the computer I create, but not if I copy or use it in other computer)
2. Vagrant add box   myUbuntu /pathMyUbuntu...
3. Vagrant up

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
