### ISSUE TITLE
Ensure that python is installed on the box when using Ansible

### ISSUE THREAD

**Issue by stertingen** [hashicorp/vagrant#9468]
### Vagrant version
2.0.2

### Host operating system
Arch Linux

### Guest operating system
Ubuntu 16.04

### Vagrantfile (workaround included)
```ruby
  config.vm.provider "virtualbox" do |vb, override|
    override.vm.box = "ubuntu/xenial64"

    # Workaround
    override.vm.provision "shell", inline: "which python || sudo apt -y install python"
    
    override.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.extra_vars = ansible_extra_vars
    end
  end
```

Yes, I know, the usage of the ubuntu/* boxes is discouraged. Anyway, these boxes do not ship with python preinstalled, running Ansible on a vanilla ubuntu/xenial64 box will fail.

When using Ansible, Vagrant should ensure that Ansible is able to run on that machine; measing that all requirements are met. There might be an option to change this behavior, similar to `ansible.install_mode` for ansible_local.

### Debug output
https://gist.github.com/stertingen/c50c67187a373bfd9c4eb6a4c2363033

### Expected behavior
Ansible should run the playbook without failure.

### Actual behavior
Ansible fails while ”gathering facts“ and complains about missing python.

### Steps to reproduce
1. Paste above snippet into Vagrantfile
2. Remove workaround
3. Create a valid playbook.yml for Ansible
4. Run vagrant up

**Comment by chrisroberts** [comment]
Hi there,

Thanks for opening this issue but this enhancement request is not something that is feasible for the provisioner to do. This would require the provisioner to have the ability to install python for any supported guest, and install it "correctly" which will likely have a different meaning for different users.

Instead the user can ensure python is installed on the guest by including a shell provisioner to install python before running the ansible provisioner. If the box does not provide python by default, using the shell provisioner will ensure that python is installed correctly.

Cheers!
