### ISSUE TITLE
Cannot configure Hyper-V box memory

### ISSUE THREAD

**Issue by AnthonyMastrean** [hashicorp/vagrant#9477]
I cannot configure the memory for a Hyper-V box without the following error. If I remove or comment the memory configuration, it works!

### Vagrant version
2.0.2

### Host operating system
Windows 10 Pro 1709

### Guest operating system
Ubuntu 17.10

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1710"
  config.vm.provider "hyperv"
  config.vm.provider "hyperv" do |h|
    h.memory = 4096
  end
end
```

### Debug output
https://gist.githubusercontent.com/AnthonyMastrean/23bc15b7bf9fb59c4cb4/raw/9742ca4c5b806b15b36040121a12b4aedea3fc0b/vagrant-9477.log

### Expected behavior
The Vagrant machine should start.

### Actual behavior
The `up` command fails, complaining about setting the memory, I think.

```
An error occurred while executing a PowerShell script. This error
is shown below. Please read the error message and see if this is
a configuration error with your system. If it is not, then please
report a bug.

Script: import_vm_vmcx.ps1
Error:

Hyper-V\Set-VM : 'generic-ubuntu1710-hyperv' failed to modify resources.
An unexpected error occurred: Provider is not capable of the attempted operation (0x80041024).
'generic-ubuntu1710-hyperv' failed to modify resources. (Virtual machine ID 6144DF79-B0FB-44AB-8997-4FCC928FAAD9)
'generic-ubuntu1710-hyperv' encountered an unexpected error: Provider is not capable of the attempted operation (0x80041024). (Virtual machine ID 6144DF79-B0FB-44AB-8997-4FCC928FAAD9)
At C:\HashiCorp\Vagrant\embedded\gems\gems\vagrant-2.0.2\plugins\providers\hyperv\scripts\import_vm_vmcx.ps1:103 char:5
+     Hyper-V\Set-VM -VM $vmConfig.VM -MemoryMinimumBytes $MemoryMinimu ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.SetVM
```

### Steps to reproduce
1. Copy the `Vagrantfile`, as above
2. Run `vagrant up`

**Comment by briancain** [comment]
Have you tried using one of the `bento` boxes (like `"bento/ubuntu-17.10"`)? I'm curious if that would work for you. Thanks!

**Comment by pieterbreed** [comment]
I'm having exactly the same issue. I will try if it is better with your suggested `bento/ubuntu-17.10` version. I'm on Windows 10 Pro Insider Preview, Build 17074.

**Comment by pieterbreed** [comment]
No, using the bento box didn't make the problem go away for me.

**Comment by chrisroberts** [comment]
@AnthonyMastrean @pieterbreed Hi! I'm trying to reproduce this error and have so far been unsuccessful in generating an exact reproduction. I have been able to force an error by allocating more memory to the guest than the host is able to provide, but the error message I receive is different than yours. If you configure the memory to a lower value (like `"1024"`) do you still receive the same error? 

Thanks!

**Comment by Blaiserman** [comment]
Same here with Vagrant 2.1.2 and  Windows 10 Pro 1803

**Comment by vchrizz** [comment]
Same here with Vagrant 2.2.0 on Windows Server 2012R2 and box generic/debian9.

To reproduce the error, `vagrant init` a new instance, set memory to something higher than 2048 and omit setting maxmemory.
example:
```
Vagrant.configure("2") do |config|
  #config.vm.box = "debian/stretch64" # does not support provider hyperv
  config.vm.box = "generic/debian9"
  config.vm.provider "hyperv" do |h|
    h.memory = 4096
    # h.maxmemory = 4096
  end
end
```
To fix the error, set memory to something higher than 2048 and set maxmemory to the same.
example:
```
Vagrant.configure("2") do |config|
  #config.vm.box = "debian/stretch64" # does not support provider hyperv
  config.vm.box = "generic/debian9"
  config.vm.provider "hyperv" do |h|
    h.memory = 4096
    h.maxmemory = 4096
  end
end
```
