### ISSUE TITLE
vagrant assumes Windows guests are Darwin

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9481]
When Windows guest boxes are not explicitly labelled as Windows boxes, then Vagrant sometimes treats them as Darwin / macOS boxes, which breaks things.

### Vagrant version

Vagrant 2.0.1

### Host operating system

mac OS High Sierra 10.13.3

### Guest operating system

Windows 10 Evaluation x86_64

This behavior may in fact be the cause of some other odd Windows guest behavior in recent tickets I've opened. I will try explicitly configuring guest as Windows type and see if that fixes the problems.

**Update**

Strangely, explicitly configuring `config.vm.guest = :windows` in my `Vagrantfile` does not appear to change that Vagrant treats the guest as Darwin rather than Windows. I will promote this configuration to my Vagrantfile packer template, repack the box, and see if that helps somehow.

**Comment by briancain** [comment]
Can you please provide a debug gist link for when you see this behavior? Thanks.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
