### ISSUE TITLE
Cannot assign static IP on a debian/jessie64/stretch64 using libvirt provider

### ISSUE THREAD

**Issue by Aurelien-** [hashicorp/vagrant#9486]
Hello,

I am not able to set a static IP with : 

> config.vm.network "private_network", ip: "XXX.XXX.XXX.XXX"

System config :

> Ubuntu 16.04, 4.13.0-32-generic
> Vagrant 2.0.2 (installed from deb package)
> libvirtd (libvirt) 1.3.1

Vagrant libvirt plugin installed with command :

> vagrant plugin install vagrant-libvirt

vagrant plugin list :

> vagrant-libvirt (0.0.43)
> virtualbox (0.8.6)

Guest systems tried : 

> 
> debian/jessie64 and debian/stretch64
> 
### Vagrantfile

> Vagrant.configure("2") do |config|
>     config.vm.box = "debian/stretch64"
>     config.vm.provider "libvirt"
> 
>     config.vm.synced_folder ".", "/vagrant", :nfs => true, :mount_options => ['rw', 'vers=3', 'tcp']
>  
>     config.vm.provider "libvirt" do |v|
>         v.memory = 4096
>         v.cpus = 1
>     end
> 
>     # Basic setup through a shell provisioner
>     config.vm.provision "shell", inline: <<-SHELL
>       apt-get update
>       apt-get upgrade -y
>       apt-get install -y net-tools htop apt-transport-https curl iftop
>     SHELL
> 
> 
>       (1..1).each do |i|
>           config.vm.define "test-#{i}" do |node|
>              node.vm.network "private_network", ip: "192.168.50.#{i+1}"
>              node.vm.hostname = "test-#{i}"
>           end
>       end  
> end

### Debug output
https://gist.github.com/Aurelien-/37d17bb3bfc43c36d11af248663d9e6d

### Expected behavior
sudo ifconfig should return 192.168.50.2 for ens6 interface

### Actual behavior
sudo ifconfig returns random address in subnet 192.168.50.0 for ens6 interface. Almost surely obtained by DHCP.

### Steps to reproduce
1. Use provided Vagranfile in this issue
2. vagrant up --provider=libvirt

I am able to force the ip with the following provisioning lines, but only after the second boot (`vagrant halt; vagrant up`) : 

> node.vm.provision "shell", inline: "echo \'[Match]
> Name=ens6
> 
> [Network]
> DHCP=yes
> Address=192.168.50.#{i+1}\' > /etc/systemd/network/98-ens6.network"

This has been also tested on a debian/jessie64 box with same results (no static ip, forced with the provisiong shell script).

**Comment by briancain** [comment]
Hello @Aurelien- - the provider `vagrant-libvirt` is not apart of core Vagrant. Please open all libvirt provider issues with the right repository...thanks!

https://github.com/vagrant-libvirt/vagrant-libvirt
