### ISSUE TITLE
Cannot get default virtualbox provider working on a Ubuntu 16.04

### ISSUE THREAD

**Issue by Aurelien-** [hashicorp/vagrant#9487]
Hello,

I cannot get the default Virtualbox provider working, but libvirt is working fine.

System config :

> Ubuntu 16.04, 4.13.0-32-generic
> Vagrant 2.0.2 (installed from deb package)
> libvirtd (libvirt) 1.3.1
> virtualbox (0.8.6)

Vagrant libvirt and virtualbox plugins installed with command :

> vagrant plugin install vagrant-libvirt
> vagrant plugin install virtualbox

vagrant plugin list :

> vagrant-libvirt (0.0.43)
> virtualbox (0.8.6)

virtualbox installed packages:
```

apt-cache pkgnames | grep virtualbox*
virtualbox-source
unity-scope-virtualbox
virtualbox-guest-utils
virtualbox-guest-additions-iso
virtualbox-guest-dkms
virtualbox-dkms
virtualbox-guest-dkms-hwe
virtualbox-ext-pack
virtualbox
virtualbox-guest-x11-hwe
virtualbox-guest-source
virtualbox-qt
virtualbox-guest-source-hwe
virtualbox-guest-utils-hwe
virtualbox-dbg
virtualbox-guest-x11
```

Guest systems tried : 

> 
>  debian/stretch64
> 

### Vagrantfile

```
 # -*- mode: ruby -*-
 # vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/stretch64"

end
```

### Debug output
https://gist.github.com/Aurelien-/cb0ff99f7011d0e397bf2df3e9662c69

### Expected behavior
vagrant up should start successfully

### Actual behavior
Failed with following error:

> Stderr: VBoxManage: error: Failed to create the VirtualBox object!
> VBoxManage: error: Code NS_BASE_STREAM_WOULD_BLOCK (0x80470007) - Stream operation would block (extended info not available)
> VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
> 
> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["list", "hostonlyifs"]
> 
> Stderr: VBoxManage: error: Failed to create the VirtualBox object!
> VBoxManage: error: Code NS_BASE_STREAM_WOULD_BLOCK (0x80470007) - Stream operation would block (extended info not available)
> VBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.
> 
>  INFO interface: Machine: error-exit ["Vagrant::Errors::VBoxManageError", "There was an error while executing `VBoxManage`, a CLI used by Vagrant\nfor controlling VirtualBox. The command and stderr is shown below.\n\nCommand: [\"list\", \"hostonlyifs\"]\n\nStderr: VBoxManage: error: Failed to create the VirtualBox object!\nVBoxManage: error: Code NS_BASE_STREAM_WOULD_BLOCK (0x80470007) - Stream operation would block (extended info not available)\nVBoxManage: error: Most likely, the VirtualBox COM server is not running or failed to start.\n"]

### Steps to reproduce
1. Use provided Vagranfile in this issue
2. vagrant up

**Comment by briancain** [comment]
Hi @Aurelien- - What version of Virtualbox are you running on Ubuntu?

Also you do not need to install `virtualbox` when using vagrant, as it comes with Vagrant as the default provider. You should remove the plugin `virtualbox` from Vagrant.

**Comment by Aurelien-** [comment]
Hello,
The version shipped in the official repo of 16.04 is 5.0.40-dfsg-0ubuntu1.16.04.2. Here the log of apt-get install virtualbox : https://gist.github.com/Aurelien-/7f1323bc74b16c4b2f61010ffd3f9105

I removed vagrant and virtualbox and reinstalled them. Vagrant from the deb file and virtualbox from the repo. No virtualbox plugin installed. 

```
vagrant plugin list
vagrant-libvirt (0.0.43)
```

Got the same error as before after a `vagrant up` right after the install.

Got virtualbox from deb file : Oracle VM VirtualBox Manager 5.2.6
Same error as before : https://gist.github.com/Aurelien-/d4c2f66162b86eaa15c617329a3febb2

**Comment by briancain** [comment]
Can you provide your vagrantfile as well? And are you able to bring up a virtual machine through the virtualbox GUI?

**Comment by Aurelien-** [comment]
Arf sorry, didn't tried Virtualbox alone as I was thinking it was just a plugin embedded in Vagrant. So got the same error coming from wrong permissions in my ~/.config/Virtualbox folder (no write permission). Fixed by adding +w for folder and files.

For reference : https://askubuntu.com/questions/525421/virtualbox-runs-as-root-critical-error-as-user

**Comment by briancain** [comment]
Great! So I assume it's working now @Aurelien- ?

**Comment by Aurelien-** [comment]
Yes it is working, well not together with libvirt but that is another problem. Thanks !
