### ISSUE TITLE
list_boxes failing on WSL

### ISSUE THREAD

**Issue by Crisfole** [hashicorp/vagrant#9491]
I get a missing method error on WSL during `vagrant box list` when calling `directory` on a box.  I *have* run fully through https://www.vagrantup.com/docs/other/wsl.html. My bashrc exports `VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"`.

Exact line where failure occurs: https://github.com/hashicorp/vagrant/blob/master/plugins/commands/box/command/list.rb#L55

### Vagrant version
```
$ vagrant -v
Vagrant 2.0.2
$ vagrant.exe -v
Vagrant 2.0.2
```

### Host operating system
Windows 10 up to date as of 2/20

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
https://gist.github.com/Crisfole/2efba17e7bdbcde379388581ccfe57b5
Sanitized of actual client data. This uses a box downloaded from s3. That url is scrubbed.

### Expected behavior
No exception.

### Actual behavior
A missing_method error for NillClass

### Steps to reproduce
1. execute `vagrant box list` on WSL

**Comment by chrisroberts** [comment]
The 2.0.3 release included fixes for latest WSL version. If you still encounter this error after upgrading, please open a new issue. Cheers!
