### ISSUE TITLE
Cannot add local box in WSL

### ISSUE THREAD

**Issue by Crisfole** [hashicorp/vagrant#9492]
After finally packing up a box for use on windows in the WSL I went to add the box and got a bunch of red text. It worked from git bash, so I do not have debug output for you.

### Vagrant version
```
$ vagrant -v
Vagrant 2.0.2
$ vagrant.exe -v
Vagrant 2.0.2
```

### Host operating system
Windows 10 up to date as of 2/20

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
Unavailable:
```
$ vagrant box add --name client/ubuntu-14.04--hyperv build/ubuntu-14.04-amd64.box
==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'natera/ubuntu-14.04--hyperv' (v0) for provider:
    box: Unpacking necessary files from: file:///c/Users/chris/client/build/ubuntu-14.04-amd64.box
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

x Vagrantfile
x Virtual Hard Disks\\packer-hyperv-iso.vhdx: Can't create 'Virtual Hard Disks\\packer-hyperv-iso.vhdx'
x Virtual Machines\\BF34C03F-FAAE-474B-A46D-187DBE7620BC.VMRS: Can't create 'Virtual Machines\\BF34C03F-FAAE-474B-A46D-187DBE7620BC.VMRS'
x Virtual Machines\\BF34C03F-FAAE-474B-A46D-187DBE7620BC.vmcx: Can't create 'Virtual Machines\\BF34C03F-FAAE-474B-A46D-187DBE7620BC.vmcx'
x Virtual Machines\\BF34C03F-FAAE-474B-A46D-187DBE7620BC.vmgs: Can't create 'Virtual Machines\\BF34C03F-FAAE-474B-A46D-187DBE7620BC.vmgs'
x Virtual Machines\\box.xml: Can't create 'Virtual Machines\\box.xml'
x metadata.json
bsdtar: Error exit delayed from previous errors.
```

### Expected behavior
The box gets added.

### Actual behavior
Angry messages about failing to create folders with windows paths.

### Steps to reproduce
1. Execute command from output above with hyperv box packaged by Packer (also on WSL via symlink, which works great except colors)

**Comment by chrisroberts** [comment]
Hi there. Is the problem that the box cannot be added when you are running with WSL, but can be added when you are running outside the WSL? Can you also please run the box add command you show in the description with the `--debug` flag and provide a gist of the output?

Thanks!

**Comment by Crisfole** [comment]
Correct, I added the box from git bash. I can't really re execute the code since I reset to factory...

**Comment by briancain** [comment]
If you can reproduce this in the future, please open a new issue and provide debug output. Otherwise I'm going to close this. Thanks!
