### ISSUE TITLE
NFS synced_folder with mount_options doesn't work on Windows machine

### ISSUE THREAD

**Issue by DzeryCZ** [hashicorp/vagrant#9495]
I have an issue with `nfs` synced_folder on Windows 10 machine. 

If I have configuration like this:
```config.vm.synced_folder "../myproject", "/myproject", type: "nfs"```

Everything works fine. But when I want to try play around performance and do some mount_options changes. E.g. 
```config.vm.synced_folder "../myproject", "/myproject", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp']```

It always returns:

```
default: Mounting shared folders...
default: /myproject => C:/Users/j.zivny/projects/myproject
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o rw,vers=3,tcp,dmode=777,fmode=777,uid=1000,gid=1000 myproject  /myproject 

The error output from the command was:

  fmask     =<arg> umask of regular files
```

When I delete `mount_options` parameter, everything works.

My software: 
- Vagrant 2.0.1
- VirtualBox 5.2.4 r119785
- Host: Windows 10 1709
- Guest: Ubuntu 14.04

Any idea?

**Comment by adamreid** [comment]
The documentation for the [NFS](https://www.vagrantup.com/docs/synced-folders/nfs.html) synchronized folders states that 

> Windows users: NFS folders do not work on Windows hosts. Vagrant will ignore your request for NFS synced folders on Windows.

So what you were observing was that the sync folder was working with `vboxsf` without options. When you added options intended for `nfs` those got passed to `vboxsf` instead which did not understand them.

**Comment by chrisroberts** [comment]
When synced folder type is not valid given the host/guest platforms, and error should be raised instead of silently ignoring.
