### ISSUE TITLE
VirtualBox NAT Adapter not getting DHCP lease in private_network setup when consistent network device naming is turned off on guest

### ISSUE THREAD

**Issue by sgulinski** [hashicorp/vagrant#9498]
### Vagrant version
Vagrant 2.0.2 + VirtualBox 5.2.6 r120293

### Host operating system
macOS High Sierra 10.13.3

### Guest operating system
Red Hat Enterprise Linux 7.4 (own, Packer baked box) and CentOS 7.4 (`bento/centos-7.4` official box)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.vm.network "private_network", ip: "192.168.33.10"
end

```

### Debug output
This issue is easily reproducible, but if my debug output would still be useful, then please let me know and I will provide one.

### Expected behavior
VM is brought up, user is able to ssh to the machine using `vagrant ssh`

### Actual behavior
Vagrant times out with an error message saying `Timeout while waiting for the machine to boot`. I have first observed this issue on my own (Packer baked) box based on RHEL 7.4, but I have managed to replicate the same problem using an official `bento/centos-7.4` box. Essentially after disabling consistent network device naming by adding `net.ifnames=0 biosdevname=0` to grub, NAT network adapter doesn't get DHCP lease from VirtualBox and Vagrant can't do initial ssh to the running VM.  

### Steps to reproduce
1. vagrant up
2. vagrant ssh
3. sudo vi /etc/default/grub
4. change `GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet"` to `GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet net.ifnames=0 biosdevname=0"`
5. sudo grub2-mkconfig -o /boot/grub2/grub.cfg
6. exit
7. vagrant halt
8. vagrant up

### References
N/A

**Comment by chrisroberts** [comment]
Hi there,

This isn't something that vagrant can fix. If you want to have the consistent naming disabled, you will have to create a box with it disabled instead of disabling it on an existing box. The box in it's original form has the networking configuration setup to bring the device up, but once the device name changes, that configuration is no longer valid. The only way to resolve that is to create a box with the consistent name feature disabled.

Cheers!
