### ISSUE TITLE
Need to run ansible provision in the same process

### ISSUE THREAD

**Issue by myguddy** [hashicorp/vagrant#9505]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

I tried install two VM using vagrant and ansible.
Indeed, the second server requires the information from the first server, generating key
in order to the second server join the first server as client.

Normally in ansible playbook, the variable can be referred in other play and host
using hostvars['name']['variable-name'].

I tried with this but I think each ansible playbook runs  independently.
The variables cannot shared between plays and each host.

Is there anyway to share variables between play or each host?
Right now I save the information in local, then pass it to the second server.

I believe there is a better way to do so.

### Vagrantfile
```ruby
ENV["LC_ALL"] = "en_US.UTF-8"

VM_MEM = 512
VM_CPUS = 1

Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"

    config.vm.define "nom1" do |node|
        node.vm.provider :virtualbox do |vb|
            vb.name = "nom1"
            vb.memory = VM_MEM
            vb.cpus = VM_CPUS
        end
        # node.vm.hostname = "dockervm.k8s.dev"
        node.vm.network :private_network, ip: "192.168.100.10"
        # node.vm.synced_folder "./", "/vagrant", type: "nfs"
    end

    config.vm.define "nom2" do |node|
        node.vm.provider :virtualbox do |vb|
            vb.name = "nom2"
            vb.memory = VM_MEM
            vb.cpus = VM_CPUS
        end
        # node.vm.hostname = "dockervm.k8s.dev"
        node.vm.network :private_network, ip: "192.168.100.11"
        # node.vm.synced_folder "./", "/vagrant", type: "nfs"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision/playbook.yaml"
        ansible.verbose = "v"
    end
end
```
ansible playbook.yaml
```
---
- hosts: nom1
  tasks:

    - command: /bin/echo "this is a test"
      register: foo
    - set_fact:
        boo: "{{foo.stdout}}"


- hosts: nom2
  gather_facts: no
  tasks:
    - debug: var=foo
      when: foo is defined

    - debug: var=hostvars['nom1']['boo']
      when: hostvars['nom1']['boo'] is defined
...
```

### Expected behavior
At the second play of ansible, it is defined the variable boo from first play.

### Actual behavior
But error says "this variable is not defined" in the second play
==> 

### Steps to reproduce
1. locate playbook.yaml in  ./playbook
2. vagrant up
3. result:
    TASK [debug] *******************************************************************
skipping: [nom2] => {"changed": false, "skip_reason": "Conditional result was False"}

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
