### ISSUE TITLE
Conflicting shells for Windows guests

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9508]
`vagrant ssh` launches a Command Prompt session while `vagrant ssh -c`... launches bash. Could the work that went into getting `vagrant ssh` to load a shell actually available for Windows guests be extended to the `vagrant ssh -c` logic as well?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
