### ISSUE TITLE
VAGRANT UP

### ISSUE THREAD

**Issue by cammo1123** [hashicorp/vagrant#9512]
Every Time I
    `VAGRANT UP`
This Error shows:
`Progress state: VBOX_E_IPRT_ERROR
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not create the directory 'C:\Users\Cameron Youell\VirtualBox VMs\ubuntu-16.04-amd64_1519715
423391_23048' (VERR_ACCESS_DENIED)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component ApplianceWrap, interface IAppliance
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(struct HandlerArg *)" at line 886 of file
 VBoxManageAppliance.cpp`

**Comment by ilovemysillybanana** [comment]
Are you admin? I use vagrant with chefdk and it seems to require admin to work.

**Comment by cammo1123** [comment]
Yes I am

**Comment by cammo1123** [comment]
Thank you
Just had to do cd to my user
