### ISSUE TITLE
Privileged shell provisioning silently broken for SmartOS and Solaris11 guests

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9517]
### Vagrant version

Vagrant 2.0.1

### Host operating system

macOS High Sierra 10.13

### Guest operating system

SmartOS 20180203T031130Z

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/smartos"

  config.ssh.sudo_command = "print \".\nvagrant\n\" | /usr/lib/embedded_su root -c '%c''"

  config.vm.synced_folder ".", "/opt/vagrant", type: "rsync", disabled: true

  config.vm.provision "file", source: "flag.txt", destination: "/opt/home/vagrant/flag.txt"
  config.vm.provision "shell", path: "bootstrap.sh"
end
```

Packer source:

https://github.com/mcandre/packer-templates/tree/5d4f8f16765103af9e06d1adf167565bcca38d5f/smartos

### Expected behavior

When I `vagrant up`, then the bootstrap script is executed.

### Actual behavior

The script silently fails to execute. `vagrant up` exits with a successful zero status.

I am confident that the bootstrap script is failing to be executed, because when I replace the script content with a call to halt the machine, the machine does not halt.

### Steps to reproduce

1. Build the Vagrant box.
2. Import the box.
3. Run `vagrant up`.

As a workaround, I am applying the `privileged: false` option to my shell provisioners for the time being.

**Comment by briancain** [comment]
Please provide a link to a gist containing the debug output of the run. It should give us more information and tell us if the provision script actually ran our not. Thanks!

**Comment by mcandre** [comment]
The provisioning script did not actually run, as the VM did not `halt`.

I recently discovered that the parent guest plugin solaris11 is affected as well.

I tried several sudo and suexec configurations, but for some reason they were unable to improve the behavior.

**Comment by kikitux** [comment]
@mcandre seems you missed brian request, please check and provide gist with output to be able to move this forward

**Comment by mcandre** [comment]
My bad, I recently learned that pfexec is the thing to setup for Solaris derivatives. I'll probably get my VM working according to the more conventional Solaris idioms.
