### ISSUE TITLE
Getting Vagrant Up error after receiving Windows 10 updates.

### ISSUE THREAD

**Issue by lg2696** [hashicorp/vagrant#9519]
I tried the solution on issue #6852 but it did not solve my problem.  I have tried un-installing and re-installing various versions in addition to the C++ Redistributed SP1 for 2010.  Please see the attached image for the error I received.  I have been trying to resolve this issue for several months.  I am a Nanodegree student at Udacity but they offer no support in using the tools they require for completing the course.  They told me to use these forums.  So far I received no response.  I am also running out of ideas to try to fix this issue.

![vagrantuperror20180227](https://user-images.githubusercontent.com/31082820/36766361-838ea882-1c03-11e8-8ee1-d958152a99b6.JPG)

- ...

**Comment by briancain** [comment]
Hi @lg2696 - 

When you ran `vagrant init`, it placed a blank `Vagrantfile` down with a template. That default box is called `base`, however there are no Vagrant boxes by that name. You need to go into your Vagrantfile and replace the `"base"` with a box that exists. 

```
config.vm.box = "base"
```

You can find Vagrant boxes here: https://app.vagrantup.com/

Thanks!
