### ISSUE TITLE
homestead.rb:236:in `+': no implicit conversion of Integer into String (TypeError)

### ISSUE THREAD

**Issue by ackerchez** [hashicorp/vagrant#9523]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

Installed Version: 2.0.2
Latest Version: 2.0.2

### Host operating system
This is the operating system that you run locally.

MAC OSX 10.11.6

### Guest operating system
This is the operating system you run in the virtual machine.

Laravel Homestead

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

Vagrant up.

### Actual behavior
What actually happened?

Documents/Homestead/scripts/homestead.rb:236:in `+': no implicit conversion of Integer into String (TypeError)
	from /Users/jonathanackerman/Documents/Homestead/scripts/homestead.rb:236:in `block (3 levels) in configure'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/kernel_v2/config/vm_provisioner.rb:82:in `add_config'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/kernel_v2/config/vm.rb:336:in `provision'
	from /Users/jonathanackerman/Documents/Homestead/scripts/homestead.rb:235:in `block (2 levels) in configure'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/kernel_v2/config/vm_provisioner.rb:82:in `add_config'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/plugins/kernel_v2/config/vm.rb:336:in `provision'
	from /Users/jonathanackerman/Documents/Homestead/scripts/homestead.rb:212:in `block in configure'
	from /Users/jonathanackerman/Documents/Homestead/scripts/homestead.rb:197:in `each'
	from /Users/jonathanackerman/Documents/Homestead/scripts/homestead.rb:197:in `configure'
	from /Users/jonathanackerman/Documents/Homestead/Vagrantfile:35:in `block in <top (required)>'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/config/loader.rb:119:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/config/loader.rb:119:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/config/loader.rb:116:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/config/loader.rb:116:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:771:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:771:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:517:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:185:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:504:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/lib/vagrant/environment.rb:753:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:154:in `<main>'

### Steps to reproduce
1.  installed virtualbox & vagrant
2. installed homestead box, cloned repo, and set up homestead config.yaml.
3. vagrant up

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by briancain** [comment]
Hi @ackerchez - According to your gist, the error you are receiving is a problem with Homestead, not Vagrant:

```
Documents/Homestead/scripts/homestead.rb:236:in +': no implicit conversion of Integer into String (TypeError) from /Users/jonathanackerman/Documents/Homestead/scripts/homestead.rb:236:inblock (3 levels) in configure'
```

I recommend fixing that, or opening an issue with the Homestead project. Thanks!
