### ISSUE TITLE
Vagrant String encoding

### ISSUE THREAD

**Issue by charles-d-burton** [hashicorp/vagrant#9530]
### Vagrant version
V2.0.2
### Host operating system
Ubuntu 16.04

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  class Username
    def to_s
      print "Need your Github creds.\n"
      print "Username: "
      STDIN.gets.chomp
    end
  end
  class Password
    # encoding: US_ASCII
    def to_s
      begin
      system 'stty -echo'
      print "Password: "
      pass = STDIN.gets.chomp
      print pass
      ensure
      system 'stty echo'
      end
      pass.encode("ASCII")
    end
  end
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/ubuntu1604"
  config.vm.provision "file", source: "./defaults", destination: "defaults"
  config.vm.provision "file", source: "./gaviota", destination: "gaviota"
  config.vm.provision "file", source: "./web", destination: "web"

  config.vm.provision "shell", env: {"GITHUB_USER" => Username.new, "GITHUB_PASSWORD" => Password.new, "UNATTENDED" => "1"}, path: "./setup.sh"

  #config.vm.synced_folder "/data", "/vagrant_data"
  config.vm.provider :libvirt do |libvirt|
          libvirt.cpus = 2
          libvirt.memory = 4096
  end
end

```

### Expected behavior
What I'm expecting is Vagrant to pass a string literal in the password field to the guest OS.
For instance when it prompts for the password and you type in something like 
$$$$$$
It should pass that string as an environment variable to the gues.
### Actual behavior
Vagrant or ruby is changing the encoding.
This is what the guest sees

GITHUB Password set; 144614461446$

### Steps to reproduce
1. Create script that prints variable and name it setup.sh
2. Run the vagrant file passing in special characters for the password
3.

### References
https://github.com/hashicorp/vagrant/issues/2662

**Comment by kikitux** [comment]
Hello

`$` is an special character in Ruby.

So its more a ruby question on how to get an string with $ and not an actual Vagrant issue
