### ISSUE TITLE
Vagrant has trouble getting valid IP addresses using Hyper V

### ISSUE THREAD

**Issue by ilovemysillybanana** [hashicorp/vagrant#9532]
### Vagrant version
```
C:\Users\jose
λ  vagrant -v
Vagrant 2.0.2
```

### Hyper-V Version
```
Version
10.0.16299.192
```

### Host operating system
Microsoft Windows 10 Enterprise x64 
Version	10.0.16299 Build 16299

### Guest operating system
[mwrock/Windows2012R2](https://app.vagrantup.com/mwrock/boxes/Windows2012R2)

But this effects all vms I try to converge.

### Vagrantfile
```ruby
Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "mwrock/Windows2012R2"
  c.vm.network(:public_network, {:bridge=>"SwitchNo2"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :hyperv do |p|
    p.cpus = 2
    p.memory = 4096
  end
end

```

### Debug output
https://gist.github.com/ilovemysillybanana/8a9000749200668fff5d56d5fd0a45e4

### Expected behavior
Sometimes Vagrant gives me a bad IP address, it's not consistent though. I'll work maybe half my day or a few weeks and then suddenly each IP I get is a bad 169.x.x.x ip. I've tried deleting the vm and recreating, redownloading the image, reinstalling vagrant, rebooting, recreating the switches for hyper v and nothing has fixed the issue. This actually wasn't an issue until about two weeks ago and since then has been on and off, but when it happens it doesn't go away for at least a few hours. 

### Steps to reproduce
1. Download image
2. Vagrant Up

**Comment by briancain** [comment]
Hi @ilovemysillybanana - Do you have debug output from just Vagrant that demonstrates this behavior? The gist you linked to doesn't have any output from Vagrant itself.

**Comment by ilovemysillybanana** [comment]
@briancain Sure, here's one where it worked:

https://gist.github.com/ilovemysillybanana/bb2db8e7013feaaf84610db32253e903

This is one five minutes later that failed:
https://gist.github.com/ilovemysillybanana/4272cf642080b4e55336f0a73c810903

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
