### ISSUE TITLE
Pruning an SMB share failed

### ISSUE THREAD

**Issue by desolat** [hashicorp/vagrant#9540]
I had the same issue as in #9460 and had a look at the debug output (see gist for it): seems the SMB share names are simply too long and get wrapped around on the powershell output. Vagrant uses the truncated share names than and fails.

### Vagrant version
2.0.2

### Host operating system
Window 8

### Guest operating system
Linux

### Debug output
https://gist.github.com/desolat/84645fe12726598d53a332f56854e1c0

### References
#9460

**Comment by anrizal** [comment]
Hello,

I have the same issue, but it I could not get the debug output, because everytime, I run vagrant up --debug, It works

Host OS: windows 10 build 16299
vagrant 2.0.3
SMB version 3.0
Guest OS = ubuntu 16.04

**Comment by rasmuskr** [comment]
Hey just wanted to share a possible workaround to this.

I had a similar issue with pruning on destroy would get stuck and waiting forever but I managed to get it to work by editing:

C:\HashiCorp\Vagrant\embedded\gems\2.0.4\gems\vagrant-2.0.4\plugins\hosts\windows\scripts\unset_share.ps1 

and adding /Y to line two so it looks like this:
`$result = net share $share_name /DELETE /Y`
as suggested in this post for forcing deletes of shares
https://superuser.com/questions/285543/net-share-xyz-delete-fails-if-a-file-is-in-use-on-that-share

**Comment by chrisroberts** [comment]
Fixed by PR #9872 which includes a powershell util update for preventing line wrapping. Thanks for the report!

**Comment by Kub4jz** [comment]
Thank you @rasmuskr! We are facing the same problem in 2.2.2, but your fix saves us.
