### ISSUE TITLE
install plugin vagrant-bindfs | conflicting dependencies ffi

### ISSUE THREAD

**Issue by GiampaoloFalqui** [hashicorp/vagrant#9541]
### Vagrant version
Vagrant 2.0.2

### Host operating system
Windows 7 64bit Ultimate

### Guest operating system
Ubuntu 16.04

### Vagrantfile
This issue is not related to usage of a specific Vagrant instance, but to the install of a Vagrant plugin.

### Debug output
https://gist.github.com/GiampaoloFalqui/293384573939b310ce820f564c2fe1cb

### Expected behavior
Installed vagrant-bidnfs.

### Actual behavior
Threw an error related to ffi dependency not passing a version requirement. This also happen if I try to install the vagrant plugin ffi by itself.

### Steps to reproduce
1. Install vagrant.
2. Install plugin vagrant-bindfs.

### References
/

**Comment by briancain** [comment]
Hi @GiampaoloFalqui - Do you have any other plugins installed? And or did you upgrade from a previous version of Vagrant?

I just tried this with a fresh install of Windows 7 and Vagrant 2.0.2 and it works as expected.
<img width="912" alt="screen shot 2018-03-06 at 3 54 25 pm" src="https://user-images.githubusercontent.com/810277/37065690-b30e389a-2156-11e8-8d5a-875e79fb42f0.png">

**Comment by GiampaoloFalqui** [comment]
Hello @briancain.

Do you have any other plugins installed? Nope, freshly installed Vagrant.
And or did you upgrade from a previous version of Vagrant? No, installed it from scratch.

Is there anything else that I can provide you to debug this?

**Comment by briancain** [comment]
@GiampaoloFalqui I recommend uninstalling vagrant completely. Make sure the install directory is gone after you uninstall. Then re-install Vagrant 2.0.2 and try again. Thanks!

**Comment by GiampaoloFalqui** [comment]
Seems like it worked. Thanks!
