### ISSUE TITLE
windows 7 GetSmbShare does not work / lazy powershell version checking

### ISSUE THREAD

**Issue by SauliusTheBlack** [hashicorp/vagrant#9547]
## Vagrant version
2.0.2
### Host operating system
Windows 7 Pro

### Guest operating system
Ubuntu

### Vagrantfile
Omitted since not needed here

### Debug output
omitted a full file, excerpt included:

```
PS C:\Users\Saulius> Write-Output $PSVersionTable.PSVersion.Major
4
PS C:\Users\Saulius> Get-SmbShare
Get-SmbShare : The term 'Get-SmbShare' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
Get-SmbShare
~~~~~~~~~~~~
     CategoryInfo          : ObjectNotFound: (Get-SmbShare:String) [], CommandNotFoundException
     FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Saulius> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1

ERROR warden: Error occurred: Vagrant failed to generate a list of local SMB shares. Please try
running the command again.

```

### Expected behavior
Listed and created SMB shares

### Actual behavior
Fatal error, vagrant up just stopped.

### Steps to reproduce
1. have windows 7
2. install vagrant
3. try to create a smb share
4. vagrant will say that it can't create a list of smb shares

### My research showed that:
- vagrant looks up the major version of PowerShell(mine is 4.x)
- in smb.rb it runs Get-SmbShare|Format-List on line 114
- Get-SmbShare is only available starting at Windows 8/Server 2012

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included with the Vagrant command you used. This helps us figure out what's actually going on. Thanks!

**Comment by morganics** [comment]
I'm also on Windows 7 and have the same error:

DEBUG subprocess: Exit status: 0
 INFO synced_folder_cleanup: Invoking synced folder cleanup for: rsync
 INFO synced_folder_cleanup: Invoking synced folder cleanup for: smb
DEBUG host: Searching for cap: smb_cleanup
DEBUG host: Checking in: windows
DEBUG host: Found cap: smb_cleanup in windows
DEBUG host: Searching for cap: smb_cleanup
DEBUG host: Checking in: windows
DEBUG host: Found cap: smb_cleanup in windows
 INFO host: Execute capability: smb_cleanup [#<Vagrant::Environment: C:/users/[username]/PycharmProjects/ansible_flask_example/deployment>, #<Vagrant::Machine: ansible_example (VagrantPlugins::ProviderVirtualBox::Provider)>, {}] (windows)
DEBUG smb: generating machine ID name=ansible_example cwd=C:/users/[username]/PycharmProjects/ansible_flask_example/deployment
 INFO subprocess: Starting process: ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "Get-SmbShare|Format-List"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: Get-SmbShare : The term 'Get-SmbShare' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Get-SmbShare|Format-List
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-SmbShare:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31998
DEBUG subprocess: Exit status: 1
ERROR warden: Error occurred: Vagrant failed to generate a list of local SMB shares. Please try
running the command again.

**Comment by diegomanansala** [comment]
Getting the same error, but I'm on Windows 10.

https://gist.github.com/diegomanansala/fb53f7322ee37d760abddc13b2f5da19

**Comment by leem32** [comment]
Same error on Windows 7 Pro with the latest vagrant using Centos 7. Had to use nfs instead which works perfectly using [winnfsd](https://github.com/winnfsd/vagrant-winnfsdl) plugin.

**Comment by markvr** [comment]
I also get this error:
```
INFO subprocess: Starting process: ["C:\Windows\System32\WindowsPowerShell\v1.0/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "Get-SmbShare|Format-List"]
INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: Get-SmbShare : The term 'Get-SmbShare' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
```
but running it from the cmd line works ok:
```
PS C:\> C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "Get-SmbShare|Format-List"


Name        : ADMIN$
ScopeName   : *
Path        : C:\Windows
Description : Remote Admin

Name        : C
ScopeName   : *
Path        : C:\
Description :

Name        : C$
ScopeName   : *
Path        : C:\
Description : Default share

Name        : IPC$
ScopeName   : *
Path        :
Description : Remote IPC
```

Weird...I can't find any reason why it should work from manually from the cmd line, but not from within Vagrant.
