### ISSUE TITLE
SSH key update silently fails if the home directory has bad permissions

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9554]
While tinkering with Haiku guests, I noticed that the Vagrant logic for updating insecure SSH keys silently fails when the user's home directory has the wrong permissions. Vagrant continues the rest of the `vagrant up` steps, ignoring the fact that it never actually got to update the SSH key.

I had been running `mkdir -p /boot/vagrant && useradd -d vagrant` in Packer to setup the home directory. When I noticed that Haiku's `useradd` does not ensure that the home directory is actually owned by its intended user, I added a further `chown vagrant /boot/vagrant` command to my Packer configuration.

Once the home directory got the correct file permissions, `vagrant up` got further along, adding the new SSH key and attempting to reauthenticate using the new key.

### Vagrant version

Vagrant 2.0.2

### Host operating system

macOS 10.13 High Sierra

### Guest operating system

Haiku alpha4

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/haiku"
  config.ssh.sudo_command = "su user -c '%c'"
end
```

Packer source: https://github.com/mcandre/packer-templates/tree/6630511ccbba5b50e5666dcafcf38e6791b7bc92/haiku

### Expected behavior

When `vagrant up` attempts to update SSH keys, I expect Vagrant to emit an error message on file permission errors.

What should have happened?

### Actual behavior

Vagrant emitted a message that it was about to update SSH keys, then skipped ahead to provisioning the rest of the VM as if nothing had gone wrong.

### Steps to reproduce
1. `vagrant up`

**Comment by kallisti5** [comment]
@mcandre   Please keep in mind Haiku Alpha4 is extremely outdated.  The nightly images should be where the focus is. (Alpha4 was pre-package management even)

**Comment by kallisti5** [comment]
See #9553  this one might no longer be relevant

**Comment by jbonhag** [comment]
Going to close this one as key replacement works as of (at least) nightly v54142. Btw, I've had success overriding the default username as follows:

```ruby
config.ssh.username = "user"
```

rather than creating a `vagrant` user.
