### ISSUE TITLE
vagrant rsync silently fails after vagrant up loudly fails

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9556]
When the rsync phase of `vagrant up` loudly fails, such as due to a file permissions error, then successive `vagrant rsync` commands silently fail.

### Vagrant version

Vagrant 2.0.2

### Host operating system

macOS 10.13 High Sierra

### Guest operating system

Haiku alpha4

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/haiku"
  config.vm.synced_folder ".", "/boot/vagrant-src", type: "rsync"
end
```

Packer source: https://github.com/mcandre/packer-templates/tree/647b87b3624f9f8e068fe77f48b9982ca496e60d/haiku

### Expected behavior

`vagrant rsync` exits with a non-zero status and emits an message about file permission errors.

### Actual behavior

`vagrant rsync` silently terminates.

### Steps to reproduce
1. `vagrant up`
2. `vagrant rsync`

**Comment by kallisti5** [comment]
Does vagrant rsync require rsync on the guest?

If so, the following command will need to be run (with an internet connection): ```pkgman install rsync```

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
