### ISSUE TITLE
Vagrant box download hides https:// to http:// redirects

### ISSUE THREAD

**Issue by andreaso** [hashicorp/vagrant#9558]
### Vagrant version
Vagrant 2.0.2

### Host operating system
Ubuntu 17.10

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
end
```

### Expected behavior
Downloading the `ubuntu/xenial64` box gives me the following output.

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/xenial64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/xenial64'
    default: URL: https://vagrantcloud.com/ubuntu/xenial64
==> default: Adding box 'ubuntu/xenial64' (v20180309.0.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/ubuntu/boxes/xenial64/versions/20180309.0.0/providers/virtualbox.box
==> default: Successfully added box 'ubuntu/xenial64' (v20180309.0.0) for 'virtualbox'!
==> default: Importing base box 'ubuntu/xenial64'...
...
```

Only seeing https:// urls I expect that the Vagrant box is downloaded  using __https://__.

### Actual behavior
Taking a closer look I see that https://vagrantcloud.com/ubuntu/boxes/xenial64/versions/20180309.0.0/providers/virtualbox.box redirects to https://app.vagrantup.com/ubuntu/boxes/xenial64/versions/20180309.0.0/providers/virtualbox.box, which redirects to http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box, which is what gets downloaded. That is, the actual box is downloaded using __http://__.

### References
The redirect itself has gotten a separate report: https://bugs.launchpad.net/cloud-images/+bug/1754948

**Comment by briancain** [comment]
Hi @andreaso , thanks for opening an issue! This should already be resolved via #9344 and will be functional in the next release of Vagrant (2.0.3). Thanks!

**Comment by andreaso** [comment]
Thanks for the pointer! Yet, I'm not sure if I consider https://github.com/hashicorp/vagrant/pull/9344 a full fix for this particular issue. Yes, do you see that there is a redirect, and you get see the new hostname, but not the protocol. Hence, a downgrade to __http://__ is still hidden.

```
~$ /home/andreas/git/vagrant/exec/vagrant box add ubuntu/bionic64
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

==> box: Loading metadata for box 'ubuntu/bionic64'
    box: URL: https://vagrantcloud.com/ubuntu/bionic64
==> box: Adding box 'ubuntu/bionic64' (v20180310.0.0) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/ubuntu/boxes/bionic64/versions/20180310.0.0/providers/virtualbox.box
    box: Download redirected to host: cloud-images.ubuntu.com
==> box: Successfully added box 'ubuntu/bionic64' (v20180310.0.0) for 'virtualbox'!
```

@briancain

**Comment by andreaso** [comment]
But yeah, given the code which has already been adding, what remains is a really really easy fix. Just need to choose what info to extract from the `location_uri` object.

https://github.com/hashicorp/vagrant/blob/586ee5bfbabdc14da46cbce8849674afa62d5e9d/lib/vagrant/util/downloader.rb#L117

I'll gladly submit a small PR myself. Just that I don't know what would be preferable; proto+host, or the full url?

**Comment by moutons** [comment]
The full URL would be better for simple visual debugging.
