### ISSUE TITLE
Error in Vagrant: ERROR NoMethodError: undefined method `gsub' for nil:NilClass

### ISSUE THREAD

**Issue by cli0** [hashicorp/vagrant#9559]
### Vagrant version

Vagrant 2.0.2

### Host operating system

Ubuntu 16.04 

### Guest operating system

Ubuntu 16.04 

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
   config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.provider "virtualbox" do |vb|
  #   # Customize the amount of memory on the VM:
      vb.memory = 8192
      vb.cpus = 2
  #    vb.customize ["modifyvm", :id, "--memory", 8192]
  end

  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.hostname = "cli0"
  config.vm.synced_folder ".", "/home/vagrant/Setup/"
end
```

The bootstrap script only installs some basic dependencies (git, go, python, ruby etc.). Among other things I also install Fake-S3 https://github.com/jubos/fake-s3 . After that I use a simple curl command to write a file inside the fake-s3 storage. As a result I get the following error message from the s3 server:

### Debug output

https://gist.github.com/cli0/7c5bbc7d93d26144b48fcd07dc0ad2e2

### Steps to reproduce
1. Set up the latest ubuntu/xenial64 box and add some basic dependencies
2. Install fake-s3 (as per the readme of the github page)
3. Try to store something with a curl command

### Expected behavior
The file should have been stored and no error message thrown.

### Actual behavior
I get an error message "ERROR NoMethodError: undefined method `gsub' for nil:NilClass`" and nothing gets stored.

**Comment by briancain** [comment]
Hi @cli0 - The gist you provided shows that the error you're experiencing is from fake-s3, not vagrant. Please open an issue with them, thanks!
