### ISSUE TITLE
fork/exec error on WSL : invalid argument

### ISSUE THREAD

**Issue by kettro** [hashicorp/vagrant#9562]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
2.0.2, but only know from the installer

### Host operating system
Windows 10, WSL with Ubuntu 14.04.05

### Guest operating system
Can't get that far

### Vagrantfile
--

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.
https://gist.github.com/kettro/87d9e642f69c26c04701848e9b98be8a

### Expected behavior
What should have happened?
Normal output of `vagrant --version`

### Actual behavior
What actually happened?
Received `Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: invalid argument`.

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
- GH-8055

**Comment by chrisroberts** [comment]
@kettro Can you confirm if this error is still occurring with the 2.0.3 release? Thanks!

**Comment by garethellis36** [comment]
I get the same error with 2.0.3. Steps:
- `wget` latest vagrant .deb file
- `sudo dkpg -i <vagrant>.deb`
- `vagrant --version` results in `Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: invalid argument`

Windows 10, WSL Ubuntu 14.04.5

**Comment by pcanham** [comment]
tested this with version 2.0.4 as well using the 64bit version of vagrant from the following location "https://releases.hashicorp.com/vagrant/2.0.4/vagrant_2.0.4_x86_64.deb"

`vagrant --version --debug
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: invalid argument
`
`
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
`
Running under Windows 10 version 1607

**Comment by pcanham** [comment]
```
ldd /opt/vagrant/embedded/bin/ruby
        linux-vdso.so.1 =>  (0x00007fffd247f000)
        libruby.so.2.4 => /opt/vagrant/embedded/bin/../lib/libruby.so.2.4 (0x00007f6063b70000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f60637a0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6063570000)
        libgmp.so.10 => /opt/vagrant/embedded/bin/../lib/../lib/libgmp.so.10 (0x00007f60632d0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f60630c0000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f6062e70000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6062b60000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6064200000)
```

**Comment by musavih2** [comment]
Having the same issue on the same platform (Windows 10 WSL). Has any solution or workaround been found?

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
