### ISSUE TITLE
Vagrant on Windows attempts to rename with invalid filename

### ISSUE THREAD

**Issue by darkn3rd** [hashicorp/vagrant#9564]
This is either a bug, or enhancement request to not bomb at virtualbox level, and catch this earlier with more meaningful message.

### Vagrant version

```
> vagrant -v
Vagrant 2.0.2
> vboxmanage -v
5.2.8r121009
```

### Host operating system

`Microsoft Windows [Version 10.0.16299.248]`

### Guest operating system

Ubuntu 14.04 Trusty Tahr from `bento/ubuntu-14.04` box

### Vagrantfile

```ruby
TIME = Time.now.strftime('%Y-%m-%dT%H:%M:%S')
VAGRANT_BOX = 'bento/ubuntu-14.04'
PRIMARY_SYSTEM = 'a.local'

hosts = {
  'a.local' => '172.16.0.41',
  'b.local' => '172.16.0.42',
  'c.local' => '172.16.0.43'
}

Vagrant.configure('2') do |config|
  hosts.each do |hostname, ipaddr|
    default = if hostname == PRIMARY_SYSTEM then true else false end
    config.vm.define hostname, primary: default do |node|
      node.vm.box = VAGRANT_BOX
      node.vm.hostname = hostname
      node.vm.network 'private_network', ip: ipaddr
      node.vm.provider('virtualbox') { |vbox| vbox.name = "#{hostname}_#{TIME}" } # <- BAM
    end
  end
end
```

### Debug output

Upon request, not needed for this.

### Expected behavior

The vagrant up process would not result in renaming a directory to an invalid file name.  

### Actual behavior

```
==> a.local: Setting the name of the VM: a.local_2018-03-12T14:45:59
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["modifyvm", "604288dc-f351-4cf8-8449-8a5cf24165fa", "--name", "a.local_2018-03-12T14:45:59"]

Stderr: VBoxManage.exe: error: Could not rename the directory 'C:\Users\joaquin\VirtualBox VMs\ubuntu-14.04-amd64_152089
1170952_57258' to 'C:\Users\joaquin\VirtualBox VMs\a.local_2018-03-12T14:45:59' to save the settings file (VERR_INVA
LID_NAME)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 3111 of file VBoxManageModifyVM.cpp
```

### Steps to reproduce
1.  In `Vagrantfile` for virtualbox config block, have `v.name = 'my:new:name'`
2.  `vagrant up`
3.  BOOM

**Comment by fsustim** [comment]
I run into the same error today on Ubuntu.  How did fix the 'can not rename...' error?

**Comment by chrisroberts** [comment]
This is an issue of attempting to use invalid characters for the VM name that virtualbox does not support. The correct action would be to remove invalid characters from the name (in the original example the `:` characters).

Cheers!
