### ISSUE TITLE
Unable to use SMB shared folders on OSX (10.13.2) host and FreeBSD 10.3 guest

### ISSUE THREAD

**Issue by davecranwell-adestra** [hashicorp/vagrant#9567]
### Vagrant version
2.0.2

### Host operating system
OSX 10.13.2

### Guest operating system
freeBSD 10.3 (bento/freebsd-10.3)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/freebsd-10.3"
 
  config.vm.network "forwarded_port", guest: 8000, host: 8000, auto_correct: true
  config.vm.network "forwarded_port", guest: 8001, host: 8001, auto_correct: true

  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder "./amf", "/home/vagrant/shared-amfroot", type: "smb" #create:true, smb_password: 'vagrant', smb_username: 'vagrant', mount_options: ["username=vagrant","password=vagrant"] #type: "rsync", rsync__exclude: ["node_modules/"], rsync__args: ["--verbose", "--archive", "--delete", "--copy-links"]

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.customize ["modifyvm",:id,"--memory","2048"]
  end
  
  config.ssh.forward_agent = true

  config.vm.provision "shell" do |shell|
    shell.inline = "pkg install -y python && ln -s /usr/local/bin/python /usr/local/python || true"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.inventory_path = "ansible/hosts"
    ansible.limit = "vagrant-dev"
    # ansible.tags = ['git']
    ansible.playbook = "ansible/playbooks/dev-server.yml"
  end
end

```

### Debug output
https://gist.github.com/davecranwell-adestra/9d596282c41a6fe24dff9ecec4f570d2

### Expected behavior
It should work , or fail with a helpful explanation of exactly what part failed with steps to mitigate it, tailored to my host env. 

### Actual behavior
Always receive message 
> Vagrant SMB synced folders require the account password to be stored
in an NT compatible format. Please update your sharing settings to
enable a Windows compatible password and try again.

### Further information
I've followed all the steps here https://www.vagrantup.com/docs/synced-folders/smb.html

My Mac's login is Active Directory controlled by our IT team, so i've created a new "vagrant" user in the OSX Sharing settings.

I can see no mention of a _lack_ of freeBSD support, but perhaps my specific bento box doesn't contain the right packages on the guest side? I would expect a different error message if that were true.

**Edit**: I've since double checked samba on guest by installing samba44. It's unclear from your documentation whether it's expected to be running at startup on the guest. I haven't bothered to configure it yet, but the error message from Vagrant remains the same as before.

**Comment by briancain** [comment]
Just to double check, is this setting is enabled? If not, you will end up with that error on macOS.

<img width="780" alt="screen shot 2018-03-13 at 8 56 29 am" src="https://user-images.githubusercontent.com/810277/37353385-78f088b6-269c-11e8-9d53-1f9a0a3086e0.png">

**Comment by davecranwell-adestra** [comment]
![screen shot 2018-03-13 at 17 07 07](https://user-images.githubusercontent.com/33837371/37357692-fe029fb4-26e0-11e8-9685-64459ab7a4f7.png)

Yup. However as I mentioned I've had to set up a "vagrant" user rather than use my actual osx login user. Dunno if that's related.

**Comment by davecranwell-adestra** [comment]
Added note that I have now installed samba44 on the FreeBSD guest, but it's unclear from the vagranup.com docs what the status of samba is expected to be: should the samba software merely be installed on the guest, or should it be running and fully configured?

**Comment by briancain** [comment]
Is the share you're trying to mount on your user, or the vagrant user? If it's on your local user that's running `vagrant`, I imagine that's why you are getting that error message. According to the docs:

> To use the SMB synced folder type on a macOS host, file sharing must be enabled for the local account

If you can figure out why you aren't showing up and enable that for your local user, I imagine it should work?

**Comment by davecranwell-adestra** [comment]
Thanks, I'll chat with IT and see if they can somehow make my AD user visible within OSX.

**Comment by briancain** [comment]
I'll go ahead and close this since it seems to be working as expected. If you need more help I recommend emailing the vagrantup google group, thanks! :)

**Comment by VimukthiPerera** [comment]
I have fixed this error by adding the following line to the Vagrantfile:

`server_config.vm.synced_folder ".", "/vagrant", disabled: true`

I got the above error with the setting that pointed out by @briancain is enabled.

**Comment by davecranwell-adestra** [comment]
@VimukthiPerera Doesn't that disable the syncing of that folder?

**Comment by VimukthiPerera** [comment]
@davecranwell-adestra of course it does. I could not figure out how to fix the problem or what caused the problem. Only disabling the sync worked and thought everyone should know. :)

**Comment by shirts** [comment]
I was also running into this issue on macOS. The snippet @VimukthiPerera posted works fine, however If you'd like to keep syncing enabled, changing it to rsync should fix the problem:

```
config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
```

https://www.vagrantup.com/docs/synced-folders/rsync.html
