### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by moda20** [hashicorp/vagrant#9568]
I am running the quorum 7 nodes example and i encountered this error when running vagrant up. This is not the first time i run vagrant up, but this is the first time i get this error.

### Vagrant version
Vagrant 2.0.2

### Host operating system
arch linux Zen

### Guest operating system
Ubuntu Xenial

### Vagrantfile
```
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "vagrant/bootstrap.sh"
  config.vm.network "forwarded_port", guest: 22000, host: 22000
  config.vm.network "forwarded_port", guest: 22001, host: 22001
  config.vm.network "forwarded_port", guest: 22002, host: 22002
  config.vm.network "forwarded_port", guest: 22003, host: 22003
  config.vm.network "forwarded_port", guest: 22004, host: 22004
  config.vm.network "forwarded_port", guest: 22005, host: 22005
  config.vm.network "forwarded_port", guest: 22006, host: 22006
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end
end
```

### Debug output
https://gist.github.com/moda20/e436e5513c3851b50d28d2e90576f444

### Expected behavior
install all dependencies  of the VM

### Actual behavior
exported an error.

**Comment by chrisroberts** [comment]
Latest release resolves the automatic exception output so closing this up.
