### ISSUE TITLE
rsync synced folder randomly fails silently

### ISSUE THREAD

**Issue by tuminoid** [hashicorp/vagrant#9571]
### Vagrant version
`Vagrant 2.0.2`

### Host operating system
Ubuntu 16.04.4 LTS

### Guest operating system
Issue has been seen in RHEL 7.4 and Debian Jessie

### Vagrantfile
```ruby
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
```

### Debug output
No debug output, happens randomly, like 1 out of 100.

### Expected behavior
Files from current dir get synced to box's `/vagrant`.

### Actual behavior
Random files and/or directories are missing from `/vagrant`.

### Steps to reproduce
1. `vagrant up`
2. Provisioning fails as they try to read files from `/vagrant` and they're missing

### Info
Rsync just randomly fails to sync all the files from source to target. Random files or directories are missing. This occurs randomly and not very often, so it is hard to catch. Maybe 1 out of 100. Vagrant or rsync do not produce any output that would indicate a failure, and failure is only noticed when supposedly synced file is being read and it is not there.

**Comment by chrisroberts** [comment]
Hi there,

With no way to reproduce this error there is not really any action that can be taken at this time. If you run your `vagrant up`s with `--debug` and capture the output for the occasion when this behavior exhibits itself, please open a new issue with the debug output and we can investigate further.

Thanks!
