### ISSUE TITLE
Alpine guest

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9574]
Could Vagrant get a guest plugin for Alpine Linux?

* Default `config.ssh.shell` to `ash`
* Install rsync command: `apk add -U rsync`
* Halt command: `poweroff`

**Comment by ladar** [comment]
Are you aware of the generic Alpine base images? They should have the open-vm-tools setup already. Try:

`vagrant init generic/alpine37 && vagrant up`
or
`vagrant init generic/alpine38 && vagrant up`

If you want to change the default shell from bash to ash, it's easy enough. Just add a provisioning script to the Vagrantfile, like so:

```ruby
config.vm.provision "shell", run: "always", inline: <<-SHELL
  sudo sed -i "s/\(^vagrant.*\)bash/\1ash/g" /etc/passwd
SHELL
```

**Comment by mcandre** [comment]
No, the whole point of a guest plugin is to AVOID having to manually write such boilerplate in our Vagrantfiles.

**Comment by briancain** [comment]
Closing this, as it has already been done, merged, and shipped!
