### ISSUE TITLE
Vagrant on Windows with GitBash

### ISSUE THREAD

**Issue by Raffaello** [hashicorp/vagrant#9577]
### Vagrant version
2.0.2

### Host operating system
Windows 10, running witinh GitBash (MinGW)

### Guest operating system
Ubuntu

### Actual behavior
```
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:37:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:37:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:31:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:31:in `<main>'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:37:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:37:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:31:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.2/bin/vagrant:31:in `<main>'
```
### Steps to reproduce
1. Install Git for windows and run the git CLI (you should be in a mingw env)
2. try to run a vagrant using a vagrant-host plugin
3. you should have the error reported.

**Comment by chrisroberts** [comment]
Hi there,

This error can some times happen due to the size of the environment being too large (all the currently set environment variables). Can you check the environment variables you have defined in your environment, and reduce the number or the size of the values where possible and try running the command again?

**Comment by Raffaello** [comment]
I provision for a normal command prompt. Now if i have just to spin up or down the machine i have no more issues. So I cannot go further in this ticket. For me can be closed. Thanks

**Comment by NameTheJew** [comment]
Im also having this problem
Trying to install CoreOS via Vagrant 2.1.2 onto VirtualBox Version 5.2.12 r122591 (Qt5.6.2)
HOST: Window 7
1 . Download and extract https://github.com/coreos/coreos-vagrant
2 . rename config.rb & user-data
3 . open cmd
4 . cd /coreos-vagrant-master dir
5 . vagrant up
6 . Get the following error
```
C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `[]=': Invalid argument - ruby_setenv(VAGRANT_NO_PLUGINS) (Errno::EINVAL)
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:47:in `block in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:36:in `each_index'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vag
```

Trying to follow this CoreOS guide
https://coreos.com/os/docs/latest/booting-on-vagrant.html

**Comment by fgerards** [comment]
also having this issue after updating to vagrant 2.1.2 from 2.0.2 - nothing else changed

**Comment by elzzz** [comment]
FIX FOR WINDOWS 10 AND VAGRANT 2.1.2 (via GitBash):
```
vim /c/HashiCorp/Vagrant/embedded/mingw64/bin/gem

#!/c/HashiCorp/Vagrant/embedded/mingw64/bin/ruby.exe
```

**Comment by klxg5** [comment]
@elzzz Thanks, however, I am still getting the same error. I assume I am supposed to replace

#!/usr/bin/env ruby
with
#!/c/HashiCorp/Vagrant/embedded/mingw64/bin/ruby.exe

Is this correct? I am also running windows 10 with vagrant 2.1.2

**Comment by elzzz** [comment]
@klxg5 Yes, you should replace it. If you have installed vagrant to C:\HashCorp\Vagrant\ and you have ruby.exe in C:\HashiCorp\Vagrant\embedded\mingw64\bin\ruby.exe you should replace 1 line in C:\HashiCorp\Vagrant\embedded\mingw64\bin\gem
```
#!/usr/bin/env ruby
to
#!/c/HashiCorp/Vagrant/embedded/mingw64/bin/ruby.exe
```
After that use gitbash to vagrant up. It worked for me.
