### ISSUE TITLE
vagrant download is SLOW

### ISSUE THREAD

**Issue by marcoflorian** [hashicorp/vagrant#9580]
Downloading: https://vagrantcloud.com/...
Progress: 0% (Rate: 19841/s, Estimated time remaining: 8:19:57)

WHY IS THIS SO SLOW?

**Comment by chrisroberts** [comment]
Duplicate #8434

**Comment by mrwen00** [comment]
To resolve this problem, first you should download box with wget, axel or any other tools.
For example: https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1905_01.VirtualBox.box

Then execute it:
$ vagrant box add centos/7 CentOS-7-x86_64-Vagrant-1905_01.VirtualBox.box

In Vagrantfile:
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end

Now vagrant will add the box which downloaded into vagrant list box.
