### ISSUE TITLE
Can not specify a box version with a direct box file

### ISSUE THREAD

**Issue by marcoflorian** [hashicorp/vagrant#9581]
Since downloading through TERMINAL is REALLY SLOW. I downloaded the file manually and I am trying to add the box manually too. Although, I am not able to set the box version.

vagrant box add --box-version VERSION --name NAME --force file:///PATH

==> box: Box file was not detected as metadata. Adding it directly...
You specified a box version constraint with a direct box file
path. Box version constraints only work with boxes from Vagrant
Cloud or a custom box host. Please remove the version constraint
and try again.

How can I do this?

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. Thank you and have a great day! 😄
