### ISSUE TITLE
config.vm.box_url file:// broken in Vagrant 2.0.3

### ISSUE THREAD

**Issue by localhorst-org** [hashicorp/vagrant#9582]
### Vagrant version
> vagrant version
Installed Version: 2.0.3
Latest Version: 2.0.2

### Host operating system
Window  10 Pro
Version 1709
Build	16299.309

### Guest operating system
VirtualBox 5.2.8 
Ubuntu 16.04

### Vagrantfile
peace of code from Vagratfile

[...]
  config.vm.box = "ciss-vagrant-ubuntu1604"
  config.vm.box_url = "file://D:/virtualboxvm/ciss-vagrant-ubuntu1604-box.json"
  #config.vm.box_url = "https://<subdownload>.localhorst.org/box/ciss/ciss-vagrant-ubuntu1604-box.json"
  config.vm.hostname = "devubuntuciss"
[...]

### After upgrade to Vagrant 2.0.3 my self new build Box comes not up
> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ciss-vagrant-ubuntu1604' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'file://D:/virtualboxvm/ciss-vagrant-ubuntu1604-box.json'
    default: URL: file://D:/virtualboxvm/ciss-vagrant-ubuntu1604-box.json
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Invalid file://hostname/, expected localhost or 127.0.0.1 or none

If i switch in the Vagrantfile to the  config.vm.box_url = https:// the box is comming up in the usual way..

### Downgrade to Vagrant 2.0.2
> vagrant version
Installed Version: 2.0.2
Latest Version: 2.0.2

### The file URL is working in the usual way for me
> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ciss-vagrant-ubuntu1604' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'file://D:/virtualboxvm/ciss-vagrant-ubuntu1604-box.json'
    default: URL: file://D:/virtualboxvm/ciss-vagrant-ubuntu1604-box.json
==> default: Adding box 'ciss-vagrant-ubuntu1604' (v20180316) for provider: virtualbox
    default: Unpacking necessary files from: file://D:/virtualboxvm/ciss-vagrant-ubuntu1604-20180316.box
    default: Progress: 80% (Rate: 226M/s, Estimated time remaining: 0:00:01)
[...]
    default: Calculating and comparing box checksum...
==> default: Successfully added box 'ciss-vagrant-ubuntu1604' (v20180316) for 'virtualbox'!
==> default: Importing base box 'ciss-vagrant-ubuntu1604'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ciss-vagrant-ubuntu1604' is up to date...
==> default: Setting the name of the VM: devubuntuciss
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
[...]

-> box is comming up in the usual way.

thx in advance

**Comment by chrisroberts** [comment]
Hi there,

Would you please provide a gist of the output using the `--debug` flag. Thanks!

**Comment by localhorst-org** [comment]
hi chris roberts,

please be not astonished. i switched the computer. the software and windows
version are absolutly the same. but the box file path and file name are a
little bit diffrent. the beahvior switch from vagrant 2.0.2 to 2.0.3 is the
same and i create a debug log.

> vagrant version
Installed Version: 2.0.3
Latest Version: 2.0.3

short output

> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'vagrant-ubuntu' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'file://C:/hptmp/vagrantbox/vagrant-ubuntu.json'
    default: URL: file://C:/hptmp/vagrantbox/vagrant-ubuntu.json
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Invalid file://hostname/, expected localhost or 127.0.0.1 or none


debug log 

> vagrant up --debug 2>&1 | Tee-Object -FilePath ".\vagrant_fileurl_203.log"

https://gist.github.com/localhorst-org/fa9a52285d5da85a1c5371ba3075a430#file-vagrant_fileurl_203-log


switch back to vagrant 2.0.2

> vagrant version
Installed Version: 2.0.2
Latest Version: 2.0.3

> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'vagrant-ubuntu' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'file://C:/hptmp/vagrantbox/vagrant-ubuntu.json'
    default: URL: file://C:/hptmp/vagrantbox/vagrant-ubuntu.json
==> default: Adding box 'vagrant-ubuntu' (v20180308) for provider: virtualbox
    default: Unpacking necessary files from: file://C:/hptmp/vagrantbox/vagrant-ubuntu-20180308.box
    default:
    default: Calculating and comparing box checksum...
[...]
    default: Calculating and comparing box checksum...
==> default: Successfully added box 'vagrant-ubuntu' (v20180308) for 'virtualbox'!
==> default: Importing base box 'vagrant-ubuntu'...
Progress: 10%
[...]
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'vagrant-ubuntu' is up to date...
==> default: Setting the name of the VM: devubu
==> default: Clearing any previously set network interfaces...
==> default: Specific bridge '["en1: Intel(R) Ethernet Connection I219-LM", "en2: Intel(R) Dual Band Wireless-AC 8260"]' not found. You may be asked to specify
==> default: which network to bridge to.
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly

-> worked with vagrant 2.0.2 as ususal

kind regards horst

**Comment by sebastiaanluca** [comment]
Maybe related, but upgrading to 2.0.3 bricked vagrant on macOS 12.10.6. I don't have the logs anymore after downgrading to 2.0.2 where everything works, but basically it complained about invalid URLs for all my boxes when running *any* vagrant command.

**Comment by CorePlusPlus** [comment]
I encountered the same problem like localhorst-org

**Comment by chrisroberts** [comment]
Hi there,

The 2.0.4 release of Vagrant includes a patched version of curl which fixes the `file://` protocol usage.

Cheers!

**Comment by chrisroberts** [comment]
@localhorst-org Can you try updating your `box_url` value to match below:

```ruby
config.vm.box_url = "file:///D:/virtualboxvm/ciss-vagrant-ubuntu1604-box.json"
```

Please notice the extra `/` before the `D:`.

Thanks!

**Comment by localhorst-org** [comment]
@chrisroberts,

in my first try yesterday, i  thought to short. i changed the box_url with to the three /// and get an error. i have to change the url on both playces. in the Vagrant file

config.vm.box_url = "file:///D:/virtualboxvm/ciss-vagrant-ubuntu1604-box.json"

and the Json file.

"url": "file:///D:/virtualboxvm/ciss-vagrant-ubuntu1604-20180423.box"

and now it works again as expected.

Thank you for your patience. 

Kind regards Horst

**Comment by dgonano** [comment]
I'm still having this issue with 2.0.4. 
```
ubuntu14dev.vm.box = "company/parc-ubuntu14"
ubuntu14dev.vm.box_url = "../ubuntu_14/metadata.json"
ubuntu14dev.vm.box_version = "1.0.0"
````
The JSON file contains all the details about box versions and URLs etc. 
I've tried `file://../ubuntu_14/metadata.json` but no luck. 

It's relative as its part of a repo people clone is different places, and it worked with 2.0.0. 
Thoughts? Am I using it how its not supposed to be used?
