### ISSUE TITLE
Vagrant show failed about stdout

### ISSUE THREAD

**Issue by letanphucoro** [hashicorp/vagrant#9590]
When I run "vagrant up" and not start vagrant.
It show errors like this:

![vagrant_error](https://user-images.githubusercontent.com/20813513/37581346-c8ac5fb4-2b7a-11e8-99b0-9015b7e03198.PNG)

How to resolve it?
I hope about helpful!

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!
