### ISSUE TITLE
`vagrant ssh` error when custom ssh config set

### ISSUE THREAD

**Issue by Willian-Zhang** [hashicorp/vagrant#9601]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
Vagrant 2.0.3

### Host operating system
This is the operating system that you run locally.
macOS 10.13.3 (17D102)

### Guest operating system
This is the operating system you run in the virtual machine.
ubuntu/xenial64 (20180313.0.0)

### Vagrantfile
Actaully a clear new vagrant file would be the same.
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/xenial64"
  # set up network ip and port forwarding
  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "512"
    vb.cpus = 1
    # Fixes some DNS issues on some networks
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  # Copy your .gitconfig file so that your git credentials are correct
  if File.exists?(File.expand_path("~/.gitconfig"))
    config.vm.provision "file", source: "~/.gitconfig", destination: "~/.gitconfig"
  end

  # Copy your ssh keys for github so that your git credentials work
  if File.exists?(File.expand_path("~/.ssh/id_rsa"))
    config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  end
  
  # Change the permission of files and directories
  # so that nosetests runs without extra arguments.
  config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=775,fmode=664"]
  
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git python-pip python-dev build-essential
    pip install --upgrade pip
    apt-get -y autoremove
    # Make vi look nice
    sudo -H -u ubuntu echo "colorscheme desert" > ~/.vimrc
    # Install app dependencies
    cd /vagrant
    sudo pip install -r requirements.txt
  SHELL

end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### `~/.ssh/config`
```
Host *
  PreferredAuthentications keyboard-interactive,password
  UseKeychain yes
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?
```
$ vagrant ssh
Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-116-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud


```

### Actual behavior
What actually happened?
```
$ vagrant ssh
vagrant@127.0.0.1: Permission denied (publickey).
```

### Steps to reproduce
0. setup your own `~/.ssh/config`
1. `vagrant up`
2. `vagrant ssh`

### References
Are there any other GitHub issues (open or closed) that should be linked here?
n/a

**Comment by Willian-Zhang** [comment]
I have a good reason that I set my own ssh config as:
`PreferredAuthentications keyboard-interactive,password`

Most Linux SSH Policy restrict retry number of ssh access.
If you are like me, managing multiple remote servers (other than vagrant), you would have many key-trys before actually passwording into a password-enabled remote server.
So that will cause the server to reject requests when during the key-tries.

Setting default policy to `password` actually avoid sending keys before actually trying to type-in a password, and all other key servers are configured using `IdentityFile`.

Please let me know if there's a better way to manage these. 

What so ever, this is an unwanted behavior.
Also for people the same issue as me, my current work-around  is adding below to my ssh config.
```
# Vagrant SSH
Host 127.0.0.1
  PreferredAuthentications gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive
```

**Comment by atulanandnitt** [comment]
@Willian-Zhang : can u pls suggest,   How can I get ssh config ?

**Comment by JuPlutonic** [comment]
@atulanandnitt I'm use C:\Program Files\OpenSSH-Win64\ example file
1. put it to C:\Users\$USER\.ssh or that 
2. vagrant ssh -- -vvv cold give errors with reference to  C:\Users\$USER\.ssh\config file line numbers
3. comment out that lines 
4. 
you could uncomment line 51 `PasswordAuthentification yes` (if you don't want to use key files)
and add `ChallengeResponseAuthentication yes` (if putty don't understand private_key)

**Comment by chrisroberts** [comment]
Hi there,

Vagrant will not use the host's local ssh configuration file, nor the keys unless it is instructed to within the Vagrantfile configuration. However, based on your Vagrantfile comments, it appears you are using this for accessing GitHub from the guest. Instead of pushing your private key to the guest, you can enable the forward agent setting in your Vagrantfile and have the key available for you that way:

https://www.vagrantup.com/docs/vagrantfile/ssh_settings.html#config-ssh-forward_agent

Cheers!
