### ISSUE TITLE
Ansible provisioner forces VM to shutdown ()

### ISSUE THREAD

**Issue by clubery** [hashicorp/vagrant#9603]
### Vagrant version
Vagrant 2.0.0

### Host operating system
macOS 10.12.6

### Guest operating system
ubuntu/trusty64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.99.110"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "play.yml"
    ansible.verbose = "vvvv"
   end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/clubery/4df5aba9e74e13cea9c263c6b8eb28e4

### Expected behavior
Vagrant box starts up after being provisioned with ansible

### Actual behavior
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: vtest_default_1521641500990_69661
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.1
==> default: [vagrant-dns] TLD but no host_name given. No patterns will be configured.
pid-file for killed process 18594 found (/Users/devuser/.vagrant.d/tmp/dns/daemon/vagrant-dns.pid), deleting.
vagrant-dns: process with pid 19036 started.
==> default: Restarted DNS Service
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /opt/dev/vtest
==> default: Running provisioner: ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.4.3.0).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

==> default: Destroying VM and associated drives...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "00d471f5-0f62-4a6a-baf3-8bc47bba3421", "--machinereadable"]

Stderr: VBoxManage: error: Could not find a registered machine with UUID {00d471f5-0f62-4a6a-baf3-8bc47bba3421}
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2776 of file VBoxManageInfo.cpp

```

### Steps to reproduce
1. Create playbook file named play.yml with the following content:
```
---
hosts: "default"
tasks:
  debug:
    msg: "Hello world"
```
2. Create a Vagrantfile in the same directory as play.yml with the following content:
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.99.110"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "play.yml"
    ansible.verbose = "vvvv"
   end
end
```
3. Run vagrant up

I know the logs here will show that I am using Vagrant 2.0.0 and Virtualbox 5.1.
This is a result of me downgrading after this bug manifested in the latest versions for me.
I have looked at many "similar" issues to this but nothing seems to solve it, so upgrading isn't going to help here. I also removed both the virtualbox and vagrant completely and tried installing the homebrew cask versions. Still the same result. I have also deleted the ~/.vagrant.d/ directory each time I did a new install. Any help would be appreciated.

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by gildegoma** [comment]
@clubery at first glance, it looks more like a VirtualBox integration problem (although I'm quite surprised by the debug sequence in the gist):

Could you please try the following changes and give us the results, so we can better figure out what the root cause could be:

1. Upgrade to Vagrant 2.0.3 (and maybe to Virtualbox 5.2) 
1. The `ubuntu/trusty64` base box comes with a quite old version of the virtualbox guest additions (v4.3.36), and you're running Virtualbox 5.1. What happens if you install more recent guest addtions, or use another base box (like for instance [`bento/ubuntu-16.04`](https://app.vagrantup.com/bento/boxes/ubuntu-16.04), which is baked with guest additions v5.2.x) ?
1. Replace the `ansible` provisioner block with a dummy `shell` provisioner. For instance:
    ```
    config.vm.provision "shell",
      inline: "echo Hello, World"
    ```
1. Try a `vagrant up` without any provisioner configured (or maybe with a `vagrant up --no-provisioner`)

I'm curious to see if the same VM shutdown problem persists in each of the above steps...

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
