### ISSUE TITLE
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104

### ISSUE THREAD

**Issue by remikkrezel** [hashicorp/vagrant#9612]
There is a problem after vagrant up. After couple of seconds cli shows:  OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104 with virtualbox 5.2. When installed vbox 5.1 the error is: GnuTLS recv error (-54): Error in the pull function. What is wrong? Please help

**Comment by briancain** [comment]
Hi there,

Thank you for opening an issue. However, there is not enough information here to reproduce or provide a recommendation. When you first open an issue, a template is pre-filled in the box. That template provides instructions for getting your host and guest information, the version of Vagrant, and the debug output. Without that information, it is very challenging for us to assist you.

Please supply that information either by updating this ticket or by closing this ticket and opening a new one. Thank you!

**Comment by remikkrezel** [comment]
What is the command to get this template?

**Comment by briancain** [comment]
@remikkrezel - when you open an issue on github it automatically fills the box with the template.

**Comment by remikkrezel** [comment]
### Vagrant version

Vagrant 2.0.3

### Host operating system
Ubuntu 16.04 LTS

### Guest operating system

laravel/homestead

### Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "laravel/homestead"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```


### Debug output
https://gist.github.com/remikkrezel/ae74aec9034b2ca080a04b02894f3ed3

### Expected behavior

Download larave/homestead

### Actual behavior

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104

### Steps to reproduce
1. Installing Vagrant 
2. mkdir ~/Vagrant
3. vagrant init laravel/homestead
4. vagrant up
also tried:
1. vagrant box add laravel/homestead --insecure

**Comment by briancain** [comment]
@remikkrezel - are you able to add other boxes from vagrant cloud? Or does it just happen with `laravel/homestead`?

**Comment by remikkrezel** [comment]
only with homestead

**Comment by remikkrezel** [comment]
What can I do to solve this problem? I assume that this is server side issue

**Comment by lzomedia** [comment]
I have the same issue when updating to a different box  Scotchbox v 3.5 from 3

**Comment by chrisroberts** [comment]
Hi there. This looks to be a local connectivity issue. You can see the box download get to 77.5M of the box downloaded, and then the download speed drops and does not recover. After some time the server resets the connection. Please try to download the box again.

Cheers!

**Comment by sean9999** [comment]
i experienced the same issue trying to get a bento box ( centos 7.4 for virtualbox )

**Comment by sean9999** [comment]
it appears to be a networking issue between hashicorp and S3

**Comment by remikkrezel** [comment]
Yes, I tried download box in other network and it works

**Comment by mjscosta** [comment]
Same problem here, same solution, tried another network ...

**Comment by bearrito** [comment]
Same issue here. Different box.

**Comment by poldelgado** [comment]
I 've the same issue, how can i try another network??

**Comment by mjscosta** [comment]
I had a mobile network instead of the ADSL/Cable.

This issue, might be related with timeouts of the underlying communication protocol, It would require some investigation, it would be nice to know, the OS where this "bug" is being detected. 

1- Does vagrant packs its own openssl, or it is OS dependent ?
2- Do all of you guys, have the issue in the same OS, which OS/version do you have the bug?

**Comment by poldelgado** [comment]
I've the same issue, i'm using ubuntu 18.04

**Comment by SreeChandan** [comment]
Im facing this error code to0 with errno. 10054. Im on windows 10.
If this problem is with downloading files cant we just download them normally(not from command prompt). And then put them in the folder. That might have sounded a bit redundant as this is supposed to be an automated tool. Hope there is a workaround within vagrant.

**Comment by ibrasec** [comment]
I am facing the same issue adding box bento/ubuntu-16.04 
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/ubuntu-16.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: = 2.3.5
==> default: Loading metadata for box 'bento/ubuntu-16.04'
    default: URL: https://vagrantcloud.com/bento/ubuntu-16.04
==> default: Adding box 'bento/ubuntu-16.04' (v2.3.5) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/2.3.5/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104

**Comment by lzomedia** [comment]
the problem in my case was with the network

**Comment by lzomedia** [comment]
me after some problems I've decided to go with docker and I found http://devilbox.org quite useful for my local projects

**Comment by codeandrew** [comment]
<img width="860" alt="screen shot 2018-07-31 at 5 33 45 pm" src="https://user-images.githubusercontent.com/21142513/43451619-f0713494-94e7-11e8-842c-0a2b2ef71821.png">

Also encountered this error on the first install 
```
$ vagrant init hashicorp/precise64
$ vagrant up
```

Always stops at one point. 
But I managed to  install it after several tries. 

Tried switching to different networks

**Comment by casivaagustin** [comment]
This is a workaround that might help to fix it without change the network

> vagrant box add --insecure laravel/homestead

**Comment by roshimon** [comment]
@casivaagustin Unfortunately that didn't work for me.

**Comment by ysksn** [comment]
![errno104](https://user-images.githubusercontent.com/1235270/44297229-f5944180-a308-11e8-850b-aaa6a36bcbe8.png)

I had faced the same issue downloading docker-compose today. However, `curl`ing after a couple of minutes didn't help me at all. Eventually, I used another network(ISP) to download it without any issue.

**Comment by Dusak** [comment]
i face this  problem  and It is a connection problem

**Comment by adiec7** [comment]
i'm having same issue no solution yet

**Comment by antoniogregorio** [comment]
I did it...and worked fine, Thanks.

**Comment by alam-jahangir** [comment]
I faced this same problem. It's network speed problem to download vagrant  development environment like ( vm.box=../centos-x.x ).

**Comment by tbernacchi** [comment]
Same issue here:

➜  vagrant vagrant box add --insecure ubuntu/bionic64 
==> box: Loading metadata for box 'ubuntu/bionic64'
    box: URL: https://vagrantcloud.com/ubuntu/bionic64
==> box: Adding box 'ubuntu/bionic64' (v20191010.0.0) for provider: virtualbox
    box: Downloading: https://vagrantcloud.com/ubuntu/boxes/bionic64/versions/20191010.0.0/providers/virtualbox.box
==> box: Box download is resuming from prior download progress
    box: Download redirected to host: cloud-images.ubuntu.com
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
