### ISSUE TITLE
Vagrant VMware Workstation plugin: installation hangs on domain controlled host

### ISSUE THREAD

**Issue by isarpreiss** [hashicorp/vagrant#9619]
### Vagrant version
Vagrant: 2.0.3, reproduceable since 2.0.0, 1.9.X versions doesn't seem to be affected.
Plugin: vagrant-ware-workstation plugin 5.0.4, reproduceable since 5.0.0, 4.0.X versions doesn't seem to be affected.
VMWare: VMware Workstation Pro14

### Host operating system
Windows 10 Enterprise 
Version 1703
OS Build 15063.909
Domain controlled user, local user with administrator rights.

### Expected behavior
Calling 'vagrant plugin install vagrant-vmware-workstation' should install the latest version of the plugin (atm. 2.0.5). A process which has already an elevated token doesn't need to check for further administrator users / groups. 

### Actual behavior

The user started CMD console with elevated process token (Run as admin) and runs 'vagrant plugin install vagrant-vmware-workstation'. The installation starts, downloads the required files and doesn't comeback. 

Using the ProcessExplorer reveils, the "vagrant-vmware-installer_windows_amd64.exe" execuable calls WMI which doesn't come back. The call queries for the name of an user (probably the administrator) with the id-ending '-500' :
```cmd
C:\windows\system32\wbem\wmic.exe useraccount where "SID like 'S-1-5-%-500'" get name
```
Although the current user has admin priviliges, there is no such local user with an id ending on "-500" and the call doesn't finish or takes way to long, since the domain is quite large. 

![vagrant_issue](https://user-images.githubusercontent.com/37658424/37908615-0bbe74b6-3109-11e8-848f-69bee4530d2a.PNG)

### Steps to reproduce
1. Get a domain controlled environment
2. Install Vagrant and VMware Workstation 14
3. Install the latest vagrant-vmware-workstation plugin -> should fail
4. Try the same with e.g. Vagrant 1.9.6, Workstation 12 and Plugin <5.0.0 -> should work

### References
- GH #9167 (seems similar with another plugin, but i don't even get the question for administrator rights.)

**Comment by chrisroberts** [comment]
Hi there,

I'm sorry you are running into this problem. A new VMware plugin has been released and the installer does not use `wmci.exe` which is the root of your issue here. You can read more about the plugin release here:

https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

and installation instructions here:

https://www.vagrantup.com/docs/vmware/installation.html

Cheers!
