### ISSUE TITLE
Documentation on Vagrant Cloud box upload is out of date

### ISSUE THREAD

**Issue by starrychloe** [hashicorp/vagrant#9621]
When trying to upload a box, the documentation states that you will get a JSON response with an upload URL.

https://www.vagrantup.com/docs/vagrant-cloud/boxes/create.html#creating-boxes-with-the-api

However, when I did this, I was given HTML output instead. 

```
$ curl 'https://vagrantcloud.com/api/v1/box/starrychloe/qmp-nycmesh-3.2.1/version/1.0.0/provider/virtualbox/upload?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
<html><body>You are being <a href="https://app.vagrantup.com/api/v1/box/starrychloe/qmp-nycmesh-3.2.1/version/1.0.0/provider/virtualbox/upload?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx">redirected</a>.</body></html>
```

It wasn't obvious, but I had to copy & paste the anchor link into a browser, which _then_ presented the upload URL.

```
{"upload_path":"https://archivist.vagrantup.com/v1/object/eyJhbGciOiJIUzI1NiIsInR5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
```

### Vagrant version
Irrelevant

**Comment by briancain** [comment]
Hi @starrychloe - Thanks for the report. This will be fixed soon once we deploy a new version of Vagrant Cloud. Thanks!
