### ISSUE TITLE
Random timeouts on vagrant up and vmware workstation 9

### ISSUE THREAD

**Issue by rupebac** [hashicorp/vagrant#9623]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Vagrant 2.0.2

### Host operating system
Windows 10

### Guest operating system
Win7PESE

### Vagrantfile
the configuration bit (without the provisioning or other preparation code):

```ruby
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = baseBoxName
  config.vm.box_check_update = true
  config.vm.box_url = [ jsonUrl ]

  config.vm.provider "vmware_workstation" do |v|
    v.gui = false
    v.vmx["numvcpus"] = "2"
    v.vmx["memsize"] = "1024"
    v.vmx['displayname'] = displayName
  end

  #config.vm.guest = :windows
  config.vm.communicator="ssh"
  if ARGV[0]=='up' or ARGV[0]=='provision' or ARGV[0]=='reload' then
	config.ssh.private_key_path=dir+"\\id_rsa"
  end
  config.ssh.shell = "cmd /C vagrant-shell.bat & exit 0"
  config.ssh.username = "ssh"
  #config.ssh.sudo_command = "%c"
  config.ssh.export_command_template = 'set %ENV_KEY%="%ENV_VALUE%"'

  config.vm.synced_folder ".", "/vagrant", disabled: true
  #config.vm.network :forwarded_port, guest: 80, host: 4567
  config.vm.provision "shell", run: "up, provision" do |s|

  s.privileged = false
  s.binary=false
  s.upload_path = "X:\\Windows\\System32\\vagrant-shell.bat"

end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/rupebac/b4ac4b4721a1264ac392d5a63aaba094

### Expected behavior
It should just work always

### Actual behavior
Some random times, bringing the machine up fails. I cannot identify when. It is running on vmware workstation 9.

For quite some time, the same Vagrantfile has been working flawless. Not sure if it is since the last update to vagrant 2.0.2 (from vagrant 1.9), or perhaps an update from Windows that forced me to reinstall vmware workstation.

**Comment by chrisroberts** [comment]
Hi there,

A new Vagrant VMware plugin has been released, you can read about it here: https://www.hashicorp.com/blog/introducing-the-vagrant-vmware-desktop-plugin

This new plugin replaces both the vagrant-vmware-workstation and vagrant-vmware-fusion plugins. There will be no new development work done on either of the old plugins. All new development and fixes will be found within the vagrant-vmware-desktop plugin. Would you please install the new plugin, and see if that resolves your issue. If you still encounter the same behavior with the new plugin, I'll be happy to investigate further.

Cheers!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
