### ISSUE TITLE
Vagrant does not create new instances with the correct network mode. Package or init or up is broken.

### ISSUE THREAD

**Issue by starrychloe** [hashicorp/vagrant#9630]
https://superuser.com/questions/1196330/how-do-i-package-a-vagrant-box-with-custom-vagrant-file-public-network-ram-set

When you include the network directive

    config.vm.network "public_network"

and package it into a box, it doesn't not create that type of network when you instantiate the box.

### Vagrant version
Vagrant 2.0.1

### Host operating system
Windows 8.1

### Guest operating system
OpenWRT 

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  #config.vm.box = "nycmesh-qmp-openwrt"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "64"
    #vb.customize ["modifyvm", :id, "--ostype", "Linux26"]
    #vb.customize ["storageattach", :id, "--medium", "../build/qMp_3.2.1-Clearance_VirtualBox_x86_factory_20170406-2203.vdi"]
    #vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', "../build/qMp_3.2.1-Clearance_VirtualBox_x86_factory_20170406-2203.vdi"]
  end
end
```

### Expected behavior
Expected it to create an instance with 'bridged adapter'.

### Actual behavior
It created an instance with 'NAT'.

### Steps to reproduce
1. `vagrant package --base node --vagrantfile package-the-vagrantfile/Vagrantfile`
2. `vagrant init package.box --minimal ; vagrant up`
3.

### References
The main Vagrantfile in the package.box uses `../` for the path, but which subdirectory is it in? There are no other subdirectories inside the `package.box` tarfile.

    include_vagrantfile = File.expand_path("../include/_Vagrantfile", __FILE__)
When the box is initialized, the new Vagrantfile no longer references the included package Vagrant file, nor are any of the contents of the included Vagrantfile in the new main Vagrantfile.

**Comment by starrychloe** [comment]
Additional information: There may be some ambiguity in the command line parameters. I had `package.box` in my list of `vagrant box list`. When you run `vagrant init package.box` does that refer to the filename `package.box` or to an item in `vagrant box list`? It generates a Vagrantfile with `config.vm.box = "package.box"`. Does that refer to the filename `package.box` or to an item in the list `vagrant box list`? I ran `vagrant box remove package.box` and when it initialized the instance and started the instance, it did create a network adapter with 'bridged', but it was the 2nd adapter and it created two adapters, whereas the original instance only had one bridged adapter. So it still didn't work.

```
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
```

**Comment by briancain** [comment]
Hi there,

The first interface you see on the guest is the NAT interface which is generated by Vagrant and is required. This interface is used for port forwarding, among other things. Users have posted methods in the past for disabling the NAT interface but I'm afraid that setup is not supported by Vagrant. You may be able to accomplish removing the NAT interface by adding provider-specific customizations in your Vagrantfile:

* [Relevant issue about the NAT interface](https://github.com/hashicorp/vagrant/issues/2093)
* [VirtualBox Customizations](https://www.vagrantup.com/docs/virtualbox/configuration.html#vboxmanage-customizations)
* [VMware Customizations](https://www.vagrantup.com/docs/vmware/configuration.html#vmx-customization)

Cheers!
