### ISSUE TITLE
Vagrant+Centos 7 inet in guest OS go down

### ISSUE THREAD

**Issue by Marcolino179** [hashicorp/vagrant#9631]
I initialized a virtual machine through the parallel provider on MacOs based on centos / 7 official box, the problem that the machine after a few minutes after the start, loses the ip of the network and running the remote command"ifconfig" shows that the inet of the network on eth0 is gone and I'm forced to restart the networking service on the virtual machine.

### Vagrant version
Vagrant 2.0.3

### Host operating system
macOs Hig Sierra 10.13.3

### Guest operating system
Centos 7

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"

  config.vm.network "forwarded_port", guest: 80, host: 8800
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "forwarded_port", guest: 10000, host: 10000
  config.vm.network "forwarded_port", guest: 5555, host: 5555
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  config.vm.provider "parallels" do |prl|
    prl.update_guest_tools = true
  end
  # ----------------------------------------------------------------------------
  # setup
  # ----------------------------------------------------------------------------
   config.vm.provision :shell, path: "vagrant_data/assets/init.sh"
end
```

**Comment by chrisroberts** [comment]
Hi there,

The parallels provider is a third party plugin and not part of Vagrant core. If you can reproduce the issue using the virtualbox provider,  please create a new issue with the Vagrantfile used and a gist of the debug output from `vagrant up --debug`.

Cheers!
