### ISSUE TITLE
Windows Vagrant version: unknown

### ISSUE THREAD

**Issue by Walkoss** [hashicorp/vagrant#9634]
### Vagrant version
Windows Vagrant version: `2.0.3`
Windows Subsystem for Linux Vagrant version: `2.0.3`

![image](https://user-images.githubusercontent.com/1349320/38096995-84d13178-3374-11e8-95f2-78cae157a005.png)

### Host operating system
Windows 10

### Guest operating system
`laravel/homestead` -> Ubuntu

### Vagrantfile
https://github.com/laravel/homestead/blob/master/Vagrantfile

### Debug output
https://gist.github.com/Walkoss/cfd098138fed518d9f9364b1ad4875c5

### Expected behavior
Vagrant should start the virtual machine

### Actual behavior
As Vagrant on WSL doesn't recognize Vagrant Windows version, it raised an exception.

**Comment by Walkoss** [comment]
`VAGRANT_WSL_ENABLE_WINDOWS_ACCESS` env variable is set
`PATH` env variable contains `/mnt/c/Program Files/Oracle/VirtualBox`

**Comment by Walkoss** [comment]
This morning, vagrant worked perfectly on WSL but without any update, it fails now. I tried to reinstall on windows and WSL.

**Comment by chrisroberts** [comment]
@Walkoss What is the output of this command from within WSL:

```
$ /mnt/c/HashiCorp/Vagrant/bin/vagrant.exe version
```

**Comment by Walkoss** [comment]
@chrisroberts here is the output

```
Installed Version: 2.0.3
Latest Version: 2.0.3

You're running an up-to-date version of Vagrant!
```

**Comment by chrisroberts** [comment]
Can you provide a gist of the output with the full debug:

```
$ vagrant up --debug
```

Thanks!

**Comment by Walkoss** [comment]
https://gist.github.com/Walkoss/dc817f50ca8e659e896e817d675e3174

Thanks

**Comment by chrisroberts** [comment]
@Walkoss It looks like the version check error is suppressing the actual error which is a problem parsing the Vagrantfile. You can see it here: https://gist.github.com/Walkoss/dc817f50ca8e659e896e817d675e3174#file-gistfile1-txt-L242

I'll create a new issue to track this problem and get it fixed in a future release. Cheers!
