### ISSUE TITLE
Vagrantfile parse error suppressed by WSL version check

### ISSUE THREAD

**Issue by chrisroberts** [hashicorp/vagrant#9635]
Vagrantfile parse errors can cause the WSL version check to fail and hide the actual error. Version check from the WSL should be using the `--version` flag instead of the `version` command which would reduce issues like this. When version cannot be extracted output from command should be included in the error to help with local user debugging of issue.

Source: #9634

**Comment by andrecastillo** [comment]
I'm having the same exact issue. 

Question, is there a way I can work around this error till a fix is released?
