### ISSUE TITLE
Cannot change the box_url after the initial vagrant up

### ISSUE THREAD

**Issue by tallen1983** [hashicorp/vagrant#9637]
### Vagrant version
2.0.3

### Host operating system
Windows

### Guest operating system
Irrelevant

### Vagrantfile
```ruby
    config.vm.box_url = "file://some/path/to/mybox.json"
```

### Expected behavior
If I change the box_url later, it should begin checking the new location, not the old location the next time I `vagrant up` when it checks for an outdated box.

### Actual behavior
No matter what you change the box_url to in Vagrantfile, it always uses the url it used to initially provision the box.

### Steps to reproduce
1. Provision a box
2. Change where the json file exists in Vagrantfile
3. Run `vagrant box outdated --debug` and see that it still uses the old URL (also happens with `vagrant up`)

### Details
The metadata_url file in ~/.vagrant.d/boxes/< some string >/ contains the original URL used to provision the box, and is never updated based on the new contents of an updated Vagrantfile.

**Comment by chrisroberts** [comment]
Hi there,

This is the expected behavior. You can update the box URL by destroying and creating the guest again. 

Cheers!

**Comment by staelche** [comment]
Hi there,

just for documentary reasons. I just had this issue with custom box urls, as well. I had to change the domain of the page hosting my own boxes.

The solution was not just to destroy the current Vagrant box but to remove all old box versions from the local Vagrant installation, too. After doing this Vagrant used the new box_url value of the VagrantFile.
