### ISSUE TITLE
Downloading boxex doesn't take the full bandwidth of my connection and it's very slow ??

### ISSUE THREAD

**Issue by YousefSaber** [hashicorp/vagrant#9642]
On speedtest.net 

My connection bandwidth speed is 6.6Mbps down 

![image](https://user-images.githubusercontent.com/33742499/38153959-b5e81370-346f-11e8-8dd3-9b0c055ec4f2.png)

but when updating my box its download speed is 0.6 Mbps ???

![image](https://user-images.githubusercontent.com/33742499/38153976-c6bb3902-346f-11e8-9343-1443f55a9a00.png)

**Comment by YousefSaber** [comment]
when I pressed ctrl + c to cancel download to restart it showed me this 

![image](https://user-images.githubusercontent.com/33742499/38154053-4ba1854a-3470-11e8-8d7e-d4af73c4deec.png)

**Comment by chrisroberts** [comment]
Hi there,

You are downloading a box from ubuntu's cloud-images domain. We have no control over speed and/or throttling from that source location.

Cheers!

**Comment by YousefSaber** [comment]
@chrisroberts fine I'll upload my feedback on 

https://askubuntu.com/questions/ask

thank you very much
