### ISSUE TITLE
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: no such file or directory

### ISSUE THREAD

**Issue by EvanWashkow** [hashicorp/vagrant#9647]
Same issue as before, and the same fix works as well
https://github.com/hashicorp/vagrant/issues/9185

(In my case, I just `sudo ln -s /usr/bin/ruby /opt/vagrant/embedded/bin/ruby`)

### Vagrant version
2.0.3

### Host operating system
Arch linux

### Guest operating system
Scotchbox

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
	config.ssh.username = "vagrant"
 	config.ssh.password = "vagrant"
	config.vm.box = "scotch/box"
	config.vm.network "private_network", ip: "192.168.33.10"
	config.vm.hostname = "scotchbox"
	config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

end
```

### Debug output
```
% vagrant up
Exec error: fork/exec /opt/vagrant/embedded/bin/ruby: no such file or directory
```

### Expected behavior
Vagrant should boot

### Actual behavior
Vagrant doesn't boot: it can't find ruby on the local machine

### Steps to reproduce
1. Install a fresh copy of Arch
2. Install Vagrant and Virtualbox
3. Try `vagrant up`

### References
- GH-9185

**Comment by nmaludy** [comment]
+1 just ran across this myself on an Ubuntu test host.

Works fine on RHEL/CentOS.

**Comment by briancain** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier 

Cheers!

**Comment by roshan8** [comment]
i'm facing the same issue on `ubuntu 20.04` and vigrant version is `2.2.9`

**Comment by devtote** [comment]
Same issue in Arch, vagrant version 2.2.9-1. The workaround with "sudo ln -s /usr/bin/ruby /opt/vagrant/embedded/bin/ruby" does not fix it.
