### ISSUE TITLE
Vagrant 2.0.3 Gives Warning "constant ::Fixnum is deprecated"

### ISSUE THREAD

**Issue by eliu** [hashicorp/vagrant#9655]
### Vagrant version
Vagrant 2.0.3

### Host operating system
macOS High Sierra 10.13.4

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior
Type `vagrant status` should not give any warning messages.

### Actual behavior
Type `vagrant status` gives warning as follows: 

```bash
$ vagrant status
~/.vagrant.d/gems/2.4.3/gems/rubyhacks-0.1.5/lib/rubyhacks.rb:536: warning: constant ::Fixnum is deprecated
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
```

### Steps to reproduce
1. type `vagrant status`

### References
N/A

**Comment by chrisroberts** [comment]
Hi there,

This warning is not coming from Vagrant. The warning is being generated by a library called "rubyhacks" that has either been installed as a vagrant plugin, or is a dependency of a vagrant plugin you have installed.

Cheers!

**Comment by eliu** [comment]
Thanks @chrisroberts . Indeed, it was coming from a plugin called `hostmanager` which has a dependency lib rubyhacks...of course, after your inspiring comments. 👍
