### ISSUE TITLE
"Vagrant up" command failing after upgrading to Vagrant 2.0.3

### ISSUE THREAD

**Issue by Sharavanan-E** [hashicorp/vagrant#9656]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
2.0.3

### Host operating system
Windows 7

### Debug output
Choose a provisioning script:
1. bug-bounty.rb
2. debugger.rb
3. mason-itb.rb
4. mason-with-debugger.rb
5. mason.rb
6. ranorex.rb
7 - No provisioning script
Provisioning script number: 3
INFO - Finished downloading provisioning script template
INFO - Creating windows_8.1_enterprise_sp1_32_eng_vmware-2... with provisioning
script mason-itb.rb
Your license to use 'vagrant-vmware-desktop' hasn't been verified in
months. We'll attempt to verify it now. This requires an internet
connection. If the verification fails, you'll need to connect to the
internet. If verification continues to fail, please contact support
at support@hashicorp.com
Your license to use 'vagrant-vmware-desktop' hasn't been verified in
months. We'll attempt to verify it now. This requires an internet
connection. If the verification fails, you'll need to connect to the
internet. If verification continues to fail, please contact support
at support@hashicorp.com
Verification successful. Please use Vagrant while connected to the
internet from time to time so Vagrant can keep your license verified.
Verification successful. Please use Vagrant while connected to the
internet from time to time so Vagrant can keep your license verified.
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Box 'windows_8.1_enterprise_sp1_32_eng_vmware-2' could not be found
. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'windows_8.1_enterprise_sp1_32_eng_vmware-2' (v0) for pr
ovider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Downloading: https://xyz.xyx.com/repo/boxes/windows-8.1/windows_8.1_enterprise_sp1_32_eng_vmware.b
ox
    default: Progress: 100% (Rate: 50.0M/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'windows_8.1_enterprise_sp1_32_eng_vmware-2'
(v0) for 'vmware_workstation'!
Your license to use 'vagrant-vmware-desktop' hasn't been verified in
months. We'll attempt to verify it now. This requires an internet
connection. If the verification fails, you'll need to connect to the
internet. If verification continues to fail, please contact support
at support@hashicorp.com
Verification successful. Please use Vagrant while connected to the
internet from time to time so Vagrant can keep your license verified.
C:/devstack/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-desktop-1.0.0/lib/vagrant-
vmware-desktop-deprecated/lib/vagrant-vmware-desktop/action_farm.rb:584:in `call
': undefined method `metadata' for nil:NilClass (NoMethodError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/builtin/prepare_clone.rb:15:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/builtin/handle_box.rb:56:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/warden.rb:34:in `call'
        from C:/devstack/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-desktop-1.0.0
/lib/vagrant-vmware-desktop-deprecated/lib/vagrant-vmware-desktop/action_farm.rb
:104:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/warden.rb:34:in `call'
        from C:/devstack/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-desktop-1.0.0
/lib/vagrant-vmware-desktop-deprecated/lib/vagrant-vmware-desktop/action_farm.rb
:393:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/warden.rb:34:in `call'
        from C:/devstack/.vagrant.d/gems/2.4.3/gems/vagrant-vmware-desktop-1.0.0
/lib/vagrant-vmware-desktop-deprecated/lib/vagrant-vmware-desktop/action_farm.rb
:251:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/machine.rb:227:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/machine.rb:202:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/environment.rb:592:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/machine.rb:188:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/machine.rb:188:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vag
rant/batch_action.rb:82:in `block (2 levels) in run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.3/gems/logging-2.2.2/lib/log
ging/diagnostic_context.rb:474:in `block in create_with_logging_context'
ERROR - Vagrant failed to launch the VM : windows_8.1_enterprise_sp1_32_eng_vmwa
re-2
==> default: VM not created. Moving on...
INFO - Vagrant successfully destroyed the VM!
ERROR - Failed to launch up the VM!

### Expected behavior
Should work in Vagrant 2.0.3

### Actual behavior
Vagrant up command is failing after upgrading to 2.0.3

### Steps to reproduce
1. Install Vagrant 2.0.3
2. Install VmwareUtility 1.0.0
2. Install vagrant-omnibus 1.5.0
3. Install vagrant-vmware-desktop 1.0.0 plugin and also license it
4. Run Vagrant init and up command by pointing the box.After downloading the box, failed with error

**Comment by Sharavanan-E** [comment]
This issue not occurring in Vagrant 2.0.2. Happening after upgrading vagrant.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
