### ISSUE TITLE
in `initialize': No such file or directory 

### ISSUE THREAD

**Issue by zhoujun165** [hashicorp/vagrant#9661]
### Vagrant version
2.0.3

### Host operating system
win10

### Debug output

C:\Users\Administrator>vagrant
D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver.rb:174:in `initialize': No such file or directory @ rb_sysopen - NUL (Errno::ENOENT)
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver.rb:174:in `open'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver.rb:174:in `output'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/modules/ui.rb:40:in `after_resolution'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:115:in `end_resolution'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:83:in `ensure in resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:83:in `resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver.rb:188:in `resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/request_set.rb:368:in `resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/request_set.rb:380:in `resolve_current'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems.rb:239:in `finish_resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/rdoc.rb:15:in `<top (required)>'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/uninstaller.rb:11:in `<top (required)>'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/bundler.rb:9:in `<top (required)>'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/manager.rb:4:in `require_relative'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/manager.rb:4:in `<top (required)>'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant.rb:264:in `require_relative'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant.rb:264:in `<top (required)>'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:75:in `<main>'

**Comment by chrisroberts** [comment]
Hi there,

Can you try setting the `VAGRANT_DISABLE_RESOLV_REPLACE` environment variable and see if that fixes this issue. `set VAGRANT_DISABLE_RESOLV_REPLACE=1` or running it inline with the command should be sufficient:

```
> VAGRANT_DISABLE_RESOLV_REPLACE=1 vagrant
```

Thanks!

**Comment by zhoujun165** [comment]
it didn't work

**Comment by chrisroberts** [comment]
Would you please provide a gist of the debug output with the `VAGRANT_DISABLE_RESOLV_REPLACE` environment variable set:

```
vagrant --debug
```

Thanks!

**Comment by zhoujun165** [comment]
C:\Users\Administrator>vagrant --debug
 INFO global: Vagrant version: 2.0.3
 INFO global: Ruby version: 2.4.3
 INFO global: RubyGems version: 2.6.14
 INFO global: VAGRANT_DISABLE_RESOLV_REPLACE="1"
 INFO global: VAGRANT_EXECUTABLE="D:\\Program Files (x86)\\Vagrant\\embedded\\gems\\2.0.3\\gems\\vagrant-2.0.3\\bin\\vagrant"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="D:\\Program Files (x86)\\Vagrant\\embedded"
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_LOG="debug"
 WARN global: resolv replacement has not been enabled!
D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver.rb:174:in `initialize': No such file or directory @ rb_sysopen - NUL (Errno::ENOENT)
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver.rb:174:in `open'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver.rb:174:in `output'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/modules/ui.rb:40:in `after_resolution'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:115:in `end_resolution'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:83:in `ensure in resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:83:in `resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/resolver.rb:188:in `resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/request_set.rb:368:in `resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/request_set.rb:380:in `resolve_current'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems.rb:239:in `finish_resolve'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/rdoc.rb:15:in `<top (required)>'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/uninstaller.rb:11:in `<top (required)>'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/bundler.rb:9:in `<top (required)>'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/manager.rb:4:in `require_relative'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant/plugin/manager.rb:4:in `<top (required)>'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant.rb:264:in `require_relative'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/lib/vagrant.rb:264:in `<top (required)>'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from D:/Program Files (x86)/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from D:/Program Files (x86)/Vagrant/embedded/gems/2.0.3/gems/vagrant-2.0.3/bin/vagrant:75:in `<main>'

**Comment by chrisroberts** [comment]
Hi @zhoujun165,

Thank you for providing the debug output. This is an interesting and unexpected error you are encountering. I have not been able to reproduce this behavior on my Windows installation. Would you please run the following commands and paste the output here:

```
> "D:\Program Files (x86)\Vagrant\embedded\mingw64\bin\ruby.exe" -e 'File.open("NUL", "w"); puts "ok NUL"'
> "D:\Program Files (x86)\Vagrant\embedded\mingw64\bin\ruby.exe" -e 'File.open("\\\\.\\NUL", "w"); puts "ok \\\\.\\NUL"'
> dir
```

Thanks!

**Comment by zhoujun165** [comment]
Hi @chrisroberts 

```
C:\Users\Administrator>"D:\Program Files (x86)\Vagrant\embedded\mingw64\bin\ruby.exe" -e 'File.open("NUL", "w"); puts "ok NUL"'
-e:1:in `initialize': No such file or directory @ rb_sysopen - NUL (Errno::ENOENT)
        from -e:1:in `open'
        from -e:1:in `<main>'

C:\Users\Administrator> "D:\Program Files (x86)\Vagrant\embedded\mingw64\bin\ruby.exe" -e 'File.open("\\\\.\\NUL", "w"); puts "ok \\\\.\\NUL"'
-e:1:in `initialize': No such file or directory @ rb_sysopen - \\.\NUL (Errno::ENOENT)
        from -e:1:in `open'
        from -e:1:in `<main>'

C:\Users\Administrator>dir
 驱动器 C 中的卷是 Windows10
 卷的序列号是 0DC3-11AB

 C:\Users\Administrator 的目录

2018/04/09  19:50    <DIR>          .
2018/04/09  19:50    <DIR>          ..
2018/04/08  19:56    <DIR>          .dotnet
2018/01/07  18:41    <DIR>          .PhpStorm2017.2
2018/01/07  17:46    <DIR>          3D Objects
2018/01/07  17:46    <DIR>          Contacts
2018/04/07  09:49    <DIR>          Desktop
2018/04/08  20:19    <DIR>          Documents
2018/04/08  22:53    <DIR>          Downloads
2018/04/07  09:49    <DIR>          Favorites
2018/01/07  17:49    <DIR>          Links
2018/01/07  17:46    <DIR>          Music
2018/01/08  18:36    <DIR>          Pictures
2018/01/07  17:46    <DIR>          Saved Games
2018/01/07  17:47    <DIR>          Searches
2018/04/08  20:21    <DIR>          source
2018/01/07  20:24    <DIR>          Videos
               0 个文件              0 字节
              17 个目录 58,047,795,200 可用字节
```

Thank you for your help!

**Comment by chrisroberts** [comment]
@zhoujun165 Would you please upgrade to the latest Vagrant release and verify if this problem persists. Thanks!

**Comment by logosity** [comment]
I've gotten this error recently (on Mac OSX Sierra) while writing a new Vagrantfile - and it was initially very confusing. Eventually,  I recalled that I had forcibly killed a vagrant destroy operation mid-stream a couple of restarts ago and then added a shell provisioner. Only then, did I get the error (I also had the plugin `vagrant fsnotify` running in another shell that could've been the root problem). Regardless, things were in a wonky state. The fix was making sure I had no vagrant/Vbox related processes running `ps aux | grep -i vagrant` killing off things that shouldn't be running (including virtualbox via `pkill Vbox`) and trying again. This fixed the error.

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
