### ISSUE TITLE
Add ability to throttle basebox downloads

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [hashicorp/vagrant#9667]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
$ vagrant -v
Vagrant 2.0.2

### Host operating system
Windows 10

### Guest operating system
Ubuntu

### Expected behavior
add a parameter in vagrantfile to limit/throttle basebox downloads

Both curl and wget (the underlying command used to download the boxes ) support rate limiting the downloads:
curl:
--limit-rate <speed> eg: curl --limit-rate 423K
wget:
  --limit-rate=amount eg: wget --limit-rate=423k
### Actual behavior
What actually happened?
basebox's download a maximum available internet speed

**Comment by jmcgnh** [comment]
I've tested this 2-line modification to downloader.rb. It inserts any options found in the environment variable VAGRANT_CURL_EXTRA_OPTIONS into the exec of curl. I know --limit-rate works. I wanted to increase the persistence with --retry, but that doesn't seem to help. It also should address a case where someone needed to insert an extra header for authentication to a private registry.

https://gist.github.com/jmcgnh/d237105a5a6e7dd7555a657953252887

```*** lib/vagrant/util/downloader.rb      2019-04-24 16:41:14.967086653 -0400
--- /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/downloader.rb  2019-06-28 16:02:33.328278927 -0400
***************
*** 3,8 ****
--- 3,9 ----
  require "log4r"
  require "digest/md5"
  require "digest/sha1"
+ require "shellwords"
  require "vagrant/util/busy"
  require "vagrant/util/platform"
  require "vagrant/util/subprocess"
***************
*** 258,263 ****
--- 259,265 ----
          options << "--cert" << @client_cert if @client_cert
          options << "-u" << @auth if @auth
          options << "--location-trusted" if @location_trusted
+         options += Shellwords.split(ENV['VAGRANT_CURL_EXTRA_OPTIONS'])  if ENV['VAGRANT_CURL_EXTRA_OPTIONS']

          if @headers
            Array(@headers).each do |header|
```

**Comment by soapy1** [comment]
The `--limit-rate` option can be set for downloading a box using curl with the `config.vm.box_download_options` https://www.vagrantup.com/docs/vagrantfile/machine_settings.html#config-vm-box_download_options. 

The Vagrantfile will looks something like:
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_download_options = {"limit-rate": "423K"}
end
```

**Comment by jbonhag** [comment]
Hey there,

I'm going to close this issue as the provided solution using `config.vm.box_download_options` has been confirmed to work.

Thanks!
