### ISSUE TITLE
Exec error: fork/exec D:\HashiCorp\Vagrant\embedded\mingw64\bin\ruby.exe: Access is denied.

### ISSUE THREAD

**Issue by prassawant** [hashicorp/vagrant#9672]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
I have installed 2.0.3
### Host operating system
This is the operating system that you run locally.
Windows 10 enterprize
### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
Vagrant.configure(2) do |config|
	config.vm.define "devops-box" do |devbox|
		devbox.vm.box = "ubuntu/xenial64"
    		#devbox.vm.network "private_network", ip: "192.168.199.9"
    		#devbox.vm.hostname = "devops-box"
      		devbox.vm.provision "shell", path: "scripts/install.sh"
    		devbox.vm.provider "virtualbox" do |v|
    		  v.memory = 4096
    		  v.cpus = 2
    		end
	end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?
vagrant status show the box status
### Actual behavior
What actually happened?
it throws error Exec error: fork/exec D:\HashiCorp\Vagrant\embedded\mingw64\bin\ruby.exe: Access is denied.
it same error for any vagrant command such as vagrant -v 
### Steps to reproduce
1. install vagrant from 
https://releases.hashicorp.com/vagrant/2.0.3/vagrant_2.0.3_x86_64.rpm?_ga=2.78022100.1906345317.1523303049-1488191433.1518524815
on windows 10 enterprise

2. after installation say vagrant -v 
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by prassawant** [comment]
downgraded to 1.9.8 and it's working fine version 2.x and above is an issue

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by prassawant** [comment]
somehow i have not received the notification about waiting-reply .. will open new issue and add glist in same issue
