### ISSUE TITLE
Enhancement: Add the "force" option to the "reload" command

### ISSUE THREAD

**Issue by Spamme1** [hashicorp/vagrant#9677]
### Vagrant version
2.0.3

We were using the ```vagrant reload``` command but it some rare cases the virtual machine couldn't be gracefully shut down, in this cases we would like to have a hard shut down, but the ```vagrant reload``` command doesn't have this option, therefore we had to change to two separate commands.
```
vagrant halt --force
sleep 10s
vagrant up
```
It would be nice if it would be possible to have the ```--force``` option also in the ```vagrant reload``` command, because effectively the ```reload``` command should be the replacement of the ```halt``` and ```up``` command, but the missing ```--force``` option makes it not a complete replacement.

**Comment by elshobokshy** [comment]
I agree, it would be amazing having this.
