### ISSUE TITLE
Vagrant rsync fails silently and randomly

### ISSUE THREAD

**Issue by tuminoid** [hashicorp/vagrant#9682]
### Vagrant version
`Vagrant 2.0.3`

### Host operating system
Ubuntu 16.04.4 LTS

### Guest operating system
This issue in from RHEL 7.4 guest.
Issue has been seen in RHEL 7.4 and Debian Jessie guests. 

### Vagrantfile
```ruby
  config.vm.box = "#{ceph_vm_name}"
  config.vm.box_url = "#{ceph_vm_url}"
  config.vm.box_check_update = true
  config.vm.box_version = "= #{ceph_box_version}"
  # resize disk to this
  config.disksize.size = "#{disk_ceph}GB"

  # sync files in boxes
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vm.synced_folder "../../packer/ceph/ceph", "/usr/share/ceph/", type: "rsync"

  config.vm.define :ceph1 do |config|
    config.vm.provider "virtualbox" do |v|
        v.linked_clone = true
        v.memory = memory_ceph
        v.cpus = cpus_ceph
    end

    config.vm.hostname = "ceph1"
    config.vm.network "private_network", ip: "192.168.10.10"
    config.vm.provision :shell, :path => "scripts/resize-disk.sh"
    config.vm.provision :shell, :path => "scripts/ceph.sh"
  end


  config.vm.define :ceph2 do |config|
    config.vm.provider "virtualbox" do |v|
        v.linked_clone = true
        v.memory = memory_ceph
        v.cpus = cpus_ceph
    end

    config.vm.hostname = "ceph2"
    config.vm.network "private_network", ip: "192.168.10.11"
    config.vm.provision :shell, :path => "scripts/resize-disk.sh"
    config.vm.provision :shell, :path => "scripts/ceph.sh"
  end
```

### Debug output
https://gist.github.com/tuminoid/cf4ae5df5379efc425867de0305f5039

### Expected behavior
Files from current dir get synced to box's `/vagrant`.

### Actual behavior
Random files and/or directories are missing from `/vagrant`.

### Steps to reproduce
1. `vagrant up`
2. Provisioning fails as they try to read files from `/vagrant` and they're missing

Occurs randomly. Sometimes few times a day, sometimes once a week.

### Info
Rsync just randomly fails to sync all the files from source to target. Random files or directories are missing. This occurs randomly and not very often, so it is hard to catch. Maybe 1 out of 100. Vagrant or rsync do not produce any output that would indicate a failure, and failure is only noticed when supposedly synced file is being read and it is not there.

In the below case, failure occurred after few hours of trying to reprocuce in a loop:
`export VAGRANT_LOG=debug; while vagrant up &>vagrant_debug.txt; do vagrant rm -f; done`

Success case from `ceph1`:
```
 INFO subprocess: Starting process: ["/usr/bin/rsync", "--verbose", "--archive", "--delete", "-z", "--copy-links", "--no-owner", "--no-group", "--rsync-path", "sudo rsync", "-e", "ssh -p 2222 -o LogLevel=FATAL  -o ControlMaster=auto -o ControlPath=/tmp/ssh.989 -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/path/to/project/vagrant/ceph/.vagrant/machines/ceph1/virtualbox/private_key'", "--exclude", ".vagrant/", "/path/to/project/vagrant/ceph/", "vagrant@127.0.0.1:/vagrant"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: sending incremental file list
DEBUG subprocess: stdout: ./
.gitignore
README.md
DEBUG subprocess: stdout: Vagrantfile
vagrant_debug.txt
DEBUG subprocess: stdout: insecure-keyring/
insecure-keyring/ceph-client-key
insecure-keyring/ceph.client.admin.keyring
DEBUG subprocess: stdout: insecure-keyring/ceph.conf
insecure-keyring/ceph.mon.keyring
scripts/
scripts/ceph.sh
scripts/resize-disk.sh
DEBUG subprocess: stdout:
sent 34,884 bytes  received 236 bytes  70,240.00 bytes/sec
total size is 456,567  speedup is 13.00
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 31999
DEBUG subprocess: Exit status: 0
```

Failing case from `ceph2`:
```
 INFO subprocess: Starting process: ["/usr/bin/rsync", "--verbose", "--archive", "--delete", "-z", "--copy-links", "--no-owner", "--no-group", "--rsync-path", "sudo rsync", "-e", "ssh -p 2201 -o LogLevel=FATAL  -o ControlMaster=auto -o ControlPath=/tmp/ssh.989 -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/path/to/project/vagrant/ceph/.vagrant/machines/ceph2/virtualbox/private_key'", "--exclude", ".vagrant/", "/path/to/project/vagrant/ceph/", "vagrant@127.0.0.1:/vagrant"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: sending incremental file list
DEBUG subprocess: stdout: vagrant_debug.txt
DEBUG subprocess: stdout:
sent 25,226 bytes  received 3,914 bytes  58,280.00 bytes/sec
total size is 931,268  speedup is 31.96
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
```

For whatever reason, it only synced the log file (newest file?), when it was supposed to sync `insecure-keys` and `scripts` directories, plus `.gitignore`, `Vagrantfile` and other files in the directory.

**Comment by tuminoid** [comment]
Ping @chrisroberts, this is #9571 with debug logs this time.

**Comment by briancain** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. From the information you provided, it seems like this is likely an issue with rsync rather than Vagrant. The debug output is showing the rsync command that is being run, and due to the random nature of this failure, it is likely a fault with rsync. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier 

Cheers!
