### ISSUE TITLE
Provider customizations called multiple times

### ISSUE THREAD

**Issue by spiffytech** [hashicorp/vagrant#9684]
### Vagrant version
Vagrant 2.0.3

### Host operating system
Mac OS High Sierra

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "datadisk" do |datadisk|
    datadisk.vm.box = "ubuntu/xenial64"

    datadisk.vm.provider "virtualbox" do |provider|
      puts "adding data disk"
      extra_disk = "/tmp/datadisk.vdi"
      unless File.exist?(extra_disk)
        provider.customize ['createhd', '--filename', extra_disk,
          '--size', 500  # Megabytes
        ]
      end
      provider.customize ['storageattach', :id, '--storagectl',
        'SATAController', '--port', 1, '--device', 0, '--type', 'hdd',
        '--medium', extra_disk
      ]
    end
  end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/spiffytech/1e1f9d535d787739547a13fa7a73e4ac

### Expected behavior
The machine's `provider` block should be called only once, so that the extra disk is only created once.

### Actual behavior
The `provider` block is called several times, causing VirtualBox to complain the disk file already exists.

### Steps to reproduce
1. Verify that the file `/tmp/datadisk.vdi` does not exist
2. vagrant up

**Comment by chrisroberts** [comment]
Hi there,

It looks like this has been resolved within a previously shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one.

Cheers!
