### ISSUE TITLE
"error setting certificate verify locations; CAfile: /opt/vagrant/embedded/cacert.pem"

### ISSUE THREAD

**Issue by EvanWashkow** [hashicorp/vagrant#9693]
After trying to `vagrant up` WPDistillery (or `scotch/box` in general), I get the message

```
The box 'scotch/box' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/scotch/box"]
Error: error setting certificate verify locations:
  CAfile: /opt/vagrant/embedded/cacert.pem
  CApath: none
```

Initially, this appears to be an issue with the `/opt/vagrant/embedded/cacert.pem`, since I'm unable to find it on my file system in that directory at all.

By setting `config.vm.box_download_insecure = true` in my `vagrantfile`, it finally does download and setup, but I'd rather not do that.

### Vagrant  version
2.0.3

### Host operating system
Arch

### Guest operating system
Scotchbox

### Vagrantfile
```ruby

# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# WPDistillery Vagrantfile using Scotch Box
#
# File Version: 1.2.0

Vagrant.configure("2") do |config|

    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"
    config.vm.box = "scotch/box"
    config.vm.box_download_insecure = true
    config.vm.network "private_network", ip: "192.168.33.20"
    config.vm.hostname = "wpdistillery.vm"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

    # WPDistillery Windows Support
    if Vagrant::Util::Platform.windows?
      config.vm.provision "shell",
      inline: "echo \"Converting Files for Windows\" && sudo apt-get install -y dos2unix && cd /var/www/ && dos2unix wpdistillery/config.yml && dos2unix wpdistillery/provision.sh && dos2unix wpdistillery/wpdistillery.sh",
      run: "always", privileged: false
    end

    # Run Provisioning – executed within the first `vagrant up` and every `vagrant provision`
    config.vm.provision "shell", path: "wpdistillery/provision.sh"

    # OPTIONAL - Update WordPress and all Plugins on vagrant up – executed within every `vagrant up`
    #config.vm.provision "shell", inline: "echo \"== Update WordPress & Plugins ==\" && cd /var/www/public && wp core update && wp plugin update --all", run: "always", privileged: false

    # OPTIONAL - Enable NFS. Make sure to remove line 13 (See https://stefanwrobel.com/how-to-make-vagrant-performance-not-suck)
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

end

```

### Debug output

```
The box 'scotch/box' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/scotch/box"]
Error: error setting certificate verify locations:
  CAfile: /opt/vagrant/embedded/cacert.pem
  CApath: none
```

### Expected behavior
To be able to download ScotchBox without insecure connections

### Actual behavior
Got the above error

### Steps to reproduce
1. Clone WPDistillery (or set up ScotchBox): https://github.com/flurinduerst/WPDistillery
    1. If on WPDistillery, I set a local branch to tag `2.3`. But, it really doesn't matter because it's an issue with ScotchBox
2. Try `vagrant up`

### References
- https://github.com/scotch-io/scotch-box/issues/25
- https://github.com/scotch-io/scotch-box/issues/278

_I realize these issues on from Scotch Box's repo, however, the certificate file is missing on Vagrant's side._

**Comment by briancain** [comment]
@EvanWashkow - What does this directory look like for you on your machine `/opt/vagrant/embedded`? Latest Arch packages will use the system cacert bundle...did you perhaps upgrade from an old version of vagrant on your system at all?

**Comment by EvanWashkow** [comment]
@briancain No, it was a fresh install, using the Anarchy arch installer (I disabled their custom repo to run just vanilla Arch). The issue was bugging my development so much I switched to Manjaro.

To the best of my recollection, there was only three directories there: `etc`, `gems` and `rgloader`. The `cacert.pem` was missing (obviously).

It's possible that installing Vagrant didn't pull the system's `cacert`. It's possible that the Anarchy arch installer missed that package. Shouldn't that package be listed as a vagrant dependency (or one of its dependencies' dependency)?

**Comment by EvanWashkow** [comment]
That being said, it might be a mute point since the installer might be at fault. However, it seems unlikely to me since it does a network install of Arch, using pacman I believe. So, it should resolve every dependency...(?)

**Comment by briancain** [comment]
@EvanWashkow - could you run the following command and share the output in a gist file?

```ruby
VAGRANT_DEBUG_LAUNCHER="1" vagrant box add scotch/box
```

Thanks!

**Comment by EvanWashkow** [comment]
I removed Arch a week ago because of this issue, so I'm unable to provide that output.

**Comment by chrisroberts** [comment]
Without debug feedback I'm going to close this up. Thanks!

**Comment by EvanWashkow** [comment]
@briancain
