### ISSUE TITLE
synced_folder user and group work only on the last directory, previous are owned by root:root

### ISSUE THREAD

**Issue by aalexanderr** [hashicorp/vagrant#9702]
### Vagrant version
Vagrant 2.0.3

### Host operating system
Ubuntu 16.04 64bit

### Guest operating system
hashicorp/precise64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder "somename/", "/home/vagrant/go/src/github.com/",
      owner: "vagrant", group: "vagrant"
//provisioning omitted as it does not impact this behaviour
end
```

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

LMK if it is neccessary in this case

### Expected behavior
What should have happened?
I think that  the whole path ~/go/src/github.com should be owned by vagrant:vagrant

### Actual behavior
only last directory is owned by vagrant:vagrant, previous (created by vagrant) directories are owned by root:root

### Steps to reproduce
1. create synced directory that is nested in new directory on guest machine
2. vagrant up
3. vagrant ssh
4. check ownership of the created directories

### References
Unknown

**Comment by briancain** [comment]
Hi @aalexanderr - this is expected behavior based on what the synced_folder documentation tells me. These options are purely for the destination of the mounted folder, rather than every folder that exists on the path specified. I recommend adding a provision script to chown the entire path recursively.

```ruby
config.vm.provision "shell", inline: <<-SHELL
chown -R vagrant:vagrant /home/vagrant/go
SHELL
```

Thanks!
