### ISSUE TITLE
'Vagrant box outdated' command not showing outdated boxes

### ISSUE THREAD

**Issue by Sharavanan-E** [hashicorp/vagrant#9706]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Python 3.4.3
Vagrant 2.0.2
Vagrant-omnibus 1.5.0
vagrant-vmware-desktop = 1.0.0

### Host operating system
Windows 7

### Guest operating system
Windows 7

### Vagrantfile

```ruby
Vagrant.configure(2) do |config|
  config.vm.communicator = "winrm"
  config.vm.box = "windows_10_client_pro_rs5_32_eng_vmware"
  config.vm.box_url = "https://a.b.c.com/artifactory/api/vagrant/repo/windows_10_client_pro_rs5_32_eng_vmware"
  config.vm.box_download_insecure = true
  config.vm.box_check_update = true
  config.winrm.username = "test"
  config.winrm.password = "test"
  config.winrm.transport = :plaintext
  config.vm.guest = :windows
  config.windows.halt_timeout = 120
  config.vm.provider "vmware_workstation" do |v|
    v.gui = true
    v.vmx["memsize"] = "2048"
    v.vmx["numvcpus"] = "2"
	  v.vmx["isolation.tools.dnd.enable"] = "TRUE"
    v.enable_vmrun_ip_lookup = false
    v.ssh_info_public = true
  end
end
```

Our vagrant vmware boxes are stored in JFrog artifactory vagrant repo layout. Whenever we upload the box into repository, setting proper version number and provider.
For this box, repo looks like,
Stored as: windows_10_client_pro_rs5_32_eng_vmware
box_version: 1.0.0
box_provider: vmware_workstation
box_name: windows_10_client_pro_rs5_32_eng_vmware

Stored as: windows_10_client_pro_rs5_32_eng_vmware-2.0.0.box
box_version: 2.0.0
box_provider: vmware_workstation
box_name: windows_10_client_pro_rs5_32_eng_vmware

Stored as: windows_10_client_pro_rs5_32_eng_vmware-3.0.0.box
box_version: 3.0.0
box_provider: vmware_workstation
box_name: windows_10_client_pro_rs5_32_eng_vmware

### Debug output
debugging log added into gist
https://gist.github.com/Sharavanan-E/27e7670779d5133141d840eca287372b

if I run the vagrant box update -b <<name>>, trying to download the latest version

When I hit to repo, getting box metadata.
https://a.b.c.com/artifactory/api/vagrant/repo/windows_10_client_pro_rs5_32_eng_vmware

{"name":"windows_10_client_pro_rs5_32_eng_vmware","description":null,"short_description":null,"versions":[{"version":"1.0.0","status":"active","description_html":null,"description_markdown":null,"providers":[{"name":"vmware_workstation","url":"https://aa.b.c.com/artifactory/api/vagrant/repo/windows-10/windows_10_client_pro_rs5_32_eng_vmware.box"}]},{"version":"3.0.0","status":"active","description_html":null,"description_markdown":null,"providers":[{"name":"vmware_workstation","url":"https://aa.b.c.com/artifactory/api/vagrant/repo/windows-10/windows_10_client_pro_rs5_32_eng_vmware-3.0.0.box"}]},{"version":"4.0.0","status":"active","description_html":null,"description_markdown":null,"providers":[{"name":"vmware_workstation","url":"https://aa.b.c.com/artifactory/api/vagrant/repo/windows-10/windows_10_client_pro_rs5_32_eng_vmware-4.0.0.box"}]},{"version":"2.0.0","status":"active","description_html":null,"description_markdown":null,"providers":[{"name":"vmware_workstation","url":"https://aa.b.c.com/artifactory/api/vagrant/repo/windows-10/windows_10_client_pro_rs5_32_eng_vmware-2.0.0.box"}]}]}

### Expected behavior
vagrant box outdated/up/resume should show the outdated boxes.

### Actual behavior
vagrant box outdated/up/resume not showing the outdated boxes warning message.

**Comment by briancain** [comment]
Do you get this behavior if you install an old box from Vagrant Cloud and then run the `outdated` command?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
