### ISSUE TITLE
vangrant reinstall on win10

### ISSUE THREAD

**Issue by newLedger** [hashicorp/vagrant#9711]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Version 2.0.3

### Host operating system
Win 10 pro

### Guest operating system
ubuntu 16.04 but not there yet

### Vagrantfile
install issue, not there

### Debug output
no errors, just no install exe after reinstall, reboot, and nothing
### Expected behavior
What should have happened?
I removed Hyperv and install VirtualBox, after this, I got VM errors on vagrant up.  I uninstalled everything and reinstalled.  I should have a freash install of vagrant
### Actual behavior
What actually happened?
 when I reinstalled vagrant, its act like it, did, but I reboot and no program files ever get copied, so I'm unable to get vagrant launch, there is no exe,  no errors, it just doesn't actually copy the files.  Repair does nothing!

### Steps to reproduce
1. uninstall vagrant
2. install vagrant
3.  nothing gets a coped, program directory empty

**Comment by briancain** [comment]
Hi @newLedger - If you use the Vagrant package to uninstall Vagrant, does `C:\Hashicorp` exist? And if so, are there are files inside?

**Comment by newLedger** [comment]
Yes, C:\HashiCorp is still there even after uninstall. and yes there is a files in it. there is a vangant.exe there but it runs in a shell

**Comment by newLedger** [comment]
when I came back to it, it worked.  Thanks
