### ISSUE TITLE
Vagrant can not use a locally added box

### ISSUE THREAD

**Issue by martinanderssondotcom** [hashicorp/vagrant#9714]
The `--name` option to `vagrant box add` is, according to [the docs](https://www.vagrantup.com/docs/cli/box.html#name-value):

> [...] the value that you would put into config.vm.box in your Vagrantfile.

I.e., I oughta be able to do this first:

    vagrant box add my-local-box.box --name hello

Runnning `vagrant box list` confirms this box has been added.

Then in a Vagrantfile, I specify the following:

> config.vm.box = "hello"

But on `vagrant up` I get this error message:

> Couldn't open file /D:/Workdir/hello

To put this differently, can someone please enlighten how to "properly" add a local box and then like.. use it?

I know that if the Vagrantfile reference a local - unadded - box, then it will be automagically added and successfully used on the first `vagrant up`. But adding it manually first and then try to use it seemingly doesn't work.

So what did `vagrant up` do differently? He added the box with a ".box" suffix. Indeed, if I also manually add the box as "hello.box" and then reference "hello.box" in my Vagrantfile, it works. 

The docs should clearly state that the name must have an added suffix ".box" for locally added boxes, or we make Vagrant smart enough to like, you know, check his own box register. I vote for the latter!

I am using Vagrant 2.0.2 on Windows 10.

**Comment by chrisroberts** [comment]
Hi there,

Would you please provide a copy of the Vagrantfile in use, the output shown from running `vagrant box list`, and the debug output from when the box is not able to be found. The debug output can be enabled using the `--debug` option.

Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
