### ISSUE TITLE
I check the latest 2.0.4 vagrant by sha256 it's ok. and check the gpg, then it's failed.

### ISSUE THREAD

**Issue by sancao2** [hashicorp/vagrant#9715]
➜  Downloads shasum -a 256 -c ./vagrant_2.0.4_SHA256SUMS 
shasum: vagrant_2.0.4_i686.deb: 
vagrant_2.0.4_i686.deb: FAILED open or read
shasum: vagrant_2.0.4_i686.msi: No such file or directory
vagrant_2.0.4_i686.msi: FAILED open or read
shasum: vagrant_2.0.4_i686.rpm: No such file or directory
vagrant_2.0.4_i686.rpm: FAILED open or read
shasum: vagrant_2.0.4_x86_64.deb: No such file or directory
vagrant_2.0.4_x86_64.deb: FAILED open or read
vagrant_2.0.4_x86_64.dmg: OK
shasum: vagrant_2.0.4_x86_64.msi: No such file or directory
vagrant_2.0.4_x86_64.msi: FAILED open or read
shasum: vagrant_2.0.4_x86_64.rpm: No such file or directory
vagrant_2.0.4_x86_64.rpm: FAILED open or read
shasum: vagrant_2.0.4_x86_64.tar.xz: No such file or directory
vagrant_2.0.4_x86_64.tar.xz: FAILED open or read
shasum: WARNING: 7 listed files could not be read
➜  Downloads gpg --verify ./vagrant_2.0.4_SHA256SUMS.sig ./vagrant_2.0.4_x86_64.dmg
gpg: Signature made Sat Apr 21 05:08:37 2018 CST
gpg:                using RSA key 91A6E7F85D05C65630BEF18951852D87348FFC4C
gpg: BAD signature from "HashiCorp Security <security@hashicorp.com>" [unknown]

**Comment by chrisroberts** [comment]
Hi there,

The signed file is the SHA256SUMS file, not the dmg file. The command you will want to run is:

```
$ gpg --verify ./vagrant_2.0.4_SHA256SUMS.sig ./vagrant_2.0.4_SHA256SUMS
```

Cheers!
