### ISSUE TITLE
Unable to use file:////server/share/filename.box for box urls

### ISSUE THREAD

**Issue by PrimarDarren** [hashicorp/vagrant#9721]
### Vagrant version
v2.0.4 after upgrading from v1.9.5

### Host operating system
Windows 10

### Guest operating system
Ubuntu

### Vagrantfile
Empty vagrantfile

### Expected behavior
Had a share \\\\servername\share with box there filename.box
Used "file:////servername/share/filename.box" for url in the metadata.json file
Was using "vagrant box add metadata.json" to add boxes just fine for v1.9.5

### Actual behavior
Vagrant v2.0.5 complains about the host should be localhost or 127.0.0.1 or none.
Also v2.0.5 doesn't seem to recognise metadata.json as a metadata file unless I serve it via http.

### Steps to reproduce
1. try add a box with url set to "file:////servername/share/filename.box" in the metadata.json

### References
Had a quick look for existing reports but had trouble finding any.

**Comment by chrisroberts** [comment]
Hi there,

Would you please provide a gist of the output from the `vagrant box add` command with the `--debug` flag enabled.

Thanks!

**Comment by chrisroberts** [comment]
Hi @PrimarDarren. Thanks for providing more information. This was previously reported in #9636 and a fix (#9730) is staged for the next release. Until then, the workaround is to use an extra `//` at the start of the path. 

Given your box value of:

`file:////servername/share/filename.box`

Update it to:

`file://////servername/share/filename.box`

and that will make things work until the next release is available. 

Cheers!

**Comment by suikast42** [comment]
For the bpx that works fine. Butr what about imprt the box over metadatada.json ? That doesn't work

bsdtar.EXE: Error opening archive: Unrecognized archive format
