### ISSUE TITLE
Unable to install on system using RVM

### ISSUE THREAD

**Issue by fgblomqvist** [hashicorp/vagrant#9731]
After installing from Ubuntu PPA, this is what I get:
```
$ vagrant --version
Traceback (most recent call last):
	2: from /usr/bin/vagrant:23:in `<main>'
	1: from /usr/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem vagrant (>= 0.a) with executable vagrant (Gem::GemNotFoundException)
```
At a loss what to do here. Am I supposed to install the vagrant gem in one of my ruby versions? Which ruby version is Vagrant trying to use? The one I have set as default is 2.5.1, so not sure why the error is from 2.5.0.

**Comment by chrisroberts** [comment]
Hi there,

Vagrant is no longer released as a standalone RubyGem. The official installers are the recommended way to install Vagrant: https://www.vagrantup.com/downloads.html

If you want to use Ruby in your system Ruby, you will either need to use Bundler, or pull the Vagrant source, run a `gem build vagrant.gemspec` and use the generated gem to install into your system rubygems.

Cheers!

**Comment by fgblomqvist** [comment]
For anyone who stumbles upon this issue: the real solution is to NOT install from the Ubuntu PPA. Instead, download their deb from their website.

**Comment by Mahuton** [comment]
Use this link to install the .deb.

- 64-bit:  [ttps://releases.hashicorp.com/vagrant/2.1.1/vagrant_2.1.1_x86_64.deb](https://releases.hashicorp.com/vagrant/2.1.1/vagrant_2.1.1_x86_64.deb) 

- 32-bit: [https://releases.hashicorp.com/vagrant/2.1.1/vagrant_2.1.1_i686.msi](https://releases.hashicorp.com/vagrant/2.1.1/vagrant_2.1.1_i686.msi)

**Comment by ginsburgnm** [comment]
Installed from hashicorp, same problem.
