### ISSUE TITLE
Request a synchronous mirror interface and permission.

### ISSUE THREAD

**Issue by aunhappy** [hashicorp/vagrant#9740]
As we all know, accessing [https://app.vagrantup.com/boxes/search](https://app.vagrantup.com/boxes/search) from China is very slow, it takes a long time to download a mirror, or you must use proxy software.In China, you can download some foreign images through [https://mirrors.tuna.tsinghua.edu.cn/](https://mirrors.tuna.tsinghua.edu.cn/).so i request a synchronous mirror interface and permission for [https://mirrors.tuna.tsinghua.edu.cn/](https://mirrors.tuna.tsinghua.edu.cn/).thank you.

**Comment by chrisroberts** [comment]
Hi there. At this time this is not something we are ready or able to setup. Cheers!
