### ISSUE TITLE
Bundler error updating plugins after upgrade of vagrant

### ISSUE THREAD

**Issue by onedsc** [hashicorp/vagrant#9744]
After upgrading Vagrant to 2.0.4 and then trying to upgrade plugins the following error was given:

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies bigdecimal (= 1.3.2) and bigdecimal (= 1.3.0)
  Activated bigdecimal-1.3.0
  which does not match conflicting dependency (= 1.3.2)

  Conflicting dependency chains:
    bigdecimal (= 1.3.0), 1.3.0 activated

  versus:
    bigdecimal (= 1.3.2)

  Gems matching bigdecimal (= 1.3.2):
    bigdecimal-1.3.2

### Vagrant version
Vagrant 2.0.4

### Host operating system
MacOS High Sierra

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
https://gist.github.com/onedsc/c0a5da380dc0cfda42efa76e1ef9b312

### Expected behavior
Upgrade correctly

### Actual behavior
Fails

### Steps to reproduce
1. Upgrade to latest vagrant
2. Try to upgrade plugins

**Comment by chrisroberts** [comment]
Hi there,

Do you currently have any Vagrant plugins installed? If so, does a `vagrant plugin expunge` resolve the problem?

Thanks!

**Comment by onedsc** [comment]
$ vagrant plugin expunge

This command permanently deletes all currently installed user plugins. It
should only be used when a repair command is unable to properly fix the
system.

Continue? [N]: y

All user installed plugins have been removed from this Vagrant environment!

$ vagrant version
Installed Version: 2.0.4
Latest Version: 2.0.4

You're running an up-to-date version of Vagrant!

$ vagrant plugin update
Updating installed plugins...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies openssl (= 2.0.5) and openssl (= 2.0.7)
  Activated openssl-2.0.7
  which does not match conflicting dependency (= 2.0.5)

  Conflicting dependency chains:
    openssl (= 2.0.7), 2.0.7 activated

  versus:
    openssl (= 2.0.5)

  Gems matching openssl (= 2.0.5):
    openssl-2.0.5

**Comment by chrisroberts** [comment]
@onedsc Thanks! Before running the command below, would you also provide the output from:

```
$ ls -l /opt/vagrant/embedded/lib/ruby/gems/2.4.0/specifications/default
```

The Vagrant installer package includes an uninstall script. Running that script and then installing the Vagrant package again should resolve this issue.

Thanks!

**Comment by onedsc** [comment]
$ ls -l /opt/vagrant/embedded/lib/ruby/gems/2.4.0/specifications/default
total 72
-rw-r--r--  1 root  wheel  1810 Mar 14 17:02 bigdecimal-1.3.0.gemspec
-rw-r--r--  1 root  wheel  1969 Apr 19 13:54 bigdecimal-1.3.2.gemspec
-rw-r--r--  1 root  wheel   898 Apr 19 13:54 io-console-0.4.6.gemspec
-rw-r--r--  1 root  wheel  2424 Apr 19 13:54 json-2.0.4.gemspec
-rw-r--r--  1 root  wheel  2371 Mar 14 17:02 openssl-2.0.5.gemspec
-rw-r--r--  1 root  wheel  2373 Apr 19 13:54 openssl-2.0.7.gemspec
-rw-r--r--  1 root  wheel  3137 Apr 19 13:54 psych-2.2.2.gemspec
-rw-r--r--  1 root  wheel  6235 Apr 19 13:54 rdoc-5.0.0.gemspec

Uninstalling and reinstalling fixed the issue.  Thanks.  Looks like there is a bug in the upgrade no cleaning up the gems.

**Comment by chrisroberts** [comment]
Yep, it does. Thanks for providing the output for confirmation.
