### ISSUE TITLE
Vagrant Cloud: Resumable uploads

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9752]
HTTP upload is currently the main way to publish Vagrant boxes, where large files often error during upload, requiring a complete reupload, lasting multiple hours. This is less than ideal, typing up developer resources babysitting uploads and significantly impeding timely, reliable releases when  the artifacts require security updates, as operating systems tend to do. Some users have proposed integrating torrent/magnet URL's into Vagrant, so that both uploads and downloads would see a significant speed increase. That would be nice, but it does represent some effort on the backend. Fortunately, downloads are resumable, at a decent transfer speed. Rather, the user experience could be qualitatively improved for Vagrant box developers by simply providing a resumable frontend. Maybe allow users to rsync their boxes up to Vagrant Cloud?

As a workaround, users can pay for hosting elsewhere, using rsync, BitTorrent seedboxes, Dropbox, and so on to upload Vagrant boxes in a resumable manner. Unfortunately, there are few free options for users here even at the 10's of GiB range of storage capacity required to host a user's Vagrant boxes. I appreciate that Vagrant Cloud offers (quite a lot of) free storage capacity for Vagrant boxes, I just wish it were more convenient to make use of it.

**Comment by chrisroberts** [comment]
Hi there,

Thank you for this suggestion. Currently only HTTP uploads are supported for Vagrant Cloud and resumable uploads are not supported. This may be something we revisit in the future, but at this time there are currently no plans to expand upload support beyond the current HTTP based offering. Users are able to upload boxes to alternate locations and provide Vagrant Cloud with the location if the currently supported HTTP upload is insufficient.

Cheers!
