### ISSUE TITLE
(There was an error while executing `VBoxManage ) Error

### ISSUE THREAD

**Issue by YousefSaber** [hashicorp/vagrant#9753]
when I run vagrant up or vagrant reload 

I got this error ??
```

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/bionic64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "cecaf864-39f6-4dac-b441-00b66571bb69", "--type", "headless"]

Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

```

vagrant version 2.0.4
 Oracle VM virtualbox  v5.2.8

**Comment by chrisroberts** [comment]
Hi there,

The issue is that you do not have VT-x enabled in your system BIOS which is required for running VirtualBox. Enable that setting in your BIOS and then the `vagrant up` command will work.

Cheers!

**Comment by YousefSaber** [comment]
@chrisroberts 

no I've solved the problem 

I've upgraded yesterday to windows April update and activated memory integrity
that caused the issue and turning it off solved the issue 

![image](https://user-images.githubusercontent.com/33742499/39482416-3dc04ef8-4d6f-11e8-8e63-d39b4bf6c23f.png)


also the steps in these links are important in order for VirtualBox to work 

https://discuss.erpnext.com/t/virtualbox-wont-run-raw-mode-unavailable-courtesy-of-hyper-v/34541/8

https://superuser.com/questions/1306513/how-can-you-turn-core-isolation-memory-integrity-back-off-again-in-windows-10-bu

**Comment by chrisroberts** [comment]
@YousefSaber Thanks for providing the extra information and links. I'm sure this is going to be very helpful for others as they upgrade.
