### ISSUE TITLE
Unable to ssh using vagrant

### ISSUE THREAD

**Issue by shravyarani** [hashicorp/vagrant#9755]
Unable to SSH betweens VMs created using vagrant:

### Vagrant version
Vagrant 2.0.4

### Host operating system
Mac

### Vagrantfile
```ruby
BOX_IMAGE="xxx/2.3.0"
BOX_VERSION="2.3.0"
SWITCH_COUNT=2
Vagrant.configure("2") do |config|
  (1..SWITCH_COUNT).each do |i|
        config.vm.define "switch#{i}" do |subconfig|
                subconfig.vm.box = BOX_IMAGE
                subconfig.vm.box_version = BOX_VERSION
                subconfig.vm.hostname = "switch#{i}"
                subconfig.vm.network "private_network", ip: "10.0.0.#{i + 10}"
        end
  end
  # call shell scripts
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y apache2
  #SHELL
end
```

### output

Bringing machine 'switch1' up with 'virtualbox' provider...
Bringing machine 'switch2' up with 'virtualbox' provider...
==> switch1: Importing base box 'opx/2.3.0'...
==> switch1: Matching MAC address for NAT networking...
==> switch1: Checking if box 'opx/2.3.0' is up to date...
==> switch1: Setting the name of the VM: opxVagrant_switch1_1525220706088_49165
==> switch1: Clearing any previously set network interfaces...
==> switch1: Preparing network interfaces based on configuration...
    switch1: Adapter 1: nat
    switch1: Adapter 2: hostonly
==> switch1: Forwarding ports...
    switch1: 22 (guest) => 2222 (host) (adapter 1)
==> switch1: Booting VM...
==> switch1: Waiting for machine to boot. This may take a few minutes...
    switch1: SSH address: 127.0.0.1:2222
    switch1: SSH username: vagrant
    switch1: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

### Expected behavior
What should have happened?
Create 3 vms each pingable from other
### Actual behavior
Failed with above error
### Steps to reproduce
1. copy vagrantfile
2. vagrant up

**Comment by chrisroberts** [comment]
Hi there,

The most common cause of this issue is a configuration problem with the guest. Since the box you are using is not publicly available, I cannot inspect it's behavior to help you debug the problem. The best course of action is to open the guest VM in the UI and validate that it has proper networking connectivity, the sshd is running, and nothing is blocking access to the port.

Cheers!
