### ISSUE TITLE
vagrant up for new machine fails with "LookupAccountName (SystemCallError)"

### ISSUE THREAD

**Issue by jeffreyhaole** [hashicorp/vagrant#9765]
### Vagrant version
2.0.4

### Host operating system
Windows 7 Pro

### Guest operating system
Debian Stretch

### Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/stretch64"
  config.vm.hostname = "devbox2"
  config.vm.network "private_network", ip: "192.168.0.10"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.name = "devbox2"
  end

end

```

### Debug output
Available upon request, otherwise I think this will suffice:

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'debian/stretch64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'debian/stretch64' is up to date...
==> default: Setting the name of the VM: devbox2
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/win32-file-security-1.0.10/lib/win32/file/security.rb:440:in `block in set_permissions': No mapping between account names and security IDs was done. - LookupAccountName (SystemCallError)
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/win32-file-security-1.0.10/lib/win32/file/security.rb:401:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/win32-file-security-1.0.10/lib/win32/file/security.rb:401:in `set_permissions'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/communicators/ssh/communicator.rb:200:in `ready?'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/communicators/ssh/communicator.rb:85:in `block in wait_for_ready'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:33:in `block in catch'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:33:in `catch'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/plugins/communicators/ssh/communicator.rb:62:in `wait_for_ready'
        from C:/HashiCorp/Vagrant/embedded/gems/2.0.4/gems/vagrant-2.0.4/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'

### Expected behavior
VM should be created

### Actual behavior
VM failed to create

### Steps to reproduce
1. copy my Vagrantfile to a known location
2. Launch cygwin and cd to that location
3. Run `vagrant up`

### Notes
I recently upgraded from Vagrant 2.0.0 to 2.0.4.  I can run `vagrant halt` and `vagrant up` on machines I created prior to the upgrade, but I cannot create _new_ machines.  It appears to be a problem with the insecure ssh key replacement.

I may be barking up the wrong tree, but maybe this is where my problem is coming from?
https://github.com/hashicorp/vagrant/commit/973172077373f151639f4f02f7e1101aa86a9534

**Comment by chrisroberts** [comment]
@jeffreyhaole If you run `vagrant up` from a `cmd.exe` do you still get the same error?

**Comment by jeffreyhaole** [comment]
Let me check that, but fyi, downgrading to vagrant 2.0.3 (before that commit) resolved the problem.

**Comment by jeffreyhaole** [comment]
Um...  Didn't actually mean to close this issue, so I'm reopening.

It's going to be a few minutes for me to go back to 2.0.4.

**Comment by jeffreyhaole** [comment]
@chrisroberts There is no error when running in a `cmd` window.

**Comment by chrisroberts** [comment]
@jeffreyhaole Thanks for confirmation! :+1:
