### ISSUE TITLE
"vagrant reload" should just "up" if VM doesn't exist (or at least have an option to...)

### ISSUE THREAD

**Issue by memotype** [hashicorp/vagrant#9768]
I feel like this would be much more intuitive and also be a lot friendlier for scripting. For example, we have a number of Vagrant VMs/containers that we use for building certain things like RPMs (i.e, so I know I'm using a version of rpmbuild from Centos 7 without installing and pinning it via apt on my Debian build agents), etc, but in my Makefile I have to do something like this:

```
define vagrant_cmd
        $(if $(shell cd $(1) && vagrant status | grep "not created"),up,reload)
endef

[...]

$(ansible_rpm): $(ansible_tar) $(ansible_rpm_src)
        set -ex; \
        cd $(ansible_dir) \
        vagrant $(call vagrant_cmd,$(shell pwd)) \
        vagrant docker-logs -f
```

Which is ugly and subject to random changes in the wording of English prose intended for human consumption and not computer parsing.

Or, if the devs think it's better to assume the user **didn't** want to "up" a VM when running the "reload" command, can we have some kind of "reload-or-up" command, or maybe a "--reload" option to the "up" command (or a "--up" option to the "reload" command), or possibly even an exit status to the "status" command (0 for "running", 1 for "created but not running" and 2 for "not created", or something like that)?

Edit: And I know Vagrant isn't really meant for this purpose, but just general script-ability is something I'm sure most users would appreciate. Also, just the annoyance of having to guess the state of my current vagrant instance when running commands manually, or having to run and visually parse "vagrant status" to know whether or not to run "vagrant up" or "vagrant reload". It just seems obvious that if I want to "reload", of course I want to "up" if it's not already created/running...

**Comment by briancain** [comment]
Hi there @memotype - thanks for opening an issue! I suggest you take at the alias feature recently merged into Vagrant as of 2.0.4. You can define your own `reload-or-up` command that will behave how you want for your scripts. Thanks!

https://www.vagrantup.com/docs/cli/aliases.html

**Comment by memotype** [comment]
Ok, but seems like something like this would be useful as a built-in, instead of having to define an alias on every build host or every user's machine, still seems like "reload" defaulting to "up" would be far more intuitive. The alias functionality is cool, but by that logic, "reload" could just be an alias for "up-or-destroy-then-up". I mean, isn't the whole point of Vagrant to be a collection of convenient functions for managing VMs? At what point do you just stop implementing features because "hey, we have 'alias' now, so go screw yourself and just write an alias"?

**Comment by chrisroberts** [comment]
Hi there,

I'm sorry that you are frustrated with the response that you received on this issue. 

> At what point do you just stop implementing features because "hey, we have 'alias' now, so go screw yourself and just write an alias"

This was never implied by the response to this issue and I would ask you to please be respectful of others when creating or replying on issues. We are all here to make Vagrant better in the ways that each of us can. Introducing hostility into the conversation does result in any gained productivity.

With regards to the behavior of the `reload` command referenced in this issue; the behavior of the `reload` command is to restart an existing guest by halting it and then starting it. The functionality of the `reload` command has never involved creating a new guest, nor destroying an existing guest. The alias tooling was recommended for the behavior you are seeking for two reasons:

1. The behavior you are seeking is non-standard
2. Modifying the existing behavior of exit codes is a very heavy change

Using an alias is likely the easiest way to attain the specific behavior you are seeking. If you don't feel like that is an appropriate solution for this issue, we are more than happy to review constructive arguments/criticisms or pull requests.

Cheers!

**Comment by memotype** [comment]
> and I would ask you to please be respectful of others when creating or replying on issues. 

You're right. I was frustrated trying to get my build jobs to work and it did seem like I was being brushed off, but re-reading the comment I can see how I misinterpreted it. I appologize.

> behavior of the reload command is to restart an existing guest 

I guess this is more of a docker-specific issue then, because the behavior of up and reload is different depending on if the container has already been built. And as far as I can tell, the exit status of the vagrant commands aren't a consistent way to tell if the command succeeded. For example, I tried `vagrant reload || vagrant up` in my build jobs, but the reload command outputs "the container hasn't been built" and exits with status `0` so the "up" never gets run. But if I just do "vagrant up" it won't rebuild the container even if the Dockerfile has been updated. And as far as I can tell, there's no good way to tell if container has been built already except for grepping the output of "vagrant status", but that's tricky because of the informational output at the bottom sometimes contains phrases that would make grepping tricky.

So, what I would like to suggest is one of the following:

1. As above, some kind of `--reload` option to the "up" command which causes it to "up or reload if already up" (similar to "--provision" which is handy if you don't know if the box is up or not, but you want to re-run the provisioners either way).

2. A `--rebuild` option to the "reload" command.

3. A "docker-rebuild" command that does a docker build regardless of whether or not the container is already built, and then starts up the container.

4. Make it so that "vagrant reload" just does an "up" if the container hasn't been built yet, possibly with a message saying that's what it's doing.

5. A change to the exit codes for commands to more precisely reflect whether or not the command succeeded so that `vagrant reload || vagrant up` works consistently.

I understand that this is probably a corner case, so I don't expect a quick fix or anything, it just seems like it would be something that at least some people might want. At a minimum, the ritual of having to run "vagrant status" every time to know if you should run "up" or "reload" feels unnecessarily tedious, let alone the difficulties in scripting.

As for the alias suggestion, I've read the linked doc page and I'm not sure how I would write an alias that would do a "reload-or-up".

**Comment by memotype** [comment]
I'd like to re-open this issue because I don't believe the functionality I'm requesting can be implemented with aliases, because from what I understand, you can only a) create a synonym for another command, or b) create a command that runs a shell script, but I can't find a way to reliably script this because the exit codes don't seem to reflect success or failure accurately, and there's no way to reliably parse the output of the status command.

**Comment by briancain** [comment]
Let's take a step back here. I'm trying to figure out exactly what the problem you're experiencing here is...

> But if I just do "vagrant up" it won't rebuild the container even if the Dockerfile has been updated.

From my testing, I do not actually experience the behavior you mentioned above. If I `vagrant up` a few docker images and then destroy/up or reload them, it does actually rebuild the images with the updated Dockerfile each time.

How are you actually running these containers in Vagrant in your Vagrantfile with the docker provider? Are you specifying a `build_dir`, or with the `image` option? With this configuration below using `build_dir`, Vagrant rebuilds the image any time you `up` a new set of containers or `reload` existing containers:

```ruby
(1..3).each do |i|
  config.vm.define "docker-#{i}"  do |vm|
    vm.vm.provider "docker" do |d|
      d.build_dir = "."
      d.cmd = ["tail", "-f", "/dev/null"]
    end
  end
end
```

In this case, with both the `reload` and `up` command, vagrant rebuilds the image. Like you mentioned, if you attempt to `reload` containers that don't exist, vagrant does not `up` them, but that is consistent behavior across all providers. I'm not sure if this is the actual problem you're running into, and trying to use reload/up to get around it? Maybe not...

All that being said, I'm still :-1: on changing the existing behavior and exit code status of the `reload` command, or changing its behavior to be different across multiple providers. I'm echoing the explanation on the feedback @chrisroberts mentioned above.

And we're back to aliases. This should give you the ability to write out the non-standard behavior you are looking for today. If you want to script behavior based on `vagrant status`, you can always include the `--machine-readable` flag which will output a more script-friendly format. Then you can have a more machine friendly format for checking if your containers do not exist, so you can run up instead of halt in your alias script.

**Comment by memotype** [comment]
>In this case, with both the reload and up command, vagrant rebuilds the image

This is not the behavior I'm experiencing. When I do an "up" and the container is already built, it just gives a warning and starts the already built container:

```
$ vagrant up
Bringing machine 'default' up with 'docker' provider...
==> default: Image is already built from the Dockerfile. `vagrant reload` to rebuild.
==> default: Vagrant has noticed that the synced folder definitions have changed.
==> default: With Docker, these synced folder changes won't take effect until you
==> default: destroy the container and recreate it.
==> default: Starting container...
==> default: Provisioners will not be run since container doesn't support SSH.
```

>you can always include the --machine-readable flag 

I had no idea this option even existed, it's not listed in the `--help`. I'll look in to this, because it might be the solution I'm looking for.

**Comment by memotype** [comment]
Also, to be clear, the destroy+up option is what I'm doing currently, but I don't want to have to destroy and completely rebuild if it's not necessary, I want to let docker do it's smart thing by only rebuilding layers that need to be rebuilt, if any.

**Comment by chrisroberts** [comment]
@memotype Can you provide a minimal Vagrantfile that reproduces the behavior you are experiencing? This should help us not only to see the actual behavior but also help us to pinpoint what you are running into.

Thanks!

**Comment by memotype** [comment]
Vagrantfile: http://termbin.com/sh0k

Dockerfile: http://termbin.com/y3m1

test.sh: http://termbin.com/uhi2

Console interaction: http://termbin.com/4dlw

**Comment by memotype** [comment]
(Also, I'm not sure why I'm getting those golang stack traces, I've been meaning to open an issue about that, but I'm not sure where to open it. I don't get those stack traces when I run docker commands manually.)

**Comment by dreki** [comment]
This would be a great feature. We automate Docker container creation via Vagrant, and being able to do this easily and reliably would be super useful.

**Comment by memotype** [comment]
Since opening this issue, I've switched to using docker-compose wherever possible, because it handles cases of container re-creation a lot more simply. I'll unsubscribe from this issue, but leave it open in case anyone else wants to track it.

**Comment by briancain** [comment]
After reviewing this issue again this time, we don't think it makes sense to change the established behavior of the reload command in Vagrant. Again, thank you for suggesting this and taking the time to contribute to the project. Cheers!
