### ISSUE TITLE
Snapshot plugin should exit with non-zero code if unknown subcommand

### ISSUE THREAD

**Issue by wolfgang42** [hashicorp/vagrant#9773]
**Vagrant version:** 2.0.4
**Host operating system:** Ubuntu 16.04
**Guest operating system:** any

I keep making this mistake:
<pre>
$ ./command1.sh && <strong>vagrant snapshot take after-command1</strong> && ./command2.sh
Doing complicated things #1...
<strong>Usage: vagrant snapshot &lt;subcommand&gt; [&lt;args&gt;]

Available subcommands:
     delete
     list
     pop
     push
     restore
     save

For help on any individual subcommand run `vagrant snapshot &lt;subcommand&gt; -h`</strong>
Doing complicated things #2...
</pre>

What I meant to do, of course, is <code>vagrant snapshot <em>save</em></code>, but even though I messed up the command it carried on regardless, so when it turned out that command2 didn't do what I wanted I had to roll back to an even earlier snapshot and rerun command1, thus losing 45 minutes.

### Expected behavior
`vagrant snapshot <unknown-subcommand>` should exit with a non-zero exit code.

### Actual behavior
`vagrant snapshot <unknown-subcommand>` returns exit code 0.

If this change sounds OK I will work on a patch.

**Comment by wolfgang42** [comment]
For my own reference, here's the section that implements this logic: https://github.com/hashicorp/vagrant/blob/9c299a2a357fcf87f356bb9d56e18a037a53d138/plugins/commands/snapshot/command/root.rb#L54-L57

**Comment by TomyLobo** [comment]
Thanks for reporting this, wolfgang. Precisely my issue :)

I tend to do the following to temporarily abuse a VM and revert it back to its original state
```
vagrant snapshot take foo && vagrant up --provision && vagrant halt -f && (command to restore the snapshot without booting) && vagrant snapshot delete foo
```
If the snapshot isn't taken, that's pretty bad...

Also thanks brian for fixing it.
