### ISSUE TITLE
Vagrant commands not working for Hyper-V provisioner

### ISSUE THREAD

**Issue by oldluke92** [hashicorp/vagrant#9775]
### Vagrant version
2.1.0

### Host operating system
Windows 10 v1803 (April Update)

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1604"
end
```

### Debug output
[vagrant destroy log](https://gist.github.com/oldluke92/ca5d7a4d849a22cead49691fd90caeec)

### Expected behavior
Vagrant command should be executed

### Actual behavior

Error occures:

```
C:/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/lib/vagrant/machine.rb:164:in `action': undefined method `fire_triggers' for nil:NilClass (NoMethodError)
[...]
```

### Steps to reproduce
1. Get a pc with Windows 10 pro x64 and HyperV
2. Install Vagrant 2.1.0
3. Place the contents of the mentioned Vagrantfile above in a Vagrantfile in some directory
4. Repair the 'vagrant up' Command (see #9774 )
5. Start powershell as administrator (Click on the windows logo on your windows taskbar, type "powershell", right-click the "Windows Powershell" entry and click the "Run as Administrator" option.
6. Navigate to the directory with the above mentioned Vagrantfile in the powershell window
7. type 'vagrant up', hit enter and wait for the VM to be created and booted
8. try using 'vagrant halt', 'vagrant destroy', 'vagrant ssh' or 'vagrant provision' (I'm pretty sure any other command will fail too, but these are the ones I tested)

**Comment by josenk** [comment]
Also a problem with vagrant-vmware-esxi.
   https://github.com/josenk/vagrant-vmware-esxi/issues/39

I can confirm the problem is resolved in Vagrant 2.1.1.dev.
