### ISSUE TITLE
rsync: Option to toggle privilege

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9779]
Some guests such as Haiku nighty x86 are unable to offer privileged SSH channels. This leads to breakages in `vagrant rsync`, as the base rsync capability assumes a full `sudo`-enabled channel.

https://github.com/hashicorp/vagrant/blob/master/plugins/synced_folders/rsync/default_unix_cap.rb

Could we add a `privileged` option to rsync configuration, similar to shell script provisioning, so that rsync can continue to function in (single-user) environments without privileged/sudo channels?

**Comment by soapy1** [comment]
Hi there,

It looks like will be resolved in the next shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one. This is already covered in the config option `rsync__rsync_path`.

Cheers!
