### ISSUE TITLE
Haiku guest plugin: avoid privileged SSH channel for rsync commands

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9780]
Haiku nightly is primarily a single-user system and Haiku nightly x86 does not appear to support privileged SSH channels, breaking `vagrant rsync`. Specifically, the Haiku guest plugin should override the base rsync_pre, rsync, and rsync_post implementations, removing the sudo elevation of the SSH communication.

I'm trying crazy hacks to work around this by heavily customizing the SmartOS guest plugin (one of the few plugins that does not use a privileged SSH channel) and applying that to my Haiku nightly x86 box, but long term it would be better to have the Haiku guest plugin account for this behavior.

**Comment by soapy1** [comment]
Hi there,

It looks like will be resolved in the next shipped version of Vagrant so I am now closing this issue. If the original issue was not fully resolved, please reopen this issue or create a new one. This is already covered in the config option rsync__rsync_path.

Cheers!
