### ISSUE TITLE
Corruption in vagrant global-status

### ISSUE THREAD

**Issue by mcandre** [hashicorp/vagrant#9786]
`vagrant global-status` often reports leftover VMs, when in fact the resources have been deleted, including the VirtualBox instances and the relevant source directories. Would be nice if `global-status` could somehow detect when this is the case, and maybe cleanup the leftover Vagrant internal metadata that was having the instance present in the `global-status` report.

**Comment by briancain** [comment]
Hi, this seems to be a duplicate of https://github.com/hashicorp/vagrant/issues/10380 and since there was no response on that one, I'm going to go ahead and close it. Thanks!
