### ISSUE TITLE
hyperv: setting enable_virtualization_extension not provided, but a "shouldn't exist" error is raised.

### ISSUE THREAD

**Issue by kopfpilot** [hashicorp/vagrant#9789]
### Vagrant version
2.1.0 (+ change from https://github.com/hashicorp/vagrant/commit/2730fe7ec9ab1c39c9bda2d63c5745026639a783)

### Host operating system
Windows 10 [10.0.17134.1]

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu1604-desktop"
  config.vm.network "private_network", bridge: "c08cb7b8-9b3c-408e-8e30-5e16a3aeb444"
end
```

### Debug output
relevant part of the debug output:
>  INFO warden: Calling IN action: #<Vagrant::Action::Builtin::ConfigValidate:0x0000000005e7af40>
> ERROR warden: Error occurred: There are errors in the configuration of this machine. Please fix
>the following errors and try again:
>
>Hyper-V:
>* The following settings shouldn't exist: enable_virtualization_extension

### Expected behavior
The VM should have been created.

### Actual behavior
The error message 'The following settings shouldn't exist: enable_virtualization_extension' appeared.
According the documentation the parameter is "enable_virtualization_extensions". 

Also it does not matter if enable_virtualization_extension or enable_virtualization_extensions is present in the Vagrantfile. The result is always the same.

When I perform a search in the vagrant installation folder, all results include the additional s, which is missing in the error message.
```
$ grep -E 'enable_virtualization_extension' -R /c/HashiCorp/Vagrant
/c/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/providers/hyperv/action/import.rb:          enable_virtualization_extensions = env[:machine].provider_config.enable_virtualization_extensions
/c/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/providers/hyperv/action/import.rb:          env[:ui].output("Configured enable virtualization extensions is #{enable_virtualization_extensions}") if enable_virtualization_extensions
/c/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/providers/hyperv/action/import.rb:          options[:enable_virtualization_extensions] = "True" if enable_virtualization_extensions and enable_virtualization_extensions == true
/c/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/providers/hyperv/config.rb:      attr_accessor :enable_virtualization_extensions # Enable virtualization extensions (nested virtualization). Values: true, false
/c/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/providers/hyperv/config.rb:        @enable_virtualization_extensions = UNSET_VALUE
/c/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/providers/hyperv/config.rb:        @enable_virtualization_extensions = false if @enable_virtualization_extensions == UNSET_VALUE # TODO will this work?
/c/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/providers/hyperv/scripts/import_vm_vmcx.ps1:    [string]$enable_virtualization_extensions=$False
/c/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/providers/hyperv/scripts/import_vm_vmcx.ps1:if ($enable_virtualization_extensions -eq "True") {
/c/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/providers/hyperv/scripts/import_vm_xml.ps1:    [string]$enable_virtualization_extensions=$False
/c/HashiCorp/Vagrant/embedded/gems/2.1.0/gems/vagrant-2.1.0/plugins/providers/hyperv/scripts/import_vm_xml.ps1:if ($enable_virtualization_extensions -eq "True") {
```
How is this validation error even possible?!

### Steps to reproduce
1. Install vagrant 2.1.0 to c:\HashiCorp
2. Fix file c:\HashiCorp\Vagrant\embedded\gems\2.1.0\gems\vagrant-2.1.0\plugins\providers\hyperv\action\import.rb according change in commit 2730fe7.
3. vagrant up

**Comment by chrisroberts** [comment]
Hi there,

Can you please provide a debug gist from: `vagrant up --debug`

Thanks!

**Comment by kopfpilot** [comment]
Here we go https://gist.github.com/kopfpilot/d8473de605d06086dbe648c28cd59ce6
