### ISSUE TITLE
shell provider not running scripts on domain joined machines.

### ISSUE THREAD

**Issue by whiggs** [hashicorp/vagrant#9815]
I have a variety of different Windows machines defined in my Vagrantfile.  Some of these machines are domain joined, and some of them are not.  The non-domain joined machines use the "vagrant" username and password to authenticate using Winrm, but I use my domain credentials to authenticate to winrm on the machines which are domain joined.  I have noticed that the ability to run inline scripts using the shell provider on machines which are joined to a domain (in the vagrant file, "master" is the machine that I used) is broken.  The console will say that it is running the inline script, but never generates any output that should be returned by the inline script, and I can verify the inline script did not run due to the absense of tasks which the script was supposed to complete when logging into the machine after it has been created.  I have not verified if this issue extends to external scripts as well, but it appears to be an issue with the shell provider itself.
**What it should look like**
![image](https://user-images.githubusercontent.com/11139575/39816792-438cc388-536a-11e8-913c-756beeec937c.png)

**What it actually looks like**
![image](https://user-images.githubusercontent.com/11139575/39816831-62ba1cec-536a-11e8-9247-00f073df4b01.png)

### Vagrant version
2.1.1

### Host operating system
Windows 10 1709 x64

### Guest operating system
Windows server 2016

### Vagrantfile
$packageTestScript = <<SCRIPT
net.exe config server /autodisconnect:-1
$ErrorActionPreference = "Stop"
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
$env:PATH +=";$($env:SystemDrive)\\ProgramData\\chocolatey\\bin"
Get-PackageProvider -Name NuGet -ForceBootstrap -Force
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Install-module Azurerm -allowclobber -force
choco.exe install -fvy serviceassistant --source 'https://www.myget.org/F/serviceassistant/api/v2'
choco.exe install -fvy sharepointconsole --source 'https://www.myget.org/F/sharepointconsole/api/v2'
SCRIPT

$packageserverScript = <<SCRIPT
net.exe config server /autodisconnect:-1
$ErrorActionPreference = "Stop"
iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
$env:PATH +=";$($env:SystemDrive)\\ProgramData\\chocolatey\\bin"
Get-PackageProvider -Name NuGet -ForceBootstrap -Force
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Install-module Azurerm -allowclobber -force
choco.exe install -fvy serviceassistant --source 'https://www.myget.org/F/serviceassistant/api/v2'
choco.exe install -fvy sharepointconsole --source 'https://www.myget.org/F/sharepointconsole/api/v2'
choco.exe install conemu -yvf
Add-WindowsFeature -Name RSAT-AD-Tools
Add-WindowsFeature -Name RSAT-AD-Powershell
SCRIPT

Vagrant.configure("2") do |config|
config.vm.box = "atlas_shrugged/vsphere_dummy"
config.vm.box_check_update = true
config.vm.define "master" do |sub|
	sub.vm.guest = :windows
	sub.vm.usable_port_range = 2200..6000
	sub.vm.communicator = "winrm"
	sub.vm.boot_timeout = 500
	sub.winrm.transport = :negotiate
	sub.winrm.basic_auth_only = true
	sub.winrm.port = 5985
	sub.winrm.guest_port = 5985
	sub.winrm.username = 'LL_MAIN\'
	sub.winrm.password = ""
	sub.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true #, host_ip: "127.0.0.1"
	sub.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true #, host_ip: "127.0.0.1"
	sub.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
	#sub.vm.network :forwarded_port, guest: 139, host: 139, id: "smb", auto_correct: true #, host_ip: "127.0.0.1"
	sub.vm.synced_folder "packages", "C:/vagrant", type: "smb", smb_username: 'LL_MAIN\', smb_password: ""
	#sub.vm.provision :shell, :path => 'packages/install-rsat.ps1', :powershell_elevated_interactive => true
	sub.vm.provision :shell, :inline => $packageserverScript, :powershell_elevated_interactive => true
	sub.vm.provision "reload"
	sub.vm.provider "vsphere" do |vsphere, override|
		vsphere.host = 'vcenter-test.acuitylightinggroup.com'
		vsphere.insecure = true
		vsphere.compute_resource_name = 'Test Environment'
		#vsphere.resource_pool_name = 'NFS_CDOTSAS_Busintellocal'
		vsphere.template_name = '/Templates/dom'
		vsphere.vm_base_path = "B.Local/Hyperion"
		vsphere.name = 'vagrrrmas'
		vsphere.user = 'LL_MAIN\'
		vsphere.password = ''
	end
  end
  config.vm.define "after" do |dom|
	dom.vm.guest = :windows
	dom.vm.usable_port_range = 22..6000
	dom.vm.communicator = "winrm"
	dom.vm.boot_timeout = 500
	dom.winrm.transport = :negotiate
	dom.winrm.basic_auth_only = true
	dom.winrm.port = 5985
	dom.winrm.guest_port = 5985
	dom.winrm.username = "vagrant"
	dom.winrm.password = "vagrant"
	#dom.vm.communicator = "ssh"
	#dom.ssh.username = "saynotoadmins"
	#dom.ssh.keep_alive = "True"
	
	dom.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true #, host_ip: "127.0.0.1"
	dom.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true #, host_ip: "127.0.0.1"
	dom.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
	#dom.vm.network :forwarded_port, guest: 139, host: 139, id: "smb", auto_correct: true #, host_ip: "127.0.0.1"
	#dom.vm.synced_folder 'packages', '/packages'
	dom.vm.synced_folder "packages", "C:/vagrant", type: "smb", smb_username: 'LL_MAIN\', smb_password: ""
	dom.vm.provision :shell, :path => 'packages/install-rsat.ps1', :powershell_elevated_interactive => true
	dom.vm.provision :shell, :inline => $packageTestScript, :powershell_elevated_interactive => true
	dom.vm.provision :shell, :path => 'packages/join-domain.ps1', :powershell_elevated_interactive => true
	#dom.vm.provision "shell", path: "packages/join-domain.ps1", privileged: false
	dom.vm.provision "reload"
	dom.vm.provider "vsphere" do |vsphere, override|
		vsphere.host = 'vcenter-test.acuitylightinggroup.com'
		vsphere.insecure = true
		vsphere.compute_resource_name = 'Test Environment'
		#vsphere.resource_pool_name = 'NFS_CDOTSAS_Busintellocal'
		vsphere.template_name = '/Templates/thev'
		vsphere.vm_base_path = "B.Local/Hyperion"
		vsphere.name = 'vagrrr2'
		vsphere.user = 'LL_MAIN\'
		vsphere.password = ''
	end
  end
  config.vm.define "newvagrant" do |new|
	new.vm.guest = :windows
	new.vm.usable_port_range = 22..6000
	new.vm.communicator = "winrm"
	new.vm.boot_timeout = 500
	new.winrm.transport = :negotiate
	new.winrm.basic_auth_only = true
	new.winrm.port = 5985
	new.winrm.guest_port = 5985
	new.winrm.username = "vagrant"
	new.winrm.password = "vagrant"
	#new.vm.communicator = "ssh"
	#new.ssh.username = "vagrant"
	#new.ssh.password = "vagrant"
	#new.winssh.keep_alive = "True"
	
	new.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true #, host_ip: "127.0.0.1"
	new.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true #, host_ip: "127.0.0.1"
	new.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
	#new.vm.network :forwarded_port, guest: 139, host: 139, id: "smb", auto_correct: true #, host_ip: "127.0.0.1"
	#dom.vm.synced_folder 'packages', '/packages'
	new.vm.synced_folder "packages", "C:/vagrant", type: "smb", smb_username: 'LL_MAIN\', smb_password: ""
	new.vm.provision :shell, :path => 'packages/install-rsat.ps1', :powershell_elevated_interactive => true
	new.vm.provision :shell, :inline => $packageTestScript, :powershell_elevated_interactive => true
	#dom.vm.provision "shell", path: "packages/join-domain.ps1", privileged: false
	new.vm.provision "reload"
	new.vm.provider "vsphere" do |vsphere, override|
		vsphere.host = 'vcenter-test.acuitylightinggroup.com'
		vsphere.insecure = true
		vsphere.compute_resource_name = 'Test Environment'
		#vsphere.resource_pool_name = 'NFS_CDOTSAS_Busintellocal'
		vsphere.template_name = '/Templates/thev'
		vsphere.vm_base_path = "B.Local/Hyperion"
		vsphere.name = 'lastvagr'
		vsphere.user = 'LL_MAIN\'
		vsphere.password = ''
	end
  end
  config.vm.define "trend" do |tre|
	tre.vm.guest = :windows
	tre.vm.usable_port_range = 2200..6000
	tre.vm.communicator = "winrm"
	tre.vm.boot_timeout = 500
	tre.winrm.transport = :negotiate
	tre.winrm.basic_auth_only = true
	tre.winrm.port = 5985
	tre.winrm.guest_port = 5985
	tre.winrm.username = 'vagrant'
	tre.winrm.password = "vagrant"
	#tre.vm.communicator = "ssh"
	#tre.ssh.username = "saynotoadmins"
	#tre.ssh.keep_alive = "True"
	
	tre.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true #, host_ip: "127.0.0.1"
	tre.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true #, host_ip: "127.0.0.1"
	tre.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
	tre.vm.network :forwarded_port, guest: 139, host: 139, id: "smb", auto_correct: true #, host_ip: "127.0.0.1"
	tre.vm.synced_folder ".", '/packages', type: "smb", create: true
	tre.vm.provision :shell, :path => 'packages/install-rsat.ps1', :powershell_elevated_interactive => true
	tre.vm.provision :shell, :inline => $packageTestScript, :powershell_elevated_interactive => true
	#dom.vm.provision "shell", path: "packages/join-domain.ps1", privileged: false
	tre.vm.provision "reload"
	tre.vm.provider "vsphere" do |vsphere, override|
		vsphere.host = 'vcenter-test.acuitylightinggroup.com'
		vsphere.insecure = true
		vsphere.compute_resource_name = 'Test Environment'
		#vsphere.resource_pool_name = 'NFS_CDOTSAS_Busintellocal'
		vsphere.template_name = '/Templates/tren'
		vsphere.vm_base_path = "B.Local/Hyperion"
		vsphere.name = 'vagrtrend'
		vsphere.user = 'LL_MAIN\'
		vsphere.password = ''
	end
  end
  config.vm.define "regular" do |reg|
	reg.vm.guest = :windows
	reg.vm.usable_port_range = 2200..6000
	reg.vm.communicator = "winrm"
	reg.vm.boot_timeout = 500
	reg.winrm.transport = :negotiate
	reg.winrm.basic_auth_only = true
	reg.winrm.port = 5985
	reg.winrm.guest_port = 5985
	reg.winrm.username = "vagrant"
	reg.winrm.password = "vagrant"
	reg.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true #, host_ip: "127.0.0.1"
	reg.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true #, host_ip: "127.0.0.1"
	reg.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
	#reg.vm.network :forwarded_port, guest: 139, host: 139, id: "smb", auto_correct: true #, host_ip: "127.0.0.1"
	reg.vm.synced_folder "packages", "C:/vagrant", type: "smb", smb_username: 'LL_MAIN\', smb_password: ""
	#reg.vm.provision :shell, :path => 'packages/install-rsat.ps1', :powershell_elevated_interactive => true
	reg.vm.provision :shell, :inline => $packageTestScript, :powershell_elevated_interactive => true
	reg.vm.provision "reload"
	#dom.vm.provision "shell", path: "packages/join-domain.ps1", privileged: false
	reg.vm.provider "vsphere" do |vsphere, override|
		vsphere.host = 'vcenter-test.acuitylightinggroup.com'
		vsphere.insecure = true
		vsphere.compute_resource_name = 'Test Environment'
		#vsphere.resource_pool_name = 'NFS_CDOTSAS_Busintellocal'
		vsphere.template_name = '/Templates/reg10'
		vsphere.vm_base_path = "B.Local/Hyperion"
		vsphere.name = 'vagrreg10'
		vsphere.user = 'LL_MAIN\'
		vsphere.password = ''
	end
  end
end

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
https://gist.github.com/whiggs/eafbb9ca145dc0fd28293793f494ab87

### Expected behavior
The shell provisioner should run the inline powershell script

### Actual behavior
Console says that it is running the inline script, but no output is returned and, when machine is accessed via rdp, none of the tasks that script was to perform have been done.

### Steps to reproduce
1. run "vagrant up master"
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?
For example:
- GH-1234
- ...

**Comment by kikitux** [comment]
Hello

Your description of the issue is very complicated to be able to reproduce.

Can be something on the base box, the domain, the plugin, network, long etc.

As we don't have any of those to reproduce this, I would suggest:

- try to reproduce on a minimal Vagrantfile
- using virtualbox

So we can reproduce this, otherwise is difficult to start.

**Comment by chrisroberts** [comment]
Hi there,

Would you please provide a minimal Vagrantfile that displays the unexpected behavior and the debug log from using the minimal Vagrantfile. 

Thanks!
