### ISSUE TITLE
WSL use custom box have a error . This is usually because the filesystem "vboxsf" is not available.

### ISSUE THREAD

**Issue by kuops** [hashicorp/vagrant#9816]
when i use the custom box in `Windows WSL`（use the centos/7 base box install other soft），use vagrant package export a box，do `vagrant init mycentos/7 && vagrant up`   

### Vagrant version
```
kuops@kuops:/mnt/d/vagrant-home/mycentos$ vagrant -v
Vagrant 2.1.1
```
### Host operating system
```
kuops@kuops:/mnt/d/vagrant-home/mycentos$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
kuops@kuops:/mnt/d/vagrant-home/mycentos$ uname  -r
4.4.0-43-Microsoft
```
### Guest operating system
This is the operating system you run in the virtual machine.

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "mycentos/7"
end
```

### Debug output
```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount: unknown filesystem type 'vboxsf'
```

vagrant plugin list
```
kuops@kuops:/mnt/d/vagrant-home/mycentos$ vagrant  plugin list
No plugins installed.
```

**Comment by kuops** [comment]
![qq 20180509230021](https://user-images.githubusercontent.com/18283256/39822334-e3762002-53dc-11e8-8f3e-4ed6b8788e24.png)

**Comment by briancain** [comment]
Hello @kuops - You need to make sure that the virtualbox guest additions are installed on your custom vagrant box. Otherwise you won't be able to mount the shared folder. This step usually happens when you build your own box. Thanks!
