### ISSUE TITLE
vagrant-vbguest plugin: does not upd./inst. VBoxGuestAdditions in guests/nodes of DC/OS

### ISSUE THREAD

**Issue by RogerWeihrauch** [hashicorp/vagrant#9819]
Hi all
Regardless using default 'vagrant up' command or additional lines in 'Vagrantfile' like:
  # Vagrant Plugin Installer Parameters:
  config.vbguest.installer_arguments=['--nox11','--force','-- --do']
Whether the integrated VBoxGuestAdditions.iso  is used for install, nor the recent one can/will be installed (automatically or manually).
Trying to use it while getting DC/OS up and running and can be reproduced with default deploying procedure on every 'vagrant up' command

## Vagrant version
rogiwankenobi@jessie:~$ vagrant -v
Vagrant 2.1.1
rogiwankenobi@jessie:~$ 

###Host operating system
rogiwankenobi@jessie:~$ uname -a
Linux jessie 4.9.0-0.bpo.6-amd64 #1 SMP Debian 4.9.82-1+deb9u3~bpo8+1 (2018-03-22) x86_64 GNU/Linux
rogiwankenobi@jessie:~$

### Guest operating system
rogiwankenobi@jessie:~/dcos-vagrant$ ssh vagrant@m1.dcos
vagrant@m1.dcos's password: 
[vagrant@m1 ~]$ uname -a
Linux m1.dcos 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@m1 ~]$ cat /proc/version 
Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016
[vagrant@m1 ~]$ 

### Vagrantfile
You will find at this gist:
<script src="https://gist.github.com/RogerWeihrauch/18d5d4cd9bdba9db1749652a9ed8d421.js"></script>

### Debug output on 'vagrant up' you will find here:
<script src="https://gist.github.com/RogerWeihrauch/18d5d4cd9bdba9db1749652a9ed8d421.js"></script>

### Expected behavior
ASFAIK; the VBoxGuestAdditions should be installed during first vagrant up for DC/OS on each node;or be upgraded after check on a new version of them.

### Actual behavior
The VBoxGuestAdditions are not touched in any way.0

### Steps to reproduce
1. get up a DC/OS cluster with 'vagrant up' as described on 'https://github.com/dcos/dcos-vagrant' and watch command line output relating to any hints on VBoxGuestAdditions. (There will be none or a hint on not matching versions)
2. execute rogiwankenobi@jessie:~/dcos-vagrant$ vagrant vbguest --status and watch the informations given:
rogiwankenobi@jessie:~/dcos-vagrant$ vagrant vbguest --status
 INFO dcos-vagrant: Validating Plugins...
 INFO dcos-vagrant: Validating User Config...
 INFO dcos-vagrant: Validating Installer Checksum...
 INFO dcos-vagrant: Using DC/OS Installer: installers/dcos/dcos_generate_config-1.11.0.sh
 INFO dcos-vagrant: Using DC/OS Config: etc/config-1.11.yaml
 INFO dcos-vagrant: Validating Machine Config...
 INFO dcos-vagrant: Validating Command...
 INFO dcos-vagrant: Configuring VirtualBox Host-Only Network...
[m1] GuestAdditions versions on your host (5.1.34) and guest (5.1.18) do not match.
[a1] GuestAdditions versions on your host (5.1.34) and guest (5.1.18) do not match.
[a2] GuestAdditions versions on your host (5.1.34) and guest (5.1.18) do not match.
[a3] GuestAdditions versions on your host (5.1.34) and guest (5.1.18) do not match.
[a4] GuestAdditions versions on your host (5.1.34) and guest (5.1.18) do not match.
[a5] GuestAdditions versions on your host (5.1.34) and guest (5.1.18) do not match.
[p1] GuestAdditions versions on your host (5.1.34) and guest (5.1.18) do not match.
[boot] GuestAdditions versions on your host (5.1.34) and guest (5.1.18) do not match.
rogiwankenobi@jessie:~/dcos-vagrant$ 

3. try to manually install on CLI in each node: no success

### References
Are there any other GitHub issues (open or closed) that should be linked here?
If you google around with keywords like: 'vagrant vbguest plugin' you may find many hints on not working the plugin as expected/intended to.

**Comment by briancain** [comment]
Hi there @RogerWeihrauch - Thanks for the issue, however the plugin you are looking for is in a different project! https://github.com/dotless-de/vagrant-vbguest Thanks.
