### ISSUE TITLE
`vagrant box list -i` adds no additional information

### ISSUE THREAD

**Issue by triplepoint** [hashicorp/vagrant#9826]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
vagrant 2.1.1

### Host operating system
macos 10.13.4

### Guest operating system
N/A

### Vagrantfile
N/A

### Debug output
N/A

### Expected behavior
`vagrant box list -i` or `vagrant box list --box-info` are listed in the output of `vagrant box list --help` as `Displays additional information about the boxes`.

this flag should cause vagrant box list to print additional information (ideally the URL for the box, but I'm not really sure what it was intended to produce).

### Actual behavior
The output of `vagrant box list -i` and `vagrant box list` are identical.

### Steps to reproduce
1. `vagrant box list -i`
2. ` vagrant box list`
3.  Observe that the outputs are the same.

**Comment by briancain** [comment]
Hi @triplepoint , yes! I can see why that option seems unusual. That option is still valid. The majority of the time Vagrant boxes do not provide any additional information about the box for the output to differ without the argument. This is up to the box maintainer to supply, but is often not utilized.

If you want to know more we have docs on that here! https://www.vagrantup.com/docs/boxes/info.html Thanks.
