### ISSUE TITLE
Shell provisioner does not properly detect failure

### ISSUE THREAD

**Issue by chrisroberts** [hashicorp/vagrant#9830]
When running a shell provisioner on a windows guest via the winrm communicator, the provisioner may return a false success when the `powershell_elevated_interactive` option is enabled. Was reproduced by creating a `vagranttest` administrator user. 

### Vagrant version
2.1.2.dev

### Host operating system
any

### Guest operating system
windows

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = 'win10'
  config.vm.provision :shell, :inline => 'New-Item C:\testfile.txt -ItemType file', :powershell_elevated_interactive => true
  config.winrm.username = 'vagranttest'
  config.winrm.password = 'vagranttest'
end
```

### Debug output

Failure when running as vagranttest user:

https://gist.github.com/chrisroberts/41b36611d2ee90bf9ef54698fc896335

Success when running as vagrant user:

https://gist.github.com/chrisroberts/2b4a252a4ee4d6fe18c4218e6f45a4af

### Expected behavior

Vagrant should produce an error message that provisioner was not successfully run when configured user does not have an active session.

### Actual behavior

Provision task appears to be successful.

### Steps to reproduce

1. Create new admin user
2. Update winrm config to user new admin user
3. Attempt to run provisioner

**Comment by soapy1** [comment]
This issue has been resolved by vagrant 2.2.7
