### ISSUE TITLE
vagrant chef-solo provisioning fails with no method error

### ISSUE THREAD

**Issue by anadimisra** [hashicorp/vagrant#9835]
### Vagrant version
Anadis-MacBook-Pro:vbox-vm anadi$ vagrant -v
Vagrant 2.1.1

### Host operating system
OSX High Sierra

### Guest operating system
ubuntu 16.04 x86_64

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "provisioner" do |provisioner|
    provisioner.vm.box = "ubuntu/xenial64"
    provisioner.vm.box_version = "20180509.0.0"
    provisioner.vm.box_check_update = false
    provisioner.omnibus.chef_version = :latest
    provisioner.vm.network "forwarded_port", guest: 80, host: 8989
    provisioner.vm.provider :virtualbox do |vbox|
      vbox.name = "chef-provisioned"
    end
    provisioner.vm.provision "chef_solo" do |chef|
      chef.node_name = "chef-provisioned"
      chef.cookbooks_path = "../../cookbooks"
      chef.verbose_logging = true
      chef.add_recipe "learn_chef_apache2"
    end
  end
end
```
### Debug output
https://gist.github.com/anadimisra/a370cf4178c842ad1d261907eca637ae

### Expected behavior
Vagrant Provisions an Ubuntu machine through chef with Apache HTTPD web server installed

### Actual behavior
Fails with FATAL error 
```bash
==> provisioner: Running chef-solo...
==> provisioner: [2018-05-15T10:40:14+00:00] FATAL: Configuration error NoMethodError: undefined method `<<' for nil:NilClass
==> provisioner: [2018-05-15T10:40:14+00:00] FATAL:   /tmp/vagrant-chef/solo.rb:24:in `from_string'
==> provisioner: [2018-05-15T10:40:14+00:00] FATAL: Aborting due to error in '/tmp/vagrant-chef/solo.rb'
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```
### Steps to reproduce
1. Use Vagrant with Virtualbox provider
2. Create a simple chef provisioner
3. run vagrant up

### Generated solo.rb file from the Guest VM
```ruby
node_name "chef-provisioned"
file_cache_path    "/var/chef/cache"
file_backup_path   "/var/chef/backup"
cookbook_path ["/tmp/vagrant-chef/4cf62a940e70dd6c25094e15c3d06903/cookbooks"]
log_level :info
verbose_logging true

encrypted_data_bag_secret nil






http_proxy nil
http_proxy_user nil
http_proxy_pass nil
https_proxy nil
https_proxy_user nil
https_proxy_pass nil
no_proxy nil


Chef::Config.from_file "/tmp/vagrant-chef/custom-config.rb"
```

and in the `/tmp/vagrant-chef/custom-config.rb` file

```ruby
Ohai::Config[:plugin_path] << "/etc/chef/ohai_plugins"
```

**Comment by chrisroberts** [comment]
Looks like the plugin path config value isn't initialized to an array as it previously has been. Should be able to fix it up with a check/init before push.

**Comment by anadimisra** [comment]
@chrisroberts I'm not very good at ruby, but I could try fixing and a pull request if you can guide me to the files where this might be coming from

**Comment by chrisroberts** [comment]
@anadimisra Hi! After chasing down the origin of this error, it looks like it's the vagrant-ohai plugin which is creating the custom config file, so there is nothing that can be done from Vagrant itself. The file creation happens here: https://github.com/avishai-ish-shalom/vagrant-ohai/blob/master/lib/vagrant-ohai/action_configure_chef.rb#L20

Cheers!

**Comment by anadimisra** [comment]
@chrisroberts thanks! I'll see their source code and file a pull request
