### ISSUE TITLE
Support vagrant trigger.after for the status action

### ISSUE THREAD

**Issue by gforghetti** [hashicorp/vagrant#9845]
### Vagrant version
2.1 

### Host operating system
Not applicable

### Guest operating system
Not applicable

### Vagrantfile
```ruby
Not applicable
```

### Debug output
Not applicable

Would be nice if the vagrant trigger.after would support the **:status** action.
It would be very handy to be able to run a script after a **vagrant status** command.
In my case the script would query and display information from the guest to check the status of applications, memory, cpu util, etc, etc.

**Comment by ArneBachmann** [comment]
Nice idea

**Comment by briancain** [comment]
Hey there, this will be in the next release of Vagrant via #10615. Cheers! :tada:
