### ISSUE TITLE
Allow executing commands on the host between provisioning commands

### ISSUE THREAD

**Issue by sandersaares** [hashicorp/vagrant#9846]
Vagrant triggers appear to only be able to execute commands before or after Vagrant operations like "up". What I need is the ability to execute a command between two provisioning commands along the lines of:

1. `config.vm.provision aaa`
1. Now run something on host
1. `config.vm.provision bbb`

With vagrant-triggers plugin this is possible as:

```ruby
  config.vm.provision aaa

  config.vm.provision "Run command on host",
    type: "trigger" do |trigger|
    trigger.fire do
      run "xyz"
    end
  end

  config.vm.provision bbb
```

I request an equivalent capability be added to Vagrant (or documented, if it already exists).

**Comment by briancain** [comment]
Hey there, this will be in the next release of Vagrant via #10615. Cheers! :tada:
