### ISSUE TITLE
hashicorp-files.hashicorp.com is down

### ISSUE THREAD

**Issue by mlushpenko** [hashicorp/vagrant#9847]
I am trying to run vagrant up and it keeps timing out to download the box. I tried curling and pining website from home and work networks and getting the same results.

If I try to download `ubuntu/precise32` everything goes fine.

**Comment by chrisroberts** [comment]
Hi there. That host has been deactivated and boxes stored at that location have been migrated to Vagrant Cloud.

Cheers!
