### ISSUE TITLE
Incorrect URL Centos

### ISSUE THREAD

**Issue by z3t0** [hashicorp/vagrant#9852]
Centos is using the incorrect url

Current: 
```
https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1804_021.VirtualBox.box
```

Should be:
```
https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1804_02.VirtualBox.box
```

**Comment by chrisroberts** [comment]
Hi there,

This is an issue with the box configuration that was created by the owner in Vagrant Cloud. The box is remotely hosted, thus it is not an issue with Vagrant or Vagrant Cloud. It will need to be fixed by the box owner.

Cheers!
