### ISSUE TITLE
Error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by sridharin2020** [hashicorp/vagrant#9857]
I am unable to download any vagrant box, I have used vagrant on this host machine.
I have a centos6 vagrant box running in a different directory. Now any box i try ti bring it up i am getting this error.

Both virtualbox and vagrant are uptodate.

[root@cent1 ubuntu14]# vboxmanage -v
5.2.12r122591
 

### Vagrant version
Vagrant 2.1.1

### Host operating system
CentOS Linux release 7.3.1611 (Core)

### Guest operating system
ubuntu/trusty64
but i am not able to download any box

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/trusty64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
```

### Debug output
https://gist.github.com/sridharin2020/9fda14233b9300ebbe49440be246969a

### Expected behavior
It should have downloaded the box

### Actual behavior
[root@cent1 ubuntu14]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'ubuntu/trusty64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/ubuntu/trusty64"]
Error: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
[root@cent1 ubuntu14]#

### Steps to reproduce
1. vagrant init ubuntu/trusty64
2. vagrant up

**Comment by sridharin2020** [comment]
If I download the box manually and do a vagrant up, it starts up.
steps performed.

wget https://app.vagrantup.com/ubuntu/boxes/trusty64/versions/20180510.0.5/providers/virtualbox.box
vagrant box add ubuntu/trusty64 virtualbox.box
vagrant up

**Comment by chrisroberts** [comment]
Hi there,

Is your system configured to use a proxy? Do you get the same error using the latest release of Vagrant?

**Comment by sridharin2020** [comment]
Hi,
Yes system is configured to use proxy from environmental variables.
[root@cent1 ~]# echo $http_proxy
http://xxxxx.yyy.com:9090/
[root@cent1 ~]# echo $https_proxy
https://xxxxx.yyy.com:9090/

Yes I am using latest version of Vagrant.
[root@cent1 ~]# vagrant -v
Vagrant 2.1.1

**Comment by chrisroberts** [comment]
Hi there,

You most likely have a custom certificate bundle installed on your system for connecting to the proxy. You can use the `SSL_CERT_FILE` and `CURL_CA_BUNDLE` environment variables to override Vagrant using the vendored versions. Just export those environment variables to the paths on your local system (most likely in the `/etc/ssl` directory, something like `/etc/ssl/certs/ca-certificates.crt`)

Cheers!

**Comment by mvilain** [comment]
I'm having this same problem behind a firewall but on MacOS.  I can use wget just fine. There isn't a custom certificate installed, just the vendor certs. Setting those environment variables didn't solve this problem.

In git, if I specify the proxy in the config file, I get through the proxy server just fine.  Vagrant, however, can't see to deal with proxy.  I used 
"vagrant plugin install vagrant-proxyconf" 
using the https_proxy environment variable and it pulled the ruby gem without a problem.

If I don't specify the https_proxy environment variable and run "vagrant up", it hangs even with the proxyconf plugin.
