### ISSUE TITLE
Permission issue wth private_key file generated during "vagrant up" 

### ISSUE THREAD

**Issue by mohkum** [hashicorp/vagrant#9866]
Hi, 

Setup details are as below. 

vagrant version is --> Vagrant 2.1.1
Virtual Box Version --> Tried with two different versions "VirtualBox-5.2.12-122591-Win" OR "VirtualBox-5.2.10-122406-Win"
Host Operating System Version --> Windows 10 Pro
Guest operating system --> CentOS 7.4

I am running "vagrant up" and then script is throwing error. I am running command as normal user.

********************************************************************
    app1.demo.ca: Vagrant insecure key detected. Vagrant will automatically replace
    app1.demo.ca: this with a newly generated keypair for better security.
    app1.demo.ca:
    app1.demo.ca: Inserting generated public key within guest...
    app1.demo.ca: Removing insecure key from the guest if it's present...
    app1.demo.ca: Key inserted! Disconnecting and reconnecting using new SSH key...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
    app1.demo.ca: Warning: Remote connection disconnect. Retrying...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
********************************************************************

I enabled debug logs and in this i can permission error while reading private_key file

************************************************************************************

DEBUG ssh: == Net-SSH connection debug-level log END ==
 **INFO retryable: Retryable exception raised: #<Errno::EACCES: Permission denied @ rb_sysopen - C:/GitRepo/project-demo/vagrant/.vagrant/machines/app1.demo.ca/virtualbox/private_key>**
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 127.0.0.1
 INFO ssh:   - Port: 2222
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["C:/GitRepo/project-demo/vagrant/.vagrant/machines/app1.demo.ca/virtualbox/private_key"]
DEBUG ssh:   - connect_opts: {:auth_methods=>["none", "hostbased", "publickey"], :config=>false, :forward_agent=>false, :send_env=>false, :keys_only=>true, :verify_host_key=>false, :password=>nil, :port=>2222, :timeout=>15, :user_known_hosts_file=>[], :verbose=>:debug, :encryption=>["aes128-cbc", "3des-cbc", "blowfish-cbc", "cast128-cbc", "aes192-cbc", "aes256-cbc", "rijndael-cbc@lysator.liu.se", "idea-cbc", "arcfour128", "arcfour256", "arcfour", "aes128-ctr", "aes192-ctr", "aes256-ctr", "cast128-ctr", "blowfish-ctr", "3des-ctr", "none"], :logger=>#<Logger:0x00000000071e2f88 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x00000000071e2f10 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00000000071e2ec0 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<StringIO:0x00000000071e2fd8>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00000000071e2e70>>>, :keys=>["C:/GitRepo/project-demo/vagrant/.vagrant/machines/app1.demo.ca/virtualbox/private_key"]}

************************************************************************************

**Comment by briancain** [comment]
Hello @mohkum - can you please provide:

- The permissions on the private key `C:/GitRepo/project-demo/vagrant/.vagrant/machines/app1.demo.ca/virtualbox/private_key` and if the key can be read by the user running Vagrant

Thanks!

**Comment by mohkum** [comment]
Hi @briancain 
I get permission error while opening file in notepad/Notepad++.
I can't even copy private_key to any other folder.
Is their any Vagrant command I need to run to rad the file?

Thanks,
Mohit

**Comment by briancain** [comment]
@mohkum - Can you provide what the permissions are? Running `icacls PATH_TO_PRIVKEY` will give us more information as to why the permissions seem to be wrong. You could also destroy the machine and make sure `C:/GitRepo/project-demo/vagrant/.vagrant/machines/app1.demo.ca` is gone, and then attempt to recreate the guest. Thanks!

**Comment by mohkum** [comment]
Thanks @briancain ... 

After your morning's comment, I went and looked into the file permission and I found no user is listed. Just one cryptic value is listed as owner.
So then I ran "vagrant destroy"  and deleting all folders and ran "vagrant up" again. 
This time when "vagrant up" created brand new private_key file & throwing retry warning; I went to the file and manually added my ID in permission list. 
And it worked.

Just for your reference output of icacls command without adding any permission is

********************************************
C:\Users\mokumar>icacls C:\GitRepo\project-demo\vagrant\.vagrant\machines\app1.demo.ca\virtualbox\private_key
C:\GitRepo\project-demo\vagrant\.vagrant\machines\app1.demo.ca\virtualbox\private_key MOKUMAR\:(F)

Successfully processed 1 files; Failed processing 0 files
********************************************

After adding permission, its

********************************************
C:\Users\mokumar>icacls C:\GitRepo\project-demo\vagrant\.vagrant\machines\app1.demo.ca\virtualbox\private_key
C:\GitRepo\project-demo\vagrant\.vagrant\machines\app1.demo.ca\virtualbox\private_key MOKUMAR\__vmware__:(RX)
                                                                                                        MOKUMAR\:(F)

Successfully processed 1 files; Failed processing 0 files
********************************************

**Comment by briancain** [comment]
Glad it was fixed! I'll go ahead and close this issue. Thanks!
