### ISSUE TITLE
Vagrant can't find the private_key file if the working directory path contains spaces on Windows.

### ISSUE THREAD

**Issue by mak3e** [hashicorp/vagrant#9870]
### Vagrant version
Vagrant 2.1.1

### Host operating system
Windows 7 Enterprise 64-bit 

### Guest operating system
Ubuntu 16.04

### Relevant parts of the Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.define "x", primary: true do |x|
    x.vm.box = "x"
    x.vm.box_url = "<local image>"
    x.vm.provider "virtualbox" do |virtualbox|
      virtualbox.customize ["modifyvm", :id, "--nictype1", "virtio"]
    end
    x.ssh.insert_key = true
  end
end
```
### Relevant parts of the run script (batch-file)
```cmd
set VAGRANT_CWD=C:\Path\With a\Space\
vagrant up
```

### Expected behavior
Vagrant box boots normally using the default insecure vagrant key

### Actual behavior
Vagrant can't find the key and asks for password
```cmd
vagrant@127.0.0.1's password:
bash: a/Space/.vagrant/machines/x/virtualbox/private_key: No such file or directory
```

**Comment by briancain** [comment]
Hi there @mak3e - please provide a [gist](https://gist.github.com/) with the behavior you are seeing. I just tried to reproduce your issue with Vagrant 2.1.1 and 2.1.2 with `cmd.exe` following your instructions and it works as expected.

<img width="413" alt="screen shot 2018-08-02 at 11 27 17 am" src="https://user-images.githubusercontent.com/810277/43603260-476d496c-9647-11e8-805c-a3094965b70c.png">

**Comment by BlueSlug** [comment]
Hi, I'm also experiencing this issue. A gist of what I think is the simplest case can be found here: https://gist.github.com/BlueSlug/9469d152ab7d5c71869b765a65373edf

### Vagrant version
Vagrant 2.1.2

### Host operating system
Windows 10 Pro 64-bit, version 1803 (running in PowerShell)

### Guest operating system
Fedora 28

**Comment by briancain** [comment]
Thanks @BlueSlug - I was able to reproduce it with that command. I've included a fix in this PR https://github.com/hashicorp/vagrant/pull/10389
