### ISSUE TITLE
vagrant docker: docker network create

### ISSUE THREAD

**Issue by StuporHero** [hashicorp/vagrant#9873]
Vagrant 2.1.1
Windows 10
Docker 18.03.1-ce-win65 (17513)

I have a custom Ubuntu 16.04 image that has the ChefDK setup in it to run `kitchen test` on a cookbook. Kitchen is setup to use Docker to execute and test the cookbook. In order for this to work in Vagrant, I need to manually create a docker network and include it my configuration. This works just fine, but for maximum portability of the build configuration, I'd like to be able to create the network as part of the `vagrant up` command. The manual command is simple:

```
Usage:  docker network create [OPTIONS] NETWORK

Create a network

Options:
      --attachable           Enable manual container attachment
      --aux-address map      Auxiliary IPv4 or IPv6 addresses used by Network driver (default map[])
      --config-from string   The network from which copying the configuration
      --config-only          Create a configuration only network
  -d, --driver string        Driver to manage the Network (default "bridge")
      --gateway strings      IPv4 or IPv6 Gateway for the master subnet
      --ingress              Create swarm routing-mesh network
      --internal             Restrict external access to the network
      --ip-range strings     Allocate container ip from a sub-range
      --ipam-driver string   IP Address Management Driver (default "default")
      --ipam-opt map         Set IPAM driver specific options (default map[])
      --ipv6                 Enable IPv6 networking
      --label list           Set metadata on a network
  -o, --opt map              Set driver specific options (default map[])
      --scope string         Control the network's scope
      --subnet strings       Subnet in CIDR format that represents a network segment
```

This should probably get its own subsection in the `config.vm.provider 'docker'` block with the implied addition of the `--network` flag on the `docker run` command. This would also be useful for multi-container setups where multiple containers are created together by Vagrant since the `--link` flag is now deprecated. Thanks for your consideration!

**Comment by StuporHero** [comment]
A couple of additional notes:
- If the network already exists, the `vagrant up` command should not fail.
- There should be some kind of "remove on destroy" option to automatically run `docker network rm <network>` on `vagrant destroy`.

**Comment by briancain** [comment]
I have created a pull request https://github.com/hashicorp/vagrant/pull/10702 which addresses this issue. Thanks!
