### ISSUE TITLE
Dynamically linked version of OpenSSL in AppImage "container" causes `vagrant ssh` to fail.

### ISSUE THREAD

**Issue by espoelstra** [hashicorp/vagrant#9875]
### Vagrant version
Using Vagrant 2.1.1

### Host operating system
Ubuntu 18.04

### Guest operating system
Ubuntu 18.04/16.04/etc

### Vagrantfile
Fails on 16.04, 18.04, pretty much any version because the AppImage SSL doesn't match the host.
```ruby
## -*- mode: ruby -*-
## vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "4096"
   end
end
```

### Debug output
Will paste if requested, issue seems pretty straightforward.

### Expected behavior
I should be able to `vagrant ssh` without any errors when using the AppImage version of Vagrant.

AppImage is a fantastic and portable format, and I would like to use it on Ubuntu/Fedora/everywhere rather than only using it when a native package isn't available. I understand that it increases the size of the AppImage if you pull in libssl and it also means you have to release a new version if there is a security issue identified in an older version of libssl contained in the AppImage, but since they are designed to be self contained runtimes and hopefully your build process has reproducible artifacts, you should be able to bundle a version of OpenSSL and re-release the AppImage with a slightly bumped version if the libssl you include in a version is superceded.

### Actual Behavior
Using AppImage version and `vagrant ssh` results in `OpenSSL version mismatch. Built against 100020ef, you have 1000106f``.

### Steps to reproduce
1. `vagrant init bento/ubuntu-18.04`
2. `vagrant up`
3. `vagrant ssh`

**Comment by espoelstra** [comment]
https://github.com/openssl/openssl/issues/1631#issuecomment-250021959

**Comment by thurt** [comment]
@davidsolorzano20  same here. downgrading vagrant from 2.1.1 to 2.1.0 fixed my error. Any idea why?  links provided above don't describe downgrading vagrant as a solution

**Comment by davidsolorzano20** [comment]
@thurt I checked in 2 operating systems Ubuntu 18.04 and LinuxMint 18.3, I got the same error, I updated the openssl in both and nothing. then I decided to try an earlier version of vagrant.

**Comment by Genovo** [comment]
same error on "bento/ubuntu-16.04", 
```
~$ vagrant ssh n4
OpenSSL version mismatch. Built against 1000207f, you have 1000106f
```
but downgrading to Vagrant 2.1.0 did not fix error
```
~$ vagrant --version
Vagrant 2.1.0
```
Also not related to non-Ubuntu OpenSSL issues,  
```
~$ ldd /usr/bin/openssl
	linux-vdso.so.1 =>  (0x00007ffcdcbdc000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f2baca45000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f2bac601000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2bac237000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2bac033000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2baccae000)
```
Upgraded to latest stable OpenSSL,  got same error
```
~$ openssl version
OpenSSL 1.0.2o  27 Mar 2018
#  It was 1.0.2g
```
Switched from "bento/ubuntu-16.04"  to "ubuntu/xenial64" and back to Vagrant 2.1.1 
Same error
