### ISSUE TITLE
Error: on vagrant up command Error"VBOX_E_FILE_ERROR"

### ISSUE THREAD

**Issue by sahilshehri** [hashicorp/vagrant#9881]
When i issue a command "vagrant up" it gives the error output which is pasted below, related to virtual box. Could anyone guide me what to do ? Error"VBOX_E_FILE_ERROR"
=================================================
C:\Ubuntu
λ vagrant -v
Vagrant 2.1.1
!
C:\Ubuntu
λ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "\\\\?\\C:\\Users\\Windows.DESKTOP-TOVDFFU\\.vagrant.d\\boxes\\ubuntu-VAGRANTSLASH-trusty64\\20180522.0.1\\virtualbox\\box.ovf", "--vsys", "0", "--vmname", "ubuntu-cloudimg-trusty-vagrant-amd64_1527591194410_52134", "--vsys", "0", "--unit", "6", "--disk", "C:\\Users\\Windows.DESKTOP-TOVDFFU\\VirtualBox VMs\\ubuntu-cloudimg-trusty-vagrant-amd64_1527591194410_52134\\box-disk1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting \\?\C:\Users\Windows.DESKTOP-TOVDFFU\.vagrant.d\boxes\ubuntu-VAGRANTSLASH-trusty64\20180522.0.1\virtualbox\box.ovf...
OK.
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage.exe: error: Appliance import failed
VBoxManage.exe: error: Could not create the imported medium 'C:\Users\Windows.DESKTOP-TOVDFFU\VirtualBox VMs\ubuntu-cloudimg-trusty-vagrant-amd64_1527591194410_52134\box-disk1.vmdk'.
VBoxManage.exe: error: VMDK: Compressed image is corrupted '\\?\C:\Users\Windows.DESKTOP-TOVDFFU\.vagrant.d\boxes\ubuntu-VAGRANTSLASH-trusty64\20180522.0.1\virtualbox\box-disk1.vmdk' (VERR_ZIP_CORRUPTED)
VBoxManage.exe: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(struct HandlerArg *)" at line 886 of file VBoxManageAppliance.cpp

**Comment by chrisroberts** [comment]
Hi there,

It appears that the box file you downloaded is corrupted. Please try removing the local box and then running `vagrant up` again. You can remove the box by running: `vagrant box remove ubuntu/trusty64`. Please see if that resolves the problem.

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
