### ISSUE TITLE
Windows 10 - Cannot run 'vagrant up' or 'vagrant reload' (Warning: Remote connection disconnect)

### ISSUE THREAD

**Issue by ghost** [hashicorp/vagrant#9883]
### Vagrant version
2.1.1

### Host operating system
Windows 10

### Guest operating system
Ubuntu_64

### Vagrantfile
(default Homestead file)

```# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'json'
require 'yaml'

VAGRANTFILE_API_VERSION ||= "2"
confDir = $confDir ||= File.expand_path(File.dirname(__FILE__))

homesteadYamlPath = confDir + "/Homestead.yaml"
homesteadJsonPath = confDir + "/Homestead.json"
afterScriptPath = confDir + "/after.sh"
aliasesPath = confDir + "/aliases"

require File.expand_path(File.dirname(__FILE__) + '/scripts/homestead.rb')

Vagrant.require_version '>= 1.9.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if File.exist? aliasesPath then
        config.vm.provision "file", source: aliasesPath, destination: "/tmp/bash_aliases"
        config.vm.provision "shell" do |s|
            s.inline = "awk '{ sub(\"\r$\", \"\"); print }' /tmp/bash_aliases > /home/vagrant/.bash_aliases"
        end
    end

    if File.exist? homesteadYamlPath then
        settings = YAML::load(File.read(homesteadYamlPath))
    elsif File.exist? homesteadJsonPath then
        settings = JSON::parse(File.read(homesteadJsonPath))
    else
        abort "Homestead settings file not found in #{confDir}"
    end

    Homestead.configure(config, settings)

    if File.exist? afterScriptPath then
        config.vm.provision "shell", path: afterScriptPath, privileged: false, keep_color: true
    end

    if Vagrant.has_plugin?('vagrant-hostsupdater')
        config.hostsupdater.aliases = settings['sites'].map { |site| site['map'] }
    elsif Vagrant.has_plugin?('vagrant-hostmanager')
        config.hostmanager.enabled = true
        config.hostmanager.manage_host = true
        config.hostmanager.aliases = settings['sites'].map { |site| site['map'] }
    end
end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
See https://gist.github.com/KerryRitterWaa/642de787653178b08c85cf33822e49b8

### Expected behavior
The virtual machine should launch.

### Actual behavior
`homestead-7: Warning: Remote connection disconnect. Retrying...` replays until vagrant crashes.

### Steps to reproduce
1. Install Virtualbox v5.1.26.
2. Install Vagrant 2.1.1.
3. `git clone https://github.com/laravel/homestead.git C:/homestead/`, `cd C:/homestead`, `git checkout v7.6.1`
4. `./init.bat`
5. `vagrant up`

**Comment by squalltua** [comment]
Same problem. but it happening after upgrade 2.0 to 2.1.1
before upgrading vagrant still working than upgraded to 2.1.1 broken!!
all of projects cannot run 'vagrant up'
"Warning: Remote connection disconnect. Retrying...".
And try to direct login with vagrant/vagrant (username/password) can't work

Next step i will try downgrade to 2.0.1 version. I hope will work but not work 👎 .
same problem like 2.1.1 version

And try upgrade and downgrade VirtualBox 5.1.38, 5.2.0, 5.2.12

**Vagrant version**
2.0.1, 2.1.1

**Host operating system**
Windows 10 Home

**Guest operating system**
ubuntu/xenial64

**VisualBox verison**
5.1.38, 5.2.0, 5.2.12

**Comment by chrisroberts** [comment]
Hi there,

Are you still experiencing this issue with the latest larvel release (6.1.0)? Also, can you log into the guest via the vbox UI?

**Comment by squalltua** [comment]
@chrisroberts 
I cannot log into the guest via Vbox UI with (username/password) vagrant/vagrant or ubuntu/vagrant 

Sorry. What is the "larvel"?

**Comment by KerryRitterWaa** [comment]
I am experiencing this on the last two Laravel releases, 5.6 and 5.5.

The box is able to launch and display the login screen in the preview, but the console output is `homestead-7: Warning: Remote connection disconnect. Retrying...` over and over. In this scenario, I am able to launch the vbox and manually log-in, but the vagrant process is never able to pick up.

**Comment by viral-vector** [comment]
I am experiencing this as well. Tried various combinations of Vagrant/VBox with no luck. Even after a clean install (homestead as well + removing dot folders), no luck. This issue began after I upgraded.

**Comment by chrisroberts** [comment]
Vagrant 2.1.2 release included updates on private key permission handling that resolved this issue. Cheers!
