### ISSUE TITLE
Can't update box after specifying version

### ISSUE THREAD

**Issue by l0b0** [hashicorp/vagrant#9884]
`vagrant up --no-provision` was nagging me:

```
==> default: A newer version of the box 'ubuntu/bionic64' for provider 'virtualbox' is
==> default: available! You currently have version '20180517.0.0'. The latest is version
==> default: '20180529.0.0'. Run `vagrant box update` to update.
```

To avoid this error and ensure that all users have the same Vagrant box, I tried setting it in the Vagrantfile, after which `vagrant box update` failed unexpectedly and `vagrant up --no-provision` silently ignores the outdated version.

### Vagrant version

2.1.1

### Host operating system

Arch Linux (up to date as of today, 2018-05-30).

### Guest operating system

ubuntu/bionic64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20180529.0.0"
  config.vm.provision "shell", inline: "sudo /vagrant/provisioning/vagrant/provision.sh"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provisioning/ansible/setup-development-vm.yml"
  end
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
```

### Expected behavior

1. `vagrant box update` should update the box.
1. `vagrant up --no-provision && vagrant provision` should **either** advise the user to update the box **or** update the box automatically before provisioning.

### Actual behavior

```
$ vagrant box update
==> default: Box 'ubuntu/bionic64' not installed, can't check for updates.
```

`vagrant up --no-provision && vagrant provision` prints no warning and does not update the box.

### Steps to reproduce
1. Spin up a "ubuntu/bionic64" box with no version specified
1. Specify a box version as above
1. Either
   1. run `vagrant box update` or
   1. run `vagrant up --no-provision && vagrant provision`

**Comment by briancain** [comment]
Hi @l0b0 - did you download the box before running `vagrant box update`? Vagrant won't downgrade a box to an older version once the machine is running. If you want it using an older version of the box, you need to destroy the guest and bring it back up with the version constraint in your Vagrantfile.

**Comment by l0b0** [comment]
@briancain No, I didn't download it. ubuntu/bionic64 seems to be updated every day, and I want to make sure users are on the same version. The rest of the comment I don't understand - I'm not trying to downgrade, but instead to *upgrade* to a specific version and keep the box at that version. The problem is that as soon as I specify a version, *without updating* Vagrant seems to stop worrying about which version I'm running.

**Comment by briancain** [comment]
@l0b0 - I think I understand what you're running into now...

Basically you're saying you have a Vagrantfile with a `box_version` that doesn't exist locally but is a newer than what you currently have installed. Running `vagrant box update` fails because it claims the box is not installed (which is technically true, because you don't have that specific box version locally). Right?

**Comment by l0b0** [comment]
That is correct.

**Comment by kikitux** [comment]
If there is no project run, the command that need to be run is
```
vagrant box add ubuntu/bionic64
```

If there is a project run, ie after `vagrant up` then the command to update the box being used is `vagrant box update`

alvaro.
