### ISSUE TITLE
ed25519 keys are not supported and keeps Vagrant hanging without informing the user

### ISSUE THREAD

**Issue by Porkepix** [hashicorp/vagrant#9886]
### Vagrant version
Vagrant 2.1.1

### Host operating system
Archlinux

### Guest operating system
Debian Stretch 9.4

### Vagrantfile
```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  # ssh settings
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_ed25519", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "~/.ssh/id_ed25519.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "shell", inline: <<-EOC
    sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
    sudo service ssh restart
  EOC
end

```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
No need for a Gist as the part under is the only useful one here in the debug:

```
DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not up: #<Vagrant::Errors::SSHKeyTypeNotSupported: The private key you're attempting to use with this Vagrant box uses an unsupported encryption type. The SSH library Vagrant uses does not support this key type. Please use `ssh-rsa` or `ssh-dss` instead. Note that sometimes keys in your ssh-agent can interfere with this as well, so verify the keys are valid there in addition to standard file paths.>
```

### Expected behavior
It shouldn't be an issue to use ed25519 SSH keys. At the very least it should inform user even without the debug mode as here there's nothing informing the user something wrong is going on.
But a support for what is as of now the best SSH keys we have would be nice.

### Actual behavior
What actually happened?
It gets stuck on the `==> default: Waiting for SSH to become available...` step.

### Steps to reproduce
1. Just Vagrant up the Vagrantfile with a ed25519 key in your home.

### References
https://github.com/hashicorp/vagrant/issues/4367

**Comment by dansimau** [comment]
(Previous issue on this is #4367.)

To hack ed25519 support into Vagrant since 2.2.x, you can do:

```
sudo /opt/vagrant/embedded/bin/gem install ed25519 -v '>= 1.2, < 2.0' -i /opt/vagrant/embedded/gems/$(vagrant --version |cut -f2 -d' ')
sudo /opt/vagrant/embedded/bin/gem install bcrypt_pbkdf -v '>= 1.0, < 2.0' -i /opt/vagrant/embedded/gems/$(vagrant --version |cut -f2 -d' ')
```

Would be great to fix this permanently though; it's a headache for Vagrant to break one day to the next in our environment.
