### ISSUE TITLE
Have a way for the user to set the provider without environment variable

### ISSUE THREAD

**Issue by Porkepix** [hashicorp/vagrant#9887]
### Vagrant version
Vagrant 2.1.1

### Actual behavior
Currently the only way I found to set the provider to use is environment variable or set the variable from within the Vagrantfile with `ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'`.

### Expected behavior
Have a way to simply set a standard variable inside the Vagrantfile would probaly be nicer.

**Comment by chrisroberts** [comment]
This can be done within the Vagrantfile by simply stating the provider without a block. For example:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "a-box"
  config.vm.provider :libvirt
end
```

Cheers!

**Comment by Porkepix** [comment]
@chrisroberts This is failing here.
Before filing this issue I tried this but with a slightly different syntax: `config.vm.provider :libvirt`. Just tried yours, result is the same, Vagrant is trying to use VirtualBox anyway:

```
VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
```
