### ISSUE TITLE
Become a better macOS Citizen

### ISSUE THREAD

**Issue by ideologysec** [hashicorp/vagrant#9891]
### Vagrant version
```
vagrant -v
Vagrant 2.1.1
```

### Host operating system
```
user@localhost$ uname -a
Darwin localhost.tld 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro13,3 Darwin
```
(High Sierra 10.13.4)

### Expected behavior
Non-Apple binaries should install to /usr/local, not /opt
1) it's already in $PATH
2) it would follow pretty much every other CLI app convention, **_and the UNIX standard_**:
http://hivelogic.com/articles/using_usr_local/
3) I wouldn't have an /opt folder cluttering up my hard drive for one single application 👎

### Actual behavior
vagrant installs to /opt 😡

### Steps to reproduce
1. Install Vagrant with HashiCorp pkg or via Homebrew
2.  
```
user@localhost$ brew cask install vagrant
user@localhost$ greadlink -f /usr/local/bin/vagrant
/opt/vagrant/bin/vagrant
```
3. or browse to / and see the new /opt directory if installed via package
4. 😰

### References (tangential, but related to being a good macOS citizen)
Codesigning ruby: https://github.com/hashicorp/vagrant/issues/9849
Codesigning Vagrant at all: https://github.com/hashicorp/vagrant/issues/8278

## FINAL THOUGHTS:
Please please please please please, even if you don't codesign the binaries (and you really should, for all of the reasons outlined by the linked issues, namely for process monitoring + control, binary health certification, Apple moving in that direction, etc), 

move all of the vagrant binaries + drivers to /usr/local (./opt and ./bin)

Thank you.

**Comment by chrisroberts** [comment]
Hi there,

@wheelerlaw is correct as illustrated in his link to http://www.pathname.com/fhs/pub/fhs-2.3.html#OPTADDONAPPLICATIONSOFTWAREPACKAGES. As such, the installation location will remain within `/opt` for POSIX-like systems.

Cheers!

**Comment by ideologysec** [comment]
Somehow, I'm less than cheerful.

Setting aside the standard (which I'm happy to be wrong about, thanks for the links - I don't work with BSD or Linux much these days), I'd love to have the concern about the fact that no other macOS software packages install themselves to opt, and that cluttering the root filesystem is a disrespectful decision, addressed (by which I mean hearing a rationale, other than being told to go pound sand because the FHS standard allows for it).

**Comment by envygeeks** [comment]
As a long time systems person, I prefer it in /opt because it makes my life easier if I decide to trash it.  If you use `/usr/local` I have to search out garbage (this is what annoys me about brew, and why we force people to install brew in `/opt` or in `~/.brew` rather than in `/usr/local`.

**Comment by ideologysec** [comment]
And as a user, vagrant is literally the *only* piece of software I have installed into /opt on my crufty dev machine. I'm intensely aggravated by the lack of even a consideration for an *option* to install somewhere else; I'm happy to have dropped it for Ansible which installs into whatever dir or Docker vm I tell it to.
