### ISSUE TITLE
Specific version of Elasticsearch to install

### ISSUE THREAD

**Issue by joshuaboltz** [hashicorp/vagrant#9894]
### Issue Type
 - Feature Idea

### Your Environment
- Drupal VM

### Your OS
 - **macOS** (10.13.4)

### Summary
- During a vagrant provision process, it would be nice to specific the version of Elasticsearch to install, similar to how a specific version of Solr can be configured in the config.yml
- This is important since Drupal Search API doesn't always support the latest versions right away, and maybe other complexities in the way of using the latest version

Since I'm not sure where this issue actually fits, cross-linking to https://github.com/geerlingguy/drupal-vm/issues/1784

**Comment by briancain** [comment]
Hi @joshuaboltz - thanks for opening an issue, however this is out of scope for what Vagrant can do for you. You will likely get more traction for this on the other project you cross linked to. Thanks!
