### ISSUE TITLE
public network not working

### ISSUE THREAD

**Issue by dpxcc** [hashicorp/vagrant#9895]
### Vagrant version
2.0.3

### Host operating system
OS X 10.13.4

### Guest operating system
Ubuntu Server 14.04

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network"
  config.vm.synced_folder "./share", "/home/vagrant/share"
end
```

### Debug output
==> default: Configuring and enabling network interfaces...

### Expected behavior
Vagrant successfully configures and enables public network interface.

### Actual behavior
Vagrant hangs while trying to configure and enable the public network interface.

### Steps to reproduce
1. vagrant up

### References
Are there any other GitHub issues (open or closed) that should be linked here?

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
