### ISSUE TITLE
error with vagrant package --vagrantfile

### ISSUE THREAD

**Issue by dceldran** [hashicorp/vagrant#9899]
Hello all,

I'm having a problem when i am creating my custom package with include vagrantfile.

If i create a new package without the --vagrantfile option, all works fine, but if i use the --vagrantfile, i get this error into the "adding additional vagrantfile" step:

 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000004dc8a58>
C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/win32-file-security-1.0.10/lib/win32/file/security.rb:681:in `chown': undefined method `wincode' for 0:Integer (NoMethodError)

I execute all the process in debug mode:

https://pastebin.com/cGrUBiwE

thanks!

**Comment by barumpus** [comment]
Same problem. I am running VirtualBox 5.1.18 on a WIndows 7 (64bit) host machine, trying to package a Windows 10 Pro VM just created from an iso built from microsoft's "media creation tool" ISO creator. Vagrant version 2.1.1.

NOTE: same core error messsage as @briancain above:
`C:/HashiCorp/Vagrant/embedded/gems/2.1.1/gems/win32-file-security-1.0.10/lib/win32/file/security.rb:681:in `chown': undefined method `wincode' for 0:Integer (NoMethodError)`

The output (without using --debug) is at https://pastebin.com/c7G0fvPC.
I can re-run with --debug if that would be helpful.

Regardless of error, thanks and good karma to all the smart Vagrant coders. :)

**Comment by talweksler** [comment]
Same here, also with --include

**Comment by tamjap** [comment]
Thanks for the work-around, Northcraft.  I've been stuck on it for a bit.  This isn't an urgent project for us, so I may take a couple of days to try the vagrant file with various settings commented out to see if I can narrow down what exactly is causing the problem, or if it's just the inclusion of the vagrantfile in general.

**Comment by tamjap** [comment]
OK - just as a follow up to this, I tried with a vagrantfile that had everything commented out and still got the error.  It appears that this is an error with the inclusion of the file, not with a specific setting within the file.

**Comment by dwmuller** [comment]
I'm also getting this error, running on Windows 7, trying to package a Win10 VirtualBox VM, using Vagrant 2.1.1.

**Comment by JRoppert** [comment]
Same here. Working on Windows 10 and packaging an Ubuntu Server 18.04.
Vagrant 2.1.1 and VirtualBox 5.2.12 r122591

**Comment by PierreR** [comment]
Same here Vagrant 2.1.1 and VirtualBox 5.2.8 (using the --vagrantfile option)
Was working before. The only change is that the box has been generated with the latest packer 1.2.4 instead of packer 1.2.3 but the update of the os (windows 10) is more likely to be what trigger the issue for me.

**Comment by chrisroberts** [comment]
Hi there,

PR #9923 is included in the 2.1.2 release and should resolve this issue. There were issues encountered in various Windows environments where the win32 additions were not working correctly. The file modifications were replaced with powershell commands and should resolve the problems.

I'm going to close this up but if you still are having issues, we can either reopen this issue or a new one can be opened.

Cheers!
