### ISSUE TITLE
Permissions for private_key windows host

### ISSUE THREAD

**Issue by regniws** [hashicorp/vagrant#9900]
### Vagrant version
2.1.1

### Host operating system
Windows 10

### Guest operating system
ubuntu 14.04

### Expected behavior
private_key creates with valid access permissions

### Actual behavior
private_key is not accessible for vagrant proccess due to insufficient access right 

### References
Commit f0e232d gives permissions for private key file, but Etc.getlogin returns short user name instaed name with domain, so if I 'vagrant up' for the first time created private key had wrong permissions and vagrant proccess can't access it, therefore can't connect to just created VM. 

```
            begin
              priv_path = @machine.data_dir.join("private_key").to_s
              File.set_permissions(priv_path, Etc.getlogin => File::FULL)
            rescue => e
              @logger.warn("Error encountered during private key permissions set - " \
                "#{e.class}: #{e.message}")
            end
```

**Comment by jrampon** [comment]
I'm seeing the same issue. The private key is created with permissions for locale user `machine\username` instead of `domain\username`. As soon as I change the permission to the correct user, the Vagrant process continues as expected. I'm also using Vagrant 2.1.1 on Windows 10.
