### ISSUE TITLE
bento/ubuntu-16.04 v201805.15.0 not found for Virtualbox

### ISSUE THREAD

**Issue by gesinn-it** [hashicorp/vagrant#9903]
### Vagrant version
2.1.1

### Host operating system
Windows 7 Pro

### Guest operating system
bento/ubuntu-16.04

### Vagrantfile
```ruby
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_version = "201805.15.0"
```

### Expected behavior
base box for VirtualBox loaded (https://app.vagrantup.com/bento/boxes/ubuntu-16.04/versions/201805.15.0)

### Actual behavior
```
Box: bento/ubuntu-16.04
Address: https://vagrantcloud.com/bento/ubuntu-16.04
Constraints: 201805.15.0
Available versions: 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.4, 2.3.5, 2.3.7, 2.3.8, 201708.22.0, 201710.25.0, 201801.02.0, 201802.02.0, 201803.24.0
```

**Comment by briancain** [comment]
Hello! Thanks for opening an issue. When opening a new issue on the Vagrant project, we ask that everyone provide a [gist](https://gist.github.com/) containing the behavior you're seeing with the `--debug` flag included. This helps us figure out what's actually going on. Thanks!

**Comment by briancain** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks!
