### ISSUE TITLE
Problem with downloading boxes from vagrantcloud from EU.

### ISSUE THREAD

**Issue by drummerdox** [hashicorp/vagrant#9907]
Can`t download vagrant box hosted from vagrantcloud, due download speed drop to 0 during the time.
Try to download from direct link using chrome, wget, curl. 

http://www.speedtest.net/result/7373432078

### Vagrant version

Vagrant 2.1.1

### Host operating system
linux ubuntu 16 lts

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }
end
```

### Debug output

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'scotch/box' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'scotch/box'
    default: URL: https://vagrantcloud.com/scotch/box
==> default: Adding box 'scotch/box' (v3.5) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/scotch/boxes/box/versions/3.5/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```
### Expected behavior

Downloaded vagrant box

### Actual behavior

Download crashes due low download speed.

### Steps to reproduce

1. Just try to download box from https://vagrantcloud.com/scotch/boxes/box/versions/3.5/providers/virtualbox.box or vagrant up

**Comment by rgevaert** [comment]
I experienced similar issues in Ethiopia (I was teaching a class about Vagrant). (Maybe there is some ratelimiting going on because all the computers were behind NAT)
