### ISSUE TITLE
CURL_OPENSSL_4 not found (required by /usr/lib/virtualbox/VBoxRT.so)

### ISSUE THREAD

**Issue by c00per912** [hashicorp/vagrant#9908]
Hello Community.

I can't start my VM using command `vagrant up`. It ends with error:

> There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["--version"]
> 
> Stderr: /usr/lib/virtualbox/VBoxManage: /tmp/.mount_vagranB1uPe7/usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by /usr/lib/virtualbox/VBoxRT.so)

### Vagrant version
Vagrant 2.1.1

### Packer version
Packer 1.2.4

### Virtualbox version
Virtualbox 5.2.12-122591-Ubuntu-bionic amd64

### Host operating system
Ubuntu 18.04 LTS
Linux 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Guest operating system
Metasploitable3 Windows Server 2008 R2

### Vagrantfile
https://gist.github.com/c00per912/fc4efac7fa077f1ff4a6d33333e9a39f

### Debug output
https://gist.github.com/c00per912/ca63e8920bd03b83f75489e088606708

### Expected behavior
I would start metasploitable3 with command `vagrant up`.

### Actual behavior
When I type command `vagrant up` it stop with the error CURL_OPENSSL_4 not found.
I cant't analyse the file /tmp/.mount_vagranEZpqOO/usr/lib/x86_64-linux-gnu/libcurl.so.4 because the directory /tmp/.mount_vagranEZpqOO is only for 1 second visible. After the error is shown this directory is removed by vagrant. The command `vagrant up --no-destroy-on-error` is the same and the directory is removed too after 1 second.
When I analyse the file /usr/lib/x86_64-linux-gnu/libcurl.so.4.5.0 with command `readelf -v libcurl.so.4.5.0`, I get this output:

https://gist.github.com/c00per912/e6b2eb172f239c3ef4577230e96998b0

I think everything looks fine. But I don't know if vagrant uses this version of libcurl.
After installing libcurl4-openssl-dev I get the same error.

### Steps to reproduce
I walked through this tutorial to install metasploitable3 https://github.com/rapid7/metasploitable3
and tried the automatic and the manual installation, but it's all the same.

I spend hours to find a solution for this error but can't find anyone with the same problem. There are many threads with curl problems but nobody with libcurl.so.4 without CURL_OPENSSL_4.
The most solutions with curl problems is to install libcurl4-openssl-dev or vagrant-libvirt. But both bring no solution for me.

Can anyone help me please?

Best regards
c00per912

**Comment by briancain** [comment]
Hi there @c00per912 - it looks like you are running into a related issue https://github.com/hashicorp/vagrant/issues/9875 . I recommend removing your current installation of Vagrant and instead try installing Vagrant from the `.deb` package. Let me know if that fixes your issue...thank you!

**Comment by c00per912** [comment]
Hi braincain. Thank you for helping me. I've removed 

/usr/local/bin/packer, 
/usr/local/bin/vagrant, 
~/.gem and 
~/.vagrant.d 

manually. 

After it I remove virtualbox-5.2 via apt and removed `deb https://download.virtualbox.org/virtualbox/debian bionic contrib` from source.list. Then I try first to install virtualbox via apt. The installation stops at 77% and broke the virtualbox installation. sudo dpkg --configure -a didn't work for me to repair the broken install. I wasn't able to install it nor to remove it completely. But sudo `dpkg --purge virtualbox virtualbox-qt` and `sudo apt clean` and `sudo apt autoclean` did the trick for me. I installed virtualbox-5.2 again via apt from source `deb https://download.virtualbox.org/virtualbox/debian bionic contrib`. After it I installed packer and vagrant via apt.

**Vagrant version**
Vagrant 2.0.2

**Packer version**
Packer 1.0.4

When I now run through the tutorial above, I get another error:

```
$ vagrant up
Traceback (most recent call last):
	25: from /usr/bin/vagrant:23:in `<main>'
	24: from /usr/bin/vagrant:23:in `load'
	23: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/bin/vagrant:146:in `<top (required)>'
	22: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:269:in `cli'
	21: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/cli.rb:46:in `execute'
	20: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/commands/up/command.rb:87:in `execute'
	19: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
	18: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:186:in `each'
	17: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
	16: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
	15: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/environment.rb:694:in `machine'
	14: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:79:in `machine'
	13: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/vagrantfile.rb:79:in `new'
	12: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:140:in `initialize'
	11: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/machine.rb:248:in `communicate'
	10: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/registry.rb:27:in `get'
	 9: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
	 8: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 7: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
	 5: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
	 4: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/shell.rb:8:in `<top (required)>'
	 3: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/lib/vagrant/util/silence_warnings.rb:8:in `silence!'
	 2: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/communicators/winrm/shell.rb:9:in `block in <top (required)>'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- winrm (LoadError)
```
When I fix this I can tell you if it work.

Best regards
c00per912

**Comment by c00per912** [comment]
Hi chrisroberts. Now it works fine.
First I thought the .deb package from ubuntu is needed.
https://packages.ubuntu.com/bionic/vagrant
I make it simple and install it via apt. But there where many dependencies problems between vagrant and ruby gems. To install the vagrant-reload plugin I must uninstall vagrant-libvirt but this is need by some ruby gems.
With the latest vagrant .deb package from https://releases.hashicorp.com/vagrant/2.1.1/ it works fine. I think braincain meant this too.

Many many thanks @braincain&chrisroberts!!! 

Best regards
c00per912
