### ISSUE TITLE
Automating authorized_keys in vagrantfile.

### ISSUE THREAD

**Issue by krashidov** [hashicorp/vagrant#992]
I'm trying to make our dev onboarding process as seamless as possible.

Part of the functionality we want in the VM is to have our code pulled in from github onto the VM.

In my Vagrantfile I added the private_key and forward_agent options like so:

<code>config.ssh.private_key_path = "~/.ssh/id_rsa"</code>
<code>config.ssh.forward_agent = true</code>

However, when I do a <code>vagrant up</code>

I get this:

SSH authentication failed! This is typically caused by the public/private
keypair for the SSH user not being properly set on the guest VM. Please
verify that the guest VM is setup with the proper public key, and that
the private key path for Vagrant is setup properly as well.

To fix this, I SSH (with vagrant as the password), and I append my public key to ~/.ssh/authorized_keys

I'm also using the puppet provisioner. 

I've found a hacky workaround using sed, but is there a way for vagrant to automatically add my public key to the authorized keys?

**Comment by hackeron** [comment]
Is there still no easy way to add a public key??

**Comment by yeago** [comment]
eh whatever I found it easier to just use ssh forwarding or whatever.

**Comment by dwickern** [comment]
Building on the example from @alex-moreno, this provisioning script will replace the default insecure key with your custom ssh key. Vagrant is configured to use both keys, so it will use the insecure key to provision the first time, then use your private key going forward.

```
private_key_path = File.join(Dir.home, ".ssh", "id_rsa")
public_key_path = File.join(Dir.home, ".ssh", "id_rsa.pub")
insecure_key_path = File.join(Dir.home, ".vagrant.d", "insecure_private_key")

private_key = IO.read(private_key_path)
public_key = IO.read(public_key_path)

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.ssh.insert_key = false
  config.ssh.private_key_path = [
    private_key_path,
    insecure_key_path # to provision the first time
  ]

  config.vm.provision :shell, :inline => <<-SCRIPT
    set -e
    
    echo '#{private_key}' > /home/vagrant/.ssh/id_rsa
    chmod 600 /home/vagrant/.ssh/id_rsa

    echo '#{public_key}' > /home/vagrant/.ssh/authorized_keys
    chmod 600 /home/vagrant/.ssh/authorized_keys
  SCRIPT
end
```

**Comment by CalebEverett** [comment]
That script didn't work for me. I've been trying to parse through the code to figure out how the keys and password get set up and it would be nice if there were a more straightforward way to set up the authentication with a specified set of keys.

The entire .ssh directory gets overwritten when the public key is inserted, overwriting any provisioned keys if the insecure_key is included in the private_key path and there's no password.

https://github.com/mitchellh/vagrant/blob/1f88a9737369eda3dede0d3aeb30928adf82a9f7/plugins/communicators/ssh/communicator.rb#L149

https://github.com/mitchellh/vagrant/blob/1f88a9737369eda3dede0d3aeb30928adf82a9f7/plugins/guests/linux/cap/insert_public_key.rb#L12

If you set a password, then keys aren't used at all.

If you don't set a password, then the default of 'vagrant' remains, which defeats the intent of only being able to get in with a specified key pair, but it does prevent the insertion of a newly generated set of keys (and overwriting of the guest .ssh directory).

I tried this
```
  config.vm.provision "file", source: "~/.vagrant.d/vagrant_private_key.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.private_key_path = ["~/.vagrant.d/vagrant_private_key", "~/.vagrant.d/insecure_private_key"]
  config.ssh.password = nil
  config.ssh.insert_key = false
```
 and then do a vagrant ssh and the password prompt comes up, for which "vagrant" works and the .ssh directory has been overwritten with authorized_keys.

Do you pretty much have to get into the box after it's running to make it secure?

**Comment by sr105** [comment]
I wanted to allow either the vagrant created key or the user's key. Thanks to the examples above, I was able to use this.

```ruby
  # SSH Key Access
  public_key_path = File.join(Dir.home, ".ssh", "id_rsa.pub")
  if File.exist?(public_key_path)
    public_key = IO.read(public_key_path)
  end
  config.ssh.forward_agent = true
  config.ssh.keys_only = false

  # Disables the vagrant generated key.
  # Uncomment if you only want access via user's key.
  #config.ssh.insert_key = false


  config.vm.provision :shell, :inline => <<-SCRIPT
    set -e

    # Add host user's ssh public key to authorized_hosts
    homedir=$(getent passwd "$SUDO_USER" | cut -d: -f6)
    echo '#{public_key}' >> $homedir/.ssh/authorized_keys
    chmod 600 $homedir/.ssh/authorized_keys
  SCRIPT
```

**Comment by inetbiz** [comment]
@sr105 what would I do if I"m on a Win10 host? My keys are on an SD Chip.

**Comment by sr105** [comment]
Can't you change the `public_key_path` to pint to your public key file?

**Comment by inetbiz** [comment]
@sr105 It think I would use `/d/ssh` to represent drive d:. I'll test that.

**Comment by westonplatter** [comment]
In case you've come to find out how to do this, 

Mac & Vagrant

```

Vagrant.configure('2') do |config|
  config.vm.box      = 'ubuntu/xenial64' # 17.10
  config.vm.hostname = 'mybox'

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.forward_agent = true
  config.ssh.keys_only = false

  # Disables the vagrant generated key.
  # Uncomment if you only want access via user's key.
  config.ssh.insert_key = false
end
```

**Comment by rodolfovillaruz** [comment]
@CalebEverett I added this configuration and it worked. Thank you!

```
Vagrant.configure("2") do |config|
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]
  config.ssh.insert_key = false
end
```

**Comment by nurettin** [comment]
Since `/vagrant` is already mounted as Vagrantfile's folder, copy public keys to that folder, add 

    config.vm.provision "shell", inline: "cat /vagrant/*.pub >> /home/vagrant/.ssh/authorized_keys"

run `vagrant provision` to copy all keys in the folder to vm.

**Comment by ngstigator** [comment]
Another way is to append a specific set of public keys into the guest `authorized_keys`.
```
  # Copy local public key(s) to guest
  config.vm.provision "file", source: "./import_keys.pub", destination: "/home/vagrant/.ssh/import_keys.pub"

  # append import key(s) to authorized_keys and remove duplicates
  $script = <<-SCRIPT
  cd /home/vagrant/.ssh
  cat import_keys.pub >> authorized_keys
  sort authorized_keys | uniq > public_keys.pub
  mv public_keys.pub authorized_keys
  rm *.pub
  SCRIPT

  config.vm.provision "shell" do |sh|
    sh.inline = $script
    sh.privileged = false
  end
```

Note that duplicates are removed for faux idempotence on repeated provisions.
