### ISSUE TITLE
Weird error when import vmcx VM in hyperv after removing an switch

### ISSUE THREAD

**Issue by bbrala** [hashicorp/vagrant#9922]
This is a little weird. Things were all fine, but after removing an external switch i get an error when trying to import a VM. I'll see if i can find some reason for this...

Master branch
Windows 1804
Hyper-V

See this gist https://gist.github.com/bbrala/dffe78b267f7d4ac5baffbf05456d278

When testing changes for #9872

**Comment by bbrala** [comment]
The switch name is the original switch name which was used to create the basebox with packer. But this shouldn't really leak...

**Comment by chrisroberts** [comment]
@bbrala Thanks for reporting this. I believe that #9929 will fix this.

**Comment by bbrala** [comment]
No problem, i think that should do yeah. I'll try and check out if the branch fixes this tonight.

**Comment by bbrala** [comment]
See #9929 for comment, it seems to fix this problem.

**Comment by chrisroberts** [comment]
@bbrala Awesome, thanks for the confirmation!
