### ISSUE TITLE
bento/ubuntu-18.04 does not have ifupdown installed by default

### ISSUE THREAD

**Issue by HowellBP** [hashicorp/vagrant#9924]
### Vagrant version
2.0.0

### Host operating system
macOS 10.12.6 Sierra

### Guest operating system
Ubuntu 18.04 Bionic

### Debug output
https://gist.github.com/HowellBP/ed781d188d7fc54353a6a5abaffa0ed1

### Expected behavior
Vagrant provisioned the box

### Actual behavior
Vagrant failed attempting ifup/ifdown because the packages aren't installed

### Steps to reproduce
1. configure vagrant with bento/ubuntu-18.04 version 201806.08.0
2. vagrant up
3. vagrant will fail attempting ifup/ifdown due to missing binaries

### Workaround
The guest machine will still be built and can still be accessed using `vagrant ssh hostname`. You can then `sudo apt-get install ifupdown` and log out, `vagrant halt`, and `vagrant up` again, and it will succeed. If you delete the guest(s) using `vagrant destroy` then you'll have to re-install `ifupdown`.

Whatever handles the network operations during provisioning should be updated to either use `ifconfig up` or the package `ifupdown` should be installed prior to attempting network actions.

**Comment by briancain** [comment]
Hi @HowellBP - The latest ubuntu versions now use [netplan](https://netplan.io/) to configure networking. If you upgrade to the latest Vagrant (2.1.1), you will be able to properly configure a ubuntu 18.04 box with netplan. Thanks!
