### ISSUE TITLE
Vagrant up does not detect existing Hyper-V virtual switches

### ISSUE THREAD

**Issue by alex94cp** [hashicorp/vagrant#9939]
### Vagrant version
Vagrant 2.1.1

### Host operating system
Windows 10 x64 (build 1803)

### Debug output

```vagrant up --provider hyperv``` fails with [this output](https://gist.github.com/alex94cp/38ffd8124ce9fd5f35a1df8a5bcdf023) (basically, NoSwitches error), even though a virtual switch already exists ([this](https://gist.github.com/alex94cp/7295f38fdfd8789d5a7c70951e555e46) is the output from the get_switches.ps1 script

### Expected behavior
```vagrant up``` should have detected the existing virtual switch.

### Steps to reproduce
1. vagrant up --provider hyperv

**Comment by chrisroberts** [comment]
Hi there,

The latest Vagrant release includes a large number of updates to the Hyper-V provider. Would you please verify if you are still experiencing this behavior with the latest Vagrant release (2.1.2). 

Thanks!

**Comment by alex94cp** [comment]
It's working perfectly now (though there seems to be an encoding issue when the computer name includes non-ascii characters, maybe related to #9679). Anyway, thanks a lot!

**Comment by chrisroberts** [comment]
@alex94cp Great, thanks for letting me know it's resolved. Yeah, there are still some encoding issues to be resolved which is likely what you are seeing.

Cheers!
