### ISSUE TITLE
Provider detection for new machine fails due to outdate powershell while cygwin available

### ISSUE THREAD

**Issue by bootleq** [hashicorp/vagrant#9941]
### Vagrant version
Vagrant 2.1.1

### Host operating system
Windows 7 SP1

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
end
```
### Debug output
Result of `VAGRANT_LOG=debug VAGRANT_POWERSHELL_VERSION_DETECTION_TIMEOUT=2 vagrant status`:
https://gist.github.com/bootleq/145ca1181e42331b804832585c510599

### Expected behavior
Since I run cygwin, I expect vagrant won't be stopped by checking PowerShell.
If prepend `VAGRANT_DEFAULT_PROVIDER=virtualbox` to original command, it works as expected.

### Actual behavior
Got error message
```
INFO interface: error: The version of powershell currently installed on this host is less than
the required minimum version. Please upgrade the installed version of
powershell to the minimum required version and run the command again.
```

### Steps to reproduce
1. With new Vagrantfile as above, and virtualbox machine didn't created yet.
2. Issue command `vagrant status`.

**Comment by briancain** [comment]
Hi @bootleq - what version of powershell do you currently have installed?

**Comment by bootleq** [comment]
Sorry I should mention that PowerShell **2** (invalid version) was installed.
After some trail, I found we can up a new machine without PowerShell, if skip default_provider and `windows_hyperv_enabled?` detection, or do detect but not fail immediately.

**Comment by briancain** [comment]
Hi! If you had Powershell 2 installed then that error is expected. I'm going to go ahead and close this issue, thanks! If you think you have any other bugs feel free to open a new one or comment on this one with your problem.
