### ISSUE TITLE
SMB shares not mounting if Vagrant installed in a path with spaces

### ISSUE THREAD

**Issue by Jckf** [hashicorp/vagrant#9942]
Vagrant 2.1.1 under Windows 10 with an Ubuntu guest.

To reproduce this all you have to do is install Vagrant in a path with spaces, and configure your VM to use SMB shares for synced folders.

Relevant debug output: https://pastebin.com/9dQqQHL3

The problem lies with the `powerup_command` method in `powershell.rb`: https://github.com/hashicorp/vagrant/blob/master/lib/vagrant/util/powershell.rb#L202 as it does not properly escape the `path` argument. Sadly I don't know enough about Ruby to create a fix and open a pull request.

**Comment by Mr-Pingu** [comment]
Same problem here. Would like to know if there's a work-around in the mean time?
