### ISSUE TITLE
window 10, mounting failed with the error: No such device

### ISSUE THREAD

**Issue by jesse1993** [hashicorp/vagrant#9945]
### Vagrant version
Vagrant 2.0.2

### Host operating system
Microsoft Windows 10 family
10.0.17134 version 17134

### Guest operating system
bento/centos-7.4

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.4"
  config.vm.define "vt11"
end
```

### Debug output
https://gist.github.com/jesse1993/9e359e53803ebc70b87e3c073cdfaa97

### Expected behavior
vagrant up and no error

### Actual behavior
mounting failed with the error: No such device

### Steps to reproduce
1.vagrant up vt11
2.vagrant halt vt11
3.vagrant up vt11

OR

1.vagrant up vt11
2.vagrant reload vt11

### Describe
The error appeared in the second time of vagrant up, the first time was not wrong.
About half a year ago, I wrote a complex vagrant project, which works well. Then I'm busy with my work, I've been running this project again recently, and I didn't make any changes. And then the mistake appeared. Is this perhaps due to the automatic upgrade of window?

**Comment by jesse1993** [comment]
Vagrant is upgraded to the 2.1.1 version, and the error is not solved

**Comment by briancain** [comment]
@jesse1993 have you verified that virtualbox guest editions are installed on the vagrant box that you're using? The error message says that failing to mount a shared folder is usually due to not having virtualbox guest editions.

**Comment by jesse1993** [comment]
I have installed plugin vagrant-vbguest (0.15.2),  so the reason for the error may be that vagrant-vbguest not work?

The following is the version I used：
VirtualBox  5.2.12 r122591 (Qt5.6.2)
 vagrant-vbguest (0.15.2)
 Windows 10 family 10.0.17134 version 17134

**Comment by lechatthecat** [comment]
I am not sure this will work but can you try this?:
https://noteoneverything.blogspot.com/2017/07/when-you-run-vagrant-up-you-might-face.html

**Comment by jesse1993** [comment]
@lechatthecat yes, it's ok now, thanks for the help.
But this requires extra work and It is not convenient to use, looking forward to a better way

**Comment by briancain** [comment]
Hi @jesse1993 - what you are encountering is a problem with the Vagrant box you are using. You could look for a different box to use, but this is not a problem with Vagrant itself! I'm going to go ahead and close this issue. But if you are still stuck or you are looking for a better solution, I recommend emailing the Vagrant up mailing list. Thanks!
