### ISSUE TITLE
Getting Error while pushing "`push': stack level too deep (SystemStackError)"

### ISSUE THREAD

**Issue by Basha0** [hashicorp/vagrant#9946]
Hello so I am getting an error while trying to push my box to an ftp Server.
I am using Vagrant+Django with python3 and a postgresql Database and Vaprobash file.
Everything working fine and now I want to push it on a prod server with "vagrant push".
config.push.define "ftp" do |push|
    push.host = "xxxxxx.xxxxxx.com"
    push.username = "xxxxxxxxxxxx"
    push.password = "xxxxxxxxx"
    #push.destination = "/dev/raumbuchung"
  end

i ll post the whole vagrant file below.
If you guys need the Debug output just say so.

### Vagrant version
2.1.1

### Host operating system
Mac High Sierra 10.13.4

### Guest operating system
Ubuntu

### Vagrantfile
https://gist.github.com/Basha0/4db4918b024cd469445b1defa97da1ea

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Expected behavior
Vagrant push to ftp Server

### Actual behavior
getting this output
/opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/pushes/ftp/push.rb:20:in `push': stack level too deep (SystemStackError)
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:655:in `push'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/push/command.rb:28:in `execute'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/cli.rb:54:in `execute'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:275:in `cli'
	from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/bin/vagrant:156:in `<main>'

### Steps to reproduce
1.Set vagrantfile
2.Vagrant up
3.vagrant push

###Debug
https://gist.github.com/Basha0/ff5a8f6e4d4953c28311a245c082feb6

**Comment by chrisroberts** [comment]
@Basha0 Hi. I was able to reproduce this error when the configured directory for the FTP push contains too many files to be successfully processed. This is the origin of the error you encountered. You'll need to either reduce the number of files or update the `dir` configuration option for the ftp push to use a subdirectory.

I've also created a PR to prevent this error from surfacing and providing a customized error with context on the problem: #9952

Cheers!

**Comment by Basha0** [comment]
@chrisroberts  Yeah I also figured that out. I started excluding folder by folder and I found out that one folder couldn't be uploaded. But I didn't know that it was due the amount of data in that folder. So thats is a nice Info to have. I uploaded that folder Manually and it worked.
But still good to know why the folder wants uploaded by Vagrant.
