### ISSUE TITLE
The "metadata.json" file for the box 'scotch/box' was not found.

### ISSUE THREAD

**Issue by JayMaree** [hashicorp/vagrant#9951]
### Vagrant version
Vagrant 2.1.1

### Host operating system
MacOS High Sierra

### Guest operating system
scotch-box

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :
#Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
#Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
Vagrant.configure("2") do |config|

    config.vm.box = "scotch/box"
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.hostname = "scotchbox"
    config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]

    # Optional NFS. Make sure to remove other synced_folder line too
    #config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }

end
```

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
jaymaree@iws-lpt0097 ~/W/r/scotch-box> vagrant up
The "metadata.json" file for the box 'scotch/box' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:

https://www.vagrantup.com/docs/boxes/format.html

### Expected behavior
The box should start.

### Actual behavior
See debug for error

**Comment by briancain** [comment]
Hi there @JayMaree - if you try a previous version of the Vagrant box `"scotch/box"` do you still get that error?

The problem you're facing is not an issue with Vagrant, but something that would be handled by the maintainer of the box itself.

**Comment by JayMaree** [comment]
Hi @briancain, thanks for the reply. How can I add specific versions? The latest scotch/box version is 3.5, but I would like to try the 3.0 version.

Using the vagrant box add command gives me the same error:
`jaymaree@Jays-MacBook-Pro ~/W/r/scotch-box> vagrant box add scotch/box
==> box: Loading metadata for box 'scotch/box'
    box: URL: https://vagrantcloud.com/scotch/box
==> box: Adding box 'scotch/box' (v3.5) for provider: virtualbox
The "metadata.json" file for the box 'scotch/box' was not found.
Boxes require this file in order for Vagrant to determine the
provider it was made for. If you made the box, please add a
"metadata.json" file to it. If someone else made the box, please
notify the box creator that the box is corrupt. Documentation for
box file format can be found at the URL below:

https://www.vagrantup.com/docs/boxes/format.html`

**Comment by briancain** [comment]
Use the `--box-version` flag if you are adding it with the `box add` command

> --box-version VERSION        Constrain version of the added box

Otherwise, you can specify a version in your Vagrantfile with `config.vm.box_version`.

**Comment by JayMaree** [comment]
It has been fixed in the meanwhile. The box's had some corrupted files in the vagrant.d folder. Thanks anyway!
