### ISSUE TITLE
Pass variable to provisioner to help detect deploying to Vagrant host

### ISSUE THREAD

**Issue by jeffWelling** [hashicorp/vagrant#9954]
It would be helpful for writing Ansible playbooks (as one example) if Vagrant set a magic variable to help communicate to Ansible that the host is currently running in a Vagrant environment. This would allow you to have Ansible tasks which are only run against Vagrant hosts.

Eg
```
- name: Do the thing if Vagrant
  apt:
    state: latest
    name: vim
  when: vagrant is true
```

Current work-arounds include:
1) Use the shell provisioner in Vagrantfile to drop a /.vagrant file before the Ansible provisioner is run
2) Set the variable by hand in the Ansible playbook

I've checked if this is a duplicate issue but it doesn't seem to be. 
If there's a better way to accomplish this pls just let me know :)

### Vagrant version
Vagrant 1.8.1

### Host operating system
Ubuntu 16.04.4 LTS

### Guest operating system
CentOS Linux 7 (Core)

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.define "consul1" do |consul1|
    consul1.vm.box = "centos/7"
  end
end
```

Thanks!

**Comment by gildegoma** [comment]
Thank you @jeffWelling for asking, and filling the issue template so precisely 👍

From your Vagrantfile, I suppose that you're not using any of the [Vagrant Ansible](https://www.vagrantup.com/docs/provisioning/ansible_intro.html) provisioners. These two provisioners are the only components where Vagrant (without additional plugins) supports some Ansible integration capabilities. By using them, you can easily get your question resolved, as illustrated below. The simplest way is to rely on the [**extra_vars**](https://www.vagrantup.com/docs/provisioning/ansible_common.html#extra_vars) option (but you also can consider [group](https://www.vagrantup.com/docs/provisioning/ansible_common.html#groups) or [host](https://www.vagrantup.com/docs/provisioning/ansible_common.html#host_vars) variables).

Example:

```ruby
Vagrant.configure(2) do |config|
  config.vm.define "consul1" do |consul1|
    consul1.vm.box = "centos/7"
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "ansible/consul.yml"
    ansible.extra_vars = { vagrant: true }
  end
end
```

Then you simply have to run `vagrant up --provision` or `vagrant provision` (when the vm is already up).

**Comment by gildegoma** [comment]
I am closing this issue. If you have more question, please let's move the discussion to the [vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). Thank you 😃

**Comment by jeffWelling** [comment]
Thanks @gildegoma! I am indeed using the Vagrant Ansible provisioner, I just forgot to include that part in my Vagrantfile sample, my bad! This works perfectly though.

**Comment by tagirb** [comment]
@gildegoma Sorry, for posting into a closed issue, but it describes precisely the feature I'd like to have in Vagrant.

Some background for better understanding. In our team we use Ansible either directly or combined with Vagrant and Packer. Packer Ansible Provisioner provides passes by default some `extra_vars`, e.g., [packer_builder_type](https://www.packer.io/docs/provisioners/ansible.html#packer_builder_type), whereas Vagrant Ansible provisioner requires adding such a variable explicitly.

While this is an absolutely viable solution, it requires customizing every `Vagrantfile` accordingly. Why not let Vagrant Ansible Provisioner supply a default extra var, just like Packer Ansible Provisioner does this?
