### ISSUE TITLE
Vagrant 2.1.2 can't boot on Windows 10

### ISSUE THREAD

**Issue by edwin-egalite** [hashicorp/vagrant#9955]
### Vagrant version
2.1.2

### Host operating system
Windows 10 17134.137

### Guest operating system
bento Ubuntu 16.04

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
Vagrant should boot normally.

### Actual behavior
$ vagrant.exe up --provision
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- vagrant/share

### Steps to reproduce
1. vagrant.exe up --provision

**Comment by poon64** [comment]
I have the same problem with Windows 7 after installing version 2.1.2. 
The error message is exactly the same. 
When I try to install any plugin I get this message, 
```  
$ vagrant plugin install vagrant-share
FATAL: vagrant-reload plugin not detected. Please install the plugin with
       'vagrant plugin install vagrant-reload' before continuing. 
``` 
The same thing happens with any plugin that I try to install, or if I try to do plugin repair or --reinstall. 
I'm running this from the Git Bash console.

**Comment by tkaw220** [comment]
Sadly, nearly every new releases have issues on Windows platform.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this issue. There was a missing loader file in the Windows packages. The file has been added and fixed packages have been uploaded to the releases site.

Cheers!

**Comment by poon64** [comment]
Nice, I'll try it at work tomorrow 😀

Den ons 27 juni 2018 19:20Chris Roberts <notifications@github.com> skrev:

**Comment by angel-luis** [comment]
`vagrant plugin expunge --reinstall

This command permanently deletes all currently installed user plugins. It
should only be used when a repair command is unable to properly fix the
system.

Continue? [N]: y

All user installed plugins have been removed from this Vagrant environment!

Vagrant will now attempt to reinstall user plugins that were removed.
Installing the 'vagrant-share' plugin. This can take a few minutes...
Fetching: vagrant-share-1.1.9.gem (100%)
Installed the plugin 'vagrant-share (1.1.9)'!

C:\Users\Angel Luis>vagrant
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- vagrant/share`

So no, it's not fixed.

**Comment by angel-luis** [comment]
A provisional solution is to use ngrok as default. 

So, if you have a private newtork in 192.168.33.10:

`ngrok http 192.168.33.10:80`
