### ISSUE TITLE
Unexpected SMB prompt on Mac OS, Vagrant >=2.1.1

### ISSUE THREAD

**Issue by trey-stafford** [hashicorp/vagrant#9960]
### Vagrant version
Observed in vagrant versions 2.1.1 and 2.1.2. Versions before 2.1.1 do not have this issue.

### Host operating system
Problem is observed when running vagrant on Mac OS High Sierra. Note that this
problem does not occur on an Ubuntu 16.04 host.

### Guest operating system
Ubuntu 16.04

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.provision :shell do |s|
    s.name = 'apt-get update'
    s.inline = 'apt-get update'
  end
  config.vm.provision :shell do |s|
    s.name = 'librarian-puppet install'
    s.inline = 'cd /vagrant/puppet && librarian-puppet install --path=./modules'
  end
  config.vm.provision :puppet do |puppet|
    puppet.working_directory = '/vagrant'
    puppet.manifests_path = './puppet'
    puppet.manifest_file = 'site.pp'
    puppet.options = '--detailed-exitcodes --modulepath ./puppet/modules'
    puppet.hiera_config_path = './puppet/hiera.yaml'
  end
end
```

### Debug output
Selected debug output (excluding debug output from cloning of VM): https://gist.github.com/trey-stafford/5f09225f15fa5eb81b4e28be0c1bba23 

### Expected behavior
A machine without configuration for an SMB share is upped without SMB shares or prompts for username/password to connect to an SMB.

### Actual behavior
Vagrant prompts for SMB credentials on vagrant up, despite no configuration to do so.

### References
This issue from vagrant-aws appears to be related: 

https://github.com/mitchellh/vagrant-aws/issues/365

**Comment by chrisroberts** [comment]
Hi there,

Vagrant will attempt to sync folders based on the capabilities of the host and guest. In this case it seems that there are no guest tools available for mounting the default synced folder so Vagrant is detecting what's available and using it's best option (in this case it is SMB). SMB support was added for macOS in the 2.0.2 release which is why you may have not seen this previously (it was likely defaulting to rsync) but are now. You can disable the default synced folder using:

```ruby
config.vm.synced_folder '.', '/vagrant', disabled: true
```

or you can force it to use rsync:

```ruby
config.vm.synced_folder '.', '/vagrant', type: :rsync
```

Cheers!

**Comment by trey-stafford** [comment]
@chrisroberts I appreciate the feedback - I clearly should have looked more closely at the changelogs!

In either case, your proposed solution did not work. However, it should be noted that we were able to force the use of rsync with the following:
````            
config.vm.allowed_synced_folder_types = [:rsync]
```

**Comment by jessereynolds** [comment]
Thanks @trey-stafford ... it would be great to have your workaround added to the SMB file sync doc page under *how to disable smb*
