### ISSUE TITLE
rpmbuild vagrant failed

### ISSUE THREAD

**Issue by chunglam1999** [hashicorp/vagrant#9961]
root@lenovo-2 rpmbuild]# rpmbuild -ba SPECS/vagrant.spec
+ xargs chmod a+x
+ install -D -m 755 /root/rpmbuild/SOURCES/binstub /root/rpmbuild/BUILDROOT/vagrant-2.0.4-1.el7.x86_64/usr/bin/vagrant
+ sed -i 's|@vagrant_embedded_dir@|%{vagrant_embedded_dir}|' /root/rpmbuild/BUILDROOT/vagrant-2.0.4-1.el7.x86_64/usr/bin/vagrant
+ install -D -m 0644 '/root/rpmbuild/BUILDROOT/vagrant-2.0.4-1.el7.x86_64%{vagrant_plugin_instdir}/contrib/bash/completion.sh' /root/rpmbuild/BUILDROOT/vagrant-2.0.4-1.el7.x86_64/usr/share/bash-completion/completions/vagrant
install: cannot stat '/root/rpmbuild/BUILDROOT/vagrant-2.0.4-1.el7.x86_64%{vagrant_plugin_instdir}/contrib/bash/completion.sh': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.TXrXTn (%install)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.TXrXTn (%install)

Vagrant version
2.0.4-1

Host operating system
Centos 7

Guest operating system
N/A

Vagrantfile
# Copy-paste your Vagrantfile here (but don't include sensitive information such as passwords, authentication tokens, or email addresses)
N/A

Debug output
N/A

Expected behavior
I think the 'vagrant_plugin_instdir' is not defined in vagrant.spec

Actual behavior
N/A

Steps to reproduce
rpmbuild -ba SPECS/vagrant.spec
References
N/A

**Comment by chrisroberts** [comment]
Hi there,

I think you may have opened this issue on the wrong repository. This repository does not include a `SPECS/vagrant.spec` file.

Cheers!

**Comment by chunglam1999** [comment]
thx for reply. May I ask do you where can I find vagrant.spec to build rpm file of vagrant.

**Comment by chrisroberts** [comment]
@chunglam1999 Sorry, I do not know.
