### ISSUE TITLE
 parameter cannot be found that matches parameter name 'ExposeVirtualizationExtensions after upgrade from 2.1.1 to 2.1.2 

### ISSUE THREAD

**Issue by taldov** [hashicorp/vagrant#9962]
### Vagrant version
2.1.2

### Host operating system
Windows 2012 R2 

### Guest operating system
Windows 2016 Server 

### Vagrantfile
Vagrant.configure("2") do |config|
  config.vm.box = "delphi_01"
end

### Debug output
https://gist.github.com/taldov/317c8dac91ec681a95284cf68987d148

### Expected behavior
Turn on box 

### Actual behavior
Getting Error 

### Steps to reproduce
Run "Vagrant up" after updating from 2.1.1.

**Comment by taldov** [comment]
Any workaround?

**Comment by taldov** [comment]
I did add the 8 lines to vagrantVM.psm1 After this I'm getting this error 
A parameter cannot be found that matches parameter name 'CheckpointType'.

**Comment by hegyre** [comment]
Hello,
I have the same issue, and the workaournd adding the 8 lines lead to the same error:

Script: configure_vm.ps1
Error:

Failed to disable checkpoints on VM: A parameter cannot be found that matches parameter name 'CheckpointType'.
