### ISSUE TITLE
Issue with Vagrant up

### ISSUE THREAD

**Issue by mohapatrasiddhartha** [hashicorp/vagrant#9969]
I am facing issue with vagrant up suddenly .  The bellow error is coming . Please give me the solution for this issue .

Error :- 
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "172b0023-e8ec-4830-91ea-d8efbef61f53", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'vagrant_default_1530354501086_86698' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\bgh49601\VirtualBox VMs\vagrant_default_1530354501086_86698\Logs\VBoxHardening.log'

VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

 INFO interface: Machine: error-exit ["Vagrant::Errors::VBoxManageError", "There was an error while executing `VBoxManage`, a CLI used by Vagrant\nfor controlling VirtualBox. The command and stderr is shown below.\n\nCommand: [\"startvm\", \"172b0023-e8ec-4830-91ea-d8efbef61f53\", \"--type\", \"headless\"]\n\nStderr: VBoxManage.exe: error: The virtual machine 'vagrant_default_1530354501086_86698' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\\Users\\bgh49601\\VirtualBox VMs\\vagrant_default_1530354501086_86698\\Logs\\VBoxHardening.log'\r\nVBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine\r\n"] .

You can find the attached log file .

**Comment by chrisroberts** [comment]
@mohapatrasiddhartha Can you provide the log file?

**Comment by briancain** [comment]
Hi @mohapatrasiddhartha - if you upgrade from Vagrant `1.9.2` to the latest version, do you still encounter your issue?

**Comment by heyitsaakash** [comment]
Did we get to the cause I also got same issue

**Comment by mohapatrasiddhartha** [comment]
@briancain Still I am facing same issue .
@heyitsaakash As in my team some people are using Windows 8 and some people are using windows 10. We observe Vagrant issues coming frequently in windows 10 machine. I had re-imaged my machine to windows 8. Without encountering an error its working perfectly in windows 8.

**Comment by chrisroberts** [comment]
@mohapatrasiddhartha Hi there. The issue being encountered is originating from VirtualBox, not Vagrant. The log file specified in the error message:

> More details may be available in 'C:\Users\bgh49601\VirtualBox VMs\vagrant_default_1530354501086_86698\Logs\VBoxHardening.log'

will have more information on the underlying problem. If you provide that file I will be happy to have a look and see if I can identify the issue for you.

Cheers!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/hashicorp/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
