### ISSUE TITLE
Failed configuring network interfaces after packaging

### ISSUE THREAD

**Issue by petesiss** [hashicorp/vagrant#997]
Im using OSX 10.7.4 for running vagrant, and Centos6 vm boxes.

I set up a new VM from a fully working base box, and then package it as my own box having made very few (or even no) changes. 

When I then add the new .box file and and try to use it for a new vm it fails to set up the network interfaces correctly:

```
[default] Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifup eth1 2> /dev/null
```

It doesn't seem to matter which networking I choose in the Vagrantfile (host only / bridged) or whether I package it in the directory with the running vm or elsewhere using the --base [vm-name]. I always get the same result.

I have found I can solve this by: 
- manually going in to the vm and clearing everything apart from eth0 out of `/etc/udev/rules.d/70-persistent-net.rules`
- removing any `/etc/sysconfig/network-scripts/ifcfg-eth1` or similar files (except the one for eth0).

Once I do that then the machine reloads fine and all the interfaces come back up.

For my use case its not a huge issue as we're not doing this on a large scale, but it would be great to know whats going wrong. Could be something Im missing when packaging.

**Comment by jimmychu0807** [comment]
Just want to add I also encountered this issue after repackaging a CentOS 6.5 box. Removing `/etc/udev/rules.d/70-persistent-net.rules` and `/etc/sysconfig/network-scripts/ifcfg-eth1`, and then a `vagrant reload --provision` works for me.

**Comment by ageofzetta** [comment]
Same problem here. 
Ubuntu 14.04 on a Windows 8.1 host
Vagrant 1.7.4 on Virtualbox 4.3.28

The VM network got misconfigured after i added the public_network option on the Vagrantfile

To solve it i deleted the following file: ``` /etc/udev/rules.d/70-persistent-net.rules ``` 

Also i edited the file ``` /etc/network/interfaces ``` and removed  everything but **eth0 configuration**  (just delete everyithing between ``` #VAGRANT-BEGIN ``` and ``` #VAGRANT-END ``` )

*NOTE: I also  removed the public_network option*

**Comment by pporada-gl** [comment]
I packaged a Centos 7.1 virtualbox where I run the following and am still encountering issues starting up a vagrant.
```
rm -f /etc/udev/rules.d/70-persistent-net.rules;
rm -f /etc/sysconfig/network-scripts/ifcfg-eth1
ln -sf /dev/null /etc/udev/rules.d/70-persistent-net.rules
ln -sf /dev/null /lib/udev/rules.d/75-persistent-net-generator.rules

for ndev in `ls -1 /etc/sysconfig/network-scripts/ifcfg-*`; do
    if [ "`basename $ndev`" != "ifcfg-lo" ]; then
        sed -i '/^HWADDR/d' "$ndev";
        sed -i '/^UUID/d' "$ndev";
    fi
done
```

The output from the gui shows "work still pending". I can login but no IP address is every assigned. I have the following lines relevant to networking in my Vagrantfile.
```
config.vm.provider :virtualbox do |vb|
        vb.memory = 1024
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    config.vm.network "private_network", ip: "192.168.200.42"
```

I can run vagrant destroy -f and vagrant up till the cows come home and SOMETIMES I can get the vagrant to actually start successfully.
