### ISSUE TITLE
'Preparing to edit /etc/exports' fails: No such file or directory @ rb_file_s_stat - /etc/exports

### ISSUE THREAD

**Issue by matthewhegarty** [hashicorp/vagrant#9970]
### Vagrant version
Vagrant 2.1.2

### Host operating system
Linux Mint 17 Qiana 64-bit

### Guest operating system
Debian 8 (Jessie)

### Vagrantfile
[link](https://github.com/Asana/vagrant-php7/blob/master/Vagrantfile)

### Debug output
https://gist.github.com/matthewhegarty/5ab5200e860891f4260a4468f85dad5d

### Expected behavior
Vagrant should have started successfully (have reproduced this with other instances)
- https://github.com/spiritix/vagrant-php7

### Actual behavior
Consistently fails at this step:

```
Preparing to edit /etc/exports. Administrator privileges will be required...
```
with 

```
/opt/vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/plugins/hosts/linux/cap/nfs.rb:187:in `stat': No such file or directory @ rb_file_s_stat - /etc/exports (Errno::ENOENT)
```

Note that the VM  is started ok, but the provisioning doesn't complete.

### Steps to reproduce
1. `git clone git@github.com:Asana/vagrant-php7.git`
2. ` cd vagrant-php7`
3. `vagrant up`

### Workaround

For me, using [this image](https://github.com/sapienza/vagrant-php-box) worked ok

**Comment by hstock** [comment]
same problem here with debian/contrib-stretch64

**Comment by matthewhegarty** [comment]
Also occurs with `CentOS-65-x64`

**Comment by matthewhegarty** [comment]
Looks like this is an issue with a missing dependency on the host rather than the guest.  I was able to fix with:

```
sudo apt-get install nfs-kernel-server
```

Looks like nfs is a [required dependency](https://www.vagrantup.com/docs/synced-folders/nfs.html)

**Comment by briancain** [comment]
Yes, that's right @matthewhegarty - the fix here on our end will be catching this instead of showing an error. Then we can give a proper error message to let users know that they're missing nfs.

**Comment by ycjo** [comment]
@matthewhegarty thank you!!!!!!!!!

**Comment by briancain** [comment]
Hey there @matthewhegarty - It looks like this has been fixed since the issue was first reported. With version 2.2.4 I just tried bringing up a guest on a linux host without nfs installed. Got a proper vagrant error rather than a stack trace complaining about `/etc/exports` not existing. Going to go ahead and close this then. Thanks!
