### ISSUE TITLE
Exec error: fork/exec /usr/bin/ruby: argument list too long

### ISSUE THREAD

**Issue by karmux** [hashicorp/vagrant#9972]
### Vagrant version
Vagrant 2.1.2

### Host operating system
Manjaro Linux 17.1.11

### Guest operating system
any

### Vagrantfile
https://github.com/coreos/coreos-vagrant/blob/master/Vagrantfile

### Debug output
Installing plugins: vagrant-ignition
...
Installing plugins: vagrant-ignition
Exec error: fork/exec /usr/bin/ruby: argument list too long
Installation of one or more plugins has failed. Aborting.
...
Installation of one or more plugins has failed. Aborting.

### Expected behavior
`vagrant up` installs plugin and completes.

### Actual behavior
Above error happens when setting up any Vagrant project that requires some plugins.

### Steps to reproduce
Follow steps from here:
https://github.com/coreos/coreos-vagrant

### Workaround
https://github.com/hashicorp/vagrant/issues/8055#issuecomment-264201024

**Comment by websitesca** [comment]
I confirm the above issue as well running Vagrant 2.1.2 on mac osx 10.13.2. the workaround from @zymzxq solved the problem for me

**Comment by adolfoabegg** [comment]
Thank you @zymzxq 👍

**Comment by jifbrodeur** [comment]
I can confirm that the error does not happen on 2.1.1 I downgraded vagrant and the error message: fork/exec /opt/vagrant/embedded/bin/ruby: argument list too long no longer occure.
Thanks

**Comment by promethe42** [comment]
I can confirm that the error does not happen with the exact same `Vagrantfile` after downgrading to 2.1.1.

**Comment by chrisroberts** [comment]
Closing this up as these issues were fixed in 2.1.5

Cheers!
