### ISSUE TITLE
Shared folders fail to mount after installing MSYS2 in a Windows guest

### ISSUE THREAD

**Issue by wbowling** [hashicorp/vagrant#9975]
### Vagrant version
Vagrant 2.1.1

### Host operating system
macOS High Sierra - 10.13.5

### Guest operating system
Windows Server 2016

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |virtualbox, override|
    virtualbox.gui = true
    config.vm.box = "mwrock/Windows2016"
    config.vm.guest = :windows
    config.vm.communicator = "winrm"
    config.vm.synced_folder ".", "/mount_here"
  end
end
```

### Debug output
```
Cannot run a document in the middle of a pipeline: C:\msys64\usr\bin\cmd.
At line:43 char:1
+ cmd /c mklink /D "$MountPoint" "$VmProviderUncPath" | out-null
```

https://gist.github.com/wbowling/b746abae5735abbb345032df32768b55

### Expected behavior
`vagrant up` should complete and mount the shared folders

### Actual behavior
`C:\msys64\usr\bin\cmd` is run instead of `cmd.exe` and fails to mount the shared folders

### Steps to reproduce
1. `vagrant up`
1. Install https://www.msys2.org/ in guest
1. `vagrant halt`
1. `vagrant up`

**Comment by kasper93** [comment]
MSYS2 should never overwrite Windows binaries. You should fix PATH order in the system and if it MSYS installer does add path with wrong order it should be reported to them. 

If you start msys shell then it is fine to have their binaries take precedence (it automatically fixes the PATH) in any other scenario it will just break software/scripts. There are few conflicts like mentioned `cmd`, `find` etc. 

You cannot expect software to be aware that you replaced well-known binaries with something else.

**Comment by wbowling** [comment]
@kasper93 All good points, I agree this is more of a MSYS2 issue that vagrant.

> You should fix PATH order in the system and if it MSYS installer does add path with wrong order it should be reported to them

👍 I'll double check that and open an issue with them if it's the case.

The proposed PR only brings the powershell script inline with https://github.com/hashicorp/vagrant/blob/master/lib/vagrant/util/platform.rb#L527, making the call to `cmd.exe` more explicit without relying on `PATHEXT`. It should have no other side effects but will catch this case too.
