### ISSUE TITLE
add automatic dependency resolution

### ISSUE THREAD

**Issue by TheTesla** [hashicorp/vagrant#9979]
eg:

```
$ vagrant up --provider=lxc
Bringing machine 'default' up with 'lxc' provider...
==> default: Checking if box 'hrishikeshdate/xenial64' is up to date...
==> default: Setting up mount entries for shared folders...
    default: /vagrant => /home/stefan/ansible-seafiles
`redir` is not installed or is not accessible on the PATH.
```

it should automatically install redir - maybe locally if no permission escalation is provided.

**Comment by chrisroberts** [comment]
Hi there. The lxc provider is not a builtin Vagrant provider. This issue should be submitted to the vagrant-lxc project here: https://github.com/fgrehm/vagrant-lxc

Cheers!
