### ISSUE TITLE
redir not closed

### ISSUE THREAD

**Issue by TheTesla** [hashicorp/vagrant#9980]
### Vagrant version
Vagrant 2.1.2

### Host operating system
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
4.13.0-45-generic

### Guest operating system
rvanlaar/bionic64-lxc

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "rvanlaar/bionic64-lxc"
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y python
  SHELL
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "deploy.yml"
  end
end
```

### Expected behavior
redir is closed after vagrant destroy or vagrant halt
It should also be closed if there is a bug in vagrant-lxc because redir is an indirect "child" of the running container. 

### Actual behavior
redir process persists

### Steps to reproduce
1. vagrant up --provider-lxc
2. vagrant halt
3. vagrant destroy
4. sudo netstat -apn | grep redir

### References
https://github.com/fgrehm/vagrant-lxc/issues/59

**Comment by chrisroberts** [comment]
Hi there. This is an issue for the vagrant-lxc plugin which can be located here: https://github.com/fgrehm/vagrant-lxc

Cheers!
