### ISSUE TITLE
Host-only adapter stays in 'configuring' state in guest

### ISSUE THREAD

**Issue by jeffery-cavallaro-cavcom** [hashicorp/vagrant#9981]
### Vagrant version
Vagrant 2.1.2

### Host operating system
Ubuntu bionic beaver and MacOS Sierra

### Guest operating system
Ubuntu bionic beaver

### Vagrantfile
```ruby
Vagrant.configure('2') do |config|
  HOSTNAME = 'bionic64'

  config.vm.box = 'ubuntu/bionic64'
  config.vm.box_check_update = true
  config.vm.hostname = HOSTNAME

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :private_network, type: :dhcp

  config.vm.synced_folder '/home/jeffery', '/home/jeffery'

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.name = HOSTNAME
    vb.memory = '4096'
    vb.cpus = 1
  end

  config.vm.provision :shell, run: 'always', inline: <<-SHELL
    systemctl start systemd-timesyncd.service
  SHELL

  config.vm.provision :shell, inline: <<-SHELL
    apt-get update
    apt-get -y dist-upgrade
  SHELL

  config.vm.provision :shell, path: './scripts/apache.sh'
end
```
### Debug output
vagrant@bionic64:~$ networkctl
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 enp0s3           ether              routable    configured
  3 enp0s8           ether              routable    configuring

3 links listed.

### Expected behavior
systemd-networkd-wait-online.service should see the host-only network (enp0s8 - vboxnet0) up (configured) and the guest boot process should continue normally.

### Actual behavior
systemd-networkd-wait-online.service times out after the default 2 minutes because the the host-only adapter stays in the 'configuring' stage permanently.  The boot process then continues normally.  Note that this only happens on a reload or halt/up sequence; the initial provisioning is successful.

### Steps to reproduce
1. vagrant up
2. vagrant reload or vagrant halt then vagrant up
3.

**Comment by briancain** [comment]
Hi @jeffery-cavallaro-cavcom - after doing some investigation, it seems like the error here might be with systemd-networkd. Vagrant is laying down a `netplan` config file, which then gets translated over to a networkd config file. There's a bit more investigation on our end to see if there's anything we can do to fix it for us, but for now you should be able to set a static IP for a private network rather than relying on DHCP.

**Comment by briancain** [comment]
Hey all - So this seems to have been finally resolved upstream. I'm going to go ahead and close this, but if you encounter an issue please feel free to open a new one or comment on here, thanks!
