### ISSUE TITLE
Windows Vagrant on non english OS / hyperv provider

### ISSUE THREAD

**Issue by couchgott** [hashicorp/vagrant#9986]
### Vagrant version
2.1.2

### Host operating system
Windows 10 (1803), german language (in my case)

### Debug output
```
vagrant up
Bringing machine 'default' up with 'hyperv' provider...
==> default: Verifying Hyper-V is enabled...
==> default: Verifying Hyper-V is accessible...
Hyper-V access check has failed for the configured destination. This
is usually caused by running on a non-system drive which is missing
required permissions. Running the following command may resolve the
problem:

  icacls.exe d:\XXXX /T /Q /grant "NT AUTHORITY\SYSTEM:(IO)(CI)(F)"
```

### Expected behavior
Vagrant Starts the machine.

### Actual behavior
Error as above

### debugging:

the vagrantVM.psm1 (on PATH\TO\VAGRANT\embedded\gems\2.1.2\gems\vagrant-2.1.2\plugins\providers\hyperv\scripts\utils\VagrantVM\VagrantVM.psm1 )does have on line 712:
```
$systemACL = $acl.Access | where {$_.IdentityReference -eq "NT AUTHORITY\SYSTEM" -and $_.FileSystemRights -eq "FullControl" -and $_.AccessControlType -eq "Allow" -and $_.IsInherited -eq $true}
```
on a german windows this user is called:

NT-AUTORITÄT\SYSTEM

#### work-around:

for the moment i changed that line into:
```
$systemACL = $acl.Access | where {$_.IdentityReference -like "*SYSTEM" -and $_.FileSystemRights -eq "FullControl" -and $_.AccessControlType -eq "Allow" -and $_.IsInherited -eq $true}
```
which is working for me. 

also this part: 
```
-and $_.IsInherited -eq $true
```
seems to be a bit overdone for me. it basically would not matter if the permissions are inherited or not as long as the permissions are set correctly. 

################

it might be better to extract the SID and translate to the Username like:

```
    $BuiltinUsersSID = New-Object System.Security.Principal.SecurityIdentifier 'S-1-5-18'
    $BuiltinUsersGroup = $BuiltinUsersSID.Translate([System.Security.Principal.NTAccount])
    $acl = Get-ACL -Path D:\AP0990
    $systemACL = $acl.Access | where {$_.IdentityReference -eq $BuiltinUsersGroup.Value -and $_.FileSystemRights -eq "FullControl" -and $_.AccessControlType -eq "Allow" -and $_.IsInherited -eq $true}
    if($systemACL) {
        return $true
    }
```
but i cannot get that variable expanded. My Powershell knowledge is a bit limited. so not sure how to get this snippet wo work as expected. 

### Steps to reproduce
1. Install Vagrant on German (i guess other languages as well) Windows
2.  use the hyperv provider
3. try to up a machine

**Comment by kasper93** [comment]
Already reported here https://github.com/hashicorp/vagrant/issues/9973

**Comment by couchgott** [comment]
oha, 
sorry i've overseen that.

**Comment by lostiniceland** [comment]
Thanks for the work-around. Works until a fix is supplied

**Comment by hirsche** [comment]
Had the same problem - the intermediate fix also works for me.

**Comment by sdaaish** [comment]
Same problem, this solution works perfectly. Thanks!
