### ISSUE TITLE
SSH error in Cbench installation over vagrant Fedora box

### ISSUE THREAD

**Issue by federer422** [hashicorp/vagrant#9990]
### Vagrant version
Vagrant 1.8.1

### Host operating system
Linux UBuntu 16.0.4

### Guest operating system
Fedora 

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

# The WCBench README describes how to use Vagrant for WCBench work
# See: https://github.com/dfarrell07/wcbench#user-content-detailed-walkthrough-vagrant

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Build Vagrant box based on Fedora 20
    config.vm.box = "bento/fedora-26"

    # Configure VM RAM and CPU
    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 4
    end

    # This allows sudo commands in wcbench.sh to work
    config.ssh.pty = true

    # Unexpectedly, /usr/local/bin isn't in the default path
    # The cbench and oflops binary install there, need to add it
    config.vm.provision "shell", inline: "echo export PATH=$PATH:/usr/local/bin >> /home/vagrant/.bashrc"
    config.vm.provision "shell", inline: "echo export PATH=$PATH:/usr/local/bin >> /root/.bashrc"

    # Drop code in /home/vagrant/wcbench, not /vagrant
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder ".", "/home/vagrant/wcbench"

    # Install OpenDaylight and CBench with verbose output
    config.vm.provision "shell", inline: 'su -c "/home/vagrant/wcbench/wcbench.sh -vci" vagrant'
end
```

### Debug output
https://gist.github.com/federer422/66d3693b86e861adbc0bc6dda6906954

### Expected behavior
What should have happened?
**After "vagrant up"  and `provision`, It should have install cbench  properly.** 

### Actual behavior

What actually happened?

**Cbench installation fails. Part it fails :** 

==> default: Building CBench
==> default: checking for a BSD-compatible install... /bin/install -c
==> default: checking whether build environment is sane... yes
==> default: checking for a thread-safe mkdir -p... /bin/mkdir -p
==> default: checking for gawk... gawk
==> default: checking whether make sets $(MAKE)... yes
==> default: checking whether make supports nested variables... yes
==> default: checking for /home/vagrant/openflow/include/openflow/openflow.h... no
==> default: configure: error: Could not find openflow source at /home/vagrant/openflow -- please install
==> default: 		
==> default: make: *** No targets specified and no makefile found.  Stop.
==> default: make: *** No rule to make target 'install'.  Stop.
==> default: CBench is not installed
==> default: Failed to install CBench

**And as an error at last** >>> The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed.

**First issue after `vagrant provision` is :** 

==> default: Cloning openflow source code into /home/vagrant/openflow
==> default: Cloning into '/home/vagrant/openflow'...
==> default: fatal: read error: Connection reset by peer

**Clearly, theres a problem with SSH but after it crashes, I can build a SSH connection between host and Fedora by myself :** 

ray@ubuntu:~/wcbench-master$ vagrant ssh
/usr/bin/vagrant:57: warning: Insecure world writable dir /home/ray in PATH, mode 040757
/usr/lib/ruby/vendor_ruby/vagrant/pre-rubygems.rb:33: warning: Insecure world writable dir /home/ray in PATH, mode 040757
/usr/lib/ruby/vendor_ruby/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /home/ray in PATH, mode 040757
Last login: Thu Jul  5 11:48:24 2018
[vagrant@localhost ~]$ ^

**It looks like a cbench issue more that vagrant, but I thought SSH could be the main reason.**

**Here is the vagran ssh config response** 

Host default
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile "/home/ray/wcbench-master/.vagrant/machines/default/virtualbox/private_key"
  IdentitiesOnly yes
  LogLevel FATAL

**Related topics** : https://github.com/dfarrell07/wcbench
                         https://github.com/dfarrell07/vagrant-opendaylight

**Comment by chrisroberts** [comment]
Hi there,

This is an issue with the provisioner script that is being invoked by Vagrant and not an error that is being generated by Vagrant. You'll need to debug the script being used to provision the guest to resolve the error.

Cheers!
