### ISSUE TITLE
[Feature request] [Enhancement] Check `/etc/exports` before prompting for sudo password on vagrant up (when using NFS mounts)

### ISSUE THREAD

**Issue by kapad** [hashicorp/vagrant#9991]
When using nfs mounts, vagrant prompts for my sudo password every time Vagrant up is run. I know there's the option of adding aliases and editing my sudoer's file to allow vagrant to create nfs mounts without prompting for my password, but I think there's also the simpler option of checking to see if the required lines for running vagrant up and creating the nfs mounts are already present in /etc/exports. 

That way, the password will only be required when any changes need to be made to the `/etc/exports` file and not on every vagrant up. 

PS: I checked the `/etc/exports` file after running `vagrant halt` and the lines are persisted across vm reboots. The only time the lines added by vagrant are removed is when the VM is destroyed. (AFAIK)

**Comment by soapy1** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
