### ISSUE TITLE
Networking fail - cant assign a specific IP

### ISSUE THREAD

**Issue by brainst0rm** [hashicorp/vagrant#9994]
Please note that the Vagrant issue tracker is in priority reserved for bug reports and enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

**Tip:** Before submitting your issue, don't hesitate to remove the above introductory text, possible empty sections (e.g. References), and this tip.

### Vagrant version
1.8.1

### Host operating system
Ubuntu 16.04

### Guest operating system
bento/ubuntu-16.04 / ubuntu/xenial64

### Vagrantfile

```ruby
-*- mode: ruby -*-
vi: set ft=ruby :
Vagrant.configure("2") do |config|
   config.vm.box = "bento/ubuntu-16.04"
   config.vm.network "private_network", ip: "192.168.33.10"
   config.vm.network "public_network"
end
```

**Expected behavior**
Create a VM with the mentioned IP.

### Actual behavior

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown eth1 2> /dev/null

Stdout from the command:



Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
```

### Steps to reproduce
Works on one machine but doesn't on another one. The same Vagrant file. It does setup the VM, however does not assign the IP to it.

**Comment by briancain** [comment]
Hi @brainst0rm - please upgrade your version of Vagrant and try again. Thanks!

**Comment by brainst0rm** [comment]
@briancain  , you're right. Upgrading to latest Vagrant does fix the issue as I noted down [HERE](https://www.npsoni.com/2018/07/06/vagrant-private-ip-error-mesg-ttyname-failed-inappropriate-ioctl-for-device/). However, any clues on why that would happen? I guess I am just curious to understand the issue under the hood.

**Comment by briancain** [comment]
@brainst0rm - hard to say without seeing a debug log, but my guess is that old version of Vagrants implementation of how it sets up networking on debian is stale and no longer works with a newer Ubuntu release like 16.04.

**Comment by briancain** [comment]
Since it's fixed with the latest version of Vagrant I'm going to go ahead and close this issue. If you have more questions however you are free to send a message to the vagrant up mailing list. Thank you!
